### ISSUE TITLE
MOC - March of the Machine Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#10019]
This checklist is here to help manage the implementation of March of the Machine Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Goro-Goro and Satoru](https://scryfall.com/search?q=!gorogoroandsatoru)
- [ ] In progress -- [Katilda and Lier](https://scryfall.com/search?q=!katildaandlier)
- [ ] In progress -- [Slimefoot and Squee](https://scryfall.com/search?q=!slimefootandsquee)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"GoroGoroAndSatoru"or!"KatildaAndLier"or!"SlimefootAndSquee"&unique=cards)
# Implemented Cards

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by zelane** [comment]
[PR](https://github.com/magefree/mage/pull/10255) for [Moira and Teshar](https://scryfall.com/search?q=!moiraandteshar)

**Comment by theelk801** [comment]
@JayDi85 would you be able to do Ichor Elixir? I'm not sure how the die rolling code works anymore
