### ISSUE TITLE
MOM - March of the Machine Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#10018]
This checklist is here to help manage the implementation of March of the Machine. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Aerial Boost](https://scryfall.com/search?q=!aerialboost)
- [x] Done -- [Aetherblade Agent](https://scryfall.com/search?q=!aetherbladeagent)
- [x] Done -- [Akki Scrapchomper](https://scryfall.com/search?q=!akkiscrapchomper)
- [x] Done -- [Alabaster Host Intercessor](https://scryfall.com/search?q=!alabasterhostintercessor)
- [x] Done -- [Alabaster Host Sanctifier](https://scryfall.com/search?q=!alabasterhostsanctifier)
- [x] Done -- [Ancient Imperiosaur](https://scryfall.com/search?q=!ancientimperiosaur)
- [x] Done -- [Angelic Intervention](https://scryfall.com/search?q=!angelicintervention)
- [x] Done -- [Arachnoid Adaptation](https://scryfall.com/search?q=!arachnoidadaptation)
- [x] Done -- [Archangel Elspeth](https://scryfall.com/search?q=!archangelelspeth)
- [x] Done -- [Archpriest of Shadows](https://scryfall.com/search?q=!archpriestofshadows)
- [x] Done -- [Artistic Refusal](https://scryfall.com/search?q=!artisticrefusal)
- [x] Done -- [Assimilate Essence](https://scryfall.com/search?q=!assimilateessence)
- [x] Done -- [Astral Wingspan](https://scryfall.com/search?q=!astralwingspan)
- [x] Done -- [Atraxa's Fall](https://scryfall.com/search?q=!atraxasfall)
- [x] Done -- [Attentive Skywarden](https://scryfall.com/search?q=!attentiveskywarden)
- [x] Done -- [Axgard Artisan](https://scryfall.com/search?q=!axgardartisan)
- [x] Done -- [Ayara, Widow of the Realm](https://scryfall.com/search?q=!ayarawidowoftherealm)
- [x] Done -- [Baral and Kari Zev](https://scryfall.com/search?q=!baralandkarizev)
- [x] Done -- [Beamtown Beatstick](https://scryfall.com/search?q=!beamtownbeatstick)
- [x] Done -- [Bladed Battle-Fan](https://scryfall.com/search?q=!bladedbattlefan)
- [x] Done -- [Blighted Burgeoning](https://scryfall.com/search?q=!blightedburgeoning)
- [x] Done -- [Blightreaper Thallid](https://scryfall.com/search?q=!blightreaperthallid)
- [x] Done -- [Bloated Processor](https://scryfall.com/search?q=!bloatedprocessor)
- [x] Done -- [Bloodfeather Phoenix](https://scryfall.com/search?q=!bloodfeatherphoenix)
- [x] Done -- [Bloodfell Caves](https://scryfall.com/search?q=!bloodfellcaves)
- [x] Done -- [Blossoming Sands](https://scryfall.com/search?q=!blossomingsands)
- [x] Done -- [Bola Slinger](https://scryfall.com/search?q=!bolaslinger)
- [x] Done -- [Bonded Herdbeast](https://scryfall.com/search?q=!bondedherdbeast)
- [x] Done -- [Boon-Bringer Valkyrie](https://scryfall.com/search?q=!boonbringervalkyrie)
- [x] Done -- [Borborygmos and Fblthp](https://scryfall.com/search?q=!borborygmosandfblthp)
- [x] Done -- [Botanical Brawler](https://scryfall.com/search?q=!botanicalbrawler)
- [x] Done -- [Breach the Multiverse](https://scryfall.com/search?q=!breachthemultiverse)
- [x] Done -- [Burning Sun's Fury](https://scryfall.com/search?q=!burningsunsfury)
- [x] Done -- [Captive Weird](https://scryfall.com/search?q=!captiveweird)
- [x] Done -- [Chandra, Hope's Beacon](https://scryfall.com/search?q=!chandrahopesbeacon)
- [x] Done -- [Change the Equation](https://scryfall.com/search?q=!changetheequation)
- [x] Done -- [Chomping Kavu](https://scryfall.com/search?q=!chompingkavu)
- [x] Done -- [Chrome Host Seedshark](https://scryfall.com/search?q=!chromehostseedshark)
- [x] Done -- [City on Fire](https://scryfall.com/search?q=!cityonfire)
- [x] Done -- [Collective Nightmare](https://scryfall.com/search?q=!collectivenightmare)
- [x] Done -- [Coming In Hot](https://scryfall.com/search?q=!cominginhot)
- [x] Done -- [Compleated Huntmaster](https://scryfall.com/search?q=!compleatedhuntmaster)
- [x] Done -- [Complete the Circuit](https://scryfall.com/search?q=!completethecircuit)
- [x] Done -- [Consuming Aetherborn](https://scryfall.com/search?q=!consumingaetherborn)
- [x] Done -- [Converter Beast](https://scryfall.com/search?q=!converterbeast)
- [x] Done -- [Copper Host Crusher](https://scryfall.com/search?q=!copperhostcrusher)
- [x] Done -- [Corrupted Conviction](https://scryfall.com/search?q=!corruptedconviction)
- [x] Done -- [Corruption of Towashi](https://scryfall.com/search?q=!corruptionoftowashi)
- [x] Done -- [Cosmic Hunger](https://scryfall.com/search?q=!cosmichunger)
- [x] Done -- [Cragsmasher Yeti](https://scryfall.com/search?q=!cragsmasheryeti)
- [x] Done -- [Crystal Carapace](https://scryfall.com/search?q=!crystalcarapace)
- [x] Done -- [Cut Short](https://scryfall.com/search?q=!cutshort)
- [x] Done -- [Deadly Derision](https://scryfall.com/search?q=!deadlyderision)
- [x] Done -- [Deeproot Wayfinder](https://scryfall.com/search?q=!deeprootwayfinder)
- [x] Done -- [Dismal Backwater](https://scryfall.com/search?q=!dismalbackwater)
- [x] Done -- [Disturbing Conversion](https://scryfall.com/search?q=!disturbingconversion)
- [x] Done -- [Djeru and Hazoret](https://scryfall.com/search?q=!djeruandhazoret)
- [x] Done -- [Doomskar Warrior](https://scryfall.com/search?q=!doomskarwarrior)
- [x] Done -- [Drana and Linvala](https://scryfall.com/search?q=!dranaandlinvala)
- [x] Done -- [Dreg Recycler](https://scryfall.com/search?q=!dregrecycler)
- [x] Done -- [Dusk Legion Duelist](https://scryfall.com/search?q=!dusklegionduelist)
- [x] Done -- [Elesh Norn](https://scryfall.com/search?q=!eleshnorn)
- [x] Done -- [Elspeth's Smite](https://scryfall.com/search?q=!elspethssmite)
- [x] Done -- [Elvish Vatkeeper](https://scryfall.com/search?q=!elvishvatkeeper)
- [x] Done -- [Enduring Bondwarden](https://scryfall.com/search?q=!enduringbondwarden)
- [x] Done -- [Ephara's Dispersal](https://scryfall.com/search?q=!epharasdispersal)
- [x] Done -- [Errant and Giada](https://scryfall.com/search?q=!errantandgiada)
- [x] Done -- [Essence of Orthodoxy](https://scryfall.com/search?q=!essenceoforthodoxy)
- [x] Done -- [Etali, Primal Conqueror](https://scryfall.com/search?q=!etaliprimalconqueror)
- [x] Done -- [Etched Familiar](https://scryfall.com/search?q=!etchedfamiliar)
- [x] Done -- [Etched Host Doombringer](https://scryfall.com/search?q=!etchedhostdoombringer)
- [x] Done -- [Expedition Lookout](https://scryfall.com/search?q=!expeditionlookout)
- [x] Done -- [Eyes of Gitaxias](https://scryfall.com/search?q=!eyesofgitaxias)
- [x] Done -- [Faerie Mastermind](https://scryfall.com/search?q=!faeriemastermind)
- [x] Done -- [Failed Conversion](https://scryfall.com/search?q=!failedconversion)
- [x] Done -- [Fairgrounds Trumpeter](https://scryfall.com/search?q=!fairgroundstrumpeter)
- [x] Done -- [Fearless Skald](https://scryfall.com/search?q=!fearlessskald)
- [x] Done -- [Fertilid's Favor](https://scryfall.com/search?q=!fertilidsfavor)
- [x] Done -- [Final Flourish](https://scryfall.com/search?q=!finalflourish)
- [x] Done -- [Flitting Guerrilla](https://scryfall.com/search?q=!flittingguerrilla)
- [x] Done -- [Flywheel Racer](https://scryfall.com/search?q=!flywheelracer)
- [x] Done -- [Furnace Gremlin](https://scryfall.com/search?q=!furnacegremlin)
- [x] Done -- [Furnace Host Charger](https://scryfall.com/search?q=!furnacehostcharger)
- [x] Done -- [Furnace Reins](https://scryfall.com/search?q=!furnacereins)
- [x] Done -- [Furtive Analyst](https://scryfall.com/search?q=!furtiveanalyst)
- [x] Done -- [Ghalta and Mavren](https://scryfall.com/search?q=!ghaltaandmavren)
- [x] Done -- [Gift of Compleation](https://scryfall.com/search?q=!giftofcompleation)
- [x] Done -- [Glissa, Herald of Predation](https://scryfall.com/search?q=!glissaheraldofpredation)
- [x] Done -- [Glistening Dawn](https://scryfall.com/search?q=!glisteningdawn)
- [x] Done -- [Glistening Deluge](https://scryfall.com/search?q=!glisteningdeluge)
- [x] Done -- [Gloomfang Mauler](https://scryfall.com/search?q=!gloomfangmauler)
- [x] Done -- [Gnottvold Hermit](https://scryfall.com/search?q=!gnottvoldhermit)
- [x] Done -- [Golden-Scale Aeronaut](https://scryfall.com/search?q=!goldenscaleaeronaut)
- [x] Done -- [Grafted Butcher](https://scryfall.com/search?q=!graftedbutcher)
- [x] Done -- [Guardian of Ghirapur](https://scryfall.com/search?q=!guardianofghirapur)
- [x] Done -- [Halo Forager](https://scryfall.com/search?q=!haloforager)
- [x] Done -- [Halo Hopper](https://scryfall.com/search?q=!halohopper)
- [x] Done -- [Halo-Charged Skaab](https://scryfall.com/search?q=!halochargedskaab)
- [x] Done -- [Hangar Scrounger](https://scryfall.com/search?q=!hangarscrounger)
- [x] Done -- [Harried Artisan](https://scryfall.com/search?q=!harriedartisan)
- [x] Done -- [Heliod, the Radiant Dawn](https://scryfall.com/search?q=!heliodtheradiantdawn)
- [x] Done -- [Herbology Instructor](https://scryfall.com/search?q=!herbologyinstructor)
- [x] Done -- [Hidetsugu and Kairi](https://scryfall.com/search?q=!hidetsuguandkairi)
- [x] Done -- [Hoarding Broodlord](https://scryfall.com/search?q=!hoardingbroodlord)
- [x] Done -- [Ichor Drinker](https://scryfall.com/search?q=!ichordrinker)
- [x] Done -- [Ichor Shade](https://scryfall.com/search?q=!ichorshade)
- [x] Done -- [Infected Defector](https://scryfall.com/search?q=!infecteddefector)
- [x] Done -- [Inga and Esika](https://scryfall.com/search?q=!ingaandesika)
- [x] Done -- [Injector Crocodile](https://scryfall.com/search?q=!injectorcrocodile)
- [x] Done -- [Inspired Charge](https://scryfall.com/search?q=!inspiredcharge)
- [x] Done -- [Interdisciplinary Mascot](https://scryfall.com/search?q=!interdisciplinarymascot)
- [x] Done -- [Into the Fire](https://scryfall.com/search?q=!intothefire)
- [x] Done -- [Invasion of Alara](https://scryfall.com/search?q=!invasionofalara)
- [x] Done -- [Invasion of Amonkhet](https://scryfall.com/search?q=!invasionofamonkhet)
- [x] Done -- [Invasion of Arcavios](https://scryfall.com/search?q=!invasionofarcavios)
- [x] Done -- [Invasion of Azgol](https://scryfall.com/search?q=!invasionofazgol)
- [x] Done -- [Invasion of Belenon](https://scryfall.com/search?q=!invasionofbelenon)
- [x] Done -- [Invasion of Dominaria](https://scryfall.com/search?q=!invasionofdominaria)
- [x] Done -- [Invasion of Eldraine](https://scryfall.com/search?q=!invasionofeldraine)
- [x] Done -- [Invasion of Ergamon](https://scryfall.com/search?q=!invasionofergamon)
- [x] Done -- [Invasion of Fiora](https://scryfall.com/search?q=!invasionoffiora)
- [x] Done -- [Invasion of Gobakhan](https://scryfall.com/search?q=!invasionofgobakhan)
- [x] Done -- [Invasion of Ikoria](https://scryfall.com/search?q=!invasionofikoria)
- [x] Done -- [Invasion of Innistrad](https://scryfall.com/search?q=!invasionofinnistrad)
- [x] Done -- [Invasion of Ixalan](https://scryfall.com/search?q=!invasionofixalan)
- [x] Done -- [Invasion of Kaladesh](https://scryfall.com/search?q=!invasionofkaladesh)
- [x] Done -- [Invasion of Kaldheim](https://scryfall.com/search?q=!invasionofkaldheim)
- [x] Done -- [Invasion of Kamigawa](https://scryfall.com/search?q=!invasionofkamigawa)
- [x] Done -- [Invasion of Karsus](https://scryfall.com/search?q=!invasionofkarsus)
- [x] Done -- [Invasion of Kylem](https://scryfall.com/search?q=!invasionofkylem)
- [x] Done -- [Invasion of Lorwyn](https://scryfall.com/search?q=!invasionoflorwyn)
- [x] Done -- [Invasion of Mercadia](https://scryfall.com/search?q=!invasionofmercadia)
- [x] Done -- [Invasion of Moag](https://scryfall.com/search?q=!invasionofmoag)
- [x] Done -- [Invasion of Muraganda](https://scryfall.com/search?q=!invasionofmuraganda)
- [x] Done -- [Invasion of New Capenna](https://scryfall.com/search?q=!invasionofnewcapenna)
- [x] Done -- [Invasion of New Phyrexia](https://scryfall.com/search?q=!invasionofnewphyrexia)
- [x] Done -- [Invasion of Pyrulea](https://scryfall.com/search?q=!invasionofpyrulea)
- [x] Done -- [Invasion of Ravnica](https://scryfall.com/search?q=!invasionofravnica)
- [x] Done -- [Invasion of Regatha](https://scryfall.com/search?q=!invasionofregatha)
- [x] Done -- [Invasion of Segovia](https://scryfall.com/search?q=!invasionofsegovia)
- [x] Done -- [Invasion of Shandalar](https://scryfall.com/search?q=!invasionofshandalar)
- [x] Done -- [Invasion of Tarkir](https://scryfall.com/search?q=!invasionoftarkir)
- [x] Done -- [Invasion of Theros](https://scryfall.com/search?q=!invasionoftheros)
- [x] Done -- [Invasion of Tolvada](https://scryfall.com/search?q=!invasionoftolvada)
- [x] Done -- [Invasion of Ulgrotha](https://scryfall.com/search?q=!invasionofulgrotha)
- [x] Done -- [Invasion of Vryn](https://scryfall.com/search?q=!invasionofvryn)
- [x] Done -- [Invasion of Xerex](https://scryfall.com/search?q=!invasionofxerex)
- [x] Done -- [Invasion of Zendikar](https://scryfall.com/search?q=!invasionofzendikar)
- [x] Done -- [Iridescent Blademaster](https://scryfall.com/search?q=!iridescentblademaster)
- [x] Done -- [Jin-Gitaxias](https://scryfall.com/search?q=!jingitaxias)
- [x] Done -- [Joyful Stormsculptor](https://scryfall.com/search?q=!joyfulstormsculptor)
- [x] Done -- [Jungle Hollow](https://scryfall.com/search?q=!junglehollow)
- [x] Done -- [Kami of Whispered Hopes](https://scryfall.com/search?q=!kamiofwhisperedhopes)
- [x] Done -- [Karsus Depthguard](https://scryfall.com/search?q=!karsusdepthguard)
- [x] Done -- [Khenra Spellspear](https://scryfall.com/search?q=!khenraspellspear)
- [x] Done -- [Kitesail](https://scryfall.com/search?q=!kitesail)
- [x] Done -- [Kithkin Billyrider](https://scryfall.com/search?q=!kithkinbillyrider)
- [x] Done -- [Knight of the New Coalition](https://scryfall.com/search?q=!knightofthenewcoalition)
- [x] Done -- [Knight-Errant of Eos](https://scryfall.com/search?q=!knighterrantofeos)
- [x] Done -- [Kogla and Yidaro](https://scryfall.com/search?q=!koglaandyidaro)
- [x] Done -- [Kor Halberd](https://scryfall.com/search?q=!korhalberd)
- [x] Done -- [Kroxa and Kunoros](https://scryfall.com/search?q=!kroxaandkunoros)
- [x] Done -- [Lithomantic Barrage](https://scryfall.com/search?q=!lithomanticbarrage)
- [x] Done -- [Marauding Dreadship](https://scryfall.com/search?q=!maraudingdreadship)
- [x] Done -- [Marshal of Zhalfir](https://scryfall.com/search?q=!marshalofzhalfir)
- [x] Done -- [Meeting of Minds](https://scryfall.com/search?q=!meetingofminds)
- [x] Done -- [Merciless Repurposing](https://scryfall.com/search?q=!mercilessrepurposing)
- [x] Done -- [Mirran Banesplitter](https://scryfall.com/search?q=!mirranbanesplitter)
- [x] Done -- [Mirrodin Avenged](https://scryfall.com/search?q=!mirrodinavenged)
- [x] Done -- [Mirror-Shield Hoplite](https://scryfall.com/search?q=!mirrorshieldhoplite)
- [x] Done -- [Moment of Truth](https://scryfall.com/search?q=!momentoftruth)
- [x] Done -- [Monastery Mentor](https://scryfall.com/search?q=!monasterymentor)
- [x] Done -- [Mutagen Connoisseur](https://scryfall.com/search?q=!mutagenconnoisseur)
- [x] Done -- [Nahiri's Warcrafting](https://scryfall.com/search?q=!nahiriswarcrafting)
- [x] Done -- [Negate](https://scryfall.com/search?q=!negate)
- [x] Done -- [Nezumi Freewheeler](https://scryfall.com/search?q=!nezumifreewheeler)
- [x] Done -- [Nezumi Informant](https://scryfall.com/search?q=!nezumiinformant)
- [x] Done -- [Norn's Inquisitor](https://scryfall.com/search?q=!nornsinquisitor)
- [x] Done -- [Oculus Whelp](https://scryfall.com/search?q=!oculuswhelp)
- [x] Done -- [Omen Hawker](https://scryfall.com/search?q=!omenhawker)
- [x] Done -- [Omnath, Locus of All](https://scryfall.com/search?q=!omnathlocusofall)
- [x] Done -- [Onakke Javelineer](https://scryfall.com/search?q=!onakkejavelineer)
- [x] Done -- [Oracle of Tragedy](https://scryfall.com/search?q=!oracleoftragedy)
- [x] Done -- [Order of the Mirror](https://scryfall.com/search?q=!orderofthemirror)
- [x] Done -- [Orthion, Hero of Lavabrink](https://scryfall.com/search?q=!orthionherooflavabrink)
- [x] Done -- [Overgrown Pest](https://scryfall.com/search?q=!overgrownpest)
- [x] Done -- [Ozolith, the Shattered Spire](https://scryfall.com/search?q=!ozoliththeshatteredspire)
- [x] Done -- [Phyrexian Archivist](https://scryfall.com/search?q=!phyrexianarchivist)
- [x] Done -- [Phyrexian Awakening](https://scryfall.com/search?q=!phyrexianawakening)
- [x] Done -- [Phyrexian Censor](https://scryfall.com/search?q=!phyrexiancensor)
- [x] Done -- [Phyrexian Gargantua](https://scryfall.com/search?q=!phyrexiangargantua)
- [x] Done -- [Phyrexian Pegasus](https://scryfall.com/search?q=!phyrexianpegasus)
- [x] Done -- [Pile On](https://scryfall.com/search?q=!pileon)
- [x] Done -- [Placid Rottentail](https://scryfall.com/search?q=!placidrottentail)
- [x] Done -- [Polukranos Reborn](https://scryfall.com/search?q=!polukranosreborn)
- [x] Done -- [Portent Tracker](https://scryfall.com/search?q=!portenttracker)
- [x] Done -- [Preening Champion](https://scryfall.com/search?q=!preeningchampion)
- [x] Done -- [Progenitor Exarch](https://scryfall.com/search?q=!progenitorexarch)
- [x] Done -- [Protocol Knight](https://scryfall.com/search?q=!protocolknight)
- [x] Done -- [Pyretic Prankster](https://scryfall.com/search?q=!pyreticprankster)
- [x] Done -- [Quintorius, Loremaster](https://scryfall.com/search?q=!quintoriusloremaster)
- [x] Done -- [Ral's Reinforcements](https://scryfall.com/search?q=!ralsreinforcements)
- [x] Done -- [Ramosian Greatsword](https://scryfall.com/search?q=!ramosiangreatsword)
- [x] Done -- [Rampaging Geoderm](https://scryfall.com/search?q=!rampaginggeoderm)
- [x] Done -- [Rampaging Raptor](https://scryfall.com/search?q=!rampagingraptor)
- [x] Done -- [Rankle and Torbran](https://scryfall.com/search?q=!rankleandtorbran)
- [x] Done -- [Ravenous Sailback](https://scryfall.com/search?q=!ravenoussailback)
- [x] Done -- [Realmbreaker's Grasp](https://scryfall.com/search?q=!realmbreakersgrasp)
- [x] Done -- [Realmbreaker, the Invasion Tree](https://scryfall.com/search?q=!realmbreakertheinvasiontree)
- [x] Done -- [Redcap Heelslasher](https://scryfall.com/search?q=!redcapheelslasher)
- [x] Done -- [Referee Squad](https://scryfall.com/search?q=!refereesquad)
- [x] Done -- [Render Inert](https://scryfall.com/search?q=!renderinert)
- [x] Done -- [Rona, Herald of Invasion](https://scryfall.com/search?q=!ronaheraldofinvasion)
- [x] Done -- [Rugged Highlands](https://scryfall.com/search?q=!ruggedhighlands)
- [x] Done -- [Ruins Recluse](https://scryfall.com/search?q=!ruinsrecluse)
- [x] Done -- [Saiba Cryptomancer](https://scryfall.com/search?q=!saibacryptomancer)
- [x] Done -- [Sandstalker Moloch](https://scryfall.com/search?q=!sandstalkermoloch)
- [x] Done -- [Scorn-Blade Berserker](https://scryfall.com/search?q=!scornbladeberserker)
- [x] Done -- [Scoured Barrens](https://scryfall.com/search?q=!scouredbarrens)
- [x] Done -- [Scrappy Bruiser](https://scryfall.com/search?q=!scrappybruiser)
- [x] Done -- [Scrollshift](https://scryfall.com/search?q=!scrollshift)
- [x] Done -- [Sculpted Perfection](https://scryfall.com/search?q=!sculptedperfection)
- [x] Done -- [Seal from Existence](https://scryfall.com/search?q=!sealfromexistence)
- [x] Done -- [Searing Barb](https://scryfall.com/search?q=!searingbarb)
- [x] Done -- [See Double](https://scryfall.com/search?q=!seedouble)
- [x] Done -- [Seed of Hope](https://scryfall.com/search?q=!seedofhope)
- [x] Done -- [Seedpod Caretaker](https://scryfall.com/search?q=!seedpodcaretaker)
- [x] Done -- [Seer of Stolen Sight](https://scryfall.com/search?q=!seerofstolensight)
- [x] Done -- [Seraph of New Capenna](https://scryfall.com/search?q=!seraphofnewcapenna)
- [x] Done -- [Serpent-Blade Assailant](https://scryfall.com/search?q=!serpentbladeassailant)
- [x] Done -- [Shatter the Source](https://scryfall.com/search?q=!shatterthesource)
- [x] Done -- [Sheoldred](https://scryfall.com/search?q=!sheoldred)
- [x] Done -- [Shivan Branch-Burner](https://scryfall.com/search?q=!shivanbranchburner)
- [x] Done -- [Sigiled Sentinel](https://scryfall.com/search?q=!sigiledsentinel)
- [x] Done -- [Skittering Surveyor](https://scryfall.com/search?q=!skitteringsurveyor)
- [x] Done -- [Skyclave Aerialist](https://scryfall.com/search?q=!skyclaveaerialist)
- [x] Done -- [Stasis Field](https://scryfall.com/search?q=!stasisfield)
- [x] Done -- [Stoke the Flames](https://scryfall.com/search?q=!stoketheflames)
- [x] Done -- [Storm the Seedcore](https://scryfall.com/search?q=!stormtheseedcore)
- [x] Done -- [Stormclaw Rager](https://scryfall.com/search?q=!stormclawrager)
- [x] Done -- [Streetwise Negotiator](https://scryfall.com/search?q=!streetwisenegotiator)
- [x] Done -- [Sun-Blessed Guardian](https://scryfall.com/search?q=!sunblessedguardian)
- [x] Done -- [Sunder the Gateway](https://scryfall.com/search?q=!sunderthegateway)
- [x] Done -- [Sunfall](https://scryfall.com/search?q=!sunfall)
- [x] Done -- [Surge of Salvation](https://scryfall.com/search?q=!surgeofsalvation)
- [x] Done -- [Surrak and Goreclaw](https://scryfall.com/search?q=!surrakandgoreclaw)
- [x] Done -- [Swiftwater Cliffs](https://scryfall.com/search?q=!swiftwatercliffs)
- [x] Done -- [Sword of Once and Future](https://scryfall.com/search?q=!swordofonceandfuture)
- [x] Done -- [Swordsworn Cavalier](https://scryfall.com/search?q=!swordsworncavalier)
- [x] Done -- [Tandem Takedown](https://scryfall.com/search?q=!tandemtakedown)
- [x] Done -- [Tangled Skyline](https://scryfall.com/search?q=!tangledskyline)
- [x] Done -- [Tarkir Duneshaper](https://scryfall.com/search?q=!tarkirduneshaper)
- [x] Done -- [Temporal Cleansing](https://scryfall.com/search?q=!temporalcleansing)
- [x] Done -- [Tenured Oilcaster](https://scryfall.com/search?q=!tenuredoilcaster)
- [x] Done -- [Terror of Towashi](https://scryfall.com/search?q=!terroroftowashi)
- [x] Done -- [Thalia and The Gitrog Monster](https://scryfall.com/search?q=!thaliaandthegitrogmonster)
- [x] Done -- [Thornwood Falls](https://scryfall.com/search?q=!thornwoodfalls)
- [x] Done -- [Thrashing Frontliner](https://scryfall.com/search?q=!thrashingfrontliner)
- [x] Done -- [Thunderhead Squadron](https://scryfall.com/search?q=!thunderheadsquadron)
- [x] Done -- [Tidal Terror](https://scryfall.com/search?q=!tidalterror)
- [x] Done -- [Tiller of Flesh](https://scryfall.com/search?q=!tillerofflesh)
- [x] Done -- [Timberland Ancient](https://scryfall.com/search?q=!timberlandancient)
- [x] Done -- [Trailblazing Historian](https://scryfall.com/search?q=!trailblazinghistorian)
- [x] Done -- [Tranquil Cove](https://scryfall.com/search?q=!tranquilcove)
- [x] Done -- [Transcendent Message](https://scryfall.com/search?q=!transcendentmessage)
- [x] Done -- [Traumatic Revelation](https://scryfall.com/search?q=!traumaticrevelation)
- [x] Done -- [Tribute to the World Tree](https://scryfall.com/search?q=!tributetotheworldtree)
- [x] Done -- [Unseal the Necropolis](https://scryfall.com/search?q=!unsealthenecropolis)
- [x] Done -- [Urabrask](https://scryfall.com/search?q=!urabrask)
- [x] Done -- [Urn of Godfire](https://scryfall.com/search?q=!urnofgodfire)
- [x] Done -- [Vanquish the Weak](https://scryfall.com/search?q=!vanquishtheweak)
- [x] Done -- [Vengeant Earth](https://scryfall.com/search?q=!vengeantearth)
- [x] Done -- [Volcanic Spite](https://scryfall.com/search?q=!volcanicspite)
- [x] Done -- [Voldaren Thrillseeker](https://scryfall.com/search?q=!voldarenthrillseeker)
- [x] Done -- [Vorinclex](https://scryfall.com/search?q=!vorinclex)
- [x] Done -- [War Historian](https://scryfall.com/search?q=!warhistorian)
- [x] Done -- [War-Trained Slasher](https://scryfall.com/search?q=!wartrainedslasher)
- [x] Done -- [Wary Thespian](https://scryfall.com/search?q=!warythespian)
- [x] Done -- [Wicked Slumber](https://scryfall.com/search?q=!wickedslumber)
- [x] Done -- [Wildwood Escort](https://scryfall.com/search?q=!wildwoodescort)
- [x] Done -- [Wind-Scarred Crag](https://scryfall.com/search?q=!windscarredcrag)
- [x] Done -- [Wrenn and Realmbreaker](https://scryfall.com/search?q=!wrennandrealmbreaker)
- [x] Done -- [Wrenn's Resolve](https://scryfall.com/search?q=!wrennsresolve)
- [x] Done -- [Xerex Strobe-Knight](https://scryfall.com/search?q=!xerexstrobeknight)
- [x] Done -- [Yargle and Multani](https://scryfall.com/search?q=!yargleandmultani)
- [x] Done -- [Zephyr Singer](https://scryfall.com/search?q=!zephyrsinger)
- [x] Done -- [Zephyr Winder](https://scryfall.com/search?q=!zephyrwinder)
- [x] Done -- [Zhalfirin Lancer](https://scryfall.com/search?q=!zhalfirinlancer)
- [x] Done -- [Zhalfirin Shapecraft](https://scryfall.com/search?q=!zhalfirinshapecraft)
- [x] Done -- [Zimone and Dina](https://scryfall.com/search?q=!zimoneanddina)
- [x] Done -- [Zurgo and Ojutai](https://scryfall.com/search?q=!zurgoandojutai)
</details>

**Comment by theelk801** [comment]
Additional tasks:

none yet
