### ISSUE TITLE
MAT - March of the Machine: The Aftermath Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#10020]
This checklist is here to help manage the implementation of March of the Machine: The Aftermath. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Animist's Might](https://scryfall.com/search?q=!animistsmight)
- [x] Done -- [Arni Metalbrow](https://scryfall.com/search?q=!arnimetalbrow)
- [x] Done -- [Ayara's Oathsworn](https://scryfall.com/search?q=!ayarasoathsworn)
- [x] Done -- [Blot Out](https://scryfall.com/search?q=!blotout)
- [x] Done -- [Calix, Guided by Fate](https://scryfall.com/search?q=!calixguidedbyfate)
- [x] Done -- [Campus Renovation](https://scryfall.com/search?q=!campusrenovation)
- [x] Done -- [Coppercoat Vanguard](https://scryfall.com/search?q=!coppercoatvanguard)
- [x] Done -- [Cosmic Rebirth](https://scryfall.com/search?q=!cosmicrebirth)
- [x] Done -- [Danitha, New Benalia's Light](https://scryfall.com/search?q=!danithanewbenaliaslight)
- [x] Done -- [Death-Rattle Oni](https://scryfall.com/search?q=!deathrattleoni)
- [x] Done -- [Deification](https://scryfall.com/search?q=!deification)
- [x] Done -- [Drannith Ruins](https://scryfall.com/search?q=!drannithruins)
- [x] Done -- [Feast of the Victorious Dead](https://scryfall.com/search?q=!feastofthevictoriousdead)
- [x] Done -- [Filter Out](https://scryfall.com/search?q=!filterout)
- [x] Done -- [Gold-Forged Thopteryx](https://scryfall.com/search?q=!goldforgedthopteryx)
- [x] Done -- [Harnessed Snubhorn](https://scryfall.com/search?q=!harnessedsnubhorn)
- [x] Done -- [Jirina, Dauntless General](https://scryfall.com/search?q=!jirinadauntlessgeneral)
- [x] Done -- [Jolrael, Voice of Zhalfir](https://scryfall.com/search?q=!jolraelvoiceofzhalfir)
- [x] Done -- [Karn, Legacy Reforged](https://scryfall.com/search?q=!karnlegacyreforged)
- [x] Done -- [Kiora, Sovereign of the Deep](https://scryfall.com/search?q=!kiorasovereignofthedeep)
- [x] Done -- [Kolaghan Warmonger](https://scryfall.com/search?q=!kolaghanwarmonger)
- [x] Done -- [Leyline Immersion](https://scryfall.com/search?q=!leylineimmersion)
- [x] Done -- [Markov Baron](https://scryfall.com/search?q=!markovbaron)
- [x] Done -- [Metropolis Reformer](https://scryfall.com/search?q=!metropolisreformer)
- [x] Done -- [Nahiri's Resolve](https://scryfall.com/search?q=!nahirisresolve)
- [x] Done -- [Nahiri, Forged in Fury](https://scryfall.com/search?q=!nahiriforgedinfury)
- [x] Done -- [Narset, Enlightened Exile](https://scryfall.com/search?q=!narsetenlightenedexile)
- [x] Done -- [Nashi, Moon's Legacy](https://scryfall.com/search?q=!nashimoonslegacy)
- [x] Done -- [Nissa, Resurgent Animist](https://scryfall.com/search?q=!nissaresurgentanimist)
- [x] Done -- [Niv-Mizzet, Supreme](https://scryfall.com/search?q=!nivmizzetsupreme)
- [x] Done -- [Ob Nixilis, Captive Kingpin](https://scryfall.com/search?q=!obnixiliscaptivekingpin)
- [x] Done -- [Open the Way](https://scryfall.com/search?q=!opentheway)
- [x] Done -- [Pia Nalaar, Consul of Revival](https://scryfall.com/search?q=!pianalaarconsulofrevival)
- [x] Done -- [Plargg and Nassari](https://scryfall.com/search?q=!plarggandnassari)
- [x] Done -- [Rebuild the City](https://scryfall.com/search?q=!rebuildthecity)
- [x] Done -- [Reckless Handling](https://scryfall.com/search?q=!recklesshandling)
- [x] Done -- [Rocco, Street Chef](https://scryfall.com/search?q=!roccostreetchef)
- [x] Done -- [Samut, Vizier of Naktamun](https://scryfall.com/search?q=!samutvizierofnaktamun)
- [x] Done -- [Sarkhan, Soul Aflame](https://scryfall.com/search?q=!sarkhansoulaflame)
- [x] Done -- [Sigarda, Font of Blessings](https://scryfall.com/search?q=!sigardafontofblessings)
- [x] Done -- [Spark Rupture](https://scryfall.com/search?q=!sparkrupture)
- [x] Done -- [Tazri, Stalwart Survivor](https://scryfall.com/search?q=!tazristalwartsurvivor)
- [x] Done -- [The Kenriths' Royal Funeral](https://scryfall.com/search?q=!thekenrithsroyalfuneral)
- [x] Done -- [Tolarian Contempt](https://scryfall.com/search?q=!tolariancontempt)
- [x] Done -- [Training Grounds](https://scryfall.com/search?q=!traininggrounds)
- [x] Done -- [Tranquil Frillback](https://scryfall.com/search?q=!tranquilfrillback)
- [x] Done -- [Tyvar the Bellicose](https://scryfall.com/search?q=!tyvarthebellicose)
- [x] Done -- [Undercity Upheaval](https://scryfall.com/search?q=!undercityupheaval)
- [x] Done -- [Urborg Scavengers](https://scryfall.com/search?q=!urborgscavengers)
- [x] Done -- [Vesuvan Drifter](https://scryfall.com/search?q=!vesuvandrifter)
</details>

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by jimga150** [comment]
Taking a shot at [Ob Nixilis, Captive Kingpin](https://scryfall.com/search?q=!obnixiliscaptivekingpin)

**Comment by thebear132** [comment]
[[Urborg Scavenger]] is still not working yet unfortunately
https://github.com/magefree/mage/issues/10409

**Comment by xenohedron** [comment]
@theelk801 all cards are implemented

**Comment by DamianRobles** [comment]
[MAT] Deification isn't avaliable rn

**Comment by jimga150** [comment]
@DamianRobles As in its not in the latest beta release? That would be because the latest beta release is from mid-april, and deifiication got merged in on may 3rd. the next beta release will have the card.
