### ISSUE TITLE
LTR - The Lord of the Rings: Tales of Middle-earth Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#10258]
This checklist is here to help manage the implementation of The Lord of the Rings: Tales of Middle-earth. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Anduril, Flame of the West](https://scryfall.com/search?q=!andurilflameofthewest)
- [x] Done -- [Aragorn and Arwen, Wed](https://scryfall.com/search?q=!aragornandarwenwed)
- [x] Done -- [Aragorn, Company Leader](https://scryfall.com/search?q=!aragorncompanyleader)
- [x] Done -- [Aragorn, the Uniter](https://scryfall.com/search?q=!aragorntheuniter)
- [x] Done -- [Arwen Undomiel](https://scryfall.com/search?q=!arwenundomiel)
- [x] Done -- [Arwen's Gift](https://scryfall.com/search?q=!arwensgift)
- [x] Done -- [Arwen, Mortal Queen](https://scryfall.com/search?q=!arwenmortalqueen)
- [x] Done -- [Assault on Osgiliath](https://scryfall.com/search?q=!assaultonosgiliath)
- [x] Done -- [Bag End Porter](https://scryfall.com/search?q=!bagendporter)
- [x] Done -- [Banish from Edoras](https://scryfall.com/search?q=!banishfromedoras)
- [x] Done -- [Barad-dur](https://scryfall.com/search?q=!baraddur)
- [x] Done -- [Barrow-Blade](https://scryfall.com/search?q=!barrowblade)
- [x] Done -- [Battle-Scarred Goblin](https://scryfall.com/search?q=!battlescarredgoblin)
- [x] Done -- [Bewitching Leechcraft](https://scryfall.com/search?q=!bewitchingleechcraft)
- [x] Done -- [Bilbo's Ring](https://scryfall.com/search?q=!bilbosring)
- [x] Done -- [Bilbo, Retired Burglar](https://scryfall.com/search?q=!bilboretiredburglar)
- [x] Done -- [Bill Ferny, Bree Swindler](https://scryfall.com/search?q=!billfernybreeswindler)
- [x] Done -- [Bill the Pony](https://scryfall.com/search?q=!billthepony)
- [x] Done -- [Birthday Escape](https://scryfall.com/search?q=!birthdayescape)
- [x] Done -- [Bitter Downfall](https://scryfall.com/search?q=!bitterdownfall)
- [x] Done -- [Bombadil's Song](https://scryfall.com/search?q=!bombadilssong)
- [x] Done -- [Book of Mazarbul](https://scryfall.com/search?q=!bookofmazarbul)
- [x] Done -- [Borne Upon a Wind](https://scryfall.com/search?q=!borneuponawind)
- [x] Done -- [Boromir, Warden of the Tower](https://scryfall.com/search?q=!boromirwardenofthetower)
- [x] Done -- [Brandywine Farmer](https://scryfall.com/search?q=!brandywinefarmer)
- [x] Done -- [Breaking of the Fellowship](https://scryfall.com/search?q=!breakingofthefellowship)
- [x] Done -- [Butterbur, Bree Innkeeper](https://scryfall.com/search?q=!butterburbreeinnkeeper)
- [x] Done -- [Call of the Ring](https://scryfall.com/search?q=!callofthering)
- [x] Done -- [Captain of Umbar](https://scryfall.com/search?q=!captainofumbar)
- [x] Done -- [Cast into the Fire](https://scryfall.com/search?q=!castintothefire)
- [x] Done -- [Celeborn the Wise](https://scryfall.com/search?q=!celebornthewise)
- [x] Done -- [Chance-Met Elves](https://scryfall.com/search?q=!chancemetelves)
- [x] Done -- [Cirith Ungol Patrol](https://scryfall.com/search?q=!cirithungolpatrol)
- [x] Done -- [Claim the Precious](https://scryfall.com/search?q=!claimtheprecious)
- [x] Done -- [Council's Deliberation](https://scryfall.com/search?q=!councilsdeliberation)
- [x] Done -- [Dawn of a New Age](https://scryfall.com/search?q=!dawnofanewage)
- [x] Done -- [Deceive the Messenger](https://scryfall.com/search?q=!deceivethemessenger)
- [x] Done -- [Delighted Halfling](https://scryfall.com/search?q=!delightedhalfling)
- [x] Done -- [Denethor, Ruling Steward](https://scryfall.com/search?q=!denethorrulingsteward)
- [x] Done -- [Display of Power](https://scryfall.com/search?q=!displayofpower)
- [x] Done -- [Doors of Durin](https://scryfall.com/search?q=!doorsofdurin)
- [x] Done -- [Dreadful as the Storm](https://scryfall.com/search?q=!dreadfulasthestorm)
- [x] Done -- [Dunedain Blade](https://scryfall.com/search?q=!dunedainblade)
- [x] Done -- [Dunedain Rangers](https://scryfall.com/search?q=!dunedainrangers)
- [x] Done -- [Dunland Crebain](https://scryfall.com/search?q=!dunlandcrebain)
- [x] Done -- [Eagles of the North](https://scryfall.com/search?q=!eaglesofthenorth)
- [x] Done -- [East-Mark Cavalier](https://scryfall.com/search?q=!eastmarkcavalier)
- [x] Done -- [Easterling Vanguard](https://scryfall.com/search?q=!easterlingvanguard)
- [x] Done -- [Eastfarthing Farmer](https://scryfall.com/search?q=!eastfarthingfarmer)
- [x] Done -- [Elanor Gardner](https://scryfall.com/search?q=!elanorgardner)
- [x] Done -- [Elrond, Lord of Rivendell](https://scryfall.com/search?q=!elrondlordofrivendell)
- [x] Done -- [Elrond, Master of Healing](https://scryfall.com/search?q=!elrondmasterofhealing)
- [x] Done -- [Elven Chorus](https://scryfall.com/search?q=!elvenchorus)
- [x] Done -- [Elven Farsight](https://scryfall.com/search?q=!elvenfarsight)
- [x] Done -- [Elvish Mariner](https://scryfall.com/search?q=!elvishmariner)
- [x] Done -- [Enraged Huorn](https://scryfall.com/search?q=!enragedhuorn)
- [x] Done -- [Ent's Fury](https://scryfall.com/search?q=!entsfury)
- [x] Done -- [Ent-Draught Basin](https://scryfall.com/search?q=!entdraughtbasin)
- [x] Done -- [Entish Restoration](https://scryfall.com/search?q=!entishrestoration)
- [x] Done -- [Eomer of the Riddermark](https://scryfall.com/search?q=!eomeroftheriddermark)
- [x] Done -- [Eomer, Marshal of Rohan](https://scryfall.com/search?q=!eomermarshalofrohan)
- [x] Done -- [Eowyn, Fearless Knight](https://scryfall.com/search?q=!eowynfearlessknight)
- [x] Done -- [Eowyn, Lady of Rohan](https://scryfall.com/search?q=!eowynladyofrohan)
- [x] Done -- [Erebor Flamesmith](https://scryfall.com/search?q=!ereborflamesmith)
- [x] Done -- [Erkenbrand, Lord of Westfold](https://scryfall.com/search?q=!erkenbrandlordofwestfold)
- [x] Done -- [Errand-Rider of Gondor](https://scryfall.com/search?q=!errandriderofgondor)
- [x] Done -- [Escape from Orthanc](https://scryfall.com/search?q=!escapefromorthanc)
- [x] Done -- [Esquire of the King](https://scryfall.com/search?q=!esquireoftheking)
- [x] Done -- [Fall of Cair Andros](https://scryfall.com/search?q=!fallofcairandros)
- [x] Done -- [Fall of Gil-galad](https://scryfall.com/search?q=!fallofgilgalad)
- [x] Done -- [Fangorn, Tree Shepherd](https://scryfall.com/search?q=!fangorntreeshepherd)
- [x] Done -- [Faramir, Field Commander](https://scryfall.com/search?q=!faramirfieldcommander)
- [x] Done -- [Faramir, Prince of Ithilien](https://scryfall.com/search?q=!faramirprinceofithilien)
- [x] Done -- [Fear, Fire, Foes!](https://scryfall.com/search?q=!fearfirefoes!)
- [x] Done -- [Fiery Inscription](https://scryfall.com/search?q=!fieryinscription)
- [x] Done -- [Fire of Orthanc](https://scryfall.com/search?q=!fireoforthanc)
- [x] Done -- [Fires of Mount Doom](https://scryfall.com/search?q=!firesofmountdoom)
- [x] Done -- [Flame of Anor](https://scryfall.com/search?q=!flameofanor)
- [x] Done -- [Flowering of the White Tree](https://scryfall.com/search?q=!floweringofthewhitetree)
- [x] Done -- [Fog on the Barrow-Downs](https://scryfall.com/search?q=!fogonthebarrowdowns)
- [x] Done -- [Foray of Orcs](https://scryfall.com/search?q=!forayoforcs)
- [x] Done -- [Forge Anew](https://scryfall.com/search?q=!forgeanew)
- [x] Done -- [Friendly Rivalry](https://scryfall.com/search?q=!friendlyrivalry)
- [x] Done -- [Frodo Baggins](https://scryfall.com/search?q=!frodobaggins)
- [x] Done -- [Frodo, Determined Hero](https://scryfall.com/search?q=!frododeterminedhero)
- [x] Done -- [Frodo, Sauron's Bane](https://scryfall.com/search?q=!frodosauronsbane)
- [x] Done -- [Galadhrim Bow](https://scryfall.com/search?q=!galadhrimbow)
- [x] Done -- [Galadhrim Guide](https://scryfall.com/search?q=!galadhrimguide)
- [x] Done -- [Galadriel of Lothlorien](https://scryfall.com/search?q=!galadrieloflothlorien)
- [x] Done -- [Galadriel, Gift-Giver](https://scryfall.com/search?q=!galadrielgiftgiver)
- [x] Done -- [Gandalf the Grey](https://scryfall.com/search?q=!gandalfthegrey)
- [x] Done -- [Gandalf the White](https://scryfall.com/search?q=!gandalfthewhite)
- [x] Done -- [Gandalf's Sanction](https://scryfall.com/search?q=!gandalfssanction)
- [x] Done -- [Gandalf, Friend of the Shire](https://scryfall.com/search?q=!gandalffriendoftheshire)
- [x] Done -- [Gandalf, White Rider](https://scryfall.com/search?q=!gandalfwhiterider)
- [x] Done -- [Generous Ent](https://scryfall.com/search?q=!generousent)
- [x] Done -- [Gift of Strands](https://scryfall.com/search?q=!giftofstrands)
- [x] Done -- [Gimli's Axe](https://scryfall.com/search?q=!gimlisaxe)
- [x] Done -- [Gimli's Fury](https://scryfall.com/search?q=!gimlisfury)
- [x] Done -- [Gimli, Counter of Kills](https://scryfall.com/search?q=!gimlicounterofkills)
- [x] Done -- [Gimli, Mournful Avenger](https://scryfall.com/search?q=!gimlimournfulavenger)
- [x] Done -- [Glamdring](https://scryfall.com/search?q=!glamdring)
- [x] Done -- [Gloin, Dwarf Emissary](https://scryfall.com/search?q=!gloindwarfemissary)
- [x] Done -- [Glorfindel, Dauntless Rescuer](https://scryfall.com/search?q=!glorfindeldauntlessrescuer)
- [x] Done -- [Glorious Gale](https://scryfall.com/search?q=!gloriousgale)
- [x] Done -- [Goblin Assailant](https://scryfall.com/search?q=!goblinassailant)
- [x] Done -- [Goblin Fireleaper](https://scryfall.com/search?q=!goblinfireleaper)
- [x] Done -- [Goldberry, River-Daughter](https://scryfall.com/search?q=!goldberryriverdaughter)
- [x] Done -- [Gollum's Bite](https://scryfall.com/search?q=!gollumsbite)
- [x] Done -- [Gollum, Patient Plotter](https://scryfall.com/search?q=!gollumpatientplotter)
- [x] Done -- [Gollum, Scheming Guide](https://scryfall.com/search?q=!gollumschemingguide)
- [x] Done -- [Gorbag of Minas Morgul](https://scryfall.com/search?q=!gorbagofminasmorgul)
- [x] Done -- [Gothmog, Morgul Lieutenant](https://scryfall.com/search?q=!gothmogmorgullieutenant)
- [x] Done -- [Great Hall of the Citadel](https://scryfall.com/search?q=!greathallofthecitadel)
- [x] Done -- [Grey Havens Navigator](https://scryfall.com/search?q=!greyhavensnavigator)
- [x] Done -- [Grima Wormtongue](https://scryfall.com/search?q=!grimawormtongue)
- [x] Done -- [Grishnakh, Brash Instigator](https://scryfall.com/search?q=!grishnakhbrashinstigator)
- [x] Done -- [Grond, the Gatebreaker](https://scryfall.com/search?q=!grondthegatebreaker)
- [x] Done -- [Gwaihir the Windlord](https://scryfall.com/search?q=!gwaihirthewindlord)
- [x] Done -- [Haradrim Spearmaster](https://scryfall.com/search?q=!haradrimspearmaster)
- [x] Done -- [Haunt of the Dead Marshes](https://scryfall.com/search?q=!hauntofthedeadmarshes)
- [x] Done -- [Hew the Entwood](https://scryfall.com/search?q=!hewtheentwood)
- [x] Done -- [Hithlain Knots](https://scryfall.com/search?q=!hithlainknots)
- [x] Done -- [Hobbit's Sting](https://scryfall.com/search?q=!hobbitssting)
- [x] Done -- [Horn of Gondor](https://scryfall.com/search?q=!hornofgondor)
- [x] Done -- [Horn of the Mark](https://scryfall.com/search?q=!hornofthemark)
- [x] Done -- [Horses of the Bruinen](https://scryfall.com/search?q=!horsesofthebruinen)
- [x] Done -- [Improvised Club](https://scryfall.com/search?q=!improvisedclub)
- [x] Done -- [Inherited Envelope](https://scryfall.com/search?q=!inheritedenvelope)
- [x] Done -- [Ioreth of the Healing House](https://scryfall.com/search?q=!iorethofthehealinghouse)
- [x] Done -- [Isildur's Fateful Strike](https://scryfall.com/search?q=!isildursfatefulstrike)
- [x] Done -- [Isolation at Orthanc](https://scryfall.com/search?q=!isolationatorthanc)
- [x] Done -- [Ithilien Kingfisher](https://scryfall.com/search?q=!ithilienkingfisher)
- [x] Done -- [King of the Oathbreakers](https://scryfall.com/search?q=!kingoftheoathbreakers)
- [x] Done -- [Knight of the Keep](https://scryfall.com/search?q=!knightofthekeep)
- [x] Done -- [Knights of Dol Amroth](https://scryfall.com/search?q=!knightsofdolamroth)
- [x] Done -- [Landroval, Horizon Witness](https://scryfall.com/search?q=!landrovalhorizonwitness)
- [x] Done -- [Lash of the Balrog](https://scryfall.com/search?q=!lashofthebalrog)
- [x] Done -- [Last March of the Ents](https://scryfall.com/search?q=!lastmarchoftheents)
- [x] Done -- [Legolas, Counter of Kills](https://scryfall.com/search?q=!legolascounterofkills)
- [x] Done -- [Legolas, Master Archer](https://scryfall.com/search?q=!legolasmasterarcher)
- [x] Done -- [Lembas](https://scryfall.com/search?q=!lembas)
- [x] Done -- [Lobelia Sackville-Baggins](https://scryfall.com/search?q=!lobeliasackvillebaggins)
- [x] Done -- [Long List of the Ents](https://scryfall.com/search?q=!longlistoftheents)
- [x] Done -- [Lorien Revealed](https://scryfall.com/search?q=!lorienrevealed)
- [x] Done -- [Lost Isle Calling](https://scryfall.com/search?q=!lostislecalling)
- [x] Done -- [Lost to Legend](https://scryfall.com/search?q=!losttolegend)
- [x] Done -- [Lothlorien Lookout](https://scryfall.com/search?q=!lothlorienlookout)
- [x] Done -- [Lotho, Corrupt Shirriff](https://scryfall.com/search?q=!lothocorruptshirriff)
- [x] Done -- [Many Partings](https://scryfall.com/search?q=!manypartings)
- [x] Done -- [March from the Black Gate](https://scryfall.com/search?q=!marchfromtheblackgate)
- [x] Done -- [Mauhur, Uruk-hai Captain](https://scryfall.com/search?q=!mauhururukhaicaptain)
- [x] Done -- [Meneldor, Swift Savior](https://scryfall.com/search?q=!meneldorswiftsavior)
- [x] Done -- [Meriadoc Brandybuck](https://scryfall.com/search?q=!meriadocbrandybuck)
- [x] Done -- [Merry, Esquire of Rohan](https://scryfall.com/search?q=!merryesquireofrohan)
- [x] Done -- [Minas Tirith](https://scryfall.com/search?q=!minastirith)
- [x] Done -- [Mines of Moria](https://scryfall.com/search?q=!minesofmoria)
- [x] Done -- [Mirkwood Bats](https://scryfall.com/search?q=!mirkwoodbats)
- [x] Done -- [Mirkwood Spider](https://scryfall.com/search?q=!mirkwoodspider)
- [x] Done -- [Mirror of Galadriel](https://scryfall.com/search?q=!mirrorofgaladriel)
- [x] Done -- [Mirrormere Guardian](https://scryfall.com/search?q=!mirrormereguardian)
- [x] Done -- [Mithril Coat](https://scryfall.com/search?q=!mithrilcoat)
- [x] Done -- [Mordor Muster](https://scryfall.com/search?q=!mordormuster)
- [x] Done -- [Mordor Trebuchet](https://scryfall.com/search?q=!mordortrebuchet)
- [x] Done -- [Morgul-Knife Wound](https://scryfall.com/search?q=!morgulknifewound)
- [x] Done -- [Moria Marauder](https://scryfall.com/search?q=!moriamarauder)
- [x] Done -- [Mount Doom](https://scryfall.com/search?q=!mountdoom)
- [x] Done -- [Mushroom Watchdogs](https://scryfall.com/search?q=!mushroomwatchdogs)
- [x] Done -- [Nasty End](https://scryfall.com/search?q=!nastyend)
- [x] Done -- [Nazgul](https://scryfall.com/search?q=!nazgul)
- [x] Done -- [Nimble Hobbit](https://scryfall.com/search?q=!nimblehobbit)
- [x] Done -- [Nimrodel Watcher](https://scryfall.com/search?q=!nimrodelwatcher)
- [x] Done -- [Now for Wrath, Now for Ruin!](https://scryfall.com/search?q=!nowforwrathnowforruin!)
- [x] Done -- [Oath of the Grey Host](https://scryfall.com/search?q=!oathofthegreyhost)
- [x] Done -- [Old Man Willow](https://scryfall.com/search?q=!oldmanwillow)
- [x] Done -- [Oliphaunt](https://scryfall.com/search?q=!oliphaunt)
- [x] Done -- [Olog-hai Crusher](https://scryfall.com/search?q=!ologhaicrusher)
- [x] Done -- [One Ring to Rule Them All](https://scryfall.com/search?q=!oneringtorulethemall)
- [x] Done -- [Orcish Bowmasters](https://scryfall.com/search?q=!orcishbowmasters)
- [x] Done -- [Orcish Medicine](https://scryfall.com/search?q=!orcishmedicine)
- [x] Done -- [Palantir of Orthanc](https://scryfall.com/search?q=!palantiroforthanc)
- [x] Done -- [Pelargir Survivor](https://scryfall.com/search?q=!pelargirsurvivor)
- [x] Done -- [Peregrin Took](https://scryfall.com/search?q=!peregrintook)
- [x] Done -- [Phial of Galadriel](https://scryfall.com/search?q=!phialofgaladriel)
- [x] Done -- [Pippin's Bravery](https://scryfall.com/search?q=!pippinsbravery)
- [x] Done -- [Pippin, Guard of the Citadel](https://scryfall.com/search?q=!pippinguardofthecitadel)
- [x] Done -- [Press the Enemy](https://scryfall.com/search?q=!presstheenemy)
- [x] Done -- [Prince Imrahil the Fair](https://scryfall.com/search?q=!princeimrahilthefair)
- [x] Done -- [Protector of Gondor](https://scryfall.com/search?q=!protectorofgondor)
- [x] Done -- [Quarrel's End](https://scryfall.com/search?q=!quarrelsend)
- [x] Done -- [Quickbeam, Upstart Ent](https://scryfall.com/search?q=!quickbeamupstartent)
- [x] Done -- [Radagast the Brown](https://scryfall.com/search?q=!radagastthebrown)
- [x] Done -- [Rally at the Hornburg](https://scryfall.com/search?q=!rallyatthehornburg)
- [x] Done -- [Ranger's Firebrand](https://scryfall.com/search?q=!rangersfirebrand)
- [x] Done -- [Rangers of Ithilien](https://scryfall.com/search?q=!rangersofithilien)
- [x] Done -- [Relentless Rohirrim](https://scryfall.com/search?q=!relentlessrohirrim)
- [x] Done -- [Reprieve](https://scryfall.com/search?q=!reprieve)
- [x] Done -- [Revive the Shire](https://scryfall.com/search?q=!revivetheshire)
- [x] Done -- [Ringsight](https://scryfall.com/search?q=!ringsight)
- [x] Done -- [Ringwraiths](https://scryfall.com/search?q=!ringwraiths)
- [x] Done -- [Rise of the Witch-king](https://scryfall.com/search?q=!riseofthewitchking)
- [x] Done -- [Rising of the Day](https://scryfall.com/search?q=!risingoftheday)
- [x] Done -- [Rivendell](https://scryfall.com/search?q=!rivendell)
- [x] Done -- [Rohirrim Lancer](https://scryfall.com/search?q=!rohirrimlancer)
- [x] Done -- [Rosie Cotton of South Lane](https://scryfall.com/search?q=!rosiecottonofsouthlane)
- [x] Done -- [Rush the Room](https://scryfall.com/search?q=!rushtheroom)
- [x] Done -- [Sam's Desperate Rescue](https://scryfall.com/search?q=!samsdesperaterescue)
- [x] Done -- [Samwise Gamgee](https://scryfall.com/search?q=!samwisegamgee)
- [x] Done -- [Samwise the Stouthearted](https://scryfall.com/search?q=!samwisethestouthearted)
- [x] Done -- [Saradoc, Master of Buckland](https://scryfall.com/search?q=!saradocmasterofbuckland)
- [x] Done -- [Saruman of Many Colors](https://scryfall.com/search?q=!sarumanofmanycolors)
- [x] Done -- [Saruman the White](https://scryfall.com/search?q=!sarumanthewhite)
- [x] Done -- [Saruman's Trickery](https://scryfall.com/search?q=!sarumanstrickery)
- [x] Done -- [Sauron's Ransom](https://scryfall.com/search?q=!sauronsransom)
- [x] Done -- [Sauron, the Dark Lord](https://scryfall.com/search?q=!sauronthedarklord)
- [x] Done -- [Sauron, the Lidless Eye](https://scryfall.com/search?q=!sauronthelidlesseye)
- [x] Done -- [Sauron, the Necromancer](https://scryfall.com/search?q=!sauronthenecromancer)
- [x] Done -- [Scroll of Isildur](https://scryfall.com/search?q=!scrollofisildur)
- [x] Done -- [Second Breakfast](https://scryfall.com/search?q=!secondbreakfast)
- [x] Done -- [Shadow Summoning](https://scryfall.com/search?q=!shadowsummoning)
- [x] Done -- [Shadow of the Enemy](https://scryfall.com/search?q=!shadowoftheenemy)
- [x] Done -- [Shadowfax, Lord of Horses](https://scryfall.com/search?q=!shadowfaxlordofhorses)
- [x] Done -- [Shagrat, Loot Bearer](https://scryfall.com/search?q=!shagratlootbearer)
- [x] Done -- [Sharkey, Tyrant of the Shire](https://scryfall.com/search?q=!sharkeytyrantoftheshire)
- [x] Done -- [Shelob's Ambush](https://scryfall.com/search?q=!shelobsambush)
- [x] Done -- [Shelob, Child of Ungoliant](https://scryfall.com/search?q=!shelobchildofungoliant)
- [x] Done -- [Shire Scarecrow](https://scryfall.com/search?q=!shirescarecrow)
- [x] Done -- [Shire Shirriff](https://scryfall.com/search?q=!shireshirriff)
- [x] Done -- [Shire Terrace](https://scryfall.com/search?q=!shireterrace)
- [x] Done -- [Shortcut to Mushrooms](https://scryfall.com/search?q=!shortcuttomushrooms)
- [x] Done -- [Shower of Arrows](https://scryfall.com/search?q=!showerofarrows)
- [x] Done -- [Slip On the Ring](https://scryfall.com/search?q=!sliponthering)
- [x] Done -- [Smeagol, Helpful Guide](https://scryfall.com/search?q=!smeagolhelpfulguide)
- [x] Done -- [Smite the Deathless](https://scryfall.com/search?q=!smitethedeathless)
- [x] Done -- [Snarling Warg](https://scryfall.com/search?q=!snarlingwarg)
- [x] Done -- [Soldier of the Grey Host](https://scryfall.com/search?q=!soldierofthegreyhost)
- [x] Done -- [Soothing of Smeagol](https://scryfall.com/search?q=!soothingofsmeagol)
- [x] Done -- [Spiteful Banditry](https://scryfall.com/search?q=!spitefulbanditry)
- [x] Done -- [Stalwarts of Osgiliath](https://scryfall.com/search?q=!stalwartsofosgiliath)
- [x] Done -- [Stern Scolding](https://scryfall.com/search?q=!sternscolding)
- [x] Done -- [Stew the Coneys](https://scryfall.com/search?q=!stewtheconeys)
- [x] Done -- [Sting, the Glinting Dagger](https://scryfall.com/search?q=!stingtheglintingdagger)
- [x] Done -- [Stone of Erech](https://scryfall.com/search?q=!stoneoferech)
- [x] Done -- [Storm of Saruman](https://scryfall.com/search?q=!stormofsaruman)
- [x] Done -- [Strider, Ranger of the North](https://scryfall.com/search?q=!striderrangerofthenorth)
- [x] Done -- [Surrounded by Orcs](https://scryfall.com/search?q=!surroundedbyorcs)
- [x] Done -- [Swarming of Moria](https://scryfall.com/search?q=!swarmingofmoria)
- [x] Done -- [Tale of Tinuviel](https://scryfall.com/search?q=!taleoftinuviel)
- [x] Done -- [The Balrog, Durin's Bane](https://scryfall.com/search?q=!thebalrogdurinsbane)
- [x] Done -- [The Balrog, Flame of Udun](https://scryfall.com/search?q=!thebalrogflameofudun)
- [x] Done -- [The Bath Song](https://scryfall.com/search?q=!thebathsong)
- [x] Done -- [The Battle of Bywater](https://scryfall.com/search?q=!thebattleofbywater)
- [x] Done -- [The Black Breath](https://scryfall.com/search?q=!theblackbreath)
- [x] Done -- [The Grey Havens](https://scryfall.com/search?q=!thegreyhavens)
- [x] Done -- [The Mouth of Sauron](https://scryfall.com/search?q=!themouthofsauron)
- [x] Done -- [The One Ring](https://scryfall.com/search?q=!theonering)
- [x] Done -- [The Ring Goes South](https://scryfall.com/search?q=!theringgoessouth)
- [x] Done -- [The Shire](https://scryfall.com/search?q=!theshire)
- [x] Done -- [The Torment of Gollum](https://scryfall.com/search?q=!thetormentofgollum)
- [x] Done -- [The Watcher in the Water](https://scryfall.com/search?q=!thewatcherinthewater)
- [x] Done -- [Theoden, King of Rohan](https://scryfall.com/search?q=!theodenkingofrohan)
- [x] Done -- [There and Back Again](https://scryfall.com/search?q=!thereandbackagain)
- [x] Done -- [Tom Bombadil](https://scryfall.com/search?q=!tombombadil)
- [x] Done -- [Took Reaper](https://scryfall.com/search?q=!tookreaper)
- [x] Done -- [Trailblazer's Boots](https://scryfall.com/search?q=!trailblazersboots)
- [x] Done -- [Treason of Isengard](https://scryfall.com/search?q=!treasonofisengard)
- [x] Done -- [Troll of Khazad-dum](https://scryfall.com/search?q=!trollofkhazaddum)
- [x] Done -- [Ugluk of the White Hand](https://scryfall.com/search?q=!uglukofthewhitehand)
- [x] Done -- [Uruk-hai Berserker](https://scryfall.com/search?q=!urukhaiberserker)
- [x] Done -- [Voracious Fell Beast](https://scryfall.com/search?q=!voraciousfellbeast)
- [x] Done -- [War of the Last Alliance](https://scryfall.com/search?q=!warofthelastalliance)
- [x] Done -- [Warbeast of Gorgoroth](https://scryfall.com/search?q=!warbeastofgorgoroth)
- [x] Done -- [Westfold Rider](https://scryfall.com/search?q=!westfoldrider)
- [x] Done -- [Willow-Wind](https://scryfall.com/search?q=!willowwind)
- [x] Done -- [Witch-king of Angmar](https://scryfall.com/search?q=!witchkingofangmar)
- [x] Done -- [Witch-king, Bringer of Ruin](https://scryfall.com/search?q=!witchkingbringerofruin)
- [x] Done -- [Wizard's Rockets](https://scryfall.com/search?q=!wizardsrockets)
- [x] Done -- [Wose Pathfinder](https://scryfall.com/search?q=!wosepathfinder)
- [x] Done -- [You Cannot Pass!](https://scryfall.com/search?q=!youcannotpass!)
</details>

**Comment by theelk801** [comment]
Additional tasks:
- [ ] Implemented tempted by the ring mechanic (we don't know what it does yet)

**Comment by alexander-novo** [comment]
Tempted by the ring mechanic:

![image](https://user-images.githubusercontent.com/11657716/236557152-df532989-9d1e-4ad0-b770-9a67c99ca8d3.png)

**Comment by alexander-novo** [comment]
I'll grab [Saruman of Many Colors](https://scryfall.com/search?q=!sarumanofmanycolors) and [Storm of Saruman](https://scryfall.com/search?q=!stormofsaruman)

**Comment by Susucre** [comment]
I have opened a couple pull requests on 
[Orcish Bowmasters](https://github.com/magefree/mage/pull/10450) and [Rise of the Witch-King](https://github.com/magefree/mage/pull/10466).

Not sure it is needed to list them here, I did not want to waste somebody else effort to implement those, as there are still many ltr and ltc cards to implement.

**Comment by alexander-novo** [comment]
I'll nab [Goldberry, River-Daughter](https://scryfall.com/search?q=!goldberryriverdaughter)

**Comment by rockydirtbag** [comment]
I made Gandalf the White. PR [here](https://github.com/magefree/mage/pull/10528)

**Comment by TiagoMDG** [comment]
Created Ent's Fury. [Pull Request](https://github.com/magefree/mage/pull/10532/commits/81b8b172d3215c570d60898e821b1394c23eed4e)

**Comment by TiagoMDG** [comment]
Implemented Strider, Ranger of the North.  [Pull Request](https://github.com/magefree/mage/pull/10536)

**Comment by TiagoMDG** [comment]
Did Barrow-Blade. [Pull Request](Barrow-Blade)

**Comment by bobby-mccann** [comment]
I'll do [Witch-king of Angmar](https://scryfall.com/card/ltr/114/witch-king-of-angmar)

**Comment by bobby-mccann** [comment]
I'll do [Radagast the Brown](https://scryfall.com/search?q=!radagastthebrown)

**Comment by bobby-mccann** [comment]
I'll do [Glamdring](https://scryfall.com/search?q=!glamdring)

**Comment by bobby-mccann** [comment]
I'll do [Bill Ferny, Bree Swindler](https://scryfall.com/search?q=!billfernybreeswindler)

**Comment by bobby-mccann** [comment]
I'll do [Forge Anew](https://scryfall.com/search?q=!forgeanew)

**Comment by theelk801** [comment]
that's a wrap, thanks to everyone who contributed

**Comment by Susucre** [comment]
5 new cards in LTR: https://scryfall.com/search?q=set%3Altr+-is%3Areprint+cn%3E%3D824&unique=cards&as=grid&order=set&dir=desc

@JayDi85 If possible, could I get rights to edit the issues from others. That would make things easier for theelk801 and xenohedron that keep those issues up to date, I'd like to also contribute to keeping things organized.

**Comment by Susucre** [comment]
@theelk801 if/when you have time, there is a bunch of new variants for LTR.

Should be good with all the new cards from the collector boosters/jumpstart (it is hard to keep track will all the details)
