### ISSUE TITLE
WHO - Doctor Who Card Set Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#10653]
This checklist is here to help manage the implementation of Doctor Who. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [TARDIS](https://scryfall.com/search?q=!tardis)
- [ ] In progress -- [The Parting of the Ways](https://scryfall.com/search?q=!thepartingoftheways)
- [ ] In progress -- [The Tenth Doctor](https://scryfall.com/search?q=!thetenthdoctor)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"TARDIS"or!"ThePartingOfTheWays"or!"TheTenthDoctor"&unique=cards)
# Implemented Cards

- [x] Done -- [Exterminate!](https://scryfall.com/search?q=!exterminate!)

**Comment by xenohedron** [comment]
Official release notes including rulings which may be relevant for implementations:

https://magic.wizards.com/en/news/feature/magic-the-gathering-doctor-who-release-notes

**Comment by ThallianFolmin** [comment]
I hope it is ok to post this here:
Rose Tyler is bugged. Instead of counting all permanents with time counter, she counts all permanents.

**Comment by Susucre** [comment]
Usually that is worth a bug issue. It is less likely to be forgotten and easier to search that way.

**Comment by Mo1eculeMan** [comment]
Hi! I don't have permission to check things off because I'm new, but I'm attempting to implement The Twelfth Doctor, and may move onto other ones once I can get him working.

**Comment by Mo1eculeMan** [comment]
Hello! I finished The Twelfth Doctor, and in the coming days will start work on The Eleventh Doctor. Cheers!

**Comment by permadeath** [comment]
I am currently working on Genesis of the Daleks.  Thanks!

**Comment by Cguy7777** [comment]
Working on The Beast, Deathless Prince

**Comment by Cguy7777** [comment]
Working on The Third Doctor

**Comment by Cguy7777** [comment]
Working on Duggan, Private Detective

**Comment by Cguy7777** [comment]
Working on Leela, Sevateem Warrior

**Comment by jimga150** [comment]
Working on [Donna Noble](https://scryfall.com/search?q=!donnanoble)

**Comment by skiwkr** [comment]
Working on Me, the Immortal

**Comment by skiwkr** [comment]
Working on The Foretold Soldier

**Comment by skiwkr** [comment]
Working on Flesh Duplicate and Zygon Infiltrator.  

Does anyone have any insight on what would be the best/easiest way to implement the "copy until other card untaps" effect?  If there's an easy way to make a custom duration that doesn't involve adding a whole new enum to Duration that would probably be the easiest way to do it, but I'm not sure if it's possible or if I should just be making a modified copy effect.

**Comment by xenohedron** [comment]
> Does anyone have any insight on what would be the best/easiest way to implement the "copy until other card untaps" effect? If there's an easy way to make a custom duration that doesn't involve adding a whole new enum to Duration that would probably be the easiest way to do it, but I'm not sure if it's possible or if I should just be making a modified copy effect.

You can override `isInactive()` in your continuous effect, see  #11791 for an example

**Comment by Susucre** [comment]
> Has anyone plans to working on [The Master, Formed Anew](https://scryfall.com/search?q=!themasterformedanew)?

I don't think anyone is working on it (we try to keep the InProgress checkmarks just for that). Do you want to try to work on it?

**Comment by Aycaramba100** [comment]
> > Has anyone plans to working on [The Master, Formed Anew](https://scryfall.com/search?q=!themasterformedanew)?
> 
> I don't think anyone is working on it (we try to keep the InProgress checkmarks just for that). Do you want to try to work on it?

Unfortunately, I have no idea about coding. Is there a simple guide for dummies?

**Comment by Mrdadbody** [comment]
Really the Second doctor and vislor added lol

**Comment by jimga150** [comment]
Working on [Weeping Angel](https://scryfall.com/search?q=!weepingangel) (oops)

**Comment by Sidorovich77** [comment]
I've implemented Vrestin, Menoptra Leader.
#12643

**Comment by padfoothelix** [comment]
Working on This is How it Ends, Fugitive of the Judoon, River Song's Diary (almost done with these).

Working on Danny Pink too but this one is a little bit more tricky.

River Song is shown as in progress on this page but it has been coded for some time ; I suppose it might be a bug because of River Song's Diary ?

**Comment by padfoothelix** [comment]
Working on The Moment

**Comment by davinsoman** [comment]
Hello, I'm new here and to Open Source itself. If possible, could I work on The Eighth Doctor if no one else is currently working on it? I also plan on working on The War Doctor and any other additions when I can get around to it. Thank you in advance, looking forward to it.

**Comment by padfoothelix** [comment]
Working on Ashad, the Lone Cyberman

**Comment by P0T4T054CK** [comment]
the card "Vislor Turlough" shows up in the implemented card section but it is not on xmage. I super want to build reanimator doctors and need that card <3

**Comment by padfoothelix** [comment]
Working on The Fourth Doctor.

**Comment by matoro** [comment]
These cards are blocked on the face-down rework in https://github.com/magefree/mage/pull/13486

[[Cyber Conversion]], [[Cybership]], [[Death in Heaven]], [[Missy]], [[The Cyber-Controller]]
