### ISSUE TITLE
WOE - Wilds of Eldraine Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#10759]
This checklist is here to help manage the implementation of Wilds of Eldraine. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Ashiok, Wicked Manipulator](https://scryfall.com/search?q=!ashiokwickedmanipulator)
- [ ] In progress -- [Moonshaker Cavalry](https://scryfall.com/search?q=!moonshakercavalry)
- [ ] In progress -- [Talion, the Kindly Lord](https://scryfall.com/search?q=!talionthekindlylord)
- [ ] In progress -- [Tough Cookie](https://scryfall.com/search?q=!toughcookie)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"AshiokWickedManipulator"or!"MoonshakerCavalry"or!"TalionTheKindlyLord"or!"ToughCookie"&unique=cards)
# Implemented Cards

- [x] Done -- [Cruel Somnophage](https://scryfall.com/search?q=!cruelsomnophage)
- [x] Done -- [Restless Fortress](https://scryfall.com/search?q=!restlessfortress)
- [x] Done -- [Sleight of Hand](https://scryfall.com/search?q=!sleightofhand)

**Comment by theelk801** [comment]
Additional Tasks:

None yet

**Comment by Susucre** [comment]
I think with the start of spoilers today, we could pin that one (And the one that will be created for the Commander Set for the set. I think there will be 20 new cards, and reprints.)

**Comment by Susucre** [comment]
For anyone wanting to start working on Roles, seems like this is a new StateBaseAction to sacrifice all but the newest Role on each permanent:
https://magic.wizards.com/en/news/feature/wilds-of-eldraine-mechanics 

There are 6 different roles in the main set, and 1 more in the commander set.

**Comment by Susucre** [comment]
Did Celebration too: #10818

**Comment by Susucre** [comment]
Just to avoid multiple devs working on the same cards, as this already happened today with two different Ego Drain PRs, I'd like to mention that Icewrought Sentry should be done #10879, and with the new trigger I'm now working on Hylda of the Icy Crown.

And altought I have made an attempt at Johann's Stopgap, if someone wants to try to make that without the -2+2 workaround, I do not mind at all. Probably will close my PR if I can't figure that out.

**Comment by xenohedron** [comment]
All cards have been implemented!
* Special thanks to @Susucre and @xanderhall .
* I enabled booster generation including Enchanting Tales.
* Only one text discrepancy left that indicates a potential logic discrepancy: Free the Fae (the adventure side of Picklock Prankster).
* Of course, there may be bugs lurking so please open an issue if you find one.
* Just need @theelk801 to add the alternate art printings, then should be good for a release on time!

**Comment by Susucre** [comment]
Is there also a need to add new tokens in the token list?

**Comment by theelk801** [comment]
I think @PurpleCrowbar usually does that, but we can close this anyway
