### ISSUE TITLE
WOC - Wilds of Eldraine Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#10815]
This checklist is here to help manage the implementation of Wilds of Eldraine Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [x] In progress -- [Court of Locthwain](https://scryfall.com/search?q=!courtoflocthwain)
- [x] In progress -- [Liberated Livestock](https://scryfall.com/search?q=!liberatedlivestock)
- [x] In progress -- [Tegwyll's Scouring](https://scryfall.com/search?q=!tegwyllsscouring)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"CourtOfLocthwain"or!"LiberatedLivestock"or!"TegwyllsScouring"&unique=cards)
# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Ajani's Chosen](https://scryfall.com/search?q=!ajanischosen)
- [x] Done -- [Alela, Cunning Conqueror](https://scryfall.com/search?q=!alelacunningconqueror)
- [x] Done -- [Ancestral Mask](https://scryfall.com/search?q=!ancestralmask)
- [x] Done -- [Angelic Destiny](https://scryfall.com/search?q=!angelicdestiny)
- [x] Done -- [Arcane Denial](https://scryfall.com/search?q=!arcanedenial)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Archmage of Echoes](https://scryfall.com/search?q=!archmageofechoes)
- [x] Done -- [Archon of Sun's Grace](https://scryfall.com/search?q=!archonofsunsgrace)
- [x] Done -- [Aura Gnarlid](https://scryfall.com/search?q=!auragnarlid)
- [x] Done -- [Austere Command](https://scryfall.com/search?q=!austerecommand)
- [x] Done -- [Bear Umbra](https://scryfall.com/search?q=!bearumbra)
- [x] Done -- [Blightwing Bandit](https://scryfall.com/search?q=!blightwingbandit)
- [x] Done -- [Bojuka Bog](https://scryfall.com/search?q=!bojukabog)
- [x] Done -- [Brazen Borrower](https://scryfall.com/search?q=!brazenborrower)
- [x] Done -- [Brenard, Ginger Sculptor](https://scryfall.com/search?q=!brenardgingersculptor)
- [x] Done -- [Canopy Vista](https://scryfall.com/search?q=!canopyvista)
- [x] Done -- [Careful Cultivation](https://scryfall.com/search?q=!carefulcultivation)
- [x] Done -- [Castle Ardenvale](https://scryfall.com/search?q=!castleardenvale)
- [x] Done -- [Celestial Archon](https://scryfall.com/search?q=!celestialarchon)
- [x] Done -- [Choked Estuary](https://scryfall.com/search?q=!chokedestuary)
- [x] Done -- [Cloud of Faeries](https://scryfall.com/search?q=!cloudoffaeries)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Consider](https://scryfall.com/search?q=!consider)
- [x] Done -- [Court of Ardenvale](https://scryfall.com/search?q=!courtofardenvale)
- [x] Done -- [Court of Embereth](https://scryfall.com/search?q=!courtofembereth)
- [x] Done -- [Court of Garenbrig](https://scryfall.com/search?q=!courtofgarenbrig)
- [x] Done -- [Court of Vantress](https://scryfall.com/search?q=!courtofvantress)
- [x] Done -- [Danitha Capashen, Paragon](https://scryfall.com/search?q=!danithacapashenparagon)
- [x] Done -- [Darkwater Catacombs](https://scryfall.com/search?q=!darkwatercatacombs)
- [x] Done -- [Daybreak Coronet](https://scryfall.com/search?q=!daybreakcoronet)
- [x] Done -- [Destiny Spinner](https://scryfall.com/search?q=!destinyspinner)
- [x] Done -- [Dig Through Time](https://scryfall.com/search?q=!digthroughtime)
- [x] Done -- [Dimir Aqueduct](https://scryfall.com/search?q=!dimiraqueduct)
- [x] Done -- [Dimir Signet](https://scryfall.com/search?q=!dimirsignet)
- [x] Done -- [Distant Melody](https://scryfall.com/search?q=!distantmelody)
- [x] Done -- [Eidolon of Blossoms](https://scryfall.com/search?q=!eidolonofblossoms)
- [x] Done -- [Eidolon of Countless Battles](https://scryfall.com/search?q=!eidolonofcountlessbattles)
- [x] Done -- [Ellivere of the Wild Court](https://scryfall.com/search?q=!ellivereofthewildcourt)
- [x] Done -- [Enchantress's Presence](https://scryfall.com/search?q=!enchantressspresence)
- [x] Done -- [Ethereal Armor](https://scryfall.com/search?q=!etherealarmor)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Fact or Fiction](https://scryfall.com/search?q=!factorfiction)
- [x] Done -- [Faerie Bladecrafter](https://scryfall.com/search?q=!faeriebladecrafter)
- [x] Done -- [Faerie Conclave](https://scryfall.com/search?q=!faerieconclave)
- [x] Done -- [Faerie Formation](https://scryfall.com/search?q=!faerieformation)
- [x] Done -- [Faerie Seer](https://scryfall.com/search?q=!faerieseer)
- [x] Done -- [Fellwar Stone](https://scryfall.com/search?q=!fellwarstone)
- [x] Done -- [Fertile Ground](https://scryfall.com/search?q=!fertileground)
- [x] Done -- [Fortified Village](https://scryfall.com/search?q=!fortifiedvillage)
- [x] Done -- [Frantic Search](https://scryfall.com/search?q=!franticsearch)
- [x] Done -- [Generous Gift](https://scryfall.com/search?q=!generousgift)
- [x] Done -- [Giant Inheritance](https://scryfall.com/search?q=!giantinheritance)
- [x] Done -- [Glen Elendra Archmage](https://scryfall.com/search?q=!glenelendraarchmage)
- [x] Done -- [Glen Elendra Liege](https://scryfall.com/search?q=!glenelendraliege)
- [x] Done -- [Gylwain, Casting Director](https://scryfall.com/search?q=!gylwaincastingdirector)
- [x] Done -- [Hall of Heliod's Generosity](https://scryfall.com/search?q=!hallofheliodsgenerosity)
- [x] Done -- [Halo Forager](https://scryfall.com/search?q=!haloforager)
- [x] Done -- [Hullbreaker Horror](https://scryfall.com/search?q=!hullbreakerhorror)
- [x] Done -- [Hypnotic Sprite](https://scryfall.com/search?q=!hypnoticsprite)
- [x] Done -- [Illusionist's Gambit](https://scryfall.com/search?q=!illusionistsgambit)
- [x] Done -- [Indomitable Might](https://scryfall.com/search?q=!indomitablemight)
- [x] Done -- [Jukai Naturalist](https://scryfall.com/search?q=!jukainaturalist)
- [x] Done -- [Keep Watch](https://scryfall.com/search?q=!keepwatch)
- [x] Done -- [Kenrith's Transformation](https://scryfall.com/search?q=!kenrithstransformation)
- [x] Done -- [Kindred Dominance](https://scryfall.com/search?q=!kindreddominance)
- [x] Done -- [Knickknack Ouphe](https://scryfall.com/search?q=!knickknackouphe)
- [x] Done -- [Kor Spiritdancer](https://scryfall.com/search?q=!korspiritdancer)
- [x] Done -- [Korvold, Gleeful Glutton](https://scryfall.com/search?q=!korvoldgleefulglutton)
- [x] Done -- [Krosan Verge](https://scryfall.com/search?q=!krosanverge)
- [x] Done -- [Loamcrafter Faun](https://scryfall.com/search?q=!loamcrafterfaun)
- [x] Done -- [Malleable Impostor](https://scryfall.com/search?q=!malleableimpostor)
- [x] Done -- [Mantle of the Ancients](https://scryfall.com/search?q=!mantleoftheancients)
- [x] Done -- [Midnight Clock](https://scryfall.com/search?q=!midnightclock)
- [x] Done -- [Mind Stone](https://scryfall.com/search?q=!mindstone)
- [x] Done -- [Misleading Signpost](https://scryfall.com/search?q=!misleadingsignpost)
- [x] Done -- [Myriad Landscape](https://scryfall.com/search?q=!myriadlandscape)
- [x] Done -- [Nettling Nuisance](https://scryfall.com/search?q=!nettlingnuisance)
- [x] Done -- [Nightmare Unmaking](https://scryfall.com/search?q=!nightmareunmaking)
- [x] Done -- [Nightveil Sprite](https://scryfall.com/search?q=!nightveilsprite)
- [x] Done -- [Nymris, Oona's Trickster](https://scryfall.com/search?q=!nymrisoonastrickster)
- [x] Done -- [Oona, Queen of the Fae](https://scryfall.com/search?q=!oonaqueenofthefae)
- [x] Done -- [Opt](https://scryfall.com/search?q=!opt)
- [x] Done -- [Ox Drover](https://scryfall.com/search?q=!oxdrover)
- [x] Done -- [Paradise Druid](https://scryfall.com/search?q=!paradisedruid)
- [x] Done -- [Path of Ancestry](https://scryfall.com/search?q=!pathofancestry)
- [x] Done -- [Perplexing Test](https://scryfall.com/search?q=!perplexingtest)
- [x] Done -- [Pollenbright Wings](https://scryfall.com/search?q=!pollenbrightwings)
- [x] Done -- [Puppeteer Clique](https://scryfall.com/search?q=!puppeteerclique)
- [x] Done -- [Quickling](https://scryfall.com/search?q=!quickling)
- [x] Done -- [Rankle, Master of Pranks](https://scryfall.com/search?q=!ranklemasterofpranks)
- [x] Done -- [Reality Shift](https://scryfall.com/search?q=!realityshift)
- [x] Done -- [Realm-Cloaked Giant](https://scryfall.com/search?q=!realmcloakedgiant)
- [x] Done -- [Reckless Spite](https://scryfall.com/search?q=!recklessspite)
- [x] Done -- [Reconnaissance Mission](https://scryfall.com/search?q=!reconnaissancemission)
- [x] Done -- [Reflections of Littjara](https://scryfall.com/search?q=!reflectionsoflittjara)
- [x] Done -- [Repulse](https://scryfall.com/search?q=!repulse)
- [x] Done -- [Retether](https://scryfall.com/search?q=!retether)
- [x] Done -- [Rishkar's Expertise](https://scryfall.com/search?q=!rishkarsexpertise)
- [x] Done -- [Run Away Together](https://scryfall.com/search?q=!runawaytogether)
- [x] Done -- [Sage's Reverie](https://scryfall.com/search?q=!sagesreverie)
- [x] Done -- [Sanctum Weaver](https://scryfall.com/search?q=!sanctumweaver)
- [x] Done -- [Scion of Oona](https://scryfall.com/search?q=!scionofoona)
- [x] Done -- [Secluded Glen](https://scryfall.com/search?q=!secludedglen)
- [x] Done -- [Setessan Champion](https://scryfall.com/search?q=!setessanchampion)
- [x] Done -- [Shadow Puppeteers](https://scryfall.com/search?q=!shadowpuppeteers)
- [x] Done -- [Shalai, Voice of Plenty](https://scryfall.com/search?q=!shalaivoiceofplenty)
- [x] Done -- [Siona, Captain of the Pyleas](https://scryfall.com/search?q=!sionacaptainofthepyleas)
- [x] Done -- [Snake Umbra](https://scryfall.com/search?q=!snakeumbra)
- [x] Done -- [Snap](https://scryfall.com/search?q=!snap)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Songbirds' Blessing](https://scryfall.com/search?q=!songbirdsblessing)
- [x] Done -- [Sower of Temptation](https://scryfall.com/search?q=!soweroftemptation)
- [x] Done -- [Spectral Steel](https://scryfall.com/search?q=!spectralsteel)
- [x] Done -- [Starfield Mystic](https://scryfall.com/search?q=!starfieldmystic)
- [x] Done -- [Sun Titan](https://scryfall.com/search?q=!suntitan)
- [x] Done -- [Sungrass Prairie](https://scryfall.com/search?q=!sungrassprairie)
- [x] Done -- [Sunken Hollow](https://scryfall.com/search?q=!sunkenhollow)
- [x] Done -- [Swords to Plowshares](https://scryfall.com/search?q=!swordstoplowshares)
- [x] Done -- [Sylvan Ranger](https://scryfall.com/search?q=!sylvanranger)
- [x] Done -- [Tainted Isle](https://scryfall.com/search?q=!taintedisle)
- [x] Done -- [Talisman of Dominance](https://scryfall.com/search?q=!talismanofdominance)
- [x] Done -- [Tegwyll, Duke of Splendor](https://scryfall.com/search?q=!tegwylldukeofsplendor)
- [x] Done -- [Temple of Deceit](https://scryfall.com/search?q=!templeofdeceit)
- [x] Done -- [Temple of Plenty](https://scryfall.com/search?q=!templeofplenty)
- [x] Done -- [Temple of the False God](https://scryfall.com/search?q=!templeofthefalsegod)
- [x] Done -- [Theoretical Duplication](https://scryfall.com/search?q=!theoreticalduplication)
- [x] Done -- [Thrilling Encore](https://scryfall.com/search?q=!thrillingencore)
- [x] Done -- [Throne of Eldraine](https://scryfall.com/search?q=!throneofeldraine)
- [x] Done -- [Timber Paladin](https://scryfall.com/search?q=!timberpaladin)
- [x] Done -- [Timely Ward](https://scryfall.com/search?q=!timelyward)
- [x] Done -- [Tithe Taker](https://scryfall.com/search?q=!tithetaker)
- [x] Done -- [Transcendent Envoy](https://scryfall.com/search?q=!transcendentenvoy)
- [x] Done -- [Umbra Mystic](https://scryfall.com/search?q=!umbramystic)
- [x] Done -- [Unfinished Business](https://scryfall.com/search?q=!unfinishedbusiness)
- [x] Done -- [Utopia Sprawl](https://scryfall.com/search?q=!utopiasprawl)
- [x] Done -- [Verdant Embrace](https://scryfall.com/search?q=!verdantembrace)
- [x] Done -- [Vitu-Ghazi, the City-Tree](https://scryfall.com/search?q=!vitughazithecitytree)
- [x] Done -- [Warbriar Blessing](https://scryfall.com/search?q=!warbriarblessing)
- [x] Done -- [Wayfarer's Bauble](https://scryfall.com/search?q=!wayfarersbauble)
- [x] Done -- [Winds of Rath](https://scryfall.com/search?q=!windsofrath)
</details>

**Comment by theelk801** [comment]
Additional Tasks:

none yet
