### ISSUE TITLE
LCI - The Lost Caverns of Ixalan Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11238]
This checklist is here to help manage the implementation of The Lost Caverns of Ixalan. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abrade](https://scryfall.com/search?q=!abrade)
- [x] Done -- [Abuelo's Awakening](https://scryfall.com/search?q=!abuelosawakening)
- [x] Done -- [Abuelo, Ancestral Echo](https://scryfall.com/search?q=!abueloancestralecho)
- [x] Done -- [Abyssal Gorestalker](https://scryfall.com/search?q=!abyssalgorestalker)
- [x] Done -- [Aclazotz, Deepest Betrayal](https://scryfall.com/search?q=!aclazotzdeepestbetrayal)
- [x] Done -- [Acolyte of Aclazotz](https://scryfall.com/search?q=!acolyteofaclazotz)
- [x] Done -- [Acrobatic Leap](https://scryfall.com/search?q=!acrobaticleap)
- [x] Done -- [Adaptive Gemguard](https://scryfall.com/search?q=!adaptivegemguard)
- [x] Done -- [Akal Pakal, First Among Equals](https://scryfall.com/search?q=!akalpakalfirstamongequals)
- [x] Done -- [Akawalli, the Seething Tower](https://scryfall.com/search?q=!akawallitheseethingtower)
- [x] Done -- [Amalia Benavides Aguirre](https://scryfall.com/search?q=!amaliabenavidesaguirre)
- [x] Done -- [Ancestors' Aid](https://scryfall.com/search?q=!ancestorsaid)
- [x] Done -- [Ancestral Reminiscence](https://scryfall.com/search?q=!ancestralreminiscence)
- [x] Done -- [Anim Pakal, Thousandth Moon](https://scryfall.com/search?q=!animpakalthousandthmoon)
- [x] Done -- [Another Chance](https://scryfall.com/search?q=!anotherchance)
- [x] Done -- [Armored Kincaller](https://scryfall.com/search?q=!armoredkincaller)
- [x] Done -- [Attentive Sunscribe](https://scryfall.com/search?q=!attentivesunscribe)
- [x] Done -- [Bartolome del Presidio](https://scryfall.com/search?q=!bartolomedelpresidio)
- [x] Done -- [Basking Capybara](https://scryfall.com/search?q=!baskingcapybara)
- [x] Done -- [Bat Colony](https://scryfall.com/search?q=!batcolony)
- [x] Done -- [Bedrock Tortoise](https://scryfall.com/search?q=!bedrocktortoise)
- [x] Done -- [Belligerent Yearling](https://scryfall.com/search?q=!belligerentyearling)
- [x] Done -- [Bitter Triumph](https://scryfall.com/search?q=!bittertriumph)
- [x] Done -- [Bloodletter of Aclazotz](https://scryfall.com/search?q=!bloodletterofaclazotz)
- [x] Done -- [Bloodthorn Flail](https://scryfall.com/search?q=!bloodthornflail)
- [x] Done -- [Bonehoard Dracosaur](https://scryfall.com/search?q=!bonehoarddracosaur)
- [x] Done -- [Brackish Blunder](https://scryfall.com/search?q=!brackishblunder)
- [x] Done -- [Braided Net](https://scryfall.com/search?q=!braidednet)
- [x] Done -- [Brass's Tunnel-Grinder](https://scryfall.com/search?q=!brassstunnelgrinder)
- [x] Done -- [Brazen Blademaster](https://scryfall.com/search?q=!brazenblademaster)
- [x] Done -- [Breeches, Eager Pillager](https://scryfall.com/search?q=!breecheseagerpillager)
- [x] Done -- [Bringer of the Last Gift](https://scryfall.com/search?q=!bringerofthelastgift)
- [x] Done -- [Broodrage Mycoid](https://scryfall.com/search?q=!broodragemycoid)
- [x] Done -- [Buried Treasure](https://scryfall.com/search?q=!buriedtreasure)
- [x] Done -- [Burning Sun Cavalry](https://scryfall.com/search?q=!burningsuncavalry)
- [x] Done -- [Calamitous Cave-In](https://scryfall.com/search?q=!calamitouscavein)
- [x] Done -- [Canonized in Blood](https://scryfall.com/search?q=!canonizedinblood)
- [x] Done -- [Caparocti Sunborn](https://scryfall.com/search?q=!caparoctisunborn)
- [x] Done -- [Captain Storm, Cosmium Raider](https://scryfall.com/search?q=!captainstormcosmiumraider)
- [x] Done -- [Captivating Cave](https://scryfall.com/search?q=!captivatingcave)
- [x] Done -- [Careening Mine Cart](https://scryfall.com/search?q=!careeningminecart)
- [x] Done -- [Cartographer's Companion](https://scryfall.com/search?q=!cartographerscompanion)
- [x] Done -- [Cavern Stomper](https://scryfall.com/search?q=!cavernstomper)
- [x] Done -- [Cavern of Souls](https://scryfall.com/search?q=!cavernofsouls)
- [x] Done -- [Cavernous Maw](https://scryfall.com/search?q=!cavernousmaw)
- [x] Done -- [Cenote Scout](https://scryfall.com/search?q=!cenotescout)
- [x] Done -- [Chart a Course](https://scryfall.com/search?q=!chartacourse)
- [x] Done -- [Child of the Volcano](https://scryfall.com/search?q=!childofthevolcano)
- [x] Done -- [Chimil, the Inner Sun](https://scryfall.com/search?q=!chimiltheinnersun)
- [x] Done -- [Chupacabra Echo](https://scryfall.com/search?q=!chupacabraecho)
- [x] Done -- [Clay-Fired Bricks](https://scryfall.com/search?q=!clayfiredbricks)
- [x] Done -- [Coati Scavenger](https://scryfall.com/search?q=!coatiscavenger)
- [x] Done -- [Cogwork Wrestler](https://scryfall.com/search?q=!cogworkwrestler)
- [x] Done -- [Colossadactyl](https://scryfall.com/search?q=!colossadactyl)
- [x] Done -- [Compass Gnome](https://scryfall.com/search?q=!compassgnome)
- [x] Done -- [Confounding Riddle](https://scryfall.com/search?q=!confoundingriddle)
- [x] Done -- [Contested Game Ball](https://scryfall.com/search?q=!contestedgameball)
- [x] Done -- [Corpses of the Lost](https://scryfall.com/search?q=!corpsesofthelost)
- [x] Done -- [Cosmium Blast](https://scryfall.com/search?q=!cosmiumblast)
- [x] Done -- [Cosmium Confluence](https://scryfall.com/search?q=!cosmiumconfluence)
- [x] Done -- [Council of Echoes](https://scryfall.com/search?q=!councilofechoes)
- [x] Done -- [Curator of Sun's Creation](https://scryfall.com/search?q=!curatorofsunscreation)
- [x] Done -- [Daring Discovery](https://scryfall.com/search?q=!daringdiscovery)
- [x] Done -- [Dauntless Dismantler](https://scryfall.com/search?q=!dauntlessdismantler)
- [x] Done -- [Dead Weight](https://scryfall.com/search?q=!deadweight)
- [x] Done -- [Deathcap Marionette](https://scryfall.com/search?q=!deathcapmarionette)
- [x] Done -- [Deconstruction Hammer](https://scryfall.com/search?q=!deconstructionhammer)
- [x] Done -- [Deep Goblin Skulltaker](https://scryfall.com/search?q=!deepgoblinskulltaker)
- [x] Done -- [Deep-Cavern Bat](https://scryfall.com/search?q=!deepcavernbat)
- [x] Done -- [Deepfathom Echo](https://scryfall.com/search?q=!deepfathomecho)
- [x] Done -- [Deeproot Pilgrimage](https://scryfall.com/search?q=!deeprootpilgrimage)
- [x] Done -- [Defossilize](https://scryfall.com/search?q=!defossilize)
- [x] Done -- [Diamond Pick-Axe](https://scryfall.com/search?q=!diamondpickaxe)
- [x] Done -- [Didact Echo](https://scryfall.com/search?q=!didactecho)
- [x] Done -- [Digsite Conservator](https://scryfall.com/search?q=!digsiteconservator)
- [x] Done -- [Dinotomaton](https://scryfall.com/search?q=!dinotomaton)
- [x] Done -- [Dire Flail](https://scryfall.com/search?q=!direflail)
- [x] Done -- [Disruptor Wanderglyph](https://scryfall.com/search?q=!disruptorwanderglyph)
- [x] Done -- [Disturbed Slumber](https://scryfall.com/search?q=!disturbedslumber)
- [x] Done -- [Dowsing Device](https://scryfall.com/search?q=!dowsingdevice)
- [x] Done -- [Dreadmaw's Ire](https://scryfall.com/search?q=!dreadmawsire)
- [x] Done -- [Dusk Rose Reliquary](https://scryfall.com/search?q=!duskrosereliquary)
- [x] Done -- [Earthshaker Dreadmaw](https://scryfall.com/search?q=!earthshakerdreadmaw)
- [x] Done -- [Eaten by Piranhas](https://scryfall.com/search?q=!eatenbypiranhas)
- [x] Done -- [Echo of Dusk](https://scryfall.com/search?q=!echoofdusk)
- [x] Done -- [Echoing Deeps](https://scryfall.com/search?q=!echoingdeeps)
- [x] Done -- [Enterprising Scallywag](https://scryfall.com/search?q=!enterprisingscallywag)
- [x] Done -- [Envoy of Okinec Ahau](https://scryfall.com/search?q=!envoyofokinecahau)
- [x] Done -- [Etali's Favor](https://scryfall.com/search?q=!etalisfavor)
- [x] Done -- [Explorer's Cache](https://scryfall.com/search?q=!explorerscache)
- [x] Done -- [Fabrication Foundry](https://scryfall.com/search?q=!fabricationfoundry)
- [x] Done -- [Family Reunion](https://scryfall.com/search?q=!familyreunion)
- [x] Done -- [Fanatical Offering](https://scryfall.com/search?q=!fanaticaloffering)
- [x] Done -- [Forgotten Monument](https://scryfall.com/search?q=!forgottenmonument)
- [x] Done -- [Frilled Cave-Wurm](https://scryfall.com/search?q=!frilledcavewurm)
- [x] Done -- [Fungal Fortitude](https://scryfall.com/search?q=!fungalfortitude)
- [x] Done -- [Gargantuan Leech](https://scryfall.com/search?q=!gargantuanleech)
- [x] Done -- [Geological Appraiser](https://scryfall.com/search?q=!geologicalappraiser)
- [x] Done -- [Get Lost](https://scryfall.com/search?q=!getlost)
- [x] Done -- [Ghalta, Stampede Tyrant](https://scryfall.com/search?q=!ghaltastampedetyrant)
- [x] Done -- [Gishath, Sun's Avatar](https://scryfall.com/search?q=!gishathsunsavatar)
- [x] Done -- [Glimpse the Core](https://scryfall.com/search?q=!glimpsethecore)
- [x] Done -- [Glorifier of Suffering](https://scryfall.com/search?q=!glorifierofsuffering)
- [x] Done -- [Glowcap Lantern](https://scryfall.com/search?q=!glowcaplantern)
- [x] Done -- [Goblin Tomb Raider](https://scryfall.com/search?q=!goblintombraider)
- [x] Done -- [Goldfury Strider](https://scryfall.com/search?q=!goldfurystrider)
- [x] Done -- [Grasping Shadows](https://scryfall.com/search?q=!graspingshadows)
- [x] Done -- [Greedy Freebooter](https://scryfall.com/search?q=!greedyfreebooter)
- [x] Done -- [Growing Rites of Itlimoc](https://scryfall.com/search?q=!growingritesofitlimoc)
- [x] Done -- [Guardian of the Great Door](https://scryfall.com/search?q=!guardianofthegreatdoor)
- [x] Done -- [Helping Hand](https://scryfall.com/search?q=!helpinghand)
- [x] Done -- [Hermitic Nautilus](https://scryfall.com/search?q=!hermiticnautilus)
- [x] Done -- [Hidden Cataract](https://scryfall.com/search?q=!hiddencataract)
- [x] Done -- [Hidden Courtyard](https://scryfall.com/search?q=!hiddencourtyard)
- [x] Done -- [Hidden Necropolis](https://scryfall.com/search?q=!hiddennecropolis)
- [x] Done -- [Hidden Nursery](https://scryfall.com/search?q=!hiddennursery)
- [x] Done -- [Hidden Volcano](https://scryfall.com/search?q=!hiddenvolcano)
- [x] Done -- [Hit the Mother Lode](https://scryfall.com/search?q=!hitthemotherlode)
- [x] Done -- [Hotfoot Gnome](https://scryfall.com/search?q=!hotfootgnome)
- [x] Done -- [Hoverstone Pilgrim](https://scryfall.com/search?q=!hoverstonepilgrim)
- [x] Done -- [Huatli's Final Strike](https://scryfall.com/search?q=!huatlisfinalstrike)
- [x] Done -- [Huatli, Poet of Unity](https://scryfall.com/search?q=!huatlipoetofunity)
- [x] Done -- [Hulking Raptor](https://scryfall.com/search?q=!hulkingraptor)
- [x] Done -- [Hunter's Blowgun](https://scryfall.com/search?q=!huntersblowgun)
- [x] Done -- [Hurl into History](https://scryfall.com/search?q=!hurlintohistory)
- [x] Done -- [Idol of the Deep King](https://scryfall.com/search?q=!idolofthedeepking)
- [x] Done -- [In the Presence of Ages](https://scryfall.com/search?q=!inthepresenceofages)
- [x] Done -- [Inti, Seneschal of the Sun](https://scryfall.com/search?q=!intiseneschalofthesun)
- [x] Done -- [Intrepid Paleontologist](https://scryfall.com/search?q=!intrepidpaleontologist)
- [x] Done -- [Inverted Iceberg](https://scryfall.com/search?q=!invertediceberg)
- [x] Done -- [Ironpaw Aspirant](https://scryfall.com/search?q=!ironpawaspirant)
- [x] Done -- [Itzquinth, Firstborn of Gishath](https://scryfall.com/search?q=!itzquinthfirstbornofgishath)
- [x] Done -- [Ixalli's Lorekeeper](https://scryfall.com/search?q=!ixallislorekeeper)
- [x] Done -- [Jade Seedstones](https://scryfall.com/search?q=!jadeseedstones)
- [x] Done -- [Jadelight Spelunker](https://scryfall.com/search?q=!jadelightspelunker)
- [x] Done -- [Join the Dead](https://scryfall.com/search?q=!jointhedead)
- [x] Done -- [Kaslem's Stonetree](https://scryfall.com/search?q=!kaslemsstonetree)
- [x] Done -- [Kellan, Daring Traveler](https://scryfall.com/search?q=!kellandaringtraveler)
- [x] Done -- [Kinjalli's Dawnrunner](https://scryfall.com/search?q=!kinjallisdawnrunner)
- [x] Done -- [Kitesail Larcenist](https://scryfall.com/search?q=!kitesaillarcenist)
- [x] Done -- [Kutzil's Flanker](https://scryfall.com/search?q=!kutzilsflanker)
- [x] Done -- [Kutzil, Malamet Exemplar](https://scryfall.com/search?q=!kutzilmalametexemplar)
- [x] Done -- [Lodestone Needle](https://scryfall.com/search?q=!lodestoneneedle)
- [x] Done -- [Magmatic Galleon](https://scryfall.com/search?q=!magmaticgalleon)
- [x] Done -- [Malamet Battle Glyph](https://scryfall.com/search?q=!malametbattleglyph)
- [x] Done -- [Malamet Brawler](https://scryfall.com/search?q=!malametbrawler)
- [x] Done -- [Malamet Scythe](https://scryfall.com/search?q=!malametscythe)
- [x] Done -- [Malamet Veteran](https://scryfall.com/search?q=!malametveteran)
- [x] Done -- [Malamet War Scribe](https://scryfall.com/search?q=!malametwarscribe)
- [x] Done -- [Malcolm, Alluring Scoundrel](https://scryfall.com/search?q=!malcolmalluringscoundrel)
- [x] Done -- [Malicious Eclipse](https://scryfall.com/search?q=!maliciouseclipse)
- [x] Done -- [Marauding Brinefang](https://scryfall.com/search?q=!maraudingbrinefang)
- [x] Done -- [Market Gnome](https://scryfall.com/search?q=!marketgnome)
- [x] Done -- [Master's Guide-Mural](https://scryfall.com/search?q=!mastersguidemural)
- [x] Done -- [Matzalantli, the Great Door](https://scryfall.com/search?q=!matzalantlithegreatdoor)
- [x] Done -- [Mephitic Draught](https://scryfall.com/search?q=!mephiticdraught)
- [x] Done -- [Merfolk Cave-Diver](https://scryfall.com/search?q=!merfolkcavediver)
- [x] Done -- [Might of the Ancestors](https://scryfall.com/search?q=!mightoftheancestors)
- [x] Done -- [Miner's Guidewing](https://scryfall.com/search?q=!minersguidewing)
- [x] Done -- [Mineshaft Spider](https://scryfall.com/search?q=!mineshaftspider)
- [x] Done -- [Mischievous Pup](https://scryfall.com/search?q=!mischievouspup)
- [x] Done -- [Molten Collapse](https://scryfall.com/search?q=!moltencollapse)
- [x] Done -- [Nicanzil, Current Conductor](https://scryfall.com/search?q=!nicanzilcurrentconductor)
- [x] Done -- [Nurturing Bristleback](https://scryfall.com/search?q=!nurturingbristleback)
- [x] Done -- [Oaken Siren](https://scryfall.com/search?q=!oakensiren)
- [x] Done -- [Ojer Axonil, Deepest Might](https://scryfall.com/search?q=!ojeraxonildeepestmight)
- [x] Done -- [Ojer Kaslem, Deepest Growth](https://scryfall.com/search?q=!ojerkaslemdeepestgrowth)
- [x] Done -- [Ojer Pakpatiq, Deepest Epoch](https://scryfall.com/search?q=!ojerpakpatiqdeepestepoch)
- [x] Done -- [Ojer Taq, Deepest Foundation](https://scryfall.com/search?q=!ojertaqdeepestfoundation)
- [x] Done -- [Oltec Archaeologists](https://scryfall.com/search?q=!oltecarchaeologists)
- [x] Done -- [Oltec Cloud Guard](https://scryfall.com/search?q=!olteccloudguard)
- [x] Done -- [Orazca Puzzle-Door](https://scryfall.com/search?q=!orazcapuzzledoor)
- [x] Done -- [Oteclan Landmark](https://scryfall.com/search?q=!oteclanlandmark)
- [x] Done -- [Out of Air](https://scryfall.com/search?q=!outofair)
- [x] Done -- [Over the Edge](https://scryfall.com/search?q=!overtheedge)
- [x] Done -- [Palani's Hatcher](https://scryfall.com/search?q=!palanishatcher)
- [x] Done -- [Panicked Altisaur](https://scryfall.com/search?q=!panickedaltisaur)
- [x] Done -- [Pathfinding Axejaw](https://scryfall.com/search?q=!pathfindingaxejaw)
- [x] Done -- [Petrify](https://scryfall.com/search?q=!petrify)
- [x] Done -- [Pirate Hat](https://scryfall.com/search?q=!piratehat)
- [x] Done -- [Pit of Offerings](https://scryfall.com/search?q=!pitofofferings)
- [x] Done -- [Plundering Pirate](https://scryfall.com/search?q=!plunderingpirate)
- [x] Done -- [Poetic Ingenuity](https://scryfall.com/search?q=!poeticingenuity)
- [x] Done -- [Poison Dart Frog](https://scryfall.com/search?q=!poisondartfrog)
- [x] Done -- [Preacher of the Schism](https://scryfall.com/search?q=!preacheroftheschism)
- [x] Done -- [Primordial Gnawer](https://scryfall.com/search?q=!primordialgnawer)
- [x] Done -- [Promising Vein](https://scryfall.com/search?q=!promisingvein)
- [x] Done -- [Pugnacious Hammerskull](https://scryfall.com/search?q=!pugnacioushammerskull)
- [x] Done -- [Queen's Bay Paladin](https://scryfall.com/search?q=!queensbaypaladin)
- [x] Done -- [Quicksand Whirlpool](https://scryfall.com/search?q=!quicksandwhirlpool)
- [x] Done -- [Quintorius Kand](https://scryfall.com/search?q=!quintoriuskand)
- [x] Done -- [Rampaging Ceratops](https://scryfall.com/search?q=!rampagingceratops)
- [x] Done -- [Rampaging Spiketail](https://scryfall.com/search?q=!rampagingspiketail)
- [x] Done -- [Ray of Ruin](https://scryfall.com/search?q=!rayofruin)
- [x] Done -- [Relic's Roar](https://scryfall.com/search?q=!relicsroar)
- [x] Done -- [Resplendent Angel](https://scryfall.com/search?q=!resplendentangel)
- [x] Done -- [Restless Anchorage](https://scryfall.com/search?q=!restlessanchorage)
- [x] Done -- [Restless Prairie](https://scryfall.com/search?q=!restlessprairie)
- [x] Done -- [Restless Reef](https://scryfall.com/search?q=!restlessreef)
- [x] Done -- [Restless Ridgeline](https://scryfall.com/search?q=!restlessridgeline)
- [x] Done -- [Restless Vents](https://scryfall.com/search?q=!restlessvents)
- [x] Done -- [River Herald Guide](https://scryfall.com/search?q=!riverheraldguide)
- [x] Done -- [River Herald Scout](https://scryfall.com/search?q=!riverheraldscout)
- [x] Done -- [Roaming Throne](https://scryfall.com/search?q=!roamingthrone)
- [x] Done -- [Ruin-Lurker Bat](https://scryfall.com/search?q=!ruinlurkerbat)
- [x] Done -- [Rumbling Rockslide](https://scryfall.com/search?q=!rumblingrockslide)
- [x] Done -- [Runaway Boulder](https://scryfall.com/search?q=!runawayboulder)
- [x] Done -- [Sage of Days](https://scryfall.com/search?q=!sageofdays)
- [x] Done -- [Saheeli's Lattice](https://scryfall.com/search?q=!saheelislattice)
- [x] Done -- [Saheeli, the Sun's Brilliance](https://scryfall.com/search?q=!saheelithesunsbrilliance)
- [x] Done -- [Sanguine Evangelist](https://scryfall.com/search?q=!sanguineevangelist)
- [x] Done -- [Scampering Surveyor](https://scryfall.com/search?q=!scamperingsurveyor)
- [x] Done -- [Screaming Phantom](https://scryfall.com/search?q=!screamingphantom)
- [x] Done -- [Scytheclaw Raptor](https://scryfall.com/search?q=!scytheclawraptor)
- [x] Done -- [Seeker of Sunlight](https://scryfall.com/search?q=!seekerofsunlight)
- [x] Done -- [Seismic Monstrosaur](https://scryfall.com/search?q=!seismicmonstrosaur)
- [x] Done -- [Self-Reflection](https://scryfall.com/search?q=!selfreflection)
- [x] Done -- [Sentinel of the Nameless City](https://scryfall.com/search?q=!sentinelofthenamelesscity)
- [x] Done -- [Shipwreck Sentry](https://scryfall.com/search?q=!shipwrecksentry)
- [x] Done -- [Sinuous Benthisaur](https://scryfall.com/search?q=!sinuousbenthisaur)
- [x] Done -- [Skullcap Snail](https://scryfall.com/search?q=!skullcapsnail)
- [x] Done -- [Soaring Sandwing](https://scryfall.com/search?q=!soaringsandwing)
- [x] Done -- [Song of Stupefaction](https://scryfall.com/search?q=!songofstupefaction)
- [x] Done -- [Sorcerous Spyglass](https://scryfall.com/search?q=!sorcerousspyglass)
- [x] Done -- [Soulcoil Viper](https://scryfall.com/search?q=!soulcoilviper)
- [x] Done -- [Souls of the Lost](https://scryfall.com/search?q=!soulsofthelost)
- [x] Done -- [Sovereign Okinec Ahau](https://scryfall.com/search?q=!sovereignokinecahau)
- [x] Done -- [Spelunking](https://scryfall.com/search?q=!spelunking)
- [x] Done -- [Spring-Loaded Sawblades](https://scryfall.com/search?q=!springloadedsawblades)
- [x] Done -- [Spyglass Siren](https://scryfall.com/search?q=!spyglasssiren)
- [x] Done -- [Squirming Emergence](https://scryfall.com/search?q=!squirmingemergence)
- [x] Done -- [Staggering Size](https://scryfall.com/search?q=!staggeringsize)
- [x] Done -- [Stalactite Stalker](https://scryfall.com/search?q=!stalactitestalker)
- [x] Done -- [Starving Revenant](https://scryfall.com/search?q=!starvingrevenant)
- [x] Done -- [Staunch Crewmate](https://scryfall.com/search?q=!staunchcrewmate)
- [x] Done -- [Stinging Cave Crawler](https://scryfall.com/search?q=!stingingcavecrawler)
- [x] Done -- [Subterranean Schooner](https://scryfall.com/search?q=!subterraneanschooner)
- [x] Done -- [Sunbird Standard](https://scryfall.com/search?q=!sunbirdstandard)
- [x] Done -- [Sunfire Torch](https://scryfall.com/search?q=!sunfiretorch)
- [x] Done -- [Sunken Citadel](https://scryfall.com/search?q=!sunkencitadel)
- [x] Done -- [Sunshot Militia](https://scryfall.com/search?q=!sunshotmilitia)
- [x] Done -- [Swashbuckler's Whip](https://scryfall.com/search?q=!swashbucklerswhip)
- [x] Done -- [Synapse Necromage](https://scryfall.com/search?q=!synapsenecromage)
- [x] Done -- [Tarrian's Journal](https://scryfall.com/search?q=!tarriansjournal)
- [x] Done -- [Tarrian's Soulcleaver](https://scryfall.com/search?q=!tarrianssoulcleaver)
- [x] Done -- [Tectonic Hazard](https://scryfall.com/search?q=!tectonichazard)
- [x] Done -- [Tendril of the Mycotyrant](https://scryfall.com/search?q=!tendrilofthemycotyrant)
- [x] Done -- [Terror Tide](https://scryfall.com/search?q=!terrortide)
- [x] Done -- [The Ancient One](https://scryfall.com/search?q=!theancientone)
- [x] Done -- [The Belligerent](https://scryfall.com/search?q=!thebelligerent)
- [x] Done -- [The Enigma Jewel](https://scryfall.com/search?q=!theenigmajewel)
- [x] Done -- [The Everflowing Well](https://scryfall.com/search?q=!theeverflowingwell)
- [x] Done -- [The Millennium Calendar](https://scryfall.com/search?q=!themillenniumcalendar)
- [x] Done -- [The Mycotyrant](https://scryfall.com/search?q=!themycotyrant)
- [x] Done -- [The Skullspore Nexus](https://scryfall.com/search?q=!theskullsporenexus)
- [x] Done -- [Thousand Moons Crackshot](https://scryfall.com/search?q=!thousandmoonscrackshot)
- [x] Done -- [Thousand Moons Infantry](https://scryfall.com/search?q=!thousandmoonsinfantry)
- [x] Done -- [Thousand Moons Smithy](https://scryfall.com/search?q=!thousandmoonssmithy)
- [x] Done -- [Thrashing Brontodon](https://scryfall.com/search?q=!thrashingbrontodon)
- [x] Done -- [Threefold Thunderhulk](https://scryfall.com/search?q=!threefoldthunderhulk)
- [x] Done -- [Throne of the Grim Captain](https://scryfall.com/search?q=!throneofthegrimcaptain)
- [x] Done -- [Tinker's Tote](https://scryfall.com/search?q=!tinkerstote)
- [x] Done -- [Tishana's Tidebinder](https://scryfall.com/search?q=!tishanastidebinder)
- [x] Done -- [Tithing Blade](https://scryfall.com/search?q=!tithingblade)
- [x] Done -- [Treasure Map](https://scryfall.com/search?q=!treasuremap)
- [x] Done -- [Triumphant Chomp](https://scryfall.com/search?q=!triumphantchomp)
- [x] Done -- [Trumpeting Carnosaur](https://scryfall.com/search?q=!trumpetingcarnosaur)
- [x] Done -- [Twists and Turns](https://scryfall.com/search?q=!twistsandturns)
- [x] Done -- [Uchbenbak, the Great Mistake](https://scryfall.com/search?q=!uchbenbakthegreatmistake)
- [x] Done -- [Unlucky Drop](https://scryfall.com/search?q=!unluckydrop)
- [x] Done -- [Unstable Glyphbridge](https://scryfall.com/search?q=!unstableglyphbridge)
- [x] Done -- [Vanguard of the Rose](https://scryfall.com/search?q=!vanguardoftherose)
- [x] Done -- [Visage of Dread](https://scryfall.com/search?q=!visageofdread)
- [x] Done -- [Vito's Inquisitor](https://scryfall.com/search?q=!vitosinquisitor)
- [x] Done -- [Vito, Fanatic of Aclazotz](https://scryfall.com/search?q=!vitofanaticofaclazotz)
- [x] Done -- [Volatile Fault](https://scryfall.com/search?q=!volatilefault)
- [x] Done -- [Volatile Wanderglyph](https://scryfall.com/search?q=!volatilewanderglyph)
- [x] Done -- [Wail of the Forgotten](https://scryfall.com/search?q=!wailoftheforgotten)
- [x] Done -- [Walk with the Ancestors](https://scryfall.com/search?q=!walkwiththeancestors)
- [x] Done -- [Warden of the Inner Sky](https://scryfall.com/search?q=!wardenoftheinnersky)
- [x] Done -- [Waterlogged Hulk](https://scryfall.com/search?q=!waterloggedhulk)
- [x] Done -- [Waterwind Scout](https://scryfall.com/search?q=!waterwindscout)
- [x] Done -- [Waylaying Pirates](https://scryfall.com/search?q=!waylayingpirates)
- [x] Done -- [Zoetic Glyph](https://scryfall.com/search?q=!zoeticglyph)
- [x] Done -- [Zoyowa Lava-Tongue](https://scryfall.com/search?q=!zoyowalavatongue)
- [x] Done -- [Zoyowa's Justice](https://scryfall.com/search?q=!zoyowasjustice)
</details>

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by xenohedron** [comment]
https://magic.wizards.com/en/news/feature/the-lost-caverns-of-ixalan-mechanics

**Comment by Susucre** [comment]
I have ideas on how to implement Craft with, but haven't started on that if anyone wants to do it.

Probably will introduce `CraftWithCost` to set up the different use cases.
For now we know of the possibilities:
- `craft with A`
- `craft with a A, a B, a C and a D` (4 different CraftWithCost, one for each)
- `craft with N or more A` (one Cost with the N in its constructor)

**Comment by theelk801** [comment]
we're gonna want to pass in a target class that targets both permanents and cards in graveyards

**Comment by Susucre** [comment]
@theelk801 LCI is all done. Time to add all the special version.
