### ISSUE TITLE
REX - Jurassic World Collection Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11240]
This checklist is here to help manage the implementation of Jurassic World Collection. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Blue, Loyal Raptor](https://scryfall.com/search?q=!blueloyalraptor)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Compy Swarm](https://scryfall.com/search?q=!compyswarm)
- [x] Done -- [Cresting Mosasaurus](https://scryfall.com/search?q=!crestingmosasaurus)
- [x] Done -- [Dino DNA](https://scryfall.com/search?q=!dinodna)
- [x] Done -- [Don't Move](https://scryfall.com/search?q=!dontmove)
- [x] Done -- [Ellie and Alan, Paleontologists](https://scryfall.com/search?q=!ellieandalanpaleontologists)
- [x] Done -- [Grim Giganotosaurus](https://scryfall.com/search?q=!grimgiganotosaurus)
- [x] Done -- [Henry Wu, InGen Geneticist](https://scryfall.com/search?q=!henrywuingengeneticist)
- [x] Done -- [Hunting Velociraptor](https://scryfall.com/search?q=!huntingvelociraptor)
- [x] Done -- [Ian Malcolm, Chaotician](https://scryfall.com/search?q=!ianmalcolmchaotician)
- [x] Done -- [Indominus Rex, Alpha](https://scryfall.com/search?q=!indominusrexalpha)
- [x] Done -- [Indoraptor, the Perfect Hybrid](https://scryfall.com/search?q=!indoraptortheperfecthybrid)
- [x] Done -- [Life Finds a Way](https://scryfall.com/search?q=!lifefindsaway)
- [x] Done -- [Owen Grady, Raptor Trainer](https://scryfall.com/search?q=!owengradyraptortrainer)
- [x] Done -- [Permission Denied](https://scryfall.com/search?q=!permissiondenied)
- [x] Done -- [Ravenous Tyrannosaurus](https://scryfall.com/search?q=!ravenoustyrannosaurus)
- [x] Done -- [Savage Order](https://scryfall.com/search?q=!savageorder)
- [x] Done -- [Spitting Dilophosaurus](https://scryfall.com/search?q=!spittingdilophosaurus)
- [x] Done -- [Swooping Pteranodon](https://scryfall.com/search?q=!swoopingpteranodon)
- [x] Done -- [Welcome to . . .](https://scryfall.com/search?q=!welcometo)
</details>

**Comment by jimga150** [comment]
Working on [Hunting Velociraptor](https://scryfall.com/search?q=!huntingvelociraptor)

**Comment by jimga150** [comment]
Taking on [Dino DNA](https://scryfall.com/search?q=!dinodna)

**Comment by jimga150** [comment]
Working on [Owen Grady, Raptor Trainer](https://scryfall.com/search?q=!owengradyraptortrainer)

**Comment by jimga150** [comment]
Working on [Cresting Mosasaurus](https://scryfall.com/search?q=!crestingmosasaurus)

**Comment by jimga150** [comment]
Working on [Grim Giganotosaurus](https://scryfall.com/search?q=!grimgiganotosaurus)

**Comment by jimga150** [comment]
Working on [Henry Wu, InGen Geneticist](https://scryfall.com/search?q=!henrywuingengeneticist)

**Comment by jimga150** [comment]
Working on [Ian Malcolm, Chaotician](https://scryfall.com/search?q=!ianmalcolmchaotician)

**Comment by jimga150** [comment]
Working on [Indominus Rex, Alpha](https://scryfall.com/search?q=!indominusrexalpha)
