### ISSUE TITLE
Tracking for not yet implemented cards from very old sets.

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11320]
This is for old cards that do not have tracking set issues.
This list voluntarily excludes Ante cards (#11319), and text changing cards (#2082).

As a note, the cards may have been reprinted in other sets.

- [ ] [LEA][Illusionary Mask](https://scryfall.com/card/lea/249/illusionary-mask)
- [ ] [LEG][Falling Star](https://scryfall.com/card/leg/145/falling-star) -- with an errata to not have dexterity involved. See Chaos Orb current implementation.
- [ ] [LEG][Equinox](https://scryfall.com/card/leg/13/equinox)
- [ ] [LEG][Silhouette](https://scryfall.com/card/leg/77/silhouette)
- [ ] [LEG][Takklemaggot](https://scryfall.com/card/leg/119/takklemaggot)
- [ ] [LEG][Backdraft](https://scryfall.com/card/leg/132/backdraft)
- [ ] [LEG][Firestorm Phoenix](https://scryfall.com/card/leg/147/firestorm-phoenix)
- [ ] [LEG][Quarum Trench Gnomes](https://scryfall.com/card/leg/162/quarum-trench-gnomes)
- [ ] [LEG][North Star](https://scryfall.com/card/leg/288/north-star)
- [ ] [DRK][Frankenstein's Monster](https://scryfall.com/card/drk/45/frankensteins-monster)
- [ ] [DRK][Whippoorwill](https://scryfall.com/card/drk/91/whippoorwill)
- [ ] [DRK][Reflecting Mirror](https://scryfall.com/card/drk/106/reflecting-mirror)
- [ ] [PHPR][Sewers of Estark](https://scryfall.com/card/phpr/2/sewers-of-estark)
