### ISSUE TITLE
PIP - Fallout Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11324]
This checklist is here to help manage the implementation of Fallout. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Alpha Deathclaw](https://scryfall.com/search?q=!alphadeathclaw)
- [ ] In progress -- [Caesar, Legion's Emperor](https://scryfall.com/search?q=!caesarlegionsemperor)
- [ ] In progress -- [Dogmeat, Ever Loyal](https://scryfall.com/search?q=!dogmeateverloyal)
- [ ] In progress -- [Feral Ghoul](https://scryfall.com/search?q=!feralghoul)
- [ ] In progress -- [Idolized](https://scryfall.com/search?q=!idolized)
- [ ] In progress -- [Mr. House, President and CEO](https://scryfall.com/search?q=!mrhousepresidentandceo)
- [ ] In progress -- [Overencumbered](https://scryfall.com/search?q=!overencumbered)
- [ ] In progress -- [Rex, Cyber-Hound](https://scryfall.com/search?q=!rexcyberhound)
- [ ] In progress -- [The Wise Mothman](https://scryfall.com/search?q=!thewisemothman)
- [ ] In progress -- [V.A.T.S.](https://scryfall.com/search?q=!vats)
- [ ] In progress -- [Vault 101: Birthday Party](https://scryfall.com/search?q=!vault101birthdayparty)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"AlphaDeathclaw"or!"CaesarLegionsEmperor"or!"DogmeatEverLoyal"or!"FeralGhoul"or!"Idolized"or!"MrHousePresidentAndCEO"or!"Overencumbered"or!"RexCyberHound"or!"TheWiseMothman"or!"VATS"or!"Vault101BirthdayParty"&unique=cards)
# Implemented Cards

- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Crucible of Worlds](https://scryfall.com/search?q=!crucibleofworlds)
- [x] Done -- [Dr. Madison Li](https://scryfall.com/search?q=!drmadisonli)
- [x] Done -- [Gary Clone](https://scryfall.com/search?q=!garyclone)
- [x] Done -- [Intelligence Bobblehead](https://scryfall.com/search?q=!intelligencebobblehead)
- [x] Done -- [Nuka-Cola Vending Machine](https://scryfall.com/search?q=!nukacolavendingmachine)
- [x] Done -- [Radstorm](https://scryfall.com/search?q=!radstorm)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Wasteland](https://scryfall.com/search?q=!wasteland)

**Comment by theelk801** [comment]
Additional Tasks:

- [ ] Implement rad counter mechanic

**Comment by jimga150** [comment]
Working on [Mr. House, President and CEO](https://scryfall.com/search?q=!mrhousepresidentandceo)

**Comment by Cguy7777** [comment]
Working on Expert-Level Safe

**Comment by Susucre** [comment]
I've started work on Rad Counter mechanics.
It is quite the wild one with the "inherent triggered ability without source".

**Comment by spcphd1976** [comment]
Can't wait for the full bobblehead set. They are relatively weak without each other.

**Comment by AyuDiego** [comment]
The Wise Mothman appears in Implemented Cards but in the game no appear

**Comment by Grath** [comment]
> The Wise Mothman appears in Implemented Cards but in the game no appear

It requires Radiation counters, which weren't implemented until shortly after the latest release. It'll be available in the next release, whenever that happens.

**Comment by AyuDiego** [comment]
> shortly

Ah okay, I installed the latest beta today and I thought that I had it but no problem. Thanks for the info

**Comment by JacoLoco** [comment]
Some of the implemented cards like "Desdemona, Freedom's Edge" or "Diamond city" are disappared... Can you help?

And if you will implement Aradesh, Mysterius Stranger, Paladin Elizabeth, Rose, Vault 11, Wild Wasteland, and Yes man....
 That would be grate.. . . TNKS!"

**Comment by Grath** [comment]
Not disappeared - those were both implemented since the last Beta update.

**Comment by JacoLoco** [comment]
Does they appear to you? Even Vault 87 doesn't appear to me.

**Comment by Grath** [comment]
Vault 87 was also implemented since the last update. JayDi has been working hard on a bunch of GUI improvements, hopefully there will be a new release soon and all of the cards marked as currently implemented will be available when that happens. If you can't wait, you can try https://alpha-xmage.net/ which is much more recent than the beta, but still about two weeks out of date.

**Comment by JacoLoco** [comment]
Yeah, i've seen that they were was also implemented since the last update. But theese three i can't find.. "Desdemona, Freedom's Edge", "Diamond city", "Vault 87" . Do You see them?

**Comment by Grath** [comment]
I already told you those cards will be available after the next update. They don't magically appear as soon as they're implemented, the majority of each update is the inclusion of the cards which have been implemented since the last update.

**Comment by JacoLoco** [comment]
I was believing that the implemented one was already in the current beta... and the unimplemented - "in progress" are the one that will gonna be added.

So then, it's a coincidence that the vast majority of the Implemented Cards are present and visible in the research?
And this means that they were included in past beta updates and so  then "Desdemona, Freedom's Edge", "Diamond city", "Vault 87" still not and they have to pass thru that?

**Comment by Grath** [comment]
The current beta release was made on June 6th. Rose and Diamond City were implemented on June 16th in #12482, Vault 87 was implemented on July 7th in #12560, and Desdemona was implemented on July 8th in #12565. Because time is linear, these cards are not available in the current beta. They will be available in the next beta, or they are currently available in the alpha. Please refrain from further spam on this issue because you are unable to understand what "those cards were implemented since the last beta release and will be available in the next release" means despite having been told that three times now.

**Comment by JacoLoco** [comment]
So tell me how do i know that for some card the date of implementation is different from the others in the "implemented" group? I'm not inside all the post, there is no chart referring to time and date of implementing. Didn't saw that.
Beside that, is not spam to aks a thing that is unclear. Linear, isn't?

**Comment by JayDi85** [comment]
@JacoLoco it's fast information topic and can be outdated. Actual info can be found by repository search (if you enter card name then can find many useful info).

Unimplemented card example:
![shot_240816_205517](https://github.com/user-attachments/assets/40441e8c-1aaa-447a-a4d2-ce59390c7542)
![shot_240816_205543](https://github.com/user-attachments/assets/e70a6c08-b988-468f-9a22-46dc7714d955)
![shot_240816_205624](https://github.com/user-attachments/assets/5f8adfc1-fe7e-4303-aaff-b7ffbf5d4fe2)

Implemented card example:
![shot_240816_205724](https://github.com/user-attachments/assets/c61a1023-bd69-455e-ae7b-05c6bcbff3b9)

**Comment by xenohedron** [comment]
All cards are implemented
