### ISSUE TITLE
CLU - Ravnica: Clue Edition Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11517]
This checklist is here to help manage the implementation of Ravnica: Clue. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards

- [x] Done -- [Dining Room](https://scryfall.com/search?q=!diningroom)
- [x] Done -- [Hallowed Fountain](https://scryfall.com/search?q=!hallowedfountain)
- [x] Done -- [Lead Pipe](https://scryfall.com/search?q=!leadpipe)
- [x] Done -- [Steam Vents](https://scryfall.com/search?q=!steamvents)

**Comment by theelk801** [comment]
additional tasks:

none yet

**Comment by Cguy7777** [comment]
Working on Wrench

**Comment by Cguy7777** [comment]
Working on Aegis of the Legion, Candlestick, and Rope

**Comment by Sidorovich77** [comment]
I've implemented Apothecary White and Emissary Green.
#12642

**Comment by jimga150** [comment]
Working on [Amzu, Swarm's Hunger](https://scryfall.com/search?q=!amzuswarmshunger)
