### ISSUE TITLE
MKM - Murders at Karlov Manor Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11516]
This checklist is here to help manage the implementation of Murders at Karlov Manor. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [A Killer Among Us](https://scryfall.com/search?q=!akilleramongus)
- [x] Done -- [Absolving Lammasu](https://scryfall.com/search?q=!absolvinglammasu)
- [x] Done -- [Aftermath Analyst](https://scryfall.com/search?q=!aftermathanalyst)
- [x] Done -- [Agency Coroner](https://scryfall.com/search?q=!agencycoroner)
- [x] Done -- [Agency Outfitter](https://scryfall.com/search?q=!agencyoutfitter)
- [x] Done -- [Agrus Kos, Spirit of Justice](https://scryfall.com/search?q=!agruskosspiritofjustice)
- [x] Done -- [Airtight Alibi](https://scryfall.com/search?q=!airtightalibi)
- [x] Done -- [Alley Assailant](https://scryfall.com/search?q=!alleyassailant)
- [x] Done -- [Alquist Proft, Master Sleuth](https://scryfall.com/search?q=!alquistproftmastersleuth)
- [x] Done -- [Analyze the Pollen](https://scryfall.com/search?q=!analyzethepollen)
- [x] Done -- [Anzrag's Rampage](https://scryfall.com/search?q=!anzragsrampage)
- [x] Done -- [Anzrag, the Quake-Mole](https://scryfall.com/search?q=!anzragthequakemole)
- [x] Done -- [Archdruid's Charm](https://scryfall.com/search?q=!archdruidscharm)
- [x] Done -- [Assassin's Trophy](https://scryfall.com/search?q=!assassinstrophy)
- [x] Done -- [Assemble the Players](https://scryfall.com/search?q=!assembletheplayers)
- [x] Done -- [Audience with Trostani](https://scryfall.com/search?q=!audiencewithtrostani)
- [x] Done -- [Aurelia's Vindicator](https://scryfall.com/search?q=!aureliasvindicator)
- [x] Done -- [Aurelia, the Law Above](https://scryfall.com/search?q=!aureliathelawabove)
- [x] Done -- [Auspicious Arrival](https://scryfall.com/search?q=!auspiciousarrival)
- [x] Done -- [Axebane Ferox](https://scryfall.com/search?q=!axebaneferox)
- [x] Done -- [Barbed Servitor](https://scryfall.com/search?q=!barbedservitor)
- [x] Done -- [Basilica Stalker](https://scryfall.com/search?q=!basilicastalker)
- [x] Done -- [Behind the Mask](https://scryfall.com/search?q=!behindthemask)
- [x] Done -- [Benthic Criminologists](https://scryfall.com/search?q=!benthiccriminologists)
- [x] Done -- [Bite Down on Crime](https://scryfall.com/search?q=!bitedownoncrime)
- [x] Done -- [Blood Spatter Analysis](https://scryfall.com/search?q=!bloodspatteranalysis)
- [x] Done -- [Bolrac-Clan Basher](https://scryfall.com/search?q=!bolracclanbasher)
- [x] Done -- [Branch of Vitu-Ghazi](https://scryfall.com/search?q=!branchofvitughazi)
- [x] Done -- [Break Out](https://scryfall.com/search?q=!breakout)
- [x] Done -- [Bubble Smuggler](https://scryfall.com/search?q=!bubblesmuggler)
- [x] Done -- [Burden of Proof](https://scryfall.com/search?q=!burdenofproof)
- [x] Done -- [Buried in the Garden](https://scryfall.com/search?q=!buriedinthegarden)
- [x] Done -- [Call a Surprise Witness](https://scryfall.com/search?q=!callasurprisewitness)
- [x] Done -- [Candlestick](https://scryfall.com/search?q=!candlestick)
- [x] Done -- [Case File Auditor](https://scryfall.com/search?q=!casefileauditor)
- [x] Done -- [Case of the Burning Masks](https://scryfall.com/search?q=!caseoftheburningmasks)
- [x] Done -- [Case of the Crimson Pulse](https://scryfall.com/search?q=!caseofthecrimsonpulse)
- [x] Done -- [Case of the Filched Falcon](https://scryfall.com/search?q=!caseofthefilchedfalcon)
- [x] Done -- [Case of the Gateway Express](https://scryfall.com/search?q=!caseofthegatewayexpress)
- [x] Done -- [Case of the Gorgon's Kiss](https://scryfall.com/search?q=!caseofthegorgonskiss)
- [x] Done -- [Case of the Locked Hothouse](https://scryfall.com/search?q=!caseofthelockedhothouse)
- [x] Done -- [Case of the Pilfered Proof](https://scryfall.com/search?q=!caseofthepilferedproof)
- [x] Done -- [Case of the Ransacked Lab](https://scryfall.com/search?q=!caseoftheransackedlab)
- [x] Done -- [Case of the Shattered Pact](https://scryfall.com/search?q=!caseoftheshatteredpact)
- [x] Done -- [Case of the Stashed Skeleton](https://scryfall.com/search?q=!caseofthestashedskeleton)
- [x] Done -- [Case of the Trampled Garden](https://scryfall.com/search?q=!caseofthetrampledgarden)
- [x] Done -- [Case of the Uneaten Feast](https://scryfall.com/search?q=!caseoftheuneatenfeast)
- [x] Done -- [Caught Red-Handed](https://scryfall.com/search?q=!caughtredhanded)
- [x] Done -- [Cease // Desist](https://scryfall.com/search?q=!ceasedesist)
- [x] Done -- [Cerebral Confiscation](https://scryfall.com/search?q=!cerebralconfiscation)
- [x] Done -- [Chalk Outline](https://scryfall.com/search?q=!chalkoutline)
- [x] Done -- [Clandestine Meddler](https://scryfall.com/search?q=!clandestinemeddler)
- [x] Done -- [Coerced to Kill](https://scryfall.com/search?q=!coercedtokill)
- [x] Done -- [Cold Case Cracker](https://scryfall.com/search?q=!coldcasecracker)
- [x] Done -- [Commercial District](https://scryfall.com/search?q=!commercialdistrict)
- [x] Done -- [Concealed Weapon](https://scryfall.com/search?q=!concealedweapon)
- [x] Done -- [Connecting the Dots](https://scryfall.com/search?q=!connectingthedots)
- [x] Done -- [Conspiracy Unraveler](https://scryfall.com/search?q=!conspiracyunraveler)
- [x] Done -- [Convenient Target](https://scryfall.com/search?q=!convenienttarget)
- [x] Done -- [Cornered Crook](https://scryfall.com/search?q=!corneredcrook)
- [x] Done -- [Coveted Falcon](https://scryfall.com/search?q=!covetedfalcon)
- [x] Done -- [Crime Novelist](https://scryfall.com/search?q=!crimenovelist)
- [x] Done -- [Crimestopper Sprite](https://scryfall.com/search?q=!crimestoppersprite)
- [x] Done -- [Crowd-Control Warden](https://scryfall.com/search?q=!crowdcontrolwarden)
- [x] Done -- [Cryptex](https://scryfall.com/search?q=!cryptex)
- [x] Done -- [Cryptic Coat](https://scryfall.com/search?q=!crypticcoat)
- [x] Done -- [Culvert Ambusher](https://scryfall.com/search?q=!culvertambusher)
- [x] Done -- [Curious Cadaver](https://scryfall.com/search?q=!curiouscadaver)
- [x] Done -- [Curious Inquiry](https://scryfall.com/search?q=!curiousinquiry)
- [x] Done -- [Deadly Complication](https://scryfall.com/search?q=!deadlycomplication)
- [x] Done -- [Deadly Cover-Up](https://scryfall.com/search?q=!deadlycoverup)
- [x] Done -- [Deduce](https://scryfall.com/search?q=!deduce)
- [x] Done -- [Defenestrated Phantom](https://scryfall.com/search?q=!defenestratedphantom)
- [x] Done -- [Delney, Streetwise Lookout](https://scryfall.com/search?q=!delneystreetwiselookout)
- [x] Done -- [Demand Answers](https://scryfall.com/search?q=!demandanswers)
- [x] Done -- [Detective's Satchel](https://scryfall.com/search?q=!detectivessatchel)
- [x] Done -- [Dog Walker](https://scryfall.com/search?q=!dogwalker)
- [x] Done -- [Doorkeeper Thrull](https://scryfall.com/search?q=!doorkeeperthrull)
- [x] Done -- [Doppelgang](https://scryfall.com/search?q=!doppelgang)
- [x] Done -- [Drag the Canal](https://scryfall.com/search?q=!dragthecanal)
- [x] Done -- [Dramatic Accusation](https://scryfall.com/search?q=!dramaticaccusation)
- [x] Done -- [Due Diligence](https://scryfall.com/search?q=!duediligence)
- [x] Done -- [Elegant Parlor](https://scryfall.com/search?q=!elegantparlor)
- [x] Done -- [Eliminate the Impossible](https://scryfall.com/search?q=!eliminatetheimpossible)
- [x] Done -- [Escape Tunnel](https://scryfall.com/search?q=!escapetunnel)
- [x] Done -- [Essence of Antiquity](https://scryfall.com/search?q=!essenceofantiquity)
- [x] Done -- [Etrata, Deadly Fugitive](https://scryfall.com/search?q=!etratadeadlyfugitive)
- [x] Done -- [Evidence Examiner](https://scryfall.com/search?q=!evidenceexaminer)
- [x] Done -- [Exit Specialist](https://scryfall.com/search?q=!exitspecialist)
- [x] Done -- [Expedited Inheritance](https://scryfall.com/search?q=!expeditedinheritance)
- [x] Done -- [Expose the Culprit](https://scryfall.com/search?q=!exposetheculprit)
- [x] Done -- [Extract a Confession](https://scryfall.com/search?q=!extractaconfession)
- [x] Done -- [Ezrim, Agency Chief](https://scryfall.com/search?q=!ezrimagencychief)
- [x] Done -- [Fae Flight](https://scryfall.com/search?q=!faeflight)
- [x] Done -- [Faerie Snoop](https://scryfall.com/search?q=!faeriesnoop)
- [x] Done -- [Fanatical Strength](https://scryfall.com/search?q=!fanaticalstrength)
- [x] Done -- [Felonious Rage](https://scryfall.com/search?q=!feloniousrage)
- [x] Done -- [Festerleech](https://scryfall.com/search?q=!festerleech)
- [x] Done -- [Flotsam // Jetsam](https://scryfall.com/search?q=!flotsamjetsam)
- [x] Done -- [Flourishing Bloom-Kin](https://scryfall.com/search?q=!flourishingbloomkin)
- [x] Done -- [Forensic Gadgeteer](https://scryfall.com/search?q=!forensicgadgeteer)
- [x] Done -- [Forensic Researcher](https://scryfall.com/search?q=!forensicresearcher)
- [x] Done -- [Forum Familiar](https://scryfall.com/search?q=!forumfamiliar)
- [x] Done -- [Frantic Scapegoat](https://scryfall.com/search?q=!franticscapegoat)
- [x] Done -- [Fugitive Codebreaker](https://scryfall.com/search?q=!fugitivecodebreaker)
- [x] Done -- [Furtive Courier](https://scryfall.com/search?q=!furtivecourier)
- [x] Done -- [Fuss // Bother](https://scryfall.com/search?q=!fussbother)
- [x] Done -- [Gadget Technician](https://scryfall.com/search?q=!gadgettechnician)
- [x] Done -- [Galvanize](https://scryfall.com/search?q=!galvanize)
- [x] Done -- [Gearbane Orangutan](https://scryfall.com/search?q=!gearbaneorangutan)
- [x] Done -- [Get a Leg Up](https://scryfall.com/search?q=!getalegup)
- [x] Done -- [Gleaming Geardrake](https://scryfall.com/search?q=!gleaminggeardrake)
- [x] Done -- [Glint Weaver](https://scryfall.com/search?q=!glintweaver)
- [x] Done -- [Goblin Maskmaker](https://scryfall.com/search?q=!goblinmaskmaker)
- [x] Done -- [Granite Witness](https://scryfall.com/search?q=!granitewitness)
- [x] Done -- [Gravestone Strider](https://scryfall.com/search?q=!gravestonestrider)
- [x] Done -- [Greenbelt Radical](https://scryfall.com/search?q=!greenbeltradical)
- [x] Done -- [Griffnaut Tracker](https://scryfall.com/search?q=!griffnauttracker)
- [x] Done -- [Haazda Vigilante](https://scryfall.com/search?q=!haazdavigilante)
- [x] Done -- [Hard-Hitting Question](https://scryfall.com/search?q=!hardhittingquestion)
- [x] Done -- [Harried Dronesmith](https://scryfall.com/search?q=!harrieddronesmith)
- [x] Done -- [Hedge Maze](https://scryfall.com/search?q=!hedgemaze)
- [x] Done -- [Hedge Whisperer](https://scryfall.com/search?q=!hedgewhisperer)
- [x] Done -- [Hide in Plain Sight](https://scryfall.com/search?q=!hideinplainsight)
- [x] Done -- [Homicide Investigator](https://scryfall.com/search?q=!homicideinvestigator)
- [x] Done -- [Hotshot Investigators](https://scryfall.com/search?q=!hotshotinvestigators)
- [x] Done -- [Hunted Bonebrute](https://scryfall.com/search?q=!huntedbonebrute)
- [x] Done -- [Hustle // Bustle](https://scryfall.com/search?q=!hustlebustle)
- [x] Done -- [Ill-Timed Explosion](https://scryfall.com/search?q=!illtimedexplosion)
- [x] Done -- [Illicit Masquerade](https://scryfall.com/search?q=!illicitmasquerade)
- [x] Done -- [Incinerator of the Guilty](https://scryfall.com/search?q=!incineratoroftheguilty)
- [x] Done -- [Innocent Bystander](https://scryfall.com/search?q=!innocentbystander)
- [x] Done -- [Inside Source](https://scryfall.com/search?q=!insidesource)
- [x] Done -- [Insidious Roots](https://scryfall.com/search?q=!insidiousroots)
- [x] Done -- [Intrude on the Mind](https://scryfall.com/search?q=!intrudeonthemind)
- [x] Done -- [It Doesn't Add Up](https://scryfall.com/search?q=!itdoesntaddup)
- [x] Done -- [Izoni, Center of the Web](https://scryfall.com/search?q=!izonicenteroftheweb)
- [x] Done -- [Jaded Analyst](https://scryfall.com/search?q=!jadedanalyst)
- [x] Done -- [Judith, Carnage Connoisseur](https://scryfall.com/search?q=!judithcarnageconnoisseur)
- [x] Done -- [Karlov Watchdog](https://scryfall.com/search?q=!karlovwatchdog)
- [x] Done -- [Kaya, Spirits' Justice](https://scryfall.com/search?q=!kayaspiritsjustice)
- [x] Done -- [Kellan, Inquisitive Prodigy](https://scryfall.com/search?q=!kellaninquisitiveprodigy)
- [x] Done -- [Knife](https://scryfall.com/search?q=!knife)
- [x] Done -- [Kraul Whipcracker](https://scryfall.com/search?q=!kraulwhipcracker)
- [x] Done -- [Krenko's Buzzcrusher](https://scryfall.com/search?q=!krenkosbuzzcrusher)
- [x] Done -- [Krenko, Baron of Tin Street](https://scryfall.com/search?q=!krenkobaronoftinstreet)
- [x] Done -- [Krovod Haunch](https://scryfall.com/search?q=!krovodhaunch)
- [x] Done -- [Kylox's Voltstrider](https://scryfall.com/search?q=!kyloxsvoltstrider)
- [x] Done -- [Kylox, Visionary Inventor](https://scryfall.com/search?q=!kyloxvisionaryinventor)
- [x] Done -- [Lamplight Phoenix](https://scryfall.com/search?q=!lamplightphoenix)
- [x] Done -- [Lazav, Wearer of Faces](https://scryfall.com/search?q=!lazavweareroffaces)
- [x] Done -- [Lead Pipe](https://scryfall.com/search?q=!leadpipe)
- [x] Done -- [Leering Onlooker](https://scryfall.com/search?q=!leeringonlooker)
- [x] Done -- [Leyline of the Guildpact](https://scryfall.com/search?q=!leylineoftheguildpact)
- [x] Done -- [Lightning Helix](https://scryfall.com/search?q=!lightninghelix)
- [x] Done -- [Living Conundrum](https://scryfall.com/search?q=!livingconundrum)
- [x] Done -- [Long Goodbye](https://scryfall.com/search?q=!longgoodbye)
- [x] Done -- [Lost in the Maze](https://scryfall.com/search?q=!lostinthemaze)
- [x] Done -- [Loxodon Eavesdropper](https://scryfall.com/search?q=!loxodoneavesdropper)
- [x] Done -- [Lumbering Laundry](https://scryfall.com/search?q=!lumberinglaundry)
- [x] Done -- [Lush Portico](https://scryfall.com/search?q=!lushportico)
- [x] Done -- [Macabre Reconstruction](https://scryfall.com/search?q=!macabrereconstruction)
- [x] Done -- [Magnetic Snuffler](https://scryfall.com/search?q=!magneticsnuffler)
- [x] Done -- [Magnifying Glass](https://scryfall.com/search?q=!magnifyingglass)
- [x] Done -- [Make Your Move](https://scryfall.com/search?q=!makeyourmove)
- [x] Done -- [Makeshift Binding](https://scryfall.com/search?q=!makeshiftbinding)
- [x] Done -- [Marketwatch Phantom](https://scryfall.com/search?q=!marketwatchphantom)
- [x] Done -- [Massacre Girl, Known Killer](https://scryfall.com/search?q=!massacregirlknownkiller)
- [x] Done -- [Meddling Youths](https://scryfall.com/search?q=!meddlingyouths)
- [x] Done -- [Melek, Reforged Researcher](https://scryfall.com/search?q=!melekreforgedresearcher)
- [x] Done -- [Meticulous Archive](https://scryfall.com/search?q=!meticulousarchive)
- [x] Done -- [Mistway Spy](https://scryfall.com/search?q=!mistwayspy)
- [x] Done -- [Murder](https://scryfall.com/search?q=!murder)
- [x] Done -- [Museum Nightwatch](https://scryfall.com/search?q=!museumnightwatch)
- [x] Done -- [Neighborhood Guardian](https://scryfall.com/search?q=!neighborhoodguardian)
- [x] Done -- [Nervous Gardener](https://scryfall.com/search?q=!nervousgardener)
- [x] Done -- [Nightdrinker Moroii](https://scryfall.com/search?q=!nightdrinkermoroii)
- [x] Done -- [Niv-Mizzet, Guildpact](https://scryfall.com/search?q=!nivmizzetguildpact)
- [x] Done -- [No More Lies](https://scryfall.com/search?q=!nomorelies)
- [x] Done -- [No Witnesses](https://scryfall.com/search?q=!nowitnesses)
- [x] Done -- [Not on My Watch](https://scryfall.com/search?q=!notonmywatch)
- [x] Done -- [Novice Inspector](https://scryfall.com/search?q=!noviceinspector)
- [x] Done -- [Offender at Large](https://scryfall.com/search?q=!offenderatlarge)
- [x] Done -- [Officious Interrogation](https://scryfall.com/search?q=!officiousinterrogation)
- [x] Done -- [On the Job](https://scryfall.com/search?q=!onthejob)
- [x] Done -- [Out Cold](https://scryfall.com/search?q=!outcold)
- [x] Done -- [Outrageous Robbery](https://scryfall.com/search?q=!outrageousrobbery)
- [x] Done -- [Perimeter Enforcer](https://scryfall.com/search?q=!perimeterenforcer)
- [x] Done -- [Person of Interest](https://scryfall.com/search?q=!personofinterest)
- [x] Done -- [Persuasive Interrogators](https://scryfall.com/search?q=!persuasiveinterrogators)
- [x] Done -- [Pick Your Poison](https://scryfall.com/search?q=!pickyourpoison)
- [x] Done -- [Polygraph Orb](https://scryfall.com/search?q=!polygraphorb)
- [x] Done -- [Pompous Gadabout](https://scryfall.com/search?q=!pompousgadabout)
- [x] Done -- [Presumed Dead](https://scryfall.com/search?q=!presumeddead)
- [x] Done -- [Private Eye](https://scryfall.com/search?q=!privateeye)
- [x] Done -- [Proft's Eidetic Memory](https://scryfall.com/search?q=!proftseideticmemory)
- [x] Done -- [Projektor Inspector](https://scryfall.com/search?q=!projektorinspector)
- [x] Done -- [Public Thoroughfare](https://scryfall.com/search?q=!publicthoroughfare)
- [x] Done -- [Push // Pull](https://scryfall.com/search?q=!pushpull)
- [x] Done -- [Pyrotechnic Performer](https://scryfall.com/search?q=!pyrotechnicperformer)
- [x] Done -- [Rakdos, Patron of Chaos](https://scryfall.com/search?q=!rakdospatronofchaos)
- [x] Done -- [Rakish Scoundrel](https://scryfall.com/search?q=!rakishscoundrel)
- [x] Done -- [Raucous Theater](https://scryfall.com/search?q=!raucoustheater)
- [x] Done -- [Reasonable Doubt](https://scryfall.com/search?q=!reasonabledoubt)
- [x] Done -- [Reckless Detective](https://scryfall.com/search?q=!recklessdetective)
- [x] Done -- [Red Herring](https://scryfall.com/search?q=!redherring)
- [x] Done -- [Reenact the Crime](https://scryfall.com/search?q=!reenactthecrime)
- [x] Done -- [Relive the Past](https://scryfall.com/search?q=!relivethepast)
- [x] Done -- [Repeat Offender](https://scryfall.com/search?q=!repeatoffender)
- [x] Done -- [Repulsive Mutation](https://scryfall.com/search?q=!repulsivemutation)
- [x] Done -- [Riftburst Hellion](https://scryfall.com/search?q=!riftbursthellion)
- [x] Done -- [Rope](https://scryfall.com/search?q=!rope)
- [x] Done -- [Rot Farm Mortipede](https://scryfall.com/search?q=!rotfarmmortipede)
- [x] Done -- [Rubblebelt Braggart](https://scryfall.com/search?q=!rubblebeltbraggart)
- [x] Done -- [Rubblebelt Maverick](https://scryfall.com/search?q=!rubblebeltmaverick)
- [x] Done -- [Rune-Brand Juggler](https://scryfall.com/search?q=!runebrandjuggler)
- [x] Done -- [Sample Collector](https://scryfall.com/search?q=!samplecollector)
- [x] Done -- [Sanctuary Wall](https://scryfall.com/search?q=!sanctuarywall)
- [x] Done -- [Sanguine Savior](https://scryfall.com/search?q=!sanguinesavior)
- [x] Done -- [Sanitation Automaton](https://scryfall.com/search?q=!sanitationautomaton)
- [x] Done -- [Scene of the Crime](https://scryfall.com/search?q=!sceneofthecrime)
- [x] Done -- [Seasoned Consultant](https://scryfall.com/search?q=!seasonedconsultant)
- [x] Done -- [Shadowy Backstreet](https://scryfall.com/search?q=!shadowybackstreet)
- [x] Done -- [Shady Informant](https://scryfall.com/search?q=!shadyinformant)
- [x] Done -- [Sharp-Eyed Rookie](https://scryfall.com/search?q=!sharpeyedrookie)
- [x] Done -- [Shock](https://scryfall.com/search?q=!shock)
- [x] Done -- [Slice from the Shadows](https://scryfall.com/search?q=!slicefromtheshadows)
- [x] Done -- [Slime Against Humanity](https://scryfall.com/search?q=!slimeagainsthumanity)
- [x] Done -- [Slimy Dualleech](https://scryfall.com/search?q=!slimydualleech)
- [x] Done -- [Snarling Gorehound](https://scryfall.com/search?q=!snarlinggorehound)
- [x] Done -- [Soul Enervation](https://scryfall.com/search?q=!soulenervation)
- [x] Done -- [Soul Search](https://scryfall.com/search?q=!soulsearch)
- [x] Done -- [Steamcore Scholar](https://scryfall.com/search?q=!steamcorescholar)
- [x] Done -- [Sudden Setback](https://scryfall.com/search?q=!suddensetback)
- [x] Done -- [Sumala Sentry](https://scryfall.com/search?q=!sumalasentry)
- [x] Done -- [Surveillance Monitor](https://scryfall.com/search?q=!surveillancemonitor)
- [x] Done -- [Suspicious Detonation](https://scryfall.com/search?q=!suspiciousdetonation)
- [x] Done -- [Tenth District Hero](https://scryfall.com/search?q=!tenthdistricthero)
- [x] Done -- [Teysa, Opulent Oligarch](https://scryfall.com/search?q=!teysaopulentoligarch)
- [x] Done -- [The Chase Is On](https://scryfall.com/search?q=!thechaseison)
- [x] Done -- [The Pride of Hull Clade](https://scryfall.com/search?q=!theprideofhullclade)
- [x] Done -- [They Went This Way](https://scryfall.com/search?q=!theywentthisway)
- [x] Done -- [Thinking Cap](https://scryfall.com/search?q=!thinkingcap)
- [x] Done -- [Thundering Falls](https://scryfall.com/search?q=!thunderingfalls)
- [x] Done -- [Tin Street Gossip](https://scryfall.com/search?q=!tinstreetgossip)
- [x] Done -- [Tolsimir, Midnight's Light](https://scryfall.com/search?q=!tolsimirmidnightslight)
- [x] Done -- [Tomik, Wielder of Law](https://scryfall.com/search?q=!tomikwielderoflaw)
- [x] Done -- [Topiary Panther](https://scryfall.com/search?q=!topiarypanther)
- [x] Done -- [Torch the Witness](https://scryfall.com/search?q=!torchthewitness)
- [x] Done -- [Toxin Analysis](https://scryfall.com/search?q=!toxinanalysis)
- [x] Done -- [Treacherous Greed](https://scryfall.com/search?q=!treacherousgreed)
- [x] Done -- [Trostani, Three Whispers](https://scryfall.com/search?q=!trostanithreewhispers)
- [x] Done -- [Tunnel Tipster](https://scryfall.com/search?q=!tunneltipster)
- [x] Done -- [Unauthorized Exit](https://scryfall.com/search?q=!unauthorizedexit)
- [x] Done -- [Undercity Eliminator](https://scryfall.com/search?q=!undercityeliminator)
- [x] Done -- [Undercity Sewers](https://scryfall.com/search?q=!undercitysewers)
- [x] Done -- [Undercover Crocodelf](https://scryfall.com/search?q=!undercovercrocodelf)
- [x] Done -- [Underground Mortuary](https://scryfall.com/search?q=!undergroundmortuary)
- [x] Done -- [Undergrowth Recon](https://scryfall.com/search?q=!undergrowthrecon)
- [x] Done -- [Unscrupulous Agent](https://scryfall.com/search?q=!unscrupulousagent)
- [x] Done -- [Unyielding Gatekeeper](https://scryfall.com/search?q=!unyieldinggatekeeper)
- [x] Done -- [Urgent Necropsy](https://scryfall.com/search?q=!urgentnecropsy)
- [x] Done -- [Vannifar, Evolved Enigma](https://scryfall.com/search?q=!vannifarevolvedenigma)
- [x] Done -- [Vein Ripper](https://scryfall.com/search?q=!veinripper)
- [x] Done -- [Vengeful Creeper](https://scryfall.com/search?q=!vengefulcreeper)
- [x] Done -- [Vengeful Tracker](https://scryfall.com/search?q=!vengefultracker)
- [x] Done -- [Vitu-Ghazi Inspector](https://scryfall.com/search?q=!vitughaziinspector)
- [x] Done -- [Voja, Jaws of the Conclave](https://scryfall.com/search?q=!vojajawsoftheconclave)
- [x] Done -- [Warleader's Call](https://scryfall.com/search?q=!warleaderscall)
- [x] Done -- [Wispdrinker Vampire](https://scryfall.com/search?q=!wispdrinkervampire)
- [x] Done -- [Wojek Investigator](https://scryfall.com/search?q=!wojekinvestigator)
- [x] Done -- [Worldsoul's Rage](https://scryfall.com/search?q=!worldsoulsrage)
- [x] Done -- [Wrench](https://scryfall.com/search?q=!wrench)
- [x] Done -- [Yarus, Roar of the Old Gods](https://scryfall.com/search?q=!yarusroaroftheoldgods)
</details>

**Comment by theelk801** [comment]
additional tasks:

none yet

**Comment by Cguy7777** [comment]
Working on Voja, Jaws of the Conclave

**Comment by Cguy7777** [comment]
Working on Get a Leg Up

**Comment by DominionSpy** [comment]
Working on [A Killer Among Us](https://scryfall.com/search?q=!akilleramongus)

**Comment by Cguy7777** [comment]
Working on Candlestick

**Comment by Susucre** [comment]
Quoting the [https://magic.wizards.com/en/news/feature/murders-at-karlov-manor-release-notes](Release Notes), Suspend has been modified. It is now optional to cast the spell once the last counter is removed.

> Suspend has received a functional update along with this release: when the last time counter is removed from a suspended card, casting that spell is now optional. If you don't cast it, it will remain in exile indefinitely.

**Comment by DominionSpy** [comment]
When the Case mechanic PR is successfully merged, I'll work on the other Case cards.

**Comment by jimga150** [comment]
Working on [Archdruid's Charm](https://scryfall.com/search?q=!archdruidscharm)

**Comment by DominionSpy** [comment]
Working on [Flotsam // Jestam](https://scryfall.com/search?q=!flotsamjetsam) and [Push // Pull](https://scryfall.com/search?q=!pushpull)

**Comment by DominionSpy** [comment]
Working on [Kaya, Spirits' Justice](https://scryfall.com/search?q=!kayaspiritsjustice)

**Comment by Cguy7777** [comment]
Working on Flourishing Bloom-Kin

**Comment by jimga150** [comment]
Working on [Expedited Inheritance](https://scryfall.com/search?q=!expeditedinheritance)

**Comment by Cguy7777** [comment]
Working on Hedge Whisperer

**Comment by Cguy7777** [comment]
Working on Blood Spatter Analysis

**Comment by DominionSpy** [comment]
Working on Illicit Masquerade

**Comment by Cguy7777** [comment]
Working on Coerced to Kill

**Comment by Cguy7777** [comment]
Working on Connecting the Dots

**Comment by JayDi85** [comment]
I added Disguise ability implementation, but there are some non-implemented cards with it like [[Bubble Smuggler]]. So feel free to add it.

**Comment by Susucre** [comment]
@JayDi85 do you have plans for implementing the Cloaks card, or should I look at them?

**Comment by JayDi85** [comment]
Yes, I will add it

**Comment by Susucre** [comment]
@theelk801 set is done I think. ssk97 did work on the remaining cards. Disguise/Cloak is not much different than Morph/Manifest and issues/bugs relative to face down have separate issues.
