### ISSUE TITLE
MKC - Murders at Karlov Manor Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11669]
This checklist is here to help manage the implementation of Murders at Karlov Manor Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Kaust, Eyes of the Glade](https://scryfall.com/search?q=!kausteyesoftheglade)
- [ ] In progress -- [Mirko, Obsessive Theorist](https://scryfall.com/search?q=!mirkoobsessivetheorist)
- [ ] In progress -- [Nelly Borca, Impulsive Accuser](https://scryfall.com/search?q=!nellyborcaimpulsiveaccuser)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"KaustEyesOfTheGlade"or!"MirkoObsessiveTheorist"or!"NellyBorcaImpulsiveAccuser"&unique=cards)
# Implemented Cards

- [x] Done -- [Morska, Undersea Sleuth](https://scryfall.com/search?q=!morskaunderseasleuth)

**Comment by Susucre** [comment]
Quoting the [Release Notes](https://magic.wizards.com/en/news/feature/murders-at-karlov-manor-release-notes), Suspend has been modified. It is now optional to cast the spell once the last counter is removed.

> Suspend has received a functional update along with this release: when the last time counter is removed from a suspended card, casting that spell is now optional. If you don't cast it, it will remain in exile indefinitely.

**Comment by jimga150** [comment]
Working on [Redemption Arc](https://scryfall.com/search?q=!redemptionarc)

**Comment by kzymaris** [comment]
Working on [Unshakable Tail](https://scryfall.com/search?q=!unshakabletail)

**Comment by Cguy7777** [comment]
Working on Final-Word Phantom

**Comment by skiwkr** [comment]
Working on Prisoner's Dilemma

**Comment by ShadyV** [comment]
Hello, any chance someone could work on implementing Mob Verdict please? Much appreciated.

**Comment by UranicMammal874** [comment]
Hi! Is there any way someone could try to implement Nelly Borca please? Thanks very much!

**Comment by matoro** [comment]
Attempt at Take the Bait in https://github.com/magefree/mage/pull/14321

**Comment by jantizio** [comment]
@UranicMammal874 I tried to implement Nelly Borca in #14386

**Comment by greenlovecat** [comment]
Hi, Team!
Added: True Identity and Veiled Ascension from Deadly Disguise Commander Precon
https://github.com/magefree/mage/pull/14868
Please review and approve!
