### ISSUE TITLE
Permanent research/refactors/reworks/bugs

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11826]
Editable summary list of different problems with permanents for research and fixes/improvements.

1

> Each permanent keeps original/blueprint object for reset own characteristics and apply active effects on each game cycle: PermanentCard::card and PermanentToken:token

There are multiple methods to take access to it, e.g. getMainCard, getCard, getToken, getMageObject, etc. Some of the uses can modify it — that’s wrong. Possible bugs: color/pt/types applied forever after buggy effect/ability instead temporary.

 * [ ] search all usages of original card/token and make sure it’s in read only mode. Cards changes also can use game state with card’s characteristics and its buggy too (if you change card then it apply forever and for every related permanents).

2

> Permanent from a card uses card id. Permanent from a token uses random id. 

Its can be buggy too — some effects can target permanent but apply to card and vise versa. As example: look at Game::enterWithCounters method (it set for a card id but apply for a permanent id before etb). Possible bugs: some effects/abilities can work with cards, but can be broken with tokens.
* [ ] Research: permanent from a card usages - is it really generates diff permanents from the same card? What really happens with permanent id? What really happens with a copies?
* [ ] Research: Is it possible to use a random id for PermanentCard too (can be very-very buggy, but it’s correct logic).

3

> Xmage uses zone change counter (ZCC) to implement paper’s “new object” rules (e.g. after move between zones). Permanent uses a static ZCC (un-changeable, after zone change must be removed from a game). Card uses dynamic ZCC (+1 to zcc after each zone change).

* [ ] Research: is ZCCs of permanent and related card are synced in all use cases (some abilities can require it);
* [ ] Research: there are few methods to change and update zcc of the permanent. Must search all usages and restrict to use it like throw exception. ZCC must be init on first usage only.
