### ISSUE TITLE
BIG - The Big Score Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11851]
This checklist is here to help manage the implementation of The Big Score. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Ancient Cornucopia](https://scryfall.com/search?q=!ancientcornucopia)
- [x] Done -- [Bristlebud Farmer](https://scryfall.com/search?q=!bristlebudfarmer)
- [x] Done -- [Collector's Cage](https://scryfall.com/search?q=!collectorscage)
- [x] Done -- [Esoteric Duplicator](https://scryfall.com/search?q=!esotericduplicator)
- [x] Done -- [Fomori Vault](https://scryfall.com/search?q=!fomorivault)
- [x] Done -- [Generous Plunderer](https://scryfall.com/search?q=!generousplunderer)
- [x] Done -- [Grand Abolisher](https://scryfall.com/search?q=!grandabolisher)
- [x] Done -- [Greed's Gambit](https://scryfall.com/search?q=!greedsgambit)
- [x] Done -- [Harvester of Misery](https://scryfall.com/search?q=!harvesterofmisery)
- [x] Done -- [Hostile Investigator](https://scryfall.com/search?q=!hostileinvestigator)
- [x] Done -- [Legion Extruder](https://scryfall.com/search?q=!legionextruder)
- [x] Done -- [Loot, the Key to Everything](https://scryfall.com/search?q=!lootthekeytoeverything)
- [x] Done -- [Lost Jitte](https://scryfall.com/search?q=!lostjitte)
- [x] Done -- [Lotus Ring](https://scryfall.com/search?q=!lotusring)
- [x] Done -- [Memory Vessel](https://scryfall.com/search?q=!memoryvessel)
- [x] Done -- [Molten Duplication](https://scryfall.com/search?q=!moltenduplication)
- [x] Done -- [Nexus of Becoming](https://scryfall.com/search?q=!nexusofbecoming)
- [x] Done -- [Oltec Matterweaver](https://scryfall.com/search?q=!oltecmatterweaver)
- [x] Done -- [Omenpath Journey](https://scryfall.com/search?q=!omenpathjourney)
- [x] Done -- [Pest Control](https://scryfall.com/search?q=!pestcontrol)
- [x] Done -- [Rest in Peace](https://scryfall.com/search?q=!restinpeace)
- [x] Done -- [Sandstorm Salvager](https://scryfall.com/search?q=!sandstormsalvager)
- [x] Done -- [Simulacrum Synthesizer](https://scryfall.com/search?q=!simulacrumsynthesizer)
- [x] Done -- [Sword of Wealth and Power](https://scryfall.com/search?q=!swordofwealthandpower)
- [x] Done -- [Tarnation Vista](https://scryfall.com/search?q=!tarnationvista)
- [x] Done -- [Territory Forge](https://scryfall.com/search?q=!territoryforge)
- [x] Done -- [Torpor Orb](https://scryfall.com/search?q=!torpororb)
- [x] Done -- [Transmutation Font](https://scryfall.com/search?q=!transmutationfont)
- [x] Done -- [Vaultborn Tyrant](https://scryfall.com/search?q=!vaultborntyrant)
- [x] Done -- [Worldwalker Helm](https://scryfall.com/search?q=!worldwalkerhelm)
</details>

**Comment by theelk801** [comment]
Additional tasks: none yet

**Comment by theelk801** [comment]
that's a wrap, thanks to @Susucre for helping
