### ISSUE TITLE
BLB - Bloomburrow Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11853]
This checklist is here to help manage the implementation of Bloomburrow. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Bria, Riptide Rogue](https://scryfall.com/search?q=!briariptiderogue)
- [ ] In progress -- [Byrke, Long Ear of the Law](https://scryfall.com/search?q=!byrkelongearofthelaw)
- [ ] In progress -- [Lumra, Bellow of the Woods](https://scryfall.com/search?q=!lumrabellowofthewoods)
- [ ] In progress -- [Mabel, Heir to Cragflame](https://scryfall.com/search?q=!mabelheirtocragflame)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"BriaRiptideRogue"or!"ByrkeLongEarOfTheLaw"or!"LumraBellowOfTheWoods"or!"MabelHeirToCragflame"&unique=cards)
# Implemented Cards

**Comment by theelk801** [comment]
Additional tasks: none yet

**Comment by jimga150** [comment]
Working on [Alania, Divergent Storm](https://scryfall.com/search?q=!alaniadivergentstorm)

**Comment by jimga150** [comment]
Working on [Splash Portal](https://scryfall.com/search?q=!splashportal)

**Comment by jimga150** [comment]
Working on [Eluge, the Shoreless Sea](https://scryfall.com/search?q=!elugetheshorelesssea)

**Comment by jimga150** [comment]
> Implement "Pawprint" mechanic (and [update Rage Extractor](https://x.com/Dunkatog/status/1811520152011440177) symbol from {P} to {H})

It looks like https://gatherer.wizards.com/handlers/ already switched the "p" symbol to be the pawprint, but "h" hasnt been populated yet. Cani just make this change and we can leave this one card to sit with a broken symbol (maybe ill add hint text to it) until WOTC gets that done?

**Comment by theelk801** [comment]
we don't have to follow gatherer exactly in this kind of situation, if the symbol is supposed to change we can just change it

**Comment by Susucre** [comment]
Scryfall is currently on {H} for Rage Extractor, and on {P} for Paw symbol. I would expect mtgjson to soon sync with that.

**Comment by JayDi85** [comment]
Scryfall is main source for all symbols. It download svg icons and generate all other image formats from it. So it must be compatible. See `ScryfallSymbolsSource`. Gatherer source support outdated and maybe will be removed someday (it contains only low quality png symbols).

**Comment by jimga150** [comment]
Working on [Season of Gathering](https://scryfall.com/search?q=!seasonofgathering)

**Comment by EdgarEat** [comment]
> Working on [Alania, Divergent Storm](https://scryfall.com/search?q=!alaniadivergentstorm)

Thank you for your effort! I wish more cards were added to this app because this is mtg heaven! I wish cards like Danny Pink were added so I can finish my commander decks.

**Comment by jimga150** [comment]
> > Working on [Alania, Divergent Storm](https://scryfall.com/search?q=!alaniadivergentstorm)
> 
> Thank you for your effort! I wish more cards were added to this app because this is mtg heaven! I wish cards like Danny Pink were added so I can finish my commander decks.

I'm actually going through these cause my friend is making an Alania deck and he wants to play it lmao--its such a fantastic commander!

**Comment by jimga150** [comment]
Working on [Valley Floodcaller](https://scryfall.com/search?q=!valleyfloodcaller)

**Comment by jimga150** [comment]
Working on [Season of Loss](https://scryfall.com/search?q=!seasonofloss)

**Comment by alma555** [comment]
Working on Camellia

**Comment by Lorenzomicci** [comment]
Working on [Clement, the Worrywort](https://scryfall.com/search?q=!clementtheworrywort)

**Comment by TramplingDancer** [comment]
Cards like [Gev, Scaled Scorch](https://scryfall.com/search?q=!gevscaledscorch) and [Kastral, the Windcrested](https://scryfall.com/search?q=!kastralthewindcrested) are not available in the game yet, but are listed here as done now. When will they be available, with the next update?

**Comment by Piovra92** [comment]
[Helga, Skittish Seer](https://scryfall.com/search?q=!helgaskittishseer) results as DONE, but it is not implemented in the game, is it an error? Thanks

**Comment by Grath** [comment]
> Cards like [Gev, Scaled Scorch](https://scryfall.com/search?q=!gevscaledscorch) and [Kastral, the Windcrested](https://scryfall.com/search?q=!kastralthewindcrested) are not available in the game yet, but are listed here as done now. When will they be available, with the next update?

Gev was implemented in 79f8ab94bb8b17667317b7f4414f0004024ba661 last week and Kastral in #12773 last week. They will be available with the next update, which should occur before long (JayDi said "next update within a day" yesterday.)

> [Helga, Skittish Seer](https://scryfall.com/search?q=!helgaskittishseer) results as DONE, but it is not implemented in the game, is it an error? Thanks

https://github.com/magefree/mage/pull/12740 implemented two weeks ago, since the last update happened. Cards that have been implemented don't become available until after XMage updates.

**Comment by SeventhM** [comment]
> Cards that have been implemented don't become available until after XMage updates.

I've noticed this came up a few times now. Is there a possibility of an increase in update cadence, or would that cause other issues elsewhere?

**Comment by JayDi85** [comment]
> Is there a possibility of an increase in update cadence

Nope. Release window depends on finished features, free time, critical bugs, etc. if you want to have access to latest cards as fast as possible then you can build and run app from a source code. Wiki page has a detailed instructions for developers.

**Comment by earchip94** [comment]
Working on Clement the Worrywart

**Comment by TramplingDancer** [comment]
Sword of the Squeak (https://scryfall.com/card/blc/40/sword-of-the-squeak) is missing kn this list. I have been wondering when it will be implemented but I can't find any reference to it so I thought I'd post it here.

**Comment by Grath** [comment]
Not missing, you're looking in the wrong location: https://github.com/magefree/mage/issues/12568

**Comment by MorihiroS** [comment]
> * In progress -- [Clement, the Worrywort](https://scryfall.com/search?q=!clementtheworrywort)

@theelk801 it's already implemented

**Comment by muz** [comment]
Updated the original issue.

For posterity, the last remaining card is against https://github.com/magefree/mage/pull/12844 which is probably ripe for re-review now that Waterbending is also implemented and the game engine has moved on a bit in the year+ since when it was first attempted to be implemented.
