### ISSUE TITLE
MH3 - Modern Horizons 3 Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11852]
This checklist is here to help manage the implementation of Modern Horizons 3. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abstruse Appropriation](https://scryfall.com/search?q=!abstruseappropriation)
- [x] Done -- [Accursed Marauder](https://scryfall.com/search?q=!accursedmarauder)
- [x] Done -- [Aerie Auxiliary](https://scryfall.com/search?q=!aerieauxiliary)
- [x] Done -- [Aether Revolt](https://scryfall.com/search?q=!aetherrevolt)
- [x] Done -- [Aether Spike](https://scryfall.com/search?q=!aetherspike)
- [x] Done -- [Ajani Fells the Godsire](https://scryfall.com/search?q=!ajanifellsthegodsire)
- [x] Done -- [Ajani, Nacatl Pariah](https://scryfall.com/search?q=!ajaninacatlpariah)
- [x] Done -- [Amped Raptor](https://scryfall.com/search?q=!ampedraptor)
- [x] Done -- [Amphibian Downpour](https://scryfall.com/search?q=!amphibiandownpour)
- [x] Done -- [Angel of the Ruins](https://scryfall.com/search?q=!angeloftheruins)
- [x] Done -- [Annoyed Altisaur](https://scryfall.com/search?q=!annoyedaltisaur)
- [x] Done -- [Arcbound Condor](https://scryfall.com/search?q=!arcboundcondor)
- [x] Done -- [Archway of Innovation](https://scryfall.com/search?q=!archwayofinnovation)
- [x] Done -- [Arena of Glory](https://scryfall.com/search?q=!arenaofglory)
- [x] Done -- [Argent Dais](https://scryfall.com/search?q=!argentdais)
- [x] Done -- [Arna Kennerud, Skycaptain](https://scryfall.com/search?q=!arnakennerudskycaptain)
- [x] Done -- [Ashling, Flame Dancer](https://scryfall.com/search?q=!ashlingflamedancer)
- [x] Done -- [Barbarian Ring](https://scryfall.com/search?q=!barbarianring)
- [x] Done -- [Basking Broodscale](https://scryfall.com/search?q=!baskingbroodscale)
- [x] Done -- [Bespoke Battlewagon](https://scryfall.com/search?q=!bespokebattlewagon)
- [x] Done -- [Birthing Ritual](https://scryfall.com/search?q=!birthingritual)
- [x] Done -- [Bloodsoaked Insight](https://scryfall.com/search?q=!bloodsoakedinsight)
- [x] Done -- [Bloodstained Mire](https://scryfall.com/search?q=!bloodstainedmire)
- [x] Done -- [Boggart Trawler](https://scryfall.com/search?q=!boggarttrawler)
- [x] Done -- [Bountiful Landscape](https://scryfall.com/search?q=!bountifullandscape)
- [x] Done -- [Brainsurge](https://scryfall.com/search?q=!brainsurge)
- [x] Done -- [Branching Evolution](https://scryfall.com/search?q=!branchingevolution)
- [x] Done -- [Breaker of Creation](https://scryfall.com/search?q=!breakerofcreation)
- [x] Done -- [Breathe Your Last](https://scryfall.com/search?q=!breatheyourlast)
- [x] Done -- [Breya, Etherium Shaper](https://scryfall.com/search?q=!breyaetheriumshaper)
- [x] Done -- [Bridgeworks Battle](https://scryfall.com/search?q=!bridgeworksbattle)
- [x] Done -- [Buried Alive](https://scryfall.com/search?q=!buriedalive)
- [x] Done -- [Cephalid Coliseum](https://scryfall.com/search?q=!cephalidcoliseum)
- [x] Done -- [Charitable Levy](https://scryfall.com/search?q=!charitablelevy)
- [x] Done -- [Chthonian Nightmare](https://scryfall.com/search?q=!chthoniannightmare)
- [x] Done -- [Collective Resistance](https://scryfall.com/search?q=!collectiveresistance)
- [x] Done -- [Colossal Dreadmask](https://scryfall.com/search?q=!colossaldreadmask)
- [x] Done -- [Conduit Goblin](https://scryfall.com/search?q=!conduitgoblin)
- [x] Done -- [Consign to Memory](https://scryfall.com/search?q=!consigntomemory)
- [x] Done -- [Consuming Corruption](https://scryfall.com/search?q=!consumingcorruption)
- [x] Done -- [Contaminated Landscape](https://scryfall.com/search?q=!contaminatedlandscape)
- [x] Done -- [Copycrook](https://scryfall.com/search?q=!copycrook)
- [x] Done -- [Corrupted Shapeshifter](https://scryfall.com/search?q=!corruptedshapeshifter)
- [x] Done -- [Crabomination](https://scryfall.com/search?q=!crabomination)
- [x] Done -- [Cranial Ram](https://scryfall.com/search?q=!cranialram)
- [x] Done -- [Cursed Mirror](https://scryfall.com/search?q=!cursedmirror)
- [x] Done -- [Cursed Wombat](https://scryfall.com/search?q=!cursedwombat)
- [x] Done -- [Cyclops Superconductor](https://scryfall.com/search?q=!cyclopssuperconductor)
- [x] Done -- [Deceptive Landscape](https://scryfall.com/search?q=!deceptivelandscape)
- [x] Done -- [Decree of Justice](https://scryfall.com/search?q=!decreeofjustice)
- [x] Done -- [Deem Inferior](https://scryfall.com/search?q=!deeminferior)
- [x] Done -- [Deep Analysis](https://scryfall.com/search?q=!deepanalysis)
- [x] Done -- [Depth Defiler](https://scryfall.com/search?q=!depthdefiler)
- [x] Done -- [Deserted Temple](https://scryfall.com/search?q=!desertedtemple)
- [x] Done -- [Detective's Phoenix](https://scryfall.com/search?q=!detectivesphoenix)
- [x] Done -- [Devourer of Destiny](https://scryfall.com/search?q=!devourerofdestiny)
- [x] Done -- [Disciple of Freyalise](https://scryfall.com/search?q=!discipleoffreyalise)
- [x] Done -- [Disruptor Flute](https://scryfall.com/search?q=!disruptorflute)
- [x] Done -- [Distinguished Conjurer](https://scryfall.com/search?q=!distinguishedconjurer)
- [x] Done -- [Dog Umbra](https://scryfall.com/search?q=!dogumbra)
- [x] Done -- [Dreadmobile](https://scryfall.com/search?q=!dreadmobile)
- [x] Done -- [Dreamdrinker Vampire](https://scryfall.com/search?q=!dreamdrinkervampire)
- [x] Done -- [Dreamtide Whale](https://scryfall.com/search?q=!dreamtidewhale)
- [x] Done -- [Drossclaw](https://scryfall.com/search?q=!drossclaw)
- [x] Done -- [Drowner of Truth](https://scryfall.com/search?q=!drowneroftruth)
- [x] Done -- [Drownyard Lurker](https://scryfall.com/search?q=!drownyardlurker)
- [x] Done -- [Echoes of Eternity](https://scryfall.com/search?q=!echoesofeternity)
- [x] Done -- [Eladamri, Korvecdal](https://scryfall.com/search?q=!eladamrikorvecdal)
- [x] Done -- [Eldrazi Linebreaker](https://scryfall.com/search?q=!eldrazilinebreaker)
- [x] Done -- [Eldrazi Ravager](https://scryfall.com/search?q=!eldraziravager)
- [x] Done -- [Eldrazi Repurposer](https://scryfall.com/search?q=!eldrazirepurposer)
- [x] Done -- [Electrozoa](https://scryfall.com/search?q=!electrozoa)
- [x] Done -- [Emerald Medallion](https://scryfall.com/search?q=!emeraldmedallion)
- [x] Done -- [Emissary of Soulfire](https://scryfall.com/search?q=!emissaryofsoulfire)
- [x] Done -- [Emperor of Bones](https://scryfall.com/search?q=!emperorofbones)
- [x] Done -- [Emrakul's Messenger](https://scryfall.com/search?q=!emrakulsmessenger)
- [x] Done -- [Emrakul, the World Anew](https://scryfall.com/search?q=!emrakultheworldanew)
- [x] Done -- [Envoy of the Ancestors](https://scryfall.com/search?q=!envoyoftheancestors)
- [x] Done -- [Essence Reliquary](https://scryfall.com/search?q=!essencereliquary)
- [x] Done -- [Estrid's Invocation](https://scryfall.com/search?q=!estridsinvocation)
- [x] Done -- [Etched Slith](https://scryfall.com/search?q=!etchedslith)
- [x] Done -- [Etherium Pteramander](https://scryfall.com/search?q=!etheriumpteramander)
- [x] Done -- [Eviscerator's Insight](https://scryfall.com/search?q=!evisceratorsinsight)
- [x] Done -- [Evolution Witness](https://scryfall.com/search?q=!evolutionwitness)
- [x] Done -- [Expanding Ooze](https://scryfall.com/search?q=!expandingooze)
- [x] Done -- [Expel the Unworthy](https://scryfall.com/search?q=!expeltheunworthy)
- [x] Done -- [Faithful Watchdog](https://scryfall.com/search?q=!faithfulwatchdog)
- [x] Done -- [Fanatic of Rhonas](https://scryfall.com/search?q=!fanaticofrhonas)
- [x] Done -- [Fanged Flames](https://scryfall.com/search?q=!fangedflames)
- [x] Done -- [Fangs of Kalonia](https://scryfall.com/search?q=!fangsofkalonia)
- [x] Done -- [Fell the Profane](https://scryfall.com/search?q=!felltheprofane)
- [x] Done -- [Fetid Gargantua](https://scryfall.com/search?q=!fetidgargantua)
- [x] Done -- [Flare of Cultivation](https://scryfall.com/search?q=!flareofcultivation)
- [x] Done -- [Flare of Denial](https://scryfall.com/search?q=!flareofdenial)
- [x] Done -- [Flare of Duplication](https://scryfall.com/search?q=!flareofduplication)
- [x] Done -- [Flare of Fortitude](https://scryfall.com/search?q=!flareoffortitude)
- [x] Done -- [Flare of Malice](https://scryfall.com/search?q=!flareofmalice)
- [x] Done -- [Fledgling Dragon](https://scryfall.com/search?q=!fledglingdragon)
- [x] Done -- [Flooded Strand](https://scryfall.com/search?q=!floodedstrand)
- [x] Done -- [Flusterstorm](https://scryfall.com/search?q=!flusterstorm)
- [x] Done -- [Foreboding Landscape](https://scryfall.com/search?q=!forebodinglandscape)
- [x] Done -- [Fowl Strike](https://scryfall.com/search?q=!fowlstrike)
- [x] Done -- [Frogmyr Enforcer](https://scryfall.com/search?q=!frogmyrenforcer)
- [x] Done -- [Furnace Hellkite](https://scryfall.com/search?q=!furnacehellkite)
- [x] Done -- [Galvanic Discharge](https://scryfall.com/search?q=!galvanicdischarge)
- [x] Done -- [Genku, Future Shaper](https://scryfall.com/search?q=!genkufutureshaper)
- [x] Done -- [Ghostfire Slice](https://scryfall.com/search?q=!ghostfireslice)
- [x] Done -- [Gift of the Viper](https://scryfall.com/search?q=!giftoftheviper)
- [x] Done -- [Glaring Fleshraker](https://scryfall.com/search?q=!glaringfleshraker)
- [x] Done -- [Glasswing Grace](https://scryfall.com/search?q=!glasswinggrace)
- [x] Done -- [Glimpse the Impossible](https://scryfall.com/search?q=!glimpsetheimpossible)
- [x] Done -- [Glyph Elemental](https://scryfall.com/search?q=!glyphelemental)
- [x] Done -- [Golden-Tail Trainer](https://scryfall.com/search?q=!goldentailtrainer)
- [x] Done -- [Gravedig](https://scryfall.com/search?q=!gravedig)
- [x] Done -- [Grim Servant](https://scryfall.com/search?q=!grimservant)
- [x] Done -- [Grist, Voracious Larva](https://scryfall.com/search?q=!gristvoraciouslarva)
- [x] Done -- [Guardian of the Forgotten](https://scryfall.com/search?q=!guardianoftheforgotten)
- [x] Done -- [Guide of Souls](https://scryfall.com/search?q=!guideofsouls)
- [x] Done -- [Harbinger of the Seas](https://scryfall.com/search?q=!harbingeroftheseas)
- [x] Done -- [Herigast, Erupting Nullkite](https://scryfall.com/search?q=!herigasteruptingnullkite)
- [x] Done -- [Hexgold Slith](https://scryfall.com/search?q=!hexgoldslith)
- [x] Done -- [Hope-Ender Coatl](https://scryfall.com/search?q=!hopeendercoatl)
- [x] Done -- [Horrid Shadowspinner](https://scryfall.com/search?q=!horridshadowspinner)
- [x] Done -- [Horrific Assault](https://scryfall.com/search?q=!horrificassault)
- [x] Done -- [Hydra Trainer](https://scryfall.com/search?q=!hydratrainer)
- [x] Done -- [Hydroelectric Specimen](https://scryfall.com/search?q=!hydroelectricspecimen)
- [x] Done -- [Idol of False Gods](https://scryfall.com/search?q=!idoloffalsegods)
- [x] Done -- [Imskir Iron-Eater](https://scryfall.com/search?q=!imskirironeater)
- [x] Done -- [Indebted Spirit](https://scryfall.com/search?q=!indebtedspirit)
- [x] Done -- [Infernal Captor](https://scryfall.com/search?q=!infernalcaptor)
- [x] Done -- [Inspired Inventor](https://scryfall.com/search?q=!inspiredinventor)
- [x] Done -- [Inventor's Axe](https://scryfall.com/search?q=!inventorsaxe)
- [x] Done -- [Invert Polarity](https://scryfall.com/search?q=!invertpolarity)
- [x] Done -- [It That Heralds the End](https://scryfall.com/search?q=!itthatheraldstheend)
- [x] Done -- [Izzet Generatorium](https://scryfall.com/search?q=!izzetgeneratorium)
- [x] Done -- [Jet Medallion](https://scryfall.com/search?q=!jetmedallion)
- [x] Done -- [Jolted Awake](https://scryfall.com/search?q=!joltedawake)
- [x] Done -- [Junk Diver](https://scryfall.com/search?q=!junkdiver)
- [x] Done -- [K'rrik, Son of Yawgmoth](https://scryfall.com/search?q=!krriksonofyawgmoth)
- [x] Done -- [Kaalia of the Vast](https://scryfall.com/search?q=!kaaliaofthevast)
- [x] Done -- [Kami of Jealous Thirst](https://scryfall.com/search?q=!kamiofjealousthirst)
- [x] Done -- [Kappa Cannoneer](https://scryfall.com/search?q=!kappacannoneer)
- [x] Done -- [Kozilek's Command](https://scryfall.com/search?q=!kozilekscommand)
- [x] Done -- [Kozilek's Unsealing](https://scryfall.com/search?q=!kozileksunsealing)
- [x] Done -- [Kozilek, the Broken Reality](https://scryfall.com/search?q=!kozilekthebrokenreality)
- [x] Done -- [Kudo, King Among Bears](https://scryfall.com/search?q=!kudokingamongbears)
- [x] Done -- [Laelia, the Blade Reforged](https://scryfall.com/search?q=!laeliathebladereforged)
- [x] Done -- [Legion Leadership](https://scryfall.com/search?q=!legionleadership)
- [x] Done -- [Lethal Throwdown](https://scryfall.com/search?q=!lethalthrowdown)
- [x] Done -- [Lion Umbra](https://scryfall.com/search?q=!lionumbra)
- [x] Done -- [Malevolent Rumble](https://scryfall.com/search?q=!malevolentrumble)
- [x] Done -- [Mandibular Kite](https://scryfall.com/search?q=!mandibularkite)
- [x] Done -- [Marionette Apprentice](https://scryfall.com/search?q=!marionetteapprentice)
- [x] Done -- [Meltdown](https://scryfall.com/search?q=!meltdown)
- [x] Done -- [Metastatic Evangel](https://scryfall.com/search?q=!metastaticevangel)
- [x] Done -- [Meteoric Mace](https://scryfall.com/search?q=!meteoricmace)
- [x] Done -- [Mindless Conscription](https://scryfall.com/search?q=!mindlessconscription)
- [x] Done -- [Mogg Mob](https://scryfall.com/search?q=!moggmob)
- [x] Done -- [Molten Gatekeeper](https://scryfall.com/search?q=!moltengatekeeper)
- [x] Done -- [Monstrous Vortex](https://scryfall.com/search?q=!monstrousvortex)
- [x] Done -- [Monumental Henge](https://scryfall.com/search?q=!monumentalhenge)
- [x] Done -- [Muster the Departed](https://scryfall.com/search?q=!musterthedeparted)
- [x] Done -- [Nadier's Nightblade](https://scryfall.com/search?q=!nadiersnightblade)
- [x] Done -- [Nadu, Winged Wisdom](https://scryfall.com/search?q=!naduwingedwisdom)
- [x] Done -- [Necrodominance](https://scryfall.com/search?q=!necrodominance)
- [x] Done -- [Nesting Grounds](https://scryfall.com/search?q=!nestinggrounds)
- [x] Done -- [Nethergoyf](https://scryfall.com/search?q=!nethergoyf)
- [x] Done -- [Nightshade Dryad](https://scryfall.com/search?q=!nightshadedryad)
- [x] Done -- [Null Elemental Blast](https://scryfall.com/search?q=!nullelementalblast)
- [x] Done -- [Nulldrifter](https://scryfall.com/search?q=!nulldrifter)
- [x] Done -- [Nyxborn Hydra](https://scryfall.com/search?q=!nyxbornhydra)
- [x] Done -- [Nyxborn Unicorn](https://scryfall.com/search?q=!nyxbornunicorn)
- [x] Done -- [Obstinate Gargoyle](https://scryfall.com/search?q=!obstinategargoyle)
- [x] Done -- [Ocelot Pride](https://scryfall.com/search?q=!ocelotpride)
- [x] Done -- [Ondu Knotmaster](https://scryfall.com/search?q=!onduknotmaster)
- [x] Done -- [Ophiomancer](https://scryfall.com/search?q=!ophiomancer)
- [x] Done -- [Orim's Chant](https://scryfall.com/search?q=!orimschant)
- [x] Done -- [Party Thrasher](https://scryfall.com/search?q=!partythrasher)
- [x] Done -- [Path of Annihilation](https://scryfall.com/search?q=!pathofannihilation)
- [x] Done -- [Pearl Medallion](https://scryfall.com/search?q=!pearlmedallion)
- [x] Done -- [Pearl-Ear, Imperial Advisor](https://scryfall.com/search?q=!pearlearimperialadvisor)
- [x] Done -- [Perilous Landscape](https://scryfall.com/search?q=!perilouslandscape)
- [x] Done -- [Petrifying Meddler](https://scryfall.com/search?q=!petrifyingmeddler)
- [x] Done -- [Phelia, Exuberant Shepherd](https://scryfall.com/search?q=!pheliaexuberantshepherd)
- [x] Done -- [Phlage, Titan of Fire's Fury](https://scryfall.com/search?q=!phlagetitanoffiresfury)
- [x] Done -- [Phyrexian Ironworks](https://scryfall.com/search?q=!phyrexianironworks)
- [x] Done -- [Phyrexian Tower](https://scryfall.com/search?q=!phyrexiantower)
- [x] Done -- [Pinnacle Monk](https://scryfall.com/search?q=!pinnaclemonk)
- [x] Done -- [Planar Genesis](https://scryfall.com/search?q=!planargenesis)
- [x] Done -- [Polluted Delta](https://scryfall.com/search?q=!polluteddelta)
- [x] Done -- [Powerbalance](https://scryfall.com/search?q=!powerbalance)
- [x] Done -- [Priest of Titania](https://scryfall.com/search?q=!priestoftitania)
- [x] Done -- [Primal Prayers](https://scryfall.com/search?q=!primalprayers)
- [x] Done -- [Propagator Drone](https://scryfall.com/search?q=!propagatordrone)
- [x] Done -- [Proud Pack-Rhino](https://scryfall.com/search?q=!proudpackrhino)
- [x] Done -- [Psychic Frog](https://scryfall.com/search?q=!psychicfrog)
- [x] Done -- [Pyretic Rebirth](https://scryfall.com/search?q=!pyreticrebirth)
- [x] Done -- [Quest for the Necropolis](https://scryfall.com/search?q=!questforthenecropolis)
- [x] Done -- [Ral and the Implicit Maze](https://scryfall.com/search?q=!ralandtheimplicitmaze)
- [x] Done -- [Ral, Monsoon Mage](https://scryfall.com/search?q=!ralmonsoonmage)
- [x] Done -- [Razorgrass Ambush](https://scryfall.com/search?q=!razorgrassambush)
- [x] Done -- [Reckless Pyrosurfer](https://scryfall.com/search?q=!recklesspyrosurfer)
- [x] Done -- [Recruiter of the Guard](https://scryfall.com/search?q=!recruiteroftheguard)
- [x] Done -- [Reef Worm](https://scryfall.com/search?q=!reefworm)
- [x] Done -- [Refurbished Familiar](https://scryfall.com/search?q=!refurbishedfamiliar)
- [x] Done -- [Reiterating Bolt](https://scryfall.com/search?q=!reiteratingbolt)
- [x] Done -- [Retrofitted Transmogrant](https://scryfall.com/search?q=!retrofittedtransmogrant)
- [x] Done -- [Revitalizing Repast](https://scryfall.com/search?q=!revitalizingrepast)
- [x] Done -- [Riddle Gate Gargoyle](https://scryfall.com/search?q=!riddlegategargoyle)
- [x] Done -- [Ripples of Undeath](https://scryfall.com/search?q=!ripplesofundeath)
- [x] Done -- [Roil Cartographer](https://scryfall.com/search?q=!roilcartographer)
- [x] Done -- [Rosecot Knight](https://scryfall.com/search?q=!rosecotknight)
- [x] Done -- [Rosheen, Roaring Prophet](https://scryfall.com/search?q=!rosheenroaringprophet)
- [x] Done -- [Ruby Medallion](https://scryfall.com/search?q=!rubymedallion)
- [x] Done -- [Rush of Inspiration](https://scryfall.com/search?q=!rushofinspiration)
- [x] Done -- [Sage of the Unknowable](https://scryfall.com/search?q=!sageoftheunknowable)
- [x] Done -- [Sapphire Medallion](https://scryfall.com/search?q=!sapphiremedallion)
- [x] Done -- [Sarpadian Simulacrum](https://scryfall.com/search?q=!sarpadiansimulacrum)
- [x] Done -- [Scurrilous Sentry](https://scryfall.com/search?q=!scurriloussentry)
- [x] Done -- [Scurry of Gremlins](https://scryfall.com/search?q=!scurryofgremlins)
- [x] Done -- [Seething Landscape](https://scryfall.com/search?q=!seethinglandscape)
- [x] Done -- [Serum Visionary](https://scryfall.com/search?q=!serumvisionary)
- [x] Done -- [Sevinne's Reclamation](https://scryfall.com/search?q=!sevinnesreclamation)
- [x] Done -- [Shadow of the Second Sun](https://scryfall.com/search?q=!shadowofthesecondsun)
- [x] Done -- [Shattered Landscape](https://scryfall.com/search?q=!shatteredlandscape)
- [x] Done -- [Sheltering Landscape](https://scryfall.com/search?q=!shelteringlandscape)
- [x] Done -- [Shifting Woodland](https://scryfall.com/search?q=!shiftingwoodland)
- [x] Done -- [Shilgengar, Sire of Famine](https://scryfall.com/search?q=!shilgengarsireoffamine)
- [x] Done -- [Shrieking Drake](https://scryfall.com/search?q=!shriekingdrake)
- [x] Done -- [Siege Smash](https://scryfall.com/search?q=!siegesmash)
- [x] Done -- [Signature Slam](https://scryfall.com/search?q=!signatureslam)
- [x] Done -- [Sink into Stupor](https://scryfall.com/search?q=!sinkintostupor)
- [x] Done -- [Six](https://scryfall.com/search?q=!six)
- [x] Done -- [Skittering Precursor](https://scryfall.com/search?q=!skitteringprecursor)
- [x] Done -- [Skoa, Embermage](https://scryfall.com/search?q=!skoaembermage)
- [x] Done -- [Smelted Chargebug](https://scryfall.com/search?q=!smeltedchargebug)
- [x] Done -- [Snapping Voidcraw](https://scryfall.com/search?q=!snappingvoidcraw)
- [x] Done -- [Sneaky Snacker](https://scryfall.com/search?q=!sneakysnacker)
- [x] Done -- [Snow-Covered Wastes](https://scryfall.com/search?q=!snowcoveredwastes)
- [x] Done -- [Solar Transformer](https://scryfall.com/search?q=!solartransformer)
- [x] Done -- [Solstice Zealot](https://scryfall.com/search?q=!solsticezealot)
- [x] Done -- [Sorin of House Markov](https://scryfall.com/search?q=!sorinofhousemarkov)
- [x] Done -- [Sowing Mycospawn](https://scryfall.com/search?q=!sowingmycospawn)
- [x] Done -- [Spawn-Gang Commander](https://scryfall.com/search?q=!spawngangcommander)
- [x] Done -- [Springheart Nantuko](https://scryfall.com/search?q=!springheartnantuko)
- [x] Done -- [Spymaster's Vault](https://scryfall.com/search?q=!spymastersvault)
- [x] Done -- [Static Prison](https://scryfall.com/search?q=!staticprison)
- [x] Done -- [Strength of the Harvest](https://scryfall.com/search?q=!strengthoftheharvest)
- [x] Done -- [Strix Serenade](https://scryfall.com/search?q=!strixserenade)
- [x] Done -- [Stump Stomp](https://scryfall.com/search?q=!stumpstomp)
- [x] Done -- [Sundering Eruption](https://scryfall.com/search?q=!sunderingeruption)
- [x] Done -- [Suppression Ray](https://scryfall.com/search?q=!suppressionray)
- [x] Done -- [Sylvan Safekeeper](https://scryfall.com/search?q=!sylvansafekeeper)
- [x] Done -- [Tamiyo Meets the Story Circle](https://scryfall.com/search?q=!tamiyomeetsthestorycircle)
- [x] Done -- [Tamiyo, Inquisitive Student](https://scryfall.com/search?q=!tamiyoinquisitivestudent)
- [x] Done -- [Temperamental Oozewagg](https://scryfall.com/search?q=!temperamentaloozewagg)
- [x] Done -- [Tempest Harvester](https://scryfall.com/search?q=!tempestharvester)
- [x] Done -- [Territory Culler](https://scryfall.com/search?q=!territoryculler)
- [x] Done -- [The Creation of Avacyn](https://scryfall.com/search?q=!thecreationofavacyn)
- [x] Done -- [The Hunger Tide Rises](https://scryfall.com/search?q=!thehungertiderises)
- [x] Done -- [The Necrobloom](https://scryfall.com/search?q=!thenecrobloom)
- [x] Done -- [Thief of Existence](https://scryfall.com/search?q=!thiefofexistence)
- [x] Done -- [Thraben Charm](https://scryfall.com/search?q=!thrabencharm)
- [x] Done -- [Thriving Skyclaw](https://scryfall.com/search?q=!thrivingskyclaw)
- [x] Done -- [Titans' Vanguard](https://scryfall.com/search?q=!titansvanguard)
- [x] Done -- [Toxic Deluge](https://scryfall.com/search?q=!toxicdeluge)
- [x] Done -- [Tranquil Landscape](https://scryfall.com/search?q=!tranquillandscape)
- [x] Done -- [Trickster's Elk](https://scryfall.com/search?q=!tricksterselk)
- [x] Done -- [Triton Wavebreaker](https://scryfall.com/search?q=!tritonwavebreaker)
- [x] Done -- [Tune the Narrative](https://scryfall.com/search?q=!tunethenarrative)
- [x] Done -- [Twisted Landscape](https://scryfall.com/search?q=!twistedlandscape)
- [x] Done -- [Twisted Riddlekeeper](https://scryfall.com/search?q=!twistedriddlekeeper)
- [x] Done -- [Ugin's Binding](https://scryfall.com/search?q=!uginsbinding)
- [x] Done -- [Ugin's Labyrinth](https://scryfall.com/search?q=!uginslabyrinth)
- [x] Done -- [Ulamog, the Defiler](https://scryfall.com/search?q=!ulamogthedefiler)
- [x] Done -- [Unfathomable Truths](https://scryfall.com/search?q=!unfathomabletruths)
- [x] Done -- [Unstable Amulet](https://scryfall.com/search?q=!unstableamulet)
- [x] Done -- [Urza's Cave](https://scryfall.com/search?q=!urzascave)
- [x] Done -- [Urza's Incubator](https://scryfall.com/search?q=!urzasincubator)
- [x] Done -- [Utter Insignificance](https://scryfall.com/search?q=!utterinsignificance)
- [x] Done -- [Vexing Bauble](https://scryfall.com/search?q=!vexingbauble)
- [x] Done -- [Victimize](https://scryfall.com/search?q=!victimize)
- [x] Done -- [Voidpouncer](https://scryfall.com/search?q=!voidpouncer)
- [x] Done -- [Volatile Stormdrake](https://scryfall.com/search?q=!volatilestormdrake)
- [x] Done -- [Voltstorm Angel](https://scryfall.com/search?q=!voltstormangel)
- [x] Done -- [Warped Tusker](https://scryfall.com/search?q=!warpedtusker)
- [x] Done -- [Warren Soultrader](https://scryfall.com/search?q=!warrensoultrader)
- [x] Done -- [Wastescape Battlemage](https://scryfall.com/search?q=!wastescapebattlemage)
- [x] Done -- [Waterlogged Teachings](https://scryfall.com/search?q=!waterloggedteachings)
- [x] Done -- [Wheel of Potential](https://scryfall.com/search?q=!wheelofpotential)
- [x] Done -- [White Orchid Phantom](https://scryfall.com/search?q=!whiteorchidphantom)
- [x] Done -- [Wight of the Reliquary](https://scryfall.com/search?q=!wightofthereliquary)
- [x] Done -- [Windswept Heath](https://scryfall.com/search?q=!windsweptheath)
- [x] Done -- [Wing It](https://scryfall.com/search?q=!wingit)
- [x] Done -- [Winter Moon](https://scryfall.com/search?q=!wintermoon)
- [x] Done -- [Wirewood Symbiote](https://scryfall.com/search?q=!wirewoodsymbiote)
- [x] Done -- [Witch Enchanter](https://scryfall.com/search?q=!witchenchanter)
- [x] Done -- [Wither and Bloom](https://scryfall.com/search?q=!witherandbloom)
- [x] Done -- [Wooded Foothills](https://scryfall.com/search?q=!woodedfoothills)
- [x] Done -- [Worn Powerstone](https://scryfall.com/search?q=!wornpowerstone)
- [x] Done -- [Wrath of the Skies](https://scryfall.com/search?q=!wrathoftheskies)
- [x] Done -- [Writhing Chrysalis](https://scryfall.com/search?q=!writhingchrysalis)
- [x] Done -- [Wumpus Aberration](https://scryfall.com/search?q=!wumpusaberration)
- [x] Done -- [Wurmcoil Larva](https://scryfall.com/search?q=!wurmcoillarva)
</details>

**Comment by Susucre** [comment]
I have started to implement leaks in the alpha server, so once they are confirmed I'll add them here:

<details>
  <summary> Leaked cards implemented </summary>
  - Brainsurge
  - Flare of Duplication
  - Flare of Fortitude
  - Grist, Voracious Larva // Grist, the Plague Swarm
  - Marionette Apprentice
  - Ocelot Pride
  - Ral, Monsoon Mage // Ral, Leyline Prodigy
  - Sorin of House Markov // Sorin, Ravenous Neonate
  - Tamiyo, Inquisitive Student // Tamiyo, Seasoned Scholar
  - Warren Soultrader
</details>

**Comment by Susucre** [comment]
So Kindred is confirmed the new name for Tribal with [[Echoes of Eternity]].

I assume we are waiting for Scryfall to update on old cards before making the change?

**Comment by theelk801** [comment]
yeah, we actually knew about this change a while ago and were waiting for them to implement it, it's looking like they're doing that either in this set or with bloomburrow

**Comment by theelk801** [comment]
[source](https://magic.wizards.com/en/news/announcements/card-updates-coming-with-khans-of-tarkir-on-mtg-arena)

**Comment by Grath** [comment]
I'm taking a crack at The Necrobloom, current game plan is to build out the infrastructure for #10811 to implement the card but not do the entire refactor unless I get really bored over the holiday weekend.

**Comment by grimreap124** [comment]
I just created a PR for Golden-Tail Trainer

**Comment by Susucre** [comment]
@theelk801 last couple cards are implemented. Can close this one.
