### ISSUE TITLE
ACR - Assassin's Creed Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11854]
This checklist is here to help manage the implementation of Assassin's Creed. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Altair Ibn-La'Ahad](https://scryfall.com/search?q=!altairibnlaahad)
- [ ] In progress -- [Cleopatra, Exiled Pharaoh](https://scryfall.com/search?q=!cleopatraexiledpharaoh)
- [ ] In progress -- [Eivor, Battle-Ready](https://scryfall.com/search?q=!eivorbattleready)
- [ ] In progress -- [Ezio Auditore da Firenze](https://scryfall.com/search?q=!ezioauditoredafirenze)
- [ ] In progress -- [Ezio, Blade of Vengeance](https://scryfall.com/search?q=!eziobladeofvengeance)
- [ ] In progress -- [Haystack](https://scryfall.com/search?q=!haystack)
- [ ] In progress -- [Hidden Blade](https://scryfall.com/search?q=!hiddenblade)
- [ ] In progress -- [Leonardo da Vinci](https://scryfall.com/search?q=!leonardodavinci)
- [ ] In progress -- [The Animus](https://scryfall.com/search?q=!theanimus)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"AltairIbnLaAhad"or!"CleopatraExiledPharaoh"or!"EivorBattleReady"or!"EzioAuditoreDaFirenze"or!"EzioBladeOfVengeance"or!"Haystack"or!"HiddenBlade"or!"LeonardoDaVinci"or!"TheAnimus"&unique=cards)
# Implemented Cards

- [x] Done -- [Cover of Darkness](https://scryfall.com/search?q=!coverofdarkness)
- [x] Done -- [Sword of Feast and Famine](https://scryfall.com/search?q=!swordoffeastandfamine)
- [x] Done -- [Temporal Trespass](https://scryfall.com/search?q=!temporaltrespass)

**Comment by jimga150** [comment]
Working on [Cleopatra, Exiled Pharaoh](https://scryfall.com/search?q=!cleopatraexiledpharaoh)

**Comment by GuruCeaselessHunger** [comment]
i play a lot of Eldrazis artifacts legendary permanents and the occasional saga and would love to see The Capitoline Triads implemented jimga150 if this sways the card towards being implemented sooner than signing up for github was worth it to leave this comment
thanks for the fun games ahead -GURU-

**Comment by MistMan** [comment]
I'd like to see implemented Yggdrasil. It's starting to see play in some decks and I'd like to test It out.

**Comment by Cytocide** [comment]
I'd like to request implementation of Ezio Auditore da Firenze and other remaining spells with the freerunning mechanic (viewpoint synchronization & eagle vision)

**Comment by afm2708** [comment]
Can I request become anonymous and roshan?

**Comment by Grath** [comment]
Roshan is already implemented, this issue just hasn't been updated in a while.

**Comment by Day666832** [comment]
Hi just curious if anyone is still working on these and if there was a guide available anywhere to help out

**Comment by TOX1CDonkey9** [comment]
Awesome. Thank you!

**Comment by im-inuenc** [comment]
Added pull request for What Must Be Done: https://github.com/magefree/mage/pull/13377
