### ISSUE TITLE
OTJ - Outlaws of Thunder Junction Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#11850]
This checklist is here to help manage the implementation of Outlaws of Thunder Junction. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abraded Bluffs](https://scryfall.com/search?q=!abradedbluffs)
- [x] Done -- [Akul the Unrepentant](https://scryfall.com/search?q=!akultheunrepentant)
- [x] Done -- [Aloe Alchemist](https://scryfall.com/search?q=!aloealchemist)
- [x] Done -- [Ambush Gigapede](https://scryfall.com/search?q=!ambushgigapede)
- [x] Done -- [Ankle Biter](https://scryfall.com/search?q=!anklebiter)
- [x] Done -- [Annie Flash, the Veteran](https://scryfall.com/search?q=!annieflashtheveteran)
- [x] Done -- [Annie Joins Up](https://scryfall.com/search?q=!anniejoinsup)
- [x] Done -- [Another Round](https://scryfall.com/search?q=!anotherround)
- [x] Done -- [Archangel of Tithes](https://scryfall.com/search?q=!archangeloftithes)
- [x] Done -- [Archmage's Newt](https://scryfall.com/search?q=!archmagesnewt)
- [x] Done -- [Arid Archway](https://scryfall.com/search?q=!aridarchway)
- [x] Done -- [Armored Armadillo](https://scryfall.com/search?q=!armoredarmadillo)
- [x] Done -- [Assimilation Aegis](https://scryfall.com/search?q=!assimilationaegis)
- [x] Done -- [At Knifepoint](https://scryfall.com/search?q=!atknifepoint)
- [x] Done -- [Aven Interrupter](https://scryfall.com/search?q=!aveninterrupter)
- [x] Done -- [Badlands Revival](https://scryfall.com/search?q=!badlandsrevival)
- [x] Done -- [Bandit's Haul](https://scryfall.com/search?q=!banditshaul)
- [x] Done -- [Baron Bertram Graywater](https://scryfall.com/search?q=!baronbertramgraywater)
- [x] Done -- [Beastbond Outcaster](https://scryfall.com/search?q=!beastbondoutcaster)
- [x] Done -- [Betrayal at the Vault](https://scryfall.com/search?q=!betrayalatthevault)
- [x] Done -- [Binding Negotiation](https://scryfall.com/search?q=!bindingnegotiation)
- [x] Done -- [Blacksnag Buzzard](https://scryfall.com/search?q=!blacksnagbuzzard)
- [x] Done -- [Blood Hustler](https://scryfall.com/search?q=!bloodhustler)
- [x] Done -- [Blooming Marsh](https://scryfall.com/search?q=!bloomingmarsh)
- [x] Done -- [Boneyard Desecrator](https://scryfall.com/search?q=!boneyarddesecrator)
- [x] Done -- [Bonny Pall, Clearcutter](https://scryfall.com/search?q=!bonnypallclearcutter)
- [x] Done -- [Boom Box](https://scryfall.com/search?q=!boombox)
- [x] Done -- [Botanical Sanctum](https://scryfall.com/search?q=!botanicalsanctum)
- [x] Done -- [Bounding Felidar](https://scryfall.com/search?q=!boundingfelidar)
- [x] Done -- [Bovine Intervention](https://scryfall.com/search?q=!bovineintervention)
- [x] Done -- [Breeches, the Blastmaker](https://scryfall.com/search?q=!breechestheblastmaker)
- [x] Done -- [Bridled Bighorn](https://scryfall.com/search?q=!bridledbighorn)
- [x] Done -- [Brimstone Roundup](https://scryfall.com/search?q=!brimstoneroundup)
- [x] Done -- [Bristlepack Sentry](https://scryfall.com/search?q=!bristlepacksentry)
- [x] Done -- [Bristling Backwoods](https://scryfall.com/search?q=!bristlingbackwoods)
- [x] Done -- [Bristly Bill, Spine Sower](https://scryfall.com/search?q=!bristlybillspinesower)
- [x] Done -- [Bruse Tarl, Roving Rancher](https://scryfall.com/search?q=!brusetarlrovingrancher)
- [x] Done -- [Bucolic Ranch](https://scryfall.com/search?q=!bucolicranch)
- [x] Done -- [Cactarantula](https://scryfall.com/search?q=!cactarantula)
- [x] Done -- [Cactusfolk Sureshot](https://scryfall.com/search?q=!cactusfolksureshot)
- [x] Done -- [Calamity, Galloping Inferno](https://scryfall.com/search?q=!calamitygallopinginferno)
- [x] Done -- [Canyon Crab](https://scryfall.com/search?q=!canyoncrab)
- [x] Done -- [Caught in the Crossfire](https://scryfall.com/search?q=!caughtinthecrossfire)
- [x] Done -- [Caustic Bronco](https://scryfall.com/search?q=!causticbronco)
- [x] Done -- [Claim Jumper](https://scryfall.com/search?q=!claimjumper)
- [x] Done -- [Colossal Rattlewurm](https://scryfall.com/search?q=!colossalrattlewurm)
- [x] Done -- [Concealed Courtyard](https://scryfall.com/search?q=!concealedcourtyard)
- [x] Done -- [Conduit Pylons](https://scryfall.com/search?q=!conduitpylons)
- [x] Done -- [Congregation Gryff](https://scryfall.com/search?q=!congregationgryff)
- [x] Done -- [Consuming Ashes](https://scryfall.com/search?q=!consumingashes)
- [x] Done -- [Corrupted Conviction](https://scryfall.com/search?q=!corruptedconviction)
- [x] Done -- [Creosote Heath](https://scryfall.com/search?q=!creosoteheath)
- [x] Done -- [Cunning Coyote](https://scryfall.com/search?q=!cunningcoyote)
- [x] Done -- [Dance of the Tumbleweeds](https://scryfall.com/search?q=!danceofthetumbleweeds)
- [x] Done -- [Daring Thunder-Thief](https://scryfall.com/search?q=!daringthunderthief)
- [x] Done -- [Deadeye Duelist](https://scryfall.com/search?q=!deadeyeduelist)
- [x] Done -- [Deepmuck Desperado](https://scryfall.com/search?q=!deepmuckdesperado)
- [x] Done -- [Demonic Ruckus](https://scryfall.com/search?q=!demonicruckus)
- [x] Done -- [Desert's Due](https://scryfall.com/search?q=!desertsdue)
- [x] Done -- [Desperate Bloodseeker](https://scryfall.com/search?q=!desperatebloodseeker)
- [x] Done -- [Discerning Peddler](https://scryfall.com/search?q=!discerningpeddler)
- [x] Done -- [Djinn of Fool's Fall](https://scryfall.com/search?q=!djinnoffoolsfall)
- [x] Done -- [Doc Aurlock, Grizzled Genius](https://scryfall.com/search?q=!docaurlockgrizzledgenius)
- [x] Done -- [Double Down](https://scryfall.com/search?q=!doubledown)
- [x] Done -- [Drover Grizzly](https://scryfall.com/search?q=!drovergrizzly)
- [x] Done -- [Duelist of the Mind](https://scryfall.com/search?q=!duelistofthemind)
- [x] Done -- [Dust Animus](https://scryfall.com/search?q=!dustanimus)
- [x] Done -- [Emergent Haunting](https://scryfall.com/search?q=!emergenthaunting)
- [x] Done -- [Eriette's Lullaby](https://scryfall.com/search?q=!erietteslullaby)
- [x] Done -- [Eriette, the Beguiler](https://scryfall.com/search?q=!eriettethebeguiler)
- [x] Done -- [Eroded Canyon](https://scryfall.com/search?q=!erodedcanyon)
- [x] Done -- [Ertha Jo, Frontier Mentor](https://scryfall.com/search?q=!erthajofrontiermentor)
- [x] Done -- [Explosive Derailment](https://scryfall.com/search?q=!explosivederailment)
- [x] Done -- [Failed Fording](https://scryfall.com/search?q=!failedfording)
- [x] Done -- [Fake Your Own Death](https://scryfall.com/search?q=!fakeyourowndeath)
- [x] Done -- [Fblthp, Lost on the Range](https://scryfall.com/search?q=!fblthplostontherange)
- [x] Done -- [Ferocification](https://scryfall.com/search?q=!ferocification)
- [x] Done -- [Festering Gulch](https://scryfall.com/search?q=!festeringgulch)
- [x] Done -- [Final Showdown](https://scryfall.com/search?q=!finalshowdown)
- [x] Done -- [Fleeting Reflection](https://scryfall.com/search?q=!fleetingreflection)
- [x] Done -- [Forlorn Flats](https://scryfall.com/search?q=!forlornflats)
- [x] Done -- [Form a Posse](https://scryfall.com/search?q=!formaposse)
- [x] Done -- [Forsaken Miner](https://scryfall.com/search?q=!forsakenminer)
- [x] Done -- [Fortune, Loyal Steed](https://scryfall.com/search?q=!fortuneloyalsteed)
- [x] Done -- [Freestrider Commando](https://scryfall.com/search?q=!freestridercommando)
- [x] Done -- [Freestrider Lookout](https://scryfall.com/search?q=!freestriderlookout)
- [x] Done -- [Frontier Seeker](https://scryfall.com/search?q=!frontierseeker)
- [x] Done -- [Full Steam Ahead](https://scryfall.com/search?q=!fullsteamahead)
- [x] Done -- [Geralf, the Fleshwright](https://scryfall.com/search?q=!geralfthefleshwright)
- [x] Done -- [Getaway Glamer](https://scryfall.com/search?q=!getawayglamer)
- [x] Done -- [Geyser Drake](https://scryfall.com/search?q=!geyserdrake)
- [x] Done -- [Ghired, Mirror of the Wilds](https://scryfall.com/search?q=!ghiredmirrorofthewilds)
- [x] Done -- [Giant Beaver](https://scryfall.com/search?q=!giantbeaver)
- [x] Done -- [Gila Courser](https://scryfall.com/search?q=!gilacourser)
- [x] Done -- [Gisa, the Hellraiser](https://scryfall.com/search?q=!gisathehellraiser)
- [x] Done -- [Gold Pan](https://scryfall.com/search?q=!goldpan)
- [x] Done -- [Gold Rush](https://scryfall.com/search?q=!goldrush)
- [x] Done -- [Goldvein Hydra](https://scryfall.com/search?q=!goldveinhydra)
- [x] Done -- [Great Train Heist](https://scryfall.com/search?q=!greattrainheist)
- [x] Done -- [Hardbristle Bandit](https://scryfall.com/search?q=!hardbristlebandit)
- [x] Done -- [Harrier Strix](https://scryfall.com/search?q=!harrierstrix)
- [x] Done -- [Hell to Pay](https://scryfall.com/search?q=!helltopay)
- [x] Done -- [Hellspur Brute](https://scryfall.com/search?q=!hellspurbrute)
- [x] Done -- [Hellspur Posse Boss](https://scryfall.com/search?q=!hellspurposseboss)
- [x] Done -- [High Noon](https://scryfall.com/search?q=!highnoon)
- [x] Done -- [Highway Robbery](https://scryfall.com/search?q=!highwayrobbery)
- [x] Done -- [Hollow Marauder](https://scryfall.com/search?q=!hollowmarauder)
- [x] Done -- [Holy Cow](https://scryfall.com/search?q=!holycow)
- [x] Done -- [Honest Rutstein](https://scryfall.com/search?q=!honestrutstein)
- [x] Done -- [Insatiable Avarice](https://scryfall.com/search?q=!insatiableavarice)
- [x] Done -- [Inspiring Vantage](https://scryfall.com/search?q=!inspiringvantage)
- [x] Done -- [Intimidation Campaign](https://scryfall.com/search?q=!intimidationcampaign)
- [x] Done -- [Intrepid Stablemaster](https://scryfall.com/search?q=!intrepidstablemaster)
- [x] Done -- [Inventive Wingsmith](https://scryfall.com/search?q=!inventivewingsmith)
- [x] Done -- [Irascible Wolverine](https://scryfall.com/search?q=!irasciblewolverine)
- [x] Done -- [Iron-Fist Pulverizer](https://scryfall.com/search?q=!ironfistpulverizer)
- [x] Done -- [Jace Reawakened](https://scryfall.com/search?q=!jacereawakened)
- [x] Done -- [Jagged Barrens](https://scryfall.com/search?q=!jaggedbarrens)
- [x] Done -- [Jailbreak Scheme](https://scryfall.com/search?q=!jailbreakscheme)
- [x] Done -- [Jem Lightfoote, Sky Explorer](https://scryfall.com/search?q=!jemlightfooteskyexplorer)
- [x] Done -- [Jolene, Plundering Pugilist](https://scryfall.com/search?q=!joleneplunderingpugilist)
- [x] Done -- [Kaervek, the Punisher](https://scryfall.com/search?q=!kaervekthepunisher)
- [x] Done -- [Kambal, Profiteering Mayor](https://scryfall.com/search?q=!kambalprofiteeringmayor)
- [x] Done -- [Kellan Joins Up](https://scryfall.com/search?q=!kellanjoinsup)
- [x] Done -- [Kellan, the Kid](https://scryfall.com/search?q=!kellanthekid)
- [x] Done -- [Kraum, Violent Cacophony](https://scryfall.com/search?q=!kraumviolentcacophony)
- [x] Done -- [Lassoed by the Law](https://scryfall.com/search?q=!lassoedbythelaw)
- [x] Done -- [Laughing Jasper Flint](https://scryfall.com/search?q=!laughingjasperflint)
- [x] Done -- [Lavaspur Boots](https://scryfall.com/search?q=!lavaspurboots)
- [x] Done -- [Lazav, Familiar Stranger](https://scryfall.com/search?q=!lazavfamiliarstranger)
- [x] Done -- [Lilah, Undefeated Slickshot](https://scryfall.com/search?q=!lilahundefeatedslickshot)
- [x] Done -- [Lively Dirge](https://scryfall.com/search?q=!livelydirge)
- [x] Done -- [Loan Shark](https://scryfall.com/search?q=!loanshark)
- [x] Done -- [Lonely Arroyo](https://scryfall.com/search?q=!lonelyarroyo)
- [x] Done -- [Longhorn Sharpshooter](https://scryfall.com/search?q=!longhornsharpshooter)
- [x] Done -- [Lush Oasis](https://scryfall.com/search?q=!lushoasis)
- [x] Done -- [Luxurious Locomotive](https://scryfall.com/search?q=!luxuriouslocomotive)
- [x] Done -- [Magda, the Hoardmaster](https://scryfall.com/search?q=!magdathehoardmaster)
- [x] Done -- [Magebane Lizard](https://scryfall.com/search?q=!magebanelizard)
- [x] Done -- [Make Your Own Luck](https://scryfall.com/search?q=!makeyourownluck)
- [x] Done -- [Malcolm, the Eyes](https://scryfall.com/search?q=!malcolmtheeyes)
- [x] Done -- [Map the Frontier](https://scryfall.com/search?q=!mapthefrontier)
- [x] Done -- [Marauding Sphinx](https://scryfall.com/search?q=!maraudingsphinx)
- [x] Done -- [Marchesa, Dealer of Death](https://scryfall.com/search?q=!marchesadealerofdeath)
- [x] Done -- [Metamorphic Blast](https://scryfall.com/search?q=!metamorphicblast)
- [x] Done -- [Mine Raider](https://scryfall.com/search?q=!mineraider)
- [x] Done -- [Mirage Mesa](https://scryfall.com/search?q=!miragemesa)
- [x] Done -- [Miriam, Herd Whisperer](https://scryfall.com/search?q=!miriamherdwhisperer)
- [x] Done -- [Mobile Homestead](https://scryfall.com/search?q=!mobilehomestead)
- [x] Done -- [Mourner's Surprise](https://scryfall.com/search?q=!mournerssurprise)
- [x] Done -- [Mystical Tether](https://scryfall.com/search?q=!mysticaltether)
- [x] Done -- [Neutralize the Guards](https://scryfall.com/search?q=!neutralizetheguards)
- [x] Done -- [Nezumi Linkbreaker](https://scryfall.com/search?q=!nezumilinkbreaker)
- [x] Done -- [Nimble Brigand](https://scryfall.com/search?q=!nimblebrigand)
- [x] Done -- [Nurturing Pixie](https://scryfall.com/search?q=!nurturingpixie)
- [x] Done -- [Oasis Gardener](https://scryfall.com/search?q=!oasisgardener)
- [x] Done -- [Obeka, Splitter of Seconds](https://scryfall.com/search?q=!obekasplitterofseconds)
- [x] Done -- [Oko, the Ringleader](https://scryfall.com/search?q=!okotheringleader)
- [x] Done -- [Omenport Vigilante](https://scryfall.com/search?q=!omenportvigilante)
- [x] Done -- [One Last Job](https://scryfall.com/search?q=!onelastjob)
- [x] Done -- [Ornery Tumblewagg](https://scryfall.com/search?q=!ornerytumblewagg)
- [x] Done -- [Outcaster Greenblade](https://scryfall.com/search?q=!outcastergreenblade)
- [x] Done -- [Outcaster Trailblazer](https://scryfall.com/search?q=!outcastertrailblazer)
- [x] Done -- [Outlaw Medic](https://scryfall.com/search?q=!outlawmedic)
- [x] Done -- [Outlaw Stitcher](https://scryfall.com/search?q=!outlawstitcher)
- [x] Done -- [Outlaws' Fury](https://scryfall.com/search?q=!outlawsfury)
- [x] Done -- [Overzealous Muscle](https://scryfall.com/search?q=!overzealousmuscle)
- [x] Done -- [Patient Naturalist](https://scryfall.com/search?q=!patientnaturalist)
- [x] Done -- [Peerless Ropemaster](https://scryfall.com/search?q=!peerlessropemaster)
- [x] Done -- [Phantom Interference](https://scryfall.com/search?q=!phantominterference)
- [x] Done -- [Pillage the Bog](https://scryfall.com/search?q=!pillagethebog)
- [x] Done -- [Pitiless Carnage](https://scryfall.com/search?q=!pitilesscarnage)
- [x] Done -- [Plan the Heist](https://scryfall.com/search?q=!plantheheist)
- [x] Done -- [Prairie Dog](https://scryfall.com/search?q=!prairiedog)
- [x] Done -- [Prickly Pair](https://scryfall.com/search?q=!pricklypair)
- [x] Done -- [Prosperity Tycoon](https://scryfall.com/search?q=!prosperitytycoon)
- [x] Done -- [Quick Draw](https://scryfall.com/search?q=!quickdraw)
- [x] Done -- [Quilled Charger](https://scryfall.com/search?q=!quilledcharger)
- [x] Done -- [Railway Brawler](https://scryfall.com/search?q=!railwaybrawler)
- [x] Done -- [Rakdos Joins Up](https://scryfall.com/search?q=!rakdosjoinsup)
- [x] Done -- [Rakdos, the Muscle](https://scryfall.com/search?q=!rakdosthemuscle)
- [x] Done -- [Rakish Crew](https://scryfall.com/search?q=!rakishcrew)
- [x] Done -- [Rambling Possum](https://scryfall.com/search?q=!ramblingpossum)
- [x] Done -- [Rattleback Apothecary](https://scryfall.com/search?q=!rattlebackapothecary)
- [x] Done -- [Raucous Entertainer](https://scryfall.com/search?q=!raucousentertainer)
- [x] Done -- [Raven of Fell Omens](https://scryfall.com/search?q=!ravenoffellomens)
- [x] Done -- [Razzle-Dazzler](https://scryfall.com/search?q=!razzledazzler)
- [x] Done -- [Reach for the Sky](https://scryfall.com/search?q=!reachforthesky)
- [x] Done -- [Reckless Lackey](https://scryfall.com/search?q=!recklesslackey)
- [x] Done -- [Redrock Sentinel](https://scryfall.com/search?q=!redrocksentinel)
- [x] Done -- [Requisition Raid](https://scryfall.com/search?q=!requisitionraid)
- [x] Done -- [Resilient Roadrunner](https://scryfall.com/search?q=!resilientroadrunner)
- [x] Done -- [Return the Favor](https://scryfall.com/search?q=!returnthefavor)
- [x] Done -- [Rictus Robber](https://scryfall.com/search?q=!rictusrobber)
- [x] Done -- [Riku of Many Paths](https://scryfall.com/search?q=!rikuofmanypaths)
- [x] Done -- [Rise of the Varmints](https://scryfall.com/search?q=!riseofthevarmints)
- [x] Done -- [Rodeo Pyromancers](https://scryfall.com/search?q=!rodeopyromancers)
- [x] Done -- [Rooftop Assassin](https://scryfall.com/search?q=!rooftopassassin)
- [x] Done -- [Roxanne, Starfall Savant](https://scryfall.com/search?q=!roxannestarfallsavant)
- [x] Done -- [Rush of Dread](https://scryfall.com/search?q=!rushofdread)
- [x] Done -- [Rustler Rampage](https://scryfall.com/search?q=!rustlerrampage)
- [x] Done -- [Ruthless Lawbringer](https://scryfall.com/search?q=!ruthlesslawbringer)
- [x] Done -- [Sandstorm Verge](https://scryfall.com/search?q=!sandstormverge)
- [x] Done -- [Satoru, the Infiltrator](https://scryfall.com/search?q=!satorutheinfiltrator)
- [x] Done -- [Scalestorm Summoner](https://scryfall.com/search?q=!scalestormsummoner)
- [x] Done -- [Scorching Shot](https://scryfall.com/search?q=!scorchingshot)
- [x] Done -- [Seize the Secrets](https://scryfall.com/search?q=!seizethesecrets)
- [x] Done -- [Selvala, Eager Trailblazer](https://scryfall.com/search?q=!selvalaeagertrailblazer)
- [x] Done -- [Seraphic Steed](https://scryfall.com/search?q=!seraphicsteed)
- [x] Done -- [Servant of the Stinger](https://scryfall.com/search?q=!servantofthestinger)
- [x] Done -- [Shackle Slinger](https://scryfall.com/search?q=!shackleslinger)
- [x] Done -- [Shepherd of the Clouds](https://scryfall.com/search?q=!shepherdoftheclouds)
- [x] Done -- [Sheriff of Safe Passage](https://scryfall.com/search?q=!sheriffofsafepassage)
- [x] Done -- [Shifting Grift](https://scryfall.com/search?q=!shiftinggrift)
- [x] Done -- [Shoot the Sheriff](https://scryfall.com/search?q=!shootthesheriff)
- [x] Done -- [Silver Deputy](https://scryfall.com/search?q=!silverdeputy)
- [x] Done -- [Skulduggery](https://scryfall.com/search?q=!skulduggery)
- [x] Done -- [Slick Sequence](https://scryfall.com/search?q=!slicksequence)
- [x] Done -- [Slickshot Lockpicker](https://scryfall.com/search?q=!slickshotlockpicker)
- [x] Done -- [Slickshot Show-Off](https://scryfall.com/search?q=!slickshotshowoff)
- [x] Done -- [Slickshot Vault-Buster](https://scryfall.com/search?q=!slickshotvaultbuster)
- [x] Done -- [Smuggler's Surprise](https://scryfall.com/search?q=!smugglerssurprise)
- [x] Done -- [Snakeskin Veil](https://scryfall.com/search?q=!snakeskinveil)
- [x] Done -- [Soured Springs](https://scryfall.com/search?q=!souredsprings)
- [x] Done -- [Spinewoods Armadillo](https://scryfall.com/search?q=!spinewoodsarmadillo)
- [x] Done -- [Spinewoods Paladin](https://scryfall.com/search?q=!spinewoodspaladin)
- [x] Done -- [Spirebluff Canal](https://scryfall.com/search?q=!spirebluffcanal)
- [x] Done -- [Spring Splasher](https://scryfall.com/search?q=!springsplasher)
- [x] Done -- [Stagecoach Security](https://scryfall.com/search?q=!stagecoachsecurity)
- [x] Done -- [Steer Clear](https://scryfall.com/search?q=!steerclear)
- [x] Done -- [Step Between Worlds](https://scryfall.com/search?q=!stepbetweenworlds)
- [x] Done -- [Sterling Hound](https://scryfall.com/search?q=!sterlinghound)
- [x] Done -- [Sterling Keykeeper](https://scryfall.com/search?q=!sterlingkeykeeper)
- [x] Done -- [Sterling Supplier](https://scryfall.com/search?q=!sterlingsupplier)
- [x] Done -- [Stingerback Terror](https://scryfall.com/search?q=!stingerbackterror)
- [x] Done -- [Stoic Sphinx](https://scryfall.com/search?q=!stoicsphinx)
- [x] Done -- [Stop Cold](https://scryfall.com/search?q=!stopcold)
- [x] Done -- [Stubborn Burrowfiend](https://scryfall.com/search?q=!stubbornburrowfiend)
- [x] Done -- [Taii Wakeen, Perfect Shot](https://scryfall.com/search?q=!taiiwakeenperfectshot)
- [x] Done -- [Take Up the Shield](https://scryfall.com/search?q=!takeuptheshield)
- [x] Done -- [Take for a Ride](https://scryfall.com/search?q=!takeforaride)
- [x] Done -- [Take the Fall](https://scryfall.com/search?q=!takethefall)
- [x] Done -- [Terror of the Peaks](https://scryfall.com/search?q=!terrorofthepeaks)
- [x] Done -- [The Gitrog, Ravenous Ride](https://scryfall.com/search?q=!thegitrogravenousride)
- [x] Done -- [The Key to the Vault](https://scryfall.com/search?q=!thekeytothevault)
- [x] Done -- [This Town Ain't Big Enough](https://scryfall.com/search?q=!thistownaintbigenough)
- [x] Done -- [Three Steps Ahead](https://scryfall.com/search?q=!threestepsahead)
- [x] Done -- [Throw from the Saddle](https://scryfall.com/search?q=!throwfromthesaddle)
- [x] Done -- [Thunder Lasso](https://scryfall.com/search?q=!thunderlasso)
- [x] Done -- [Thunder Salvo](https://scryfall.com/search?q=!thundersalvo)
- [x] Done -- [Tinybones Joins Up](https://scryfall.com/search?q=!tinybonesjoinsup)
- [x] Done -- [Tinybones, the Pickpocket](https://scryfall.com/search?q=!tinybonesthepickpocket)
- [x] Done -- [Tomb Trawler](https://scryfall.com/search?q=!tombtrawler)
- [x] Done -- [Trained Arynx](https://scryfall.com/search?q=!trainedarynx)
- [x] Done -- [Trash the Town](https://scryfall.com/search?q=!trashthetown)
- [x] Done -- [Treasure Dredger](https://scryfall.com/search?q=!treasuredredger)
- [x] Done -- [Trick Shot](https://scryfall.com/search?q=!trickshot)
- [x] Done -- [Tumbleweed Rising](https://scryfall.com/search?q=!tumbleweedrising)
- [x] Done -- [Unfortunate Accident](https://scryfall.com/search?q=!unfortunateaccident)
- [x] Done -- [Unscrupulous Contractor](https://scryfall.com/search?q=!unscrupulouscontractor)
- [x] Done -- [Vadmir, New Blood](https://scryfall.com/search?q=!vadmirnewblood)
- [x] Done -- [Vault Plunderer](https://scryfall.com/search?q=!vaultplunderer)
- [x] Done -- [Vengeful Townsfolk](https://scryfall.com/search?q=!vengefultownsfolk)
- [x] Done -- [Vial Smasher, Gleeful Grenadier](https://scryfall.com/search?q=!vialsmashergleefulgrenadier)
- [x] Done -- [Visage Bandit](https://scryfall.com/search?q=!visagebandit)
- [x] Done -- [Voracious Varmint](https://scryfall.com/search?q=!voraciousvarmint)
- [x] Done -- [Vraska Joins Up](https://scryfall.com/search?q=!vraskajoinsup)
- [x] Done -- [Vraska, the Silencer](https://scryfall.com/search?q=!vraskathesilencer)
- [x] Done -- [Wanted Griffin](https://scryfall.com/search?q=!wantedgriffin)
- [x] Done -- [Wrangler of the Damned](https://scryfall.com/search?q=!wranglerofthedamned)
- [x] Done -- [Wylie Duke, Atiin Hero](https://scryfall.com/search?q=!wyliedukeatiinhero)
</details>

**Comment by theelk801** [comment]
Additional tasks: none yet

**Comment by PurpleCrowbar** [comment]
@Susucre You done with Gisa, the Hellraiser? Think I've got a finished version, just forgot to tick the box, oops

**Comment by theelk801** [comment]
that's a wrap, thanks to @Susucre and @PurpleCrowbar for the contributions

**Comment by Susucre** [comment]
@JayDi85 Is there any chance for an update soon? Don't want to rush you if you have plans to add other improvements before.
The sooner the limited is available, the better we can expect common/uncommon to work correctly, as they for the most part are played in draft/sealed. (For instance the WOE release we were ready right before paper prerelease if I recall right, and the bugs were fixed within a week.)
Once the limited formats is available elsewhere, there are way less limited games so bugs can be missed for a while, as only some of the cards are played in constructed.
