### ISSUE TITLE
OTC - Outlaws of Thunder Junction Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#12011]
This checklist is here to help manage the implementation of Outlaws of Thunder Junction Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Gonti, Canny Acquisitor](https://scryfall.com/search?q=!gonticannyacquisitor)
- [ ] In progress -- [Olivia, Opulent Outlaw](https://scryfall.com/search?q=!oliviaopulentoutlaw)
- [ ] In progress -- [Yuma, Proud Protector](https://scryfall.com/search?q=!yumaproudprotector)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"GontiCannyAcquisitor"or!"OliviaOpulentOutlaw"or!"YumaProudProtector"&unique=cards)
# Implemented Cards

- [x] Done -- [Stella Lee, Wild Card](https://scryfall.com/search?q=!stellaleewildcard)

**Comment by theelk801** [comment]
Additional tasks:

- [ ] Implement "bounties" mechanic

**Comment by Grath** [comment]
All cards are now implemented, closing issue.
