### ISSUE TITLE
M3C - Modern Horizons 3 Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#12206]
This checklist is here to help manage the implementation of Modern Horizons 3 Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [March from Velis Vel](https://scryfall.com/search?q=!marchfromvelisvel)
- [ ] In progress -- [Planar Nexus](https://scryfall.com/search?q=!planarnexus)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"MarchFromVelisVel"or!"PlanarNexus"&unique=cards)
# Implemented Cards

- [x] Done -- [Final Act](https://scryfall.com/search?q=!finalact)

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by Susucre** [comment]
I have started to implement leaks in the alpha server, so once they are confirmed I'll add them here:

<details>
  <summary> Leaked cards implemented </summary>
  - Pyrogoyf
</details>

**Comment by grimreap124** [comment]
Created a PR for Hideous Taskmaster

**Comment by grimreap124** [comment]
I'm implementing Aether Refinery but need to wait for scryfall to get the token
Branch: Implement-M3C-Aether-Refinery

**Comment by drownik** [comment]
Any clues about when the implemented cards are going to be added to Xmage?? Some of the "implemented" cards are not available in the client yet.
![image](https://github.com/user-attachments/assets/fa220b1e-0ee7-4fb0-9a01-5e14abe7145a)

**Comment by Notshauna** [comment]
> Any clues about when the implemented cards are going to be added to Xmage?? Some of the "implemented" cards are not available in the client yet.

Next update.

**Comment by JacoLoco** [comment]
Yes pleas add them... Still in need.. Thanks. 
![IMG20240814123311](https://github.com/user-attachments/assets/f617b1da-de40-4d60-a45c-36b2ff61597c)

**Comment by Sidorovich77** [comment]
Working on [Desert Warfare](https://scryfall.com/card/m3c/64/desert-warfare)

**Comment by muz** [comment]
Linking two attempts to implement Desert Warfare:
* https://github.com/magefree/mage/pull/12749
* https://github.com/magefree/mage/pull/13628
