### ISSUE TITLE
BLC - Bloomburrow Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#12568]
This checklist is here to help manage the implementation of Bloomburrow Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Bello, Bard of the Brambles](https://scryfall.com/search?q=!bellobardofthebrambles)
- [ ] In progress -- [Flubs, the Fool](https://scryfall.com/search?q=!flubsthefool)
- [ ] In progress -- [Hazel of the Rootbloom](https://scryfall.com/search?q=!hazeloftherootbloom)
- [ ] In progress -- [Ms. Bumbleflower](https://scryfall.com/search?q=!msbumbleflower)
- [ ] In progress -- [Zinnia, Valley's Voice](https://scryfall.com/search?q=!zinniavalleysvoice)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"BelloBardOfTheBrambles"or!"FlubsTheFool"or!"HazelOfTheRootbloom"or!"MsBumbleflower"or!"ZinniaValleysVoice"&unique=cards)
# Implemented Cards

- [x] Done -- [Chatterfang, Squirrel General](https://scryfall.com/search?q=!chatterfangsquirrelgeneral)
- [x] Done -- [Jace, the Mind Sculptor](https://scryfall.com/search?q=!jacethemindsculptor)

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by jimga150** [comment]
Working on [Fortune Teller's Talent](https://scryfall.com/search?q=!fortunetellerstalent)

**Comment by jimga150** [comment]
Working on [Rapid Augmenter](https://scryfall.com/search?q=!rapidaugmenter)

**Comment by DreamWaker** [comment]
So, I have a working [Ms. Bumbleflower](https://scryfall.com/search?q=!Ms.Bumbleflower) and a semi working [Zinnia, Valley's Voice](https://scryfall.com/search?q=!ZinniaValleysVoice) (Had to add something to it to make it trigger properly, that shouldn't affect it much)

**Comment by TramplingDancer** [comment]
@theelk801 @Grath some cards are missing.
For example [Gev, Scaled Scorch](https://scryfall.com/card/blb/214/gev-scaled-scorch)

**Comment by WishYouWereHere** [comment]
Evercoat Ursine is missing from BLC.

**Comment by Grath** [comment]
I implemented it three weeks ago, there hasn't been a release since then. It'll be available after the next release.

**Comment by sneddigrolyat** [comment]
Hi, #14595 is my first attempt to contribute. I'm hoping to get Zinnia implemented. AI made some changes to OffspringAbility. It made it sound like the offspring ability was triggered but didn't persist until the card was entering the board, so it added an offspring ability delayed effect. Can anyone check this out for me, or let me know if there is additional testing I should do. Thanks.

**Comment by sneddigrolyat** [comment]
Hi, it says @ #14595 is waiting for review by a maintainer. @theelk801 @DreamWaker @Grath @keloks can anyone help get this assigned? Thank you. I'm new to MTG and this is my first commander so I appreciate any help anyone can offer.

**Comment by keloks** [comment]
Hi sneddi! I believe I do not have the power to assign anything :_(

I have read the changes and everything seems fine, but sadly cannot check if they work or not. Back when I gave Zinnia a try, i remember spending hours trying to test the new code, partly because I am not well versed in Java maybe.

Anyway, hope this is the answer to the offspring mechanic and particularly to Zinnia, thank you for collaborating :D

**Comment by sneddigrolyat** [comment]
Thanks @keloks. I feel you. It's definitely been many hours of testing for me, too. This updated #14609 has worked for all the scenarios I have been able to come up with, so hopefully it is closer to the answer so we can get this card implemented.

**Comment by sneddigrolyat** [comment]
My latest attempt for Zinnia is #14625 to address #12752

**Comment by sneddigrolyat** [comment]
So far #14625 seems pretty promising after reworking it. I just tested it on a private server and everything seemed good. Can anyone else take a look?
