### ISSUE TITLE
Tracking issue: Reworking DynamicValue wrt effect text generation

### ISSUE THREAD

**Issue by jimga150** [magefree/mage#12759]
Original discussion #12595

TODO:

- [ ] Get go-ahead on small PR implementing backwards-compatible changes with a few pertinent examples (#12596)
- [ ] Implement `getMessage(EffectPhrasing phrasing)` and possibly `getHint()` for all implementations of `DynamicValue`, merging in stages, Fixing any oracle text errors introduced

- [ ] A
- [ ] B
- [ ] C
- [ ] D
- [ ] E
- [ ] F
- [ ] G
- [ ] H
- [ ] I
- [ ] J
- [ ] K
- [ ] L
- [ ] M
- [ ] N
- [ ] O
- [ ] P
- [ ] Q
- [ ] R
- [ ] S
- [ ] T
- [ ] U
- [ ] V
- [ ] W
- [ ] X
- [ ] Y
- [ ] Z

- [ ] Add multiplier to `BoostSourceEffect` and similar effects that take `DynamicValue` as args
- [ ] Sweep for any `DynamicValue` classes that dont need to be classes
- [ ] Replace all Hint instances that can be replaced with a call to appropriate getHint()
- [ ] Remove any removable uses of `setText()` for all effects using `DynamicValue`
- [ ] Sweep for effects with custom rules text and `DynamicValue` arguments
- [ ] Remove `toString` in `DynamicValue`
- [ ] Fix any preexisting, newly trivial oracle text errors
