### ISSUE TITLE
DSC - Duskmourn: House of Horror Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#12775]
This checklist is here to help manage the implementation of Duskmourn: House of Horror Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Aminatou, Veil Piercer](https://scryfall.com/search?q=!aminatouveilpiercer)
- [ ] In progress -- [Valgavoth, Harrower of Souls](https://scryfall.com/search?q=!valgavothharrowerofsouls)
- [ ] In progress -- [Winter, Cynical Opportunist](https://scryfall.com/search?q=!wintercynicalopportunist)
- [ ] In progress -- [Zimone, Mystery Unraveler](https://scryfall.com/search?q=!zimonemysteryunraveler)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"AminatouVeilPiercer"or!"ValgavothHarrowerOfSouls"or!"WinterCynicalOpportunist"or!"ZimoneMysteryUnraveler"&unique=cards)
# Implemented Cards

- [x] Done -- [Archon of Cruelty](https://scryfall.com/search?q=!archonofcruelty)
- [x] Done -- [Crypt Ghast](https://scryfall.com/search?q=!cryptghast)
- [x] Done -- [Damn](https://scryfall.com/search?q=!damn)
- [x] Done -- [Exhume](https://scryfall.com/search?q=!exhume)
- [x] Done -- [Goryo's Vengeance](https://scryfall.com/search?q=!goryosvengeance)
- [x] Done -- [Living Death](https://scryfall.com/search?q=!livingdeath)

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by robertfrosty** [comment]
I'm working on Redress Fate right now, will update after I've tested.

**Comment by MistMan** [comment]
I'd like to see [[The Lord of Pain]] implemented.

**Comment by Callumvl** [comment]
First time contributor, I have made a PR with an attempt at the master of keys

**Comment by mtwilliams14** [comment]
I think I was able to implement Zimone's Hypothesis. I have not been able to test it but I think I was able to create a filter for even/odd power and base most of it off of extinction event. Never done this before so unsure how to test

**Comment by matoro** [comment]
Completed Zimone's Hypothesis in https://github.com/magefree/mage/pull/14296

**Comment by mllagostera** [comment]
PR created for Winter, Cynical Opportunist [#14636](https://github.com/magefree/mage/pull/14636)
