### ISSUE TITLE
DFT - Aetherdrift Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#13033]
This checklist is here to help manage the implementation of Aetherdrift. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards
All cards are implemented
# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Aatchik, Emerald Radian](https://scryfall.com/search?q=Aatchik,+Emerald+Radian)
- [x] Done -- [Adrenaline Jockey](https://scryfall.com/search?q=Adrenaline+Jockey)
- [x] Done -- [Aether Syphon](https://scryfall.com/search?q=Aether+Syphon)
- [x] Done -- [Aetherjacket](https://scryfall.com/search?q=Aetherjacket)
- [x] Done -- [Afterburner Expert](https://scryfall.com/search?q=Afterburner+Expert)
- [x] Done -- [Agonasaur Rex](https://scryfall.com/search?q=Agonasaur+Rex)
- [x] Done -- [Air Response Unit](https://scryfall.com/search?q=Air+Response+Unit)
- [x] Done -- [Alacrian Armory](https://scryfall.com/search?q=Alacrian+Armory)
- [x] Done -- [Alacrian Jaguar](https://scryfall.com/search?q=Alacrian+Jaguar)
- [x] Done -- [Amonkhet Raceway](https://scryfall.com/search?q=Amonkhet+Raceway)
- [x] Done -- [Ancient Vendetta](https://scryfall.com/search?q=Ancient+Vendetta)
- [x] Done -- [Apocalypse Runner](https://scryfall.com/search?q=Apocalypse+Runner)
- [x] Done -- [Autarch Mammoth](https://scryfall.com/search?q=Autarch+Mammoth)
- [x] Done -- [Avishkar Raceway](https://scryfall.com/search?q=Avishkar+Raceway)
- [x] Done -- [Back on Track](https://scryfall.com/search?q=Back+on+Track)
- [x] Done -- [Basri, Tomorrow's Champion](https://scryfall.com/search?q=Basri,+Tomorrow's+Champion)
- [x] Done -- [Beastrider Vanguard](https://scryfall.com/search?q=Beastrider+Vanguard)
- [x] Done -- [Bestow Greatness](https://scryfall.com/search?q=Bestow+Greatness)
- [x] Done -- [Bleachbone Verge](https://scryfall.com/search?q=Bleachbone+Verge)
- [x] Done -- [Bloodfell Caves](https://scryfall.com/search?q=Bloodfell+Caves)
- [x] Done -- [Bloodghast](https://scryfall.com/search?q=Bloodghast)
- [x] Done -- [Blossoming Sands](https://scryfall.com/search?q=Blossoming+Sands)
- [x] Done -- [Boom Scholar](https://scryfall.com/search?q=Boom+Scholar)
- [x] Done -- [Boommobile](https://scryfall.com/search?q=Boommobile)
- [x] Done -- [Boosted Sloop](https://scryfall.com/search?q=Boosted+Sloop)
- [x] Done -- [Bounce Off](https://scryfall.com/search?q=Bounce+Off)
- [x] Done -- [Brightfield Glider](https://scryfall.com/search?q=Brightfield+Glider)
- [x] Done -- [Brightfield Mustang](https://scryfall.com/search?q=Brightfield+Mustang)
- [x] Done -- [Brightglass Gearhulk](https://scryfall.com/search?q=Brightglass+Gearhulk)
- [x] Done -- [Broadcast Rambler](https://scryfall.com/search?q=Broadcast+Rambler)
- [x] Done -- [Broadside Barrage](https://scryfall.com/search?q=Broadside+Barrage)
- [x] Done -- [Broken Wings](https://scryfall.com/search?q=Broken+Wings)
- [x] Done -- [Broodheart Engine](https://scryfall.com/search?q=Broodheart+Engine)
- [x] Done -- [Bulwark Ox](https://scryfall.com/search?q=Bulwark+Ox)
- [x] Done -- [Burner Rocket](https://scryfall.com/search?q=Burner+Rocket)
- [x] Done -- [Burnout Bashtronaut](https://scryfall.com/search?q=Burnout+Bashtronaut)
- [x] Done -- [Caelorna, Coral Tyrant](https://scryfall.com/search?q=Caelorna,+Coral+Tyrant)
- [x] Done -- [Camera Launcher](https://scryfall.com/search?q=Camera+Launcher)
- [x] Done -- [Canyon Vaulter](https://scryfall.com/search?q=Canyon+Vaulter)
- [x] Done -- [Captain Howler, Sea Scourge](https://scryfall.com/search?q=Captain+Howler,+Sea+Scourge)
- [x] Done -- [Caradora, Heart of Alacria](https://scryfall.com/search?q=Caradora,+Heart+of+Alacria)
- [x] Done -- [Carrion Cruiser](https://scryfall.com/search?q=Carrion+Cruiser)
- [x] Done -- [Chandra, Spark Hunter](https://scryfall.com/search?q=Chandra,+Spark+Hunter)
- [x] Done -- [Chitin Gravestalker](https://scryfall.com/search?q=Chitin+Gravestalker)
- [x] Done -- [Clamorous Ironclad](https://scryfall.com/search?q=Clamorous+Ironclad)
- [x] Done -- [Cloudspire Captain](https://scryfall.com/search?q=Cloudspire+Captain)
- [x] Done -- [Cloudspire Coordinator](https://scryfall.com/search?q=Cloudspire+Coordinator)
- [x] Done -- [Cloudspire Skycycle](https://scryfall.com/search?q=Cloudspire+Skycycle)
- [x] Done -- [Coalstoke Gearhulk](https://scryfall.com/search?q=Coalstoke+Gearhulk)
- [x] Done -- [Collision Course](https://scryfall.com/search?q=Collision+Course)
- [x] Done -- [Count on Luck](https://scryfall.com/search?q=Count+on+Luck)
- [x] Done -- [Country Roads](https://scryfall.com/search?q=Country+Roads)
- [x] Done -- [Crash and Burn](https://scryfall.com/search?q=Crash+and+Burn)
- [x] Done -- [Cryptcaller Chariot](https://scryfall.com/search?q=Cryptcaller+Chariot)
- [x] Done -- [Cursecloth Wrappings](https://scryfall.com/search?q=Cursecloth+Wrappings)
- [x] Done -- [Daretti, Rocketeer Engineer](https://scryfall.com/search?q=Daretti,+Rocketeer+Engineer)
- [x] Done -- [Daring Mechanic](https://scryfall.com/search?q=Daring+Mechanic)
- [x] Done -- [Deathless Pilot](https://scryfall.com/search?q=Deathless+Pilot)
- [x] Done -- [Debris Beetle](https://scryfall.com/search?q=Debris+Beetle)
- [x] Done -- [Defend the Rider](https://scryfall.com/search?q=Defend+the+Rider)
- [x] Done -- [Demonic Junker](https://scryfall.com/search?q=Demonic+Junker)
- [x] Done -- [Detention Chariot](https://scryfall.com/search?q=Detention+Chariot)
- [x] Done -- [Dismal Backwater](https://scryfall.com/search?q=Dismal+Backwater)
- [x] Done -- [District Mascot](https://scryfall.com/search?q=District+Mascot)
- [x] Done -- [Diversion Unit](https://scryfall.com/search?q=Diversion+Unit)
- [x] Done -- [Draconautics Engineer](https://scryfall.com/search?q=Draconautics+Engineer)
- [x] Done -- [Dracosaur Auxiliary](https://scryfall.com/search?q=Dracosaur+Auxiliary)
- [x] Done -- [Dredger's Insight](https://scryfall.com/search?q=Dredger's+Insight)
- [x] Done -- [Dune Drifter](https://scryfall.com/search?q=Dune+Drifter)
- [x] Done -- [Dynamite Diver](https://scryfall.com/search?q=Dynamite+Diver)
- [x] Done -- [Earthrumbler](https://scryfall.com/search?q=Earthrumbler)
- [x] Done -- [Elvish Refueler](https://scryfall.com/search?q=Elvish+Refueler)
- [x] Done -- [Embalmed Ascendant](https://scryfall.com/search?q=Embalmed+Ascendant)
- [x] Done -- [Endrider Catalyzer](https://scryfall.com/search?q=Endrider+Catalyzer)
- [x] Done -- [Endrider Spikespitter](https://scryfall.com/search?q=Endrider+Spikespitter)
- [x] Done -- [Engine Rat](https://scryfall.com/search?q=Engine+Rat)
- [x] Done -- [Explosive Getaway](https://scryfall.com/search?q=Explosive+Getaway)
- [x] Done -- [Fang Guardian](https://scryfall.com/search?q=Fang+Guardian)
- [x] Done -- [Fang-Druid Summoner](https://scryfall.com/search?q=Fang-Druid+Summoner)
- [x] Done -- [Far Fortune, End Boss](https://scryfall.com/search?q=Far+Fortune,+End+Boss)
- [x] Done -- [Fearless Swashbuckler](https://scryfall.com/search?q=Fearless+Swashbuckler)
- [x] Done -- [Flood the Engine](https://scryfall.com/search?q=Flood+the+Engine)
- [x] Done -- [Foul Roads](https://scryfall.com/search?q=Foul+Roads)
- [x] Done -- [Fuel the Flames](https://scryfall.com/search?q=Fuel+the+Flames)
- [x] Done -- [Full Throttle](https://scryfall.com/search?q=Full+Throttle)
- [x] Done -- [Gallant Strike](https://scryfall.com/search?q=Gallant+Strike)
- [x] Done -- [Gas Guzzler](https://scryfall.com/search?q=Gas+Guzzler)
- [x] Done -- [Gastal Blockbuster](https://scryfall.com/search?q=Gastal+Blockbuster)
- [x] Done -- [Gastal Raider](https://scryfall.com/search?q=Gastal+Raider)
- [x] Done -- [Gastal Thrillroller](https://scryfall.com/search?q=Gastal+Thrillroller)
- [x] Done -- [Gastal Thrillseeker](https://scryfall.com/search?q=Gastal+Thrillseeker)
- [x] Done -- [Gearseeker Serpent](https://scryfall.com/search?q=Gearseeker+Serpent)
- [x] Done -- [Gilded Ghoda](https://scryfall.com/search?q=Gilded+Ghoda)
- [x] Done -- [Glitch Ghost Surveyor](https://scryfall.com/search?q=Glitch+Ghost+Surveyor)
- [x] Done -- [Gloryheath Lynx](https://scryfall.com/search?q=Gloryheath+Lynx)
- [x] Done -- [Goblin Surveyor](https://scryfall.com/search?q=Goblin+Surveyor)
- [x] Done -- [Gonti, Night Minister](https://scryfall.com/search?q=Gonti,+Night+Minister)
- [x] Done -- [Greasewrench Goblin](https://scryfall.com/search?q=Greasewrench+Goblin)
- [x] Done -- [Greenbelt Guardian](https://scryfall.com/search?q=Greenbelt+Guardian)
- [x] Done -- [Grim Bauble](https://scryfall.com/search?q=Grim+Bauble)
- [x] Done -- [Grim Javelineer](https://scryfall.com/search?q=Grim+Javelineer)
- [x] Done -- [Guardian Sunmare](https://scryfall.com/search?q=Guardian+Sunmare)
- [x] Done -- [Guidelight Matrix](https://scryfall.com/search?q=Guidelight+Matrix)
- [x] Done -- [Guidelight Optimizer](https://scryfall.com/search?q=Guidelight+Optimizer)
- [x] Done -- [Guidelight Pathmaker](https://scryfall.com/search?q=Guidelight+Pathmaker)
- [x] Done -- [Guidelight Synergist](https://scryfall.com/search?q=Guidelight+Synergist)
- [x] Done -- [Haunt the Network](https://scryfall.com/search?q=Haunt+the+Network)
- [x] Done -- [Haunted Hellride](https://scryfall.com/search?q=Haunted+Hellride)
- [x] Done -- [Hazard of the Dunes](https://scryfall.com/search?q=Hazard+of+the+Dunes)
- [x] Done -- [Hazoret, Godseeker](https://scryfall.com/search?q=Hazoret,+Godseeker)
- [x] Done -- [Hellish Sideswipe](https://scryfall.com/search?q=Hellish+Sideswipe)
- [x] Done -- [Hour of Victory](https://scryfall.com/search?q=Hour+of+Victory)
- [x] Done -- [Howler's Heavy](https://scryfall.com/search?q=Howler's+Heavy)
- [x] Done -- [Howlsquad Heavy](https://scryfall.com/search?q=Howlsquad+Heavy)
- [x] Done -- [Hulldrifter](https://scryfall.com/search?q=Hulldrifter)
- [x] Done -- [Interface Ace](https://scryfall.com/search?q=Interface+Ace)
- [x] Done -- [Intimidation Tactics](https://scryfall.com/search?q=Intimidation+Tactics)
- [x] Done -- [Jibbirik Omnivore](https://scryfall.com/search?q=Jibbirik+Omnivore)
- [x] Done -- [Jungle Hollow](https://scryfall.com/search?q=Jungle+Hollow)
- [x] Done -- [Kalakscion, Hunger Tyrant](https://scryfall.com/search?q=Kalakscion,+Hunger+Tyrant)
- [x] Done -- [Keen Buccaneer](https://scryfall.com/search?q=Keen+Buccaneer)
- [x] Done -- [Ketramose, the New Dawn](https://scryfall.com/search?q=Ketramose,+the+New+Dawn)
- [x] Done -- [Kickoff Celebrations](https://scryfall.com/search?q=Kickoff+Celebrations)
- [x] Done -- [Kolodin, Triumph Caster](https://scryfall.com/search?q=Kolodin,+Triumph+Caster)
- [x] Done -- [Lagorin, Soul of Alacria](https://scryfall.com/search?q=Lagorin,+Soul+of+Alacria)
- [x] Done -- [Leonin Surveyor](https://scryfall.com/search?q=Leonin+Surveyor)
- [x] Done -- [Lifecraft Engine](https://scryfall.com/search?q=Lifecraft+Engine)
- [x] Done -- [Lightning Strike](https://scryfall.com/search?q=Lightning+Strike)
- [x] Done -- [Lightshield Parry](https://scryfall.com/search?q=Lightshield+Parry)
- [x] Done -- [Lightwheel Enhancements](https://scryfall.com/search?q=Lightwheel+Enhancements)
- [x] Done -- [Locust Spray](https://scryfall.com/search?q=Locust+Spray)
- [x] Done -- [Loot, the Pathfinder](https://scryfall.com/search?q=Loot,+the+Pathfinder)
- [x] Done -- [Lotusguard Disciple](https://scryfall.com/search?q=Lotusguard+Disciple)
- [x] Done -- [Loxodon Surveyor](https://scryfall.com/search?q=Loxodon+Surveyor)
- [x] Done -- [Lumbering Worldwagon](https://scryfall.com/search?q=Lumbering+Worldwagon)
- [x] Done -- [Magmakin Artillerist](https://scryfall.com/search?q=Magmakin+Artillerist)
- [x] Done -- [Marauding Mako](https://scryfall.com/search?q=Marauding+Mako)
- [x] Done -- [March of the World Ooze](https://scryfall.com/search?q=March+of+the+World+Ooze)
- [x] Done -- [Marketback Walker](https://scryfall.com/search?q=Marketback+Walker)
- [x] Done -- [Marshals' Pathcruiser](https://scryfall.com/search?q=Marshals'+Pathcruiser)
- [x] Done -- [Maximum Overdrive](https://scryfall.com/search?q=Maximum+Overdrive)
- [x] Done -- [Memory Guardian](https://scryfall.com/search?q=Memory+Guardian)
- [x] Done -- [Mendicant Core, Guidelight](https://scryfall.com/search?q=Mendicant+Core,+Guidelight)
- [x] Done -- [Midnight Mangler](https://scryfall.com/search?q=Midnight+Mangler)
- [x] Done -- [Migrating Ketradon](https://scryfall.com/search?q=Migrating+Ketradon)
- [x] Done -- [Mimeoplasm, Revered One](https://scryfall.com/search?q=Mimeoplasm,+Revered+One)
- [x] Done -- [Mindspring Merfolk](https://scryfall.com/search?q=Mindspring+Merfolk)
- [x] Done -- [Molt Tender](https://scryfall.com/search?q=Molt+Tender)
- [x] Done -- [Momentum Breaker](https://scryfall.com/search?q=Momentum+Breaker)
- [x] Done -- [Monument to Endurance](https://scryfall.com/search?q=Monument+to+Endurance)
- [x] Done -- [Mu Yanling, Wind Rider](https://scryfall.com/search?q=Mu+Yanling,+Wind+Rider)
- [x] Done -- [Muraganda Raceway](https://scryfall.com/search?q=Muraganda+Raceway)
- [x] Done -- [Mutant Surveyor](https://scryfall.com/search?q=Mutant+Surveyor)
- [x] Done -- [Nesting Bot](https://scryfall.com/search?q=Nesting+Bot)
- [x] Done -- [Night Market](https://scryfall.com/search?q=Night+Market)
- [x] Done -- [Nimble Thopterist](https://scryfall.com/search?q=Nimble+Thopterist)
- [x] Done -- [Oildeep Gearhulk](https://scryfall.com/search?q=Oildeep+Gearhulk)
- [x] Done -- [Ooze Patrol](https://scryfall.com/search?q=Ooze+Patrol)
- [x] Done -- [Outpace Oblivion](https://scryfall.com/search?q=Outpace+Oblivion)
- [x] Done -- [Oviya, Automech Artisan](https://scryfall.com/search?q=Oviya,+Automech+Artisan)
- [x] Done -- [Pacesetter Paragon](https://scryfall.com/search?q=Pacesetter+Paragon)
- [x] Done -- [Pactdoll Terror](https://scryfall.com/search?q=Pactdoll+Terror)
- [x] Done -- [Pedal to the Metal](https://scryfall.com/search?q=Pedal+to+the+Metal)
- [x] Done -- [Perilous Snare](https://scryfall.com/search?q=Perilous+Snare)
- [x] Done -- [Pit Automaton](https://scryfall.com/search?q=Pit+Automaton)
- [x] Done -- [Plow Through](https://scryfall.com/search?q=Plow+Through)
- [x] Done -- [Point the Way](https://scryfall.com/search?q=Point+the+Way)
- [x] Done -- [Possession Engine](https://scryfall.com/search?q=Possession+Engine)
- [x] Done -- [Pothole Mole](https://scryfall.com/search?q=Pothole+Mole)
- [x] Done -- [Pride of the Road](https://scryfall.com/search?q=Pride+of+the+Road)
- [x] Done -- [Prowcatcher Specialist](https://scryfall.com/search?q=Prowcatcher+Specialist)
- [x] Done -- [Push the Limit](https://scryfall.com/search?q=Push+the+Limit)
- [x] Done -- [Pyrewood Gearhulk](https://scryfall.com/search?q=Pyrewood+Gearhulk)
- [x] Done -- [Quag Feast](https://scryfall.com/search?q=Quag+Feast)
- [x] Done -- [Racers' Scoreboard](https://scryfall.com/search?q=Racers'+Scoreboard)
- [x] Done -- [Radiant Lotus](https://scryfall.com/search?q=Radiant+Lotus)
- [x] Done -- [Rangers' Aetherhive](https://scryfall.com/search?q=Rangers'+Aetherhive)
- [x] Done -- [Rangers' Refueler](https://scryfall.com/search?q=Rangers'+Refueler)
- [x] Done -- [Reckless Velocitaur](https://scryfall.com/search?q=Reckless+Velocitaur)
- [x] Done -- [Redshift, Rocketeer Chief](https://scryfall.com/search?q=Redshift,+Rocketeer+Chief)
- [x] Done -- [Reef Roads](https://scryfall.com/search?q=Reef+Roads)
- [x] Done -- [Regal Imperiosaur](https://scryfall.com/search?q=Regal+Imperiosaur)
- [x] Done -- [Repurposing Bay](https://scryfall.com/search?q=Repurposing+Bay)
- [x] Done -- [Ride's End](https://scryfall.com/search?q=Ride's+End)
- [x] Done -- [Ripclaw Wrangler](https://scryfall.com/search?q=Ripclaw+Wrangler)
- [x] Done -- [Riptide Gearhulk](https://scryfall.com/search?q=Riptide+Gearhulk)
- [x] Done -- [Rise from the Wreck](https://scryfall.com/search?q=Rise+from+the+Wreck)
- [x] Done -- [Risen Necroregent](https://scryfall.com/search?q=Risen+Necroregent)
- [x] Done -- [Risky Shortcut](https://scryfall.com/search?q=Risky+Shortcut)
- [x] Done -- [Riverchurn Monument](https://scryfall.com/search?q=Riverchurn+Monument)
- [x] Done -- [Riverpyre Verge](https://scryfall.com/search?q=Riverpyre+Verge)
- [x] Done -- [Road Rage](https://scryfall.com/search?q=Road+Rage)
- [x] Done -- [Roadside Assistance](https://scryfall.com/search?q=Roadside+Assistance)
- [x] Done -- [Roadside Blowout](https://scryfall.com/search?q=Roadside+Blowout)
- [x] Done -- [Rocketeer Boostbuggy](https://scryfall.com/search?q=Rocketeer+Boostbuggy)
- [x] Done -- [Rocky Roads](https://scryfall.com/search?q=Rocky+Roads)
- [x] Done -- [Rover Blades](https://scryfall.com/search?q=Rover+Blades)
- [x] Done -- [Rugged Highlands](https://scryfall.com/search?q=Rugged+Highlands)
- [x] Done -- [Run Over](https://scryfall.com/search?q=Run+Over)
- [x] Done -- [Sab-Sunen, Luxa Embodied](https://scryfall.com/search?q=Sab-Sunen,+Luxa+Embodied)
- [x] Done -- [Sabotage Strategist](https://scryfall.com/search?q=Sabotage+Strategist)
- [x] Done -- [Salvation Engine](https://scryfall.com/search?q=Salvation+Engine)
- [x] Done -- [Samut, the Driving Force](https://scryfall.com/search?q=Samut,+the+Driving+Force)
- [x] Done -- [Scoured Barrens](https://scryfall.com/search?q=Scoured+Barrens)
- [x] Done -- [Scrap Compactor](https://scryfall.com/search?q=Scrap+Compactor)
- [x] Done -- [Scrounging Skyray](https://scryfall.com/search?q=Scrounging+Skyray)
- [x] Done -- [Shefet Archfiend](https://scryfall.com/search?q=Shefet+Archfiend)
- [x] Done -- [Silken Strength](https://scryfall.com/search?q=Silken+Strength)
- [x] Done -- [Sita Varma, Masked Racer](https://scryfall.com/search?q=Sita+Varma,+Masked+Racer)
- [x] Done -- [Skybox Ferry](https://scryfall.com/search?q=Skybox+Ferry)
- [x] Done -- [Skycrash](https://scryfall.com/search?q=Skycrash)
- [x] Done -- [Skyseer's Chariot](https://scryfall.com/search?q=Skyseer's+Chariot)
- [x] Done -- [Skyserpent Seeker](https://scryfall.com/search?q=Skyserpent+Seeker)
- [x] Done -- [Skystreak Engineer](https://scryfall.com/search?q=Skystreak+Engineer)
- [x] Done -- [Slick Imitator](https://scryfall.com/search?q=Slick+Imitator)
- [x] Done -- [Spectacular Pileup](https://scryfall.com/search?q=Spectacular+Pileup)
- [x] Done -- [Spectral Interference](https://scryfall.com/search?q=Spectral+Interference)
- [x] Done -- [Spell Pierce](https://scryfall.com/search?q=Spell+Pierce)
- [x] Done -- [Spikeshell Harrier](https://scryfall.com/search?q=Spikeshell+Harrier)
- [x] Done -- [Spin Out](https://scryfall.com/search?q=Spin+Out)
- [x] Done -- [Spire Mechcycle](https://scryfall.com/search?q=Spire+Mechcycle)
- [x] Done -- [Spotcycle Scouter](https://scryfall.com/search?q=Spotcycle+Scouter)
- [x] Done -- [Stall Out](https://scryfall.com/search?q=Stall+Out)
- [x] Done -- [Stampeding Scurryfoot](https://scryfall.com/search?q=Stampeding+Scurryfoot)
- [x] Done -- [Starting Column](https://scryfall.com/search?q=Starting+Column)
- [x] Done -- [Stock Up](https://scryfall.com/search?q=Stock+Up)
- [x] Done -- [Streaking Oilgorger](https://scryfall.com/search?q=Streaking+Oilgorger)
- [x] Done -- [Sunbillow Verge](https://scryfall.com/search?q=Sunbillow+Verge)
- [x] Done -- [Sundial, Dawn Tyrant](https://scryfall.com/search?q=Sundial,+Dawn+Tyrant)
- [x] Done -- [Swiftwater Cliffs](https://scryfall.com/search?q=Swiftwater+Cliffs)
- [x] Done -- [Swiftwing Assailant](https://scryfall.com/search?q=Swiftwing+Assailant)
- [x] Done -- [Syphon Fuel](https://scryfall.com/search?q=Syphon+Fuel)
- [x] Done -- [Terrian, World Tyrant](https://scryfall.com/search?q=Terrian,+World+Tyrant)
- [x] Done -- [The Aetherspark](https://scryfall.com/search?q=The+Aetherspark)
- [x] Done -- [The Last Ride](https://scryfall.com/search?q=The+Last+Ride)
- [x] Done -- [The Speed Demon](https://scryfall.com/search?q=The+Speed+Demon)
- [x] Done -- [Thopter Fabricator](https://scryfall.com/search?q=Thopter+Fabricator)
- [x] Done -- [Thornwood Falls](https://scryfall.com/search?q=Thornwood+Falls)
- [x] Done -- [Thunderhead Gunner](https://scryfall.com/search?q=Thunderhead+Gunner)
- [x] Done -- [Thundering Broodwagon](https://scryfall.com/search?q=Thundering+Broodwagon)
- [x] Done -- [Thunderous Velocipede](https://scryfall.com/search?q=Thunderous+Velocipede)
- [x] Done -- [Ticket Tortoise](https://scryfall.com/search?q=Ticket+Tortoise)
- [x] Done -- [Trade the Helm](https://scryfall.com/search?q=Trade+the+Helm)
- [x] Done -- [Tranquil Cove](https://scryfall.com/search?q=Tranquil+Cove)
- [x] Done -- [Transit Mage](https://scryfall.com/search?q=Transit+Mage)
- [x] Done -- [Trip Up](https://scryfall.com/search?q=Trip+Up)
- [x] Done -- [Tune Up](https://scryfall.com/search?q=Tune+Up)
- [x] Done -- [Tyrox, Saurid Tyrant](https://scryfall.com/search?q=Tyrox,+Saurid+Tyrant)
- [x] Done -- [Unstoppable Plan](https://scryfall.com/search?q=Unstoppable+Plan)
- [x] Done -- [Unswerving Sloth](https://scryfall.com/search?q=Unswerving+Sloth)
- [x] Done -- [Valor's Flagship](https://scryfall.com/search?q=Valor's+Flagship)
- [x] Done -- [Veloheart Bike](https://scryfall.com/search?q=Veloheart+Bike)
- [x] Done -- [Venomsac Lagac](https://scryfall.com/search?q=Venomsac+Lagac)
- [x] Done -- [Veteran Beastrider](https://scryfall.com/search?q=Veteran+Beastrider)
- [x] Done -- [Vnwxt, Verbose Host](https://scryfall.com/search?q=Vnwxt,+Verbose+Host)
- [x] Done -- [Voyage Home](https://scryfall.com/search?q=Voyage+Home)
- [x] Done -- [Voyager Glidecar](https://scryfall.com/search?q=Voyager+Glidecar)
- [x] Done -- [Voyager Quickwelder](https://scryfall.com/search?q=Voyager+Quickwelder)
- [x] Done -- [Walking Sarcophagus](https://scryfall.com/search?q=Walking+Sarcophagus)
- [x] Done -- [Wastewood Verge](https://scryfall.com/search?q=Wastewood+Verge)
- [x] Done -- [Waxen Shapethief](https://scryfall.com/search?q=Waxen+Shapethief)
- [x] Done -- [Webstrike Elite](https://scryfall.com/search?q=Webstrike+Elite)
- [x] Done -- [Wickerfolk Indomitable](https://scryfall.com/search?q=Wickerfolk+Indomitable)
- [x] Done -- [Wild Roads](https://scryfall.com/search?q=Wild+Roads)
- [x] Done -- [Willowrush Verge](https://scryfall.com/search?q=Willowrush+Verge)
- [x] Done -- [Wind-Scarred Crag](https://scryfall.com/search?q=Wind-Scarred+Crag)
- [x] Done -- [Winter, Cursed Rider](https://scryfall.com/search?q=Winter,+Cursed+Rider)
- [x] Done -- [Wreck Remover](https://scryfall.com/search?q=Wreck+Remover)
- [x] Done -- [Wreckage Wickerfolk](https://scryfall.com/search?q=Wreckage+Wickerfolk)
- [x] Done -- [Wretched Doll](https://scryfall.com/search?q=Wretched+Doll)
- [x] Done -- [Zahur, Glory's Past](https://scryfall.com/search?q=Zahur,+Glory's+Past)
</details>

**Comment by theelk801** [comment]
Additional tasks:

- [ ] Implement "Start your engines!" mechanic
- [ ] Implement "Exhaust" mechanic

**Comment by Grath** [comment]
Given the accelerated proliferation of additional state tracking - poison, experience, city's blessing, monarch, initiative, day/night, and now speed - might it be reasonable to move some or all of this information to some sort of pop-up window rather than trying to cram it all into the same panel of information about each player? That, or only adding the numeric information (poison, exp, speed) when those numbers become nonzero.

**Comment by JayDi85** [comment]
@Grath current player's speed information can be done by card's icon like `ClassReminderAbility`. Even more -- it can be improved by color change, e.g. 1/2/3 speed as default colored icon, 4 speed as green colored icon

**Comment by JayDi85** [comment]
Card icon with dynamic text example (from `ClassReminderAbility`):

![Image](https://github.com/user-attachments/assets/dde0aece-986d-4105-8e17-a2dc375b158f)

**Comment by tiera3** [comment]
> [@Grath](https://github.com/Grath) player's speed information can be done by card's icon like `ClassReminderAbility`. Even more -- it can be improved by color change, e.g. 1/2/3 speed as default colored icon, 4 speed as green colored icon

If "speed" continues to exist even if the card is lost, then it might be better to put such information in the command zone (like Day/Night, Tempted by the Ring, etc).

**Comment by cauevianna** [comment]
Still coundt find Ketramose, the New Dawn, in deck editor

**Comment by cauevianna** [comment]
Do you know when the next update will be avaliable?
