### ISSUE TITLE
Eternal Masters Oracle update

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2039]
# Oracle

In EMA, there have been the following Oracle changes which will have to be implemented. Functional errata are marked in boldface, and unimplemented cards are omitted.
## Multiple cards
- [x] [Text that referred to “casting cards” now refers to “casting spells”.](http://www.yawgatog.com/resources/oracle-changes/soi-ema/#S0) I've looked at [Alchemist's Refuge](http://magiccards.info/query?q=%21Alchemist's+Refuge) and it uses a nonland card filter to implement this. Should the implementation be changed even though the functionality stays the same? In any case, ability text will have to be updated.
- [x] [Abilities that deal targeted damage equal to some gamestate-derived number have been reworded for clarity.](http://www.yawgatog.com/resources/oracle-changes/soi-ema/#S1) Non-functional errata, ability text needs to be updated.
- [x] [“For the first time in a turn” has been changed to “for the first time each turn”.](http://www.yawgatog.com/resources/oracle-changes/soi-ema/#S2) Non-functional errata, ability text needs to be updated.
## Single card
- [x] [Hamlet Captain](http://magiccards.info/query?q=%21Hamlet+Captain): “Human creatures” → “Humans”
- [x] [Iona's Blessing](http://magiccards.info/query?q=%21Iona's+Bllessing): “can block an additional creature” → “can block an additional creature each combat”
- [x] [Konda, Lord of Eiganjo](http://magiccards.info/query?q=%21Konda,+Lord+of+Eiganjo): vigilance moved before indestructible and reminder text removed
- [x] [Mimic Vat](http://magiccards.info/query?q=%21Mimic+Vat): “the exiled card” → “a card exiled with Mimic Vat”
- [x] [Nature's Cloak](http://magiccards.info/query?q=%21Nature's+Cloak): extra “forestwalk” removed
- [x] ~~[Prey Upon](http://magiccards.info/query?q=%21Prey+Upon): fight reminder text removed~~ reverted in CN2
- [x] [Sakashima's Student](http://magiccards.info/query?q=%21Sakashima's+Student): “still” removed
- [x] [Stormscape Battlemage](http://magiccards.info/query?q=%21Stormscape+Battlemage): kicker reminder text added
- [x] [Sword of Kaldra](http://magiccards.info/query?q=%21): “Exile it only if it's still on the battlefield” reminder text added
- [x] [Winter Orb](http://magiccards.info/query?q=%21Winter+Orb): “As long as Winter Orb is untapped” added (**functional errata**, https://github.com/magefree/mage/commit/b44e2f3cdd2fecfc5e04530d123252a510ab931a)
# Cards

The following cards have been printed in EMA and will have to be implemented.
## Reprints
- [x] [Abundant Growth](https://mtg.wtf/card/ema/156)
- [x] [Ancestral Mask](https://mtg.wtf/card/ema/157)
- [x] [Animate Dead](https://mtg.wtf/card/ema/78)
- [x] [Annihilate](https://mtg.wtf/card/ema/79)
- [x] [Arcanis the Omnipotent](https://mtg.wtf/card/ema/39)
- [x] [Argothian Enchantress](https://mtg.wtf/card/ema/158)
- [x] [Armadillo Cloak](https://mtg.wtf/card/ema/195)
- [x] [Ashnod's Altar](https://mtg.wtf/card/ema/218)
- [x] [Avarax](https://mtg.wtf/card/ema/117)
- [x] [Aven Riftwatcher](https://mtg.wtf/card/ema/1)
- [x] [Balance](https://mtg.wtf/card/ema/2)
- [x] [Baleful Strix](https://mtg.wtf/card/ema/196)
- [x] [Ballynock Cohort](https://mtg.wtf/card/ema/3)
- [x] [Battle Squadron](https://mtg.wtf/card/ema/118)
- [x] [Beetleback Chief](https://mtg.wtf/card/ema/119)
- [x] [Benevolent Bodyguard](https://mtg.wtf/card/ema/4)
- [x] [Blightsoil Druid](https://mtg.wtf/card/ema/80)
- [x] [Blood Artist](https://mtg.wtf/card/ema/81)
- [x] [Bloodbraid Elf](https://mtg.wtf/card/ema/197)
- [x] [Bloodfell Caves](https://mtg.wtf/card/ema/236)
- [x] [Blossoming Sands](https://mtg.wtf/card/ema/237)
- [x] [Borderland Marauder](https://mtg.wtf/card/ema/120)
- [x] [Brago, King Eternal](https://mtg.wtf/card/ema/198)
- [x] [Braids, Cabal Minion](https://mtg.wtf/card/ema/82)
- [x] [Brainstorm](https://mtg.wtf/card/ema/40)
- [x] [Brawn](https://mtg.wtf/card/ema/159)
- [x] [Burning Vengeance](https://mtg.wtf/card/ema/121)
- [x] [Cabal Therapy](https://mtg.wtf/card/ema/83)
- [x] [Calciderm](https://mtg.wtf/card/ema/5)
- [x] [Call the Skybreaker](https://mtg.wtf/card/ema/214)
- [x] [Carbonize](https://mtg.wtf/card/ema/122)
- [x] [Carrion Feeder](https://mtg.wtf/card/ema/84)
- [x] [Centaur Chieftain](https://mtg.wtf/card/ema/160)
- [x] [Cephalid Sage](https://mtg.wtf/card/ema/41)
- [x] [Chain Lightning](https://mtg.wtf/card/ema/123)
- [x] [Chrome Mox](https://mtg.wtf/card/ema/219)
- [x] [Civic Wayfinder](https://mtg.wtf/card/ema/161)
- [x] [Coalition Honor Guard](https://mtg.wtf/card/ema/6)
- [x] [Commune with the Gods](https://mtg.wtf/card/ema/162)
- [x] [Control Magic](https://mtg.wtf/card/ema/42)
- [x] [Counterspell](https://mtg.wtf/card/ema/43)
- [x] [Crater Hellion](https://mtg.wtf/card/ema/124)
- [x] [Dack Fayden](https://mtg.wtf/card/ema/199)
- [x] [Daze](https://mtg.wtf/card/ema/44)
- [x] [Deadbridge Shaman](https://mtg.wtf/card/ema/85)
- [x] [Deathrite Shaman](https://mtg.wtf/card/ema/215)
- [x] [Deep Analysis](https://mtg.wtf/card/ema/45)
- [x] [Desperate Ravings](https://mtg.wtf/card/ema/125)
- [x] [Diminishing Returns](https://mtg.wtf/card/ema/46)
- [x] [Dismal Backwater](https://mtg.wtf/card/ema/238)
- [x] [Dragon Egg](https://mtg.wtf/card/ema/126)
- [x] [Dream Twist](https://mtg.wtf/card/ema/47)
- [x] [Dualcaster Mage](https://mtg.wtf/card/ema/127)
- [x] [Duplicant](https://mtg.wtf/card/ema/220)
- [x] [Duress](https://mtg.wtf/card/ema/86)
- [x] [Eight-and-a-Half-Tails](https://mtg.wtf/card/ema/7)
- [x] [Elephant Guide](https://mtg.wtf/card/ema/163)
- [x] [Elite Vanguard](https://mtg.wtf/card/ema/8)
- [x] [Elvish Vanguard](https://mtg.wtf/card/ema/164)
- [x] [Emmessi Tome](https://mtg.wtf/card/ema/221)
- [x] [Emperor Crocodile](https://mtg.wtf/card/ema/165)
- [x] [Enlightened Tutor](https://mtg.wtf/card/ema/9)
- [x] [Entomb](https://mtg.wtf/card/ema/87)
- [x] [Extract from Darkness](https://mtg.wtf/card/ema/200)
- [x] [Eyeblight's Ending](https://mtg.wtf/card/ema/88)
- [x] [Fact or Fiction](https://mtg.wtf/card/ema/48)
- [x] [Faith's Fetters](https://mtg.wtf/card/ema/10)
- [x] [Faithless Looting](https://mtg.wtf/card/ema/128)
- [x] [Fervent Cathar](https://mtg.wtf/card/ema/129)
- [x] [Field of Souls](https://mtg.wtf/card/ema/11)
- [x] [Firebolt](https://mtg.wtf/card/ema/130)
- [x] [Flame Jab](https://mtg.wtf/card/ema/131)
- [x] [Flame-Kin Zealot](https://mtg.wtf/card/ema/201)
- [x] [Flinthoof Boar](https://mtg.wtf/card/ema/166)
- [x] [Fog](https://mtg.wtf/card/ema/167)
- [x] [Force of Will](https://mtg.wtf/card/ema/49)
- [x] [Future Sight](https://mtg.wtf/card/ema/50)
- [x] [Gaea's Blessing](https://mtg.wtf/card/ema/168)
- [x] [Gamble](https://mtg.wtf/card/ema/132)
- [x] [Gaseous Form](https://mtg.wtf/card/ema/51)
- [x] [Ghitu Slinger](https://mtg.wtf/card/ema/133)
- [x] [Giant Solifuge](https://mtg.wtf/card/ema/216)
- [x] [Giant Tortoise](https://mtg.wtf/card/ema/52)
- [x] [Glacial Wall](https://mtg.wtf/card/ema/53)
- [x] [Glare of Subdual](https://mtg.wtf/card/ema/202)
- [x] [Glimmerpoint Stag](https://mtg.wtf/card/ema/12)
- [x] [Goblin Charbelcher](https://mtg.wtf/card/ema/222)
- [x] [Goblin Trenches](https://mtg.wtf/card/ema/203)
- [x] [Gravedigger](https://mtg.wtf/card/ema/89)
- [x] [Green Sun's Zenith](https://mtg.wtf/card/ema/169)
- [x] [Harmonize](https://mtg.wtf/card/ema/170)
- [x] [Havoc Demon](https://mtg.wtf/card/ema/90)
- [x] [Heritage Druid](https://mtg.wtf/card/ema/171)
- [x] [Honden of Cleansing Fire](https://mtg.wtf/card/ema/13)
- [x] [Honden of Infinite Rage](https://mtg.wtf/card/ema/134)
- [x] [Honden of Life's Web](https://mtg.wtf/card/ema/172)
- [x] [Honden of Night's Reach](https://mtg.wtf/card/ema/91)
- [x] [Honden of Seeing Winds](https://mtg.wtf/card/ema/54)
- [x] [Humble](https://mtg.wtf/card/ema/14)
- [x] [Hydroblast](https://mtg.wtf/card/ema/55)
- [x] [Hymn to Tourach](https://mtg.wtf/card/ema/92)
- [x] [Ichorid](https://mtg.wtf/card/ema/93)
- [x] [Imperious Perfect](https://mtg.wtf/card/ema/173)
- [x] [Inkwell Leviathan](https://mtg.wtf/card/ema/56)
- [x] [Innocent Blood](https://mtg.wtf/card/ema/94)
- [x] [Intangible Virtue](https://mtg.wtf/card/ema/15)
- [x] [Invigorate](https://mtg.wtf/card/ema/174)
- [x] [Isochron Scepter](https://mtg.wtf/card/ema/223)
- [x] [Jace, the Mind Sculptor](https://mtg.wtf/card/ema/57)
- [x] [Jareth, Leonine Titan](https://mtg.wtf/card/ema/16)
- [x] [Jetting Glasskite](https://mtg.wtf/card/ema/58)
- [x] [Juggernaut](https://mtg.wtf/card/ema/224)
- [x] [Jungle Hollow](https://mtg.wtf/card/ema/239)
- [x] [Karakas](https://mtg.wtf/card/ema/240)
- [x] [Karmic Guide](https://mtg.wtf/card/ema/17)
- [x] [Keldon Champion](https://mtg.wtf/card/ema/135)
- [x] [Keldon Marauders](https://mtg.wtf/card/ema/136)
- [x] [Kird Ape](https://mtg.wtf/card/ema/137)
- [x] [Kor Hookmaster](https://mtg.wtf/card/ema/18)
- [x] [Llanowar Elves](https://mtg.wtf/card/ema/175)
- [x] [Lys Alana Huntmaster](https://mtg.wtf/card/ema/176)
- [x] [Lys Alana Scarblade](https://mtg.wtf/card/ema/95)
- [x] [Maelstrom Wanderer](https://mtg.wtf/card/ema/204)
- [x] [Malicious Affliction](https://mtg.wtf/card/ema/96)
- [x] [Man-o'-War](https://mtg.wtf/card/ema/59)
- [x] [Mana Crypt](https://mtg.wtf/card/ema/225)
- [x] [Maze of Ith](https://mtg.wtf/card/ema/241)
- [x] [Memory Lapse](https://mtg.wtf/card/ema/60)
- [x] [Merfolk Looter](https://mtg.wtf/card/ema/61)
- [x] [Mesa Enchantress](https://mtg.wtf/card/ema/19)
- [x] [Millikin](https://mtg.wtf/card/ema/226)
- [x] [Mindless Automaton](https://mtg.wtf/card/ema/227)
- [x] [Mishra's Factory](https://mtg.wtf/card/ema/242)
- [x] [Mistral Charger](https://mtg.wtf/card/ema/20)
- [x] [Mogg Fanatic](https://mtg.wtf/card/ema/138)
- [x] [Mogg War Marshal](https://mtg.wtf/card/ema/139)
- [x] [Monk Idealist](https://mtg.wtf/card/ema/21)
- [x] [Mother of Runes](https://mtg.wtf/card/ema/22)
- [x] [Mystical Tutor](https://mtg.wtf/card/ema/62)
- [x] [Natural Order](https://mtg.wtf/card/ema/177)
- [x] [Nature's Claim](https://mtg.wtf/card/ema/178)
- [x] [Nausea](https://mtg.wtf/card/ema/97)
- [x] [Necropotence](https://mtg.wtf/card/ema/98)
- [x] [Nekrataal](https://mtg.wtf/card/ema/99)
- [x] [Nevinyrral's Disk](https://mtg.wtf/card/ema/228)
- [x] [Night's Whisper](https://mtg.wtf/card/ema/100)
- [x] [Nimble Mongoose](https://mtg.wtf/card/ema/179)
- [x] [Oona's Grace](https://mtg.wtf/card/ema/63)
- [x] [Orcish Oriflamme](https://mtg.wtf/card/ema/140)
- [x] [Pacifism](https://mtg.wtf/card/ema/23)
- [x] [Peregrine Drake](https://mtg.wtf/card/ema/64)
- [x] [Phantom Monster](https://mtg.wtf/card/ema/65)
- [x] [Phyrexian Gargantua](https://mtg.wtf/card/ema/101)
- [x] [Phyrexian Ingester](https://mtg.wtf/card/ema/66)
- [x] [Phyrexian Rager](https://mtg.wtf/card/ema/102)
- [x] [Pilgrim's Eye](https://mtg.wtf/card/ema/229)
- [x] [Plague Witch](https://mtg.wtf/card/ema/103)
- [x] [Price of Progress](https://mtg.wtf/card/ema/141)
- [x] [Prismatic Lens](https://mtg.wtf/card/ema/230)
- [x] [Prodigal Sorcerer](https://mtg.wtf/card/ema/67)
- [x] [Prowling Pangolin](https://mtg.wtf/card/ema/104)
- [x] [Pyroblast](https://mtg.wtf/card/ema/142)
- [x] [Pyrokinesis](https://mtg.wtf/card/ema/143)
- [x] [Quiet Speculation](https://mtg.wtf/card/ema/68)
- [x] [Raise the Alarm](https://mtg.wtf/card/ema/24)
- [x] [Rally the Peasants](https://mtg.wtf/card/ema/25)
- [x] [Rancor](https://mtg.wtf/card/ema/180)
- [x] [Reckless Charge](https://mtg.wtf/card/ema/144)
- [x] [Regal Force](https://mtg.wtf/card/ema/181)
- [x] [Relic of Progenitus](https://mtg.wtf/card/ema/231)
- [x] [Roar of the Wurm](https://mtg.wtf/card/ema/182)
- [x] [Roots](https://mtg.wtf/card/ema/183)
- [x] [Rorix Bladewing](https://mtg.wtf/card/ema/145)
- [x] [Rugged Highlands](https://mtg.wtf/card/ema/243)
- [x] [Scoured Barrens](https://mtg.wtf/card/ema/244)
- [x] [Screeching Skaab](https://mtg.wtf/card/ema/69)
- [x] [Seal of Cleansing](https://mtg.wtf/card/ema/26)
- [x] [Seal of Strength](https://mtg.wtf/card/ema/184)
- [x] [Second Thoughts](https://mtg.wtf/card/ema/27)
- [x] [Seismic Stomp](https://mtg.wtf/card/ema/146)
- [x] [Sengir Autocrat](https://mtg.wtf/card/ema/105)
- [x] [Sensei's Divining Top](https://mtg.wtf/card/ema/232)
- [x] [Sentinel Spider](https://mtg.wtf/card/ema/185)
- [x] [Serendib Efreet](https://mtg.wtf/card/ema/70)
- [x] [Serra Angel](https://mtg.wtf/card/ema/28)
- [x] [Shaman of the Pack](https://mtg.wtf/card/ema/205)
- [x] [Shardless Agent](https://mtg.wtf/card/ema/206)
- [x] [Shelter](https://mtg.wtf/card/ema/29)
- [x] [Shoreline Ranger](https://mtg.wtf/card/ema/71)
- [x] [Siege-Gang Commander](https://mtg.wtf/card/ema/147)
- [x] [Silent Departure](https://mtg.wtf/card/ema/72)
- [x] [Silvos, Rogue Elemental](https://mtg.wtf/card/ema/186)
- [x] [Sinkhole](https://mtg.wtf/card/ema/106)
- [x] [Skulking Ghost](https://mtg.wtf/card/ema/107)
- [x] [Sneak Attack](https://mtg.wtf/card/ema/148)
- [x] [Soulcatcher](https://mtg.wtf/card/ema/30)
- [x] [Sphinx of the Steel Wind](https://mtg.wtf/card/ema/207)
- [x] [Sprite Noble](https://mtg.wtf/card/ema/73)
- [x] [Squadron Hawk](https://mtg.wtf/card/ema/31)
- [x] [Stingscourger](https://mtg.wtf/card/ema/149)
- [x] [Stupefying Touch](https://mtg.wtf/card/ema/74)
- [x] [Sulfuric Vortex](https://mtg.wtf/card/ema/150)
- [x] [Swiftwater Cliffs](https://mtg.wtf/card/ema/245)
- [x] [Swords to Plowshares](https://mtg.wtf/card/ema/32)
- [x] [Sylvan Library](https://mtg.wtf/card/ema/187)
- [x] [Sylvan Might](https://mtg.wtf/card/ema/188)
- [x] [Thornweald Archer](https://mtg.wtf/card/ema/189)
- [x] [Thornwood Falls](https://mtg.wtf/card/ema/246)
- [x] [Thunderclap Wyvern](https://mtg.wtf/card/ema/208)
- [x] [Ticking Gnomes](https://mtg.wtf/card/ema/233)
- [x] [Tidal Wave](https://mtg.wtf/card/ema/75)
- [x] [Timberwatch Elf](https://mtg.wtf/card/ema/190)
- [x] [Tooth and Claw](https://mtg.wtf/card/ema/151)
- [x] [Torrent of Souls](https://mtg.wtf/card/ema/217)
- [x] [Toxic Deluge](https://mtg.wtf/card/ema/108)
- [x] [Tragic Slip](https://mtg.wtf/card/ema/109)
- [x] [Tranquil Cove](https://mtg.wtf/card/ema/247)
- [x] [Trygon Predator](https://mtg.wtf/card/ema/209)
- [x] [Twisted Abomination](https://mtg.wtf/card/ema/110)
- [x] [Undying Rage](https://mtg.wtf/card/ema/152)
- [x] [Unexpectedly Absent](https://mtg.wtf/card/ema/33)
- [x] [Urborg Uprising](https://mtg.wtf/card/ema/111)
- [x] [Vampiric Tutor](https://mtg.wtf/card/ema/112)
- [x] [Victimize](https://mtg.wtf/card/ema/113)
- [x] [Vindicate](https://mtg.wtf/card/ema/210)
- [x] [Visara the Dreadful](https://mtg.wtf/card/ema/114)
- [x] [Void](https://mtg.wtf/card/ema/211)
- [x] [Wake of Vultures](https://mtg.wtf/card/ema/115)
- [x] [Wakedancer](https://mtg.wtf/card/ema/116)
- [x] [Wall of Omens](https://mtg.wtf/card/ema/34)
- [x] [War Priest of Thune](https://mtg.wtf/card/ema/35)
- [x] [Warden of Evos Isle](https://mtg.wtf/card/ema/76)
- [x] [Wasteland](https://mtg.wtf/card/ema/248)
- [x] [Wee Dragonauts](https://mtg.wtf/card/ema/212)
- [x] [Welkin Guide](https://mtg.wtf/card/ema/36)
- [x] [Werebear](https://mtg.wtf/card/ema/191)
- [x] [Whitemane Lion](https://mtg.wtf/card/ema/37)
- [x] [Wildfire Emissary](https://mtg.wtf/card/ema/153)
- [x] [Wind-Scarred Crag](https://mtg.wtf/card/ema/249)
- [x] [Winter Orb](https://mtg.wtf/card/ema/234)
- [x] [Wirewood Symbiote](https://mtg.wtf/card/ema/192)
- [x] [Wonder](https://mtg.wtf/card/ema/77)
- [x] [Worldgorger Dragon](https://mtg.wtf/card/ema/154)
- [x] [Worn Powerstone](https://mtg.wtf/card/ema/235)
- [x] [Wrath of God](https://mtg.wtf/card/ema/38)
- [x] [Xantid Swarm](https://mtg.wtf/card/ema/193)
- [x] [Yavimaya Enchantress](https://mtg.wtf/card/ema/194)
- [x] [Young Pyromancer](https://mtg.wtf/card/ema/155)
- [x] [Zealous Persecution](https://mtg.wtf/card/ema/213)
