### ISSUE TITLE
Eldritch Moon rules and Oracle update

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2205]
# Rules

The following rules changes from EMN may be relevant for XMage:

- [ ] Two new rules related to timing:

    > **601.3a.** If an effect allows a player to cast a spell as though it had flash only if an alternative or additional cost is paid, that player may begin to cast that spell as though it had flash.

    > **601.3b.** If an effect allows a player to cast a spell with certain characteristics as though it had flash, that player may consider any choices to be made during that spell's proposal that may cause it to have those characteristics. If any such choices could cause it to match these characteristics, that player may begin to cast that spell.

    > *Example: An effect says that you may cast Aura spells as though they had flash, and you have a creature card with bestow in your hand. Because choosing the bestow ability's alternative cost causes that spell to become an Aura spell, you may legally begin to cast that spell as though it had flash.*
- [ ] A mana ability can no longer be used to pay for itself:

    > **605.3c.** Once a player begins to activate a mana ability, that ability can't be activated again until it has resolved.

- [ ] Permanents entering the battlefield at the same time as [Sutured Ghoul](http://mtg.wtf/card/m12/112) can no longer be exiled to its replacement effect:

    > **614.13a.** While applying an effect that modifies how a permanent enters the battlefield, you may have to choose a number of objects that will also change zones. You can't choose the object that will become that permanent or any other object entering the battlefield at the same time as that object.

    > *Example: Sutured Ghoul says, in part, "As Sutured Ghoul enters the battlefield, exile any number of creature cards from your graveyard." If Sutured Ghoul and Runeclaw Bear enter the battlefield from your graveyard at the same time, you can't choose to exile either of them when applying Sutured Ghoul's replacement effect.*

- [x] New keyword action: meld
- [ ] Offering has been reworded, this is related to the new 601.3a and 601.3b
- [x] New keyword ability: emerge
- [x] New keyword ability: escalate
- [x] You can no longer look at the sideboard of a player you control (as far as I can tell, this was never implemented in the first place)
- [ ] Turns of players who have left the game are skipped:

    > **800.4i.** If a player who has left the game would begin a turn, that turn doesn't begin.

# Cards

The following cards have been printed in EMN and will have to be implemented.

## Reprints

- [x] [Convolute](https://mtg.wtf/card/emn/53)
- [x] [Hamlet Captain](https://mtg.wtf/card/emn/161)
- [x] [Murder](https://mtg.wtf/card/emn/97)
- [x] [Peace of Mind](https://mtg.wtf/card/emn/36)
- [x] [Prey Upon](https://mtg.wtf/card/emn/166)
- [x] [Ride Down](https://mtg.wtf/card/emn/188)
- [x] [Rise from the Grave](https://mtg.wtf/card/emn/102)
- [x] [Terrarion](https://mtg.wtf/card/emn/201)
- [x] [Turn Aside](https://mtg.wtf/card/emn/78)

## New cards

- [x] [Abandon Reason](https://mtg.wtf/card/emn/115)
- [x] [Abolisher of Bloodlines](https://mtg.wtf/card/emn/111b)
- [x] [Abundant Maw](https://mtg.wtf/card/emn/1)
- [x] [Advanced Stitchwing](https://mtg.wtf/card/emn/49)
- [x] [Alchemist's Greeting](https://mtg.wtf/card/emn/116)
- [x] [Assembled Alphas](https://mtg.wtf/card/emn/117)
- [x] [Aurora of Emrakul](https://mtg.wtf/card/emn/193b)
- [x] [Backwoods Survivalists](https://mtg.wtf/card/emn/150)
- [x] [Bedlam Reveler](https://mtg.wtf/card/emn/118)
- [x] [Blessed Alliance](https://mtg.wtf/card/emn/13)
- [x] [Blood Mist](https://mtg.wtf/card/emn/119)
- [x] [Bloodbriar](https://mtg.wtf/card/emn/151)
- [x] [Bloodhall Priest](https://mtg.wtf/card/emn/181)
- [x] [Bold Impaler](https://mtg.wtf/card/emn/120)
- [x] [Boon of Emrakul](https://mtg.wtf/card/emn/81)
- [x] [Borrowed Grace](https://mtg.wtf/card/emn/14)
- [x] [Borrowed Hostility](https://mtg.wtf/card/emn/121)
- [x] [Borrowed Malevolence](https://mtg.wtf/card/emn/82)
- [x] [Brazen Wolves](https://mtg.wtf/card/emn/122)
- [x] [Brisela, Voice of Nightmares](https://mtg.wtf/card/emn/15b)
- [x] [Bruna, the Fading Light](https://mtg.wtf/card/emn/15a)
- [x] [Campaign of Vengeance](https://mtg.wtf/card/emn/182)
- [x] [Cathar's Shield](https://mtg.wtf/card/emn/192)
- [x] [Cemetery Recruitment](https://mtg.wtf/card/emn/83)
- [x] [Certain Death](https://mtg.wtf/card/emn/84)
- [x] [Chilling Grasp](https://mtg.wtf/card/emn/50)
- [x] [Chittering Host](https://mtg.wtf/card/emn/96b)
- [x] [Choking Restraints](https://mtg.wtf/card/emn/16)
- [x] [Clear Shot](https://mtg.wtf/card/emn/152)
- [x] [Coax from the Blind Eternities](https://mtg.wtf/card/emn/51)
- [x] [Collective Brutality](https://mtg.wtf/card/emn/85)
- [x] [Collective Defiance](https://mtg.wtf/card/emn/123)
- [x] [Collective Effort](https://mtg.wtf/card/emn/17)
- [x] [Conduit of Emrakul](https://mtg.wtf/card/emn/124b)
- [x] [Conduit of Storms](https://mtg.wtf/card/emn/124a)
- [x] [Contingency Plan](https://mtg.wtf/card/emn/52)
- [x] [Courageous Outrider](https://mtg.wtf/card/emn/18)
- [x] [Crop Sigil](https://mtg.wtf/card/emn/153)
- [x] [Crossroads Consecrator](https://mtg.wtf/card/emn/154)
- [x] [Cryptbreaker](https://mtg.wtf/card/emn/86)
- [x] [Cryptolith Fragment](https://mtg.wtf/card/emn/193a)
- [x] [Cultist's Staff](https://mtg.wtf/card/emn/194)
- [x] [Curious Homunculus](https://mtg.wtf/card/emn/54a)
- [x] [Dark Salvation](https://mtg.wtf/card/emn/87)
- [x] [Dawn Gryff](https://mtg.wtf/card/emn/19)
- [x] [Decimator of the Provinces](https://mtg.wtf/card/emn/2)
- [x] [Deploy the Gatewatch](https://mtg.wtf/card/emn/20)
- [x] [Deranged Whelp](https://mtg.wtf/card/emn/125)
- [x] [Desperate Sentry](https://mtg.wtf/card/emn/21)
- [x] [Displace](https://mtg.wtf/card/emn/55)
- [x] [Distemper of the Blood](https://mtg.wtf/card/emn/126)
- [x] [Distended Mindbender](https://mtg.wtf/card/emn/3)
- [x] [Docent of Perfection](https://mtg.wtf/card/emn/56a)
- [x] [Drag Under](https://mtg.wtf/card/emn/57)
- [x] [Drogskol Shieldmate](https://mtg.wtf/card/emn/22)
- [x] [Dronepack Kindred](https://mtg.wtf/card/emn/148b)
- [x] [Drownyard Behemoth](https://mtg.wtf/card/emn/4)
- [x] [Dusk Feaster](https://mtg.wtf/card/emn/88)
- [x] [Elder Deep-Fiend](https://mtg.wtf/card/emn/5)
- [x] [Eldritch Evolution](https://mtg.wtf/card/emn/155)
- [x] [Emrakul's Evangel](https://mtg.wtf/card/emn/156)
- [x] [Emrakul's Influence](https://mtg.wtf/card/emn/157)
- [x] [Emrakul, the Promised End](https://mtg.wtf/card/emn/6)
- [x] [Enlightened Maniac](https://mtg.wtf/card/emn/58)
- [x] [Erupting Dreadwolf](https://mtg.wtf/card/emn/142b)
- [x] [Eternal Scourge](https://mtg.wtf/card/emn/7)
- [x] [Extricator of Flesh](https://mtg.wtf/card/emn/23b)
- [x] [Extricator of Sin](https://mtg.wtf/card/emn/23a)
- [x] [Exultant Cultist](https://mtg.wtf/card/emn/59)
- [x] [Faith Unbroken](https://mtg.wtf/card/emn/24)
- [x] [Faithbearer Paladin](https://mtg.wtf/card/emn/25)
- [x] [Falkenrath Reaver](https://mtg.wtf/card/emn/127)
- [x] [Fibrous Entangler](https://mtg.wtf/card/emn/174b)
- [x] [Field Creeper](https://mtg.wtf/card/emn/195)
- [x] [Fiend Binder](https://mtg.wtf/card/emn/26)
- [x] [Final Iteration](https://mtg.wtf/card/emn/56b)
- [x] [Fogwalker](https://mtg.wtf/card/emn/60)
- [x] [Fortune's Favor](https://mtg.wtf/card/emn/61)
- [x] [Foul Emissary](https://mtg.wtf/card/emn/158)
- [x] [Furyblade Vampire](https://mtg.wtf/card/emn/128)
- [x] [Galvanic Bombardment](https://mtg.wtf/card/emn/129)
- [x] [Gavony Unhallowed](https://mtg.wtf/card/emn/89)
- [x] [Geier Reach Sanitarium](https://mtg.wtf/card/emn/203)
- [x] [Geist of the Archives](https://mtg.wtf/card/emn/62)
- [x] [Geist of the Lonely Vigil](https://mtg.wtf/card/emn/27)
- [x] [Geist-Fueled Scarecrow](https://mtg.wtf/card/emn/196)
- [x] [Gisa and Geralf](https://mtg.wtf/card/emn/183)
- [x] [Gisela, the Broken Blade](https://mtg.wtf/card/emn/28a)
- [x] [Give No Ground](https://mtg.wtf/card/emn/29)
- [x] [Gnarlwood Dryad](https://mtg.wtf/card/emn/159)
- [x] [Graf Harvest](https://mtg.wtf/card/emn/90)
- [x] [Graf Rats](https://mtg.wtf/card/emn/91a)
- [x] [Grapple with the Past](https://mtg.wtf/card/emn/160)
- [x] [Grim Flayer](https://mtg.wtf/card/emn/184)
- [x] [Grisly Anglerfish](https://mtg.wtf/card/emn/63b)
- [x] [Grizzled Angler](https://mtg.wtf/card/emn/63a)
- [x] [Guardian of Pilgrims](https://mtg.wtf/card/emn/30)
- [x] [Hanweir Battlements](https://mtg.wtf/card/emn/204a)
- [x] [Hanweir Garrison](https://mtg.wtf/card/emn/130a)
- [x] [Hanweir, the Writhing Township](https://mtg.wtf/card/emn/130b)
- [x] [Harmless Offering](https://mtg.wtf/card/emn/131)
- [x] [Haunted Dead](https://mtg.wtf/card/emn/92)
- [x] [Heron's Grace Champion](https://mtg.wtf/card/emn/185)
- [x] [Howling Chorus](https://mtg.wtf/card/emn/168b)
- [x] [Identity Thief](https://mtg.wtf/card/emn/64)
- [x] [Impetuous Devils](https://mtg.wtf/card/emn/132)
- [x] [Imprisoned in the Moon](https://mtg.wtf/card/emn/65)
- [x] [Incendiary Flow](https://mtg.wtf/card/emn/133)
- [x] [Ingenious Skaab](https://mtg.wtf/card/emn/66)
- [x] [Insatiable Gorgers](https://mtg.wtf/card/emn/134)
- [x] [Ironclad Slayer](https://mtg.wtf/card/emn/31)
- [x] [Ironwright's Cleansing](https://mtg.wtf/card/emn/32)
- [x] [Ishkanah, Grafwidow](https://mtg.wtf/card/emn/162)
- [x] [It That Rides as One](https://mtg.wtf/card/emn/33b)
- [x] [It of the Horrid Swarm](https://mtg.wtf/card/emn/8)
- [x] [Kessig Prowler](https://mtg.wtf/card/emn/163a)
- [x] [Laboratory Brute](https://mtg.wtf/card/emn/67)
- [x] [Lashweed Lurker](https://mtg.wtf/card/emn/9)
- [x] [Liliana's Elite](https://mtg.wtf/card/emn/94)
- [x] [Liliana, the Last Hope](https://mtg.wtf/card/emn/93)
- [x] [Lone Rider](https://mtg.wtf/card/emn/33a)
- [x] [Long Road Home](https://mtg.wtf/card/emn/34)
- [x] [Lunar Force](https://mtg.wtf/card/emn/68)
- [x] [Lunarch Mantle](https://mtg.wtf/card/emn/35)
- [x] [Lupine Prototype](https://mtg.wtf/card/emn/197)
- [x] [Make Mischief](https://mtg.wtf/card/emn/135)
- [x] [Markov Crusader](https://mtg.wtf/card/emn/95)
- [x] [Mausoleum Wanderer](https://mtg.wtf/card/emn/69)
- [x] [Mercurial Geists](https://mtg.wtf/card/emn/186)
- [x] [Midnight Scavengers](https://mtg.wtf/card/emn/96a)
- [x] [Mind's Dilation](https://mtg.wtf/card/emn/70)
- [x] [Mirrorwing Dragon](https://mtg.wtf/card/emn/136)
- [x] [Mockery of Nature](https://mtg.wtf/card/emn/10)
- [x] [Mournwillow](https://mtg.wtf/card/emn/187)
- [x] [Nahiri's Wrath](https://mtg.wtf/card/emn/137)
- [x] [Nebelgast Herald](https://mtg.wtf/card/emn/71)
- [x] [Nephalia Academy](https://mtg.wtf/card/emn/205)
- [x] [Niblis of Frost](https://mtg.wtf/card/emn/72)
- [x] [Noose Constrictor](https://mtg.wtf/card/emn/164)
- [x] [Noosegraf Mob](https://mtg.wtf/card/emn/98)
- [x] [Oath of Liliana](https://mtg.wtf/card/emn/99)
- [x] [Olivia's Dragoon](https://mtg.wtf/card/emn/100)
- [x] [Otherworldly Outburst](https://mtg.wtf/card/emn/138)
- [x] [Permeating Mass](https://mtg.wtf/card/emn/165)
- [x] [Primal Druid](https://mtg.wtf/card/emn/167)
- [x] [Prophetic Ravings](https://mtg.wtf/card/emn/139)
- [x] [Providence](https://mtg.wtf/card/emn/37)
- [x] [Prying Questions](https://mtg.wtf/card/emn/101)
- [x] [Repel the Abominable](https://mtg.wtf/card/emn/38)
- [x] [Ruthless Disposal](https://mtg.wtf/card/emn/103)
- [x] [Sanctifier of Souls](https://mtg.wtf/card/emn/39)
- [x] [Savage Alliance](https://mtg.wtf/card/emn/140)
- [x] [Scour the Laboratory](https://mtg.wtf/card/emn/73)
- [x] [Selfless Spirit](https://mtg.wtf/card/emn/40)
- [x] [Shreds of Sanity](https://mtg.wtf/card/emn/141)
- [x] [Shrill Howler](https://mtg.wtf/card/emn/168a)
- [x] [Sigarda's Aid](https://mtg.wtf/card/emn/41)
- [x] [Sigardian Priest](https://mtg.wtf/card/emn/42)
- [x] [Sinuous Predator](https://mtg.wtf/card/emn/163b)
- [x] [Skirsdag Supplicant](https://mtg.wtf/card/emn/104)
- [x] [Slayer's Cleaver](https://mtg.wtf/card/emn/198)
- [x] [Smoldering Werewolf](https://mtg.wtf/card/emn/142a)
- [x] [Somberwald Stag](https://mtg.wtf/card/emn/169)
- [x] [Soul Separator](https://mtg.wtf/card/emn/199)
- [x] [Spectral Reserves](https://mtg.wtf/card/emn/43)
- [x] [Spell Queller](https://mtg.wtf/card/emn/189)
- [x] [Spirit of the Hunt](https://mtg.wtf/card/emn/170)
- [x] [Splendid Reclamation](https://mtg.wtf/card/emn/171)
- [x] [Spontaneous Mutation](https://mtg.wtf/card/emn/74)
- [x] [Spreading Flames](https://mtg.wtf/card/emn/143)
- [x] [Springsage Ritual](https://mtg.wtf/card/emn/172)
- [x] [Steadfast Cathar](https://mtg.wtf/card/emn/44)
- [x] [Stensia Banquet](https://mtg.wtf/card/emn/144)
- [x] [Stensia Innkeeper](https://mtg.wtf/card/emn/145)
- [x] [Stitcher's Graft](https://mtg.wtf/card/emn/200)
- [x] [Strange Augmentation](https://mtg.wtf/card/emn/105)
- [x] [Stromkirk Condemned](https://mtg.wtf/card/emn/106)
- [x] [Stromkirk Occultist](https://mtg.wtf/card/emn/146)
- [x] [Subjugator Angel](https://mtg.wtf/card/emn/45)
- [x] [Succumb to Temptation](https://mtg.wtf/card/emn/107)
- [x] [Summary Dismissal](https://mtg.wtf/card/emn/75)
- [x] [Swift Spinner](https://mtg.wtf/card/emn/173)
- [x] [Take Inventory](https://mtg.wtf/card/emn/76)
- [x] [Tamiyo, Field Researcher](https://mtg.wtf/card/emn/190)
- [x] [Tangleclaw Werewolf](https://mtg.wtf/card/emn/174a)
- [x] [Tattered Haunter](https://mtg.wtf/card/emn/77)
- [x] [Thalia's Lancers](https://mtg.wtf/card/emn/47)
- [x] [Thalia, Heretic Cathar](https://mtg.wtf/card/emn/46)
- [x] [Thermo-Alchemist](https://mtg.wtf/card/emn/147)
- [x] [Thirsting Axe](https://mtg.wtf/card/emn/202)
- [x] [Thraben Foulbloods](https://mtg.wtf/card/emn/108)
- [x] [Thraben Standard Bearer](https://mtg.wtf/card/emn/48)
- [x] [Tree of Perdition](https://mtg.wtf/card/emn/109)
- [x] [Ulrich of the Krallenhorde](https://mtg.wtf/card/emn/191a)
- [x] [Ulrich, Uncontested Alpha](https://mtg.wtf/card/emn/191b)
- [x] [Ulvenwald Abomination](https://mtg.wtf/card/emn/175b)
- [x] [Ulvenwald Captive](https://mtg.wtf/card/emn/175a)
- [x] [Ulvenwald Observer](https://mtg.wtf/card/emn/176)
- [x] [Unsubstantiate](https://mtg.wtf/card/emn/79)
- [x] [Vampire Cutthroat](https://mtg.wtf/card/emn/110)
- [x] [Vexing Scuttler](https://mtg.wtf/card/emn/11)
- [x] [Vildin-Pack Outcast](https://mtg.wtf/card/emn/148a)
- [x] [Voldaren Pariah](https://mtg.wtf/card/emn/111a)
- [x] [Voracious Reader](https://mtg.wtf/card/emn/54b)
- [x] [Wailing Ghoul](https://mtg.wtf/card/emn/112)
- [x] [Waxing Moon](https://mtg.wtf/card/emn/177)
- [x] [Weaver of Lightning](https://mtg.wtf/card/emn/149)
- [x] [Weirded Vampire](https://mtg.wtf/card/emn/113)
- [x] [Wharf Infiltrator](https://mtg.wtf/card/emn/80)
- [x] [Whispers of Emrakul](https://mtg.wtf/card/emn/114)
- [x] [Wolfkin Bond](https://mtg.wtf/card/emn/178)
- [x] [Woodcutter's Grit](https://mtg.wtf/card/emn/179)
- [x] [Woodland Patrol](https://mtg.wtf/card/emn/180)
- [x] [Wretched Gryff](https://mtg.wtf/card/emn/12)
