### ISSUE TITLE
From the Vault: Lore Oracle update

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2207]
# Cards

The following cards have been printed in V16 and will have to be implemented.

## Reprints

- [x] [Beseech the Queen](https://mtg.wtf/card/v16/1)
- [x] [Cabal Ritual](https://mtg.wtf/card/v16/2)
- [x] [Conflux](https://mtg.wtf/card/v16/3)
- [x] [Dark Depths](https://mtg.wtf/card/v16/4)
- [x] [Glissa, the Traitor](https://mtg.wtf/card/v16/5)
- [x] [Helvault](https://mtg.wtf/card/v16/6)
- [x] [Memnarch](https://mtg.wtf/card/v16/7)
- [x] [Mind's Desire](https://mtg.wtf/card/v16/8)
- [x] [Momir Vig, Simic Visionary](https://mtg.wtf/card/v16/9)
- [x] [Near-Death Experience](https://mtg.wtf/card/v16/10)
- [x] [Obliterate](https://mtg.wtf/card/v16/11)
- [x] [Phyrexian Processor](https://mtg.wtf/card/v16/12)
- [x] [Tolaria West](https://mtg.wtf/card/v16/13)
- [x] [Umezawa's Jitte](https://mtg.wtf/card/v16/14)
- [x] [Unmask](https://mtg.wtf/card/v16/15)
