### ISSUE TITLE
Kaladesh rules and Oracle update

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2473]
# Rules

The following rules changes from KLD may be relevant for XMage:

- [ ] New symbol for energy counters, represented in plain text as `{E}`, and counter costs as a new type of cost (“Pay {E}” means “remove an energy counter from yourself”).
- [ ] Face-up objects in the command zone can now be chosen as a source of damage. Notably, the emblem of [Chandra, Torch of Defiance](https://mtg.wtf/card/kld/110) can be chosen.
- [x] New artifact type: Vehicle
- [x] New planeswalker type: Dovin
- [x] New planeswalker type: Saheeli
- [x] New creature type: Aetherborn
- [ ] New creature type: Monkey
- [x] New creature type: Pilot
- [x] New creature type: Servo
- [ ] New rules concerning power and toughness on noncreature objects:
    > **208.3a.** If an effect would be created that affects the power and/or toughness of a noncreature permanent, that effect is created even though it doesn't do anything unless that permanent becomes a creature.

    > *Example: Veteran Motorist has the ability "Whenever Veteran Motorist crews a Vehicle, that Vehicle gets +1/+1 until end of turn," and it's tapped to pay the crew cost of a Vehicle. This triggered ability resolves while the Vehicle it crewed isn't yet a creature. The continuous effect is created and will apply to the Vehicle once it becomes a creature.*

    > **208.5.** If a creature somehow has no value for its power, its power is 0. The same is true for toughness.

    > **301.7a.** Each Vehicle has a printed power and toughness, but it has these characteristics only if it's also a creature. See rule 208.3.

    > **301.7b.** If a Vehicle becomes a creature, it immediately has its printed power and toughness. Other effects, including the effect that makes it a creature, may modify these values or set them to different values.
- [ ] New rule regarding one-shot effects with durations:
    > **610.3c.** If multiple one-shot effects are created this way immediately after one or more simultaneous events, those one-shot effects are also simultaneous.

    > *Example: Two Banisher Priests have each exiled a card. All creatures are destroyed at the same time by Day of Judgment. The two exiled cards are returned to the battlefield at the same time.*
- [ ] New keyword action: create
- [ ] New rule regarding revealed cards in libraries:
    > **701.14c.** If cards in a player's library are shuffled or otherwise reordered, any revealed cards that are reordered stop being revealed and become new objects.
- [ ] Populate, investigate, living weapon, and myriad have been redefined using create. Reminder text may need to be updated.
- [x] New keyword ability: crew
- [x] New keyword ability: fabricate

# Oracle

In KLD, there have been the following Oracle changes which will have to be implemented. Functional errata are marked in boldface, and unimplemented cards are omitted.

## Multiple cards

- [x] Card names with Æ or æ in them have been changed to use Ae or ae.
- [ ] [Aluren](https://mtg.wtf/card/tp/107), [Quick Sliver](http://mtg.wtf/card/le/136), and [Winding Canyons](http://mtg.wtf/card/wl/167) now say “cast creature spells” instead of “play creature cards”. Notably, **you can no longer play [Dryad Arbor](https://mtg.wtf/card/v12/5) at instant speed using Aluren or Winding Canyons**.
- [ ] [A comma has been added to some cards that create copy effects with exceptions.](http://www.yawgatog.com/resources/oracle-changes/cn2-kld/#S2)
- [ ] Cards that put tokens onto the battlefield now use the create keyword action. Note how status modifiers like “tapped” sometimes precede the other characteristics like P/T.

## Single card

- [ ] [https://mtg.wtf/card/m15/212](Avarice Amulet): changed to use “whenever” instead of “when”.
- [ ] [https://mtg.wtf/card/us/295](Fluctuator): extra “you” removed.
- [ ] [https://mtg.wtf/card/mr/272](Lion's Eye Diamond): Activation costs listed in a different order for consistency. Not a functional change since costs can always be paid in any order.

# Cards

The following cards have been printed in KLD and will have to be implemented.

## Reprints

- [x] [Aether Tradewinds](https://mtg.wtf/card/kld/38)
- [x] [Cataclysmic Gearhulk](https://mtg.wtf/card/kld/9)
- [x] [Chief of the Foundry](https://mtg.wtf/card/kld/200)
- [x] [Combustible Gearhulk](https://mtg.wtf/card/kld/112)
- [x] [Creeping Mold](https://mtg.wtf/card/kld/150)
- [x] [Demolish](https://mtg.wtf/card/kld/113)
- [x] [Diabolic Tutor](https://mtg.wtf/card/kld/75)
- [x] [Forest](https://mtg.wtf/card/kld/264)
- [x] [Hunt the Weak](https://mtg.wtf/card/kld/158)
- [x] [Inspired Charge](https://mtg.wtf/card/kld/20)
- [x] [Island](https://mtg.wtf/card/kld/255)
- [x] [Mind Rot](https://mtg.wtf/card/kld/93)
- [x] [Mountain](https://mtg.wtf/card/kld/261)
- [x] [Noxious Gearhulk](https://mtg.wtf/card/kld/96)
- [x] [Plains](https://mtg.wtf/card/kld/252)
- [x] [Pressure Point](https://mtg.wtf/card/kld/23)
- [x] [Prophetic Prism](https://mtg.wtf/card/kld/229)
- [x] [Stone Quarry](https://mtg.wtf/card/kld/269)
- [x] [Swamp](https://mtg.wtf/card/kld/258)
- [x] [Torrential Gearhulk](https://mtg.wtf/card/kld/67)
- [x] [Verdurous Gearhulk](https://mtg.wtf/card/kld/172)
- [x] [Wind Drake](https://mtg.wtf/card/kld/70)
- [x] [Woodland Stream](https://mtg.wtf/card/kld/274)

## New cards

- [x] [Accomplished Automaton](https://mtg.wtf/card/kld/191)
- [x] [Acrobatic Maneuver](https://mtg.wtf/card/kld/1)
- [x] [Aerial Responder](https://mtg.wtf/card/kld/2)
- [x] [Aether Hub](https://mtg.wtf/card/kld/242)
- [x] [Aether Meltdown](https://mtg.wtf/card/kld/36)
- [x] [Aether Theorist](https://mtg.wtf/card/kld/37)
- [x] [Aetherborn Marauder](https://mtg.wtf/card/kld/71)
- [x] [Aetherflux Reservoir](https://mtg.wtf/card/kld/192)
- [x] [Aethersquall Ancient](https://mtg.wtf/card/kld/39)
- [x] [Aetherstorm Roc](https://mtg.wtf/card/kld/3)
- [x] [Aethertorch Renegade](https://mtg.wtf/card/kld/106)
- [x] [Aetherworks Marvel](https://mtg.wtf/card/kld/193)
- [x] [Ambitious Aetherborn](https://mtg.wtf/card/kld/72)
- [x] [Angel of Invention](https://mtg.wtf/card/kld/4)
- [x] [Animation Module](https://mtg.wtf/card/kld/194)
- [x] [Appetite for the Unnatural](https://mtg.wtf/card/kld/141)
- [x] [Aradara Express](https://mtg.wtf/card/kld/195)
- [x] [Arborback Stomper](https://mtg.wtf/card/kld/142)
- [x] [Architect of the Untamed](https://mtg.wtf/card/kld/143)
- [x] [Armorcraft Judge](https://mtg.wtf/card/kld/144)
- [x] [Attune with Aether](https://mtg.wtf/card/kld/145)
- [x] [Authority of the Consuls](https://mtg.wtf/card/kld/5)
- [x] [Aviary Mechanic](https://mtg.wtf/card/kld/6)
- [x] [Ballista Charger](https://mtg.wtf/card/kld/196)
- [x] [Bastion Mastodon](https://mtg.wtf/card/kld/197)
- [x] [Blooming Marsh](https://mtg.wtf/card/kld/243)
- [x] [Blossoming Defense](https://mtg.wtf/card/kld/146)
- [x] [Bomat Bazaar Barge](https://mtg.wtf/card/kld/198)
- [x] [Bomat Courier](https://mtg.wtf/card/kld/199)
- [x] [Botanical Sanctum](https://mtg.wtf/card/kld/244)
- [x] [Brazen Scourge](https://mtg.wtf/card/kld/107)
- [x] [Bristling Hydra](https://mtg.wtf/card/kld/147)
- [x] [Built to Last](https://mtg.wtf/card/kld/7)
- [x] [Built to Smash](https://mtg.wtf/card/kld/108)
- [x] [Captured by the Consulate](https://mtg.wtf/card/kld/8)
- [x] [Cathartic Reunion](https://mtg.wtf/card/kld/109)
- [x] [Ceremonious Rejection](https://mtg.wtf/card/kld/40)
- [x] [Chandra's Pyrohelix](https://mtg.wtf/card/kld/111)
- [x] [Chandra, Pyrogenius](https://mtg.wtf/card/kld/265)
- [x] [Chandra, Torch of Defiance](https://mtg.wtf/card/kld/110)
- [x] [Cloudblazer](https://mtg.wtf/card/kld/176)
- [x] [Cogworker's Puzzleknot](https://mtg.wtf/card/kld/201)
- [x] [Commencement of Festivities](https://mtg.wtf/card/kld/148)
- [x] [Concealed Courtyard](https://mtg.wtf/card/kld/245)
- [x] [Confiscation Coup](https://mtg.wtf/card/kld/41)
- [x] [Consul's Shieldguard](https://mtg.wtf/card/kld/11)
- [x] [Consulate Skygate](https://mtg.wtf/card/kld/202)
- [x] [Consulate Surveillance](https://mtg.wtf/card/kld/10)
- [x] [Contraband Kingpin](https://mtg.wtf/card/kld/177)
- [x] [Cowl Prowler](https://mtg.wtf/card/kld/149)
- [x] [Cultivator of Blades](https://mtg.wtf/card/kld/151)
- [x] [Cultivator's Caravan](https://mtg.wtf/card/kld/203)
- [x] [Curio Vendor](https://mtg.wtf/card/kld/42)
- [x] [Deadlock Trap](https://mtg.wtf/card/kld/204)
- [x] [Decoction Module](https://mtg.wtf/card/kld/205)
- [x] [Demolition Stomper](https://mtg.wtf/card/kld/206)
- [x] [Demon of Dark Schemes](https://mtg.wtf/card/kld/73)
- [x] [Depala, Pilot Exemplar](https://mtg.wtf/card/kld/178)
- [x] [Dhund Operative](https://mtg.wtf/card/kld/74)
- [x] [Die Young](https://mtg.wtf/card/kld/76)
- [x] [Disappearing Act](https://mtg.wtf/card/kld/43)
- [x] [Dovin Baan](https://mtg.wtf/card/kld/179)
- [x] [Dramatic Reversal](https://mtg.wtf/card/kld/44)
- [x] [Dubious Challenge](https://mtg.wtf/card/kld/152)
- [x] [Dukhara Peafowl](https://mtg.wtf/card/kld/207)
- [x] [Dukhara Scavenger](https://mtg.wtf/card/kld/77)
- [x] [Durable Handicraft](https://mtg.wtf/card/kld/153)
- [x] [Dynavolt Tower](https://mtg.wtf/card/kld/208)
- [x] [Eager Construct](https://mtg.wtf/card/kld/209)
- [x] [Eddytrail Hawk](https://mtg.wtf/card/kld/12)
- [x] [Electrostatic Pummeler](https://mtg.wtf/card/kld/210)
- [x] [Elegant Edgecrafters](https://mtg.wtf/card/kld/154)
- [x] [Eliminate the Competition](https://mtg.wtf/card/kld/78)
- [x] [Embraal Bruiser](https://mtg.wtf/card/kld/79)
- [x] [Empyreal Voyager](https://mtg.wtf/card/kld/180)
- [x] [Engineered Might](https://mtg.wtf/card/kld/181)
- [x] [Era of Innovation](https://mtg.wtf/card/kld/45)
- [x] [Essence Extraction](https://mtg.wtf/card/kld/80)
- [x] [Experimental Aviator](https://mtg.wtf/card/kld/46)
- [x] [Fabrication Module](https://mtg.wtf/card/kld/211)
- [x] [Failed Inspection](https://mtg.wtf/card/kld/47)
- [x] [Fairgrounds Trumpeter](https://mtg.wtf/card/kld/155)
- [x] [Fairgrounds Warden](https://mtg.wtf/card/kld/13)
- [x] [Fateful Showdown](https://mtg.wtf/card/kld/114)
- [x] [Filigree Familiar](https://mtg.wtf/card/kld/212)
- [x] [Fireforger's Puzzleknot](https://mtg.wtf/card/kld/213)
- [x] [Flame Lash](https://mtg.wtf/card/kld/266)
- [x] [Fleetwheel Cruiser](https://mtg.wtf/card/kld/214)
- [x] [Fortuitous Find](https://mtg.wtf/card/kld/81)
- [x] [Foundry Inspector](https://mtg.wtf/card/kld/215)
- [x] [Foundry Screecher](https://mtg.wtf/card/kld/82)
- [x] [Fragmentize](https://mtg.wtf/card/kld/14)
- [x] [Fretwork Colony](https://mtg.wtf/card/kld/83)
- [x] [Fumigate](https://mtg.wtf/card/kld/15)
- [x] [Furious Reprisal](https://mtg.wtf/card/kld/115)
- [x] [Gearseeker Serpent](https://mtg.wtf/card/kld/48)
- [x] [Gearshift Ace](https://mtg.wtf/card/kld/16)
- [x] [Ghirapur Guide](https://mtg.wtf/card/kld/156)
- [x] [Ghirapur Orrery](https://mtg.wtf/card/kld/216)
- [x] [Giant Spectacle](https://mtg.wtf/card/kld/116)
- [x] [Glassblower's Puzzleknot](https://mtg.wtf/card/kld/217)
- [x] [Glimmer of Genius](https://mtg.wtf/card/kld/49)
- [x] [Glint-Nest Crane](https://mtg.wtf/card/kld/50)
- [x] [Glint-Sleeve Artisan](https://mtg.wtf/card/kld/17)
- [x] [Gonti, Lord of Luxury](https://mtg.wtf/card/kld/84)
- [x] [Guardian of the Great Conduit](https://mtg.wtf/card/kld/271)
- [x] [Harnessed Lightning](https://mtg.wtf/card/kld/117)
- [x] [Harsh Scrutiny](https://mtg.wtf/card/kld/85)
- [x] [Hazardous Conditions](https://mtg.wtf/card/kld/182)
- [x] [Herald of the Fair](https://mtg.wtf/card/kld/18)
- [x] [Highspire Artisan](https://mtg.wtf/card/kld/157)
- [x] [Hightide Hermit](https://mtg.wtf/card/kld/51)
- [x] [Hijack](https://mtg.wtf/card/kld/118)
- [x] [Impeccable Timing](https://mtg.wtf/card/kld/19)
- [x] [Incendiary Sabotage](https://mtg.wtf/card/kld/119)
- [x] [Insidious Will](https://mtg.wtf/card/kld/52)
- [x] [Inspiring Vantage](https://mtg.wtf/card/kld/246)
- [x] [Inventor's Apprentice](https://mtg.wtf/card/kld/120)
- [x] [Inventor's Goggles](https://mtg.wtf/card/kld/218)
- [x] [Inventors' Fair](https://mtg.wtf/card/kld/247)
- [x] [Iron League Steed](https://mtg.wtf/card/kld/219)
- [x] [Janjeet Sentry](https://mtg.wtf/card/kld/53)
- [x] [Kambal, Consul of Allocation](https://mtg.wtf/card/kld/183)
- [x] [Key to the City](https://mtg.wtf/card/kld/220)
- [x] [Kujar Seedsculptor](https://mtg.wtf/card/kld/159)
- [x] [Larger Than Life](https://mtg.wtf/card/kld/160)
- [x] [Lathnu Hellion](https://mtg.wtf/card/kld/121)
- [x] [Lawless Broker](https://mtg.wtf/card/kld/86)
- [x] [Liberating Combustion](https://mtg.wtf/card/kld/267)
- [x] [Live Fast](https://mtg.wtf/card/kld/87)
- [x] [Long-Finned Skywhale](https://mtg.wtf/card/kld/54)
- [x] [Longtusk Cub](https://mtg.wtf/card/kld/161)
- [x] [Lost Legacy](https://mtg.wtf/card/kld/88)
- [x] [Madcap Experiment](https://mtg.wtf/card/kld/122)
- [x] [Make Obsolete](https://mtg.wtf/card/kld/89)
- [x] [Malfunction](https://mtg.wtf/card/kld/55)
- [x] [Marionette Master](https://mtg.wtf/card/kld/90)
- [x] [Master Trinketeer](https://mtg.wtf/card/kld/21)
- [x] [Maulfist Doorbuster](https://mtg.wtf/card/kld/123)
- [x] [Maulfist Squad](https://mtg.wtf/card/kld/91)
- [x] [Metallurgic Summonings](https://mtg.wtf/card/kld/56)
- [x] [Metalspinner's Puzzleknot](https://mtg.wtf/card/kld/221)
- [x] [Metalwork Colossus](https://mtg.wtf/card/kld/222)
- [x] [Midnight Oil](https://mtg.wtf/card/kld/92)
- [x] [Minister of Inquiries](https://mtg.wtf/card/kld/57)
- [x] [Morbid Curiosity](https://mtg.wtf/card/kld/94)
- [x] [Multiform Wonder](https://mtg.wtf/card/kld/223)
- [x] [Narnam Cobra](https://mtg.wtf/card/kld/224)
- [x] [Nature's Way](https://mtg.wtf/card/kld/162)
- [x] [Night Market Lookout](https://mtg.wtf/card/kld/95)
- [x] [Nimble Innovator](https://mtg.wtf/card/kld/58)
- [x] [Ninth Bridge Patrol](https://mtg.wtf/card/kld/22)
- [x] [Nissa, Nature's Artisan](https://mtg.wtf/card/kld/270)
- [x] [Nissa, Vital Force](https://mtg.wtf/card/kld/163)
- [x] [Ornamental Courage](https://mtg.wtf/card/kld/164)
- [x] [Ovalchase Daredevil](https://mtg.wtf/card/kld/97)
- [x] [Ovalchase Dragster](https://mtg.wtf/card/kld/225)
- [x] [Oviya Pashiri, Sage Lifecrafter](https://mtg.wtf/card/kld/165)
- [x] [Padeem, Consul of Innovation](https://mtg.wtf/card/kld/59)
- [x] [Panharmonicon](https://mtg.wtf/card/kld/226)
- [x] [Paradoxical Outcome](https://mtg.wtf/card/kld/60)
- [x] [Peema Outrider](https://mtg.wtf/card/kld/166)
- [x] [Perpetual Timepiece](https://mtg.wtf/card/kld/227)
- [x] [Pia Nalaar](https://mtg.wtf/card/kld/124)
- [x] [Prakhata Club Security](https://mtg.wtf/card/kld/98)
- [x] [Prakhata Pillar-Bug](https://mtg.wtf/card/kld/228)
- [x] [Propeller Pioneer](https://mtg.wtf/card/kld/24)
- [x] [Quicksmith Genius](https://mtg.wtf/card/kld/125)
- [x] [Rashmi, Eternities Crafter](https://mtg.wtf/card/kld/184)
- [x] [Reckless Fireweaver](https://mtg.wtf/card/kld/126)
- [x] [Refurbish](https://mtg.wtf/card/kld/25)
- [x] [Renegade Firebrand](https://mtg.wtf/card/kld/268)
- [x] [Renegade Freighter](https://mtg.wtf/card/kld/230)
- [x] [Renegade Tactics](https://mtg.wtf/card/kld/127)
- [x] [Restoration Gearsmith](https://mtg.wtf/card/kld/185)
- [x] [Revoke Privileges](https://mtg.wtf/card/kld/26)
- [x] [Revolutionary Rebuff](https://mtg.wtf/card/kld/61)
- [x] [Riparian Tiger](https://mtg.wtf/card/kld/167)
- [x] [Ruinous Gremlin](https://mtg.wtf/card/kld/128)
- [x] [Rush of Vitality](https://mtg.wtf/card/kld/99)
- [x] [Sage of Shaila's Claim](https://mtg.wtf/card/kld/168)
- [x] [Saheeli Rai](https://mtg.wtf/card/kld/186)
- [x] [Saheeli's Artistry](https://mtg.wtf/card/kld/62)
- [x] [Salivating Gremlins](https://mtg.wtf/card/kld/129)
- [x] [Scrapheap Scrounger](https://mtg.wtf/card/kld/231)
- [x] [Select for Inspection](https://mtg.wtf/card/kld/63)
- [x] [Self-Assembler](https://mtg.wtf/card/kld/232)
- [x] [Sequestered Stash](https://mtg.wtf/card/kld/248)
- [x] [Servant of the Conduit](https://mtg.wtf/card/kld/169)
- [x] [Servo Exhibition](https://mtg.wtf/card/kld/27)
- [x] [Shrewd Negotiation](https://mtg.wtf/card/kld/64)
- [x] [Sky Skiff](https://mtg.wtf/card/kld/233)
- [x] [Skyship Stalker](https://mtg.wtf/card/kld/130)
- [x] [Skysovereign, Consul Flagship](https://mtg.wtf/card/kld/234)
- [x] [Skyswirl Harrier](https://mtg.wtf/card/kld/28)
- [x] [Skywhaler's Shot](https://mtg.wtf/card/kld/29)
- [x] [Smuggler's Copter](https://mtg.wtf/card/kld/235)
- [x] [Snare Thopter](https://mtg.wtf/card/kld/236)
- [x] [Spark of Creativity](https://mtg.wtf/card/kld/131)
- [x] [Speedway Fanatic](https://mtg.wtf/card/kld/132)
- [x] [Spirebluff Canal](https://mtg.wtf/card/kld/249)
- [x] [Spireside Infiltrator](https://mtg.wtf/card/kld/133)
- [x] [Spontaneous Artist](https://mtg.wtf/card/kld/134)
- [x] [Start Your Engines](https://mtg.wtf/card/kld/135)
- [x] [Subtle Strike](https://mtg.wtf/card/kld/100)
- [x] [Syndicate Trafficker](https://mtg.wtf/card/kld/101)
- [x] [Take Down](https://mtg.wtf/card/kld/170)
- [x] [Tasseled Dromedary](https://mtg.wtf/card/kld/30)
- [x] [Terrain Elemental](https://mtg.wtf/card/kld/272)
- [x] [Territorial Gorger](https://mtg.wtf/card/kld/136)
- [x] [Terror of the Fairgrounds](https://mtg.wtf/card/kld/137)
- [x] [Tezzeret's Ambition](https://mtg.wtf/card/kld/65)
- [x] [Thriving Grubs](https://mtg.wtf/card/kld/138)
- [x] [Thriving Ibex](https://mtg.wtf/card/kld/31)
- [x] [Thriving Rats](https://mtg.wtf/card/kld/102)
- [x] [Thriving Rhino](https://mtg.wtf/card/kld/171)
- [x] [Thriving Turtle](https://mtg.wtf/card/kld/66)
- [x] [Tidy Conclusion](https://mtg.wtf/card/kld/103)
- [x] [Toolcraft Exemplar](https://mtg.wtf/card/kld/32)
- [x] [Torch Gauntlet](https://mtg.wtf/card/kld/237)
- [x] [Trusty Companion](https://mtg.wtf/card/kld/33)
- [x] [Underhanded Designs](https://mtg.wtf/card/kld/104)
- [x] [Unlicensed Disintegration](https://mtg.wtf/card/kld/187)
- [x] [Vedalken Blademaster](https://mtg.wtf/card/kld/68)
- [x] [Verdant Crescendo](https://mtg.wtf/card/kld/273)
- [x] [Veteran Motorist](https://mtg.wtf/card/kld/188)
- [x] [Visionary Augmenter](https://mtg.wtf/card/kld/34)
- [x] [Voltaic Brawler](https://mtg.wtf/card/kld/189)
- [x] [Wayward Giant](https://mtg.wtf/card/kld/139)
- [x] [Weaponcraft Enthusiast](https://mtg.wtf/card/kld/105)
- [x] [Weldfast Monitor](https://mtg.wtf/card/kld/238)
- [x] [Weldfast Wingsmith](https://mtg.wtf/card/kld/69)
- [x] [Welding Sparks](https://mtg.wtf/card/kld/140)
- [x] [Whirler Virtuoso](https://mtg.wtf/card/kld/190)
- [x] [Whirlermaker](https://mtg.wtf/card/kld/239)
- [x] [Wild Wanderer](https://mtg.wtf/card/kld/173)
- [x] [Wildest Dreams](https://mtg.wtf/card/kld/174)
- [x] [Wily Bandar](https://mtg.wtf/card/kld/175)
- [x] [Wispweaver Angel](https://mtg.wtf/card/kld/35)
- [x] [Woodweaver's Puzzleknot](https://mtg.wtf/card/kld/240)
- [x] [Workshop Assistant](https://mtg.wtf/card/kld/241)

**Comment by jmharmon** [comment]
Monkey creature type has been added already.
https://github.com/magefree/mage/blob/725adb1a2549e58323e60464aa56653f260ff35f/Mage/src/main/java/mage/constants/SubType.java
