### ISSUE TITLE
Commander 2017 Set - Tracking Issue C17

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#3461]
- [x] Not Done -- [Alms Collector](https://www.google.com.au/search?q=intext:"Alms+Collector"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Not Done -- [New Blood](https://www.google.com.au/search?q=intext:"New+Blood"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Not Done -- [Portal Mage](https://www.google.com.au/search?q=intext:"Portal+Mage"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Not Done -- [Stalking Leonin](https://www.google.com.au/search?q=intext:"Stalking+Leonin"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Not Done -- [Vindictive Lich](https://www.google.com.au/search?q=intext:"Vindictive+Lich"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Arahbo, Roar of the World](https://www.google.com.au/search?q=intext:"Arahbo++Roar+of+the+World"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Balan, Wandering Knight](https://www.google.com.au/search?q=intext:"Balan++Wandering+Knight"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Bloodforged War Axe](https://www.google.com.au/search?q=intext:"Bloodforged+War+Axe"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Bloodline Necromancer](https://www.google.com.au/search?q=intext:"Bloodline+Necromancer"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Bloodsworn Steward](https://www.google.com.au/search?q=intext:"Bloodsworn+Steward"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Boneyard Scourge](https://www.google.com.au/search?q=intext:"Boneyard+Scourge"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Crimson Honor Guard](https://www.google.com.au/search?q=intext:"Crimson+Honor+Guard"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Curse of Bounty](https://www.google.com.au/search?q=intext:"Curse+of+Bounty"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Curse of Disturbance](https://www.google.com.au/search?q=intext:"Curse+of+Disturbance"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Curse of Opulence](https://www.google.com.au/search?q=intext:"Curse+of+Opulence"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Curse of Verbosity](https://www.google.com.au/search?q=intext:"Curse+of+Verbosity"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Curse of Vitality](https://www.google.com.au/search?q=intext:"Curse+of+Vitality"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Disrupt Decorum](https://www.google.com.au/search?q=intext:"Disrupt+Decorum"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Edgar Markov](https://www.google.com.au/search?q=intext:"Edgar+Markov"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Fortunate Few](https://www.google.com.au/search?q=intext:"Fortunate+Few"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Fractured Identity](https://www.google.com.au/search?q=intext:"Fractured+Identity"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Galecaster Colossus](https://www.google.com.au/search?q=intext:"Galecaster+Colossus"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Hammer of Nazahn](https://www.google.com.au/search?q=intext:"Hammer+of+Nazahn"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Heirloom Blade](https://www.google.com.au/search?q=intext:"Heirloom+Blade"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Herald's Horn](https://www.google.com.au/search?q=intext:"Herald's+Horn"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Hungry Lynx](https://www.google.com.au/search?q=intext:"Hungry+Lynx"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Inalla, Archmage Ritualist](https://www.google.com.au/search?q=intext:"Inalla++Archmage+Ritualist"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Izzet Chemister](https://www.google.com.au/search?q=intext:"Izzet+Chemister"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Kess, Dissident Mage](https://www.google.com.au/search?q=intext:"Kess++Dissident+Mage"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Kheru Mind-Eater](https://www.google.com.au/search?q=intext:"Kheru+Mind-Eater"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Kindred Boon](https://www.google.com.au/search?q=intext:"Kindred+Boon"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Kindred Charge](https://www.google.com.au/search?q=intext:"Kindred+Charge"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Kindred Discovery](https://www.google.com.au/search?q=intext:"Kindred+Discovery"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Kindred Dominance](https://www.google.com.au/search?q=intext:"Kindred+Dominance"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Kindred Summons](https://www.google.com.au/search?q=intext:"Kindred+Summons"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Licia, Sanguine Tribune](https://www.google.com.au/search?q=intext:"Licia++Sanguine+Tribune"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Magus of the Mind](https://www.google.com.au/search?q=intext:"Magus+of+the+Mind"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Mairsil, the Pretender](https://www.google.com.au/search?q=intext:"Mairsil++the+Pretender"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Mathas, Fiend Seeker](https://www.google.com.au/search?q=intext:"Mathas++Fiend+Seeker"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Mirri, Weatherlight Duelist](https://www.google.com.au/search?q=intext:"Mirri++Weatherlight+Duelist"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Mirror of the Forebears](https://www.google.com.au/search?q=intext:"Mirror+of+the+Forebears"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Nazahn, Revered Bladesmith](https://www.google.com.au/search?q=intext:"Nazahn++Revered+Bladesmith"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [O-Kagachi, Vengeful Kami](https://www.google.com.au/search?q=intext:"O-Kagachi++Vengeful+Kami"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Path of Ancestry](https://www.google.com.au/search?q=intext:"Path+of+Ancestry"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Patron of the Vein](https://www.google.com.au/search?q=intext:"Patron+of+the+Vein"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Qasali Slingers](https://www.google.com.au/search?q=intext:"Qasali+Slingers"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Ramos, Dragon Engine](https://www.google.com.au/search?q=intext:"Ramos++Dragon+Engine"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Scalelord Reckoner](https://www.google.com.au/search?q=intext:"Scalelord+Reckoner"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Shifting Shadow](https://www.google.com.au/search?q=intext:"Shifting+Shadow"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Taigam, Ojutai Master](https://www.google.com.au/search?q=intext:"Taigam++Ojutai+Master"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Taigam, Sidisi's Hand](https://www.google.com.au/search?q=intext:"Taigam++Sidisi's+Hand"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Teferi's Protection](https://www.google.com.au/search?q=intext:"Teferi's+Protection"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Territorial Hellkite](https://www.google.com.au/search?q=intext:"Territorial+Hellkite"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [The Ur-Dragon](https://www.google.com.au/search?q=intext:"The+Ur-Dragon"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Traverse the Outlands](https://www.google.com.au/search?q=intext:"Traverse+the+Outlands"+Commander+2017+mtg&source=lnms&tbm=isch)
- [x] Done -- [Wasitora, Nekoru Queen](https://www.google.com.au/search?q=intext:"Wasitora++Nekoru+Queen"+Commander+2017+mtg&source=lnms&tbm=isch)

**Comment by spjspj** [comment]
- [ ] In Progress -- [Alms Collector](https://www.google.com.au/search?q=intext:"Alms+Collector"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Arahbo, Roar of the World](https://www.google.com.au/search?q=intext:"Arahbo++Roar+of+the+World"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Balan, Wandering Knight](https://www.google.com.au/search?q=intext:"Balan++Wandering+Knight"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Bloodforged War Axe](https://www.google.com.au/search?q=intext:"Bloodforged+War+Axe"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Bloodline Necromancer](https://www.google.com.au/search?q=intext:"Bloodline+Necromancer"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Boneyard Scourge](https://www.google.com.au/search?q=intext:"Boneyard+Scourge"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Fortunate Few](https://www.google.com.au/search?q=intext:"Fortunate+Few"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Fractured Identity](https://www.google.com.au/search?q=intext:"Fractured+Identity"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Hammer of Nazahn](https://www.google.com.au/search?q=intext:"Hammer+of+Nazahn"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Herald's Horn](https://www.google.com.au/search?q=intext:"Herald's+Horn"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Hungry Lynx](https://www.google.com.au/search?q=intext:"Hungry+Lynx"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Kindred Discovery](https://www.google.com.au/search?q=intext:"Kindred+Discovery"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Licia, Sanguine Tribune](https://www.google.com.au/search?q=intext:"Licia++Sanguine+Tribune"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Mirri, Weatherlight Duelist](https://www.google.com.au/search?q=intext:"Mirri++Weatherlight+Duelist"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Nazahn, Revered Bladesmith](https://www.google.com.au/search?q=intext:"Nazahn++Revered+Bladesmith"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Path of Ancestry](https://www.google.com.au/search?q=intext:"Path+of+Ancestry"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Scalelord Reckoner](https://www.google.com.au/search?q=intext:"Scalelord+Reckoner"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Stalking Leonin](https://www.google.com.au/search?q=intext:"Stalking+Leonin"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Summon the Tribe](https://www.google.com.au/search?q=intext:"Summon+the+Tribe"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Territorial Hellkite](https://www.google.com.au/search?q=intext:"Territorial+Hellkite"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [The Ur-Dragon](https://www.google.com.au/search?q=intext:"The+Ur-Dragon"+Commander+2017+mtg&source=lnms&tbm=isch)
- [ ] In Progress -- [Traverse the Outlands](https://www.google.com.au/search?q=intext:"Traverse+the+Outlands"+Commander+2017+mtg&source=lnms&tbm=isch)

**Comment by JRHerlehy** [comment]
Why are all the cards listed twice?  Is that indicating you're working on all of them...?

**Comment by spjspj** [comment]
No, it gives people a place to say 'In progress' (aka they're working on them).  So the 'Done' vs 'Not Done' tick actually says if it's done or not.  I am currently working on Traverse the Outlands

**Comment by Eleros** [comment]
I've already put up a pull request for Balan a while ago so that's technically done.

**Comment by spjspj** [comment]
I noticed the pull request for Balan so put it to 'In progress' so noone else touches it :)

**Comment by Eleros** [comment]
Got it. Sorry, didn't know this thingy was here before. 
Still new to the whole development part ^^'

**Comment by Eleros** [comment]
Will do Bloodsworn Steward & Hungry Lynx later today.

**Comment by Eleros** [comment]
Working on the curse cycle right now.

**Comment by spjspj** [comment]
Was wondering if I could open this up wider so people can select what they're working on more easily :(

**Comment by Eleros** [comment]
It does seem kinda inconvenient right now. Maybe just use a google doc or something?
Not sure if it's possible right now to give other people rights for checking/unchecking tasks without giving them rights to push to the repo.

**Comment by theelk801** [comment]
Working on the Ur-Dragon right now.

**Comment by Eleros** [comment]
So are you doing Eminence in general then?

**Comment by theelk801** [comment]
I just realized that hadn't been done. I can do that, doesn't seem to hard to implement. I just finished with Ur-Dragon's other ability (need to make sure it works right but I'm pretty sure it does, had to get creative) so I haven't even started on the eminence part yet.

**Comment by theelk801** [comment]
Alright, I'm taking Edgar, Inalla and Arahbo.

**Comment by Eleros** [comment]
Guess I'll do the rest of the Kindred cycle then.
Bloodsworn Steward and Kindred Dominance are already done btw and should be marked as such.

**Comment by theelk801** [comment]
Boneyard Scourge is deceptively difficult. I'm not sure how to make it so it doesn't trigger when it and another dragon both die at the same time.

**Comment by Eleros** [comment]
I'll do Hammer of Nazahn, Heirloom Blade, Shifting Shadow next.

**Comment by Eleros** [comment]
@theelk801 Nether Traitor looks similar enough. Might wanna check that one out.

**Comment by theelk801** [comment]
Just checked, Nether Traitor triggers if it dies at the same time as other creatures even though it isn't supposed to. So now there's another bugged creature.

**Comment by theelk801** [comment]
Does anyone have an idea on how to make Vindictive Lich's targeting restriction work? I tried using the AnotherTargetPredicate and TargetTag from Blood Feud, but it gives me a NullPointerException. Part of me wants to do 7 modes with each chosen once, but that seems unnecessarily complicated.

**Comment by spjspj** [comment]
Something (possibly?) similar is Uncage the Menagerie - you could go through each mode, if they say yes the first time let them choose any target opponent, then if they say yes the second time, in the overridden
```
public boolean canTarget(UUID id, Cards cards, Game game) { 
```
part, you don't let that player be targetted again

```
class UncageTheMenagerieTarget extends TargetCardInLibrary {

    private int xValue;

    public UncageTheMenagerieTarget(int xValue) {
        super(0, xValue, new FilterCreatureCard(xValue + " creature cards with different names with converted mana cost " + xValue));
        this.xValue = xValue;
    }

    public UncageTheMenagerieTarget(final UncageTheMenagerieTarget target) {
        super(target);
        this.xValue = target.xValue;
    }

    @Override
    public UncageTheMenagerieTarget copy() {
        return new UncageTheMenagerieTarget(this);
    }

    @Override
    public boolean canTarget(UUID id, Cards cards, Game game) {
        Card card = cards.get(id, game);
        if (card != null) {
            for (UUID targetId : this.getTargets()) {
                Card iCard = game.getCard(targetId);
                if (iCard != null && iCard.getName().equals(card.getName())) {
                    return false;
                }
            }
            if (!(card.isCreature() && card.getConvertedManaCost() == xValue)) {
                return false;
            }

            return filter.match(card, game);
        }
        return false;
    }
}
```

**Comment by theelk801** [comment]
So I tried to implement without the targeting restriction, basically like Clan Defiance, and it won't let me choose fewer than all three modes.

**Comment by theelk801** [comment]
So I've got Mairsil done except for the "once per turn" stipulation. Anybody got any ideas? I'm thinking of adding a once per turn stipulation to the base ActivatedAbilities class even though it's redundant alongside the LimitedTimesPerTurnActivatedAbility class.

**Comment by LevelX2** [comment]
> Does anyone have an idea on how to make Vindictive Lich's targeting restriction work? I tried using the AnotherTargetPredicate and TargetTag from Blood Feud, but it gives me a NullPointerException.

This should work. Can you provide the code, so I can check what's the problem?

**Comment by theelk801** [comment]
public class VindictiveLich extends CardImpl {

    public VindictiveLich(UUID ownerId, CardSetInfo setInfo) {
        super(ownerId, setInfo, new CardType[]{CardType.CREATURE}, "{3}{B}");

        this.subtype.add("Zombie");
        this.subtype.add("Wizard");
        this.power = new MageInt(4);
        this.toughness = new MageInt(1);

        // When Vindictive Lich dies, choose one or more. Each mode must target a different player.
        // *Target opponent sacrifices a creature.
        Ability ability = new DiesTriggeredAbility(new SacrificeEffect(StaticFilters.FILTER_PERMANENT_CREATURE, 1, "target opponent"));
        ability.addTarget(new TargetOpponent());
        ability.getModes().setMinModes(1);
        ability.getModes().setMaxModes(3);

        // *Target opponent discards two cards.
        Mode mode = new Mode();
        mode.getEffects().add(new DiscardTargetEffect(2, false));
        mode.getTargets().add(new TargetOpponent());
        ability.addMode(mode);

        // *Target opponent loses 5 life.
        mode = new Mode();
        mode.getEffects().add(new LoseLifeTargetEffect(2));
        mode.getTargets().add(new TargetOpponent());
        ability.addMode(mode);
        this.addAbility(ability);
    }

    public VindictiveLich(final VindictiveLich card) {
        super(card);
    }

    @Override
    public VindictiveLich copy() {
        return new VindictiveLich(this);
    }
}

**Comment by LevelX2** [comment]
> So I've got Mairsil done except for the "once per turn" stipulation. Anybody got any ideas? I'm thinking of adding a once per turn stipulation to the base ActivatedAbilities class even though it's redundant alongside the LimitedTimesPerTurnActivatedAbility class.

First idea of mine would be to create a watcher that registered the activations and a rule modifying effect that prevents the activation before the first.

**Comment by LevelX2** [comment]
> public class VindictiveLich

Where do you set the target tags >0? (e.g. target.setTargetTag(1); - etc.)

**Comment by theelk801** [comment]
So this is the version that doesn't have the targeting restriction at all, it can target the same person more than once. I just wanted to see if this one would work before I started adding to it. The problem is that it won't let me choose fewer than all three modes.

**Comment by LevelX2** [comment]
Mode handling for triggered abilities does not yet work correctly with that predicate. I'm looking into it.

**Comment by theelk801** [comment]
Alright, I figured that was the case. I noticed that there haven't been any cards up until now that have modal abilities that allow multiple choices so I'm not surprised that there was an undetected issue.

**Comment by spjspj** [comment]
I'll add in the pre-constructed decks.  Does anyone know of the actual distribution of different colours of lands in them?

**Comment by theelk801** [comment]
https://www.mtggoldfish.com/articles/commander-2017-decklists

That's all the deck lists.

**Comment by spjspj** [comment]
I meant the quantity of say https://img.scryfall.com/cards/large/en/c17/297.jpg vs https://img.scryfall.com/cards/large/en/c17/295.jpg

**Comment by theelk801** [comment]
Yeah, I kind of figured that but was too lazy to check. I can actually get you that info though, I have all four decks.

**Comment by spjspj** [comment]
I can just fudge it.

**Comment by theelk801** [comment]
dragons:
plains:295-297
island:298-300
swamp:301-303
mountain:304-306(2x each)
forest:307-309

**Comment by theelk801** [comment]
wizards:
island:3x(298,300),2x(299)
swamp:2x(301-303)
mountain:2x(304),1x(305,306)

**Comment by theelk801** [comment]
vampires:
swamp: 2x each, 1 extra 302
mountain:same as wizards
plains: same as dragons

**Comment by theelk801** [comment]
cats:
plains:3x(296), 2x(295), 1x(297)
forest: 3x(307), 2x(308), 1x(309)

**Comment by spjspj** [comment]
cheers! 
Can you check if Outpost Siege is in the vampire deck?  Two sources (wizards.com and mtgspoiler.com) both say it is but it feels like it should be in the durgons deck.

**Comment by theelk801** [comment]
Yeah, it's in Vampires and not Dragons. The Dragon deck has three sieges, they probably didn't want to overload it.

**Comment by jeacaveo** [comment]
Do we know if Alms Collector is gonna be implemented soon?

**Comment by theelk801** [comment]
It is, it'll be in the next update.

**Comment by jeacaveo** [comment]
@theelk801 Awesome, thanks for the reply!

**Comment by JayDi85** [comment]
All cards done.
