### ISSUE TITLE
Fallback render mode issues (origin image render)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4168]
Render mode with enabled option "Fall back to plain image based rendering" have many issues. P.S. I'm work on it to fix (done on  #4173 pullrequest):

**1. On missed card**:
- [x] Wrong card size (it's too big):
![shot_171117_014457](https://user-images.githubusercontent.com/8344157/32917554-f6d1a6b2-cb38-11e7-9e4f-b746d1d608b6.png)
![shot_171117_014712](https://user-images.githubusercontent.com/8344157/32917645-47025a14-cb39-11e7-9eeb-6df8ccad0530.png)

- [x] Wrong mana icons position:
![shot_171117_014608](https://user-images.githubusercontent.com/8344157/32917595-1f11e434-cb39-11e7-91f0-ff9a903ed864.png)

**2. On image card**:
- [x] Wrong position for mana and life (it's can be set with margin from rigth-top-bottom corners like origin images):
![shot_171117_015039](https://user-images.githubusercontent.com/8344157/32917926-17d873da-cb3a-11e7-846c-643c7ce56b0a.png)

 - [x] White annoying pips on corners:
![shot_171118_171311](https://user-images.githubusercontent.com/8344157/32980648-ccb7b9ce-cc83-11e7-8e2a-1308fb90ed02.png)

- [ ] Need options to hide all generic icons and text from origin image (now user can hide card's name from option but can't do it for life and mana icons):
![shot_171117_015641](https://user-images.githubusercontent.com/8344157/32918076-9727e0d0-cb3a-11e7-8056-92a1d6b1d37e.png)

- [x] Need round corners:
![shot_171118_052930](https://user-images.githubusercontent.com/8344157/32975526-7fa99920-cc21-11e7-8956-2eb2c16455fd.png)

- [ ] Need to fix aliasing icons on battlefield:
![shot_171118_053016](https://user-images.githubusercontent.com/8344157/32975534-a00e37ca-cc21-11e7-821b-b37a252c7d8f.png)

 - [x] Need to fix black rectangle in deck editor card info:
![shot_171118_053129](https://user-images.githubusercontent.com/8344157/32975556-d9c9b66a-cc21-11e7-8982-218e769f0761.png)

 - [ ] Need to fix card's grouping in deck editor for source list (use the same height as user's deck panel use):
![shot_171125_001803](https://user-images.githubusercontent.com/8344157/33223118-5d2c12f6-d176-11e7-9803-af62479b9628.png)

 - [ ] Need to fix card's grouping in game:
![shot_171220_000353](https://user-images.githubusercontent.com/8344157/34176497-7b1d3ce8-e519-11e7-85c5-208c49f8647b.png)

 - [x] Need to fix can attack border:
![shot_171225_072539](https://user-images.githubusercontent.com/8344157/34331954-ea9761be-e944-11e7-914a-a167d4eab9df.png)

 - [ ] Need to fix draft mode icon sizes:
![shot_171230_060928](https://user-images.githubusercontent.com/8344157/34450649-39981f06-ed28-11e7-9b51-853d8e63185b.png)

 - [ ] Need to rewrite counters -- it's weird
![shot_180111_155825](https://user-images.githubusercontent.com/8344157/34824541-5a06cd4a-f6e8-11e7-8888-40347ba023e5.png)

 - [x] Need to replace repeated banchs of errors on each loading editor by one run error on start up:
![shot_180114_023446](https://user-images.githubusercontent.com/8344157/34910684-c076a626-f8d3-11e7-86c1-fea4994dc647.png)

 - [ ] Show hints in download window about fallback render settings. E.g. after download images user can switch to new render mode.

 - [ ] Add option to select round corners render mode (non, small corners like paper, big corners for white corner pimps remove);
  
 - [ ] Small text is bad visible
![shot_180114_165146](https://user-images.githubusercontent.com/8344157/34916084-4c3012b6-f94b-11e7-94b5-b0b022293c50.png)

 - [x] Energy icons need to replace:
![shot_180129_064021](https://user-images.githubusercontent.com/8344157/35491337-603129e2-04bf-11e8-8211-e74502fd0698.png)

**Comment by JayDi85** [comment]
Outdated. Many render problems was fixed or useless.
