### ISSUE TITLE
Add SVG icons support

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4196]
Wizard's symbols in gif format is weird. It have many artefacts:

![shot_171124_155532](https://user-images.githubusercontent.com/8344157/33209595-ff94b1de-d12f-11e7-92f1-ef04e4051ae0.png)

XMage must use SVG symbols. [Scryfall have it](https://scryfall.com/docs/api/colors). What need to do:
 - [x] add svg library support for images loading;
 - [x] new render for mana icons in cards;
 - [x] new render for mana icons in tables;
 - [x] new render for mana icons in other windows (hints, info);
 - [x] support empty images draw (mana text instead images);
 - [x] support pnp generation from svg (for html texts)
 - [x] add svg symbols downloading from scryfall (not so easy, need parse, API is [not support it yet](https://github.com/scryfall/feedback/issues/620));
 - [x] test new svg version in linux machines (can it draw svg correct?);
 - [ ] check and change symbols sizes and position (some old symbols load by image offsets, old images have "border space" and so on);
 - [x] fix bug with image downloading (after download images is not reloading from disk);
 - [ ] add option to draw mana cost with shadow;
 - [ ] mana icons in card hints and test errors (see #4278);
 - [ ] fix mana icons on card's hint (replace orbs with mana)
 - [ ] fix mana icons in player's badges on:
![shot_171227_061335](https://user-images.githubusercontent.com/8344157/34368427-5d5f059c-eacd-11e7-947b-128d34923199.png)
 - [x] fix windows 10 svg errors;

I'm work on that issue.

Some results:
![mtg - svg -render example](https://user-images.githubusercontent.com/8344157/33210195-a64c4c92-d132-11e7-9071-d98b23aef942.png)

![shot_171125_170837](https://user-images.githubusercontent.com/8344157/33241324-2fdaf50c-d2dd-11e7-8a26-40a92659ceea.png)

![shot_171126_190952](https://user-images.githubusercontent.com/8344157/33241345-6912b116-d2dd-11e7-8144-2c80ed5a9fb2.png)
