### ISSUE TITLE
UST - Card Implementation Tracker (Tracking issue for Unstable) 

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4233]
- [ ] Not done -- [Angelic Rocket](https://www.google.com.au/search?q=intext:"Angelic+Rocket"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [As Luck Would Have It](https://www.google.com.au/search?q=intext:"As+Luck+Would+Have+It"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Baron Von Count](https://www.google.com.au/search?q=intext:"Baron+Von+Count"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Big Boa Constrictor](https://www.google.com.au/search?q=intext:"Big+Boa+Constrictor"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Bumbling Pangolin](https://www.google.com.au/search?q=intext:"Bumbling+Pangolin"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Buzzing Whack-a-Doodle](https://www.google.com.au/search?q=intext:"Buzzing+Whack-a-Doodle"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Chittering Doom](https://www.google.com.au/search?q=intext:"Chittering+Doom"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Common Iguana](https://www.google.com.au/search?q=intext:"Common+Iguana"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Contraption Cannon](https://www.google.com.au/search?q=intext:"Contraption+Cannon"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Crow Storm](https://www.google.com.au/search?q=intext:"Crow+Storm"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Curious Killbot](https://www.google.com.au/search?q=intext:"Curious+Killbot"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Dirty Rat](https://www.google.com.au/search?q=intext:"Dirty+Rat"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Eager Beaver](https://www.google.com.au/search?q=intext:"Eager+Beaver"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Earl of Squirrel](https://www.google.com.au/search?q=intext:"Earl+of+Squirrel"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Feisty Stegosaurus](https://www.google.com.au/search?q=intext:"Feisty+Stegosaurus"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [GO TO JAIL](https://www.google.com.au/search?q=intext:"GO+TO+JAIL"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Gnome-Made Engine](https://www.google.com.au/search?q=intext:"Gnome-Made+Engine"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Ground Pounder](https://www.google.com.au/search?q=intext:"Ground+Pounder"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Hammer Helper](https://www.google.com.au/search?q=intext:"Hammer+Helper"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Hammer Jammer](https://www.google.com.au/search?q=intext:"Hammer+Jammer"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Hangman](https://www.google.com.au/search?q=intext:"Hangman"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Hazmat Suit (Used)](https://www.google.com.au/search?q=intext:"Hazmat+Suit+(Used)"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Hot Fix](https://www.google.com.au/search?q=intext:"Hot+Fix"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Hydradoodle](https://www.google.com.au/search?q=intext:"Hydradoodle"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Incite Insight](https://www.google.com.au/search?q=intext:"Incite+Insight"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Inhumaniac](https://www.google.com.au/search?q=intext:"Inhumaniac"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Jackknight](https://www.google.com.au/search?q=intext:"Jackknight"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Krark's Other Thumb](https://www.google.com.au/search?q=intext:"Krark's+Other+Thumb"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Lobe Lobber](https://www.google.com.au/search?q=intext:"Lobe+Lobber"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Mad Science Fair Project](https://www.google.com.au/search?q=intext:"Mad+Science+Fair+Project"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Mer Man](https://www.google.com.au/search?q=intext:"Mer+Man"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Numbing Jellyfish](https://www.google.com.au/search?q=intext:"Numbing+Jellyfish"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Ordinary Pony](https://www.google.com.au/search?q=intext:"Ordinary+Pony"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Painiac](https://www.google.com.au/search?q=intext:"Painiac"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Shaggy Camel](https://www.google.com.au/search?q=intext:"Shaggy+Camel"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Skull Saucer](https://www.google.com.au/search?q=intext:"Skull+Saucer"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Snickering Squirrel](https://www.google.com.au/search?q=intext:"Snickering+Squirrel"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Split Screen](https://www.google.com.au/search?q=intext:"Split+Screen"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Spy Eye](https://www.google.com.au/search?q=intext:"Spy+Eye"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Squirrel-Powered Scheme](https://www.google.com.au/search?q=intext:"Squirrel-Powered+Scheme"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Staff of the Letter Magus](https://www.google.com.au/search?q=intext:"Staff+of+the+Letter+Magus"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Steamflogger Boss](https://www.google.com.au/search?q=intext:"Steamflogger+Boss"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Steamflogger Service Rep](https://www.google.com.au/search?q=intext:"Steamflogger+Service+Rep"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Steel Squirrel](https://www.google.com.au/search?q=intext:"Steel+Squirrel"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Stinging Scorpion](https://www.google.com.au/search?q=intext:"Stinging+Scorpion"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Summon the Pack](https://www.google.com.au/search?q=intext:"Summon+the+Pack"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [The Big Idea](https://www.google.com.au/search?q=intext:"The+Big+Idea"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Time Out](https://www.google.com.au/search?q=intext:"Time+Out"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Voracious Vacuum](https://www.google.com.au/search?q=intext:"Voracious+Vacuum"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Wall of Fortune](https://www.google.com.au/search?q=intext:"Wall+of+Fortune"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Wild Crocodile](https://www.google.com.au/search?q=intext:"Wild+Crocodile"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Willing Test Subject](https://www.google.com.au/search?q=intext:"Willing+Test+Subject"+Unstable+mtg&source=lnms&tbm=isch)
- [x] Done -- [Sword of Dungeons and Dragons](https://www.google.com.au/search?q=intext:"Sword+of+Dungeons+and+Dragons"+Unstable+mtg&source=lnms&tbm=isch)

**Comment by spjspj** [comment]
- [ ] Reserved/In progress -- [Angelic Rocket](https://www.google.com.au/search?q=intext:"Angelic+Rocket"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [As Luck Would Have It](https://www.google.com.au/search?q=intext:"As+Luck+Would+Have+It"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Baron Von Count](https://www.google.com.au/search?q=intext:"Baron+Von+Count"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Big Boa Constrictor](https://www.google.com.au/search?q=intext:"Big+Boa+Constrictor"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Bumbling Pangolin](https://www.google.com.au/search?q=intext:"Bumbling+Pangolin"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Buzzing Whack-a-Doodle](https://www.google.com.au/search?q=intext:"Buzzing+Whack-a-Doodle"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Chittering Doom](https://www.google.com.au/search?q=intext:"Chittering+Doom"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Common Iguana](https://www.google.com.au/search?q=intext:"Common+Iguana"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Contraption Cannon](https://www.google.com.au/search?q=intext:"Contraption+Cannon"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Crow Storm](https://www.google.com.au/search?q=intext:"Crow+Storm"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Curious Killbot](https://www.google.com.au/search?q=intext:"Curious+Killbot"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Dirty Rat](https://www.google.com.au/search?q=intext:"Dirty+Rat"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Eager Beaver](https://www.google.com.au/search?q=intext:"Eager+Beaver"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Earl of Squirrel](https://www.google.com.au/search?q=intext:"Earl+of+Squirrel"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Feisty Stegosaurus](https://www.google.com.au/search?q=intext:"Feisty+Stegosaurus"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [GO TO JAIL](https://www.google.com.au/search?q=intext:"GO+TO+JAIL"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Gnome-Made Engine](https://www.google.com.au/search?q=intext:"Gnome-Made+Engine"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Ground Pounder](https://www.google.com.au/search?q=intext:"Ground+Pounder"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Hammer Helper](https://www.google.com.au/search?q=intext:"Hammer+Helper"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Hammer Jammer](https://www.google.com.au/search?q=intext:"Hammer+Jammer"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Hangman](https://www.google.com.au/search?q=intext:"Hangman"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Hazmat Suit (Used)](https://www.google.com.au/search?q=intext:"Hazmat+Suit+(Used)"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Hot Fix](https://www.google.com.au/search?q=intext:"Hot+Fix"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Hydradoodle](https://www.google.com.au/search?q=intext:"Hydradoodle"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Incite Insight](https://www.google.com.au/search?q=intext:"Incite+Insight"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Inhumaniac](https://www.google.com.au/search?q=intext:"Inhumaniac"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Jackknight](https://www.google.com.au/search?q=intext:"Jackknight"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Krark's Other Thumb](https://www.google.com.au/search?q=intext:"Krark's+Other+Thumb"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Lobe Lobber](https://www.google.com.au/search?q=intext:"Lobe+Lobber"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Mad Science Fair Project](https://www.google.com.au/search?q=intext:"Mad+Science+Fair+Project"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Mer Man](https://www.google.com.au/search?q=intext:"Mer+Man"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Numbing Jellyfish](https://www.google.com.au/search?q=intext:"Numbing+Jellyfish"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Ordinary Pony](https://www.google.com.au/search?q=intext:"Ordinary+Pony"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Painiac](https://www.google.com.au/search?q=intext:"Painiac"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Shaggy Camel](https://www.google.com.au/search?q=intext:"Shaggy+Camel"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Skull Saucer](https://www.google.com.au/search?q=intext:"Skull+Saucer"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Snickering Squirrel](https://www.google.com.au/search?q=intext:"Snickering+Squirrel"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Split Screen](https://www.google.com.au/search?q=intext:"Split+Screen"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Spy Eye](https://www.google.com.au/search?q=intext:"Spy+Eye"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Squirrel-Powered Scheme](https://www.google.com.au/search?q=intext:"Squirrel-Powered+Scheme"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Staff of the Letter Magus](https://www.google.com.au/search?q=intext:"Staff+of+the+Letter+Magus"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Steamflogger Boss](https://www.google.com.au/search?q=intext:"Steamflogger+Boss"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Steamflogger Service Rep](https://www.google.com.au/search?q=intext:"Steamflogger+Service+Rep"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Steel Squirrel](https://www.google.com.au/search?q=intext:"Steel+Squirrel"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Stinging Scorpion](https://www.google.com.au/search?q=intext:"Stinging+Scorpion"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Summon the Pack](https://www.google.com.au/search?q=intext:"Summon+the+Pack"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [The Big Idea](https://www.google.com.au/search?q=intext:"The+Big+Idea"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Time Out](https://www.google.com.au/search?q=intext:"Time+Out"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Voracious Vacuum](https://www.google.com.au/search?q=intext:"Voracious+Vacuum"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Wall of Fortune](https://www.google.com.au/search?q=intext:"Wall+of+Fortune"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Wild Crocodile](https://www.google.com.au/search?q=intext:"Wild+Crocodile"+Unstable+mtg&source=lnms&tbm=isch)
- [ ] Reserved/In progress -- [Willing Test Subject](https://www.google.com.au/search?q=intext:"Willing+Test+Subject"+Unstable+mtg&source=lnms&tbm=isch)

**Comment by JayDi85** [comment]
!!!**WARNING**!!! 
Don't broke the game and don't add bloating code to game engine. It's a very dangerous set. If game haven't necessary ability, then don't implement it. [Technical debt](https://en.wikipedia.org/wiki/Technical_debt) is very bad thing.

I recommend to create check list "possible/unpossible to implement" in xmage.

**Comment by spjspj** [comment]
These are the ones that are slightly implementable (aka I've taken out ones that have keywords such as watermark, reminder text, 'copy text box' etc.  For the 'Host' creature ones I was thinking we could either implement it without the 'Host' part (as I also didn't list the 'Augment' type cards).

But Crow Storm is eminently playable and way cooler than Empty the Warrens.  We also have the Star Wars Set as an example of an existing set which is non-standard.

**Comment by theelk801** [comment]
I think Crow Storm is the only one we really need to be honest, it's the one people are gonna want to put in their cubes at least.

**Comment by theelk801** [comment]
If we want to do die rolls we'll want to add an infrastructure for it to allow for cards that modify them or trigger off of them. I can't say I really want to though, I'd rather start with the voting matters cards from Conspiracy first.

**Comment by theelk801** [comment]
Well I just mean so that we can have things which trigger off of and modify the results of die rolls. Just rolling a die is whatever, but making them interact with each other is another matter.

**Comment by JayDi85** [comment]
Can you show card's example with modified roll's result?

Found only that (one or two rolls):
1. Simple roll activating on other trigger (enter to battlefield): [Feisty Stegosaurus](https://scryfall.com/card/ust/81)
![shot_171209_203257](https://user-images.githubusercontent.com/8344157/33797380-29d75568-dd20-11e7-809d-d0525b9227d1.png)
2. Simple trigger's ability on other trigger (rolling): [Ground Pounder](https://scryfall.com/card/ust/104)
![shot_171209_203436](https://user-images.githubusercontent.com/8344157/33797397-651dd188-dd20-11e7-9327-ce00ffe4d0b6.png)

**Comment by theelk801** [comment]
![](http://mythicspoiler.com/ust/cards/snickeringsquirrel.jpg)
![](http://mythicspoiler.com/ust/cards/walloffortune.jpg)
![](http://mythicspoiler.com/ust/cards/squirrelpoweredscheme.jpg)

**Comment by JayDi85** [comment]
Can't find [Dr. Julius Jumblemorph](https://scryfall.com/card/ust/130) card in todo list. It's already implemented by xmage in [Mistform Ultimus](https://scryfall.com/card/tsb/26) card.

> Dr. Julius Jumblemorph is every creature type (even if this card isn’t on the battlefield).

![shot_171216_042442](https://user-images.githubusercontent.com/8344157/34065191-0d530286-e219-11e7-86fd-fd24e144c621.png)

**Comment by spjspj** [comment]
^^ Noone's implemented Host/Augment yet so I didn't bother adding it to the list.

**Comment by Iwasrunningoutofnamesatthispoint** [comment]
Its not all about the Host/Augment abillity.
A G/W Changeling makes an awesome commander.

What are the chances to see the other Legendary creatures too? The big idea appears doable to me...

**Comment by spjspj** [comment]
Yes, the big idea is doable.  It's not really a good thing to add a semi-implemented card.

**Comment by Iwasrunningoutofnamesatthispoint** [comment]
I dont see an issue with implementing him this way.
Since we dont have augment cards yet all he will do is to shuffle your lib. Which also seems to be easy to implement.
Nobody will be upset if its done this way :)

(and I will be happy)

**Comment by Zzooouhh** [comment]
I've made Infinity Elemental, or at least the closest approximation possible within the current engine to my knowledge - its power constantly hovers at Integer.MAX_VALUE and is unchangeable by boost effects unless a "set power" effect (such as Sorceress Queen) overwrites it - this is predominantly intended to prevent integer overflows. I've tested it with boost effects and set P/T effects, please have a look whether I missed anything important: 8bc9ae1

**Comment by JayDi85** [comment]
@Zzooouhh 
[Java can't handle integer overflow at all](https://stackoverflow.com/questions/3001836/how-does-java-handle-integer-underflows-and-overflows-and-how-would-you-check-fo).

If xmage got overflow "error" then you can't find it and app/server will work at normal but with wrong values. It's a bad thing.

Search xmage code and found `Integer.MAX_VALUE` in many sources. Try to test Infinity Elemental with single and double strike on [Terrifying Presence](https://scryfall.com/card/ddl/65) or another damage prevention card (it have PreventionEffectImpl with max int -- if Infinity Elemental may can kill that creature then it's a bug).

**Comment by Zzooouhh** [comment]
@JayDi85 Damage prevention correctly negates all the damage Infinity Elemental would deal. What however makes it behave badly is damage value modifying effects (Dictate of the Twin Gods, etc.), double strike damage if the first hit isn't lethal, "gain life equal to this creature's power" type effects, and . All of these are probably solvable by just including an integer overflow check on PlayerImpl.gainLife and PlayerImpl.loseLife (maybe also PlayerImpl.doDamage, which would probably be redundant)
