### ISSUE TITLE
Rivals of Ixalan - Card implementation

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4328]
# Cards in set:
- [x] [Admiral's Order](https://www.google.com.au/search?q=Admiral's+Order+MTG&tbm=isch)
- [x] [Aggressive Urge](https://www.google.com.au/search?q=Aggressive+Urge+MTG&tbm=isch)
- [x] [Angrath's Ambusher](https://www.google.com.au/search?q=Angrath's+Ambusher+MTG&tbm=isch)
- [x] [Angrath's Fury](https://www.google.com.au/search?q=Angrath's+Fury+MTG&tbm=isch)
- [x] [Angrath, Minotaur Pirate](https://www.google.com.au/search?q=Angrath,+Minotaur+Pirate+MTG&tbm=isch)
- [x] [Angrath, the Flame-Chained](https://www.google.com.au/search?q=Angrath,+the+Flame-Chained+MTG&tbm=isch)
- [x] [Aquatic Incursion](https://www.google.com.au/search?q=Aquatic+Incursion+MTG&tbm=isch)
- [x] [Arch of Orazca](https://www.google.com.au/search?q=Arch+of+Orazca+MTG&tbm=isch)
- [x] [Arterial Flow](https://www.google.com.au/search?q=Arterial+Flow+MTG&tbm=isch)
- [x] [Atzal, Cave of Eternity](https://www.google.com.au/search?q=Atzal,+Cave+of+Eternity+MTG&tbm=isch)
- [x] [Atzocan Seer](https://www.google.com.au/search?q=Atzocan+Seer+MTG&tbm=isch)
- [x] [Awakened Amalgam](https://www.google.com.au/search?q=Awakened+Amalgam+MTG&tbm=isch)
- [x] [Azor's Gateway](https://www.google.com.au/search?q=Azor's+Gateway+MTG&tbm=isch)
- [x] [Azor, the Lawbringer](https://www.google.com.au/search?q=Azor,+the+Lawbringer+MTG&tbm=isch)
- [x] [Baffling End](https://www.google.com.au/search?q=Baffling+End+MTG&tbm=isch)
- [x] [Bishop of Binding](https://www.google.com.au/search?q=Bishop+of+Binding+MTG&tbm=isch)
- [x] [Blazing Hope](https://www.google.com.au/search?q=Blazing+Hope+MTG&tbm=isch)
- [x] [Blood Sun](https://www.google.com.au/search?q=Blood+Sun+MTG&tbm=isch)
- [x] [Bombard](https://www.google.com.au/search?q=Bombard+MTG&tbm=isch)
- [x] [Brass's Bounty](https://www.google.com.au/search?q=Brass's+Bounty+MTG&tbm=isch)
- [x] [Brazen Freebooter](https://www.google.com.au/search?q=Brazen+Freebooter+MTG&tbm=isch)
- [x] [Buccaneer's Bravado](https://www.google.com.au/search?q=Buccaneer's+Bravado+MTG&tbm=isch)
- [x] [Cacophodon](https://www.google.com.au/search?q=Cacophodon+MTG&tbm=isch)
- [x] [Canal Monitor](https://www.google.com.au/search?q=Canal+Monitor+MTG&tbm=isch)
- [x] [Captain's Hook](https://www.google.com.au/search?q=Captain's+Hook+MTG&tbm=isch)
- [x] [Champion of Dusk](https://www.google.com.au/search?q=Champion+of+Dusk+MTG&tbm=isch)
- [x] [Charging Tuskodon](https://www.google.com.au/search?q=Charging+Tuskodon+MTG&tbm=isch)
- [x] [Cherished Hatchling](https://www.google.com.au/search?q=Cherished+Hatchling+MTG&tbm=isch)
- [x] [Cinder Barrens](https://www.google.com.au/search?q=Cinder+Barrens+MTG&tbm=isch)
- [x] [Cleansing Ray](https://www.google.com.au/search?q=Cleansing+Ray+MTG&tbm=isch)
- [x] [Colossal Dreadmaw](https://www.google.com.au/search?q=Colossal+Dreadmaw+MTG&tbm=isch)
- [x] [Crafty Cutpurse](https://www.google.com.au/search?q=Crafty+Cutpurse+MTG&tbm=isch)
- [x] [Crashing Tide](https://www.google.com.au/search?q=Crashing+Tide+MTG&tbm=isch)
- [x] [Crested Herdcaller](https://www.google.com.au/search?q=Crested+Herdcaller+MTG&tbm=isch)
- [x] [Curious Obsession](https://www.google.com.au/search?q=Curious+Obsession+MTG&tbm=isch)
- [x] [Daring Buccaneer](https://www.google.com.au/search?q=Daring+Buccaneer+MTG&tbm=isch)
- [x] [Dark Inquiry](https://www.google.com.au/search?q=Dark+Inquiry+MTG&tbm=isch)
- [x] [Dead Man's Chest](https://www.google.com.au/search?q=Dead+Man's+Chest+MTG&tbm=isch)
- [x] [Deadeye Brawler](https://www.google.com.au/search?q=Deadeye+Brawler+MTG&tbm=isch)
- [x] [Deadeye Rig-Hauler](https://www.google.com.au/search?q=Deadeye+Rig-Hauler+MTG&tbm=isch)
- [x] [Deeproot Elite](https://www.google.com.au/search?q=Deeproot+Elite+MTG&tbm=isch)
- [x] [Dinosaur Hunter](https://www.google.com.au/search?q=Dinosaur+Hunter+MTG&tbm=isch)
- [x] [Dire Fleet Daredevil](https://www.google.com.au/search?q=Dire+Fleet+Daredevil+MTG&tbm=isch)
- [x] [Dire Fleet Neckbreaker](https://www.google.com.au/search?q=Dire+Fleet+Neckbreaker+MTG&tbm=isch)
- [x] [Dire Fleet Poisoner](https://www.google.com.au/search?q=Dire+Fleet+Poisoner+MTG&tbm=isch)
- [x] [Divine Verdict](https://www.google.com.au/search?q=Divine+Verdict+MTG&tbm=isch)
- [x] [Dusk Charger](https://www.google.com.au/search?q=Dusk+Charger+MTG&tbm=isch)
- [x] [Dusk Legion Zealot](https://www.google.com.au/search?q=Dusk+Legion+Zealot+MTG&tbm=isch)
- [x] [Elenda, the Dusk Rose](https://www.google.com.au/search?q=Elenda,+the+Dusk+Rose+MTG&tbm=isch)
- [x] [Enter the Unknown](https://www.google.com.au/search?q=Enter+the+Unknown+MTG&tbm=isch)
- [x] [Etali, Primal Storm](https://www.google.com.au/search?q=Etali,+Primal+Storm+MTG&tbm=isch)
- [x] [Everdawn Champion](https://www.google.com.au/search?q=Everdawn+Champion+MTG&tbm=isch)
- [x] [Evolving Wilds](https://www.google.com.au/search?q=Evolving+Wilds+MTG&tbm=isch)
- [x] [Expel From Orazca](https://www.google.com.au/search?q=Expel+From+Orazca+MTG&tbm=isch)
- [x] [Exultant Skymarcher](https://www.google.com.au/search?q=Exultant+Skymarcher+MTG&tbm=isch)
- [x] [Famished Paladin](https://www.google.com.au/search?q=Famished+Paladin+MTG&tbm=isch)
- [x] [Fanatical Firebrand](https://www.google.com.au/search?q=Fanatical+Firebrand+MTG&tbm=isch)
- [x] [Fathom Fleet Boarder](https://www.google.com.au/search?q=Fathom+Fleet+Boarder+MTG&tbm=isch)
- [x] [Flood of Recollection](https://www.google.com.au/search?q=Flood+of+Recollection+MTG&tbm=isch)
- [x] [Forerunner of the Coalition](https://www.google.com.au/search?q=Forerunner+of+the+Coalition+MTG&tbm=isch)
- [x] [Forerunner of the Empire](https://www.google.com.au/search?q=Forerunner+of+the+Empire+MTG&tbm=isch)
- [x] [Forerunner of the Heralds](https://www.google.com.au/search?q=Forerunner+of+the+Heralds+MTG&tbm=isch)
- [x] [Forerunner of the Legion](https://www.google.com.au/search?q=Forerunner+of+the+Legion+MTG&tbm=isch)
- [x] [Forest](https://www.google.com.au/search?q=Forest+MTG&tbm=isch)
- [x] [Form of the Dinosaur](https://www.google.com.au/search?q=Form+of+the+Dinosaur+MTG&tbm=isch)
- [x] [Forsaken Sanctuary](https://www.google.com.au/search?q=Forsaken+Sanctuary+MTG&tbm=isch)
- [x] [Foul Orchard](https://www.google.com.au/search?q=Foul+Orchard+MTG&tbm=isch)
- [x] [Frilled Deathspitter](https://www.google.com.au/search?q=Frilled+Deathspitter+MTG&tbm=isch)
- [x] [Ghalta, Primal Hunger](https://www.google.com.au/search?q=Ghalta,+Primal+Hunger+MTG&tbm=isch)
- [x] [Giltgrove Stalker](https://www.google.com.au/search?q=Giltgrove+Stalker+MTG&tbm=isch)
- [x] [Gleaming Barrier](https://www.google.com.au/search?q=Gleaming+Barrier+MTG&tbm=isch)
- [x] [Goblin Trailblazer](https://www.google.com.au/search?q=Goblin+Trailblazer+MTG&tbm=isch)
- [x] [Gold-Forge Garrison](https://www.google.com.au/search?q=Gold-Forge+Garrison+MTG&tbm=isch)
- [x] [Golden  Guardian](https://www.google.com.au/search?q=Golden++Guardian+MTG&tbm=isch)
- [x] [Golden Demise](https://www.google.com.au/search?q=Golden+Demise+MTG&tbm=isch)
- [x] [Grasping Scoundrel](https://www.google.com.au/search?q=Grasping+Scoundrel+MTG&tbm=isch)
- [x] [Gruesome Fate](https://www.google.com.au/search?q=Gruesome+Fate+MTG&tbm=isch)
- [x] [Hadana's Climb](https://www.google.com.au/search?q=Hadana's+Climb+MTG&tbm=isch)
- [x] [Hardy Veteran](https://www.google.com.au/search?q=Hardy+Veteran+MTG&tbm=isch)
- [x] [Highland Lake](https://www.google.com.au/search?q=Highland+Lake+MTG&tbm=isch)
- [x] [Hornswoggle](https://www.google.com.au/search?q=Hornswoggle+MTG&tbm=isch)
- [x] [Huatli, Radiant Champion](https://www.google.com.au/search?q=Huatli,+Radiant+Champion+MTG&tbm=isch)
- [x] [Hunt the Weak](https://www.google.com.au/search?q=Hunt+the+Weak+MTG&tbm=isch)
- [x] [Impale](https://www.google.com.au/search?q=Impale+MTG&tbm=isch)
- [x] [Imperial Ceratops](https://www.google.com.au/search?q=Imperial+Ceratops+MTG&tbm=isch)
- [x] [Induced Amnesia](https://www.google.com.au/search?q=Induced+Amnesia+MTG&tbm=isch)
- [x] [Island](https://www.google.com.au/search?q=Island+MTG&tbm=isch)
- [x] [Jade Bearer](https://www.google.com.au/search?q=Jade+Bearer+MTG&tbm=isch)
- [x] [Jadecraft Artisan](https://www.google.com.au/search?q=Jadecraft+Artisan+MTG&tbm=isch)
- [x] [Jadelight Ranger](https://www.google.com.au/search?q=Jadelight+Ranger+MTG&tbm=isch)
- [x] [Journey to Eternity](https://www.google.com.au/search?q=Journey+to+Eternity+MTG&tbm=isch)
- [x] [Jungle Creeper](https://www.google.com.au/search?q=Jungle+Creeper+MTG&tbm=isch)
- [x] [Jungleborn Pioneer](https://www.google.com.au/search?q=Jungleborn+Pioneer+MTG&tbm=isch)
- [x] [Kitesail Corsair](https://www.google.com.au/search?q=Kitesail+Corsair+MTG&tbm=isch)
- [x] [Knight of the Stampede](https://www.google.com.au/search?q=Knight+of+the+Stampede+MTG&tbm=isch)
- [x] [Kumena's Awakening](https://www.google.com.au/search?q=Kumena's+Awakening+MTG&tbm=isch)
- [x] [Kumena, Tyrant of Orazca](https://www.google.com.au/search?q=Kumena,+Tyrant+of+Orazca+MTG&tbm=isch)
- [x] [Legion Conquistador](https://www.google.com.au/search?q=Legion+Conquistador+MTG&tbm=isch)
- [x] [Legion Lieutenant](https://www.google.com.au/search?q=Legion+Lieutenant+MTG&tbm=isch)
- [x] [Luminous Bond](https://www.google.com.au/search?q=Luminous+Bond+MTG&tbm=isch)
- [x] [Majestic Heliopterus](https://www.google.com.au/search?q=Majestic+Heliopterus+MTG&tbm=isch)
- [x] [Martyr of Dusk](https://www.google.com.au/search?q=Martyr+of+Dusk+MTG&tbm=isch)
- [x] [Mastermind's Acquisition](https://www.google.com.au/search?q=Mastermind's+Acquisition+MTG&tbm=isch)
- [x] [Mausoleum Harpy](https://www.google.com.au/search?q=Mausoleum+Harpy+MTG&tbm=isch)
- [x] [Merfolk Mistbinder](https://www.google.com.au/search?q=Merfolk+Mistbinder+MTG&tbm=isch)
- [x] [Metzali, Tower of Triumph](https://www.google.com.au/search?q=Metzali,+Tower+of+Triumph+MTG&tbm=isch)
- [x] [Mist-Cloacked Herald](https://www.google.com.au/search?q=Mist-Cloacked+Herald+MTG&tbm=isch)
- [x] [Moment of Craving](https://www.google.com.au/search?q=Moment+of+Craving+MTG&tbm=isch)
- [x] [Moment of Triumph](https://www.google.com.au/search?q=Moment+of+Triumph+MTG&tbm=isch)
- [x] [Mountain](https://www.google.com.au/search?q=Mountain+MTG&tbm=isch)
- [x] [Mutiny](https://www.google.com.au/search?q=Mutiny+MTG&tbm=isch)
- [x] [Naturalize](https://www.google.com.au/search?q=Naturalize+MTG&tbm=isch)
- [x] [Needletooth Raptor](https://www.google.com.au/search?q=Needletooth+Raptor+MTG&tbm=isch)
- [x] [Negate](https://www.google.com.au/search?q=Negate+MTG&tbm=isch)
- [x] [Nezahal, Primal Tide](https://www.google.com.au/search?q=Nezahal,+Primal+Tide+MTG&tbm=isch)
- [x] [Oathsworn Vampire](https://www.google.com.au/search?q=Oathsworn+Vampire+MTG&tbm=isch)
- [x] [Orazca Frillback](https://www.google.com.au/search?q=Orazca+Frillback+MTG&tbm=isch)
- [x] [Orazca Raptor](https://www.google.com.au/search?q=Orazca+Raptor+MTG&tbm=isch)
- [x] [Orazca Relic](https://www.google.com.au/search?q=Orazca+Relic+MTG&tbm=isch)
- [x] [Overgrown Armasaur](https://www.google.com.au/search?q=Overgrown+Armasaur+MTG&tbm=isch)
- [x] [Paladin of Atonement](https://www.google.com.au/search?q=Paladin+of+Atonement+MTG&tbm=isch)
- [x] [Path of Mettle](https://www.google.com.au/search?q=Path+of+Mettle+MTG&tbm=isch)
- [x] [Path to Discovery](https://www.google.com.au/search?q=Path+to+Discovery+MTG&tbm=isch)
- [x] [Pirate's Pillage](https://www.google.com.au/search?q=Pirate's+Pillage+MTG&tbm=isch)
- [x] [Pitiless Plunderer](https://www.google.com.au/search?q=Pitiless+Plunderer+MTG&tbm=isch)
- [x] [Plains](https://www.google.com.au/search?q=Plains+MTG&tbm=isch)
- [x] [Plummet](https://www.google.com.au/search?q=Plummet+MTG&tbm=isch)
- [x] [Polyraptor](https://www.google.com.au/search?q=Polyraptor+MTG&tbm=isch)
- [x] [Pride of Conquerors](https://www.google.com.au/search?q=Pride+of+Conquerors+MTG&tbm=isch)
- [x] [Profane Procession](https://www.google.com.au/search?q=Profane+Procession+MTG&tbm=isch)
- [x] [Protean Raider](https://www.google.com.au/search?q=Protean+Raider+MTG&tbm=isch)
- [x] [Radiant Destiny](https://www.google.com.au/search?q=Radiant+Destiny+MTG&tbm=isch)
- [x] [Raging Regisaur](https://www.google.com.au/search?q=Raging+Regisaur+MTG&tbm=isch)
- [x] [Raptor Companion](https://www.google.com.au/search?q=Raptor+Companion+MTG&tbm=isch)
- [x] [Ravenous Chupacabra](https://www.google.com.au/search?q=Ravenous+Chupacabra+MTG&tbm=isch)
- [x] [Reaver Ambush](https://www.google.com.au/search?q=Reaver+Ambush+MTG&tbm=isch)
- [x] [Reckless Rage](https://www.google.com.au/search?q=Reckless+Rage+MTG&tbm=isch)
- [x] [Recover](https://www.google.com.au/search?q=Recover+MTG&tbm=isch)
- [x] [Rekindling Phoenix](https://www.google.com.au/search?q=Rekindling+Phoenix+MTG&tbm=isch)
- [x] [Relentless Raptor](https://www.google.com.au/search?q=Relentless+Raptor+MTG&tbm=isch)
- [x] [Resplendent Griffin](https://www.google.com.au/search?q=Resplendent+Griffin+MTG&tbm=isch)
- [x] [Return to the Wind](https://www.google.com.au/search?q=Return+to+the+Wind+MTG&tbm=isch)
- [x] [River Darter](https://www.google.com.au/search?q=River+Darter+MTG&tbm=isch)
- [x] [Riverwise Augur](https://www.google.com.au/search?q=Riverwise+Augur+MTG&tbm=isch)
- [x] [Sadistic Skymarcher](https://www.google.com.au/search?q=Sadistic+Skymarcher+MTG&tbm=isch)
- [x] [Sailor of Means](https://www.google.com.au/search?q=Sailor+of+Means+MTG&tbm=isch)
- [x] [Sanctum of the Sun](https://www.google.com.au/search?q=Sanctum+of+the+Sun+MTG&tbm=isch)
- [x] [Sanguine Glorifier](https://www.google.com.au/search?q=Sanguine+Glorifier+MTG&tbm=isch)
- [x] [Sea Legs](https://www.google.com.au/search?q=Sea+Legs+MTG&tbm=isch)
- [x] [Seafloor Oracle](https://www.google.com.au/search?q=Seafloor+Oracle+MTG&tbm=isch)
- [x] [Secrets of the Golden City](https://www.google.com.au/search?q=Secrets+of+the+Golden+City+MTG&tbm=isch)
- [x] [See Red](https://www.google.com.au/search?q=See+Red+MTG&tbm=isch)
- [x] [Shake the Foundations](https://www.google.com.au/search?q=Shake+the+Foundations+MTG&tbm=isch)
- [x] [Shatter](https://www.google.com.au/search?q=Shatter+MTG&tbm=isch)
- [x] [Siegehorn Ceratops](https://www.google.com.au/search?q=Siegehorn+Ceratops+MTG&tbm=isch)
- [x] [Silent Gravestone](https://www.google.com.au/search?q=Silent+Gravestone+MTG&tbm=isch)
- [x] [Silverclad Ferocidons](https://www.google.com.au/search?q=Silverclad+Ferocidons+MTG&tbm=isch)
- [x] [Silvergill Adept](https://www.google.com.au/search?q=Silvergill+Adept+MTG&tbm=isch)
- [x] [Siren Reaver](https://www.google.com.au/search?q=Siren+Reaver+MTG&tbm=isch)
- [x] [Skymarcher Aspirant](https://www.google.com.au/search?q=Skymarcher+Aspirant+MTG&tbm=isch)
- [x] [Slaughter the Strong](https://www.google.com.au/search?q=Slaughter+the+Strong+MTG&tbm=isch)
- [x] [Slippery Scoundrel](https://www.google.com.au/search?q=Slippery+Scoundrel+MTG&tbm=isch)
- [x] [Snubhorn Sentry](https://www.google.com.au/search?q=Snubhorn+Sentry+MTG&tbm=isch)
- [x] [Soul of the Rapids](https://www.google.com.au/search?q=Soul+of+the+Rapids+MTG&tbm=isch)
- [x] [Sphinx's Decree](https://www.google.com.au/search?q=Sphinx's+Decree+MTG&tbm=isch)
- [x] [Spire Winder](https://www.google.com.au/search?q=Spire+Winder+MTG&tbm=isch)
- [x] [Squire's Devotion](https://www.google.com.au/search?q=Squire's+Devotion+MTG&tbm=isch)
- [x] [Stampeding Horncrest](https://www.google.com.au/search?q=Stampeding+Horncrest+MTG&tbm=isch)
- [x] [Stone Quarry](https://www.google.com.au/search?q=Stone+Quarry+MTG&tbm=isch)
- [x] [Storm Fleet Sprinter](https://www.google.com.au/search?q=Storm+Fleet+Sprinter+MTG&tbm=isch)
- [x] [Storm Fleet Swashbuckler](https://www.google.com.au/search?q=Storm+Fleet+Swashbuckler+MTG&tbm=isch)
- [x] [Storm the Vault](https://www.google.com.au/search?q=Storm+the+Vault+MTG&tbm=isch)
- [x] [Strength of the Pack](https://www.google.com.au/search?q=Strength+of+the+Pack+MTG&tbm=isch)
- [x] [Strider Harness](https://www.google.com.au/search?q=Strider+Harness+MTG&tbm=isch)
- [x] [Sun Sentinel](https://www.google.com.au/search?q=Sun+Sentinel+MTG&tbm=isch)
- [x] [Sun-Collared Raptor](https://www.google.com.au/search?q=Sun-Collared+Raptor+MTG&tbm=isch)
- [x] [Sun-Crested Pterodon](https://www.google.com.au/search?q=Sun-Crested+Pterodon+MTG&tbm=isch)
- [x] [Swab Goblin](https://www.google.com.au/search?q=Swab+Goblin+MTG&tbm=isch)
- [x] [Swaggering Corsair](https://www.google.com.au/search?q=Swaggering+Corsair+MTG&tbm=isch)
- [x] [Swamp](https://www.google.com.au/search?q=Swamp+MTG&tbm=isch)
- [x] [Swift Warden](https://www.google.com.au/search?q=Swift+Warden+MTG&tbm=isch)
- [x] [Sworn Gaurdian](https://www.google.com.au/search?q=Sworn+Gaurdian+MTG&tbm=isch)
- [x] [Temple Altisaur](https://www.google.com.au/search?q=Temple+Altisaur+MTG&tbm=isch)
- [x] [Tendershoot Dryad](https://www.google.com.au/search?q=Tendershoot+Dryad+MTG&tbm=isch)
- [x] [Tetzimoc, Primal Death](https://www.google.com.au/search?q=Tetzimoc,+Primal+Death+MTG&tbm=isch)
- [x] [The Immortal Sun](https://www.google.com.au/search?q=The+Immortal+Sun+MTG&tbm=isch)
- [x] [Thrashing Brontodon](https://www.google.com.au/search?q=Thrashing+Brontodon+MTG&tbm=isch)
- [x] [Thunderherd Migration](https://www.google.com.au/search?q=Thunderherd+Migration+MTG&tbm=isch)
- [x] [Tilonali's Crown](https://www.google.com.au/search?q=Tilonali's+Crown+MTG&tbm=isch)
- [x] [Tilonalli's Summoner](https://www.google.com.au/search?q=Tilonalli's+Summoner+MTG&tbm=isch)
- [x] [Timestream Navigator](https://www.google.com.au/search?q=Timestream+Navigator+MTG&tbm=isch)
- [x] [Tomb Robber](https://www.google.com.au/search?q=Tomb+Robber+MTG&tbm=isch)
- [x] [Tomb of the Dusk Rose](https://www.google.com.au/search?q=Tomb+of+the+Dusk+Rose+MTG&tbm=isch)
- [x] [Trapjaw Tyrant](https://www.google.com.au/search?q=Trapjaw+Tyrant+MTG&tbm=isch)
- [x] [Traveler's Amulet](https://www.google.com.au/search?q=Traveler's+Amulet+MTG&tbm=isch)
- [x] [Twilight Prophet](https://www.google.com.au/search?q=Twilight+Prophet+MTG&tbm=isch)
- [x] [Vampire Champion](https://www.google.com.au/search?q=Vampire+Champion+MTG&tbm=isch)
- [x] [Vampire Revenant](https://www.google.com.au/search?q=Vampire+Revenant+MTG&tbm=isch)
- [x] [Vault of Catlacan](https://www.google.com.au/search?q=Vault+of+Catlacan+MTG&tbm=isch)
- [x] [Vona's Hunger](https://www.google.com.au/search?q=Vona's+Hunger+MTG&tbm=isch)
- [x] [Voracious Vampire](https://www.google.com.au/search?q=Voracious+Vampire+MTG&tbm=isch)
- [x] [Vraska's Conquistador](https://www.google.com.au/search?q=Vraska's+Conquistador+MTG&tbm=isch)
- [x] [Vraska's Scorn](https://www.google.com.au/search?q=Vraska's+Scorn+MTG&tbm=isch)
- [x] [Vraska, Scheming Gorgon](https://www.google.com.au/search?q=Vraska,+Scheming+Gorgon+MTG&tbm=isch)
- [x] [Warkite Marauder](https://www.google.com.au/search?q=Warkite+Marauder+MTG&tbm=isch)
- [x] [Waterknot](https://www.google.com.au/search?q=Waterknot+MTG&tbm=isch)
- [x] [Wayward Swordtooth](https://www.google.com.au/search?q=Wayward+Swordtooth+MTG&tbm=isch)
- [x] [Winged Temple of Orazca](https://www.google.com.au/search?q=Winged+Temple+of+Orazca+MTG&tbm=isch)
- [x] [Woodland Stream](https://www.google.com.au/search?q=Woodland+Stream+MTG&tbm=isch)
- [x] [World Shaper](https://www.google.com.au/search?q=World+Shaper+MTG&tbm=isch)
- [x] [Zacama, Primal Calamity](https://www.google.com.au/search?q=Zacama,+Primal+Calamity+MTG&tbm=isch)
- [x] [Zetalpa, Primal Dawn](https://www.google.com.au/search?q=Zetalpa,+Primal+Dawn+MTG&tbm=isch)

**Comment by LevelX2** [comment]
Working on:
- Paladin of Atonement

**Comment by Zzooouhh** [comment]
Implemented Elenda, the Dusk Rose and Zetalpa, Primal Dawn:  #4330

**Comment by JayDi85** [comment]
Scryfall have useful cards order list with actual spoiler data -- no need to search not working google images:
https://scryfall.com/sets/rix?order=spoiled

**Comment by JayDi85** [comment]
### Done:
- Forerunner of the Heralds

### Working on:

**Comment by JayDi85** [comment]
@LevelX2 see Dire Fleet Neckbreaker in your list. It was done already.

**Comment by JayDi85** [comment]
BIG Rivals of Ixalan Release Notes:

> The Release Notes include information concerning the release of a new Magic: The Gathering set, as well as a collection of clarifications and rulings involving that set's cards. It's intended to make playing with the new cards more fun by clearing up the common misconceptions and confusion inevitably caused by new mechanics and interactions. 

https://magic.wizards.com/en/articles/archive/feature/rivals-ixalan-release-notes-2018-01-05

**Comment by imendi7** [comment]
Any tutorial where I can learn how to implement cards?

I want to contribute!

**Comment by LevelX2** [comment]
> Any tutorial where I can learn how to implement cards?

https://github.com/magefree/mage/wiki/Developer-Getting-Started

**Comment by JayDi85** [comment]
@imendi7 use developer getting started. Train to setup, build, test and run xmage source code from scratch. After that you can read [howto guides](https://github.com/magefree/mage/wiki/Developer-HOWTO-Guides) (I've added info about card implementation).

**Comment by JayDi85** [comment]
@imendi7 try to implement [Grasping Scoundrel](https://scryfall.com/card/rix/74) from new set (I will hold on it to tomorrow). Use  [Adanto Vanguard](https://scryfall.com/card/xln/1) as example.

**Comment by imendi7** [comment]
OK, Ill start working on this now. I am quite a basic programmer, I hope I can deal with this. 

Thanks!

**Comment by JayDi85** [comment]
@imendi7 you can also contribute to xmage another way -- by testing new or old mechanics and [report bugs about it](https://github.com/magefree/mage/issues).

**Comment by imendi7** [comment]
I've already installed all the stuff. I am going to start now implementing Grasping Scoundrel.

**Comment by imendi7** [comment]
I've already implemented the card, but I'm having some troubles with its test. I cannot get to the point where "When the server is running in test mode, a Quick Start button will be available on the Tables screen." 

I've added to both "Mage Client" and "Mage Server" the argument "testMode=true", and actually in the "Output - Run (Mage Server)" console I see the text "MAGE server running  in test mode", but, still, I cannot see the "Quick Start button". What can I do?

Thanks!

**Comment by JayDi85** [comment]
You need only mage server command line. If you see test mode in logs then it's ok. After that go to tables and click here:

![shot_180106_231442](https://user-images.githubusercontent.com/8344157/34643077-70eb072e-f337-11e7-9fe9-08d54f986290.png)

**Comment by imendi7** [comment]
![image](https://user-images.githubusercontent.com/35166785/34643229-ea55baf8-f320-11e7-95f1-161815234886.png)

I still don't have the "Quick Start" button.

I see that I am connected to "xmage.de:17171" server and you are to "test2@localhost". Can this be the reason?

Thanks!

**Comment by JayDi85** [comment]
Yes, you must connect to your local server.

**Comment by use** [comment]
Working on:

* Daring Buccaneer

**Comment by AricHaldan** [comment]
Hello everyone, I've tried to help implement some cards, but I'm still quite unexperienced and I haven't been able to properly test or find out how I tick the boxes. They're relatively simple cards so they ought to work properly; I've been working on 

Brazen Freebooter and
Hornswoggle

I think I sent them through git but i'm not sure yet

**Comment by imendi7** [comment]
Good morning!

So little by little I'm learning how to deal with the procedure. However, right now I am still stuck at testing step.

I managed to begin a Quick Start game, but when I click on the smiley button I cannot get the Grasping Scoundrel appear on the game. In the NetBeans console I see "WARN  2018-01-07 11:07:01,315 Unknown card [Grasping Scoundrel]: hand:Human:Grasping Scoundrel:1". According to the HOWTO guide "If xmage can't find your card name (see errors log or check it in deck editor) then delete all cards*.db files in developer folder -- it's force to recreate new database;" so I deleted all of them and retried the test but the result is the same. How can I manage this problem?

Thanks!!

**Comment by JayDi85** [comment]
@imendi7 check out that things:
 * Update your source code from github, open set's list and ensure about card name -- search by that name in source code. If can't fnd -- then fix and go to delete db files step;
 * Run client and open deck editor;
 * Search for your card by name:
   * if find -- that's ok, you have typos in card name in init.txt
   * if can't find -- go to next step:
 * Search for your card by visually (open set in deck editor and look on it):
   * if find -- it's a card name typo -- go to delete db files step;
   * if can't find -- it's a missing card -- go to delete db files step;
 * Delete db files:
   * search all cards*.db in devs dir -- it's must have 3 different dirs (server, client and tests -- if you run it);
   * or search and delete it manually from `db` folders;
   * run your TEST server, ensure you see logs with missing cards and recreating db;
   * run your client and connect to TEST server;
   * open deck editor and search card -- it's must be ok now;

**Comment by imendi7** [comment]
@JayDi85 Sorry for being so annoying. 

I couldn't find my card in the deck editor, so I deleated all the cards*.db files in devs dir. But when I try to run the TEST server, the "Select the Main Class for Execution" window pops up but without any available main classes, so I cannot run the TEST server. 

![image](https://user-images.githubusercontent.com/35166785/34649131-3e269494-f3a9-11e7-8726-f86d2cfbf05f.png)

**Comment by JayDi85** [comment]
@imendi7 no, by "run TEST server" i mean run your local xmage server. But you are try to run xmage tests. Don't do it.

P.S. use devs chat on https://gitter.im/xmage-devs/Lobby
