### ISSUE TITLE
Add new cheat engine for manual testing

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4334]
Current test mode is not easy to use -- need to restart too many times.

New test mode can do:
 * [x] improved line parser;
 * [x] compatible with current files;
 * [x] collect commands in groups;
 * [x] select group to execute;
 * [x] no more endless file edits (can save useful commands/cards in one place);
 * [ ] special commands support like:   
    * [x] show opponent hand;
    * [x] show opponent library;
    * [x] use custom params to show only needed info;
    * [ ] add mana to pool (choose dialog);
    * [ ] add lands to battlefield (choose dialog);
    * [ ] execute custom text command (enter text dialog);
    * [ ] remove card from battlefield;
    * [ ] clear battlefield (?) and more (need to research and suggest).

Window example:
![shot_180104_012917](https://user-images.githubusercontent.com/8344157/34540685-e321071c-f0ee-11e7-86f7-0f89a8877c7a.png)

Init.txt example:

```
[@mana add]
[@lands add]

[add x10 colored lands]
battlefield:Human:Forest:10
battlefield:Human:Plains:10
battlefield:Human:Mountain:10
battlefield:Human:Swamp:10
battlefield:Human:Island:10

[test choice black lotus]
graveyard:Human:Plains:1
graveyard:Human:Lightning Bolt:1
graveyard:Human:Bearer of the Heavens:1
battlefield:Human:Black Lotus:5
battlefield:Human:Island:10
hand:Human:Amass the Components:5

[Forerunner of the Legion]
battlefield:Human:Plains:10
battlefield:Human:Swamp:10
hand:Human:Forerunner of the Legion:2
battlefield:Human:Forerunner of the Legion:1
hand:Human:Adanto Vanguard:1
library:Human:Anointed Deacon:3
library:Human:Lightning Bolt:1
library:Human:Bearer of the Heavens:1

[Forerunner of the Empire]
battlefield:Human:Forest:10
battlefield:Human:Plains:10
battlefield:Human:Mountain:10
hand:Human:Forerunner of the Empire:2
battlefield:Human:Forerunner of the Empire:1
hand:Human:Bonded Horncrest:1
library:Human:Burning Sun's Avatar:3
library:Human:Lightning Bolt:1
library:Human:Bearer of the Heavens:1
```

**Comment by LevelX2** [comment]
Looks like an interesting improvement. 👍

**Comment by JayDi85** [comment]
Added 2 new special commands in "cheat" menu for `init.txt`:
  * `[@show opponent hand]` -- show cards from opponent's hand;
  * `[@show opponent library]` -- show cards from opponent's library.

And added special command params to show more or less info for card's list:
 * `pt` -- show power / toughness;
 * `color` -- show color identity;
 * `abilities count` -- show abilities count;
 * `abilities list` -- show abilities list (class names).

Example command for init.txt:
```
[@show opponent hand]
pt
color
abilities count
abilities list

[@show opponent library]
```

![shot_180126_063547](https://user-images.githubusercontent.com/8344157/35422961-affbfe32-0264-11e8-8ba0-8fd1ce1c11fa.png)

![shot_180126_063607](https://user-images.githubusercontent.com/8344157/35422962-b4a8fef8-0264-11e8-9c68-bd4a9964dc43.png)

**Comment by JayDi85** [comment]
Most popular features in cheat commands are implemented, so it can be closed. If someone want new feature then create new issue with request.
