### ISSUE TITLE
Oracle updates for cards and rules from Wizards (11.01.2018)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4412]
[From forum](https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=21567):

[Wizards blog about changes](https://magic.wizards.com/en/articles/archive/news/rivals-ixalan-oracle-changes-2018-01-11):

 * [ ] Gnathosaur (Lizard to Dinosaur)
 * [ ] Pteron Ghost (Spirit to Dinosaur Spirit)
 * [ ] Regal Behemoth (Lizard to Dinosaur)
 * [ ] Ripscale Predator (Lizard to Dinosaur)

 * [ ] Grafdigger's Cage's old rules text:

 * [ ] Creature cards can't enter the battlefield from graveyards or libraries.
 * [ ] Players can't cast spells from graveyards or libraries.

 * [ ] Grafdigger's Cage's new rules text:

 * [ ] Creature cards in graveyards and libraries can't enter the battlefield.
 * [ ] Players can't cast spells from graveyards or libraries.

 * [ ] Calming Verse's old rules text:

 * [ ] Destroy all enchantments you don't control. Then, if you control an untapped land, destroy all enchantments you control.

 * [ ] Calming Verse's new rules text:

 * [ ] Destroy all enchantments you don't control. Then if you control an untapped land, destroy all enchantments you control.

 * [ ] Rhystic Scrying's old rules text:

 * [ ] Draw three cards. Then, if any player pays 2, discard three cards.

 * [ ] Rhystic Scrying's new rules text:

 * [ ] Draw three cards. Then if any player pays 2, discard three cards.

 * [ ] Fire and Brimstone's old rules text:

 * [ ] Fire and Brimstone deals 4 damage to target player who declared an attacking creature this turn and 4 damage to you.

 * [ ] Fire and Brimstone's new rules text:

 * [ ] Fire and Brimstone deals 4 damage to target player who attacked this turn and 4 damage to you.
