### ISSUE TITLE
Xmas Cards - Card Implementation Tracker (Tracking issue for Special Occassion Xmas cards) 

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4455]
- [ ] Not done -- [1996 World Champion](https://www.google.com.au/search?q=intext:"1996+World+Champion"+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Fruitcake Elemental](https://www.google.com.au/search?q=intext:"Fruitcake+Elemental"+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Gifts Given](https://www.google.com.au/search?q=intext:"Gifts+Given"+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Mishra's Toy Workshop](https://www.google.com.au/search?q=intext:"Mishra's+Toy+Workshop"+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Robot Chicken](https://www.google.com.au/search?q=intext:"Robot+Chicken"+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Season's Beatings](https://www.google.com.au/search?q=intext:"Season's+Beatings"+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Shichifukujin Dragon](https://www.google.com.au/search?q=intext:"Shichifukujin+Dragon"+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Snow Mercy](https://www.google.com.au/search?q=intext:"Snow+Mercy"+mtg&source=lnms&tbm=isch)
- [ ] Not done -- [Stocking Tiger](https://www.google.com.au/search?q=intext:"Stocking+Tiger"+mtg&source=lnms&tbm=isch)
