### ISSUE TITLE
Show active ability icons on the cards while playing

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4488]
**Your any suggestions or hints are welcome in that topic.**

Left bottom corner and side is free to use for special icons:
![shot_180206_113609](https://user-images.githubusercontent.com/8344157/35846913-f37bcebe-0b31-11e8-964d-7d84f89b1ceb.png)

Many special icons can be drawn here. Cards in battlefield, cards in graveyard, cards in hands:
 - basic abilities like flying, trample;
 - special activated conditions like raid;
 - active triggers like mana or ability (if they available to execute for user by click on it)
 - other useful things and hints.

Magic Duels and Magic Arena can be reference for special icons usage:

![shot_180206_114145](https://user-images.githubusercontent.com/8344157/35847130-c252325a-0b32-11e8-9d7b-962501b58b7c.png)

![shot_180206_114233](https://user-images.githubusercontent.com/8344157/35847156-d7cb835c-0b32-11e8-908b-484b680c57ad.png)

It's an incremental dev process -- start with basic icons like flying and add more icons later.

What to do before programming:
 - [x] Research data available for current and other players (some data can't be retrieved by client for other players, some data available only on priority phase). May be cards will need to store more info like special flags for GUI;
 - [x] Research icons drawing methods: icons is part of card (like current mana) or out of cards (like mtg arena/duels);
 - [ ] Create needed icons list with conditions to show ([basic keywords list from wiki](https://mtg.gamepedia.com/Category:Keywords));
 - [x] Cards example with many and low icons count (e.g. hide too many icons in one by popup hints);

What to do while programming:
 - [x] Add icons mechanics in code:
  - [x] Flying;
  - [x] Trample;
  - [ ] TODO: add each icon type here;
 - [x] Find or create free to use graphic icons (SVG is preferred);
 - [x] Research icon types (with items or with text symbols like "F" for flying);
 - [ ] Add icons downloading if they are not free to use like current icons mana ([full list of Magic Duels icons](https://mtg.gamepedia.com/Category:Magic_keyword_images));
 - [x] Add options to enable or disable special icons drawing.

P.S. The old one topic on it:  #2278

**Comment by JayDi85** [comment]
Proof of concept:

![shot_210103_104833](https://user-images.githubusercontent.com/8344157/103473504-cafc9380-4db2-11eb-9f2b-d78ab76aea5a.png)

**Comment by JayDi85** [comment]
Card icons implemented by #7467
