### ISSUE TITLE
Scryfall downloads wrong images for old sets

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#4628]
Scryfall uses the modern numbering order (WUBRG) instead of the old (BUGRW) most of the other sites are using. This causes old sets before collectors' numbers appeared on cards to be downloaded incorrectly.

Scryfall option should either skip those sets or get them fixed so there isn't a bunch of incorrect images downloaded.

TODO:
* [x] Limited Edition Alpha (LEA)
* [x] Unlimited Edition (2ED)
* [x] Arabian Nights (ARN)
* [x] Antiquities (ATQ)
* [x] Revised Edition (3ED)
* [x] Legends (LEG)
* [x] The Dark (DRK)
* [x] Fallen Empires (FEM)
* [x] Ice Age (ICE)
* [x] Homelands (HML)
* [x] Mirage (MIR)
* [x] Visions (VIS)
* [x] Weatherlight (WTH)
* [x] Fifth Edition (5ED)
* [x] Tempest (TMP)
* [x] Stronghold (STH)

**Comment by JayDi85** [comment]
Report wrong sets here -- I will fix numbering.

**Comment by ketsuban** [comment]
@JayDi85 I don't know whether this will save you any time or not but I've gone through and determined to the best of my ability which early sets are misnumbered; in short, it's all sets prior to Exodus except Limited Edition Beta, Fourth Edition and Alliances. The long version is

* Limited Edition Alpha (LEA)
* Unlimited Edition (2ED)
* Arabian Nights (ARN)
* Antiquities (ATQ)
* Revised Edition (3ED)
* Legends (LEG)
* The Dark (DRK)
* Fallen Empires (FEM)
* Ice Age (ICE)
* Homelands (HML)
* Mirage (MIR)
* Visions (VIS)
* Weatherlight (WTH)
* Fifth Edition (5ED)
* Tempest (TMP)
* Stronghold (STH)
* Exodus (EXO)
* Unglued (UGL)
* Urza's Saga (USG)
* Urza's Legacy (ULG)
* Urza's Destiny (UDS)
* Sixth Edition (6ED)

**Comment by JayDi85** [comment]
@ketsuban thanks for your list, I've fixed that sets (will available on next release) . If you found more then fill free to report here.

**Comment by ketsuban** [comment]
@JayDi85 I've just discovered that Portal (POR) and Portal Second Age (P02) are also in a state of disarray.

**Comment by JayDi85** [comment]
@ketsuban thx, I've updated that files. It's will be available after next release.
