### ISSUE TITLE
DOM - Dominaria set card implementation tracking

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4643]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/products/dominaria

# Unimplemented cards

- None

# Cards in set:

- [x] Done -- [Academy Drake](https://scryfall.com/search?q=Academy+Drake)
- [x] Done -- [Academy Journeymage](https://scryfall.com/search?q=Academy+Journeymage)
- [x] Done -- [Adamant Will](https://scryfall.com/search?q=Adamant+Will)
- [x] Done -- [Adeliz, the Cinder Wind](https://scryfall.com/search?q=Adeliz,+the+Cinder+Wind)
- [x] Done -- [Adventurous Impulse](https://scryfall.com/search?q=Adventurous+Impulse)
- [x] Done -- [Aesthir Glider](https://scryfall.com/search?q=Aesthir+Glider)
- [x] Done -- [Amaranthine Wall](https://scryfall.com/search?q=Amaranthine+Wall)
- [x] Done -- [Ancient Animus](https://scryfall.com/search?q=Ancient+Animus)
- [x] Done -- [Arbor Armament](https://scryfall.com/search?q=Arbor+Armament)
- [x] Done -- [Arcane Flight](https://scryfall.com/search?q=Arcane+Flight)
- [x] Done -- [Artificer's Assistant](https://scryfall.com/search?q=Artificers+Assistant)
- [x] Done -- [Arvad the Cursed](https://scryfall.com/search?q=Arvad+the+Cursed)
- [x] Done -- [Aryel, Knight of Windgrace](https://scryfall.com/search?q=Aryel,+Knight+of+Windgrace)
- [x] Done -- [Aven Sentry](https://scryfall.com/search?q=Aven+Sentry)
- [x] Done -- [Baird, Steward of Argive](https://scryfall.com/search?q=Baird,+Steward+of+Argive)
- [x] Done -- [Baloth Gorger](https://scryfall.com/search?q=Baloth+Gorger)
- [x] Done -- [Befuddle](https://scryfall.com/search?q=Befuddle)
- [x] Done -- [Benalish Honor Guard](https://scryfall.com/search?q=Benalish+Honor+Guard)
- [x] Done -- [Benalish Marshal](https://scryfall.com/search?q=Benalish+Marshal)
- [x] Done -- [Blackblade Reforged](https://scryfall.com/search?q=Blackblade+Reforged)
- [x] Done -- [Blessed Light](https://scryfall.com/search?q=Blessed+Light)
- [x] Done -- [Blessing of Belzenlok](https://scryfall.com/search?q=Blessing+of+Belzenlok)
- [x] Done -- [Blink of an Eye](https://scryfall.com/search?q=Blink+of+an+Eye)
- [x] Done -- [Bloodstone Goblin](https://scryfall.com/search?q=Bloodstone+Goblin)
- [x] Done -- [Bloodtallow Candle](https://scryfall.com/search?q=Bloodtallow+Candle)
- [x] Done -- [Board the Weatherlight](https://scryfall.com/search?q=Board+the+Weatherlight)
- [x] Done -- [Broken Bond](https://scryfall.com/search?q=Broken+Bond)
- [x] Done -- [Cabal Evangel](https://scryfall.com/search?q=Cabal+Evangel)
- [x] Done -- [Cabal Paladin](https://scryfall.com/search?q=Cabal+Paladin)
- [x] Done -- [Cabal Stronghold](https://scryfall.com/search?q=Cabal+Stronghold)
- [x] Done -- [Caligo Skin-Witch](https://scryfall.com/search?q=Caligo+Skin-Witch)
- [x] Done -- [Call the Cavalry](https://scryfall.com/search?q=Call+the+Cavalry)
- [x] Done -- [Cast Down](https://scryfall.com/search?q=Cast+Down)
- [x] Done -- [Chainer's Torment](https://scryfall.com/search?q=Chainers+Torment)
- [x] Done -- [Champion of the Flame](https://scryfall.com/search?q=Champion+of+the+Flame)
- [x] Done -- [Chandra's Outburst](https://scryfall.com/search?q=Chandras+Outburst)
- [x] Done -- [Chandra, Bold Pyromancer](https://scryfall.com/search?q=Chandra,+Bold+Pyromancer)
- [x] Done -- [Charge](https://scryfall.com/search?q=Charge)
- [x] Done -- [Clifftop Retreat](https://scryfall.com/search?q=Clifftop+Retreat)
- [x] Done -- [Cloudreader Sphinx](https://scryfall.com/search?q=Cloudreader+Sphinx)
- [x] Done -- [Cold-Water Snapper](https://scryfall.com/search?q=Cold-Water+Snapper)
- [x] Done -- [Corrosive Ooze](https://scryfall.com/search?q=Corrosive+Ooze)
- [x] Done -- [Curator's Ward](https://scryfall.com/search?q=Curators+Ward)
- [x] Done -- [D'Avenant Trapper](https://scryfall.com/search?q=DAvenant+Trapper)
- [x] Done -- [Damping Sphere](https://scryfall.com/search?q=Damping+Sphere)
- [x] Done -- [Danitha Capashen, Paragon](https://scryfall.com/search?q=Danitha+Capashen,+Paragon)
- [x] Done -- [Darigaaz Reincarnated](https://scryfall.com/search?q=Darigaaz+Reincarnated)
- [x] Done -- [Daring Archaeologist](https://scryfall.com/search?q=Daring+Archaeologist)
- [x] Done -- [Dark Bargain](https://scryfall.com/search?q=Dark+Bargain)
- [x] Done -- [Dauntless Bodyguard](https://scryfall.com/search?q=Dauntless+Bodyguard)
- [x] Done -- [Deathbloom Thallid](https://scryfall.com/search?q=Deathbloom+Thallid)
- [x] Done -- [Deep Freeze](https://scryfall.com/search?q=Deep+Freeze)
- [x] Done -- [Demonic Vigor](https://scryfall.com/search?q=Demonic+Vigor)
- [x] Done -- [Demonlord Belzenlok](https://scryfall.com/search?q=Demonlord+Belzenlok)
- [x] Done -- [Diligent Excavator](https://scryfall.com/search?q=Diligent+Excavator)
- [x] Done -- [Divest](https://scryfall.com/search?q=Divest)
- [x] Done -- [Divination](https://scryfall.com/search?q=Divination)
- [x] Done -- [Dread Shade](https://scryfall.com/search?q=Dread+Shade)
- [x] Done -- [Drudge Sentinel](https://scryfall.com/search?q=Drudge+Sentinel)
- [x] Done -- [Dub](https://scryfall.com/search?q=Dub)
- [x] Done -- [Elfhame Druid](https://scryfall.com/search?q=Elfhame+Druid)
- [x] Done -- [Eviscerate](https://scryfall.com/search?q=Eviscerate)
- [x] Done -- [Evra, Halcyon Witness](https://scryfall.com/search?q=Evra,+Halcyon+Witness)
- [x] Done -- [Excavation Elephant](https://scryfall.com/search?q=Excavation+Elephant)
- [x] Done -- [Fall of the Thran](https://scryfall.com/search?q=Fall+of+the+Thran)
- [x] Done -- [Feral Abomination](https://scryfall.com/search?q=Feral+Abomination)
- [x] Done -- [Fervent Strike](https://scryfall.com/search?q=Fervent+Strike)
- [x] Done -- [Fiery Intervention](https://scryfall.com/search?q=Fiery+Intervention)
- [x] Done -- [Fight with Fire](https://scryfall.com/search?q=Fight+with+Fire)
- [x] Done -- [Final Parting](https://scryfall.com/search?q=Final+Parting)
- [x] Done -- [Fire Elemental](https://scryfall.com/search?q=Fire+Elemental)
- [x] Done -- [Firefist Adept](https://scryfall.com/search?q=Firefist+Adept)
- [x] Done -- [Firesong and Sunspeaker](https://scryfall.com/search?q=Firesong+and+Sunspeaker)
- [x] Done -- [Forebear's Blade](https://scryfall.com/search?q=Forebears+Blade)
- [x] Done -- [Frenzied Rage](https://scryfall.com/search?q=Frenzied+Rage)
- [x] Done -- [Fungal Infection](https://scryfall.com/search?q=Fungal+Infection)
- [x] Done -- [Fungal Plots](https://scryfall.com/search?q=Fungal+Plots)
- [x] Done -- [Gaea's Blessing](https://scryfall.com/search?q=Gaeas+Blessing)
- [x] Done -- [Gaea's Protector](https://scryfall.com/search?q=Gaeas+Protector)
- [x] Done -- [Garna, the Bloodflame](https://scryfall.com/search?q=Garna,+the+Bloodflame)
- [x] Done -- [Ghitu Chronicler](https://scryfall.com/search?q=Ghitu+Chronicler)
- [x] Done -- [Ghitu Journeymage](https://scryfall.com/search?q=Ghitu+Journeymage)
- [x] Done -- [Ghitu Lavarunner](https://scryfall.com/search?q=Ghitu+Lavarunner)
- [x] Done -- [Gideon's Reproach](https://scryfall.com/search?q=Gideons+Reproach)
- [x] Done -- [Gift of Growth](https://scryfall.com/search?q=Gift+of+Growth)
- [x] Done -- [Gilded Lotus](https://scryfall.com/search?q=Gilded+Lotus)
- [x] Done -- [Goblin Barrage](https://scryfall.com/search?q=Goblin+Barrage)
- [x] Done -- [Goblin Chainwhirler](https://scryfall.com/search?q=Goblin+Chainwhirler)
- [x] Done -- [Goblin Warchief](https://scryfall.com/search?q=Goblin+Warchief)
- [x] Done -- [Grand Warlord Radha](https://scryfall.com/search?q=Grand+Warlord+Radha)
- [x] Done -- [Grow from the Ashes](https://scryfall.com/search?q=Grow+from+the+Ashes)
- [x] Done -- [Grunn, the Lonely King](https://scryfall.com/search?q=Grunn,+the+Lonely+King)
- [x] Done -- [Guardians of Koilos](https://scryfall.com/search?q=Guardians+of+Koilos)
- [x] Done -- [Hallar, the Firefletcher](https://scryfall.com/search?q=Hallar,+the+Firefletcher)
- [x] Done -- [Haphazard Bombardment](https://scryfall.com/search?q=Haphazard+Bombardment)
- [x] Done -- [Healing Grace](https://scryfall.com/search?q=Healing+Grace)
- [x] Done -- [Helm of the Host](https://scryfall.com/search?q=Helm+of+the+Host)
- [x] Done -- [Hinterland Harbor](https://scryfall.com/search?q=Hinterland+Harbor)
- [x] Done -- [History of Benalia](https://scryfall.com/search?q=History+of+Benalia)
- [x] Done -- [Homarid Explorer](https://scryfall.com/search?q=Homarid+Explorer)
- [x] Done -- [Howling Golem](https://scryfall.com/search?q=Howling+Golem)
- [x] Done -- [Icy Manipulator](https://scryfall.com/search?q=Icy+Manipulator)
- [x] Done -- [In Bolas's Clutches](https://scryfall.com/search?q=In+Bolass+Clutches)
- [x] Done -- [Invoke the Divine](https://scryfall.com/search?q=Invoke+the+Divine)
- [x] Done -- [Isolated Chapel](https://scryfall.com/search?q=Isolated+Chapel)
- [x] Done -- [Jaya Ballard](https://scryfall.com/search?q=Jaya+Ballard)
- [x] Done -- [Jaya's Immolating Inferno](https://scryfall.com/search?q=Jayas+Immolating+Inferno)
- [x] Done -- [Jhoira's Familiar](https://scryfall.com/search?q=Jhoiras+Familiar)
- [x] Done -- [Jhoira, Weatherlight Captain](https://scryfall.com/search?q=Jhoira,+Weatherlight+Captain)
- [x] Done -- [Jodah, Archmage Eternal](https://scryfall.com/search?q=Jodah,+Archmage+Eternal)
- [x] Done -- [Josu Vess, Lich Knight](https://scryfall.com/search?q=Josu+Vess,+Lich+Knight)
- [x] Done -- [Jousting Lance](https://scryfall.com/search?q=Jousting+Lance)
- [x] Done -- [Juggernaut](https://scryfall.com/search?q=Juggernaut)
- [x] Done -- [Kamahl's Druidic Vow](https://scryfall.com/search?q=Kamahls+Druidic+Vow)
- [x] Done -- [Karn's Temporal Sundering](https://scryfall.com/search?q=Karns+Temporal+Sundering)
- [x] Done -- [Karn, Scion of Urza](https://scryfall.com/search?q=Karn,+Scion+of+Urza)
- [x] Done -- [Karplusan Hound](https://scryfall.com/search?q=Karplusan+Hound)
- [x] Done -- [Kazarov, Sengir Pureblood](https://scryfall.com/search?q=Kazarov,+Sengir+Pureblood)
- [x] Done -- [Keldon Overseer](https://scryfall.com/search?q=Keldon+Overseer)
- [x] Done -- [Keldon Raider](https://scryfall.com/search?q=Keldon+Raider)
- [x] Done -- [Keldon Warcaller](https://scryfall.com/search?q=Keldon+Warcaller)
- [x] Done -- [Knight of Grace](https://scryfall.com/search?q=Knight+of+Grace)
- [x] Done -- [Knight of Malice](https://scryfall.com/search?q=Knight+of+Malice)
- [x] Done -- [Knight of New Benalia](https://scryfall.com/search?q=Knight+of+New+Benalia)
- [x] Done -- [Krosan Druid](https://scryfall.com/search?q=Krosan+Druid)
- [x] Done -- [Kwende, Pride of Femeref](https://scryfall.com/search?q=Kwende,+Pride+of+Femeref)
- [x] Done -- [Lich's Mastery](https://scryfall.com/search?q=Lichs+Mastery)
- [x] Done -- [Lingering Phantom](https://scryfall.com/search?q=Lingering+Phantom)
- [x] Done -- [Llanowar Elves](https://scryfall.com/search?q=Llanowar+Elves)
- [x] Done -- [Llanowar Envoy](https://scryfall.com/search?q=Llanowar+Envoy)
- [x] Done -- [Llanowar Scout](https://scryfall.com/search?q=Llanowar+Scout)
- [x] Done -- [Lyra Dawnbringer](https://scryfall.com/search?q=Lyra+Dawnbringer)
- [x] Done -- [Mammoth Spider](https://scryfall.com/search?q=Mammoth+Spider)
- [x] Done -- [Marwyn, the Nurturer](https://scryfall.com/search?q=Marwyn,+the+Nurturer)
- [x] Done -- [Meandering River](https://scryfall.com/search?q=Meandering+River)
- [x] Done -- [Memorial to Folly](https://scryfall.com/search?q=Memorial+to+Folly)
- [x] Done -- [Memorial to Genius](https://scryfall.com/search?q=Memorial+to+Genius)
- [x] Done -- [Memorial to Glory](https://scryfall.com/search?q=Memorial+to+Glory)
- [x] Done -- [Memorial to Unity](https://scryfall.com/search?q=Memorial+to+Unity)
- [x] Done -- [Memorial to War](https://scryfall.com/search?q=Memorial+to+War)
- [x] Done -- [Merfolk Trickster](https://scryfall.com/search?q=Merfolk+Trickster)
- [x] Done -- [Mesa Unicorn](https://scryfall.com/search?q=Mesa+Unicorn)
- [x] Done -- [Mishra's Self-Replicator](https://scryfall.com/search?q=Mishras+Self-Replicator)
- [x] Done -- [Mox Amber](https://scryfall.com/search?q=Mox+Amber)
- [x] Done -- [Muldrotha, the Gravetide](https://scryfall.com/search?q=Muldrotha,+the+Gravetide)
- [x] Done -- [Multani, Yavimaya's Avatar](https://scryfall.com/search?q=Multani,+Yavimayas+Avatar)
- [x] Done -- [Naban, Dean of Iteration](https://scryfall.com/search?q=Naban,+Dean+of+Iteration)
- [x] Done -- [Naru Meha, Master Wizard](https://scryfall.com/search?q=Naru+Meha,+Master+Wizard)
- [x] Done -- [Nature's Spiral](https://scryfall.com/search?q=Natures+Spiral)
- [x] Done -- [Navigator's Compass](https://scryfall.com/search?q=Navigators+Compass)
- [x] Done -- [Niambi, Faithful Healer](https://scryfall.com/search?q=Niambi,+Faithful+Healer)
- [x] Done -- [Oath of Teferi](https://scryfall.com/search?q=Oath+of+Teferi)
- [x] Done -- [On Serra's Wings](https://scryfall.com/search?q=On+Serras+Wings)
- [x] Done -- [Opt](https://scryfall.com/search?q=Opt)
- [x] Done -- [Orcish Vandal](https://scryfall.com/search?q=Orcish+Vandal)
- [x] Done -- [Pardic Wanderer](https://scryfall.com/search?q=Pardic+Wanderer)
- [x] Done -- [Pegasus Courser](https://scryfall.com/search?q=Pegasus+Courser)
- [x] Done -- [Phyrexian Scriptures](https://scryfall.com/search?q=Phyrexian+Scriptures)
- [x] Done -- [Pierce the Sky](https://scryfall.com/search?q=Pierce+the+Sky)
- [x] Done -- [Powerstone Shard](https://scryfall.com/search?q=Powerstone+Shard)
- [x] Done -- [Precognition Field](https://scryfall.com/search?q=Precognition+Field)
- [x] Done -- [Primevals' Glorious Rebirth](https://scryfall.com/search?q=Primevals+Glorious+Rebirth)
- [x] Done -- [Primordial Wurm](https://scryfall.com/search?q=Primordial+Wurm)
- [x] Done -- [Pyromantic Pilgrim](https://scryfall.com/search?q=Pyromantic+Pilgrim)
- [x] Done -- [Radiating Lightning](https://scryfall.com/search?q=Radiating+Lightning)
- [x] Done -- [Raff Capashen, Ship's Mage](https://scryfall.com/search?q=Raff+Capashen,+Ships+Mage)
- [x] Done -- [Rampaging Cyclops](https://scryfall.com/search?q=Rampaging+Cyclops)
- [x] Done -- [Rat Colony](https://scryfall.com/search?q=Rat+Colony)
- [x] Done -- [Relic Runner](https://scryfall.com/search?q=Relic+Runner)
- [x] Done -- [Rescue](https://scryfall.com/search?q=Rescue)
- [x] Done -- [Rite of Belzenlok](https://scryfall.com/search?q=Rite+of+Belzenlok)
- [x] Done -- [Rona, Disciple of Gix](https://scryfall.com/search?q=Rona,+Disciple+of+Gix)
- [x] Done -- [Run Amok](https://scryfall.com/search?q=Run+Amok)
- [x] Done -- [Sage of Lat-Nam](https://scryfall.com/search?q=Sage+of+Lat-Nam)
- [x] Done -- [Sanctum Spirit](https://scryfall.com/search?q=Sanctum+Spirit)
- [x] Done -- [Saproling Migration](https://scryfall.com/search?q=Saproling+Migration)
- [x] Done -- [Seal Away](https://scryfall.com/search?q=Seal+Away)
- [x] Done -- [Seismic Shift](https://scryfall.com/search?q=Seismic+Shift)
- [x] Done -- [Sentinel of the Pearl Trident](https://scryfall.com/search?q=Sentinel+of+the+Pearl+Trident)
- [x] Done -- [Sergeant-at-Arms](https://scryfall.com/search?q=Sergeant-at-Arms)
- [x] Done -- [Serra Angel](https://scryfall.com/search?q=Serra+Angel)
- [x] Done -- [Serra Disciple](https://scryfall.com/search?q=Serra+Disciple)
- [x] Done -- [Settle the Score](https://scryfall.com/search?q=Settle+the+Score)
- [x] Done -- [Shalai, Voice of Plenty](https://scryfall.com/search?q=Shalai,+Voice+of+Plenty)
- [x] Done -- [Shanna, Sisay's Legacy](https://scryfall.com/search?q=Shanna,+Sisays+Legacy)
- [x] Done -- [Shield of the Realm](https://scryfall.com/search?q=Shield+of+the+Realm)
- [x] Done -- [Shivan Fire](https://scryfall.com/search?q=Shivan+Fire)
- [x] Done -- [Short Sword](https://scryfall.com/search?q=Short+Sword)
- [x] Done -- [Siege-Gang Commander](https://scryfall.com/search?q=Siege-Gang+Commander)
- [x] Done -- [Skirk Prospector](https://scryfall.com/search?q=Skirk+Prospector)
- [x] Done -- [Skittering Surveyor](https://scryfall.com/search?q=Skittering+Surveyor)
- [x] Done -- [Skizzik](https://scryfall.com/search?q=Skizzik)
- [x] Done -- [Slimefoot, the Stowaway](https://scryfall.com/search?q=Slimefoot,+the+Stowaway)
- [x] Done -- [Slinn Voda, the Rising Deep](https://scryfall.com/search?q=Slinn+Voda,+the+Rising+Deep)
- [x] Done -- [Song of Freyalise](https://scryfall.com/search?q=Song+of+Freyalise)
- [x] Done -- [Sorcerer's Wand](https://scryfall.com/search?q=Sorcerers+Wand)
- [x] Done -- [Soul Salvage](https://scryfall.com/search?q=Soul+Salvage)
- [x] Done -- [Sparring Construct](https://scryfall.com/search?q=Sparring+Construct)
- [x] Done -- [Spore Swarm](https://scryfall.com/search?q=Spore+Swarm)
- [x] Done -- [Sporecrown Thallid](https://scryfall.com/search?q=Sporecrown+Thallid)
- [x] Done -- [Squee, the Immortal](https://scryfall.com/search?q=Squee,+the+Immortal)
- [x] Done -- [Steel Leaf Champion](https://scryfall.com/search?q=Steel+Leaf+Champion)
- [x] Done -- [Stronghold Confessor](https://scryfall.com/search?q=Stronghold+Confessor)
- [x] Done -- [Sulfur Falls](https://scryfall.com/search?q=Sulfur+Falls)
- [x] Done -- [Sylvan Awakening](https://scryfall.com/search?q=Sylvan+Awakening)
- [x] Done -- [Syncopate](https://scryfall.com/search?q=Syncopate)
- [x] Done -- [Tatyova, Benthic Druid](https://scryfall.com/search?q=Tatyova,+Benthic+Druid)
- [x] Done -- [Teferi's Sentinel](https://scryfall.com/search?q=Teferis+Sentinel)
- [x] Done -- [Teferi, Hero of Dominaria](https://scryfall.com/search?q=Teferi,+Hero+of+Dominaria)
- [x] Done -- [Teferi, Timebender](https://scryfall.com/search?q=Teferi,+Timebender)
- [x] Done -- [Tempest Djinn](https://scryfall.com/search?q=Tempest+Djinn)
- [x] Done -- [Temporal Machinations](https://scryfall.com/search?q=Temporal+Machinations)
- [x] Done -- [Territorial Allosaurus](https://scryfall.com/search?q=Territorial+Allosaurus)
- [x] Done -- [Teshar, Ancestor's Apostle](https://scryfall.com/search?q=Teshar,+Ancestors+Apostle)
- [x] Done -- [Tetsuko Umezawa, Fugitive](https://scryfall.com/search?q=Tetsuko+Umezawa,+Fugitive)
- [x] Done -- [Thallid Omnivore](https://scryfall.com/search?q=Thallid+Omnivore)
- [x] Done -- [Thallid Soothsayer](https://scryfall.com/search?q=Thallid+Soothsayer)
- [x] Done -- [The Antiquities War](https://scryfall.com/search?q=The+Antiquities+War)
- [x] Done -- [The Eldest Reborn](https://scryfall.com/search?q=The+Eldest+Reborn)
- [x] Done -- [The First Eruption](https://scryfall.com/search?q=The+First+Eruption)
- [x] Done -- [The Flame of Keld](https://scryfall.com/search?q=The+Flame+of+Keld)
- [x] Done -- [The Mending of Dominaria](https://scryfall.com/search?q=The+Mending+of+Dominaria)
- [x] Done -- [The Mirari Conjecture](https://scryfall.com/search?q=The+Mirari+Conjecture)
- [x] Done -- [Thorn Elemental](https://scryfall.com/search?q=Thorn+Elemental)
- [x] Done -- [Thran Temporal Gateway](https://scryfall.com/search?q=Thran+Temporal+Gateway)
- [x] Done -- [Tiana, Ship's Caretaker](https://scryfall.com/search?q=Tiana,+Ships+Caretaker)
- [x] Done -- [Timber Gorge](https://scryfall.com/search?q=Timber+Gorge)
- [x] Done -- [Time of Ice](https://scryfall.com/search?q=Time+of+Ice)
- [x] Done -- [Tolarian Scholar](https://scryfall.com/search?q=Tolarian+Scholar)
- [x] Done -- [Torgaar, Famine Incarnate](https://scryfall.com/search?q=Torgaar,+Famine+Incarnate)
- [x] Done -- [Tragic Poet](https://scryfall.com/search?q=Tragic+Poet)
- [x] Done -- [Traxos, Scourge of Kroog](https://scryfall.com/search?q=Traxos,+Scourge+of+Kroog)
- [x] Done -- [Triumph of Gerrard](https://scryfall.com/search?q=Triumph+of+Gerrard)
- [x] Done -- [Two-Headed Giant](https://scryfall.com/search?q=Two-Headed+Giant)
- [x] Done -- [Untamed Kavu](https://scryfall.com/search?q=Untamed+Kavu)
- [x] Done -- [Unwind](https://scryfall.com/search?q=Unwind)
- [x] Done -- [Urgoros, the Empty One](https://scryfall.com/search?q=Urgoros,+the+Empty+One)
- [x] Done -- [Urza's Ruinous Blast](https://scryfall.com/search?q=Urzas+Ruinous+Blast)
- [x] Done -- [Urza's Tome](https://scryfall.com/search?q=Urzas+Tome)
- [x] Done -- [Valduk, Keeper of the Flame](https://scryfall.com/search?q=Valduk,+Keeper+of+the+Flame)
- [x] Done -- [Verdant Force](https://scryfall.com/search?q=Verdant+Force)
- [x] Done -- [Verix Bladewing](https://scryfall.com/search?q=Verix+Bladewing)
- [x] Done -- [Vicious Offering](https://scryfall.com/search?q=Vicious+Offering)
- [x] Done -- [Vodalian Arcanist](https://scryfall.com/search?q=Vodalian+Arcanist)
- [x] Done -- [Voltaic Servant](https://scryfall.com/search?q=Voltaic+Servant)
- [x] Done -- [Warcry Phoenix](https://scryfall.com/search?q=Warcry+Phoenix)
- [x] Done -- [Warlord's Fury](https://scryfall.com/search?q=Warlords+Fury)
- [x] Done -- [Weatherlight](https://scryfall.com/search?q=Weatherlight)
- [x] Done -- [Weight of Memory](https://scryfall.com/search?q=Weight+of+Memory)
- [x] Done -- [Whisper, Blood Liturgist](https://scryfall.com/search?q=Whisper,+Blood+Liturgist)
- [x] Done -- [Wild Onslaught](https://scryfall.com/search?q=Wild+Onslaught)
- [x] Done -- [Windgrace Acolyte](https://scryfall.com/search?q=Windgrace+Acolyte)
- [x] Done -- [Wizard's Lightning](https://scryfall.com/search?q=Wizards+Lightning)
- [x] Done -- [Wizard's Retort](https://scryfall.com/search?q=Wizards+Retort)
- [x] Done -- [Woodland Cemetery](https://scryfall.com/search?q=Woodland+Cemetery)
- [x] Done -- [Yargle, Glutton of Urborg](https://scryfall.com/search?q=Yargle,+Glutton+of+Urborg)
- [x] Done -- [Yavimaya Sapherd](https://scryfall.com/search?q=Yavimaya+Sapherd)
- [x] Done -- [Yawgmoth's Vile Offering](https://scryfall.com/search?q=Yawgmoths+Vile+Offering)
- [x] Done -- [Zahid, Djinn of the Lamp](https://scryfall.com/search?q=Zahid,+Djinn+of+the+Lamp)
- [x] Done -- [Zhalfirin Void](https://scryfall.com/search?q=Zhalfirin+Void)

**Comment by zeflap** [comment]
Missing:
 Jhoira, Weatherlight Captain|2UR|Legendary Creature — Human Artificer|3|3|Whenever you cast a historic spell, draw a card. (Artifacts, legendaries, and Sagas are historic.)

**Comment by spjspj** [comment]
cheers zeflap

**Comment by JayDi85** [comment]
Need to change script generator -- google search is useless at all (no found for new cards, even old card images are not enough for devs). Add scryfall links -- it's the best one with fast updates and full info:
 * `https://scryfall.com/search?q=Voltaic+Servant`

**Comment by JayDi85** [comment]
Missing cards from list:
 * [x] Serra Disciple -- done
 * [x] Homarid Explorer -- done
 * [x] Academy Drake -- done
 * [x] Cast Down -- done
 * [x] Cabal Evangel -- done
 * [x] Zhalfirin Void -- done

**Comment by rystan** [comment]
[x] Arvad the Cursed #4714 

Thanks @JayDi85

**Comment by rystan** [comment]
- [X] Memorial to Folly -- done
- [X] Memorial to Genius -- done
- [X] Memorial to Glory -- done
- [X] Memorial to Unity -- done
- [X] Memorial to War -- done

PRs #4735, #4736, #4737, #4738

**Comment by theelk801** [comment]
I updated the to do list

**Comment by BrewBrewBrewTheDeck** [comment]
Hello all, newbie here, quick question just to make sure: If I am working on one of the cards not yet done I simply check its box in the second post with In Progress before them, right? In other words, those with unchecked boxes in that post do not have anyone else working on them yet, correct?

**Comment by LevelX2** [comment]
> In other words, those with unchecked boxes in that post do not have anyone else working on them yet, correct

Vorrecht!

**Comment by BrewBrewBrewTheDeck** [comment]
A’ight, thanks.

**Comment by keelahnkhan** [comment]
- [x] Sanctum Spirit -- done   https://github.com/magefree/mage/pull/4765

**Comment by rscoates** [comment]
- [ ] Dark Bargain -- done #4766 
(again, hope done correctly)

**Comment by BrewBrewBrewTheDeck** [comment]
Since I can’t seem to mark the checkboxes here are the cards that I am currently working on:
• Gift of Growth 
• Krosan Druid 
• Precognition Field

**Comment by rscoates** [comment]
- [ ] Gift of Growth -- done #4768 

Apologies @BrewBrewBrewTheDeck, didn't see.

**Comment by rscoates** [comment]
Working on Stronghold Confessor.

**Comment by BrewBrewBrewTheDeck** [comment]
@rscoates No worries, I am completely new here so if anyone so desires just do the ones I listed. For now I have yet to figure out how to even properly test the cards I did. 

@LevelX2 helped me with this earlier but so far we couldn’t determine what went wrong. The issue is that the cards I added showed up in-game (in the deck editor) but had no oracle text when hovering over them. Like, they’re just blank in that area. The cards themselves were fine, I think, but maybe I missed something. If you wanna look over my version of Gift of Growth, for example, this is it: 

https://pastebin.com/0f4n6cJz

Level glanced over it and saw nothing out of the ordinary. But perhaps the error lies with the file itself after all and you can spot it. Or know what else might result in that issue.

**Comment by rscoates** [comment]
Working on:
Run Amok
Healing Grace

**Comment by theelk801** [comment]
Slinn Voda is already done, I just pushed it.

**Comment by jack-the-BOSS** [comment]
Working on Aryel, Knight of Windgrace

**Comment by theelk801** [comment]
Take a look at Minamo Sightbender and Merchant's Dockhand.

**Comment by jack-the-BOSS** [comment]
@theelk801 Yes, thank you. Minamo Sightbender especially was a big help. Not quite there but it's coming together.

**Comment by rscoates** [comment]
Working on:
Radiating Lightning

**Comment by jack-the-BOSS** [comment]
Done/Need an experienced developer to check:
Aryel, Knight of Windgrace PR #4781

**Comment by theelk801** [comment]
I gave it a glance, I'll look into it more soon. If you tested it and it works, it's probably fine, but the main thing to check is whether something like Experiment Kraj or Quicksilver Elemental is able to properly copy its ability.

**Comment by rscoates** [comment]
Working on:
Corrosive Ooze

**Comment by rscoates** [comment]
Working on:
Seismic Shift

**Comment by theelk801** [comment]
I'll do Healing Grace

**Comment by rscoates** [comment]
Thanks @theelk801. Much appreciated.

**Comment by rscoates** [comment]
Working on:
Firesong and Sunspeaker

**Comment by jpgunter** [comment]
Elfhame Druid: https://github.com/magefree/mage/pull/4791

**Comment by jack-the-BOSS** [comment]
I have some minor fixes to **Aryel, Knight of Windgrace** PR: #4793 However, I'm very new to this, and the card **does not work.** I hope that I at least provided a good base to make the work easier.

**Comment by jpgunter** [comment]
Fixing up firesong: https://github.com/magefree/mage/pull/4794

**Comment by jack-the-BOSS** [comment]
I don't know if you guys want this, but here is a list of cards that for various reasons do not show up in the client (in mine anyway). I put stars next to commons and uncommons that are good to great in limited and thus somewhat important for those practicing for prerelease events:
20 Healing Grace
49 Curator’s Ward
50 Deep Freeze *
61 Precognition Field
82 Chainer’s Torment * 
86 Demonlord Belzenlok
101 Rat Colony
108 Torgaar, Famine Incarnate
109 Urgoros, the Empty One *
122 The First Eruption
128 Goblin Barrage *
131 Haphazard Bombardment
132 Jaya Ballard
141 Seismic Shift
150 Warcry Phoenix *
158 Corrosive Ooze
159 Elfhame Druid *
167 Krosan Druid *
192 Aryel, Knight of Windgrace *
193 Darigaaz Reincarnated
195 Grand Warlord Radha *
196 Hallar, the Firefletcher *
199 Muldrotha, the Gravetide
200 Oath of Teferi
203 Rona, Disciple of Gix
204 Shanna, Sisay’s Legacy*
205 Slimefoot, the Stowaway*
208 Tiana, Ship’s Caretaker*
225 Navigator’s Compass
228 Shield of the Realm*
231 Sorcerer’s Wand
275 Chandra, Bold Pyromancer
276 Chandra’s Outburst

**Comment by rscoates** [comment]
@jack-the-BOSS - sure you have, but just in case... have you tried deleting the cards*.db files and/or checking the Force Cardbase Update checkbox in the client? These look like the last few to get finished and it may be a caching issue.

**Comment by JayDi85** [comment]
@jack-the-BOSS update to latest xmage source code. I'm fixed yesterday some card errors (loading problem). And clean up all db-dirs (client and server) to re-create cards.

**Comment by jack-the-BOSS** [comment]
@rscoates Good point, not since yesterday.

**Comment by RMFDEMON** [comment]
Hey man, an error happened when trying to do her ultimate. Her emblem crashed when I tried to play any instant or sorcery in my graveyard. Can you help with this? Here's a screenshot:
![capture](https://user-images.githubusercontent.com/16737649/39077729-44b9d820-44c1-11e8-9107-a7664c540abe.PNG)

**Comment by RMFDEMON** [comment]
By the way, everything else works fine with her.

**Comment by RMFDEMON** [comment]
And when do you guys think there’ll be a fix?

**Comment by LevelX2** [comment]
@RMFDEMON 
Alsways read here about content of upcoming fixes: https://github.com/magefree/mage/wiki/Features-and-fixes-not-released-yet
Fix will be live with next server restart 8:00 CET

**Comment by RMFDEMON** [comment]
Hey, on the new version it still don't work.

**Comment by RMFDEMON** [comment]
I don't know if it's because if it's fast mana.

**Comment by RMFDEMON** [comment]
Plus in both cases I had at least 1 manamorphose in my graveyard.

**Comment by RMFDEMON** [comment]
Actually it might be because I was also online and there were 2 on the field.

**Comment by RMFDEMON** [comment]
Because it works with 1 on the field I guess.

**Comment by ThestalosMonarca** [comment]
@RMFDEMON, i tried here, and works fine for me, i using the last version, 1.4.32V0.
