### ISSUE TITLE
Planarchase Implementation

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4704]
- [ ] Not Done -- [bant](https://magiccards.info/extra/plane/planechase-anthology/bant.html)
- [ ] Not Done -- [grixis](https://magiccards.info/extra/plane/planechase-anthology/grixis.html)
- [ ] Not Done -- [naya](https://magiccards.info/extra/plane/planechase-anthology/naya.html)
- [ ] Not Done -- [the maelstrom](https://magiccards.info/extra/plane/planechase-anthology/the-maelstrom.html)
- [ ] Not Done -- [lethe lake](https://magiccards.info/extra/plane/planechase-anthology/lethe-lake.html)
- [ ] Not Done -- [pools of becoming](https://magiccards.info/extra/plane/planechase-anthology/pools-of-becoming.html)
- [ ] Not Done -- [academy at tolaria west](https://magiccards.info/extra/plane/planechase-anthology/academy-at-tolaria-west.html)
- [ ] Not Done -- [isle of vesuva](https://magiccards.info/extra/plane/planechase-anthology/isle-of-vesuva.html)
- [ ] Not Done -- [krosa](https://magiccards.info/extra/plane/planechase-anthology/krosa.html)
- [ ] Not Done -- [llanowar](https://magiccards.info/extra/plane/planechase-anthology/llanowar.html)
- [ ] Not Done -- [otaria](https://magiccards.info/extra/plane/planechase-anthology/otaria.html)
- [ ] Not Done -- [shiv](https://magiccards.info/extra/plane/planechase-anthology/shiv.html)
- [ ] Not Done -- [the eon fog](https://magiccards.info/extra/plane/planechase-anthology/the-eon-fog.html)
- [ ] Not Done -- [turri island](https://magiccards.info/extra/plane/planechase-anthology/turri-island.html)
- [ ] Not Done -- [the aether flues](https://magiccards.info/extra/plane/planechase-anthology/the-aether-flues.html)
- [ ] Not Done -- [skybreen](https://magiccards.info/extra/plane/planechase-anthology/skybreen.html)
- [ ] Not Done -- [minamo](https://magiccards.info/extra/plane/planechase-anthology/minamo.html)
- [ ] Not Done -- [sokenzan](https://magiccards.info/extra/plane/planechase-anthology/sokenzan.html)
- [ ] Not Done -- [mirrored depths](https://magiccards.info/extra/plane/planechase-anthology/mirrored-depths.html)
- [ ] Not Done -- [tember city](https://magiccards.info/extra/plane/planechase-anthology/tember-city.html)
- [ ] Not Done -- [goldmeadow](https://magiccards.info/extra/plane/planechase-anthology/goldmeadow.html)
- [ ] Not Done -- [the great forest](https://magiccards.info/extra/plane/planechase-anthology/the-great-forest.html)
- [ ] Not Done -- [velis vel](https://magiccards.info/extra/plane/planechase-anthology/velis-vel.html)
- [ ] Not Done -- [celestine reef](https://magiccards.info/extra/plane/planechase-anthology/celestine-reef.html)
- [ ] Not Done -- [cliffside market](https://magiccards.info/extra/plane/planechase-anthology/cliffside-market.html)
- [ ] Not Done -- [glimmervoid basin](https://magiccards.info/extra/plane/planechase-anthology/glimmervoid-basin.html)
- [ ] Not Done -- [panopticon](https://magiccards.info/extra/plane/planechase-anthology/panopticon.html)
- [ ] Not Done -- [fields of summer](https://magiccards.info/extra/plane/planechase-anthology/fields-of-summer.html)
- [ ] Not Done -- [feeding grounds](https://magiccards.info/extra/plane/planechase-anthology/feeding-grounds.html)
- [ ] Not Done -- [the fourth sphere](https://magiccards.info/extra/plane/planechase-anthology/the-fourth-sphere.html)
- [ ] Not Done -- [horizon boughs](https://magiccards.info/extra/plane/planechase-anthology/horizon-boughs.html)
- [ ] Not Done -- [sea of sand](https://magiccards.info/extra/plane/planechase-anthology/sea-of-sand.html)
- [ ] Not Done -- [stronghold furnace](https://magiccards.info/extra/plane/planechase-anthology/stronghold-furnace.html)
- [ ] Not Done -- [agyrem](https://magiccards.info/extra/plane/planechase-anthology/agyrem.html)
- [ ] Not Done -- [izzet steam maze](https://magiccards.info/extra/plane/planechase-anthology/izzet-steam-maze.html)
- [ ] Not Done -- [undercity reaches](https://magiccards.info/extra/plane/planechase-anthology/undercity-reaches.html)
- [ ] Not Done -- [the hippodrome](https://magiccards.info/extra/plane/planechase-anthology/the-hippodrome.html)
- [ ] Not Done -- [sanctum of serra](https://magiccards.info/extra/plane/planechase-anthology/sanctum-of-serra.html)
- [ ] Not Done -- [eloren wilds](https://magiccards.info/extra/plane/planechase-anthology/eloren-wilds.html)
- [ ] Not Done -- [ravens run](https://magiccards.info/extra/plane/planechase-anthology/ravens-run.html)
- [ ] Not Done -- [the dark barony](https://magiccards.info/extra/plane/planechase-anthology/the-dark-barony.html)
- [ ] Not Done -- [immersturm](https://magiccards.info/extra/plane/planechase-anthology/immersturm.html)
- [ ] Not Done -- [naar isle](https://magiccards.info/extra/plane/planechase-anthology/naar-isle.html)
- [ ] Not Done -- [murasa](https://magiccards.info/extra/plane/planechase-anthology/murasa.html)
- [ ] Not Done -- [tazeem](https://magiccards.info/extra/plane/planechase-anthology/tazeem.html)
- [ ] Not Done -- [jund](https://magiccards.info/extra/plane/planechase-anthology/jund.html)
- [ ] Not Done -- [lair of the ashen idol](https://magiccards.info/extra/plane/planechase-anthology/lair-of-the-ashen-idol.html)
- [ ] Not Done -- [edge of malacol](https://magiccards.info/extra/plane/planechase-anthology/edge-of-malacol.html)
- [ ] Not Done -- [windriddle palaces](https://magiccards.info/extra/plane/planechase-anthology/windriddle-palaces.html)
- [ ] Not Done -- [talon gates](https://magiccards.info/extra/plane/planechase-anthology/talon-gates.html)
- [ ] Not Done -- [bloodhill bastion](https://magiccards.info/extra/plane/planechase-anthology/bloodhill-bastion.html)
- [ ] Not Done -- [truga jungle](https://magiccards.info/extra/plane/planechase-anthology/truga-jungle.html)
- [ ] Not Done -- [grove of the dreampods](https://magiccards.info/extra/plane/planechase-anthology/grove-of-the-dreampods.html)
- [ ] Not Done -- [gavony](https://magiccards.info/extra/plane/planechase-anthology/gavony.html)
- [ ] Not Done -- [kessig](https://magiccards.info/extra/plane/planechase-anthology/kessig.html)
- [ ] Not Done -- [nephalia](https://magiccards.info/extra/plane/planechase-anthology/nephalia.html)
- [ ] Not Done -- [stensia](https://magiccards.info/extra/plane/planechase-anthology/stensia.html)
- [ ] Not Done -- [orochi colony](https://magiccards.info/extra/plane/planechase-anthology/orochi-colony.html)
- [ ] Not Done -- [takenuma](https://magiccards.info/extra/plane/planechase-anthology/takenuma.html)
- [ ] Not Done -- [aretopolis](https://magiccards.info/extra/plane/planechase-anthology/aretopolis.html)
- [ ] Not Done -- [astral arena](https://magiccards.info/extra/plane/planechase-anthology/astral-arena.html)
- [ ] Not Done -- [the zephyr maze](https://magiccards.info/extra/plane/planechase-anthology/the-zephyr-maze.html)
- [ ] Not Done -- [glen elendra](https://magiccards.info/extra/plane/planechase-anthology/glen-elendra.html)
- [ ] Not Done -- [quicksilver sea](https://magiccards.info/extra/plane/planechase-anthology/quicksilver-sea.html)
- [ ] Not Done -- [kharasha foothills](https://magiccards.info/extra/plane/planechase-anthology/kharasha-foothills.html)
- [ ] Not Done -- [furnace layer](https://magiccards.info/extra/plane/planechase-anthology/furnace-layer.html)
- [ ] Not Done -- [norns dominion](https://magiccards.info/extra/plane/planechase-anthology/norns-dominion.html)
- [ ] Not Done -- [onakke catacomb](https://magiccards.info/extra/plane/planechase-anthology/onakke-catacomb.html)
- [ ] Not Done -- [grand ossuary](https://magiccards.info/extra/plane/planechase-anthology/grand-ossuary.html)
- [ ] Not Done -- [kilnspire district](https://magiccards.info/extra/plane/planechase-anthology/kilnspire-district.html)
- [ ] Not Done -- [orzhova](https://magiccards.info/extra/plane/planechase-anthology/orzhova.html)
- [ ] Not Done -- [prahv](https://magiccards.info/extra/plane/planechase-anthology/prahv.html)
- [ ] Not Done -- [selesnya loft gardens](https://magiccards.info/extra/plane/planechase-anthology/selesnya-loft-gardens.html)
- [ ] Not Done -- [mount keralia](https://magiccards.info/extra/plane/planechase-anthology/mount-keralia.html)
- [ ] Not Done -- [trail of the mage rings](https://magiccards.info/extra/plane/planechase-anthology/trail-of-the-mage-rings.html)
- [ ] Not Done -- [stairs to infinity](https://magiccards.info/extra/plane/planechase-anthology/stairs-to-infinity.html)
- [ ] Not Done -- [akoum](https://magiccards.info/extra/plane/planechase-anthology/akoum.html)
- [ ] Not Done -- [hedron fields of agadeem](https://magiccards.info/extra/plane/planechase-anthology/hedron-fields-of-agadeem.html)

**Comment by zeflap** [comment]
@spjspj Naya is wonky, seems to sometimes need you to put a spell or ability on the stack to allow you to play any lands at all.

**Comment by spjspj** [comment]
@zeflap I don't think I've seen that.  Is there a way to recreate it?

**Comment by zeflap** [comment]
All I've needed for it to happen is to make a 4 player planechase EDH game, you tend to eventually get to Naya, and then it sporadically just happens.
Sorry that I don't have a better description.

**Comment by theelk801** [comment]
I was thinking of implementing some planes. Is there anything I should know that isn't gleanable from the ones already implemented?

**Comment by spjspj** [comment]
Theelk801: Not really.  I have a test harness to give me a chaos roll and then a planar roll aka no nil rolls otherwise too frustrating to roll the planar die.  They should be added to the .txt file for tokens and emblems as well for display.  Have been afk for two weeks or so now.  Was going to do some more when get back home.  Also might have a look at the new legendary border that modo/paper cards have added with dom.

**Comment by spjspj** [comment]
Interplanar Tunnel - Phenomenon -When you encounter Interplanar Tunnel, reveal cards from the top of your planar deck until you reveal five plane cards. Put a plane card from among them on top of your planar deck, then put the rest of the revealed cards on the bottom in a random order. -(Then planeswalk away from this phenomenon.)--      
Chaotic Aether - Phenomenon -When you encounter Chaotic Aether, each blank roll of the planar die is a CHAOS roll until a player planeswalks away from a plane. -(Then planeswalk away from this phenomenon.)--      - Cliffside Market - Plane — Mercadia -When you planeswalk to Cliffside Market or at the beginning of your upkeep, you may exchange life totals with target player.-Whenever you roll -{CHAOS}-, exchange control of two target permanents that share a card type.-      
Morphic Tide - Phenomenon -When you encounter Morphic Tide, each player shuffles all permanents they own into their library, then reveals that many cards from the top of their library. Each player puts all artifact, creature, land, and planeswalker cards revealed this way onto the battlefield, then does the same for enchantment cards, then puts all cards revealed this way that weren’t put onto the battlefield on the bottom of their library in any order. -(Then planeswalk away from this phenomenon.)--      
Mutual Epiphany - Phenomenon -When you encounter Mutual Epiphany, each player draws four cards. -(Then planeswalk away from this phenomenon.)--      
Planewide Disaster - Phenomenon -When you encounter Planewide Disaster, destroy all creatures. -(Then planeswalk away from this phenomenon.)--      
Reality Shaping - Phenomenon -When you encounter Reality Shaping, starting with you, each player may put a permanent card from their hand onto the battlefield. -(Then planeswalk away from this phenomenon.)--      
Spatial Merging - Phenomenon -When you encounter Spatial Merging, reveal cards from the top of your planar deck until you reveal two plane cards. Simultaneously planeswalk to both of them. Put all other cards revealed this way on the bottom of your planar deck in any order.-      
Time Distortion - Phenomenon -When you encounter Time Distortion, reverse the game’s turn order. -(For example, if play had proceeded clockwise around the table, it now goes counterclockwise. Then planeswalk away from this phenomenon.)--      

Eloren Wilds - Plane — Shandalar -Whenever a player taps a permanent for mana, that player adds one mana of any type that permanent produced.-Whenever you roll -{CHAOS}-, target player can’t cast spells until a player planeswalks.-      
Feeding Grounds - Plane — Muraganda -Red spells cost -{1}- less to cast.-Green spells cost -{1}- less to cast.-Whenever you roll -{CHAOS}-, put X +1/+1 counters on target creature, where X is that creature’s converted mana cost.-      
Fields of Summer - Plane — Moag -Whenever a player casts a spell, that player may gain 2 life.-Whenever you roll -{CHAOS}-, you may gain 10 life.-      
Furnace Layer - Plane — New Phyrexia -When you planeswalk to Furnace Layer or at the beginning of your upkeep, select target player at random. That player discards a card. If that player discards a land card this way, they lose 3 life.-Whenever you roll -{CHAOS}-, you may destroy target nonland permanent.-      
Gavony - Plane — Innistrad -All creatures have vigilance.-Whenever you roll -{CHAOS}-, creatures you control gain indestructible until end of turn.-      
Glen Elendra - Plane — Lorwyn -At end of combat, you may exchange control of target creature you control that dealt combat damage to a player this combat and target creature that player controls.-Whenever you roll -{CHAOS}-, gain control of target creature you own.-      
Glimmervoid Basin - Plane — Mirrodin -Whenever a player casts an instant or sorcery spell with a single target, that player copies that spell for each other spell, permanent, card not on the battlefield, and/or player the spell could target. Each copy targets a different one of them.-Whenever you roll -{CHAOS}-, choose target creature. Each player except that creature’s controller creates a token that’s a copy of that creature.-      
Goldmeadow - Plane — Lorwyn -Whenever a land enters the battlefield, that land’s controller creates three 0/1 white Goat creature tokens.-Whenever you roll -{CHAOS}-, create a 0/1 white Goat creature token.-      
Grand Ossuary - Plane — Ravnica -Whenever a creature dies, its controller distributes a number of +1/+1 counters equal to its power among any number of target creatures they control.-Whenever you roll -{CHAOS}-, each player exiles all creatures they control and creates X 1/1 green Saproling creature tokens, where X is the total power of the creatures they exiled this way. Then planeswalk.-      
Grixis - Plane — Alara -Blue, black, and/or red creature cards in your graveyard have unearth. The unearth cost is equal to the card’s mana cost. -(Pay the card’s mana cost: Return it to the battlefield. The creature gains haste. Exile it at the beginning of the next end step or if it would leave the battlefield. Unearth only as a sorcery.)--Whenever you roll -{CHAOS}-, put target creature card from a graveyard onto the battlefield under your control.-      
Grove of the Dreampods - Plane — Fabacin -When you planeswalk to Grove of the Dreampods or at the beginning of your upkeep, reveal cards from the top of your library until you reveal a creature card. Put that card onto the battlefield and the rest on the bottom of your library in a random order.-Whenever you roll -{CHAOS}-, return target creature card from your graveyard to the battlefield.-      
Hedron Fields of Agadeem - Plane — Zendikar -Creatures with power 7 or greater can’t attack or block.-Whenever you roll -{CHAOS}-, create a 7/7 colorless Eldrazi creature token with annihilator 1. -(Whenever it attacks, defending player sacrifices a permanent.)--      
Dreampod Druid --{1}--{G}-- Creature — Human Druid -At the beginning of each upkeep, if Dreampod Druid is enchanted, create a 1/1 green Saproling creature token.- 2/2 -      - Edge of Malacol - Plane — Belenon -If a creature you control would untap during your untap step, put two +1/+1 counters on it instead.-Whenever you roll -{CHAOS}-, untap each creature you control.-      
The Aether Flues - Plane — Iquatana -When you planeswalk to The Aether Flues or at the beginning of your upkeep, you may sacrifice a creature. If you do, reveal cards from the top of your library until you reveal a creature card, put that card onto the battlefield, then shuffle all other cards revealed this way into your library.-Whenever you roll -{CHAOS}-, you may put a creature card from your hand onto the battlefield.-      
Agyrem - Plane — Ravnica -Whenever a white creature dies, return it to the battlefield under its owner’s control at the beginning of the next end step.-Whenever a nonwhite creature dies, return it to its owner’s hand at the beginning of the next end step.-Whenever you roll -{CHAOS}-, creatures can’t attack you until a player planeswalks.-      
Akoum - Plane — Zendikar -Players may cast enchantment spells as though they had flash.-Whenever you roll -{CHAOS}-, destroy target creature that isn’t enchanted.-      
Bant - Plane — Alara -All creatures have exalted. -(Whenever a creature attacks alone, it gets +1/+1 until end of turn for each instance of exalted among permanents its controller controls.)--Whenever you roll -{CHAOS}-, put a divinity counter on target green, white, or blue creature. That creature has indestructible for as long as it has a divinity counter on it.-      
Bloodhill Bastion - Plane — Equilor -Whenever a creature enters the battlefield, it gains double strike and haste until end of turn.-Whenever you roll -{CHAOS}-, exile target nontoken creature you control, then return it to the battlefield under your control.-      
Celestine Reef - Plane — Luvion -Creatures without flying or islandwalk can’t attack.-Whenever you roll -{CHAOS}-, until a player planeswalks, you can’t lose the game and your opponents can’t win the game.-      
The Dark Barony - Plane — Ulgrotha -Whenever a nonblack card is put into a player’s graveyard from anywhere, that player loses 1 life.-Whenever you roll -{CHAOS}-, each opponent discards a card.-      
The Eon Fog - Plane — Equilor -Players skip their untap steps.-Whenever you roll -{CHAOS}-, untap all permanents you control.-      
The Fourth Sphere - Plane — Phyrexia -At the beginning of your upkeep, sacrifice a nonblack creature.-Whenever you roll -{CHAOS}-, create a 2/2 black Zombie creature token.-      
Assassinate --{2}--{B}-- Sorcery -Destroy target tapped creature.-      - Astral Arena - Plane — Kolbahan -No more than one creature can attack each combat.-No more than one creature can block each combat.-Whenever you roll -{CHAOS}-, Astral Arena deals 2 damage to each creature.-      
The Great Forest - Plane — Lorwyn -Each creature assigns combat damage equal to its toughness rather than its power.-Whenever you roll -{CHAOS}-, creatures you control get +0/+2 and gain trample until end of turn.-      
The Hippodrome - Plane — Segovia -All creatures get -5/-0.-Whenever you roll -{CHAOS}-, you may destroy target creature if its power is 0 or less.-      
Horizon Boughs - Plane — Pyrulea -All permanents untap during each player’s untap step.-Whenever you roll -{CHAOS}-, you may search your library for up to three basic land cards, put them onto the battlefield tapped, then shuffle your library.-      
Immersturm - Plane — Valla -Whenever a creature enters the battlefield, that creature’s controller may have it deal damage equal to its power to any target of their choice.-Whenever you roll -{CHAOS}-, exile target creature, then return it to the battlefield under its owner’s control.-      
Arc Trail --{1}--{R}-- Sorcery -Arc Trail deals 2 damage to any target and 1 damage to another target.-      - Aretopolis - Plane — Kephalai -When you planeswalk to Aretopolis or at the beginning of your upkeep, put a scroll counter on Aretopolis, then you gain life equal to the number of scroll counters on it.-When Aretopolis has ten or more scroll counters on it, planeswalk.-Whenever you roll -{CHAOS}-, put a scroll counter on Aretopolis, then draw cards equal to the number of scroll counters on it.-      
Isle of Vesuva - Plane — Dominaria -Whenever a nontoken creature enters the battlefield, its controller creates a token that’s a copy of that creature.-Whenever you roll -{CHAOS}-, destroy target creature and all other creatures with the same name as that creature.-      
Izzet Steam Maze - Plane — Ravnica -Whenever a player casts an instant or sorcery spell, that player copies it. The player may choose new targets for the copy.-Whenever you roll -{CHAOS}-, instant and sorcery spells you cast this turn cost -{3}- less to cast.-      
Jund - Plane — Alara -Whenever a player casts a black, red, or green creature spell, it gains devour 5. -(As the creature enters the battlefield, its controller may sacrifice any number of creatures. The creature enters the battlefield with five times that many +1/+1 counters on it.)--Whenever you roll -{CHAOS}-, create two 1/1 red Goblin creature tokens.-      
Kessig - Plane — Innistrad -Prevent all combat damage that would be dealt by non-Werewolf creatures.-Whenever you roll -{CHAOS}-, each creature you control gets +2/+2, gains trample, and becomes a Werewolf in addition to its other types until end of turn.-      
Kharasha Foothills - Plane — Mongseng -Whenever a creature you control attacks a player, for each other opponent, you may create a token that’s a copy of that creature, tapped and attacking that opponent. Exile those tokens at the beginning of the next end step.-Whenever you roll -{CHAOS}-, you may sacrifice any number of creatures. If you do, Kharasha Foothills deals that much damage to target creature.-      
Kilnspire District - Plane — Ravnica -When you planeswalk to Kilnspire District or at the beginning of your precombat main phase, put a charge counter on Kilnspire District, then add -{R}- for each charge counter on it.-Whenever you roll -{CHAOS}-, you may pay -{X}-. If you do, Kilnspire District deals X damage to any target.-      
Krosa - Plane — Dominaria -All creatures get +2/+2.-Whenever you roll -{CHAOS}-, you may add -{W}--{U}--{B}--{R}--{G}-.-      
Lair of the Ashen Idol - Plane — Azgol -At the beginning of your upkeep, sacrifice a creature. If you can’t, planeswalk.-Whenever you roll -{CHAOS}-, any number of target players each create a 2/2 black Zombie creature token.-      
Lethe Lake - Plane — Arkhos -At the beginning of your upkeep, put the top ten cards of your library into your graveyard.-Whenever you roll -{CHAOS}-, target player puts the top ten cards of their library into their graveyard.-      
Llanowar - Plane — Dominaria -All creatures have “-{T}-: Add -{G}--{G}-.”-Whenever you roll -{CHAOS}-, untap all creatures you control.-      
The Maelstrom - Plane — Alara -When you planeswalk to The Maelstrom or at the beginning of your upkeep, you may reveal the top card of your library. If it’s a permanent card, you may put it onto the battlefield. If you revealed a card but didn’t put it onto the battlefield, put it on the bottom of your library.-Whenever you roll -{CHAOS}-, return target permanent card from your graveyard to the battlefield.-      
Minamo - Plane — Kamigawa -Whenever a player casts a spell, that player may draw a card. -Whenever you roll -{CHAOS}-, each player may return a blue card from their graveyard to their hand.-      
Mirrored Depths - Plane — Karsus -Whenever a player casts a spell, that player flips a coin. If the player loses the flip, counter that spell.-Whenever you roll -{CHAOS}-, target player reveals the top card of their library. If it’s a nonland card, you may cast it without paying its mana cost.-      
Mount Keralia - Plane — Regatha -At the beginning of your end step, put a pressure counter on Mount Keralia.-When you planeswalk away from Mount Keralia, it deals damage equal to the number of pressure counters on it to each creature and each planeswalker.-Whenever you roll -{CHAOS}-, prevent all damage that planes named Mount Keralia would deal this game to permanents you control.-      
Murasa - Plane — Zendikar -Whenever a nontoken creature enters the battlefield, its controller may search their library for a basic land card, put it onto the battlefield tapped, then shuffle their library.-Whenever you roll -{CHAOS}-, target land becomes a 4/4 creature that’s still a land.-      
Naar Isle - Plane — Wildfire -At the beginning of your upkeep, put a flame counter on Naar Isle, then Naar Isle deals damage to you equal to the number of flame counters on it.-Whenever you roll -{CHAOS}-, Naar Isle deals 3 damage to target player or planeswalker.-      
Naya - Plane — Alara -You may play any number of lands on each of your turns.-Whenever you roll -{CHAOS}-, target red, green, or white creature you control gets +1/+1 until end of turn for each land you control.-      
Nephalia - Plane — Innistrad -At the beginning of your end step, put the top seven cards of your library into your graveyard. Then return a card at random from your graveyard to your hand.-Whenever you roll -{CHAOS}-, return target card from your graveyard to your hand.-      
Norn&#39;s Dominion - Plane — New Phyrexia -When you planeswalk away from Norn’s Dominion, destroy each nonland permanent without a fate counter on it, then remove all fate counters from all permanents.-Whenever you roll -{CHAOS}-, you may put a fate counter on target permanent.-      
Onakke Catacomb - Plane — Shandalar -All creatures are black and have deathtouch.-Whenever you roll -{CHAOS}-, creatures you control get +1/+0 and gain first strike until end of turn.-      
Orochi Colony - Plane — Kamigawa -Whenever a creature you control deals combat damage to a player, you may search your library for a basic land card, put it onto the battlefield tapped, then shuffle your library.-Whenever you roll -{CHAOS}-, target creature can’t be blocked this turn.-      
Orzhova - Plane — Ravnica -When you planeswalk away from Orzhova, each player returns all creature cards from their graveyard to the battlefield.-Whenever you roll -{CHAOS}-, for each opponent, exile up to one target creature card from that player’s graveyard.-      
Otaria - Plane — Dominaria -Instant and sorcery cards in graveyards have flashback. The flashback cost is equal to the card’s mana cost. -(Its owner may cast the card from their graveyard for its mana cost. Then they exile it.)--Whenever you roll -{CHAOS}-, take an extra turn after this one.-      
Panopticon - Plane — Mirrodin -When you planeswalk to Panopticon, draw a card.-At the beginning of your draw step, draw an additional card.-Whenever you roll -{CHAOS}-, draw a card.-      
Pools of Becoming - Plane — Bolas’s Meditation Realm -At the beginning of your end step, put the cards in your hand on the bottom of your library in any order, then draw that many cards.-Whenever you roll -{CHAOS}-, reveal the top three cards of your planar deck. Each of the revealed cards’ -{CHAOS}- abilities triggers. Then put the revealed cards on the bottom of your planar deck in any order.-      
Prahv - Plane — Ravnica -If you cast a spell this turn, you can’t attack with creatures.-If you attacked with creatures this turn, you can’t cast spells.-Whenever you roll -{CHAOS}-, you gain life equal to the number of cards in your hand.-      
Quicksilver Sea - Plane — Mirrodin -When you planeswalk to Quicksilver Sea or at the beginning of your upkeep, scry 4. -(Look at the top four cards of your library, then put any number of them on the bottom of your library and the rest on top in any order.)--Whenever you roll -{CHAOS}-, reveal the top card of your library. You may play it without paying its mana cost.-      
Raven&#39;s Run - Plane — Shadowmoor -All creatures have wither. -(They deal damage to creatures in the form of -1/-1 counters.)--Whenever you roll -{CHAOS}-, put a -1/-1 counter on target creature, two -1/-1 counters on another target creature, and three -1/-1 counters on a third target creature.-      
Sanctum of Serra - Plane — Serra’s Realm -When you planeswalk away from Sanctum of Serra, destroy all nonland permanents.-Whenever you roll -{CHAOS}-, you may have your life total become 20.-      
Sea of Sand - Plane — Rabiah -Players reveal each card they draw.-Whenever a player draws a land card, that player gains 3 life.-Whenever a player draws a nonland card, that player loses 3 life.-Whenever you roll -{CHAOS}-, put target permanent on top of its owner’s library.-      
Selesnya Loft Gardens - Plane — Ravnica -If an effect would create one or more tokens, it creates twice that many of those tokens instead.-If an effect would put one or more counters on a permanent, it puts twice that many of those counters on that permanent instead.-Whenever you roll -{CHAOS}-, until end of turn, whenever you tap a land for mana, add one mana of any type that land produced.-      
Shiv - Plane — Dominaria -All creatures have “-{R}-: This creature gets +1/+0 until end of turn.”-Whenever you roll -{CHAOS}-, create a 5/5 red Dragon creature token with flying.-      
Skybreen - Plane — Kaldheim -Players play with the top card of their libraries revealed.-Spells that share a card type with the top card of a library can’t be cast.-Whenever you roll -{CHAOS}-, target player loses life equal to the number of cards in their hand.-      
Sokenzan - Plane — Kamigawa -All creatures get +1/+1 and have haste.-Whenever you roll -{CHAOS}-, untap all creatures that attacked this turn. After this main phase, there is an additional combat phase followed by an additional main phase.-      
Stairs to Infinity - Plane — Xerex -Players have no maximum hand size.-Whenever you roll the planar die, draw a card.-Whenever you roll -{CHAOS}-, reveal the top card of your planar deck. You may put it on the bottom of your planar deck.-      
Stensia - Plane — Innistrad -Whenever a creature deals damage to one or more players for the first time each turn, put a +1/+1 counter on it.-Whenever you roll -{CHAOS}-, each creature you control gains “-{T}-: This creature deals 1 damage to target player or planeswalker” until end of turn.-      
Stronghold Furnace - Plane — Rath -If a source would deal damage to a permanent or player, it deals double that damage to that permanent or player instead.-Whenever you roll -{CHAOS}-, Stronghold Furnace deals 1 damage to any target.-      
Takenuma - Plane — Kamigawa -Whenever a creature leaves the battlefield, its controller draws a card.-Whenever you roll -{CHAOS}-, return target creature you control to its owner’s hand.-      
Talon Gates - Plane — Dominaria -Any time you could cast a sorcery, you may exile a nonland card from your hand with X time counters on it, where X is its converted mana cost. If the exiled card doesn’t have suspend, it gains suspend. -(At the beginning of its owner’s upkeep, they remove a time counter. When the last is removed, the player casts it without paying its mana cost. If it’s a creature, it has haste.)--Whenever you roll -{CHAOS}-, remove two time counters from each suspended card you own.-      
Tazeem - Plane — Zendikar -Creatures can’t block.-Whenever you roll -{CHAOS}-, draw a card for each land you control.-      
Tember City - Plane — Kinshala -Whenever a player taps a land for mana, Tember City deals 1 damage to that player.-Whenever you roll -{CHAOS}-, each other player sacrifices a nonland permanent.-      
Trail of the Mage-Rings - Plane — Vryn -Instant and sorcery spells have rebound. -(The spell’s controller exiles the spell as it resolves if they cast it from their hand. At the beginning of that player’s next upkeep, they may cast that card from exile without paying its mana cost.)--Whenever you roll -{CHAOS}-, you may search your library for an instant or sorcery card, reveal it, put it into your hand, then shuffle your library.-      
Truga Jungle - Plane — Ergamon -All lands have “-{T}-: Add one mana of any color.”-Whenever you roll -{CHAOS}-, reveal the top three cards of your library. Put all land cards revealed this way into your hand and the rest on the bottom of your library in any order.-      
Turri Island - Plane — Ir -Creature spells cost -{2}- less to cast.-Whenever you roll -{CHAOS}-, reveal the top three cards of your library. Put all creature cards revealed this way into your hand and the rest into your graveyard.-      
Undercity Reaches - Plane — Ravnica -Whenever a creature deals combat damage to a player, its controller may draw a card.-Whenever you roll -{CHAOS}-, you have no maximum hand size for the rest of the game.-      
Velis Vel - Plane — Lorwyn -Each creature gets +1/+1 for each other creature on the battlefield that shares at least one creature type with it. -(For example, if two Elemental Shamans and an Elemental Spirit are on the battlefield, each gets +2/+2.)--Whenever you roll -{CHAOS}-, target creature gains all creature types until end of turn.-      
Windriddle Palaces - Plane — Belenon -Players play with the top card of their libraries revealed.-You may play the top card of any player’s library.-Whenever you roll -{CHAOS}-, each player puts the top card of their library into their graveyard.-
The Zephyr Maze - Plane — Kyneth -Creatures with flying get +2/+0.-Creatures without flying get -2/-0.-Whenever you roll -{CHAOS}-, target creature gains flying until end of turn.-      
Academy at Tolaria West - Plane — Dominaria -At the beginning of your end step, if you have no cards in hand, draw seven cards.-Whenever you roll -{CHAOS}-, discard your hand.-

**Comment by muz** [comment]
I was going to start adding missing Planes in #14149 but my attention was drawn to here. Just adding that since this issue was last updated, there's also been a set of Dr Who (WHO) Planes [released](https://scryfall.com/search?q=type%3Aplane+-is%3Afunny+-is%3Amemorabilia&unique=cards&as=checklist&order=set).

It doesn't make sense to add these if they'd need heavy refactoring following the core Planechase implementation being finished and fixed up
