### ISSUE TITLE
TOR - Torment set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4860]
# ![Logo](https://magic.wizards.com/sites/mtg/files/EN_GAMEINFO_PRODUCTS_SetIcon_T_JUD_140512_0.png) Torment

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/torment

# Unimplemented cards

22|[Alter Reality](https://magiccards.info/query?q=!Alter+Reality)

# Cards in set:
- [x] [Accelerate](https://magiccards.info/query?q=!Accelerate)
- [x] [Acorn Harvest](https://magiccards.info/query?q=!Acorn+Harvest)
- [ ] [Alter Reality](https://magiccards.info/query?q=!Alter+Reality)
- [x] [Ambassador Laquatus](https://magiccards.info/query?q=!Ambassador+Laquatus)
- [x] [Angel of Retribution](https://magiccards.info/query?q=!Angel+of+Retribution)
- [x] [Anurid Scavenger](https://magiccards.info/query?q=!Anurid+Scavenger)
- [x] [Aquamoeba](https://magiccards.info/query?q=!Aquamoeba)
- [x] [Arrogant Wurm](https://magiccards.info/query?q=!Arrogant+Wurm)
- [x] [Aven Trooper](https://magiccards.info/query?q=!Aven+Trooper)
- [x] [Balshan Collaborator](https://magiccards.info/query?q=!Balshan+Collaborator)
- [x] [Balthor the Stout](https://magiccards.info/query?q=!Balthor+the+Stout)
- [x] [Barbarian Outcast](https://magiccards.info/query?q=!Barbarian+Outcast)
- [x] [Basking Rootwalla](https://magiccards.info/query?q=!Basking+Rootwalla)
- [x] [Boneshard Slasher](https://magiccards.info/query?q=!Boneshard+Slasher)
- [x] [Breakthrough](https://magiccards.info/query?q=!Breakthrough)
- [x] [Cabal Coffers](https://magiccards.info/query?q=!Cabal+Coffers)
- [x] [Cabal Ritual](https://magiccards.info/query?q=!Cabal+Ritual)
- [x] [Cabal Surgeon](https://magiccards.info/query?q=!Cabal+Surgeon)
- [x] [Cabal Torturer](https://magiccards.info/query?q=!Cabal+Torturer)
- [x] [Carrion Rats](https://magiccards.info/query?q=!Carrion+Rats)
- [x] [Carrion Wurm](https://magiccards.info/query?q=!Carrion+Wurm)
- [x] [Centaur Chieftain](https://magiccards.info/query?q=!Centaur+Chieftain)
- [x] [Centaur Veteran](https://magiccards.info/query?q=!Centaur+Veteran)
- [x] [Cephalid Aristocrat](https://magiccards.info/query?q=!Cephalid+Aristocrat)
- [x] [Cephalid Illusionist](https://magiccards.info/query?q=!Cephalid+Illusionist)
- [x] [Cephalid Sage](https://magiccards.info/query?q=!Cephalid+Sage)
- [x] [Cephalid Snitch](https://magiccards.info/query?q=!Cephalid+Snitch)
- [x] [Cephalid Vandal](https://magiccards.info/query?q=!Cephalid+Vandal)
- [x] [Chainer's Edict](https://magiccards.info/query?q=!Chainer's+Edict)
- [x] [Chainer, Dementia Master](https://magiccards.info/query?q=!Chainer,+Dementia+Master)
- [x] [Churning Eddy](https://magiccards.info/query?q=!Churning+Eddy)
- [x] [Circular Logic](https://magiccards.info/query?q=!Circular+Logic)
- [x] [Cleansing Meditation](https://magiccards.info/query?q=!Cleansing+Meditation)
- [x] [Compulsion](https://magiccards.info/query?q=!Compulsion)
- [x] [Coral Net](https://magiccards.info/query?q=!Coral+Net)
- [x] [Crackling Club](https://magiccards.info/query?q=!Crackling+Club)
- [x] [Crazed Firecat](https://magiccards.info/query?q=!Crazed+Firecat)
- [x] [Crippling Fatigue](https://magiccards.info/query?q=!Crippling+Fatigue)
- [x] [Dawn of the Dead](https://magiccards.info/query?q=!Dawn+of+the+Dead)
- [x] [Deep Analysis](https://magiccards.info/query?q=!Deep+Analysis)
- [x] [Devastating Dreams](https://magiccards.info/query?q=!Devastating+Dreams)
- [x] [Dwell on the Past](https://magiccards.info/query?q=!Dwell+on+the+Past)
- [x] [Enslaved Dwarf](https://magiccards.info/query?q=!Enslaved+Dwarf)
- [x] [Equal Treatment](https://magiccards.info/query?q=!Equal+Treatment)
- [x] [Faceless Butcher](https://magiccards.info/query?q=!Faceless+Butcher)
- [x] [False Memories](https://magiccards.info/query?q=!False+Memories)
- [x] [Far Wanderings](https://magiccards.info/query?q=!Far+Wanderings)
- [x] [Fiery Temper](https://magiccards.info/query?q=!Fiery+Temper)
- [x] [Flaming Gambit](https://magiccards.info/query?q=!Flaming+Gambit)
- [x] [Flash of Defiance](https://magiccards.info/query?q=!Flash+of+Defiance)
- [x] [Floating Shield](https://magiccards.info/query?q=!Floating+Shield)
- [x] [Frantic Purification](https://magiccards.info/query?q=!Frantic+Purification)
- [x] [Ghostly Wings](https://magiccards.info/query?q=!Ghostly+Wings)
- [x] [Gloomdrifter](https://magiccards.info/query?q=!Gloomdrifter)
- [x] [Gravegouger](https://magiccards.info/query?q=!Gravegouger)
- [x] [Grim Lavamancer](https://magiccards.info/query?q=!Grim+Lavamancer)
- [x] [Grotesque Hybrid](https://magiccards.info/query?q=!Grotesque+Hybrid)
- [x] [Gurzigost](https://magiccards.info/query?q=!Gurzigost)
- [x] [Hell-Bent Raider](https://magiccards.info/query?q=!Hell-Bent+Raider)
- [x] [Hydromorph Guardian](https://magiccards.info/query?q=!Hydromorph+Guardian)
- [x] [Hydromorph Gull](https://magiccards.info/query?q=!Hydromorph+Gull)
- [x] [Hypnox](https://magiccards.info/query?q=!Hypnox)
- [x] [Hypochondria](https://magiccards.info/query?q=!Hypochondria)
- [x] [Ichorid](https://magiccards.info/query?q=!Ichorid)
- [x] [Insidious Dreams](https://magiccards.info/query?q=!Insidious+Dreams)
- [x] [Insist](https://magiccards.info/query?q=!Insist)
- [x] [Invigorating Falls](https://magiccards.info/query?q=!Invigorating+Falls)
- [x] [Kamahl's Sledge](https://magiccards.info/query?q=!Kamahl's+Sledge)
- [x] [Krosan Constrictor](https://magiccards.info/query?q=!Krosan+Constrictor)
- [x] [Krosan Restorer](https://magiccards.info/query?q=!Krosan+Restorer)
- [x] [Laquatus's Champion](https://magiccards.info/query?q=!Laquatus's+Champion)
- [x] [Last Laugh](https://magiccards.info/query?q=!Last+Laugh)
- [x] [Liquify](https://magiccards.info/query?q=!Liquify)
- [x] [Llawan, Cephalid Empress](https://magiccards.info/query?q=!Llawan,+Cephalid+Empress)
- [x] [Longhorn Firebeast](https://magiccards.info/query?q=!Longhorn+Firebeast)
- [x] [Major Teroh](https://magiccards.info/query?q=!Major+Teroh)
- [x] [Mesmeric Fiend](https://magiccards.info/query?q=!Mesmeric+Fiend)
- [x] [Militant Monk](https://magiccards.info/query?q=!Militant+Monk)
- [x] [Mind Sludge](https://magiccards.info/query?q=!Mind+Sludge)
- [x] [Morningtide](https://magiccards.info/query?q=!Morningtide)
- [x] [Mortal Combat](https://magiccards.info/query?q=!Mortal+Combat)
- [x] [Mortiphobia](https://magiccards.info/query?q=!Mortiphobia)
- [x] [Mutilate](https://magiccards.info/query?q=!Mutilate)
- [x] [Mystic Familiar](https://magiccards.info/query?q=!Mystic+Familiar)
- [x] [Nantuko Blightcutter](https://magiccards.info/query?q=!Nantuko+Blightcutter)
- [x] [Nantuko Calmer](https://magiccards.info/query?q=!Nantuko+Calmer)
- [x] [Nantuko Cultivator](https://magiccards.info/query?q=!Nantuko+Cultivator)
- [x] [Nantuko Shade](https://magiccards.info/query?q=!Nantuko+Shade)
- [x] [Narcissism](https://magiccards.info/query?q=!Narcissism)
- [x] [Nostalgic Dreams](https://magiccards.info/query?q=!Nostalgic+Dreams)
- [x] [Obsessive Search](https://magiccards.info/query?q=!Obsessive+Search)
- [x] [Organ Grinder](https://magiccards.info/query?q=!Organ+Grinder)
- [x] [Overmaster](https://magiccards.info/query?q=!Overmaster)
- [x] [Parallel Evolution](https://magiccards.info/query?q=!Parallel+Evolution)
- [x] [Pardic Arsonist](https://magiccards.info/query?q=!Pardic+Arsonist)
- [x] [Pardic Collaborator](https://magiccards.info/query?q=!Pardic+Collaborator)
- [x] [Pardic Lancer](https://magiccards.info/query?q=!Pardic+Lancer)
- [x] [Pay No Heed](https://magiccards.info/query?q=!Pay+No+Heed)
- [x] [Petradon](https://magiccards.info/query?q=!Petradon)
- [x] [Petravark](https://magiccards.info/query?q=!Petravark)
- [x] [Pitchstone Wall](https://magiccards.info/query?q=!Pitchstone+Wall)
- [x] [Plagiarize](https://magiccards.info/query?q=!Plagiarize)
- [x] [Possessed Aven](https://magiccards.info/query?q=!Possessed+Aven)
- [x] [Possessed Barbarian](https://magiccards.info/query?q=!Possessed+Barbarian)
- [x] [Possessed Centaur](https://magiccards.info/query?q=!Possessed+Centaur)
- [x] [Possessed Nomad](https://magiccards.info/query?q=!Possessed+Nomad)
- [x] [Psychotic Haze](https://magiccards.info/query?q=!Psychotic+Haze)
- [x] [Putrid Imp](https://magiccards.info/query?q=!Putrid+Imp)
- [x] [Pyromania](https://magiccards.info/query?q=!Pyromania)
- [x] [Radiate](https://magiccards.info/query?q=!Radiate)
- [x] [Rancid Earth](https://magiccards.info/query?q=!Rancid+Earth)
- [x] [Reborn Hero](https://magiccards.info/query?q=!Reborn+Hero)
- [x] [Restless Dreams](https://magiccards.info/query?q=!Restless+Dreams)
- [x] [Retraced Image](https://magiccards.info/query?q=!Retraced+Image)
- [x] [Sengir Vampire](https://magiccards.info/query?q=!Sengir+Vampire)
- [x] [Seton's Scout](https://magiccards.info/query?q=!Seton's+Scout)
- [x] [Shade's Form](https://magiccards.info/query?q=!Shade's+Form)
- [x] [Shambling Swarm](https://magiccards.info/query?q=!Shambling+Swarm)
- [x] [Sickening Dreams](https://magiccards.info/query?q=!Sickening+Dreams)
- [x] [Skullscorch](https://magiccards.info/query?q=!Skullscorch)
- [x] [Skywing Aven](https://magiccards.info/query?q=!Skywing+Aven)
- [x] [Slithery Stalker](https://magiccards.info/query?q=!Slithery+Stalker)
- [x] [Sonic Seizure](https://magiccards.info/query?q=!Sonic+Seizure)
- [x] [Soul Scourge](https://magiccards.info/query?q=!Soul+Scourge)
- [x] [Spirit Flare](https://magiccards.info/query?q=!Spirit+Flare)
- [x] [Stern Judge](https://magiccards.info/query?q=!Stern+Judge)
- [x] [Strength of Isolation](https://magiccards.info/query?q=!Strength+of+Isolation)
- [x] [Strength of Lunacy](https://magiccards.info/query?q=!Strength+of+Lunacy)
- [x] [Stupefying Touch](https://magiccards.info/query?q=!Stupefying+Touch)
- [x] [Tainted Field](https://magiccards.info/query?q=!Tainted+Field)
- [x] [Tainted Isle](https://magiccards.info/query?q=!Tainted+Isle)
- [x] [Tainted Peak](https://magiccards.info/query?q=!Tainted+Peak)
- [x] [Tainted Wood](https://magiccards.info/query?q=!Tainted+Wood)
- [x] [Temporary Insanity](https://magiccards.info/query?q=!Temporary+Insanity)
- [x] [Teroh's Faithful](https://magiccards.info/query?q=!Teroh's+Faithful)
- [x] [Teroh's Vanguard](https://magiccards.info/query?q=!Teroh's+Vanguard)
- [x] [Transcendence](https://magiccards.info/query?q=!Transcendence)
- [x] [Turbulent Dreams](https://magiccards.info/query?q=!Turbulent+Dreams)
- [x] [Unhinge](https://magiccards.info/query?q=!Unhinge)
- [x] [Vengeful Dreams](https://magiccards.info/query?q=!Vengeful+Dreams)
- [x] [Violent Eruption](https://magiccards.info/query?q=!Violent+Eruption)
- [x] [Waste Away](https://magiccards.info/query?q=!Waste+Away)
- [x] [Zombie Trailblazer](https://magiccards.info/query?q=!Zombie+Trailblazer)

**Comment by awjackson** [comment]
This checklist is out of date. Spirit Flare, Cephalid Snitch and Retraced Image are implemented.

**Comment by xenohedron** [comment]
Checklist is out of date- Floating Shield, Carrion Rats, Carrion Wurm are implemented.

**Comment by xenohedron** [comment]
All implemented except text changing effects per #2082
