### ISSUE TITLE
1.4.29V3 - Feedback from xmage.de

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4876]
# Feedback from 1.4.29V3

--
- [ ] Muldrotha, the Gravetide: I've found a bug with Muldrotha where if I cause it to re-enter the field, I cannot re-use its effect that turn, when I should be able to, making it difficult to run combos with it. (reported by Orochai / 2018-04-25 12:53:15.986).
- [ ] Karn's Temporal Sundering Broken: It says you may bounce up to one, but it forces you to bounce one (reported by Electro / 2018-04-26 05:22:51.438).
- [ ] Nyxathid: Opponent cast Cyclonic rift on Nyxathid, afterward the game no longer let me cast Nyxathid from my hand (reported by Novalent / 2018-04-26 09:18:55.435).
- [ ] rona: rona, disciple of gix still not working (reported by igniteaxiom / 2018-04-26 10:10:58.501).
- [ ] Blightning Bug: Blightning does not make target player discard any cards. It only does the damage. (reported by Neopard / 2018-04-26 12:03:38.386).
- [ ] Bug: I am not receiving life from (Ashes of the abhorrent) when opponents sac a creature from Porphyry Nodes (reported by Fonagers / 2018-04-26 13:34:06.576).
- [ ] Priority Bug: I don't get a turn. Keeps skipping my turn!!! I draw, it automaticallly goes to opponent's turn. No chance to play, no discard, no nothing. This is dom draft. (reported by IronGuidon / 2018-04-27 03:01:14.263).
- [ ] Undo Metalworker Mana Ability when clicking on the spell first: It would be nice to be able to undo Metalworkers mana ability without having to ask for a rollback. (reported by MrUnbelievable / 2018-04-27 03:26:48.098).
- [ ] Xmage just froze: Tried to play silumgar when i didn't have enough mana, after that I couldn't use anything (reported by KingKali / 2018-04-27 04:13:04.464).

**Comment by theelk801** [comment]
Was the rona report made before or after the server reset? I'm pretty sure I fixed her.

**Comment by LevelX2** [comment]
> Was the rona report made before or after the server reset? I'm pretty sure I fixed her.

Was made after. But we don't know when the bug happened.
