### ISSUE TITLE
Judgment set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4897]
# ![Logo](http://magic.wizards.com/sites/mtg/files/EN_GAMEINFO_PRODUCTS_SetIcon_T_TOR_140512.png) Judgment

https://magic.wizards.com/en/game-info/products/card-set-archive/judgment

# Cards in set:
- [x] [Ancestor's Chosen](https://www.google.com.au/search?q=Ancestor's+Chosen+MTG&tbm=isch)
- [x] [Anger](https://www.google.com.au/search?q=Anger+MTG&tbm=isch)
- [x] [Anurid Barkripper](https://www.google.com.au/search?q=Anurid+Barkripper+MTG&tbm=isch)
- [x] [Anurid Brushhopper](https://www.google.com.au/search?q=Anurid+Brushhopper+MTG&tbm=isch)
- [x] [Anurid Swarmsnapper](https://www.google.com.au/search?q=Anurid+Swarmsnapper+MTG&tbm=isch)
- [x] [Arcane Teachings](https://www.google.com.au/search?q=Arcane+Teachings+MTG&tbm=isch)
- [x] [Aven Fogbringer](https://www.google.com.au/search?q=Aven+Fogbringer+MTG&tbm=isch)
- [ ] [Aven Warcraft](https://www.google.com.au/search?q=Aven+Warcraft+MTG&tbm=isch)
- [x] [Balthor the Defiled](https://www.google.com.au/search?q=Balthor+the+Defiled+MTG&tbm=isch)
- [ ] [Barbarian Bully](https://www.google.com.au/search?q=Barbarian+Bully+MTG&tbm=isch)
- [x] [Battle Screech](https://www.google.com.au/search?q=Battle+Screech+MTG&tbm=isch)
- [x] [Battlefield Scrounger](https://www.google.com.au/search?q=Battlefield+Scrounger+MTG&tbm=isch)
- [x] [Battlewise Aven](https://www.google.com.au/search?q=Battlewise+Aven+MTG&tbm=isch)
- [x] [Benevolent Bodyguard](https://www.google.com.au/search?q=Benevolent+Bodyguard+MTG&tbm=isch)
- [x] [Book Burning](https://www.google.com.au/search?q=Book+Burning+MTG&tbm=isch)
- [x] [Border Patrol](https://www.google.com.au/search?q=Border+Patrol+MTG&tbm=isch)
- [x] [Brawn](https://www.google.com.au/search?q=Brawn+MTG&tbm=isch)
- [x] [Breaking Point](https://www.google.com.au/search?q=Breaking+Point+MTG&tbm=isch)
- [x] [Browbeat](https://www.google.com.au/search?q=Browbeat+MTG&tbm=isch)
- [x] [Burning Wish](https://www.google.com.au/search?q=Burning+Wish+MTG&tbm=isch)
- [x] [Cabal Therapy](https://www.google.com.au/search?q=Cabal+Therapy+MTG&tbm=isch)
- [x] [Cabal Trainee](https://www.google.com.au/search?q=Cabal+Trainee+MTG&tbm=isch)
- [x] [Cagemail](https://www.google.com.au/search?q=Cagemail+MTG&tbm=isch)
- [x] [Canopy Claws](https://www.google.com.au/search?q=Canopy+Claws+MTG&tbm=isch)
- [x] [Centaur Rootcaster](https://www.google.com.au/search?q=Centaur+Rootcaster+MTG&tbm=isch)
- [x] [Cephalid Constable](https://www.google.com.au/search?q=Cephalid+Constable+MTG&tbm=isch)
- [x] [Cephalid Inkshrouder](https://www.google.com.au/search?q=Cephalid+Inkshrouder+MTG&tbm=isch)
- [x] [Chastise](https://www.google.com.au/search?q=Chastise+MTG&tbm=isch)
- [x] [Commander Eesha](https://www.google.com.au/search?q=Commander+Eesha+MTG&tbm=isch)
- [x] [Crush of Wurms](https://www.google.com.au/search?q=Crush+of+Wurms+MTG&tbm=isch)
- [x] [Cunning Wish](https://www.google.com.au/search?q=Cunning+Wish+MTG&tbm=isch)
- [x] [Death Wish](https://www.google.com.au/search?q=Death+Wish+MTG&tbm=isch)
- [x] [Defy Gravity](https://www.google.com.au/search?q=Defy+Gravity+MTG&tbm=isch)
- [x] [Dwarven Bloodboiler](https://www.google.com.au/search?q=Dwarven+Bloodboiler+MTG&tbm=isch)
- [x] [Dwarven Driller](https://www.google.com.au/search?q=Dwarven+Driller+MTG&tbm=isch)
- [ ] [Dwarven Scorcher](https://www.google.com.au/search?q=Dwarven+Scorcher+MTG&tbm=isch)
- [x] [Earsplitting Rats](https://www.google.com.au/search?q=Earsplitting+Rats+MTG&tbm=isch)
- [x] [Elephant Guide](https://www.google.com.au/search?q=Elephant+Guide+MTG&tbm=isch)
- [x] [Ember Shot](https://www.google.com.au/search?q=Ember+Shot+MTG&tbm=isch)
- [x] [Envelop](https://www.google.com.au/search?q=Envelop+MTG&tbm=isch)
- [x] [Epic Struggle](https://www.google.com.au/search?q=Epic+Struggle+MTG&tbm=isch)
- [x] [Erhnam Djinn](https://www.google.com.au/search?q=Erhnam+Djinn+MTG&tbm=isch)
- [x] [Exoskeletal Armor](https://www.google.com.au/search?q=Exoskeletal+Armor+MTG&tbm=isch)
- [x] [Filth](https://www.google.com.au/search?q=Filth+MTG&tbm=isch)
- [x] [Firecat Blitz](https://www.google.com.au/search?q=Firecat+Blitz+MTG&tbm=isch)
- [x] [Flaring Pain](https://www.google.com.au/search?q=Flaring+Pain+MTG&tbm=isch)
- [x] [Flash of Insight](https://www.google.com.au/search?q=Flash+of+Insight+MTG&tbm=isch)
- [x] [Fledgling Dragon](https://www.google.com.au/search?q=Fledgling+Dragon+MTG&tbm=isch)
- [x] [Folk Medicine](https://www.google.com.au/search?q=Folk+Medicine+MTG&tbm=isch)
- [x] [Forcemage Advocate](https://www.google.com.au/search?q=Forcemage+Advocate+MTG&tbm=isch)
- [x] [Funeral Pyre](https://www.google.com.au/search?q=Funeral+Pyre+MTG&tbm=isch)
- [x] [Genesis](https://www.google.com.au/search?q=Genesis+MTG&tbm=isch)
- [x] [Giant Warthog](https://www.google.com.au/search?q=Giant+Warthog+MTG&tbm=isch)
- [x] [Glory](https://www.google.com.au/search?q=Glory+MTG&tbm=isch)
- [x] [Golden Wish](https://www.google.com.au/search?q=Golden+Wish+MTG&tbm=isch)
- [x] [Goretusk Firebeast](https://www.google.com.au/search?q=Goretusk+Firebeast+MTG&tbm=isch)
- [ ] [Grave Consequences](https://www.google.com.au/search?q=Grave+Consequences+MTG&tbm=isch)
- [ ] [Grip of Amnesia](https://www.google.com.au/search?q=Grip+of+Amnesia+MTG&tbm=isch)
- [x] [Grizzly Fate](https://www.google.com.au/search?q=Grizzly+Fate+MTG&tbm=isch)
- [x] [Guided Strike](https://www.google.com.au/search?q=Guided+Strike+MTG&tbm=isch)
- [x] [Guiltfeeder](https://www.google.com.au/search?q=Guiltfeeder+MTG&tbm=isch)
- [x] [Hapless Researcher](https://www.google.com.au/search?q=Hapless+Researcher+MTG&tbm=isch)
- [x] [Harvester Druid](https://www.google.com.au/search?q=Harvester+Druid+MTG&tbm=isch)
- [x] [Hunting Grounds](https://www.google.com.au/search?q=Hunting+Grounds+MTG&tbm=isch)
- [ ] [Infectious Rage](https://www.google.com.au/search?q=Infectious+Rage+MTG&tbm=isch)
- [x] [Ironshell Beetle](https://www.google.com.au/search?q=Ironshell+Beetle+MTG&tbm=isch)
- [x] [Jeska, Warrior Adept](https://www.google.com.au/search?q=Jeska,+Warrior+Adept+MTG&tbm=isch)
- [x] [Keep Watch](https://www.google.com.au/search?q=Keep+Watch+MTG&tbm=isch)
- [x] [Krosan Reclamation](https://www.google.com.au/search?q=Krosan+Reclamation+MTG&tbm=isch)
- [x] [Krosan Verge](https://www.google.com.au/search?q=Krosan+Verge+MTG&tbm=isch)
- [x] [Krosan Wayfarer](https://www.google.com.au/search?q=Krosan+Wayfarer+MTG&tbm=isch)
- [x] [Laquatus's Disdain](https://www.google.com.au/search?q=Laquatus's+Disdain+MTG&tbm=isch)
- [x] [Lava Dart](https://www.google.com.au/search?q=Lava+Dart+MTG&tbm=isch)
- [x] [Lead Astray](https://www.google.com.au/search?q=Lead+Astray+MTG&tbm=isch)
- [x] [Liberated Dwarf](https://www.google.com.au/search?q=Liberated+Dwarf+MTG&tbm=isch)
- [x] [Lightning Surge](https://www.google.com.au/search?q=Lightning+Surge+MTG&tbm=isch)
- [x] [Living Wish](https://www.google.com.au/search?q=Living+Wish+MTG&tbm=isch)
- [ ] [Lost in Thought](https://www.google.com.au/search?q=Lost+in+Thought+MTG&tbm=isch)
- [x] [Masked Gorgon](https://www.google.com.au/search?q=Masked+Gorgon+MTG&tbm=isch)
- [x] [Mental Note](https://www.google.com.au/search?q=Mental+Note+MTG&tbm=isch)
- [x] [Mirari's Wake](https://www.google.com.au/search?q=Mirari's+Wake+MTG&tbm=isch)
- [x] [Mirror Wall](https://www.google.com.au/search?q=Mirror+Wall+MTG&tbm=isch)
- [x] [Mist of Stagnation](https://www.google.com.au/search?q=Mist+of+Stagnation+MTG&tbm=isch)
- [x] [Morality Shift](https://www.google.com.au/search?q=Morality+Shift+MTG&tbm=isch)
- [x] [Nantuko Monastery](https://www.google.com.au/search?q=Nantuko+Monastery+MTG&tbm=isch)
- [x] [Nantuko Tracer](https://www.google.com.au/search?q=Nantuko+Tracer+MTG&tbm=isch)
- [x] [Nomad Mythmaker](https://www.google.com.au/search?q=Nomad+Mythmaker+MTG&tbm=isch)
- [x] [Nullmage Advocate](https://www.google.com.au/search?q=Nullmage+Advocate+MTG&tbm=isch)
- [x] [Phantom Centaur](https://www.google.com.au/search?q=Phantom+Centaur+MTG&tbm=isch)
- [x] [Phantom Flock](https://www.google.com.au/search?q=Phantom+Flock+MTG&tbm=isch)
- [x] [Phantom Nantuko](https://www.google.com.au/search?q=Phantom+Nantuko+MTG&tbm=isch)
- [x] [Phantom Nishoba](https://www.google.com.au/search?q=Phantom+Nishoba+MTG&tbm=isch)
- [x] [Phantom Nomad](https://www.google.com.au/search?q=Phantom+Nomad+MTG&tbm=isch)
- [x] [Phantom Tiger](https://www.google.com.au/search?q=Phantom+Tiger+MTG&tbm=isch)
- [x] [Planar Chaos](https://www.google.com.au/search?q=Planar+Chaos+MTG&tbm=isch)
- [x] [Prismatic Strands](https://www.google.com.au/search?q=Prismatic+Strands+MTG&tbm=isch)
- [x] [Pulsemage Advocate](https://www.google.com.au/search?q=Pulsemage+Advocate+MTG&tbm=isch)
- [x] [Quiet Speculation](https://www.google.com.au/search?q=Quiet+Speculation+MTG&tbm=isch)
- [ ] [Rats' Feast](https://www.google.com.au/search?q=Rats'+Feast+MTG&tbm=isch)
- [x] [Ray of Revelation](https://www.google.com.au/search?q=Ray+of+Revelation+MTG&tbm=isch)
- [x] [Riftstone Portal](https://www.google.com.au/search?q=Riftstone+Portal+MTG&tbm=isch)
- [x] [Scalpelexis](https://www.google.com.au/search?q=Scalpelexis+MTG&tbm=isch)
- [x] [Seedtime](https://www.google.com.au/search?q=Seedtime+MTG&tbm=isch)
- [ ] [Selfless Exorcist](https://www.google.com.au/search?q=Selfless+Exorcist+MTG&tbm=isch)
- [ ] [Serene Sunset](https://www.google.com.au/search?q=Serene+Sunset+MTG&tbm=isch)
- [ ] [Shaman's Trance](https://www.google.com.au/search?q=Shaman's+Trance+MTG&tbm=isch)
- [x] [Shieldmage Advocate](https://www.google.com.au/search?q=Shieldmage+Advocate+MTG&tbm=isch)
- [x] [Silver Seraph](https://www.google.com.au/search?q=Silver+Seraph+MTG&tbm=isch)
- [x] [Solitary Confinement](https://www.google.com.au/search?q=Solitary+Confinement+MTG&tbm=isch)
- [x] [Soulcatchers' Aerie](https://www.google.com.au/search?q=Soulcatchers'+Aerie+MTG&tbm=isch)
- [ ] [Soulgorger Orgg](https://www.google.com.au/search?q=Soulgorger+Orgg+MTG&tbm=isch)
- [x] [Spellgorger Barbarian](https://www.google.com.au/search?q=Spellgorger+Barbarian+MTG&tbm=isch)
- [x] [Spelljack](https://www.google.com.au/search?q=Spelljack+MTG&tbm=isch)
- [x] [Spirit Cairn](https://www.google.com.au/search?q=Spirit+Cairn+MTG&tbm=isch)
- [x] [Spurnmage Advocate](https://www.google.com.au/search?q=Spurnmage+Advocate+MTG&tbm=isch)
- [x] [Stitch Together](https://www.google.com.au/search?q=Stitch+Together+MTG&tbm=isch)
- [x] [Sudden Strength](https://www.google.com.au/search?q=Sudden+Strength+MTG&tbm=isch)
- [x] [Suntail Hawk](https://www.google.com.au/search?q=Suntail+Hawk+MTG&tbm=isch)
- [x] [Sutured Ghoul](https://www.google.com.au/search?q=Sutured+Ghoul+MTG&tbm=isch)
- [x] [Swelter](https://www.google.com.au/search?q=Swelter+MTG&tbm=isch)
- [x] [Swirling Sandstorm](https://www.google.com.au/search?q=Swirling+Sandstorm+MTG&tbm=isch)
- [x] [Sylvan Safekeeper](https://www.google.com.au/search?q=Sylvan+Safekeeper+MTG&tbm=isch)
- [x] [Telekinetic Bonds](https://www.google.com.au/search?q=Telekinetic+Bonds+MTG&tbm=isch)
- [x] [Test of Endurance](https://www.google.com.au/search?q=Test+of+Endurance+MTG&tbm=isch)
- [x] [Thriss, Nantuko Primus](https://www.google.com.au/search?q=Thriss,+Nantuko+Primus+MTG&tbm=isch)
- [x] [Toxic Stench](https://www.google.com.au/search?q=Toxic+Stench+MTG&tbm=isch)
- [x] [Trained Pronghorn](https://www.google.com.au/search?q=Trained+Pronghorn+MTG&tbm=isch)
- [x] [Treacherous Vampire](https://www.google.com.au/search?q=Treacherous+Vampire+MTG&tbm=isch)
- [x] [Treacherous Werewolf](https://www.google.com.au/search?q=Treacherous+Werewolf+MTG&tbm=isch)
- [x] [Tunneler Wurm](https://www.google.com.au/search?q=Tunneler+Wurm+MTG&tbm=isch)
- [x] [Unquestioned Authority](https://www.google.com.au/search?q=Unquestioned+Authority+MTG&tbm=isch)
- [x] [Valor](https://www.google.com.au/search?q=Valor+MTG&tbm=isch)
- [x] [Venomous Vines](https://www.google.com.au/search?q=Venomous+Vines+MTG&tbm=isch)
- [x] [Vigilant Sentry](https://www.google.com.au/search?q=Vigilant+Sentry+MTG&tbm=isch)
- [x] [Web of Inertia](https://www.google.com.au/search?q=Web+of+Inertia+MTG&tbm=isch)
- [x] [Wonder](https://www.google.com.au/search?q=Wonder+MTG&tbm=isch)
- [x] [Worldgorger Dragon](https://www.google.com.au/search?q=Worldgorger+Dragon+MTG&tbm=isch)
- [ ] [Wormfang Behemoth](https://www.google.com.au/search?q=Wormfang+Behemoth+MTG&tbm=isch)
- [ ] [Wormfang Crab](https://www.google.com.au/search?q=Wormfang+Crab+MTG&tbm=isch)
- [x] [Wormfang Drake](https://www.google.com.au/search?q=Wormfang+Drake+MTG&tbm=isch)
- [x] [Wormfang Manta](https://www.google.com.au/search?q=Wormfang+Manta+MTG&tbm=isch)
- [x] [Wormfang Newt](https://www.google.com.au/search?q=Wormfang+Newt+MTG&tbm=isch)
- [x] [Wormfang Turtle](https://www.google.com.au/search?q=Wormfang+Turtle+MTG&tbm=isch)

**Comment by awjackson** [comment]
This checklist is out of date. Selfless Exorcist, Grip of Amnesia, Rats' Feast, Barbarian Bully and Dwarven Scorcher are implemented.

**Comment by xenohedron** [comment]
Following cards are implemented: Wormfang Behemoth, Grave Consequences, Serene Sunset
