### ISSUE TITLE
ONS - Onslaught set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4900]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/onslaught

# Unimplemented cards

- [ ] [Artificial Evolution](https://magiccards.info/query?q=!Artificial+Evolution)

# Implemented
<details><summary>Click to expand</summary>

- [x] [Circle of Solace](https://magiccards.info/query?q=!Circle+of+Solace)
- [x] [Crown of Ascension](https://magiccards.info/query?q=!Crown+of+Ascension)
- [x] [Crown of Awe](https://magiccards.info/query?q=!Crown+of+Awe)
- [x] [Crown of Suspicion](https://magiccards.info/query?q=!Crown+of+Suspicion)
- [x] [Crown of Vigor](https://magiccards.info/query?q=!Crown+of+Vigor)
- [x] [Graxiplon](https://magiccards.info/query?q=!Graxiplon)
- [x] [Meddle](https://magiccards.info/query?q=!Meddle)
- [x] [Kaboom!](https://magiccards.info/query?q=!Kaboom!)
- [x] [AEther Charge](https://magiccards.info/query?q=!AEther+Charge)
- [x] [Accursed Centaur](https://magiccards.info/query?q=!Accursed+Centaur)
- [x] [Aggravated Assault](https://magiccards.info/query?q=!Aggravated+Assault)
- [x] [Airborne Aid](https://magiccards.info/query?q=!Airborne+Aid)
- [x] [Airdrop Condor](https://magiccards.info/query?q=!Airdrop+Condor)
- [x] [Akroma's Blessing](https://magiccards.info/query?q=!Akroma's+Blessing)
- [x] [Akroma's Vengeance](https://magiccards.info/query?q=!Akroma's+Vengeance)
- [x] [Ancestor's Prophet](https://magiccards.info/query?q=!Ancestor's+Prophet)
- [x] [Animal Magnetism](https://magiccards.info/query?q=!Animal+Magnetism)
- [x] [Annex](https://magiccards.info/query?q=!Annex)
- [x] [Anurid Murkdiver](https://magiccards.info/query?q=!Anurid+Murkdiver)
- [x] [Aphetto Alchemist](https://magiccards.info/query?q=!Aphetto+Alchemist)
- [x] [Aphetto Dredging](https://magiccards.info/query?q=!Aphetto+Dredging)
- [x] [Aphetto Grifter](https://magiccards.info/query?q=!Aphetto+Grifter)
- [x] [Aphetto Vulture](https://magiccards.info/query?q=!Aphetto+Vulture)
- [x] [Arcanis the Omnipotent](https://magiccards.info/query?q=!Arcanis+the+Omnipotent)
- [x] [Ascending Aven](https://magiccards.info/query?q=!Ascending+Aven)
- [x] [Astral Slide](https://magiccards.info/query?q=!Astral+Slide)
- [x] [Aura Extraction](https://magiccards.info/query?q=!Aura+Extraction)
- [x] [Aurification](https://magiccards.info/query?q=!Aurification)
- [x] [Avarax](https://magiccards.info/query?q=!Avarax)
- [x] [Aven Brigadier](https://magiccards.info/query?q=!Aven+Brigadier)
- [x] [Aven Fateshaper](https://magiccards.info/query?q=!Aven+Fateshaper)
- [x] [Aven Soulgazer](https://magiccards.info/query?q=!Aven+Soulgazer)
- [x] [Backslide](https://magiccards.info/query?q=!Backslide)
- [x] [Barkhide Mauler](https://magiccards.info/query?q=!Barkhide+Mauler)
- [x] [Barren Moor](https://magiccards.info/query?q=!Barren+Moor)
- [x] [Battering Craghorn](https://magiccards.info/query?q=!Battering+Craghorn)
- [x] [Battlefield Medic](https://magiccards.info/query?q=!Battlefield+Medic)
- [x] [Biorhythm](https://magiccards.info/query?q=!Biorhythm)
- [x] [Birchlore Rangers](https://magiccards.info/query?q=!Birchlore+Rangers)
- [x] [Blackmail](https://magiccards.info/query?q=!Blackmail)
- [x] [Blatant Thievery](https://magiccards.info/query?q=!Blatant+Thievery)
- [x] [Blistering Firecat](https://magiccards.info/query?q=!Blistering+Firecat)
- [x] [Bloodline Shaman](https://magiccards.info/query?q=!Bloodline+Shaman)
- [x] [Bloodstained Mire](https://magiccards.info/query?q=!Bloodstained+Mire)
- [x] [Boneknitter](https://magiccards.info/query?q=!Boneknitter)
- [x] [Break Open](https://magiccards.info/query?q=!Break+Open)
- [x] [Brightstone Ritual](https://magiccards.info/query?q=!Brightstone+Ritual)
- [x] [Broodhatch Nantuko](https://magiccards.info/query?q=!Broodhatch+Nantuko)
- [x] [Butcher Orgg](https://magiccards.info/query?q=!Butcher+Orgg)
- [x] [Cabal Archon](https://magiccards.info/query?q=!Cabal+Archon)
- [x] [Cabal Executioner](https://magiccards.info/query?q=!Cabal+Executioner)
- [x] [Cabal Slaver](https://magiccards.info/query?q=!Cabal+Slaver)
- [x] [Callous Oppressor](https://magiccards.info/query?q=!Callous+Oppressor)
- [x] [Catapult Master](https://magiccards.info/query?q=!Catapult+Master)
- [x] [Catapult Squad](https://magiccards.info/query?q=!Catapult+Squad)
- [x] [Centaur Glade](https://magiccards.info/query?q=!Centaur+Glade)
- [x] [Chain of Acid](https://magiccards.info/query?q=!Chain+of+Acid)
- [x] [Chain of Plasma](https://magiccards.info/query?q=!Chain+of+Plasma)
- [x] [Chain of Silence](https://magiccards.info/query?q=!Chain+of+Silence)
- [x] [Chain of Smog](https://magiccards.info/query?q=!Chain+of+Smog)
- [x] [Chain of Vapor](https://magiccards.info/query?q=!Chain+of+Vapor)
- [x] [Charging Slateback](https://magiccards.info/query?q=!Charging+Slateback)
- [x] [Choking Tethers](https://magiccards.info/query?q=!Choking+Tethers)
- [x] [Clone](https://magiccards.info/query?q=!Clone)
- [x] [Commando Raid](https://magiccards.info/query?q=!Commando+Raid)
- [x] [Complicate](https://magiccards.info/query?q=!Complicate)
- [x] [Contested Cliffs](https://magiccards.info/query?q=!Contested+Cliffs)
- [x] [Convalescent Care](https://magiccards.info/query?q=!Convalescent+Care)
- [x] [Cover of Darkness](https://magiccards.info/query?q=!Cover+of+Darkness)
- [x] [Crafty Pathmage](https://magiccards.info/query?q=!Crafty+Pathmage)
- [x] [Crowd Favorites](https://magiccards.info/query?q=!Crowd+Favorites)
- [x] [Crown of Ascension](https://magiccards.info/query?q=!Crown+of+Ascension)
- [x] [Crown of Awe](https://magiccards.info/query?q=!Crown+of+Awe)
- [x] [Crown of Fury](https://magiccards.info/query?q=!Crown+of+Fury)
- [x] [Crown of Suspicion](https://magiccards.info/query?q=!Crown+of+Suspicion)
- [x] [Crown of Vigor](https://magiccards.info/query?q=!Crown+of+Vigor)
- [x] [Crude Rampart](https://magiccards.info/query?q=!Crude+Rampart)
- [x] [Cruel Revival](https://magiccards.info/query?q=!Cruel+Revival)
- [x] [Cryptic Gateway](https://magiccards.info/query?q=!Cryptic+Gateway)
- [x] [Custody Battle](https://magiccards.info/query?q=!Custody+Battle)
- [x] [Daru Cavalier](https://magiccards.info/query?q=!Daru+Cavalier)
- [x] [Daru Encampment](https://magiccards.info/query?q=!Daru+Encampment)
- [x] [Daru Healer](https://magiccards.info/query?q=!Daru+Healer)
- [x] [Daru Lancer](https://magiccards.info/query?q=!Daru+Lancer)
- [x] [Daunting Defender](https://magiccards.info/query?q=!Daunting+Defender)
- [x] [Dawning Purist](https://magiccards.info/query?q=!Dawning+Purist)
- [x] [Death Match](https://magiccards.info/query?q=!Death+Match)
- [x] [Death Pulse](https://magiccards.info/query?q=!Death+Pulse)
- [x] [Defensive Maneuvers](https://magiccards.info/query?q=!Defensive+Maneuvers)
- [x] [Demystify](https://magiccards.info/query?q=!Demystify)
- [x] [Dirge of Dread](https://magiccards.info/query?q=!Dirge+of+Dread)
- [x] [Disciple of Grace](https://magiccards.info/query?q=!Disciple+of+Grace)
- [x] [Disciple of Malice](https://magiccards.info/query?q=!Disciple+of+Malice)
- [x] [Discombobulate](https://magiccards.info/query?q=!Discombobulate)
- [x] [Dispersing Orb](https://magiccards.info/query?q=!Dispersing+Orb)
- [x] [Disruptive Pitmage](https://magiccards.info/query?q=!Disruptive+Pitmage)
- [x] [Dive Bomber](https://magiccards.info/query?q=!Dive+Bomber)
- [x] [Doom Cannon](https://magiccards.info/query?q=!Doom+Cannon)
- [x] [Doomed Necromancer](https://magiccards.info/query?q=!Doomed+Necromancer)
- [x] [Doubtless One](https://magiccards.info/query?q=!Doubtless+One)
- [x] [Dragon Roost](https://magiccards.info/query?q=!Dragon+Roost)
- [x] [Dream Chisel](https://magiccards.info/query?q=!Dream+Chisel)
- [x] [Dwarven Blastminer](https://magiccards.info/query?q=!Dwarven+Blastminer)
- [x] [Ebonblade Reaper](https://magiccards.info/query?q=!Ebonblade+Reaper)
- [x] [Elven Riders](https://magiccards.info/query?q=!Elven+Riders)
- [x] [Elvish Guidance](https://magiccards.info/query?q=!Elvish+Guidance)
- [x] [Elvish Pathcutter](https://magiccards.info/query?q=!Elvish+Pathcutter)
- [x] [Elvish Pioneer](https://magiccards.info/query?q=!Elvish+Pioneer)
- [x] [Elvish Scrapper](https://magiccards.info/query?q=!Elvish+Scrapper)
- [x] [Elvish Vanguard](https://magiccards.info/query?q=!Elvish+Vanguard)
- [x] [Elvish Warrior](https://magiccards.info/query?q=!Elvish+Warrior)
- [x] [Embermage Goblin](https://magiccards.info/query?q=!Embermage+Goblin)
- [x] [Enchantress's Presence](https://magiccards.info/query?q=!Enchantress's+Presence)
- [x] [Endemic Plague](https://magiccards.info/query?q=!Endemic+Plague)
- [x] [Entrails Feaster](https://magiccards.info/query?q=!Entrails+Feaster)
- [x] [Erratic Explosion](https://magiccards.info/query?q=!Erratic+Explosion)
- [x] [Essence Fracture](https://magiccards.info/query?q=!Essence+Fracture)
- [x] [Everglove Courier](https://magiccards.info/query?q=!Everglove+Courier)
- [x] [Exalted Angel](https://magiccards.info/query?q=!Exalted+Angel)
- [x] [Explosive Vegetation](https://magiccards.info/query?q=!Explosive+Vegetation)
- [x] [Fade from Memory](https://magiccards.info/query?q=!Fade+from+Memory)
- [x] [Fallen Cleric](https://magiccards.info/query?q=!Fallen+Cleric)
- [x] [False Cure](https://magiccards.info/query?q=!False+Cure)
- [x] [Feeding Frenzy](https://magiccards.info/query?q=!Feeding+Frenzy)
- [x] [Festering Goblin](https://magiccards.info/query?q=!Festering+Goblin)
- [x] [Fever Charm](https://magiccards.info/query?q=!Fever+Charm)
- [x] [Flamestick Courier](https://magiccards.info/query?q=!Flamestick+Courier)
- [x] [Fleeting Aven](https://magiccards.info/query?q=!Fleeting+Aven)
- [x] [Flooded Strand](https://magiccards.info/query?q=!Flooded+Strand)
- [x] [Foothill Guide](https://magiccards.info/query?q=!Foothill+Guide)
- [x] [Forest](https://magiccards.info/query?q=!Forest)
- [x] [Forgotten Cave](https://magiccards.info/query?q=!Forgotten+Cave)
- [x] [Frightshroud Courier](https://magiccards.info/query?q=!Frightshroud+Courier)
- [x] [Future Sight](https://magiccards.info/query?q=!Future+Sight)
- [x] [Gangrenous Goliath](https://magiccards.info/query?q=!Gangrenous+Goliath)
- [x] [Ghosthelm Courier](https://magiccards.info/query?q=!Ghosthelm+Courier)
- [x] [Gigapede](https://magiccards.info/query?q=!Gigapede)
- [x] [Glarecaster](https://magiccards.info/query?q=!Glarecaster)
- [x] [Glory Seeker](https://magiccards.info/query?q=!Glory+Seeker)
- [x] [Gluttonous Zombie](https://magiccards.info/query?q=!Gluttonous+Zombie)
- [x] [Goblin Burrows](https://magiccards.info/query?q=!Goblin+Burrows)
- [x] [Goblin Machinist](https://magiccards.info/query?q=!Goblin+Machinist)
- [x] [Goblin Piledriver](https://magiccards.info/query?q=!Goblin+Piledriver)
- [x] [Goblin Pyromancer](https://magiccards.info/query?q=!Goblin+Pyromancer)
- [x] [Goblin Sharpshooter](https://magiccards.info/query?q=!Goblin+Sharpshooter)
- [x] [Goblin Sky Raider](https://magiccards.info/query?q=!Goblin+Sky+Raider)
- [x] [Goblin Sledder](https://magiccards.info/query?q=!Goblin+Sledder)
- [x] [Goblin Taskmaster](https://magiccards.info/query?q=!Goblin+Taskmaster)
- [x] [Grand Coliseum](https://magiccards.info/query?q=!Grand+Coliseum)
- [x] [Grand Melee](https://magiccards.info/query?q=!Grand+Melee)
- [x] [Grassland Crusader](https://magiccards.info/query?q=!Grassland+Crusader)
- [x] [Gratuitous Violence](https://magiccards.info/query?q=!Gratuitous+Violence)
- [x] [Gravel Slinger](https://magiccards.info/query?q=!Gravel+Slinger)
- [x] [Gravespawn Sovereign](https://magiccards.info/query?q=!Gravespawn+Sovereign)
- [x] [Graxiplon](https://magiccards.info/query?q=!Graxiplon)
- [x] [Grinning Demon](https://magiccards.info/query?q=!Grinning+Demon)
- [x] [Gustcloak Harrier](https://magiccards.info/query?q=!Gustcloak+Harrier)
- [x] [Gustcloak Runner](https://magiccards.info/query?q=!Gustcloak+Runner)
- [x] [Gustcloak Savior](https://magiccards.info/query?q=!Gustcloak+Savior)
- [x] [Gustcloak Sentinel](https://magiccards.info/query?q=!Gustcloak+Sentinel)
- [x] [Gustcloak Skirmisher](https://magiccards.info/query?q=!Gustcloak+Skirmisher)
- [x] [Harsh Mercy](https://magiccards.info/query?q=!Harsh+Mercy)
- [x] [Haunted Cadaver](https://magiccards.info/query?q=!Haunted+Cadaver)
- [x] [Head Games](https://magiccards.info/query?q=!Head+Games)
- [x] [Headhunter](https://magiccards.info/query?q=!Headhunter)
- [x] [Heedless One](https://magiccards.info/query?q=!Heedless+One)
- [x] [Hystrodon](https://magiccards.info/query?q=!Hystrodon)
- [x] [Imagecrafter](https://magiccards.info/query?q=!Imagecrafter)
- [x] [Improvised Armor](https://magiccards.info/query?q=!Improvised+Armor)
- [x] [Infest](https://magiccards.info/query?q=!Infest)
- [x] [Information Dealer](https://magiccards.info/query?q=!Information+Dealer)
- [x] [Inspirit](https://magiccards.info/query?q=!Inspirit)
- [x] [Insurrection](https://magiccards.info/query?q=!Insurrection)
- [x] [Invigorating Boon](https://magiccards.info/query?q=!Invigorating+Boon)
- [x] [Ironfist Crusher](https://magiccards.info/query?q=!Ironfist+Crusher)
- [x] [Island](https://magiccards.info/query?q=!Island)
- [x] [Ixidor's Will](https://magiccards.info/query?q=!Ixidor's+Will)
- [x] [Ixidor, Reality Sculptor](https://magiccards.info/query?q=!Ixidor,+Reality+Sculptor)
- [x] [Jareth, Leonine Titan](https://magiccards.info/query?q=!Jareth,+Leonine+Titan)
- [x] [Kamahl's Summons](https://magiccards.info/query?q=!Kamahl's+Summons)
- [x] [Kamahl, Fist of Krosa](https://magiccards.info/query?q=!Kamahl,+Fist+of+Krosa)
- [x] [Krosan Colossus](https://magiccards.info/query?q=!Krosan+Colossus)
- [x] [Krosan Groundshaker](https://magiccards.info/query?q=!Krosan+Groundshaker)
- [x] [Krosan Tusker](https://magiccards.info/query?q=!Krosan+Tusker)
- [x] [Lavamancer's Skill](https://magiccards.info/query?q=!Lavamancer's+Skill)
- [x] [Lay Waste](https://magiccards.info/query?q=!Lay+Waste)
- [x] [Leery Fogbeast](https://magiccards.info/query?q=!Leery+Fogbeast)
- [x] [Lightning Rift](https://magiccards.info/query?q=!Lightning+Rift)
- [x] [Lonely Sandbar](https://magiccards.info/query?q=!Lonely+Sandbar)
- [x] [Mage's Guile](https://magiccards.info/query?q=!Mage's+Guile)
- [x] [Mana Echoes](https://magiccards.info/query?q=!Mana+Echoes)
- [x] [Meddle](https://magiccards.info/query?q=!Meddle)
- [x] [Menacing Ogre](https://magiccards.info/query?q=!Menacing+Ogre)
- [x] [Misery Charm](https://magiccards.info/query?q=!Misery+Charm)
- [x] [Mistform Dreamer](https://magiccards.info/query?q=!Mistform+Dreamer)
- [x] [Mistform Mask](https://magiccards.info/query?q=!Mistform+Mask)
- [x] [Mistform Mutant](https://magiccards.info/query?q=!Mistform+Mutant)
- [x] [Mistform Shrieker](https://magiccards.info/query?q=!Mistform+Shrieker)
- [x] [Mistform Skyreaver](https://magiccards.info/query?q=!Mistform+Skyreaver)
- [x] [Mistform Stalker](https://magiccards.info/query?q=!Mistform+Stalker)
- [x] [Mistform Wall](https://magiccards.info/query?q=!Mistform+Wall)
- [x] [Mobilization](https://magiccards.info/query?q=!Mobilization)
- [x] [Mountain](https://magiccards.info/query?q=!Mountain)
- [x] [Mythic Proportions](https://magiccards.info/query?q=!Mythic+Proportions)
- [x] [Nameless One](https://magiccards.info/query?q=!Nameless+One)
- [x] [Nantuko Husk](https://magiccards.info/query?q=!Nantuko+Husk)
- [x] [Naturalize](https://magiccards.info/query?q=!Naturalize)
- [x] [Nosy Goblin](https://magiccards.info/query?q=!Nosy+Goblin)
- [x] [Nova Cleric](https://magiccards.info/query?q=!Nova+Cleric)
- [x] [Oblation](https://magiccards.info/query?q=!Oblation)
- [x] [Oversold Cemetery](https://magiccards.info/query?q=!Oversold+Cemetery)
- [x] [Overwhelming Instinct](https://magiccards.info/query?q=!Overwhelming+Instinct)
- [x] [Pacifism](https://magiccards.info/query?q=!Pacifism)
- [x] [Patriarch's Bidding](https://magiccards.info/query?q=!Patriarch's+Bidding)
- [x] [Pearlspear Courier](https://magiccards.info/query?q=!Pearlspear+Courier)
- [x] [Peer Pressure](https://magiccards.info/query?q=!Peer+Pressure)
- [x] [Piety Charm](https://magiccards.info/query?q=!Piety+Charm)
- [x] [Pinpoint Avalanche](https://magiccards.info/query?q=!Pinpoint+Avalanche)
- [x] [Plains](https://magiccards.info/query?q=!Plains)
- [x] [Polluted Delta](https://magiccards.info/query?q=!Polluted+Delta)
- [x] [Primal Boost](https://magiccards.info/query?q=!Primal+Boost)
- [x] [Profane Prayers](https://magiccards.info/query?q=!Profane+Prayers)
- [x] [Prowling Pangolin](https://magiccards.info/query?q=!Prowling+Pangolin)
- [x] [Psychic Trance](https://magiccards.info/query?q=!Psychic+Trance)
- [x] [Quicksilver Dragon](https://magiccards.info/query?q=!Quicksilver+Dragon)
- [x] [Ravenous Baloth](https://magiccards.info/query?q=!Ravenous+Baloth)
- [x] [Read the Runes](https://magiccards.info/query?q=!Read+the+Runes)
- [x] [Reckless One](https://magiccards.info/query?q=!Reckless+One)
- [x] [Reminisce](https://magiccards.info/query?q=!Reminisce)
- [x] [Renewed Faith](https://magiccards.info/query?q=!Renewed+Faith)
- [x] [Righteous Cause](https://magiccards.info/query?q=!Righteous+Cause)
- [x] [Riptide Biologist](https://magiccards.info/query?q=!Riptide+Biologist)
- [x] [Riptide Chronologist](https://magiccards.info/query?q=!Riptide+Chronologist)
- [x] [Riptide Entrancer](https://magiccards.info/query?q=!Riptide+Entrancer)
- [x] [Riptide Laboratory](https://magiccards.info/query?q=!Riptide+Laboratory)
- [x] [Riptide Replicator](https://magiccards.info/query?q=!Riptide+Replicator)
- [x] [Riptide Shapeshifter](https://magiccards.info/query?q=!Riptide+Shapeshifter)
- [x] [Risky Move](https://magiccards.info/query?q=!Risky+Move)
- [x] [Rorix Bladewing](https://magiccards.info/query?q=!Rorix+Bladewing)
- [x] [Rotlung Reanimator](https://magiccards.info/query?q=!Rotlung+Reanimator)
- [x] [Rummaging Wizard](https://magiccards.info/query?q=!Rummaging+Wizard)
- [x] [Run Wild](https://magiccards.info/query?q=!Run+Wild)
- [x] [Sage Aven](https://magiccards.info/query?q=!Sage+Aven)
- [x] [Sandskin](https://magiccards.info/query?q=!Sandskin)
- [x] [Screaming Seahawk](https://magiccards.info/query?q=!Screaming+Seahawk)
- [x] [Screeching Buzzard](https://magiccards.info/query?q=!Screeching+Buzzard)
- [x] [Sea's Claim](https://magiccards.info/query?q=!Sea's+Claim)
- [x] [Searing Flesh](https://magiccards.info/query?q=!Searing+Flesh)
- [x] [Seaside Haven](https://magiccards.info/query?q=!Seaside+Haven)
- [x] [Secluded Steppe](https://magiccards.info/query?q=!Secluded+Steppe)
- [x] [Serpentine Basilisk](https://magiccards.info/query?q=!Serpentine+Basilisk)
- [x] [Severed Legion](https://magiccards.info/query?q=!Severed+Legion)
- [x] [Shade's Breath](https://magiccards.info/query?q=!Shade's+Breath)
- [x] [Shaleskin Bruiser](https://magiccards.info/query?q=!Shaleskin+Bruiser)
- [x] [Shared Triumph](https://magiccards.info/query?q=!Shared+Triumph)
- [x] [Shepherd of Rot](https://magiccards.info/query?q=!Shepherd+of+Rot)
- [x] [Shieldmage Elder](https://magiccards.info/query?q=!Shieldmage+Elder)
- [x] [Shock](https://magiccards.info/query?q=!Shock)
- [x] [Sigil of the New Dawn](https://magiccards.info/query?q=!Sigil+of+the+New+Dawn)
- [x] [Silent Specter](https://magiccards.info/query?q=!Silent+Specter)
- [x] [Silklash Spider](https://magiccards.info/query?q=!Silklash+Spider)
- [x] [Silvos, Rogue Elemental](https://magiccards.info/query?q=!Silvos,+Rogue+Elemental)
- [x] [Skirk Commando](https://magiccards.info/query?q=!Skirk+Commando)
- [x] [Skirk Fire Marshal](https://magiccards.info/query?q=!Skirk+Fire+Marshal)
- [x] [Skirk Prospector](https://magiccards.info/query?q=!Skirk+Prospector)
- [x] [Skittish Valesk](https://magiccards.info/query?q=!Skittish+Valesk)
- [x] [Slate of Ancestry](https://magiccards.info/query?q=!Slate+of+Ancestry)
- [x] [Slice and Dice](https://magiccards.info/query?q=!Slice+and+Dice)
- [x] [Slipstream Eel](https://magiccards.info/query?q=!Slipstream+Eel)
- [x] [Smother](https://magiccards.info/query?q=!Smother)
- [x] [Snapping Thragg](https://magiccards.info/query?q=!Snapping+Thragg)
- [x] [Snarling Undorak](https://magiccards.info/query?q=!Snarling+Undorak)
- [x] [Solar Blast](https://magiccards.info/query?q=!Solar+Blast)
- [x] [Soulless One](https://magiccards.info/query?q=!Soulless+One)
- [x] [Sparksmith](https://magiccards.info/query?q=!Sparksmith)
- [x] [Spined Basher](https://magiccards.info/query?q=!Spined+Basher)
- [x] [Spitfire Handler](https://magiccards.info/query?q=!Spitfire+Handler)
- [x] [Spitting Gourna](https://magiccards.info/query?q=!Spitting+Gourna)
- [x] [Spurred Wolverine](https://magiccards.info/query?q=!Spurred+Wolverine)
- [x] [Spy Network](https://magiccards.info/query?q=!Spy+Network)
- [x] [Stag Beetle](https://magiccards.info/query?q=!Stag+Beetle)
- [x] [Standardize](https://magiccards.info/query?q=!Standardize)
- [x] [Starlit Sanctum](https://magiccards.info/query?q=!Starlit+Sanctum)
- [x] [Starstorm](https://magiccards.info/query?q=!Starstorm)
- [x] [Steely Resolve](https://magiccards.info/query?q=!Steely+Resolve)
- [x] [Strongarm Tactics](https://magiccards.info/query?q=!Strongarm+Tactics)
- [x] [Sunfire Balm](https://magiccards.info/query?q=!Sunfire+Balm)
- [x] [Supreme Inquisitor](https://magiccards.info/query?q=!Supreme+Inquisitor)
- [x] [Swamp](https://magiccards.info/query?q=!Swamp)
- [x] [Swat](https://magiccards.info/query?q=!Swat)
- [x] [Symbiotic Beast](https://magiccards.info/query?q=!Symbiotic+Beast)
- [x] [Symbiotic Elf](https://magiccards.info/query?q=!Symbiotic+Elf)
- [x] [Symbiotic Wurm](https://magiccards.info/query?q=!Symbiotic+Wurm)
- [x] [Syphon Mind](https://magiccards.info/query?q=!Syphon+Mind)
- [x] [Syphon Soul](https://magiccards.info/query?q=!Syphon+Soul)
- [x] [Taunting Elf](https://magiccards.info/query?q=!Taunting+Elf)
- [x] [Tempting Wurm](https://magiccards.info/query?q=!Tempting+Wurm)
- [x] [Tephraderm](https://magiccards.info/query?q=!Tephraderm)
- [x] [Thoughtbound Primoc](https://magiccards.info/query?q=!Thoughtbound+Primoc)
- [x] [Thrashing Mudspawn](https://magiccards.info/query?q=!Thrashing+Mudspawn)
- [x] [Threaten](https://magiccards.info/query?q=!Threaten)
- [x] [Thunder of Hooves](https://magiccards.info/query?q=!Thunder+of+Hooves)
- [x] [Towering Baloth](https://magiccards.info/query?q=!Towering+Baloth)
- [x] [Trade Secrets](https://magiccards.info/query?q=!Trade+Secrets)
- [x] [Tranquil Thicket](https://magiccards.info/query?q=!Tranquil+Thicket)
- [x] [Treespring Lorian](https://magiccards.info/query?q=!Treespring+Lorian)
- [x] [Tribal Golem](https://magiccards.info/query?q=!Tribal+Golem)
- [x] [Tribal Unity](https://magiccards.info/query?q=!Tribal+Unity)
- [x] [Trickery Charm](https://magiccards.info/query?q=!Trickery+Charm)
- [x] [True Believer](https://magiccards.info/query?q=!True+Believer)
- [x] [Undead Gladiator](https://magiccards.info/query?q=!Undead+Gladiator)
- [x] [Unholy Grotto](https://magiccards.info/query?q=!Unholy+Grotto)
- [x] [Unified Strike](https://magiccards.info/query?q=!Unified+Strike)
- [x] [Venomspout Brackus](https://magiccards.info/query?q=!Venomspout+Brackus)
- [x] [Visara the Dreadful](https://magiccards.info/query?q=!Visara+the+Dreadful)
- [x] [Vitality Charm](https://magiccards.info/query?q=!Vitality+Charm)
- [x] [Voice of the Woods](https://magiccards.info/query?q=!Voice+of+the+Woods)
- [x] [Voidmage Prodigy](https://magiccards.info/query?q=!Voidmage+Prodigy)
- [x] [Walking Desecration](https://magiccards.info/query?q=!Walking+Desecration)
- [x] [Wall of Mulch](https://magiccards.info/query?q=!Wall+of+Mulch)
- [x] [Wave of Indifference](https://magiccards.info/query?q=!Wave+of+Indifference)
- [x] [Weathered Wayfarer](https://magiccards.info/query?q=!Weathered+Wayfarer)
- [x] [Weird Harvest](https://magiccards.info/query?q=!Weird+Harvest)
- [x] [Wellwisher](https://magiccards.info/query?q=!Wellwisher)
- [x] [Wheel and Deal](https://magiccards.info/query?q=!Wheel+and+Deal)
- [x] [Whipcorder](https://magiccards.info/query?q=!Whipcorder)
- [x] [Windswept Heath](https://magiccards.info/query?q=!Windswept+Heath)
- [x] [Wirewood Elf](https://magiccards.info/query?q=!Wirewood+Elf)
- [x] [Wirewood Herald](https://magiccards.info/query?q=!Wirewood+Herald)
- [x] [Wirewood Lodge](https://magiccards.info/query?q=!Wirewood+Lodge)
- [x] [Wirewood Pride](https://magiccards.info/query?q=!Wirewood+Pride)
- [x] [Wirewood Savage](https://magiccards.info/query?q=!Wirewood+Savage)
- [x] [Withering Hex](https://magiccards.info/query?q=!Withering+Hex)
- [x] [Wooded Foothills](https://magiccards.info/query?q=!Wooded+Foothills)
- [x] [Words of War](https://magiccards.info/query?q=!Words+of+War)
- [x] [Words of Waste](https://magiccards.info/query?q=!Words+of+Waste)
- [x] [Words of Wilding](https://magiccards.info/query?q=!Words+of+Wilding)
- [x] [Words of Wind](https://magiccards.info/query?q=!Words+of+Wind)
- [x] [Words of Worship](https://magiccards.info/query?q=!Words+of+Worship)
- [x] [Wretched Anurid](https://magiccards.info/query?q=!Wretched+Anurid)
</details>

**Comment by xenohedron** [comment]
These cards have been implemented: Crown of Ascension, Crown of Awe, Crown of Suspicion, Crown of Vigor, Graxiplon, Meddle

**Comment by xenohedron** [comment]
All implemented except text changing effects per #2082
