### ISSUE TITLE
Legions set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4901]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/legions

# Unimplemented cards
- None

# Cards in set:
- [x] [Akroma's Devoted](https://magiccards.info/query?q=!Akroma's+Devoted)
- [x] [Akroma, Angel of Wrath](https://magiccards.info/query?q=!Akroma,+Angel+of+Wrath)
- [x] [Aphetto Exterminator](https://magiccards.info/query?q=!Aphetto+Exterminator)
- [x] [Aven Envoy](https://magiccards.info/query?q=!Aven+Envoy)
- [x] [Aven Redeemer](https://magiccards.info/query?q=!Aven+Redeemer)
- [x] [Aven Warhawk](https://magiccards.info/query?q=!Aven+Warhawk)
- [x] [Bane of the Living](https://magiccards.info/query?q=!Bane+of+the+Living)
- [x] [Beacon of Destiny](https://magiccards.info/query?q=!Beacon+of+Destiny)
- [x] [Berserk Murlodont](https://magiccards.info/query?q=!Berserk+Murlodont)
- [x] [Blade Sliver](https://magiccards.info/query?q=!Blade+Sliver)
- [x] [Blood Celebrant](https://magiccards.info/query?q=!Blood+Celebrant)
- [x] [Bloodstoke Howler](https://magiccards.info/query?q=!Bloodstoke+Howler)
- [x] [Branchsnap Lorian](https://magiccards.info/query?q=!Branchsnap+Lorian)
- [x] [Brontotherium](https://magiccards.info/query?q=!Brontotherium)
- [x] [Brood Sliver](https://magiccards.info/query?q=!Brood+Sliver)
- [x] [Caller of the Claw](https://magiccards.info/query?q=!Caller+of+the+Claw)
- [x] [Canopy Crawler](https://magiccards.info/query?q=!Canopy+Crawler)
- [x] [Celestial Gatekeeper](https://magiccards.info/query?q=!Celestial+Gatekeeper)
- [x] [Cephalid Pathmage](https://magiccards.info/query?q=!Cephalid+Pathmage)
- [x] [Chromeshell Crab](https://magiccards.info/query?q=!Chromeshell+Crab)
- [x] [Clickslither](https://magiccards.info/query?q=!Clickslither)
- [x] [Cloudreach Cavalry](https://magiccards.info/query?q=!Cloudreach+Cavalry)
- [x] [Corpse Harvester](https://magiccards.info/query?q=!Corpse+Harvester)
- [x] [Covert Operative](https://magiccards.info/query?q=!Covert+Operative)
- [x] [Crested Craghorn](https://magiccards.info/query?q=!Crested+Craghorn)
- [x] [Crookclaw Elder](https://magiccards.info/query?q=!Crookclaw+Elder)
- [x] [Crypt Sliver](https://magiccards.info/query?q=!Crypt+Sliver)
- [x] [Dark Supplicant](https://magiccards.info/query?q=!Dark+Supplicant)
- [x] [Daru Mender](https://magiccards.info/query?q=!Daru+Mender)
- [x] [Daru Sanctifier](https://magiccards.info/query?q=!Daru+Sanctifier)
- [x] [Daru Stinger](https://magiccards.info/query?q=!Daru+Stinger)
- [x] [Deathmark Prelate](https://magiccards.info/query?q=!Deathmark+Prelate)
- [x] [Defender of the Order](https://magiccards.info/query?q=!Defender+of+the+Order)
- [x] [Defiant Elf](https://magiccards.info/query?q=!Defiant+Elf)
- [x] [Deftblade Elite](https://magiccards.info/query?q=!Deftblade+Elite)
- [x] [Dermoplasm](https://magiccards.info/query?q=!Dermoplasm)
- [x] [Dreamborn Muse](https://magiccards.info/query?q=!Dreamborn+Muse)
- [x] [Drinker of Sorrow](https://magiccards.info/query?q=!Drinker+of+Sorrow)
- [x] [Dripping Dead](https://magiccards.info/query?q=!Dripping+Dead)
- [x] [Earthblighter](https://magiccards.info/query?q=!Earthblighter)
- [x] [Echo Tracer](https://magiccards.info/query?q=!Echo+Tracer)
- [x] [Elvish Soultiller](https://magiccards.info/query?q=!Elvish+Soultiller)
- [x] [Embalmed Brawler](https://magiccards.info/query?q=!Embalmed+Brawler)
- [x] [Enormous Baloth](https://magiccards.info/query?q=!Enormous+Baloth)
- [x] [Essence Sliver](https://magiccards.info/query?q=!Essence+Sliver)
- [x] [Feral Throwback](https://magiccards.info/query?q=!Feral+Throwback)
- [x] [Flamewave Invoker](https://magiccards.info/query?q=!Flamewave+Invoker)
- [x] [Frenetic Raptor](https://magiccards.info/query?q=!Frenetic+Raptor)
- [x] [Fugitive Wizard](https://magiccards.info/query?q=!Fugitive+Wizard)
- [x] [Gempalm Avenger](https://magiccards.info/query?q=!Gempalm+Avenger)
- [x] [Gempalm Incinerator](https://magiccards.info/query?q=!Gempalm+Incinerator)
- [x] [Gempalm Polluter](https://magiccards.info/query?q=!Gempalm+Polluter)
- [x] [Gempalm Sorcerer](https://magiccards.info/query?q=!Gempalm+Sorcerer)
- [x] [Gempalm Strider](https://magiccards.info/query?q=!Gempalm+Strider)
- [x] [Ghastly Remains](https://magiccards.info/query?q=!Ghastly+Remains)
- [x] [Glintwing Invoker](https://magiccards.info/query?q=!Glintwing+Invoker)
- [x] [Glowering Rogon](https://magiccards.info/query?q=!Glowering+Rogon)
- [x] [Glowrider](https://magiccards.info/query?q=!Glowrider)
- [x] [Goblin Assassin](https://magiccards.info/query?q=!Goblin+Assassin)
- [x] [Goblin Clearcutter](https://magiccards.info/query?q=!Goblin+Clearcutter)
- [x] [Goblin Dynamo](https://magiccards.info/query?q=!Goblin+Dynamo)
- [x] [Goblin Firebug](https://magiccards.info/query?q=!Goblin+Firebug)
- [x] [Goblin Goon](https://magiccards.info/query?q=!Goblin+Goon)
- [x] [Goblin Grappler](https://magiccards.info/query?q=!Goblin+Grappler)
- [x] [Goblin Lookout](https://magiccards.info/query?q=!Goblin+Lookout)
- [x] [Goblin Turncoat](https://magiccards.info/query?q=!Goblin+Turncoat)
- [x] [Graveborn Muse](https://magiccards.info/query?q=!Graveborn+Muse)
- [x] [Havoc Demon](https://magiccards.info/query?q=!Havoc+Demon)
- [x] [Hollow Specter](https://magiccards.info/query?q=!Hollow+Specter)
- [x] [Hundroog](https://magiccards.info/query?q=!Hundroog)
- [x] [Hunter Sliver](https://magiccards.info/query?q=!Hunter+Sliver)
- [x] [Imperial Hellkite](https://magiccards.info/query?q=!Imperial+Hellkite)
- [x] [Infernal Caretaker](https://magiccards.info/query?q=!Infernal+Caretaker)
- [x] [Keeneye Aven](https://magiccards.info/query?q=!Keeneye+Aven)
- [x] [Keeper of the Nine Gales](https://magiccards.info/query?q=!Keeper+of+the+Nine+Gales)
- [x] [Kilnmouth Dragon](https://magiccards.info/query?q=!Kilnmouth+Dragon)
- [x] [Krosan Cloudscraper](https://magiccards.info/query?q=!Krosan+Cloudscraper)
- [x] [Krosan Vorine](https://magiccards.info/query?q=!Krosan+Vorine)
- [x] [Lavaborn Muse](https://magiccards.info/query?q=!Lavaborn+Muse)
- [x] [Liege of the Axe](https://magiccards.info/query?q=!Liege+of+the+Axe)
- [x] [Lowland Tracker](https://magiccards.info/query?q=!Lowland+Tracker)
- [x] [Macetail Hystrodon](https://magiccards.info/query?q=!Macetail+Hystrodon)
- [x] [Magma Sliver](https://magiccards.info/query?q=!Magma+Sliver)
- [x] [Master of the Veil](https://magiccards.info/query?q=!Master+of+the+Veil)
- [x] [Merchant of Secrets](https://magiccards.info/query?q=!Merchant+of+Secrets)
- [x] [Mistform Seaswift](https://magiccards.info/query?q=!Mistform+Seaswift)
- [x] [Mistform Sliver](https://magiccards.info/query?q=!Mistform+Sliver)
- [x] [Mistform Ultimus](https://magiccards.info/query?q=!Mistform+Ultimus)
- [x] [Mistform Wakecaster](https://magiccards.info/query?q=!Mistform+Wakecaster)
- [x] [Nantuko Vigilante](https://magiccards.info/query?q=!Nantuko+Vigilante)
- [x] [Needleshot Gourna](https://magiccards.info/query?q=!Needleshot+Gourna)
- [x] [Noxious Ghoul](https://magiccards.info/query?q=!Noxious+Ghoul)
- [x] [Patron of the Wild](https://magiccards.info/query?q=!Patron+of+the+Wild)
- [x] [Phage the Untouchable](https://magiccards.info/query?q=!Phage+the+Untouchable)
- [x] [Planar Guide](https://magiccards.info/query?q=!Planar+Guide)
- [x] [Plated Sliver](https://magiccards.info/query?q=!Plated+Sliver)
- [x] [Primal Whisperer](https://magiccards.info/query?q=!Primal+Whisperer)
- [x] [Primoc Escapee](https://magiccards.info/query?q=!Primoc+Escapee)
- [x] [Quick Sliver](https://magiccards.info/query?q=!Quick+Sliver)
- [x] [Ridgetop Raptor](https://magiccards.info/query?q=!Ridgetop+Raptor)
- [x] [Riptide Director](https://magiccards.info/query?q=!Riptide+Director)
- [x] [Riptide Mangler](https://magiccards.info/query?q=!Riptide+Mangler)
- [x] [Rockshard Elemental](https://magiccards.info/query?q=!Rockshard+Elemental)
- [x] [Root Sliver](https://magiccards.info/query?q=!Root+Sliver)
- [x] [Scion of Darkness](https://magiccards.info/query?q=!Scion+of+Darkness)
- [x] [Seedborn Muse](https://magiccards.info/query?q=!Seedborn+Muse)
- [x] [Shaleskin Plower](https://magiccards.info/query?q=!Shaleskin+Plower)
- [x] [Shifting Sliver](https://magiccards.info/query?q=!Shifting+Sliver)
- [x] [Skinthinner](https://magiccards.info/query?q=!Skinthinner)
- [x] [Skirk Alarmist](https://magiccards.info/query?q=!Skirk+Alarmist)
- [x] [Skirk Drill Sergeant](https://magiccards.info/query?q=!Skirk+Drill+Sergeant)
- [x] [Skirk Marauder](https://magiccards.info/query?q=!Skirk+Marauder)
- [x] [Skirk Outrider](https://magiccards.info/query?q=!Skirk+Outrider)
- [x] [Smokespew Invoker](https://magiccards.info/query?q=!Smokespew+Invoker)
- [x] [Sootfeather Flock](https://magiccards.info/query?q=!Sootfeather+Flock)
- [x] [Spectral Sliver](https://magiccards.info/query?q=!Spectral+Sliver)
- [x] [Starlight Invoker](https://magiccards.info/query?q=!Starlight+Invoker)
- [x] [Stoic Champion](https://magiccards.info/query?q=!Stoic+Champion)
- [x] [Stonewood Invoker](https://magiccards.info/query?q=!Stonewood+Invoker)
- [x] [Sunstrike Legionnaire](https://magiccards.info/query?q=!Sunstrike+Legionnaire)
- [x] [Swooping Talon](https://magiccards.info/query?q=!Swooping+Talon)
- [x] [Synapse Sliver](https://magiccards.info/query?q=!Synapse+Sliver)
- [x] [Timberwatch Elf](https://magiccards.info/query?q=!Timberwatch+Elf)
- [x] [Totem Speaker](https://magiccards.info/query?q=!Totem+Speaker)
- [x] [Toxin Sliver](https://magiccards.info/query?q=!Toxin+Sliver)
- [x] [Tribal Forcemage](https://magiccards.info/query?q=!Tribal+Forcemage)
- [x] [Unstable Hulk](https://magiccards.info/query?q=!Unstable+Hulk)
- [x] [Vexing Beetle](https://magiccards.info/query?q=!Vexing+Beetle)
- [x] [Vile Deacon](https://magiccards.info/query?q=!Vile+Deacon)
- [x] [Voidmage Apprentice](https://magiccards.info/query?q=!Voidmage+Apprentice)
- [x] [Wall of Deceit](https://magiccards.info/query?q=!Wall+of+Deceit)
- [x] [Wall of Hope](https://magiccards.info/query?q=!Wall+of+Hope)
- [x] [Warbreak Trumpeter](https://magiccards.info/query?q=!Warbreak+Trumpeter)
- [x] [Ward Sliver](https://magiccards.info/query?q=!Ward+Sliver)
- [x] [Warped Researcher](https://magiccards.info/query?q=!Warped+Researcher)
- [x] [Weaver of Lies](https://magiccards.info/query?q=!Weaver+of+Lies)
- [x] [Whipgrass Entangler](https://magiccards.info/query?q=!Whipgrass+Entangler)
- [x] [White Knight](https://magiccards.info/query?q=!White+Knight)
- [x] [Willbender](https://magiccards.info/query?q=!Willbender)
- [x] [Windborn Muse](https://magiccards.info/query?q=!Windborn+Muse)
- [x] [Wingbeat Warrior](https://magiccards.info/query?q=!Wingbeat+Warrior)
- [x] [Wirewood Channeler](https://magiccards.info/query?q=!Wirewood+Channeler)
- [x] [Wirewood Hivemaster](https://magiccards.info/query?q=!Wirewood+Hivemaster)
- [x] [Withered Wretch](https://magiccards.info/query?q=!Withered+Wretch)
- [x] [Zombie Brute](https://magiccards.info/query?q=!Zombie+Brute)
