### ISSUE TITLE
SCG - Scourge set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4902]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/scourge

# Unimplemented cards

13|[Exiled Doomsayer](https://magiccards.info/query?q=!Exiled+Doomsayer)

# Cards in set:
- [x] [Accelerated Mutation](https://magiccards.info/query?q=!Accelerated+Mutation)
- [x] [Ageless Sentinels](https://magiccards.info/query?q=!Ageless+Sentinels)
- [x] [Alpha Status](https://magiccards.info/query?q=!Alpha+Status)
- [x] [Ambush Commander](https://magiccards.info/query?q=!Ambush+Commander)
- [x] [Ancient Ooze](https://magiccards.info/query?q=!Ancient+Ooze)
- [x] [Aphetto Runecaster](https://magiccards.info/query?q=!Aphetto+Runecaster)
- [x] [Ark of Blight](https://magiccards.info/query?q=!Ark+of+Blight)
- [x] [Astral Steel](https://magiccards.info/query?q=!Astral+Steel)
- [x] [Aven Farseer](https://magiccards.info/query?q=!Aven+Farseer)
- [x] [Aven Liberator](https://magiccards.info/query?q=!Aven+Liberator)
- [x] [Bladewing the Risen](https://magiccards.info/query?q=!Bladewing+the+Risen)
- [x] [Bladewing's Thrall](https://magiccards.info/query?q=!Bladewing's+Thrall)
- [x] [Bonethorn Valesk](https://magiccards.info/query?q=!Bonethorn+Valesk)
- [x] [Brain Freeze](https://magiccards.info/query?q=!Brain+Freeze)
- [x] [Break Asunder](https://magiccards.info/query?q=!Break+Asunder)
- [x] [Cabal Conditioning](https://magiccards.info/query?q=!Cabal+Conditioning)
- [x] [Cabal Interrogator](https://magiccards.info/query?q=!Cabal+Interrogator)
- [x] [Call to the Grave](https://magiccards.info/query?q=!Call+to+the+Grave)
- [x] [Carbonize](https://magiccards.info/query?q=!Carbonize)
- [x] [Carrion Feeder](https://magiccards.info/query?q=!Carrion+Feeder)
- [x] [Chartooth Cougar](https://magiccards.info/query?q=!Chartooth+Cougar)
- [x] [Chill Haunting](https://magiccards.info/query?q=!Chill+Haunting)
- [x] [Claws of Wirewood](https://magiccards.info/query?q=!Claws+of+Wirewood)
- [x] [Clutch of Undeath](https://magiccards.info/query?q=!Clutch+of+Undeath)
- [x] [Coast Watcher](https://magiccards.info/query?q=!Coast+Watcher)
- [x] [Consumptive Goo](https://magiccards.info/query?q=!Consumptive+Goo)
- [x] [Daru Spiritualist](https://magiccards.info/query?q=!Daru+Spiritualist)
- [x] [Daru Warchief](https://magiccards.info/query?q=!Daru+Warchief)
- [x] [Dawn Elemental](https://magiccards.info/query?q=!Dawn+Elemental)
- [x] [Day of the Dragons](https://magiccards.info/query?q=!Day+of+the+Dragons)
- [x] [Death's-Head Buzzard](https://magiccards.info/query?q=!Death's-Head+Buzzard)
- [x] [Decree of Annihilation](https://magiccards.info/query?q=!Decree+of+Annihilation)
- [x] [Decree of Justice](https://magiccards.info/query?q=!Decree+of+Justice)
- [x] [Decree of Pain](https://magiccards.info/query?q=!Decree+of+Pain)
- [x] [Decree of Savagery](https://magiccards.info/query?q=!Decree+of+Savagery)
- [x] [Decree of Silence](https://magiccards.info/query?q=!Decree+of+Silence)
- [x] [Dimensional Breach](https://magiccards.info/query?q=!Dimensional+Breach)
- [x] [Dispersal Shield](https://magiccards.info/query?q=!Dispersal+Shield)
- [x] [Divergent Growth](https://magiccards.info/query?q=!Divergent+Growth)
- [x] [Dragon Breath](https://magiccards.info/query?q=!Dragon+Breath)
- [x] [Dragon Fangs](https://magiccards.info/query?q=!Dragon+Fangs)
- [x] [Dragon Mage](https://magiccards.info/query?q=!Dragon+Mage)
- [x] [Dragon Scales](https://magiccards.info/query?q=!Dragon+Scales)
- [x] [Dragon Shadow](https://magiccards.info/query?q=!Dragon+Shadow)
- [x] [Dragon Tyrant](https://magiccards.info/query?q=!Dragon+Tyrant)
- [x] [Dragon Wings](https://magiccards.info/query?q=!Dragon+Wings)
- [x] [Dragonspeaker Shaman](https://magiccards.info/query?q=!Dragonspeaker+Shaman)
- [x] [Dragonstalker](https://magiccards.info/query?q=!Dragonstalker)
- [x] [Dragonstorm](https://magiccards.info/query?q=!Dragonstorm)
- [x] [Edgewalker](https://magiccards.info/query?q=!Edgewalker)
- [x] [Elvish Aberration](https://magiccards.info/query?q=!Elvish+Aberration)
- [x] [Enrage](https://magiccards.info/query?q=!Enrage)
- [x] [Eternal Dragon](https://magiccards.info/query?q=!Eternal+Dragon)
- [ ] [Exiled Doomsayer](https://magiccards.info/query?q=!Exiled+Doomsayer)
- [x] [Extra Arms](https://magiccards.info/query?q=!Extra+Arms)
- [x] [Faces of the Past](https://magiccards.info/query?q=!Faces+of+the+Past)
- [x] [Fatal Mutation](https://magiccards.info/query?q=!Fatal+Mutation)
- [x] [Fierce Empath](https://magiccards.info/query?q=!Fierce+Empath)
- [x] [Final Punishment](https://magiccards.info/query?q=!Final+Punishment)
- [x] [Force Bubble](https://magiccards.info/query?q=!Force+Bubble)
- [x] [Forgotten Ancient](https://magiccards.info/query?q=!Forgotten+Ancient)
- [x] [Form of the Dragon](https://magiccards.info/query?q=!Form+of+the+Dragon)
- [x] [Frontline Strategist](https://magiccards.info/query?q=!Frontline+Strategist)
- [x] [Frozen Solid](https://magiccards.info/query?q=!Frozen+Solid)
- [x] [Gilded Light](https://magiccards.info/query?q=!Gilded+Light)
- [x] [Goblin Brigand](https://magiccards.info/query?q=!Goblin+Brigand)
- [x] [Goblin Psychopath](https://magiccards.info/query?q=!Goblin+Psychopath)
- [x] [Goblin War Strike](https://magiccards.info/query?q=!Goblin+War+Strike)
- [x] [Goblin Warchief](https://magiccards.info/query?q=!Goblin+Warchief)
- [x] [Grip of Chaos](https://magiccards.info/query?q=!Grip+of+Chaos)
- [x] [Guilty Conscience](https://magiccards.info/query?q=!Guilty+Conscience)
- [x] [Hindering Touch](https://magiccards.info/query?q=!Hindering+Touch)
- [x] [Hunting Pack](https://magiccards.info/query?q=!Hunting+Pack)
- [x] [Karona's Zealot](https://magiccards.info/query?q=!Karona's+Zealot)
- [x] [Karona, False God](https://magiccards.info/query?q=!Karona,+False+God)
- [x] [Krosan Drover](https://magiccards.info/query?q=!Krosan+Drover)
- [x] [Krosan Warchief](https://magiccards.info/query?q=!Krosan+Warchief)
- [x] [Kurgadon](https://magiccards.info/query?q=!Kurgadon)
- [x] [Lethal Vapors](https://magiccards.info/query?q=!Lethal+Vapors)
- [x] [Lingering Death](https://magiccards.info/query?q=!Lingering+Death)
- [x] [Long-Term Plans](https://magiccards.info/query?q=!Long-Term+Plans)
- [x] [Mercurial Kite](https://magiccards.info/query?q=!Mercurial+Kite)
- [x] [Metamorphose](https://magiccards.info/query?q=!Metamorphose)
- [x] [Mind's Desire](https://magiccards.info/query?q=!Mind's+Desire)
- [x] [Mischievous Quanar](https://magiccards.info/query?q=!Mischievous+Quanar)
- [x] [Misguided Rage](https://magiccards.info/query?q=!Misguided+Rage)
- [x] [Mistform Warchief](https://magiccards.info/query?q=!Mistform+Warchief)
- [x] [Nefashu](https://magiccards.info/query?q=!Nefashu)
- [x] [Noble Templar](https://magiccards.info/query?q=!Noble+Templar)
- [x] [One with Nature](https://magiccards.info/query?q=!One+with+Nature)
- [x] [Parallel Thoughts](https://magiccards.info/query?q=!Parallel+Thoughts)
- [x] [Pemmin's Aura](https://magiccards.info/query?q=!Pemmin's+Aura)
- [x] [Primitive Etchings](https://magiccards.info/query?q=!Primitive+Etchings)
- [x] [Proteus Machine](https://magiccards.info/query?q=!Proteus+Machine)
- [x] [Putrid Raptor](https://magiccards.info/query?q=!Putrid+Raptor)
- [x] [Pyrostatic Pillar](https://magiccards.info/query?q=!Pyrostatic+Pillar)
- [x] [Rain of Blades](https://magiccards.info/query?q=!Rain+of+Blades)
- [x] [Raven Guild Initiate](https://magiccards.info/query?q=!Raven+Guild+Initiate)
- [x] [Raven Guild Master](https://magiccards.info/query?q=!Raven+Guild+Master)
- [x] [Reaping the Graves](https://magiccards.info/query?q=!Reaping+the+Graves)
- [x] [Recuperate](https://magiccards.info/query?q=!Recuperate)
- [x] [Reward the Faithful](https://magiccards.info/query?q=!Reward+the+Faithful)
- [x] [Riptide Survivor](https://magiccards.info/query?q=!Riptide+Survivor)
- [x] [Rock Jockey](https://magiccards.info/query?q=!Rock+Jockey)
- [x] [Root Elemental](https://magiccards.info/query?q=!Root+Elemental)
- [x] [Rush of Knowledge](https://magiccards.info/query?q=!Rush+of+Knowledge)
- [x] [Scattershot](https://magiccards.info/query?q=!Scattershot)
- [x] [Scornful Egotist](https://magiccards.info/query?q=!Scornful+Egotist)
- [x] [Shoreline Ranger](https://magiccards.info/query?q=!Shoreline+Ranger)
- [x] [Siege-Gang Commander](https://magiccards.info/query?q=!Siege-Gang+Commander)
- [x] [Silver Knight](https://magiccards.info/query?q=!Silver+Knight)
- [x] [Skirk Volcanist](https://magiccards.info/query?q=!Skirk+Volcanist)
- [x] [Skulltap](https://magiccards.info/query?q=!Skulltap)
- [x] [Sliver Overlord](https://magiccards.info/query?q=!Sliver+Overlord)
- [x] [Soul Collector](https://magiccards.info/query?q=!Soul+Collector)
- [x] [Spark Spray](https://magiccards.info/query?q=!Spark+Spray)
- [x] [Sprouting Vines](https://magiccards.info/query?q=!Sprouting+Vines)
- [x] [Stabilizer](https://magiccards.info/query?q=!Stabilizer)
- [x] [Stifle](https://magiccards.info/query?q=!Stifle)
- [x] [Sulfuric Vortex](https://magiccards.info/query?q=!Sulfuric+Vortex)
- [x] [Temple of the False God](https://magiccards.info/query?q=!Temple+of+the+False+God)
- [x] [Temporal Fissure](https://magiccards.info/query?q=!Temporal+Fissure)
- [x] [Tendrils of Agony](https://magiccards.info/query?q=!Tendrils+of+Agony)
- [x] [Thundercloud Elemental](https://magiccards.info/query?q=!Thundercloud+Elemental)
- [x] [Titanic Bulvox](https://magiccards.info/query?q=!Titanic+Bulvox)
- [x] [Torrent of Fire](https://magiccards.info/query?q=!Torrent+of+Fire)
- [x] [Trap Digger](https://magiccards.info/query?q=!Trap+Digger)
- [x] [Treetop Scout](https://magiccards.info/query?q=!Treetop+Scout)
- [x] [Twisted Abomination](https://magiccards.info/query?q=!Twisted+Abomination)
- [x] [Unburden](https://magiccards.info/query?q=!Unburden)
- [x] [Uncontrolled Infestation](https://magiccards.info/query?q=!Uncontrolled+Infestation)
- [x] [Undead Warchief](https://magiccards.info/query?q=!Undead+Warchief)
- [x] [Unspeakable Symbol](https://magiccards.info/query?q=!Unspeakable+Symbol)
- [x] [Upwelling](https://magiccards.info/query?q=!Upwelling)
- [x] [Vengeful Dead](https://magiccards.info/query?q=!Vengeful+Dead)
- [x] [Wing Shards](https://magiccards.info/query?q=!Wing+Shards)
- [x] [Wipe Clean](https://magiccards.info/query?q=!Wipe+Clean)
- [x] [Wirewood Guardian](https://magiccards.info/query?q=!Wirewood+Guardian)
- [x] [Wirewood Symbiote](https://magiccards.info/query?q=!Wirewood+Symbiote)
- [x] [Woodcloaker](https://magiccards.info/query?q=!Woodcloaker)
- [x] [Xantid Swarm](https://magiccards.info/query?q=!Xantid+Swarm)
- [x] [Zealous Inquisitor](https://magiccards.info/query?q=!Zealous+Inquisitor)
- [x] [Zombie Cutthroat](https://magiccards.info/query?q=!Zombie+Cutthroat)

**Comment by xenohedron** [comment]
Shortlist at the top is out of date - Rock Jockey and Stabilizer are implemented

**Comment by xenohedron** [comment]
Last card implemented in ff745d4
