### ISSUE TITLE
Wrong color replacement in BecomesCreature effects

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4905]
MTG rules 105.3:
> Effects may change an object’s color or give a color to a colorless object. **If an effect gives an 
object a new color, the new color replaces all previous colors the object** had (unless the effect said 
the object became that color “in addition” to its other colors). Effects may also make a colored 
object become colorless.

Example fix: 72314a9512ea787434bce4599af11d26777b5f5f

There many methods to check (search source by `case ColorChangingEffects_5`):
 * [x] FIXED: BecomesBlackZombieAdditionEffect.java
 * [ ] have problems: BecomesCreatureAllEffect.java
 * [x] FIXED: BecomesCreatureAttachedEffect.java
 * [ ] BecomesCreatureAttachedWithActivatedAbilityOrSpellEffect.java
 * [ ] BecomesCreatureSourceEffect.java
 * [ ] BecomesCreatureTargetEffect.java
 * [ ] BecomesFaceDownCreatureAllEffect.java
 * [ ] BecomesFaceDownCreatureEffect.java
 * [ ] ContinuousEffectImpl.java
 * [ ] DralnusCrusade.java
 * [ ] GrimoireOfTheDead.java
 * [ ] ImprisonedInTheMoon.java
 * [x] OK: LiegeOfTheTangle.java
 * [ ] LifeAndLimb.java
 * [ ] PolymorphistsJest.java
 * [ ] SarkhanTheDragonspeaker.java
 * [ ] SongOfTheDryads.java
 * [ ] TestamentOfFaith.java
