### ISSUE TITLE
MRD - Mirrodin set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4917]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/mirrodin

# Cards in set:
- [x] [AEther Spellbomb](https://magiccards.info/query?q=!AEther+Spellbomb)
- [x] [Alpha Myr](https://magiccards.info/query?q=!Alpha+Myr)
- [x] [Altar of Shadows](https://magiccards.info/query?q=!Altar+of+Shadows)
- [x] [Altar's Light](https://magiccards.info/query?q=!Altar's+Light)
- [x] [Ancient Den](https://magiccards.info/query?q=!Ancient+Den)
- [x] [Annul](https://magiccards.info/query?q=!Annul)
- [x] [Arc-Slogger](https://magiccards.info/query?q=!Arc-Slogger)
- [x] [Arrest](https://magiccards.info/query?q=!Arrest)
- [x] [Assert Authority](https://magiccards.info/query?q=!Assert+Authority)
- [x] [Atog](https://magiccards.info/query?q=!Atog)
- [x] [Auriok Bladewarden](https://magiccards.info/query?q=!Auriok+Bladewarden)
- [x] [Auriok Steelshaper](https://magiccards.info/query?q=!Auriok+Steelshaper)
- [x] [Auriok Transfixer](https://magiccards.info/query?q=!Auriok+Transfixer)
- [x] [Awe Strike](https://magiccards.info/query?q=!Awe+Strike)
- [x] [Banshee's Blade](https://magiccards.info/query?q=!Banshee's+Blade)
- [x] [Barter in Blood](https://magiccards.info/query?q=!Barter+in+Blood)
- [x] [Battlegrowth](https://magiccards.info/query?q=!Battlegrowth)
- [x] [Betrayal of Flesh](https://magiccards.info/query?q=!Betrayal+of+Flesh)
- [x] [Blinding Beam](https://magiccards.info/query?q=!Blinding+Beam)
- [x] [Blinkmoth Urn](https://magiccards.info/query?q=!Blinkmoth+Urn)
- [x] [Blinkmoth Well](https://magiccards.info/query?q=!Blinkmoth+Well)
- [x] [Bloodscent](https://magiccards.info/query?q=!Bloodscent)
- [x] [Bonesplitter](https://magiccards.info/query?q=!Bonesplitter)
- [x] [Bosh, Iron Golem](https://magiccards.info/query?q=!Bosh,+Iron+Golem)
- [x] [Bottle Gnomes](https://magiccards.info/query?q=!Bottle+Gnomes)
- [x] [Broodstar](https://magiccards.info/query?q=!Broodstar)
- [x] [Brown Ouphe](https://magiccards.info/query?q=!Brown+Ouphe)
- [x] [Cathodion](https://magiccards.info/query?q=!Cathodion)
- [x] [Chalice of the Void](https://magiccards.info/query?q=!Chalice+of+the+Void)
- [x] [Chimney Imp](https://magiccards.info/query?q=!Chimney+Imp)
- [x] [Chromatic Sphere](https://magiccards.info/query?q=!Chromatic+Sphere)
- [x] [Chrome Mox](https://magiccards.info/query?q=!Chrome+Mox)
- [x] [Clockwork Beetle](https://magiccards.info/query?q=!Clockwork+Beetle)
- [x] [Clockwork Condor](https://magiccards.info/query?q=!Clockwork+Condor)
- [x] [Clockwork Dragon](https://magiccards.info/query?q=!Clockwork+Dragon)
- [x] [Clockwork Vorrac](https://magiccards.info/query?q=!Clockwork+Vorrac)
- [x] [Cloudpost](https://magiccards.info/query?q=!Cloudpost)
- [x] [Cobalt Golem](https://magiccards.info/query?q=!Cobalt+Golem)
- [x] [Confusion in the Ranks](https://magiccards.info/query?q=!Confusion+in+the+Ranks)
- [x] [Consume Spirit](https://magiccards.info/query?q=!Consume+Spirit)
- [x] [Contaminated Bond](https://magiccards.info/query?q=!Contaminated+Bond)
- [x] [Copper Myr](https://magiccards.info/query?q=!Copper+Myr)
- [x] [Copperhoof Vorrac](https://magiccards.info/query?q=!Copperhoof+Vorrac)
- [x] [Creeping Mold](https://magiccards.info/query?q=!Creeping+Mold)
- [x] [Crystal Shard](https://magiccards.info/query?q=!Crystal+Shard)
- [x] [Culling Scales](https://magiccards.info/query?q=!Culling+Scales)
- [x] [Damping Matrix](https://magiccards.info/query?q=!Damping+Matrix)
- [x] [Dead-Iron Sledge](https://magiccards.info/query?q=!Dead-Iron+Sledge)
- [x] [Deconstruct](https://magiccards.info/query?q=!Deconstruct)
- [x] [Detonate](https://magiccards.info/query?q=!Detonate)
- [x] [Disarm](https://magiccards.info/query?q=!Disarm)
- [x] [Disciple of the Vault](https://magiccards.info/query?q=!Disciple+of+the+Vault)
- [x] [Domineer](https://magiccards.info/query?q=!Domineer)
- [x] [Dragon Blood](https://magiccards.info/query?q=!Dragon+Blood)
- [x] [Dream's Grip](https://magiccards.info/query?q=!Dream's+Grip)
- [x] [Dross Harvester](https://magiccards.info/query?q=!Dross+Harvester)
- [x] [Dross Prowler](https://magiccards.info/query?q=!Dross+Prowler)
- [x] [Dross Scorpion](https://magiccards.info/query?q=!Dross+Scorpion)
- [x] [Duplicant](https://magiccards.info/query?q=!Duplicant)
- [x] [Duskworker](https://magiccards.info/query?q=!Duskworker)
- [x] [Electrostatic Bolt](https://magiccards.info/query?q=!Electrostatic+Bolt)
- [x] [Elf Replica](https://magiccards.info/query?q=!Elf+Replica)
- [x] [Empyrial Plate](https://magiccards.info/query?q=!Empyrial+Plate)
- [x] [Extraplanar Lens](https://magiccards.info/query?q=!Extraplanar+Lens)
- [x] [Fabricate](https://magiccards.info/query?q=!Fabricate)
- [x] [Fangren Hunter](https://magiccards.info/query?q=!Fangren+Hunter)
- [x] [Farsight Mask](https://magiccards.info/query?q=!Farsight+Mask)
- [x] [Fatespinner](https://magiccards.info/query?q=!Fatespinner)
- [x] [Fiery Gambit](https://magiccards.info/query?q=!Fiery+Gambit)
- [x] [Fireshrieker](https://magiccards.info/query?q=!Fireshrieker)
- [x] [Fists of the Anvil](https://magiccards.info/query?q=!Fists+of+the+Anvil)
- [x] [Flayed Nim](https://magiccards.info/query?q=!Flayed+Nim)
- [ ] [Forest](https://magiccards.info/query?q=!Forest)
- [x] [Forge Armor](https://magiccards.info/query?q=!Forge+Armor)
- [x] [Fractured Loyalty](https://magiccards.info/query?q=!Fractured+Loyalty)
- [x] [Frogmite](https://magiccards.info/query?q=!Frogmite)
- [x] [Galvanic Key](https://magiccards.info/query?q=!Galvanic+Key)
- [x] [Gate to the AEther](https://magiccards.info/query?q=!Gate+to+the+AEther)
- [x] [Gilded Lotus](https://magiccards.info/query?q=!Gilded+Lotus)
- [x] [Glimmervoid](https://magiccards.info/query?q=!Glimmervoid)
- [x] [Glissa Sunseeker](https://magiccards.info/query?q=!Glissa+Sunseeker)
- [x] [Goblin Charbelcher](https://magiccards.info/query?q=!Goblin+Charbelcher)
- [x] [Goblin Dirigible](https://magiccards.info/query?q=!Goblin+Dirigible)
- [x] [Goblin Replica](https://magiccards.info/query?q=!Goblin+Replica)
- [x] [Goblin Striker](https://magiccards.info/query?q=!Goblin+Striker)
- [x] [Goblin War Wagon](https://magiccards.info/query?q=!Goblin+War+Wagon)
- [x] [Gold Myr](https://magiccards.info/query?q=!Gold+Myr)
- [x] [Golem-Skin Gauntlets](https://magiccards.info/query?q=!Golem-Skin+Gauntlets)
- [x] [Grab the Reins](https://magiccards.info/query?q=!Grab+the+Reins)
- [x] [Granite Shard](https://magiccards.info/query?q=!Granite+Shard)
- [x] [Great Furnace](https://magiccards.info/query?q=!Great+Furnace)
- [x] [Grid Monitor](https://magiccards.info/query?q=!Grid+Monitor)
- [x] [Grim Reminder](https://magiccards.info/query?q=!Grim+Reminder)
- [x] [Groffskithur](https://magiccards.info/query?q=!Groffskithur)
- [x] [Heartwood Shard](https://magiccards.info/query?q=!Heartwood+Shard)
- [x] [Hematite Golem](https://magiccards.info/query?q=!Hematite+Golem)
- [x] [Hum of the Radix](https://magiccards.info/query?q=!Hum+of+the+Radix)
- [x] [Icy Manipulator](https://magiccards.info/query?q=!Icy+Manipulator)
- [x] [Incite War](https://magiccards.info/query?q=!Incite+War)
- [x] [Inertia Bubble](https://magiccards.info/query?q=!Inertia+Bubble)
- [x] [Iron Myr](https://magiccards.info/query?q=!Iron+Myr)
- [x] [Irradiate](https://magiccards.info/query?q=!Irradiate)
- [ ] [Island](https://magiccards.info/query?q=!Island)
- [x] [Isochron Scepter](https://magiccards.info/query?q=!Isochron+Scepter)
- [x] [Jinxed Choker](https://magiccards.info/query?q=!Jinxed+Choker)
- [x] [Journey of Discovery](https://magiccards.info/query?q=!Journey+of+Discovery)
- [x] [Krark's Thumb](https://magiccards.info/query?q=!Krark's+Thumb)
- [x] [Krark-Clan Grunt](https://magiccards.info/query?q=!Krark-Clan+Grunt)
- [x] [Krark-Clan Shaman](https://magiccards.info/query?q=!Krark-Clan+Shaman)
- [x] [Leaden Myr](https://magiccards.info/query?q=!Leaden+Myr)
- [x] [Leonin Abunas](https://magiccards.info/query?q=!Leonin+Abunas)
- [x] [Leonin Bladetrap](https://magiccards.info/query?q=!Leonin+Bladetrap)
- [x] [Leonin Den-Guard](https://magiccards.info/query?q=!Leonin+Den-Guard)
- [x] [Leonin Elder](https://magiccards.info/query?q=!Leonin+Elder)
- [x] [Leonin Scimitar](https://magiccards.info/query?q=!Leonin+Scimitar)
- [x] [Leonin Skyhunter](https://magiccards.info/query?q=!Leonin+Skyhunter)
- [x] [Leonin Sun Standard](https://magiccards.info/query?q=!Leonin+Sun+Standard)
- [x] [Leveler](https://magiccards.info/query?q=!Leveler)
- [x] [Liar's Pendulum](https://magiccards.info/query?q=!Liar's+Pendulum)
- [x] [Lifespark Spellbomb](https://magiccards.info/query?q=!Lifespark+Spellbomb)
- [x] [Lightning Coils](https://magiccards.info/query?q=!Lightning+Coils)
- [x] [Lightning Greaves](https://magiccards.info/query?q=!Lightning+Greaves)
- [x] [Living Hive](https://magiccards.info/query?q=!Living+Hive)
- [x] [Lodestone Myr](https://magiccards.info/query?q=!Lodestone+Myr)
- [x] [Looming Hoverguard](https://magiccards.info/query?q=!Looming+Hoverguard)
- [x] [Loxodon Mender](https://magiccards.info/query?q=!Loxodon+Mender)
- [x] [Loxodon Peacekeeper](https://magiccards.info/query?q=!Loxodon+Peacekeeper)
- [x] [Loxodon Punisher](https://magiccards.info/query?q=!Loxodon+Punisher)
- [x] [Loxodon Warhammer](https://magiccards.info/query?q=!Loxodon+Warhammer)
- [x] [Lumengrid Augur](https://magiccards.info/query?q=!Lumengrid+Augur)
- [x] [Lumengrid Sentinel](https://magiccards.info/query?q=!Lumengrid+Sentinel)
- [x] [Lumengrid Warden](https://magiccards.info/query?q=!Lumengrid+Warden)
- [x] [Luminous Angel](https://magiccards.info/query?q=!Luminous+Angel)
- [x] [Malachite Golem](https://magiccards.info/query?q=!Malachite+Golem)
- [x] [March of the Machines](https://magiccards.info/query?q=!March+of+the+Machines)
- [x] [Mask of Memory](https://magiccards.info/query?q=!Mask+of+Memory)
- [x] [Mass Hysteria](https://magiccards.info/query?q=!Mass+Hysteria)
- [x] [Megatog](https://magiccards.info/query?q=!Megatog)
- [x] [Mesmeric Orb](https://magiccards.info/query?q=!Mesmeric+Orb)
- [x] [Mind's Eye](https://magiccards.info/query?q=!Mind's+Eye)
- [x] [Mindslaver](https://magiccards.info/query?q=!Mindslaver)
- [x] [Mindstorm Crown](https://magiccards.info/query?q=!Mindstorm+Crown)
- [ ] [Mirror Golem](https://magiccards.info/query?q=!Mirror+Golem)
- [x] [Molder Slug](https://magiccards.info/query?q=!Molder+Slug)
- [x] [Molten Rain](https://magiccards.info/query?q=!Molten+Rain)
- [x] [Moriok Scavenger](https://magiccards.info/query?q=!Moriok+Scavenger)
- [ ] [Mountain](https://magiccards.info/query?q=!Mountain)
- [ ] [Mourner's Shield](https://magiccards.info/query?q=!Mourner's+Shield)
- [x] [Myr Adapter](https://magiccards.info/query?q=!Myr+Adapter)
- [x] [Myr Enforcer](https://magiccards.info/query?q=!Myr+Enforcer)
- [x] [Myr Incubator](https://magiccards.info/query?q=!Myr+Incubator)
- [x] [Myr Mindservant](https://magiccards.info/query?q=!Myr+Mindservant)
- [x] [Myr Prototype](https://magiccards.info/query?q=!Myr+Prototype)
- [x] [Myr Retriever](https://magiccards.info/query?q=!Myr+Retriever)
- [x] [Necrogen Mists](https://magiccards.info/query?q=!Necrogen+Mists)
- [x] [Necrogen Spellbomb](https://magiccards.info/query?q=!Necrogen+Spellbomb)
- [x] [Needlebug](https://magiccards.info/query?q=!Needlebug)
- [x] [Neurok Familiar](https://magiccards.info/query?q=!Neurok+Familiar)
- [x] [Neurok Hoversail](https://magiccards.info/query?q=!Neurok+Hoversail)
- [x] [Neurok Spy](https://magiccards.info/query?q=!Neurok+Spy)
- [x] [Nightmare Lash](https://magiccards.info/query?q=!Nightmare+Lash)
- [x] [Nim Devourer](https://magiccards.info/query?q=!Nim+Devourer)
- [x] [Nim Lasher](https://magiccards.info/query?q=!Nim+Lasher)
- [x] [Nim Replica](https://magiccards.info/query?q=!Nim+Replica)
- [x] [Nim Shambler](https://magiccards.info/query?q=!Nim+Shambler)
- [x] [Nim Shrieker](https://magiccards.info/query?q=!Nim+Shrieker)
- [x] [Nuisance Engine](https://magiccards.info/query?q=!Nuisance+Engine)
- [x] [Oblivion Stone](https://magiccards.info/query?q=!Oblivion+Stone)
- [x] [Ogre Leadfoot](https://magiccards.info/query?q=!Ogre+Leadfoot)
- [x] [Omega Myr](https://magiccards.info/query?q=!Omega+Myr)
- [x] [One Dozen Eyes](https://magiccards.info/query?q=!One+Dozen+Eyes)
- [x] [Ornithopter](https://magiccards.info/query?q=!Ornithopter)
- [x] [Override](https://magiccards.info/query?q=!Override)
- [x] [Pearl Shard](https://magiccards.info/query?q=!Pearl+Shard)
- [x] [Pentavus](https://magiccards.info/query?q=!Pentavus)
- [x] [Pewter Golem](https://magiccards.info/query?q=!Pewter+Golem)
- [ ] [Plains](https://magiccards.info/query?q=!Plains)
- [x] [Plated Slagwurm](https://magiccards.info/query?q=!Plated+Slagwurm)
- [x] [Platinum Angel](https://magiccards.info/query?q=!Platinum+Angel)
- [x] [Power Conduit](https://magiccards.info/query?q=!Power+Conduit)
- [x] [Predator's Strike](https://magiccards.info/query?q=!Predator's+Strike)
- [x] [Promise of Power](https://magiccards.info/query?q=!Promise+of+Power)
- [x] [Proteus Staff](https://magiccards.info/query?q=!Proteus+Staff)
- [x] [Psychic Membrane](https://magiccards.info/query?q=!Psychic+Membrane)
- [x] [Psychogenic Probe](https://magiccards.info/query?q=!Psychogenic+Probe)
- [x] [Pyrite Spellbomb](https://magiccards.info/query?q=!Pyrite+Spellbomb)
- [x] [Quicksilver Elemental](https://magiccards.info/query?q=!Quicksilver+Elemental)
- [x] [Quicksilver Fountain](https://magiccards.info/query?q=!Quicksilver+Fountain)
- [x] [Raise the Alarm](https://magiccards.info/query?q=!Raise+the+Alarm)
- [x] [Razor Barrier](https://magiccards.info/query?q=!Razor+Barrier)
- [x] [Regress](https://magiccards.info/query?q=!Regress)
- [x] [Reiver Demon](https://magiccards.info/query?q=!Reiver+Demon)
- [x] [Relic Bane](https://magiccards.info/query?q=!Relic+Bane)
- [x] [Roar of the Kha](https://magiccards.info/query?q=!Roar+of+the+Kha)
- [x] [Rule of Law](https://magiccards.info/query?q=!Rule+of+Law)
- [x] [Rust Elemental](https://magiccards.info/query?q=!Rust+Elemental)
- [x] [Rustmouth Ogre](https://magiccards.info/query?q=!Rustmouth+Ogre)
- [x] [Rustspore Ram](https://magiccards.info/query?q=!Rustspore+Ram)
- [x] [Scale of Chiss-Goria](https://magiccards.info/query?q=!Scale+of+Chiss-Goria)
- [x] [Scrabbling Claws](https://magiccards.info/query?q=!Scrabbling+Claws)
- [x] [Sculpting Steel](https://magiccards.info/query?q=!Sculpting+Steel)
- [x] [Scythe of the Wretched](https://magiccards.info/query?q=!Scythe+of+the+Wretched)
- [x] [Seat of the Synod](https://magiccards.info/query?q=!Seat+of+the+Synod)
- [x] [Second Sunrise](https://magiccards.info/query?q=!Second+Sunrise)
- [x] [Seething Song](https://magiccards.info/query?q=!Seething+Song)
- [x] [Serum Tank](https://magiccards.info/query?q=!Serum+Tank)
- [x] [Shared Fate](https://magiccards.info/query?q=!Shared+Fate)
- [x] [Shatter](https://magiccards.info/query?q=!Shatter)
- [x] [Shrapnel Blast](https://magiccards.info/query?q=!Shrapnel+Blast)
- [x] [Silver Myr](https://magiccards.info/query?q=!Silver+Myr)
- [x] [Skeleton Shard](https://magiccards.info/query?q=!Skeleton+Shard)
- [x] [Skyhunter Cub](https://magiccards.info/query?q=!Skyhunter+Cub)
- [x] [Skyhunter Patrol](https://magiccards.info/query?q=!Skyhunter+Patrol)
- [x] [Slagwurm Armor](https://magiccards.info/query?q=!Slagwurm+Armor)
- [x] [Slith Ascendant](https://magiccards.info/query?q=!Slith+Ascendant)
- [x] [Slith Bloodletter](https://magiccards.info/query?q=!Slith+Bloodletter)
- [x] [Slith Firewalker](https://magiccards.info/query?q=!Slith+Firewalker)
- [x] [Slith Predator](https://magiccards.info/query?q=!Slith+Predator)
- [x] [Slith Strider](https://magiccards.info/query?q=!Slith+Strider)
- [x] [Solar Tide](https://magiccards.info/query?q=!Solar+Tide)
- [x] [Soldier Replica](https://magiccards.info/query?q=!Soldier+Replica)
- [x] [Solemn Simulacrum](https://magiccards.info/query?q=!Solemn+Simulacrum)
- [x] [Somber Hoverguard](https://magiccards.info/query?q=!Somber+Hoverguard)
- [x] [Soul Foundry](https://magiccards.info/query?q=!Soul+Foundry)
- [x] [Soul Nova](https://magiccards.info/query?q=!Soul+Nova)
- [x] [Spellweaver Helix](https://magiccards.info/query?q=!Spellweaver+Helix)
- [x] [Sphere of Purity](https://magiccards.info/query?q=!Sphere+of+Purity)
- [x] [Spikeshot Goblin](https://magiccards.info/query?q=!Spikeshot+Goblin)
- [x] [Spoils of the Vault](https://magiccards.info/query?q=!Spoils+of+the+Vault)
- [x] [Stalking Stones](https://magiccards.info/query?q=!Stalking+Stones)
- [x] [Steel Wall](https://magiccards.info/query?q=!Steel+Wall)
- [x] [Sun Droplet](https://magiccards.info/query?q=!Sun+Droplet)
- [x] [Sunbeam Spellbomb](https://magiccards.info/query?q=!Sunbeam+Spellbomb)
- [ ] [Swamp](https://magiccards.info/query?q=!Swamp)
- [x] [Sword of Kaldra](https://magiccards.info/query?q=!Sword+of+Kaldra)
- [x] [Sylvan Scrying](https://magiccards.info/query?q=!Sylvan+Scrying)
- [x] [Synod Sanctum](https://magiccards.info/query?q=!Synod+Sanctum)
- [x] [Taj-Nar Swordsmith](https://magiccards.info/query?q=!Taj-Nar+Swordsmith)
- [x] [Talisman of Dominance](https://magiccards.info/query?q=!Talisman+of+Dominance)
- [x] [Talisman of Impulse](https://magiccards.info/query?q=!Talisman+of+Impulse)
- [x] [Talisman of Indulgence](https://magiccards.info/query?q=!Talisman+of+Indulgence)
- [x] [Talisman of Progress](https://magiccards.info/query?q=!Talisman+of+Progress)
- [x] [Talisman of Unity](https://magiccards.info/query?q=!Talisman+of+Unity)
- [x] [Tanglebloom](https://magiccards.info/query?q=!Tanglebloom)
- [x] [Tangleroot](https://magiccards.info/query?q=!Tangleroot)
- [x] [Tel-Jilad Archers](https://magiccards.info/query?q=!Tel-Jilad+Archers)
- [x] [Tel-Jilad Chosen](https://magiccards.info/query?q=!Tel-Jilad+Chosen)
- [x] [Tel-Jilad Exile](https://magiccards.info/query?q=!Tel-Jilad+Exile)
- [x] [Tel-Jilad Stylus](https://magiccards.info/query?q=!Tel-Jilad+Stylus)
- [x] [Tempest of Light](https://magiccards.info/query?q=!Tempest+of+Light)
- [x] [Temporal Cascade](https://magiccards.info/query?q=!Temporal+Cascade)
- [x] [Terror](https://magiccards.info/query?q=!Terror)
- [x] [Thirst for Knowledge](https://magiccards.info/query?q=!Thirst+for+Knowledge)
- [x] [Thought Prison](https://magiccards.info/query?q=!Thought+Prison)
- [x] [Thoughtcast](https://magiccards.info/query?q=!Thoughtcast)
- [x] [Timesifter](https://magiccards.info/query?q=!Timesifter)
- [x] [Titanium Golem](https://magiccards.info/query?q=!Titanium+Golem)
- [x] [Tooth and Nail](https://magiccards.info/query?q=!Tooth+and+Nail)
- [x] [Tooth of Chiss-Goria](https://magiccards.info/query?q=!Tooth+of+Chiss-Goria)
- [x] [Tower of Champions](https://magiccards.info/query?q=!Tower+of+Champions)
- [x] [Tower of Eons](https://magiccards.info/query?q=!Tower+of+Eons)
- [x] [Tower of Fortunes](https://magiccards.info/query?q=!Tower+of+Fortunes)
- [x] [Tower of Murmurs](https://magiccards.info/query?q=!Tower+of+Murmurs)
- [x] [Trash for Treasure](https://magiccards.info/query?q=!Trash+for+Treasure)
- [x] [Tree of Tales](https://magiccards.info/query?q=!Tree+of+Tales)
- [x] [Triskelion](https://magiccards.info/query?q=!Triskelion)
- [x] [Troll Ascetic](https://magiccards.info/query?q=!Troll+Ascetic)
- [x] [Trolls of Tel-Jilad](https://magiccards.info/query?q=!Trolls+of+Tel-Jilad)
- [x] [Turn to Dust](https://magiccards.info/query?q=!Turn+to+Dust)
- [x] [Vault of Whispers](https://magiccards.info/query?q=!Vault+of+Whispers)
- [x] [Vedalken Archmage](https://magiccards.info/query?q=!Vedalken+Archmage)
- [x] [Vermiculos](https://magiccards.info/query?q=!Vermiculos)
- [x] [Viridian Joiner](https://magiccards.info/query?q=!Viridian+Joiner)
- [x] [Viridian Longbow](https://magiccards.info/query?q=!Viridian+Longbow)
- [x] [Viridian Shaman](https://magiccards.info/query?q=!Viridian+Shaman)
- [x] [Vorrac Battlehorns](https://magiccards.info/query?q=!Vorrac+Battlehorns)
- [x] [Vulshok Battlegear](https://magiccards.info/query?q=!Vulshok+Battlegear)
- [x] [Vulshok Battlemaster](https://magiccards.info/query?q=!Vulshok+Battlemaster)
- [x] [Vulshok Berserker](https://magiccards.info/query?q=!Vulshok+Berserker)
- [x] [Vulshok Gauntlets](https://magiccards.info/query?q=!Vulshok+Gauntlets)
- [x] [Wail of the Nim](https://magiccards.info/query?q=!Wail+of+the+Nim)
- [x] [Wall of Blood](https://magiccards.info/query?q=!Wall+of+Blood)
- [x] [Wanderguard Sentry](https://magiccards.info/query?q=!Wanderguard+Sentry)
- [x] [War Elemental](https://magiccards.info/query?q=!War+Elemental)
- [x] [Welding Jar](https://magiccards.info/query?q=!Welding+Jar)
- [x] [Wizard Replica](https://magiccards.info/query?q=!Wizard+Replica)
- [x] [Woebearer](https://magiccards.info/query?q=!Woebearer)
- [x] [Worldslayer](https://magiccards.info/query?q=!Worldslayer)
- [x] [Wrench Mind](https://magiccards.info/query?q=!Wrench+Mind)
- [x] [Wurmskin Forger](https://magiccards.info/query?q=!Wurmskin+Forger)
- [x] [Yotian Soldier](https://magiccards.info/query?q=!Yotian+Soldier)

**Comment by NoahGleason** [comment]
Mourner's Shield (#5047) and Mirror Golem (#5046) have been merged so Mirrodin is now fully implemented!
