### ISSUE TITLE
DST - Darksteel set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4918]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/darksteel

# Cards in set:
- [x] [AEther Snap](https://magiccards.info/query?q=!AEther+Snap)
- [x] [AEther Vial](https://magiccards.info/query?q=!AEther+Vial)
- [x] [Ageless Entity](https://magiccards.info/query?q=!Ageless+Entity)
- [x] [Angel's Feather](https://magiccards.info/query?q=!Angel's+Feather)
- [x] [Arcane Spyglass](https://magiccards.info/query?q=!Arcane+Spyglass)
- [x] [Arcbound Bruiser](https://magiccards.info/query?q=!Arcbound+Bruiser)
- [x] [Arcbound Crusher](https://magiccards.info/query?q=!Arcbound+Crusher)
- [x] [Arcbound Fiend](https://magiccards.info/query?q=!Arcbound+Fiend)
- [x] [Arcbound Hybrid](https://magiccards.info/query?q=!Arcbound+Hybrid)
- [x] [Arcbound Lancer](https://magiccards.info/query?q=!Arcbound+Lancer)
- [x] [Arcbound Overseer](https://magiccards.info/query?q=!Arcbound+Overseer)
- [x] [Arcbound Ravager](https://magiccards.info/query?q=!Arcbound+Ravager)
- [x] [Arcbound Reclaimer](https://magiccards.info/query?q=!Arcbound+Reclaimer)
- [x] [Arcbound Slith](https://magiccards.info/query?q=!Arcbound+Slith)
- [x] [Arcbound Stinger](https://magiccards.info/query?q=!Arcbound+Stinger)
- [x] [Arcbound Worker](https://magiccards.info/query?q=!Arcbound+Worker)
- [x] [Auriok Glaivemaster](https://magiccards.info/query?q=!Auriok+Glaivemaster)
- [x] [Auriok Siege Sled](https://magiccards.info/query?q=!Auriok+Siege+Sled)
- [x] [Barbed Lightning](https://magiccards.info/query?q=!Barbed+Lightning)
- [x] [Blinkmoth Nexus](https://magiccards.info/query?q=!Blinkmoth+Nexus)
- [x] [Burden of Greed](https://magiccards.info/query?q=!Burden+of+Greed)
- [x] [Carry Away](https://magiccards.info/query?q=!Carry+Away)
- [x] [Chimeric Egg](https://magiccards.info/query?q=!Chimeric+Egg)
- [x] [Chittering Rats](https://magiccards.info/query?q=!Chittering+Rats)
- [x] [Chromescale Drake](https://magiccards.info/query?q=!Chromescale+Drake)
- [x] [Coretapper](https://magiccards.info/query?q=!Coretapper)
- [x] [Crazed Goblin](https://magiccards.info/query?q=!Crazed+Goblin)
- [x] [Darksteel Brute](https://magiccards.info/query?q=!Darksteel+Brute)
- [x] [Darksteel Citadel](https://magiccards.info/query?q=!Darksteel+Citadel)
- [x] [Darksteel Colossus](https://magiccards.info/query?q=!Darksteel+Colossus)
- [x] [Darksteel Forge](https://magiccards.info/query?q=!Darksteel+Forge)
- [x] [Darksteel Gargoyle](https://magiccards.info/query?q=!Darksteel+Gargoyle)
- [x] [Darksteel Ingot](https://magiccards.info/query?q=!Darksteel+Ingot)
- [x] [Darksteel Pendant](https://magiccards.info/query?q=!Darksteel+Pendant)
- [x] [Darksteel Reactor](https://magiccards.info/query?q=!Darksteel+Reactor)
- [x] [Death Cloud](https://magiccards.info/query?q=!Death+Cloud)
- [x] [Death-Mask Duplicant](https://magiccards.info/query?q=!Death-Mask+Duplicant)
- [x] [Demon's Horn](https://magiccards.info/query?q=!Demon's+Horn)
- [x] [Dismantle](https://magiccards.info/query?q=!Dismantle)
- [x] [Dragon's Claw](https://magiccards.info/query?q=!Dragon's+Claw)
- [x] [Drill-Skimmer](https://magiccards.info/query?q=!Drill-Skimmer)
- [x] [Drooling Ogre](https://magiccards.info/query?q=!Drooling+Ogre)
- [x] [Dross Golem](https://magiccards.info/query?q=!Dross+Golem)
- [x] [Eater of Days](https://magiccards.info/query?q=!Eater+of+Days)
- [x] [Echoing Calm](https://magiccards.info/query?q=!Echoing+Calm)
- [x] [Echoing Courage](https://magiccards.info/query?q=!Echoing+Courage)
- [x] [Echoing Decay](https://magiccards.info/query?q=!Echoing+Decay)
- [x] [Echoing Ruin](https://magiccards.info/query?q=!Echoing+Ruin)
- [x] [Echoing Truth](https://magiccards.info/query?q=!Echoing+Truth)
- [x] [Emissary of Despair](https://magiccards.info/query?q=!Emissary+of+Despair)
- [x] [Emissary of Hope](https://magiccards.info/query?q=!Emissary+of+Hope)
- [x] [Essence Drain](https://magiccards.info/query?q=!Essence+Drain)
- [x] [Fangren Firstborn](https://magiccards.info/query?q=!Fangren+Firstborn)
- [x] [Fireball](https://magiccards.info/query?q=!Fireball)
- [x] [Flamebreak](https://magiccards.info/query?q=!Flamebreak)
- [x] [Furnace Dragon](https://magiccards.info/query?q=!Furnace+Dragon)
- [x] [Gemini Engine](https://magiccards.info/query?q=!Gemini+Engine)
- [x] [Genesis Chamber](https://magiccards.info/query?q=!Genesis+Chamber)
- [x] [Geth's Grimoire](https://magiccards.info/query?q=!Geth's+Grimoire)
- [x] [Goblin Archaeologist](https://magiccards.info/query?q=!Goblin+Archaeologist)
- [x] [Greater Harvester](https://magiccards.info/query?q=!Greater+Harvester)
- [x] [Grimclaw Bats](https://magiccards.info/query?q=!Grimclaw+Bats)
- [x] [Hallow](https://magiccards.info/query?q=!Hallow)
- [x] [Heartseeker](https://magiccards.info/query?q=!Heartseeker)
- [x] [Hoverguard Observer](https://magiccards.info/query?q=!Hoverguard+Observer)
- [x] [Hunger of the Nim](https://magiccards.info/query?q=!Hunger+of+the+Nim)
- [x] [Infested Roothold](https://magiccards.info/query?q=!Infested+Roothold)
- [x] [Inflame](https://magiccards.info/query?q=!Inflame)
- [x] [Juggernaut](https://magiccards.info/query?q=!Juggernaut)
- [x] [Karstoderm](https://magiccards.info/query?q=!Karstoderm)
- [x] [Kraken's Eye](https://magiccards.info/query?q=!Kraken's+Eye)
- [x] [Krark-Clan Stoker](https://magiccards.info/query?q=!Krark-Clan+Stoker)
- [x] [Last Word](https://magiccards.info/query?q=!Last+Word)
- [x] [Leonin Battlemage](https://magiccards.info/query?q=!Leonin+Battlemage)
- [x] [Leonin Bola](https://magiccards.info/query?q=!Leonin+Bola)
- [x] [Leonin Shikari](https://magiccards.info/query?q=!Leonin+Shikari)
- [x] [Lich's Tomb](https://magiccards.info/query?q=!Lich's+Tomb)
- [x] [Loxodon Mystic](https://magiccards.info/query?q=!Loxodon+Mystic)
- [x] [Machinate](https://magiccards.info/query?q=!Machinate)
- [x] [Magnetic Flux](https://magiccards.info/query?q=!Magnetic+Flux)
- [x] [Memnarch](https://magiccards.info/query?q=!Memnarch)
- [x] [Mephitic Ooze](https://magiccards.info/query?q=!Mephitic+Ooze)
- [x] [Metal Fatigue](https://magiccards.info/query?q=!Metal+Fatigue)
- [x] [Mirrodin's Core](https://magiccards.info/query?q=!Mirrodin's+Core)
- [x] [Murderous Spoils](https://magiccards.info/query?q=!Murderous+Spoils)
- [x] [Mycosynth Lattice](https://magiccards.info/query?q=!Mycosynth+Lattice)
- [x] [Myr Landshaper](https://magiccards.info/query?q=!Myr+Landshaper)
- [x] [Myr Matrix](https://magiccards.info/query?q=!Myr+Matrix)
- [x] [Myr Moonvessel](https://magiccards.info/query?q=!Myr+Moonvessel)
- [x] [Nemesis Mask](https://magiccards.info/query?q=!Nemesis+Mask)
- [x] [Neurok Prodigy](https://magiccards.info/query?q=!Neurok+Prodigy)
- [x] [Neurok Transmuter](https://magiccards.info/query?q=!Neurok+Transmuter)
- [x] [Nim Abomination](https://magiccards.info/query?q=!Nim+Abomination)
- [x] [Nourish](https://magiccards.info/query?q=!Nourish)
- [x] [Oxidda Golem](https://magiccards.info/query?q=!Oxidda+Golem)
- [x] [Oxidize](https://magiccards.info/query?q=!Oxidize)
- [x] [Panoptic Mirror](https://magiccards.info/query?q=!Panoptic+Mirror)
- [x] [Pristine Angel](https://magiccards.info/query?q=!Pristine+Angel)
- [x] [Psychic Overload](https://magiccards.info/query?q=!Psychic+Overload)
- [x] [Pteron Ghost](https://magiccards.info/query?q=!Pteron+Ghost)
- [x] [Pulse of the Dross](https://magiccards.info/query?q=!Pulse+of+the+Dross)
- [x] [Pulse of the Fields](https://magiccards.info/query?q=!Pulse+of+the+Fields)
- [x] [Pulse of the Forge](https://magiccards.info/query?q=!Pulse+of+the+Forge)
- [x] [Pulse of the Grid](https://magiccards.info/query?q=!Pulse+of+the+Grid)
- [x] [Pulse of the Tangle](https://magiccards.info/query?q=!Pulse+of+the+Tangle)
- [x] [Purge](https://magiccards.info/query?q=!Purge)
- [x] [Quicksilver Behemoth](https://magiccards.info/query?q=!Quicksilver+Behemoth)
- [x] [Razor Golem](https://magiccards.info/query?q=!Razor+Golem)
- [x] [Reap and Sow](https://magiccards.info/query?q=!Reap+and+Sow)
- [x] [Rebuking Ceremony](https://magiccards.info/query?q=!Rebuking+Ceremony)
- [x] [Reshape](https://magiccards.info/query?q=!Reshape)
- [x] [Retract](https://magiccards.info/query?q=!Retract)
- [x] [Ritual of Restoration](https://magiccards.info/query?q=!Ritual+of+Restoration)
- [x] [Roaring Slagwurm](https://magiccards.info/query?q=!Roaring+Slagwurm)
- [x] [Savage Beating](https://magiccards.info/query?q=!Savage+Beating)
- [x] [Scavenging Scarab](https://magiccards.info/query?q=!Scavenging+Scarab)
- [x] [Screams from Within](https://magiccards.info/query?q=!Screams+from+Within)
- [x] [Scrounge](https://magiccards.info/query?q=!Scrounge)
- [x] [Second Sight](https://magiccards.info/query?q=!Second+Sight)
- [x] [Serum Powder](https://magiccards.info/query?q=!Serum+Powder)
- [x] [Shield of Kaldra](https://magiccards.info/query?q=!Shield+of+Kaldra)
- [x] [Shriveling Rot](https://magiccards.info/query?q=!Shriveling+Rot)
- [x] [Shunt](https://magiccards.info/query?q=!Shunt)
- [x] [Skullclamp](https://magiccards.info/query?q=!Skullclamp)
- [x] [Slobad, Goblin Tinkerer](https://magiccards.info/query?q=!Slobad,+Goblin+Tinkerer)
- [x] [Soulscour](https://magiccards.info/query?q=!Soulscour)
- [x] [Spawning Pit](https://magiccards.info/query?q=!Spawning+Pit)
- [x] [Specter's Shroud](https://magiccards.info/query?q=!Specter's+Shroud)
- [x] [Spellbinder](https://magiccards.info/query?q=!Spellbinder)
- [x] [Spincrusher](https://magiccards.info/query?q=!Spincrusher)
- [x] [Spire Golem](https://magiccards.info/query?q=!Spire+Golem)
- [x] [Stand Together](https://magiccards.info/query?q=!Stand+Together)
- [x] [Steelshaper Apprentice](https://magiccards.info/query?q=!Steelshaper+Apprentice)
- [x] [Stir the Pride](https://magiccards.info/query?q=!Stir+the+Pride)
- [x] [Sundering Titan](https://magiccards.info/query?q=!Sundering+Titan)
- [x] [Surestrike Trident](https://magiccards.info/query?q=!Surestrike+Trident)
- [x] [Sword of Fire and Ice](https://magiccards.info/query?q=!Sword+of+Fire+and+Ice)
- [x] [Sword of Light and Shadow](https://magiccards.info/query?q=!Sword+of+Light+and+Shadow)
- [x] [Synod Artificer](https://magiccards.info/query?q=!Synod+Artificer)
- [x] [Talon of Pain](https://magiccards.info/query?q=!Talon+of+Pain)
- [x] [Tangle Golem](https://magiccards.info/query?q=!Tangle+Golem)
- [x] [Tangle Spider](https://magiccards.info/query?q=!Tangle+Spider)
- [x] [Tanglewalker](https://magiccards.info/query?q=!Tanglewalker)
- [x] [Tears of Rage](https://magiccards.info/query?q=!Tears+of+Rage)
- [x] [Tel-Jilad Outrider](https://magiccards.info/query?q=!Tel-Jilad+Outrider)
- [x] [Tel-Jilad Wolf](https://magiccards.info/query?q=!Tel-Jilad+Wolf)
- [x] [Test of Faith](https://magiccards.info/query?q=!Test+of+Faith)
- [x] [Thought Dissector](https://magiccards.info/query?q=!Thought+Dissector)
- [x] [Thunderstaff](https://magiccards.info/query?q=!Thunderstaff)
- [x] [Trinisphere](https://magiccards.info/query?q=!Trinisphere)
- [x] [Turn the Tables](https://magiccards.info/query?q=!Turn+the+Tables)
- [x] [Unforge](https://magiccards.info/query?q=!Unforge)
- [x] [Ur-Golem's Eye](https://magiccards.info/query?q=!Ur-Golem's+Eye)
- [x] [Vedalken Engineer](https://magiccards.info/query?q=!Vedalken+Engineer)
- [x] [Vex](https://magiccards.info/query?q=!Vex)
- [x] [Viridian Acolyte](https://magiccards.info/query?q=!Viridian+Acolyte)
- [x] [Viridian Zealot](https://magiccards.info/query?q=!Viridian+Zealot)
- [x] [Voltaic Construct](https://magiccards.info/query?q=!Voltaic+Construct)
- [x] [Vulshok Morningstar](https://magiccards.info/query?q=!Vulshok+Morningstar)
- [x] [Vulshok War Boar](https://magiccards.info/query?q=!Vulshok+War+Boar)
- [x] [Wand of the Elements](https://magiccards.info/query?q=!Wand+of+the+Elements)
- [x] [Well of Lost Dreams](https://magiccards.info/query?q=!Well+of+Lost+Dreams)
- [x] [Whispersilk Cloak](https://magiccards.info/query?q=!Whispersilk+Cloak)
- [x] [Wirefly Hive](https://magiccards.info/query?q=!Wirefly+Hive)
- [x] [Wurm's Tooth](https://magiccards.info/query?q=!Wurm's+Tooth)

**Comment by NoahGleason** [comment]
Neurok Transmuter has been implemented (#5049)

**Comment by NoahGleason** [comment]
Thought Dissector has been implemented (#5048) so Darksteel is now fully implemented!
