### ISSUE TITLE
5DN - Fifth Dawn set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4919]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/fifth-dawn

# Unimplemented cards

37|[Spectral Shift](https://magiccards.info/query?q=!Spectral+Shift)

# Cards in set:
- [x] [Abuna's Chant](https://magiccards.info/query?q=!Abuna's+Chant)
- [x] [Acquire](https://magiccards.info/query?q=!Acquire)
- [x] [Advanced Hoverguard](https://magiccards.info/query?q=!Advanced+Hoverguard)
- [x] [All Suns' Dawn](https://magiccards.info/query?q=!All+Suns'+Dawn)
- [x] [Anodet Lurker](https://magiccards.info/query?q=!Anodet+Lurker)
- [x] [Arachnoid](https://magiccards.info/query?q=!Arachnoid)
- [x] [Arcbound Wanderer](https://magiccards.info/query?q=!Arcbound+Wanderer)
- [x] [Armed Response](https://magiccards.info/query?q=!Armed+Response)
- [x] [Artificer's Intuition](https://magiccards.info/query?q=!Artificer's+Intuition)
- [x] [Auriok Champion](https://magiccards.info/query?q=!Auriok+Champion)
- [x] [Auriok Salvagers](https://magiccards.info/query?q=!Auriok+Salvagers)
- [x] [Auriok Windwalker](https://magiccards.info/query?q=!Auriok+Windwalker)
- [x] [Avarice Totem](https://magiccards.info/query?q=!Avarice+Totem)
- [x] [Baton of Courage](https://magiccards.info/query?q=!Baton+of+Courage)
- [x] [Battered Golem](https://magiccards.info/query?q=!Battered+Golem)
- [x] [Beacon of Creation](https://magiccards.info/query?q=!Beacon+of+Creation)
- [x] [Beacon of Destruction](https://magiccards.info/query?q=!Beacon+of+Destruction)
- [x] [Beacon of Immortality](https://magiccards.info/query?q=!Beacon+of+Immortality)
- [x] [Beacon of Tomorrows](https://magiccards.info/query?q=!Beacon+of+Tomorrows)
- [x] [Beacon of Unrest](https://magiccards.info/query?q=!Beacon+of+Unrest)
- [x] [Blasting Station](https://magiccards.info/query?q=!Blasting+Station)
- [x] [Blind Creeper](https://magiccards.info/query?q=!Blind+Creeper)
- [x] [Blinkmoth Infusion](https://magiccards.info/query?q=!Blinkmoth+Infusion)
- [x] [Bringer of the Black Dawn](https://magiccards.info/query?q=!Bringer+of+the+Black+Dawn)
- [x] [Bringer of the Blue Dawn](https://magiccards.info/query?q=!Bringer+of+the+Blue+Dawn)
- [x] [Bringer of the Green Dawn](https://magiccards.info/query?q=!Bringer+of+the+Green+Dawn)
- [x] [Bringer of the Red Dawn](https://magiccards.info/query?q=!Bringer+of+the+Red+Dawn)
- [x] [Bringer of the White Dawn](https://magiccards.info/query?q=!Bringer+of+the+White+Dawn)
- [x] [Cackling Imp](https://magiccards.info/query?q=!Cackling+Imp)
- [x] [Channel the Suns](https://magiccards.info/query?q=!Channel+the+Suns)
- [x] [Chimeric Coils](https://magiccards.info/query?q=!Chimeric+Coils)
- [x] [Circle of Protection: Artifacts](https://magiccards.info/query?q=!Circle+of+Protection:+Artifacts)
- [x] [Clearwater Goblet](https://magiccards.info/query?q=!Clearwater+Goblet)
- [x] [Clock of Omens](https://magiccards.info/query?q=!Clock+of+Omens)
- [x] [Composite Golem](https://magiccards.info/query?q=!Composite+Golem)
- [x] [Condescend](https://magiccards.info/query?q=!Condescend)
- [x] [Conjurer's Bauble](https://magiccards.info/query?q=!Conjurer's+Bauble)
- [x] [Cosmic Larva](https://magiccards.info/query?q=!Cosmic+Larva)
- [x] [Cranial Plating](https://magiccards.info/query?q=!Cranial+Plating)
- [x] [Crucible of Worlds](https://magiccards.info/query?q=!Crucible+of+Worlds)
- [x] [Dawn's Reflection](https://magiccards.info/query?q=!Dawn's+Reflection)
- [x] [Desecration Elemental](https://magiccards.info/query?q=!Desecration+Elemental)
- [x] [Devour in Shadow](https://magiccards.info/query?q=!Devour+in+Shadow)
- [x] [Disruption Aura](https://magiccards.info/query?q=!Disruption+Aura)
- [x] [Door to Nothingness](https://magiccards.info/query?q=!Door+to+Nothingness)
- [x] [Doubling Cube](https://magiccards.info/query?q=!Doubling+Cube)
- [x] [Dross Crocodile](https://magiccards.info/query?q=!Dross+Crocodile)
- [x] [Early Frost](https://magiccards.info/query?q=!Early+Frost)
- [x] [Ebon Drake](https://magiccards.info/query?q=!Ebon+Drake)
- [x] [Endless Whispers](https://magiccards.info/query?q=!Endless+Whispers)
- [x] [Energy Chamber](https://magiccards.info/query?q=!Energy+Chamber)
- [x] [Engineered Explosives](https://magiccards.info/query?q=!Engineered+Explosives)
- [x] [Ensouled Scimitar](https://magiccards.info/query?q=!Ensouled+Scimitar)
- [x] [Eon Hub](https://magiccards.info/query?q=!Eon+Hub)
- [x] [Etched Oracle](https://magiccards.info/query?q=!Etched+Oracle)
- [x] [Eternal Witness](https://magiccards.info/query?q=!Eternal+Witness)
- [x] [Eyes of the Watcher](https://magiccards.info/query?q=!Eyes+of+the+Watcher)
- [x] [Fangren Pathcutter](https://magiccards.info/query?q=!Fangren+Pathcutter)
- [x] [Feedback Bolt](https://magiccards.info/query?q=!Feedback+Bolt)
- [x] [Ferocious Charge](https://magiccards.info/query?q=!Ferocious+Charge)
- [x] [Ferropede](https://magiccards.info/query?q=!Ferropede)
- [x] [Fill with Fright](https://magiccards.info/query?q=!Fill+with+Fright)
- [x] [Fist of Suns](https://magiccards.info/query?q=!Fist+of+Suns)
- [x] [Fleshgrafter](https://magiccards.info/query?q=!Fleshgrafter)
- [x] [Fold into AEther](https://magiccards.info/query?q=!Fold+into+AEther)
- [x] [Furnace Whelp](https://magiccards.info/query?q=!Furnace+Whelp)
- [x] [Gemstone Array](https://magiccards.info/query?q=!Gemstone+Array)
- [x] [Goblin Brawler](https://magiccards.info/query?q=!Goblin+Brawler)
- [x] [Goblin Cannon](https://magiccards.info/query?q=!Goblin+Cannon)
- [x] [Grafted Wargear](https://magiccards.info/query?q=!Grafted+Wargear)
- [x] [Granulate](https://magiccards.info/query?q=!Granulate)
- [x] [Grinding Station](https://magiccards.info/query?q=!Grinding+Station)
- [x] [Guardian Idol](https://magiccards.info/query?q=!Guardian+Idol)
- [x] [Healer's Headdress](https://magiccards.info/query?q=!Healer's+Headdress)
- [x] [Heliophial](https://magiccards.info/query?q=!Heliophial)
- [x] [Helm of Kaldra](https://magiccards.info/query?q=!Helm+of+Kaldra)
- [x] [Horned Helm](https://magiccards.info/query?q=!Horned+Helm)
- [x] [Hoverguard Sweepers](https://magiccards.info/query?q=!Hoverguard+Sweepers)
- [x] [Infused Arrows](https://magiccards.info/query?q=!Infused+Arrows)
- [x] [Into Thin Air](https://magiccards.info/query?q=!Into+Thin+Air)
- [x] [Ion Storm](https://magiccards.info/query?q=!Ion+Storm)
- [x] [Iron-Barb Hellion](https://magiccards.info/query?q=!Iron-Barb+Hellion)
- [x] [Joiner Adept](https://magiccards.info/query?q=!Joiner+Adept)
- [x] [Krark-Clan Engineers](https://magiccards.info/query?q=!Krark-Clan+Engineers)
- [x] [Krark-Clan Ironworks](https://magiccards.info/query?q=!Krark-Clan+Ironworks)
- [x] [Krark-Clan Ogre](https://magiccards.info/query?q=!Krark-Clan+Ogre)
- [x] [Lantern of Insight](https://magiccards.info/query?q=!Lantern+of+Insight)
- [x] [Leonin Squire](https://magiccards.info/query?q=!Leonin+Squire)
- [x] [Lose Hope](https://magiccards.info/query?q=!Lose+Hope)
- [x] [Loxodon Anchorite](https://magiccards.info/query?q=!Loxodon+Anchorite)
- [x] [Loxodon Stalwart](https://magiccards.info/query?q=!Loxodon+Stalwart)
- [x] [Lunar Avenger](https://magiccards.info/query?q=!Lunar+Avenger)
- [x] [Magma Giant](https://magiccards.info/query?q=!Magma+Giant)
- [x] [Magma Jet](https://magiccards.info/query?q=!Magma+Jet)
- [x] [Magnetic Theft](https://magiccards.info/query?q=!Magnetic+Theft)
- [x] [Mana Geyser](https://magiccards.info/query?q=!Mana+Geyser)
- [x] [Mephidross Vampire](https://magiccards.info/query?q=!Mephidross+Vampire)
- [x] [Moriok Rigger](https://magiccards.info/query?q=!Moriok+Rigger)
- [x] [Mycosynth Golem](https://magiccards.info/query?q=!Mycosynth+Golem)
- [x] [Myr Quadropod](https://magiccards.info/query?q=!Myr+Quadropod)
- [x] [Myr Servitor](https://magiccards.info/query?q=!Myr+Servitor)
- [x] [Neurok Stealthsuit](https://magiccards.info/query?q=!Neurok+Stealthsuit)
- [x] [Night's Whisper](https://magiccards.info/query?q=!Night's+Whisper)
- [x] [Nim Grotesque](https://magiccards.info/query?q=!Nim+Grotesque)
- [x] [Opaline Bracers](https://magiccards.info/query?q=!Opaline+Bracers)
- [x] [Ouphe Vandals](https://magiccards.info/query?q=!Ouphe+Vandals)
- [x] [Paradise Mantle](https://magiccards.info/query?q=!Paradise+Mantle)
- [x] [Pentad Prism](https://magiccards.info/query?q=!Pentad+Prism)
- [x] [Plasma Elemental](https://magiccards.info/query?q=!Plasma+Elemental)
- [x] [Plunge into Darkness](https://magiccards.info/query?q=!Plunge+into+Darkness)
- [x] [Possessed Portal](https://magiccards.info/query?q=!Possessed+Portal)
- [x] [Qumulox](https://magiccards.info/query?q=!Qumulox)
- [x] [Rain of Rust](https://magiccards.info/query?q=!Rain+of+Rust)
- [x] [Raksha Golden Cub](https://magiccards.info/query?q=!Raksha+Golden+Cub)
- [x] [Razorgrass Screen](https://magiccards.info/query?q=!Razorgrass+Screen)
- [x] [Razormane Masticore](https://magiccards.info/query?q=!Razormane+Masticore)
- [x] [Relentless Rats](https://magiccards.info/query?q=!Relentless+Rats)
- [x] [Relic Barrier](https://magiccards.info/query?q=!Relic+Barrier)
- [x] [Retaliate](https://magiccards.info/query?q=!Retaliate)
- [x] [Reversal of Fortune](https://magiccards.info/query?q=!Reversal+of+Fortune)
- [x] [Rite of Passage](https://magiccards.info/query?q=!Rite+of+Passage)
- [x] [Roar of Reclamation](https://magiccards.info/query?q=!Roar+of+Reclamation)
- [x] [Rude Awakening](https://magiccards.info/query?q=!Rude+Awakening)
- [x] [Salvaging Station](https://magiccards.info/query?q=!Salvaging+Station)
- [x] [Sawtooth Thresher](https://magiccards.info/query?q=!Sawtooth+Thresher)
- [x] [Screaming Fury](https://magiccards.info/query?q=!Screaming+Fury)
- [x] [Serum Visions](https://magiccards.info/query?q=!Serum+Visions)
- [x] [Shattered Dreams](https://magiccards.info/query?q=!Shattered+Dreams)
- [x] [Silent Arbiter](https://magiccards.info/query?q=!Silent+Arbiter)
- [x] [Skullcage](https://magiccards.info/query?q=!Skullcage)
- [x] [Skyhunter Prowler](https://magiccards.info/query?q=!Skyhunter+Prowler)
- [x] [Skyhunter Skirmisher](https://magiccards.info/query?q=!Skyhunter+Skirmisher)
- [x] [Skyreach Manta](https://magiccards.info/query?q=!Skyreach+Manta)
- [x] [Solarion](https://magiccards.info/query?q=!Solarion)
- [x] [Spark Elemental](https://magiccards.info/query?q=!Spark+Elemental)
- [x] [Sparring Collar](https://magiccards.info/query?q=!Sparring+Collar)
- [ ] [Spectral Shift](https://magiccards.info/query?q=!Spectral+Shift)
- [x] [Spinal Parasite](https://magiccards.info/query?q=!Spinal+Parasite)
- [x] [Staff of Domination](https://magiccards.info/query?q=!Staff+of+Domination)
- [x] [Stand Firm](https://magiccards.info/query?q=!Stand+Firm)
- [x] [Stasis Cocoon](https://magiccards.info/query?q=!Stasis+Cocoon)
- [x] [Steelshaper's Gift](https://magiccards.info/query?q=!Steelshaper's+Gift)
- [x] [Summoner's Egg](https://magiccards.info/query?q=!Summoner's+Egg)
- [x] [Summoning Station](https://magiccards.info/query?q=!Summoning+Station)
- [x] [Suncrusher](https://magiccards.info/query?q=!Suncrusher)
- [x] [Suntouched Myr](https://magiccards.info/query?q=!Suntouched+Myr)
- [x] [Sylvok Explorer](https://magiccards.info/query?q=!Sylvok+Explorer)
- [x] [Synod Centurion](https://magiccards.info/query?q=!Synod+Centurion)
- [x] [Tangle Asp](https://magiccards.info/query?q=!Tangle+Asp)
- [x] [Tel-Jilad Justice](https://magiccards.info/query?q=!Tel-Jilad+Justice)
- [x] [Tel-Jilad Lifebreather](https://magiccards.info/query?q=!Tel-Jilad+Lifebreather)
- [x] [Thermal Navigator](https://magiccards.info/query?q=!Thermal+Navigator)
- [x] [Thought Courier](https://magiccards.info/query?q=!Thought+Courier)
- [x] [Tornado Elemental](https://magiccards.info/query?q=!Tornado+Elemental)
- [x] [Trinket Mage](https://magiccards.info/query?q=!Trinket+Mage)
- [x] [Tyrranax](https://magiccards.info/query?q=!Tyrranax)
- [x] [Vanquish](https://magiccards.info/query?q=!Vanquish)
- [x] [Vedalken Mastermind](https://magiccards.info/query?q=!Vedalken+Mastermind)
- [x] [Vedalken Orrery](https://magiccards.info/query?q=!Vedalken+Orrery)
- [x] [Vedalken Shackles](https://magiccards.info/query?q=!Vedalken+Shackles)
- [x] [Vicious Betrayal](https://magiccards.info/query?q=!Vicious+Betrayal)
- [x] [Viridian Lorebearers](https://magiccards.info/query?q=!Viridian+Lorebearers)
- [x] [Viridian Scout](https://magiccards.info/query?q=!Viridian+Scout)
- [x] [Vulshok Sorcerer](https://magiccards.info/query?q=!Vulshok+Sorcerer)
- [x] [Wayfarer's Bauble](https://magiccards.info/query?q=!Wayfarer's+Bauble)

**Comment by xenohedron** [comment]
All implemented except text changing effects per #2082
