### ISSUE TITLE
CHK - Champions of Kamigawa set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4927]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/champions-of-kamigawa

# Unimplemented cards

94|[Swirl the Mists](https://magiccards.info/query?q=!Swirl+the+Mists)

# Cards in set:
- [x] [Akki Avalanchers](https://magiccards.info/query?q=!Akki+Avalanchers)
- [x] [Akki Coalflinger](https://magiccards.info/query?q=!Akki+Coalflinger)
- [x] [Akki Lavarunner](https://magiccards.info/query?q=!Akki+Lavarunner)
- [x] [Akki Rockspeaker](https://magiccards.info/query?q=!Akki+Rockspeaker)
- [x] [Akki Underminer](https://magiccards.info/query?q=!Akki+Underminer)
- [x] [Ashen-Skin Zubera](https://magiccards.info/query?q=!Ashen-Skin+Zubera)
- [x] [Aura of Dominion](https://magiccards.info/query?q=!Aura+of+Dominion)
- [x] [Autumn-Tail, Kitsune Sage](https://magiccards.info/query?q=!Autumn-Tail,+Kitsune+Sage)
- [x] [Azami, Lady of Scrolls](https://magiccards.info/query?q=!Azami,+Lady+of+Scrolls)
- [x] [Azusa, Lost but Seeking](https://magiccards.info/query?q=!Azusa,+Lost+but+Seeking)
- [x] [Battle-Mad Ronin](https://magiccards.info/query?q=!Battle-Mad+Ronin)
- [x] [Befoul](https://magiccards.info/query?q=!Befoul)
- [x] [Ben-Ben, Akki Hermit](https://magiccards.info/query?q=!Ben-Ben,+Akki+Hermit)
- [x] [Blessed Breath](https://magiccards.info/query?q=!Blessed+Breath)
- [x] [Blind with Anger](https://magiccards.info/query?q=!Blind+with+Anger)
- [x] [Blood Rites](https://magiccards.info/query?q=!Blood+Rites)
- [x] [Blood Speaker](https://magiccards.info/query?q=!Blood+Speaker)
- [x] [Bloodthirsty Ogre](https://magiccards.info/query?q=!Bloodthirsty+Ogre)
- [x] [Boseiju, Who Shelters All](https://magiccards.info/query?q=!Boseiju,+Who+Shelters+All)
- [x] [Brothers Yamazaki](https://magiccards.info/query?q=!Brothers+Yamazaki)
- [x] [Brutal Deceiver](https://magiccards.info/query?q=!Brutal+Deceiver)
- [x] [Budoka Gardener](https://magiccards.info/query?q=!Budoka+Gardener)
- [x] [Burr Grafter](https://magiccards.info/query?q=!Burr+Grafter)
- [x] [Bushi Tenderfoot](https://magiccards.info/query?q=!Bushi+Tenderfoot)
- [x] [Cage of Hands](https://magiccards.info/query?q=!Cage+of+Hands)
- [x] [Call to Glory](https://magiccards.info/query?q=!Call+to+Glory)
- [x] [Callous Deceiver](https://magiccards.info/query?q=!Callous+Deceiver)
- [x] [Candles' Glow](https://magiccards.info/query?q=!Candles'+Glow)
- [x] [Cleanfall](https://magiccards.info/query?q=!Cleanfall)
- [x] [Cloudcrest Lake](https://magiccards.info/query?q=!Cloudcrest+Lake)
- [x] [Commune with Nature](https://magiccards.info/query?q=!Commune+with+Nature)
- [x] [Consuming Vortex](https://magiccards.info/query?q=!Consuming+Vortex)
- [x] [Counsel of the Soratami](https://magiccards.info/query?q=!Counsel+of+the+Soratami)
- [x] [Cranial Extraction](https://magiccards.info/query?q=!Cranial+Extraction)
- [x] [Cruel Deceiver](https://magiccards.info/query?q=!Cruel+Deceiver)
- [x] [Crushing Pain](https://magiccards.info/query?q=!Crushing+Pain)
- [x] [Cursed Ronin](https://magiccards.info/query?q=!Cursed+Ronin)
- [x] [Cut the Tethers](https://magiccards.info/query?q=!Cut+the+Tethers)
- [x] [Dampen Thought](https://magiccards.info/query?q=!Dampen+Thought)
- [x] [Dance of Shadows](https://magiccards.info/query?q=!Dance+of+Shadows)
- [x] [Deathcurse Ogre](https://magiccards.info/query?q=!Deathcurse+Ogre)
- [x] [Desperate Ritual](https://magiccards.info/query?q=!Desperate+Ritual)
- [x] [Devoted Retainer](https://magiccards.info/query?q=!Devoted+Retainer)
- [x] [Devouring Greed](https://magiccards.info/query?q=!Devouring+Greed)
- [x] [Devouring Rage](https://magiccards.info/query?q=!Devouring+Rage)
- [x] [Distress](https://magiccards.info/query?q=!Distress)
- [x] [Dokai, Weaver of Life](https://magiccards.info/query?q=!Dokai,+Weaver+of+Life)
- [x] [Dosan the Falling Leaf](https://magiccards.info/query?q=!Dosan+the+Falling+Leaf)
- [x] [Dripping-Tongue Zubera](https://magiccards.info/query?q=!Dripping-Tongue+Zubera)
- [x] [Earthshaker](https://magiccards.info/query?q=!Earthshaker)
- [x] [Eerie Procession](https://magiccards.info/query?q=!Eerie+Procession)
- [x] [Eiganjo Castle](https://magiccards.info/query?q=!Eiganjo+Castle)
- [x] [Eight-and-a-Half-Tails](https://magiccards.info/query?q=!Eight-and-a-Half-Tails)
- [x] [Ember-Fist Zubera](https://magiccards.info/query?q=!Ember-Fist+Zubera)
- [x] [Ethereal Haze](https://magiccards.info/query?q=!Ethereal+Haze)
- [x] [Eye of Nowhere](https://magiccards.info/query?q=!Eye+of+Nowhere)
- [x] [Feast of Worms](https://magiccards.info/query?q=!Feast+of+Worms)
- [x] [Feral Deceiver](https://magiccards.info/query?q=!Feral+Deceiver)
- [x] [Field of Reality](https://magiccards.info/query?q=!Field+of+Reality)
- [x] [Floating-Dream Zubera](https://magiccards.info/query?q=!Floating-Dream+Zubera)
- [x] [Forbidden Orchard](https://magiccards.info/query?q=!Forbidden+Orchard)
- [x] [Forest](https://magiccards.info/query?q=!Forest)
- [x] [Frostwielder](https://magiccards.info/query?q=!Frostwielder)
- [x] [Gale Force](https://magiccards.info/query?q=!Gale+Force)
- [x] [General's Kabuto](https://magiccards.info/query?q=!General's+Kabuto)
- [x] [Ghostly Prison](https://magiccards.info/query?q=!Ghostly+Prison)
- [x] [Gibbering Kami](https://magiccards.info/query?q=!Gibbering+Kami)
- [x] [Gifts Ungiven](https://magiccards.info/query?q=!Gifts+Ungiven)
- [x] [Glacial Ray](https://magiccards.info/query?q=!Glacial+Ray)
- [x] [Glimpse of Nature](https://magiccards.info/query?q=!Glimpse+of+Nature)
- [x] [Godo, Bandit Warlord](https://magiccards.info/query?q=!Godo,+Bandit+Warlord)
- [x] [Goka the Unjust](https://magiccards.info/query?q=!Goka+the+Unjust)
- [x] [Graceful Adept](https://magiccards.info/query?q=!Graceful+Adept)
- [x] [Guardian of Solitude](https://magiccards.info/query?q=!Guardian+of+Solitude)
- [x] [Gutwrencher Oni](https://magiccards.info/query?q=!Gutwrencher+Oni)
- [x] [Hair-Strung Koto](https://magiccards.info/query?q=!Hair-Strung+Koto)
- [x] [Hall of the Bandit Lord](https://magiccards.info/query?q=!Hall+of+the+Bandit+Lord)
- [x] [Hana Kami](https://magiccards.info/query?q=!Hana+Kami)
- [x] [Hanabi Blast](https://magiccards.info/query?q=!Hanabi+Blast)
- [x] [Hankyu](https://magiccards.info/query?q=!Hankyu)
- [x] [Harsh Deceiver](https://magiccards.info/query?q=!Harsh+Deceiver)
- [x] [He Who Hungers](https://magiccards.info/query?q=!He+Who+Hungers)
- [x] [Heartbeat of Spring](https://magiccards.info/query?q=!Heartbeat+of+Spring)
- [x] [Hearth Kami](https://magiccards.info/query?q=!Hearth+Kami)
- [x] [Hideous Laughter](https://magiccards.info/query?q=!Hideous+Laughter)
- [x] [Hikari, Twilight Guardian](https://magiccards.info/query?q=!Hikari,+Twilight+Guardian)
- [x] [Hinder](https://magiccards.info/query?q=!Hinder)
- [x] [Hisoka's Defiance](https://magiccards.info/query?q=!Hisoka's+Defiance)
- [x] [Hisoka's Guard](https://magiccards.info/query?q=!Hisoka's+Guard)
- [x] [Hisoka, Minamo Sensei](https://magiccards.info/query?q=!Hisoka,+Minamo+Sensei)
- [x] [Hold the Line](https://magiccards.info/query?q=!Hold+the+Line)
- [x] [Honden of Cleansing Fire](https://magiccards.info/query?q=!Honden+of+Cleansing+Fire)
- [x] [Honden of Infinite Rage](https://magiccards.info/query?q=!Honden+of+Infinite+Rage)
- [x] [Honden of Life's Web](https://magiccards.info/query?q=!Honden+of+Life's+Web)
- [x] [Honden of Night's Reach](https://magiccards.info/query?q=!Honden+of+Night's+Reach)
- [x] [Honden of Seeing Winds](https://magiccards.info/query?q=!Honden+of+Seeing+Winds)
- [x] [Honor-Worn Shaku](https://magiccards.info/query?q=!Honor-Worn+Shaku)
- [x] [Horizon Seed](https://magiccards.info/query?q=!Horizon+Seed)
- [x] [Horobi, Death's Wail](https://magiccards.info/query?q=!Horobi,+Death's+Wail)
- [x] [Humble Budoka](https://magiccards.info/query?q=!Humble+Budoka)
- [x] [Hundred-Talon Kami](https://magiccards.info/query?q=!Hundred-Talon+Kami)
- [x] [Imi Statue](https://magiccards.info/query?q=!Imi+Statue)
- [x] [Iname, Death Aspect](https://magiccards.info/query?q=!Iname,+Death+Aspect)
- [x] [Iname, Life Aspect](https://magiccards.info/query?q=!Iname,+Life+Aspect)
- [x] [Indomitable Will](https://magiccards.info/query?q=!Indomitable+Will)
- [x] [Initiate of Blood](https://magiccards.info/query?q=!Initiate+of+Blood)
- [x] [Innocence Kami](https://magiccards.info/query?q=!Innocence+Kami)
- [x] [Isamaru, Hound of Konda](https://magiccards.info/query?q=!Isamaru,+Hound+of+Konda)
- [x] [Island](https://magiccards.info/query?q=!Island)
- [x] [Jade Idol](https://magiccards.info/query?q=!Jade+Idol)
- [x] [Journeyer's Kite](https://magiccards.info/query?q=!Journeyer's+Kite)
- [x] [Joyous Respite](https://magiccards.info/query?q=!Joyous+Respite)
- [x] [Jugan, the Rising Star](https://magiccards.info/query?q=!Jugan,+the+Rising+Star)
- [x] [Jukai Messenger](https://magiccards.info/query?q=!Jukai+Messenger)
- [x] [Junkyo Bell](https://magiccards.info/query?q=!Junkyo+Bell)
- [x] [Jushi Apprentice](https://magiccards.info/query?q=!Jushi+Apprentice)
- [x] [Kabuto Moth](https://magiccards.info/query?q=!Kabuto+Moth)
- [x] [Kami of Ancient Law](https://magiccards.info/query?q=!Kami+of+Ancient+Law)
- [x] [Kami of Fire's Roar](https://magiccards.info/query?q=!Kami+of+Fire's+Roar)
- [x] [Kami of Lunacy](https://magiccards.info/query?q=!Kami+of+Lunacy)
- [x] [Kami of Old Stone](https://magiccards.info/query?q=!Kami+of+Old+Stone)
- [x] [Kami of Twisted Reflection](https://magiccards.info/query?q=!Kami+of+Twisted+Reflection)
- [x] [Kami of the Hunt](https://magiccards.info/query?q=!Kami+of+the+Hunt)
- [x] [Kami of the Painted Road](https://magiccards.info/query?q=!Kami+of+the+Painted+Road)
- [x] [Kami of the Palace Fields](https://magiccards.info/query?q=!Kami+of+the+Palace+Fields)
- [x] [Kami of the Waning Moon](https://magiccards.info/query?q=!Kami+of+the+Waning+Moon)
- [x] [Kashi-Tribe Reaver](https://magiccards.info/query?q=!Kashi-Tribe+Reaver)
- [x] [Kashi-Tribe Warriors](https://magiccards.info/query?q=!Kashi-Tribe+Warriors)
- [x] [Keiga, the Tide Star](https://magiccards.info/query?q=!Keiga,+the+Tide+Star)
- [x] [Kenzo the Hardhearted](https://magiccards.info/query?q=!Kenzo+the+Hardhearted)
- [x] [Kiki-Jiki, Mirror Breaker](https://magiccards.info/query?q=!Kiki-Jiki,+Mirror+Breaker)
- [x] [Kiku, Night's Flower](https://magiccards.info/query?q=!Kiku,+Night's+Flower)
- [x] [Kitsune Blademaster](https://magiccards.info/query?q=!Kitsune+Blademaster)
- [x] [Kitsune Diviner](https://magiccards.info/query?q=!Kitsune+Diviner)
- [x] [Kitsune Healer](https://magiccards.info/query?q=!Kitsune+Healer)
- [x] [Kitsune Mystic](https://magiccards.info/query?q=!Kitsune+Mystic)
- [x] [Kitsune Riftwalker](https://magiccards.info/query?q=!Kitsune+Riftwalker)
- [x] [Kodama of the North Tree](https://magiccards.info/query?q=!Kodama+of+the+North+Tree)
- [x] [Kodama of the South Tree](https://magiccards.info/query?q=!Kodama+of+the+South+Tree)
- [x] [Kodama's Might](https://magiccards.info/query?q=!Kodama's+Might)
- [x] [Kodama's Reach](https://magiccards.info/query?q=!Kodama's+Reach)
- [x] [Kokusho, the Evening Star](https://magiccards.info/query?q=!Kokusho,+the+Evening+Star)
- [x] [Konda's Banner](https://magiccards.info/query?q=!Konda's+Banner)
- [x] [Konda's Hatamoto](https://magiccards.info/query?q=!Konda's+Hatamoto)
- [x] [Konda, Lord of Eiganjo](https://magiccards.info/query?q=!Konda,+Lord+of+Eiganjo)
- [x] [Kumano's Pupils](https://magiccards.info/query?q=!Kumano's+Pupils)
- [x] [Kumano, Master Yamabushi](https://magiccards.info/query?q=!Kumano,+Master+Yamabushi)
- [x] [Kuro, Pitlord](https://magiccards.info/query?q=!Kuro,+Pitlord)
- [x] [Kusari-Gama](https://magiccards.info/query?q=!Kusari-Gama)
- [x] [Lantern Kami](https://magiccards.info/query?q=!Lantern+Kami)
- [x] [Lantern-Lit Graveyard](https://magiccards.info/query?q=!Lantern-Lit+Graveyard)
- [x] [Lava Spike](https://magiccards.info/query?q=!Lava+Spike)
- [x] [Lifted by Clouds](https://magiccards.info/query?q=!Lifted+by+Clouds)
- [x] [Long-Forgotten Gohei](https://magiccards.info/query?q=!Long-Forgotten+Gohei)
- [x] [Lure](https://magiccards.info/query?q=!Lure)
- [x] [Mana Seism](https://magiccards.info/query?q=!Mana+Seism)
- [x] [Marrow-Gnawer](https://magiccards.info/query?q=!Marrow-Gnawer)
- [x] [Masako the Humorless](https://magiccards.info/query?q=!Masako+the+Humorless)
- [x] [Matsu-Tribe Decoy](https://magiccards.info/query?q=!Matsu-Tribe+Decoy)
- [x] [Meloku the Clouded Mirror](https://magiccards.info/query?q=!Meloku+the+Clouded+Mirror)
- [x] [Midnight Covenant](https://magiccards.info/query?q=!Midnight+Covenant)
- [x] [Minamo, School at Water's Edge](https://magiccards.info/query?q=!Minamo,+School+at+Water's+Edge)
- [x] [Mindblaze](https://magiccards.info/query?q=!Mindblaze)
- [x] [Moonring Mirror](https://magiccards.info/query?q=!Moonring+Mirror)
- [x] [Moss Kami](https://magiccards.info/query?q=!Moss+Kami)
- [x] [Mothrider Samurai](https://magiccards.info/query?q=!Mothrider+Samurai)
- [x] [Mountain](https://magiccards.info/query?q=!Mountain)
- [x] [Myojin of Cleansing Fire](https://magiccards.info/query?q=!Myojin+of+Cleansing+Fire)
- [x] [Myojin of Infinite Rage](https://magiccards.info/query?q=!Myojin+of+Infinite+Rage)
- [x] [Myojin of Life's Web](https://magiccards.info/query?q=!Myojin+of+Life's+Web)
- [x] [Myojin of Night's Reach](https://magiccards.info/query?q=!Myojin+of+Night's+Reach)
- [x] [Myojin of Seeing Winds](https://magiccards.info/query?q=!Myojin+of+Seeing+Winds)
- [x] [Mystic Restraints](https://magiccards.info/query?q=!Mystic+Restraints)
- [x] [Nagao, Bound by Honor](https://magiccards.info/query?q=!Nagao,+Bound+by+Honor)
- [x] [Nature's Will](https://magiccards.info/query?q=!Nature's+Will)
- [x] [Nezumi Bone-Reader](https://magiccards.info/query?q=!Nezumi+Bone-Reader)
- [x] [Nezumi Cutthroat](https://magiccards.info/query?q=!Nezumi+Cutthroat)
- [x] [Nezumi Graverobber](https://magiccards.info/query?q=!Nezumi+Graverobber)
- [x] [Nezumi Ronin](https://magiccards.info/query?q=!Nezumi+Ronin)
- [x] [Nezumi Shortfang](https://magiccards.info/query?q=!Nezumi+Shortfang)
- [x] [Night Dealings](https://magiccards.info/query?q=!Night+Dealings)
- [x] [Night of Souls' Betrayal](https://magiccards.info/query?q=!Night+of+Souls'+Betrayal)
- [x] [Nighteyes the Desecrator](https://magiccards.info/query?q=!Nighteyes+the+Desecrator)
- [x] [Nine-Ringed Bo](https://magiccards.info/query?q=!Nine-Ringed+Bo)
- [x] [No-Dachi](https://magiccards.info/query?q=!No-Dachi)
- [x] [Numai Outcast](https://magiccards.info/query?q=!Numai+Outcast)
- [x] [Oathkeeper, Takeno's Daisho](https://magiccards.info/query?q=!Oathkeeper,+Takeno's+Daisho)
- [x] [Okina, Temple to the Grandfathers](https://magiccards.info/query?q=!Okina,+Temple+to+the+Grandfathers)
- [x] [Oni Possession](https://magiccards.info/query?q=!Oni+Possession)
- [x] [Orbweaver Kumo](https://magiccards.info/query?q=!Orbweaver+Kumo)
- [x] [Order of the Sacred Bell](https://magiccards.info/query?q=!Order+of+the+Sacred+Bell)
- [x] [Ore Gorger](https://magiccards.info/query?q=!Ore+Gorger)
- [x] [Orochi Eggwatcher](https://magiccards.info/query?q=!Orochi+Eggwatcher)
- [x] [Orochi Hatchery](https://magiccards.info/query?q=!Orochi+Hatchery)
- [x] [Orochi Leafcaller](https://magiccards.info/query?q=!Orochi+Leafcaller)
- [x] [Orochi Ranger](https://magiccards.info/query?q=!Orochi+Ranger)
- [x] [Orochi Sustainer](https://magiccards.info/query?q=!Orochi+Sustainer)
- [x] [Otherworldly Journey](https://magiccards.info/query?q=!Otherworldly+Journey)
- [x] [Pain Kami](https://magiccards.info/query?q=!Pain+Kami)
- [x] [Painwracker Oni](https://magiccards.info/query?q=!Painwracker+Oni)
- [x] [Part the Veil](https://magiccards.info/query?q=!Part+the+Veil)
- [x] [Peer Through Depths](https://magiccards.info/query?q=!Peer+Through+Depths)
- [x] [Petals of Insight](https://magiccards.info/query?q=!Petals+of+Insight)
- [x] [Pinecrest Ridge](https://magiccards.info/query?q=!Pinecrest+Ridge)
- [x] [Pious Kitsune](https://magiccards.info/query?q=!Pious+Kitsune)
- [x] [Plains](https://magiccards.info/query?q=!Plains)
- [x] [Psychic Puppetry](https://magiccards.info/query?q=!Psychic+Puppetry)
- [x] [Pull Under](https://magiccards.info/query?q=!Pull+Under)
- [x] [Quiet Purity](https://magiccards.info/query?q=!Quiet+Purity)
- [x] [Rag Dealer](https://magiccards.info/query?q=!Rag+Dealer)
- [x] [Ragged Veins](https://magiccards.info/query?q=!Ragged+Veins)
- [x] [Reach Through Mists](https://magiccards.info/query?q=!Reach+Through+Mists)
- [x] [Reciprocate](https://magiccards.info/query?q=!Reciprocate)
- [x] [Reito Lantern](https://magiccards.info/query?q=!Reito+Lantern)
- [x] [Rend Flesh](https://magiccards.info/query?q=!Rend+Flesh)
- [x] [Rend Spirit](https://magiccards.info/query?q=!Rend+Spirit)
- [x] [Reverse the Sands](https://magiccards.info/query?q=!Reverse+the+Sands)
- [x] [Reweave](https://magiccards.info/query?q=!Reweave)
- [x] [River Kaijin](https://magiccards.info/query?q=!River+Kaijin)
- [x] [Ronin Houndmaster](https://magiccards.info/query?q=!Ronin+Houndmaster)
- [x] [Rootrunner](https://magiccards.info/query?q=!Rootrunner)
- [x] [Ryusei, the Falling Star](https://magiccards.info/query?q=!Ryusei,+the+Falling+Star)
- [x] [Sachi, Daughter of Seshiro](https://magiccards.info/query?q=!Sachi,+Daughter+of+Seshiro)
- [x] [Sakura-Tribe Elder](https://magiccards.info/query?q=!Sakura-Tribe+Elder)
- [x] [Samurai Enforcers](https://magiccards.info/query?q=!Samurai+Enforcers)
- [x] [Samurai of the Pale Curtain](https://magiccards.info/query?q=!Samurai+of+the+Pale+Curtain)
- [x] [Scuttling Death](https://magiccards.info/query?q=!Scuttling+Death)
- [x] [Seizan, Perverter of Truth](https://magiccards.info/query?q=!Seizan,+Perverter+of+Truth)
- [x] [Sensei Golden-Tail](https://magiccards.info/query?q=!Sensei+Golden-Tail)
- [x] [Sensei's Divining Top](https://magiccards.info/query?q=!Sensei's+Divining+Top)
- [x] [Serpent Skin](https://magiccards.info/query?q=!Serpent+Skin)
- [x] [Seshiro the Anointed](https://magiccards.info/query?q=!Seshiro+the+Anointed)
- [x] [Shell of the Last Kappa](https://magiccards.info/query?q=!Shell+of+the+Last+Kappa)
- [x] [Shidako, Broodmistress](https://magiccards.info/query?q=!Shidako,+Broodmistress)
- [x] [Shimatsu the Bloodcloaked](https://magiccards.info/query?q=!Shimatsu+the+Bloodcloaked)
- [x] [Shinka, the Bloodsoaked Keep](https://magiccards.info/query?q=!Shinka,+the+Bloodsoaked+Keep)
- [x] [Shisato, Whispering Hunter](https://magiccards.info/query?q=!Shisato,+Whispering+Hunter)
- [x] [Shizo, Death's Storehouse](https://magiccards.info/query?q=!Shizo,+Death's+Storehouse)
- [x] [Sideswipe](https://magiccards.info/query?q=!Sideswipe)
- [x] [Sift Through Sands](https://magiccards.info/query?q=!Sift+Through+Sands)
- [x] [Silent-Chant Zubera](https://magiccards.info/query?q=!Silent-Chant+Zubera)
- [x] [Sire of the Storm](https://magiccards.info/query?q=!Sire+of+the+Storm)
- [x] [Soilshaper](https://magiccards.info/query?q=!Soilshaper)
- [x] [Sokenzan Bruiser](https://magiccards.info/query?q=!Sokenzan+Bruiser)
- [x] [Soratami Cloudskater](https://magiccards.info/query?q=!Soratami+Cloudskater)
- [x] [Soratami Mirror-Guard](https://magiccards.info/query?q=!Soratami+Mirror-Guard)
- [x] [Soratami Mirror-Mage](https://magiccards.info/query?q=!Soratami+Mirror-Mage)
- [x] [Soratami Rainshaper](https://magiccards.info/query?q=!Soratami+Rainshaper)
- [x] [Soratami Savant](https://magiccards.info/query?q=!Soratami+Savant)
- [x] [Soratami Seer](https://magiccards.info/query?q=!Soratami+Seer)
- [x] [Sosuke, Son of Seshiro](https://magiccards.info/query?q=!Sosuke,+Son+of+Seshiro)
- [x] [Soul of Magma](https://magiccards.info/query?q=!Soul+of+Magma)
- [x] [Soulblast](https://magiccards.info/query?q=!Soulblast)
- [x] [Soulless Revival](https://magiccards.info/query?q=!Soulless+Revival)
- [x] [Squelch](https://magiccards.info/query?q=!Squelch)
- [x] [Stabwhisker the Odious](https://magiccards.info/query?q=!Stabwhisker+the+Odious)
- [x] [Stone Rain](https://magiccards.info/query?q=!Stone+Rain)
- [x] [Strange Inversion](https://magiccards.info/query?q=!Strange+Inversion)
- [x] [Strength of Cedars](https://magiccards.info/query?q=!Strength+of+Cedars)
- [x] [Struggle for Sanity](https://magiccards.info/query?q=!Struggle+for+Sanity)
- [x] [Student of Elements](https://magiccards.info/query?q=!Student+of+Elements)
- [x] [Swallowing Plague](https://magiccards.info/query?q=!Swallowing+Plague)
- [x] [Swamp](https://magiccards.info/query?q=!Swamp)
- [ ] [Swirl the Mists](https://magiccards.info/query?q=!Swirl+the+Mists)
- [x] [Takeno, Samurai General](https://magiccards.info/query?q=!Takeno,+Samurai+General)
- [x] [Tatsumasa, the Dragon's Fang](https://magiccards.info/query?q=!Tatsumasa,+the+Dragon's+Fang)
- [x] [Teller of Tales](https://magiccards.info/query?q=!Teller+of+Tales)
- [x] [Tenza, Godo's Maul](https://magiccards.info/query?q=!Tenza,+Godo's+Maul)
- [x] [Terashi's Cry](https://magiccards.info/query?q=!Terashi's+Cry)
- [x] [The Unspeakable](https://magiccards.info/query?q=!The+Unspeakable)
- [x] [Thief of Hope](https://magiccards.info/query?q=!Thief+of+Hope)
- [x] [Thoughtbind](https://magiccards.info/query?q=!Thoughtbind)
- [x] [Thousand-legged Kami](https://magiccards.info/query?q=!Thousand-legged+Kami)
- [x] [Through the Breach](https://magiccards.info/query?q=!Through+the+Breach)
- [x] [Tide of War](https://magiccards.info/query?q=!Tide+of+War)
- [x] [Time Stop](https://magiccards.info/query?q=!Time+Stop)
- [x] [Time of Need](https://magiccards.info/query?q=!Time+of+Need)
- [x] [Tobita, Master of Winds](https://magiccards.info/query?q=!Tobita,+Master+of+Winds)
- [x] [Tok-Tok, Volcano Born](https://magiccards.info/query?q=!Tok-Tok,+Volcano+Born)
- [x] [Tomoya the Revealer](https://magiccards.info/query?q=!Tomoya+the+Revealer)
- [x] [Tranquil Garden](https://magiccards.info/query?q=!Tranquil+Garden)
- [x] [Uba Mask](https://magiccards.info/query?q=!Uba+Mask)
- [x] [Uncontrollable Anger](https://magiccards.info/query?q=!Uncontrollable+Anger)
- [x] [Unearthly Blizzard](https://magiccards.info/query?q=!Unearthly+Blizzard)
- [x] [Unnatural Speed](https://magiccards.info/query?q=!Unnatural+Speed)
- [x] [Untaidake, the Cloud Keeper](https://magiccards.info/query?q=!Untaidake,+the+Cloud+Keeper)
- [x] [Uyo, Silent Prophet](https://magiccards.info/query?q=!Uyo,+Silent+Prophet)
- [x] [Vassal's Duty](https://magiccards.info/query?q=!Vassal's+Duty)
- [x] [Venerable Kumo](https://magiccards.info/query?q=!Venerable+Kumo)
- [x] [Vigilance](https://magiccards.info/query?q=!Vigilance)
- [x] [Villainous Ogre](https://magiccards.info/query?q=!Villainous+Ogre)
- [x] [Vine Kami](https://magiccards.info/query?q=!Vine+Kami)
- [x] [Waking Nightmare](https://magiccards.info/query?q=!Waking+Nightmare)
- [x] [Wandering Ones](https://magiccards.info/query?q=!Wandering+Ones)
- [x] [Waterveil Cavern](https://magiccards.info/query?q=!Waterveil+Cavern)
- [x] [Wear Away](https://magiccards.info/query?q=!Wear+Away)
- [x] [Wicked Akuba](https://magiccards.info/query?q=!Wicked+Akuba)
- [x] [Yamabushi's Flame](https://magiccards.info/query?q=!Yamabushi's+Flame)
- [x] [Yamabushi's Storm](https://magiccards.info/query?q=!Yamabushi's+Storm)
- [x] [Yosei, the Morning Star](https://magiccards.info/query?q=!Yosei,+the+Morning+Star)
- [x] [Zo-Zu the Punisher](https://magiccards.info/query?q=!Zo-Zu+the+Punisher)

**Comment by xenohedron** [comment]
All implemented except text changing effects per #2082
