### ISSUE TITLE
BOK - Betrayers of Kamigawa set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4928]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/betrayers-of-kamigawa

# Unimplemented cards

- none

# Cards in set:
- [x] [Akki Blizzard-Herder](https://magiccards.info/query?q=!Akki+Blizzard-Herder)
- [x] [Akki Raider](https://magiccards.info/query?q=!Akki+Raider)
- [x] [Ashen Monstrosity](https://magiccards.info/query?q=!Ashen+Monstrosity)
- [x] [Aura Barbs](https://magiccards.info/query?q=!Aura+Barbs)
- [x] [Baku Altar](https://magiccards.info/query?q=!Baku+Altar)
- [x] [Bile Urchin](https://magiccards.info/query?q=!Bile+Urchin)
- [x] [Blademane Baku](https://magiccards.info/query?q=!Blademane+Baku)
- [x] [Blazing Shoal](https://magiccards.info/query?q=!Blazing+Shoal)
- [x] [Blessing of Leeches](https://magiccards.info/query?q=!Blessing+of+Leeches)
- [x] [Blinding Powder](https://magiccards.info/query?q=!Blinding+Powder)
- [x] [Body of Jukai](https://magiccards.info/query?q=!Body+of+Jukai)
- [x] [Budoka Pupil](https://magiccards.info/query?q=!Budoka+Pupil)
- [x] [Call for Blood](https://magiccards.info/query?q=!Call+for+Blood)
- [x] [Callow Jushi](https://magiccards.info/query?q=!Callow+Jushi)
- [x] [Child of Thorns](https://magiccards.info/query?q=!Child+of+Thorns)
- [x] [Chisei, Heart of Oceans](https://magiccards.info/query?q=!Chisei,+Heart+of+Oceans)
- [x] [Clash of Realities](https://magiccards.info/query?q=!Clash+of+Realities)
- [x] [Crack the Earth](https://magiccards.info/query?q=!Crack+the+Earth)
- [x] [Crawling Filth](https://magiccards.info/query?q=!Crawling+Filth)
- [x] [Cunning Bandit](https://magiccards.info/query?q=!Cunning+Bandit)
- [x] [Day of Destiny](https://magiccards.info/query?q=!Day+of+Destiny)
- [x] [Disrupting Shoal](https://magiccards.info/query?q=!Disrupting+Shoal)
- [x] [Empty-Shrine Kannushi](https://magiccards.info/query?q=!Empty-Shrine+Kannushi)
- [x] [Enshrined Memories](https://magiccards.info/query?q=!Enshrined+Memories)
- [x] [Eradicate](https://magiccards.info/query?q=!Eradicate)
- [x] [Faithful Squire](https://magiccards.info/query?q=!Faithful+Squire)
- [x] [Final Judgment](https://magiccards.info/query?q=!Final+Judgment)
- [x] [First Volley](https://magiccards.info/query?q=!First+Volley)
- [x] [Flames of the Blood Hand](https://magiccards.info/query?q=!Flames+of+the+Blood+Hand)
- [x] [Floodbringer](https://magiccards.info/query?q=!Floodbringer)
- [x] [Forked-Branch Garami](https://magiccards.info/query?q=!Forked-Branch+Garami)
- [x] [Frost Ogre](https://magiccards.info/query?q=!Frost+Ogre)
- [x] [Frostling](https://magiccards.info/query?q=!Frostling)
- [x] [Fumiko the Lowblood](https://magiccards.info/query?q=!Fumiko+the+Lowblood)
- [x] [Genju of the Cedars](https://magiccards.info/query?q=!Genju+of+the+Cedars)
- [x] [Genju of the Falls](https://magiccards.info/query?q=!Genju+of+the+Falls)
- [x] [Genju of the Fens](https://magiccards.info/query?q=!Genju+of+the+Fens)
- [x] [Genju of the Fields](https://magiccards.info/query?q=!Genju+of+the+Fields)
- [x] [Genju of the Realm](https://magiccards.info/query?q=!Genju+of+the+Realm)
- [x] [Genju of the Spires](https://magiccards.info/query?q=!Genju+of+the+Spires)
- [x] [Gnarled Mass](https://magiccards.info/query?q=!Gnarled+Mass)
- [x] [Goblin Cohort](https://magiccards.info/query?q=!Goblin+Cohort)
- [x] [Gods' Eye, Gate to the Reikai](https://magiccards.info/query?q=!Gods'+Eye,+Gate+to+the+Reikai)
- [x] [Goryo's Vengeance](https://magiccards.info/query?q=!Goryo's+Vengeance)
- [x] [Harbinger of Spring](https://magiccards.info/query?q=!Harbinger+of+Spring)
- [x] [Heart of Light](https://magiccards.info/query?q=!Heart+of+Light)
- [x] [Heartless Hidetsugu](https://magiccards.info/query?q=!Heartless+Hidetsugu)
- [x] [Heed the Mists](https://magiccards.info/query?q=!Heed+the+Mists)
- [x] [Hero's Demise](https://magiccards.info/query?q=!Hero's+Demise)
- [x] [Higure, the Still Wind](https://magiccards.info/query?q=!Higure,+the+Still+Wind)
- [x] [Hired Muscle](https://magiccards.info/query?q=!Hired+Muscle)
- [x] [Hokori, Dust Drinker](https://magiccards.info/query?q=!Hokori,+Dust+Drinker)
- [x] [Horobi's Whisper](https://magiccards.info/query?q=!Horobi's+Whisper)
- [x] [Hundred-Talon Strike](https://magiccards.info/query?q=!Hundred-Talon+Strike)
- [x] [In the Web of War](https://magiccards.info/query?q=!In+the+Web+of+War)
- [x] [Indebted Samurai](https://magiccards.info/query?q=!Indebted+Samurai)
- [x] [Ink-Eyes, Servant of Oni](https://magiccards.info/query?q=!Ink-Eyes,+Servant+of+Oni)
- [x] [Ire of Kaminari](https://magiccards.info/query?q=!Ire+of+Kaminari)
- [x] [Isao, Enlightened Bushi](https://magiccards.info/query?q=!Isao,+Enlightened+Bushi)
- [x] [Ishi-Ishi, Akki Crackshot](https://magiccards.info/query?q=!Ishi-Ishi,+Akki+Crackshot)
- [x] [Iwamori of the Open Fist](https://magiccards.info/query?q=!Iwamori+of+the+Open+Fist)
- [x] [Jetting Glasskite](https://magiccards.info/query?q=!Jetting+Glasskite)
- [x] [Kaijin of the Vanishing Touch](https://magiccards.info/query?q=!Kaijin+of+the+Vanishing+Touch)
- [ ] [Kaiso, Memory of Loyalty](https://magiccards.info/query?q=!Kaiso,+Memory+of+Loyalty)
- [x] [Kami of False Hope](https://magiccards.info/query?q=!Kami+of+False+Hope)
- [x] [Kami of Tattered Shoji](https://magiccards.info/query?q=!Kami+of+Tattered+Shoji)
- [x] [Kami of the Honored Dead](https://magiccards.info/query?q=!Kami+of+the+Honored+Dead)
- [x] [Kentaro, the Smiling Cat](https://magiccards.info/query?q=!Kentaro,+the+Smiling+Cat)
- [x] [Kira, Great Glass-Spinner](https://magiccards.info/query?q=!Kira,+Great+Glass-Spinner)
- [x] [Kitsune Palliator](https://magiccards.info/query?q=!Kitsune+Palliator)
- [x] [Kodama of the Center Tree](https://magiccards.info/query?q=!Kodama+of+the+Center+Tree)
- [x] [Kumano's Blessing](https://magiccards.info/query?q=!Kumano's+Blessing)
- [x] [Kyoki, Sanity's Eclipse](https://magiccards.info/query?q=!Kyoki,+Sanity's+Eclipse)
- [x] [Lifegift](https://magiccards.info/query?q=!Lifegift)
- [x] [Lifespinner](https://magiccards.info/query?q=!Lifespinner)
- [x] [Loam Dweller](https://magiccards.info/query?q=!Loam+Dweller)
- [x] [Mannichi, the Fevered Dream](https://magiccards.info/query?q=!Mannichi,+the+Fevered+Dream)
- [x] [Mark of Sakiko](https://magiccards.info/query?q=!Mark+of+Sakiko)
- [x] [Mark of the Oni](https://magiccards.info/query?q=!Mark+of+the+Oni)
- [x] [Matsu-Tribe Sniper](https://magiccards.info/query?q=!Matsu-Tribe+Sniper)
- [x] [Mending Hands](https://magiccards.info/query?q=!Mending+Hands)
- [x] [Minamo Sightbender](https://magiccards.info/query?q=!Minamo+Sightbender)
- [x] [Minamo's Meddling](https://magiccards.info/query?q=!Minamo's+Meddling)
- [x] [Mirror Gallery](https://magiccards.info/query?q=!Mirror+Gallery)
- [x] [Mistblade Shinobi](https://magiccards.info/query?q=!Mistblade+Shinobi)
- [x] [Moonlit Strider](https://magiccards.info/query?q=!Moonlit+Strider)
- [x] [Neko-Te](https://magiccards.info/query?q=!Neko-Te)
- [x] [Nezumi Shadow-Watcher](https://magiccards.info/query?q=!Nezumi+Shadow-Watcher)
- [x] [Ninja of the Deep Hours](https://magiccards.info/query?q=!Ninja+of+the+Deep+Hours)
- [x] [Nourishing Shoal](https://magiccards.info/query?q=!Nourishing+Shoal)
- [x] [Ogre Marauder](https://magiccards.info/query?q=!Ogre+Marauder)
- [x] [Ogre Recluse](https://magiccards.info/query?q=!Ogre+Recluse)
- [x] [Okiba-Gang Shinobi](https://magiccards.info/query?q=!Okiba-Gang+Shinobi)
- [x] [Opal-Eye, Konda's Yojimbo](https://magiccards.info/query?q=!Opal-Eye,+Konda's+Yojimbo)
- [x] [Orb of Dreams](https://magiccards.info/query?q=!Orb+of+Dreams)
- [x] [Ornate Kanzashi](https://magiccards.info/query?q=!Ornate+Kanzashi)
- [x] [Overblaze](https://magiccards.info/query?q=!Overblaze)
- [x] [Oyobi, Who Split the Heavens](https://magiccards.info/query?q=!Oyobi,+Who+Split+the+Heavens)
- [x] [Patron of the Akki](https://magiccards.info/query?q=!Patron+of+the+Akki)
- [x] [Patron of the Kitsune](https://magiccards.info/query?q=!Patron+of+the+Kitsune)
- [x] [Patron of the Moon](https://magiccards.info/query?q=!Patron+of+the+Moon)
- [x] [Patron of the Nezumi](https://magiccards.info/query?q=!Patron+of+the+Nezumi)
- [x] [Patron of the Orochi](https://magiccards.info/query?q=!Patron+of+the+Orochi)
- [x] [Petalmane Baku](https://magiccards.info/query?q=!Petalmane+Baku)
- [x] [Phantom Wings](https://magiccards.info/query?q=!Phantom+Wings)
- [x] [Psychic Spear](https://magiccards.info/query?q=!Psychic+Spear)
- [x] [Pus Kami](https://magiccards.info/query?q=!Pus+Kami)
- [x] [Quash](https://magiccards.info/query?q=!Quash)
- [x] [Quillmane Baku](https://magiccards.info/query?q=!Quillmane+Baku)
- [x] [Reduce to Dreams](https://magiccards.info/query?q=!Reduce+to+Dreams)
- [x] [Ribbons of the Reikai](https://magiccards.info/query?q=!Ribbons+of+the+Reikai)
- [x] [Roar of Jukai](https://magiccards.info/query?q=!Roar+of+Jukai)
- [x] [Ronin Cliffrider](https://magiccards.info/query?q=!Ronin+Cliffrider)
- [x] [Ronin Warclub](https://magiccards.info/query?q=!Ronin+Warclub)
- [x] [Sakiko, Mother of Summer](https://magiccards.info/query?q=!Sakiko,+Mother+of+Summer)
- [x] [Sakura-Tribe Springcaller](https://magiccards.info/query?q=!Sakura-Tribe+Springcaller)
- [x] [Scaled Hulk](https://magiccards.info/query?q=!Scaled+Hulk)
- [x] [Scour](https://magiccards.info/query?q=!Scour)
- [x] [Scourge of Numai](https://magiccards.info/query?q=!Scourge+of+Numai)
- [x] [Shimmering Glasskite](https://magiccards.info/query?q=!Shimmering+Glasskite)
- [x] [Shining Shoal](https://magiccards.info/query?q=!Shining+Shoal)
- [x] [Shinka Gatekeeper](https://magiccards.info/query?q=!Shinka+Gatekeeper)
- [x] [Shirei, Shizo's Caretaker](https://magiccards.info/query?q=!Shirei,+Shizo's+Caretaker)
- [x] [Shizuko, Caller of Autumn](https://magiccards.info/query?q=!Shizuko,+Caller+of+Autumn)
- [x] [Shuko](https://magiccards.info/query?q=!Shuko)
- [x] [Shuriken](https://magiccards.info/query?q=!Shuriken)
- [x] [Sickening Shoal](https://magiccards.info/query?q=!Sickening+Shoal)
- [x] [Silverstorm Samurai](https://magiccards.info/query?q=!Silverstorm+Samurai)
- [x] [Skullmane Baku](https://magiccards.info/query?q=!Skullmane+Baku)
- [x] [Skullsnatcher](https://magiccards.info/query?q=!Skullsnatcher)
- [x] [Slumbering Tora](https://magiccards.info/query?q=!Slumbering+Tora)
- [x] [Soratami Mindsweeper](https://magiccards.info/query?q=!Soratami+Mindsweeper)
- [x] [Sosuke's Summons](https://magiccards.info/query?q=!Sosuke's+Summons)
- [x] [Sowing Salt](https://magiccards.info/query?q=!Sowing+Salt)
- [x] [Splinter](https://magiccards.info/query?q=!Splinter)
- [x] [Split-Tail Miko](https://magiccards.info/query?q=!Split-Tail+Miko)
- [x] [Stir the Grave](https://magiccards.info/query?q=!Stir+the+Grave)
- [x] [Stream of Consciousness](https://magiccards.info/query?q=!Stream+of+Consciousness)
- [x] [Sway of the Stars](https://magiccards.info/query?q=!Sway+of+the+Stars)
- [x] [Takeno's Cavalry](https://magiccards.info/query?q=!Takeno's+Cavalry)
- [x] [Takenuma Bleeder](https://magiccards.info/query?q=!Takenuma+Bleeder)
- [x] [Tallowisp](https://magiccards.info/query?q=!Tallowisp)
- [x] [Teardrop Kami](https://magiccards.info/query?q=!Teardrop+Kami)
- [x] [Tendo Ice Bridge](https://magiccards.info/query?q=!Tendo+Ice+Bridge)
- [x] [Terashi's Grasp](https://magiccards.info/query?q=!Terashi's+Grasp)
- [x] [Terashi's Verdict](https://magiccards.info/query?q=!Terashi's+Verdict)
- [x] [That Which Was Taken](https://magiccards.info/query?q=!That+Which+Was+Taken)
- [x] [Threads of Disloyalty](https://magiccards.info/query?q=!Threads+of+Disloyalty)
- [x] [Three Tragedies](https://magiccards.info/query?q=!Three+Tragedies)
- [x] [Throat Slitter](https://magiccards.info/query?q=!Throat+Slitter)
- [x] [Toils of Night and Day](https://magiccards.info/query?q=!Toils+of+Night+and+Day)
- [x] [Tomorrow, Azami's Familiar](https://magiccards.info/query?q=!Tomorrow,+Azami's+Familiar)
- [x] [Torrent of Stone](https://magiccards.info/query?q=!Torrent+of+Stone)
- [x] [Toshiro Umezawa](https://magiccards.info/query?q=!Toshiro+Umezawa)
- [x] [Traproot Kami](https://magiccards.info/query?q=!Traproot+Kami)
- [x] [Twist Allegiance](https://magiccards.info/query?q=!Twist+Allegiance)
- [x] [Umezawa's Jitte](https://magiccards.info/query?q=!Umezawa's+Jitte)
- [x] [Unchecked Growth](https://magiccards.info/query?q=!Unchecked+Growth)
- [x] [Uproot](https://magiccards.info/query?q=!Uproot)
- [x] [Veil of Secrecy](https://magiccards.info/query?q=!Veil+of+Secrecy)
- [x] [Vital Surge](https://magiccards.info/query?q=!Vital+Surge)
- [x] [Walker of Secret Ways](https://magiccards.info/query?q=!Walker+of+Secret+Ways)
- [x] [Ward of Piety](https://magiccards.info/query?q=!Ward+of+Piety)
- [x] [Waxmane Baku](https://magiccards.info/query?q=!Waxmane+Baku)
- [x] [Yomiji, Who Bars the Way](https://magiccards.info/query?q=!Yomiji,+Who+Bars+the+Way)
- [x] [Yukora, the Prisoner](https://magiccards.info/query?q=!Yukora,+the+Prisoner)
