### ISSUE TITLE
SOK - Saviors of Kamigawa set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4929]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/saviors-of-kamigawa

# Unimplemented cards

- none

# Cards in set:
- [x] [AEther Shockwave](https://magiccards.info/query?q=!AEther+Shockwave)
- [x] [Adamaro, First to Desire](https://magiccards.info/query?q=!Adamaro,+First+to+Desire)
- [x] [Akki Drillmaster](https://magiccards.info/query?q=!Akki+Drillmaster)
- [x] [Akki Underling](https://magiccards.info/query?q=!Akki+Underling)
- [x] [Akuta, Born of Ash](https://magiccards.info/query?q=!Akuta,+Born+of+Ash)
- [x] [Araba Mothrider](https://magiccards.info/query?q=!Araba+Mothrider)
- [x] [Arashi, the Sky Asunder](https://magiccards.info/query?q=!Arashi,+the+Sky+Asunder)
- [x] [Ashes of the Fallen](https://magiccards.info/query?q=!Ashes+of+the+Fallen)
- [x] [Ayumi, the Last Visitor](https://magiccards.info/query?q=!Ayumi,+the+Last+Visitor)
- [x] [Barrel Down Sokenzan](https://magiccards.info/query?q=!Barrel+Down+Sokenzan)
- [x] [Blood Clock](https://magiccards.info/query?q=!Blood+Clock)
- [x] [Bounteous Kirin](https://magiccards.info/query?q=!Bounteous+Kirin)
- [x] [Briarknit Kami](https://magiccards.info/query?q=!Briarknit+Kami)
- [x] [Burning-Eye Zubera](https://magiccards.info/query?q=!Burning-Eye+Zubera)
- [x] [Captive Flame](https://magiccards.info/query?q=!Captive+Flame)
- [x] [Celestial Kirin](https://magiccards.info/query?q=!Celestial+Kirin)
- [x] [Charge Across the Araba](https://magiccards.info/query?q=!Charge+Across+the+Araba)
- [x] [Choice of Damnations](https://magiccards.info/query?q=!Choice+of+Damnations)
- [x] [Cloudhoof Kirin](https://magiccards.info/query?q=!Cloudhoof+Kirin)
- [x] [Cowed by Wisdom](https://magiccards.info/query?q=!Cowed+by+Wisdom)
- [x] [Curtain of Light](https://magiccards.info/query?q=!Curtain+of+Light)
- [x] [Cut the Earthly Bond](https://magiccards.info/query?q=!Cut+the+Earthly+Bond)
- [x] [Death Denied](https://magiccards.info/query?q=!Death+Denied)
- [x] [Death of a Thousand Stings](https://magiccards.info/query?q=!Death+of+a+Thousand+Stings)
- [x] [Deathknell Kami](https://magiccards.info/query?q=!Deathknell+Kami)
- [x] [Deathmask Nezumi](https://magiccards.info/query?q=!Deathmask+Nezumi)
- [x] [Dense Canopy](https://magiccards.info/query?q=!Dense+Canopy)
- [x] [Descendant of Kiyomaro](https://magiccards.info/query?q=!Descendant+of+Kiyomaro)
- [x] [Descendant of Masumaro](https://magiccards.info/query?q=!Descendant+of+Masumaro)
- [x] [Descendant of Soramaro](https://magiccards.info/query?q=!Descendant+of+Soramaro)
- [x] [Dosan's Oldest Chant](https://magiccards.info/query?q=!Dosan's+Oldest+Chant)
- [x] [Dreamcatcher](https://magiccards.info/query?q=!Dreamcatcher)
- [x] [Ebony Owl Netsuke](https://magiccards.info/query?q=!Ebony+Owl+Netsuke)
- [x] [Eiganjo Free-Riders](https://magiccards.info/query?q=!Eiganjo+Free-Riders)
- [x] [Elder Pine of Jukai](https://magiccards.info/query?q=!Elder+Pine+of+Jukai)
- [x] [Endless Swarm](https://magiccards.info/query?q=!Endless+Swarm)
- [x] [Enduring Ideal](https://magiccards.info/query?q=!Enduring+Ideal)
- [x] [Erayo's Essence](https://magiccards.info/query?q=!Erayo's+Essence)
- [x] [Erayo, Soratami Ascendant](https://magiccards.info/query?q=!Erayo,+Soratami+Ascendant)
- [x] [Eternal Dominion](https://magiccards.info/query?q=!Eternal+Dominion)
- [x] [Evermind](https://magiccards.info/query?q=!Evermind)
- [x] [Exile into Darkness](https://magiccards.info/query?q=!Exile+into+Darkness)
- [x] [Feral Lightning](https://magiccards.info/query?q=!Feral+Lightning)
- [x] [Fiddlehead Kami](https://magiccards.info/query?q=!Fiddlehead+Kami)
- [x] [Footsteps of the Goryo](https://magiccards.info/query?q=!Footsteps+of+the+Goryo)
- [x] [Freed from the Real](https://magiccards.info/query?q=!Freed+from+the+Real)
- [x] [Gaze of Adamaro](https://magiccards.info/query?q=!Gaze+of+Adamaro)
- [x] [Ghost-Lit Nourisher](https://magiccards.info/query?q=!Ghost-Lit+Nourisher)
- [x] [Ghost-Lit Raider](https://magiccards.info/query?q=!Ghost-Lit+Raider)
- [x] [Ghost-Lit Redeemer](https://magiccards.info/query?q=!Ghost-Lit+Redeemer)
- [x] [Ghost-Lit Stalker](https://magiccards.info/query?q=!Ghost-Lit+Stalker)
- [x] [Ghost-Lit Warder](https://magiccards.info/query?q=!Ghost-Lit+Warder)
- [x] [Glitterfang](https://magiccards.info/query?q=!Glitterfang)
- [x] [Gnat Miser](https://magiccards.info/query?q=!Gnat+Miser)
- [x] [Godo's Irregulars](https://magiccards.info/query?q=!Godo's+Irregulars)
- [x] [Hail of Arrows](https://magiccards.info/query?q=!Hail+of+Arrows)
- [x] [Hand of Cruelty](https://magiccards.info/query?q=!Hand+of+Cruelty)
- [x] [Hand of Honor](https://magiccards.info/query?q=!Hand+of+Honor)
- [x] [Haru-Onna](https://magiccards.info/query?q=!Haru-Onna)
- [x] [Hidetsugu's Second Rite](https://magiccards.info/query?q=!Hidetsugu's+Second+Rite)
- [x] [Homura's Essence](https://magiccards.info/query?q=!Homura's+Essence)
- [x] [Homura, Human Ascendant](https://magiccards.info/query?q=!Homura,+Human+Ascendant)
- [x] [Ideas Unbound](https://magiccards.info/query?q=!Ideas+Unbound)
- [x] [Iizuka the Ruthless](https://magiccards.info/query?q=!Iizuka+the+Ruthless)
- [x] [Iname as One](https://magiccards.info/query?q=!Iname+as+One)
- [x] [Infernal Kirin](https://magiccards.info/query?q=!Infernal+Kirin)
- [x] [Inner Calm, Outer Strength](https://magiccards.info/query?q=!Inner+Calm,+Outer+Strength)
- [x] [Inner Fire](https://magiccards.info/query?q=!Inner+Fire)
- [x] [Inner-Chamber Guard](https://magiccards.info/query?q=!Inner-Chamber+Guard)
- [x] [Into the Fray](https://magiccards.info/query?q=!Into+the+Fray)
- [x] [Ivory Crane Netsuke](https://magiccards.info/query?q=!Ivory+Crane+Netsuke)
- [x] [Jiwari, the Earth Aflame](https://magiccards.info/query?q=!Jiwari,+the+Earth+Aflame)
- [x] [Kagemaro's Clutch](https://magiccards.info/query?q=!Kagemaro's+Clutch)
- [x] [Kagemaro, First to Suffer](https://magiccards.info/query?q=!Kagemaro,+First+to+Suffer)
- [x] [Kaho, Minamo Historian](https://magiccards.info/query?q=!Kaho,+Minamo+Historian)
- [x] [Kami of Empty Graves](https://magiccards.info/query?q=!Kami+of+Empty+Graves)
- [x] [Kami of the Crescent Moon](https://magiccards.info/query?q=!Kami+of+the+Crescent+Moon)
- [x] [Kami of the Tended Garden](https://magiccards.info/query?q=!Kami+of+the+Tended+Garden)
- [x] [Kashi-Tribe Elite](https://magiccards.info/query?q=!Kashi-Tribe+Elite)
- [x] [Kataki, War's Wage](https://magiccards.info/query?q=!Kataki,+War's+Wage)
- [x] [Kemuri-Onna](https://magiccards.info/query?q=!Kemuri-Onna)
- [x] [Kiku's Shadow](https://magiccards.info/query?q=!Kiku's+Shadow)
- [x] [Kiri-Onna](https://magiccards.info/query?q=!Kiri-Onna)
- [x] [Kitsune Bonesetter](https://magiccards.info/query?q=!Kitsune+Bonesetter)
- [x] [Kitsune Dawnblade](https://magiccards.info/query?q=!Kitsune+Dawnblade)
- [x] [Kitsune Loreweaver](https://magiccards.info/query?q=!Kitsune+Loreweaver)
- [x] [Kiyomaro, First to Stand](https://magiccards.info/query?q=!Kiyomaro,+First+to+Stand)
- [x] [Kuon's Essence](https://magiccards.info/query?q=!Kuon's+Essence)
- [x] [Kuon, Ogre Ascendant](https://magiccards.info/query?q=!Kuon,+Ogre+Ascendant)
- [x] [Kuro's Taken](https://magiccards.info/query?q=!Kuro's+Taken)
- [x] [Locust Miser](https://magiccards.info/query?q=!Locust+Miser)
- [x] [Maga, Traitor to Mortals](https://magiccards.info/query?q=!Maga,+Traitor+to+Mortals)
- [x] [Manriki-Gusari](https://magiccards.info/query?q=!Manriki-Gusari)
- [x] [Masumaro, First to Live](https://magiccards.info/query?q=!Masumaro,+First+to+Live)
- [x] [Matsu-Tribe Birdstalker](https://magiccards.info/query?q=!Matsu-Tribe+Birdstalker)
- [x] [Measure of Wickedness](https://magiccards.info/query?q=!Measure+of+Wickedness)
- [x] [Meishin, the Mind Cage](https://magiccards.info/query?q=!Meishin,+the+Mind+Cage)
- [x] [Michiko Konda, Truth Seeker](https://magiccards.info/query?q=!Michiko+Konda,+Truth+Seeker)
- [x] [Mikokoro, Center of the Sea](https://magiccards.info/query?q=!Mikokoro,+Center+of+the+Sea)
- [x] [Minamo Scrollkeeper](https://magiccards.info/query?q=!Minamo+Scrollkeeper)
- [x] [Miren, the Moaning Well](https://magiccards.info/query?q=!Miren,+the+Moaning+Well)
- [x] [Molting Skin](https://magiccards.info/query?q=!Molting+Skin)
- [x] [Moonbow Illusionist](https://magiccards.info/query?q=!Moonbow+Illusionist)
- [x] [Moonwing Moth](https://magiccards.info/query?q=!Moonwing+Moth)
- [x] [Murmurs from Beyond](https://magiccards.info/query?q=!Murmurs+from+Beyond)
- [x] [Neverending Torment](https://magiccards.info/query?q=!Neverending+Torment)
- [x] [Nightsoil Kami](https://magiccards.info/query?q=!Nightsoil+Kami)
- [x] [Nikko-Onna](https://magiccards.info/query?q=!Nikko-Onna)
- [x] [O-Naginata](https://magiccards.info/query?q=!O-Naginata)
- [x] [Oboro Breezecaller](https://magiccards.info/query?q=!Oboro+Breezecaller)
- [x] [Oboro Envoy](https://magiccards.info/query?q=!Oboro+Envoy)
- [x] [Oboro, Palace in the Clouds](https://magiccards.info/query?q=!Oboro,+Palace+in+the+Clouds)
- [x] [Okina Nightwatch](https://magiccards.info/query?q=!Okina+Nightwatch)
- [x] [One with Nothing](https://magiccards.info/query?q=!One+with+Nothing)
- [x] [Oni of Wild Places](https://magiccards.info/query?q=!Oni+of+Wild+Places)
- [x] [Oppressive Will](https://magiccards.info/query?q=!Oppressive+Will)
- [x] [Overwhelming Intellect](https://magiccards.info/query?q=!Overwhelming+Intellect)
- [x] [Pain's Reward](https://magiccards.info/query?q=!Pain's+Reward)
- [x] [Path of Anger's Flame](https://magiccards.info/query?q=!Path+of+Anger's+Flame)
- [x] [Pithing Needle](https://magiccards.info/query?q=!Pithing+Needle)
- [x] [Plow Through Reito](https://magiccards.info/query?q=!Plow+Through+Reito)
- [x] [Presence of the Wise](https://magiccards.info/query?q=!Presence+of+the+Wise)
- [x] [Promise of Bunrei](https://magiccards.info/query?q=!Promise+of+Bunrei)
- [x] [Promised Kannushi](https://magiccards.info/query?q=!Promised+Kannushi)
- [x] [Pure Intentions](https://magiccards.info/query?q=!Pure+Intentions)
- [x] [Rally the Horde](https://magiccards.info/query?q=!Rally+the+Horde)
- [x] [Raving Oni-Slave](https://magiccards.info/query?q=!Raving+Oni-Slave)
- [x] [Razorjaw Oni](https://magiccards.info/query?q=!Razorjaw+Oni)
- [x] [Reki, the History of Kamigawa](https://magiccards.info/query?q=!Reki,+the+History+of+Kamigawa)
- [x] [Rending Vines](https://magiccards.info/query?q=!Rending+Vines)
- [x] [Reverence](https://magiccards.info/query?q=!Reverence)
- [x] [Ronin Cavekeeper](https://magiccards.info/query?q=!Ronin+Cavekeeper)
- [x] [Rune-Tail's Essence](https://magiccards.info/query?q=!Rune-Tail's+Essence)
- [x] [Rune-Tail, Kitsune Ascendant](https://magiccards.info/query?q=!Rune-Tail,+Kitsune+Ascendant)
- [x] [Rushing-Tide Zubera](https://magiccards.info/query?q=!Rushing-Tide+Zubera)
- [x] [Sakashima the Impostor](https://magiccards.info/query?q=!Sakashima+the+Impostor)
- [x] [Sakura-Tribe Scout](https://magiccards.info/query?q=!Sakura-Tribe+Scout)
- [x] [Sasaya's Essence](https://magiccards.info/query?q=!Sasaya's+Essence)
- [x] [Sasaya, Orochi Ascendant](https://magiccards.info/query?q=!Sasaya,+Orochi+Ascendant)
- [x] [Scroll of Origins](https://magiccards.info/query?q=!Scroll+of+Origins)
- [x] [Secretkeeper](https://magiccards.info/query?q=!Secretkeeper)
- [x] [Seed the Land](https://magiccards.info/query?q=!Seed+the+Land)
- [x] [Seek the Horizon](https://magiccards.info/query?q=!Seek+the+Horizon)
- [x] [Sekki, Seasons' Guide](https://magiccards.info/query?q=!Sekki,+Seasons'+Guide)
- [x] [Shape Stealer](https://magiccards.info/query?q=!Shape+Stealer)
- [x] [Shifting Borders](https://magiccards.info/query?q=!Shifting+Borders)
- [x] [Shinen of Fear's Chill](https://magiccards.info/query?q=!Shinen+of+Fear's+Chill)
- [x] [Shinen of Flight's Wings](https://magiccards.info/query?q=!Shinen+of+Flight's+Wings)
- [x] [Shinen of Fury's Fire](https://magiccards.info/query?q=!Shinen+of+Fury's+Fire)
- [x] [Shinen of Life's Roar](https://magiccards.info/query?q=!Shinen+of+Life's+Roar)
- [x] [Shinen of Stars' Light](https://magiccards.info/query?q=!Shinen+of+Stars'+Light)
- [x] [Sink into Takenuma](https://magiccards.info/query?q=!Sink+into+Takenuma)
- [x] [Skull Collector](https://magiccards.info/query?q=!Skull+Collector)
- [x] [Skyfire Kirin](https://magiccards.info/query?q=!Skyfire+Kirin)
- [x] [Sokenzan Renegade](https://magiccards.info/query?q=!Sokenzan+Renegade)
- [x] [Sokenzan Spellblade](https://magiccards.info/query?q=!Sokenzan+Spellblade)
- [x] [Soramaro, First to Dream](https://magiccards.info/query?q=!Soramaro,+First+to+Dream)
- [x] [Soratami Cloud Chariot](https://magiccards.info/query?q=!Soratami+Cloud+Chariot)
- [x] [Spiraling Embers](https://magiccards.info/query?q=!Spiraling+Embers)
- [x] [Spiritual Visit](https://magiccards.info/query?q=!Spiritual+Visit)
- [x] [Stampeding Serow](https://magiccards.info/query?q=!Stampeding+Serow)
- [x] [Sunder from Within](https://magiccards.info/query?q=!Sunder+from+Within)
- [x] [Thoughts of Ruin](https://magiccards.info/query?q=!Thoughts+of+Ruin)
- [x] [Tomb of Urami](https://magiccards.info/query?q=!Tomb+of+Urami)
- [x] [Torii Watchward](https://magiccards.info/query?q=!Torii+Watchward)
- [x] [Trusted Advisor](https://magiccards.info/query?q=!Trusted+Advisor)
- [x] [Twincast](https://magiccards.info/query?q=!Twincast)
- [x] [Undying Flames](https://magiccards.info/query?q=!Undying+Flames)
- [x] [Wine of Blood and Iron](https://magiccards.info/query?q=!Wine+of+Blood+and+Iron)
- [x] [Yuki-Onna](https://magiccards.info/query?q=!Yuki-Onna)
