### ISSUE TITLE
Test framework: add commands for real time checks/assertions

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4936]
Current test framework can do checks (assertions) only on game's end. That's a big limit -- devs need to create plenty of tests to reproduce and check each step (e.g. you can test only final result). But with real time checks you can assert errors in the middle of the game (e.g. you can test all progress to final result).

Framework must allow to insert checks like other player commands and generate standard test errors:
 * [x] color (have or not have) -- `checkColor`;
 * [x] card type (have or not have);
 * [x] card subtype (have or not have) -- `checkSubType`;
 * [x] ability (have or not have) -- `checkAbility`;
 * [x] power and toughness -- `checkPT`;
 * [x] permanent count -- `checkPermanentCount`;
 * [x] hand count -- `checkHandCount`;
 * [x] graveyard count;
 * [x] damage
 * [x] exile count;
 * [x] command zone count;
 * [x] counters count;
 * [x] mana pool;
 * [x] player life;

Other:
 * [x] add "resolve" command to wait stack resolving in same step (cast 1, resolve, cast 2);

Code example with real time checks:
```
    public void test_DaxosGotBoostAndSaveColor() {
        addCard(Zone.HAND, playerA, daxosCard, 1);
        addCard(Zone.BATTLEFIELD, playerA, "Swamp", 4);
        //
        addCard(Zone.HAND, playerA, "Chaoslace", 1); // Target spell or permanent becomes red.
        addCard(Zone.BATTLEFIELD, playerA, "Mountain", 1);
        //
        addCard(Zone.HAND, playerA, "Archetype of Courage", 1); // Enchantment to trigger Daxos
        addCard(Zone.BATTLEFIELD, playerA, "Plains", 4);

        // dax cast
        castSpell(1, PhaseStep.PRECOMBAT_MAIN, playerA, daxosCard);
        checkPermanentCount("dax exist", 1, PhaseStep.POSTCOMBAT_MAIN, playerA, daxosCard, 1);
        checkColor("dax without color", 1, PhaseStep.POSTCOMBAT_MAIN, playerA, daxosCard, "R", false);
        // give dax new color
        castSpell(3, PhaseStep.PRECOMBAT_MAIN, playerA, "Chaoslace", daxosCard);
        checkPT("dax not boost", 3, PhaseStep.BEGIN_COMBAT, playerA, daxosCard, 0, 0);
        checkColor("dax is red", 3, PhaseStep.BEGIN_COMBAT, playerA, daxosCard, "R", true);
        // color is saved on boost
        castSpell(5, PhaseStep.PRECOMBAT_MAIN, playerA, "Archetype of Courage"); // make dax to creature
        checkPT("dax boost", 5, PhaseStep.BEGIN_COMBAT, playerA, daxosCard, 5, 5);
        checkAbility("dax fly", 5, PhaseStep.BEGIN_COMBAT, playerA, daxosCard, FlyingAbility.class, true);
        checkColor("dax is red", 5, PhaseStep.BEGIN_COMBAT, playerA, daxosCard, "R", true);

        setStopAt(5, PhaseStep.END_TURN);
        execute();
    }
```

**Comment by Zerrisx** [comment]
Is library the last command needed here?  Is it still missing?

**Comment by JayDi85** [comment]
@the-red-lily you must use `setStrictChooseMode` (test will raise error on miss choice command) and `assertAllCommandsUsed` (test will raise error on wrong/unused commands -- your use case).

Example:
``` java
setStrictChooseMode(true);
setStopAt(1, PhaseStep.BEGIN_COMBAT);
execute();
assertAllCommandsUsed();
```

**Comment by JayDi85** [comment]
BTW I recommends to write test by steps (commands group with comment): add some commands and checks, run it; add another commands and run it again. If you debug existing test then comment all commands except first and run it with additional checks (I do that a lot while debugging tests).

See `ModalDoubleFacesCardsInCommanderTest` for an example of how to write a test.

**Comment by the-red-lily** [comment]
Thanks for the tips and heads up, I'll check out that test file.

> @the-red-lily you must use `setStrictChooseMode` (test will raise error on miss choice command) and `assertAllCommandsUsed` (test will raise error on wrong/unused commands -- your use case).

Why are these modes not included by default?

**Comment by Alex-Vasile** [comment]
> Thanks for the tips and heads up, I'll check out that test file.
> 
> > @the-red-lily you must use `setStrictChooseMode` (test will raise error on miss choice command) and `assertAllCommandsUsed` (test will raise error on wrong/unused commands -- your use case).
> 
> Why are these modes not enabled by default?

I am working on enabling `assertAllCommandsUsed`. The reason it's not enabled is since many tests have errors that need fixing. (it was added after the tests were written).

The `setStrictChooseMode` is not needed for all tests since some choices are okay for the AI to autochoose (e.g only one option available).

**Comment by the-red-lily** [comment]
Is someone working on fixing those old tests? If not I could take that mantle
