### ISSUE TITLE
DIS - Dissension set card implementation tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4954]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/dissension

# Unimplemented cards

- [x] Not Done -- [Azorius Ploy](https://scryfall.com/search?q=Azorius+Ploy)
- [x] Not Done -- [Fertile Imagination](https://scryfall.com/search?q=Fertile+Imagination)
- [x] Not Done -- [Flash Foliage](https://scryfall.com/search?q=Flash+Foliage)
- [x] Not Done -- [Muse Vessel](https://scryfall.com/search?q=Muse+Vessel)
- [x] Not Done -- [Nettling Curse](https://scryfall.com/search?q=Nettling+Curse)
- [x] Not Done -- [Nightcreep](https://scryfall.com/search?q=Nightcreep)
- [x] Not Done -- [Nihilistic Glee](https://scryfall.com/search?q=Nihilistic+Glee)
- [x] Not Done -- [Rakdos Augermage](https://scryfall.com/search?q=Rakdos+Augermage)
- [x] Not Done -- [Rakdos Riteknife](https://scryfall.com/search?q=Rakdos+Riteknife)
- [x] Not Done -- [Stormscale Anarch](https://scryfall.com/search?q=Stormscale+Anarch)
- [x] Not Done -- [Street Savvy](https://scryfall.com/search?q=Street+Savvy)
- [x] Not Done -- [Swift Silence](https://scryfall.com/search?q=Swift+Silence)
- [x] Not Done -- [Vigean Intuition](https://scryfall.com/search?q=Vigean+Intuition)
- [x] Not Done -- [Weight of Spires](https://scryfall.com/search?q=Weight+of+Spires)

# Cards in set:

- [x] Done -- [Aethermage's Touch](https://scryfall.com/search?q=Aethermages+Touch)
- [x] Done -- [Anthem of Rakdos](https://scryfall.com/search?q=Anthem+of+Rakdos)
- [x] Done -- [Aquastrand Spider](https://scryfall.com/search?q=Aquastrand+Spider)
- [x] Done -- [Assault Zeppelid](https://scryfall.com/search?q=Assault+Zeppelid)
- [x] Done -- [Aurora Eidolon](https://scryfall.com/search?q=Aurora+Eidolon)
- [x] Done -- [Avatar of Discord](https://scryfall.com/search?q=Avatar+of+Discord)
- [x] Done -- [Azorius Aethermage](https://scryfall.com/search?q=Azorius+Aethermage)
- [x] Done -- [Azorius Chancery](https://scryfall.com/search?q=Azorius+Chancery)
- [x] Done -- [Azorius First-Wing](https://scryfall.com/search?q=Azorius+First-Wing)
- [x] Done -- [Azorius Guildmage](https://scryfall.com/search?q=Azorius+Guildmage)
- [x] Done -- [Azorius Herald](https://scryfall.com/search?q=Azorius+Herald)
- [x] Done -- [Azorius Signet](https://scryfall.com/search?q=Azorius+Signet)
- [x] Done -- [Beacon Hawk](https://scryfall.com/search?q=Beacon+Hawk)
- [x] Done -- [Biomantic Mastery](https://scryfall.com/search?q=Biomantic+Mastery)
- [x] Done -- [Blessing of the Nephilim](https://scryfall.com/search?q=Blessing+of+the+Nephilim)
- [x] Done -- [Blood Crypt](https://scryfall.com/search?q=Blood+Crypt)
- [x] Done -- [Bond of Agony](https://scryfall.com/search?q=Bond+of+Agony)
- [x] Done -- [Bound // Determined](https://scryfall.com/search?q=Bound+//+Determined)
- [x] Done -- [Brace for Impact](https://scryfall.com/search?q=Brace+for+Impact)
- [x] Done -- [Brain Pry](https://scryfall.com/search?q=Brain+Pry)
- [x] Done -- [Breeding Pool](https://scryfall.com/search?q=Breeding+Pool)
- [x] Done -- [Bronze Bombshell](https://scryfall.com/search?q=Bronze+Bombshell)
- [x] Done -- [Cackling Flames](https://scryfall.com/search?q=Cackling+Flames)
- [x] Done -- [Carom](https://scryfall.com/search?q=Carom)
- [x] Done -- [Celestial Ancient](https://scryfall.com/search?q=Celestial+Ancient)
- [x] Done -- [Coiling Oracle](https://scryfall.com/search?q=Coiling+Oracle)
- [x] Done -- [Condemn](https://scryfall.com/search?q=Condemn)
- [x] Done -- [Court Hussar](https://scryfall.com/search?q=Court+Hussar)
- [x] Done -- [Crime // Punishment](https://scryfall.com/search?q=Crime+//+Punishment)
- [x] Done -- [Crypt Champion](https://scryfall.com/search?q=Crypt+Champion)
- [x] Done -- [Cytoplast Manipulator](https://scryfall.com/search?q=Cytoplast+Manipulator)
- [x] Done -- [Cytoplast Root-Kin](https://scryfall.com/search?q=Cytoplast+Root-Kin)
- [x] Done -- [Cytoshape](https://scryfall.com/search?q=Cytoshape)
- [x] Done -- [Cytospawn Shambler](https://scryfall.com/search?q=Cytospawn+Shambler)
- [x] Done -- [Delirium Skeins](https://scryfall.com/search?q=Delirium+Skeins)
- [x] Done -- [Demon's Jester](https://scryfall.com/search?q=Demons+Jester)
- [x] Done -- [Demonfire](https://scryfall.com/search?q=Demonfire)
- [x] Done -- [Dovescape](https://scryfall.com/search?q=Dovescape)
- [x] Done -- [Dread Slag](https://scryfall.com/search?q=Dread+Slag)
- [x] Done -- [Drekavac](https://scryfall.com/search?q=Drekavac)
- [x] Done -- [Elemental Resonance](https://scryfall.com/search?q=Elemental+Resonance)
- [x] Done -- [Enemy of the Guildpact](https://scryfall.com/search?q=Enemy+of+the+Guildpact)
- [x] Done -- [Enigma Eidolon](https://scryfall.com/search?q=Enigma+Eidolon)
- [x] Done -- [Entropic Eidolon](https://scryfall.com/search?q=Entropic+Eidolon)
- [x] Done -- [Evolution Vat](https://scryfall.com/search?q=Evolution+Vat)
- [x] Done -- [Experiment Kraj](https://scryfall.com/search?q=Experiment+Kraj)
- [x] Done -- [Flame-Kin War Scout](https://scryfall.com/search?q=Flame-Kin+War+Scout)
- [x] Done -- [Flaring Flame-Kin](https://scryfall.com/search?q=Flaring+Flame-Kin)
- [x] Done -- [Freewind Equenaut](https://scryfall.com/search?q=Freewind+Equenaut)
- [x] Done -- [Ghost Quarter](https://scryfall.com/search?q=Ghost+Quarter)
- [x] Done -- [Gnat Alley Creeper](https://scryfall.com/search?q=Gnat+Alley+Creeper)
- [x] Done -- [Gobhobbler Rats](https://scryfall.com/search?q=Gobhobbler+Rats)
- [x] Done -- [Govern the Guildless](https://scryfall.com/search?q=Govern+the+Guildless)
- [x] Done -- [Grand Arbiter Augustin IV](https://scryfall.com/search?q=Grand+Arbiter+Augustin+IV)
- [x] Done -- [Guardian of the Guildpact](https://scryfall.com/search?q=Guardian+of+the+Guildpact)
- [x] Done -- [Haazda Exonerator](https://scryfall.com/search?q=Haazda+Exonerator)
- [x] Done -- [Haazda Shield Mate](https://scryfall.com/search?q=Haazda+Shield+Mate)
- [x] Done -- [Hallowed Fountain](https://scryfall.com/search?q=Hallowed+Fountain)
- [x] Done -- [Helium Squirter](https://scryfall.com/search?q=Helium+Squirter)
- [x] Done -- [Hellhole Rats](https://scryfall.com/search?q=Hellhole+Rats)
- [x] Done -- [Hide // Seek](https://scryfall.com/search?q=Hide+//+Seek)
- [x] Done -- [Hit // Run](https://scryfall.com/search?q=Hit+//+Run)
- [x] Done -- [Ignorant Bliss](https://scryfall.com/search?q=Ignorant+Bliss)
- [x] Done -- [Indrik Stomphowler](https://scryfall.com/search?q=Indrik+Stomphowler)
- [x] Done -- [Infernal Tutor](https://scryfall.com/search?q=Infernal+Tutor)
- [x] Done -- [Isperia the Inscrutable](https://scryfall.com/search?q=Isperia+the+Inscrutable)
- [x] Done -- [Jagged Poppet](https://scryfall.com/search?q=Jagged+Poppet)
- [x] Done -- [Kill-Suit Cultist](https://scryfall.com/search?q=Kill-Suit+Cultist)
- [x] Done -- [Kindle the Carnage](https://scryfall.com/search?q=Kindle+the+Carnage)
- [x] Done -- [Leafdrake Roost](https://scryfall.com/search?q=Leafdrake+Roost)
- [x] Done -- [Loaming Shaman](https://scryfall.com/search?q=Loaming+Shaman)
- [x] Done -- [Lyzolda, the Blood Witch](https://scryfall.com/search?q=Lyzolda,+the+Blood+Witch)
- [x] Done -- [Macabre Waltz](https://scryfall.com/search?q=Macabre+Waltz)
- [x] Done -- [Magewright's Stone](https://scryfall.com/search?q=Magewrights+Stone)
- [x] Done -- [Might of the Nephilim](https://scryfall.com/search?q=Might+of+the+Nephilim)
- [x] Done -- [Minister of Impediments](https://scryfall.com/search?q=Minister+of+Impediments)
- [x] Done -- [Mistral Charger](https://scryfall.com/search?q=Mistral+Charger)
- [x] Done -- [Momir Vig, Simic Visionary](https://scryfall.com/search?q=Momir+Vig,+Simic+Visionary)
- [x] Done -- [Novijen Sages](https://scryfall.com/search?q=Novijen+Sages)
- [x] Done -- [Novijen, Heart of Progress](https://scryfall.com/search?q=Novijen,+Heart+of+Progress)
- [x] Done -- [Ocular Halo](https://scryfall.com/search?q=Ocular+Halo)
- [x] Done -- [Odds // Ends](https://scryfall.com/search?q=Odds+//+Ends)
- [x] Done -- [Ogre Gatecrasher](https://scryfall.com/search?q=Ogre+Gatecrasher)
- [x] Done -- [Omnibian](https://scryfall.com/search?q=Omnibian)
- [x] Done -- [Overrule](https://scryfall.com/search?q=Overrule)
- [x] Done -- [Pain Magnification](https://scryfall.com/search?q=Pain+Magnification)
- [x] Done -- [Paladin of Prahv](https://scryfall.com/search?q=Paladin+of+Prahv)
- [x] Done -- [Palliation Accord](https://scryfall.com/search?q=Palliation+Accord)
- [x] Done -- [Patagia Viper](https://scryfall.com/search?q=Patagia+Viper)
- [x] Done -- [Pillar of the Paruns](https://scryfall.com/search?q=Pillar+of+the+Paruns)
- [x] Done -- [Plaxcaster Frogling](https://scryfall.com/search?q=Plaxcaster+Frogling)
- [x] Done -- [Plaxmanta](https://scryfall.com/search?q=Plaxmanta)
- [x] Done -- [Plumes of Peace](https://scryfall.com/search?q=Plumes+of+Peace)
- [x] Done -- [Prahv, Spires of Order](https://scryfall.com/search?q=Prahv,+Spires+of+Order)
- [x] Done -- [Pride of the Clouds](https://scryfall.com/search?q=Pride+of+the+Clouds)
- [x] Done -- [Proclamation of Rebirth](https://scryfall.com/search?q=Proclamation+of+Rebirth)
- [x] Done -- [Proper Burial](https://scryfall.com/search?q=Proper+Burial)
- [x] Done -- [Protean Hulk](https://scryfall.com/search?q=Protean+Hulk)
- [x] Done -- [Psychic Possession](https://scryfall.com/search?q=Psychic+Possession)
- [x] Done -- [Psychotic Fury](https://scryfall.com/search?q=Psychotic+Fury)
- [x] Done -- [Pure // Simple](https://scryfall.com/search?q=Pure+//+Simple)
- [x] Done -- [Ragamuffyn](https://scryfall.com/search?q=Ragamuffyn)
- [x] Done -- [Rain of Gore](https://scryfall.com/search?q=Rain+of+Gore)
- [x] Done -- [Rakdos Carnarium](https://scryfall.com/search?q=Rakdos+Carnarium)
- [x] Done -- [Rakdos Guildmage](https://scryfall.com/search?q=Rakdos+Guildmage)
- [x] Done -- [Rakdos Ickspitter](https://scryfall.com/search?q=Rakdos+Ickspitter)
- [x] Done -- [Rakdos Pit Dragon](https://scryfall.com/search?q=Rakdos+Pit+Dragon)
- [x] Done -- [Rakdos Signet](https://scryfall.com/search?q=Rakdos+Signet)
- [x] Done -- [Rakdos the Defiler](https://scryfall.com/search?q=Rakdos+the+Defiler)
- [x] Done -- [Ratcatcher](https://scryfall.com/search?q=Ratcatcher)
- [x] Done -- [Research // Development](https://scryfall.com/search?q=Research+//+Development)
- [x] Done -- [Riot Spikes](https://scryfall.com/search?q=Riot+Spikes)
- [x] Done -- [Rise // Fall](https://scryfall.com/search?q=Rise+//+Fall)
- [x] Done -- [Rix Maadi, Dungeon Palace](https://scryfall.com/search?q=Rix+Maadi,+Dungeon+Palace)
- [x] Done -- [Sandstorm Eidolon](https://scryfall.com/search?q=Sandstorm+Eidolon)
- [x] Done -- [Seal of Doom](https://scryfall.com/search?q=Seal+of+Doom)
- [x] Done -- [Seal of Fire](https://scryfall.com/search?q=Seal+of+Fire)
- [x] Done -- [Shielding Plax](https://scryfall.com/search?q=Shielding+Plax)
- [x] Done -- [Silkwing Scout](https://scryfall.com/search?q=Silkwing+Scout)
- [x] Done -- [Simic Basilisk](https://scryfall.com/search?q=Simic+Basilisk)
- [x] Done -- [Simic Growth Chamber](https://scryfall.com/search?q=Simic+Growth+Chamber)
- [x] Done -- [Simic Guildmage](https://scryfall.com/search?q=Simic+Guildmage)
- [x] Done -- [Simic Initiate](https://scryfall.com/search?q=Simic+Initiate)
- [x] Done -- [Simic Ragworm](https://scryfall.com/search?q=Simic+Ragworm)
- [x] Done -- [Simic Signet](https://scryfall.com/search?q=Simic+Signet)
- [x] Done -- [Simic Sky Swallower](https://scryfall.com/search?q=Simic+Sky+Swallower)
- [x] Done -- [Skullmead Cauldron](https://scryfall.com/search?q=Skullmead+Cauldron)
- [x] Done -- [Sky Hussar](https://scryfall.com/search?q=Sky+Hussar)
- [x] Done -- [Skyscribing](https://scryfall.com/search?q=Skyscribing)
- [x] Done -- [Slaughterhouse Bouncer](https://scryfall.com/search?q=Slaughterhouse+Bouncer)
- [x] Done -- [Slithering Shade](https://scryfall.com/search?q=Slithering+Shade)
- [x] Done -- [Soulsworn Jury](https://scryfall.com/search?q=Soulsworn+Jury)
- [x] Done -- [Spell Snare](https://scryfall.com/search?q=Spell+Snare)
- [x] Done -- [Sporeback Troll](https://scryfall.com/search?q=Sporeback+Troll)
- [x] Done -- [Sprouting Phytohydra](https://scryfall.com/search?q=Sprouting+Phytohydra)
- [x] Done -- [Squealing Devil](https://scryfall.com/search?q=Squealing+Devil)
- [x] Done -- [Stalking Vengeance](https://scryfall.com/search?q=Stalking+Vengeance)
- [x] Done -- [Steeling Stance](https://scryfall.com/search?q=Steeling+Stance)
- [x] Done -- [Stoic Ephemera](https://scryfall.com/search?q=Stoic+Ephemera)
- [x] Done -- [Stomp and Howl](https://scryfall.com/search?q=Stomp+and+Howl)
- [x] Done -- [Supply // Demand](https://scryfall.com/search?q=Supply+//+Demand)
- [x] Done -- [Taste for Mayhem](https://scryfall.com/search?q=Taste+for+Mayhem)
- [x] Done -- [Thrive](https://scryfall.com/search?q=Thrive)
- [x] Done -- [Tidespout Tyrant](https://scryfall.com/search?q=Tidespout+Tyrant)
- [x] Done -- [Transguild Courier](https://scryfall.com/search?q=Transguild+Courier)
- [x] Done -- [Trial // Error](https://scryfall.com/search?q=Trial+//+Error)
- [x] Done -- [Trygon Predator](https://scryfall.com/search?q=Trygon+Predator)
- [x] Done -- [Twinstrike](https://scryfall.com/search?q=Twinstrike)
- [x] Done -- [Unliving Psychopath](https://scryfall.com/search?q=Unliving+Psychopath)
- [x] Done -- [Utopia Sprawl](https://scryfall.com/search?q=Utopia+Sprawl)
- [x] Done -- [Utvara Scalper](https://scryfall.com/search?q=Utvara+Scalper)
- [x] Done -- [Valor Made Real](https://scryfall.com/search?q=Valor+Made+Real)
- [x] Done -- [Verdant Eidolon](https://scryfall.com/search?q=Verdant+Eidolon)
- [x] Done -- [Vesper Ghoul](https://scryfall.com/search?q=Vesper+Ghoul)
- [x] Done -- [Vigean Graftmage](https://scryfall.com/search?q=Vigean+Graftmage)
- [x] Done -- [Vigean Hydropon](https://scryfall.com/search?q=Vigean+Hydropon)
- [x] Done -- [Vision Skeins](https://scryfall.com/search?q=Vision+Skeins)
- [x] Done -- [Voidslime](https://scryfall.com/search?q=Voidslime)
- [x] Done -- [Wakestone Gargoyle](https://scryfall.com/search?q=Wakestone+Gargoyle)
- [x] Done -- [Walking Archive](https://scryfall.com/search?q=Walking+Archive)
- [x] Done -- [War's Toll](https://scryfall.com/search?q=Wars+Toll)
- [x] Done -- [Whiptail Moloch](https://scryfall.com/search?q=Whiptail+Moloch)
- [x] Done -- [Windreaver](https://scryfall.com/search?q=Windreaver)
- [x] Done -- [Wit's End](https://scryfall.com/search?q=Wits+End)
- [x] Done -- [Wrecking Ball](https://scryfall.com/search?q=Wrecking+Ball)
- [x] Done -- [Writ of Passage](https://scryfall.com/search?q=Writ+of+Passage)

**Comment by NoahGleason** [comment]
Okay, I've submitted a PR for every missing DIS card (Stormscale Anarch was already implemented).

**Comment by Dilnu** [comment]
@NoahGleason Please feel free to mark these cards as done in the checklist in this and other similar bugs after your Pull Requests are merged.
