### ISSUE TITLE
GPT - Guildpact set card implementation tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4955]
Mark cards you are working on in the second post of this issue.
If the card is committed, mark here the Checkbox of the card to signal it's finished.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/fifth-dawn

# Unimplemented cards

- [x] Not Done -- [Aetherplasm](https://scryfall.com/search?q=Aetherplasm)
- [x] Not Done -- [Conjurer's Ban](https://scryfall.com/search?q=Conjurers+Ban)
- [x] Not Done -- [Petrified Wood-Kin](https://scryfall.com/search?q=Petrified+Wood-Kin)
- [x] Not Done -- [Predatory Focus](https://scryfall.com/search?q=Predatory+Focus)

# Cards in set:

- [x] Done -- [Absolver Thrull](https://scryfall.com/search?q=Absolver+Thrull)
- [x] Done -- [Abyssal Nocturnus](https://scryfall.com/search?q=Abyssal+Nocturnus)
- [x] Done -- [Agent of Masks](https://scryfall.com/search?q=Agent+of+Masks)
- [x] Done -- [Angel of Despair](https://scryfall.com/search?q=Angel+of+Despair)
- [x] Done -- [Battering Wurm](https://scryfall.com/search?q=Battering+Wurm)
- [x] Done -- [Beastmaster's Magemark](https://scryfall.com/search?q=Beastmasters+Magemark)
- [x] Done -- [Belfry Spirit](https://scryfall.com/search?q=Belfry+Spirit)
- [x] Done -- [Benediction of Moons](https://scryfall.com/search?q=Benediction+of+Moons)
- [x] Done -- [Bioplasm](https://scryfall.com/search?q=Bioplasm)
- [x] Done -- [Blind Hunter](https://scryfall.com/search?q=Blind+Hunter)
- [x] Done -- [Bloodscale Prowler](https://scryfall.com/search?q=Bloodscale+Prowler)
- [x] Done -- [Borborygmos](https://scryfall.com/search?q=Borborygmos)
- [x] Done -- [Burning-Tree Bloodscale](https://scryfall.com/search?q=Burning-Tree+Bloodscale)
- [x] Done -- [Burning-Tree Shaman](https://scryfall.com/search?q=Burning-Tree+Shaman)
- [x] Done -- [Castigate](https://scryfall.com/search?q=Castigate)
- [x] Done -- [Caustic Rain](https://scryfall.com/search?q=Caustic+Rain)
- [x] Done -- [Cerebral Vortex](https://scryfall.com/search?q=Cerebral+Vortex)
- [x] Done -- [Crash Landing](https://scryfall.com/search?q=Crash+Landing)
- [x] Done -- [Cremate](https://scryfall.com/search?q=Cremate)
- [x] Done -- [Cry of Contrition](https://scryfall.com/search?q=Cry+of+Contrition)
- [x] Done -- [Cryptwailing](https://scryfall.com/search?q=Cryptwailing)
- [x] Done -- [Crystal Seer](https://scryfall.com/search?q=Crystal+Seer)
- [x] Done -- [Culling Sun](https://scryfall.com/search?q=Culling+Sun)
- [x] Done -- [Daggerclaw Imp](https://scryfall.com/search?q=Daggerclaw+Imp)
- [x] Done -- [Debtors' Knell](https://scryfall.com/search?q=Debtors+Knell)
- [x] Done -- [Djinn Illuminatus](https://scryfall.com/search?q=Djinn+Illuminatus)
- [x] Done -- [Douse in Gloom](https://scryfall.com/search?q=Douse+in+Gloom)
- [x] Done -- [Droning Bureaucrats](https://scryfall.com/search?q=Droning+Bureaucrats)
- [x] Done -- [Drowned Rusalka](https://scryfall.com/search?q=Drowned+Rusalka)
- [x] Done -- [Dryad Sophisticate](https://scryfall.com/search?q=Dryad+Sophisticate)
- [x] Done -- [Dune-Brood Nephilim](https://scryfall.com/search?q=Dune-Brood+Nephilim)
- [x] Done -- [Earth Surge](https://scryfall.com/search?q=Earth+Surge)
- [x] Done -- [Electrolyze](https://scryfall.com/search?q=Electrolyze)
- [x] Done -- [Exhumer Thrull](https://scryfall.com/search?q=Exhumer+Thrull)
- [x] Done -- [Fencer's Magemark](https://scryfall.com/search?q=Fencers+Magemark)
- [x] Done -- [Feral Animist](https://scryfall.com/search?q=Feral+Animist)
- [x] Done -- [Frazzle](https://scryfall.com/search?q=Frazzle)
- [x] Done -- [Gatherer of Graces](https://scryfall.com/search?q=Gatherer+of+Graces)
- [x] Done -- [Gelectrode](https://scryfall.com/search?q=Gelectrode)
- [x] Done -- [Ghor-Clan Bloodscale](https://scryfall.com/search?q=Ghor-Clan+Bloodscale)
- [x] Done -- [Ghor-Clan Savage](https://scryfall.com/search?q=Ghor-Clan+Savage)
- [x] Done -- [Ghost Council of Orzhova](https://scryfall.com/search?q=Ghost+Council+of+Orzhova)
- [x] Done -- [Ghost Warden](https://scryfall.com/search?q=Ghost+Warden)
- [x] Done -- [Ghostway](https://scryfall.com/search?q=Ghostway)
- [x] Done -- [Giant Solifuge](https://scryfall.com/search?q=Giant+Solifuge)
- [x] Done -- [Gigadrowse](https://scryfall.com/search?q=Gigadrowse)
- [x] Done -- [Glint-Eye Nephilim](https://scryfall.com/search?q=Glint-Eye+Nephilim)
- [x] Done -- [Goblin Flectomancer](https://scryfall.com/search?q=Goblin+Flectomancer)
- [x] Done -- [Godless Shrine](https://scryfall.com/search?q=Godless+Shrine)
- [x] Done -- [Graven Dominator](https://scryfall.com/search?q=Graven+Dominator)
- [x] Done -- [Gristleback](https://scryfall.com/search?q=Gristleback)
- [x] Done -- [Gruul Guildmage](https://scryfall.com/search?q=Gruul+Guildmage)
- [x] Done -- [Gruul Nodorog](https://scryfall.com/search?q=Gruul+Nodorog)
- [x] Done -- [Gruul Scrapper](https://scryfall.com/search?q=Gruul+Scrapper)
- [x] Done -- [Gruul Signet](https://scryfall.com/search?q=Gruul+Signet)
- [x] Done -- [Gruul Turf](https://scryfall.com/search?q=Gruul+Turf)
- [x] Done -- [Gruul War Plow](https://scryfall.com/search?q=Gruul+War+Plow)
- [x] Done -- [Guardian's Magemark](https://scryfall.com/search?q=Guardians+Magemark)
- [x] Done -- [Harrier Griffin](https://scryfall.com/search?q=Harrier+Griffin)
- [x] Done -- [Hatching Plans](https://scryfall.com/search?q=Hatching+Plans)
- [x] Done -- [Hissing Miasma](https://scryfall.com/search?q=Hissing+Miasma)
- [x] Done -- [Hypervolt Grasp](https://scryfall.com/search?q=Hypervolt+Grasp)
- [x] Done -- [Infiltrator's Magemark](https://scryfall.com/search?q=Infiltrators+Magemark)
- [x] Done -- [Ink-Treader Nephilim](https://scryfall.com/search?q=Ink-Treader+Nephilim)
- [x] Done -- [Invoke the Firemind](https://scryfall.com/search?q=Invoke+the+Firemind)
- [x] Done -- [Izzet Boilerworks](https://scryfall.com/search?q=Izzet+Boilerworks)
- [x] Done -- [Izzet Chronarch](https://scryfall.com/search?q=Izzet+Chronarch)
- [x] Done -- [Izzet Guildmage](https://scryfall.com/search?q=Izzet+Guildmage)
- [x] Done -- [Izzet Signet](https://scryfall.com/search?q=Izzet+Signet)
- [x] Done -- [Killer Instinct](https://scryfall.com/search?q=Killer+Instinct)
- [x] Done -- [Leap of Flame](https://scryfall.com/search?q=Leap+of+Flame)
- [x] Done -- [Leyline of Lifeforce](https://scryfall.com/search?q=Leyline+of+Lifeforce)
- [x] Done -- [Leyline of Lightning](https://scryfall.com/search?q=Leyline+of+Lightning)
- [x] Done -- [Leyline of Singularity](https://scryfall.com/search?q=Leyline+of+Singularity)
- [x] Done -- [Leyline of the Meek](https://scryfall.com/search?q=Leyline+of+the+Meek)
- [x] Done -- [Leyline of the Void](https://scryfall.com/search?q=Leyline+of+the+Void)
- [x] Done -- [Lionheart Maverick](https://scryfall.com/search?q=Lionheart+Maverick)
- [x] Done -- [Living Inferno](https://scryfall.com/search?q=Living+Inferno)
- [x] Done -- [Martyred Rusalka](https://scryfall.com/search?q=Martyred+Rusalka)
- [x] Done -- [Mimeofacture](https://scryfall.com/search?q=Mimeofacture)
- [x] Done -- [Mizzium Transreliquat](https://scryfall.com/search?q=Mizzium+Transreliquat)
- [x] Done -- [Moratorium Stone](https://scryfall.com/search?q=Moratorium+Stone)
- [x] Done -- [Mortify](https://scryfall.com/search?q=Mortify)
- [x] Done -- [Mourning Thrull](https://scryfall.com/search?q=Mourning+Thrull)
- [x] Done -- [Necromancer's Magemark](https://scryfall.com/search?q=Necromancers+Magemark)
- [x] Done -- [Niv-Mizzet, the Firemind](https://scryfall.com/search?q=Niv-Mizzet,+the+Firemind)
- [x] Done -- [Nivix, Aerie of the Firemind](https://scryfall.com/search?q=Nivix,+Aerie+of+the+Firemind)
- [x] Done -- [Ogre Savant](https://scryfall.com/search?q=Ogre+Savant)
- [x] Done -- [Order of the Stars](https://scryfall.com/search?q=Order+of+the+Stars)
- [x] Done -- [Orzhov Basilica](https://scryfall.com/search?q=Orzhov+Basilica)
- [x] Done -- [Orzhov Euthanist](https://scryfall.com/search?q=Orzhov+Euthanist)
- [x] Done -- [Orzhov Guildmage](https://scryfall.com/search?q=Orzhov+Guildmage)
- [x] Done -- [Orzhov Pontiff](https://scryfall.com/search?q=Orzhov+Pontiff)
- [x] Done -- [Orzhov Signet](https://scryfall.com/search?q=Orzhov+Signet)
- [x] Done -- [Orzhova, the Church of Deals](https://scryfall.com/search?q=Orzhova,+the+Church+of+Deals)
- [x] Done -- [Ostiary Thrull](https://scryfall.com/search?q=Ostiary+Thrull)
- [x] Done -- [Parallectric Feedback](https://scryfall.com/search?q=Parallectric+Feedback)
- [x] Done -- [Petrahydrox](https://scryfall.com/search?q=Petrahydrox)
- [x] Done -- [Pillory of the Sleepless](https://scryfall.com/search?q=Pillory+of+the+Sleepless)
- [x] Done -- [Plagued Rusalka](https://scryfall.com/search?q=Plagued+Rusalka)
- [x] Done -- [Poisonbelly Ogre](https://scryfall.com/search?q=Poisonbelly+Ogre)
- [x] Done -- [Primeval Light](https://scryfall.com/search?q=Primeval+Light)
- [x] Done -- [Pyromatics](https://scryfall.com/search?q=Pyromatics)
- [x] Done -- [Quicken](https://scryfall.com/search?q=Quicken)
- [x] Done -- [Rabble-Rouser](https://scryfall.com/search?q=Rabble-Rouser)
- [x] Done -- [Repeal](https://scryfall.com/search?q=Repeal)
- [x] Done -- [Restless Bones](https://scryfall.com/search?q=Restless+Bones)
- [x] Done -- [Revenant Patriarch](https://scryfall.com/search?q=Revenant+Patriarch)
- [x] Done -- [Rumbling Slum](https://scryfall.com/search?q=Rumbling+Slum)
- [x] Done -- [Runeboggle](https://scryfall.com/search?q=Runeboggle)
- [x] Done -- [Sanguine Praetor](https://scryfall.com/search?q=Sanguine+Praetor)
- [x] Done -- [Savage Twister](https://scryfall.com/search?q=Savage+Twister)
- [x] Done -- [Scab-Clan Mauler](https://scryfall.com/search?q=Scab-Clan+Mauler)
- [x] Done -- [Schismotivate](https://scryfall.com/search?q=Schismotivate)
- [x] Done -- [Scorched Rusalka](https://scryfall.com/search?q=Scorched+Rusalka)
- [x] Done -- [Seize the Soul](https://scryfall.com/search?q=Seize+the+Soul)
- [x] Done -- [Shadow Lance](https://scryfall.com/search?q=Shadow+Lance)
- [x] Done -- [Shattering Spree](https://scryfall.com/search?q=Shattering+Spree)
- [x] Done -- [Shrieking Grotesque](https://scryfall.com/search?q=Shrieking+Grotesque)
- [x] Done -- [Siege of Towers](https://scryfall.com/search?q=Siege+of+Towers)
- [x] Done -- [Silhana Ledgewalker](https://scryfall.com/search?q=Silhana+Ledgewalker)
- [x] Done -- [Silhana Starfletcher](https://scryfall.com/search?q=Silhana+Starfletcher)
- [x] Done -- [Sinstriker's Will](https://scryfall.com/search?q=Sinstrikers+Will)
- [x] Done -- [Skarrg, the Rage Pits](https://scryfall.com/search?q=Skarrg,+the+Rage+Pits)
- [x] Done -- [Skarrgan Firebird](https://scryfall.com/search?q=Skarrgan+Firebird)
- [x] Done -- [Skarrgan Pit-Skulk](https://scryfall.com/search?q=Skarrgan+Pit-Skulk)
- [x] Done -- [Skarrgan Skybreaker](https://scryfall.com/search?q=Skarrgan+Skybreaker)
- [x] Done -- [Skeletal Vampire](https://scryfall.com/search?q=Skeletal+Vampire)
- [x] Done -- [Sky Swallower](https://scryfall.com/search?q=Sky+Swallower)
- [x] Done -- [Skyrider Trainee](https://scryfall.com/search?q=Skyrider+Trainee)
- [x] Done -- [Smogsteed Rider](https://scryfall.com/search?q=Smogsteed+Rider)
- [x] Done -- [Souls of the Faultless](https://scryfall.com/search?q=Souls+of+the+Faultless)
- [x] Done -- [Spelltithe Enforcer](https://scryfall.com/search?q=Spelltithe+Enforcer)
- [x] Done -- [Starved Rusalka](https://scryfall.com/search?q=Starved+Rusalka)
- [x] Done -- [Steam Vents](https://scryfall.com/search?q=Steam+Vents)
- [x] Done -- [Steamcore Weird](https://scryfall.com/search?q=Steamcore+Weird)
- [x] Done -- [Stitch in Time](https://scryfall.com/search?q=Stitch+in+Time)
- [x] Done -- [Stomping Ground](https://scryfall.com/search?q=Stomping+Ground)
- [x] Done -- [Storm Herd](https://scryfall.com/search?q=Storm+Herd)
- [x] Done -- [Stratozeppelid](https://scryfall.com/search?q=Stratozeppelid)
- [x] Done -- [Streetbreaker Wurm](https://scryfall.com/search?q=Streetbreaker+Wurm)
- [x] Done -- [Sword of the Paruns](https://scryfall.com/search?q=Sword+of+the+Paruns)
- [x] Done -- [Teysa, Orzhov Scion](https://scryfall.com/search?q=Teysa,+Orzhov+Scion)
- [x] Done -- [Thunderheads](https://scryfall.com/search?q=Thunderheads)
- [x] Done -- [Tibor and Lumia](https://scryfall.com/search?q=Tibor+and+Lumia)
- [x] Done -- [Tin Street Hooligan](https://scryfall.com/search?q=Tin+Street+Hooligan)
- [x] Done -- [To Arms!](https://scryfall.com/search?q=To+Arms!)
- [x] Done -- [Torch Drake](https://scryfall.com/search?q=Torch+Drake)
- [x] Done -- [Train of Thought](https://scryfall.com/search?q=Train+of+Thought)
- [x] Done -- [Ulasht, the Hate Seed](https://scryfall.com/search?q=Ulasht,+the+Hate+Seed)
- [x] Done -- [Vacuumelt](https://scryfall.com/search?q=Vacuumelt)
- [x] Done -- [Vedalken Plotter](https://scryfall.com/search?q=Vedalken+Plotter)
- [x] Done -- [Vertigo Spawn](https://scryfall.com/search?q=Vertigo+Spawn)
- [x] Done -- [Wee Dragonauts](https://scryfall.com/search?q=Wee+Dragonauts)
- [x] Done -- [Wild Cantor](https://scryfall.com/search?q=Wild+Cantor)
- [x] Done -- [Wildsize](https://scryfall.com/search?q=Wildsize)
- [x] Done -- [Witch-Maw Nephilim](https://scryfall.com/search?q=Witch-Maw+Nephilim)
- [x] Done -- [Withstand](https://scryfall.com/search?q=Withstand)
- [x] Done -- [Wreak Havoc](https://scryfall.com/search?q=Wreak+Havoc)
- [x] Done -- [Wurmweaver Coil](https://scryfall.com/search?q=Wurmweaver+Coil)
- [x] Done -- [Yore-Tiller Nephilim](https://scryfall.com/search?q=Yore-Tiller+Nephilim)

**Comment by NoahGleason** [comment]
A PR has been requested for every missing card in this set, so this issue should be closed once #5137 and #5082 are merged.
