### ISSUE TITLE
TSP - Time Spiral set card implementation tracker

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4956]
Mark cards you are working on in the second post of this issue.
If the card is committed, mark here the Checkbox of the card to signal it's finished.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/time-spiral

# Unimplemented cards

- [x] Not Done -- [Aether Web](https://scryfall.com/search?q=Aether+Web)
- [x] Not Done -- [Aetherflame Wall](https://scryfall.com/search?q=Aetherflame+Wall)
- [x] Not Done -- [Chameleon Blur](https://scryfall.com/search?q=Chameleon+Blur)
- [x] Not Done -- [Cyclopean Giant](https://scryfall.com/search?q=Cyclopean+Giant)
- [x] Not Done -- [Durkwood Tracker](https://scryfall.com/search?q=Durkwood+Tracker)
- [x] Not Done -- [Plated Pegasus](https://scryfall.com/search?q=Plated+Pegasus)
- [x] Not Done -- [Premature Burial](https://scryfall.com/search?q=Premature+Burial)
- [x] Not Done -- [Thick-Skinned Goblin](https://scryfall.com/search?q=Thick-Skinned+Goblin)
- [x] Not Done -- [Truth or Tale](https://scryfall.com/search?q=Truth+or+Tale)

# Cards in set:

- [x] Done -- [Academy Ruins](https://scryfall.com/search?q=Academy+Ruins)
- [x] Done -- [Amrou Scout](https://scryfall.com/search?q=Amrou+Scout)
- [x] Done -- [Amrou Seekers](https://scryfall.com/search?q=Amrou+Seekers)
- [x] Done -- [Ancestral Vision](https://scryfall.com/search?q=Ancestral+Vision)
- [x] Done -- [Ancient Grudge](https://scryfall.com/search?q=Ancient+Grudge)
- [x] Done -- [Angel's Grace](https://scryfall.com/search?q=Angels+Grace)
- [x] Done -- [Ashcoat Bear](https://scryfall.com/search?q=Ashcoat+Bear)
- [x] Done -- [Aspect of Mongoose](https://scryfall.com/search?q=Aspect+of+Mongoose)
- [x] Done -- [Assassinate](https://scryfall.com/search?q=Assassinate)
- [x] Done -- [Assembly-Worker](https://scryfall.com/search?q=Assembly-Worker)
- [x] Done -- [Barbed Shocker](https://scryfall.com/search?q=Barbed+Shocker)
- [x] Done -- [Basal Sliver](https://scryfall.com/search?q=Basal+Sliver)
- [x] Done -- [Basalt Gargoyle](https://scryfall.com/search?q=Basalt+Gargoyle)
- [x] Done -- [Benalish Cavalry](https://scryfall.com/search?q=Benalish+Cavalry)
- [x] Done -- [Bewilder](https://scryfall.com/search?q=Bewilder)
- [x] Done -- [Blazing Blade Askari](https://scryfall.com/search?q=Blazing+Blade+Askari)
- [x] Done -- [Bogardan Hellkite](https://scryfall.com/search?q=Bogardan+Hellkite)
- [x] Done -- [Bogardan Rager](https://scryfall.com/search?q=Bogardan+Rager)
- [x] Done -- [Bonesplitter Sliver](https://scryfall.com/search?q=Bonesplitter+Sliver)
- [x] Done -- [Brass Gnat](https://scryfall.com/search?q=Brass+Gnat)
- [x] Done -- [Brine Elemental](https://scryfall.com/search?q=Brine+Elemental)
- [x] Done -- [Calciform Pools](https://scryfall.com/search?q=Calciform+Pools)
- [x] Done -- [Call to the Netherworld](https://scryfall.com/search?q=Call+to+the+Netherworld)
- [x] Done -- [Cancel](https://scryfall.com/search?q=Cancel)
- [x] Done -- [Candles of Leng](https://scryfall.com/search?q=Candles+of+Leng)
- [x] Done -- [Careful Consideration](https://scryfall.com/search?q=Careful+Consideration)
- [x] Done -- [Castle Raptors](https://scryfall.com/search?q=Castle+Raptors)
- [x] Done -- [Cavalry Master](https://scryfall.com/search?q=Cavalry+Master)
- [x] Done -- [Celestial Crusader](https://scryfall.com/search?q=Celestial+Crusader)
- [x] Done -- [Children of Korlis](https://scryfall.com/search?q=Children+of+Korlis)
- [x] Done -- [Chromatic Star](https://scryfall.com/search?q=Chromatic+Star)
- [x] Done -- [Chronatog Totem](https://scryfall.com/search?q=Chronatog+Totem)
- [x] Done -- [Chronosavant](https://scryfall.com/search?q=Chronosavant)
- [x] Done -- [Clockspinning](https://scryfall.com/search?q=Clockspinning)
- [x] Done -- [Clockwork Hydra](https://scryfall.com/search?q=Clockwork+Hydra)
- [x] Done -- [Cloudchaser Kestrel](https://scryfall.com/search?q=Cloudchaser+Kestrel)
- [x] Done -- [Coal Stoker](https://scryfall.com/search?q=Coal+Stoker)
- [x] Done -- [Conflagrate](https://scryfall.com/search?q=Conflagrate)
- [x] Done -- [Coral Trickster](https://scryfall.com/search?q=Coral+Trickster)
- [x] Done -- [Corpulent Corpse](https://scryfall.com/search?q=Corpulent+Corpse)
- [x] Done -- [Crookclaw Transmuter](https://scryfall.com/search?q=Crookclaw+Transmuter)
- [x] Done -- [Curse of the Cabal](https://scryfall.com/search?q=Curse+of+the+Cabal)
- [x] Done -- [D'Avenant Healer](https://scryfall.com/search?q=DAvenant+Healer)
- [x] Done -- [Dark Withering](https://scryfall.com/search?q=Dark+Withering)
- [x] Done -- [Deathspore Thallid](https://scryfall.com/search?q=Deathspore+Thallid)
- [x] Done -- [Deep-Sea Kraken](https://scryfall.com/search?q=Deep-Sea+Kraken)
- [x] Done -- [Dementia Sliver](https://scryfall.com/search?q=Dementia+Sliver)
- [x] Done -- [Demonic Collusion](https://scryfall.com/search?q=Demonic+Collusion)
- [x] Done -- [Detainment Spell](https://scryfall.com/search?q=Detainment+Spell)
- [x] Done -- [Divine Congregation](https://scryfall.com/search?q=Divine+Congregation)
- [x] Done -- [Draining Whelk](https://scryfall.com/search?q=Draining+Whelk)
- [x] Done -- [Dralnu, Lich Lord](https://scryfall.com/search?q=Dralnu,+Lich+Lord)
- [x] Done -- [Dread Return](https://scryfall.com/search?q=Dread+Return)
- [x] Done -- [Dreadship Reef](https://scryfall.com/search?q=Dreadship+Reef)
- [x] Done -- [Dream Stalker](https://scryfall.com/search?q=Dream+Stalker)
- [x] Done -- [Drifter il-Dal](https://scryfall.com/search?q=Drifter+il-Dal)
- [x] Done -- [Drudge Reavers](https://scryfall.com/search?q=Drudge+Reavers)
- [x] Done -- [Durkwood Baloth](https://scryfall.com/search?q=Durkwood+Baloth)
- [x] Done -- [Duskrider Peregrine](https://scryfall.com/search?q=Duskrider+Peregrine)
- [x] Done -- [Empty the Warrens](https://scryfall.com/search?q=Empty+the+Warrens)
- [x] Done -- [Endrek Sahr, Master Breeder](https://scryfall.com/search?q=Endrek+Sahr,+Master+Breeder)
- [x] Done -- [Errant Doomsayers](https://scryfall.com/search?q=Errant+Doomsayers)
- [x] Done -- [Errant Ephemeron](https://scryfall.com/search?q=Errant+Ephemeron)
- [x] Done -- [Eternity Snare](https://scryfall.com/search?q=Eternity+Snare)
- [x] Done -- [Evangelize](https://scryfall.com/search?q=Evangelize)
- [x] Done -- [Evil Eye of Urborg](https://scryfall.com/search?q=Evil+Eye+of+Urborg)
- [x] Done -- [Faceless Devourer](https://scryfall.com/search?q=Faceless+Devourer)
- [x] Done -- [Fallen Ideal](https://scryfall.com/search?q=Fallen+Ideal)
- [x] Done -- [Fathom Seer](https://scryfall.com/search?q=Fathom+Seer)
- [x] Done -- [Feebleness](https://scryfall.com/search?q=Feebleness)
- [x] Done -- [Firemaw Kavu](https://scryfall.com/search?q=Firemaw+Kavu)
- [x] Done -- [Firewake Sliver](https://scryfall.com/search?q=Firewake+Sliver)
- [x] Done -- [Flagstones of Trokair](https://scryfall.com/search?q=Flagstones+of+Trokair)
- [x] Done -- [Flamecore Elemental](https://scryfall.com/search?q=Flamecore+Elemental)
- [x] Done -- [Fledgling Mawcor](https://scryfall.com/search?q=Fledgling+Mawcor)
- [x] Done -- [Flickering Spirit](https://scryfall.com/search?q=Flickering+Spirit)
- [x] Done -- [Flowstone Channeler](https://scryfall.com/search?q=Flowstone+Channeler)
- [x] Done -- [Fool's Demise](https://scryfall.com/search?q=Fools+Demise)
- [x] Done -- [Foriysian Interceptor](https://scryfall.com/search?q=Foriysian+Interceptor)
- [x] Done -- [Foriysian Totem](https://scryfall.com/search?q=Foriysian+Totem)
- [x] Done -- [Fortify](https://scryfall.com/search?q=Fortify)
- [x] Done -- [Fortune Thief](https://scryfall.com/search?q=Fortune+Thief)
- [x] Done -- [Fungal Reaches](https://scryfall.com/search?q=Fungal+Reaches)
- [x] Done -- [Fungus Sliver](https://scryfall.com/search?q=Fungus+Sliver)
- [x] Done -- [Fury Sliver](https://scryfall.com/search?q=Fury+Sliver)
- [x] Done -- [Gauntlet of Power](https://scryfall.com/search?q=Gauntlet+of+Power)
- [x] Done -- [Gaze of Justice](https://scryfall.com/search?q=Gaze+of+Justice)
- [x] Done -- [Gemhide Sliver](https://scryfall.com/search?q=Gemhide+Sliver)
- [x] Done -- [Gemstone Caverns](https://scryfall.com/search?q=Gemstone+Caverns)
- [x] Done -- [Ghitu Firebreathing](https://scryfall.com/search?q=Ghitu+Firebreathing)
- [x] Done -- [Ghostflame Sliver](https://scryfall.com/search?q=Ghostflame+Sliver)
- [x] Done -- [Glass Asp](https://scryfall.com/search?q=Glass+Asp)
- [x] Done -- [Goblin Skycutter](https://scryfall.com/search?q=Goblin+Skycutter)
- [x] Done -- [Gorgon Recluse](https://scryfall.com/search?q=Gorgon+Recluse)
- [x] Done -- [Grapeshot](https://scryfall.com/search?q=Grapeshot)
- [x] Done -- [Greater Gargadon](https://scryfall.com/search?q=Greater+Gargadon)
- [x] Done -- [Greenseeker](https://scryfall.com/search?q=Greenseeker)
- [x] Done -- [Griffin Guide](https://scryfall.com/search?q=Griffin+Guide)
- [x] Done -- [Ground Rift](https://scryfall.com/search?q=Ground+Rift)
- [x] Done -- [Gustcloak Cavalier](https://scryfall.com/search?q=Gustcloak+Cavalier)
- [x] Done -- [Harmonic Sliver](https://scryfall.com/search?q=Harmonic+Sliver)
- [x] Done -- [Haunting Hymn](https://scryfall.com/search?q=Haunting+Hymn)
- [x] Done -- [Havenwood Wurm](https://scryfall.com/search?q=Havenwood+Wurm)
- [x] Done -- [Herd Gnarr](https://scryfall.com/search?q=Herd+Gnarr)
- [x] Done -- [Hivestone](https://scryfall.com/search?q=Hivestone)
- [x] Done -- [Hypergenesis](https://scryfall.com/search?q=Hypergenesis)
- [x] Done -- [Ib Halfheart, Goblin Tactician](https://scryfall.com/search?q=Ib+Halfheart,+Goblin+Tactician)
- [x] Done -- [Icatian Crier](https://scryfall.com/search?q=Icatian+Crier)
- [x] Done -- [Ignite Memories](https://scryfall.com/search?q=Ignite+Memories)
- [x] Done -- [Ironclaw Buzzardiers](https://scryfall.com/search?q=Ironclaw+Buzzardiers)
- [x] Done -- [Ith, High Arcanist](https://scryfall.com/search?q=Ith,+High+Arcanist)
- [x] Done -- [Ivory Giant](https://scryfall.com/search?q=Ivory+Giant)
- [x] Done -- [Ixidron](https://scryfall.com/search?q=Ixidron)
- [x] Done -- [Jaya Ballard, Task Mage](https://scryfall.com/search?q=Jaya+Ballard,+Task+Mage)
- [x] Done -- [Jedit's Dragoons](https://scryfall.com/search?q=Jedits+Dragoons)
- [x] Done -- [Jhoira's Timebug](https://scryfall.com/search?q=Jhoiras+Timebug)
- [x] Done -- [Kaervek the Merciless](https://scryfall.com/search?q=Kaervek+the+Merciless)
- [x] Done -- [Keldon Halberdier](https://scryfall.com/search?q=Keldon+Halberdier)
- [x] Done -- [Kher Keep](https://scryfall.com/search?q=Kher+Keep)
- [x] Done -- [Knight of the Holy Nimbus](https://scryfall.com/search?q=Knight+of+the+Holy+Nimbus)
- [x] Done -- [Krosan Grip](https://scryfall.com/search?q=Krosan+Grip)
- [x] Done -- [Liege of the Pit](https://scryfall.com/search?q=Liege+of+the+Pit)
- [x] Done -- [Lightning Axe](https://scryfall.com/search?q=Lightning+Axe)
- [x] Done -- [Lim-Dul the Necromancer](https://scryfall.com/search?q=Lim-Dul+the+Necromancer)
- [x] Done -- [Living End](https://scryfall.com/search?q=Living+End)
- [x] Done -- [Locket of Yesterdays](https://scryfall.com/search?q=Locket+of+Yesterdays)
- [x] Done -- [Looter il-Kor](https://scryfall.com/search?q=Looter+il-Kor)
- [x] Done -- [Lotus Bloom](https://scryfall.com/search?q=Lotus+Bloom)
- [x] Done -- [Magus of the Candelabra](https://scryfall.com/search?q=Magus+of+the+Candelabra)
- [x] Done -- [Magus of the Disk](https://scryfall.com/search?q=Magus+of+the+Disk)
- [x] Done -- [Magus of the Jar](https://scryfall.com/search?q=Magus+of+the+Jar)
- [x] Done -- [Magus of the Mirror](https://scryfall.com/search?q=Magus+of+the+Mirror)
- [x] Done -- [Magus of the Scroll](https://scryfall.com/search?q=Magus+of+the+Scroll)
- [x] Done -- [Mana Skimmer](https://scryfall.com/search?q=Mana+Skimmer)
- [x] Done -- [Mangara of Corondor](https://scryfall.com/search?q=Mangara+of+Corondor)
- [x] Done -- [Might Sliver](https://scryfall.com/search?q=Might+Sliver)
- [x] Done -- [Might of Old Krosa](https://scryfall.com/search?q=Might+of+Old+Krosa)
- [x] Done -- [Mindlash Sliver](https://scryfall.com/search?q=Mindlash+Sliver)
- [x] Done -- [Mindstab](https://scryfall.com/search?q=Mindstab)
- [x] Done -- [Mishra, Artificer Prodigy](https://scryfall.com/search?q=Mishra,+Artificer+Prodigy)
- [x] Done -- [Mogg War Marshal](https://scryfall.com/search?q=Mogg+War+Marshal)
- [x] Done -- [Molder](https://scryfall.com/search?q=Molder)
- [x] Done -- [Molten Slagheap](https://scryfall.com/search?q=Molten+Slagheap)
- [x] Done -- [Momentary Blink](https://scryfall.com/search?q=Momentary+Blink)
- [x] Done -- [Moonlace](https://scryfall.com/search?q=Moonlace)
- [x] Done -- [Mwonvuli Acid-Moss](https://scryfall.com/search?q=Mwonvuli+Acid-Moss)
- [x] Done -- [Mystical Teachings](https://scryfall.com/search?q=Mystical+Teachings)
- [x] Done -- [Nantuko Shaman](https://scryfall.com/search?q=Nantuko+Shaman)
- [x] Done -- [Nether Traitor](https://scryfall.com/search?q=Nether+Traitor)
- [x] Done -- [Nightshade Assassin](https://scryfall.com/search?q=Nightshade+Assassin)
- [x] Done -- [Norin the Wary](https://scryfall.com/search?q=Norin+the+Wary)
- [x] Done -- [Opal Guardian](https://scryfall.com/search?q=Opal+Guardian)
- [x] Done -- [Opaline Sliver](https://scryfall.com/search?q=Opaline+Sliver)
- [x] Done -- [Ophidian Eye](https://scryfall.com/search?q=Ophidian+Eye)
- [x] Done -- [Orcish Cannonade](https://scryfall.com/search?q=Orcish+Cannonade)
- [x] Done -- [Outrider en-Kor](https://scryfall.com/search?q=Outrider+en-Kor)
- [x] Done -- [Paradise Plume](https://scryfall.com/search?q=Paradise+Plume)
- [x] Done -- [Paradox Haze](https://scryfall.com/search?q=Paradox+Haze)
- [x] Done -- [Pardic Dragon](https://scryfall.com/search?q=Pardic+Dragon)
- [x] Done -- [Pendelhaven Elder](https://scryfall.com/search?q=Pendelhaven+Elder)
- [x] Done -- [Pentarch Paladin](https://scryfall.com/search?q=Pentarch+Paladin)
- [x] Done -- [Pentarch Ward](https://scryfall.com/search?q=Pentarch+Ward)
- [x] Done -- [Penumbra Spider](https://scryfall.com/search?q=Penumbra+Spider)
- [x] Done -- [Phantom Wurm](https://scryfall.com/search?q=Phantom+Wurm)
- [x] Done -- [Phthisis](https://scryfall.com/search?q=Phthisis)
- [x] Done -- [Phyrexian Totem](https://scryfall.com/search?q=Phyrexian+Totem)
- [x] Done -- [Pit Keeper](https://scryfall.com/search?q=Pit+Keeper)
- [x] Done -- [Plague Sliver](https://scryfall.com/search?q=Plague+Sliver)
- [x] Done -- [Plunder](https://scryfall.com/search?q=Plunder)
- [x] Done -- [Primal Forcemage](https://scryfall.com/search?q=Primal+Forcemage)
- [x] Done -- [Prismatic Lens](https://scryfall.com/search?q=Prismatic+Lens)
- [x] Done -- [Psionic Sliver](https://scryfall.com/search?q=Psionic+Sliver)
- [x] Done -- [Psychotic Episode](https://scryfall.com/search?q=Psychotic+Episode)
- [x] Done -- [Pull from Eternity](https://scryfall.com/search?q=Pull+from+Eternity)
- [x] Done -- [Pulmonic Sliver](https://scryfall.com/search?q=Pulmonic+Sliver)
- [x] Done -- [Quilled Sliver](https://scryfall.com/search?q=Quilled+Sliver)
- [x] Done -- [Reiterate](https://scryfall.com/search?q=Reiterate)
- [x] Done -- [Restore Balance](https://scryfall.com/search?q=Restore+Balance)
- [x] Done -- [Return to Dust](https://scryfall.com/search?q=Return+to+Dust)
- [x] Done -- [Rift Bolt](https://scryfall.com/search?q=Rift+Bolt)
- [x] Done -- [Riftwing Cloudskate](https://scryfall.com/search?q=Riftwing+Cloudskate)
- [x] Done -- [Saffi Eriksdotter](https://scryfall.com/search?q=Saffi+Eriksdotter)
- [x] Done -- [Sage of Epityr](https://scryfall.com/search?q=Sage+of+Epityr)
- [x] Done -- [Saltcrusted Steppe](https://scryfall.com/search?q=Saltcrusted+Steppe)
- [x] Done -- [Sangrophage](https://scryfall.com/search?q=Sangrophage)
- [x] Done -- [Sarpadian Empires, Vol. VII](https://scryfall.com/search?q=Sarpadian+Empires,+Vol.+VII)
- [x] Done -- [Savage Thallid](https://scryfall.com/search?q=Savage+Thallid)
- [x] Done -- [Scarwood Treefolk](https://scryfall.com/search?q=Scarwood+Treefolk)
- [x] Done -- [Scion of the Ur-Dragon](https://scryfall.com/search?q=Scion+of+the+Ur-Dragon)
- [x] Done -- [Screeching Sliver](https://scryfall.com/search?q=Screeching+Sliver)
- [x] Done -- [Scryb Ranger](https://scryfall.com/search?q=Scryb+Ranger)
- [x] Done -- [Search for Tomorrow](https://scryfall.com/search?q=Search+for+Tomorrow)
- [x] Done -- [Sedge Sliver](https://scryfall.com/search?q=Sedge+Sliver)
- [x] Done -- [Sengir Nosferatu](https://scryfall.com/search?q=Sengir+Nosferatu)
- [x] Done -- [Serra Avenger](https://scryfall.com/search?q=Serra+Avenger)
- [x] Done -- [Shadow Sliver](https://scryfall.com/search?q=Shadow+Sliver)
- [x] Done -- [Sidewinder Sliver](https://scryfall.com/search?q=Sidewinder+Sliver)
- [x] Done -- [Skittering Monstrosity](https://scryfall.com/search?q=Skittering+Monstrosity)
- [x] Done -- [Skulking Knight](https://scryfall.com/search?q=Skulking+Knight)
- [x] Done -- [Slipstream Serpent](https://scryfall.com/search?q=Slipstream+Serpent)
- [x] Done -- [Smallpox](https://scryfall.com/search?q=Smallpox)
- [x] Done -- [Snapback](https://scryfall.com/search?q=Snapback)
- [x] Done -- [Spectral Force](https://scryfall.com/search?q=Spectral+Force)
- [x] Done -- [Spell Burst](https://scryfall.com/search?q=Spell+Burst)
- [x] Done -- [Spike Tiller](https://scryfall.com/search?q=Spike+Tiller)
- [x] Done -- [Spiketail Drakeling](https://scryfall.com/search?q=Spiketail+Drakeling)
- [x] Done -- [Spinneret Sliver](https://scryfall.com/search?q=Spinneret+Sliver)
- [x] Done -- [Spirit Loop](https://scryfall.com/search?q=Spirit+Loop)
- [x] Done -- [Sporesower Thallid](https://scryfall.com/search?q=Sporesower+Thallid)
- [x] Done -- [Sprite Noble](https://scryfall.com/search?q=Sprite+Noble)
- [x] Done -- [Sprout](https://scryfall.com/search?q=Sprout)
- [x] Done -- [Squall Line](https://scryfall.com/search?q=Squall+Line)
- [x] Done -- [Stonebrow, Krosan Hero](https://scryfall.com/search?q=Stonebrow,+Krosan+Hero)
- [x] Done -- [Stonewood Invocation](https://scryfall.com/search?q=Stonewood+Invocation)
- [x] Done -- [Stormcloud Djinn](https://scryfall.com/search?q=Stormcloud+Djinn)
- [x] Done -- [Strangling Soot](https://scryfall.com/search?q=Strangling+Soot)
- [x] Done -- [Strength in Numbers](https://scryfall.com/search?q=Strength+in+Numbers)
- [x] Done -- [Stronghold Overseer](https://scryfall.com/search?q=Stronghold+Overseer)
- [x] Done -- [Stuffy Doll](https://scryfall.com/search?q=Stuffy+Doll)
- [x] Done -- [Subterranean Shambler](https://scryfall.com/search?q=Subterranean+Shambler)
- [x] Done -- [Sudden Death](https://scryfall.com/search?q=Sudden+Death)
- [x] Done -- [Sudden Shock](https://scryfall.com/search?q=Sudden+Shock)
- [x] Done -- [Sudden Spoiling](https://scryfall.com/search?q=Sudden+Spoiling)
- [x] Done -- [Sulfurous Blast](https://scryfall.com/search?q=Sulfurous+Blast)
- [x] Done -- [Swarmyard](https://scryfall.com/search?q=Swarmyard)
- [x] Done -- [Tectonic Fiend](https://scryfall.com/search?q=Tectonic+Fiend)
- [x] Done -- [Teferi, Mage of Zhalfir](https://scryfall.com/search?q=Teferi,+Mage+of+Zhalfir)
- [x] Done -- [Telekinetic Sliver](https://scryfall.com/search?q=Telekinetic+Sliver)
- [x] Done -- [Temporal Eddy](https://scryfall.com/search?q=Temporal+Eddy)
- [x] Done -- [Temporal Isolation](https://scryfall.com/search?q=Temporal+Isolation)
- [x] Done -- [Tendrils of Corruption](https://scryfall.com/search?q=Tendrils+of+Corruption)
- [x] Done -- [Terramorphic Expanse](https://scryfall.com/search?q=Terramorphic+Expanse)
- [x] Done -- [Thallid Germinator](https://scryfall.com/search?q=Thallid+Germinator)
- [x] Done -- [Thallid Shell-Dweller](https://scryfall.com/search?q=Thallid+Shell-Dweller)
- [x] Done -- [Thelon of Havenwood](https://scryfall.com/search?q=Thelon+of+Havenwood)
- [x] Done -- [Thelonite Hermit](https://scryfall.com/search?q=Thelonite+Hermit)
- [x] Done -- [Think Twice](https://scryfall.com/search?q=Think+Twice)
- [x] Done -- [Thrill of the Hunt](https://scryfall.com/search?q=Thrill+of+the+Hunt)
- [x] Done -- [Thunder Totem](https://scryfall.com/search?q=Thunder+Totem)
- [x] Done -- [Tivadar of Thorn](https://scryfall.com/search?q=Tivadar+of+Thorn)
- [x] Done -- [Tolarian Sentinel](https://scryfall.com/search?q=Tolarian+Sentinel)
- [x] Done -- [Traitor's Clutch](https://scryfall.com/search?q=Traitors+Clutch)
- [x] Done -- [Trespasser il-Vec](https://scryfall.com/search?q=Trespasser+il-Vec)
- [x] Done -- [Trickbind](https://scryfall.com/search?q=Trickbind)
- [x] Done -- [Triskelavus](https://scryfall.com/search?q=Triskelavus)
- [x] Done -- [Tromp the Domains](https://scryfall.com/search?q=Tromp+the+Domains)
- [x] Done -- [Two-Headed Sliver](https://scryfall.com/search?q=Two-Headed+Sliver)
- [x] Done -- [Undying Rage](https://scryfall.com/search?q=Undying+Rage)
- [x] Done -- [Unyaro Bees](https://scryfall.com/search?q=Unyaro+Bees)
- [x] Done -- [Urborg Syphon-Mage](https://scryfall.com/search?q=Urborg+Syphon-Mage)
- [x] Done -- [Urza's Factory](https://scryfall.com/search?q=Urzas+Factory)
- [x] Done -- [Vampiric Sliver](https://scryfall.com/search?q=Vampiric+Sliver)
- [x] Done -- [Venser's Sliver](https://scryfall.com/search?q=Vensers+Sliver)
- [x] Done -- [Verdant Embrace](https://scryfall.com/search?q=Verdant+Embrace)
- [x] Done -- [Vesuva](https://scryfall.com/search?q=Vesuva)
- [x] Done -- [Vesuvan Shapeshifter](https://scryfall.com/search?q=Vesuvan+Shapeshifter)
- [x] Done -- [Viashino Bladescout](https://scryfall.com/search?q=Viashino+Bladescout)
- [x] Done -- [Viscerid Deepwalker](https://scryfall.com/search?q=Viscerid+Deepwalker)
- [x] Done -- [Viscid Lemures](https://scryfall.com/search?q=Viscid+Lemures)
- [x] Done -- [Voidmage Husher](https://scryfall.com/search?q=Voidmage+Husher)
- [x] Done -- [Volcanic Awakening](https://scryfall.com/search?q=Volcanic+Awakening)
- [x] Done -- [Walk the Aeons](https://scryfall.com/search?q=Walk+the+Aeons)
- [x] Done -- [Watcher Sliver](https://scryfall.com/search?q=Watcher+Sliver)
- [x] Done -- [Weathered Bodyguards](https://scryfall.com/search?q=Weathered+Bodyguards)
- [x] Done -- [Weatherseed Totem](https://scryfall.com/search?q=Weatherseed+Totem)
- [x] Done -- [Wheel of Fate](https://scryfall.com/search?q=Wheel+of+Fate)
- [x] Done -- [Wipe Away](https://scryfall.com/search?q=Wipe+Away)
- [x] Done -- [Word of Seizing](https://scryfall.com/search?q=Word+of+Seizing)
- [x] Done -- [Wormwood Dryad](https://scryfall.com/search?q=Wormwood+Dryad)
- [x] Done -- [Wurmcalling](https://scryfall.com/search?q=Wurmcalling)
- [x] Done -- [Yavimaya Dryad](https://scryfall.com/search?q=Yavimaya+Dryad)
- [x] Done -- [Zealot il-Vec](https://scryfall.com/search?q=Zealot+il-Vec)

**Comment by NoahGleason** [comment]
A PR has been submitted for every missing card, so this issue should be closed once they're all merged.
