### ISSUE TITLE
PLC - Planar Chaos set card implementation tracker

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4957]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/planar-chaos

# Unimplemented cards

- [x] Not Done -- [Dichotomancy](https://scryfall.com/search?q=Dichotomancy)
- [x] Not Done -- [Molten Firebird](https://scryfall.com/search?q=Molten+Firebird)

# Cards in set:

- [x] Done -- [Aeon Chronicler](https://scryfall.com/search?q=Aeon+Chronicler)
- [x] Done -- [Aether Membrane](https://scryfall.com/search?q=Aether+Membrane)
- [x] Done -- [Akroma, Angel of Fury](https://scryfall.com/search?q=Akroma,+Angel+of+Fury)
- [x] Done -- [Ana Battlemage](https://scryfall.com/search?q=Ana+Battlemage)
- [x] Done -- [Aquamorph Entity](https://scryfall.com/search?q=Aquamorph+Entity)
- [x] Done -- [Auramancer's Guise](https://scryfall.com/search?q=Auramancers+Guise)
- [x] Done -- [Aven Riftwatcher](https://scryfall.com/search?q=Aven+Riftwatcher)
- [x] Done -- [Battering Sliver](https://scryfall.com/search?q=Battering+Sliver)
- [x] Done -- [Benalish Commander](https://scryfall.com/search?q=Benalish+Commander)
- [x] Done -- [Big Game Hunter](https://scryfall.com/search?q=Big+Game+Hunter)
- [x] Done -- [Blightspeaker](https://scryfall.com/search?q=Blightspeaker)
- [x] Done -- [Blood Knight](https://scryfall.com/search?q=Blood+Knight)
- [x] Done -- [Body Double](https://scryfall.com/search?q=Body+Double)
- [x] Done -- [Bog Serpent](https://scryfall.com/search?q=Bog+Serpent)
- [x] Done -- [Boom // Bust](https://scryfall.com/search?q=Boom+//+Bust)
- [x] Done -- [Braids, Conjurer Adept](https://scryfall.com/search?q=Braids,+Conjurer+Adept)
- [x] Done -- [Brain Gorgers](https://scryfall.com/search?q=Brain+Gorgers)
- [x] Done -- [Brute Force](https://scryfall.com/search?q=Brute+Force)
- [x] Done -- [Calciderm](https://scryfall.com/search?q=Calciderm)
- [x] Done -- [Cautery Sliver](https://scryfall.com/search?q=Cautery+Sliver)
- [x] Done -- [Chronozoa](https://scryfall.com/search?q=Chronozoa)
- [x] Done -- [Circle of Affliction](https://scryfall.com/search?q=Circle+of+Affliction)
- [x] Done -- [Citanul Woodreaders](https://scryfall.com/search?q=Citanul+Woodreaders)
- [x] Done -- [Cradle to Grave](https://scryfall.com/search?q=Cradle+to+Grave)
- [x] Done -- [Crovax, Ascendant Hero](https://scryfall.com/search?q=Crovax,+Ascendant+Hero)
- [x] Done -- [Damnation](https://scryfall.com/search?q=Damnation)
- [x] Done -- [Darkheart Sliver](https://scryfall.com/search?q=Darkheart+Sliver)
- [x] Done -- [Dash Hopes](https://scryfall.com/search?q=Dash+Hopes)
- [x] Done -- [Dawn Charm](https://scryfall.com/search?q=Dawn+Charm)
- [x] Done -- [Dead // Gone](https://scryfall.com/search?q=Dead+//+Gone)
- [x] Done -- [Deadly Grub](https://scryfall.com/search?q=Deadly+Grub)
- [x] Done -- [Deadwood Treefolk](https://scryfall.com/search?q=Deadwood+Treefolk)
- [x] Done -- [Detritivore](https://scryfall.com/search?q=Detritivore)
- [x] Done -- [Dismal Failure](https://scryfall.com/search?q=Dismal+Failure)
- [x] Done -- [Dormant Sliver](https://scryfall.com/search?q=Dormant+Sliver)
- [x] Done -- [Dreamscape Artist](https://scryfall.com/search?q=Dreamscape+Artist)
- [x] Done -- [Dunerider Outlaw](https://scryfall.com/search?q=Dunerider+Outlaw)
- [x] Done -- [Dust Corona](https://scryfall.com/search?q=Dust+Corona)
- [x] Done -- [Dust Elemental](https://scryfall.com/search?q=Dust+Elemental)
- [x] Done -- [Enslave](https://scryfall.com/search?q=Enslave)
- [x] Done -- [Erratic Mutation](https://scryfall.com/search?q=Erratic+Mutation)
- [x] Done -- [Essence Warden](https://scryfall.com/search?q=Essence+Warden)
- [x] Done -- [Evolution Charm](https://scryfall.com/search?q=Evolution+Charm)
- [x] Done -- [Extirpate](https://scryfall.com/search?q=Extirpate)
- [x] Done -- [Fa'adiyah Seer](https://scryfall.com/search?q=Faadiyah+Seer)
- [x] Done -- [Fatal Frenzy](https://scryfall.com/search?q=Fatal+Frenzy)
- [x] Done -- [Firefright Mage](https://scryfall.com/search?q=Firefright+Mage)
- [x] Done -- [Frenetic Sliver](https://scryfall.com/search?q=Frenetic+Sliver)
- [x] Done -- [Frozen Aether](https://scryfall.com/search?q=Frozen+Aether)
- [x] Done -- [Fungal Behemoth](https://scryfall.com/search?q=Fungal+Behemoth)
- [x] Done -- [Fury Charm](https://scryfall.com/search?q=Fury+Charm)
- [x] Done -- [Gaea's Anthem](https://scryfall.com/search?q=Gaeas+Anthem)
- [x] Done -- [Ghost Tactician](https://scryfall.com/search?q=Ghost+Tactician)
- [x] Done -- [Giant Dustwasp](https://scryfall.com/search?q=Giant+Dustwasp)
- [x] Done -- [Gossamer Phantasm](https://scryfall.com/search?q=Gossamer+Phantasm)
- [x] Done -- [Groundbreaker](https://scryfall.com/search?q=Groundbreaker)
- [x] Done -- [Hammerheim Deadeye](https://scryfall.com/search?q=Hammerheim+Deadeye)
- [x] Done -- [Harmonize](https://scryfall.com/search?q=Harmonize)
- [x] Done -- [Healing Leaves](https://scryfall.com/search?q=Healing+Leaves)
- [x] Done -- [Hedge Troll](https://scryfall.com/search?q=Hedge+Troll)
- [x] Done -- [Heroes Remembered](https://scryfall.com/search?q=Heroes+Remembered)
- [x] Done -- [Hunting Wilds](https://scryfall.com/search?q=Hunting+Wilds)
- [x] Done -- [Imp's Mischief](https://scryfall.com/search?q=Imps+Mischief)
- [x] Done -- [Intet, the Dreamer](https://scryfall.com/search?q=Intet,+the+Dreamer)
- [x] Done -- [Jedit Ojanen of Efrava](https://scryfall.com/search?q=Jedit+Ojanen+of+Efrava)
- [x] Done -- [Jodah's Avenger](https://scryfall.com/search?q=Jodahs+Avenger)
- [x] Done -- [Kavu Predator](https://scryfall.com/search?q=Kavu+Predator)
- [x] Done -- [Keen Sense](https://scryfall.com/search?q=Keen+Sense)
- [x] Done -- [Keldon Marauders](https://scryfall.com/search?q=Keldon+Marauders)
- [x] Done -- [Kor Dirge](https://scryfall.com/search?q=Kor+Dirge)
- [x] Done -- [Lavacore Elemental](https://scryfall.com/search?q=Lavacore+Elemental)
- [x] Done -- [Life and Limb](https://scryfall.com/search?q=Life+and+Limb)
- [x] Done -- [Magus of the Arena](https://scryfall.com/search?q=Magus+of+the+Arena)
- [x] Done -- [Magus of the Bazaar](https://scryfall.com/search?q=Magus+of+the+Bazaar)
- [x] Done -- [Magus of the Coffers](https://scryfall.com/search?q=Magus+of+the+Coffers)
- [x] Done -- [Magus of the Library](https://scryfall.com/search?q=Magus+of+the+Library)
- [x] Done -- [Magus of the Tabernacle](https://scryfall.com/search?q=Magus+of+the+Tabernacle)
- [x] Done -- [Malach of the Dawn](https://scryfall.com/search?q=Malach+of+the+Dawn)
- [x] Done -- [Mana Tithe](https://scryfall.com/search?q=Mana+Tithe)
- [x] Done -- [Mantle of Leadership](https://scryfall.com/search?q=Mantle+of+Leadership)
- [x] Done -- [Melancholy](https://scryfall.com/search?q=Melancholy)
- [x] Done -- [Merfolk Thaumaturgist](https://scryfall.com/search?q=Merfolk+Thaumaturgist)
- [x] Done -- [Mesa Enchantress](https://scryfall.com/search?q=Mesa+Enchantress)
- [x] Done -- [Midnight Charm](https://scryfall.com/search?q=Midnight+Charm)
- [x] Done -- [Mire Boa](https://scryfall.com/search?q=Mire+Boa)
- [x] Done -- [Mirri the Cursed](https://scryfall.com/search?q=Mirri+the+Cursed)
- [x] Done -- [Muck Drubb](https://scryfall.com/search?q=Muck+Drubb)
- [x] Done -- [Mycologist](https://scryfall.com/search?q=Mycologist)
- [x] Done -- [Necrotic Sliver](https://scryfall.com/search?q=Necrotic+Sliver)
- [x] Done -- [Needlepeak Spider](https://scryfall.com/search?q=Needlepeak+Spider)
- [x] Done -- [Null Profusion](https://scryfall.com/search?q=Null+Profusion)
- [x] Done -- [Numot, the Devastator](https://scryfall.com/search?q=Numot,+the+Devastator)
- [x] Done -- [Oros, the Avenger](https://scryfall.com/search?q=Oros,+the+Avenger)
- [x] Done -- [Ovinize](https://scryfall.com/search?q=Ovinize)
- [x] Done -- [Pallid Mycoderm](https://scryfall.com/search?q=Pallid+Mycoderm)
- [x] Done -- [Phantasmagorian](https://scryfall.com/search?q=Phantasmagorian)
- [x] Done -- [Piracy Charm](https://scryfall.com/search?q=Piracy+Charm)
- [x] Done -- [Pongify](https://scryfall.com/search?q=Pongify)
- [x] Done -- [Porphyry Nodes](https://scryfall.com/search?q=Porphyry+Nodes)
- [x] Done -- [Poultice Sliver](https://scryfall.com/search?q=Poultice+Sliver)
- [x] Done -- [Pouncing Wurm](https://scryfall.com/search?q=Pouncing+Wurm)
- [x] Done -- [Primal Plasma](https://scryfall.com/search?q=Primal+Plasma)
- [x] Done -- [Prodigal Pyromancer](https://scryfall.com/search?q=Prodigal+Pyromancer)
- [x] Done -- [Psychotrope Thallid](https://scryfall.com/search?q=Psychotrope+Thallid)
- [x] Done -- [Pyrohemia](https://scryfall.com/search?q=Pyrohemia)
- [x] Done -- [Radha, Heir to Keld](https://scryfall.com/search?q=Radha,+Heir+to+Keld)
- [x] Done -- [Rathi Trapper](https://scryfall.com/search?q=Rathi+Trapper)
- [x] Done -- [Reality Acid](https://scryfall.com/search?q=Reality+Acid)
- [x] Done -- [Rebuff the Wicked](https://scryfall.com/search?q=Rebuff+the+Wicked)
- [x] Done -- [Reckless Wurm](https://scryfall.com/search?q=Reckless+Wurm)
- [x] Done -- [Reflex Sliver](https://scryfall.com/search?q=Reflex+Sliver)
- [x] Done -- [Retether](https://scryfall.com/search?q=Retether)
- [x] Done -- [Revered Dead](https://scryfall.com/search?q=Revered+Dead)
- [x] Done -- [Ridged Kusite](https://scryfall.com/search?q=Ridged+Kusite)
- [x] Done -- [Riftmarked Knight](https://scryfall.com/search?q=Riftmarked+Knight)
- [x] Done -- [Riptide Pilferer](https://scryfall.com/search?q=Riptide+Pilferer)
- [x] Done -- [Roiling Horror](https://scryfall.com/search?q=Roiling+Horror)
- [x] Done -- [Rough // Tumble](https://scryfall.com/search?q=Rough+//+Tumble)
- [x] Done -- [Saltblast](https://scryfall.com/search?q=Saltblast)
- [x] Done -- [Saltfield Recluse](https://scryfall.com/search?q=Saltfield+Recluse)
- [x] Done -- [Seal of Primordium](https://scryfall.com/search?q=Seal+of+Primordium)
- [x] Done -- [Serendib Sorcerer](https://scryfall.com/search?q=Serendib+Sorcerer)
- [x] Done -- [Serra Sphinx](https://scryfall.com/search?q=Serra+Sphinx)
- [x] Done -- [Serra's Boon](https://scryfall.com/search?q=Serras+Boon)
- [x] Done -- [Shade of Trokair](https://scryfall.com/search?q=Shade+of+Trokair)
- [x] Done -- [Shaper Parasite](https://scryfall.com/search?q=Shaper+Parasite)
- [x] Done -- [Shivan Meteor](https://scryfall.com/search?q=Shivan+Meteor)
- [x] Done -- [Shivan Wumpus](https://scryfall.com/search?q=Shivan+Wumpus)
- [x] Done -- [Shrouded Lore](https://scryfall.com/search?q=Shrouded+Lore)
- [x] Done -- [Simian Spirit Guide](https://scryfall.com/search?q=Simian+Spirit+Guide)
- [x] Done -- [Sinew Sliver](https://scryfall.com/search?q=Sinew+Sliver)
- [x] Done -- [Skirk Shaman](https://scryfall.com/search?q=Skirk+Shaman)
- [x] Done -- [Sophic Centaur](https://scryfall.com/search?q=Sophic+Centaur)
- [x] Done -- [Spellshift](https://scryfall.com/search?q=Spellshift)
- [x] Done -- [Spitting Sliver](https://scryfall.com/search?q=Spitting+Sliver)
- [x] Done -- [Stingscourger](https://scryfall.com/search?q=Stingscourger)
- [x] Done -- [Stonecloaker](https://scryfall.com/search?q=Stonecloaker)
- [x] Done -- [Stormfront Riders](https://scryfall.com/search?q=Stormfront+Riders)
- [x] Done -- [Sulfur Elemental](https://scryfall.com/search?q=Sulfur+Elemental)
- [x] Done -- [Sunlance](https://scryfall.com/search?q=Sunlance)
- [x] Done -- [Synchronous Sliver](https://scryfall.com/search?q=Synchronous+Sliver)
- [x] Done -- [Temporal Extortion](https://scryfall.com/search?q=Temporal+Extortion)
- [x] Done -- [Teneb, the Harvester](https://scryfall.com/search?q=Teneb,+the+Harvester)
- [x] Done -- [Tidewalker](https://scryfall.com/search?q=Tidewalker)
- [x] Done -- [Timbermare](https://scryfall.com/search?q=Timbermare)
- [x] Done -- [Timebender](https://scryfall.com/search?q=Timebender)
- [x] Done -- [Timecrafting](https://scryfall.com/search?q=Timecrafting)
- [x] Done -- [Torchling](https://scryfall.com/search?q=Torchling)
- [x] Done -- [Treacherous Urge](https://scryfall.com/search?q=Treacherous+Urge)
- [x] Done -- [Uktabi Drake](https://scryfall.com/search?q=Uktabi+Drake)
- [x] Done -- [Urborg, Tomb of Yawgmoth](https://scryfall.com/search?q=Urborg,+Tomb+of+Yawgmoth)
- [x] Done -- [Utopia Vow](https://scryfall.com/search?q=Utopia+Vow)
- [x] Done -- [Vampiric Link](https://scryfall.com/search?q=Vampiric+Link)
- [x] Done -- [Veiling Oddity](https://scryfall.com/search?q=Veiling+Oddity)
- [x] Done -- [Venarian Glimmer](https://scryfall.com/search?q=Venarian+Glimmer)
- [x] Done -- [Vitaspore Thallid](https://scryfall.com/search?q=Vitaspore+Thallid)
- [x] Done -- [Voidstone Gargoyle](https://scryfall.com/search?q=Voidstone+Gargoyle)
- [x] Done -- [Volcano Hellion](https://scryfall.com/search?q=Volcano+Hellion)
- [x] Done -- [Vorosh, the Hunter](https://scryfall.com/search?q=Vorosh,+the+Hunter)
- [x] Done -- [Waning Wurm](https://scryfall.com/search?q=Waning+Wurm)
- [x] Done -- [Whitemane Lion](https://scryfall.com/search?q=Whitemane+Lion)
- [x] Done -- [Wild Pair](https://scryfall.com/search?q=Wild+Pair)
- [x] Done -- [Wistful Thinking](https://scryfall.com/search?q=Wistful+Thinking)

**Comment by NoahGleason** [comment]
A pull request has been submitted for Dichotomancy (#5140) and for Molten Firebird (#5141), so this should be closed once both are merged.
