### ISSUE TITLE
FUT - Future Sight set card implementation tracker

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4958]
- [x] Not Done -- [Vedalken AEthermage](https://scryfall.com/search?q=Vedalken+AEthermage)
- [x] Done -- [Akroma's Memorial](https://scryfall.com/search?q=Akromas+Memorial)
- [x] Done -- [Angel of Salvation](https://scryfall.com/search?q=Angel+of+Salvation)
- [x] Done -- [Arc Blade](https://scryfall.com/search?q=Arc+Blade)
- [x] Done -- [Arcanum Wings](https://scryfall.com/search?q=Arcanum+Wings)
- [x] Done -- [Augur il-Vec](https://scryfall.com/search?q=Augur+il-Vec)
- [x] Done -- [Augur of Skulls](https://scryfall.com/search?q=Augur+of+Skulls)
- [x] Done -- [Aven Augur](https://scryfall.com/search?q=Aven+Augur)
- [x] Done -- [Aven Mindcensor](https://scryfall.com/search?q=Aven+Mindcensor)
- [x] Done -- [Barren Glory](https://scryfall.com/search?q=Barren+Glory)
- [x] Done -- [Baru, Fist of Krosa](https://scryfall.com/search?q=Baru,+Fist+of+Krosa)
- [x] Done -- [Bitter Ordeal](https://scryfall.com/search?q=Bitter+Ordeal)
- [x] Done -- [Blade of the Sixth Pride](https://scryfall.com/search?q=Blade+of+the+Sixth+Pride)
- [x] Done -- [Blind Phantasm](https://scryfall.com/search?q=Blind+Phantasm)
- [x] Done -- [Bloodshot Trainee](https://scryfall.com/search?q=Bloodshot+Trainee)
- [x] Done -- [Bogardan Lancer](https://scryfall.com/search?q=Bogardan+Lancer)
- [x] Done -- [Boldwyr Intimidator](https://scryfall.com/search?q=Boldwyr+Intimidator)
- [x] Done -- [Bonded Fetch](https://scryfall.com/search?q=Bonded+Fetch)
- [x] Done -- [Bound in Silence](https://scryfall.com/search?q=Bound+in+Silence)
- [x] Done -- [Bridge from Below](https://scryfall.com/search?q=Bridge+from+Below)
- [x] Done -- [Centaur Omenreader](https://scryfall.com/search?q=Centaur+Omenreader)
- [x] Done -- [Char-Rumbler](https://scryfall.com/search?q=Char-Rumbler)
- [x] Done -- [Chronomantic Escape](https://scryfall.com/search?q=Chronomantic+Escape)
- [x] Done -- [Cloud Key](https://scryfall.com/search?q=Cloud+Key)
- [x] Done -- [Cloudseeder](https://scryfall.com/search?q=Cloudseeder)
- [x] Done -- [Coalition Relic](https://scryfall.com/search?q=Coalition+Relic)
- [x] Done -- [Cryptic Annelid](https://scryfall.com/search?q=Cryptic+Annelid)
- [x] Done -- [Cutthroat il-Dal](https://scryfall.com/search?q=Cutthroat+il-Dal)
- [x] Done -- [Cyclical Evolution](https://scryfall.com/search?q=Cyclical+Evolution)
- [x] Done -- [Dakmor Salvage](https://scryfall.com/search?q=Dakmor+Salvage)
- [x] Done -- [Darksteel Garrison](https://scryfall.com/search?q=Darksteel+Garrison)
- [x] Done -- [Daybreak Coronet](https://scryfall.com/search?q=Daybreak+Coronet)
- [x] Done -- [Death Rattle](https://scryfall.com/search?q=Death+Rattle)
- [x] Done -- [Deepcavern Imp](https://scryfall.com/search?q=Deepcavern+Imp)
- [x] Done -- [Delay](https://scryfall.com/search?q=Delay)
- [x] Done -- [Dryad Arbor](https://scryfall.com/search?q=Dryad+Arbor)
- [x] Done -- [Dust of Moments](https://scryfall.com/search?q=Dust+of+Moments)
- [x] Done -- [Edge of Autumn](https://scryfall.com/search?q=Edge+of+Autumn)
- [x] Done -- [Emberwilde Augur](https://scryfall.com/search?q=Emberwilde+Augur)
- [x] Done -- [Emblem of the Warmind](https://scryfall.com/search?q=Emblem+of+the+Warmind)
- [x] Done -- [Epochrasite](https://scryfall.com/search?q=Epochrasite)
- [x] Done -- [Even the Odds](https://scryfall.com/search?q=Even+the+Odds)
- [x] Done -- [Fatal Attraction](https://scryfall.com/search?q=Fatal+Attraction)
- [x] Done -- [Festering March](https://scryfall.com/search?q=Festering+March)
- [x] Done -- [Fleshwrither](https://scryfall.com/search?q=Fleshwrither)
- [x] Done -- [Flowstone Embrace](https://scryfall.com/search?q=Flowstone+Embrace)
- [x] Done -- [Fomori Nomad](https://scryfall.com/search?q=Fomori+Nomad)
- [x] Done -- [Force of Savagery](https://scryfall.com/search?q=Force+of+Savagery)
- [x] Done -- [Foresee](https://scryfall.com/search?q=Foresee)
- [x] Done -- [Frenzy Sliver](https://scryfall.com/search?q=Frenzy+Sliver)
- [x] Done -- [Gathan Raiders](https://scryfall.com/search?q=Gathan+Raiders)
- [x] Done -- [Ghostfire](https://scryfall.com/search?q=Ghostfire)
- [x] Done -- [Gibbering Descent](https://scryfall.com/search?q=Gibbering+Descent)
- [x] Done -- [Gift of Granite](https://scryfall.com/search?q=Gift+of+Granite)
- [x] Done -- [Glittering Wish](https://scryfall.com/search?q=Glittering+Wish)
- [x] Done -- [Goldmeadow Lookout](https://scryfall.com/search?q=Goldmeadow+Lookout)
- [x] Done -- [Grave Peril](https://scryfall.com/search?q=Grave+Peril)
- [x] Done -- [Grave Scrabbler](https://scryfall.com/search?q=Grave+Scrabbler)
- [x] Done -- [Graven Cairns](https://scryfall.com/search?q=Graven+Cairns)
- [x] Done -- [Grinning Ignus](https://scryfall.com/search?q=Grinning+Ignus)
- [x] Done -- [Grove of the Burnwillows](https://scryfall.com/search?q=Grove+of+the+Burnwillows)
- [x] Done -- [Haze of Rage](https://scryfall.com/search?q=Haze+of+Rage)
- [x] Done -- [Heartwood Storyteller](https://scryfall.com/search?q=Heartwood+Storyteller)
- [x] Done -- [Henchfiend of Ukor](https://scryfall.com/search?q=Henchfiend+of+Ukor)
- [x] Done -- [Homing Sliver](https://scryfall.com/search?q=Homing+Sliver)
- [x] Done -- [Horizon Canopy](https://scryfall.com/search?q=Horizon+Canopy)
- [x] Done -- [Ichor Slick](https://scryfall.com/search?q=Ichor+Slick)
- [x] Done -- [Imperial Mask](https://scryfall.com/search?q=Imperial+Mask)
- [x] Done -- [Imperiosaur](https://scryfall.com/search?q=Imperiosaur)
- [x] Done -- [Infiltrator il-Kor](https://scryfall.com/search?q=Infiltrator+il-Kor)
- [x] Done -- [Intervention Pact](https://scryfall.com/search?q=Intervention+Pact)
- [x] Done -- [Jhoira of the Ghitu](https://scryfall.com/search?q=Jhoira+of+the+Ghitu)
- [x] Done -- [Judge Unworthy](https://scryfall.com/search?q=Judge+Unworthy)
- [x] Done -- [Kavu Primarch](https://scryfall.com/search?q=Kavu+Primarch)
- [x] Done -- [Keldon Megaliths](https://scryfall.com/search?q=Keldon+Megaliths)
- [x] Done -- [Knight of Sursi](https://scryfall.com/search?q=Knight+of+Sursi)
- [x] Done -- [Korlash, Heir to Blackblade](https://scryfall.com/search?q=Korlash,+Heir+to+Blackblade)
- [x] Done -- [Leaden Fists](https://scryfall.com/search?q=Leaden+Fists)
- [x] Done -- [Linessa, Zephyr Mage](https://scryfall.com/search?q=Linessa,+Zephyr+Mage)
- [x] Done -- [Llanowar Augur](https://scryfall.com/search?q=Llanowar+Augur)
- [x] Done -- [Llanowar Empath](https://scryfall.com/search?q=Llanowar+Empath)
- [x] Done -- [Llanowar Mentor](https://scryfall.com/search?q=Llanowar+Mentor)
- [x] Done -- [Llanowar Reborn](https://scryfall.com/search?q=Llanowar+Reborn)
- [x] Done -- [Logic Knot](https://scryfall.com/search?q=Logic+Knot)
- [x] Done -- [Lost Auramancers](https://scryfall.com/search?q=Lost+Auramancers)
- [x] Done -- [Lost Hours](https://scryfall.com/search?q=Lost+Hours)
- [x] Done -- [Lucent Liminid](https://scryfall.com/search?q=Lucent+Liminid)
- [x] Done -- [Lumithread Field](https://scryfall.com/search?q=Lumithread+Field)
- [x] Done -- [Lymph Sliver](https://scryfall.com/search?q=Lymph+Sliver)
- [x] Done -- [Maelstrom Djinn](https://scryfall.com/search?q=Maelstrom+Djinn)
- [x] Done -- [Magus of the Abyss](https://scryfall.com/search?q=Magus+of+the+Abyss)
- [x] Done -- [Magus of the Future](https://scryfall.com/search?q=Magus+of+the+Future)
- [x] Done -- [Magus of the Moat](https://scryfall.com/search?q=Magus+of+the+Moat)
- [x] Done -- [Magus of the Moon](https://scryfall.com/search?q=Magus+of+the+Moon)
- [x] Done -- [Magus of the Vineyard](https://scryfall.com/search?q=Magus+of+the+Vineyard)
- [x] Done -- [Marshaling Cry](https://scryfall.com/search?q=Marshaling+Cry)
- [x] Done -- [Mass of Ghouls](https://scryfall.com/search?q=Mass+of+Ghouls)
- [x] Done -- [Mesmeric Sliver](https://scryfall.com/search?q=Mesmeric+Sliver)
- [x] Done -- [Minions' Murmurs](https://scryfall.com/search?q=Minions+Murmurs)
- [x] Done -- [Mistmeadow Skulk](https://scryfall.com/search?q=Mistmeadow+Skulk)
- [x] Done -- [Molten Disaster](https://scryfall.com/search?q=Molten+Disaster)
- [x] Done -- [Muraganda Petroglyphs](https://scryfall.com/search?q=Muraganda+Petroglyphs)
- [x] Done -- [Mystic Speculation](https://scryfall.com/search?q=Mystic+Speculation)
- [x] Done -- [Nacatl War-Pride](https://scryfall.com/search?q=Nacatl+War-Pride)
- [x] Done -- [Narcomoeba](https://scryfall.com/search?q=Narcomoeba)
- [x] Done -- [Nessian Courser](https://scryfall.com/search?q=Nessian+Courser)
- [x] Done -- [New Benalia](https://scryfall.com/search?q=New+Benalia)
- [x] Done -- [Nihilith](https://scryfall.com/search?q=Nihilith)
- [x] Done -- [Nimbus Maze](https://scryfall.com/search?q=Nimbus+Maze)
- [x] Done -- [Nix](https://scryfall.com/search?q=Nix)
- [x] Done -- [Oblivion Crown](https://scryfall.com/search?q=Oblivion+Crown)
- [x] Done -- [Oriss, Samite Guardian](https://scryfall.com/search?q=Oriss,+Samite+Guardian)
- [x] Done -- [Pact of Negation](https://scryfall.com/search?q=Pact+of+Negation)
- [x] Done -- [Pact of the Titan](https://scryfall.com/search?q=Pact+of+the+Titan)
- [x] Done -- [Patrician's Scorn](https://scryfall.com/search?q=Patricians+Scorn)
- [x] Done -- [Petrified Plating](https://scryfall.com/search?q=Petrified+Plating)
- [x] Done -- [Phosphorescent Feast](https://scryfall.com/search?q=Phosphorescent+Feast)
- [x] Done -- [Pooling Venom](https://scryfall.com/search?q=Pooling+Venom)
- [x] Done -- [Putrid Cyclops](https://scryfall.com/search?q=Putrid+Cyclops)
- [x] Done -- [Pyromancer's Swath](https://scryfall.com/search?q=Pyromancers+Swath)
- [x] Done -- [Quagnoth](https://scryfall.com/search?q=Quagnoth)
- [x] Done -- [Quiet Disrepair](https://scryfall.com/search?q=Quiet+Disrepair)
- [x] Done -- [Ramosian Revivalist](https://scryfall.com/search?q=Ramosian+Revivalist)
- [x] Done -- [Ravaging Riftwurm](https://scryfall.com/search?q=Ravaging+Riftwurm)
- [x] Done -- [Reality Strobe](https://scryfall.com/search?q=Reality+Strobe)
- [x] Done -- [Riddle of Lightning](https://scryfall.com/search?q=Riddle+of+Lightning)
- [x] Done -- [Rift Elemental](https://scryfall.com/search?q=Rift+Elemental)
- [x] Done -- [Riftsweeper](https://scryfall.com/search?q=Riftsweeper)
- [x] Done -- [Rites of Flourishing](https://scryfall.com/search?q=Rites+of+Flourishing)
- [x] Done -- [River of Tears](https://scryfall.com/search?q=River+of+Tears)
- [x] Done -- [Saltskitter](https://scryfall.com/search?q=Saltskitter)
- [x] Done -- [Samite Censer-Bearer](https://scryfall.com/search?q=Samite+Censer-Bearer)
- [x] Done -- [Sarcomite Myr](https://scryfall.com/search?q=Sarcomite+Myr)
- [x] Done -- [Scourge of Kher Ridges](https://scryfall.com/search?q=Scourge+of+Kher+Ridges)
- [x] Done -- [Scout's Warning](https://scryfall.com/search?q=Scouts+Warning)
- [x] Done -- [Second Wind](https://scryfall.com/search?q=Second+Wind)
- [x] Done -- [Seht's Tiger](https://scryfall.com/search?q=Sehts+Tiger)
- [x] Done -- [Shah of Naar Isle](https://scryfall.com/search?q=Shah+of+Naar+Isle)
- [x] Done -- [Shapeshifter's Marrow](https://scryfall.com/search?q=Shapeshifters+Marrow)
- [x] Done -- [Shimian Specter](https://scryfall.com/search?q=Shimian+Specter)
- [x] Done -- [Shivan Sand-Mage](https://scryfall.com/search?q=Shivan+Sand-Mage)
- [x] Done -- [Skirk Ridge Exhumer](https://scryfall.com/search?q=Skirk+Ridge+Exhumer)
- [x] Done -- [Skizzik Surger](https://scryfall.com/search?q=Skizzik+Surger)
- [x] Done -- [Slaughter Pact](https://scryfall.com/search?q=Slaughter+Pact)
- [x] Done -- [Sliver Legion](https://scryfall.com/search?q=Sliver+Legion)
- [x] Done -- [Sliversmith](https://scryfall.com/search?q=Sliversmith)
- [x] Done -- [Snake Cult Initiation](https://scryfall.com/search?q=Snake+Cult+Initiation)
- [x] Done -- [Soultether Golem](https://scryfall.com/search?q=Soultether+Golem)
- [x] Done -- [Sparkspitter](https://scryfall.com/search?q=Sparkspitter)
- [x] Done -- [Spellweaver Volute](https://scryfall.com/search?q=Spellweaver+Volute)
- [x] Done -- [Spellwild Ouphe](https://scryfall.com/search?q=Spellwild+Ouphe)
- [x] Done -- [Spin into Myth](https://scryfall.com/search?q=Spin+into+Myth)
- [x] Done -- [Spirit en-Dal](https://scryfall.com/search?q=Spirit+en-Dal)
- [x] Done -- [Sporoloth Ancient](https://scryfall.com/search?q=Sporoloth+Ancient)
- [x] Done -- [Sprout Swarm](https://scryfall.com/search?q=Sprout+Swarm)
- [x] Done -- [Steamflogger Boss](https://scryfall.com/search?q=Steamflogger+Boss)
- [x] Done -- [Storm Entity](https://scryfall.com/search?q=Storm+Entity)
- [x] Done -- [Street Wraith](https://scryfall.com/search?q=Street+Wraith)
- [x] Done -- [Stronghold Rats](https://scryfall.com/search?q=Stronghold+Rats)
- [x] Done -- [Summoner's Pact](https://scryfall.com/search?q=Summoners+Pact)
- [x] Done -- [Sword of the Meek](https://scryfall.com/search?q=Sword+of+the+Meek)
- [x] Done -- [Take Possession](https://scryfall.com/search?q=Take+Possession)
- [x] Done -- [Tarmogoyf](https://scryfall.com/search?q=Tarmogoyf)
- [x] Done -- [Tarox Bladewing](https://scryfall.com/search?q=Tarox+Bladewing)
- [x] Done -- [Thornweald Archer](https://scryfall.com/search?q=Thornweald+Archer)
- [x] Done -- [Thunderblade Charge](https://scryfall.com/search?q=Thunderblade+Charge)
- [x] Done -- [Tolaria West](https://scryfall.com/search?q=Tolaria+West)
- [x] Done -- [Tombstalker](https://scryfall.com/search?q=Tombstalker)
- [x] Done -- [Unblinking Bleb](https://scryfall.com/search?q=Unblinking+Bleb)
- [x] Done -- [Utopia Mycon](https://scryfall.com/search?q=Utopia+Mycon)
- [x] Done -- [Vedalken Aethermage](https://scryfall.com/search?q=Vedalken+Aethermage)
- [x] Done -- [Veilstone Amulet](https://scryfall.com/search?q=Veilstone+Amulet)
- [x] Done -- [Venser's Diffusion](https://scryfall.com/search?q=Vensers+Diffusion)
- [x] Done -- [Venser, Shaper Savant](https://scryfall.com/search?q=Venser,+Shaper+Savant)
- [x] Done -- [Virulent Sliver](https://scryfall.com/search?q=Virulent+Sliver)
- [x] Done -- [Whetwheel](https://scryfall.com/search?q=Whetwheel)
- [x] Done -- [Whip-Spine Drake](https://scryfall.com/search?q=Whip-Spine+Drake)
- [x] Done -- [Witch's Mist](https://scryfall.com/search?q=Witchs+Mist)
- [x] Done -- [Wrap in Vigor](https://scryfall.com/search?q=Wrap+in+Vigor)
- [x] Done -- [Yixlid Jailer](https://scryfall.com/search?q=Yixlid+Jailer)
- [x] Done -- [Zoetic Cavern](https://scryfall.com/search?q=Zoetic+Cavern)
