### ISSUE TITLE
BBD - Battlebond set card implementation tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4962]
Mark cards you are working on in the second post of this issue.
If the card is committed, mark here the Checkbox of the card to signal it's finished.

- [ ] Not Done -- [Charging Binox](https://scryfall.com/search?q=Charging+Binox)
- [ ] Not Done -- [Dwarven Lightsmith](https://scryfall.com/search?q=Dwarven+Lightsmith)
- [ ] Not Done -- [Fan Favorite](https://scryfall.com/search?q=Fan+Favorite)
- [ ] Not Done -- [Huddle Up](https://scryfall.com/search?q=Huddle+Up)
- [ ] Not Done -- [Pir's Whim](https://scryfall.com/search?q=Pirs+Whim)
- [ ] Not Done -- [Pir, Imaginative Rascal](https://scryfall.com/search?q=Pir,+Imaginative+Rascal)
- [ ] Not Done -- [Rowan Kenrith](https://scryfall.com/search?q=Rowan+Kenrith)
- [ ] Not Done -- [Rushblade Commander](https://scryfall.com/search?q=Rushblade+Commander)
- [ ] Not Done -- [Soaring Show-Off](https://scryfall.com/search?q=Soaring+Show-Off)
- [ ] Not Done -- [Toothy, Imaginary Friend](https://scryfall.com/search?q=Toothy,+Imaginary+Friend)
- [ ] Not Done -- [Will Kenrith](https://scryfall.com/search?q=Will+Kenrith)
- [x] Done -- [Bountiful Promenade](https://scryfall.com/search?q=Bountiful+Promenade)
- [x] Done -- [Luxury Suite](https://scryfall.com/search?q=Luxury+Suite)
- [x] Done -- [Morphic Pool](https://scryfall.com/search?q=Morphic+Pool)
- [x] Done -- [Sea of Clouds](https://scryfall.com/search?q=Sea+of+Clouds)
- [x] Done -- [Spire Garden](https://scryfall.com/search?q=Spire+Garden)

**Comment by theelk801** [comment]
- [ ] In progress -- [Charging Binox](https://scryfall.com/search?q=Charging+Binox)
- [ ] In progress -- [Dwarven Lightsmith](https://scryfall.com/search?q=Dwarven+Lightsmith)
- [ ] In progress -- [Fan Favorite](https://scryfall.com/search?q=Fan+Favorite)
- [ ] In progress -- [Huddle Up](https://scryfall.com/search?q=Huddle+Up)
- [ ] In progress -- [Pir's Whim](https://scryfall.com/search?q=Pirs+Whim)
- [ ] In progress -- [Pir, Imaginative Rascal](https://scryfall.com/search?q=Pir,+Imaginative+Rascal)
- [ ] In progress -- [Rowan Kenrith](https://scryfall.com/search?q=Rowan+Kenrith)
- [ ] In progress -- [Rushblade Commander](https://scryfall.com/search?q=Rushblade+Commander)
- [ ] In progress -- [Soaring Show-Off](https://scryfall.com/search?q=Soaring+Show-Off)
- [ ] In progress -- [Toothy, Imaginary Friend](https://scryfall.com/search?q=Toothy,+Imaginary+Friend)
- [ ] In progress -- [Will Kenrith](https://scryfall.com/search?q=Will+Kenrith)

**Comment by Zzooouhh** [comment]
Thrilling Encore implemented
