### ISSUE TITLE
RAV - Ravnica: City of Guilds set card implementation tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4963]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

https://magic.wizards.com/en/game-info/products/card-set-archive/fifth-dawn

# Unimplemented cards

- none

# Cards in set:

- [x] [Agrus Kos, Wojek Veteran](https://magiccards.info/query?q=!Agrus+Kos,+Wojek+Veteran)
- [x] [Auratouched Mage](https://magiccards.info/query?q=!Auratouched+Mage)
- [x] [Autochthon Wurm](https://magiccards.info/query?q=!Autochthon+Wurm)
- [x] [Barbarian Riftcutter](https://magiccards.info/query?q=!Barbarian+Riftcutter)
- [x] [Bathe in Light](https://magiccards.info/query?q=!Bathe+in+Light)
- [x] [Belltower Sphinx](https://magiccards.info/query?q=!Belltower+Sphinx)
- [x] [Benevolent Ancestor](https://magiccards.info/query?q=!Benevolent+Ancestor)
- [x] [Birds of Paradise](https://magiccards.info/query?q=!Birds+of+Paradise)
- [x] [Blazing Archon](https://magiccards.info/query?q=!Blazing+Archon)
- [x] [Blockbuster](https://magiccards.info/query?q=!Blockbuster)
- [x] [Blood Funnel](https://magiccards.info/query?q=!Blood+Funnel)
- [x] [Bloodbond March](https://magiccards.info/query?q=!Bloodbond+March)
- [x] [Bloodletter Quill](https://magiccards.info/query?q=!Bloodletter+Quill)
- [x] [Boros Fury-Shield](https://magiccards.info/query?q=!Boros+Fury-Shield)
- [x] [Boros Garrison](https://magiccards.info/query?q=!Boros+Garrison)
- [x] [Boros Guildmage](https://magiccards.info/query?q=!Boros+Guildmage)
- [x] [Boros Recruit](https://magiccards.info/query?q=!Boros+Recruit)
- [x] [Boros Signet](https://magiccards.info/query?q=!Boros+Signet)
- [x] [Boros Swiftblade](https://magiccards.info/query?q=!Boros+Swiftblade)
- [x] [Bottled Cloister](https://magiccards.info/query?q=!Bottled+Cloister)
- [x] [Brainspoil](https://magiccards.info/query?q=!Brainspoil)
- [x] [Bramble Elemental](https://magiccards.info/query?q=!Bramble+Elemental)
- [x] [Breath of Fury](https://magiccards.info/query?q=!Breath+of+Fury)
- [x] [Brightflame](https://magiccards.info/query?q=!Brightflame)
- [x] [Caregiver](https://magiccards.info/query?q=!Caregiver)
- [x] [Carrion Howler](https://magiccards.info/query?q=!Carrion+Howler)
- [x] [Carven Caryatid](https://magiccards.info/query?q=!Carven+Caryatid)
- [x] [Centaur Safeguard](https://magiccards.info/query?q=!Centaur+Safeguard)
- [x] [Cerulean Sphinx](https://magiccards.info/query?q=!Cerulean+Sphinx)
- [x] [Chant of Vitu-Ghazi](https://magiccards.info/query?q=!Chant+of+Vitu-Ghazi)
- [x] [Char](https://magiccards.info/query?q=!Char)
- [x] [Chord of Calling](https://magiccards.info/query?q=!Chord+of+Calling)
- [x] [Chorus of the Conclave](https://magiccards.info/query?q=!Chorus+of+the+Conclave)
- [x] [Circu, Dimir Lobotomist](https://magiccards.info/query?q=!Circu,+Dimir+Lobotomist)
- [x] [Civic Wayfinder](https://magiccards.info/query?q=!Civic+Wayfinder)
- [x] [Cleansing Beam](https://magiccards.info/query?q=!Cleansing+Beam)
- [x] [Clinging Darkness](https://magiccards.info/query?q=!Clinging+Darkness)
- [x] [Cloudstone Curio](https://magiccards.info/query?q=!Cloudstone+Curio)
- [x] [Clutch of the Undercity](https://magiccards.info/query?q=!Clutch+of+the+Undercity)
- [x] [Coalhauler Swine](https://magiccards.info/query?q=!Coalhauler+Swine)
- [x] [Compulsive Research](https://magiccards.info/query?q=!Compulsive+Research)
- [x] [Concerted Effort](https://magiccards.info/query?q=!Concerted+Effort)
- [x] [Conclave Equenaut](https://magiccards.info/query?q=!Conclave+Equenaut)
- [x] [Conclave Phalanx](https://magiccards.info/query?q=!Conclave+Phalanx)
- [x] [Conclave's Blessing](https://magiccards.info/query?q=!Conclave's+Blessing)
- [x] [Congregation at Dawn](https://magiccards.info/query?q=!Congregation+at+Dawn)
- [x] [Consult the Necrosages](https://magiccards.info/query?q=!Consult+the+Necrosages)
- [x] [Convolute](https://magiccards.info/query?q=!Convolute)
- [x] [Copy Enchantment](https://magiccards.info/query?q=!Copy+Enchantment)
- [x] [Courier Hawk](https://magiccards.info/query?q=!Courier+Hawk)
- [x] [Crown of Convergence](https://magiccards.info/query?q=!Crown+of+Convergence)
- [x] [Cyclopean Snare](https://magiccards.info/query?q=!Cyclopean+Snare)
- [x] [Dark Confidant](https://magiccards.info/query?q=!Dark+Confidant)
- [x] [Dark Heart of the Wood](https://magiccards.info/query?q=!Dark+Heart+of+the+Wood)
- [x] [Darkblast](https://magiccards.info/query?q=!Darkblast)
- [x] [Devouring Light](https://magiccards.info/query?q=!Devouring+Light)
- [x] [Dimir Aqueduct](https://magiccards.info/query?q=!Dimir+Aqueduct)
- [x] [Dimir Cutpurse](https://magiccards.info/query?q=!Dimir+Cutpurse)
- [x] [Dimir Doppelganger](https://magiccards.info/query?q=!Dimir+Doppelganger)
- [x] [Dimir Guildmage](https://magiccards.info/query?q=!Dimir+Guildmage)
- [x] [Dimir House Guard](https://magiccards.info/query?q=!Dimir+House+Guard)
- [x] [Dimir Infiltrator](https://magiccards.info/query?q=!Dimir+Infiltrator)
- [x] [Dimir Machinations](https://magiccards.info/query?q=!Dimir+Machinations)
- [x] [Dimir Signet](https://magiccards.info/query?q=!Dimir+Signet)
- [x] [Disembowel](https://magiccards.info/query?q=!Disembowel)
- [x] [Divebomber Griffin](https://magiccards.info/query?q=!Divebomber+Griffin)
- [x] [Dizzy Spell](https://magiccards.info/query?q=!Dizzy+Spell)
- [x] [Dogpile](https://magiccards.info/query?q=!Dogpile)
- [x] [Doubling Season](https://magiccards.info/query?q=!Doubling+Season)
- [x] [Dowsing Shaman](https://magiccards.info/query?q=!Dowsing+Shaman)
- [x] [Drake Familiar](https://magiccards.info/query?q=!Drake+Familiar)
- [x] [Dream Leash](https://magiccards.info/query?q=!Dream+Leash)
- [x] [Drift of Phantasms](https://magiccards.info/query?q=!Drift+of+Phantasms)
- [x] [Dromad Purebred](https://magiccards.info/query?q=!Dromad+Purebred)
- [x] [Drooling Groodion](https://magiccards.info/query?q=!Drooling+Groodion)
- [x] [Dryad's Caress](https://magiccards.info/query?q=!Dryad's+Caress)
- [x] [Duskmantle, House of Shadow](https://magiccards.info/query?q=!Duskmantle,+House+of+Shadow)
- [x] [Elves of Deep Shadow](https://magiccards.info/query?q=!Elves+of+Deep+Shadow)
- [x] [Elvish Skysweeper](https://magiccards.info/query?q=!Elvish+Skysweeper)
- [x] [Empty the Catacombs](https://magiccards.info/query?q=!Empty+the+Catacombs)
- [x] [Ethereal Usher](https://magiccards.info/query?q=!Ethereal+Usher)
- [x] [Excruciator](https://magiccards.info/query?q=!Excruciator)
- [x] [Eye of the Storm](https://magiccards.info/query?q=!Eye+of+the+Storm)
- [x] [Faith's Fetters](https://magiccards.info/query?q=!Faith's+Fetters)
- [x] [Farseek](https://magiccards.info/query?q=!Farseek)
- [x] [Festival of the Guildpact](https://magiccards.info/query?q=!Festival+of+the+Guildpact)
- [x] [Fiery Conclusion](https://magiccards.info/query?q=!Fiery+Conclusion)
- [x] [Firemane Angel](https://magiccards.info/query?q=!Firemane+Angel)
- [x] [Fists of Ironwood](https://magiccards.info/query?q=!Fists+of+Ironwood)
- [x] [Flame Fusillade](https://magiccards.info/query?q=!Flame+Fusillade)
- [x] [Flame-Kin Zealot](https://magiccards.info/query?q=!Flame-Kin+Zealot)
- [x] [Flash Conscription](https://magiccards.info/query?q=!Flash+Conscription)
- [x] [Flickerform](https://magiccards.info/query?q=!Flickerform)
- [x] [Flight of Fancy](https://magiccards.info/query?q=!Flight+of+Fancy)
- [x] [Flow of Ideas](https://magiccards.info/query?q=!Flow+of+Ideas)
- [x] [Followed Footsteps](https://magiccards.info/query?q=!Followed+Footsteps)
- [x] [Forest](https://magiccards.info/query?q=!Forest)
- [x] [Frenzied Goblin](https://magiccards.info/query?q=!Frenzied+Goblin)
- [x] [Galvanic Arc](https://magiccards.info/query?q=!Galvanic+Arc)
- [x] [Gate Hound](https://magiccards.info/query?q=!Gate+Hound)
- [x] [Gather Courage](https://magiccards.info/query?q=!Gather+Courage)
- [x] [Gaze of the Gorgon](https://magiccards.info/query?q=!Gaze+of+the+Gorgon)
- [x] [Ghosts of the Innocent](https://magiccards.info/query?q=!Ghosts+of+the+Innocent)
- [x] [Glare of Subdual](https://magiccards.info/query?q=!Glare+of+Subdual)
- [x] [Glass Golem](https://magiccards.info/query?q=!Glass+Golem)
- [x] [Gleancrawler](https://magiccards.info/query?q=!Gleancrawler)
- [x] [Glimpse the Unthinkable](https://magiccards.info/query?q=!Glimpse+the+Unthinkable)
- [x] [Goblin Fire Fiend](https://magiccards.info/query?q=!Goblin+Fire+Fiend)
- [x] [Goblin Spelunkers](https://magiccards.info/query?q=!Goblin+Spelunkers)
- [x] [Golgari Brownscale](https://magiccards.info/query?q=!Golgari+Brownscale)
- [x] [Golgari Germination](https://magiccards.info/query?q=!Golgari+Germination)
- [x] [Golgari Grave-Troll](https://magiccards.info/query?q=!Golgari+Grave-Troll)
- [x] [Golgari Guildmage](https://magiccards.info/query?q=!Golgari+Guildmage)
- [x] [Golgari Rot Farm](https://magiccards.info/query?q=!Golgari+Rot+Farm)
- [x] [Golgari Rotwurm](https://magiccards.info/query?q=!Golgari+Rotwurm)
- [x] [Golgari Signet](https://magiccards.info/query?q=!Golgari+Signet)
- [x] [Golgari Thug](https://magiccards.info/query?q=!Golgari+Thug)
- [x] [Goliath Spider](https://magiccards.info/query?q=!Goliath+Spider)
- [x] [Grave-Shell Scarab](https://magiccards.info/query?q=!Grave-Shell+Scarab)
- [x] [Grayscaled Gharial](https://magiccards.info/query?q=!Grayscaled+Gharial)
- [x] [Greater Forgeling](https://magiccards.info/query?q=!Greater+Forgeling)
- [x] [Greater Mossdog](https://magiccards.info/query?q=!Greater+Mossdog)
- [x] [Grifter's Blade](https://magiccards.info/query?q=!Grifter's+Blade)
- [x] [Grozoth](https://magiccards.info/query?q=!Grozoth)
- [x] [Guardian of Vitu-Ghazi](https://magiccards.info/query?q=!Guardian+of+Vitu-Ghazi)
- [x] [Halcyon Glaze](https://magiccards.info/query?q=!Halcyon+Glaze)
- [x] [Hammerfist Giant](https://magiccards.info/query?q=!Hammerfist+Giant)
- [x] [Helldozer](https://magiccards.info/query?q=!Helldozer)
- [x] [Hex](https://magiccards.info/query?q=!Hex)
- [x] [Hour of Reckoning](https://magiccards.info/query?q=!Hour+of+Reckoning)
- [x] [Hunted Dragon](https://magiccards.info/query?q=!Hunted+Dragon)
- [x] [Hunted Horror](https://magiccards.info/query?q=!Hunted+Horror)
- [x] [Hunted Lammasu](https://magiccards.info/query?q=!Hunted+Lammasu)
- [x] [Hunted Phantasm](https://magiccards.info/query?q=!Hunted+Phantasm)
- [x] [Hunted Troll](https://magiccards.info/query?q=!Hunted+Troll)
- [x] [Incite Hysteria](https://magiccards.info/query?q=!Incite+Hysteria)
- [x] [Indentured Oaf](https://magiccards.info/query?q=!Indentured+Oaf)
- [x] [Induce Paranoia](https://magiccards.info/query?q=!Induce+Paranoia)
- [x] [Infectious Host](https://magiccards.info/query?q=!Infectious+Host)
- [x] [Instill Furor](https://magiccards.info/query?q=!Instill+Furor)
- [x] [Island](https://magiccards.info/query?q=!Island)
- [x] [Ivy Dancer](https://magiccards.info/query?q=!Ivy+Dancer)
- [x] [Junktroller](https://magiccards.info/query?q=!Junktroller)
- [x] [Keening Banshee](https://magiccards.info/query?q=!Keening+Banshee)
- [x] [Last Gasp](https://magiccards.info/query?q=!Last+Gasp)
- [x] [Leashling](https://magiccards.info/query?q=!Leashling)
- [x] [Leave No Trace](https://magiccards.info/query?q=!Leave+No+Trace)
- [x] [Life from the Loam](https://magiccards.info/query?q=!Life+from+the+Loam)
- [x] [Light of Sanction](https://magiccards.info/query?q=!Light+of+Sanction)
- [x] [Lightning Helix](https://magiccards.info/query?q=!Lightning+Helix)
- [x] [Lore Broker](https://magiccards.info/query?q=!Lore+Broker)
- [x] [Loxodon Gatekeeper](https://magiccards.info/query?q=!Loxodon+Gatekeeper)
- [x] [Loxodon Hierarch](https://magiccards.info/query?q=!Loxodon+Hierarch)
- [x] [Lurking Informant](https://magiccards.info/query?q=!Lurking+Informant)
- [x] [Mark of Eviction](https://magiccards.info/query?q=!Mark+of+Eviction)
- [x] [Master Warcraft](https://magiccards.info/query?q=!Master+Warcraft)
- [x] [Mausoleum Turnkey](https://magiccards.info/query?q=!Mausoleum+Turnkey)
- [x] [Mindleech Mass](https://magiccards.info/query?q=!Mindleech+Mass)
- [x] [Mindmoil](https://magiccards.info/query?q=!Mindmoil)
- [x] [Mnemonic Nexus](https://magiccards.info/query?q=!Mnemonic+Nexus)
- [x] [Moldervine Cloak](https://magiccards.info/query?q=!Moldervine+Cloak)
- [x] [Molten Sentry](https://magiccards.info/query?q=!Molten+Sentry)
- [x] [Moonlight Bargain](https://magiccards.info/query?q=!Moonlight+Bargain)
- [x] [Moroii](https://magiccards.info/query?q=!Moroii)
- [x] [Mortipede](https://magiccards.info/query?q=!Mortipede)
- [x] [Mountain](https://magiccards.info/query?q=!Mountain)
- [x] [Muddle the Mixture](https://magiccards.info/query?q=!Muddle+the+Mixture)
- [x] [Necromantic Thirst](https://magiccards.info/query?q=!Necromantic+Thirst)
- [x] [Necroplasm](https://magiccards.info/query?q=!Necroplasm)
- [x] [Netherborn Phalanx](https://magiccards.info/query?q=!Netherborn+Phalanx)
- [x] [Nightguard Patrol](https://magiccards.info/query?q=!Nightguard+Patrol)
- [x] [Nightmare Void](https://magiccards.info/query?q=!Nightmare+Void)
- [x] [Nullmage Shepherd](https://magiccards.info/query?q=!Nullmage+Shepherd)
- [x] [Nullstone Gargoyle](https://magiccards.info/query?q=!Nullstone+Gargoyle)
- [x] [Oathsworn Giant](https://magiccards.info/query?q=!Oathsworn+Giant)
- [x] [Ordruun Commando](https://magiccards.info/query?q=!Ordruun+Commando)
- [x] [Overgrown Tomb](https://magiccards.info/query?q=!Overgrown+Tomb)
- [x] [Overwhelm](https://magiccards.info/query?q=!Overwhelm)
- [x] [Pariah's Shield](https://magiccards.info/query?q=!Pariah's+Shield)
- [x] [Peel from Reality](https://magiccards.info/query?q=!Peel+from+Reality)
- [x] [Peregrine Mask](https://magiccards.info/query?q=!Peregrine+Mask)
- [x] [Perilous Forays](https://magiccards.info/query?q=!Perilous+Forays)
- [x] [Perplex](https://magiccards.info/query?q=!Perplex)
- [x] [Phytohydra](https://magiccards.info/query?q=!Phytohydra)
- [x] [Plague Boiler](https://magiccards.info/query?q=!Plague+Boiler)
- [x] [Plains](https://magiccards.info/query?q=!Plains)
- [x] [Pollenbright Wings](https://magiccards.info/query?q=!Pollenbright+Wings)
- [x] [Primordial Sage](https://magiccards.info/query?q=!Primordial+Sage)
- [x] [Privileged Position](https://magiccards.info/query?q=!Privileged+Position)
- [x] [Psychic Drain](https://magiccards.info/query?q=!Psychic+Drain)
- [x] [Putrefy](https://magiccards.info/query?q=!Putrefy)
- [x] [Quickchange](https://magiccards.info/query?q=!Quickchange)
- [x] [Rain of Embers](https://magiccards.info/query?q=!Rain+of+Embers)
- [x] [Rally the Righteous](https://magiccards.info/query?q=!Rally+the+Righteous)
- [x] [Razia's Purification](https://magiccards.info/query?q=!Razia's+Purification)
- [x] [Razia, Boros Archangel](https://magiccards.info/query?q=!Razia,+Boros+Archangel)
- [x] [Recollect](https://magiccards.info/query?q=!Recollect)
- [x] [Remand](https://magiccards.info/query?q=!Remand)
- [x] [Reroute](https://magiccards.info/query?q=!Reroute)
- [x] [Ribbons of Night](https://magiccards.info/query?q=!Ribbons+of+Night)
- [x] [Rolling Spoil](https://magiccards.info/query?q=!Rolling+Spoil)
- [x] [Roofstalker Wight](https://magiccards.info/query?q=!Roofstalker+Wight)
- [x] [Root-Kin Ally](https://magiccards.info/query?q=!Root-Kin+Ally)
- [x] [Sabertooth Alley Cat](https://magiccards.info/query?q=!Sabertooth+Alley+Cat)
- [x] [Sacred Foundry](https://magiccards.info/query?q=!Sacred+Foundry)
- [x] [Sadistic Augermage](https://magiccards.info/query?q=!Sadistic+Augermage)
- [x] [Sandsower](https://magiccards.info/query?q=!Sandsower)
- [x] [Savra, Queen of the Golgari](https://magiccards.info/query?q=!Savra,+Queen+of+the+Golgari)
- [x] [Scatter the Seeds](https://magiccards.info/query?q=!Scatter+the+Seeds)
- [x] [Scion of the Wild](https://magiccards.info/query?q=!Scion+of+the+Wild)
- [x] [Screeching Griffin](https://magiccards.info/query?q=!Screeching+Griffin)
- [x] [Searing Meditation](https://magiccards.info/query?q=!Searing+Meditation)
- [x] [Seed Spark](https://magiccards.info/query?q=!Seed+Spark)
- [x] [Seeds of Strength](https://magiccards.info/query?q=!Seeds+of+Strength)
- [x] [Seismic Spike](https://magiccards.info/query?q=!Seismic+Spike)
- [x] [Selesnya Evangel](https://magiccards.info/query?q=!Selesnya+Evangel)
- [x] [Selesnya Guildmage](https://magiccards.info/query?q=!Selesnya+Guildmage)
- [x] [Selesnya Sagittars](https://magiccards.info/query?q=!Selesnya+Sagittars)
- [x] [Selesnya Sanctuary](https://magiccards.info/query?q=!Selesnya+Sanctuary)
- [x] [Selesnya Signet](https://magiccards.info/query?q=!Selesnya+Signet)
- [x] [Sell-Sword Brute](https://magiccards.info/query?q=!Sell-Sword+Brute)
- [x] [Sewerdreg](https://magiccards.info/query?q=!Sewerdreg)
- [x] [Shadow of Doubt](https://magiccards.info/query?q=!Shadow+of+Doubt)
- [x] [Shambling Shell](https://magiccards.info/query?q=!Shambling+Shell)
- [x] [Shred Memory](https://magiccards.info/query?q=!Shred+Memory)
- [x] [Siege Wurm](https://magiccards.info/query?q=!Siege+Wurm)
- [x] [Sins of the Past](https://magiccards.info/query?q=!Sins+of+the+Past)
- [x] [Sisters of Stone Death](https://magiccards.info/query?q=!Sisters+of+Stone+Death)
- [x] [Skyknight Legionnaire](https://magiccards.info/query?q=!Skyknight+Legionnaire)
- [x] [Smash](https://magiccards.info/query?q=!Smash)
- [x] [Snapping Drake](https://magiccards.info/query?q=!Snapping+Drake)
- [x] [Sparkmage Apprentice](https://magiccards.info/query?q=!Sparkmage+Apprentice)
- [x] [Spawnbroker](https://magiccards.info/query?q=!Spawnbroker)
- [x] [Spectral Searchlight](https://magiccards.info/query?q=!Spectral+Searchlight)
- [x] [Stasis Cell](https://magiccards.info/query?q=!Stasis+Cell)
- [x] [Stinkweed Imp](https://magiccards.info/query?q=!Stinkweed+Imp)
- [x] [Stone-Seeder Hierophant](https://magiccards.info/query?q=!Stone-Seeder+Hierophant)
- [x] [Stoneshaker Shaman](https://magiccards.info/query?q=!Stoneshaker+Shaman)
- [x] [Strands of Undeath](https://magiccards.info/query?q=!Strands+of+Undeath)
- [x] [Sundering Vitae](https://magiccards.info/query?q=!Sundering+Vitae)
- [x] [Sunforger](https://magiccards.info/query?q=!Sunforger)
- [x] [Sunhome Enforcer](https://magiccards.info/query?q=!Sunhome+Enforcer)
- [x] [Sunhome, Fortress of the Legion](https://magiccards.info/query?q=!Sunhome,+Fortress+of+the+Legion)
- [x] [Suppression Field](https://magiccards.info/query?q=!Suppression+Field)
- [x] [Surge of Zeal](https://magiccards.info/query?q=!Surge+of+Zeal)
- [x] [Surveilling Sprite](https://magiccards.info/query?q=!Surveilling+Sprite)
- [x] [Svogthos, the Restless Tomb](https://magiccards.info/query?q=!Svogthos,+the+Restless+Tomb)
- [x] [Swamp](https://magiccards.info/query?q=!Swamp)
- [x] [Szadek, Lord of Secrets](https://magiccards.info/query?q=!Szadek,+Lord+of+Secrets)
- [x] [Tattered Drake](https://magiccards.info/query?q=!Tattered+Drake)
- [x] [Telling Time](https://magiccards.info/query?q=!Telling+Time)
- [x] [Temple Garden](https://magiccards.info/query?q=!Temple+Garden)
- [x] [Terraformer](https://magiccards.info/query?q=!Terraformer)
- [x] [Terrarion](https://magiccards.info/query?q=!Terrarion)
- [x] [Thoughtpicker Witch](https://magiccards.info/query?q=!Thoughtpicker+Witch)
- [x] [Three Dreams](https://magiccards.info/query?q=!Three+Dreams)
- [x] [Thundersong Trumpeter](https://magiccards.info/query?q=!Thundersong+Trumpeter)
- [x] [Tidewater Minion](https://magiccards.info/query?q=!Tidewater+Minion)
- [x] [Tolsimir Wolfblood](https://magiccards.info/query?q=!Tolsimir+Wolfblood)
- [x] [Torpid Moloch](https://magiccards.info/query?q=!Torpid+Moloch)
- [x] [Transluminant](https://magiccards.info/query?q=!Transluminant)
- [x] [Trophy Hunter](https://magiccards.info/query?q=!Trophy+Hunter)
- [x] [Tunnel Vision](https://magiccards.info/query?q=!Tunnel+Vision)
- [x] [Twilight Drover](https://magiccards.info/query?q=!Twilight+Drover)
- [x] [Twisted Justice](https://magiccards.info/query?q=!Twisted+Justice)
- [x] [Undercity Shade](https://magiccards.info/query?q=!Undercity+Shade)
- [x] [Ursapine](https://magiccards.info/query?q=!Ursapine)
- [x] [Vedalken Dismisser](https://magiccards.info/query?q=!Vedalken+Dismisser)
- [x] [Vedalken Entrancer](https://magiccards.info/query?q=!Vedalken+Entrancer)
- [x] [Veteran Armorer](https://magiccards.info/query?q=!Veteran+Armorer)
- [x] [Viashino Fangtail](https://magiccards.info/query?q=!Viashino+Fangtail)
- [x] [Viashino Slasher](https://magiccards.info/query?q=!Viashino+Slasher)
- [x] [Vigor Mortis](https://magiccards.info/query?q=!Vigor+Mortis)
- [x] [Vindictive Mob](https://magiccards.info/query?q=!Vindictive+Mob)
- [x] [Vinelasher Kudzu](https://magiccards.info/query?q=!Vinelasher+Kudzu)
- [x] [Vitu-Ghazi, the City-Tree](https://magiccards.info/query?q=!Vitu-Ghazi,+the+City-Tree)
- [x] [Votary of the Conclave](https://magiccards.info/query?q=!Votary+of+the+Conclave)
- [x] [Voyager Staff](https://magiccards.info/query?q=!Voyager+Staff)
- [x] [Vulturous Zombie](https://magiccards.info/query?q=!Vulturous+Zombie)
- [x] [War-Torch Goblin](https://magiccards.info/query?q=!War-Torch+Goblin)
- [x] [Warp World](https://magiccards.info/query?q=!Warp+World)
- [x] [Watchwolf](https://magiccards.info/query?q=!Watchwolf)
- [x] [Watery Grave](https://magiccards.info/query?q=!Watery+Grave)
- [x] [Wizened Snitches](https://magiccards.info/query?q=!Wizened+Snitches)
- [x] [Woebringer Demon](https://magiccards.info/query?q=!Woebringer+Demon)
- [x] [Wojek Apothecary](https://magiccards.info/query?q=!Wojek+Apothecary)
- [x] [Wojek Embermage](https://magiccards.info/query?q=!Wojek+Embermage)
- [x] [Wojek Siren](https://magiccards.info/query?q=!Wojek+Siren)
- [x] [Woodwraith Corrupter](https://magiccards.info/query?q=!Woodwraith+Corrupter)
- [x] [Woodwraith Strangler](https://magiccards.info/query?q=!Woodwraith+Strangler)
- [x] [Zephyr Spirit](https://magiccards.info/query?q=!Zephyr+Spirit)
