### ISSUE TITLE
M19 - Core Set 2019 set card implementation tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4987]
Mark cards you're working on in the second post of this issue.
Once the card is committed, check off the card here to show that it's finished.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/core-2019)

# Unimplemented Cards

- [x] Not Done -- [Metamorphic Alteration](https://scryfall.com/search?q=Metamorphic+Alteration)

# Implemented Cards

- [x] Done -- [Abnormal Endurance](https://scryfall.com/search?q=Abnormal+Endurance)
- [x] Done -- [Act of Treason](https://scryfall.com/search?q=Act+of+Treason)
- [x] Done -- [Aegis of the Heavens](https://scryfall.com/search?q=Aegis+of+the+Heavens)
- [x] Done -- [Aerial Engineer](https://scryfall.com/search?q=Aerial+Engineer)
- [x] Done -- [Aether Tunnel](https://scryfall.com/search?q=Aether+Tunnel)
- [x] Done -- [Aethershield Artificer](https://scryfall.com/search?q=Aethershield+Artificer)
- [x] Done -- [Aggressive Mammoth](https://scryfall.com/search?q=Aggressive+Mammoth)
- [x] Done -- [Air Elemental](https://scryfall.com/search?q=Air+Elemental)
- [x] Done -- [Ajani's Influence](https://scryfall.com/search?q=Ajanis+Influence)
- [x] Done -- [Ajani's Last Stand](https://scryfall.com/search?q=Ajanis+Last+Stand)
- [x] Done -- [Ajani's Pridemate](https://scryfall.com/search?q=Ajanis+Pridemate)
- [x] Done -- [Ajani's Welcome](https://scryfall.com/search?q=Ajanis+Welcome)
- [x] Done -- [Ajani, Adversary of Tyrants](https://scryfall.com/search?q=Ajani,+Adversary+of+Tyrants)
- [x] Done -- [Ajani, Wise Counselor](https://scryfall.com/search?q=Ajani,+Wise+Counselor)
- [x] Done -- [Alpine Moon](https://scryfall.com/search?q=Alpine+Moon)
- [x] Done -- [Amulet of Safekeeping](https://scryfall.com/search?q=Amulet+of+Safekeeping)
- [x] Done -- [Angel of the Dawn](https://scryfall.com/search?q=Angel+of+the+Dawn)
- [x] Done -- [Anticipate](https://scryfall.com/search?q=Anticipate)
- [x] Done -- [Apex of Power](https://scryfall.com/search?q=Apex+of+Power)
- [x] Done -- [Arcades, the Strategist](https://scryfall.com/search?q=Arcades,+the+Strategist)
- [x] Done -- [Arcane Encyclopedia](https://scryfall.com/search?q=Arcane+Encyclopedia)
- [x] Done -- [Arisen Gorgon](https://scryfall.com/search?q=Arisen+Gorgon)
- [x] Done -- [Aven Wind Mage](https://scryfall.com/search?q=Aven+Wind+Mage)
- [x] Done -- [Aviation Pioneer](https://scryfall.com/search?q=Aviation+Pioneer)
- [x] Done -- [Banefire](https://scryfall.com/search?q=Banefire)
- [x] Done -- [Befuddle](https://scryfall.com/search?q=Befuddle)
- [x] Done -- [Blanchwood Armor](https://scryfall.com/search?q=Blanchwood+Armor)
- [x] Done -- [Blood Divination](https://scryfall.com/search?q=Blood+Divination)
- [x] Done -- [Boggart Brute](https://scryfall.com/search?q=Boggart+Brute)
- [x] Done -- [Bogstomper](https://scryfall.com/search?q=Bogstomper)
- [x] Done -- [Bone Dragon](https://scryfall.com/search?q=Bone+Dragon)
- [x] Done -- [Bone to Ash](https://scryfall.com/search?q=Bone+to+Ash)
- [x] Done -- [Brawl-Bash Ogre](https://scryfall.com/search?q=Brawl-Bash+Ogre)
- [x] Done -- [Bristling Boar](https://scryfall.com/search?q=Bristling+Boar)
- [x] Done -- [Cancel](https://scryfall.com/search?q=Cancel)
- [x] Done -- [Catalyst Elemental](https://scryfall.com/search?q=Catalyst+Elemental)
- [x] Done -- [Cavalry Drillmaster](https://scryfall.com/search?q=Cavalry+Drillmaster)
- [x] Done -- [Centaur Courser](https://scryfall.com/search?q=Centaur+Courser)
- [x] Done -- [Chaos Wand](https://scryfall.com/search?q=Chaos+Wand)
- [x] Done -- [Child of Night](https://scryfall.com/search?q=Child+of+Night)
- [x] Done -- [Chromium, the Mutable](https://scryfall.com/search?q=Chromium,+the+Mutable)
- [x] Done -- [Cinder Barrens](https://scryfall.com/search?q=Cinder+Barrens)
- [x] Done -- [Cleansing Nova](https://scryfall.com/search?q=Cleansing+Nova)
- [x] Done -- [Colossal Dreadmaw](https://scryfall.com/search?q=Colossal+Dreadmaw)
- [x] Done -- [Colossal Majesty](https://scryfall.com/search?q=Colossal+Majesty)
- [x] Done -- [Court Cleric](https://scryfall.com/search?q=Court+Cleric)
- [x] Done -- [Crash Through](https://scryfall.com/search?q=Crash+Through)
- [x] Done -- [Crucible of Worlds](https://scryfall.com/search?q=Crucible+of+Worlds)
- [x] Done -- [Daggerback Basilisk](https://scryfall.com/search?q=Daggerback+Basilisk)
- [x] Done -- [Dark-Dweller Oracle](https://scryfall.com/search?q=Dark-Dweller+Oracle)
- [x] Done -- [Daybreak Chaplain](https://scryfall.com/search?q=Daybreak+Chaplain)
- [x] Done -- [Death Baron](https://scryfall.com/search?q=Death+Baron)
- [x] Done -- [Declare Dominance](https://scryfall.com/search?q=Declare+Dominance)
- [x] Done -- [Demanding Dragon](https://scryfall.com/search?q=Demanding+Dragon)
- [x] Done -- [Demon of Catastrophes](https://scryfall.com/search?q=Demon+of+Catastrophes)
- [x] Done -- [Departed Deckhand](https://scryfall.com/search?q=Departed+Deckhand)
- [x] Done -- [Desecrated Tomb](https://scryfall.com/search?q=Desecrated+Tomb)
- [x] Done -- [Detection Tower](https://scryfall.com/search?q=Detection+Tower)
- [x] Done -- [Diamond Mare](https://scryfall.com/search?q=Diamond+Mare)
- [x] Done -- [Diregraf Ghoul](https://scryfall.com/search?q=Diregraf+Ghoul)
- [x] Done -- [Dismissive Pyromancer](https://scryfall.com/search?q=Dismissive+Pyromancer)
- [x] Done -- [Disperse](https://scryfall.com/search?q=Disperse)
- [x] Done -- [Divination](https://scryfall.com/search?q=Divination)
- [x] Done -- [Djinn of Wishes](https://scryfall.com/search?q=Djinn+of+Wishes)
- [x] Done -- [Doomed Dissenter](https://scryfall.com/search?q=Doomed+Dissenter)
- [x] Done -- [Doublecast](https://scryfall.com/search?q=Doublecast)
- [x] Done -- [Draconic Disciple](https://scryfall.com/search?q=Draconic+Disciple)
- [x] Done -- [Dragon Egg](https://scryfall.com/search?q=Dragon+Egg)
- [x] Done -- [Dragon's Hoard](https://scryfall.com/search?q=Dragons+Hoard)
- [x] Done -- [Druid of Horns](https://scryfall.com/search?q=Druid+of+Horns)
- [x] Done -- [Druid of the Cowl](https://scryfall.com/search?q=Druid+of+the+Cowl)
- [x] Done -- [Dryad Greenseeker](https://scryfall.com/search?q=Dryad+Greenseeker)
- [x] Done -- [Duress](https://scryfall.com/search?q=Duress)
- [x] Done -- [Dwarven Priest](https://scryfall.com/search?q=Dwarven+Priest)
- [x] Done -- [Dwindle](https://scryfall.com/search?q=Dwindle)
- [x] Done -- [Electrify](https://scryfall.com/search?q=Electrify)
- [x] Done -- [Elvish Clancaller](https://scryfall.com/search?q=Elvish+Clancaller)
- [x] Done -- [Elvish Rejuvenator](https://scryfall.com/search?q=Elvish+Rejuvenator)
- [x] Done -- [Enigma Drake](https://scryfall.com/search?q=Enigma+Drake)
- [x] Done -- [Epicure of Blood](https://scryfall.com/search?q=Epicure+of+Blood)
- [x] Done -- [Essence Scatter](https://scryfall.com/search?q=Essence+Scatter)
- [x] Done -- [Exclusion Mage](https://scryfall.com/search?q=Exclusion+Mage)
- [x] Done -- [Explosive Apparatus](https://scryfall.com/search?q=Explosive+Apparatus)
- [x] Done -- [Fell Specter](https://scryfall.com/search?q=Fell+Specter)
- [x] Done -- [Field Creeper](https://scryfall.com/search?q=Field+Creeper)
- [x] Done -- [Fiery Finish](https://scryfall.com/search?q=Fiery+Finish)
- [x] Done -- [Fire Elemental](https://scryfall.com/search?q=Fire+Elemental)
- [x] Done -- [Forsaken Sanctuary](https://scryfall.com/search?q=Forsaken+Sanctuary)
- [x] Done -- [Foul Orchard](https://scryfall.com/search?q=Foul+Orchard)
- [x] Done -- [Fountain of Renewal](https://scryfall.com/search?q=Fountain+of+Renewal)
- [x] Done -- [Fraying Omnipotence](https://scryfall.com/search?q=Fraying+Omnipotence)
- [x] Done -- [Frilled Sea Serpent](https://scryfall.com/search?q=Frilled+Sea+Serpent)
- [x] Done -- [Gallant Cavalry](https://scryfall.com/search?q=Gallant+Cavalry)
- [x] Done -- [Gargoyle Sentinel](https://scryfall.com/search?q=Gargoyle+Sentinel)
- [x] Done -- [Gearsmith Guardian](https://scryfall.com/search?q=Gearsmith+Guardian)
- [x] Done -- [Gearsmith Prodigy](https://scryfall.com/search?q=Gearsmith+Prodigy)
- [x] Done -- [Ghastbark Twins](https://scryfall.com/search?q=Ghastbark+Twins)
- [x] Done -- [Ghirapur Guide](https://scryfall.com/search?q=Ghirapur+Guide)
- [x] Done -- [Ghostform](https://scryfall.com/search?q=Ghostform)
- [x] Done -- [Giant Spider](https://scryfall.com/search?q=Giant+Spider)
- [x] Done -- [Gift of Paradise](https://scryfall.com/search?q=Gift+of+Paradise)
- [x] Done -- [Gigantosaurus](https://scryfall.com/search?q=Gigantosaurus)
- [x] Done -- [Goblin Instigator](https://scryfall.com/search?q=Goblin+Instigator)
- [x] Done -- [Goblin Motivator](https://scryfall.com/search?q=Goblin+Motivator)
- [x] Done -- [Goblin Trashmaster](https://scryfall.com/search?q=Goblin+Trashmaster)
- [x] Done -- [Goreclaw, Terror of Qal Sisma](https://scryfall.com/search?q=Goreclaw,+Terror+of+Qal+Sisma)
- [x] Done -- [Grasping Scoundrel](https://scryfall.com/search?q=Grasping+Scoundrel)
- [x] Done -- [Gravedigger](https://scryfall.com/search?q=Gravedigger)
- [x] Done -- [Gravewaker](https://scryfall.com/search?q=Gravewaker)
- [x] Done -- [Graveyard Marshal](https://scryfall.com/search?q=Graveyard+Marshal)
- [x] Done -- [Greenwood Sentinel](https://scryfall.com/search?q=Greenwood+Sentinel)
- [x] Done -- [Guttersnipe](https://scryfall.com/search?q=Guttersnipe)
- [x] Done -- [Havoc Devils](https://scryfall.com/search?q=Havoc+Devils)
- [x] Done -- [Herald of Faith](https://scryfall.com/search?q=Herald+of+Faith)
- [x] Done -- [Heroic Reinforcements](https://scryfall.com/search?q=Heroic+Reinforcements)
- [x] Done -- [Hieromancer's Cage](https://scryfall.com/search?q=Hieromancers+Cage)
- [x] Done -- [Highland Game](https://scryfall.com/search?q=Highland+Game)
- [x] Done -- [Highland Lake](https://scryfall.com/search?q=Highland+Lake)
- [x] Done -- [Hired Blade](https://scryfall.com/search?q=Hired+Blade)
- [x] Done -- [Horizon Scholar](https://scryfall.com/search?q=Horizon+Scholar)
- [x] Done -- [Hostile Minotaur](https://scryfall.com/search?q=Hostile+Minotaur)
- [x] Done -- [Hungering Hydra](https://scryfall.com/search?q=Hungering+Hydra)
- [x] Done -- [Infectious Horror](https://scryfall.com/search?q=Infectious+Horror)
- [x] Done -- [Infernal Reckoning](https://scryfall.com/search?q=Infernal+Reckoning)
- [x] Done -- [Infernal Scarring](https://scryfall.com/search?q=Infernal+Scarring)
- [x] Done -- [Inferno Hellion](https://scryfall.com/search?q=Inferno+Hellion)
- [x] Done -- [Inspired Charge](https://scryfall.com/search?q=Inspired+Charge)
- [x] Done -- [Invoke the Divine](https://scryfall.com/search?q=Invoke+the+Divine)
- [x] Done -- [Isareth the Awakener](https://scryfall.com/search?q=Isareth+the+Awakener)
- [x] Done -- [Isolate](https://scryfall.com/search?q=Isolate)
- [x] Done -- [Kargan Dragonrider](https://scryfall.com/search?q=Kargan+Dragonrider)
- [x] Done -- [Knight of the Tusk](https://scryfall.com/search?q=Knight+of+the+Tusk)
- [x] Done -- [Knight's Pledge](https://scryfall.com/search?q=Knights+Pledge)
- [x] Done -- [Knightly Valor](https://scryfall.com/search?q=Knightly+Valor)
- [x] Done -- [Lathliss, Dragon Queen](https://scryfall.com/search?q=Lathliss,+Dragon+Queen)
- [x] Done -- [Lava Axe](https://scryfall.com/search?q=Lava+Axe)
- [x] Done -- [Lena, Selfless Champion](https://scryfall.com/search?q=Lena,+Selfless+Champion)
- [x] Done -- [Leonin Vanguard](https://scryfall.com/search?q=Leonin+Vanguard)
- [x] Done -- [Leonin Warleader](https://scryfall.com/search?q=Leonin+Warleader)
- [x] Done -- [Lich's Caress](https://scryfall.com/search?q=Lichs+Caress)
- [x] Done -- [Lightning Mare](https://scryfall.com/search?q=Lightning+Mare)
- [x] Done -- [Lightning Strike](https://scryfall.com/search?q=Lightning+Strike)
- [x] Done -- [Liliana's Contract](https://scryfall.com/search?q=Lilianas+Contract)
- [x] Done -- [Liliana's Spoils](https://scryfall.com/search?q=Lilianas+Spoils)
- [x] Done -- [Liliana, Untouched by Death](https://scryfall.com/search?q=Liliana,+Untouched+by+Death)
- [x] Done -- [Liliana, the Necromancer](https://scryfall.com/search?q=Liliana,+the+Necromancer)
- [x] Done -- [Llanowar Elves](https://scryfall.com/search?q=Llanowar+Elves)
- [x] Done -- [Loxodon Line Breaker](https://scryfall.com/search?q=Loxodon+Line+Breaker)
- [x] Done -- [Luminous Bonds](https://scryfall.com/search?q=Luminous+Bonds)
- [x] Done -- [Macabre Waltz](https://scryfall.com/search?q=Macabre+Waltz)
- [x] Done -- [Magistrate's Scepter](https://scryfall.com/search?q=Magistrates+Scepter)
- [x] Done -- [Make a Stand](https://scryfall.com/search?q=Make+a+Stand)
- [x] Done -- [Manalith](https://scryfall.com/search?q=Manalith)
- [x] Done -- [Marauder's Axe](https://scryfall.com/search?q=Marauders+Axe)
- [x] Done -- [Meandering River](https://scryfall.com/search?q=Meandering+River)
- [x] Done -- [Mentor of the Meek](https://scryfall.com/search?q=Mentor+of+the+Meek)
- [x] Done -- [Meteor Golem](https://scryfall.com/search?q=Meteor+Golem)
- [x] Done -- [Mighty Leap](https://scryfall.com/search?q=Mighty+Leap)
- [x] Done -- [Militia Bugler](https://scryfall.com/search?q=Militia+Bugler)
- [x] Done -- [Millstone](https://scryfall.com/search?q=Millstone)
- [x] Done -- [Mind Rot](https://scryfall.com/search?q=Mind+Rot)
- [x] Done -- [Mirror Image](https://scryfall.com/search?q=Mirror+Image)
- [x] Done -- [Mist-Cloaked Herald](https://scryfall.com/search?q=Mist-Cloaked+Herald)
- [x] Done -- [Mistcaller](https://scryfall.com/search?q=Mistcaller)
- [x] Done -- [Murder](https://scryfall.com/search?q=Murder)
- [x] Done -- [Mystic Archaeologist](https://scryfall.com/search?q=Mystic+Archaeologist)
- [x] Done -- [Naturalize](https://scryfall.com/search?q=Naturalize)
- [x] Done -- [Nexus of Fate](https://scryfall.com/search?q=Nexus+of+Fate)
- [x] Done -- [Nicol Bolas, the Arisen](https://scryfall.com/search?q=Nicol+Bolas,+the+Arisen)
- [x] Done -- [Nicol Bolas, the Ravager](https://scryfall.com/search?q=Nicol+Bolas,+the+Ravager)
- [x] Done -- [Nightmare's Thirst](https://scryfall.com/search?q=Nightmares+Thirst)
- [x] Done -- [Novice Knight](https://scryfall.com/search?q=Novice+Knight)
- [x] Done -- [Oakenform](https://scryfall.com/search?q=Oakenform)
- [x] Done -- [Omenspeaker](https://scryfall.com/search?q=Omenspeaker)
- [x] Done -- [Omniscience](https://scryfall.com/search?q=Omniscience)
- [x] Done -- [Onakke Ogre](https://scryfall.com/search?q=Onakke+Ogre)
- [x] Done -- [One with the Machine](https://scryfall.com/search?q=One+with+the+Machine)
- [x] Done -- [Open the Graves](https://scryfall.com/search?q=Open+the+Graves)
- [x] Done -- [Oreskos Swiftclaw](https://scryfall.com/search?q=Oreskos+Swiftclaw)
- [x] Done -- [Palladia-Mors, the Ruiner](https://scryfall.com/search?q=Palladia-Mors,+the+Ruiner)
- [x] Done -- [Patient Rebuilding](https://scryfall.com/search?q=Patient+Rebuilding)
- [x] Done -- [Pegasus Courser](https://scryfall.com/search?q=Pegasus+Courser)
- [x] Done -- [Pelakka Wurm](https://scryfall.com/search?q=Pelakka+Wurm)
- [x] Done -- [Pendulum of Patterns](https://scryfall.com/search?q=Pendulum+of+Patterns)
- [x] Done -- [Phylactery Lich](https://scryfall.com/search?q=Phylactery+Lich)
- [x] Done -- [Plague Mare](https://scryfall.com/search?q=Plague+Mare)
- [x] Done -- [Plummet](https://scryfall.com/search?q=Plummet)
- [x] Done -- [Poison-Tip Archer](https://scryfall.com/search?q=Poison-Tip+Archer)
- [x] Done -- [Prodigious Growth](https://scryfall.com/search?q=Prodigious+Growth)
- [x] Done -- [Psychic Corrosion](https://scryfall.com/search?q=Psychic+Corrosion)
- [x] Done -- [Psychic Symbiont](https://scryfall.com/search?q=Psychic+Symbiont)
- [x] Done -- [Rabid Bite](https://scryfall.com/search?q=Rabid+Bite)
- [x] Done -- [Radiating Lightning](https://scryfall.com/search?q=Radiating+Lightning)
- [x] Done -- [Ravenous Harpy](https://scryfall.com/search?q=Ravenous+Harpy)
- [x] Done -- [Reassembling Skeleton](https://scryfall.com/search?q=Reassembling+Skeleton)
- [x] Done -- [Reclamation Sage](https://scryfall.com/search?q=Reclamation+Sage)
- [x] Done -- [Recollect](https://scryfall.com/search?q=Recollect)
- [x] Done -- [Regal Bloodlord](https://scryfall.com/search?q=Regal+Bloodlord)
- [x] Done -- [Reliquary Tower](https://scryfall.com/search?q=Reliquary+Tower)
- [x] Done -- [Remorseful Cleric](https://scryfall.com/search?q=Remorseful+Cleric)
- [x] Done -- [Resplendent Angel](https://scryfall.com/search?q=Resplendent+Angel)
- [x] Done -- [Revitalize](https://scryfall.com/search?q=Revitalize)
- [x] Done -- [Rhox Oracle](https://scryfall.com/search?q=Rhox+Oracle)
- [x] Done -- [Riddlemaster Sphinx](https://scryfall.com/search?q=Riddlemaster+Sphinx)
- [x] Done -- [Rise from the Grave](https://scryfall.com/search?q=Rise+from+the+Grave)
- [x] Done -- [Rogue's Gloves](https://scryfall.com/search?q=Rogues+Gloves)
- [x] Done -- [Root Snare](https://scryfall.com/search?q=Root+Snare)
- [x] Done -- [Runic Armasaur](https://scryfall.com/search?q=Runic+Armasaur)
- [x] Done -- [Rupture Spire](https://scryfall.com/search?q=Rupture+Spire)
- [x] Done -- [Rustwing Falcon](https://scryfall.com/search?q=Rustwing+Falcon)
- [x] Done -- [Sai, Master Thopterist](https://scryfall.com/search?q=Sai,+Master+Thopterist)
- [x] Done -- [Salvager of Secrets](https://scryfall.com/search?q=Salvager+of+Secrets)
- [x] Done -- [Sarkhan's Dragonfire](https://scryfall.com/search?q=Sarkhans+Dragonfire)
- [x] Done -- [Sarkhan's Unsealing](https://scryfall.com/search?q=Sarkhans+Unsealing)
- [x] Done -- [Sarkhan's Whelp](https://scryfall.com/search?q=Sarkhans+Whelp)
- [x] Done -- [Sarkhan, Dragonsoul](https://scryfall.com/search?q=Sarkhan,+Dragonsoul)
- [x] Done -- [Sarkhan, Fireblood](https://scryfall.com/search?q=Sarkhan,+Fireblood)
- [x] Done -- [Satyr Enchanter](https://scryfall.com/search?q=Satyr+Enchanter)
- [x] Done -- [Scapeshift](https://scryfall.com/search?q=Scapeshift)
- [x] Done -- [Scholar of Stars](https://scryfall.com/search?q=Scholar+of+Stars)
- [x] Done -- [Serra's Guardian](https://scryfall.com/search?q=Serras+Guardian)
- [x] Done -- [Shield Mare](https://scryfall.com/search?q=Shield+Mare)
- [x] Done -- [Shivan Dragon](https://scryfall.com/search?q=Shivan+Dragon)
- [x] Done -- [Shock](https://scryfall.com/search?q=Shock)
- [x] Done -- [Siegebreaker Giant](https://scryfall.com/search?q=Siegebreaker+Giant)
- [x] Done -- [Sift](https://scryfall.com/search?q=Sift)
- [x] Done -- [Sigiled Sword of Valeron](https://scryfall.com/search?q=Sigiled+Sword+of+Valeron)
- [x] Done -- [Silverbeak Griffin](https://scryfall.com/search?q=Silverbeak+Griffin)
- [x] Done -- [Skalla Wolf](https://scryfall.com/search?q=Skalla+Wolf)
- [x] Done -- [Skeleton Archer](https://scryfall.com/search?q=Skeleton+Archer)
- [x] Done -- [Skilled Animator](https://scryfall.com/search?q=Skilled+Animator)
- [x] Done -- [Skymarch Bloodletter](https://scryfall.com/search?q=Skymarch+Bloodletter)
- [x] Done -- [Skyrider Patrol](https://scryfall.com/search?q=Skyrider+Patrol)
- [x] Done -- [Skyscanner](https://scryfall.com/search?q=Skyscanner)
- [x] Done -- [Sleep](https://scryfall.com/search?q=Sleep)
- [x] Done -- [Smelt](https://scryfall.com/search?q=Smelt)
- [x] Done -- [Snapping Drake](https://scryfall.com/search?q=Snapping+Drake)
- [x] Done -- [Sovereign's Bite](https://scryfall.com/search?q=Sovereigns+Bite)
- [x] Done -- [Sparktongue Dragon](https://scryfall.com/search?q=Sparktongue+Dragon)
- [x] Done -- [Spit Flame](https://scryfall.com/search?q=Spit+Flame)
- [x] Done -- [Star-Crowned Stag](https://scryfall.com/search?q=Star-Crowned+Stag)
- [x] Done -- [Stitcher's Supplier](https://scryfall.com/search?q=Stitchers+Supplier)
- [x] Done -- [Stone Quarry](https://scryfall.com/search?q=Stone+Quarry)
- [x] Done -- [Strangling Spores](https://scryfall.com/search?q=Strangling+Spores)
- [x] Done -- [Submerged Boneyard](https://scryfall.com/search?q=Submerged+Boneyard)
- [x] Done -- [Sun Sentinel](https://scryfall.com/search?q=Sun+Sentinel)
- [x] Done -- [Suncleanser](https://scryfall.com/search?q=Suncleanser)
- [x] Done -- [Supreme Phantom](https://scryfall.com/search?q=Supreme+Phantom)
- [x] Done -- [Sure Strike](https://scryfall.com/search?q=Sure+Strike)
- [x] Done -- [Surge Mare](https://scryfall.com/search?q=Surge+Mare)
- [x] Done -- [Suspicious Bookcase](https://scryfall.com/search?q=Suspicious+Bookcase)
- [x] Done -- [Switcheroo](https://scryfall.com/search?q=Switcheroo)
- [x] Done -- [Take Vengeance](https://scryfall.com/search?q=Take+Vengeance)
- [x] Done -- [Talons of Wildwood](https://scryfall.com/search?q=Talons+of+Wildwood)
- [x] Done -- [Tattered Mummy](https://scryfall.com/search?q=Tattered+Mummy)
- [x] Done -- [Tectonic Rift](https://scryfall.com/search?q=Tectonic+Rift)
- [x] Done -- [Tezzeret's Gatebreaker](https://scryfall.com/search?q=Tezzerets+Gatebreaker)
- [x] Done -- [Tezzeret's Strider](https://scryfall.com/search?q=Tezzerets+Strider)
- [x] Done -- [Tezzeret, Artifice Master](https://scryfall.com/search?q=Tezzeret,+Artifice+Master)
- [x] Done -- [Tezzeret, Cruel Machinist](https://scryfall.com/search?q=Tezzeret,+Cruel+Machinist)
- [x] Done -- [Thorn Lieutenant](https://scryfall.com/search?q=Thorn+Lieutenant)
- [x] Done -- [Thornhide Wolves](https://scryfall.com/search?q=Thornhide+Wolves)
- [x] Done -- [Thud](https://scryfall.com/search?q=Thud)
- [x] Done -- [Timber Gorge](https://scryfall.com/search?q=Timber+Gorge)
- [x] Done -- [Titanic Growth](https://scryfall.com/search?q=Titanic+Growth)
- [x] Done -- [Tolarian Scholar](https://scryfall.com/search?q=Tolarian+Scholar)
- [x] Done -- [Tormenting Voice](https://scryfall.com/search?q=Tormenting+Voice)
- [x] Done -- [Totally Lost](https://scryfall.com/search?q=Totally+Lost)
- [x] Done -- [Tranquil Expanse](https://scryfall.com/search?q=Tranquil+Expanse)
- [x] Done -- [Transmogrifying Wand](https://scryfall.com/search?q=Transmogrifying+Wand)
- [x] Done -- [Trumpet Blast](https://scryfall.com/search?q=Trumpet+Blast)
- [x] Done -- [Trusty Packbeast](https://scryfall.com/search?q=Trusty+Packbeast)
- [x] Done -- [Two-Headed Zombie](https://scryfall.com/search?q=Two-Headed+Zombie)
- [x] Done -- [Uncomfortable Chill](https://scryfall.com/search?q=Uncomfortable+Chill)
- [x] Done -- [Ursine Champion](https://scryfall.com/search?q=Ursine+Champion)
- [x] Done -- [Vaevictis Asmadi, the Dire](https://scryfall.com/search?q=Vaevictis+Asmadi,+the+Dire)
- [x] Done -- [Valiant Knight](https://scryfall.com/search?q=Valiant+Knight)
- [x] Done -- [Vampire Neonate](https://scryfall.com/search?q=Vampire+Neonate)
- [x] Done -- [Vampire Sovereign](https://scryfall.com/search?q=Vampire+Sovereign)
- [x] Done -- [Viashino Pyromancer](https://scryfall.com/search?q=Viashino+Pyromancer)
- [x] Done -- [Vigilant Baloth](https://scryfall.com/search?q=Vigilant+Baloth)
- [x] Done -- [Vine Mare](https://scryfall.com/search?q=Vine+Mare)
- [x] Done -- [Vivien Reid](https://scryfall.com/search?q=Vivien+Reid)
- [x] Done -- [Vivien of the Arkbow](https://scryfall.com/search?q=Vivien+of+the+Arkbow)
- [x] Done -- [Vivien's Invocation](https://scryfall.com/search?q=Viviens+Invocation)
- [x] Done -- [Vivien's Jaguar](https://scryfall.com/search?q=Viviens+Jaguar)
- [x] Done -- [Volcanic Dragon](https://scryfall.com/search?q=Volcanic+Dragon)
- [x] Done -- [Volley Veteran](https://scryfall.com/search?q=Volley+Veteran)
- [x] Done -- [Walking Corpse](https://scryfall.com/search?q=Walking+Corpse)
- [x] Done -- [Wall of Mist](https://scryfall.com/search?q=Wall+of+Mist)
- [x] Done -- [Wall of Vines](https://scryfall.com/search?q=Wall+of+Vines)
- [x] Done -- [Waterknot](https://scryfall.com/search?q=Waterknot)
- [x] Done -- [Windreader Sphinx](https://scryfall.com/search?q=Windreader+Sphinx)
- [x] Done -- [Woodland Stream](https://scryfall.com/search?q=Woodland+Stream)

**Comment by theelk801** [comment]
- [ ] In progress -- [Catalyst Elemental](https://scryfall.com/search?q=Catalyst+Elemental)
- [ ] In progress -- [Daybreak Chaplain](https://scryfall.com/search?q=Daybreak+Chaplain)
- [ ] In progress -- [Dwarven Priest](https://scryfall.com/search?q=Dwarven+Priest)
- [ ] In progress -- [Dwindle](https://scryfall.com/search?q=Dwindle)
- [ ] In progress -- [Frilled Sea Serpent](https://scryfall.com/search?q=Frilled+Sea+Serpent)
- [ ] In progress -- [Gearsmith Prodigy](https://scryfall.com/search?q=Gearsmith+Prodigy)
- [ ] In progress -- [Goblin Instigator](https://scryfall.com/search?q=Goblin+Instigator)
- [ ] In progress -- [Goblin Motivator](https://scryfall.com/search?q=Goblin+Motivator)
- [ ] In progress -- [Hostile Minotaur](https://scryfall.com/search?q=Hostile+Minotaur)
- [ ] In progress -- [Knight of the Tusk](https://scryfall.com/search?q=Knight+of+the+Tusk)
- [ ] In progress -- [Knight's Pledge](https://scryfall.com/search?q=Knights+Pledge)
- [ ] In progress -- [Loxodon Line Breaker](https://scryfall.com/search?q=Loxodon+Line+Breaker)
- [ ] In progress -- [Onakke Ogre](https://scryfall.com/search?q=Onakke+Ogre)
- [ ] In progress -- [Revitalize](https://scryfall.com/search?q=Revitalize)
- [ ] In progress -- [Rustwing Falcon](https://scryfall.com/search?q=Rustwing+Falcon)
- [ ] In progress -- [Scholar of Stars](https://scryfall.com/search?q=Scholar+of+Stars)
- [ ] In progress -- [Trusty Packbeast](https://scryfall.com/search?q=Trusty+Packbeast)
- [ ] In progress -- [Uncomfortable Chill](https://scryfall.com/search?q=Uncomfortable+Chill)

**Comment by theelk801** [comment]
Sparktongue Dragon and Vivien's Invocation both feature reflexive triggers like Heart-Piercer Manticore. I'm gonna implement some sort of framework for those as they seem like they're sticking around.

**Comment by theelk801** [comment]
Alright, I'm tapping out on Metamorphic Alteration.
