### ISSUE TITLE
GS1 -  Global Series: Jiang Yanggu & Mu Yanling set card implementation tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#5016]
Mark cards you are working on in the second post of this issue.
If the card is committed, mark the checkbox of the card here to signal that it's finished.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/Global-Series-Jiang-Yanggu-and-Mu-Yanling)

# Implemented Cards

- [x] Done -- [Aggressive Instinct](https://scryfall.com/search?q=Aggressive+Instinct)
- [x] Done -- [Ancestor Dragon](https://scryfall.com/search?q=Ancestor+Dragon)
- [x] Done -- [Armored Whirl Turtle](https://scryfall.com/search?q=Armored+Whirl+Turtle)
- [x] Done -- [Breath of Fire](https://scryfall.com/search?q=Breath+of+Fire)
- [x] Done -- [Brilliant Plan](https://scryfall.com/search?q=Brilliant+Plan)
- [x] Done -- [Cleansing Screech](https://scryfall.com/search?q=Cleansing+Screech)
- [x] Done -- [Cloak of Mists](https://scryfall.com/search?q=Cloak+of+Mists)
- [x] Done -- [Colorful Feiyi Sparrow](https://scryfall.com/search?q=Colorful+Feiyi+Sparrow)
- [x] Done -- [Confidence from Strength](https://scryfall.com/search?q=Confidence+from+Strength)
- [x] Done -- [Dragon's Presence](https://scryfall.com/search?q=Dragons+Presence)
- [x] Done -- [Drown in Shapelessness](https://scryfall.com/search?q=Drown+in+Shapelessness)
- [x] Done -- [Earth-Origin Yak](https://scryfall.com/search?q=Earth-Origin+Yak)
- [x] Done -- [Earthshaking Si](https://scryfall.com/search?q=Earthshaking+Si)
- [x] Done -- [Feiyi Snake](https://scryfall.com/search?q=Feiyi+Snake)
- [x] Done -- [Ferocious Zheng](https://scryfall.com/search?q=Ferocious+Zheng)
- [x] Done -- [Fire-Omen Crane](https://scryfall.com/search?q=Fire-Omen+Crane)
- [x] Done -- [Giant Spider](https://scryfall.com/search?q=Giant+Spider)
- [x] Done -- [Hardened-Scale Armor](https://scryfall.com/search?q=Hardened-Scale+Armor)
- [x] Done -- [Heavenly Qilin](https://scryfall.com/search?q=Heavenly+Qilin)
- [x] Done -- [Jiang Yanggu](https://scryfall.com/search?q=Jiang+Yanggu)
- [x] Done -- [Journey for the Elixir](https://scryfall.com/search?q=Journey+for+the+Elixir)
- [x] Done -- [Leopard-Spotted Jiao](https://scryfall.com/search?q=Leopard-Spotted+Jiao)
- [x] Done -- [Meandering River](https://scryfall.com/search?q=Meandering+River)
- [x] Done -- [Moon-Eating Dog](https://scryfall.com/search?q=Moon-Eating+Dog)
- [x] Done -- [Mu Yanling](https://scryfall.com/search?q=Mu+Yanling)
- [x] Done -- [Nine-Tail White Fox](https://scryfall.com/search?q=Nine-Tail+White+Fox)
- [x] Done -- [Purple-Crystal Crab](https://scryfall.com/search?q=Purple-Crystal+Crab)
- [x] Done -- [Qilin's Blessing](https://scryfall.com/search?q=Qilins+Blessing)
- [x] Done -- [Reckless Pangolin](https://scryfall.com/search?q=Reckless+Pangolin)
- [x] Done -- [Rhythmic Water Vortex](https://scryfall.com/search?q=Rhythmic+Water+Vortex)
- [x] Done -- [Sacred White Deer](https://scryfall.com/search?q=Sacred+White+Deer)
- [x] Done -- [Screeching Phoenix](https://scryfall.com/search?q=Screeching+Phoenix)
- [x] Done -- [Stormcloud Spirit](https://scryfall.com/search?q=Stormcloud+Spirit)
- [x] Done -- [Timber Gorge](https://scryfall.com/search?q=Timber+Gorge)
- [x] Done -- [Vivid Flying Fish](https://scryfall.com/search?q=Vivid+Flying+Fish)
- [x] Done -- [Welkin Tern](https://scryfall.com/search?q=Welkin+Tern)

**Comment by theelk801** [comment]
- [ ] In progress -- [Aggressive Instinct](https://scryfall.com/search?q=Aggressive+Instinct)
- [ ] In progress -- [Ancestor Dragon](https://scryfall.com/search?q=Ancestor+Dragon)
- [ ] In progress -- [Armored Whirl Turtle](https://scryfall.com/search?q=Armored+Whirl+Turtle)
- [ ] In progress -- [Breath of Fire](https://scryfall.com/search?q=Breath+of+Fire)
- [ ] In progress -- [Cleansing Screech](https://scryfall.com/search?q=Cleansing+Screech)
- [ ] In progress -- [Colorful Feiyi Sparrow](https://scryfall.com/search?q=Colorful+Feiyi+Sparrow)
- [ ] In progress -- [Confidence from Strength](https://scryfall.com/search?q=Confidence+from+Strength)
- [ ] In progress -- [Dragon's Presence](https://scryfall.com/search?q=Dragons+Presence)
- [ ] In progress -- [Drown in Shapelessness](https://scryfall.com/search?q=Drown+in+Shapelessness)
- [ ] In progress -- [Earth-Origin Yak](https://scryfall.com/search?q=Earth-Origin+Yak)
- [ ] In progress -- [Earthshaking Si](https://scryfall.com/search?q=Earthshaking+Si)
- [ ] In progress -- [Feiyi Snake](https://scryfall.com/search?q=Feiyi+Snake)
- [ ] In progress -- [Ferocious Zheng](https://scryfall.com/search?q=Ferocious+Zheng)
- [ ] In progress -- [Fire-Omen Crane](https://scryfall.com/search?q=Fire-Omen+Crane)
- [ ] In progress -- [Hardened-Scale Armor](https://scryfall.com/search?q=Hardened-Scale+Armor)
- [ ] In progress -- [Heavenly Qilin](https://scryfall.com/search?q=Heavenly+Qilin)
- [ ] In progress -- [Journey for the Elixir](https://scryfall.com/search?q=Journey+for+the+Elixir)
- [ ] In progress -- [Leopard-Spotted Jiao](https://scryfall.com/search?q=Leopard-Spotted+Jiao)
- [ ] In progress -- [Moon-Eating Dog](https://scryfall.com/search?q=Moon-Eating+Dog)
- [ ] In progress -- [Nine-Tail White Fox](https://scryfall.com/search?q=Nine-Tail+White+Fox)
- [ ] In progress -- [Purple-Crystal Crab](https://scryfall.com/search?q=Purple-Crystal+Crab)
- [ ] In progress -- [Qilin's Blessing](https://scryfall.com/search?q=Qilins+Blessing)
- [ ] In progress -- [Reckless Pangolin](https://scryfall.com/search?q=Reckless+Pangolin)
- [ ] In progress -- [Rhythmic Water Vortex](https://scryfall.com/search?q=Rhythmic+Water+Vortex)
- [ ] In progress -- [Sacred White Deer](https://scryfall.com/search?q=Sacred+White+Deer)
- [ ] In progress -- [Screeching Phoenix](https://scryfall.com/search?q=Screeching+Phoenix)
- [ ] In progress -- [Stormcloud Spirit](https://scryfall.com/search?q=Stormcloud+Spirit)
- [ ] In progress -- [Vivid Flying Fish](https://scryfall.com/search?q=Vivid+Flying+Fish)

**Comment by theelk801** [comment]
Done.
