### ISSUE TITLE
Need a 'Paste List of URLs' type image source

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#5029]
I see this operating similarly to how grabbag currently operates (a list of cards and the corresponding image's URL), but allow the user to download an image for a card from a pasted list.

So you would get the list of images for say harder to get images such as the JR, MGDC or PTC images and then paste into a text box something similar to the follwing:
```
"MGDC/Priest of Urabrask", "https://img.scryfall.com/cards/large/en/pnph/90.jpg"
"MGDC/Pristine Talisman", "https://img.scryfall.com/cards/large/en/pnph/151.jpg"
"MGDC/Reya Dawnbringer", "https://img.scryfall.com/cards/large/en/p10e/35.jpg"
"MGDC/Scaleguard Sentinels", "https://img.scryfall.com/cards/large/en/pdtk/201.jpg"
"MGDC/Squelching Leeches", "https://img.scryfall.com/cards/large/en/pjou/84.jpg"
"MGDC/Stasis Snare", "https://img.scryfall.com/cards/large/en/pbfz/50.jpg"
"PTC/Azor's Gateway", "https://img.scryfall.com/cards/large/en/prix/176sa.jpg"
"PTC/Final Iteration", "https://img.scryfall.com/cards/large/en/pemn/56sb.jpg"
"PTC/Driven", "https://img.scryfall.com/cards/large/en/phou/157sa.jpg"
"PTC/Despair", "https://img.scryfall.com/cards/large/en/phou/157sb.jpg"
"PTC/Dusk", "https://img.scryfall.com/cards/large/en/pakh/210sa.jpg"
```

It would also be nice to give an option to say 'these images are missing' so the user can get the left column of information of the equation at least.

TODO:
 - [ ] add manual download page with pasted links;
 - [ ] add instruction and links to wiki pages with pre-constructed list to download for manual mode;
 - [ ] add generate missing images button to create links list of missing images;
 - [ ] add force to re-download checkbox to re-download existing images from another sources;

**Comment by JayDi85** [comment]
It's a good idea and very useful. I can modify download dialog to add new manual mode with hints and links to wiki with pre-constructed lists. Also will add "force mode" to re-download existing images from new sources.

**Comment by spjspj** [comment]
Hey @JayDi85 - are you working on this?  I was going to give it a go if you weren't.

**Comment by JayDi85** [comment]
@spjspj yep, will release it on next week.

**Comment by JayDi85** [comment]
@spjspj yep, will release it on next week.

**Comment by spjspj** [comment]
@JayDi85 I was kind of working on this ( #5068) - change it if you like!
