### ISSUE TITLE
HML - Homelands set card implementation tracking

### ISSUE THREAD

**Issue by ryegleason** [magefree/mage#5057]
# Unimplemented:
- [ ] [Timmerian Fiends](https://magiccards.info/query?q=!Timmerian+Fiends) (Ante card)

# Implemented:
- [x] [Abbey Gargoyles](https://magiccards.info/query?q=!Abbey+Gargoyles)
- [x] [Abbey Matron](https://magiccards.info/query?q=!Abbey+Matron)
- [x] [Aether Storm](https://magiccards.info/query?q=!Aether+Storm)
- [x] [Aliban's Tower](https://magiccards.info/query?q=!Aliban's+Tower)
- [x] [Ambush](https://magiccards.info/query?q=!Ambush)
- [x] [Ambush Party](https://magiccards.info/query?q=!Ambush+Party)
- [x] [An-Havva Constable](https://magiccards.info/query?q=!An-Havva+Constable)
- [x] [An-Havva Inn](https://magiccards.info/query?q=!An-Havva+Inn)
- [x] [An-Havva Township](https://magiccards.info/query?q=!An-Havva+Township)
- [x] [An-Zerrin Ruins](https://magiccards.info/query?q=!An-Zerrin+Ruins)
- [x] [Anaba Ancestor](https://magiccards.info/query?q=!Anaba+Ancestor)
- [x] [Anaba Bodyguard](https://magiccards.info/query?q=!Anaba+Bodyguard)
- [x] [Anaba Shaman](https://magiccards.info/query?q=!Anaba+Shaman)
- [x] [Anaba Spirit Crafter](https://magiccards.info/query?q=!Anaba+Spirit+Crafter)
- [x] [Apocalypse Chime](https://magiccards.info/query?q=!Apocalypse+Chime)
- [x] [Autumn Willow](https://magiccards.info/query?q=!Autumn+Willow)
- [x] [Aysen Abbey](https://magiccards.info/query?q=!Aysen+Abbey)
- [x] [Aysen Bureaucrats](https://magiccards.info/query?q=!Aysen+Bureaucrats)
- [x] [Aysen Crusader](https://magiccards.info/query?q=!Aysen+Crusader)
- [x] [Aysen Highway](https://magiccards.info/query?q=!Aysen+Highway)
- [x] [Baki's Curse](https://magiccards.info/query?q=!Baki's+Curse)
- [x] [Baron Sengir](https://magiccards.info/query?q=!Baron+Sengir)
- [x] [Beast Walkers](https://magiccards.info/query?q=!Beast+Walkers)
- [x] [Black Carriage](https://magiccards.info/query?q=!Black+Carriage)
- [x] [Broken Visage](https://magiccards.info/query?q=!Broken+Visage)
- [x] [Carapace](https://magiccards.info/query?q=!Carapace)
- [x] [Castle Sengir](https://magiccards.info/query?q=!Castle+Sengir)
- [x] [Cemetery Gate](https://magiccards.info/query?q=!Cemetery+Gate)
- [x] [Chain Stasis](https://magiccards.info/query?q=!Chain+Stasis)
- [x] [Chandler](https://magiccards.info/query?q=!Chandler)
- [x] [Clockwork Gnomes](https://magiccards.info/query?q=!Clockwork+Gnomes)
- [x] [Clockwork Steed](https://magiccards.info/query?q=!Clockwork+Steed)
- [x] [Clockwork Swarm](https://magiccards.info/query?q=!Clockwork+Swarm)
- [x] [Coral Reef](https://magiccards.info/query?q=!Coral+Reef)
- [x] [Dark Maze](https://magiccards.info/query?q=!Dark+Maze)
- [x] [Daughter of Autumn](https://magiccards.info/query?q=!Daughter+of+Autumn)
- [x] [Death Speakers](https://magiccards.info/query?q=!Death+Speakers)
- [x] [Didgeridoo](https://magiccards.info/query?q=!Didgeridoo)
- [x] [Drudge Spell](https://magiccards.info/query?q=!Drudge+Spell)
- [x] [Dry Spell](https://magiccards.info/query?q=!Dry+Spell)
- [x] [Dwarven Pony](https://magiccards.info/query?q=!Dwarven+Pony)
- [x] [Dwarven Sea Clan](https://magiccards.info/query?q=!Dwarven+Sea+Clan)
- [x] [Dwarven Trader](https://magiccards.info/query?q=!Dwarven+Trader)
- [x] [Ebony Rhino](https://magiccards.info/query?q=!Ebony+Rhino)
- [x] [Eron the Relentless](https://magiccards.info/query?q=!Eron+the+Relentless)
- [x] [Evaporate](https://magiccards.info/query?q=!Evaporate)
- [x] [Faerie Noble](https://magiccards.info/query?q=!Faerie+Noble)
- [x] [Feast of the Unicorn](https://magiccards.info/query?q=!Feast+of+the+Unicorn)
- [x] [Feroz's Ban](https://magiccards.info/query?q=!Feroz's+Ban)
- [x] [Folk of An-Havva](https://magiccards.info/query?q=!Folk+of+An-Havva)
- [x] [Forget](https://magiccards.info/query?q=!Forget)
- [x] [Funeral March](https://magiccards.info/query?q=!Funeral+March)
- [x] [Ghost Hounds](https://magiccards.info/query?q=!Ghost+Hounds)
- [x] [Giant Albatross](https://magiccards.info/query?q=!Giant+Albatross)
- [x] [Giant Oyster](https://magiccards.info/query?q=!Giant+Oyster)
- [x] [Grandmother Sengir](https://magiccards.info/query?q=!Grandmother+Sengir)
- [x] [Greater Werewolf](https://magiccards.info/query?q=!Greater+Werewolf)
- [x] [Hazduhr the Abbot](https://magiccards.info/query?q=!Hazduhr+the+Abbot)
- [x] [Headstone](https://magiccards.info/query?q=!Headstone)
- [x] [Heart Wolf](https://magiccards.info/query?q=!Heart+Wolf)
- [x] [Hungry Mist](https://magiccards.info/query?q=!Hungry+Mist)
- [x] [Ihsan's Shade](https://magiccards.info/query?q=!Ihsan's+Shade)
- [x] [Irini Sengir](https://magiccards.info/query?q=!Irini+Sengir)
- [x] [Ironclaw Curse](https://magiccards.info/query?q=!Ironclaw+Curse)
- [x] [Jinx](https://magiccards.info/query?q=!Jinx)
- [x] [Joven](https://magiccards.info/query?q=!Joven)
- [x] [Joven's Ferrets](https://magiccards.info/query?q=!Joven's+Ferrets)
- [x] [Joven's Tools](https://magiccards.info/query?q=!Joven's+Tools)
- [x] [Koskun Falls](https://magiccards.info/query?q=!Koskun+Falls)
- [x] [Koskun Keep](https://magiccards.info/query?q=!Koskun+Keep)
- [x] [Labyrinth Minotaur](https://magiccards.info/query?q=!Labyrinth+Minotaur)
- [x] [Leaping Lizard](https://magiccards.info/query?q=!Leaping+Lizard)
- [x] [Leeches](https://magiccards.info/query?q=!Leeches)
- [x] [Mammoth Harness](https://magiccards.info/query?q=!Mammoth+Harness)
- [x] [Marjhan](https://magiccards.info/query?q=!Marjhan)
- [x] [Memory Lapse](https://magiccards.info/query?q=!Memory+Lapse)
- [x] [Merchant Scroll](https://magiccards.info/query?q=!Merchant+Scroll)
- [x] [Mesa Falcon](https://magiccards.info/query?q=!Mesa+Falcon)
- [x] [Mystic Decree](https://magiccards.info/query?q=!Mystic+Decree)
- [x] [Narwhal](https://magiccards.info/query?q=!Narwhal)
- [x] [Orcish Mine](https://magiccards.info/query?q=!Orcish+Mine)
- [x] [Primal Order](https://magiccards.info/query?q=!Primal+Order)
- [x] [Prophecy](https://magiccards.info/query?q=!Prophecy)
- [x] [Rashka the Slayer](https://magiccards.info/query?q=!Rashka+the+Slayer)
- [x] [Reef Pirates](https://magiccards.info/query?q=!Reef+Pirates)
- [x] [Renewal](https://magiccards.info/query?q=!Renewal)
- [x] [Retribution](https://magiccards.info/query?q=!Retribution)
- [x] [Reveka, Wizard Savant](https://magiccards.info/query?q=!Reveka,+Wizard+Savant)
- [x] [Root Spider](https://magiccards.info/query?q=!Root+Spider)
- [x] [Roots](https://magiccards.info/query?q=!Roots)
- [x] [Roterothopter](https://magiccards.info/query?q=!Roterothopter)
- [x] [Rysorian Badger](https://magiccards.info/query?q=!Rysorian+Badger)
- [x] [Samite Alchemist](https://magiccards.info/query?q=!Samite+Alchemist)
- [x] [Sea Sprite](https://magiccards.info/query?q=!Sea+Sprite)
- [x] [Sea Troll](https://magiccards.info/query?q=!Sea+Troll)
- [x] [Sengir Autocrat](https://magiccards.info/query?q=!Sengir+Autocrat)
- [x] [Sengir Bats](https://magiccards.info/query?q=!Sengir+Bats)
- [x] [Serra Aviary](https://magiccards.info/query?q=!Serra+Aviary)
- [x] [Serra Bestiary](https://magiccards.info/query?q=!Serra+Bestiary)
- [x] [Serra Inquisitors](https://magiccards.info/query?q=!Serra+Inquisitors)
- [x] [Serra Paladin](https://magiccards.info/query?q=!Serra+Paladin)
- [x] [Serrated Arrows](https://magiccards.info/query?q=!Serrated+Arrows)
- [x] [Shrink](https://magiccards.info/query?q=!Shrink)
- [x] [Soraya the Falconer](https://magiccards.info/query?q=!Soraya+the+Falconer)
- [x] [Spectral Bears](https://magiccards.info/query?q=!Spectral+Bears)
- [x] [Torture](https://magiccards.info/query?q=!Torture)
- [x] [Trade Caravan](https://magiccards.info/query?q=!Trade+Caravan)
- [x] [Truce](https://magiccards.info/query?q=!Truce)
- [x] [Veldrane of Sengir](https://magiccards.info/query?q=!Veldrane+of+Sengir)
- [x] [Wall of Kelp](https://magiccards.info/query?q=!Wall+of+Kelp)
- [x] [Willow Faerie](https://magiccards.info/query?q=!Willow+Faerie)
- [x] [Willow Priestess](https://magiccards.info/query?q=!Willow+Priestess)
- [x] [Winter Sky](https://magiccards.info/query?q=!Winter+Sky)
- [x] [Wizards' School](https://magiccards.info/query?q=!Wizards'+School)

**Comment by NoahGleason** [comment]
# In Progress:
- [x] Giant Albatross (#5051)
- [x] Giant Oyster (#5058) 
- [ ] Dwarven Sea Clan

**Comment by Susucre** [comment]
Closing this. The remaining card is an Ante card and for now all Ante cards are not planned. #11319 is tracking them instead of individual card sets.
