### ISSUE TITLE
Feedback XMage Version 1.4.30V7

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5155]
# 1.4.30V7

- [ ] Treasure Cove can't sac treasures: I tried to sacrifice a treasure token with Treasure Cove (the flipcard from treasure map)but it didn't work. Possibly because of the antiquities war's last trigger. (reported by CurtainGuy / 2018-07-15 16:41:05.676).
- [ ] Catacomb Dragon: Catacomb Dragon from Mirage doesn't seem to be on here yet, would be neat. (reported by Biest / 2018-07-15 17:35:54.078).
- [ ] blood moon with quicksilver amulet: when bloodmoon is out, and quicksilver amulet. bloodmoon turns nonbasic into mountain then if it gets a flood counter it should only yield U mana. however XMage treats it like a U/R dualland (reported by hypnotic_spect / 2018-07-16 03:19:50.515).
- [ ] Quitters reappear in restarted games: When the game restarts because of a draw, all players who quit earlier appear in the game again, but obviously don't respond to choosing keep or mulligan, locking the game state until they time out. (reported by SirLoinOfBeef / 2018-07-16 06:16:35.047).
- [ ] Dark-dweller oracle + dusk//dawn: The problem or bug here is playing the 2º card out of exile, i had enough mana to cast dusk but the card didnt even let me click on it (reported by Dyphon / 2018-07-16 06:45:47.34).
- [ ] Card Problems: Jaya Ballard's emblem puts cards back into the graveyard after casting them from the graveyard.When Apex of Power is copied it still adds the 10 mana even though it shouldn't. (reported by Wigglyfish2 / 2018-07-16 15:37:12.07).
- [ ] Penny Dreadful list out of date: The penny dreadful filter seems to be out of date as of the new season. The banlist is always up to date at http://pdmtgo.com/legal_cards.txt is there a way to automate updating from it? (reported by codecimal / 2018-07-16 20:21:21.781).
- [ ] image download: i cant download images it just flies trhu all 32k+ download in like 45 sec (reported by Makedake / 2018-07-16 21:53:42.588).
- [ ] Necromantic selection and mimic vat: allowed commander to go to GY to get back from NS opponent put under mimic vat no option to put into command zone (reported by Knighthawke / 2018-07-17 05:00:40.885).
- [ ] server latency: it would be nice to see what latency or ping you have between you and the server. it could be displayed on top of the window beside the "memory used" display.best regards (reported by Scythe / 2018-07-17 14:31:16.849).
- [ ] player latency: it would be nice if you could implement a visual representation of latency between you and other players inside a game. for example you could display it at the mouseover of a player's portrait (reported by Scythe / 2018-07-17 14:32:57.911).
- [ ] Please add the card "Rofellos' Gift": Please add this card, it's imperative to a deck I'm trying to build. (reported by neubstone / 2018-07-17 18:16:27.011).
- [ ] Declare Dominance Interaction: Declare dominance and bristling boar interaction causess the game to break. Doesnt let you block with 1 creature or all your creatures. either way you get an error message (reported by Czarshark / 2018-07-17 22:07:54.172).
- [ ] splice and cost increase: when playing against thalia and splicing through the breach on nourishing shoal, i had to pay additional cost for thalia twice (reported by quod / 2018-07-17 22:52:35.103).
- [ ] Global Series: Seems like Cards for the global series can not be downloaded (reported by Biest / 2018-07-18 00:40:02.723).
- [ ] Allow users to change or re-download card pictures: Some of the pictures for cards (mostly basic lands) are incorrect like a swamp having a Chandra for art.Its really confusing to I think there should be a way to fix this. (reported by DuckManGO / 2018-07-18 03:32:33.538).
- [ ] problem with rollback: whenever a player rollbacks during a multiplayer match game freezes and match can't go on. (reported by capeaux / 2018-07-18 16:09:48.75).
- [ ] Card Bug: Nullstone Gargoyle countered my artifact creature (reported by pie / 2018-07-18 22:23:32.531).
- [ ] Nullstone Golem countered a creature spell: A Nullstone golem just countered a Guardians of Koilos during a commander game, looks like a bug (reported by LeoScibi / 2018-07-18 22:23:42.877).
- [ ] Elfhame Sanctuary does not reveal the searched card: When an opponent searches for a basic land card with elfhame sanctuary, the card does not get revealed to everyone. (reported by Deadlylama / 2018-07-19 11:50:53.926).
- [ ] issues: Awesome Program but it keeps freezing and not letting us go past a certain stageVery Annoying & Frustrating :( (reported by Khornedogg / 2018-07-19 12:29:27.771).
- [ ] blood moon: blood moon still not updated (reported by shroudmaster / 2018-07-19 21:45:18.245).
- [ ] Grave Upheaval: I cast Grave Upheaval for free usingJeleva, Nephalia's Scourge ability which allowed me to targetan instant card and the instant was placed on thebattlefield... (reported by Techies / 2018-07-19 22:08:14.391).
- [ ] Start draft early if someone will have a Bye in R1: Not sure if it's "legal", but I was thinking it would be nice to start the matchups early if one person is still constructing and someone else already quit, causing a R1 bye. Less waiting. (reported by papapao / 2018-07-20 00:50:01.376).
- [ ] Standard/m19: The core 19 set cards are not showing up when you choose standard in the deck editor. Only way to use them is to choose the set only. (reported by swoosh9000 / 2018-07-20 01:06:54.653).
- [ ] Bug on Fumble: Hello,I casted "Fumble" (Battlebond) targeting a Serra Ascendant, the spell resolved but the ascendant stayed on the battlefield. (reported by Endymion / 2018-07-20 15:28:06.142).

**Comment by LevelX2** [comment]
# 1.4.30V7 2018-08-06 21:45 CET

- [ ] Mssing Card: Hey guys, i appreciate your work here and i love playing MTG online :)I just have noticed, that the card "Death or Glory"is missing in your card pool. Maybe u wanna know.Have a great day:) (reported by Krustenkaese / 2018-07-20 16:35:42.315).
- [ ] "Add Lands" adds snow lands: When using the "Add Lands" feature with ice age as the set, the game randomly adds snow covered basics to your deck, which should not be possible, at least when playing limited in a format that has those lands in it. (reported by Deadlylama / 2018-07-21 11:30:18.57).
- [ ] Es posible crear robots para jugar un match 1v1?: Hay un jugador llamado @abc y siempre crea un match de MTGO Commnader, cuando uno intenta uniser a esta mesa aparece un mensaje que dice "A human player cant join to this table". (reported by whiteraven / 2018-07-22 02:29:03.509).
- [ ] etali+seize the day: i tried to cast "seize the day" with my "etali" but i didnt get the bonus combat step (reported by aidsregen / 2018-07-22 13:59:45.405).
- [ ] bloodrush bug: Hi, it seems bloodrush (ghor-clan rampager) is bugged. Couldn't activate after declare blocker step. (reported by gregA / 2018-07-22 19:40:19.553).
- [ ] fix the interaction with blood moon and shocklands: (300 characters max)\With the new rule change for blood moon, if you play a shock land you don't need to pay 2 life for it to enter in untapped. It should just enter like a basic mountain. (reported by jc64576 / 2018-07-22 22:03:05.497).
- [ ] Poison-Tip Archer: When this dies, it shouldn't trigger (reported by jerjern / 2018-07-22 23:00:21.005).
- [ ] I can't open the preferences menu: Ummmm I can't open the preferences menu! Everything else works, besides the disconnect/connect-to-server button which only SOMETIMES works. Pls help (reported by Decaf_Doctor / 2018-07-23 03:17:35.917).
- [ ] Friends List: When it is possible, then it would be great to have such a function in the system (reported by Exsoul / 2018-07-23 22:00:01.307).
- [ ] Blood Moon Fix: Blood Moon Currently doesn't work properlyright now you still have to pay life for shocks to come in untapped and Cavern of Souls stills gets to chose a creature type (reported by HlaineLarkin / 2018-07-24 12:32:00.696).
- [ ] commander anthology 2: can't download commander anthology 2 images (reported by crud / 2018-07-24 23:52:45.666).
- [ ] commander quitting: whenever someone quits a game of 4player commander without conceding, their effects (i.e. aura of silence, urborg) stick around (reported by crud / 2018-07-25 06:21:12.241).
- [ ] BUG Chaos wand: My opponent casted my creature spell with it. (reported by BLUE_GOBLIN / 2018-07-25 11:28:01.984).
- [ ] PTC Flip walkers reverse side: The images for the reverse side of the PTC flip walkers aren't consistent, should fix this. (reported by EvilGeek / 2018-07-25 12:11:21.595).
- [ ] Cards seem to be missing on server: Have a problem where server can't find cards that are only in 1 set and legal in standard meta. (reported by KennyTiger / 2018-07-25 14:03:18.817).
- [ ] server or luncher bug again...: cant create game cards not support EDH.... and luncher wont start (reported by blaisfm / 2018-07-25 15:16:32.526).
- [ ] I have unable to play Knollspine Dragon due to a card not found error: Wondering if you can fix this. (reported by Zainb / 2018-07-26 03:09:11.644).
- [ ] injury (aftermath): when my opponent cast injury for the gy, stays in the stack and i can untap, twice (reported by luzio1150 / 2018-07-26 16:25:42.304).
- [ ] bug with kikki jiki: Kikki jiki and scourge of th throne. Token does not give bonus comat (reported by Eierkloppa / 2018-07-26 23:08:20.102).
- [ ] New Blood Doesn't do what it says: it changes creature types but not words in the text box. (reported by doc_brietz / 2018-07-27 06:32:50.254).
- [ ] Cant Cast random spells: Has happened with Dig Through Time and Thoughtseize. I click the spell and it displays a window with "Choose ability to activate" and 2 options. 1. The effect of my spell 2. Close. No matter what I choose the spell wont be put on the stack. (reported by OathOfRhino / 2018-07-27 15:54:01.651).
- [ ] Don't send feedbacks with too long descriptions: Don't automatically send feedback on "Send" button. Check first lenght of description and then return to description giving screen. (reported by Tompreos / 2018-07-27 23:27:11.358).
- [ ] Utopia Mycon asks target two times: Utopia mycon asks target two times, even when there should be only one target (reported by Tompreos / 2018-07-27 23:29:00.584).
- [ ] Can't download Symbols or images: Hi. I can't download symbols or images. (reported by TheDude / 2018-07-28 11:08:02.958).
- [ ] MTGO 1v1 Commander Rule Update: The MTGO 1v1 Commander format on xMage has not yet been updated to reflect the new bannings (reported by jspringfield / 2018-07-28 11:41:54.84).
- [ ] kenrith (will and rowan) emblem doesn't works: Emblems of will and rowan kenrith triggs, but doesn't works (doesn't copy abilities or spells). The good point is that they trigg when ce cast a spelle or play an ability.Thank for your help,Sincerely yours,Quentin (reported by senseiidora / 2018-07-29 14:44:42.254).
- [ ] contribute: If I was willing to donate some charity to xmage, just as a thank you for this amazing free site, where would I do so? (reported by prilisx / 2018-07-29 17:07:10.31).
- [ ] Hotkey to switch panels: The ability to switch panels with a hotkey would be great (reported by psypsy / 2018-07-29 21:26:59.337).
- [ ] mindslaver and the commander: i cant play the commander enemy when i take the turn of this in a multplayer game (reported by whiteraven / 2018-07-29 23:46:36.394).
- [ ] card bugged sarkhan dragonsoul: sarkhan dragonsoul only has one of his abilities programed into the game. his -9. (reported by bdock3601 / 2018-07-30 06:30:54.698).
- [ ] Subterranean Tremors Bug: Hi there. I just Subterranean Tremors'd with x=4, destroying a skullclamp equipped to a creature. Since damage doesn't destroy creatures, but the spell does destroy artifacts, my opponent shouldn't have been able to draw cards, but he did. (reported by guifig / 2018-07-30 14:32:04.646).
- [ ] Preacher: Preacher's activated ability doesn't work never eneded up with controling opps creature. (reported by Tsunamiis / 2018-07-30 17:01:37.857).
- [ ] Sweltering Suns: It did not kill True Name Nemesis when cast to deal 3dmg to all targets. (reported by RedSheBathed / 2018-07-30 22:07:33.083).
- [ ] update blood moon rules: (300 characters max) (reported by Shedrick / 2018-07-31 16:22:24.572).
- [ ] Open the Graves + Doomed Dissenter: Doomed Dissenter states that when it dies you get a 2/2 zombie.Open the Graves states that when a creature you control dies, you get a 2/2 zombie.When Dissenter dies and Open the Graves is in your control, you get NO zombies!! (reported by Himsself / 2018-07-31 17:25:39.451).
- [ ] Plasm Capture bug: Plasm Capture gives double amount of mana. (reported by Ivaldes / 2018-07-31 19:52:54.278).
- [ ] casting cost color pie change: It appears the pie chart when assess casting costs is incuding generic mana costs, making the pie about 75% colorless. Makes it difficult to properly gauge color distribution (reported by Knighthawke / 2018-07-31 22:13:34.921).
- [ ] Ne Blood Bug: New blood do not replaces all instances of the textonly the type (reported by Ivaldes / 2018-07-31 23:01:27.46).
- [ ] rememberance: rememberance triggers on all creature, not only your own (reported by bdock3601 / 2018-08-01 06:40:56.454).
- [ ] bug or glitch in drafts: the second round of draft has started and I haven't been put inside the game to play it and for my opponent same (reported by KennyTiger / 2018-08-01 11:59:15.793).
- [ ] angelic destiny bug: sacraficed creature with angelic destiny attached, angelic destiny does not return to hand (reported by LordStov / 2018-08-01 13:20:29.511).
- [ ] fix Bosejuwho shelters all: Daze was able to counter show and tell eventhough it was cast with Boseju (reported by Kwak675 / 2018-08-01 16:53:01.569).
- [ ] dylvick3: The card Primal Surge only exiles the first card of my library doesn't cast it and then doesn't repeat the process (reported by dylvick3 / 2018-08-02 04:02:05.539).
- [ ] When playing against my friend, it freezes many times: When playing against my friend, xmage freezes to often. Can anything be done? (reported by DonKarnage / 2018-08-02 09:50:58.669).
- [ ] Game stuck when Opponent disconnects with commander out and board wipe: When an opponent disconnects/leaves with their commander out and a board wipe happens, it still prompts the left player what to do with the commander and leaves the game stuck with the timer going down on the left player. (reported by Scythe / 2018-08-02 12:46:13.148).
- [ ] C18: Hey guys,When Commander 2018 cards are coming to xmage?Regards! (reported by poggers / 2018-08-02 16:17:43.377).
- [ ] Erayo flipped and Mox Amber: the title , mox amber wont tape when Erayo is flipped (reported by Antulja / 2018-08-03 19:29:44.373).
- [ ] chrome mox: i just hardlocked the game by saying yes to chrome mox, with only lands and artifacts in my handplease fix this. (reported by heat / 2018-08-04 19:32:05.667).
- [ ] elvish rejuvinator issue: elvish rejuvinator is a "may" ability but no choice is given (reported by Knighthawke / 2018-08-05 04:11:46.408).
- [ ] blood moon does not work with spreading seas: in a game, haviong blood moon already in play.played a spreading seas enchanting my hallowed fountain.i could not tap that land for blue mana afterwardsaccording to timestamp order, that land should have been an island (reported by no11 / 2018-08-05 10:50:23.009).
- [ ] missing card: i don't know if there are many cards that are not present, i just happened to find one of them, more specifically "artificial evolution" from onslaught (reported by LarryTheCow / 2018-08-05 13:02:17.707).
- [ ] bug: in draft match I was offer a single choice for a non choice spells anticipate and take vengeance and when I cliqued on the choice nothing happened and I cannot cast them, I am in a rated game and this affects my rating (reported by KennyTiger / 2018-08-05 19:14:11.736).
- [ ] Spires Of Orazoa: SPires of Orazoa can only be tapped for mana and nothing else. (reported by Zargruzh / 2018-08-05 21:02:39.107).
- [ ] bug: bounceland entering the battlefield with outpost siege came into play untapped (reported by Demoncookie / 2018-08-06 00:21:12.601).
- [ ] Fumble doesn'y bounce creature back to hand: Title (reported by mrtwigs / 2018-08-06 02:41:44.509).
- [ ] Unable to recast spells after they are remanded off a cascade trigger.: I bloodbraid elf, cascade into goyf, my oppoent remands the goyf and it goes to my had. I an unable to cast it afterwords, it pops up as: cast tarmagyf or cancel, i press cast and nothing happens. The same happened with a lightning bolt off cascade. (reported by LunaLoutre / 2018-08-06 06:02:18.652).

**Comment by LevelX2** [comment]
# 2018-08-15

- [ ] Wrong images: Hey, Arcades the Strategist got an image of pelakka wurm in my collection. just for u to know :) nice game anyway! i appreciate your work!Greetings and have a nice day:) (reported by Krustenkaese / 2018-08-06 23:14:52.847).
- [ ] kick system: enter a "/kick (playername) function, and then allow voting between other players to kick the player, specifically for inactive playersyou guys are the best (reported by QuoVadis / 2018-08-06 23:22:47.478).
- [ ] bug interaction: resolute archangel should restore life total, and not be counted as life gain. but, it is counted as lifegain on xmage (reported by bdock3601 / 2018-08-07 03:46:56.584).
- [ ] Missing card: Missing card: Clear the LandIt's from Masques (reported by TheFreeWill / 2018-08-07 06:20:17.489).
- [ ] seal away: im currently playing a brawl game. all my opponets creatures enters tapped.then i try to cast seal away to exile a tapped creature. but it wont let me cast it (reported by Trilex / 2018-08-07 21:24:02.458).
- [ ] Can't see any tables: I can't see any of the tables for some reason. (reported by Dreamweaver20 / 2018-08-08 10:00:41.832).
- [ ] Still can't see tables.: I tried a complete uninstall and reinstall, but I'm not having any luck. Any ideas? Thanks!! (reported by Dreamweaver20 / 2018-08-09 09:43:29.996).
- [ ] be able to leave games after you concede or lose: be able to leave games after you concede or lose (reported by lord0fham / 2018-08-09 10:11:33.928).
- [ ] Flashback and Replicate: When casting Gigadrowse with flashback thanks to Snapcaster Mage, there is no option to pay replicate cost, which contradicts rules 702.55a and 601.2b. (reported by quod / 2018-08-09 11:48:49.289).
- [ ] fix pls: Hi,if I animated 2 lands with "NISSA, STUARD OF ELEMENTS" i could not tap them for mana (reported by Heeri / 2018-08-09 22:27:39.16).
- [ ] el pacto negro no funciona: slaugther pact no works when u play the pact u no pay the cost at beginig of u ukeep (reported by whiteraven / 2018-08-10 04:55:03.801).
- [ ] Used boros signet casting painful truths, only got two cards.:  (reported by flaxencobra / 2018-08-10 19:40:21.916).
- [ ] Blood Sun, Boros Garrsion: Garrison ETB's tapped (reported by flaxencobra / 2018-08-10 21:45:36.556).
- [ ] bug with Populate hability: when casting Sundering Growth, if there's a non-creature token on the battlefield, xmage ask me to choose a target, and then copy the token.it happens with Clue tokens on the battlefield, not tested with others (reported by Quinti / 2018-08-11 00:45:30.863).
- [ ] i cant play agruul signet in maelstrom deck:  (reported by whiteraven / 2018-08-11 16:51:42.359).
- [ ] Stuffy Doll reanimate: Brought back Stuffy Doll with tariel, didnt get an ETB (reported by flaxencobra / 2018-08-11 22:14:50.282).
- [ ] Add commander 2018: When will the cards from commander 2018 be added? (reported by valdezzey / 2018-08-12 01:06:36.278).
- [ ] A kick/ban feature: There are griefers (reported by TurnOneMagic / 2018-08-12 01:59:02.337).
- [ ] Flashback Mystic Retrieval.: When flashing back mystic retrieval, it just exiles itself without having any effect. (reported by Azeraph / 2018-08-12 02:53:57.357).
- [ ] timed out players still affecting game??: Players that have expired or left still have global affects on the game *(frozen aether) (reported by StormCroe / 2018-08-12 14:13:47.346).
- [ ] taplands entering untapped: Just played a game of M19 draft where Cinder Barrens and Forsaken Sanctuary entered the battlefield untapped, when they're supposed to enter tapped. (reported by bhegstad / 2018-08-12 19:56:45.594).
- [ ] commander quit bug: just wondering if you guys are ever gonna fix that bug when someone quits a 4 player game and their stuff stays in play and essentially ruins the game for everyone else? (reported by crud / 2018-08-13 07:32:52.747).
- [ ] MIssing card: The card Power Taint from Urza's Saga is missing (reported by RvBelial / 2018-08-13 13:26:45.52).
- [ ] Actuall Banlist WotC 1v1: I think there is not the actual Banlist from 25 July.could taht be rght (reported by Skymo / 2018-08-13 15:27:07.701).
- [ ] Teferi, Hero of Dominaria: TEFERI HAS TO UNTAP TWO LANDS. IF I HAVE ONLY 1 TO UNTAP THEN IT BUGS!!!!PLEASE FIX!!! (reported by Mr_Ozonloch / 2018-08-13 18:04:43.119).
- [ ] cinder glade entering at the same time as the 2nd basic land should be untapped: cinder glade and other lands probably are bugged. if it enters at the same time as the basic lands it will enter untapped (reported by StormCroe / 2018-08-13 18:17:20.207).
- [ ] Benhor cheated: My opponant (BenHor) intentionally put a veraska into play from a chandra +1 without paying the mana cost.I called him on it and he said it was a bug, so i rolled back the turn , he did it again this means it is repeatable. (reported by oozy / 2018-08-14 02:05:20.17).
- [ ] Candian Highlander Points List: Demonic Tutor was reduced to 3 points in July 2018 (reported by Bmchafa / 2018-08-14 04:19:03.216).
- [ ] MTGO 1v1 Commander Rule Set: The incorrect ruleset for MTGO 1v1 Commander is still in effect (reported by jspringfield / 2018-08-14 12:21:41.208).
- [ ] Mystic Speculation: If you cast Mystic Speculation with buyback and a Leyline of the void is on the field, the card gets exiled anyway. Buyback SHOULD work. (reported by doc_brietz / 2018-08-14 15:32:13.253).
- [ ] vesuvan shapeshifter: i attempted to turn it face up with plenty of options to choose and it died (reported by doc_brietz / 2018-08-14 15:47:56.876).
- [ ] boseiju don't works with counterbalance: hi,i had boseiju and played istant and sorceries but everything was countered by counterbalance triggers.I had sphere of resistence into play if it can help.keep up the good work! (reported by Ciubulu / 2018-08-14 18:11:43.283).
- [ ] bug: could not cast creature exiled with hostage taker. when selected to cast creature menu just disappears. (reported by jmoney1123 / 2018-08-15 05:15:31.809).
- [ ] Teferi, Hero of Dominaria Untap Lands: If all my lands are untapped, I can't select two lands when Teferi, Hero of Dominaria's untap two land trigger goes on the stack. I should be able to though because Teferi's trigger says "untap two lands" and not "untap two untapped lands". (reported by chataolauj / 2018-08-15 06:27:24.422).
- [ ] Fix the quitting bug: in multiplayer games, when a player leaves the match, their permanents dont get removed. Thats VERY annoying in commander (reported by Kraya / 2018-08-15 09:14:41.764).
- [ ] Bounce land w/ Bloos Sun: Bounce lands ETB tapped with blood sun out (reported by flaxencobra / 2018-08-15 10:17:49.299).

**Comment by Alex-Vasile** [comment]
"MIssing card: The card Power Taint from Urza's Saga is missing" 

Implemented in https://github.com/magefree/mage/commit/69e795e75e0961e920b831e0798c447bce6d9201
