### ISSUE TITLE
C18 - Commander 2018 Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#5165]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Implemented Cards

- [x] Done -- [Acidic Slime](https://scryfall.com/search?q=Acidic+Slime)
- [x] Done -- [Adarkar Valkyrie](https://scryfall.com/search?q=Adarkar+Valkyrie)
- [x] Done -- [Aether Gale](https://scryfall.com/search?q=Aether+Gale)
- [x] Done -- [Aethermage's Touch](https://scryfall.com/search?q=Aethermages+Touch)
- [x] Done -- [Ajani's Chosen](https://scryfall.com/search?q=Ajanis+Chosen)
- [x] Done -- [Akoum Refuge](https://scryfall.com/search?q=Akoum+Refuge)
- [x] Done -- [Akroma's Vengeance](https://scryfall.com/search?q=Akromas+Vengeance)
- [x] Done -- [Aminatou's Augury](https://scryfall.com/search?q=Aminatous+Augury)
- [x] Done -- [Aminatou, the Fateshifter](https://scryfall.com/search?q=Aminatou,+the+Fateshifter)
- [x] Done -- [Ancient Stone Idol](https://scryfall.com/search?q=Ancient+Stone+Idol)
- [x] Done -- [Arcane Sanctum](https://scryfall.com/search?q=Arcane+Sanctum)
- [x] Done -- [Archetype of Imagination](https://scryfall.com/search?q=Archetype+of+Imagination)
- [x] Done -- [Arixmethes, Slumbering Isle](https://scryfall.com/search?q=Arixmethes,+Slumbering+Isle)
- [x] Done -- [Army of the Damned](https://scryfall.com/search?q=Army+of+the+Damned)
- [x] Done -- [Aura Gnarlid](https://scryfall.com/search?q=Aura+Gnarlid)
- [x] Done -- [Avenger of Zendikar](https://scryfall.com/search?q=Avenger+of+Zendikar)
- [x] Done -- [Azorius Chancery](https://scryfall.com/search?q=Azorius+Chancery)
- [x] Done -- [Azorius Guildgate](https://scryfall.com/search?q=Azorius+Guildgate)
- [x] Done -- [Azorius Signet](https://scryfall.com/search?q=Azorius+Signet)
- [x] Done -- [Baloth Woodcrasher](https://scryfall.com/search?q=Baloth+Woodcrasher)
- [x] Done -- [Banishing Stroke](https://scryfall.com/search?q=Banishing+Stroke)
- [x] Done -- [Bant Charm](https://scryfall.com/search?q=Bant+Charm)
- [x] Done -- [Barren Moor](https://scryfall.com/search?q=Barren+Moor)
- [x] Done -- [Bear Umbra](https://scryfall.com/search?q=Bear+Umbra)
- [x] Done -- [Blasphemous Act](https://scryfall.com/search?q=Blasphemous+Act)
- [x] Done -- [Blighted Woodland](https://scryfall.com/search?q=Blighted+Woodland)
- [x] Done -- [Blinkmoth Urn](https://scryfall.com/search?q=Blinkmoth+Urn)
- [x] Done -- [Bloodtracker](https://scryfall.com/search?q=Bloodtracker)
- [x] Done -- [Blossoming Sands](https://scryfall.com/search?q=Blossoming+Sands)
- [x] Done -- [Bojuka Bog](https://scryfall.com/search?q=Bojuka+Bog)
- [x] Done -- [Boon Satyr](https://scryfall.com/search?q=Boon+Satyr)
- [x] Done -- [Borderland Explorer](https://scryfall.com/search?q=Borderland+Explorer)
- [x] Done -- [Boreas Charger](https://scryfall.com/search?q=Boreas+Charger)
- [x] Done -- [Bosh, Iron Golem](https://scryfall.com/search?q=Bosh,+Iron+Golem)
- [x] Done -- [Brainstorm](https://scryfall.com/search?q=Brainstorm)
- [x] Done -- [Brudiclad, Telchor Engineer](https://scryfall.com/search?q=Brudiclad,+Telchor+Engineer)
- [x] Done -- [Bruna, Light of Alabaster](https://scryfall.com/search?q=Bruna,+Light+of+Alabaster)
- [x] Done -- [Budoka Gardener](https://scryfall.com/search?q=Budoka+Gardener)
- [x] Done -- [Buried Ruin](https://scryfall.com/search?q=Buried+Ruin)
- [x] Done -- [Celestial Archon](https://scryfall.com/search?q=Celestial+Archon)
- [x] Done -- [Centaur Vinecrasher](https://scryfall.com/search?q=Centaur+Vinecrasher)
- [x] Done -- [Chain Reaction](https://scryfall.com/search?q=Chain+Reaction)
- [x] Done -- [Chaos Warp](https://scryfall.com/search?q=Chaos+Warp)
- [x] Done -- [Charnelhoard Wurm](https://scryfall.com/search?q=Charnelhoard+Wurm)
- [x] Done -- [Chief of the Foundry](https://scryfall.com/search?q=Chief+of+the+Foundry)
- [x] Done -- [Cloudform](https://scryfall.com/search?q=Cloudform)
- [x] Done -- [Cold-Eyed Selkie](https://scryfall.com/search?q=Cold-Eyed+Selkie)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=Command+Tower)
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=Commanders+Sphere)
- [x] Done -- [Consign to Dust](https://scryfall.com/search?q=Consign+to+Dust)
- [x] Done -- [Conundrum Sphinx](https://scryfall.com/search?q=Conundrum+Sphinx)
- [x] Done -- [Coveted Jewel](https://scryfall.com/search?q=Coveted+Jewel)
- [x] Done -- [Crash of Rhino Beetles](https://scryfall.com/search?q=Crash+of+Rhino+Beetles)
- [x] Done -- [Creeping Renaissance](https://scryfall.com/search?q=Creeping+Renaissance)
- [x] Done -- [Crib Swap](https://scryfall.com/search?q=Crib+Swap)
- [x] Done -- [Crystal Ball](https://scryfall.com/search?q=Crystal+Ball)
- [x] Done -- [Cultivate](https://scryfall.com/search?q=Cultivate)
- [x] Done -- [Darksteel Citadel](https://scryfall.com/search?q=Darksteel+Citadel)
- [x] Done -- [Darksteel Juggernaut](https://scryfall.com/search?q=Darksteel+Juggernaut)
- [x] Done -- [Dawn's Reflection](https://scryfall.com/search?q=Dawns+Reflection)
- [x] Done -- [Daxos of Meletis](https://scryfall.com/search?q=Daxos+of+Meletis)
- [x] Done -- [Deathreap Ritual](https://scryfall.com/search?q=Deathreap+Ritual)
- [x] Done -- [Decimate](https://scryfall.com/search?q=Decimate)
- [x] Done -- [Devastation Tide](https://scryfall.com/search?q=Devastation+Tide)
- [x] Done -- [Dictate of Kruphix](https://scryfall.com/search?q=Dictate+of+Kruphix)
- [x] Done -- [Dimir Aqueduct](https://scryfall.com/search?q=Dimir+Aqueduct)
- [x] Done -- [Dimir Guildgate](https://scryfall.com/search?q=Dimir+Guildgate)
- [x] Done -- [Dimir Signet](https://scryfall.com/search?q=Dimir+Signet)
- [x] Done -- [Dismal Backwater](https://scryfall.com/search?q=Dismal+Backwater)
- [x] Done -- [Dismantling Blow](https://scryfall.com/search?q=Dismantling+Blow)
- [x] Done -- [Djinn of Wishes](https://scryfall.com/search?q=Djinn+of+Wishes)
- [x] Done -- [Dream Cache](https://scryfall.com/search?q=Dream+Cache)
- [x] Done -- [Dreamstone Hedron](https://scryfall.com/search?q=Dreamstone+Hedron)
- [x] Done -- [Duplicant](https://scryfall.com/search?q=Duplicant)
- [x] Done -- [Duskmantle Seer](https://scryfall.com/search?q=Duskmantle+Seer)
- [x] Done -- [Echo Storm](https://scryfall.com/search?q=Echo+Storm)
- [x] Done -- [Eel Umbra](https://scryfall.com/search?q=Eel+Umbra)
- [x] Done -- [Eidolon of Blossoms](https://scryfall.com/search?q=Eidolon+of+Blossoms)
- [x] Done -- [Elderwood Scion](https://scryfall.com/search?q=Elderwood+Scion)
- [x] Done -- [Emissary of Grudges](https://scryfall.com/search?q=Emissary+of+Grudges)
- [x] Done -- [Empyrial Storm](https://scryfall.com/search?q=Empyrial+Storm)
- [x] Done -- [Enchanter's Bane](https://scryfall.com/search?q=Enchanters+Bane)
- [x] Done -- [Enchantress's Presence](https://scryfall.com/search?q=Enchantresss+Presence)
- [x] Done -- [Endless Atlas](https://scryfall.com/search?q=Endless+Atlas)
- [x] Done -- [Enigma Sphinx](https://scryfall.com/search?q=Enigma+Sphinx)
- [x] Done -- [Entreat the Angels](https://scryfall.com/search?q=Entreat+the+Angels)
- [x] Done -- [Entreat the Dead](https://scryfall.com/search?q=Entreat+the+Dead)
- [x] Done -- [Epic Proportions](https://scryfall.com/search?q=Epic+Proportions)
- [x] Done -- [Esper Charm](https://scryfall.com/search?q=Esper+Charm)
- [x] Done -- [Estrid's Invocation](https://scryfall.com/search?q=Estrids+Invocation)
- [x] Done -- [Estrid, the Masked](https://scryfall.com/search?q=Estrid,+the+Masked)
- [x] Done -- [Etherium Sculptor](https://scryfall.com/search?q=Etherium+Sculptor)
- [x] Done -- [Ever-Watching Threshold](https://scryfall.com/search?q=Ever-Watching+Threshold)
- [x] Done -- [Evolving Wilds](https://scryfall.com/search?q=Evolving+Wilds)
- [x] Done -- [Explore](https://scryfall.com/search?q=Explore)
- [x] Done -- [Explosive Vegetation](https://scryfall.com/search?q=Explosive+Vegetation)
- [x] Done -- [Far Wanderings](https://scryfall.com/search?q=Far+Wanderings)
- [x] Done -- [Farhaven Elf](https://scryfall.com/search?q=Farhaven+Elf)
- [x] Done -- [Fertile Ground](https://scryfall.com/search?q=Fertile+Ground)
- [x] Done -- [Finest Hour](https://scryfall.com/search?q=Finest+Hour)
- [x] Done -- [Flameblast Dragon](https://scryfall.com/search?q=Flameblast+Dragon)
- [x] Done -- [Forge of Heroes](https://scryfall.com/search?q=Forge+of+Heroes)
- [x] Done -- [Forgotten Cave](https://scryfall.com/search?q=Forgotten+Cave)
- [x] Done -- [Forsaken Sanctuary](https://scryfall.com/search?q=Forsaken+Sanctuary)
- [x] Done -- [Foundry of the Consuls](https://scryfall.com/search?q=Foundry+of+the+Consuls)
- [x] Done -- [Fury Storm](https://scryfall.com/search?q=Fury+Storm)
- [x] Done -- [Gaze of Granite](https://scryfall.com/search?q=Gaze+of+Granite)
- [x] Done -- [Genesis Storm](https://scryfall.com/search?q=Genesis+Storm)
- [x] Done -- [Geode Golem](https://scryfall.com/search?q=Geode+Golem)
- [x] Done -- [Golgari Rot Farm](https://scryfall.com/search?q=Golgari+Rot+Farm)
- [x] Done -- [Grapple with the Past](https://scryfall.com/search?q=Grapple+with+the+Past)
- [x] Done -- [Great Furnace](https://scryfall.com/search?q=Great+Furnace)
- [x] Done -- [Grim Backwoods](https://scryfall.com/search?q=Grim+Backwoods)
- [x] Done -- [Grisly Salvage](https://scryfall.com/search?q=Grisly+Salvage)
- [x] Done -- [Ground Seal](https://scryfall.com/search?q=Ground+Seal)
- [x] Done -- [Gruul Turf](https://scryfall.com/search?q=Gruul+Turf)
- [x] Done -- [Gyrus, Waker of Corpses](https://scryfall.com/search?q=Gyrus,+Waker+of+Corpses)
- [x] Done -- [Halimar Depths](https://scryfall.com/search?q=Halimar+Depths)
- [x] Done -- [Harrow](https://scryfall.com/search?q=Harrow)
- [x] Done -- [Haunted Fengraf](https://scryfall.com/search?q=Haunted+Fengraf)
- [x] Done -- [Heavenly Blademaster](https://scryfall.com/search?q=Heavenly+Blademaster)
- [x] Done -- [Hedron Archive](https://scryfall.com/search?q=Hedron+Archive)
- [x] Done -- [Hellkite Igniter](https://scryfall.com/search?q=Hellkite+Igniter)
- [x] Done -- [Herald of the Pantheon](https://scryfall.com/search?q=Herald+of+the+Pantheon)
- [x] Done -- [High Priest of Penance](https://scryfall.com/search?q=High+Priest+of+Penance)
- [x] Done -- [Highland Lake](https://scryfall.com/search?q=Highland+Lake)
- [x] Done -- [Hunting Wilds](https://scryfall.com/search?q=Hunting+Wilds)
- [x] Done -- [Hydra Omnivore](https://scryfall.com/search?q=Hydra+Omnivore)
- [x] Done -- [Inkwell Leviathan](https://scryfall.com/search?q=Inkwell+Leviathan)
- [x] Done -- [Into the Roil](https://scryfall.com/search?q=Into+the+Roil)
- [x] Done -- [Isolated Watchtower](https://scryfall.com/search?q=Isolated+Watchtower)
- [x] Done -- [Izzet Boilerworks](https://scryfall.com/search?q=Izzet+Boilerworks)
- [x] Done -- [Izzet Guildgate](https://scryfall.com/search?q=Izzet+Guildgate)
- [x] Done -- [Izzet Signet](https://scryfall.com/search?q=Izzet+Signet)
- [x] Done -- [Jeskai Infiltrator](https://scryfall.com/search?q=Jeskai+Infiltrator)
- [x] Done -- [Jund Panorama](https://scryfall.com/search?q=Jund+Panorama)
- [x] Done -- [Jungle Hollow](https://scryfall.com/search?q=Jungle+Hollow)
- [x] Done -- [Jwar Isle Refuge](https://scryfall.com/search?q=Jwar+Isle+Refuge)
- [x] Done -- [Kazandu Refuge](https://scryfall.com/search?q=Kazandu+Refuge)
- [x] Done -- [Kestia, the Cultivator](https://scryfall.com/search?q=Kestia,+the+Cultivator)
- [x] Done -- [Khalni Garden](https://scryfall.com/search?q=Khalni+Garden)
- [x] Done -- [Khalni Heart Expedition](https://scryfall.com/search?q=Khalni+Heart+Expedition)
- [x] Done -- [Krosan Verge](https://scryfall.com/search?q=Krosan+Verge)
- [x] Done -- [Kruphix's Insight](https://scryfall.com/search?q=Kruphixs+Insight)
- [x] Done -- [Lavalanche](https://scryfall.com/search?q=Lavalanche)
- [x] Done -- [Lightform](https://scryfall.com/search?q=Lightform)
- [x] Done -- [Lonely Sandbar](https://scryfall.com/search?q=Lonely+Sandbar)
- [x] Done -- [Lord Windgrace](https://scryfall.com/search?q=Lord+Windgrace)
- [x] Done -- [Loyal Apprentice](https://scryfall.com/search?q=Loyal+Apprentice)
- [x] Done -- [Loyal Drake](https://scryfall.com/search?q=Loyal+Drake)
- [x] Done -- [Loyal Guardian](https://scryfall.com/search?q=Loyal+Guardian)
- [x] Done -- [Loyal Subordinate](https://scryfall.com/search?q=Loyal+Subordinate)
- [x] Done -- [Loyal Unicorn](https://scryfall.com/search?q=Loyal+Unicorn)
- [x] Done -- [Magmaquake](https://scryfall.com/search?q=Magmaquake)
- [x] Done -- [Magnifying Glass](https://scryfall.com/search?q=Magnifying+Glass)
- [x] Done -- [Magus of the Balance](https://scryfall.com/search?q=Magus+of+the+Balance)
- [x] Done -- [Martial Coup](https://scryfall.com/search?q=Martial+Coup)
- [x] Done -- [Maverick Thopterist](https://scryfall.com/search?q=Maverick+Thopterist)
- [x] Done -- [Meandering River](https://scryfall.com/search?q=Meandering+River)
- [x] Done -- [Mimic Vat](https://scryfall.com/search?q=Mimic+Vat)
- [x] Done -- [Mind Stone](https://scryfall.com/search?q=Mind+Stone)
- [x] Done -- [Mirrorworks](https://scryfall.com/search?q=Mirrorworks)
- [x] Done -- [Moldgraf Monstrosity](https://scryfall.com/search?q=Moldgraf+Monstrosity)
- [x] Done -- [Moonlight Bargain](https://scryfall.com/search?q=Moonlight+Bargain)
- [x] Done -- [Mortify](https://scryfall.com/search?q=Mortify)
- [x] Done -- [Mortuary Mire](https://scryfall.com/search?q=Mortuary+Mire)
- [x] Done -- [Mosswort Bridge](https://scryfall.com/search?q=Mosswort+Bridge)
- [x] Done -- [Mountain Valley](https://scryfall.com/search?q=Mountain+Valley)
- [x] Done -- [Mulldrifter](https://scryfall.com/search?q=Mulldrifter)
- [x] Done -- [Myr Battlesphere](https://scryfall.com/search?q=Myr+Battlesphere)
- [x] Done -- [Myriad Landscape](https://scryfall.com/search?q=Myriad+Landscape)
- [x] Done -- [Myth Unbound](https://scryfall.com/search?q=Myth+Unbound)
- [x] Done -- [Nesting Dragon](https://scryfall.com/search?q=Nesting+Dragon)
- [x] Done -- [New Benalia](https://scryfall.com/search?q=New+Benalia)
- [x] Done -- [Night Incarnate](https://scryfall.com/search?q=Night+Incarnate)
- [x] Done -- [Ninja of the Deep Hours](https://scryfall.com/search?q=Ninja+of+the+Deep+Hours)
- [x] Done -- [Nylea's Colossus](https://scryfall.com/search?q=Nyleas+Colossus)
- [x] Done -- [Octopus Umbra](https://scryfall.com/search?q=Octopus+Umbra)
- [x] Done -- [Orzhov Basilica](https://scryfall.com/search?q=Orzhov+Basilica)
- [x] Done -- [Orzhov Guildgate](https://scryfall.com/search?q=Orzhov+Guildgate)
- [x] Done -- [Orzhov Signet](https://scryfall.com/search?q=Orzhov+Signet)
- [x] Done -- [Overgrowth](https://scryfall.com/search?q=Overgrowth)
- [x] Done -- [Phyrexian Delver](https://scryfall.com/search?q=Phyrexian+Delver)
- [x] Done -- [Phyrexian Rebirth](https://scryfall.com/search?q=Phyrexian+Rebirth)
- [x] Done -- [Pilgrim's Eye](https://scryfall.com/search?q=Pilgrims+Eye)
- [x] Done -- [Ponder](https://scryfall.com/search?q=Ponder)
- [x] Done -- [Portent](https://scryfall.com/search?q=Portent)
- [x] Done -- [Predict](https://scryfall.com/search?q=Predict)
- [x] Done -- [Primordial Mist](https://scryfall.com/search?q=Primordial+Mist)
- [x] Done -- [Prismatic Lens](https://scryfall.com/search?q=Prismatic+Lens)
- [x] Done -- [Prototype Portal](https://scryfall.com/search?q=Prototype+Portal)
- [x] Done -- [Psychosis Crawler](https://scryfall.com/search?q=Psychosis+Crawler)
- [x] Done -- [Putrefy](https://scryfall.com/search?q=Putrefy)
- [x] Done -- [Rakdos Carnarium](https://scryfall.com/search?q=Rakdos+Carnarium)
- [x] Done -- [Rampaging Baloths](https://scryfall.com/search?q=Rampaging+Baloths)
- [x] Done -- [Ravenous Slime](https://scryfall.com/search?q=Ravenous+Slime)
- [x] Done -- [Reality Scramble](https://scryfall.com/search?q=Reality+Scramble)
- [x] Done -- [Reclamation Sage](https://scryfall.com/search?q=Reclamation+Sage)
- [x] Done -- [Retreat to Hagra](https://scryfall.com/search?q=Retreat+to+Hagra)
- [x] Done -- [Retrofitter Foundry](https://scryfall.com/search?q=Retrofitter+Foundry)
- [x] Done -- [Return to Dust](https://scryfall.com/search?q=Return+to+Dust)
- [x] Done -- [Reverse Engineer](https://scryfall.com/search?q=Reverse+Engineer)
- [x] Done -- [Righteous Authority](https://scryfall.com/search?q=Righteous+Authority)
- [x] Done -- [Rocky Tar Pit](https://scryfall.com/search?q=Rocky+Tar+Pit)
- [x] Done -- [Rubblehulk](https://scryfall.com/search?q=Rubblehulk)
- [x] Done -- [Ruinous Path](https://scryfall.com/search?q=Ruinous+Path)
- [x] Done -- [Sage's Reverie](https://scryfall.com/search?q=Sages+Reverie)
- [x] Done -- [Saheeli's Artistry](https://scryfall.com/search?q=Saheelis+Artistry)
- [x] Done -- [Saheeli's Directive](https://scryfall.com/search?q=Saheelis+Directive)
- [x] Done -- [Saheeli, the Gifted](https://scryfall.com/search?q=Saheeli,+the+Gifted)
- [x] Done -- [Sakura-Tribe Elder](https://scryfall.com/search?q=Sakura-Tribe+Elder)
- [x] Done -- [Savage Lands](https://scryfall.com/search?q=Savage+Lands)
- [x] Done -- [Savage Twister](https://scryfall.com/search?q=Savage+Twister)
- [x] Done -- [Scoured Barrens](https://scryfall.com/search?q=Scoured+Barrens)
- [x] Done -- [Scrabbling Claws](https://scryfall.com/search?q=Scrabbling+Claws)
- [x] Done -- [Scute Mob](https://scryfall.com/search?q=Scute+Mob)
- [x] Done -- [Scuttling Doom Engine](https://scryfall.com/search?q=Scuttling+Doom+Engine)
- [x] Done -- [Seaside Citadel](https://scryfall.com/search?q=Seaside+Citadel)
- [x] Done -- [Seat of the Synod](https://scryfall.com/search?q=Seat+of+the+Synod)
- [x] Done -- [Secluded Steppe](https://scryfall.com/search?q=Secluded+Steppe)
- [x] Done -- [Seer's Lantern](https://scryfall.com/search?q=Seers+Lantern)
- [x] Done -- [Seer's Sundial](https://scryfall.com/search?q=Seers+Sundial)
- [x] Done -- [Sejiri Refuge](https://scryfall.com/search?q=Sejiri+Refuge)
- [x] Done -- [Selesnya Sanctuary](https://scryfall.com/search?q=Selesnya+Sanctuary)
- [x] Done -- [Serra Avatar](https://scryfall.com/search?q=Serra+Avatar)
- [x] Done -- [Sharding Sphinx](https://scryfall.com/search?q=Sharding+Sphinx)
- [x] Done -- [Sigil of the Empty Throne](https://scryfall.com/search?q=Sigil+of+the+Empty+Throne)
- [x] Done -- [Sigiled Starfish](https://scryfall.com/search?q=Sigiled+Starfish)
- [x] Done -- [Silent Sentinel](https://scryfall.com/search?q=Silent+Sentinel)
- [x] Done -- [Silent-Blade Oni](https://scryfall.com/search?q=Silent-Blade+Oni)
- [x] Done -- [Simic Growth Chamber](https://scryfall.com/search?q=Simic+Growth+Chamber)
- [x] Done -- [Skull Storm](https://scryfall.com/search?q=Skull+Storm)
- [x] Done -- [Snake Umbra](https://scryfall.com/search?q=Snake+Umbra)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=Sol+Ring)
- [x] Done -- [Soul Snare](https://scryfall.com/search?q=Soul+Snare)
- [x] Done -- [Soul of Innistrad](https://scryfall.com/search?q=Soul+of+Innistrad)
- [x] Done -- [Soul of New Phyrexia](https://scryfall.com/search?q=Soul+of+New+Phyrexia)
- [x] Done -- [Sower of Discord](https://scryfall.com/search?q=Sower+of+Discord)
- [x] Done -- [Spawning Grounds](https://scryfall.com/search?q=Spawning+Grounds)
- [x] Done -- [Sphinx of Jwar Isle](https://scryfall.com/search?q=Sphinx+of+Jwar+Isle)
- [x] Done -- [Sphinx of Uthuun](https://scryfall.com/search?q=Sphinx+of+Uthuun)
- [x] Done -- [Steel Hellkite](https://scryfall.com/search?q=Steel+Hellkite)
- [x] Done -- [Stitch Together](https://scryfall.com/search?q=Stitch+Together)
- [x] Done -- [Submerged Boneyard](https://scryfall.com/search?q=Submerged+Boneyard)
- [x] Done -- [Swiftfoot Boots](https://scryfall.com/search?q=Swiftfoot+Boots)
- [x] Done -- [Swiftwater Cliffs](https://scryfall.com/search?q=Swiftwater+Cliffs)
- [x] Done -- [Tawnos, Urza's Apprentice](https://scryfall.com/search?q=Tawnos,+Urzas+Apprentice)
- [x] Done -- [Telling Time](https://scryfall.com/search?q=Telling+Time)
- [x] Done -- [Temple of the False God](https://scryfall.com/search?q=Temple+of+the+False+God)
- [x] Done -- [Terminus](https://scryfall.com/search?q=Terminus)
- [x] Done -- [Terramorphic Expanse](https://scryfall.com/search?q=Terramorphic+Expanse)
- [x] Done -- [Thantis, the Warweaver](https://scryfall.com/search?q=Thantis,+the+Warweaver)
- [x] Done -- [Thirst for Knowledge](https://scryfall.com/search?q=Thirst+for+Knowledge)
- [x] Done -- [Thopter Assembly](https://scryfall.com/search?q=Thopter+Assembly)
- [x] Done -- [Thopter Engineer](https://scryfall.com/search?q=Thopter+Engineer)
- [x] Done -- [Thopter Spy Network](https://scryfall.com/search?q=Thopter+Spy+Network)
- [x] Done -- [Thornwood Falls](https://scryfall.com/search?q=Thornwood+Falls)
- [x] Done -- [Tidings](https://scryfall.com/search?q=Tidings)
- [x] Done -- [Tranquil Cove](https://scryfall.com/search?q=Tranquil+Cove)
- [x] Done -- [Tranquil Expanse](https://scryfall.com/search?q=Tranquil+Expanse)
- [x] Done -- [Tranquil Thicket](https://scryfall.com/search?q=Tranquil+Thicket)
- [x] Done -- [Treasure Hunt](https://scryfall.com/search?q=Treasure+Hunt)
- [x] Done -- [Treasure Nabber](https://scryfall.com/search?q=Treasure+Nabber)
- [x] Done -- [Turntimber Sower](https://scryfall.com/search?q=Turntimber+Sower)
- [x] Done -- [Tuvasa the Sunlit](https://scryfall.com/search?q=Tuvasa+the+Sunlit)
- [x] Done -- [Unflinching Courage](https://scryfall.com/search?q=Unflinching+Courage)
- [x] Done -- [Unquestioned Authority](https://scryfall.com/search?q=Unquestioned+Authority)
- [x] Done -- [Unstable Obelisk](https://scryfall.com/search?q=Unstable+Obelisk)
- [x] Done -- [Unwinding Clock](https://scryfall.com/search?q=Unwinding+Clock)
- [x] Done -- [Utter End](https://scryfall.com/search?q=Utter+End)
- [x] Done -- [Varchild, Betrayer of Kjeldor](https://scryfall.com/search?q=Varchild,+Betrayer+of+Kjeldor)
- [x] Done -- [Varina, Lich Queen](https://scryfall.com/search?q=Varina,+Lich+Queen)
- [x] Done -- [Vedalken Humiliator](https://scryfall.com/search?q=Vedalken+Humiliator)
- [x] Done -- [Vessel of Endless Rest](https://scryfall.com/search?q=Vessel+of+Endless+Rest)
- [x] Done -- [Vow of Flight](https://scryfall.com/search?q=Vow+of+Flight)
- [x] Done -- [Vow of Wildness](https://scryfall.com/search?q=Vow+of+Wildness)
- [x] Done -- [Warped Landscape](https://scryfall.com/search?q=Warped+Landscape)
- [x] Done -- [Whiptongue Hydra](https://scryfall.com/search?q=Whiptongue+Hydra)
- [x] Done -- [Whirler Rogue](https://scryfall.com/search?q=Whirler+Rogue)
- [x] Done -- [Whitewater Naiads](https://scryfall.com/search?q=Whitewater+Naiads)
- [x] Done -- [Wild Growth](https://scryfall.com/search?q=Wild+Growth)
- [x] Done -- [Windgrace's Judgment](https://scryfall.com/search?q=Windgraces+Judgment)
- [x] Done -- [Winds of Rath](https://scryfall.com/search?q=Winds+of+Rath)
- [x] Done -- [Woodland Stream](https://scryfall.com/search?q=Woodland+Stream)
- [x] Done -- [Worm Harvest](https://scryfall.com/search?q=Worm+Harvest)
- [x] Done -- [Worn Powerstone](https://scryfall.com/search?q=Worn+Powerstone)
- [x] Done -- [Xantcha, Sleeper Agent](https://scryfall.com/search?q=Xantcha,+Sleeper+Agent)
- [x] Done -- [Yavimaya Elder](https://scryfall.com/search?q=Yavimaya+Elder)
- [x] Done -- [Yavimaya Enchantress](https://scryfall.com/search?q=Yavimaya+Enchantress)
- [x] Done -- [Yennett, Cryptic Sovereign](https://scryfall.com/search?q=Yennett,+Cryptic+Sovereign)
- [x] Done -- [Yuriko, the Tiger's Shadow](https://scryfall.com/search?q=Yuriko,+the+Tigers+Shadow)
- [x] Done -- [Zendikar Incarnate](https://scryfall.com/search?q=Zendikar+Incarnate)

**Comment by theelk801** [comment]
- [ ] In progress -- [Coveted Jewel](https://scryfall.com/search?q=Coveted+Jewel)
- [ ] In progress -- [Forge of Heroes](https://scryfall.com/search?q=Forge+of+Heroes)
- [ ] In progress -- [Geode Golem](https://scryfall.com/search?q=Geode+Golem)
- [ ] In progress -- [Retrofitter Foundry](https://scryfall.com/search?q=Retrofitter+Foundry)
- [ ] In progress -- [Saheeli's Directive](https://scryfall.com/search?q=Saheelis+Directive)
- [ ] In progress -- [Varchild, Betrayer of Kjeldor](https://scryfall.com/search?q=Varchild,+Betrayer+of+Kjeldor)

**Comment by credman0** [comment]
I am working on Amniatou, the Fateshifter.

**Comment by jesusjbr** [comment]
I am working on Xantcha, Sleeper Agent. I'll try my best for my first contribution.

**Comment by credman0** [comment]
I'm working on Emissary of Grudges

**Comment by spjspj** [comment]
Thanks to @theelk801 for all his hard work on getting the bulk of the cards done!  Also nice to see new contributors :)

**Comment by tamaroth** [comment]
@theelk801 Hey I've tested some of the new cards. I have noticed that `Tuvasa the Sunlit` is not working properly. Instead of drawing a card for only the first enchantment spell each turn, it draws for every enchantment instead.

I have tried looking at the code, but my Java and mage knowledge is limited and I could not figure out what was wrong.

**Comment by valdezzey** [comment]
Any idea on when the cards will be added to xmage?

**Comment by mzavaleta** [comment]
Hey guys, maybe not the best place to input this but, yesterday i just finally downloaded and setup the environment and tried to do a naive implementation of a card (yuriko) just to test it and i found out lost a bit because it's so huge.
I know there is a lot of information and also the code is understandable enough but anyway, is there anyone available to do some kind of pair or chat coaching in order to speed me up?

**Comment by jmharmon** [comment]
All of these cards are in the code. Has one one updated this list or what?

**Comment by theelk801** [comment]
Sorry, never got around to it.
