### ISSUE TITLE
INV - Invasion Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5224]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/invasion )

# Unimplemented Cards
50|[Crystal Spray](https://magiccards.info/query?q=!Crystal+Spray)

# Cards in set:
- [x] [Absorb](https://magiccards.info/query?q=!Absorb)
- [x] [Addle](https://magiccards.info/query?q=!Addle)
- [x] [Aether Rift](https://magiccards.info/query?q=!Aether+Rift)
- [x] [Aggressive Urge](https://magiccards.info/query?q=!Aggressive+Urge)
- [x] [Agonizing Demise](https://magiccards.info/query?q=!Agonizing+Demise)
- [x] [Alabaster Leech](https://magiccards.info/query?q=!Alabaster+Leech)
- [x] [Alloy Golem](https://magiccards.info/query?q=!Alloy+Golem)
- [x] [Ancient Kavu](https://magiccards.info/query?q=!Ancient+Kavu)
- [x] [Ancient Spring](https://magiccards.info/query?q=!Ancient+Spring)
- [x] [Andradite Leech](https://magiccards.info/query?q=!Andradite+Leech)
- [x] [Angel of Mercy](https://magiccards.info/query?q=!Angel+of+Mercy)
- [x] [Angelic Shield](https://magiccards.info/query?q=!Angelic+Shield)
- [x] [Annihilate](https://magiccards.info/query?q=!Annihilate)
- [x] [Archaeological Dig](https://magiccards.info/query?q=!Archaeological+Dig)
- [x] [Ardent Soldier](https://magiccards.info/query?q=!Ardent+Soldier)
- [x] [Armadillo Cloak](https://magiccards.info/query?q=!Armadillo+Cloak)
- [x] [Armored Guardian](https://magiccards.info/query?q=!Armored+Guardian)
- [x] [Artifact Mutation](https://magiccards.info/query?q=!Artifact+Mutation)
- [x] [Assault // Battery](https://magiccards.info/query?q=Assault/Battery)
- [x] [Atalya, Samite Master](https://magiccards.info/query?q=!Atalya,+Samite+Master)
- [x] [Aura Mutation](https://magiccards.info/query?q=!Aura+Mutation)
- [x] [Aura Shards](https://magiccards.info/query?q=!Aura+Shards)
- [x] [Backlash](https://magiccards.info/query?q=!Backlash)
- [x] [Barrin's Spite](https://magiccards.info/query?q=!Barrin's+Spite)
- [x] [Barrin's Unmaking](https://magiccards.info/query?q=!Barrin's+Unmaking)
- [x] [Benalish Emissary](https://magiccards.info/query?q=!Benalish+Emissary)
- [x] [Benalish Heralds](https://magiccards.info/query?q=!Benalish+Heralds)
- [x] [Benalish Lancer](https://magiccards.info/query?q=!Benalish+Lancer)
- [x] [Benalish Trapper](https://magiccards.info/query?q=!Benalish+Trapper)
- [x] [Bend or Break](https://magiccards.info/query?q=!Bend+or+Break)
- [x] [Bind](https://magiccards.info/query?q=!Bind)
- [x] [Blazing Specter](https://magiccards.info/query?q=!Blazing+Specter)
- [x] [Blind Seer](https://magiccards.info/query?q=!Blind+Seer)
- [x] [Blinding Light](https://magiccards.info/query?q=!Blinding+Light)
- [x] [Bloodstone Cameo](https://magiccards.info/query?q=!Bloodstone+Cameo)
- [x] [Blurred Mongoose](https://magiccards.info/query?q=!Blurred+Mongoose)
- [x] [Bog Initiate](https://magiccards.info/query?q=!Bog+Initiate)
- [x] [Breaking Wave](https://magiccards.info/query?q=!Breaking+Wave)
- [x] [Breath of Darigaaz](https://magiccards.info/query?q=!Breath+of+Darigaaz)
- [x] [Callous Giant](https://magiccards.info/query?q=!Callous+Giant)
- [x] [Canopy Surge](https://magiccards.info/query?q=!Canopy+Surge)
- [x] [Capashen Unicorn](https://magiccards.info/query?q=!Capashen+Unicorn)
- [x] [Captain Sisay](https://magiccards.info/query?q=!Captain+Sisay)
- [x] [Cauldron Dance](https://magiccards.info/query?q=!Cauldron+Dance)
- [x] [Chaotic Strike](https://magiccards.info/query?q=!Chaotic+Strike)
- [x] [Charging Troll](https://magiccards.info/query?q=!Charging+Troll)
- [x] [Chromatic Sphere](https://magiccards.info/query?q=!Chromatic+Sphere)
- [x] [Cinder Shade](https://magiccards.info/query?q=!Cinder+Shade)
- [x] [Coalition Victory](https://magiccards.info/query?q=!Coalition+Victory)
- [x] [Coastal Tower](https://magiccards.info/query?q=!Coastal+Tower)
- [x] [Collapsing Borders](https://magiccards.info/query?q=!Collapsing+Borders)
- [x] [Collective Restraint](https://magiccards.info/query?q=!Collective+Restraint)
- [x] [Cremate](https://magiccards.info/query?q=!Cremate)
- [x] [Crimson Acolyte](https://magiccards.info/query?q=!Crimson+Acolyte)
- [x] [Crosis's Attendant](https://magiccards.info/query?q=!Crosis's+Attendant)
- [x] [Crosis, the Purger](https://magiccards.info/query?q=!Crosis,+the+Purger)
- [x] [Crown of Flames](https://magiccards.info/query?q=!Crown+of+Flames)
- [x] [Crusading Knight](https://magiccards.info/query?q=!Crusading+Knight)
- [x] [Crypt Angel](https://magiccards.info/query?q=!Crypt+Angel)
- [ ] [Crystal Spray](https://magiccards.info/query?q=!Crystal+Spray)
- [x] [Cursed Flesh](https://magiccards.info/query?q=!Cursed+Flesh)
- [x] [Darigaaz's Attendant](https://magiccards.info/query?q=!Darigaaz's+Attendant)
- [x] [Darigaaz, the Igniter](https://magiccards.info/query?q=!Darigaaz,+the+Igniter)
- [x] [Death or Glory](https://magiccards.info/query?q=!Death+or+Glory)
- [x] [Defiling Tears](https://magiccards.info/query?q=!Defiling+Tears)
- [x] [Desperate Research](https://magiccards.info/query?q=!Desperate+Research)
- [x] [Devouring Strossus](https://magiccards.info/query?q=!Devouring+Strossus)
- [x] [Dismantling Blow](https://magiccards.info/query?q=!Dismantling+Blow)
- [x] [Disrupt](https://magiccards.info/query?q=!Disrupt)
- [x] [Distorting Wake](https://magiccards.info/query?q=!Distorting+Wake)
- [x] [Divine Presence](https://magiccards.info/query?q=!Divine+Presence)
- [x] [Do or Die](https://magiccards.info/query?q=!Do+or+Die)
- [x] [Drake-Skull Cameo](https://magiccards.info/query?q=!Drake-Skull+Cameo)
- [x] [Dream Thrush](https://magiccards.info/query?q=!Dream+Thrush)
- [x] [Dredge](https://magiccards.info/query?q=!Dredge)
- [x] [Dromar's Attendant](https://magiccards.info/query?q=!Dromar's+Attendant)
- [x] [Dromar, the Banisher](https://magiccards.info/query?q=!Dromar,+the+Banisher)
- [x] [Dueling Grounds](https://magiccards.info/query?q=!Dueling+Grounds)
- [x] [Duskwalker](https://magiccards.info/query?q=!Duskwalker)
- [x] [Elfhame Palace](https://magiccards.info/query?q=!Elfhame+Palace)
- [x] [Elfhame Sanctuary](https://magiccards.info/query?q=!Elfhame+Sanctuary)
- [x] [Elvish Champion](https://magiccards.info/query?q=!Elvish+Champion)
- [x] [Empress Galina](https://magiccards.info/query?q=!Empress+Galina)
- [x] [Essence Leak](https://magiccards.info/query?q=!Essence+Leak)
- [x] [Exclude](https://magiccards.info/query?q=!Exclude)
- [x] [Exotic Curse](https://magiccards.info/query?q=!Exotic+Curse)
- [x] [Explosive Growth](https://magiccards.info/query?q=!Explosive+Growth)
- [x] [Fact or Fiction](https://magiccards.info/query?q=!Fact+or+Fiction)
- [x] [Faerie Squadron](https://magiccards.info/query?q=!Faerie+Squadron)
- [x] [Fertile Ground](https://magiccards.info/query?q=!Fertile+Ground)
- [x] [Fight or Flight](https://magiccards.info/query?q=!Fight+or+Flight)
- [x] [Firebrand Ranger](https://magiccards.info/query?q=!Firebrand+Ranger)
- [x] [Fires of Yavimaya](https://magiccards.info/query?q=!Fires+of+Yavimaya)
- [x] [Firescreamer](https://magiccards.info/query?q=!Firescreamer)
- [x] [Forest](https://magiccards.info/query?q=!Forest)
- [x] [Frenzied Tilling](https://magiccards.info/query?q=!Frenzied+Tilling)
- [x] [Galina's Knight](https://magiccards.info/query?q=!Galina's+Knight)
- [x] [Geothermal Crevice](https://magiccards.info/query?q=!Geothermal+Crevice)
- [x] [Ghitu Fire](https://magiccards.info/query?q=!Ghitu+Fire)
- [x] [Glimmering Angel](https://magiccards.info/query?q=!Glimmering+Angel)
- [x] [Global Ruin](https://magiccards.info/query?q=!Global+Ruin)
- [x] [Goblin Spy](https://magiccards.info/query?q=!Goblin+Spy)
- [x] [Goham Djinn](https://magiccards.info/query?q=!Goham+Djinn)
- [x] [Halam Djinn](https://magiccards.info/query?q=!Halam+Djinn)
- [x] [Hanna, Ship's Navigator](https://magiccards.info/query?q=!Hanna,+Ship's+Navigator)
- [x] [Harrow](https://magiccards.info/query?q=!Harrow)
- [x] [Harsh Judgment](https://magiccards.info/query?q=!Harsh+Judgment)
- [x] [Hate Weaver](https://magiccards.info/query?q=!Hate+Weaver)
- [x] [Heroes' Reunion](https://magiccards.info/query?q=!Heroes'+Reunion)
- [x] [Holy Day](https://magiccards.info/query?q=!Holy+Day)
- [x] [Hooded Kavu](https://magiccards.info/query?q=!Hooded+Kavu)
- [x] [Horned Cheetah](https://magiccards.info/query?q=!Horned+Cheetah)
- [x] [Hunting Kavu](https://magiccards.info/query?q=!Hunting+Kavu)
- [x] [Hypnotic Cloud](https://magiccards.info/query?q=!Hypnotic+Cloud)
- [x] [Irrigation Ditch](https://magiccards.info/query?q=!Irrigation+Ditch)
- [x] [Island](https://magiccards.info/query?q=!Island)
- [x] [Jade Leech](https://magiccards.info/query?q=!Jade+Leech)
- [x] [Juntu Stakes](https://magiccards.info/query?q=!Juntu+Stakes)
- [x] [Kangee, Aerie Keeper](https://magiccards.info/query?q=!Kangee,+Aerie+Keeper)
- [x] [Kavu Aggressor](https://magiccards.info/query?q=!Kavu+Aggressor)
- [x] [Kavu Chameleon](https://magiccards.info/query?q=!Kavu+Chameleon)
- [x] [Kavu Climber](https://magiccards.info/query?q=!Kavu+Climber)
- [x] [Kavu Lair](https://magiccards.info/query?q=!Kavu+Lair)
- [x] [Kavu Monarch](https://magiccards.info/query?q=!Kavu+Monarch)
- [x] [Kavu Runner](https://magiccards.info/query?q=!Kavu+Runner)
- [x] [Kavu Scout](https://magiccards.info/query?q=!Kavu+Scout)
- [x] [Kavu Titan](https://magiccards.info/query?q=!Kavu+Titan)
- [x] [Keldon Necropolis](https://magiccards.info/query?q=!Keldon+Necropolis)
- [x] [Liberate](https://magiccards.info/query?q=!Liberate)
- [x] [Lightning Dart](https://magiccards.info/query?q=!Lightning+Dart)
- [x] [Llanowar Cavalry](https://magiccards.info/query?q=!Llanowar+Cavalry)
- [x] [Llanowar Elite](https://magiccards.info/query?q=!Llanowar+Elite)
- [x] [Llanowar Knight](https://magiccards.info/query?q=!Llanowar+Knight)
- [x] [Llanowar Vanguard](https://magiccards.info/query?q=!Llanowar+Vanguard)
- [x] [Loafing Giant](https://magiccards.info/query?q=!Loafing+Giant)
- [x] [Lobotomy](https://magiccards.info/query?q=!Lobotomy)
- [x] [Lotus Guardian](https://magiccards.info/query?q=!Lotus+Guardian)
- [x] [Mages' Contest](https://magiccards.info/query?q=!Mages'+Contest)
- [x] [Mana Maze](https://magiccards.info/query?q=!Mana+Maze)
- [x] [Maniacal Rage](https://magiccards.info/query?q=!Maniacal+Rage)
- [x] [Manipulate Fate](https://magiccards.info/query?q=!Manipulate+Fate)
- [x] [Marauding Knight](https://magiccards.info/query?q=!Marauding+Knight)
- [x] [Metathran Aerostat](https://magiccards.info/query?q=!Metathran+Aerostat)
- [x] [Metathran Transport](https://magiccards.info/query?q=!Metathran+Transport)
- [x] [Metathran Zombie](https://magiccards.info/query?q=!Metathran+Zombie)
- [x] [Meteor Storm](https://magiccards.info/query?q=!Meteor+Storm)
- [x] [Might Weaver](https://magiccards.info/query?q=!Might+Weaver)
- [x] [Molimo, Maro-Sorcerer](https://magiccards.info/query?q=!Molimo,+Maro-Sorcerer)
- [x] [Mountain](https://magiccards.info/query?q=!Mountain)
- [x] [Mourning](https://magiccards.info/query?q=!Mourning)
- [x] [Nightscape Apprentice](https://magiccards.info/query?q=!Nightscape+Apprentice)
- [x] [Nightscape Master](https://magiccards.info/query?q=!Nightscape+Master)
- [x] [Noble Panther](https://magiccards.info/query?q=!Noble+Panther)
- [x] [Nomadic Elf](https://magiccards.info/query?q=!Nomadic+Elf)
- [x] [Obliterate](https://magiccards.info/query?q=!Obliterate)
- [x] [Obsidian Acolyte](https://magiccards.info/query?q=!Obsidian+Acolyte)
- [x] [Opt](https://magiccards.info/query?q=!Opt)
- [x] [Ordered Migration](https://magiccards.info/query?q=!Ordered+Migration)
- [x] [Orim's Touch](https://magiccards.info/query?q=!Orim's+Touch)
- [x] [Overabundance](https://magiccards.info/query?q=!Overabundance)
- [x] [Overload](https://magiccards.info/query?q=!Overload)
- [x] [Pain // Suffering](https://magiccards.info/query?q=Pain/Suffering)
- [x] [Phantasmal Terrain](https://magiccards.info/query?q=!Phantasmal+Terrain)
- [x] [Phyrexian Altar](https://magiccards.info/query?q=!Phyrexian+Altar)
- [x] [Phyrexian Battleflies](https://magiccards.info/query?q=!Phyrexian+Battleflies)
- [x] [Phyrexian Delver](https://magiccards.info/query?q=!Phyrexian+Delver)
- [x] [Phyrexian Infiltrator](https://magiccards.info/query?q=!Phyrexian+Infiltrator)
- [x] [Phyrexian Lens](https://magiccards.info/query?q=!Phyrexian+Lens)
- [x] [Phyrexian Reaper](https://magiccards.info/query?q=!Phyrexian+Reaper)
- [x] [Phyrexian Slayer](https://magiccards.info/query?q=!Phyrexian+Slayer)
- [x] [Pincer Spider](https://magiccards.info/query?q=!Pincer+Spider)
- [x] [Plague Spitter](https://magiccards.info/query?q=!Plague+Spitter)
- [x] [Plague Spores](https://magiccards.info/query?q=!Plague+Spores)
- [x] [Plains](https://magiccards.info/query?q=!Plains)
- [x] [Planar Portal](https://magiccards.info/query?q=!Planar+Portal)
- [x] [Pledge of Loyalty](https://magiccards.info/query?q=!Pledge+of+Loyalty)
- [x] [Pouncing Kavu](https://magiccards.info/query?q=!Pouncing+Kavu)
- [x] [Power Armor](https://magiccards.info/query?q=!Power+Armor)
- [x] [Prison Barricade](https://magiccards.info/query?q=!Prison+Barricade)
- [x] [Probe](https://magiccards.info/query?q=!Probe)
- [x] [Prohibit](https://magiccards.info/query?q=!Prohibit)
- [x] [Protective Sphere](https://magiccards.info/query?q=!Protective+Sphere)
- [x] [Psychic Battle](https://magiccards.info/query?q=!Psychic+Battle)
- [x] [Pulse of Llanowar](https://magiccards.info/query?q=!Pulse+of+Llanowar)
- [x] [Pure Reflection](https://magiccards.info/query?q=!Pure+Reflection)
- [x] [Pyre Zombie](https://magiccards.info/query?q=!Pyre+Zombie)
- [x] [Quirion Elves](https://magiccards.info/query?q=!Quirion+Elves)
- [x] [Quirion Sentinel](https://magiccards.info/query?q=!Quirion+Sentinel)
- [x] [Quirion Trailblazer](https://magiccards.info/query?q=!Quirion+Trailblazer)
- [x] [Rage Weaver](https://magiccards.info/query?q=!Rage+Weaver)
- [x] [Raging Kavu](https://magiccards.info/query?q=!Raging+Kavu)
- [x] [Rainbow Crow](https://magiccards.info/query?q=!Rainbow+Crow)
- [x] [Rampant Elephant](https://magiccards.info/query?q=!Rampant+Elephant)
- [x] [Ravenous Rats](https://magiccards.info/query?q=!Ravenous+Rats)
- [x] [Razorfoot Griffin](https://magiccards.info/query?q=!Razorfoot+Griffin)
- [x] [Reckless Assault](https://magiccards.info/query?q=!Reckless+Assault)
- [x] [Reckless Spite](https://magiccards.info/query?q=!Reckless+Spite)
- [x] [Recoil](https://magiccards.info/query?q=!Recoil)
- [x] [Recover](https://magiccards.info/query?q=!Recover)
- [x] [Repulse](https://magiccards.info/query?q=!Repulse)
- [x] [Restock](https://magiccards.info/query?q=!Restock)
- [x] [Restrain](https://magiccards.info/query?q=!Restrain)
- [x] [Reviving Dose](https://magiccards.info/query?q=!Reviving+Dose)
- [x] [Reviving Vapors](https://magiccards.info/query?q=!Reviving+Vapors)
- [x] [Rewards of Diversity](https://magiccards.info/query?q=!Rewards+of+Diversity)
- [x] [Reya Dawnbringer](https://magiccards.info/query?q=!Reya+Dawnbringer)
- [x] [Riptide Crab](https://magiccards.info/query?q=!Riptide+Crab)
- [x] [Rith's Attendant](https://magiccards.info/query?q=!Rith's+Attendant)
- [x] [Rith, the Awakener](https://magiccards.info/query?q=!Rith,+the+Awakener)
- [x] [Rogue Kavu](https://magiccards.info/query?q=!Rogue+Kavu)
- [x] [Rooting Kavu](https://magiccards.info/query?q=!Rooting+Kavu)
- [x] [Rout](https://magiccards.info/query?q=!Rout)
- [x] [Ruby Leech](https://magiccards.info/query?q=!Ruby+Leech)
- [x] [Ruham Djinn](https://magiccards.info/query?q=!Ruham+Djinn)
- [x] [Sabertooth Nishoba](https://magiccards.info/query?q=!Sabertooth+Nishoba)
- [x] [Salt Marsh](https://magiccards.info/query?q=!Salt+Marsh)
- [x] [Samite Archer](https://magiccards.info/query?q=!Samite+Archer)
- [x] [Samite Ministration](https://magiccards.info/query?q=!Samite+Ministration)
- [x] [Sapphire Leech](https://magiccards.info/query?q=!Sapphire+Leech)
- [x] [Saproling Infestation](https://magiccards.info/query?q=!Saproling+Infestation)
- [x] [Saproling Symbiosis](https://magiccards.info/query?q=!Saproling+Symbiosis)
- [x] [Savage Offensive](https://magiccards.info/query?q=!Savage+Offensive)
- [x] [Scarred Puma](https://magiccards.info/query?q=!Scarred+Puma)
- [x] [Scavenged Weaponry](https://magiccards.info/query?q=!Scavenged+Weaponry)
- [x] [Scorching Lava](https://magiccards.info/query?q=!Scorching+Lava)
- [x] [Scouting Trek](https://magiccards.info/query?q=!Scouting+Trek)
- [x] [Searing Rays](https://magiccards.info/query?q=!Searing+Rays)
- [x] [Seashell Cameo](https://magiccards.info/query?q=!Seashell+Cameo)
- [x] [Seer's Vision](https://magiccards.info/query?q=!Seer's+Vision)
- [x] [Serpentine Kavu](https://magiccards.info/query?q=!Serpentine+Kavu)
- [x] [Shackles](https://magiccards.info/query?q=!Shackles)
- [x] [Shimmering Wings](https://magiccards.info/query?q=!Shimmering+Wings)
- [x] [Shivan Emissary](https://magiccards.info/query?q=!Shivan+Emissary)
- [x] [Shivan Harvest](https://magiccards.info/query?q=!Shivan+Harvest)
- [x] [Shivan Oasis](https://magiccards.info/query?q=!Shivan+Oasis)
- [x] [Shivan Zombie](https://magiccards.info/query?q=!Shivan+Zombie)
- [x] [Shoreline Raider](https://magiccards.info/query?q=!Shoreline+Raider)
- [x] [Simoon](https://magiccards.info/query?q=!Simoon)
- [x] [Skittish Kavu](https://magiccards.info/query?q=!Skittish+Kavu)
- [x] [Skizzik](https://magiccards.info/query?q=!Skizzik)
- [x] [Sky Weaver](https://magiccards.info/query?q=!Sky+Weaver)
- [x] [Sleeper's Robe](https://magiccards.info/query?q=!Sleeper's+Robe)
- [x] [Slimy Kavu](https://magiccards.info/query?q=!Slimy+Kavu)
- [x] [Slinking Serpent](https://magiccards.info/query?q=!Slinking+Serpent)
- [x] [Smoldering Tar](https://magiccards.info/query?q=!Smoldering+Tar)
- [x] [Soul Burn](https://magiccards.info/query?q=!Soul+Burn)
- [x] [Sparring Golem](https://magiccards.info/query?q=!Sparring+Golem)
- [x] [Spinal Embrace](https://magiccards.info/query?q=!Spinal+Embrace)
- [x] [Spirit Weaver](https://magiccards.info/query?q=!Spirit+Weaver)
- [x] [Spirit of Resistance](https://magiccards.info/query?q=!Spirit+of+Resistance)
- [x] [Spite // Malice](https://magiccards.info/query?q=Spite/Malice)
- [x] [Spreading Plague](https://magiccards.info/query?q=!Spreading+Plague)
- [x] [Stalking Assassin](https://magiccards.info/query?q=!Stalking+Assassin)
- [x] [Stand // Deliver](https://magiccards.info/query?q=Stand/Delver)
- [x] [Stand or Fall](https://magiccards.info/query?q=!Stand+or+Fall)
- [x] [Sterling Grove](https://magiccards.info/query?q=!Sterling+Grove)
- [x] [Stormscape Apprentice](https://magiccards.info/query?q=!Stormscape+Apprentice)
- [x] [Stormscape Master](https://magiccards.info/query?q=!Stormscape+Master)
- [x] [Strength of Unity](https://magiccards.info/query?q=!Strength+of+Unity)
- [x] [Stun](https://magiccards.info/query?q=!Stun)
- [x] [Sulam Djinn](https://magiccards.info/query?q=!Sulam+Djinn)
- [x] [Sulfur Vent](https://magiccards.info/query?q=!Sulfur+Vent)
- [x] [Sunscape Apprentice](https://magiccards.info/query?q=!Sunscape+Apprentice)
- [x] [Sunscape Master](https://magiccards.info/query?q=!Sunscape+Master)
- [x] [Swamp](https://magiccards.info/query?q=!Swamp)
- [x] [Sway of Illusion](https://magiccards.info/query?q=!Sway+of+Illusion)
- [x] [Tainted Well](https://magiccards.info/query?q=!Tainted+Well)
- [x] [Tangle](https://magiccards.info/query?q=!Tangle)
- [x] [Tectonic Instability](https://magiccards.info/query?q=!Tectonic+Instability)
- [x] [Teferi's Care](https://magiccards.info/query?q=!Teferi's+Care)
- [x] [Teferi's Moat](https://magiccards.info/query?q=!Teferi's+Moat)
- [x] [Teferi's Response](https://magiccards.info/query?q=!Teferi's+Response)
- [x] [Tek](https://magiccards.info/query?q=!Tek)
- [x] [Temporal Distortion](https://magiccards.info/query?q=!Temporal+Distortion)
- [x] [Thicket Elemental](https://magiccards.info/query?q=!Thicket+Elemental)
- [x] [Thornscape Apprentice](https://magiccards.info/query?q=!Thornscape+Apprentice)
- [x] [Thornscape Master](https://magiccards.info/query?q=!Thornscape+Master)
- [x] [Thunderscape Apprentice](https://magiccards.info/query?q=!Thunderscape+Apprentice)
- [x] [Thunderscape Master](https://magiccards.info/query?q=!Thunderscape+Master)
- [x] [Tidal Visionary](https://magiccards.info/query?q=!Tidal+Visionary)
- [x] [Tigereye Cameo](https://magiccards.info/query?q=!Tigereye+Cameo)
- [x] [Tinder Farm](https://magiccards.info/query?q=!Tinder+Farm)
- [x] [Tolarian Emissary](https://magiccards.info/query?q=!Tolarian+Emissary)
- [x] [Tower Drake](https://magiccards.info/query?q=!Tower+Drake)
- [x] [Tranquility](https://magiccards.info/query?q=!Tranquility)
- [x] [Traveler's Cloak](https://magiccards.info/query?q=!Traveler's+Cloak)
- [x] [Treefolk Healer](https://magiccards.info/query?q=!Treefolk+Healer)
- [x] [Trench Wurm](https://magiccards.info/query?q=!Trench+Wurm)
- [x] [Treva's Attendant](https://magiccards.info/query?q=!Treva's+Attendant)
- [x] [Treva, the Renewer](https://magiccards.info/query?q=!Treva,+the+Renewer)
- [x] [Tribal Flames](https://magiccards.info/query?q=!Tribal+Flames)
- [x] [Troll-Horn Cameo](https://magiccards.info/query?q=!Troll-Horn+Cameo)
- [x] [Tsabo Tavoc](https://magiccards.info/query?q=!Tsabo+Tavoc)
- [x] [Tsabo's Assassin](https://magiccards.info/query?q=!Tsabo's+Assassin)
- [x] [Tsabo's Decree](https://magiccards.info/query?q=!Tsabo's+Decree)
- [x] [Tsabo's Web](https://magiccards.info/query?q=!Tsabo's+Web)
- [x] [Turf Wound](https://magiccards.info/query?q=!Turf+Wound)
- [x] [Twilight's Call](https://magiccards.info/query?q=!Twilight's+Call)
- [x] [Undermine](https://magiccards.info/query?q=!Undermine)
- [x] [Urborg Drake](https://magiccards.info/query?q=!Urborg+Drake)
- [x] [Urborg Emissary](https://magiccards.info/query?q=!Urborg+Emissary)
- [x] [Urborg Phantom](https://magiccards.info/query?q=!Urborg+Phantom)
- [x] [Urborg Shambler](https://magiccards.info/query?q=!Urborg+Shambler)
- [x] [Urborg Skeleton](https://magiccards.info/query?q=!Urborg+Skeleton)
- [x] [Urborg Volcano](https://magiccards.info/query?q=!Urborg+Volcano)
- [x] [Urza's Filter](https://magiccards.info/query?q=!Urza's+Filter)
- [x] [Urza's Rage](https://magiccards.info/query?q=!Urza's+Rage)
- [x] [Utopia Tree](https://magiccards.info/query?q=!Utopia+Tree)
- [x] [Verdeloth the Ancient](https://magiccards.info/query?q=!Verdeloth+the+Ancient)
- [x] [Verduran Emissary](https://magiccards.info/query?q=!Verduran+Emissary)
- [x] [Viashino Grappler](https://magiccards.info/query?q=!Viashino+Grappler)
- [x] [Vicious Kavu](https://magiccards.info/query?q=!Vicious+Kavu)
- [x] [Vigorous Charge](https://magiccards.info/query?q=!Vigorous+Charge)
- [x] [Vile Consumption](https://magiccards.info/query?q=!Vile+Consumption)
- [x] [Vodalian Hypnotist](https://magiccards.info/query?q=!Vodalian+Hypnotist)
- [x] [Vodalian Merchant](https://magiccards.info/query?q=!Vodalian+Merchant)
- [x] [Vodalian Serpent](https://magiccards.info/query?q=!Vodalian+Serpent)
- [x] [Vodalian Zombie](https://magiccards.info/query?q=!Vodalian+Zombie)
- [x] [Void](https://magiccards.info/query?q=!Void)
- [x] [Voracious Cobra](https://magiccards.info/query?q=!Voracious+Cobra)
- [x] [Wallop](https://magiccards.info/query?q=!Wallop)
- [x] [Wandering Stream](https://magiccards.info/query?q=!Wandering+Stream)
- [x] [Wash Out](https://magiccards.info/query?q=!Wash+Out)
- [x] [Wax // Wane](https://magiccards.info/query?q=Wax/Wane)
- [x] [Wayfaring Giant](https://magiccards.info/query?q=!Wayfaring+Giant)
- [x] [Well-Laid Plans](https://magiccards.info/query?q=!Well-Laid+Plans)
- [x] [Whip Silk](https://magiccards.info/query?q=!Whip+Silk)
- [x] [Wings of Hope](https://magiccards.info/query?q=!Wings+of+Hope)
- [x] [Winnow](https://magiccards.info/query?q=!Winnow)
- [x] [Worldly Counsel](https://magiccards.info/query?q=!Worldly+Counsel)
- [x] [Yavimaya Barbarian](https://magiccards.info/query?q=!Yavimaya+Barbarian)
- [x] [Yavimaya Kavu](https://magiccards.info/query?q=!Yavimaya+Kavu)
- [x] [Yawgmoth's Agenda](https://magiccards.info/query?q=!Yawgmoth's+Agenda)
- [x] [Zanam Djinn](https://magiccards.info/query?q=!Zanam+Djinn)
- [x] [Zap](https://magiccards.info/query?q=!Zap)

**Comment by xenohedron** [comment]
Dueling Grounds reworked in e1ed85e

**Comment by xenohedron** [comment]
All implemented except text changing effects per #2082
