### ISSUE TITLE
PLS - Planeshift Set Card Implementation Tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5227]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/planeshift)

# Unimplemented Cards

4|[Dominaria's Judgment](https://magiccards.info/query?q=!Dominaria's+Judgment)
5|[Guard Dogs](https://magiccards.info/query?q=!Guard+Dogs)
49|[Noxious Vapors](https://magiccards.info/query?q=!Noxious+Vapors)
78|[Amphibious Kavu](https://magiccards.info/query?q=!Amphibious+Kavu)
83|[Mirrorwood Treefolk](https://magiccards.info/query?q=!Mirrorwood+Treefolk)

# Cards in set:
- [x] [Allied Strategies](https://magiccards.info/query?q=!Allied+Strategies)
- [x] [Alpha Kavu](https://magiccards.info/query?q=!Alpha+Kavu)
- [x] [Amphibious Kavu](https://magiccards.info/query?q=!Amphibious+Kavu)
- [x] [Ancient Spider](https://magiccards.info/query?q=!Ancient+Spider)
- [x] [Arctic Merfolk](https://magiccards.info/query?q=!Arctic+Merfolk)
- [x] [Aura Blast](https://magiccards.info/query?q=!Aura+Blast)
- [x] [Aurora Griffin](https://magiccards.info/query?q=!Aurora+Griffin)
- [x] [Bog Down](https://magiccards.info/query?q=!Bog+Down)
- [x] [Caldera Kavu](https://magiccards.info/query?q=!Caldera+Kavu)
- [x] [Cavern Harpy](https://magiccards.info/query?q=!Cavern+Harpy)
- [x] [Cloud Cover](https://magiccards.info/query?q=!Cloud+Cover)
- [x] [Confound](https://magiccards.info/query?q=!Confound)
- [x] [Crosis's Catacombs](https://magiccards.info/query?q=!Crosis's+Catacombs)
- [x] [Crosis's Charm](https://magiccards.info/query?q=!Crosis's+Charm)
- [x] [Darigaaz's Caldera](https://magiccards.info/query?q=!Darigaaz's+Caldera)
- [x] [Darigaaz's Charm](https://magiccards.info/query?q=!Darigaaz's+Charm)
- [x] [Daring Leap](https://magiccards.info/query?q=!Daring+Leap)
- [x] [Dark Suspicions](https://magiccards.info/query?q=!Dark+Suspicions)
- [x] [Deadapult](https://magiccards.info/query?q=!Deadapult)
- [x] [Death Bomb](https://magiccards.info/query?q=!Death+Bomb)
- [x] [Destructive Flow](https://magiccards.info/query?q=!Destructive+Flow)
- [x] [Diabolic Intent](https://magiccards.info/query?q=!Diabolic+Intent)
- [x] [Disciple of Kangee](https://magiccards.info/query?q=!Disciple+of+Kangee)
- [x] [Dominaria's Judgment](https://magiccards.info/query?q=!Dominaria's+Judgment)
- [x] [Doomsday Specter](https://magiccards.info/query?q=!Doomsday+Specter)
- [x] [Draco](https://magiccards.info/query?q=!Draco)
- [x] [Dralnu's Crusade](https://magiccards.info/query?q=!Dralnu's+Crusade)
- [x] [Dralnu's Pet](https://magiccards.info/query?q=!Dralnu's+Pet)
- [x] [Dromar's Cavern](https://magiccards.info/query?q=!Dromar's+Cavern)
- [x] [Dromar's Charm](https://magiccards.info/query?q=!Dromar's+Charm)
- [x] [Eladamri's Call](https://magiccards.info/query?q=!Eladamri's+Call)
- [x] [Ertai's Trickery](https://magiccards.info/query?q=!Ertai's+Trickery)
- [x] [Ertai, the Corrupted](https://magiccards.info/query?q=!Ertai,+the+Corrupted)
- [x] [Escape Routes](https://magiccards.info/query?q=!Escape+Routes)
- [x] [Exotic Disease](https://magiccards.info/query?q=!Exotic+Disease)
- [x] [Falling Timber](https://magiccards.info/query?q=!Falling+Timber)
- [x] [Flametongue Kavu](https://magiccards.info/query?q=!Flametongue+Kavu)
- [x] [Fleetfoot Panther](https://magiccards.info/query?q=!Fleetfoot+Panther)
- [x] [Forsaken City](https://magiccards.info/query?q=!Forsaken+City)
- [x] [Gaea's Herald](https://magiccards.info/query?q=!Gaea's+Herald)
- [x] [Gaea's Might](https://magiccards.info/query?q=!Gaea's+Might)
- [x] [Gainsay](https://magiccards.info/query?q=!Gainsay)
- [x] [Gerrard's Command](https://magiccards.info/query?q=!Gerrard's+Command)
- [x] [Goblin Game](https://magiccards.info/query?q=!Goblin+Game)
- [x] [Guard Dogs](https://magiccards.info/query?q=!Guard+Dogs)
- [x] [Heroic Defiance](https://magiccards.info/query?q=!Heroic+Defiance)
- [x] [Hobble](https://magiccards.info/query?q=!Hobble)
- [x] [Honorable Scout](https://magiccards.info/query?q=!Honorable+Scout)
- [x] [Horned Kavu](https://magiccards.info/query?q=!Horned+Kavu)
- [x] [Hull Breach](https://magiccards.info/query?q=!Hull+Breach)
- [x] [Hunting Drake](https://magiccards.info/query?q=!Hunting+Drake)
- [x] [Implode](https://magiccards.info/query?q=!Implode)
- [x] [Insolence](https://magiccards.info/query?q=!Insolence)
- [x] [Kavu Recluse](https://magiccards.info/query?q=!Kavu+Recluse)
- [x] [Keldon Mantle](https://magiccards.info/query?q=!Keldon+Mantle)
- [x] [Keldon Twilight](https://magiccards.info/query?q=!Keldon+Twilight)
- [x] [Lashknife Barrier](https://magiccards.info/query?q=!Lashknife+Barrier)
- [x] [Lava Zombie](https://magiccards.info/query?q=!Lava+Zombie)
- [x] [Lord of the Undead](https://magiccards.info/query?q=!Lord+of+the+Undead)
- [x] [Maggot Carrier](https://magiccards.info/query?q=!Maggot+Carrier)
- [x] [Magma Burst](https://magiccards.info/query?q=!Magma+Burst)
- [x] [Magnigoth Treefolk](https://magiccards.info/query?q=!Magnigoth+Treefolk)
- [x] [Malicious Advice](https://magiccards.info/query?q=!Malicious+Advice)
- [x] [Mana Cylix](https://magiccards.info/query?q=!Mana+Cylix)
- [x] [March of Souls](https://magiccards.info/query?q=!March+of+Souls)
- [x] [Marsh Crocodile](https://magiccards.info/query?q=!Marsh+Crocodile)
- [x] [Meddling Mage](https://magiccards.info/query?q=!Meddling+Mage)
- [x] [Meteor Crater](https://magiccards.info/query?q=!Meteor+Crater)
- [x] [Mire Kavu](https://magiccards.info/query?q=!Mire+Kavu)
- [x] [Mirrorwood Treefolk](https://magiccards.info/query?q=!Mirrorwood+Treefolk)
- [x] [Mogg Jailer](https://magiccards.info/query?q=!Mogg+Jailer)
- [x] [Mogg Sentry](https://magiccards.info/query?q=!Mogg+Sentry)
- [x] [Morgue Toad](https://magiccards.info/query?q=!Morgue+Toad)
- [x] [Multani's Harmony](https://magiccards.info/query?q=!Multani's+Harmony)
- [x] [Natural Emergence](https://magiccards.info/query?q=!Natural+Emergence)
- [x] [Nemata, Grove Guardian](https://magiccards.info/query?q=!Nemata,+Grove+Guardian)
- [x] [Nightscape Battlemage](https://magiccards.info/query?q=!Nightscape+Battlemage)
- [x] [Nightscape Familiar](https://magiccards.info/query?q=!Nightscape+Familiar)
- [x] [Noxious Vapors](https://magiccards.info/query?q=!Noxious+Vapors)
- [x] [Orim's Chant](https://magiccards.info/query?q=!Orim's+Chant)
- [x] [Phyrexian Bloodstock](https://magiccards.info/query?q=!Phyrexian+Bloodstock)
- [x] [Phyrexian Scuta](https://magiccards.info/query?q=!Phyrexian+Scuta)
- [x] [Phyrexian Tyranny](https://magiccards.info/query?q=!Phyrexian+Tyranny)
- [x] [Planar Overlay](https://magiccards.info/query?q=!Planar+Overlay)
- [x] [Planeswalker's Favor](https://magiccards.info/query?q=!Planeswalker's+Favor)
- [x] [Planeswalker's Fury](https://magiccards.info/query?q=!Planeswalker's+Fury)
- [x] [Planeswalker's Mirth](https://magiccards.info/query?q=!Planeswalker's+Mirth)
- [x] [Planeswalker's Mischief](https://magiccards.info/query?q=!Planeswalker's+Mischief)
- [x] [Planeswalker's Scorn](https://magiccards.info/query?q=!Planeswalker's+Scorn)
- [x] [Pollen Remedy](https://magiccards.info/query?q=!Pollen+Remedy)
- [x] [Primal Growth](https://magiccards.info/query?q=!Primal+Growth)
- [x] [Pygmy Kavu](https://magiccards.info/query?q=!Pygmy+Kavu)
- [x] [Questing Phelddagrif](https://magiccards.info/query?q=!Questing+Phelddagrif)
- [x] [Quirion Dryad](https://magiccards.info/query?q=!Quirion+Dryad)
- [x] [Quirion Explorer](https://magiccards.info/query?q=!Quirion+Explorer)
- [x] [Radiant Kavu](https://magiccards.info/query?q=!Radiant+Kavu)
- [x] [Razing Snidd](https://magiccards.info/query?q=!Razing+Snidd)
- [x] [Rith's Charm](https://magiccards.info/query?q=!Rith's+Charm)
- [x] [Rith's Grove](https://magiccards.info/query?q=!Rith's+Grove)
- [x] [Root Greevil](https://magiccards.info/query?q=!Root+Greevil)
- [x] [Rushing River](https://magiccards.info/query?q=!Rushing+River)
- [x] [Samite Elder](https://magiccards.info/query?q=!Samite+Elder)
- [x] [Samite Pilgrim](https://magiccards.info/query?q=!Samite+Pilgrim)
- [x] [Sawtooth Loon](https://magiccards.info/query?q=!Sawtooth+Loon)
- [x] [Sea Snidd](https://magiccards.info/query?q=!Sea+Snidd)
- [x] [Shifting Sky](https://magiccards.info/query?q=!Shifting+Sky)
- [x] [Shivan Wurm](https://magiccards.info/query?q=!Shivan+Wurm)
- [x] [Shriek of Dread](https://magiccards.info/query?q=!Shriek+of+Dread)
- [x] [Silver Drake](https://magiccards.info/query?q=!Silver+Drake)
- [x] [Singe](https://magiccards.info/query?q=!Singe)
- [x] [Sinister Strength](https://magiccards.info/query?q=!Sinister+Strength)
- [x] [Sisay's Ingenuity](https://magiccards.info/query?q=!Sisay's+Ingenuity)
- [x] [Skyship Weatherlight](https://magiccards.info/query?q=!Skyship+Weatherlight)
- [x] [Skyshroud Blessing](https://magiccards.info/query?q=!Skyshroud+Blessing)
- [x] [Slay](https://magiccards.info/query?q=!Slay)
- [x] [Sleeping Potion](https://magiccards.info/query?q=!Sleeping+Potion)
- [x] [Slingshot Goblin](https://magiccards.info/query?q=!Slingshot+Goblin)
- [x] [Sparkcaster](https://magiccards.info/query?q=!Sparkcaster)
- [x] [Star Compass](https://magiccards.info/query?q=!Star+Compass)
- [x] [Steel Leaf Paladin](https://magiccards.info/query?q=!Steel+Leaf+Paladin)
- [x] [Stone Kavu](https://magiccards.info/query?q=!Stone+Kavu)
- [x] [Stormscape Battlemage](https://magiccards.info/query?q=!Stormscape+Battlemage)
- [x] [Stormscape Familiar](https://magiccards.info/query?q=!Stormscape+Familiar)
- [x] [Strafe](https://magiccards.info/query?q=!Strafe)
- [x] [Stratadon](https://magiccards.info/query?q=!Stratadon)
- [x] [Sunken Hope](https://magiccards.info/query?q=!Sunken+Hope)
- [x] [Sunscape Battlemage](https://magiccards.info/query?q=!Sunscape+Battlemage)
- [x] [Sunscape Familiar](https://magiccards.info/query?q=!Sunscape+Familiar)
- [x] [Surprise Deployment](https://magiccards.info/query?q=!Surprise+Deployment)
- [x] [Tahngarth, Talruum Hero](https://magiccards.info/query?q=!Tahngarth,+Talruum+Hero)
- [x] [Terminal Moraine](https://magiccards.info/query?q=!Terminal+Moraine)
- [x] [Terminate](https://magiccards.info/query?q=!Terminate)
- [x] [Thornscape Battlemage](https://magiccards.info/query?q=!Thornscape+Battlemage)
- [x] [Thornscape Familiar](https://magiccards.info/query?q=!Thornscape+Familiar)
- [x] [Thunderscape Battlemage](https://magiccards.info/query?q=!Thunderscape+Battlemage)
- [x] [Thunderscape Familiar](https://magiccards.info/query?q=!Thunderscape+Familiar)
- [x] [Treva's Charm](https://magiccards.info/query?q=!Treva's+Charm)
- [x] [Treva's Ruins](https://magiccards.info/query?q=!Treva's+Ruins)
- [x] [Urza's Guilt](https://magiccards.info/query?q=!Urza's+Guilt)
- [x] [Voice of All](https://magiccards.info/query?q=!Voice+of+All)
- [x] [Volcano Imp](https://magiccards.info/query?q=!Volcano+Imp)
- [x] [Warped Devotion](https://magiccards.info/query?q=!Warped+Devotion)
- [x] [Waterspout Elemental](https://magiccards.info/query?q=!Waterspout+Elemental)
