### ISSUE TITLE
APC - Apocalypse Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5228]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/apocalypse)

# Unimplemented Cards

10|[False Dawn](https://magiccards.info/query?q=!False+Dawn)

# Cards in set:
- [x] [Aether Mutation](https://magiccards.info/query?q=!Aether+Mutation)
- [x] [Ana Disciple](https://magiccards.info/query?q=!Ana+Disciple)
- [x] [Ana Sanctuary](https://magiccards.info/query?q=!Ana+Sanctuary)
- [x] [Anavolver](https://magiccards.info/query?q=!Anavolver)
- [x] [Angelfire Crusader](https://magiccards.info/query?q=!Angelfire+Crusader)
- [x] [Battlefield Forge](https://magiccards.info/query?q=!Battlefield+Forge)
- [x] [Bloodfire Colossus](https://magiccards.info/query?q=!Bloodfire+Colossus)
- [x] [Bloodfire Dwarf](https://magiccards.info/query?q=!Bloodfire+Dwarf)
- [x] [Bloodfire Infusion](https://magiccards.info/query?q=!Bloodfire+Infusion)
- [x] [Bloodfire Kavu](https://magiccards.info/query?q=!Bloodfire+Kavu)
- [x] [Bog Gnarr](https://magiccards.info/query?q=!Bog+Gnarr)
- [x] [Brass Herald](https://magiccards.info/query?q=!Brass+Herald)
- [x] [Captain's Maneuver](https://magiccards.info/query?q=!Captain's+Maneuver)
- [x] [Caves of Koilos](https://magiccards.info/query?q=!Caves+of+Koilos)
- [x] [Ceta Disciple](https://magiccards.info/query?q=!Ceta+Disciple)
- [x] [Ceta Sanctuary](https://magiccards.info/query?q=!Ceta+Sanctuary)
- [x] [Cetavolver](https://magiccards.info/query?q=!Cetavolver)
- [x] [Coalition Flag](https://magiccards.info/query?q=!Coalition+Flag)
- [x] [Coalition Honor Guard](https://magiccards.info/query?q=!Coalition+Honor+Guard)
- [x] [Coastal Drake](https://magiccards.info/query?q=!Coastal+Drake)
- [x] [Consume Strength](https://magiccards.info/query?q=!Consume+Strength)
- [x] [Cromat](https://magiccards.info/query?q=!Cromat)
- [x] [Dead Ringers](https://magiccards.info/query?q=!Dead+Ringers)
- [x] [Death Grasp](https://magiccards.info/query?q=!Death+Grasp)
- [x] [Death Mutation](https://magiccards.info/query?q=!Death+Mutation)
- [x] [Dega Disciple](https://magiccards.info/query?q=!Dega+Disciple)
- [x] [Dega Sanctuary](https://magiccards.info/query?q=!Dega+Sanctuary)
- [x] [Degavolver](https://magiccards.info/query?q=!Degavolver)
- [x] [Desolation Angel](https://magiccards.info/query?q=!Desolation+Angel)
- [x] [Desolation Giant](https://magiccards.info/query?q=!Desolation+Giant)
- [x] [Diversionary Tactics](https://magiccards.info/query?q=!Diversionary+Tactics)
- [x] [Divine Light](https://magiccards.info/query?q=!Divine+Light)
- [x] [Dodecapod](https://magiccards.info/query?q=!Dodecapod)
- [x] [Dragon Arch](https://magiccards.info/query?q=!Dragon+Arch)
- [x] [Dwarven Landslide](https://magiccards.info/query?q=!Dwarven+Landslide)
- [x] [Dwarven Patrol](https://magiccards.info/query?q=!Dwarven+Patrol)
- [x] [Ebony Treefolk](https://magiccards.info/query?q=!Ebony+Treefolk)
- [x] [Emblazoned Golem](https://magiccards.info/query?q=!Emblazoned+Golem)
- [x] [Enlistment Officer](https://magiccards.info/query?q=!Enlistment+Officer)
- [x] [Evasive Action](https://magiccards.info/query?q=!Evasive+Action)
- [ ] [False Dawn](https://magiccards.info/query?q=!False+Dawn)
- [x] [Fervent Charge](https://magiccards.info/query?q=!Fervent+Charge)
- [x] [Fire // Ice](https://magiccards.info/query?q=Fire/Ice)
- [x] [Flowstone Charger](https://magiccards.info/query?q=!Flowstone+Charger)
- [x] [Foul Presence](https://magiccards.info/query?q=!Foul+Presence)
- [x] [Fungal Shambler](https://magiccards.info/query?q=!Fungal+Shambler)
- [x] [Gaea's Balance](https://magiccards.info/query?q=!Gaea's+Balance)
- [x] [Gaea's Skyfolk](https://magiccards.info/query?q=!Gaea's+Skyfolk)
- [x] [Gerrard Capashen](https://magiccards.info/query?q=!Gerrard+Capashen)
- [x] [Gerrard's Verdict](https://magiccards.info/query?q=!Gerrard's+Verdict)
- [x] [Glade Gnarr](https://magiccards.info/query?q=!Glade+Gnarr)
- [x] [Goblin Legionnaire](https://magiccards.info/query?q=!Goblin+Legionnaire)
- [x] [Goblin Ringleader](https://magiccards.info/query?q=!Goblin+Ringleader)
- [x] [Goblin Trenches](https://magiccards.info/query?q=!Goblin+Trenches)
- [x] [Grave Defiler](https://magiccards.info/query?q=!Grave+Defiler)
- [x] [Guided Passage](https://magiccards.info/query?q=!Guided+Passage)
- [x] [Haunted Angel](https://magiccards.info/query?q=!Haunted+Angel)
- [x] [Helionaut](https://magiccards.info/query?q=!Helionaut)
- [x] [Ice Cave](https://magiccards.info/query?q=!Ice+Cave)
- [x] [Illuminate](https://magiccards.info/query?q=!Illuminate)
- [x] [Illusion // Reality](https://magiccards.info/query?q=Illusion/Reality)
- [x] [Index](https://magiccards.info/query?q=!Index)
- [x] [Jaded Response](https://magiccards.info/query?q=!Jaded+Response)
- [x] [Jilt](https://magiccards.info/query?q=!Jilt)
- [x] [Jungle Barrier](https://magiccards.info/query?q=!Jungle+Barrier)
- [x] [Kavu Glider](https://magiccards.info/query?q=!Kavu+Glider)
- [x] [Kavu Howler](https://magiccards.info/query?q=!Kavu+Howler)
- [x] [Kavu Mauler](https://magiccards.info/query?q=!Kavu+Mauler)
- [x] [Last Caress](https://magiccards.info/query?q=!Last+Caress)
- [x] [Last Stand](https://magiccards.info/query?q=!Last+Stand)
- [x] [Lay of the Land](https://magiccards.info/query?q=!Lay+of+the+Land)
- [x] [Legacy Weapon](https://magiccards.info/query?q=!Legacy+Weapon)
- [x] [Life // Death](https://magiccards.info/query?q=Life/Death)
- [x] [Lightning Angel](https://magiccards.info/query?q=!Lightning+Angel)
- [x] [Living Airship](https://magiccards.info/query?q=!Living+Airship)
- [x] [Llanowar Dead](https://magiccards.info/query?q=!Llanowar+Dead)
- [x] [Llanowar Wastes](https://magiccards.info/query?q=!Llanowar+Wastes)
- [x] [Manacles of Decay](https://magiccards.info/query?q=!Manacles+of+Decay)
- [x] [Martyrs' Tomb](https://magiccards.info/query?q=!Martyrs'+Tomb)
- [x] [Mask of Intolerance](https://magiccards.info/query?q=!Mask+of+Intolerance)
- [x] [Mind Extraction](https://magiccards.info/query?q=!Mind+Extraction)
- [x] [Minotaur Illusionist](https://magiccards.info/query?q=!Minotaur+Illusionist)
- [x] [Minotaur Tactician](https://magiccards.info/query?q=!Minotaur+Tactician)
- [x] [Mournful Zombie](https://magiccards.info/query?q=!Mournful+Zombie)
- [x] [Mystic Snake](https://magiccards.info/query?q=!Mystic+Snake)
- [x] [Necra Disciple](https://magiccards.info/query?q=!Necra+Disciple)
- [x] [Necra Sanctuary](https://magiccards.info/query?q=!Necra+Sanctuary)
- [x] [Necravolver](https://magiccards.info/query?q=!Necravolver)
- [x] [Night // Day](https://magiccards.info/query?q=Night/Day)
- [x] [Order // Chaos](https://magiccards.info/query?q=Order/Chaos)
- [x] [Orim's Thunder](https://magiccards.info/query?q=!Orim's+Thunder)
- [x] [Overgrown Estate](https://magiccards.info/query?q=!Overgrown+Estate)
- [x] [Penumbra Bobcat](https://magiccards.info/query?q=!Penumbra+Bobcat)
- [x] [Penumbra Kavu](https://magiccards.info/query?q=!Penumbra+Kavu)
- [x] [Penumbra Wurm](https://magiccards.info/query?q=!Penumbra+Wurm)
- [x] [Pernicious Deed](https://magiccards.info/query?q=!Pernicious+Deed)
- [x] [Phyrexian Arena](https://magiccards.info/query?q=!Phyrexian+Arena)
- [x] [Phyrexian Gargantua](https://magiccards.info/query?q=!Phyrexian+Gargantua)
- [x] [Phyrexian Rager](https://magiccards.info/query?q=!Phyrexian+Rager)
- [x] [Planar Despair](https://magiccards.info/query?q=!Planar+Despair)
- [x] [Powerstone Minefield](https://magiccards.info/query?q=!Powerstone+Minefield)
- [x] [Prophetic Bolt](https://magiccards.info/query?q=!Prophetic+Bolt)
- [x] [Putrid Warrior](https://magiccards.info/query?q=!Putrid+Warrior)
- [x] [Quagmire Druid](https://magiccards.info/query?q=!Quagmire+Druid)
- [x] [Quicksilver Dagger](https://magiccards.info/query?q=!Quicksilver+Dagger)
- [x] [Raka Disciple](https://magiccards.info/query?q=!Raka+Disciple)
- [x] [Raka Sanctuary](https://magiccards.info/query?q=!Raka+Sanctuary)
- [x] [Rakavolver](https://magiccards.info/query?q=!Rakavolver)
- [x] [Razorfin Hunter](https://magiccards.info/query?q=!Razorfin+Hunter)
- [x] [Reef Shaman](https://magiccards.info/query?q=!Reef+Shaman)
- [x] [Savage Gorilla](https://magiccards.info/query?q=!Savage+Gorilla)
- [x] [Shield of Duty and Reason](https://magiccards.info/query?q=!Shield+of+Duty+and+Reason)
- [x] [Shimmering Mirage](https://magiccards.info/query?q=!Shimmering+Mirage)
- [x] [Shivan Reef](https://magiccards.info/query?q=!Shivan+Reef)
- [x] [Smash](https://magiccards.info/query?q=!Smash)
- [x] [Soul Link](https://magiccards.info/query?q=!Soul+Link)
- [x] [Spectral Lynx](https://magiccards.info/query?q=!Spectral+Lynx)
- [x] [Spiritmonger](https://magiccards.info/query?q=!Spiritmonger)
- [x] [Squee's Embrace](https://magiccards.info/query?q=!Squee's+Embrace)
- [x] [Squee's Revenge](https://magiccards.info/query?q=!Squee's+Revenge)
- [x] [Standard Bearer](https://magiccards.info/query?q=!Standard+Bearer)
- [x] [Strength of Night](https://magiccards.info/query?q=!Strength+of+Night)
- [x] [Suffocating Blast](https://magiccards.info/query?q=!Suffocating+Blast)
- [x] [Suppress](https://magiccards.info/query?q=!Suppress)
- [x] [Sylvan Messenger](https://magiccards.info/query?q=!Sylvan+Messenger)
- [x] [Symbiotic Deployment](https://magiccards.info/query?q=!Symbiotic+Deployment)
- [x] [Tahngarth's Glare](https://magiccards.info/query?q=!Tahngarth's+Glare)
- [x] [Temporal Spring](https://magiccards.info/query?q=!Temporal+Spring)
- [x] [Tidal Courier](https://magiccards.info/query?q=!Tidal+Courier)
- [x] [Tranquil Path](https://magiccards.info/query?q=!Tranquil+Path)
- [x] [Tundra Kavu](https://magiccards.info/query?q=!Tundra+Kavu)
- [x] [Unnatural Selection](https://magiccards.info/query?q=!Unnatural+Selection)
- [x] [Urborg Elf](https://magiccards.info/query?q=!Urborg+Elf)
- [x] [Urborg Uprising](https://magiccards.info/query?q=!Urborg+Uprising)
- [x] [Vindicate](https://magiccards.info/query?q=!Vindicate)
- [x] [Vodalian Mystic](https://magiccards.info/query?q=!Vodalian+Mystic)
- [x] [Whirlpool Drake](https://magiccards.info/query?q=!Whirlpool+Drake)
- [x] [Whirlpool Rider](https://magiccards.info/query?q=!Whirlpool+Rider)
- [x] [Whirlpool Warrior](https://magiccards.info/query?q=!Whirlpool+Warrior)
- [x] [Wild Research](https://magiccards.info/query?q=!Wild+Research)
- [x] [Yavimaya Coast](https://magiccards.info/query?q=!Yavimaya+Coast)
- [x] [Yavimaya's Embrace](https://magiccards.info/query?q=!Yavimaya's+Embrace)
- [x] [Zombie Boa](https://magiccards.info/query?q=!Zombie+Boa)

**Comment by xenohedron** [comment]
Following cards have been implemented: Mind Extraction, Zombie Boa, Tahngarth's Glare, Gaea's Balance, Captain's Maneuver

**Comment by xenohedron** [comment]
All cards are implemented
