### ISSUE TITLE
NEM - Nemesis Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5230]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/nemesis)

# Cards in set:
- [x] [Accumulated Knowledge](https://magiccards.info/query?q=!Accumulated+Knowledge)
- [x] [Aether Barrier](https://magiccards.info/query?q=!Aether+Barrier)
- [x] [Air Bladder](https://magiccards.info/query?q=!Air+Bladder)
- [x] [Ancient Hydra](https://magiccards.info/query?q=!Ancient+Hydra)
- [x] [Angelic Favor](https://magiccards.info/query?q=!Angelic+Favor)
- [x] [Animate Land](https://magiccards.info/query?q=!Animate+Land)
- [x] [Arc Mage](https://magiccards.info/query?q=!Arc+Mage)
- [x] [Ascendant Evincar](https://magiccards.info/query?q=!Ascendant+Evincar)
- [x] [Avenger en-Dal](https://magiccards.info/query?q=!Avenger+en-Dal)
- [x] [Battlefield Percher](https://magiccards.info/query?q=!Battlefield+Percher)
- [x] [Belbe's Armor](https://magiccards.info/query?q=!Belbe's+Armor)
- [x] [Belbe's Percher](https://magiccards.info/query?q=!Belbe's+Percher)
- [x] [Belbe's Portal](https://magiccards.info/query?q=!Belbe's+Portal)
- [x] [Blastoderm](https://magiccards.info/query?q=!Blastoderm)
- [x] [Blinding Angel](https://magiccards.info/query?q=!Blinding+Angel)
- [x] [Bola Warrior](https://magiccards.info/query?q=!Bola+Warrior)
- [x] [Carrion Wall](https://magiccards.info/query?q=!Carrion+Wall)
- [x] [Chieftain en-Dal](https://magiccards.info/query?q=!Chieftain+en-Dal)
- [x] [Cloudskate](https://magiccards.info/query?q=!Cloudskate)
- [x] [Coiling Woodworm](https://magiccards.info/query?q=!Coiling+Woodworm)
- [x] [Complex Automaton](https://magiccards.info/query?q=!Complex+Automaton)
- [x] [Dark Triumph](https://magiccards.info/query?q=!Dark+Triumph)
- [x] [Daze](https://magiccards.info/query?q=!Daze)
- [x] [Death Pit Offering](https://magiccards.info/query?q=!Death+Pit+Offering)
- [x] [Defender en-Vec](https://magiccards.info/query?q=!Defender+en-Vec)
- [x] [Defiant Falcon](https://magiccards.info/query?q=!Defiant+Falcon)
- [x] [Defiant Vanguard](https://magiccards.info/query?q=!Defiant+Vanguard)
- [x] [Divining Witch](https://magiccards.info/query?q=!Divining+Witch)
- [x] [Dominate](https://magiccards.info/query?q=!Dominate)
- [x] [Downhill Charge](https://magiccards.info/query?q=!Downhill+Charge)
- [x] [Ensnare](https://magiccards.info/query?q=!Ensnare)
- [x] [Eye of Yawgmoth](https://magiccards.info/query?q=!Eye+of+Yawgmoth)
- [x] [Fanatical Devotion](https://magiccards.info/query?q=!Fanatical+Devotion)
- [x] [Flame Rift](https://magiccards.info/query?q=!Flame+Rift)
- [x] [Flint Golem](https://magiccards.info/query?q=!Flint+Golem)
- [x] [Flowstone Armor](https://magiccards.info/query?q=!Flowstone+Armor)
- [x] [Flowstone Crusher](https://magiccards.info/query?q=!Flowstone+Crusher)
- [x] [Flowstone Overseer](https://magiccards.info/query?q=!Flowstone+Overseer)
- [x] [Flowstone Slide](https://magiccards.info/query?q=!Flowstone+Slide)
- [x] [Flowstone Strike](https://magiccards.info/query?q=!Flowstone+Strike)
- [x] [Flowstone Surge](https://magiccards.info/query?q=!Flowstone+Surge)
- [x] [Flowstone Thopter](https://magiccards.info/query?q=!Flowstone+Thopter)
- [x] [Flowstone Wall](https://magiccards.info/query?q=!Flowstone+Wall)
- [x] [Fog Patch](https://magiccards.info/query?q=!Fog+Patch)
- [x] [Harvest Mage](https://magiccards.info/query?q=!Harvest+Mage)
- [x] [Infiltrate](https://magiccards.info/query?q=!Infiltrate)
- [x] [Jolting Merfolk](https://magiccards.info/query?q=!Jolting+Merfolk)
- [x] [Kill Switch](https://magiccards.info/query?q=!Kill+Switch)
- [x] [Kor Haven](https://magiccards.info/query?q=!Kor+Haven)
- [x] [Laccolith Grunt](https://magiccards.info/query?q=!Laccolith+Grunt)
- [x] [Laccolith Rig](https://magiccards.info/query?q=!Laccolith+Rig)
- [x] [Laccolith Titan](https://magiccards.info/query?q=!Laccolith+Titan)
- [x] [Laccolith Warrior](https://magiccards.info/query?q=!Laccolith+Warrior)
- [x] [Laccolith Whelp](https://magiccards.info/query?q=!Laccolith+Whelp)
- [x] [Lashknife](https://magiccards.info/query?q=!Lashknife)
- [x] [Lawbringer](https://magiccards.info/query?q=!Lawbringer)
- [x] [Lightbringer](https://magiccards.info/query?q=!Lightbringer)
- [x] [Lin Sivvi, Defiant Hero](https://magiccards.info/query?q=!Lin+Sivvi,+Defiant+Hero)
- [x] [Mana Cache](https://magiccards.info/query?q=!Mana+Cache)
- [x] [Massacre](https://magiccards.info/query?q=!Massacre)
- [x] [Mind Slash](https://magiccards.info/query?q=!Mind+Slash)
- [x] [Mind Swords](https://magiccards.info/query?q=!Mind+Swords)
- [x] [Mogg Alarm](https://magiccards.info/query?q=!Mogg+Alarm)
- [x] [Mogg Salvage](https://magiccards.info/query?q=!Mogg+Salvage)
- [x] [Mogg Toady](https://magiccards.info/query?q=!Mogg+Toady)
- [x] [Moggcatcher](https://magiccards.info/query?q=!Moggcatcher)
- [x] [Mossdog](https://magiccards.info/query?q=!Mossdog)
- [x] [Murderous Betrayal](https://magiccards.info/query?q=!Murderous+Betrayal)
- [x] [Nesting Wurm](https://magiccards.info/query?q=!Nesting+Wurm)
- [x] [Netter en-Dal](https://magiccards.info/query?q=!Netter+en-Dal)
- [x] [Noble Stand](https://magiccards.info/query?q=!Noble+Stand)
- [x] [Off Balance](https://magiccards.info/query?q=!Off+Balance)
- [x] [Oracle's Attendants](https://magiccards.info/query?q=!Oracle's+Attendants)
- [x] [Oraxid](https://magiccards.info/query?q=!Oraxid)
- [x] [Overlaid Terrain](https://magiccards.info/query?q=!Overlaid+Terrain)
- [x] [Pack Hunt](https://magiccards.info/query?q=!Pack+Hunt)
- [x] [Pale Moon](https://magiccards.info/query?q=!Pale+Moon)
- [x] [Parallax Dementia](https://magiccards.info/query?q=!Parallax+Dementia)
- [x] [Parallax Inhibitor](https://magiccards.info/query?q=!Parallax+Inhibitor)
- [x] [Parallax Nexus](https://magiccards.info/query?q=!Parallax+Nexus)
- [x] [Parallax Tide](https://magiccards.info/query?q=!Parallax+Tide)
- [x] [Parallax Wave](https://magiccards.info/query?q=!Parallax+Wave)
- [x] [Phyrexian Driver](https://magiccards.info/query?q=!Phyrexian+Driver)
- [x] [Phyrexian Prowler](https://magiccards.info/query?q=!Phyrexian+Prowler)
- [x] [Plague Witch](https://magiccards.info/query?q=!Plague+Witch)
- [x] [Predator, Flagship](https://magiccards.info/query?q=!Predator,+Flagship)
- [x] [Rackling](https://magiccards.info/query?q=!Rackling)
- [x] [Rath's Edge](https://magiccards.info/query?q=!Rath's+Edge)
- [x] [Rathi Assassin](https://magiccards.info/query?q=!Rathi+Assassin)
- [x] [Rathi Fiend](https://magiccards.info/query?q=!Rathi+Fiend)
- [x] [Rathi Intimidator](https://magiccards.info/query?q=!Rathi+Intimidator)
- [x] [Refreshing Rain](https://magiccards.info/query?q=!Refreshing+Rain)
- [x] [Rejuvenation Chamber](https://magiccards.info/query?q=!Rejuvenation+Chamber)
- [x] [Reverent Silence](https://magiccards.info/query?q=!Reverent+Silence)
- [x] [Rhox](https://magiccards.info/query?q=!Rhox)
- [x] [Rising Waters](https://magiccards.info/query?q=!Rising+Waters)
- [x] [Rootwater Commando](https://magiccards.info/query?q=!Rootwater+Commando)
- [x] [Rootwater Thief](https://magiccards.info/query?q=!Rootwater+Thief)
- [x] [Rupture](https://magiccards.info/query?q=!Rupture)
- [x] [Rusting Golem](https://magiccards.info/query?q=!Rusting+Golem)
- [x] [Saproling Burst](https://magiccards.info/query?q=!Saproling+Burst)
- [x] [Saproling Cluster](https://magiccards.info/query?q=!Saproling+Cluster)
- [x] [Seahunter](https://magiccards.info/query?q=!Seahunter)
- [x] [Seal of Cleansing](https://magiccards.info/query?q=!Seal+of+Cleansing)
- [x] [Seal of Doom](https://magiccards.info/query?q=!Seal+of+Doom)
- [x] [Seal of Fire](https://magiccards.info/query?q=!Seal+of+Fire)
- [x] [Seal of Removal](https://magiccards.info/query?q=!Seal+of+Removal)
- [x] [Seal of Strength](https://magiccards.info/query?q=!Seal+of+Strength)
- [x] [Shrieking Mogg](https://magiccards.info/query?q=!Shrieking+Mogg)
- [x] [Silkenfist Fighter](https://magiccards.info/query?q=!Silkenfist+Fighter)
- [x] [Silkenfist Order](https://magiccards.info/query?q=!Silkenfist+Order)
- [x] [Sivvi's Ruse](https://magiccards.info/query?q=!Sivvi's+Ruse)
- [x] [Sivvi's Valor](https://magiccards.info/query?q=!Sivvi's+Valor)
- [x] [Skyshroud Behemoth](https://magiccards.info/query?q=!Skyshroud+Behemoth)
- [x] [Skyshroud Claim](https://magiccards.info/query?q=!Skyshroud+Claim)
- [x] [Skyshroud Cutter](https://magiccards.info/query?q=!Skyshroud+Cutter)
- [x] [Skyshroud Poacher](https://magiccards.info/query?q=!Skyshroud+Poacher)
- [x] [Skyshroud Ridgeback](https://magiccards.info/query?q=!Skyshroud+Ridgeback)
- [x] [Skyshroud Sentinel](https://magiccards.info/query?q=!Skyshroud+Sentinel)
- [x] [Sliptide Serpent](https://magiccards.info/query?q=!Sliptide+Serpent)
- [x] [Sneaky Homunculus](https://magiccards.info/query?q=!Sneaky+Homunculus)
- [x] [Spineless Thug](https://magiccards.info/query?q=!Spineless+Thug)
- [x] [Spiritual Asylum](https://magiccards.info/query?q=!Spiritual+Asylum)
- [x] [Spiteful Bully](https://magiccards.info/query?q=!Spiteful+Bully)
- [x] [Stampede Driver](https://magiccards.info/query?q=!Stampede+Driver)
- [x] [Stronghold Biologist](https://magiccards.info/query?q=!Stronghold+Biologist)
- [x] [Stronghold Discipline](https://magiccards.info/query?q=!Stronghold+Discipline)
- [x] [Stronghold Gambit](https://magiccards.info/query?q=!Stronghold+Gambit)
- [x] [Stronghold Machinist](https://magiccards.info/query?q=!Stronghold+Machinist)
- [x] [Stronghold Zeppelin](https://magiccards.info/query?q=!Stronghold+Zeppelin)
- [x] [Submerge](https://magiccards.info/query?q=!Submerge)
- [x] [Tangle Wire](https://magiccards.info/query?q=!Tangle+Wire)
- [x] [Terrain Generator](https://magiccards.info/query?q=!Terrain+Generator)
- [x] [Topple](https://magiccards.info/query?q=!Topple)
- [x] [Treetop Bracers](https://magiccards.info/query?q=!Treetop+Bracers)
- [x] [Trickster Mage](https://magiccards.info/query?q=!Trickster+Mage)
- [x] [Vicious Hunger](https://magiccards.info/query?q=!Vicious+Hunger)
- [x] [Viseling](https://magiccards.info/query?q=!Viseling)
- [x] [Voice of Truth](https://magiccards.info/query?q=!Voice+of+Truth)
- [x] [Volrath the Fallen](https://magiccards.info/query?q=!Volrath+the+Fallen)
- [x] [Wandering Eye](https://magiccards.info/query?q=!Wandering+Eye)
- [x] [Wild Mammoth](https://magiccards.info/query?q=!Wild+Mammoth)
- [x] [Woodripper](https://magiccards.info/query?q=!Woodripper)
