### ISSUE TITLE
PYC - Prophecy Set Card Implementation Tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5231]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/content/productpagemasques3prophecy)

# Unimplemented Cards

# Cards in set:

- [x] [Abolish](https://magiccards.info/query?q=!Abolish)
- [x] [Agent of Shauku](https://magiccards.info/query?q=!Agent+of+Shauku)
- [x] [Alexi's Cloak](https://magiccards.info/query?q=!Alexi's+Cloak)
- [x] [Alexi, Zephyr Mage](https://magiccards.info/query?q=!Alexi,+Zephyr+Mage)
- [x] [Aura Fracture](https://magiccards.info/query?q=!Aura+Fracture)
- [x] [Avatar of Fury](https://magiccards.info/query?q=!Avatar+of+Fury)
- [x] [Avatar of Hope](https://magiccards.info/query?q=!Avatar+of+Hope)
- [x] [Avatar of Might](https://magiccards.info/query?q=!Avatar+of+Might)
- [x] [Avatar of Will](https://magiccards.info/query?q=!Avatar+of+Will)
- [x] [Avatar of Woe](https://magiccards.info/query?q=!Avatar+of+Woe)
- [x] [Barbed Field](https://magiccards.info/query?q=!Barbed+Field)
- [x] [Blessed Wind](https://magiccards.info/query?q=!Blessed+Wind)
- [x] [Bog Elemental](https://magiccards.info/query?q=!Bog+Elemental)
- [x] [Bog Glider](https://magiccards.info/query?q=!Bog+Glider)
- [x] [Branded Brawlers](https://magiccards.info/query?q=!Branded+Brawlers)
- [x] [Brutal Suppression](https://magiccards.info/query?q=!Brutal+Suppression)
- [x] [Calming Verse](https://magiccards.info/query?q=!Calming+Verse)
- [x] [Celestial Convergence](https://magiccards.info/query?q=!Celestial+Convergence)
- [x] [Chilling Apparition](https://magiccards.info/query?q=!Chilling+Apparition)
- [x] [Chimeric Idol](https://magiccards.info/query?q=!Chimeric+Idol)
- [x] [Citadel of Pain](https://magiccards.info/query?q=!Citadel+of+Pain)
- [x] [Coastal Hornclaw](https://magiccards.info/query?q=!Coastal+Hornclaw)
- [x] [Coffin Puppets](https://magiccards.info/query?q=!Coffin+Puppets)
- [x] [Copper-Leaf Angel](https://magiccards.info/query?q=!Copper-Leaf+Angel)
- [x] [Darba](https://magiccards.info/query?q=!Darba)
- [x] [Death Charmer](https://magiccards.info/query?q=!Death+Charmer)
- [x] [Denying Wind](https://magiccards.info/query?q=!Denying+Wind)
- [x] [Despoil](https://magiccards.info/query?q=!Despoil)
- [x] [Devastate](https://magiccards.info/query?q=!Devastate)
- [x] [Diving Griffin](https://magiccards.info/query?q=!Diving+Griffin)
- [x] [Dual Nature](https://magiccards.info/query?q=!Dual+Nature)
- [x] [Elephant Resurgence](https://magiccards.info/query?q=!Elephant+Resurgence)
- [x] [Endbringer's Revel](https://magiccards.info/query?q=!Endbringer's+Revel)
- [x] [Entangler](https://magiccards.info/query?q=!Entangler)
- [x] [Excavation](https://magiccards.info/query?q=!Excavation)
- [x] [Excise](https://magiccards.info/query?q=!Excise)
- [x] [Fault Riders](https://magiccards.info/query?q=!Fault+Riders)
- [x] [Fen Stalker](https://magiccards.info/query?q=!Fen+Stalker)
- [x] [Fickle Efreet](https://magiccards.info/query?q=!Fickle+Efreet)
- [x] [Flameshot](https://magiccards.info/query?q=!Flameshot)
- [x] [Flay](https://magiccards.info/query?q=!Flay)
- [x] [Flowering Field](https://magiccards.info/query?q=!Flowering+Field)
- [x] [Foil](https://magiccards.info/query?q=!Foil)
- [x] [Forgotten Harvest](https://magiccards.info/query?q=!Forgotten+Harvest)
- [x] [Glittering Lion](https://magiccards.info/query?q=!Glittering+Lion)
- [x] [Glittering Lynx](https://magiccards.info/query?q=!Glittering+Lynx)
- [x] [Greel's Caress](https://magiccards.info/query?q=!Greel's+Caress)
- [x] [Greel, Mind Raker](https://magiccards.info/query?q=!Greel,+Mind+Raker)
- [x] [Gulf Squid](https://magiccards.info/query?q=!Gulf+Squid)
- [x] [Hazy Homunculus](https://magiccards.info/query?q=!Hazy+Homunculus)
- [x] [Heightened Awareness](https://magiccards.info/query?q=!Heightened+Awareness)
- [x] [Hollow Warrior](https://magiccards.info/query?q=!Hollow+Warrior)
- [x] [Infernal Genesis](https://magiccards.info/query?q=!Infernal+Genesis)
- [x] [Inflame](https://magiccards.info/query?q=!Inflame)
- [x] [Jeweled Spirit](https://magiccards.info/query?q=!Jeweled+Spirit)
- [x] [Jolrael's Favor](https://magiccards.info/query?q=!Jolrael's+Favor)
- [x] [Jolrael, Empress of Beasts](https://magiccards.info/query?q=!Jolrael,+Empress+of+Beasts)
- [x] [Keldon Arsonist](https://magiccards.info/query?q=!Keldon+Arsonist)
- [x] [Keldon Battlewagon](https://magiccards.info/query?q=!Keldon+Battlewagon)
- [x] [Keldon Berserker](https://magiccards.info/query?q=!Keldon+Berserker)
- [x] [Keldon Firebombers](https://magiccards.info/query?q=!Keldon+Firebombers)
- [x] [Latulla's Orders](https://magiccards.info/query?q=!Latulla's+Orders)
- [x] [Latulla, Keldon Overseer](https://magiccards.info/query?q=!Latulla,+Keldon+Overseer)
- [x] [Lesser Gargadon](https://magiccards.info/query?q=!Lesser+Gargadon)
- [x] [Living Terrain](https://magiccards.info/query?q=!Living+Terrain)
- [x] [Mageta the Lion](https://magiccards.info/query?q=!Mageta+the+Lion)
- [x] [Mageta's Boon](https://magiccards.info/query?q=!Mageta's+Boon)
- [x] [Mana Vapors](https://magiccards.info/query?q=!Mana+Vapors)
- [x] [Marsh Boa](https://magiccards.info/query?q=!Marsh+Boa)
- [x] [Mercenary Informer](https://magiccards.info/query?q=!Mercenary+Informer)
- [x] [Mine Bearer](https://magiccards.info/query?q=!Mine+Bearer)
- [x] [Mirror Strike](https://magiccards.info/query?q=!Mirror+Strike)
- [x] [Mungha Wurm](https://magiccards.info/query?q=!Mungha+Wurm)
- [x] [Nakaya Shade](https://magiccards.info/query?q=!Nakaya+Shade)
- [x] [Noxious Field](https://magiccards.info/query?q=!Noxious+Field)
- [x] [Outbreak](https://magiccards.info/query?q=!Outbreak)
- [x] [Overburden](https://magiccards.info/query?q=!Overburden)
- [x] [Panic Attack](https://magiccards.info/query?q=!Panic+Attack)
- [x] [Pit Raptor](https://magiccards.info/query?q=!Pit+Raptor)
- [x] [Plague Fiend](https://magiccards.info/query?q=!Plague+Fiend)
- [x] [Plague Wind](https://magiccards.info/query?q=!Plague+Wind)
- [x] [Psychic Theft](https://magiccards.info/query?q=!Psychic+Theft)
- [x] [Pygmy Razorback](https://magiccards.info/query?q=!Pygmy+Razorback)
- [x] [Quicksilver Wall](https://magiccards.info/query?q=!Quicksilver+Wall)
- [x] [Rebel Informer](https://magiccards.info/query?q=!Rebel+Informer)
- [x] [Rethink](https://magiccards.info/query?q=!Rethink)
- [x] [Reveille Squad](https://magiccards.info/query?q=!Reveille+Squad)
- [x] [Rhystic Cave](https://magiccards.info/query?q=!Rhystic+Cave)
- [x] [Rhystic Circle](https://magiccards.info/query?q=!Rhystic+Circle)
- [x] [Rhystic Deluge](https://magiccards.info/query?q=!Rhystic+Deluge)
- [x] [Rhystic Lightning](https://magiccards.info/query?q=!Rhystic+Lightning)
- [x] [Rhystic Scrying](https://magiccards.info/query?q=!Rhystic+Scrying)
- [x] [Rhystic Shield](https://magiccards.info/query?q=!Rhystic+Shield)
- [x] [Rhystic Study](https://magiccards.info/query?q=!Rhystic+Study)
- [x] [Rhystic Syphon](https://magiccards.info/query?q=!Rhystic+Syphon)
- [x] [Rhystic Tutor](https://magiccards.info/query?q=!Rhystic+Tutor)
- [x] [Rib Cage Spider](https://magiccards.info/query?q=!Rib+Cage+Spider)
- [x] [Ribbon Snake](https://magiccards.info/query?q=!Ribbon+Snake)
- [x] [Ridgeline Rager](https://magiccards.info/query?q=!Ridgeline+Rager)
- [x] [Root Cage](https://magiccards.info/query?q=!Root+Cage)
- [x] [Samite Sanctuary](https://magiccards.info/query?q=!Samite+Sanctuary)
- [x] [Scoria Cat](https://magiccards.info/query?q=!Scoria+Cat)
- [x] [Search for Survivors](https://magiccards.info/query?q=!Search+for+Survivors)
- [x] [Searing Wind](https://magiccards.info/query?q=!Searing+Wind)
- [x] [Sheltering Prayers](https://magiccards.info/query?q=!Sheltering+Prayers)
- [x] [Shield Dancer](https://magiccards.info/query?q=!Shield+Dancer)
- [x] [Shrouded Serpent](https://magiccards.info/query?q=!Shrouded+Serpent)
- [x] [Silt Crawler](https://magiccards.info/query?q=!Silt+Crawler)
- [x] [Snag](https://magiccards.info/query?q=!Snag)
- [x] [Soul Charmer](https://magiccards.info/query?q=!Soul+Charmer)
- [x] [Soul Strings](https://magiccards.info/query?q=!Soul+Strings)
- [x] [Spiketail Drake](https://magiccards.info/query?q=!Spiketail+Drake)
- [x] [Spiketail Hatchling](https://magiccards.info/query?q=!Spiketail+Hatchling)
- [x] [Spitting Spider](https://magiccards.info/query?q=!Spitting+Spider)
- [x] [Spore Frog](https://magiccards.info/query?q=!Spore+Frog)
- [x] [Spur Grappler](https://magiccards.info/query?q=!Spur+Grappler)
- [x] [Squirrel Wrangler](https://magiccards.info/query?q=!Squirrel+Wrangler)
- [x] [Steal Strength](https://magiccards.info/query?q=!Steal+Strength)
- [x] [Stormwatch Eagle](https://magiccards.info/query?q=!Stormwatch+Eagle)
- [x] [Sunken Field](https://magiccards.info/query?q=!Sunken+Field)
- [x] [Sword Dancer](https://magiccards.info/query?q=!Sword+Dancer)
- [x] [Task Mage Assembly](https://magiccards.info/query?q=!Task+Mage+Assembly)
- [x] [Thresher Beast](https://magiccards.info/query?q=!Thresher+Beast)
- [x] [Thrive](https://magiccards.info/query?q=!Thrive)
- [x] [Trenching Steed](https://magiccards.info/query?q=!Trenching+Steed)
- [x] [Troubled Healer](https://magiccards.info/query?q=!Troubled+Healer)
- [x] [Troublesome Spirit](https://magiccards.info/query?q=!Troublesome+Spirit)
- [x] [Verdant Field](https://magiccards.info/query?q=!Verdant+Field)
- [x] [Veteran Brawlers](https://magiccards.info/query?q=!Veteran+Brawlers)
- [x] [Vintara Elephant](https://magiccards.info/query?q=!Vintara+Elephant)
- [x] [Vintara Snapper](https://magiccards.info/query?q=!Vintara+Snapper)
- [x] [Vitalizing Wind](https://magiccards.info/query?q=!Vitalizing+Wind)
- [x] [Wall of Vipers](https://magiccards.info/query?q=!Wall+of+Vipers)
- [x] [Well of Discovery](https://magiccards.info/query?q=!Well+of+Discovery)
- [x] [Well of Life](https://magiccards.info/query?q=!Well+of+Life)
- [x] [Whip Sergeant](https://magiccards.info/query?q=!Whip+Sergeant)
- [x] [Whipstitched Zombie](https://magiccards.info/query?q=!Whipstitched+Zombie)
- [x] [Wild Might](https://magiccards.info/query?q=!Wild+Might)
- [x] [Windscouter](https://magiccards.info/query?q=!Windscouter)
- [x] [Wing Storm](https://magiccards.info/query?q=!Wing+Storm)
- [x] [Wintermoon Mesa](https://magiccards.info/query?q=!Wintermoon+Mesa)
- [x] [Withdraw](https://magiccards.info/query?q=!Withdraw)
- [x] [Zerapa Minotaur](https://magiccards.info/query?q=!Zerapa+Minotaur)
