### ISSUE TITLE
Feedback XMage Version 1.4.31V0

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5273]
# 1.4.30V0 2018-08-25 13:15 CET
Unresolved:
- [ ] Bug with dissapearing cards: I put another legendary creature on the battlefield, then rollbacked. both of my creatures dissapeared :( Pls check that that out (reported by Baneriusz / 2018-08-15 17:48:54.788).
- [ ] Profile not connecting: My profile no longer connect, event after several password reset. Could you please point me where to get help ? (reported by salmosalarrr / 2018-08-15 21:38:44.757).
- [ ] Time of Ice bug: Time of Ice leaving the battlefield and being replayed before the opponent gets an untap step fails to keep those creatures selected from the original casting tapped. (reported by DaBouche / 2018-08-16 03:43:19.064).
- [x] Lord windgrace ultimate: Hi i played with lord windgrace the new commander from c18 and the ultimate says "zero" it should be six (reported by Balisong132 / 2018-08-16 05:02:20.034).
- [ ] Herald's Horn Glitch: Herald's Horn doesn't care about creature type (picked dragon, was able to reveal Vizier of the Menagerie). (reported by Nonexistant / 2018-08-16 05:53:13.728).
- [ ] Seeing no players or games: I connected to xmage.de but not seeing any games or players (reported by mirda / 2018-08-16 11:48:50.626).
- [ ] The Nivmagus Elemental + Ground Rift combo does not work.: The Nivmagus Elemental ability is not working correctly in xmage. She is not exiling copies generated by the storm trigger, for example. The Nivmagus Elemental + Ground Rift combo does not work. (reported by alanjones / 2018-08-16 16:36:41.955).
- [ ] Add tickbox for card in latest expansion in deck editor: When importing cards it would be nice to have so it adds the cards from latest expansion and not old ones first... (reported by IlIIlIIIl / 2018-08-18 12:55:36.395).
- [ ] Hungering hydra and Declare dominance: If one plays declare dominance on hungering hydra the blocking player cant make any blocks at all. (reported by _Ezekiel_ / 2018-08-18 17:09:20.869).
- [ ] Prototype Portal: About Prototype Portal, from new Commaber, I nned to pay 5 5 to copy the artifact, buttne correct is only 5. (reported by Show_da_Luna / 2018-08-19 00:15:35.633).
- [ ] fix blood moon vs shocks: they changed the rules, now if blood moon is in play a shock will enter as an untapped mountain. (reported by jesus / 2018-08-19 04:55:43.313).
- [ ] Can't activate Birthing Pod: I have plaqyed birthing pod, spending 2 life to play it, and when i click on it to activate its effect, nothing happens. (reported by Mstr_Hyperion / 2018-08-19 16:51:35.18).
- [ ] Missing card: Illusuonary Mask (beta/Unlimited): I want to use "Illusionary Mask" in a Legacy deck. It shouldn't be too hard to implement as it is very similar to the existing "morph" mechanic (reported by sheriffharry / 2018-08-19 18:23:33.441).
- [ ] Demonic Consultation results in no effect: Used Demonic Consultation named "Toxic Deluge" and proceeded to just putting the card in the gy with no effect.. (reported by Reiyu / 2018-08-19 20:30:57.549).
- [ ] add silver bordered sets: would be cool to be able to draft silver border stuff. goofy, but cool. (reported by gtOK / 2018-08-20 00:37:06.449).
- [ ] Default basic lands: It would be nice to have a feature to choose default basic lands so I don't have to change them every time i load a new deck. (reported by iamthebest / 2018-08-20 00:44:02.251).
- [ ] scourge of the throne: scourge of the throne does not give second combat (reported by Bigstriker14 / 2018-08-20 09:22:18.712).
- [ ] please add soldevi sentry and rofellos's gift: please please add these cards (reported by neubstone / 2018-08-21 00:33:40.335).
- [ ] Lands entering tapped under Blood Sun.: Lands that usually ETB tapped are entering the battlefield tapped when blood sun in out. (reported by flaxencobra / 2018-08-21 00:56:13.546).
- [x] Commander Ninjitsu: Commander Ninjitsu is just ninjitsu right now (reported by FrankDammit / 2018-08-21 04:06:34.531).
- [ ] yuriko doesnt work with mindsalver: (300 characters max) (reported by whiteraven / 2018-08-21 04:15:28.017).
- [x] Windgrace's judgment: Does not destroy targeted permanents (reported by Kezmundo / 2018-08-21 13:10:59.369).
- [x] Windgrace's Judgment: Windgrace's judgment doesn't work properly, out of 3 target i selected only 1 was destroyed. Please fix this thank you! (reported by sichiro / 2018-08-21 13:13:15.659).
- [ ] Treasure Nabber: Treasure Nabber doesnt return artifacts to owner. (reported by flaxencobra / 2018-08-23 09:00:15.799).
- [ ] Rakdos, Lord of Riots bug fix: Rakdos, Lord of Riots applies his cost reduction buff to himself if he was removed mid combat. This is not how he should act, as he cannot apply this to himself. (reported by FirefoxStormy / 2018-08-23 17:17:28.682).
- [ ] Suffler: How's it's possible that 7 games in a row there's land flooting or no landers. This totally sucks so can please do something. (reported by JuakkoL / 2018-08-23 18:17:28.141).
- [ ] Bug?: Hi there, we had some bugs in our latets game. Lands and creatures didn't untap in the first game. In the 3rd game we where unable to attack with more than 1 creature and couldn't block with more than 1 creature. Is this a bug? (reported by mrjonasponas / 2018-08-23 20:24:55.281).
- [ ] Dont get to sac mausoleum wanderer: I play UW Spirits. Sometimes when my opponent plays an instant or sorcery ability, i dont get to sacrifice my mausoleum wanderer, which is very bad (reported by Jobuno / 2018-08-24 17:16:52.976).
- [ ] energy flux shouldn't let you sacrifice permanents you don't control: I have treasure nabber, opponent has energy flux and gilded lotus. When flux trigger is on stack he taps lotus to pay for another artifact and I gain control of it. The he doesn't pay for flux and the lotus is sacrificed, altough I'm controlling it now. (reported by DerLhurgoyf / 2018-08-24 22:44:56.209).
- [ ] spirit of the labyrinth: effect does not end after he is dead... (reported by GAMEster52 / 2018-08-25 12:53:03.25).

Resolved:
- [x] Yuriko Tigers shadow ninjutsu: Yurikos ninjustsu abillity doenst work. (reported by Kraya / 2018-08-15 12:37:44.541).
- [x] Commander18 bugs: Yuriko's Commander Ninjutsu doesn't work. Both Estrid's -1 and -7 are bugged. (reported by AculAlHazred / 2018-08-15 17:29:24.038).
- [x] cant download images: stays in the screen "check which images are missing..." and dont go further (reported by kotzweilen / 2018-08-15 17:55:31.347).
- [x] Commander ninjutsu doesn't work: it appears commander ninjutsu only works from the hand, but not from the command zone as intended. (reported by AllMight / 2018-08-15 18:25:36.089).
- [x] Oracle Text: Brudiclad's Oracle text is missing a part of the ability (it still works correctly, it's just missing from the Oracle text (reported by JohnLemon / 2018-08-15 18:42:38.909).
- [x] i have a trouble with images.: in the last update my cards dont have images now. (reported by Dan_Wick / 2018-08-15 19:25:38.021).
- [x] Image download doesn't work: Image download freezes (reported by ritz / 2018-08-15 23:08:20.493).
- [x] Images not loading: Hello,when I click the "Images" menu, the operation freezes at "Checking wich images are missing"Pls help (reported by Loizo / 2018-08-15 23:26:34.552).
- [x] Vodalian Arcanist: Vodalian Arcanist seems to be willing to tap for colorless mana for any spell, not just instants or sorceries. (reported by DaBouche / 2018-08-16 03:41:36.925).
- [x] Estrid's Invocation: Estrid's invocation allowed me to copy an opponents enchantment during my previous game. I believe this was incorrect. Thank you! (reported by Ueyes_Wdragon / 2018-08-16 06:13:25.332).
- [x] images wont download: nobody can download images. (reported by igniteaxiom / 2018-08-16 08:18:28.913).
- [x] Fix bugs pls: Hi system cant find walking ballista and that is reason why i cant start a game...same with flooded strand etc...pls fix it :] (reported by Sanin3 / 2018-08-16 13:50:33.965).
- [x] Yennet incorrectly named: the card "Yennet, Cryptic Sovereign" is incorrectly labeled as "Yennet, Crypt Sovereign" (reported by Knighthawke / 2018-08-16 21:15:51.271).
- [x] Include commander ninjitsu: Please include commander ninjitsu into the game as Yuriko cannot use her ability otherwise. She is currently coded as a regular ninja's ninjitsu as of live servers. (reported by Ambsma / 2018-08-17 14:36:21.397).
- [x] Bug: Varchild doesn't create the survivors tokens, thanks and keep up the good work (reported by Uomoconodor / 2018-08-17 19:48:19.697).
- [x] Kestia the cultivator: could now bestow Kestia the cultivator from the command zone. thx guys ur beasting it (reported by shuto / 2018-08-18 01:01:08.32).
- [x] Satyr rambler: its cmc is wrong (reported by Wigglyfish2 / 2018-08-18 01:46:56.083).
- [x] Typo for Yennett: Yennett, Cryptic Sovereign has two typis (Yennet, Crypt) (reported by Scythe / 2018-08-18 11:25:48.125).
- [x] Checking for missing images: I can't download the card images, it's checking for missing cards and wont download anything (reported by quibbz / 2018-08-18 20:35:18.92).
- [x] Images: Im an old user of Xmage, i just downloaded it on a new PC and when i click the Image button, it tells to me to Check which images are missing, and gives me no option to download all the images. (reported by Mizrrym / 2018-08-18 21:24:32.561).
- [x] Thanks: Thanks a lot for all the work you guys put into this ! (reported by Gui / 2018-08-19 02:36:05.353).
- [x] Chalice of the Void bug: I cast chalice of the void for X = 0 then my opponnent cast a Walking Balista which has a converted mana cost of 0 for X = 1 without any Cavern of soul or any uncounterable effect and chalice of the void didnt triggerred to counter the Walking Ballista. (reported by gbihgbies / 2018-08-19 04:28:00.447).
- [x] images: the image downloads still are not working! (reported by IDHeathcliff / 2018-08-19 10:10:31.903).
- [x] Support for images: Some images from some sets (for example Ramunap Excavator) can't be downloaded (reported by Shorty181 / 2018-08-19 12:51:59.926).
- [x] Yuriko: Yuriko's Commander Ninjitsu doesnt work from the command zone. Fix please. (reported by JaptainCack / 2018-08-19 18:17:35.264).
- [x] Fix Images: When I try to download images (I currently have none),it sits on the "check what images are missing..." and doesn'tdo anything else. I've let it sit for hours and it still won't do anything. (reported by Aedaillon / 2018-08-19 21:22:27.836).
- [x] Commander Ninjitsu broken: Yuriko, the Tiger's Shadow needs to work from the command zone via commander ninjitsu, but the current implementation only gave her regular ninjitsu which only works from hand (reported by Zunon / 2018-08-20 10:47:42.892).
- [x] Yuriko doesn't work: the new commander yuriko doesn't work, his capacity should be commander ninjutsu (reported by Artifacts / 2018-08-20 11:05:41.093).
- [x] A "source" to download any missing cards: Right now you could go through all of the sources in the Images list and still end up missing some card images. Would it make sense to host a repository of all the cards that would be missing? (reported by de_veneno / 2018-08-21 15:53:27.411).
- [x] Commander ninjutsu doesn't work: Commander ninjutsu doesn't work/ is very unintuitive (reported by RustyShack / 2018-08-22 01:34:10.968).
- [x] Yuriko, the Tiger's Shadow: Commanderninjitsu does not work.You guys implemented a card that does not work for whatever reason (reported by Iwanabtheguy / 2018-08-22 11:51:02.354).
- [x] fix images download pls: (300 characters max) (reported by Anomen / 2018-08-22 16:38:54.914).
- [x] Xantcha: Xantcha is bugged. She can't be able to attack its owner, but when she's given to another player, she blocks the attacks of /all/ creatures. (reported by RAmaral78 / 2018-08-23 08:35:07.348).
- [x] boreas charger: does nothing (reported by igniteaxiom / 2018-08-24 09:28:56.094).
- [x] Mixed Images: The Images for Combustible Gearhulk and Torrential Gearhulk(both masterpiece versions) are swapped. (reported by FirefoxStormy / 2018-08-24 13:36:29.101).
- [x] Xantcha, Sleeper Agent bugged: The Player owning Xantcha can't be attacked by anyone, not just only by her (reported by Sir1002 / 2018-08-24 19:18:28.94).
- [x] Knight of the Mists: Is missing its non-flanking ability, so is just a 2/2 with flanking for 3. (reported by Badasstodon / 2018-08-21 21:40:09.983).
- [x] Primordial Mist: Primordial Mist's activation text when you hover the mouse over it does not specify this turn. (reported by batman17 / 2018-08-21 06:45:40.539).
