### ISSUE TITLE
GRN - Guilds of Ravnica Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#5294]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Implemented Cards

- [x] Done -- [Affectionate Indrik](https://scryfall.com/search?q=Affectionate+Indrik)
- [x] Done -- [Arboretum Elemental](https://scryfall.com/search?q=Arboretum+Elemental)
- [x] Done -- [Arclight Phoenix](https://scryfall.com/search?q=Arclight+Phoenix)
- [x] Done -- [Artful Takedown](https://scryfall.com/search?q=Artful+Takedown)
- [x] Done -- [Assassin's Trophy](https://scryfall.com/search?q=Assassins+Trophy)
- [x] Done -- [Assemble](https://scryfall.com/search?q=Assemble)
- [x] Done -- [Assure](https://scryfall.com/search?q=Assure)
- [x] Done -- [Attendant of Vraska](https://scryfall.com/search?q=Attendant+of+Vraska)
- [x] Done -- [Aurelia, Exemplar of Justice](https://scryfall.com/search?q=Aurelia,+Exemplar+of+Justice)
- [x] Done -- [Barging Sergeant](https://scryfall.com/search?q=Barging+Sergeant)
- [x] Done -- [Barrier of Bones](https://scryfall.com/search?q=Barrier+of+Bones)
- [x] Done -- [Bartizan Bats](https://scryfall.com/search?q=Bartizan+Bats)
- [x] Done -- [Beacon Bolt](https://scryfall.com/search?q=Beacon+Bolt)
- [x] Done -- [Beamsplitter Mage](https://scryfall.com/search?q=Beamsplitter+Mage)
- [x] Done -- [Beast Whisperer](https://scryfall.com/search?q=Beast+Whisperer)
- [x] Done -- [Blade Instructor](https://scryfall.com/search?q=Blade+Instructor)
- [x] Done -- [Blood Operative](https://scryfall.com/search?q=Blood+Operative)
- [x] Done -- [Book Devourer](https://scryfall.com/search?q=Book+Devourer)
- [x] Done -- [Boros Challenger](https://scryfall.com/search?q=Boros+Challenger)
- [x] Done -- [Boros Guildgate](https://scryfall.com/search?q=Boros+Guildgate)
- [x] Done -- [Boros Guildgate](https://scryfall.com/search?q=Boros+Guildgate)
- [x] Done -- [Boros Locket](https://scryfall.com/search?q=Boros+Locket)
- [x] Done -- [Bounty Agent](https://scryfall.com/search?q=Bounty+Agent)
- [x] Done -- [Bounty of Might](https://scryfall.com/search?q=Bounty+of+Might)
- [x] Done -- [Burglar Rat](https://scryfall.com/search?q=Burglar+Rat)
- [x] Done -- [Camaraderie](https://scryfall.com/search?q=Camaraderie)
- [x] Done -- [Candlelight Vigil](https://scryfall.com/search?q=Candlelight+Vigil)
- [x] Done -- [Capture Sphere](https://scryfall.com/search?q=Capture+Sphere)
- [x] Done -- [Centaur Peacemaker](https://scryfall.com/search?q=Centaur+Peacemaker)
- [x] Done -- [Chamber Sentry](https://scryfall.com/search?q=Chamber+Sentry)
- [x] Done -- [Chance for Glory](https://scryfall.com/search?q=Chance+for+Glory)
- [x] Done -- [Charnel Troll](https://scryfall.com/search?q=Charnel+Troll)
- [x] Done -- [Chemister's Insight](https://scryfall.com/search?q=Chemisters+Insight)
- [x] Done -- [Child of Night](https://scryfall.com/search?q=Child+of+Night)
- [x] Done -- [Chromatic Lantern](https://scryfall.com/search?q=Chromatic+Lantern)
- [x] Done -- [Circuitous Route](https://scryfall.com/search?q=Circuitous+Route)
- [x] Done -- [Citywatch Sphinx](https://scryfall.com/search?q=Citywatch+Sphinx)
- [x] Done -- [Citywide Bust](https://scryfall.com/search?q=Citywide+Bust)
- [x] Done -- [Collar the Culprit](https://scryfall.com/search?q=Collar+the+Culprit)
- [x] Done -- [Command the Storm](https://scryfall.com/search?q=Command+the+Storm)
- [x] Done -- [Conclave Cavalier](https://scryfall.com/search?q=Conclave+Cavalier)
- [x] Done -- [Conclave Guildmage](https://scryfall.com/search?q=Conclave+Guildmage)
- [x] Done -- [Conclave Tribunal](https://scryfall.com/search?q=Conclave+Tribunal)
- [x] Done -- [Concoct](https://scryfall.com/search?q=Concoct)
- [x] Done -- [Connive](https://scryfall.com/search?q=Connive)
- [x] Done -- [Cosmotronic Wave](https://scryfall.com/search?q=Cosmotronic+Wave)
- [x] Done -- [Crackling Drake](https://scryfall.com/search?q=Crackling+Drake)
- [x] Done -- [Creeping Chill](https://scryfall.com/search?q=Creeping+Chill)
- [x] Done -- [Crush Contraband](https://scryfall.com/search?q=Crush+Contraband)
- [x] Done -- [Crushing Canopy](https://scryfall.com/search?q=Crushing+Canopy)
- [x] Done -- [Darkblade Agent](https://scryfall.com/search?q=Darkblade+Agent)
- [x] Done -- [Dawn of Hope](https://scryfall.com/search?q=Dawn+of+Hope)
- [x] Done -- [Dazzling Lights](https://scryfall.com/search?q=Dazzling+Lights)
- [x] Done -- [Dead Weight](https://scryfall.com/search?q=Dead+Weight)
- [x] Done -- [Deadly Visit](https://scryfall.com/search?q=Deadly+Visit)
- [x] Done -- [Deafening Clarion](https://scryfall.com/search?q=Deafening+Clarion)
- [x] Done -- [Demotion](https://scryfall.com/search?q=Demotion)
- [x] Done -- [Devious Cover-up](https://scryfall.com/search?q=Devious+Cover-up)
- [x] Done -- [Devkarin Dissident](https://scryfall.com/search?q=Devkarin+Dissident)
- [x] Done -- [Dimir Guildgate](https://scryfall.com/search?q=Dimir+Guildgate)
- [x] Done -- [Dimir Guildgate](https://scryfall.com/search?q=Dimir+Guildgate)
- [x] Done -- [Dimir Informant](https://scryfall.com/search?q=Dimir+Informant)
- [x] Done -- [Dimir Locket](https://scryfall.com/search?q=Dimir+Locket)
- [x] Done -- [Dimir Spybug](https://scryfall.com/search?q=Dimir+Spybug)
- [x] Done -- [Direct Current](https://scryfall.com/search?q=Direct+Current)
- [x] Done -- [Discovery](https://scryfall.com/search?q=Discovery)
- [x] Done -- [Disdainful Stroke](https://scryfall.com/search?q=Disdainful+Stroke)
- [x] Done -- [Disinformation Campaign](https://scryfall.com/search?q=Disinformation+Campaign)
- [x] Done -- [Dispersal](https://scryfall.com/search?q=Dispersal)
- [x] Done -- [District Guide](https://scryfall.com/search?q=District+Guide)
- [x] Done -- [Divine Visitation](https://scryfall.com/search?q=Divine+Visitation)
- [x] Done -- [Doom Whisperer](https://scryfall.com/search?q=Doom+Whisperer)
- [x] Done -- [Douser of Lights](https://scryfall.com/search?q=Douser+of+Lights)
- [x] Done -- [Dream Eater](https://scryfall.com/search?q=Dream+Eater)
- [x] Done -- [Drowned Secrets](https://scryfall.com/search?q=Drowned+Secrets)
- [x] Done -- [Electrostatic Field](https://scryfall.com/search?q=Electrostatic+Field)
- [x] Done -- [Emmara, Soul of the Accord](https://scryfall.com/search?q=Emmara,+Soul+of+the+Accord)
- [x] Done -- [Enhanced Surveillance](https://scryfall.com/search?q=Enhanced+Surveillance)
- [x] Done -- [Erratic Cyclops](https://scryfall.com/search?q=Erratic+Cyclops)
- [x] Done -- [Erstwhile Trooper](https://scryfall.com/search?q=Erstwhile+Trooper)
- [x] Done -- [Etrata, the Silencer](https://scryfall.com/search?q=Etrata,+the+Silencer)
- [x] Done -- [Expansion](https://scryfall.com/search?q=Expansion)
- [x] Done -- [Experimental Frenzy](https://scryfall.com/search?q=Experimental+Frenzy)
- [x] Done -- [Explosion](https://scryfall.com/search?q=Explosion)
- [x] Done -- [Fearless Halberdier](https://scryfall.com/search?q=Fearless+Halberdier)
- [x] Done -- [Finality](https://scryfall.com/search?q=Finality)
- [x] Done -- [Find](https://scryfall.com/search?q=Find)
- [x] Done -- [Fire Urchin](https://scryfall.com/search?q=Fire+Urchin)
- [x] Done -- [Firemind's Research](https://scryfall.com/search?q=Fireminds+Research)
- [x] Done -- [Flight of Equenauts](https://scryfall.com/search?q=Flight+of+Equenauts)
- [x] Done -- [Flourish](https://scryfall.com/search?q=Flourish)
- [x] Done -- [Flower](https://scryfall.com/search?q=Flower)
- [x] Done -- [Fresh-Faced Recruit](https://scryfall.com/search?q=Fresh-Faced+Recruit)
- [x] Done -- [Garrison Sergeant](https://scryfall.com/search?q=Garrison+Sergeant)
- [x] Done -- [Gatekeeper Gargoyle](https://scryfall.com/search?q=Gatekeeper+Gargoyle)
- [x] Done -- [Gateway Plaza](https://scryfall.com/search?q=Gateway+Plaza)
- [x] Done -- [Generous Stray](https://scryfall.com/search?q=Generous+Stray)
- [x] Done -- [Gird for Battle](https://scryfall.com/search?q=Gird+for+Battle)
- [x] Done -- [Glaive of the Guildpact](https://scryfall.com/search?q=Glaive+of+the+Guildpact)
- [x] Done -- [Glowspore Shaman](https://scryfall.com/search?q=Glowspore+Shaman)
- [x] Done -- [Goblin Banneret](https://scryfall.com/search?q=Goblin+Banneret)
- [x] Done -- [Goblin Cratermaker](https://scryfall.com/search?q=Goblin+Cratermaker)
- [x] Done -- [Goblin Electromancer](https://scryfall.com/search?q=Goblin+Electromancer)
- [x] Done -- [Goblin Locksmith](https://scryfall.com/search?q=Goblin+Locksmith)
- [x] Done -- [Golgari Findbroker](https://scryfall.com/search?q=Golgari+Findbroker)
- [x] Done -- [Golgari Guildgate](https://scryfall.com/search?q=Golgari+Guildgate)
- [x] Done -- [Golgari Guildgate](https://scryfall.com/search?q=Golgari+Guildgate)
- [x] Done -- [Golgari Locket](https://scryfall.com/search?q=Golgari+Locket)
- [x] Done -- [Golgari Raiders](https://scryfall.com/search?q=Golgari+Raiders)
- [x] Done -- [Grappling Sundew](https://scryfall.com/search?q=Grappling+Sundew)
- [x] Done -- [Gravitic Punch](https://scryfall.com/search?q=Gravitic+Punch)
- [x] Done -- [Gruesome Menagerie](https://scryfall.com/search?q=Gruesome+Menagerie)
- [x] Done -- [Guild Summit](https://scryfall.com/search?q=Guild+Summit)
- [x] Done -- [Guildmages' Forum](https://scryfall.com/search?q=Guildmages+Forum)
- [x] Done -- [Haazda Marshal](https://scryfall.com/search?q=Haazda+Marshal)
- [x] Done -- [Hammer Dropper](https://scryfall.com/search?q=Hammer+Dropper)
- [x] Done -- [Hatchery Spider](https://scryfall.com/search?q=Hatchery+Spider)
- [x] Done -- [Healer's Hawk](https://scryfall.com/search?q=Healers+Hawk)
- [x] Done -- [Hellkite Whelp](https://scryfall.com/search?q=Hellkite+Whelp)
- [x] Done -- [Hired Poisoner](https://scryfall.com/search?q=Hired+Poisoner)
- [x] Done -- [Hitchclaw Recluse](https://scryfall.com/search?q=Hitchclaw+Recluse)
- [x] Done -- [House Guildmage](https://scryfall.com/search?q=House+Guildmage)
- [x] Done -- [Hunted Witness](https://scryfall.com/search?q=Hunted+Witness)
- [x] Done -- [Hypothesizzle](https://scryfall.com/search?q=Hypothesizzle)
- [x] Done -- [Impervious Greatwurm](https://scryfall.com/search?q=Impervious+Greatwurm)
- [x] Done -- [Inescapable Blaze](https://scryfall.com/search?q=Inescapable+Blaze)
- [x] Done -- [Inspiring Unicorn](https://scryfall.com/search?q=Inspiring+Unicorn)
- [x] Done -- [Integrity](https://scryfall.com/search?q=Integrity)
- [x] Done -- [Intervention](https://scryfall.com/search?q=Intervention)
- [x] Done -- [Intrusive Packbeast](https://scryfall.com/search?q=Intrusive+Packbeast)
- [x] Done -- [Invent](https://scryfall.com/search?q=Invent)
- [x] Done -- [Invert](https://scryfall.com/search?q=Invert)
- [x] Done -- [Ionize](https://scryfall.com/search?q=Ionize)
- [x] Done -- [Ironshell Beetle](https://scryfall.com/search?q=Ironshell+Beetle)
- [x] Done -- [Izoni, Thousand-Eyed](https://scryfall.com/search?q=Izoni,+Thousand-Eyed)
- [x] Done -- [Izzet Guildgate](https://scryfall.com/search?q=Izzet+Guildgate)
- [x] Done -- [Izzet Guildgate](https://scryfall.com/search?q=Izzet+Guildgate)
- [x] Done -- [Izzet Locket](https://scryfall.com/search?q=Izzet+Locket)
- [x] Done -- [Join Shields](https://scryfall.com/search?q=Join+Shields)
- [x] Done -- [Justice Strike](https://scryfall.com/search?q=Justice+Strike)
- [x] Done -- [Knight of Autumn](https://scryfall.com/search?q=Knight+of+Autumn)
- [x] Done -- [Kraul Foragers](https://scryfall.com/search?q=Kraul+Foragers)
- [x] Done -- [Kraul Harpooner](https://scryfall.com/search?q=Kraul+Harpooner)
- [x] Done -- [Kraul Raider](https://scryfall.com/search?q=Kraul+Raider)
- [x] Done -- [Kraul Swarm](https://scryfall.com/search?q=Kraul+Swarm)
- [x] Done -- [Lava Coil](https://scryfall.com/search?q=Lava+Coil)
- [x] Done -- [Lazav, the Multifarious](https://scryfall.com/search?q=Lazav,+the+Multifarious)
- [x] Done -- [League Guildmage](https://scryfall.com/search?q=League+Guildmage)
- [x] Done -- [Leapfrog](https://scryfall.com/search?q=Leapfrog)
- [x] Done -- [Ledev Champion](https://scryfall.com/search?q=Ledev+Champion)
- [x] Done -- [Ledev Guardian](https://scryfall.com/search?q=Ledev+Guardian)
- [x] Done -- [Legion Guildmage](https://scryfall.com/search?q=Legion+Guildmage)
- [x] Done -- [Legion Warboss](https://scryfall.com/search?q=Legion+Warboss)
- [x] Done -- [Light of the Legion](https://scryfall.com/search?q=Light+of+the+Legion)
- [x] Done -- [Lotleth Giant](https://scryfall.com/search?q=Lotleth+Giant)
- [x] Done -- [Loxodon Restorer](https://scryfall.com/search?q=Loxodon+Restorer)
- [x] Done -- [Luminous Bonds](https://scryfall.com/search?q=Luminous+Bonds)
- [x] Done -- [Maniacal Rage](https://scryfall.com/search?q=Maniacal+Rage)
- [x] Done -- [March of the Multitudes](https://scryfall.com/search?q=March+of+the+Multitudes)
- [x] Done -- [Mausoleum Secrets](https://scryfall.com/search?q=Mausoleum+Secrets)
- [x] Done -- [Maximize Altitude](https://scryfall.com/search?q=Maximize+Altitude)
- [x] Done -- [Maximize Velocity](https://scryfall.com/search?q=Maximize+Velocity)
- [x] Done -- [Mephitic Vapors](https://scryfall.com/search?q=Mephitic+Vapors)
- [x] Done -- [Midnight Reaper](https://scryfall.com/search?q=Midnight+Reaper)
- [x] Done -- [Might of the Masses](https://scryfall.com/search?q=Might+of+the+Masses)
- [x] Done -- [Mission Briefing](https://scryfall.com/search?q=Mission+Briefing)
- [x] Done -- [Mnemonic Betrayal](https://scryfall.com/search?q=Mnemonic+Betrayal)
- [x] Done -- [Molderhulk](https://scryfall.com/search?q=Molderhulk)
- [x] Done -- [Moodmark Painter](https://scryfall.com/search?q=Moodmark+Painter)
- [x] Done -- [Murmuring Mystic](https://scryfall.com/search?q=Murmuring+Mystic)
- [x] Done -- [Muse Drake](https://scryfall.com/search?q=Muse+Drake)
- [x] Done -- [Narcomoeba](https://scryfall.com/search?q=Narcomoeba)
- [x] Done -- [Necrotic Wound](https://scryfall.com/search?q=Necrotic+Wound)
- [x] Done -- [Never Happened](https://scryfall.com/search?q=Never+Happened)
- [x] Done -- [Nightveil Predator](https://scryfall.com/search?q=Nightveil+Predator)
- [x] Done -- [Nightveil Sprite](https://scryfall.com/search?q=Nightveil+Sprite)
- [x] Done -- [Niv-Mizzet, Parun](https://scryfall.com/search?q=Niv-Mizzet,+Parun)
- [x] Done -- [Notion Rain](https://scryfall.com/search?q=Notion+Rain)
- [x] Done -- [Nullhide Ferox](https://scryfall.com/search?q=Nullhide+Ferox)
- [x] Done -- [Ochran Assassin](https://scryfall.com/search?q=Ochran+Assassin)
- [x] Done -- [Omnispell Adept](https://scryfall.com/search?q=Omnispell+Adept)
- [x] Done -- [Ornery Goblin](https://scryfall.com/search?q=Ornery+Goblin)
- [x] Done -- [Overgrown Tomb](https://scryfall.com/search?q=Overgrown+Tomb)
- [x] Done -- [Pack's Favor](https://scryfall.com/search?q=Packs+Favor)
- [x] Done -- [Parhelion Patrol](https://scryfall.com/search?q=Parhelion+Patrol)
- [x] Done -- [Passwall Adept](https://scryfall.com/search?q=Passwall+Adept)
- [x] Done -- [Pause for Reflection](https://scryfall.com/search?q=Pause+for+Reflection)
- [x] Done -- [Pelt Collector](https://scryfall.com/search?q=Pelt+Collector)
- [x] Done -- [Pilfering Imp](https://scryfall.com/search?q=Pilfering+Imp)
- [x] Done -- [Piston-Fist Cyclops](https://scryfall.com/search?q=Piston-Fist+Cyclops)
- [x] Done -- [Pitiless Gorgon](https://scryfall.com/search?q=Pitiless+Gorgon)
- [x] Done -- [Plaguecrafter](https://scryfall.com/search?q=Plaguecrafter)
- [x] Done -- [Portcullis Vine](https://scryfall.com/search?q=Portcullis+Vine)
- [x] Done -- [Precision Bolt](https://scryfall.com/search?q=Precision+Bolt)
- [x] Done -- [Prey Upon](https://scryfall.com/search?q=Prey+Upon)
- [x] Done -- [Price of Fame](https://scryfall.com/search?q=Price+of+Fame)
- [x] Done -- [Quasiduplicate](https://scryfall.com/search?q=Quasiduplicate)
- [x] Done -- [Radical Idea](https://scryfall.com/search?q=Radical+Idea)
- [x] Done -- [Ral's Dispersal](https://scryfall.com/search?q=Rals+Dispersal)
- [x] Done -- [Ral's Staticaster](https://scryfall.com/search?q=Rals+Staticaster)
- [x] Done -- [Ral, Caller of Storms](https://scryfall.com/search?q=Ral,+Caller+of+Storms)
- [x] Done -- [Ral, Izzet Viceroy](https://scryfall.com/search?q=Ral,+Izzet+Viceroy)
- [x] Done -- [Rampaging Monument](https://scryfall.com/search?q=Rampaging+Monument)
- [x] Done -- [Response](https://scryfall.com/search?q=Response)
- [x] Done -- [Resurgence](https://scryfall.com/search?q=Resurgence)
- [x] Done -- [Rhizome Lurcher](https://scryfall.com/search?q=Rhizome+Lurcher)
- [x] Done -- [Righteous Blow](https://scryfall.com/search?q=Righteous+Blow)
- [x] Done -- [Risk Factor](https://scryfall.com/search?q=Risk+Factor)
- [x] Done -- [Ritual of Soot](https://scryfall.com/search?q=Ritual+of+Soot)
- [x] Done -- [Roc Charger](https://scryfall.com/search?q=Roc+Charger)
- [x] Done -- [Rosemane Centaur](https://scryfall.com/search?q=Rosemane+Centaur)
- [x] Done -- [Rubblebelt Boar](https://scryfall.com/search?q=Rubblebelt+Boar)
- [x] Done -- [Runaway Steam-Kin](https://scryfall.com/search?q=Runaway+Steam-Kin)
- [x] Done -- [Sacred Foundry](https://scryfall.com/search?q=Sacred+Foundry)
- [x] Done -- [Selective Snare](https://scryfall.com/search?q=Selective+Snare)
- [x] Done -- [Selesnya Guildgate](https://scryfall.com/search?q=Selesnya+Guildgate)
- [x] Done -- [Selesnya Guildgate](https://scryfall.com/search?q=Selesnya+Guildgate)
- [x] Done -- [Selesnya Locket](https://scryfall.com/search?q=Selesnya+Locket)
- [x] Done -- [Severed Strands](https://scryfall.com/search?q=Severed+Strands)
- [x] Done -- [Siege Wurm](https://scryfall.com/search?q=Siege+Wurm)
- [x] Done -- [Silent Dart](https://scryfall.com/search?q=Silent+Dart)
- [x] Done -- [Sinister Sabotage](https://scryfall.com/search?q=Sinister+Sabotage)
- [x] Done -- [Skyknight Legionnaire](https://scryfall.com/search?q=Skyknight+Legionnaire)
- [x] Done -- [Skyline Scout](https://scryfall.com/search?q=Skyline+Scout)
- [x] Done -- [Smelt-Ward Minotaur](https://scryfall.com/search?q=Smelt-Ward+Minotaur)
- [x] Done -- [Sonic Assault](https://scryfall.com/search?q=Sonic+Assault)
- [x] Done -- [Spinal Centipede](https://scryfall.com/search?q=Spinal+Centipede)
- [x] Done -- [Sprouting Renewal](https://scryfall.com/search?q=Sprouting+Renewal)
- [x] Done -- [Statue](https://scryfall.com/search?q=Statue)
- [x] Done -- [Status](https://scryfall.com/search?q=Status)
- [x] Done -- [Steam Vents](https://scryfall.com/search?q=Steam+Vents)
- [x] Done -- [Street Riot](https://scryfall.com/search?q=Street+Riot)
- [x] Done -- [Sumala Woodshaper](https://scryfall.com/search?q=Sumala+Woodshaper)
- [x] Done -- [Sunhome Stalwart](https://scryfall.com/search?q=Sunhome+Stalwart)
- [x] Done -- [Sure Strike](https://scryfall.com/search?q=Sure+Strike)
- [x] Done -- [Swarm Guildmage](https://scryfall.com/search?q=Swarm+Guildmage)
- [x] Done -- [Swathcutter Giant](https://scryfall.com/search?q=Swathcutter+Giant)
- [x] Done -- [Swiftblade Vindicator](https://scryfall.com/search?q=Swiftblade+Vindicator)
- [x] Done -- [Sworn Companions](https://scryfall.com/search?q=Sworn+Companions)
- [x] Done -- [Tajic, Legion's Edge](https://scryfall.com/search?q=Tajic,+Legions+Edge)
- [x] Done -- [Take Heart](https://scryfall.com/search?q=Take+Heart)
- [x] Done -- [Temple Garden](https://scryfall.com/search?q=Temple+Garden)
- [x] Done -- [Tenth District Guard](https://scryfall.com/search?q=Tenth+District+Guard)
- [x] Done -- [Thief of Sanity](https://scryfall.com/search?q=Thief+of+Sanity)
- [x] Done -- [Thought Erasure](https://scryfall.com/search?q=Thought+Erasure)
- [x] Done -- [Thoughtbound Phantasm](https://scryfall.com/search?q=Thoughtbound+Phantasm)
- [x] Done -- [Thousand-Year Storm](https://scryfall.com/search?q=Thousand-Year+Storm)
- [x] Done -- [Torch Courier](https://scryfall.com/search?q=Torch+Courier)
- [x] Done -- [Trostani Discordant](https://scryfall.com/search?q=Trostani+Discordant)
- [x] Done -- [Truefire Captain](https://scryfall.com/search?q=Truefire+Captain)
- [x] Done -- [Undercity Necrolisk](https://scryfall.com/search?q=Undercity+Necrolisk)
- [x] Done -- [Undercity Uprising](https://scryfall.com/search?q=Undercity+Uprising)
- [x] Done -- [Underrealm Lich](https://scryfall.com/search?q=Underrealm+Lich)
- [x] Done -- [Unexplained Disappearance](https://scryfall.com/search?q=Unexplained+Disappearance)
- [x] Done -- [Unmoored Ego](https://scryfall.com/search?q=Unmoored+Ego)
- [x] Done -- [Urban Utopia](https://scryfall.com/search?q=Urban+Utopia)
- [x] Done -- [Vedalken Mesmerist](https://scryfall.com/search?q=Vedalken+Mesmerist)
- [x] Done -- [Veiled Shade](https://scryfall.com/search?q=Veiled+Shade)
- [x] Done -- [Venerated Loxodon](https://scryfall.com/search?q=Venerated+Loxodon)
- [x] Done -- [Vernadi Shieldmate](https://scryfall.com/search?q=Vernadi+Shieldmate)
- [x] Done -- [Vicious Rumors](https://scryfall.com/search?q=Vicious+Rumors)
- [x] Done -- [Vigorspore Wurm](https://scryfall.com/search?q=Vigorspore+Wurm)
- [x] Done -- [Vivid Revival](https://scryfall.com/search?q=Vivid+Revival)
- [x] Done -- [Vraska's Stoneglare](https://scryfall.com/search?q=Vraskas+Stoneglare)
- [x] Done -- [Vraska, Golgari Queen](https://scryfall.com/search?q=Vraska,+Golgari+Queen)
- [x] Done -- [Vraska, Regal Gorgon](https://scryfall.com/search?q=Vraska,+Regal+Gorgon)
- [x] Done -- [Wall of Mist](https://scryfall.com/search?q=Wall+of+Mist)
- [x] Done -- [Wand of Vertebrae](https://scryfall.com/search?q=Wand+of+Vertebrae)
- [x] Done -- [Wary Okapi](https://scryfall.com/search?q=Wary+Okapi)
- [x] Done -- [Watcher in the Mist](https://scryfall.com/search?q=Watcher+in+the+Mist)
- [x] Done -- [Watery Grave](https://scryfall.com/search?q=Watery+Grave)
- [x] Done -- [Wee Dragonauts](https://scryfall.com/search?q=Wee+Dragonauts)
- [x] Done -- [Whisper Agent](https://scryfall.com/search?q=Whisper+Agent)
- [x] Done -- [Whispering Snitch](https://scryfall.com/search?q=Whispering+Snitch)
- [x] Done -- [Wild Ceratok](https://scryfall.com/search?q=Wild+Ceratok)
- [x] Done -- [Wishcoin Crab](https://scryfall.com/search?q=Wishcoin+Crab)
- [x] Done -- [Wojek Bodyguard](https://scryfall.com/search?q=Wojek+Bodyguard)
- [x] Done -- [Worldsoul Colossus](https://scryfall.com/search?q=Worldsoul+Colossus)

**Comment by theelk801** [comment]
# Implemented Cards

- [x] Done -- [Impervious Greatwurm](https://scryfall.com/search?q=Impervious+Greatwurm)
- [x] Done -- [Narcomoeba](https://scryfall.com/search?q=Narcomoeba)
- [x] Done -- [Overgrown Tomb](https://scryfall.com/search?q=Overgrown+Tomb)
- [x] Done -- [Sacred Foundry](https://scryfall.com/search?q=Sacred+Foundry)
- [x] Done -- [Steam Vents](https://scryfall.com/search?q=Steam+Vents)
- [x] Done -- [Temple Garden](https://scryfall.com/search?q=Temple+Garden)
- [x] Done -- [Watery Grave](https://scryfall.com/search?q=Watery+Grave)
- [ ] In progress -- [Boros Challenger](https://scryfall.com/search?q=Boros+Challenger)
- [ ] In progress -- [Conclave Tribunal](https://scryfall.com/search?q=Conclave+Tribunal)
- [ ] In progress -- [Emmara, Soul of the Accord](https://scryfall.com/search?q=Emmara,+Soul+of+the+Accord)
- [ ] In progress -- [Legion Warboss](https://scryfall.com/search?q=Legion+Warboss)
- [ ] In progress -- [Necrotic Wound](https://scryfall.com/search?q=Necrotic+Wound)
- [ ] In progress -- [Quasiduplicate](https://scryfall.com/search?q=Quasiduplicate)
- [ ] In progress -- [Ral, Izzet Viceroy](https://scryfall.com/search?q=Ral,+Izzet+Viceroy)
- [ ] In progress -- [Sinister Sabotage](https://scryfall.com/search?q=Sinister+Sabotage)
- [ ] In progress -- [Thought Erasure](https://scryfall.com/search?q=Thought+Erasure)
- [ ] In progress -- [Underrealm Lich](https://scryfall.com/search?q=Underrealm+Lich)

**Comment by theelk801** [comment]
@Ryan-Saklad are you still working on those cards you checked off?

**Comment by themogwi** [comment]
* [x]  In Progress -- Plaguecrafter

**Comment by Ryan-Saklad** [comment]
@theelk801, sorry, I finished them and sent a commit request for them.

**Comment by theelk801** [comment]
Did you try to commit here or to your fork? You have to commit it to your fork and then open a pull request.

**Comment by Ryan-Saklad** [comment]
Ok, did that work?

**Comment by theelk801** [comment]
Yeah, perfect. I've merged it, thanks for your contributions.
