### ISSUE TITLE
Feedback XMage Version 1.4.31V2-

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5336]
# Feedback 1.4.31V2-

- [x] Piston Fist Cyclops bugged: Doesn't gain the ability to attack when you cast an instant or sorcery spell. (reported by spec_1 / 2018-09-23 00:44:51.334).
- [x] Game rolls back when trying to jump-start Radical Idea: Pretty much the title. I haven't been able to try to cast any other jump-start cards so far but who knows. (reported by Traxgarte / 2018-09-23 01:13:05.102).
- [x] Pelt Collector: Pelt collector not gaining counter when a creature dies (reported by PPtime / 2018-09-23 01:22:59.234).
- [x] Pelt Collector Death Trigger Didnt Work: Pelt Collectors death trigger didnt work when a 3/2 Merfolk Branchwalker was killed by a Ravenous Chupacabra (reported by iWearDiaper / 2018-09-23 01:23:07.906).
- [x] Jump Start cards appear to be bugged: Played two matches with GRN. Opponents have used the Jump Start ability on two different cards (Risk Factor and Chemister's Insight), and both times it caused the game to loop back to the beginning of the current turn. (reported by dcperry / 2018-09-23 01:26:02.007).
- [x] Enhanced Surveillance being symmetrical: title (reported by Traxgarte / 2018-09-23 01:47:51.75).
- [x] Beacon Bolt lacks a target: Title (reported by Traxgarte / 2018-09-23 01:55:35.329).
- [x] Dimir Spybug did not get a 1/1 counter when I surveiled with Dimir Informant: (300 characters max) (reported by Shunamoney / 2018-09-23 02:12:44.204).
- [x] grn card bugged: Camaraderie does not work, does nothing :( (reported by LordOddWar / 2018-09-23 02:17:53.285).
- [x] piston fist cyclops: cant attack after casting inst/sorc (reported by jodosal / 2018-09-23 02:27:40.104).
- [x] [Bug] GRN mechanics: Great job getting the cards in so fast!2 bugs with dimir faction i noticed.Dimir spybug's triggered ability doesn't proc (counter when scry)Lazav's activated ability seems to return him to hand after showing n error in a pop up dialogue box (reported by Aria / 2018-09-23 02:49:26.369).
- [x] jump start: https://app.roll20.net/lfg/listing/52340/the-black-horse-tavern-5e-campaign-p2p (reported by jodosal / 2018-09-23 03:09:52.578).
- [x] Jump Start using Risk Factor: Had a game error twice in a row after the roll back. Using the card work the first time, then jump starting it when the opponent selects the mode it bugs and rollsback. (reported by Chowning / 2018-09-23 03:14:28.155).
- [x] Help: (300 characters max)blood operative did not trigger off of doom whisperer (reported by Heartwood / 2018-09-23 03:29:16.925).
- [x] Help!: Dimir spybug did not trigger off of doom whisperer (reported by Heartwood / 2018-09-23 03:30:00.453).
- [x] Different types of mulligan: I think that it would be really cool to have to option to have different from just additional free mulls. (reported by ujmyhntgbrfv / 2018-09-23 03:50:47.381).
- [x] Maximize Velocity says it gives flying: In the tooltip for maximize velocity it says it gives flying rather than haste (reported by Chowning / 2018-09-23 04:38:01.383).
- [x] Runaway Steam Kin: Gets a +1 counter for any color spell instead of just red (reported by batman17 / 2018-09-23 05:50:37.367).
- [x] Beacon Bolt: Would not let me target then bugged when i tried to kick start it (reported by batman17 / 2018-09-23 05:52:18.259).
- [x] chemister's insight: can't jump-start this card (reported by Krebsy / 2018-09-23 05:59:53.07).
- [x] Never Happened: Did not let me exile a card (reported by batman17 / 2018-09-23 06:02:22.939).
- [x] jump-start: doesn't work on most cards (reported by Krebsy / 2018-09-23 06:08:36.381).
- [x] Selesnya Locket: Should tap for G and W, not G and R, please fix (reported by TestofAdam / 2018-09-23 06:12:40.437).
- [x] dimir spybug: doesn't trigger after surveil (reported by Telandril / 2018-09-23 06:16:18.639).
- [x] Selesnya Locket: Taps for red mana but not white (reported by batman17 / 2018-09-23 06:42:54.598).
- [x] GRN card bugs: Truefire captain is bugged, targetting throws exception popupBeacon bolt doesnt deal any damage (reported by Rybsson / 2018-09-23 09:01:19.723).
- [x] legion warboss: when my goblin token went to untap the turn after it was created, i got a prompt saying the untap had been replaced by giving it 2 +1/+1 counters (reported by h1jack / 2018-09-23 09:31:16.137).
- [x] Card is not working: Camaraderie GRN doesn't work, pay mana for air :p (reported by Ramia94 / 2018-09-23 09:55:30.497).
- [x] GRN card bug - comraderie: it just doesnt work, does nothing (reported by Rybsson / 2018-09-23 10:14:53.635).
- [x] "Never Happened" GRN - doesnt wokr: The card Never Happened (GRN) does not let u discard/exile teh card from opponents hand (reported by Hincu / 2018-09-23 12:28:23.615).
- [x] Vicious Rumors: crashed the game (reported by batman17 / 2018-09-23 13:39:20.512). 
**LevelX2: Can't reproduce a problem in duel.**
- [x] bug: Bounty of Might cost 4GG mana not 3GG (reported by DanielD / 2018-09-23 15:53:47.733).
- [x] mentor: doesn't work exept with aurelia (not for goblin banneret and legendary boros soldier 1WR (reported by sciacquone / 2018-09-23 16:09:43.216).
- [x] Mentor doesn't trigger: Hi, testing boros cards we have seen that mentor doesn't trigger in goblin banneret and Tajic. We have seen that Aurelia trigger. We don't know about other cards (reported by DTZebas / 2018-09-23 16:24:33.333).
- [x] Jump-Start: Does not work (reported by n1ckmerlin / 2018-09-23 16:40:58.242).
- [x] Bug: Beacon Bolt dosn't target (reported by Wigglyfish2 / 2018-09-23 17:18:23.005).

**Comment by LevelX2** [comment]
XMage 1.4.31V3a

- [ ] invert//invent: on invert, it does not specify until end of turn but it is coded as until end of turn (reported by jodosal / 2018-09-23 21:10:43.671).
- [ ] bugg genesis wave: i have view cards pick first and stack end all cards go to grave and noting in the bord... (reported by blaisfm / 2018-09-23 21:30:47.354).
- [ ] kraul harpooner: May have a bug where the fight from harpooner doesn't work. opponent did it so im not sure if its a misclick (reported by jodosal / 2018-09-23 21:38:47.891).
- [ ] Kraul Harpooner: Does not get +X/X Thanks :D (reported by Flamzy / 2018-09-23 23:16:28.507).
- [ ] Declare Blockers.: Cant Cast Spells During Declare Blockers (reported by Arctuated / 2018-09-23 23:46:51.658).
- [ ] Jump Start cards not exiling when countered: Jump Start cards are casting properly from the graveyard now, but when they are cast from the graveyard and countered, they return to the graveyard rather than being exiled. (reported by dcperry / 2018-09-24 00:04:12.937).
- [ ] Etrata doesnt win the game: My opponent had 3 Creatures with Hit Counters in their exile and i did not win the game.Pls fix (reported by MLGMtnDewritos / 2018-09-24 00:08:10.201).
- [ ] Expansion // Explosion Bug: (300 characters max)Expansion // Explosion "Explosion" deals X damage to the the targeted player instead of drawing only x Cards (reported by Tooxie / 2018-09-24 00:41:06.028).
- [ ] kraul harpooner: 1 creature in graveyard, played kraul harpooner, didnt trigger +1 to fight. Fought opposing creature and died anyway. (reported by Zox / 2018-09-24 01:52:46.405).
- [ ] Kick: The ablity to kick someone who is stalling a game or went afk (reported by redrider23 / 2018-09-24 02:29:06.814).
- [ ] Revoker on Mox Diamond: Phyrexian Revoker's ability doesn't properly stop Mox Diamond's mana ability (reported by anicebed / 2018-09-24 03:07:18.61).
- [ ] Bug Mnemonic Betrayal: Mnemonic Betrayal doesn't return the cards that weren't castto the graveyard end of turn. (reported by Boing / 2018-09-24 13:28:44.667).
- [ ] Glowspore Shaman: Glowspore Shaman gives an error code if there is no land in the graveyard. (reported by Bob49 / 2018-09-24 13:40:06.237).
- [ ] Caged Sun's rules text is wrong: Caged sun correctly only adds mana when lands I control are tapped, but the popup rules text doesn't say that (reported by DerLhurgoyf / 2018-09-24 15:06:23.887).
- [ ] Invert // Invent Bug: Invert part of Invert // Invent doesnt work correctly if you select 2 targets. 1 target works. (reported by Tooxie / 2018-09-24 16:47:12.408).
- [ ] plague crafter bug: plaguecrafter allows players to sac any permanent rather than only a creature or planeswalker (reported by No1OConsequens / 2018-09-24 23:27:53.057).
- [ ] wojek bodyguard: attempting to attack alone with wojek creates a stream of popups (reported by h1jack / 2018-09-24 23:49:22.618).
- [ ] Whispering Snitch: the trigger occurs when an opponent surveils and it should not be that way, only the controller should get the trigger (reported by TestofAdam / 2018-09-25 01:40:16.09).
- [ ] Kraul Harpooner not working: My opponent used Kraul Harpooner on one of my creatures. It didn't gain power from undergrowth, so when they fought his creature couldn't kill my flyer. (reported by dabomb59014 / 2018-09-25 05:38:11.473).
- [ ] Blood Sun: Since RIX, taplands should come into play untapped with Blood Sun, but that's not how the card behaves in xmage (reported by Traxgarte / 2018-09-25 10:34:51.351).
- [ ] Mnemoric Betrayal (GRN) Bug: When you cast mnemoric betrayal and try to cast cards from an opponents graveyard, you have to pay the normal costs, instead of any color (reported by Sliveroverlord / 2018-09-25 11:48:53.958).
- [ ] Shivan Reef is Bugged: Shivan Reef will only add colorless mana (reported by jblakeley / 2018-09-25 16:35:16.525).
- [ ] Glaive of the Guildpact Bugged: Glaive of the Guildpacts (GRN)'s first ability doesn't work. The creature doesn't get a power boost. (reported by spec_1 / 2018-09-25 17:08:40.336).
- [ ] Disregard last note: Glaive of the guildpact does work, I read it wrong. (reported by spec_1 / 2018-09-25 17:11:10.805).
- [ ] conclave guildmage: creates the wrong token with second activated ability (reported by h1jack / 2018-09-25 19:27:14.675).
- [ ] Experimental Frenzy Bug: Experimental Frenzy reads "You can't play cards from your hand". But you can in the client (reported by DeZacc / 2018-09-25 20:12:17.431).
- [ ] Expansion//Explosion is bugged: Explosion is dealing the player drawing cards damage in addition to the first target. (reported by Hix360 / 2018-09-25 21:18:30.901).
- [ ] Fight with Fire is bugged: When copying a kicked version of Fight with Fire(With Expansion or Primal Wellspring), if the original Fight with Fire is countered, the copy only deals 5 damage instead of 10. (reported by Hix360 / 2018-09-25 21:20:02.83).
- [ ] invert: this side doesn't work and is coded as until end of turn (reported by jodosal / 2018-09-25 23:36:38.113).
- [ ] Players limit on servers: I'm sure different servers are intended to support all the countries with plaing xmage, but the european server is flooded with non european players, which may causes some serious lags, seperate them please, it is unplayable (reported by Stahlwolle / 2018-09-26 00:46:08.365).
- [ ] detection tower: detection tower doesnt remove hexproof from players (reported by Rybsson / 2018-09-26 00:58:59.325).
- [ ] BUG WITH Demanding Dragon: Demanding Draogn was not able to target the opponent properly. (reported by Exul / 2018-09-26 01:02:48.417).
- [ ] selvala, heart of the wilds: With some creatures it quadruples the amount of mana, like in a special case with nylea god of the hunt, fix that (reported by Stahlwolle / 2018-09-26 01:30:47.378).
- [ ] Horobi shouldn't trigger of Animate Dead: Horobi was in play and a player cast Animate Dead. Horboi would trigger to destroy that creature. (reported by DerLhurgoyf / 2018-09-26 04:18:16.802).
- [ ] Images for commander 2018 wont work for me: I downloaded from scryfall many times (reported by HanzeeMalvo / 2018-09-26 07:33:00.958).

**Comment by LevelX2** [comment]
# XMage 1.4.31V3b

- [ ] Server lag: Serious Server problems in EVERY game round! (reported by AustrianErb / 2018-09-26 12:32:35.518).
- [ ] Yuriko bug: She's still bugged. I can put her on the stack for her ninjitsu ability but when i try to pay the mana it removes her ability form the stack. (reported by JaptainCack / 2018-09-26 15:48:37.981).
- [ ] Wrong Text: Quest for the Goblin Lord's Text is not Creature, it's Goblin (reported by AustrianErb / 2018-09-26 23:24:49.212).
- [ ] Missio Brefing Not working: Caast mission briefing targetting Connive/Conoct but I can not play it from the graveyard. (reported by viginti / 2018-09-27 13:02:48.584).
- [ ] Xmage : review: Xmage is fantastic, it has become better and better. It's a much cleaner faster way to play than MTGO online.well done ! (reported by JBE / 2018-09-27 14:18:10.093).
- [ ] Stuck losing time without priority: Every once in a while I am stuck with my timer ticking down but no way to continue the game. No buttons to either cast spells or pass prio. (reported by spec_1 / 2018-09-27 14:44:56.485).
- [ ] Mnemonic Betrayal Doesn't work: Mnemonic Betrayal from GRN has a bug that doesn't let you cast mana of any color to pay for exiled spells. (reported by spec_1 / 2018-09-27 15:15:50.652).
- [ ] Win %: Hi! Would it be possible to implement a win % for the player?Perhaps an overall win % or divided into limited and contructed (reported by _Ezekiel_ / 2018-09-27 15:38:02.979).
- [ ] Wand of Vertebrae Trigger: The 2nd ability of Wand of Vertebrae from GRN does not work. You are able to target the cards but it does not shuffle them back into your deck. (reported by Action_B4st4rd / 2018-09-27 16:12:34.943).
- [ ] Doubling season: Doubling season did not double counters onto planeswalker in a modern game (reported by not_thrilled / 2018-09-27 21:08:00.568).
- [ ] Ajani, Adversary of tyrants: =+1 ability says creature instead of creatures (reported by Wigglyfish2 / 2018-09-28 01:46:52.531).
- [ ] Experimental Frenzy's play-from-hand restriction doesn't work: Experimental Frenzy's play-from-hand restriction doesn't work (reported by Jernau_Gurgeh / 2018-09-28 03:06:06.252).
- [ ] mnemonic betrayal: can't use mana as though it were mana of any color (reported by h1jack / 2018-09-28 05:14:56.269).
- [ ] premature deckbuilding submit: I was playing Sealed with the new Ravnica set, building my deck, when I had 30 seconds left on the clock and was about to submit my deck, when the game client prematurely ended the deckbuilding session. I am sure it was not caused by lag. (reported by bhegstad / 2018-09-28 12:46:50.543).
- [ ] Failure to load card images: I have downloaded card images for Guilds of Ravnica, but the card images will not load in-game. (reported by bhegstad / 2018-09-28 12:47:33.064).
- [ ] Varska, golgari queen bug: Varska, golgari queens ultimate doesnt not work, opponent wont lose the game (reported by Klotu / 2018-09-28 13:07:34.296).
- [ ] beamsplitter mage bugged: Beamsplitter mage forces the owner to target opponent's creatures with spell copies when the owner only controls Beamsplitter Mage and no other creatures. (reported by bhegstad / 2018-09-28 18:06:47.264).
- [ ] Mission briefing: Hi,Tryed to play "Missin briefing" several times now. Seems not to work, i choose an instant or sorcery in my grave, but nothing happpens. This card is really strong can you fix it please ? Thanks in advance (reported by jull / 2018-09-28 18:52:22.57).
- [ ] plaguecrafter, Jump-start: asks to choose target permanent.when a jump-start card is cast from the graveyard, and then countered, it goes back into the graveyard rather than being exiled. (reported by MightyPhysche / 2018-09-29 04:32:24.966).
- [ ] tournament deck editing: during sealed or draft you should be allowed to change yourdeck with the available side board cards you have availableto you. (reported by MightyPhysche / 2018-09-29 04:34:11.273).

**Comment by awjackson** [comment]
Remaining checkboxes are duplicates of tracked issues (i.e. #4202) or are feature requests, so I'm closing this.
