### ISSUE TITLE
USG - Urza's Saga Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5376]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/urzas-saga)

# Cards in set:

- [x] [Absolute Grace](https://magiccards.info/query?q=!Absolute+Grace)
- [x] [Absolute Law](https://magiccards.info/query?q=!Absolute+Law)
- [x] [Abundance](https://magiccards.info/query?q=!Abundance)
- [x] [Abyssal Horror](https://magiccards.info/query?q=!Abyssal+Horror)
- [x] [Academy Researchers](https://magiccards.info/query?q=!Academy+Researchers)
- [x] [Acidic Soil](https://magiccards.info/query?q=!Acidic+Soil)
- [x] [Acridian](https://magiccards.info/query?q=!Acridian)
- [x] [Albino Troll](https://magiccards.info/query?q=!Albino+Troll)
- [x] [Anaconda](https://magiccards.info/query?q=!Anaconda)
- [x] [Angelic Chorus](https://magiccards.info/query?q=!Angelic+Chorus)
- [x] [Angelic Page](https://magiccards.info/query?q=!Angelic+Page)
- [x] [Annul](https://magiccards.info/query?q=!Annul)
- [x] [Antagonism](https://magiccards.info/query?q=!Antagonism)
- [x] [Arc Lightning](https://magiccards.info/query?q=!Arc+Lightning)
- [x] [Arcane Laboratory](https://magiccards.info/query?q=!Arcane+Laboratory)
- [x] [Argothian Elder](https://magiccards.info/query?q=!Argothian+Elder)
- [x] [Argothian Enchantress](https://magiccards.info/query?q=!Argothian+Enchantress)
- [x] [Argothian Swine](https://magiccards.info/query?q=!Argothian+Swine)
- [x] [Argothian Wurm](https://magiccards.info/query?q=!Argothian+Wurm)
- [x] [Attunement](https://magiccards.info/query?q=!Attunement)
- [x] [Back to Basics](https://magiccards.info/query?q=!Back+to+Basics)
- [x] [Barrin's Codex](https://magiccards.info/query?q=!Barrin's+Codex)
- [x] [Barrin, Master Wizard](https://magiccards.info/query?q=!Barrin,+Master+Wizard)
- [x] [Bedlam](https://magiccards.info/query?q=!Bedlam)
- [x] [Befoul](https://magiccards.info/query?q=!Befoul)
- [x] [Bereavement](https://magiccards.info/query?q=!Bereavement)
- [x] [Blanchwood Armor](https://magiccards.info/query?q=!Blanchwood+Armor)
- [x] [Blanchwood Treefolk](https://magiccards.info/query?q=!Blanchwood+Treefolk)
- [x] [Blasted Landscape](https://magiccards.info/query?q=!Blasted+Landscape)
- [x] [Blood Vassal](https://magiccards.info/query?q=!Blood+Vassal)
- [x] [Bog Raiders](https://magiccards.info/query?q=!Bog+Raiders)
- [x] [Brand](https://magiccards.info/query?q=!Brand)
- [x] [Bravado](https://magiccards.info/query?q=!Bravado)
- [x] [Breach](https://magiccards.info/query?q=!Breach)
- [x] [Brilliant Halo](https://magiccards.info/query?q=!Brilliant+Halo)
- [x] [Bull Hippo](https://magiccards.info/query?q=!Bull+Hippo)
- [x] [Bulwark](https://magiccards.info/query?q=!Bulwark)
- [x] [Cackling Fiend](https://magiccards.info/query?q=!Cackling+Fiend)
- [x] [Carpet of Flowers](https://magiccards.info/query?q=!Carpet+of+Flowers)
- [x] [Carrion Beetles](https://magiccards.info/query?q=!Carrion+Beetles)
- [x] [Catalog](https://magiccards.info/query?q=!Catalog)
- [x] [Catastrophe](https://magiccards.info/query?q=!Catastrophe)
- [x] [Cathodion](https://magiccards.info/query?q=!Cathodion)
- [x] [Cave Tiger](https://magiccards.info/query?q=!Cave+Tiger)
- [x] [Child of Gaea](https://magiccards.info/query?q=!Child+of+Gaea)
- [x] [Chimeric Staff](https://magiccards.info/query?q=!Chimeric+Staff)
- [x] [Citanul Centaurs](https://magiccards.info/query?q=!Citanul+Centaurs)
- [x] [Citanul Flute](https://magiccards.info/query?q=!Citanul+Flute)
- [x] [Citanul Hierophants](https://magiccards.info/query?q=!Citanul+Hierophants)
- [x] [Claws of Gix](https://magiccards.info/query?q=!Claws+of+Gix)
- [x] [Clear](https://magiccards.info/query?q=!Clear)
- [x] [Cloak of Mists](https://magiccards.info/query?q=!Cloak+of+Mists)
- [x] [Confiscate](https://magiccards.info/query?q=!Confiscate)
- [x] [Congregate](https://magiccards.info/query?q=!Congregate)
- [x] [Contamination](https://magiccards.info/query?q=!Contamination)
- [x] [Copper Gnomes](https://magiccards.info/query?q=!Copper+Gnomes)
- [x] [Coral Merfolk](https://magiccards.info/query?q=!Coral+Merfolk)
- [x] [Corrupt](https://magiccards.info/query?q=!Corrupt)
- [x] [Cradle Guard](https://magiccards.info/query?q=!Cradle+Guard)
- [x] [Crater Hellion](https://magiccards.info/query?q=!Crater+Hellion)
- [x] [Crazed Skirge](https://magiccards.info/query?q=!Crazed+Skirge)
- [x] [Crosswinds](https://magiccards.info/query?q=!Crosswinds)
- [x] [Crystal Chimes](https://magiccards.info/query?q=!Crystal+Chimes)
- [x] [Curfew](https://magiccards.info/query?q=!Curfew)
- [x] [Dark Hatchling](https://magiccards.info/query?q=!Dark+Hatchling)
- [x] [Dark Ritual](https://magiccards.info/query?q=!Dark+Ritual)
- [x] [Darkest Hour](https://magiccards.info/query?q=!Darkest+Hour)
- [x] [Defensive Formation](https://magiccards.info/query?q=!Defensive+Formation)
- [x] [Despondency](https://magiccards.info/query?q=!Despondency)
- [x] [Destructive Urge](https://magiccards.info/query?q=!Destructive+Urge)
- [x] [Diabolic Servitude](https://magiccards.info/query?q=!Diabolic+Servitude)
- [x] [Disciple of Grace](https://magiccards.info/query?q=!Disciple+of+Grace)
- [x] [Disciple of Law](https://magiccards.info/query?q=!Disciple+of+Law)
- [x] [Discordant Dirge](https://magiccards.info/query?q=!Discordant+Dirge)
- [x] [Disenchant](https://magiccards.info/query?q=!Disenchant)
- [x] [Disorder](https://magiccards.info/query?q=!Disorder)
- [x] [Disruptive Student](https://magiccards.info/query?q=!Disruptive+Student)
- [x] [Douse](https://magiccards.info/query?q=!Douse)
- [x] [Dragon Blood](https://magiccards.info/query?q=!Dragon+Blood)
- [x] [Drifting Djinn](https://magiccards.info/query?q=!Drifting+Djinn)
- [x] [Drifting Meadow](https://magiccards.info/query?q=!Drifting+Meadow)
- [x] [Dromosaur](https://magiccards.info/query?q=!Dromosaur)
- [x] [Duress](https://magiccards.info/query?q=!Duress)
- [x] [Eastern Paladin](https://magiccards.info/query?q=!Eastern+Paladin)
- [x] [Electryte](https://magiccards.info/query?q=!Electryte)
- [x] [Elite Archers](https://magiccards.info/query?q=!Elite+Archers)
- [x] [Elvish Herder](https://magiccards.info/query?q=!Elvish+Herder)
- [x] [Elvish Lyrist](https://magiccards.info/query?q=!Elvish+Lyrist)
- [x] [Enchantment Alteration](https://magiccards.info/query?q=!Enchantment+Alteration)
- [x] [Endless Wurm](https://magiccards.info/query?q=!Endless+Wurm)
- [x] [Endoskeleton](https://magiccards.info/query?q=!Endoskeleton)
- [x] [Energy Field](https://magiccards.info/query?q=!Energy+Field)
- [x] [Exhaustion](https://magiccards.info/query?q=!Exhaustion)
- [x] [Exhume](https://magiccards.info/query?q=!Exhume)
- [x] [Exploration](https://magiccards.info/query?q=!Exploration)
- [x] [Expunge](https://magiccards.info/query?q=!Expunge)
- [x] [Faith Healer](https://magiccards.info/query?q=!Faith+Healer)
- [x] [Falter](https://magiccards.info/query?q=!Falter)
- [x] [Fault Line](https://magiccards.info/query?q=!Fault+Line)
- [x] [Fecundity](https://magiccards.info/query?q=!Fecundity)
- [x] [Fertile Ground](https://magiccards.info/query?q=!Fertile+Ground)
- [x] [Fiery Mantle](https://magiccards.info/query?q=!Fiery+Mantle)
- [x] [Fire Ants](https://magiccards.info/query?q=!Fire+Ants)
- [x] [Flesh Reaver](https://magiccards.info/query?q=!Flesh+Reaver)
- [x] [Fluctuator](https://magiccards.info/query?q=!Fluctuator)
- [x] [Fog Bank](https://magiccards.info/query?q=!Fog+Bank)
- [x] [Forest](https://magiccards.info/query?q=!Forest)
- [x] [Fortitude](https://magiccards.info/query?q=!Fortitude)
- [x] [Gaea's Bounty](https://magiccards.info/query?q=!Gaea's+Bounty)
- [x] [Gaea's Cradle](https://magiccards.info/query?q=!Gaea's+Cradle)
- [x] [Gaea's Embrace](https://magiccards.info/query?q=!Gaea's+Embrace)
- [x] [Gamble](https://magiccards.info/query?q=!Gamble)
- [x] [Gilded Drake](https://magiccards.info/query?q=!Gilded+Drake)
- [x] [Glorious Anthem](https://magiccards.info/query?q=!Glorious+Anthem)
- [x] [Goblin Cadets](https://magiccards.info/query?q=!Goblin+Cadets)
- [x] [Goblin Lackey](https://magiccards.info/query?q=!Goblin+Lackey)
- [x] [Goblin Matron](https://magiccards.info/query?q=!Goblin+Matron)
- [x] [Goblin Offensive](https://magiccards.info/query?q=!Goblin+Offensive)
- [x] [Goblin Patrol](https://magiccards.info/query?q=!Goblin+Patrol)
- [x] [Goblin Raider](https://magiccards.info/query?q=!Goblin+Raider)
- [x] [Goblin Spelunkers](https://magiccards.info/query?q=!Goblin+Spelunkers)
- [x] [Goblin War Buggy](https://magiccards.info/query?q=!Goblin+War+Buggy)
- [x] [Gorilla Warrior](https://magiccards.info/query?q=!Gorilla+Warrior)
- [x] [Grafted Skullcap](https://magiccards.info/query?q=!Grafted+Skullcap)
- [x] [Great Whale](https://magiccards.info/query?q=!Great+Whale)
- [x] [Greater Good](https://magiccards.info/query?q=!Greater+Good)
- [x] [Greener Pastures](https://magiccards.info/query?q=!Greener+Pastures)
- [x] [Guma](https://magiccards.info/query?q=!Guma)
- [x] [Hawkeater Moth](https://magiccards.info/query?q=!Hawkeater+Moth)
- [x] [Headlong Rush](https://magiccards.info/query?q=!Headlong+Rush)
- [x] [Healing Salve](https://magiccards.info/query?q=!Healing+Salve)
- [x] [Heat Ray](https://magiccards.info/query?q=!Heat+Ray)
- [x] [Herald of Serra](https://magiccards.info/query?q=!Herald+of+Serra)
- [x] [Hermetic Study](https://magiccards.info/query?q=!Hermetic+Study)
- [x] [Hibernation](https://magiccards.info/query?q=!Hibernation)
- [x] [Hidden Ancients](https://magiccards.info/query?q=!Hidden+Ancients)
- [x] [Hidden Guerrillas](https://magiccards.info/query?q=!Hidden+Guerrillas)
- [x] [Hidden Herd](https://magiccards.info/query?q=!Hidden+Herd)
- [x] [Hidden Predators](https://magiccards.info/query?q=!Hidden+Predators)
- [x] [Hidden Spider](https://magiccards.info/query?q=!Hidden+Spider)
- [x] [Hidden Stag](https://magiccards.info/query?q=!Hidden+Stag)
- [x] [Hollow Dogs](https://magiccards.info/query?q=!Hollow+Dogs)
- [x] [Hopping Automaton](https://magiccards.info/query?q=!Hopping+Automaton)
- [x] [Horseshoe Crab](https://magiccards.info/query?q=!Horseshoe+Crab)
- [x] [Humble](https://magiccards.info/query?q=!Humble)
- [x] [Hush](https://magiccards.info/query?q=!Hush)
- [x] [Ill-Gotten Gains](https://magiccards.info/query?q=!Ill-Gotten+Gains)
- [x] [Imaginary Pet](https://magiccards.info/query?q=!Imaginary+Pet)
- [x] [Intrepid Hero](https://magiccards.info/query?q=!Intrepid+Hero)
- [x] [Island](https://magiccards.info/query?q=!Island)
- [x] [Jagged Lightning](https://magiccards.info/query?q=!Jagged+Lightning)
- [x] [Karn, Silver Golem](https://magiccards.info/query?q=!Karn,+Silver+Golem)
- [x] [Launch](https://magiccards.info/query?q=!Launch)
- [x] [Lay Waste](https://magiccards.info/query?q=!Lay+Waste)
- [x] [Lifeline](https://magiccards.info/query?q=!Lifeline)
- [x] [Lightning Dragon](https://magiccards.info/query?q=!Lightning+Dragon)
- [x] [Lilting Refrain](https://magiccards.info/query?q=!Lilting+Refrain)
- [x] [Lingering Mirage](https://magiccards.info/query?q=!Lingering+Mirage)
- [x] [Looming Shade](https://magiccards.info/query?q=!Looming+Shade)
- [x] [Lotus Blossom](https://magiccards.info/query?q=!Lotus+Blossom)
- [x] [Lull](https://magiccards.info/query?q=!Lull)
- [x] [Lurking Evil](https://magiccards.info/query?q=!Lurking+Evil)
- [x] [Mana Leech](https://magiccards.info/query?q=!Mana+Leech)
- [x] [Meltdown](https://magiccards.info/query?q=!Meltdown)
- [x] [Metrognome](https://magiccards.info/query?q=!Metrognome)
- [x] [Midsummer Revel](https://magiccards.info/query?q=!Midsummer+Revel)
- [x] [Mishra's Helix](https://magiccards.info/query?q=!Mishra's+Helix)
- [x] [Mobile Fort](https://magiccards.info/query?q=!Mobile+Fort)
- [x] [Monk Idealist](https://magiccards.info/query?q=!Monk+Idealist)
- [x] [Monk Realist](https://magiccards.info/query?q=!Monk+Realist)
- [x] [Morphling](https://magiccards.info/query?q=!Morphling)
- [x] [Mountain](https://magiccards.info/query?q=!Mountain)
- [x] [No Rest for the Wicked](https://magiccards.info/query?q=!No+Rest+for+the+Wicked)
- [x] [Noetic Scales](https://magiccards.info/query?q=!Noetic+Scales)
- [x] [Okk](https://magiccards.info/query?q=!Okk)
- [x] [Opal Acrolith](https://magiccards.info/query?q=!Opal+Acrolith)
- [x] [Opal Archangel](https://magiccards.info/query?q=!Opal+Archangel)
- [x] [Opal Caryatid](https://magiccards.info/query?q=!Opal+Caryatid)
- [x] [Opal Gargoyle](https://magiccards.info/query?q=!Opal+Gargoyle)
- [x] [Opal Titan](https://magiccards.info/query?q=!Opal+Titan)
- [x] [Oppression](https://magiccards.info/query?q=!Oppression)
- [x] [Order of Yawgmoth](https://magiccards.info/query?q=!Order+of+Yawgmoth)
- [x] [Outmaneuver](https://magiccards.info/query?q=!Outmaneuver)
- [x] [Pacifism](https://magiccards.info/query?q=!Pacifism)
- [x] [Parasitic Bond](https://magiccards.info/query?q=!Parasitic+Bond)
- [x] [Pariah](https://magiccards.info/query?q=!Pariah)
- [x] [Path of Peace](https://magiccards.info/query?q=!Path+of+Peace)
- [x] [Pegasus Charger](https://magiccards.info/query?q=!Pegasus+Charger)
- [x] [Pendrell Drake](https://magiccards.info/query?q=!Pendrell+Drake)
- [x] [Pendrell Flux](https://magiccards.info/query?q=!Pendrell+Flux)
- [x] [Peregrine Drake](https://magiccards.info/query?q=!Peregrine+Drake)
- [x] [Persecute](https://magiccards.info/query?q=!Persecute)
- [x] [Pestilence](https://magiccards.info/query?q=!Pestilence)
- [x] [Phyrexian Colossus](https://magiccards.info/query?q=!Phyrexian+Colossus)
- [x] [Phyrexian Ghoul](https://magiccards.info/query?q=!Phyrexian+Ghoul)
- [x] [Phyrexian Processor](https://magiccards.info/query?q=!Phyrexian+Processor)
- [x] [Phyrexian Tower](https://magiccards.info/query?q=!Phyrexian+Tower)
- [x] [Pit Trap](https://magiccards.info/query?q=!Pit+Trap)
- [x] [Plains](https://magiccards.info/query?q=!Plains)
- [x] [Planar Birth](https://magiccards.info/query?q=!Planar+Birth)
- [x] [Planar Void](https://magiccards.info/query?q=!Planar+Void)
- [x] [Polluted Mire](https://magiccards.info/query?q=!Polluted+Mire)
- [x] [Pouncing Jaguar](https://magiccards.info/query?q=!Pouncing+Jaguar)
- [x] [Power Sink](https://magiccards.info/query?q=!Power+Sink)
- [x] [Power Taint](https://magiccards.info/query?q=!Power+Taint)
- [x] [Presence of the Master](https://magiccards.info/query?q=!Presence+of+the+Master)
- [x] [Priest of Gix](https://magiccards.info/query?q=!Priest+of+Gix)
- [x] [Priest of Titania](https://magiccards.info/query?q=!Priest+of+Titania)
- [x] [Purging Scythe](https://magiccards.info/query?q=!Purging+Scythe)
- [x] [Rain of Filth](https://magiccards.info/query?q=!Rain+of+Filth)
- [x] [Rain of Salt](https://magiccards.info/query?q=!Rain+of+Salt)
- [x] [Ravenous Skirge](https://magiccards.info/query?q=!Ravenous+Skirge)
- [x] [Raze](https://magiccards.info/query?q=!Raze)
- [x] [Recantation](https://magiccards.info/query?q=!Recantation)
- [x] [Reclusive Wight](https://magiccards.info/query?q=!Reclusive+Wight)
- [x] [Redeem](https://magiccards.info/query?q=!Redeem)
- [x] [Reflexes](https://magiccards.info/query?q=!Reflexes)
- [x] [Rejuvenate](https://magiccards.info/query?q=!Rejuvenate)
- [x] [Remembrance](https://magiccards.info/query?q=!Remembrance)
- [x] [Remote Isle](https://magiccards.info/query?q=!Remote+Isle)
- [x] [Reprocess](https://magiccards.info/query?q=!Reprocess)
- [x] [Rescind](https://magiccards.info/query?q=!Rescind)
- [x] [Retaliation](https://magiccards.info/query?q=!Retaliation)
- [x] [Retromancer](https://magiccards.info/query?q=!Retromancer)
- [x] [Rewind](https://magiccards.info/query?q=!Rewind)
- [x] [Rumbling Crescendo](https://magiccards.info/query?q=!Rumbling+Crescendo)
- [x] [Rune of Protection: Artifacts](https://magiccards.info/query?q=!Rune+of+Protection:+Artifacts)
- [x] [Rune of Protection: Black](https://magiccards.info/query?q=!Rune+of+Protection:+Black)
- [x] [Rune of Protection: Blue](https://magiccards.info/query?q=!Rune+of+Protection:+Blue)
- [x] [Rune of Protection: Green](https://magiccards.info/query?q=!Rune+of+Protection:+Green)
- [x] [Rune of Protection: Lands](https://magiccards.info/query?q=!Rune+of+Protection:+Lands)
- [x] [Rune of Protection: Red](https://magiccards.info/query?q=!Rune+of+Protection:+Red)
- [x] [Rune of Protection: White](https://magiccards.info/query?q=!Rune+of+Protection:+White)
- [x] [Sanctum Custodian](https://magiccards.info/query?q=!Sanctum+Custodian)
- [x] [Sanctum Guardian](https://magiccards.info/query?q=!Sanctum+Guardian)
- [x] [Sandbar Merfolk](https://magiccards.info/query?q=!Sandbar+Merfolk)
- [x] [Sandbar Serpent](https://magiccards.info/query?q=!Sandbar+Serpent)
- [x] [Sanguine Guard](https://magiccards.info/query?q=!Sanguine+Guard)
- [x] [Scald](https://magiccards.info/query?q=!Scald)
- [x] [Scoria Wurm](https://magiccards.info/query?q=!Scoria+Wurm)
- [x] [Scrap](https://magiccards.info/query?q=!Scrap)
- [x] [Seasoned Marshal](https://magiccards.info/query?q=!Seasoned+Marshal)
- [x] [Serra Avatar](https://magiccards.info/query?q=!Serra+Avatar)
- [x] [Serra Zealot](https://magiccards.info/query?q=!Serra+Zealot)
- [x] [Serra's Embrace](https://magiccards.info/query?q=!Serra's+Embrace)
- [x] [Serra's Hymn](https://magiccards.info/query?q=!Serra's+Hymn)
- [x] [Serra's Liturgy](https://magiccards.info/query?q=!Serra's+Liturgy)
- [x] [Serra's Sanctum](https://magiccards.info/query?q=!Serra's+Sanctum)
- [x] [Shimmering Barrier](https://magiccards.info/query?q=!Shimmering+Barrier)
- [x] [Shiv's Embrace](https://magiccards.info/query?q=!Shiv's+Embrace)
- [x] [Shivan Gorge](https://magiccards.info/query?q=!Shivan+Gorge)
- [x] [Shivan Hellkite](https://magiccards.info/query?q=!Shivan+Hellkite)
- [x] [Shivan Raptor](https://magiccards.info/query?q=!Shivan+Raptor)
- [x] [Show and Tell](https://magiccards.info/query?q=!Show+and+Tell)
- [x] [Shower of Sparks](https://magiccards.info/query?q=!Shower+of+Sparks)
- [x] [Sicken](https://magiccards.info/query?q=!Sicken)
- [x] [Silent Attendant](https://magiccards.info/query?q=!Silent+Attendant)
- [x] [Skirge Familiar](https://magiccards.info/query?q=!Skirge+Familiar)
- [x] [Skittering Skirge](https://magiccards.info/query?q=!Skittering+Skirge)
- [x] [Sleeper Agent](https://magiccards.info/query?q=!Sleeper+Agent)
- [x] [Slippery Karst](https://magiccards.info/query?q=!Slippery+Karst)
- [x] [Smokestack](https://magiccards.info/query?q=!Smokestack)
- [x] [Smoldering Crater](https://magiccards.info/query?q=!Smoldering+Crater)
- [x] [Sneak Attack](https://magiccards.info/query?q=!Sneak+Attack)
- [x] [Somnophore](https://magiccards.info/query?q=!Somnophore)
- [x] [Songstitcher](https://magiccards.info/query?q=!Songstitcher)
- [x] [Soul Sculptor](https://magiccards.info/query?q=!Soul+Sculptor)
- [x] [Spined Fluke](https://magiccards.info/query?q=!Spined+Fluke)
- [x] [Spire Owl](https://magiccards.info/query?q=!Spire+Owl)
- [x] [Sporogenesis](https://magiccards.info/query?q=!Sporogenesis)
- [x] [Spreading Algae](https://magiccards.info/query?q=!Spreading+Algae)
- [x] [Steam Blast](https://magiccards.info/query?q=!Steam+Blast)
- [x] [Stern Proctor](https://magiccards.info/query?q=!Stern+Proctor)
- [x] [Stroke of Genius](https://magiccards.info/query?q=!Stroke+of+Genius)
- [x] [Sulfuric Vapors](https://magiccards.info/query?q=!Sulfuric+Vapors)
- [x] [Sunder](https://magiccards.info/query?q=!Sunder)
- [x] [Swamp](https://magiccards.info/query?q=!Swamp)
- [x] [Symbiosis](https://magiccards.info/query?q=!Symbiosis)
- [x] [Tainted Aether](https://magiccards.info/query?q=!Tainted+Aether)
- [x] [Telepathy](https://magiccards.info/query?q=!Telepathy)
- [x] [Temporal Aperture](https://magiccards.info/query?q=!Temporal+Aperture)
- [x] [Thran Quarry](https://magiccards.info/query?q=!Thran+Quarry)
- [x] [Thran Turbine](https://magiccards.info/query?q=!Thran+Turbine)
- [x] [Thundering Giant](https://magiccards.info/query?q=!Thundering+Giant)
- [x] [Time Spiral](https://magiccards.info/query?q=!Time+Spiral)
- [x] [Titania's Boon](https://magiccards.info/query?q=!Titania's+Boon)
- [x] [Titania's Chosen](https://magiccards.info/query?q=!Titania's+Chosen)
- [x] [Tolarian Academy](https://magiccards.info/query?q=!Tolarian+Academy)
- [x] [Tolarian Winds](https://magiccards.info/query?q=!Tolarian+Winds)
- [x] [Torch Song](https://magiccards.info/query?q=!Torch+Song)
- [x] [Treefolk Seedlings](https://magiccards.info/query?q=!Treefolk+Seedlings)
- [x] [Treetop Rangers](https://magiccards.info/query?q=!Treetop+Rangers)
- [x] [Turnabout](https://magiccards.info/query?q=!Turnabout)
- [x] [Umbilicus](https://magiccards.info/query?q=!Umbilicus)
- [x] [Unnerve](https://magiccards.info/query?q=!Unnerve)
- [x] [Unworthy Dead](https://magiccards.info/query?q=!Unworthy+Dead)
- [x] [Urza's Armor](https://magiccards.info/query?q=!Urza's+Armor)
- [x] [Vampiric Embrace](https://magiccards.info/query?q=!Vampiric+Embrace)
- [x] [Vebulid](https://magiccards.info/query?q=!Vebulid)
- [x] [Veil of Birds](https://magiccards.info/query?q=!Veil+of+Birds)
- [x] [Veiled Apparition](https://magiccards.info/query?q=!Veiled+Apparition)
- [x] [Veiled Crocodile](https://magiccards.info/query?q=!Veiled+Crocodile)
- [x] [Veiled Sentry](https://magiccards.info/query?q=!Veiled+Sentry)
- [x] [Veiled Serpent](https://magiccards.info/query?q=!Veiled+Serpent)
- [x] [Venomous Fangs](https://magiccards.info/query?q=!Venomous+Fangs)
- [x] [Vernal Bloom](https://magiccards.info/query?q=!Vernal+Bloom)
- [x] [Viashino Outrider](https://magiccards.info/query?q=!Viashino+Outrider)
- [x] [Viashino Runner](https://magiccards.info/query?q=!Viashino+Runner)
- [x] [Viashino Sandswimmer](https://magiccards.info/query?q=!Viashino+Sandswimmer)
- [x] [Viashino Weaponsmith](https://magiccards.info/query?q=!Viashino+Weaponsmith)
- [x] [Victimize](https://magiccards.info/query?q=!Victimize)
- [x] [Vile Requiem](https://magiccards.info/query?q=!Vile+Requiem)
- [x] [Voice of Grace](https://magiccards.info/query?q=!Voice+of+Grace)
- [x] [Voice of Law](https://magiccards.info/query?q=!Voice+of+Law)
- [x] [Voltaic Key](https://magiccards.info/query?q=!Voltaic+Key)
- [x] [Vug Lizard](https://magiccards.info/query?q=!Vug+Lizard)
- [x] [Wall of Junk](https://magiccards.info/query?q=!Wall+of+Junk)
- [x] [War Dance](https://magiccards.info/query?q=!War+Dance)
- [x] [Waylay](https://magiccards.info/query?q=!Waylay)
- [x] [Western Paladin](https://magiccards.info/query?q=!Western+Paladin)
- [x] [Whetstone](https://magiccards.info/query?q=!Whetstone)
- [x] [Whirlwind](https://magiccards.info/query?q=!Whirlwind)
- [x] [Wild Dogs](https://magiccards.info/query?q=!Wild+Dogs)
- [x] [Wildfire](https://magiccards.info/query?q=!Wildfire)
- [x] [Windfall](https://magiccards.info/query?q=!Windfall)
- [x] [Winding Wurm](https://magiccards.info/query?q=!Winding+Wurm)
- [x] [Wirecat](https://magiccards.info/query?q=!Wirecat)
- [x] [Witch Engine](https://magiccards.info/query?q=!Witch+Engine)
- [x] [Wizard Mentor](https://magiccards.info/query?q=!Wizard+Mentor)
- [x] [Worn Powerstone](https://magiccards.info/query?q=!Worn+Powerstone)
- [x] [Worship](https://magiccards.info/query?q=!Worship)
- [x] [Yawgmoth's Edict](https://magiccards.info/query?q=!Yawgmoth's+Edict)
- [x] [Yawgmoth's Will](https://magiccards.info/query?q=!Yawgmoth's+Will)
- [x] [Zephid](https://magiccards.info/query?q=!Zephid)
- [x] [Zephid's Embrace](https://magiccards.info/query?q=!Zephid's+Embrace)
