### ISSUE TITLE
UDS - Urza's Destiny Set Card Implementation Tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5378]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/urzas-destiny)

# Unimplemented Cards

# Cards in set:

- [x] [Academy Rector](https://magiccards.info/query?q=!Academy+Rector)
- [x] [Aether Sting](https://magiccards.info/query?q=!Aether+Sting)
- [x] [Ancient Silverback](https://magiccards.info/query?q=!Ancient+Silverback)
- [x] [Apprentice Necromancer](https://magiccards.info/query?q=!Apprentice+Necromancer)
- [x] [Archery Training](https://magiccards.info/query?q=!Archery+Training)
- [x] [Attrition](https://magiccards.info/query?q=!Attrition)
- [x] [Aura Thief](https://magiccards.info/query?q=!Aura+Thief)
- [x] [Blizzard Elemental](https://magiccards.info/query?q=!Blizzard+Elemental)
- [x] [Bloodshot Cyclops](https://magiccards.info/query?q=!Bloodshot+Cyclops)
- [x] [Body Snatcher](https://magiccards.info/query?q=!Body+Snatcher)
- [x] [Braidwood Cup](https://magiccards.info/query?q=!Braidwood+Cup)
- [x] [Braidwood Sextant](https://magiccards.info/query?q=!Braidwood+Sextant)
- [x] [Brass Secretary](https://magiccards.info/query?q=!Brass+Secretary)
- [x] [Brine Seer](https://magiccards.info/query?q=!Brine+Seer)
- [x] [Bubbling Beebles](https://magiccards.info/query?q=!Bubbling+Beebles)
- [x] [Bubbling Muck](https://magiccards.info/query?q=!Bubbling+Muck)
- [x] [Caltrops](https://magiccards.info/query?q=!Caltrops)
- [x] [Capashen Knight](https://magiccards.info/query?q=!Capashen+Knight)
- [x] [Capashen Standard](https://magiccards.info/query?q=!Capashen+Standard)
- [x] [Capashen Templar](https://magiccards.info/query?q=!Capashen+Templar)
- [x] [Carnival of Souls](https://magiccards.info/query?q=!Carnival+of+Souls)
- [x] [Chime of Night](https://magiccards.info/query?q=!Chime+of+Night)
- [x] [Cinder Seer](https://magiccards.info/query?q=!Cinder+Seer)
- [x] [Colos Yearling](https://magiccards.info/query?q=!Colos+Yearling)
- [x] [Compost](https://magiccards.info/query?q=!Compost)
- [x] [Covetous Dragon](https://magiccards.info/query?q=!Covetous+Dragon)
- [x] [Disappear](https://magiccards.info/query?q=!Disappear)
- [x] [Disease Carriers](https://magiccards.info/query?q=!Disease+Carriers)
- [x] [Donate](https://magiccards.info/query?q=!Donate)
- [x] [Dying Wail](https://magiccards.info/query?q=!Dying+Wail)
- [x] [Elvish Lookout](https://magiccards.info/query?q=!Elvish+Lookout)
- [x] [Elvish Piper](https://magiccards.info/query?q=!Elvish+Piper)
- [x] [Emperor Crocodile](https://magiccards.info/query?q=!Emperor+Crocodile)
- [x] [Encroach](https://magiccards.info/query?q=!Encroach)
- [x] [Eradicate](https://magiccards.info/query?q=!Eradicate)
- [x] [Extruder](https://magiccards.info/query?q=!Extruder)
- [x] [False Prophet](https://magiccards.info/query?q=!False+Prophet)
- [x] [Fatigue](https://magiccards.info/query?q=!Fatigue)
- [x] [Fend Off](https://magiccards.info/query?q=!Fend+Off)
- [x] [Festering Wound](https://magiccards.info/query?q=!Festering+Wound)
- [x] [Field Surgeon](https://magiccards.info/query?q=!Field+Surgeon)
- [x] [Flame Jet](https://magiccards.info/query?q=!Flame+Jet)
- [x] [Fledgling Osprey](https://magiccards.info/query?q=!Fledgling+Osprey)
- [x] [Flicker](https://magiccards.info/query?q=!Flicker)
- [x] [Fodder Cannon](https://magiccards.info/query?q=!Fodder+Cannon)
- [x] [Gamekeeper](https://magiccards.info/query?q=!Gamekeeper)
- [x] [Goblin Berserker](https://magiccards.info/query?q=!Goblin+Berserker)
- [x] [Goblin Festival](https://magiccards.info/query?q=!Goblin+Festival)
- [x] [Goblin Gardener](https://magiccards.info/query?q=!Goblin+Gardener)
- [x] [Goblin Marshal](https://magiccards.info/query?q=!Goblin+Marshal)
- [x] [Goblin Masons](https://magiccards.info/query?q=!Goblin+Masons)
- [x] [Goliath Beetle](https://magiccards.info/query?q=!Goliath+Beetle)
- [x] [Heart Warden](https://magiccards.info/query?q=!Heart+Warden)
- [x] [Hulking Ogre](https://magiccards.info/query?q=!Hulking+Ogre)
- [x] [Hunting Moa](https://magiccards.info/query?q=!Hunting+Moa)
- [x] [Illuminated Wings](https://magiccards.info/query?q=!Illuminated+Wings)
- [x] [Impatience](https://magiccards.info/query?q=!Impatience)
- [x] [Incendiary](https://magiccards.info/query?q=!Incendiary)
- [x] [Iridescent Drake](https://magiccards.info/query?q=!Iridescent+Drake)
- [x] [Ivy Seer](https://magiccards.info/query?q=!Ivy+Seer)
- [x] [Jasmine Seer](https://magiccards.info/query?q=!Jasmine+Seer)
- [x] [Junk Diver](https://magiccards.info/query?q=!Junk+Diver)
- [x] [Keldon Champion](https://magiccards.info/query?q=!Keldon+Champion)
- [x] [Keldon Vandals](https://magiccards.info/query?q=!Keldon+Vandals)
- [x] [Kingfisher](https://magiccards.info/query?q=!Kingfisher)
- [x] [Landslide](https://magiccards.info/query?q=!Landslide)
- [x] [Lurking Jackals](https://magiccards.info/query?q=!Lurking+Jackals)
- [x] [Magnify](https://magiccards.info/query?q=!Magnify)
- [x] [Mantis Engine](https://magiccards.info/query?q=!Mantis+Engine)
- [x] [Mark of Fury](https://magiccards.info/query?q=!Mark+of+Fury)
- [x] [Marker Beetles](https://magiccards.info/query?q=!Marker+Beetles)
- [x] [Mask of Law and Grace](https://magiccards.info/query?q=!Mask+of+Law+and+Grace)
- [x] [Master Healer](https://magiccards.info/query?q=!Master+Healer)
- [x] [Masticore](https://magiccards.info/query?q=!Masticore)
- [x] [Mental Discipline](https://magiccards.info/query?q=!Mental+Discipline)
- [x] [Metalworker](https://magiccards.info/query?q=!Metalworker)
- [x] [Metathran Elite](https://magiccards.info/query?q=!Metathran+Elite)
- [x] [Metathran Soldier](https://magiccards.info/query?q=!Metathran+Soldier)
- [x] [Momentum](https://magiccards.info/query?q=!Momentum)
- [x] [Multani's Decree](https://magiccards.info/query?q=!Multani's+Decree)
- [x] [Nightshade Seer](https://magiccards.info/query?q=!Nightshade+Seer)
- [x] [Opalescence](https://magiccards.info/query?q=!Opalescence)
- [x] [Opposition](https://magiccards.info/query?q=!Opposition)
- [x] [Pattern of Rebirth](https://magiccards.info/query?q=!Pattern+of+Rebirth)
- [x] [Phyrexian Monitor](https://magiccards.info/query?q=!Phyrexian+Monitor)
- [x] [Phyrexian Negator](https://magiccards.info/query?q=!Phyrexian+Negator)
- [x] [Plague Dogs](https://magiccards.info/query?q=!Plague+Dogs)
- [x] [Plated Spider](https://magiccards.info/query?q=!Plated+Spider)
- [x] [Plow Under](https://magiccards.info/query?q=!Plow+Under)
- [x] [Powder Keg](https://magiccards.info/query?q=!Powder+Keg)
- [x] [Private Research](https://magiccards.info/query?q=!Private+Research)
- [x] [Quash](https://magiccards.info/query?q=!Quash)
- [x] [Rapid Decay](https://magiccards.info/query?q=!Rapid+Decay)
- [x] [Ravenous Rats](https://magiccards.info/query?q=!Ravenous+Rats)
- [x] [Rayne, Academy Chancellor](https://magiccards.info/query?q=!Rayne,+Academy+Chancellor)
- [x] [Reckless Abandon](https://magiccards.info/query?q=!Reckless+Abandon)
- [x] [Reliquary Monk](https://magiccards.info/query?q=!Reliquary+Monk)
- [x] [Repercussion](https://magiccards.info/query?q=!Repercussion)
- [x] [Replenish](https://magiccards.info/query?q=!Replenish)
- [x] [Rescue](https://magiccards.info/query?q=!Rescue)
- [x] [Rofellos's Gift](https://magiccards.info/query?q=!Rofellos's+Gift)
- [x] [Rofellos, Llanowar Emissary](https://magiccards.info/query?q=!Rofellos,+Llanowar+Emissary)
- [x] [Sanctimony](https://magiccards.info/query?q=!Sanctimony)
- [x] [Scent of Brine](https://magiccards.info/query?q=!Scent+of+Brine)
- [x] [Scent of Cinder](https://magiccards.info/query?q=!Scent+of+Cinder)
- [x] [Scent of Ivy](https://magiccards.info/query?q=!Scent+of+Ivy)
- [x] [Scent of Jasmine](https://magiccards.info/query?q=!Scent+of+Jasmine)
- [x] [Scent of Nightshade](https://magiccards.info/query?q=!Scent+of+Nightshade)
- [x] [Scour](https://magiccards.info/query?q=!Scour)
- [x] [Scrying Glass](https://magiccards.info/query?q=!Scrying+Glass)
- [x] [Serra Advocate](https://magiccards.info/query?q=!Serra+Advocate)
- [x] [Sigil of Sleep](https://magiccards.info/query?q=!Sigil+of+Sleep)
- [x] [Skittering Horror](https://magiccards.info/query?q=!Skittering+Horror)
- [x] [Slinking Skirge](https://magiccards.info/query?q=!Slinking+Skirge)
- [x] [Solidarity](https://magiccards.info/query?q=!Solidarity)
- [x] [Soul Feast](https://magiccards.info/query?q=!Soul+Feast)
- [x] [Sowing Salt](https://magiccards.info/query?q=!Sowing+Salt)
- [x] [Splinter](https://magiccards.info/query?q=!Splinter)
- [x] [Squirming Mass](https://magiccards.info/query?q=!Squirming+Mass)
- [x] [Storage Matrix](https://magiccards.info/query?q=!Storage+Matrix)
- [x] [Taunting Elf](https://magiccards.info/query?q=!Taunting+Elf)
- [x] [Telepathic Spies](https://magiccards.info/query?q=!Telepathic+Spies)
- [x] [Temporal Adept](https://magiccards.info/query?q=!Temporal+Adept)
- [x] [Tethered Griffin](https://magiccards.info/query?q=!Tethered+Griffin)
- [x] [Thieving Magpie](https://magiccards.info/query?q=!Thieving+Magpie)
- [x] [Thorn Elemental](https://magiccards.info/query?q=!Thorn+Elemental)
- [x] [Thran Dynamo](https://magiccards.info/query?q=!Thran+Dynamo)
- [x] [Thran Foundry](https://magiccards.info/query?q=!Thran+Foundry)
- [x] [Thran Golem](https://magiccards.info/query?q=!Thran+Golem)
- [x] [Tormented Angel](https://magiccards.info/query?q=!Tormented+Angel)
- [x] [Treachery](https://magiccards.info/query?q=!Treachery)
- [x] [Trumpet Blast](https://magiccards.info/query?q=!Trumpet+Blast)
- [x] [Twisted Experiment](https://magiccards.info/query?q=!Twisted+Experiment)
- [x] [Urza's Incubator](https://magiccards.info/query?q=!Urza's+Incubator)
- [x] [Voice of Duty](https://magiccards.info/query?q=!Voice+of+Duty)
- [x] [Voice of Reason](https://magiccards.info/query?q=!Voice+of+Reason)
- [x] [Wake of Destruction](https://magiccards.info/query?q=!Wake+of+Destruction)
- [x] [Wall of Glare](https://magiccards.info/query?q=!Wall+of+Glare)
- [x] [Wild Colos](https://magiccards.info/query?q=!Wild+Colos)
- [x] [Yavimaya Elder](https://magiccards.info/query?q=!Yavimaya+Elder)
- [x] [Yavimaya Enchantress](https://magiccards.info/query?q=!Yavimaya+Enchantress)
- [x] [Yavimaya Hollow](https://magiccards.info/query?q=!Yavimaya+Hollow)
- [x] [Yawgmoth's Bargain](https://magiccards.info/query?q=!Yawgmoth's+Bargain)
