### ISSUE TITLE
TMP - Tempest Set Card Implementation Tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5379]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/tempest)

# Unimplemented Cards

60|[Duplicity](https://magiccards.info/query?q=!Duplicity)
61|[Ertai's Meddling](https://magiccards.info/query?q=!Ertai's+Meddling)
62|[Escaped Shapeshifter](https://magiccards.info/query?q=!Escaped+Shapeshifter)
102|[Whim of Volrath](https://magiccards.info/query?q=!Whim+of+Volrath)
193|[No Quarter](https://magiccards.info/query?q=!No+Quarter)
285|[Magnetic Web](https://magiccards.info/query?q=!Magnetic+Web)
293|[Phyrexian Splicer](https://magiccards.info/query?q=!Phyrexian+Splicer)

# Cards in set:

- [x] [Abandon Hope](https://magiccards.info/query?q=!Abandon+Hope)
- [x] [Advance Scout](https://magiccards.info/query?q=!Advance+Scout)
- [x] [Aftershock](https://magiccards.info/query?q=!Aftershock)
- [x] [Altar of Dementia](https://magiccards.info/query?q=!Altar+of+Dementia)
- [x] [Aluren](https://magiccards.info/query?q=!Aluren)
- [x] [Ancient Runes](https://magiccards.info/query?q=!Ancient+Runes)
- [x] [Ancient Tomb](https://magiccards.info/query?q=!Ancient+Tomb)
- [x] [Angelic Protector](https://magiccards.info/query?q=!Angelic+Protector)
- [x] [Anoint](https://magiccards.info/query?q=!Anoint)
- [x] [Apes of Rath](https://magiccards.info/query?q=!Apes+of+Rath)
- [x] [Apocalypse](https://magiccards.info/query?q=!Apocalypse)
- [x] [Armor Sliver](https://magiccards.info/query?q=!Armor+Sliver)
- [x] [Armored Pegasus](https://magiccards.info/query?q=!Armored+Pegasus)
- [x] [Auratog](https://magiccards.info/query?q=!Auratog)
- [x] [Avenging Angel](https://magiccards.info/query?q=!Avenging+Angel)
- [x] [Barbed Sliver](https://magiccards.info/query?q=!Barbed+Sliver)
- [x] [Bayou Dragonfly](https://magiccards.info/query?q=!Bayou+Dragonfly)
- [x] [Bellowing Fiend](https://magiccards.info/query?q=!Bellowing+Fiend)
- [x] [Benthic Behemoth](https://magiccards.info/query?q=!Benthic+Behemoth)
- [x] [Blood Frenzy](https://magiccards.info/query?q=!Blood+Frenzy)
- [x] [Blood Pet](https://magiccards.info/query?q=!Blood+Pet)
- [x] [Boil](https://magiccards.info/query?q=!Boil)
- [x] [Booby Trap](https://magiccards.info/query?q=!Booby+Trap)
- [x] [Bottle Gnomes](https://magiccards.info/query?q=!Bottle+Gnomes)
- [x] [Bounty Hunter](https://magiccards.info/query?q=!Bounty+Hunter)
- [x] [Broken Fall](https://magiccards.info/query?q=!Broken+Fall)
- [x] [Caldera Lake](https://magiccards.info/query?q=!Caldera+Lake)
- [x] [Canopy Spider](https://magiccards.info/query?q=!Canopy+Spider)
- [x] [Canyon Drake](https://magiccards.info/query?q=!Canyon+Drake)
- [x] [Canyon Wildcat](https://magiccards.info/query?q=!Canyon+Wildcat)
- [x] [Capsize](https://magiccards.info/query?q=!Capsize)
- [x] [Carrionette](https://magiccards.info/query?q=!Carrionette)
- [x] [Chaotic Goo](https://magiccards.info/query?q=!Chaotic+Goo)
- [x] [Charging Rhino](https://magiccards.info/query?q=!Charging+Rhino)
- [x] [Chill](https://magiccards.info/query?q=!Chill)
- [x] [Choke](https://magiccards.info/query?q=!Choke)
- [x] [Cinder Marsh](https://magiccards.info/query?q=!Cinder+Marsh)
- [ ] [Circle of Protection: Black](https://magiccards.info/query?q=!Circle+of+Protection:+Black)
- [ ] [Circle of Protection: Blue](https://magiccards.info/query?q=!Circle+of+Protection:+Blue)
- [ ] [Circle of Protection: Green](https://magiccards.info/query?q=!Circle+of+Protection:+Green)
- [ ] [Circle of Protection: Red](https://magiccards.info/query?q=!Circle+of+Protection:+Red)
- [ ] [Circle of Protection: Shadow](https://magiccards.info/query?q=!Circle+of+Protection:+Shadow)
- [ ] [Circle of Protection: White](https://magiccards.info/query?q=!Circle+of+Protection:+White)
- [x] [Clergy en-Vec](https://magiccards.info/query?q=!Clergy+en-Vec)
- [x] [Clot Sliver](https://magiccards.info/query?q=!Clot+Sliver)
- [x] [Cloudchaser Eagle](https://magiccards.info/query?q=!Cloudchaser+Eagle)
- [x] [Coercion](https://magiccards.info/query?q=!Coercion)
- [x] [Coffin Queen](https://magiccards.info/query?q=!Coffin+Queen)
- [x] [Coiled Tinviper](https://magiccards.info/query?q=!Coiled+Tinviper)
- [x] [Cold Storage](https://magiccards.info/query?q=!Cold+Storage)
- [x] [Commander Greven il-Vec](https://magiccards.info/query?q=!Commander+Greven+il-Vec)
- [x] [Corpse Dance](https://magiccards.info/query?q=!Corpse+Dance)
- [x] [Counterspell](https://magiccards.info/query?q=!Counterspell)
- [x] [Crazed Armodon](https://magiccards.info/query?q=!Crazed+Armodon)
- [x] [Crown of Flames](https://magiccards.info/query?q=!Crown+of+Flames)
- [x] [Cursed Scroll](https://magiccards.info/query?q=!Cursed+Scroll)
- [x] [Dark Banishing](https://magiccards.info/query?q=!Dark+Banishing)
- [x] [Dark Ritual](https://magiccards.info/query?q=!Dark+Ritual)
- [x] [Darkling Stalker](https://magiccards.info/query?q=!Darkling+Stalker)
- [x] [Dauthi Embrace](https://magiccards.info/query?q=!Dauthi+Embrace)
- [x] [Dauthi Ghoul](https://magiccards.info/query?q=!Dauthi+Ghoul)
- [x] [Dauthi Horror](https://magiccards.info/query?q=!Dauthi+Horror)
- [x] [Dauthi Marauder](https://magiccards.info/query?q=!Dauthi+Marauder)
- [x] [Dauthi Mercenary](https://magiccards.info/query?q=!Dauthi+Mercenary)
- [x] [Dauthi Mindripper](https://magiccards.info/query?q=!Dauthi+Mindripper)
- [x] [Dauthi Slayer](https://magiccards.info/query?q=!Dauthi+Slayer)
- [x] [Deadshot](https://magiccards.info/query?q=!Deadshot)
- [x] [Death Pits of Rath](https://magiccards.info/query?q=!Death+Pits+of+Rath)
- [x] [Diabolic Edict](https://magiccards.info/query?q=!Diabolic+Edict)
- [x] [Dirtcowl Wurm](https://magiccards.info/query?q=!Dirtcowl+Wurm)
- [x] [Disenchant](https://magiccards.info/query?q=!Disenchant)
- [x] [Dismiss](https://magiccards.info/query?q=!Dismiss)
- [x] [Disturbed Burial](https://magiccards.info/query?q=!Disturbed+Burial)
- [x] [Dracoplasm](https://magiccards.info/query?q=!Dracoplasm)
- [x] [Dread of Night](https://magiccards.info/query?q=!Dread+of+Night)
- [x] [Dream Cache](https://magiccards.info/query?q=!Dream+Cache)
- [x] [Dregs of Sorrow](https://magiccards.info/query?q=!Dregs+of+Sorrow)
- [ ] [Duplicity](https://magiccards.info/query?q=!Duplicity)
- [x] [Earthcraft](https://magiccards.info/query?q=!Earthcraft)
- [x] [Echo Chamber](https://magiccards.info/query?q=!Echo+Chamber)
- [x] [Eladamri's Vineyard](https://magiccards.info/query?q=!Eladamri's+Vineyard)
- [x] [Eladamri, Lord of Leaves](https://magiccards.info/query?q=!Eladamri,+Lord+of+Leaves)
- [x] [Elite Javelineer](https://magiccards.info/query?q=!Elite+Javelineer)
- [x] [Elven Warhounds](https://magiccards.info/query?q=!Elven+Warhounds)
- [x] [Elvish Fury](https://magiccards.info/query?q=!Elvish+Fury)
- [x] [Emerald Medallion](https://magiccards.info/query?q=!Emerald+Medallion)
- [x] [Emmessi Tome](https://magiccards.info/query?q=!Emmessi+Tome)
- [x] [Endless Scream](https://magiccards.info/query?q=!Endless+Scream)
- [x] [Energizer](https://magiccards.info/query?q=!Energizer)
- [x] [Enfeeblement](https://magiccards.info/query?q=!Enfeeblement)
- [x] [Enraging Licid](https://magiccards.info/query?q=!Enraging+Licid)
- [ ] [Ertai's Meddling](https://magiccards.info/query?q=!Ertai's+Meddling)
- [ ] [Escaped Shapeshifter](https://magiccards.info/query?q=!Escaped+Shapeshifter)
- [x] [Essence Bottle](https://magiccards.info/query?q=!Essence+Bottle)
- [x] [Evincar's Justice](https://magiccards.info/query?q=!Evincar's+Justice)
- [x] [Excavator](https://magiccards.info/query?q=!Excavator)
- [x] [Extinction](https://magiccards.info/query?q=!Extinction)
- [x] [Fevered Convulsions](https://magiccards.info/query?q=!Fevered+Convulsions)
- [x] [Field of Souls](https://magiccards.info/query?q=!Field+of+Souls)
- [x] [Fighting Drake](https://magiccards.info/query?q=!Fighting+Drake)
- [x] [Firefly](https://magiccards.info/query?q=!Firefly)
- [x] [Fireslinger](https://magiccards.info/query?q=!Fireslinger)
- [x] [Flailing Drake](https://magiccards.info/query?q=!Flailing+Drake)
- [x] [Flickering Ward](https://magiccards.info/query?q=!Flickering+Ward)
- [x] [Flowstone Giant](https://magiccards.info/query?q=!Flowstone+Giant)
- [x] [Flowstone Salamander](https://magiccards.info/query?q=!Flowstone+Salamander)
- [x] [Flowstone Sculpture](https://magiccards.info/query?q=!Flowstone+Sculpture)
- [x] [Flowstone Wyvern](https://magiccards.info/query?q=!Flowstone+Wyvern)
- [x] [Fool's Tome](https://magiccards.info/query?q=!Fool's+Tome)
- [ ] [Forest](https://magiccards.info/query?q=!Forest)
- [x] [Frog Tongue](https://magiccards.info/query?q=!Frog+Tongue)
- [x] [Fugitive Druid](https://magiccards.info/query?q=!Fugitive+Druid)
- [x] [Furnace of Rath](https://magiccards.info/query?q=!Furnace+of+Rath)
- [x] [Fylamarid](https://magiccards.info/query?q=!Fylamarid)
- [x] [Gallantry](https://magiccards.info/query?q=!Gallantry)
- [x] [Gaseous Form](https://magiccards.info/query?q=!Gaseous+Form)
- [x] [Gerrard's Battle Cry](https://magiccards.info/query?q=!Gerrard's+Battle+Cry)
- [x] [Ghost Town](https://magiccards.info/query?q=!Ghost+Town)
- [x] [Giant Crab](https://magiccards.info/query?q=!Giant+Crab)
- [x] [Giant Strength](https://magiccards.info/query?q=!Giant+Strength)
- [x] [Goblin Bombardment](https://magiccards.info/query?q=!Goblin+Bombardment)
- [x] [Gravedigger](https://magiccards.info/query?q=!Gravedigger)
- [x] [Grindstone](https://magiccards.info/query?q=!Grindstone)
- [x] [Hand to Hand](https://magiccards.info/query?q=!Hand+to+Hand)
- [x] [Hanna's Custody](https://magiccards.info/query?q=!Hanna's+Custody)
- [x] [Harrow](https://magiccards.info/query?q=!Harrow)
- [x] [Havoc](https://magiccards.info/query?q=!Havoc)
- [x] [Heart Sliver](https://magiccards.info/query?q=!Heart+Sliver)
- [x] [Heartwood Dryad](https://magiccards.info/query?q=!Heartwood+Dryad)
- [x] [Heartwood Giant](https://magiccards.info/query?q=!Heartwood+Giant)
- [x] [Heartwood Treefolk](https://magiccards.info/query?q=!Heartwood+Treefolk)
- [x] [Helm of Possession](https://magiccards.info/query?q=!Helm+of+Possession)
- [x] [Hero's Resolve](https://magiccards.info/query?q=!Hero's+Resolve)
- [x] [Horned Sliver](https://magiccards.info/query?q=!Horned+Sliver)
- [x] [Horned Turtle](https://magiccards.info/query?q=!Horned+Turtle)
- [x] [Humility](https://magiccards.info/query?q=!Humility)
- [x] [Imps' Taunt](https://magiccards.info/query?q=!Imps'+Taunt)
- [x] [Insight](https://magiccards.info/query?q=!Insight)
- [x] [Interdict](https://magiccards.info/query?q=!Interdict)
- [x] [Intuition](https://magiccards.info/query?q=!Intuition)
- [x] [Invulnerability](https://magiccards.info/query?q=!Invulnerability)
- [ ] [Island](https://magiccards.info/query?q=!Island)
- [x] [Jackal Pup](https://magiccards.info/query?q=!Jackal+Pup)
- [x] [Jet Medallion](https://magiccards.info/query?q=!Jet+Medallion)
- [x] [Jinxed Idol](https://magiccards.info/query?q=!Jinxed+Idol)
- [x] [Kezzerdrix](https://magiccards.info/query?q=!Kezzerdrix)
- [x] [Kindle](https://magiccards.info/query?q=!Kindle)
- [x] [Knight of Dawn](https://magiccards.info/query?q=!Knight+of+Dawn)
- [x] [Knight of Dusk](https://magiccards.info/query?q=!Knight+of+Dusk)
- [x] [Krakilin](https://magiccards.info/query?q=!Krakilin)
- [x] [Leeching Licid](https://magiccards.info/query?q=!Leeching+Licid)
- [x] [Legacy's Allure](https://magiccards.info/query?q=!Legacy's+Allure)
- [x] [Legerdemain](https://magiccards.info/query?q=!Legerdemain)
- [x] [Light of Day](https://magiccards.info/query?q=!Light+of+Day)
- [x] [Lightning Blast](https://magiccards.info/query?q=!Lightning+Blast)
- [x] [Lightning Elemental](https://magiccards.info/query?q=!Lightning+Elemental)
- [x] [Living Death](https://magiccards.info/query?q=!Living+Death)
- [x] [Lobotomy](https://magiccards.info/query?q=!Lobotomy)
- [x] [Lotus Petal](https://magiccards.info/query?q=!Lotus+Petal)
- [x] [Lowland Giant](https://magiccards.info/query?q=!Lowland+Giant)
- [x] [Maddening Imp](https://magiccards.info/query?q=!Maddening+Imp)
- [x] [Magmasaur](https://magiccards.info/query?q=!Magmasaur)
- [ ] [Magnetic Web](https://magiccards.info/query?q=!Magnetic+Web)
- [x] [Mana Severance](https://magiccards.info/query?q=!Mana+Severance)
- [x] [Manakin](https://magiccards.info/query?q=!Manakin)
- [x] [Manta Riders](https://magiccards.info/query?q=!Manta+Riders)
- [x] [Marble Titan](https://magiccards.info/query?q=!Marble+Titan)
- [x] [Marsh Lurker](https://magiccards.info/query?q=!Marsh+Lurker)
- [x] [Master Decoy](https://magiccards.info/query?q=!Master+Decoy)
- [x] [Mawcor](https://magiccards.info/query?q=!Mawcor)
- [x] [Maze of Shadows](https://magiccards.info/query?q=!Maze+of+Shadows)
- [x] [Meditate](https://magiccards.info/query?q=!Meditate)
- [x] [Metallic Sliver](https://magiccards.info/query?q=!Metallic+Sliver)
- [x] [Mindwhip Sliver](https://magiccards.info/query?q=!Mindwhip+Sliver)
- [x] [Minion of the Wastes](https://magiccards.info/query?q=!Minion+of+the+Wastes)
- [x] [Mirri's Guile](https://magiccards.info/query?q=!Mirri's+Guile)
- [x] [Mnemonic Sliver](https://magiccards.info/query?q=!Mnemonic+Sliver)
- [x] [Mogg Cannon](https://magiccards.info/query?q=!Mogg+Cannon)
- [x] [Mogg Conscripts](https://magiccards.info/query?q=!Mogg+Conscripts)
- [x] [Mogg Fanatic](https://magiccards.info/query?q=!Mogg+Fanatic)
- [x] [Mogg Hollows](https://magiccards.info/query?q=!Mogg+Hollows)
- [x] [Mogg Raider](https://magiccards.info/query?q=!Mogg+Raider)
- [x] [Mogg Squad](https://magiccards.info/query?q=!Mogg+Squad)
- [x] [Mongrel Pack](https://magiccards.info/query?q=!Mongrel+Pack)
- [ ] [Mountain](https://magiccards.info/query?q=!Mountain)
- [x] [Mounted Archers](https://magiccards.info/query?q=!Mounted+Archers)
- [x] [Muscle Sliver](https://magiccards.info/query?q=!Muscle+Sliver)
- [x] [Natural Spring](https://magiccards.info/query?q=!Natural+Spring)
- [x] [Nature's Revolt](https://magiccards.info/query?q=!Nature's+Revolt)
- [x] [Needle Storm](https://magiccards.info/query?q=!Needle+Storm)
- [ ] [No Quarter](https://magiccards.info/query?q=!No+Quarter)
- [x] [Nurturing Licid](https://magiccards.info/query?q=!Nurturing+Licid)
- [x] [Opportunist](https://magiccards.info/query?q=!Opportunist)
- [x] [Oracle en-Vec](https://magiccards.info/query?q=!Oracle+en-Vec)
- [x] [Orim's Prayer](https://magiccards.info/query?q=!Orim's+Prayer)
- [x] [Orim, Samite Healer](https://magiccards.info/query?q=!Orim,+Samite+Healer)
- [x] [Overrun](https://magiccards.info/query?q=!Overrun)
- [x] [Pacifism](https://magiccards.info/query?q=!Pacifism)
- [x] [Pallimud](https://magiccards.info/query?q=!Pallimud)
- [x] [Patchwork Gnomes](https://magiccards.info/query?q=!Patchwork+Gnomes)
- [x] [Pearl Medallion](https://magiccards.info/query?q=!Pearl+Medallion)
- [x] [Pegasus Refuge](https://magiccards.info/query?q=!Pegasus+Refuge)
- [x] [Perish](https://magiccards.info/query?q=!Perish)
- [x] [Phyrexian Grimoire](https://magiccards.info/query?q=!Phyrexian+Grimoire)
- [x] [Phyrexian Hulk](https://magiccards.info/query?q=!Phyrexian+Hulk)
- [ ] [Phyrexian Splicer](https://magiccards.info/query?q=!Phyrexian+Splicer)
- [x] [Pincher Beetles](https://magiccards.info/query?q=!Pincher+Beetles)
- [x] [Pine Barrens](https://magiccards.info/query?q=!Pine+Barrens)
- [x] [Pit Imp](https://magiccards.info/query?q=!Pit+Imp)
- [ ] [Plains](https://magiccards.info/query?q=!Plains)
- [x] [Power Sink](https://magiccards.info/query?q=!Power+Sink)
- [x] [Precognition](https://magiccards.info/query?q=!Precognition)
- [x] [Propaganda](https://magiccards.info/query?q=!Propaganda)
- [x] [Puppet Strings](https://magiccards.info/query?q=!Puppet+Strings)
- [x] [Quickening Licid](https://magiccards.info/query?q=!Quickening+Licid)
- [x] [Rain of Tears](https://magiccards.info/query?q=!Rain+of+Tears)
- [x] [Rampant Growth](https://magiccards.info/query?q=!Rampant+Growth)
- [x] [Ranger en-Vec](https://magiccards.info/query?q=!Ranger+en-Vec)
- [x] [Rathi Dragon](https://magiccards.info/query?q=!Rathi+Dragon)
- [x] [Rats of Rath](https://magiccards.info/query?q=!Rats+of+Rath)
- [x] [Reality Anchor](https://magiccards.info/query?q=!Reality+Anchor)
- [x] [Reanimate](https://magiccards.info/query?q=!Reanimate)
- [x] [Reap](https://magiccards.info/query?q=!Reap)
- [x] [Reckless Spite](https://magiccards.info/query?q=!Reckless+Spite)
- [x] [Recycle](https://magiccards.info/query?q=!Recycle)
- [x] [Reflecting Pool](https://magiccards.info/query?q=!Reflecting+Pool)
- [x] [Renegade Warlord](https://magiccards.info/query?q=!Renegade+Warlord)
- [x] [Repentance](https://magiccards.info/query?q=!Repentance)
- [x] [Respite](https://magiccards.info/query?q=!Respite)
- [x] [Rolling Thunder](https://magiccards.info/query?q=!Rolling+Thunder)
- [x] [Root Maze](https://magiccards.info/query?q=!Root+Maze)
- [x] [Rootbreaker Wurm](https://magiccards.info/query?q=!Rootbreaker+Wurm)
- [x] [Rootwalla](https://magiccards.info/query?q=!Rootwalla)
- [x] [Rootwater Depths](https://magiccards.info/query?q=!Rootwater+Depths)
- [x] [Rootwater Diver](https://magiccards.info/query?q=!Rootwater+Diver)
- [x] [Rootwater Hunter](https://magiccards.info/query?q=!Rootwater+Hunter)
- [x] [Rootwater Matriarch](https://magiccards.info/query?q=!Rootwater+Matriarch)
- [x] [Rootwater Shaman](https://magiccards.info/query?q=!Rootwater+Shaman)
- [x] [Ruby Medallion](https://magiccards.info/query?q=!Ruby+Medallion)
- [x] [Sacred Guide](https://magiccards.info/query?q=!Sacred+Guide)
- [x] [Sadistic Glee](https://magiccards.info/query?q=!Sadistic+Glee)
- [x] [Safeguard](https://magiccards.info/query?q=!Safeguard)
- [x] [Salt Flats](https://magiccards.info/query?q=!Salt+Flats)
- [x] [Sandstone Warrior](https://magiccards.info/query?q=!Sandstone+Warrior)
- [x] [Sapphire Medallion](https://magiccards.info/query?q=!Sapphire+Medallion)
- [x] [Sarcomancy](https://magiccards.info/query?q=!Sarcomancy)
- [x] [Scabland](https://magiccards.info/query?q=!Scabland)
- [x] [Scalding Tongs](https://magiccards.info/query?q=!Scalding+Tongs)
- [x] [Scorched Earth](https://magiccards.info/query?q=!Scorched+Earth)
- [x] [Scragnoth](https://magiccards.info/query?q=!Scragnoth)
- [x] [Screeching Harpy](https://magiccards.info/query?q=!Screeching+Harpy)
- [x] [Scroll Rack](https://magiccards.info/query?q=!Scroll+Rack)
- [x] [Sea Monster](https://magiccards.info/query?q=!Sea+Monster)
- [x] [Searing Touch](https://magiccards.info/query?q=!Searing+Touch)
- [x] [Seeker of Skybreak](https://magiccards.info/query?q=!Seeker+of+Skybreak)
- [x] [Segmented Wurm](https://magiccards.info/query?q=!Segmented+Wurm)
- [x] [Selenia, Dark Angel](https://magiccards.info/query?q=!Selenia,+Dark+Angel)
- [x] [Serene Offering](https://magiccards.info/query?q=!Serene+Offering)
- [x] [Servant of Volrath](https://magiccards.info/query?q=!Servant+of+Volrath)
- [x] [Shadow Rift](https://magiccards.info/query?q=!Shadow+Rift)
- [x] [Shadowstorm](https://magiccards.info/query?q=!Shadowstorm)
- [x] [Shatter](https://magiccards.info/query?q=!Shatter)
- [x] [Shimmering Wings](https://magiccards.info/query?q=!Shimmering+Wings)
- [x] [Shocker](https://magiccards.info/query?q=!Shocker)
- [x] [Sky Spirit](https://magiccards.info/query?q=!Sky+Spirit)
- [x] [Skyshroud Condor](https://magiccards.info/query?q=!Skyshroud+Condor)
- [x] [Skyshroud Elf](https://magiccards.info/query?q=!Skyshroud+Elf)
- [x] [Skyshroud Forest](https://magiccards.info/query?q=!Skyshroud+Forest)
- [x] [Skyshroud Ranger](https://magiccards.info/query?q=!Skyshroud+Ranger)
- [x] [Skyshroud Troll](https://magiccards.info/query?q=!Skyshroud+Troll)
- [x] [Skyshroud Vampire](https://magiccards.info/query?q=!Skyshroud+Vampire)
- [x] [Soltari Crusader](https://magiccards.info/query?q=!Soltari+Crusader)
- [x] [Soltari Emissary](https://magiccards.info/query?q=!Soltari+Emissary)
- [x] [Soltari Foot Soldier](https://magiccards.info/query?q=!Soltari+Foot+Soldier)
- [x] [Soltari Guerrillas](https://magiccards.info/query?q=!Soltari+Guerrillas)
- [x] [Soltari Lancer](https://magiccards.info/query?q=!Soltari+Lancer)
- [x] [Soltari Monk](https://magiccards.info/query?q=!Soltari+Monk)
- [x] [Soltari Priest](https://magiccards.info/query?q=!Soltari+Priest)
- [x] [Soltari Trooper](https://magiccards.info/query?q=!Soltari+Trooper)
- [x] [Souldrinker](https://magiccards.info/query?q=!Souldrinker)
- [x] [Spell Blast](https://magiccards.info/query?q=!Spell+Blast)
- [x] [Spike Drone](https://magiccards.info/query?q=!Spike+Drone)
- [x] [Spinal Graft](https://magiccards.info/query?q=!Spinal+Graft)
- [x] [Spirit Mirror](https://magiccards.info/query?q=!Spirit+Mirror)
- [x] [Spontaneous Combustion](https://magiccards.info/query?q=!Spontaneous+Combustion)
- [x] [Squee's Toy](https://magiccards.info/query?q=!Squee's+Toy)
- [x] [Stalking Stones](https://magiccards.info/query?q=!Stalking+Stones)
- [x] [Starke of Rath](https://magiccards.info/query?q=!Starke+of+Rath)
- [x] [Static Orb](https://magiccards.info/query?q=!Static+Orb)
- [x] [Staunch Defenders](https://magiccards.info/query?q=!Staunch+Defenders)
- [x] [Steal Enchantment](https://magiccards.info/query?q=!Steal+Enchantment)
- [x] [Stinging Licid](https://magiccards.info/query?q=!Stinging+Licid)
- [x] [Stone Rain](https://magiccards.info/query?q=!Stone+Rain)
- [x] [Storm Front](https://magiccards.info/query?q=!Storm+Front)
- [x] [Stun](https://magiccards.info/query?q=!Stun)
- [x] [Sudden Impact](https://magiccards.info/query?q=!Sudden+Impact)
- [ ] [Swamp](https://magiccards.info/query?q=!Swamp)
- [x] [Tahngarth's Rage](https://magiccards.info/query?q=!Tahngarth's+Rage)
- [x] [Talon Sliver](https://magiccards.info/query?q=!Talon+Sliver)
- [x] [Telethopter](https://magiccards.info/query?q=!Telethopter)
- [x] [Thalakos Dreamsower](https://magiccards.info/query?q=!Thalakos+Dreamsower)
- [x] [Thalakos Lowlands](https://magiccards.info/query?q=!Thalakos+Lowlands)
- [x] [Thalakos Mistfolk](https://magiccards.info/query?q=!Thalakos+Mistfolk)
- [x] [Thalakos Seer](https://magiccards.info/query?q=!Thalakos+Seer)
- [x] [Thalakos Sentry](https://magiccards.info/query?q=!Thalakos+Sentry)
- [x] [Thumbscrews](https://magiccards.info/query?q=!Thumbscrews)
- [x] [Time Ebb](https://magiccards.info/query?q=!Time+Ebb)
- [x] [Time Warp](https://magiccards.info/query?q=!Time+Warp)
- [x] [Tooth and Claw](https://magiccards.info/query?q=!Tooth+and+Claw)
- [x] [Torture Chamber](https://magiccards.info/query?q=!Torture+Chamber)
- [x] [Tradewind Rider](https://magiccards.info/query?q=!Tradewind+Rider)
- [x] [Trained Armodon](https://magiccards.info/query?q=!Trained+Armodon)
- [x] [Tranquility](https://magiccards.info/query?q=!Tranquility)
- [x] [Trumpeting Armodon](https://magiccards.info/query?q=!Trumpeting+Armodon)
- [x] [Twitch](https://magiccards.info/query?q=!Twitch)
- [x] [Unstable Shapeshifter](https://magiccards.info/query?q=!Unstable+Shapeshifter)
- [x] [Vec Townships](https://magiccards.info/query?q=!Vec+Townships)
- [x] [Verdant Force](https://magiccards.info/query?q=!Verdant+Force)
- [x] [Verdigris](https://magiccards.info/query?q=!Verdigris)
- [x] [Vhati il-Dal](https://magiccards.info/query?q=!Vhati+il-Dal)
- [x] [Volrath's Curse](https://magiccards.info/query?q=!Volrath's+Curse)
- [x] [Wall of Diffusion](https://magiccards.info/query?q=!Wall+of+Diffusion)
- [x] [Warmth](https://magiccards.info/query?q=!Warmth)
- [x] [Wasteland](https://magiccards.info/query?q=!Wasteland)
- [x] [Watchdog](https://magiccards.info/query?q=!Watchdog)
- [ ] [Whim of Volrath](https://magiccards.info/query?q=!Whim+of+Volrath)
- [x] [Whispers of the Muse](https://magiccards.info/query?q=!Whispers+of+the+Muse)
- [x] [Wild Wurm](https://magiccards.info/query?q=!Wild+Wurm)
- [x] [Wind Dancer](https://magiccards.info/query?q=!Wind+Dancer)
- [x] [Wind Drake](https://magiccards.info/query?q=!Wind+Drake)
- [x] [Winds of Rath](https://magiccards.info/query?q=!Winds+of+Rath)
- [x] [Winged Sliver](https://magiccards.info/query?q=!Winged+Sliver)
- [x] [Winter's Grasp](https://magiccards.info/query?q=!Winter's+Grasp)
- [x] [Wood Sage](https://magiccards.info/query?q=!Wood+Sage)
- [x] [Worthy Cause](https://magiccards.info/query?q=!Worthy+Cause)

**Comment by xenohedron** [comment]
Escaped Shapeshifter is implemented

**Comment by tiera3** [comment]
> 285|[Magnetic Web](https://magiccards.info/query?q=!Magnetic+Web)

The collector number is 295
