### ISSUE TITLE
STH - Stronghold Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5380]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/mercadian-masques)

# Unimplemented Cards

# Cards in set:

- [x] [Acidic Sliver](https://magiccards.info/query?q=!Acidic+Sliver)
- [x] [Amok](https://magiccards.info/query?q=!Amok)
- [x] [Awakening](https://magiccards.info/query?q=!Awakening)
- [x] [Bandage](https://magiccards.info/query?q=!Bandage)
- [x] [Bottomless Pit](https://magiccards.info/query?q=!Bottomless+Pit)
- [x] [Brush with Death](https://magiccards.info/query?q=!Brush+with+Death)
- [x] [Bullwhip](https://magiccards.info/query?q=!Bullwhip)
- [x] [Burgeoning](https://magiccards.info/query?q=!Burgeoning)
- [x] [Calming Licid](https://magiccards.info/query?q=!Calming+Licid)
- [x] [Cannibalize](https://magiccards.info/query?q=!Cannibalize)
- [x] [Carnassid](https://magiccards.info/query?q=!Carnassid)
- [x] [Change of Heart](https://magiccards.info/query?q=!Change+of+Heart)
- [x] [Cloud Spirit](https://magiccards.info/query?q=!Cloud+Spirit)
- [x] [Constant Mists](https://magiccards.info/query?q=!Constant+Mists)
- [x] [Contemplation](https://magiccards.info/query?q=!Contemplation)
- [x] [Contempt](https://magiccards.info/query?q=!Contempt)
- [x] [Conviction](https://magiccards.info/query?q=!Conviction)
- [x] [Convulsing Licid](https://magiccards.info/query?q=!Convulsing+Licid)
- [x] [Corrupting Licid](https://magiccards.info/query?q=!Corrupting+Licid)
- [x] [Craven Giant](https://magiccards.info/query?q=!Craven+Giant)
- [x] [Crossbow Ambush](https://magiccards.info/query?q=!Crossbow+Ambush)
- [x] [Crovax the Cursed](https://magiccards.info/query?q=!Crovax+the+Cursed)
- [x] [Crystalline Sliver](https://magiccards.info/query?q=!Crystalline+Sliver)
- [x] [Dauthi Trapper](https://magiccards.info/query?q=!Dauthi+Trapper)
- [x] [Death Stroke](https://magiccards.info/query?q=!Death+Stroke)
- [x] [Dream Halls](https://magiccards.info/query?q=!Dream+Halls)
- [x] [Dream Prowler](https://magiccards.info/query?q=!Dream+Prowler)
- [x] [Duct Crawler](https://magiccards.info/query?q=!Duct+Crawler)
- [x] [Dungeon Shade](https://magiccards.info/query?q=!Dungeon+Shade)
- [x] [Elven Rite](https://magiccards.info/query?q=!Elven+Rite)
- [x] [Endangered Armodon](https://magiccards.info/query?q=!Endangered+Armodon)
- [x] [Ensnaring Bridge](https://magiccards.info/query?q=!Ensnaring+Bridge)
- [x] [Evacuation](https://magiccards.info/query?q=!Evacuation)
- [x] [Fanning the Flames](https://magiccards.info/query?q=!Fanning+the+Flames)
- [x] [Flame Wave](https://magiccards.info/query?q=!Flame+Wave)
- [x] [Fling](https://magiccards.info/query?q=!Fling)
- [x] [Flowstone Blade](https://magiccards.info/query?q=!Flowstone+Blade)
- [x] [Flowstone Hellion](https://magiccards.info/query?q=!Flowstone+Hellion)
- [x] [Flowstone Mauler](https://magiccards.info/query?q=!Flowstone+Mauler)
- [x] [Flowstone Shambler](https://magiccards.info/query?q=!Flowstone+Shambler)
- [x] [Foul Imp](https://magiccards.info/query?q=!Foul+Imp)
- [x] [Furnace Spirit](https://magiccards.info/query?q=!Furnace+Spirit)
- [x] [Gliding Licid](https://magiccards.info/query?q=!Gliding+Licid)
- [x] [Grave Pact](https://magiccards.info/query?q=!Grave+Pact)
- [x] [Hammerhead Shark](https://magiccards.info/query?q=!Hammerhead+Shark)
- [x] [Heartstone](https://magiccards.info/query?q=!Heartstone)
- [x] [Heat of Battle](https://magiccards.info/query?q=!Heat+of+Battle)
- [x] [Hermit Druid](https://magiccards.info/query?q=!Hermit+Druid)
- [x] [Hesitation](https://magiccards.info/query?q=!Hesitation)
- [x] [Hibernation Sliver](https://magiccards.info/query?q=!Hibernation+Sliver)
- [x] [Hidden Retreat](https://magiccards.info/query?q=!Hidden+Retreat)
- [x] [Honor Guard](https://magiccards.info/query?q=!Honor+Guard)
- [x] [Horn of Greed](https://magiccards.info/query?q=!Horn+of+Greed)
- [x] [Hornet Cannon](https://magiccards.info/query?q=!Hornet+Cannon)
- [x] [Intruder Alarm](https://magiccards.info/query?q=!Intruder+Alarm)
- [x] [Invasion Plans](https://magiccards.info/query?q=!Invasion+Plans)
- [x] [Jinxed Ring](https://magiccards.info/query?q=!Jinxed+Ring)
- [x] [Lab Rats](https://magiccards.info/query?q=!Lab+Rats)
- [x] [Lancers en-Kor](https://magiccards.info/query?q=!Lancers+en-Kor)
- [x] [Leap](https://magiccards.info/query?q=!Leap)
- [x] [Lowland Basilisk](https://magiccards.info/query?q=!Lowland+Basilisk)
- [x] [Mana Leak](https://magiccards.info/query?q=!Mana+Leak)
- [x] [Mask of the Mimic](https://magiccards.info/query?q=!Mask+of+the+Mimic)
- [x] [Megrim](https://magiccards.info/query?q=!Megrim)
- [x] [Mind Games](https://magiccards.info/query?q=!Mind+Games)
- [x] [Mind Peel](https://magiccards.info/query?q=!Mind+Peel)
- [x] [Mindwarper](https://magiccards.info/query?q=!Mindwarper)
- [x] [Mob Justice](https://magiccards.info/query?q=!Mob+Justice)
- [x] [Mogg Bombers](https://magiccards.info/query?q=!Mogg+Bombers)
- [x] [Mogg Flunkies](https://magiccards.info/query?q=!Mogg+Flunkies)
- [x] [Mogg Infestation](https://magiccards.info/query?q=!Mogg+Infestation)
- [x] [Mogg Maniac](https://magiccards.info/query?q=!Mogg+Maniac)
- [x] [Morgue Thrull](https://magiccards.info/query?q=!Morgue+Thrull)
- [x] [Mortuary](https://magiccards.info/query?q=!Mortuary)
- [x] [Mox Diamond](https://magiccards.info/query?q=!Mox+Diamond)
- [x] [Mulch](https://magiccards.info/query?q=!Mulch)
- [x] [Nomads en-Kor](https://magiccards.info/query?q=!Nomads+en-Kor)
- [x] [Overgrowth](https://magiccards.info/query?q=!Overgrowth)
- [x] [Portcullis](https://magiccards.info/query?q=!Portcullis)
- [x] [Primal Rage](https://magiccards.info/query?q=!Primal+Rage)
- [x] [Provoke](https://magiccards.info/query?q=!Provoke)
- [x] [Pursuit of Knowledge](https://magiccards.info/query?q=!Pursuit+of+Knowledge)
- [x] [Rabid Rats](https://magiccards.info/query?q=!Rabid+Rats)
- [x] [Ransack](https://magiccards.info/query?q=!Ransack)
- [x] [Rebound](https://magiccards.info/query?q=!Rebound)
- [x] [Reins of Power](https://magiccards.info/query?q=!Reins+of+Power)
- [x] [Revenant](https://magiccards.info/query?q=!Revenant)
- [x] [Rolling Stones](https://magiccards.info/query?q=!Rolling+Stones)
- [x] [Ruination](https://magiccards.info/query?q=!Ruination)
- [x] [Sacred Ground](https://magiccards.info/query?q=!Sacred+Ground)
- [x] [Samite Blessing](https://magiccards.info/query?q=!Samite+Blessing)
- [x] [Scapegoat](https://magiccards.info/query?q=!Scapegoat)
- [x] [Seething Anger](https://magiccards.info/query?q=!Seething+Anger)
- [x] [Serpent Warrior](https://magiccards.info/query?q=!Serpent+Warrior)
- [x] [Shaman en-Kor](https://magiccards.info/query?q=!Shaman+en-Kor)
- [x] [Shard Phoenix](https://magiccards.info/query?q=!Shard+Phoenix)
- [x] [Shifting Wall](https://magiccards.info/query?q=!Shifting+Wall)
- [x] [Shock](https://magiccards.info/query?q=!Shock)
- [x] [Sift](https://magiccards.info/query?q=!Sift)
- [x] [Silver Wyvern](https://magiccards.info/query?q=!Silver+Wyvern)
- [x] [Skeleton Scavengers](https://magiccards.info/query?q=!Skeleton+Scavengers)
- [x] [Skyshroud Archer](https://magiccards.info/query?q=!Skyshroud+Archer)
- [x] [Skyshroud Falcon](https://magiccards.info/query?q=!Skyshroud+Falcon)
- [x] [Skyshroud Troopers](https://magiccards.info/query?q=!Skyshroud+Troopers)
- [x] [Sliver Queen](https://magiccards.info/query?q=!Sliver+Queen)
- [x] [Smite](https://magiccards.info/query?q=!Smite)
- [x] [Soltari Champion](https://magiccards.info/query?q=!Soltari+Champion)
- [x] [Spike Breeder](https://magiccards.info/query?q=!Spike+Breeder)
- [x] [Spike Colony](https://magiccards.info/query?q=!Spike+Colony)
- [x] [Spike Feeder](https://magiccards.info/query?q=!Spike+Feeder)
- [x] [Spike Soldier](https://magiccards.info/query?q=!Spike+Soldier)
- [x] [Spike Worker](https://magiccards.info/query?q=!Spike+Worker)
- [x] [Spindrift Drake](https://magiccards.info/query?q=!Spindrift+Drake)
- [x] [Spined Sliver](https://magiccards.info/query?q=!Spined+Sliver)
- [x] [Spined Wurm](https://magiccards.info/query?q=!Spined+Wurm)
- [x] [Spirit en-Kor](https://magiccards.info/query?q=!Spirit+en-Kor)
- [x] [Spitting Hydra](https://magiccards.info/query?q=!Spitting+Hydra)
- [x] [Stronghold Assassin](https://magiccards.info/query?q=!Stronghold+Assassin)
- [x] [Stronghold Taskmaster](https://magiccards.info/query?q=!Stronghold+Taskmaster)
- [x] [Sword of the Chosen](https://magiccards.info/query?q=!Sword+of+the+Chosen)
- [x] [Temper](https://magiccards.info/query?q=!Temper)
- [x] [Tempting Licid](https://magiccards.info/query?q=!Tempting+Licid)
- [x] [Thalakos Deceiver](https://magiccards.info/query?q=!Thalakos+Deceiver)
- [x] [Tidal Surge](https://magiccards.info/query?q=!Tidal+Surge)
- [x] [Tidal Warrior](https://magiccards.info/query?q=!Tidal+Warrior)
- [x] [Torment](https://magiccards.info/query?q=!Torment)
- [x] [Tortured Existence](https://magiccards.info/query?q=!Tortured+Existence)
- [x] [Venerable Monk](https://magiccards.info/query?q=!Venerable+Monk)
- [x] [Verdant Touch](https://magiccards.info/query?q=!Verdant+Touch)
- [x] [Victual Sliver](https://magiccards.info/query?q=!Victual+Sliver)
- [x] [Volrath's Gardens](https://magiccards.info/query?q=!Volrath's+Gardens)
- [x] [Volrath's Laboratory](https://magiccards.info/query?q=!Volrath's+Laboratory)
- [x] [Volrath's Shapeshifter](https://magiccards.info/query?q=!Volrath's+Shapeshifter)
- [x] [Volrath's Stronghold](https://magiccards.info/query?q=!Volrath's+Stronghold)
- [x] [Walking Dream](https://magiccards.info/query?q=!Walking+Dream)
- [x] [Wall of Blossoms](https://magiccards.info/query?q=!Wall+of+Blossoms)
- [x] [Wall of Essence](https://magiccards.info/query?q=!Wall+of+Essence)
- [x] [Wall of Razors](https://magiccards.info/query?q=!Wall+of+Razors)
- [x] [Wall of Souls](https://magiccards.info/query?q=!Wall+of+Souls)
- [x] [Wall of Tears](https://magiccards.info/query?q=!Wall+of+Tears)
- [x] [Warrior Angel](https://magiccards.info/query?q=!Warrior+Angel)
- [x] [Warrior en-Kor](https://magiccards.info/query?q=!Warrior+en-Kor)
- [x] [Youthful Knight](https://magiccards.info/query?q=!Youthful+Knight)
