### ISSUE TITLE
EXO - Exodus Set Card Implementation Tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5381]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/exodus)

# Unimplemented Cards

# Cards in set:

- [x] [Aether Tide](https://magiccards.info/query?q=!Aether+Tide)
- [x] [Allay](https://magiccards.info/query?q=!Allay)
- [x] [Anarchist](https://magiccards.info/query?q=!Anarchist)
- [x] [Angelic Blessing](https://magiccards.info/query?q=!Angelic+Blessing)
- [x] [Avenging Druid](https://magiccards.info/query?q=!Avenging+Druid)
- [x] [Bequeathal](https://magiccards.info/query?q=!Bequeathal)
- [x] [Carnophage](https://magiccards.info/query?q=!Carnophage)
- [x] [Cartographer](https://magiccards.info/query?q=!Cartographer)
- [x] [Cat Burglar](https://magiccards.info/query?q=!Cat+Burglar)
- [x] [Cataclysm](https://magiccards.info/query?q=!Cataclysm)
- [x] [Charging Paladin](https://magiccards.info/query?q=!Charging+Paladin)
- [x] [Cinder Crawler](https://magiccards.info/query?q=!Cinder+Crawler)
- [x] [City of Traitors](https://magiccards.info/query?q=!City+of+Traitors)
- [x] [Coat of Arms](https://magiccards.info/query?q=!Coat+of+Arms)
- [x] [Convalescence](https://magiccards.info/query?q=!Convalescence)
- [x] [Crashing Boars](https://magiccards.info/query?q=!Crashing+Boars)
- [x] [Culling the Weak](https://magiccards.info/query?q=!Culling+the+Weak)
- [x] [Cunning](https://magiccards.info/query?q=!Cunning)
- [x] [Curiosity](https://magiccards.info/query?q=!Curiosity)
- [x] [Cursed Flesh](https://magiccards.info/query?q=!Cursed+Flesh)
- [x] [Dauthi Cutthroat](https://magiccards.info/query?q=!Dauthi+Cutthroat)
- [x] [Dauthi Jackal](https://magiccards.info/query?q=!Dauthi+Jackal)
- [x] [Dauthi Warlord](https://magiccards.info/query?q=!Dauthi+Warlord)
- [x] [Death's Duet](https://magiccards.info/query?q=!Death's+Duet)
- [x] [Dizzying Gaze](https://magiccards.info/query?q=!Dizzying+Gaze)
- [x] [Dominating Licid](https://magiccards.info/query?q=!Dominating+Licid)
- [x] [Elven Palisade](https://magiccards.info/query?q=!Elven+Palisade)
- [x] [Elvish Berserker](https://magiccards.info/query?q=!Elvish+Berserker)
- [x] [Entropic Specter](https://magiccards.info/query?q=!Entropic+Specter)
- [x] [Ephemeron](https://magiccards.info/query?q=!Ephemeron)
- [x] [Equilibrium](https://magiccards.info/query?q=!Equilibrium)
- [x] [Erratic Portal](https://magiccards.info/query?q=!Erratic+Portal)
- [x] [Ertai, Wizard Adept](https://magiccards.info/query?q=!Ertai,+Wizard+Adept)
- [x] [Exalted Dragon](https://magiccards.info/query?q=!Exalted+Dragon)
- [x] [Fade Away](https://magiccards.info/query?q=!Fade+Away)
- [x] [Fighting Chance](https://magiccards.info/query?q=!Fighting+Chance)
- [x] [Flowstone Flood](https://magiccards.info/query?q=!Flowstone+Flood)
- [x] [Forbid](https://magiccards.info/query?q=!Forbid)
- [x] [Fugue](https://magiccards.info/query?q=!Fugue)
- [x] [Furnace Brood](https://magiccards.info/query?q=!Furnace+Brood)
- [x] [Grollub](https://magiccards.info/query?q=!Grollub)
- [x] [Hatred](https://magiccards.info/query?q=!Hatred)
- [x] [High Ground](https://magiccards.info/query?q=!High+Ground)
- [x] [Jackalope Herd](https://magiccards.info/query?q=!Jackalope+Herd)
- [x] [Keeper of the Beasts](https://magiccards.info/query?q=!Keeper+of+the+Beasts)
- [x] [Keeper of the Dead](https://magiccards.info/query?q=!Keeper+of+the+Dead)
- [x] [Keeper of the Flame](https://magiccards.info/query?q=!Keeper+of+the+Flame)
- [x] [Keeper of the Light](https://magiccards.info/query?q=!Keeper+of+the+Light)
- [x] [Keeper of the Mind](https://magiccards.info/query?q=!Keeper+of+the+Mind)
- [x] [Killer Whale](https://magiccards.info/query?q=!Killer+Whale)
- [x] [Kor Chant](https://magiccards.info/query?q=!Kor+Chant)
- [x] [Limited Resources](https://magiccards.info/query?q=!Limited+Resources)
- [x] [Mage il-Vec](https://magiccards.info/query?q=!Mage+il-Vec)
- [x] [Mana Breach](https://magiccards.info/query?q=!Mana+Breach)
- [x] [Manabond](https://magiccards.info/query?q=!Manabond)
- [x] [Maniacal Rage](https://magiccards.info/query?q=!Maniacal+Rage)
- [x] [Medicine Bag](https://magiccards.info/query?q=!Medicine+Bag)
- [x] [Memory Crystal](https://magiccards.info/query?q=!Memory+Crystal)
- [x] [Merfolk Looter](https://magiccards.info/query?q=!Merfolk+Looter)
- [x] [Mind Maggots](https://magiccards.info/query?q=!Mind+Maggots)
- [x] [Mind Over Matter](https://magiccards.info/query?q=!Mind+Over+Matter)
- [x] [Mindless Automaton](https://magiccards.info/query?q=!Mindless+Automaton)
- [x] [Mirozel](https://magiccards.info/query?q=!Mirozel)
- [x] [Mirri, Cat Warrior](https://magiccards.info/query?q=!Mirri,+Cat+Warrior)
- [x] [Mogg Assassin](https://magiccards.info/query?q=!Mogg+Assassin)
- [x] [Monstrous Hound](https://magiccards.info/query?q=!Monstrous+Hound)
- [x] [Nausea](https://magiccards.info/query?q=!Nausea)
- [x] [Necrologia](https://magiccards.info/query?q=!Necrologia)
- [x] [Null Brooch](https://magiccards.info/query?q=!Null+Brooch)
- [x] [Oath of Druids](https://magiccards.info/query?q=!Oath+of+Druids)
- [x] [Oath of Ghouls](https://magiccards.info/query?q=!Oath+of+Ghouls)
- [x] [Oath of Lieges](https://magiccards.info/query?q=!Oath+of+Lieges)
- [x] [Oath of Mages](https://magiccards.info/query?q=!Oath+of+Mages)
- [x] [Oath of Scholars](https://magiccards.info/query?q=!Oath+of+Scholars)
- [x] [Ogre Shaman](https://magiccards.info/query?q=!Ogre+Shaman)
- [x] [Onslaught](https://magiccards.info/query?q=!Onslaught)
- [x] [Paladin en-Vec](https://magiccards.info/query?q=!Paladin+en-Vec)
- [x] [Pandemonium](https://magiccards.info/query?q=!Pandemonium)
- [x] [Paroxysm](https://magiccards.info/query?q=!Paroxysm)
- [x] [Peace of Mind](https://magiccards.info/query?q=!Peace+of+Mind)
- [x] [Pegasus Stampede](https://magiccards.info/query?q=!Pegasus+Stampede)
- [x] [Penance](https://magiccards.info/query?q=!Penance)
- [x] [Pit Spawn](https://magiccards.info/query?q=!Pit+Spawn)
- [x] [Plaguebearer](https://magiccards.info/query?q=!Plaguebearer)
- [x] [Plated Rootwalla](https://magiccards.info/query?q=!Plated+Rootwalla)
- [x] [Predatory Hunger](https://magiccards.info/query?q=!Predatory+Hunger)
- [x] [Price of Progress](https://magiccards.info/query?q=!Price+of+Progress)
- [x] [Pygmy Troll](https://magiccards.info/query?q=!Pygmy+Troll)
- [x] [Rabid Wolverines](https://magiccards.info/query?q=!Rabid+Wolverines)
- [x] [Raging Goblin](https://magiccards.info/query?q=!Raging+Goblin)
- [x] [Ravenous Baboons](https://magiccards.info/query?q=!Ravenous+Baboons)
- [x] [Reaping the Rewards](https://magiccards.info/query?q=!Reaping+the+Rewards)
- [x] [Reckless Ogre](https://magiccards.info/query?q=!Reckless+Ogre)
- [x] [Reclaim](https://magiccards.info/query?q=!Reclaim)
- [x] [Reconnaissance](https://magiccards.info/query?q=!Reconnaissance)
- [x] [Recurring Nightmare](https://magiccards.info/query?q=!Recurring+Nightmare)
- [x] [Resuscitate](https://magiccards.info/query?q=!Resuscitate)
- [x] [Robe of Mirrors](https://magiccards.info/query?q=!Robe+of+Mirrors)
- [x] [Rootwater Alligator](https://magiccards.info/query?q=!Rootwater+Alligator)
- [x] [Rootwater Mystic](https://magiccards.info/query?q=!Rootwater+Mystic)
- [x] [Sabertooth Wyvern](https://magiccards.info/query?q=!Sabertooth+Wyvern)
- [x] [Scalding Salamander](https://magiccards.info/query?q=!Scalding+Salamander)
- [x] [Scare Tactics](https://magiccards.info/query?q=!Scare+Tactics)
- [x] [School of Piranha](https://magiccards.info/query?q=!School+of+Piranha)
- [x] [Scrivener](https://magiccards.info/query?q=!Scrivener)
- [x] [Seismic Assault](https://magiccards.info/query?q=!Seismic+Assault)
- [x] [Shackles](https://magiccards.info/query?q=!Shackles)
- [x] [Shattering Pulse](https://magiccards.info/query?q=!Shattering+Pulse)
- [x] [Shield Mate](https://magiccards.info/query?q=!Shield+Mate)
- [x] [Skyshaper](https://magiccards.info/query?q=!Skyshaper)
- [x] [Skyshroud Elite](https://magiccards.info/query?q=!Skyshroud+Elite)
- [x] [Skyshroud War Beast](https://magiccards.info/query?q=!Skyshroud+War+Beast)
- [x] [Slaughter](https://magiccards.info/query?q=!Slaughter)
- [x] [Soltari Visionary](https://magiccards.info/query?q=!Soltari+Visionary)
- [x] [Song of Serenity](https://magiccards.info/query?q=!Song+of+Serenity)
- [x] [Sonic Burst](https://magiccards.info/query?q=!Sonic+Burst)
- [x] [Soul Warden](https://magiccards.info/query?q=!Soul+Warden)
- [x] [Spellbook](https://magiccards.info/query?q=!Spellbook)
- [x] [Spellshock](https://magiccards.info/query?q=!Spellshock)
- [x] [Sphere of Resistance](https://magiccards.info/query?q=!Sphere+of+Resistance)
- [x] [Spike Cannibal](https://magiccards.info/query?q=!Spike+Cannibal)
- [x] [Spike Hatcher](https://magiccards.info/query?q=!Spike+Hatcher)
- [x] [Spike Rogue](https://magiccards.info/query?q=!Spike+Rogue)
- [x] [Spike Weaver](https://magiccards.info/query?q=!Spike+Weaver)
- [x] [Standing Troops](https://magiccards.info/query?q=!Standing+Troops)
- [x] [Survival of the Fittest](https://magiccards.info/query?q=!Survival+of+the+Fittest)
- [x] [Thalakos Drifters](https://magiccards.info/query?q=!Thalakos+Drifters)
- [x] [Thalakos Scout](https://magiccards.info/query?q=!Thalakos+Scout)
- [x] [Theft of Dreams](https://magiccards.info/query?q=!Theft+of+Dreams)
- [x] [Thopter Squadron](https://magiccards.info/query?q=!Thopter+Squadron)
- [x] [Thrull Surgeon](https://magiccards.info/query?q=!Thrull+Surgeon)
- [x] [Transmogrifying Licid](https://magiccards.info/query?q=!Transmogrifying+Licid)
- [x] [Treasure Hunter](https://magiccards.info/query?q=!Treasure+Hunter)
- [x] [Treasure Trove](https://magiccards.info/query?q=!Treasure+Trove)
- [x] [Vampire Hounds](https://magiccards.info/query?q=!Vampire+Hounds)
- [x] [Volrath's Dungeon](https://magiccards.info/query?q=!Volrath's+Dungeon)
- [x] [Wall of Nets](https://magiccards.info/query?q=!Wall+of+Nets)
- [x] [Wayward Soul](https://magiccards.info/query?q=!Wayward+Soul)
- [x] [Welkin Hawk](https://magiccards.info/query?q=!Welkin+Hawk)
- [x] [Whiptongue Frog](https://magiccards.info/query?q=!Whiptongue+Frog)
- [x] [Wood Elves](https://magiccards.info/query?q=!Wood+Elves)
- [x] [Workhorse](https://magiccards.info/query?q=!Workhorse)
- [x] [Zealots en-Dal](https://magiccards.info/query?q=!Zealots+en-Dal)
