### ISSUE TITLE
ICE - Ice Age Set Card Implementation Tracking

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5382]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

[Product information](https://magic.wizards.com/en/products/ice-age)

# Unimplemented Cards out of current scope

- 59|[Balduvian Shaman](https://scryfall.com/search?q=%21"BalduvianShaman"+set:ICE)  <--- Text changing
- 99|[Sleight of Mind](https://scryfall.com/search?q=%21"SleightofMind"+set:ICE) <--- Text changing
- 308|[Amulet of Quoz](https://scryfall.com/search?q=%21"AmuletofQuoz"+set:ICE) <--- Ante

# Unimplemented Cards

- [x] [Adarkar Unicorn](https://scryfall.com/search?q=!"Adarkar+Unicorn"&nbsp;e:ICE)
- [x] [Hipparion](https://scryfall.com/search?q=!"Hipparion"&nbsp;e:ICE)
- [ ] [Mercenaries](https://scryfall.com/search?q=!"Mercenaries"&nbsp;e:ICE)
- [x] [Sacred Boon](https://scryfall.com/search?q=!"Sacred+Boon"&nbsp;e:ICE)
- [x] [Snowfall](https://scryfall.com/search?q=!"Snowfall"&nbsp;e:ICE)
- [ ] [Winter's Chill](https://scryfall.com/search?q=!"Winter's+Chill"&nbsp;e:ICE)
- [ ] [Spoils of War](https://scryfall.com/search?q=%21"SpoilsofWar"+set:ICE)
- [ ] [Barbarian Guides](https://scryfall.com/search?q=!"Barbarian+Guides"&nbsp;e:ICE)
- [x] [Bone Shaman](https://scryfall.com/search?q=!"Bone+Shaman"&nbsp;e:ICE)
- [x] [Goblin Ski Patrol](https://scryfall.com/search?q=!"Goblin+Ski+Patrol"&nbsp;e:ICE)
- [x] [Lava Burst](https://scryfall.com/search?q=!"Lava+Burst"&nbsp;e:ICE)
- [x] [Orcish Conscripts](https://scryfall.com/search?q=!"Orcish+Conscripts"&nbsp;e:ICE)
- [x] [Orcish Farmer](https://scryfall.com/search?q=!"Orcish+Farmer"&nbsp;e:ICE)
- [x] [Maddening Wind](https://scryfall.com/search?q=!"Maddening+Wind"&nbsp;e:ICE)
- [x] [Touch of Vitae](https://scryfall.com/search?q=!"Touch+of+Vitae"&nbsp;e:ICE)
- [ ] [Chromatic Armor](https://scryfall.com/search?q=!"Chromatic+Armor"&nbsp;e:ICE)
- [ ] [Ghostly Flame](https://scryfall.com/search?q=!"Ghostly+Flame"&nbsp;e:ICE)
- [x] [Arcum's Sleigh](https://scryfall.com/search?q=!"Arcum's+Sleigh"&nbsp;e:ICE)
- [x] [Arcum's Weathervane](https://scryfall.com/search?q=!"Arcum's+Weathervane"&nbsp;e:ICE)
- [ ] [Arcum's Whistle](https://scryfall.com/search?q=!"Arcum's+Whistle"&nbsp;e:ICE)

[Full list](https://scryfall.com/search?q=set%3AICE+%28cn%3D1+or+cn%3D31+or+cn%3D44+or+cn%3D50+or+cn%3D101+or+cn%3D107+or+cn%3D164+or+cn%3D174+or+cn%3D176+or+cn%3D190+or+cn%3D198+or+cn%3D206+or+cn%3D207+or+cn%3D254+or+cn%3D271+or+cn%3D283+or+cn%3D292+or+cn%3D309+or+cn%3D310+or+cn%3D311%29&order=set&dir=asc&unique=prints)

# Implemented Cards:

<details><summary>Click to expand</summary>

- [x] [Abyssal Specter](https://magiccards.info/query?q=!Abyssal+Specter)
- [x] [Adarkar Sentinel](https://magiccards.info/query?q=!Adarkar+Sentinel)
- [x] [Adarkar Wastes](https://magiccards.info/query?q=!Adarkar+Wastes)
- [x] [Aegis of the Meek](https://magiccards.info/query?q=!Aegis+of+the+Meek)
- [x] [Aggression](https://magiccards.info/query?q=!Aggression)
- [x] [Altar of Bone](https://magiccards.info/query?q=!Altar+of+Bone)
- [x] [Anarchy](https://magiccards.info/query?q=!Anarchy)
- [x] [Arenson's Aura](https://magiccards.info/query?q=!Arenson's+Aura)
- [x] [Armor of Faith](https://magiccards.info/query?q=!Armor+of+Faith)
- [x] [Arnjlot's Ascent](https://magiccards.info/query?q=!Arnjlot's+Ascent)
- [x] [Ashen Ghoul](https://magiccards.info/query?q=!Ashen+Ghoul)
- [x] [Aurochs](https://magiccards.info/query?q=!Aurochs)
- [x] [Avalanche](https://magiccards.info/query?q=!Avalanche)
- [x] [Balduvian Barbarians](https://magiccards.info/query?q=!Balduvian+Barbarians)
- [x] [Balduvian Bears](https://magiccards.info/query?q=!Balduvian+Bears)
- [x] [Balduvian Conjurer](https://magiccards.info/query?q=!Balduvian+Conjurer)
- [x] [Balduvian Hydra](https://magiccards.info/query?q=!Balduvian+Hydra)
- [x] [Barbed Sextant](https://magiccards.info/query?q=!Barbed+Sextant)
- [x] [Baton of Morale](https://magiccards.info/query?q=!Baton+of+Morale)
- [x] [Battle Cry](https://magiccards.info/query?q=!Battle+Cry)
- [x] [Battle Frenzy](https://magiccards.info/query?q=!Battle+Frenzy)
- [x] [Binding Grasp](https://magiccards.info/query?q=!Binding+Grasp)
- [x] [Black Scarab](https://magiccards.info/query?q=!Black+Scarab)
- [x] [Blessed Wine](https://magiccards.info/query?q=!Blessed+Wine)
- [x] [Blinking Spirit](https://magiccards.info/query?q=!Blinking+Spirit)
- [x] [Blizzard](https://magiccards.info/query?q=!Blizzard)
- [x] [Blue Scarab](https://magiccards.info/query?q=!Blue+Scarab)
- [x] [Brainstorm](https://magiccards.info/query?q=!Brainstorm)
- [x] [Brand of Ill Omen](https://magiccards.info/query?q=!Brand+of+Ill+Omen)
- [x] [Breath of Dreams](https://magiccards.info/query?q=!Breath+of+Dreams)
- [x] [Brine Shaman](https://magiccards.info/query?q=!Brine+Shaman)
- [x] [Brown Ouphe](https://magiccards.info/query?q=!Brown+Ouphe)
- [x] [Brushland](https://magiccards.info/query?q=!Brushland)
- [x] [Burnt Offering](https://magiccards.info/query?q=!Burnt+Offering)
- [x] [Call to Arms](https://magiccards.info/query?q=!Call+to+Arms)
- [x] [Caribou Range](https://magiccards.info/query?q=!Caribou+Range)
- [x] [Celestial Sword](https://magiccards.info/query?q=!Celestial+Sword)
- [x] [Centaur Archer](https://magiccards.info/query?q=!Centaur+Archer)
- [x] [Chaos Lord](https://magiccards.info/query?q=!Chaos+Lord)
- [x] [Chaos Moon](https://magiccards.info/query?q=!Chaos+Moon)
- [x] [Chub Toad](https://magiccards.info/query?q=!Chub+Toad)
- [x] [Circle of Protection: Black](https://magiccards.info/query?q=!Circle+of+Protection:+Black)
- [x] [Circle of Protection: Blue](https://magiccards.info/query?q=!Circle+of+Protection:+Blue)
- [x] [Circle of Protection: Green](https://magiccards.info/query?q=!Circle+of+Protection:+Green)
- [x] [Circle of Protection: Red](https://magiccards.info/query?q=!Circle+of+Protection:+Red)
- [x] [Circle of Protection: White](https://magiccards.info/query?q=!Circle+of+Protection:+White)
- [x] [Clairvoyance](https://magiccards.info/query?q=!Clairvoyance)
- [x] [Cloak of Confusion](https://magiccards.info/query?q=!Cloak+of+Confusion)
- [x] [Cold Snap](https://magiccards.info/query?q=!Cold+Snap)
- [x] [Conquer](https://magiccards.info/query?q=!Conquer)
- [x] [Cooperation](https://magiccards.info/query?q=!Cooperation)
- [x] [Counterspell](https://magiccards.info/query?q=!Counterspell)
- [x] [Crown of the Ages](https://magiccards.info/query?q=!Crown+of+the+Ages)
- [x] [Curse of Marit Lage](https://magiccards.info/query?q=!Curse+of+Marit+Lage)
- [x] [Dance of the Dead](https://magiccards.info/query?q=!Dance+of+the+Dead)
- [x] [Dark Banishing](https://magiccards.info/query?q=!Dark+Banishing)
- [x] [Dark Ritual](https://magiccards.info/query?q=!Dark+Ritual)
- [x] [Death Ward](https://magiccards.info/query?q=!Death+Ward)
- [x] [Deflection](https://magiccards.info/query?q=!Deflection)
- [x] [Demonic Consultation](https://magiccards.info/query?q=!Demonic+Consultation)
- [x] [Despotic Scepter](https://magiccards.info/query?q=!Despotic+Scepter)
- [x] [Diabolic Vision](https://magiccards.info/query?q=!Diabolic+Vision)
- [x] [Dire Wolves](https://magiccards.info/query?q=!Dire+Wolves)
- [x] [Disenchant](https://magiccards.info/query?q=!Disenchant)
- [x] [Dread Wight](https://magiccards.info/query?q=!Dread+Wight)
- [x] [Dreams of the Dead](https://magiccards.info/query?q=!Dreams+of+the+Dead)
- [x] [Drift of the Dead](https://magiccards.info/query?q=!Drift+of+the+Dead)
- [x] [Drought](https://magiccards.info/query?q=!Drought)
- [x] [Dwarven Armory](https://magiccards.info/query?q=!Dwarven+Armory)
- [x] [Earthlink](https://magiccards.info/query?q=!Earthlink)
- [x] [Earthlore](https://magiccards.info/query?q=!Earthlore)
- [x] [Elder Druid](https://magiccards.info/query?q=!Elder+Druid)
- [x] [Elemental Augury](https://magiccards.info/query?q=!Elemental+Augury)
- [x] [Elkin Bottle](https://magiccards.info/query?q=!Elkin+Bottle)
- [x] [Enduring Renewal](https://magiccards.info/query?q=!Enduring+Renewal)
- [x] [Energy Storm](https://magiccards.info/query?q=!Energy+Storm)
- [x] [Enervate](https://magiccards.info/query?q=!Enervate)
- [x] [Errant Minion](https://magiccards.info/query?q=!Errant+Minion)
- [x] [Errantry](https://magiccards.info/query?q=!Errantry)
- [x] [Essence Filter](https://magiccards.info/query?q=!Essence+Filter)
- [x] [Essence Flare](https://magiccards.info/query?q=!Essence+Flare)
- [x] [Fanatical Fever](https://magiccards.info/query?q=!Fanatical+Fever)
- [x] [Fear](https://magiccards.info/query?q=!Fear)
- [x] [Fiery Justice](https://magiccards.info/query?q=!Fiery+Justice)
- [x] [Fire Covenant](https://magiccards.info/query?q=!Fire+Covenant)
- [x] [Flame Spirit](https://magiccards.info/query?q=!Flame+Spirit)
- [x] [Flare](https://magiccards.info/query?q=!Flare)
- [x] [Flooded Woodlands](https://magiccards.info/query?q=!Flooded+Woodlands)
- [x] [Flow of Maggots](https://magiccards.info/query?q=!Flow+of+Maggots)
- [x] [Folk of the Pines](https://magiccards.info/query?q=!Folk+of+the+Pines)
- [x] [Forbidden Lore](https://magiccards.info/query?q=!Forbidden+Lore)
- [x] [Force Void](https://magiccards.info/query?q=!Force+Void)
- [x] [Forest](https://magiccards.info/query?q=!Forest)
- [x] [Forgotten Lore](https://magiccards.info/query?q=!Forgotten+Lore)
- [x] [Formation](https://magiccards.info/query?q=!Formation)
- [x] [Foul Familiar](https://magiccards.info/query?q=!Foul+Familiar)
- [x] [Foxfire](https://magiccards.info/query?q=!Foxfire)
- [x] [Freyalise Supplicant](https://magiccards.info/query?q=!Freyalise+Supplicant)
- [x] [Freyalise's Charm](https://magiccards.info/query?q=!Freyalise's+Charm)
- [x] [Freyalise's Winds](https://magiccards.info/query?q=!Freyalise's+Winds)
- [x] [Fumarole](https://magiccards.info/query?q=!Fumarole)
- [x] [Fylgja](https://magiccards.info/query?q=!Fylgja)
- [x] [Fyndhorn Bow](https://magiccards.info/query?q=!Fyndhorn+Bow)
- [x] [Fyndhorn Brownie](https://magiccards.info/query?q=!Fyndhorn+Brownie)
- [x] [Fyndhorn Elder](https://magiccards.info/query?q=!Fyndhorn+Elder)
- [x] [Fyndhorn Elves](https://magiccards.info/query?q=!Fyndhorn+Elves)
- [x] [Fyndhorn Pollen](https://magiccards.info/query?q=!Fyndhorn+Pollen)
- [x] [Game of Chaos](https://magiccards.info/query?q=!Game+of+Chaos)
- [x] [Gangrenous Zombies](https://magiccards.info/query?q=!Gangrenous+Zombies)
- [x] [Gaze of Pain](https://magiccards.info/query?q=!Gaze+of+Pain)
- [x] [General Jarkeld](https://magiccards.info/query?q=!General+Jarkeld)
- [x] [Giant Growth](https://magiccards.info/query?q=!Giant+Growth)
- [x] [Giant Trap Door Spider](https://magiccards.info/query?q=!Giant+Trap+Door+Spider)
- [x] [Glacial Chasm](https://magiccards.info/query?q=!Glacial+Chasm)
- [x] [Glacial Crevasses](https://magiccards.info/query?q=!Glacial+Crevasses)
- [x] [Glacial Wall](https://magiccards.info/query?q=!Glacial+Wall)
- [x] [Glaciers](https://magiccards.info/query?q=!Glaciers)
- [x] [Goblin Lyre](https://magiccards.info/query?q=!Goblin+Lyre)
- [x] [Goblin Mutant](https://magiccards.info/query?q=!Goblin+Mutant)
- [x] [Goblin Sappers](https://magiccards.info/query?q=!Goblin+Sappers)
- [x] [Goblin Snowman](https://magiccards.info/query?q=!Goblin+Snowman)
- [x] [Gorilla Pack](https://magiccards.info/query?q=!Gorilla+Pack)
- [x] [Gravebind](https://magiccards.info/query?q=!Gravebind)
- [x] [Green Scarab](https://magiccards.info/query?q=!Green+Scarab)
- [x] [Hallowed Ground](https://magiccards.info/query?q=!Hallowed+Ground)
- [x] [Halls of Mist](https://magiccards.info/query?q=!Halls+of+Mist)
- [x] [Heal](https://magiccards.info/query?q=!Heal)
- [x] [Hecatomb](https://magiccards.info/query?q=!Hecatomb)
- [x] [Hematite Talisman](https://magiccards.info/query?q=!Hematite+Talisman)
- [x] [Hoar Shade](https://magiccards.info/query?q=!Hoar+Shade)
- [x] [Hot Springs](https://magiccards.info/query?q=!Hot+Springs)
- [x] [Howl from Beyond](https://magiccards.info/query?q=!Howl+from+Beyond)
- [x] [Hurricane](https://magiccards.info/query?q=!Hurricane)
- [x] [Hyalopterous Lemure](https://magiccards.info/query?q=!Hyalopterous+Lemure)
- [x] [Hydroblast](https://magiccards.info/query?q=!Hydroblast)
- [x] [Hymn of Rebirth](https://magiccards.info/query?q=!Hymn+of+Rebirth)
- [x] [Ice Cauldron](https://magiccards.info/query?q=!Ice+Cauldron)
- [x] [Ice Floe](https://magiccards.info/query?q=!Ice+Floe)
- [x] [Iceberg](https://magiccards.info/query?q=!Iceberg)
- [x] [Icequake](https://magiccards.info/query?q=!Icequake)
- [x] [Icy Manipulator](https://magiccards.info/query?q=!Icy+Manipulator)
- [x] [Icy Prison](https://magiccards.info/query?q=!Icy+Prison)
- [x] [Illusionary Forces](https://magiccards.info/query?q=!Illusionary+Forces)
- [x] [Illusionary Presence](https://magiccards.info/query?q=!Illusionary+Presence)
- [x] [Illusionary Terrain](https://magiccards.info/query?q=!Illusionary+Terrain)
- [x] [Illusionary Wall](https://magiccards.info/query?q=!Illusionary+Wall)
- [x] [Illusions of Grandeur](https://magiccards.info/query?q=!Illusions+of+Grandeur)
- [x] [Imposing Visage](https://magiccards.info/query?q=!Imposing+Visage)
- [x] [Incinerate](https://magiccards.info/query?q=!Incinerate)
- [x] [Infernal Darkness](https://magiccards.info/query?q=!Infernal+Darkness)
- [x] [Infernal Denizen](https://magiccards.info/query?q=!Infernal+Denizen)
- [x] [Infinite Hourglass](https://magiccards.info/query?q=!Infinite+Hourglass)
- [x] [Infuse](https://magiccards.info/query?q=!Infuse)
- [x] [Island](https://magiccards.info/query?q=!Island)
- [x] [Jester's Cap](https://magiccards.info/query?q=!Jester's+Cap)
- [x] [Jester's Mask](https://magiccards.info/query?q=!Jester's+Mask)
- [x] [Jeweled Amulet](https://magiccards.info/query?q=!Jeweled+Amulet)
- [x] [Johtull Wurm](https://magiccards.info/query?q=!Johtull+Wurm)
- [x] [Jokulhaups](https://magiccards.info/query?q=!Jokulhaups)
- [x] [Juniper Order Druid](https://magiccards.info/query?q=!Juniper+Order+Druid)
- [x] [Justice](https://magiccards.info/query?q=!Justice)
- [x] [Karplusan Forest](https://magiccards.info/query?q=!Karplusan+Forest)
- [x] [Karplusan Giant](https://magiccards.info/query?q=!Karplusan+Giant)
- [x] [Karplusan Yeti](https://magiccards.info/query?q=!Karplusan+Yeti)
- [x] [Kelsinko Ranger](https://magiccards.info/query?q=!Kelsinko+Ranger)
- [x] [Kjeldoran Dead](https://magiccards.info/query?q=!Kjeldoran+Dead)
- [x] [Kjeldoran Elite Guard](https://magiccards.info/query?q=!Kjeldoran+Elite+Guard)
- [x] [Kjeldoran Frostbeast](https://magiccards.info/query?q=!Kjeldoran+Frostbeast)
- [x] [Kjeldoran Guard](https://magiccards.info/query?q=!Kjeldoran+Guard)
- [x] [Kjeldoran Knight](https://magiccards.info/query?q=!Kjeldoran+Knight)
- [x] [Kjeldoran Phalanx](https://magiccards.info/query?q=!Kjeldoran+Phalanx)
- [x] [Kjeldoran Royal Guard](https://magiccards.info/query?q=!Kjeldoran+Royal+Guard)
- [x] [Kjeldoran Skycaptain](https://magiccards.info/query?q=!Kjeldoran+Skycaptain)
- [x] [Kjeldoran Skyknight](https://magiccards.info/query?q=!Kjeldoran+Skyknight)
- [x] [Kjeldoran Warrior](https://magiccards.info/query?q=!Kjeldoran+Warrior)
- [x] [Knight of Stromgald](https://magiccards.info/query?q=!Knight+of+Stromgald)
- [x] [Krovikan Elementalist](https://magiccards.info/query?q=!Krovikan+Elementalist)
- [x] [Krovikan Fetish](https://magiccards.info/query?q=!Krovikan+Fetish)
- [x] [Krovikan Sorcerer](https://magiccards.info/query?q=!Krovikan+Sorcerer)
- [x] [Krovikan Vampire](https://magiccards.info/query?q=!Krovikan+Vampire)
- [x] [Land Cap](https://magiccards.info/query?q=!Land+Cap)
- [x] [Lapis Lazuli Talisman](https://magiccards.info/query?q=!Lapis+Lazuli+Talisman)
- [x] [Lava Tubes](https://magiccards.info/query?q=!Lava+Tubes)
- [x] [Legions of Lim-Dul](https://magiccards.info/query?q=!Legions+of+Lim-Dul)
- [x] [Leshrac's Rite](https://magiccards.info/query?q=!Leshrac's+Rite)
- [x] [Leshrac's Sigil](https://magiccards.info/query?q=!Leshrac's+Sigil)
- [x] [Lhurgoyf](https://magiccards.info/query?q=!Lhurgoyf)
- [x] [Lightning Blow](https://magiccards.info/query?q=!Lightning+Blow)
- [x] [Lim-Dul's Hex](https://magiccards.info/query?q=!Lim-Dul's+Hex)
- [x] [Lure](https://magiccards.info/query?q=!Lure)
- [x] [Magus of the Unseen](https://magiccards.info/query?q=!Magus+of+the+Unseen)
- [x] [Malachite Talisman](https://magiccards.info/query?q=!Malachite+Talisman)
- [x] [Marton Stromgald](https://magiccards.info/query?q=!Marton+Stromgald)
- [x] [Melee](https://magiccards.info/query?q=!Melee)
- [x] [Melting](https://magiccards.info/query?q=!Melting)
- [x] [Merieke Ri Berit](https://magiccards.info/query?q=!Merieke+Ri+Berit)
- [x] [Mesmeric Trance](https://magiccards.info/query?q=!Mesmeric+Trance)
- [x] [Meteor Shower](https://magiccards.info/query?q=!Meteor+Shower)
- [x] [Mind Ravel](https://magiccards.info/query?q=!Mind+Ravel)
- [x] [Mind Warp](https://magiccards.info/query?q=!Mind+Warp)
- [x] [Minion of Leshrac](https://magiccards.info/query?q=!Minion+of+Leshrac)
- [x] [Minion of Tevesh Szat](https://magiccards.info/query?q=!Minion+of+Tevesh+Szat)
- [x] [Mistfolk](https://magiccards.info/query?q=!Mistfolk)
- [x] [Mole Worms](https://magiccards.info/query?q=!Mole+Worms)
- [x] [Monsoon](https://magiccards.info/query?q=!Monsoon)
- [x] [Moor Fiend](https://magiccards.info/query?q=!Moor+Fiend)
- [x] [Mountain](https://magiccards.info/query?q=!Mountain)
- [x] [Mountain Goat](https://magiccards.info/query?q=!Mountain+Goat)
- [x] [Mountain Titan](https://magiccards.info/query?q=!Mountain+Titan)
- [x] [Mudslide](https://magiccards.info/query?q=!Mudslide)
- [x] [Musician](https://magiccards.info/query?q=!Musician)
- [x] [Mystic Might](https://magiccards.info/query?q=!Mystic+Might)
- [x] [Mystic Remora](https://magiccards.info/query?q=!Mystic+Remora)
- [x] [Nacre Talisman](https://magiccards.info/query?q=!Nacre+Talisman)
- [x] [Naked Singularity](https://magiccards.info/query?q=!Naked+Singularity)
- [x] [Nature's Lore](https://magiccards.info/query?q=!Nature's+Lore)
- [x] [Necropotence](https://magiccards.info/query?q=!Necropotence)
- [x] [Norritt](https://magiccards.info/query?q=!Norritt)
- [x] [Oath of Lim-Dul](https://magiccards.info/query?q=!Oath+of+Lim-Dul)
- [x] [Onyx Talisman](https://magiccards.info/query?q=!Onyx+Talisman)
- [x] [Orcish Cannoneers](https://magiccards.info/query?q=!Orcish+Cannoneers)
- [x] [Orcish Healer](https://magiccards.info/query?q=!Orcish+Healer)
- [x] [Orcish Librarian](https://magiccards.info/query?q=!Orcish+Librarian)
- [x] [Orcish Lumberjack](https://magiccards.info/query?q=!Orcish+Lumberjack)
- [x] [Orcish Squatters](https://magiccards.info/query?q=!Orcish+Squatters)
- [x] [Order of the Sacred Torch](https://magiccards.info/query?q=!Order+of+the+Sacred+Torch)
- [x] [Order of the White Shield](https://magiccards.info/query?q=!Order+of+the+White+Shield)
- [x] [Pale Bears](https://magiccards.info/query?q=!Pale+Bears)
- [x] [Panic](https://magiccards.info/query?q=!Panic)
- [x] [Pentagram of the Ages](https://magiccards.info/query?q=!Pentagram+of+the+Ages)
- [x] [Pestilence Rats](https://magiccards.info/query?q=!Pestilence+Rats)
- [x] [Phantasmal Mount](https://magiccards.info/query?q=!Phantasmal+Mount)
- [x] [Pit Trap](https://magiccards.info/query?q=!Pit+Trap)
- [x] [Plains](https://magiccards.info/query?q=!Plains)
- [x] [Polar Kraken](https://magiccards.info/query?q=!Polar+Kraken)
- [x] [Portent](https://magiccards.info/query?q=!Portent)
- [x] [Power Sink](https://magiccards.info/query?q=!Power+Sink)
- [x] [Pox](https://magiccards.info/query?q=!Pox)
- [x] [Prismatic Ward](https://magiccards.info/query?q=!Prismatic+Ward)
- [x] [Pygmy Allosaurus](https://magiccards.info/query?q=!Pygmy+Allosaurus)
- [x] [Pyknite](https://magiccards.info/query?q=!Pyknite)
- [x] [Pyroblast](https://magiccards.info/query?q=!Pyroblast)
- [x] [Pyroclasm](https://magiccards.info/query?q=!Pyroclasm)
- [x] [Rally](https://magiccards.info/query?q=!Rally)
- [x] [Ray of Command](https://magiccards.info/query?q=!Ray+of+Command)
- [x] [Ray of Erasure](https://magiccards.info/query?q=!Ray+of+Erasure)
- [x] [Reality Twist](https://magiccards.info/query?q=!Reality+Twist)
- [x] [Reclamation](https://magiccards.info/query?q=!Reclamation)
- [x] [Red Scarab](https://magiccards.info/query?q=!Red+Scarab)
- [x] [Regeneration](https://magiccards.info/query?q=!Regeneration)
- [x] [Rime Dryad](https://magiccards.info/query?q=!Rime+Dryad)
- [x] [Ritual of Subdual](https://magiccards.info/query?q=!Ritual+of+Subdual)
- [x] [River Delta](https://magiccards.info/query?q=!River+Delta)
- [x] [Runed Arch](https://magiccards.info/query?q=!Runed+Arch)
- [x] [Sabretooth Tiger](https://magiccards.info/query?q=!Sabretooth+Tiger)
- [x] [Scaled Wurm](https://magiccards.info/query?q=!Scaled+Wurm)
- [x] [Sea Spirit](https://magiccards.info/query?q=!Sea+Spirit)
- [x] [Seizures](https://magiccards.info/query?q=!Seizures)
- [x] [Seraph](https://magiccards.info/query?q=!Seraph)
- [x] [Shambling Strider](https://magiccards.info/query?q=!Shambling+Strider)
- [x] [Shatter](https://magiccards.info/query?q=!Shatter)
- [x] [Shield Bearer](https://magiccards.info/query?q=!Shield+Bearer)
- [x] [Shield of the Ages](https://magiccards.info/query?q=!Shield+of+the+Ages)
- [x] [Shyft](https://magiccards.info/query?q=!Shyft)
- [x] [Sibilant Spirit](https://magiccards.info/query?q=!Sibilant+Spirit)
- [x] [Silver Erne](https://magiccards.info/query?q=!Silver+Erne)
- [x] [Skeleton Ship](https://magiccards.info/query?q=!Skeleton+Ship)
- [x] [Skull Catapult](https://magiccards.info/query?q=!Skull+Catapult)
- [x] [Snow Devil](https://magiccards.info/query?q=!Snow+Devil)
- [x] [Snow Fortress](https://magiccards.info/query?q=!Snow+Fortress)
- [x] [Snow Hound](https://magiccards.info/query?q=!Snow+Hound)
- [x] [Snow-Covered Forest](https://magiccards.info/query?q=!Snow-Covered+Forest)
- [x] [Snow-Covered Island](https://magiccards.info/query?q=!Snow-Covered+Island)
- [x] [Snow-Covered Mountain](https://magiccards.info/query?q=!Snow-Covered+Mountain)
- [x] [Snow-Covered Plains](https://magiccards.info/query?q=!Snow-Covered+Plains)
- [x] [Snow-Covered Swamp](https://magiccards.info/query?q=!Snow-Covered+Swamp)
- [x] [Soldevi Golem](https://magiccards.info/query?q=!Soldevi+Golem)
- [x] [Soldevi Machinist](https://magiccards.info/query?q=!Soldevi+Machinist)
- [x] [Soldevi Simulacrum](https://magiccards.info/query?q=!Soldevi+Simulacrum)
- [x] [Songs of the Damned](https://magiccards.info/query?q=!Songs+of+the+Damned)
- [x] [Soul Barrier](https://magiccards.info/query?q=!Soul+Barrier)
- [x] [Soul Burn](https://magiccards.info/query?q=!Soul+Burn)
- [x] [Soul Kiss](https://magiccards.info/query?q=!Soul+Kiss)
- [x] [Spoils of Evil](https://magiccards.info/query?q=!Spoils+of+Evil)
- [x] [Staff of the Ages](https://magiccards.info/query?q=!Staff+of+the+Ages)
- [x] [Stampede](https://magiccards.info/query?q=!Stampede)
- [x] [Stench of Evil](https://magiccards.info/query?q=!Stench+of+Evil)
- [x] [Stone Rain](https://magiccards.info/query?q=!Stone+Rain)
- [x] [Stone Spirit](https://magiccards.info/query?q=!Stone+Spirit)
- [x] [Stonehands](https://magiccards.info/query?q=!Stonehands)
- [x] [Storm Spirit](https://magiccards.info/query?q=!Storm+Spirit)
- [x] [Stormbind](https://magiccards.info/query?q=!Stormbind)
- [x] [Stromgald Cabal](https://magiccards.info/query?q=!Stromgald+Cabal)
- [x] [Stunted Growth](https://magiccards.info/query?q=!Stunted+Growth)
- [x] [Sulfurous Springs](https://magiccards.info/query?q=!Sulfurous+Springs)
- [x] [Sunstone](https://magiccards.info/query?q=!Sunstone)
- [x] [Swamp](https://magiccards.info/query?q=!Swamp)
- [x] [Swords to Plowshares](https://magiccards.info/query?q=!Swords+to+Plowshares)
- [x] [Tarpan](https://magiccards.info/query?q=!Tarpan)
- [x] [Thermokarst](https://magiccards.info/query?q=!Thermokarst)
- [x] [Thoughtleech](https://magiccards.info/query?q=!Thoughtleech)
- [x] [Thunder Wall](https://magiccards.info/query?q=!Thunder+Wall)
- [x] [Timberline Ridge](https://magiccards.info/query?q=!Timberline+Ridge)
- [x] [Time Bomb](https://magiccards.info/query?q=!Time+Bomb)
- [x] [Tinder Wall](https://magiccards.info/query?q=!Tinder+Wall)
- [x] [Tor Giant](https://magiccards.info/query?q=!Tor+Giant)
- [x] [Total War](https://magiccards.info/query?q=!Total+War)
- [x] [Touch of Death](https://magiccards.info/query?q=!Touch+of+Death)
- [x] [Trailblazer](https://magiccards.info/query?q=!Trailblazer)
- [x] [Underground River](https://magiccards.info/query?q=!Underground+River)
- [x] [Updraft](https://magiccards.info/query?q=!Updraft)
- [x] [Urza's Bauble](https://magiccards.info/query?q=!Urza's+Bauble)
- [x] [Veldt](https://magiccards.info/query?q=!Veldt)
- [x] [Venomous Breath](https://magiccards.info/query?q=!Venomous+Breath)
- [x] [Vertigo](https://magiccards.info/query?q=!Vertigo)
- [x] [Vexing Arcanix](https://magiccards.info/query?q=!Vexing+Arcanix)
- [x] [Vibrating Sphere](https://magiccards.info/query?q=!Vibrating+Sphere)
- [x] [Walking Wall](https://magiccards.info/query?q=!Walking+Wall)
- [x] [Wall of Lava](https://magiccards.info/query?q=!Wall+of+Lava)
- [x] [Wall of Pine Needles](https://magiccards.info/query?q=!Wall+of+Pine+Needles)
- [x] [Wall of Shields](https://magiccards.info/query?q=!Wall+of+Shields)
- [x] [War Chariot](https://magiccards.info/query?q=!War+Chariot)
- [x] [Warning](https://magiccards.info/query?q=!Warning)
- [x] [Whalebone Glider](https://magiccards.info/query?q=!Whalebone+Glider)
- [x] [White Scarab](https://magiccards.info/query?q=!White+Scarab)
- [x] [Whiteout](https://magiccards.info/query?q=!Whiteout)
- [x] [Wiitigo](https://magiccards.info/query?q=!Wiitigo)
- [x] [Wild Growth](https://magiccards.info/query?q=!Wild+Growth)
- [x] [Wind Spirit](https://magiccards.info/query?q=!Wind+Spirit)
- [x] [Wings of Aesthir](https://magiccards.info/query?q=!Wings+of+Aesthir)
- [x] [Withering Wisps](https://magiccards.info/query?q=!Withering+Wisps)
- [x] [Woolly Mammoths](https://magiccards.info/query?q=!Woolly+Mammoths)
- [x] [Woolly Spider](https://magiccards.info/query?q=!Woolly+Spider)
- [x] [Word of Blasting](https://magiccards.info/query?q=!Word+of+Blasting)
- [x] [Word of Undoing](https://magiccards.info/query?q=!Word+of+Undoing)
- [x] [Wrath of Marit Lage](https://magiccards.info/query?q=!Wrath+of+Marit+Lage)
- [x] [Yavimaya Gnats](https://magiccards.info/query?q=!Yavimaya+Gnats)
- [x] [Zur's Weirding](https://magiccards.info/query?q=!Zur's+Weirding)
- [x] [Zuran Enchanter](https://magiccards.info/query?q=!Zuran+Enchanter)
- [x] [Zuran Orb](https://magiccards.info/query?q=!Zuran+Orb)
- [x] [Zuran Spellcaster](https://magiccards.info/query?q=!Zuran+Spellcaster)

</details>

**Comment by Susucre** [comment]
Cleaned the list.
Out of scope are Ante (#11319) and Text change (#2082)

**Comment by Cguy7777** [comment]
Working on Maddening Wind

**Comment by Cguy7777** [comment]
Working on Hipparion

**Comment by Cguy7777** [comment]
Working on Touch of Vitae

**Comment by Cguy7777** [comment]
Working on Arcum's Sleigh
