### ISSUE TITLE
DEVS: NPE errors and checks

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5471]
Some cards and abilities source missing of `null` checks and can cause NPE errors (NullPointerException) and ruined the game and even the **server** (#4520). AI games heavy affected by that errors (computer uses and simulates all possible actions per priority and catches it very often).

Error example:
```
java.lang.NullPointerException
        at mage.players.PlayerImpl.playLand(PlayerImpl.java:1127)
        at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1268)
        at mage.player.ai.ComputerPlayer.activateAbility(ComputerPlayer.java:1100)
        at mage.player.ai.ComputerPlayer6.act(ComputerPlayer6.java:176)
        at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:63)
        at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:37)
        at mage.game.GameImpl.playPriority(GameImpl.java:1328)
```

Problem code example (null checks must be in `playLand`):
![shot_181223_190541](https://user-images.githubusercontent.com/8344157/50384930-c130f780-06e5-11e9-87da-5ac83d6e7cb2.png)

Regexp search pattern for potential errors:
 * `(\S+) = game\.getCard(?!(.+\n.*){1,3}(?=(?=\1 != null)|(?=\1 == null)|(?=\1 instanceof)|(?=moveCards\(\1)|(?=match\(\1)))`
 * You can use same patterns for other calls like `game.getPlayer`.

TODO for source checks:
 * [x] `game.getCard` (JayDi85);
 * [x] `game.getPlayer(***)` (Ingmar Goudt)
 * [ ] `game.getPlayer(playerId).somecode` (regexp search: `game\.getPlayer[(][^(]+?[)]\.`);
 * [ ] `game.getObject`
 * [ ] `game.getState().getValue`
 * [x] `game.getState().getWatchers().get`
 * [ ] `.getFirstTarget()`
 * [x] `.getImprinted()` (JayDi85)
 * [ ] `get(0).getTargetName()`
 * [ ] `game.getPermanent`
 * [ ] `.getFromTop(game)`
 * [ ] `.getSpellAbility().` (aura tokens don't have spell ability, example #5285), search: `((?<!this\.)(?<! )(?<!getLeftHalfCard\(\)\.)(?<!getRightHalfCard\(\)\.))getSpellAbility\(\)\.` (needs 150+ fixes)
 * [ ] extra: write tests to check empty targets in abilities (with "target" texts)
 * if you want to help then choose problem source and edit/comments here.

**Comment by ingmargoudt** [comment]
I will check game.getPlayer . 
Please note that sometimes the nullcheck is not done on the direct next line, but a bit further. Is it possible to have the regex support that?

**Comment by JayDi85** [comment]
Yep, it's a little problem. I haven't that regexp. You must check code manually anyway (IntelliJ IDEA have a useful code preview). Also it's can be without null checks at all but works fine (see `playLand` example -- it's already contain checks).

![shot_181227_174016](https://user-images.githubusercontent.com/8344157/50482132-83daab80-09fe-11e9-9476-1ae22e46c912.png)

**Comment by ingmargoudt** [comment]
#09dd9d5a

**Comment by JayDi85** [comment]
Improved search pattern (remove some compares for speedup):
 * ` (\S+) = game\.getCard(?!(.+\n.*){1,3}(?=(?=\1 != null)|(?=\1 == null)|(?=\1 instanceof)|(?=moveCards\(\1)|(?=match\(\1)))`

It's support:
 * 3 lines ahead search;
 * xxx != null
 * xxx == null
 * .match(xxx
 * moveCards(xxx
 * xxx instanceof

```
// tests
// custom

// no instanceof
Card card = game.getCard(sourceId);
card instanceof xxx

// no moveCards
Card card = game.getCard(sourceId);
moveCards(card

// no match
Card card = game.getCard(sourceId);
.match(card

// != null

// no 1
Card card = game.getCard(sourceId);
if (player != null && player.getHand().contains(sourceId) && card != null) {

// no 2
Card card = game.getCard(sourceId);        
Player player = game.getPlayer(controllerId);
if (player != null && player.getHand().contains(sourceId) && card != null) {

// yes 2
Card card123 = game.getCard(sourceId);
Player player = game.getPlayer(controllerId);
if (player != null && player.getHand().contains(sourceId) && card != null) {

// no 3
Card card = game.getCard(sourceId);
Player player = game.getPlayer(controllerId);
Player player = game.getPlayer(controllerId);
if (player != null && player.getHand().contains(sourceId) && card != null) {

// yes 4
Card card = game.getCard(sourceId);
Player player = game.getPlayer(controllerId);
Player player = game.getPlayer(controllerId);
Player player = game.getPlayer(controllerId);
if (player != null && player.getHand().contains(sourceId) && card != null) {

// tests
// == null

// no 1
Card card = game.getCard(sourceId);        
if (player != null && player.getHand().contains(sourceId) && card == null) {

// no 2
Card card = game.getCard(sourceId);        
Player player = game.getPlayer(controllerId);
if (player != null && player.getHand().contains(sourceId) && card == null) {

// no 3
Card card = game.getCard(sourceId);
Player player = game.getPlayer(controllerId);
Player player = game.getPlayer(controllerId);
if (player != null && player.getHand().contains(sourceId) && card == null) {

// yes 4
Card card = game.getCard(sourceId);
Player player = game.getPlayer(controllerId);
Player player = game.getPlayer(controllerId);
Player player = game.getPlayer(controllerId);
if (player != null && player.getHand().contains(sourceId) && card == null) {
```

**Comment by JayDi85** [comment]
It’s about code style and code review. Not actual anymore.
