### ISSUE TITLE
WTH - Weatherlight set card implementation tracker

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5489]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Cards unimplemented in set

- [x] [Ertai's Familiar](https://scryfall.com/card/wth/38/ertais-familiar)

# Cards in set:
- [x] [Abduction](https://scryfall.com/search?q=!"Abduction"&nbsp;e:Weatherlight)
- [x] [Abeyance](https://scryfall.com/search?q=!"Abeyance"&nbsp;e:Weatherlight)
- [x] [Abjure](https://scryfall.com/search?q=!"Abjure"&nbsp;e:Weatherlight)
- [x] [Aboroth](https://scryfall.com/search?q=!"Aboroth"&nbsp;e:Weatherlight)
- [x] [Abyssal Gatekeeper](https://scryfall.com/search?q=!"Abyssal+Gatekeeper"&nbsp;e:Weatherlight)
- [x] [Aether Flash](https://scryfall.com/search?q=!"Aether+Flash"&nbsp;e:Weatherlight)
- [x] [Agonizing Memories](https://scryfall.com/search?q=!"Agonizing+Memories"&nbsp;e:Weatherlight)
- [x] [Alabaster Dragon](https://scryfall.com/search?q=!"Alabaster+Dragon"&nbsp;e:Weatherlight)
- [x] [Alms](https://scryfall.com/search?q=!"Alms"&nbsp;e:Weatherlight)
- [x] [Ancestral Knowledge](https://scryfall.com/search?q=!"Ancestral+Knowledge"&nbsp;e:Weatherlight)
- [x] [Angelic Renewal](https://scryfall.com/search?q=!"Angelic+Renewal"&nbsp;e:Weatherlight)
- [x] [Apathy](https://scryfall.com/search?q=!"Apathy"&nbsp;e:Weatherlight)
- [x] [Arctic Wolves](https://scryfall.com/search?q=!"Arctic+Wolves"&nbsp;e:Weatherlight)
- [x] [Ardent Militia](https://scryfall.com/search?q=!"Ardent+Militia"&nbsp;e:Weatherlight)
- [x] [Argivian Find](https://scryfall.com/search?q=!"Argivian+Find"&nbsp;e:Weatherlight)
- [x] [Argivian Restoration](https://scryfall.com/search?q=!"Argivian+Restoration"&nbsp;e:Weatherlight)
- [x] [Aura of Silence](https://scryfall.com/search?q=!"Aura+of+Silence"&nbsp;e:Weatherlight)
- [x] [Avizoa](https://scryfall.com/search?q=!"Avizoa"&nbsp;e:Weatherlight)
- [x] [Barishi](https://scryfall.com/search?q=!"Barishi"&nbsp;e:Weatherlight)
- [x] [Barrow Ghoul](https://scryfall.com/search?q=!"Barrow+Ghoul"&nbsp;e:Weatherlight)
- [x] [Benalish Infantry](https://scryfall.com/search?q=!"Benalish+Infantry"&nbsp;e:Weatherlight)
- [x] [Benalish Knight](https://scryfall.com/search?q=!"Benalish+Knight"&nbsp;e:Weatherlight)
- [x] [Benalish Missionary](https://scryfall.com/search?q=!"Benalish+Missionary"&nbsp;e:Weatherlight)
- [x] [Betrothed of Fire](https://scryfall.com/search?q=!"Betrothed+of+Fire"&nbsp;e:Weatherlight)
- [x] [Bloodrock Cyclops](https://scryfall.com/search?q=!"Bloodrock+Cyclops"&nbsp;e:Weatherlight)
- [x] [Blossoming Wreath](https://scryfall.com/search?q=!"Blossoming+Wreath"&nbsp;e:Weatherlight)
- [x] [Bogardan Firefiend](https://scryfall.com/search?q=!"Bogardan+Firefiend"&nbsp;e:Weatherlight)
- [x] [Boiling Blood](https://scryfall.com/search?q=!"Boiling+Blood"&nbsp;e:Weatherlight)
- [x] [Bone Dancer](https://scryfall.com/search?q=!"Bone+Dancer"&nbsp;e:Weatherlight)
- [x] [Bosium Strip](https://scryfall.com/search?q=!"Bosium+Strip"&nbsp;e:Weatherlight)
- [x] [Briar Shield](https://scryfall.com/search?q=!"Briar+Shield"&nbsp;e:Weatherlight)
- [x] [Bubble Matrix](https://scryfall.com/search?q=!"Bubble+Matrix"&nbsp;e:Weatherlight)
- [x] [Buried Alive](https://scryfall.com/search?q=!"Buried+Alive"&nbsp;e:Weatherlight)
- [x] [Call of the Wild](https://scryfall.com/search?q=!"Call+of+the+Wild"&nbsp;e:Weatherlight)
- [x] [Chimeric Sphere](https://scryfall.com/search?q=!"Chimeric+Sphere"&nbsp;e:Weatherlight)
- [x] [Choking Vines](https://scryfall.com/search?q=!"Choking+Vines"&nbsp;e:Weatherlight)
- [x] [Cinder Giant](https://scryfall.com/search?q=!"Cinder+Giant"&nbsp;e:Weatherlight)
- [x] [Cinder Wall](https://scryfall.com/search?q=!"Cinder+Wall"&nbsp;e:Weatherlight)
- [x] [Circling Vultures](https://scryfall.com/search?q=!"Circling+Vultures"&nbsp;e:Weatherlight)
- [x] [Cloud Djinn](https://scryfall.com/search?q=!"Cloud+Djinn"&nbsp;e:Weatherlight)
- [x] [Coils of the Medusa](https://scryfall.com/search?q=!"Coils+of+the+Medusa"&nbsp;e:Weatherlight)
- [x] [Cone of Flame](https://scryfall.com/search?q=!"Cone+of+Flame"&nbsp;e:Weatherlight)
- [x] [Debt of Loyalty](https://scryfall.com/search?q=!"Debt+of+Loyalty"&nbsp;e:Weatherlight)
- [x] [Dense Foliage](https://scryfall.com/search?q=!"Dense+Foliage"&nbsp;e:Weatherlight)
- [x] [Desperate Gambit](https://scryfall.com/search?q=!"Desperate+Gambit"&nbsp;e:Weatherlight)
- [x] [Dingus Staff](https://scryfall.com/search?q=!"Dingus+Staff"&nbsp;e:Weatherlight)
- [x] [Disrupt](https://scryfall.com/search?q=!"Disrupt"&nbsp;e:Weatherlight)
- [x] [Doomsday](https://scryfall.com/search?q=!"Doomsday"&nbsp;e:Weatherlight)
- [x] [Downdraft](https://scryfall.com/search?q=!"Downdraft"&nbsp;e:Weatherlight)
- [x] [Duskrider Falcon](https://scryfall.com/search?q=!"Duskrider+Falcon"&nbsp;e:Weatherlight)
- [x] [Dwarven Berserker](https://scryfall.com/search?q=!"Dwarven+Berserker"&nbsp;e:Weatherlight)
- [x] [Dwarven Thaumaturgist](https://scryfall.com/search?q=!"Dwarven+Thaumaturgist"&nbsp;e:Weatherlight)
- [x] [Empyrial Armor](https://scryfall.com/search?q=!"Empyrial+Armor"&nbsp;e:Weatherlight)
- [x] [Ertai's Familiar](https://scryfall.com/search?q=!"Ertai's+Familiar"&nbsp;e:Weatherlight)
- [x] [Fallow Wurm](https://scryfall.com/search?q=!"Fallow+Wurm"&nbsp;e:Weatherlight)
- [x] [Familiar Ground](https://scryfall.com/search?q=!"Familiar+Ground"&nbsp;e:Weatherlight)
- [x] [Fatal Blow](https://scryfall.com/search?q=!"Fatal+Blow"&nbsp;e:Weatherlight)
- [x] [Fervor](https://scryfall.com/search?q=!"Fervor"&nbsp;e:Weatherlight)
- [x] [Festering Evil](https://scryfall.com/search?q=!"Festering+Evil"&nbsp;e:Weatherlight)
- [x] [Fire Whip](https://scryfall.com/search?q=!"Fire+Whip"&nbsp;e:Weatherlight)
- [x] [Firestorm](https://scryfall.com/search?q=!"Firestorm"&nbsp;e:Weatherlight)
- [x] [Fit of Rage](https://scryfall.com/search?q=!"Fit+of+Rage"&nbsp;e:Weatherlight)
- [x] [Fledgling Djinn](https://scryfall.com/search?q=!"Fledgling+Djinn"&nbsp;e:Weatherlight)
- [x] [Flux](https://scryfall.com/search?q=!"Flux"&nbsp;e:Weatherlight)
- [x] [Fog Elemental](https://scryfall.com/search?q=!"Fog+Elemental"&nbsp;e:Weatherlight)
- [x] [Foriysian Brigade](https://scryfall.com/search?q=!"Foriysian+Brigade"&nbsp;e:Weatherlight)
- [x] [Fungus Elemental](https://scryfall.com/search?q=!"Fungus+Elemental"&nbsp;e:Weatherlight)
- [x] [Gaea's Blessing](https://scryfall.com/search?q=!"Gaea's+Blessing"&nbsp;e:Weatherlight)
- [x] [Gallowbraid](https://scryfall.com/search?q=!"Gallowbraid"&nbsp;e:Weatherlight)
- [x] [Gemstone Mine](https://scryfall.com/search?q=!"Gemstone+Mine"&nbsp;e:Weatherlight)
- [x] [Gerrard's Wisdom](https://scryfall.com/search?q=!"Gerrard's+Wisdom"&nbsp;e:Weatherlight)
- [x] [Goblin Bomb](https://scryfall.com/search?q=!"Goblin+Bomb"&nbsp;e:Weatherlight)
- [x] [Goblin Grenadiers](https://scryfall.com/search?q=!"Goblin+Grenadiers"&nbsp;e:Weatherlight)
- [x] [Goblin Vandal](https://scryfall.com/search?q=!"Goblin+Vandal"&nbsp;e:Weatherlight)
- [x] [Guided Strike](https://scryfall.com/search?q=!"Guided+Strike"&nbsp;e:Weatherlight)
- [x] [Harvest Wurm](https://scryfall.com/search?q=!"Harvest+Wurm"&nbsp;e:Weatherlight)
- [x] [Haunting Misery](https://scryfall.com/search?q=!"Haunting+Misery"&nbsp;e:Weatherlight)
- [x] [Heart of Bogardan](https://scryfall.com/search?q=!"Heart+of+Bogardan"&nbsp;e:Weatherlight)
- [x] [Heat Stroke](https://scryfall.com/search?q=!"Heat+Stroke"&nbsp;e:Weatherlight)
- [x] [Heavy Ballista](https://scryfall.com/search?q=!"Heavy+Ballista"&nbsp;e:Weatherlight)
- [x] [Hidden Horror](https://scryfall.com/search?q=!"Hidden+Horror"&nbsp;e:Weatherlight)
- [x] [Hurloon Shaman](https://scryfall.com/search?q=!"Hurloon+Shaman"&nbsp;e:Weatherlight)
- [x] [Infernal Tribute](https://scryfall.com/search?q=!"Infernal+Tribute"&nbsp;e:Weatherlight)
- [x] [Inner Sanctum](https://scryfall.com/search?q=!"Inner+Sanctum"&nbsp;e:Weatherlight)
- [x] [Jabari's Banner](https://scryfall.com/search?q=!"Jabari's+Banner"&nbsp;e:Weatherlight)
- [x] [Jangling Automaton](https://scryfall.com/search?q=!"Jangling+Automaton"&nbsp;e:Weatherlight)
- [x] [Kithkin Armor](https://scryfall.com/search?q=!"Kithkin+Armor"&nbsp;e:Weatherlight)
- [x] [Lava Hounds](https://scryfall.com/search?q=!"Lava+Hounds"&nbsp;e:Weatherlight)
- [x] [Lava Storm](https://scryfall.com/search?q=!"Lava+Storm"&nbsp;e:Weatherlight)
- [x] [Liege of the Hollows](https://scryfall.com/search?q=!"Liege+of+the+Hollows"&nbsp;e:Weatherlight)
- [x] [Llanowar Behemoth](https://scryfall.com/search?q=!"Llanowar+Behemoth"&nbsp;e:Weatherlight)
- [x] [Llanowar Druid](https://scryfall.com/search?q=!"Llanowar+Druid"&nbsp;e:Weatherlight)
- [x] [Llanowar Sentinel](https://scryfall.com/search?q=!"Llanowar+Sentinel"&nbsp;e:Weatherlight)
- [x] [Lotus Vale](https://scryfall.com/search?q=!"Lotus+Vale"&nbsp;e:Weatherlight)
- [x] [Mana Chains](https://scryfall.com/search?q=!"Mana+Chains"&nbsp;e:Weatherlight)
- [x] [Mana Web](https://scryfall.com/search?q=!"Mana+Web"&nbsp;e:Weatherlight)
- [x] [Manta Ray](https://scryfall.com/search?q=!"Manta+Ray"&nbsp;e:Weatherlight)
- [x] [Maraxus of Keld](https://scryfall.com/search?q=!"Maraxus+of+Keld"&nbsp;e:Weatherlight)
- [x] [Master of Arms](https://scryfall.com/search?q=!"Master+of+Arms"&nbsp;e:Weatherlight)
- [x] [Merfolk Traders](https://scryfall.com/search?q=!"Merfolk+Traders"&nbsp;e:Weatherlight)
- [x] [Mind Stone](https://scryfall.com/search?q=!"Mind+Stone"&nbsp;e:Weatherlight)
- [x] [Mischievous Poltergeist](https://scryfall.com/search?q=!"Mischievous+Poltergeist"&nbsp;e:Weatherlight)
- [x] [Mistmoon Griffin](https://scryfall.com/search?q=!"Mistmoon+Griffin"&nbsp;e:Weatherlight)
- [x] [Morinfen](https://scryfall.com/search?q=!"Morinfen"&nbsp;e:Weatherlight)
- [x] [Mwonvuli Ooze](https://scryfall.com/search?q=!"Mwonvuli+Ooze"&nbsp;e:Weatherlight)
- [x] [Nature's Kiss](https://scryfall.com/search?q=!"Nature's+Kiss"&nbsp;e:Weatherlight)
- [x] [Nature's Resurgence](https://scryfall.com/search?q=!"Nature's+Resurgence"&nbsp;e:Weatherlight)
- [x] [Necratog](https://scryfall.com/search?q=!"Necratog"&nbsp;e:Weatherlight)
- [x] [Noble Benefactor](https://scryfall.com/search?q=!"Noble+Benefactor"&nbsp;e:Weatherlight)
- [x] [Null Rod](https://scryfall.com/search?q=!"Null+Rod"&nbsp;e:Weatherlight)
- [x] [Odylic Wraith](https://scryfall.com/search?q=!"Odylic+Wraith"&nbsp;e:Weatherlight)
- [x] [Ophidian](https://scryfall.com/search?q=!"Ophidian"&nbsp;e:Weatherlight)
- [x] [Orcish Settlers](https://scryfall.com/search?q=!"Orcish+Settlers"&nbsp;e:Weatherlight)
- [x] [Paradigm Shift](https://scryfall.com/search?q=!"Paradigm+Shift"&nbsp;e:Weatherlight)
- [x] [Peacekeeper](https://scryfall.com/search?q=!"Peacekeeper"&nbsp;e:Weatherlight)
- [x] [Pendrell Mists](https://scryfall.com/search?q=!"Pendrell+Mists"&nbsp;e:Weatherlight)
- [x] [Phantom Warrior](https://scryfall.com/search?q=!"Phantom+Warrior"&nbsp;e:Weatherlight)
- [x] [Phantom Wings](https://scryfall.com/search?q=!"Phantom+Wings"&nbsp;e:Weatherlight)
- [x] [Phyrexian Furnace](https://scryfall.com/search?q=!"Phyrexian+Furnace"&nbsp;e:Weatherlight)
- [x] [Psychic Vortex](https://scryfall.com/search?q=!"Psychic+Vortex"&nbsp;e:Weatherlight)
- [x] [Razortooth Rats](https://scryfall.com/search?q=!"Razortooth+Rats"&nbsp;e:Weatherlight)
- [x] [Redwood Treefolk](https://scryfall.com/search?q=!"Redwood+Treefolk"&nbsp;e:Weatherlight)
- [x] [Relearn](https://scryfall.com/search?q=!"Relearn"&nbsp;e:Weatherlight)
- [x] [Revered Unicorn](https://scryfall.com/search?q=!"Revered+Unicorn"&nbsp;e:Weatherlight)
- [x] [Roc Hatchling](https://scryfall.com/search?q=!"Roc+Hatchling"&nbsp;e:Weatherlight)
- [x] [Rogue Elephant](https://scryfall.com/search?q=!"Rogue+Elephant"&nbsp;e:Weatherlight)
- [x] [Sage Owl](https://scryfall.com/search?q=!"Sage+Owl"&nbsp;e:Weatherlight)
- [x] [Sawtooth Ogre](https://scryfall.com/search?q=!"Sawtooth+Ogre"&nbsp;e:Weatherlight)
- [x] [Scorched Ruins](https://scryfall.com/search?q=!"Scorched+Ruins"&nbsp;e:Weatherlight)
- [x] [Serenity](https://scryfall.com/search?q=!"Serenity"&nbsp;e:Weatherlight)
- [x] [Serra's Blessing](https://scryfall.com/search?q=!"Serra's+Blessing"&nbsp;e:Weatherlight)
- [x] [Serrated Biskelion](https://scryfall.com/search?q=!"Serrated+Biskelion"&nbsp;e:Weatherlight)
- [x] [Shadow Rider](https://scryfall.com/search?q=!"Shadow+Rider"&nbsp;e:Weatherlight)
- [x] [Shattered Crypt](https://scryfall.com/search?q=!"Shattered+Crypt"&nbsp;e:Weatherlight)
- [x] [Soul Shepherd](https://scryfall.com/search?q=!"Soul+Shepherd"&nbsp;e:Weatherlight)
- [x] [Southern Paladin](https://scryfall.com/search?q=!"Southern+Paladin"&nbsp;e:Weatherlight)
- [x] [Spinning Darkness](https://scryfall.com/search?q=!"Spinning+Darkness"&nbsp;e:Weatherlight)
- [x] [Steel Golem](https://scryfall.com/search?q=!"Steel+Golem"&nbsp;e:Weatherlight)
- [x] [Strands of Night](https://scryfall.com/search?q=!"Strands+of+Night"&nbsp;e:Weatherlight)
- [x] [Straw Golem](https://scryfall.com/search?q=!"Straw+Golem"&nbsp;e:Weatherlight)
- [x] [Striped Bears](https://scryfall.com/search?q=!"Striped+Bears"&nbsp;e:Weatherlight)
- [x] [Sylvan Hierophant](https://scryfall.com/search?q=!"Sylvan+Hierophant"&nbsp;e:Weatherlight)
- [x] [Tariff](https://scryfall.com/search?q=!"Tariff"&nbsp;e:Weatherlight)
- [x] [Teferi's Veil](https://scryfall.com/search?q=!"Teferi's+Veil"&nbsp;e:Weatherlight)
- [x] [Tendrils of Despair](https://scryfall.com/search?q=!"Tendrils+of+Despair"&nbsp;e:Weatherlight)
- [x] [Thran Forge](https://scryfall.com/search?q=!"Thran+Forge"&nbsp;e:Weatherlight)
- [x] [Thran Tome](https://scryfall.com/search?q=!"Thran+Tome"&nbsp;e:Weatherlight)
- [x] [Thunderbolt](https://scryfall.com/search?q=!"Thunderbolt"&nbsp;e:Weatherlight)
- [x] [Thundermare](https://scryfall.com/search?q=!"Thundermare"&nbsp;e:Weatherlight)
- [x] [Timid Drake](https://scryfall.com/search?q=!"Timid+Drake"&nbsp;e:Weatherlight)
- [x] [Tolarian Drake](https://scryfall.com/search?q=!"Tolarian+Drake"&nbsp;e:Weatherlight)
- [x] [Tolarian Entrancer](https://scryfall.com/search?q=!"Tolarian+Entrancer"&nbsp;e:Weatherlight)
- [x] [Tolarian Serpent](https://scryfall.com/search?q=!"Tolarian+Serpent"&nbsp;e:Weatherlight)
- [x] [Touchstone](https://scryfall.com/search?q=!"Touchstone"&nbsp;e:Weatherlight)
- [x] [Tranquil Grove](https://scryfall.com/search?q=!"Tranquil+Grove"&nbsp;e:Weatherlight)
- [x] [Uktabi Efreet](https://scryfall.com/search?q=!"Uktabi+Efreet"&nbsp;e:Weatherlight)
- [x] [Urborg Justice](https://scryfall.com/search?q=!"Urborg+Justice"&nbsp;e:Weatherlight)
- [x] [Urborg Stalker](https://scryfall.com/search?q=!"Urborg+Stalker"&nbsp;e:Weatherlight)
- [x] [Veteran Explorer](https://scryfall.com/search?q=!"Veteran+Explorer"&nbsp;e:Weatherlight)
- [x] [Vitalize](https://scryfall.com/search?q=!"Vitalize"&nbsp;e:Weatherlight)
- [x] [Vodalian Illusionist](https://scryfall.com/search?q=!"Vodalian+Illusionist"&nbsp;e:Weatherlight)
- [x] [Volunteer Reserves](https://scryfall.com/search?q=!"Volunteer+Reserves"&nbsp;e:Weatherlight)
- [x] [Wave of Terror](https://scryfall.com/search?q=!"Wave+of+Terror"&nbsp;e:Weatherlight)
- [x] [Well of Knowledge](https://scryfall.com/search?q=!"Well+of+Knowledge"&nbsp;e:Weatherlight)
- [x] [Winding Canyons](https://scryfall.com/search?q=!"Winding+Canyons"&nbsp;e:Weatherlight)
- [x] [Xanthic Statue](https://scryfall.com/search?q=!"Xanthic+Statue"&nbsp;e:Weatherlight)
- [x] [Zombie Scavengers](https://scryfall.com/search?q=!"Zombie+Scavengers"&nbsp;e:Weatherlight)

**Comment by Susucre** [comment]
with Ertai's Familiar implementation, WTH is done!
