### ISSUE TITLE
VIS - Visions set card implementation tracker

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5490]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Cards unimplemented in set

10|[Forbidden Ritual](https://scryfall.com/search?q=!"Forbidden+Ritual"&nbsp;e:Visions)
12|[Infernal Harvest](https://scryfall.com/search?q=!"Infernal+Harvest"&nbsp;e:Visions)
46|[Time and Tide](https://scryfall.com/search?q=!"Time+and+Tide"&nbsp;e:Visions)
61|[Kyscu Drake](https://scryfall.com/search?q=!"Kyscu+Drake"&nbsp;e:Visions)
66|[Quirion Druid](https://scryfall.com/search?q=!"Quirion+Druid"&nbsp;e:Visions)
83|[Heat Wave](https://scryfall.com/search?q=!"Heat+Wave"&nbsp;e:Visions)
89|[Ogre Enforcer](https://scryfall.com/search?q=!"Ogre+Enforcer"&nbsp;e:Visions)
115|[Peace Talks](https://scryfall.com/search?q=!"Peace+Talks"&nbsp;e:Visions)
131|[Guiding Spirit](https://scryfall.com/search?q=!"Guiding+Spirit"&nbsp;e:Visions)
133|[Pygmy Hippo](https://scryfall.com/search?q=!"Pygmy+Hippo"&nbsp;e:Visions)
150|[Matopi Golem](https://scryfall.com/search?q=!"Matopi+Golem"&nbsp;e:Visions)

# Cards in set:

- [x] [Aku Djinn](https://scryfall.com/search?q=!"Aku+Djinn"&nbsp;e:Visions)
- [x] [Anvil of Bogardan](https://scryfall.com/search?q=!"Anvil+of+Bogardan"&nbsp;e:Visions)
- [x] [Archangel](https://scryfall.com/search?q=!"Archangel"&nbsp;e:Visions)
- [x] [Army Ants](https://scryfall.com/search?q=!"Army+Ants"&nbsp;e:Visions)
- [x] [Betrayal](https://scryfall.com/search?q=!"Betrayal"&nbsp;e:Visions)
- [x] [Blanket of Night](https://scryfall.com/search?q=!"Blanket+of+Night"&nbsp;e:Visions)
- [x] [Bogardan Phoenix](https://scryfall.com/search?q=!"Bogardan+Phoenix"&nbsp;e:Visions)
- [x] [Brass-Talon Chimera](https://scryfall.com/search?q=!"Brass-Talon+Chimera"&nbsp;e:Visions)
- [x] [Breathstealer's Crypt](https://scryfall.com/search?q=!"Breathstealer's+Crypt"&nbsp;e:Visions)
- [x] [Breezekeeper](https://scryfall.com/search?q=!"Breezekeeper"&nbsp;e:Visions)
- [x] [Brood of Cockroaches](https://scryfall.com/search?q=!"Brood+of+Cockroaches"&nbsp;e:Visions)
- [x] [Bull Elephant](https://scryfall.com/search?q=!"Bull+Elephant"&nbsp;e:Visions)
- [x] [Chronatog](https://scryfall.com/search?q=!"Chronatog"&nbsp;e:Visions)
- [x] [City of Solitude](https://scryfall.com/search?q=!"City+of+Solitude"&nbsp;e:Visions)
- [x] [Cloud Elemental](https://scryfall.com/search?q=!"Cloud+Elemental"&nbsp;e:Visions)
- [x] [Coercion](https://scryfall.com/search?q=!"Coercion"&nbsp;e:Visions)
- [x] [Coral Atoll](https://scryfall.com/search?q=!"Coral+Atoll"&nbsp;e:Visions)
- [x] [Corrosion](https://scryfall.com/search?q=!"Corrosion"&nbsp;e:Visions)
- [x] [Creeping Mold](https://scryfall.com/search?q=!"Creeping+Mold"&nbsp;e:Visions)
- [x] [Crypt Rats](https://scryfall.com/search?q=!"Crypt+Rats"&nbsp;e:Visions)
- [x] [Daraja Griffin](https://scryfall.com/search?q=!"Daraja+Griffin"&nbsp;e:Visions)
- [x] [Dark Privilege](https://scryfall.com/search?q=!"Dark+Privilege"&nbsp;e:Visions)
- [x] [Death Watch](https://scryfall.com/search?q=!"Death+Watch"&nbsp;e:Visions)
- [x] [Desertion](https://scryfall.com/search?q=!"Desertion"&nbsp;e:Visions)
- [x] [Desolation](https://scryfall.com/search?q=!"Desolation"&nbsp;e:Visions)
- [x] [Diamond Kaleidoscope](https://scryfall.com/search?q=!"Diamond+Kaleidoscope"&nbsp;e:Visions)
- [x] [Dormant Volcano](https://scryfall.com/search?q=!"Dormant+Volcano"&nbsp;e:Visions)
- [x] [Dragon Mask](https://scryfall.com/search?q=!"Dragon+Mask"&nbsp;e:Visions)
- [x] [Dream Tides](https://scryfall.com/search?q=!"Dream+Tides"&nbsp;e:Visions)
- [x] [Dwarven Vigilantes](https://scryfall.com/search?q=!"Dwarven+Vigilantes"&nbsp;e:Visions)
- [x] [Elephant Grass](https://scryfall.com/search?q=!"Elephant+Grass"&nbsp;e:Visions)
- [x] [Elkin Lair](https://scryfall.com/search?q=!"Elkin+Lair"&nbsp;e:Visions)
- [x] [Elven Cache](https://scryfall.com/search?q=!"Elven+Cache"&nbsp;e:Visions)
- [x] [Emerald Charm](https://scryfall.com/search?q=!"Emerald+Charm"&nbsp;e:Visions)
- [x] [Equipoise](https://scryfall.com/search?q=!"Equipoise"&nbsp;e:Visions)
- [x] [Everglades](https://scryfall.com/search?q=!"Everglades"&nbsp;e:Visions)
- [x] [Eye of Singularity](https://scryfall.com/search?q=!"Eye+of+Singularity"&nbsp;e:Visions)
- [x] [Fallen Askari](https://scryfall.com/search?q=!"Fallen+Askari"&nbsp;e:Visions)
- [x] [Femeref Enchantress](https://scryfall.com/search?q=!"Femeref+Enchantress"&nbsp;e:Visions)
- [x] [Feral Instinct](https://scryfall.com/search?q=!"Feral+Instinct"&nbsp;e:Visions)
- [x] [Fireblast](https://scryfall.com/search?q=!"Fireblast"&nbsp;e:Visions)
- [x] [Firestorm Hellkite](https://scryfall.com/search?q=!"Firestorm+Hellkite"&nbsp;e:Visions)
- [x] [Flooded Shoreline](https://scryfall.com/search?q=!"Flooded+Shoreline"&nbsp;e:Visions)
- [ ] [Forbidden Ritual](https://scryfall.com/search?q=!"Forbidden+Ritual"&nbsp;e:Visions)
- [x] [Foreshadow](https://scryfall.com/search?q=!"Foreshadow"&nbsp;e:Visions)
- [x] [Freewind Falcon](https://scryfall.com/search?q=!"Freewind+Falcon"&nbsp;e:Visions)
- [x] [Funeral Charm](https://scryfall.com/search?q=!"Funeral+Charm"&nbsp;e:Visions)
- [x] [Giant Caterpillar](https://scryfall.com/search?q=!"Giant+Caterpillar"&nbsp;e:Visions)
- [x] [Goblin Recruiter](https://scryfall.com/search?q=!"Goblin+Recruiter"&nbsp;e:Visions)
- [x] [Goblin Swine-Rider](https://scryfall.com/search?q=!"Goblin+Swine-Rider"&nbsp;e:Visions)
- [x] [Gossamer Chains](https://scryfall.com/search?q=!"Gossamer+Chains"&nbsp;e:Visions)
- [x] [Griffin Canyon](https://scryfall.com/search?q=!"Griffin+Canyon"&nbsp;e:Visions)
- [ ] [Guiding Spirit](https://scryfall.com/search?q=!"Guiding+Spirit"&nbsp;e:Visions)
- [x] [Hearth Charm](https://scryfall.com/search?q=!"Hearth+Charm"&nbsp;e:Visions)
- [ ] [Heat Wave](https://scryfall.com/search?q=!"Heat+Wave"&nbsp;e:Visions)
- [x] [Helm of Awakening](https://scryfall.com/search?q=!"Helm+of+Awakening"&nbsp;e:Visions)
- [x] [Honorable Passage](https://scryfall.com/search?q=!"Honorable+Passage"&nbsp;e:Visions)
- [x] [Hope Charm](https://scryfall.com/search?q=!"Hope+Charm"&nbsp;e:Visions)
- [x] [Hulking Cyclops](https://scryfall.com/search?q=!"Hulking+Cyclops"&nbsp;e:Visions)
- [x] [Impulse](https://scryfall.com/search?q=!"Impulse"&nbsp;e:Visions)
- [x] [Infantry Veteran](https://scryfall.com/search?q=!"Infantry+Veteran"&nbsp;e:Visions)
- [ ] [Infernal Harvest](https://scryfall.com/search?q=!"Infernal+Harvest"&nbsp;e:Visions)
- [x] [Inspiration](https://scryfall.com/search?q=!"Inspiration"&nbsp;e:Visions)
- [x] [Iron-Heart Chimera](https://scryfall.com/search?q=!"Iron-Heart+Chimera"&nbsp;e:Visions)
- [x] [Jamuraan Lion](https://scryfall.com/search?q=!"Jamuraan+Lion"&nbsp;e:Visions)
- [x] [Juju Bubble](https://scryfall.com/search?q=!"Juju+Bubble"&nbsp;e:Visions)
- [x] [Jungle Basin](https://scryfall.com/search?q=!"Jungle+Basin"&nbsp;e:Visions)
- [x] [Kaervek's Spite](https://scryfall.com/search?q=!"Kaervek's+Spite"&nbsp;e:Visions)
- [x] [Karoo](https://scryfall.com/search?q=!"Karoo"&nbsp;e:Visions)
- [x] [Katabatic Winds](https://scryfall.com/search?q=!"Katabatic+Winds"&nbsp;e:Visions)
- [x] [Keeper of Kookus](https://scryfall.com/search?q=!"Keeper+of+Kookus"&nbsp;e:Visions)
- [x] [King Cheetah](https://scryfall.com/search?q=!"King+Cheetah"&nbsp;e:Visions)
- [x] [Knight of Valor](https://scryfall.com/search?q=!"Knight+of+Valor"&nbsp;e:Visions)
- [x] [Knight of the Mists](https://scryfall.com/search?q=!"Knight+of+the+Mists"&nbsp;e:Visions)
- [x] [Kookus](https://scryfall.com/search?q=!"Kookus"&nbsp;e:Visions)
- [ ] [Kyscu Drake](https://scryfall.com/search?q=!"Kyscu+Drake"&nbsp;e:Visions)
- [x] [Lead-Belly Chimera](https://scryfall.com/search?q=!"Lead-Belly+Chimera"&nbsp;e:Visions)
- [x] [Lichenthrope](https://scryfall.com/search?q=!"Lichenthrope"&nbsp;e:Visions)
- [x] [Lightning Cloud](https://scryfall.com/search?q=!"Lightning+Cloud"&nbsp;e:Visions)
- [x] [Longbow Archer](https://scryfall.com/search?q=!"Longbow+Archer"&nbsp;e:Visions)
- [x] [Magma Mine](https://scryfall.com/search?q=!"Magma+Mine"&nbsp;e:Visions)
- [x] [Man-o'-War](https://scryfall.com/search?q=!"Man-o'-War"&nbsp;e:Visions)
- [ ] [Matopi Golem](https://scryfall.com/search?q=!"Matopi+Golem"&nbsp;e:Visions)
- [x] [Miraculous Recovery](https://scryfall.com/search?q=!"Miraculous+Recovery"&nbsp;e:Visions)
- [x] [Mob Mentality](https://scryfall.com/search?q=!"Mob+Mentality"&nbsp;e:Visions)
- [x] [Mortal Wound](https://scryfall.com/search?q=!"Mortal+Wound"&nbsp;e:Visions)
- [x] [Mundungu](https://scryfall.com/search?q=!"Mundungu"&nbsp;e:Visions)
- [x] [Mystic Veil](https://scryfall.com/search?q=!"Mystic+Veil"&nbsp;e:Visions)
- [x] [Natural Order](https://scryfall.com/search?q=!"Natural+Order"&nbsp;e:Visions)
- [x] [Necromancy](https://scryfall.com/search?q=!"Necromancy"&nbsp;e:Visions)
- [x] [Necrosavant](https://scryfall.com/search?q=!"Necrosavant"&nbsp;e:Visions)
- [x] [Nekrataal](https://scryfall.com/search?q=!"Nekrataal"&nbsp;e:Visions)
- [ ] [Ogre Enforcer](https://scryfall.com/search?q=!"Ogre+Enforcer"&nbsp;e:Visions)
- [x] [Ovinomancer](https://scryfall.com/search?q=!"Ovinomancer"&nbsp;e:Visions)
- [x] [Panther Warriors](https://scryfall.com/search?q=!"Panther+Warriors"&nbsp;e:Visions)
- [x] [Parapet](https://scryfall.com/search?q=!"Parapet"&nbsp;e:Visions)
- [ ] [Peace Talks](https://scryfall.com/search?q=!"Peace+Talks"&nbsp;e:Visions)
- [x] [Phyrexian Marauder](https://scryfall.com/search?q=!"Phyrexian+Marauder"&nbsp;e:Visions)
- [x] [Phyrexian Walker](https://scryfall.com/search?q=!"Phyrexian+Walker"&nbsp;e:Visions)
- [x] [Pillar Tombs of Aku](https://scryfall.com/search?q=!"Pillar+Tombs+of+Aku"&nbsp;e:Visions)
- [x] [Prosperity](https://scryfall.com/search?q=!"Prosperity"&nbsp;e:Visions)
- [ ] [Pygmy Hippo](https://scryfall.com/search?q=!"Pygmy+Hippo"&nbsp;e:Visions)
- [x] [Python](https://scryfall.com/search?q=!"Python"&nbsp;e:Visions)
- [x] [Quicksand](https://scryfall.com/search?q=!"Quicksand"&nbsp;e:Visions)
- [ ] [Quirion Druid](https://scryfall.com/search?q=!"Quirion+Druid"&nbsp;e:Visions)
- [x] [Quirion Ranger](https://scryfall.com/search?q=!"Quirion+Ranger"&nbsp;e:Visions)
- [x] [Raging Gorilla](https://scryfall.com/search?q=!"Raging+Gorilla"&nbsp;e:Visions)
- [x] [Rainbow Efreet](https://scryfall.com/search?q=!"Rainbow+Efreet"&nbsp;e:Visions)
- [x] [Relentless Assault](https://scryfall.com/search?q=!"Relentless+Assault"&nbsp;e:Visions)
- [x] [Relic Ward](https://scryfall.com/search?q=!"Relic+Ward"&nbsp;e:Visions)
- [x] [Remedy](https://scryfall.com/search?q=!"Remedy"&nbsp;e:Visions)
- [x] [Resistance Fighter](https://scryfall.com/search?q=!"Resistance+Fighter"&nbsp;e:Visions)
- [x] [Retribution of the Meek](https://scryfall.com/search?q=!"Retribution+of+the+Meek"&nbsp;e:Visions)
- [x] [Righteous Aura](https://scryfall.com/search?q=!"Righteous+Aura"&nbsp;e:Visions)
- [x] [Righteous War](https://scryfall.com/search?q=!"Righteous+War"&nbsp;e:Visions)
- [x] [River Boa](https://scryfall.com/search?q=!"River+Boa"&nbsp;e:Visions)
- [x] [Rock Slide](https://scryfall.com/search?q=!"Rock+Slide"&nbsp;e:Visions)
- [x] [Rowen](https://scryfall.com/search?q=!"Rowen"&nbsp;e:Visions)
- [x] [Sands of Time](https://scryfall.com/search?q=!"Sands+of+Time"&nbsp;e:Visions)
- [x] [Scalebane's Elite](https://scryfall.com/search?q=!"Scalebane's+Elite"&nbsp;e:Visions)
- [x] [Shimmering Efreet](https://scryfall.com/search?q=!"Shimmering+Efreet"&nbsp;e:Visions)
- [x] [Shrieking Drake](https://scryfall.com/search?q=!"Shrieking+Drake"&nbsp;e:Visions)
- [x] [Simoon](https://scryfall.com/search?q=!"Simoon"&nbsp;e:Visions)
- [x] [Sisay's Ring](https://scryfall.com/search?q=!"Sisay's+Ring"&nbsp;e:Visions)
- [x] [Snake Basket](https://scryfall.com/search?q=!"Snake+Basket"&nbsp;e:Visions)
- [x] [Solfatara](https://scryfall.com/search?q=!"Solfatara"&nbsp;e:Visions)
- [x] [Song of Blood](https://scryfall.com/search?q=!"Song+of+Blood"&nbsp;e:Visions)
- [x] [Spider Climb](https://scryfall.com/search?q=!"Spider+Climb"&nbsp;e:Visions)
- [x] [Spitting Drake](https://scryfall.com/search?q=!"Spitting+Drake"&nbsp;e:Visions)
- [x] [Squandered Resources](https://scryfall.com/search?q=!"Squandered+Resources"&nbsp;e:Visions)
- [x] [Stampeding Wildebeests](https://scryfall.com/search?q=!"Stampeding+Wildebeests"&nbsp;e:Visions)
- [x] [Suleiman's Legacy](https://scryfall.com/search?q=!"Suleiman's+Legacy"&nbsp;e:Visions)
- [x] [Summer Bloom](https://scryfall.com/search?q=!"Summer+Bloom"&nbsp;e:Visions)
- [x] [Sun Clasp](https://scryfall.com/search?q=!"Sun+Clasp"&nbsp;e:Visions)
- [x] [Suq'Ata Assassin](https://scryfall.com/search?q=!"Suq'Ata+Assassin"&nbsp;e:Visions)
- [x] [Suq'Ata Lancer](https://scryfall.com/search?q=!"Suq'Ata+Lancer"&nbsp;e:Visions)
- [x] [Talruum Champion](https://scryfall.com/search?q=!"Talruum+Champion"&nbsp;e:Visions)
- [x] [Talruum Piper](https://scryfall.com/search?q=!"Talruum+Piper"&nbsp;e:Visions)
- [x] [Tar Pit Warrior](https://scryfall.com/search?q=!"Tar+Pit+Warrior"&nbsp;e:Visions)
- [x] [Teferi's Honor Guard](https://scryfall.com/search?q=!"Teferi's+Honor+Guard"&nbsp;e:Visions)
- [x] [Teferi's Puzzle Box](https://scryfall.com/search?q=!"Teferi's+Puzzle+Box"&nbsp;e:Visions)
- [x] [Teferi's Realm](https://scryfall.com/search?q=!"Teferi's+Realm"&nbsp;e:Visions)
- [x] [Tempest Drake](https://scryfall.com/search?q=!"Tempest+Drake"&nbsp;e:Visions)
- [x] [Three Wishes](https://scryfall.com/search?q=!"Three+Wishes"&nbsp;e:Visions)
- [ ] [Time and Tide](https://scryfall.com/search?q=!"Time+and+Tide"&nbsp;e:Visions)
- [x] [Tin-Wing Chimera](https://scryfall.com/search?q=!"Tin-Wing+Chimera"&nbsp;e:Visions)
- [x] [Tithe](https://scryfall.com/search?q=!"Tithe"&nbsp;e:Visions)
- [x] [Tremor](https://scryfall.com/search?q=!"Tremor"&nbsp;e:Visions)
- [x] [Triangle of War](https://scryfall.com/search?q=!"Triangle+of+War"&nbsp;e:Visions)
- [x] [Uktabi Orangutan](https://scryfall.com/search?q=!"Uktabi+Orangutan"&nbsp;e:Visions)
- [x] [Undiscovered Paradise](https://scryfall.com/search?q=!"Undiscovered+Paradise"&nbsp;e:Visions)
- [x] [Undo](https://scryfall.com/search?q=!"Undo"&nbsp;e:Visions)
- [x] [Urborg Mindsucker](https://scryfall.com/search?q=!"Urborg+Mindsucker"&nbsp;e:Visions)
- [x] [Vampiric Tutor](https://scryfall.com/search?q=!"Vampiric+Tutor"&nbsp;e:Visions)
- [x] [Vampirism](https://scryfall.com/search?q=!"Vampirism"&nbsp;e:Visions)
- [x] [Vanishing](https://scryfall.com/search?q=!"Vanishing"&nbsp;e:Visions)
- [x] [Viashino Sandstalker](https://scryfall.com/search?q=!"Viashino+Sandstalker"&nbsp;e:Visions)
- [x] [Viashivan Dragon](https://scryfall.com/search?q=!"Viashivan+Dragon"&nbsp;e:Visions)
- [x] [Vision Charm](https://scryfall.com/search?q=!"Vision+Charm"&nbsp;e:Visions)
- [x] [Wake of Vultures](https://scryfall.com/search?q=!"Wake+of+Vultures"&nbsp;e:Visions)
- [x] [Wand of Denial](https://scryfall.com/search?q=!"Wand+of+Denial"&nbsp;e:Visions)
- [x] [Warrior's Honor](https://scryfall.com/search?q=!"Warrior's+Honor"&nbsp;e:Visions)
- [x] [Warthog](https://scryfall.com/search?q=!"Warthog"&nbsp;e:Visions)
- [x] [Waterspout Djinn](https://scryfall.com/search?q=!"Waterspout+Djinn"&nbsp;e:Visions)
- [x] [Wicked Reward](https://scryfall.com/search?q=!"Wicked+Reward"&nbsp;e:Visions)
- [x] [Wind Shear](https://scryfall.com/search?q=!"Wind+Shear"&nbsp;e:Visions)
- [x] [Zhalfirin Crusader](https://scryfall.com/search?q=!"Zhalfirin+Crusader"&nbsp;e:Visions)

**Comment by Cguy7777** [comment]
Working on Heat Wave
