### ISSUE TITLE
ALL - Alliances set card implementation tracker

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#5492]
[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Cards unimplemented in set

5|[Diseased Vermin](https://scryfall.com/search?q=!"Diseased+Vermin"&nbsp;e:ALL)
7|[Fatal Lore](https://scryfall.com/search?q=!"Fatal+Lore"&nbsp;e:ALL)
34|[Awesome Presence](https://scryfall.com/search?q=!"Awesome+Presence"&nbsp;e:ALL)
36|[Benthic Explorers](https://scryfall.com/search?q=!"Benthic+Explorers"&nbsp;e:ALL)
48|[Phantasmal Sphere](https://scryfall.com/search?q=!"Phantasmal+Sphere"&nbsp;e:ALL)
56|[Misfortune](https://scryfall.com/search?q=!"Misfortune"&nbsp;e:ALL)
57|[Suffocation](https://scryfall.com/search?q=!"Suffocation"&nbsp;e:ALL)
73|[Gift of the Woods](https://scryfall.com/search?q=!"Gift+of+the+Woods"&nbsp;e:ALL)
84|[Taste of Paradise](https://scryfall.com/search?q=!"Taste+of+Paradise"&nbsp;e:ALL)
87|[Undergrowth](https://scryfall.com/search?q=!"Undergrowth"&nbsp;e:ALL)
114|[Primitive Justice](https://scryfall.com/search?q=!"Primitive+Justice"&nbsp;e:ALL)
116|[Rogue Skycaptain](https://scryfall.com/search?q=!"Rogue+Skycaptain"&nbsp;e:ALL)
136|[Kjeldoran Pride](https://scryfall.com/search?q=!"Kjeldoran+Pride"&nbsp;e:ALL)
149|[Scars of the Veteran](https://scryfall.com/search?q=!"Scars+of+the+Veteran"&nbsp;e:ALL)
175|[Soldevi Sentry](https://scryfall.com/search?q=!"Soldevi+Sentry"&nbsp;e:ALL)

# Cards in set:

- [x] [Aesthir Glider](https://scryfall.com/search?q=!"Aesthir+Glider"&nbsp;e:ALL)
- [x] [Agent of Stromgald](https://scryfall.com/search?q=!"Agent+of+Stromgald"&nbsp;e:ALL)
- [x] [Arcane Denial](https://scryfall.com/search?q=!"Arcane+Denial"&nbsp;e:ALL)
- [x] [Ashnod's Cylix](https://scryfall.com/search?q=!"Ashnod's+Cylix"&nbsp;e:ALL)
- [x] [Astrolabe](https://scryfall.com/search?q=!"Astrolabe"&nbsp;e:ALL)
- [ ] [Awesome Presence](https://scryfall.com/search?q=!"Awesome+Presence"&nbsp;e:ALL)
- [x] [Balduvian Dead](https://scryfall.com/search?q=!"Balduvian+Dead"&nbsp;e:ALL)
- [x] [Balduvian Horde](https://scryfall.com/search?q=!"Balduvian+Horde"&nbsp;e:ALL)
- [x] [Balduvian Trading Post](https://scryfall.com/search?q=!"Balduvian+Trading+Post"&nbsp;e:ALL)
- [x] [Balduvian War-Makers](https://scryfall.com/search?q=!"Balduvian+War-Makers"&nbsp;e:ALL)
- [ ] [Benthic Explorers](https://scryfall.com/search?q=!"Benthic+Explorers"&nbsp;e:ALL)
- [x] [Bestial Fury](https://scryfall.com/search?q=!"Bestial+Fury"&nbsp;e:ALL)
- [x] [Bounty of the Hunt](https://scryfall.com/search?q=!"Bounty+of+the+Hunt"&nbsp;e:ALL)
- [x] [Browse](https://scryfall.com/search?q=!"Browse"&nbsp;e:ALL)
- [x] [Burnout](https://scryfall.com/search?q=!"Burnout"&nbsp;e:ALL)
- [x] [Carrier Pigeons](https://scryfall.com/search?q=!"Carrier+Pigeons"&nbsp;e:ALL)
- [x] [Casting of Bones](https://scryfall.com/search?q=!"Casting+of+Bones"&nbsp;e:ALL)
- [x] [Chaos Harlequin](https://scryfall.com/search?q=!"Chaos+Harlequin"&nbsp;e:ALL)
- [x] [Contagion](https://scryfall.com/search?q=!"Contagion"&nbsp;e:ALL)
- [x] [Deadly Insect](https://scryfall.com/search?q=!"Deadly+Insect"&nbsp;e:ALL)
- [x] [Death Spark](https://scryfall.com/search?q=!"Death+Spark"&nbsp;e:ALL)
- [x] [Diminishing Returns](https://scryfall.com/search?q=!"Diminishing+Returns"&nbsp;e:ALL)
- [ ] [Diseased Vermin](https://scryfall.com/search?q=!"Diseased+Vermin"&nbsp;e:ALL)
- [x] [Dystopia](https://scryfall.com/search?q=!"Dystopia"&nbsp;e:ALL)
- [x] [Elvish Bard](https://scryfall.com/search?q=!"Elvish+Bard"&nbsp;e:ALL)
- [x] [Elvish Ranger](https://scryfall.com/search?q=!"Elvish+Ranger"&nbsp;e:ALL)
- [x] [Elvish Spirit Guide](https://scryfall.com/search?q=!"Elvish+Spirit+Guide"&nbsp;e:ALL)
- [x] [Energy Arc](https://scryfall.com/search?q=!"Energy+Arc"&nbsp;e:ALL)
- [x] [Enslaved Scout](https://scryfall.com/search?q=!"Enslaved+Scout"&nbsp;e:ALL)
- [x] [Errand of Duty](https://scryfall.com/search?q=!"Errand+of+Duty"&nbsp;e:ALL)
- [x] [Exile](https://scryfall.com/search?q=!"Exile"&nbsp;e:ALL)
- [x] [False Demise](https://scryfall.com/search?q=!"False+Demise"&nbsp;e:ALL)
- [ ] [Fatal Lore](https://scryfall.com/search?q=!"Fatal+Lore"&nbsp;e:ALL)
- [x] [Feast or Famine](https://scryfall.com/search?q=!"Feast+or+Famine"&nbsp;e:ALL)
- [x] [Fevered Strength](https://scryfall.com/search?q=!"Fevered+Strength"&nbsp;e:ALL)
- [x] [Floodwater Dam](https://scryfall.com/search?q=!"Floodwater+Dam"&nbsp;e:ALL)
- [x] [Force of Will](https://scryfall.com/search?q=!"Force+of+Will"&nbsp;e:ALL)
- [x] [Foresight](https://scryfall.com/search?q=!"Foresight"&nbsp;e:ALL)
- [x] [Fyndhorn Druid](https://scryfall.com/search?q=!"Fyndhorn+Druid"&nbsp;e:ALL)
- [x] [Gargantuan Gorilla](https://scryfall.com/search?q=!"Gargantuan+Gorilla"&nbsp;e:ALL)
- [ ] [Gift of the Woods](https://scryfall.com/search?q=!"Gift+of+the+Woods"&nbsp;e:ALL)
- [x] [Gorilla Berserkers](https://scryfall.com/search?q=!"Gorilla+Berserkers"&nbsp;e:ALL)
- [x] [Gorilla Chieftain](https://scryfall.com/search?q=!"Gorilla+Chieftain"&nbsp;e:ALL)
- [x] [Gorilla Shaman](https://scryfall.com/search?q=!"Gorilla+Shaman"&nbsp;e:ALL)
- [x] [Gorilla War Cry](https://scryfall.com/search?q=!"Gorilla+War+Cry"&nbsp;e:ALL)
- [x] [Guerrilla Tactics](https://scryfall.com/search?q=!"Guerrilla+Tactics"&nbsp;e:ALL)
- [x] [Gustha's Scepter](https://scryfall.com/search?q=!"Gustha's+Scepter"&nbsp;e:ALL)
- [x] [Hail Storm](https://scryfall.com/search?q=!"Hail+Storm"&nbsp;e:ALL)
- [x] [Heart of Yavimaya](https://scryfall.com/search?q=!"Heart+of+Yavimaya"&nbsp;e:ALL)
- [x] [Helm of Obedience](https://scryfall.com/search?q=!"Helm+of+Obedience"&nbsp;e:ALL)
- [x] [Inheritance](https://scryfall.com/search?q=!"Inheritance"&nbsp;e:ALL)
- [x] [Insidious Bookworms](https://scryfall.com/search?q=!"Insidious+Bookworms"&nbsp;e:ALL)
- [x] [Ivory Gargoyle](https://scryfall.com/search?q=!"Ivory+Gargoyle"&nbsp;e:ALL)
- [x] [Juniper Order Advocate](https://scryfall.com/search?q=!"Juniper+Order+Advocate"&nbsp;e:ALL)
- [x] [Kaysa](https://scryfall.com/search?q=!"Kaysa"&nbsp;e:ALL)
- [x] [Keeper of Tresserhorn](https://scryfall.com/search?q=!"Keeper+of+Tresserhorn"&nbsp;e:ALL)
- [x] [Kjeldoran Escort](https://scryfall.com/search?q=!"Kjeldoran+Escort"&nbsp;e:ALL)
- [x] [Kjeldoran Home Guard](https://scryfall.com/search?q=!"Kjeldoran+Home+Guard"&nbsp;e:ALL)
- [x] [Kjeldoran Outpost](https://scryfall.com/search?q=!"Kjeldoran+Outpost"&nbsp;e:ALL)
- [ ] [Kjeldoran Pride](https://scryfall.com/search?q=!"Kjeldoran+Pride"&nbsp;e:ALL)
- [x] [Krovikan Horror](https://scryfall.com/search?q=!"Krovikan+Horror"&nbsp;e:ALL)
- [x] [Krovikan Plague](https://scryfall.com/search?q=!"Krovikan+Plague"&nbsp;e:ALL)
- [x] [Lake of the Dead](https://scryfall.com/search?q=!"Lake+of+the+Dead"&nbsp;e:ALL)
- [x] [Lat-Nam's Legacy](https://scryfall.com/search?q=!"Lat-Nam's+Legacy"&nbsp;e:ALL)
- [x] [Library of Lat-Nam](https://scryfall.com/search?q=!"Library+of+Lat-Nam"&nbsp;e:ALL)
- [x] [Lim-Dul's High Guard](https://scryfall.com/search?q=!"Lim-Dul's+High+Guard"&nbsp;e:ALL)
- [x] [Lim-Dul's Paladin](https://scryfall.com/search?q=!"Lim-Dul's+Paladin"&nbsp;e:ALL)
- [x] [Lim-Dul's Vault](https://scryfall.com/search?q=!"Lim-Dul's+Vault"&nbsp;e:ALL)
- [x] [Lodestone Bauble](https://scryfall.com/search?q=!"Lodestone+Bauble"&nbsp;e:ALL)
- [x] [Lord of Tresserhorn](https://scryfall.com/search?q=!"Lord+of+Tresserhorn"&nbsp;e:ALL)
- [x] [Martyrdom](https://scryfall.com/search?q=!"Martyrdom"&nbsp;e:ALL)
- [ ] [Misfortune](https://scryfall.com/search?q=!"Misfortune"&nbsp;e:ALL)
- [x] [Mishra's Groundbreaker](https://scryfall.com/search?q=!"Mishra's+Groundbreaker"&nbsp;e:ALL)
- [x] [Misinformation](https://scryfall.com/search?q=!"Misinformation"&nbsp;e:ALL)
- [x] [Mystic Compass](https://scryfall.com/search?q=!"Mystic+Compass"&nbsp;e:ALL)
- [x] [Nature's Blessing](https://scryfall.com/search?q=!"Nature's+Blessing"&nbsp;e:ALL)
- [x] [Nature's Chosen](https://scryfall.com/search?q=!"Nature's+Chosen"&nbsp;e:ALL)
- [x] [Nature's Wrath](https://scryfall.com/search?q=!"Nature's+Wrath"&nbsp;e:ALL)
- [x] [Noble Steeds](https://scryfall.com/search?q=!"Noble+Steeds"&nbsp;e:ALL)
- [x] [Omen of Fire](https://scryfall.com/search?q=!"Omen+of+Fire"&nbsp;e:ALL)
- [x] [Phantasmal Fiend](https://scryfall.com/search?q=!"Phantasmal+Fiend"&nbsp;e:ALL)
- [ ] [Phantasmal Sphere](https://scryfall.com/search?q=!"Phantasmal+Sphere"&nbsp;e:ALL)
- [x] [Phelddagrif](https://scryfall.com/search?q=!"Phelddagrif"&nbsp;e:ALL)
- [x] [Phyrexian Boon](https://scryfall.com/search?q=!"Phyrexian+Boon"&nbsp;e:ALL)
- [x] [Phyrexian Devourer](https://scryfall.com/search?q=!"Phyrexian+Devourer"&nbsp;e:ALL)
- [x] [Phyrexian Portal](https://scryfall.com/search?q=!"Phyrexian+Portal"&nbsp;e:ALL)
- [x] [Phyrexian War Beast](https://scryfall.com/search?q=!"Phyrexian+War+Beast"&nbsp;e:ALL)
- [x] [Pillage](https://scryfall.com/search?q=!"Pillage"&nbsp;e:ALL)
- [ ] [Primitive Justice](https://scryfall.com/search?q=!"Primitive+Justice"&nbsp;e:ALL)
- [x] [Pyrokinesis](https://scryfall.com/search?q=!"Pyrokinesis"&nbsp;e:ALL)
- [x] [Reinforcements](https://scryfall.com/search?q=!"Reinforcements"&nbsp;e:ALL)
- [x] [Reprisal](https://scryfall.com/search?q=!"Reprisal"&nbsp;e:ALL)
- [x] [Ritual of the Machine](https://scryfall.com/search?q=!"Ritual+of+the+Machine"&nbsp;e:ALL)
- [ ] [Rogue Skycaptain](https://scryfall.com/search?q=!"Rogue+Skycaptain"&nbsp;e:ALL)
- [x] [Royal Decree](https://scryfall.com/search?q=!"Royal+Decree"&nbsp;e:ALL)
- [x] [Royal Herbalist](https://scryfall.com/search?q=!"Royal+Herbalist"&nbsp;e:ALL)
- [x] [Scarab of the Unseen](https://scryfall.com/search?q=!"Scarab+of+the+Unseen"&nbsp;e:ALL)
- [ ] [Scars of the Veteran](https://scryfall.com/search?q=!"Scars+of+the+Veteran"&nbsp;e:ALL)
- [x] [School of the Unseen](https://scryfall.com/search?q=!"School+of+the+Unseen"&nbsp;e:ALL)
- [x] [Seasoned Tactician](https://scryfall.com/search?q=!"Seasoned+Tactician"&nbsp;e:ALL)
- [x] [Sheltered Valley](https://scryfall.com/search?q=!"Sheltered+Valley"&nbsp;e:ALL)
- [x] [Shield Sphere](https://scryfall.com/search?q=!"Shield+Sphere"&nbsp;e:ALL)
- [x] [Sol Grail](https://scryfall.com/search?q=!"Sol+Grail"&nbsp;e:ALL)
- [x] [Soldevi Adnate](https://scryfall.com/search?q=!"Soldevi+Adnate"&nbsp;e:ALL)
- [x] [Soldevi Digger](https://scryfall.com/search?q=!"Soldevi+Digger"&nbsp;e:ALL)
- [x] [Soldevi Excavations](https://scryfall.com/search?q=!"Soldevi+Excavations"&nbsp;e:ALL)
- [x] [Soldevi Heretic](https://scryfall.com/search?q=!"Soldevi+Heretic"&nbsp;e:ALL)
- [x] [Soldevi Sage](https://scryfall.com/search?q=!"Soldevi+Sage"&nbsp;e:ALL)
- [ ] [Soldevi Sentry](https://scryfall.com/search?q=!"Soldevi+Sentry"&nbsp;e:ALL)
- [x] [Soldevi Steam Beast](https://scryfall.com/search?q=!"Soldevi+Steam+Beast"&nbsp;e:ALL)
- [x] [Soldier of Fortune](https://scryfall.com/search?q=!"Soldier+of+Fortune"&nbsp;e:ALL)
- [x] [Spiny Starfish](https://scryfall.com/search?q=!"Spiny+Starfish"&nbsp;e:ALL)
- [x] [Splintering Wind](https://scryfall.com/search?q=!"Splintering+Wind"&nbsp;e:ALL)
- [x] [Stench of Decay](https://scryfall.com/search?q=!"Stench+of+Decay"&nbsp;e:ALL)
- [x] [Storm Cauldron](https://scryfall.com/search?q=!"Storm+Cauldron"&nbsp;e:ALL)
- [x] [Storm Crow](https://scryfall.com/search?q=!"Storm+Crow"&nbsp;e:ALL)
- [x] [Storm Elemental](https://scryfall.com/search?q=!"Storm+Elemental"&nbsp;e:ALL)
- [x] [Storm Shaman](https://scryfall.com/search?q=!"Storm+Shaman"&nbsp;e:ALL)
- [x] [Stromgald Spy](https://scryfall.com/search?q=!"Stromgald+Spy"&nbsp;e:ALL)
- [ ] [Suffocation](https://scryfall.com/search?q=!"Suffocation"&nbsp;e:ALL)
- [x] [Surge of Strength](https://scryfall.com/search?q=!"Surge+of+Strength"&nbsp;e:ALL)
- [x] [Sustaining Spirit](https://scryfall.com/search?q=!"Sustaining+Spirit"&nbsp;e:ALL)
- [x] [Swamp Mosquito](https://scryfall.com/search?q=!"Swamp+Mosquito"&nbsp;e:ALL)
- [x] [Sworn Defender](https://scryfall.com/search?q=!"Sworn+Defender"&nbsp;e:ALL)
- [ ] [Taste of Paradise](https://scryfall.com/search?q=!"Taste+of+Paradise"&nbsp;e:ALL)
- [x] [Thawing Glaciers](https://scryfall.com/search?q=!"Thawing+Glaciers"&nbsp;e:ALL)
- [x] [Thought Lash](https://scryfall.com/search?q=!"Thought+Lash"&nbsp;e:ALL)
- [x] [Tidal Control](https://scryfall.com/search?q=!"Tidal+Control"&nbsp;e:ALL)
- [x] [Tornado](https://scryfall.com/search?q=!"Tornado"&nbsp;e:ALL)
- [ ] [Undergrowth](https://scryfall.com/search?q=!"Undergrowth"&nbsp;e:ALL)
- [x] [Unlikely Alliance](https://scryfall.com/search?q=!"Unlikely+Alliance"&nbsp;e:ALL)
- [x] [Urza's Engine](https://scryfall.com/search?q=!"Urza's+Engine"&nbsp;e:ALL)
- [x] [Varchild's Crusader](https://scryfall.com/search?q=!"Varchild's+Crusader"&nbsp;e:ALL)
- [x] [Varchild's War-Riders](https://scryfall.com/search?q=!"Varchild's+War-Riders"&nbsp;e:ALL)
- [x] [Veteran's Voice](https://scryfall.com/search?q=!"Veteran's+Voice"&nbsp;e:ALL)
- [x] [Viscerid Armor](https://scryfall.com/search?q=!"Viscerid+Armor"&nbsp;e:ALL)
- [x] [Viscerid Drone](https://scryfall.com/search?q=!"Viscerid+Drone"&nbsp;e:ALL)
- [x] [Wandering Mage](https://scryfall.com/search?q=!"Wandering+Mage"&nbsp;e:ALL)
- [x] [Whip Vine](https://scryfall.com/search?q=!"Whip+Vine"&nbsp;e:ALL)
- [x] [Whirling Catapult](https://scryfall.com/search?q=!"Whirling+Catapult"&nbsp;e:ALL)
- [x] [Wild Aesthir](https://scryfall.com/search?q=!"Wild+Aesthir"&nbsp;e:ALL)
- [x] [Winter's Night](https://scryfall.com/search?q=!"Winter's+Night"&nbsp;e:ALL)
- [x] [Yavimaya Ancients](https://scryfall.com/search?q=!"Yavimaya+Ancients"&nbsp;e:ALL)
- [x] [Yavimaya Ants](https://scryfall.com/search?q=!"Yavimaya+Ants"&nbsp;e:ALL)
