### ISSUE TITLE
RNA feedback and errors (BETA)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5516]
From beta server, checked it on fixed or not confirmed:
* [x] offalsnout - This card should trigger when it leaves the battlefield. (MadMoses, 2019-01-04) 
* [x] Dovin Baan ultimate - It's programmed as -X, rather than -7 (FreyHaldan, 2019-01-09) 
* [x] Drill Bit - When casting with spectacle it does not target and does not do anything (FreyHaldan, 2019-01-09) 
* [x] Domri doesn't give riot - Domri's +1 does not give a creature riot when casting it with the green mana produced (FreyHaldan, 2019-01-09) 
* [x] Ravager Wurm - the fight ability doesn't target and fizzles (FreyHaldan, 2019-01-09) 
* [x] Hydroid Krasis - doesn't gain life and doesn't draw cards when cast, though the ability does trigger (FreyHaldan, 2019-01-09) 
* [x] Azorius Skyguard - Not giving -1/+0 to opponent's creatures (Glitch, 2019-01-12)
* [x] Spectacle sorceries - Don't resolve when spectacle cost is payed (Glitch, 2019-01-12)
* [x] Arrester's admonition - Not working (Glitch, 2019-01-12)
* [x] Rakdos, the Showstopper - Flips coin only for controller's creatures (and lands) (Glitch, 2019-01-12 18:46)
* [x] new rakdos bugged - rakdos the showstopper makes you roll for every permanent (ChandraAblazin, 2019-01-12)
* [x] Sentinel's Mark (RNA) bugged - Sentinel's Mark doesn't give lifelink (GrimStrider, 2019-01-12 18:15)
* [x] Mass Manipulation - Cannot select targets beyond the second one (Glitch, 2019-01-12 18:15)
* [x] Hydroid Krasis doesn't gain life or draw cards if countered - My Hydroid Krasis was countered with Quench - it neithe drew cards nor gained life. (Zerris, 2019-01-12 19:15);
* [x] Kaya's Wrath doesn't kill anything - Kaya's Wrath just goes straight to the graveyard when cast without killing anything. (Zerris, 2019-01-12 19:17)
* [x] Kaya's Wrath - Kaya's Wrath only destroys creatures you control. Opponents creatures live. (GrimStrider, 2019-01-12 19:19)
* [x] Grotesque demise - "Exile target permanent" instead of "Exile target creature with cmc 3" (Glitch, 2019-01-12 20:57)
* [x] Plague Wight - Doesn't trigger -1/-1 (Glitch, 2019-01-12 21:02)
* [x] Silhana Wayfinder has wrong hover text - Silhana Wayfinder's hover text says look at the top four cards and put one "into your library".  That should be "on top of your library". (Zerris, 2019-01-12 21:09)
* [x] Silhana Wayfinder's ability text is wrong - Silhana Wayfinder's Ability text says "Select a creature or land to put on top of your library in a random order".  The "in a random order" part shouldn't be there. (Zerris, 2019-01-12 21:11)
 * **next build**
 * [x] amplifire bug - amplifire reveals cards until it sees a creature, but power and toughness don't change. (ChandraAblazin, 2019-01-12 22:02)
 * [x] Emergency Powers - Addendum doesn't work. (Glitch, 2019-01-12 22:52)
 * [x] Gardian Project - Not working (Glitch, 2019-01-12 23:21)
 * [x] Clear the Stage - Doesn't return creature from graveyard (Glitch, 2019-01-12 23:34)
 * [x] Rakdos Roustabout - Triggers on attack (Glitch, 2019-01-12 23:36)
 * [x] Mirror March - The enchantment doesn't seem to do anything.  I cast an Enraged Ceratok with it in play, it triggered, I flipped Heads, Heads, Tails - and nothing was created.  I got no tokens (Zerris, 2019-01-13 05:07);
 * [x] Undercity Scavenger - When I sacrificed a human token from Hero of Precinct One to Undercity Scavenger's ETB, it only got one +1/+1 counter, rather than two. (Zerris, 2019-01-13 07:39)
 * [x] Amplifire - No change in base p/t. (Glitch, 2019-01-13 09:17)
 * [x] Rakdos, the Showstopper - Even when targeting your opponent's creatures for the flips, it will still say "Zerris won the flip (heads)", even though you wanted to flip tails. (Zerris, 2019-01-13 10:42) -- jeffwadsworth: you don't target anything with this card, it cycles through the creatures on the battlefield.  It works correctly.
 * [x] trouble starting games - in RNA sealed tournaments have a problem where 1 person does not enter the game after deck submission. (jodosal, 2019-01-13 14)
 * [x] Sealed Failing to fire - Sealed games don't seem to be loading properly - you can build your deck, and it'll let you join the game, but nothing loads - your hands never show up. (Zerris, 2019-01-14 04:32)
 * [x] Dovin, Grand Arbiter Bug - +1 ability should add a loyalty counter "each time" a creature a creature deals combat damage that turn, and he only gets 1 trigger after combat damage no matter how many creatures deal damage. (spinech, 2019-01-14 03:01);
 * [x] RNA Domri +1 does not give creatures played Riot (james, 2019-01-14 04:47)
 * [x] Roustabout - Doesn't trigger on block. (Glitch, 2019-01-14 13:40)
 * [x] mass manipulation gives null error - i dont actually know about this, i read it in chat (gsail11, 2019-01-14 15:14)
 * [x] captive audience - captive audience needs a special user prompt for which opponent to enter the battlefield under (actually maybe that has already been coded and it just isn't working properly after they select) but it came into the battlefield under the casters control (gsail11, 2019-01-14 15:15)
 * [x] Conflux Images - Images don't download for the Conflux set and I'm unable to manually make a directory for the set name since Windows prohibits making folders named "CON" (skuggi, 2019-01-14 15)
 * [x] sealed breaks sometimes - Just had a sealed game not start after construction of deck finished, no idea why tbh (FreyHaldan, 2019-01-14 16:20)
 * [x] Smothering Tithe - Smothering Tithe doesn't create token regardless if opponent pays 2 colorless mana or not (CinnamonRoll, 2019-01-15 01:16:06.533) 
 * [ ] Gateway Sneak - When Gateway Sneak gains unblockable due to a gate entering, there's nothing in the hovertext to indicate this, as there is when things get haste or trample. (Zerris, 2019-01-15 01:28:45.037) 
 * [x] Unbreakable Formation Bug - The Addendum mode on this card should add +1/+1 counters and give vigiliance until end of turn, but does not give vigilance (counters only). (andrew, 2019-01-15 03:11:45.267) 
 * [x] Cube Failed to Load - Salgrem started a Sealed Cube from Cubeblog/120901, and after we built our sealed decks, the game never fired.  We both submitted decks, but it never switched off the mane pane. (Zerris, 2019-01-15 04:21:08.608) **JayDi85**: connection problem for one of the player.
 * [x] rakdos roustabout's afflict doesn't work - roustabout doesn't do damage when blocked (ChandraAblazin, 2019-01-15 12:51:20.094) 
 * [ ] Dovin, Grand Arbiter - Ultimate lets the player pick the order of cards to put on bottom of library. (Glitch, 2019-01-15 15:37:51.08) 
 * [x] Sharktocrab - Second ability text displays P1P1 (Glitch, 2019-01-15 15:42:38.388) 
 * [x] Lumbering Battlement - Doesn't exile creatures. But makes them loose counters and puts images of cards in exile zone (Glitch, 2019-01-15 15:48:15.326) 
 * [x] Standard Game Failed to Load - Game two of our match failed to load (me vs ZSparks at 11:13 AM).  We were brought to the battlefield, but our opening hands never showed up. (Zerris, 2019-01-15 17:16:28.578) **JayDi85**: connection problem for one of the player.

From reddit:
* [x] Riot doesn't trigger with mana created by Domri, Chaos Bringer.
* [x] Rakdos, The Showstopper can destroy lands as well.
* [x] Domri's Second ability is mandatory instead of optional, I can't put only 1 creature in my hand.
* **next build**
* [x] Font of Agonies - does not seem to work for me, it says "destroy that creature" instead of "destroy target creature" and when activating the ability you cannot target anything and nothing happens. (apfelmaul)

From discord:
 * [x] Ravager wurm: fight ability fizzled even though there were legal targets
 * [x] Priest of Forgotten Gods: Never got to choose target players
 * [x] Biogenic Ooze: No option to activate 1ggg ability
 * [x] Knight of the Last Breath: No option to activate 3+sac ability
 * [x] Arrester's Admonition: Caused a java exception (I think it was array index out of bounds?) and a rollback
 * **next build**
 * [x] Rakdos Roustabout - Effect triggers when declared as an attacker, not when blocked. (ShinyPants)
 * [x] Rumbling Ruin - Missing oracle text? Nothing after the comma: "When Rumbling Ruin enters the battlefield, " (ShinyPants)
 * [x] Teysa - didn't double an afterlife trigger for me (kahnyoudiggit)
 * [x] Tooltip on Revival/Revenge is for some completely different card (kahnyoudiggit)
 * [x] Code of constraint's addendum doesn't make the creature not untap (kahnyoudiggit)
 * **next build - 15.01.2019**
 * [x] Clear the mind ignores targets, and always shuffles the caster's graveyard in (kahnyoudiggit)
 * [x] Silhana Wayfinder's ability is not optional - when I saw 4 lands on top of my deck, I was forced to pick one to leave there. (it should be a may), (Zerris)
 * [x] Captive Audience is still coming into play under the caster's control, when it should come in under an opponent's (Zerris)
 * [x] Rakdos Roustabout is not dealing damage when blocked; ability never even triggers (Zerris)
 * [x] Benthic Biomancer has incorrect ability text with P1P1 (Zerris)
 * [x] Dovin, Grand Arbiter's Ultimate lets you pick the order for the cards going to the bottom
they should be random (Zerris)
 * [x] Kaya, Orzhov Usurper's second ability doesn't say "non-land" in the hover text or ability text (Zerris)

**Comment by AricHaldan** [comment]
-Dovin Baan's ultimate has been fixed I believe (there was a commit fixing it a couple of days ago
-I've also noticed Dead revels casted with spectacle does not target either so could be an overall problem with spectacle.
-Teysa Karlov doesn't double the triggers of creatures dying themselves (f.e. afterlife), but this might be correct. I'm guessing we would need to wait for gatherer to see how exactly her ability works in regard to that.
-Priest of Forgotten Gods doesn't seem to be triggering the 'target players lose life and sacrifice a creature clause' when using the sacrifice ability.

**Comment by kahnyoudiggit** [comment]
Rumbling ruin mouseover text displays as "When Rumbling Ruin enters the battlefield," - the activated ability works fine though.

**Comment by CCTV-1** [comment]
deface should be "Destroy target creature with defender",now is "Destroy target Permanent"
![tim 20190113135022](https://user-images.githubusercontent.com/7350506/51082071-952ff180-173a-11e9-980a-f332f4a45378.png)

**Comment by JayDi85** [comment]
* [ ] Lumbering Battlement - NullPointerException error. Server logs:
```
java.lang.NullPointerException
        at mage.cards.l.LumberinBattlementValue.calculate(LumberingBattlement.java:128)
        at mage.abilities.effects.common.continuous.BoostSourceEffect.apply(BoostSourceEffect.java:86)
        at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:102)
        at mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:986)
        at mage.game.GameState.applyEffects(GameState.java:573)
        at mage.game.GameImpl.applyEffects(GameImpl.java:1530)
        at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3547)
        at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3493)
        at mage.game.stack.Spell.resolve(Spell.java:293)
        at mage.game.GameImpl.resolve(GameImpl.java:1404)
        at mage.game.GameImpl.playPriority(GameImpl.java:1354)

```

**Comment by CCTV-1** [comment]
Essence Capture should be "Counter target creature spell",,now is "Counter target spell"
![1](https://user-images.githubusercontent.com/7350506/51096338-c837bb00-17f6-11e9-879b-1522e25c135b.png)

**Comment by fxyo1** [comment]
afterlife is indeed a triggered ability of a permanent.

**Comment by themogwi** [comment]
Concerning:
"Rakdos, the Showstopper - Even when targeting your opponent's creatures for the flips, it will still say "Zerris won the flip (heads)", even though you wanted to flip tails."

Is this working as intended? I know we have Mana Crypt working exactly the same, where we don't actually ask for the users input (heads/tails). 

It may be nice to allow a user to chose but this may be able to be considered a quality of life change.

**Comment by jeffwadsworth** [comment]
Unless I am going insane, the Rakdos, the Showstopper works fine.  What should it show in the log instead?
2:47 AM: [Flip a coin] jeff lost (tail).
2:47 AM: Memnite [042] died
2:47 AM: [Flip a coin] jeff lost (tail).
2:47 AM: Memnite [dfe] died
2:47 AM: [Flip a coin] jeff won (head).
2:47 AM: [Flip a coin] jeff won (head).

**Comment by themogwi** [comment]
If you are Jeff in this scenario and the creature being destroyed is your opponents would you consider this coin flip a "Loss" or a "Win"?

It's of my opinion that the flip should be considered a "Win" if you are successfully destroying a creature on your opponents battlefield and a "Loss" otherwise.

**Comment by theelk801** [comment]
the problem is that a flip is a win or a loss if you call it as such, but with Rakdos you don't call the flip and therefore don't win or lose

> 705. Flipping a Coin

>705.1. An effect that instructs a player to flip a coin may care whether that player wins or loses the flip. To flip a coin for such an effect, the player flips the coin and calls “heads” or “tails.” If the call matches the result, the player wins the flip. Otherwise, the player loses the flip. Only the player who flips the coin wins or loses the flip; no other players are involved.

>705.2. If an effect instructs a player to flip a coin and that effect cares only whether the coin comes up heads or tails without specifying a winner or loser of the flip, that player flips a coin without making a call. No player wins or loses this kind of flip.

**Comment by themogwi** [comment]
TDIL to consult WOTC's comprehensive ruleset before making my own assumptions of how something should "work" as apparently it is verbose enough to describe exactly that.

**Comment by AricHaldan** [comment]
so according to these rules does rakdos, showstopper and similar cards that flip a coin without specifying a winner or loser of the flip not trigger cards like Chance Encounter ? Because I think that with the current implementation they do, so an overhaul could be fairly important for proper rule enforcement if this is the case.

btw Maro confirmed that Teysa works with death triggers of creatures that just died http://markrosewater.tumblr.com/post/181874862323/can-you-confirm-that-teysa-karlov-works-with

**Comment by theelk801** [comment]
Yeah that's why I need to make sure I fix it. Also Teysa should be working fine now.

**Comment by AricHaldan** [comment]
I have done some testing again since most of the bugs seemed to be fixed so I thought I'd check as much cards as I can and I found some new bugs that hadn't been reported yet

- [ ] Clear the Mind: Shuffles own library regardless of target

- [ ] Sharrgan Hellkite: couldn't activate it's ability

- [ ] Cavalcade of Calamity: triggers but does not deal the damage

- [ ] Bedazzle side of Bedeck // Bedazzele does not deal the 2 damage

- [ ] Lumbering battlement: I don't really know what happens here but the creatures seem to remain on the battlefield even though they are exiled and you can still attack with them.

- [ ] Captive Audience: only chooses an opponent after it enters the battlefield and comes down on the board of the one who cast it

- [ ] Biogenic Upgrade: can't target creatures you don't control

- [ ] Domri Rade: If you do not use the mana from his +1 (or at the very least not use it on a creature) it seems to remember and stack the effect the next time you cast a creature with this effect giving it X+1 times Riot where X is the amount of times you activated the ability without casting a creature with it.

**Comment by theelk801** [comment]
Are you sure Skarrgan Hellkite had a counter on it?

**Comment by AricHaldan** [comment]
Yeah Skarrgan was my mistake, I tested it again and worked fine.
