### ISSUE TITLE
UI: save and load table/tournament settings to file

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5525]
New table/tournament dialog must have button to save and load game settings. It's already have "load last configuration" buttons but it's a different approach.

TODO:
 * [ ] make game settings config format (as example: json);
 * [ ] file format must be compatible between table/tournament modes (e.g. you can load table config for tournament dialog and setup missing values);
 * [ ] configs can contains small number of settings or other data (as example: image name and description for server side competitive/event);
 * [ ] add buttons to save and load configs (table + tournament dialogs);
 * [ ] add sample folder with standard configs for popular game and modes (see sample deck example).

P.S. #446

**Comment by Ebola16** [comment]
The current automatically saved settings doesn't store player names, skill level, or deck selection properly. This would be a nice feature to have!

Before match:
![BEFORE](https://user-images.githubusercontent.com/17330088/59460317-cea18180-8dec-11e9-8841-324d3bb0068b.PNG)

After match:
![AFTER](https://user-images.githubusercontent.com/17330088/59460330-d6612600-8dec-11e9-998d-a7baa94a41e2.PNG)
