### ISSUE TITLE
v33 feedback and errors - completed

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5529]
v33 was released ([beta's feedback topic is here](https://github.com/magefree/mage/issues/5516)). 

Here you can write feedback or error reports (if you got big bug report then feel free to create new issue).

**v33v0 (2019.01.16)**:
 * [x] Domri (RNA) -8 ult is not working, I do get the emblem, but i dont get the beasts (Wishmaster, 2019-01-16 20:19)
 * [x] aurelia triggered skill doesnt work (Aizzel, 2019-01-16 20:18)
 * [x] UMA Promo causes error message in Deck builder - When i use the UMA fullart eternal witness the deck builder pops up a error message about a card too few being detected, but it still appears in the decklist (Deadlylama, 2019-01-16 18:32): **JayDi85**: it's old saved deck with old card numbers -- that's cards replaced with same name card.
 * [x] Wrong Card Images - In Both the original and duel decks anthology of the elves vs goblins decks the card images for wirewood lodge and tranquil thicket are swapped. Also applies to patagia golem and ornithopter from 6th edition (Deadlylama, 2019-01-16 18:13), **JayDi85**: it's old card images from old versions, need to redownload new one.
 * [x] As Foretold - broken and raise null point exception:
* [x] UMA Promo causes error message in Deck builder - When i use the UMA fullart eternal witness the deck builder pops up a error message about a card too few being detected, but it still appears in the decklist (Deadlylama, 2019-01-16 18:32:17.704) 
 * [x] aurelia triggered skill doesnt work - (300 characters max) (Aizzel, 2019-01-16 20:18:56.364) 
 * [x] Domri (RNA) -8 ult is not working - I do get the emblem, but i dont get the beasts (Wishmaster, 2019-01-16 20:19:56.502) 
 * [x] Blood Sun still doesn't work properly - Blood sun as per RIX's release notes does prevent etb tapped lands from entering tapped, but still happens in xmage (Traxgarte, 2019-01-17 00:28:26.852) 
 * [x] Rhyth of the Wild Graveyard - I revived something with Rise from the Grave and had a Rhythm of the Wild on Board but couldnt choose from +1+1 and haste (Sarkhandisdick, 2019-01-17 00:53:02.808) 
 * [x] As foretold is bugged - (Currently as foretold is bugged and it cant be played, it forces a rollback.
Love you xmage (Dunadan, 2019-01-17 02:12:42.921) 
 * [x] Macabra Mockery is bugged - Macabra Mockery lets you keep the creature. It should be sacrificed at end step, but currently it doesn't. (whakapapa, 2019-01-17 09:18:52.308) 
 * [x] Macabre Mockery - Creature does not get sacreficed at the end of turn. (viginti, 2019-01-17 09:18:59.677) 
 * [x] Growth Chamber Guardian misimplementation - I played Growth-Chamber Guardian with Rhythm of the wild in play, choosing +1 counters. The counter did go on, but the deck search trigger of Growth Chamber Guardian didnt happen. (meister_gallen, 2019-01-17 13:01:38.631) 
 * [x] Exist images in game data base? Yes, but no... - After the last update was completed my program dont have images!
The images are saved in correct directory but dont read them. (BRAIANZ, 2019-01-17 17:29:23.65) 
 * [x] RNA Bug - The Bedazzle half of Bedeck // Bedazzle doesn't deal damage (Bob49, 2019-01-18 00:54:28.034) 
 * [x] As Foretold - Game rolls back when casting As Foretold (new bug with last update) (Bob49, 2019-01-18 15:34:27.701) 
 * [x] Problem with rhythm of the wild - Attempting to play a combo deck with kitchen finks and rhythm, creature died and came back but i was never given the option to put a counter on it meaning it cannot go infinite (mrleprechaun28, 2019-01-18 15:39:37.101) 
 * [x] Silhana Wayfinder doesn't use random order - Silhana wayfinder puts the one card you pick for the effect on top "in a random order" and you can pick the order of cards that go to the bottom (Deadlylama, 2019-01-18 23:55:54.749) 
 * [x] Dovin's acuity - Dovin's acuity does not bounce back to hand or even triggers when the condition is meet. (jayhovascuz, 2019-01-19 02:37:24.866) 
 * [x] As foretold NPE exception;
 * [x] Tidehollow Sculler cast exception;
 * [x] Jace, Architect of Thought - NPE error:
 * [x] MorphAbility cause ClassCastException for AI's simulatePriority:
```
Caused by: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
        at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:468)
        at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:268)
        at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:490)
        at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:268)
        at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:409)
        at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:406)

```

**33v1 release  (2019.01.22)**
 * [x] Thief of Sanity bug - Can't cast cards exiled with thief of sanity in version 1.4.33V1
When you click on exiled card it gives you the "look at card?" option, if you click "no" nothing happens. (P1000, 2019-01-22 18:45:38.099) 
 * [x] Knight of the Mists fails to destroy knights (zorkmead, 2019-01-22 20:22:52.406) 
 * [x] Expansion - can't be cast sometimes - I tried copying an electrodominanance I cast with the expansion part of expansion // explosion but it wouldn't let me (FreyHaldan, 2019-01-22 20:29:31.276) 
 * [x] Incubation Druid and rythm of the wild is broke - Rythm didnt trigger when my pheonix came back and you cant utilize 3 mana from the druid (Mexican_Agent, 2019-01-22 21:03:12.166) 
 * [x] Hostage Taker - The card that you exile with Hostage Taker I cannot seem to cast, Even though I have all the mana and costs set up. (DMage, 2019-01-22 22:41:31.358) 
 * [x] Hostage Taker - Please fix the hostage taker, won't let me cast creature from exile (AnotherTest, 2019-01-23 07:33:59.979) 
 * [x] Hostage Taker - Please fix the abilitiies (AnotherTest, 2019-01-24 02:34:33.361) 
 * [x] Hostage Taker - Please fix this creatures abiliity.  After the steal, it won't let me cast from exile. (AnotherTest, 2019-01-24 08:29:01.974) 
 * [x] Hostage Taker - still unable to cast creature exiled with hostage taker, please fix (AnotherTest, 2019-01-25 00:01:07.225) 
 * [x] Hostage taker  - I cannot cast the card exiled with it. - (300 characters max) (DMage, 2019-01-25 19:09:14.432) 
 * [x] Phrexian Processor - Phrexian processor should be "as this enters" not "when this enters" (evilgeek_, 2019-01-23 01:41:40.199) 
 * [x] targeting - when someone targets your permanents, skip is automatically canceled (igniteaxoim, 2019-01-23 03:12:48.568) **JayDi85**: must be fixed with v34
 * [x] Scuttlegator - can't attack with counters (it's calls adapt instead selects to attack);
 * [x] Ajani - bug, Ajani for standard, his +1 doesn't work at all. (doc_brietz, 2019-01-23 05:29:18.911) 
 * [x] treasure nabber - treasure nabber steals stuff permentantly (igniteaxoim, 2019-01-23 21:27:56.395) 
 * [x] Image downloads don't work - I've tried downloading the images to the new set and it doesn't let me, even tried re-downloading the program as a whole, and now I can't download any images. (Datto, 2019-01-23 21:36:41.745) 
 * [x] Rhythm of the Wild - Rhythm of the Wild seems like it tries to work as a "cast" effect rather than ETB, as it should (Magnus2D, 2019-01-23 22:14:14.844) 
 * [x] Rhythm of the wilds not giving riot - i searched a creature with prime speaker vannifar while rythm of the wild was on the battle field and it did not receive riot (Knighthawke, 2019-01-24 03:22:17.997) 
 * [x] Gonti Bugged - I can't cast the cards I exiled with Gonti, Lord of Luxury. I can look at them, but I can't cast them. (TheCheese, 2019-01-23 23:38:08.681) 
 * [x] Cannot cast card from exile - Since update 1.4.33V1, whenever I exile a card with Thada Adel, Acquisitor, I am not able to cast it that turn (Extillius, 2019-01-24 10:40:26.152) 
 * [x] Archive Trap and flashback - When Archive Trap gains flashback, you cant cast it for its 0 cost. (Shaqattack, 2019-01-24 16:18:58.355)  <- This is a known issue involving alternative costs and flashback. (in this case it works as intended though -TheElk801)
 * [x] Resolution - Hello, sadly Xmage does not work with my older computer only because the resolution is too high. As a result I can not see all cards in my hand, everything works just fine. Would it be possible to make cards even smoller? Thank you (sherynek, 2019-01-24 18:57:02.662) **JayDi85**: use GUI settings
 * [x] Spellqueller -> exile Logic knot - Spellqueller could not target logic knot. (DeStar, 2019-01-24 19:32:27.285) **JayDi85**: works fine
 * [x] Scourge of the Throne not triggering - Scourge of the Throne was attacking an opponent after cheating it into the game with Mosswort Bridge. The opponent had the most life, and he got his counters, however his untap and extra combat step didn't trigger. (Saninsince992, 2019-01-24 19:52:46.655) 
 * [x] rollback - instead of rolling back a whle turn, there should be a rollback just for the last play. that's what it's usually used for. (igniteaxoim, 2019-01-24 20:33:59.629) **JayDi85**: it's hard to implement (xmage uses many effect/plays/choices without user actions).
 * [x] mnemonic betrayal - I could not cast any cards with mnemonic betrayal (doc_brietz, 2019-01-24 20:59:26.639) **JayDi85**: works fine
 * [x] Fact or Fiction - it's bugged, won't let me choose which pile i want after opponent separates them. causes opponent to not be able to pass priority and i cant click anything during that. has happened twice now. (dukeboy4, 2019-01-24 22:43:20.558) 
 * [x] Cards now missing - Cards are now missing (GozerfishMTG, 2019-01-25 01:46:45.727) 
 * [x] Scrying - Scying seems bugged recently. Too many times to be a coincidence I scry a card to the bottom to have that same card be on top of the deck anyway. Happened on at least 10 occasions that it makes it less than likely to just be a coincidence. (binnet, 2019-01-25 08:02:43.96) 
 * [x] Kheru Spellsnatcher - Can't cast spell countered by Kheru Spellsnatcher - Countered a sandwurm convergence with the effect of the spellsnatcher and could not cast it when my turn came around (Deadlylama, 2019-01-25 15:01:24.599) **JayDi85**: works fine, tests it with sandwurm and other cards.

**33v1c release  (2019.01.26)**
* [x]  Benthic Biomancer - ability to loot not optional, but coded as optional (howdoUevenplay, 2019-01-27 10:24:06.829) 
* [x] High Alert - currently works on your opponents creatures as well and allows them to attack even if they had defender. I had a Sky Tether on an opponents creatures and also High Alert in play and he was able to attack me. (Taco, 2019-01-27 16:23:36.646) 
* [x] Thief of Sanity - doesnt work how it should (GingaNinja, 2019-01-27 22:31:24.307) 
* [x] Tasigur, the Golden Fang - Activating Tasigur didn't return any nonlands to hand. (empty graveyard->2 nonlands from mill) (Bob49, 2019-01-28 17:31:56.858) 
* [x] Selvala - Couldn't tap in response (Malitae, 2019-01-28 01:09:25.554) 
* [x] Selvala, Heart of the Wilds - needs its colored mana choice interface simplified, its bulky and takes up alot of time. (CrutchSapper, 2019-01-28 17:33:08.324) 
* [x] Tasigur+Silent Gravestone - Tasigur can't return cards while a Silent Gravestone is in play. However, the ability of Tasigur doesn't target cards in graveyards and shouldn't be effected (Bob49, 2019-01-28 17:45:31.035) 
* [x] Hurkyl's Recall - There is a bug casting Hurkyl's Recall to take back in his hand an artifact taken by the opponent (eg with Dack Fayden), as this artifact does not return in the hand of his original owners, but remains in play (gimilo81, 2019-01-28 19:27:40.925) 
* [x] Accursed Witch - Accursed Witch gives a bug when flipping (Bob49, 2019-01-29 18:08:46.957) 
* [x] Blood moon vs abundant growth. - My savannah which was enchanted with abundant growth was not able to use the abundant growth 'tap for any color mana' ability when there was a blood moon on the battlefield. As far as I can tell it should be able to. (ttowowoo, 2019-01-29 19:00:47.182) **JayDi85**: Blood moon is not fully implemented yet
* [x] Thank you - Gracias de verdad por creer en el software libre, gracias por luchar contra la tirania de MTgArena nunca se den por vencido (whiteraven, 2019-01-29 19:50:02.369) 
* [x] Commandeer - Regarding the instant card Commandeer, it doesn't work. When I try and cast it by exiling two blue cards in my hand, it just doesn't work. (Alack, 2019-01-30 18:05:50.225) 
* [x] Resplendent Angel - pump effect broken - I pumped resplendent angel to make it a 5/5, it wasn't blocked and no other effects were added to the stack, it went up to 5/5 but didn't gain me life and i didn't get an angel token at my end step (alana, 2019-01-30 21:44:13.033) 
* [x] Preacher - fix preacher in momir - failed to steal a creature in momir (dsn, 2019-01-31 03:42:39.4) 
* [x] Domri, Chaos Bringer (see #5582) - Looks like Domri +1 is still giving extra counters to things
my opponent just +1'd and then played a riot creature and it got three riot triggers instead of two (Zerris)
 * [x] Nature's Will  - it didn't untap my opponent's lands (trew, 2019-02-01 01:45:43.449)  **JayDi85: it's works fine, your lands untaps, opponent lands taps**
 * [x] Trouble Downloading Images - I try to download the images and it starts to count up then it switches to most of them complete then 0 have been downloaded. After that it stays 0 untill I close it an retry. (Ben, 2019-02-01 02:58:02.696) **JayDi85**: check your internet connection and proxy settings in preferences, then use [ipv5 fix from here](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/).
 * [x] Lethal Vapors and phasing - When you phase out Lethal Vapors while its activation is on the stack it still destroys the lethal vapors (JaptainCack, 2019-02-01 07:08:00.33)

**33v2 release  (2019.02.01)**
* [x] Domri, Chaos Bringer (see #5582) - Hi. When you activate Domri, Chaos Bringer's +1 ability to add one R or G mana but don't use it, the riot trigger still stays until you play your next creature spell. The mana empties from the pool though. (Chiefen, 2019-02-02 08:46:17.09) 
* [x] High Alert - High alert allows an opponents creature with defender to attack, when it shouldn't (AnotherTest, 2019-02-04 09:54:16.378) 
* [x] Wojek Siren - wojek siren only gives +1+0 instead of +1+1 (Sexy, 2019-02-05 07:18:33.305) 
* [x] Ratings - why when i play whith a rage quitter player in a ranking game, my rank no incresa? he lose the game no? (whiteraven, 2019-02-05 19:13:36.73) **JayDi85**: that's ok
* [x] Lags - I disconnect alot, Im not sure what you can do. but i just did the new update.. and boom. 4 games in a row disconnected. couldnt reconnect lost the game. 3 of them during the card pull on draft. 1 mid game. I love xmage. please help. (BakedWizard, 2019-02-02 06:28:12.277) 
* [x] Lags - Hi, since the new update, the game is lagging/freezing as hell after a few minutes. Other people says the same. Before the update everything was fine. (w00x, 2019-02-02 12:43:22.39) 
* [x] Lags - Not to be a nag, but since the last update, the play of the servers seems very janky, slow, and rough....anyway to smooth this out? (AnotherTest, 2019-02-04 09:00:35.815) 
* [x] Lags - Every draft seems to get stuck and skip picks, very hard to enjoy, please look into this (AnotherTest, 2019-02-05 04:08:55.831) 
* [x] Lags - Standard matchup rejects standard legal cards... (AnotherTest, 2019-02-05 18:20:03.813) 
* [x] No cards on Card vierwer and editor - sup! No cards on Card vierwer and from the deck editor. No editcions on the filters too Jus a couple images miss on the image downloader but no ono eppears On load a deck no card is recognized Best regards, Daniel Schuch (Schuch, 2019-02-07 03:37:33.653)  **JayDi85**: memory issue, same as lags

**33v3 release  (2019.02.10)**
* [x] Premodern games - Hi, Premodern games do not show up on XMage.de. Nobody can connect. All the best, Fred (Ithildin, 2019-02-09 18:22:38.862)
* [x] Just a thank you note - You are doing an amazing job guys ! Thanks a lot ! (Ithildin, 2019-02-10 15:24:43.614) 
* [x] Cards RNA - Hey ! I have a problem with the RNA cards. They are only available on Scryfall and when I download them I don't get them. It downloads from 0 to 291 cards instantly. I don't know what to do. Could you guys help me? Much love !!! (Naboki3, 2019-02-15 13:09:26.027) **JayDi85**: it's [ipv4 fix](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/).
* [x] Cards can't be found - I just updated to 1.4.33V3a (2019-02-09), and I can no longer create decks - the card images are all there in the img folder, but there's no card names in the Deck Editor, and I can't import decklists (Miryafa, 2019-02-17 20:09:34.638) 
* [x] Cards not loading (part 2) - Never mind - I just had to restart the program I guess? (Miryafa, 2019-02-17 20:24:24.522) 

**33v4 release  (2019.03.01)**

Forums:
 * [x] I can't spells like Dusk // Dawn, dread return, etc. from my gy (illuknisaa)
 * [x] Daru Spiritualist was targeted by Attrition and its ability fired off twice again. (BrassAngel42)
 * [x] Price of Fame - with new update Price of Fame does not get cheaper when targeting legendaries (freexx)
 * [x]  Intet, the Dreamer - I think there is a bug with Intet, the Dreamer's effect when playing againt the AI... after paying the mana for its activated ability, it would let me look at the card but not the option to play it without paying its mana cost.....can you take a look at it? (Sandalphon)
 * [x] Parallel Thoughts are glitched. The card says "When Parallel Thoughts comes into play, search your library for seven cards, remove them from the game in a face-down pile, and shuffle that pile. Then you shuffle your library. If you would draw a card, you may instead put the top card of the pile removed into your hand." XMage forces you to draw from the pile, including when the pile is empty, forcing you to skip your draws until the card is taken off the battlefield. (fluffystuff)
 * [x] Xantcha, Sleeper Agent has an etb trigger. It should be a replacement effect. (illuknisaa)
 * [x] I can't cast Memory side of Commit // Memory from gy. Last patch I could. (illuknisaa)
 * [x] Cephalid Pathmage onslaught -cephalid pathmage is unblockable=>this is ok, -tap, sacrifice cephalid pathmage: target creature is unblockable this turn=>this don't work, i cant sacrifice him, doesnt tap, don't does anything. (snmago11)
* [x] Banefire - x5 damage is preventable, but must not. From [reddit](https://www.reddit.com/r/XMage/comments/ak53i0/gisela_and_banefire_interaction/). So, in the client, Gisela halves Banefire damage even when X is more than 5, which it shouldn't. This isn't me just getting annoyed about something I think is wrong, I've had it put to a few judges, and they've all come back saying that Banefire would do full damage in that situation, so is this a bug, or just a missed ruling? Hope it can get fixed soon. (BlankOne782)
* [x] Terastodon - terastodon won't let me select any targets for the etb ability (QuoVadis, 2019-02-08 12:17:50.207) 
* [x] See the Unwritten - this card dont work, i try 2 time but the effect skip directly on the placing the card on the graveyard (Bellano, 2019-02-09 02:55:26.213)  **Are you sure you had creatures within the top 8 cards of your deck?  If not, that is normal.**
* [x] Premodern - Hi, On XMage.de, when we create a premodern game, it does not appear i the list of open games. Very strange. Thanks for all your hard work. (Ithildin, 2019-02-09 10:55:09.232) 

Discord:
 * [x] Domri - I don't know what happened but my opponent cast Rafter Demon using the new Domri Planeswalker's plus ability, and the rafter demon entered with 3 +1/+1 counters, when they chose for it to enter with 1 +1/+1 counter, Domri had been activated previously in the game and the creatures had only received 1 counter in those instances (AndyP) **JayDi85**: domri works fine,
 * [x] Chat logs must be read only - If I type into the chat log on the side, I can manually delete or add things. (Zerris)
 * [x] plaguecrafter's prompt text said "sacrifice a permanent" when i had a PW and enchantment out
didnt try to sac the enchantment, however so not sure if implemented incorrectly or just the text being wrong (Sphinx)
 * [x] rhythm of the wild - there is a bug you cant rhythm of the wild riot off of vannifar pod ETBs, it's probably coded as a cast trigger by accident

Other:
 * [x] magus of the moon - after being targeted by imprisoned by the moon, non basics have mountain subtype, but cant be tapped for money, double bug
![123asss](https://user-images.githubusercontent.com/8344157/51542305-5b669580-1e74-11e9-8bf6-c39a52a586e6.png)
![asdasdasd](https://user-images.githubusercontent.com/8344157/51542304-5b669580-1e74-11e9-8910-231e7fa8b2c6.png)
 * [x] Nahiri, the Harbinger -- NPE error:
```
Caused by: java.lang.NullPointerException
        at mage.cards.n.NahiriTheHarbingerEffect.apply(NahiriTheHarbinger.java:118)
        at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:171)
        at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:161)
        at mage.game.stack.StackAbility.resolve(StackAbility.java:84)
        at mage.player.ai.ComputerPlayer6.resolve(ComputerPlayer6.java:391)
```

**Users feature requests**:
* [x] BETTER UI - Just PLZ make a better UI that is more wide for a screen, and possible to make chat logs smaller (GSNameless, 2019-01-27 01:07:18.588) **JayDi85**: chat logs can be close/wrap by small error in the chat border.
* [x] game time - it is not possible anymore when you enter a game to see the maximum time for it. please add this feature again. Else I have to say, Thank you guys for spending so much effort and time on making xmage possible. (blob, 2019-01-29 18:57:03.425) **JayDi85**: `info` column in tables list contains time limit and wins count.
* [x] Export to .txt - Exactly the opposite of the "Import" button. Creates a decklist you can paste into tappedout or mtgpress. (M1k3y, 2019-02-12 06:00:13.896)

**Comment by RuohanW** [comment]
33v2 appears slower than all previous releases. The server also fails to recognize cards recognized by previous versions.

mage.MageException: Server error: Card not found - Daze - EMA/44 for deck - null
Possible reason is, that you use cards in your deck, that are only supported in newer versions of the server.
So it can help to use the same card from another set, that's already supported from this server.
	at mage.server.MageServerImpl.handleException(MageServerImpl.java:1068)
	at mage.server.MageServerImpl.executeWithResult(MageServerImpl.java:1252)
	at mage.server.MageServerImpl.joinTable(MageServerImpl.java:275)
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	at com.sun.proxy.$Proxy8.joinTable(Unknown Source)
	at mage.remote.SessionImpl.joinTable(SessionImpl.java:672)
	at mage.client.SessionHandler.joinTable(SessionHandler.java:251)
	at mage.client.dialog.NewTableDialog.btnOKActionPerformed(NewTableDialog.java:424)
	at mage.client.dialog.NewTableDialog.lambda$initComponents$3(NewTableDialog.java:180)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:149)
	at mage.client.dialog.MageDialog.show(MageDialog.java:67)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:73)
	at mage.client.dialog.NewTableDialog.showDialog(NewTableDialog.java:610)
	at mage.client.table.TablesPanel.btnNewTableActionPerformed(TablesPanel.java:1411)
	at mage.client.table.TablesPanel.lambda$initComponents$2(TablesPanel.java:966)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by apokalyptik** [comment]
4 player commander games have been almost unplayably laggy after a few rounds since 1.4.33V2.  Everyone I've conversed with about it in in-game chat has agreed.  Even tapping a single land for mana can take upwards of two or more seconds at times.

**Comment by BillyG-of-xmage-fame** [comment]
the new patch made stuff super laggy
i believe this is called a regression and unacceptable

solution: roll back to last build, call it new build, push update

everyone happy

fixing 4 cards to ruin game for everyone else not worth it

**Comment by Fubs** [comment]
Feature Suggestion from Ketsuban in discord: Add alternative mulligan rule options. [WotC is testing a new kind of mulligan rule](https://magic.wizards.com/en/articles/archive/competitive-gaming/mythic-championship-ii-format-and-london-test-2019-02-2) which we could add to xmage.
