### ISSUE TITLE
Show players ping in battlefield and other windows

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5568]
XMage gameplay depends on the quality of communication of all players. That's why it's important to know opponents ping/lag.

Lobby stores info about all players and their ping (avg, last). It's can be used to show ping info on battlefield.

TODO:
* [ ] client side code (lobby gets new info and updates all other);
* [ ] lobby: add "Ping" column in tables list (example: "125 (580)", where 125 = avg ping of all match/tourney players, 580 -- max avg ping from players);
* [ ] lobby: add ping coumn in waiting players window;
* [ ] match: add avg and last ping to player info (popup hint on avatar);
* [ ] match: add "ping" under avatar/name (last ping, always shows it -- for full and minimized avatar);
* [ ] match: colorize "ping" or username if it gets connecting problem;
* [ ] tourney: add ping to tourney players list;
* [ ] draft: add ping to player names in draft screen;

**Comment by pak1989** [comment]
Having a max avg ping during match/tourney creation would be pretty good.

**Comment by spjspj** [comment]
I'd say this is a bad thing as people who are far from the server won't be able to get any games.

**Comment by JayDi85** [comment]
Pings command works in game chat, but ignored in table/tourney. It can be useful.
