### ISSUE TITLE
Tests: add verify tests for missing tokens

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5622]
MTGJSON already have full data, so it can be used to check missing tokens data (xmage uses it's own tokens database). See `test_checkMissingTokenData` for some related tests.

TODO:
* [x] download and map bulk data to json data (see mtgjson example in `VerifyCardDataTest`);
* [x] verify card numbers;
* [x] verify tokens list in `tokens-database.txt` (sets and names);
* [x] verify tokens sets available in token classes (see `availableImageSetCodes` in token classes);
* [x] research and fix or add verify test for `setTokenType(1)`. See comment from https://github.com/magefree/mage/pull/9047#discussion_r886667015

**Comment by JayDi85** [comment]
Mtgjson already includes all data from scryfall. So it can be used for that verify tests. 

Card numbers checks already implemented, only tokens need (see tokens rework tracker in #6955).
