### ISSUE TITLE
WAR - War of the Spark Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#5662]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [x] Not Done -- [Finale of Promise](https://scryfall.com/search?q=Finale+of+Promise)
- [x] Not Done -- [God-Eternal Kefnet](https://scryfall.com/search?q=God-Eternal+Kefnet)
- [x] Not Done -- [Spark Double](https://scryfall.com/search?q=Spark+Double)

<details><summary>Implemented Cards</summary>

- [x] Done -- [Ahn-Crop Invader](https://scryfall.com/search?q=Ahn-Crop+Invader)
- [x] Done -- [Aid the Fallen](https://scryfall.com/search?q=Aid+the+Fallen)
- [x] Done -- [Ajani's Pridemate](https://scryfall.com/search?q=Ajanis+Pridemate)
- [x] Done -- [Ajani, the Greathearted](https://scryfall.com/search?q=Ajani,+the+Greathearted)
- [x] Done -- [Angrath's Rampage](https://scryfall.com/search?q=Angraths+Rampage)
- [x] Done -- [Angrath, Captain of Chaos](https://scryfall.com/search?q=Angrath,+Captain+of+Chaos)
- [x] Done -- [Arboreal Grazer](https://scryfall.com/search?q=Arboreal+Grazer)
- [x] Done -- [Arlinn's Wolf](https://scryfall.com/search?q=Arlinns+Wolf)
- [x] Done -- [Arlinn, Voice of the Pack](https://scryfall.com/search?q=Arlinn,+Voice+of+the+Pack)
- [x] Done -- [Ashiok's Skulker](https://scryfall.com/search?q=Ashioks+Skulker)
- [x] Done -- [Ashiok, Dream Render](https://scryfall.com/search?q=Ashiok,+Dream+Render)
- [x] Done -- [Augur of Bolas](https://scryfall.com/search?q=Augur+of+Bolas)
- [x] Done -- [Aven Eternal](https://scryfall.com/search?q=Aven+Eternal)
- [x] Done -- [Awakening of Vitu-Ghazi](https://scryfall.com/search?q=Awakening+of+Vitu-Ghazi)
- [x] Done -- [Band Together](https://scryfall.com/search?q=Band+Together)
- [x] Done -- [Banehound](https://scryfall.com/search?q=Banehound)
- [x] Done -- [Battlefield Promotion](https://scryfall.com/search?q=Battlefield+Promotion)
- [x] Done -- [Bioessence Hydra](https://scryfall.com/search?q=Bioessence+Hydra)
- [x] Done -- [Blast Zone](https://scryfall.com/search?q=Blast+Zone)
- [x] Done -- [Bleeding Edge](https://scryfall.com/search?q=Bleeding+Edge)
- [x] Done -- [Blindblast](https://scryfall.com/search?q=Blindblast)
- [x] Done -- [Bloom Hulk](https://scryfall.com/search?q=Bloom+Hulk)
- [x] Done -- [Bolas's Citadel](https://scryfall.com/search?q=Bolass+Citadel)
- [x] Done -- [Bolt Bend](https://scryfall.com/search?q=Bolt+Bend)
- [x] Done -- [Bond of Discipline](https://scryfall.com/search?q=Bond+of+Discipline)
- [x] Done -- [Bond of Flourishing](https://scryfall.com/search?q=Bond+of+Flourishing)
- [x] Done -- [Bond of Insight](https://scryfall.com/search?q=Bond+of+Insight)
- [x] Done -- [Bond of Passion](https://scryfall.com/search?q=Bond+of+Passion)
- [x] Done -- [Bond of Revival](https://scryfall.com/search?q=Bond+of+Revival)
- [x] Done -- [Bulwark Giant](https://scryfall.com/search?q=Bulwark+Giant)
- [x] Done -- [Burning Prophet](https://scryfall.com/search?q=Burning+Prophet)
- [x] Done -- [Callous Dismissal](https://scryfall.com/search?q=Callous+Dismissal)
- [x] Done -- [Casualties of War](https://scryfall.com/search?q=Casualties+of+War)
- [x] Done -- [Centaur Nurturer](https://scryfall.com/search?q=Centaur+Nurturer)
- [x] Done -- [Chainwhip Cyclops](https://scryfall.com/search?q=Chainwhip+Cyclops)
- [x] Done -- [Challenger Troll](https://scryfall.com/search?q=Challenger+Troll)
- [x] Done -- [Chandra's Pyrohelix](https://scryfall.com/search?q=Chandras+Pyrohelix)
- [x] Done -- [Chandra's Triumph](https://scryfall.com/search?q=Chandras+Triumph)
- [x] Done -- [Chandra, Fire Artisan](https://scryfall.com/search?q=Chandra,+Fire+Artisan)
- [x] Done -- [Charity Extractor](https://scryfall.com/search?q=Charity+Extractor)
- [x] Done -- [Charmed Stray](https://scryfall.com/search?q=Charmed+Stray)
- [x] Done -- [Command the Dreadhorde](https://scryfall.com/search?q=Command+the+Dreadhorde)
- [x] Done -- [Commence the Endgame](https://scryfall.com/search?q=Commence+the+Endgame)
- [x] Done -- [Contentious Plan](https://scryfall.com/search?q=Contentious+Plan)
- [x] Done -- [Courage in Crisis](https://scryfall.com/search?q=Courage+in+Crisis)
- [x] Done -- [Cruel Celebrant](https://scryfall.com/search?q=Cruel+Celebrant)
- [x] Done -- [Crush Dissent](https://scryfall.com/search?q=Crush+Dissent)
- [x] Done -- [Cyclops Electromancer](https://scryfall.com/search?q=Cyclops+Electromancer)
- [x] Done -- [Davriel's Shadowfugue](https://scryfall.com/search?q=Davriels+Shadowfugue)
- [x] Done -- [Davriel, Rogue Shadowmage](https://scryfall.com/search?q=Davriel,+Rogue+Shadowmage)
- [x] Done -- [Deathsprout](https://scryfall.com/search?q=Deathsprout)
- [x] Done -- [Defiant Strike](https://scryfall.com/search?q=Defiant+Strike)
- [x] Done -- [Deliver Unto Evil](https://scryfall.com/search?q=Deliver+Unto+Evil)
- [x] Done -- [Demolish](https://scryfall.com/search?q=Demolish)
- [x] Done -- [Despark](https://scryfall.com/search?q=Despark)
- [x] Done -- [Desperate Lunge](https://scryfall.com/search?q=Desperate+Lunge)
- [x] Done -- [Devouring Hellion](https://scryfall.com/search?q=Devouring+Hellion)
- [x] Done -- [Divine Arrow](https://scryfall.com/search?q=Divine+Arrow)
- [x] Done -- [Domri's Ambush](https://scryfall.com/search?q=Domris+Ambush)
- [x] Done -- [Domri, Anarch of Bolas](https://scryfall.com/search?q=Domri,+Anarch+of+Bolas)
- [x] Done -- [Dovin's Veto](https://scryfall.com/search?q=Dovins+Veto)
- [x] Done -- [Dovin, Hand of Control](https://scryfall.com/search?q=Dovin,+Hand+of+Control)
- [x] Done -- [Dreadhorde Arcanist](https://scryfall.com/search?q=Dreadhorde+Arcanist)
- [x] Done -- [Dreadhorde Butcher](https://scryfall.com/search?q=Dreadhorde+Butcher)
- [x] Done -- [Dreadhorde Invasion](https://scryfall.com/search?q=Dreadhorde+Invasion)
- [x] Done -- [Dreadhorde Twins](https://scryfall.com/search?q=Dreadhorde+Twins)
- [x] Done -- [Dreadmalkin](https://scryfall.com/search?q=Dreadmalkin)
- [x] Done -- [Duskmantle Operative](https://scryfall.com/search?q=Duskmantle+Operative)
- [x] Done -- [Elite Guardmage](https://scryfall.com/search?q=Elite+Guardmage)
- [x] Done -- [Emergence Zone](https://scryfall.com/search?q=Emergence+Zone)
- [x] Done -- [Enforcer Griffin](https://scryfall.com/search?q=Enforcer+Griffin)
- [x] Done -- [Enter the God-Eternals](https://scryfall.com/search?q=Enter+the+God-Eternals)
- [x] Done -- [Erratic Visionary](https://scryfall.com/search?q=Erratic+Visionary)
- [x] Done -- [Eternal Skylord](https://scryfall.com/search?q=Eternal+Skylord)
- [x] Done -- [Eternal Taskmaster](https://scryfall.com/search?q=Eternal+Taskmaster)
- [x] Done -- [Evolution Sage](https://scryfall.com/search?q=Evolution+Sage)
- [x] Done -- [Fblthp, the Lost](https://scryfall.com/search?q=Fblthp,+the+Lost)
- [x] Done -- [Feather, the Redeemed](https://scryfall.com/search?q=Feather,+the+Redeemed)
- [x] Done -- [Finale of Devastation](https://scryfall.com/search?q=Finale+of+Devastation)
- [x] Done -- [Finale of Eternity](https://scryfall.com/search?q=Finale+of+Eternity)
- [x] Done -- [Finale of Glory](https://scryfall.com/search?q=Finale+of+Glory)
- [x] Done -- [Finale of Revelation](https://scryfall.com/search?q=Finale+of+Revelation)
- [x] Done -- [Firemind Vessel](https://scryfall.com/search?q=Firemind+Vessel)
- [x] Done -- [Flux Channeler](https://scryfall.com/search?q=Flux+Channeler)
- [x] Done -- [Forced Landing](https://scryfall.com/search?q=Forced+Landing)
- [x] Done -- [Gateway Plaza](https://scryfall.com/search?q=Gateway+Plaza)
- [x] Done -- [Giant Growth](https://scryfall.com/search?q=Giant+Growth)
- [x] Done -- [Gideon Blackblade](https://scryfall.com/search?q=Gideon+Blackblade)
- [x] Done -- [Gideon's Battle Cry](https://scryfall.com/search?q=Gideons+Battle+Cry)
- [x] Done -- [Gideon's Company](https://scryfall.com/search?q=Gideons+Company)
- [x] Done -- [Gideon's Sacrifice](https://scryfall.com/search?q=Gideons+Sacrifice)
- [x] Done -- [Gideon's Triumph](https://scryfall.com/search?q=Gideons+Triumph)
- [x] Done -- [Gideon, the Oathsworn](https://scryfall.com/search?q=Gideon,+the+Oathsworn)
- [x] Done -- [Gleaming Overseer](https://scryfall.com/search?q=Gleaming+Overseer)
- [x] Done -- [Goblin Assailant](https://scryfall.com/search?q=Goblin+Assailant)
- [x] Done -- [Goblin Assault Team](https://scryfall.com/search?q=Goblin+Assault+Team)
- [x] Done -- [God-Eternal Bontu](https://scryfall.com/search?q=God-Eternal+Bontu)
- [x] Done -- [God-Eternal Oketra](https://scryfall.com/search?q=God-Eternal+Oketra)
- [x] Done -- [God-Eternal Rhonas](https://scryfall.com/search?q=God-Eternal+Rhonas)
- [x] Done -- [God-Pharaoh's Statue](https://scryfall.com/search?q=God-Pharaohs+Statue)
- [x] Done -- [Grateful Apparition](https://scryfall.com/search?q=Grateful+Apparition)
- [x] Done -- [Grim Initiate](https://scryfall.com/search?q=Grim+Initiate)
- [x] Done -- [Guild Globe](https://scryfall.com/search?q=Guild+Globe)
- [x] Done -- [Guildpact Informant](https://scryfall.com/search?q=Guildpact+Informant)
- [x] Done -- [Heartfire](https://scryfall.com/search?q=Heartfire)
- [x] Done -- [Heartwarming Redemption](https://scryfall.com/search?q=Heartwarming+Redemption)
- [x] Done -- [Herald of the Dreadhorde](https://scryfall.com/search?q=Herald+of+the+Dreadhorde)
- [x] Done -- [Honor the God-Pharaoh](https://scryfall.com/search?q=Honor+the+God-Pharaoh)
- [x] Done -- [Huatli's Raptor](https://scryfall.com/search?q=Huatlis+Raptor)
- [x] Done -- [Huatli, the Sun's Heart](https://scryfall.com/search?q=Huatli,+the+Suns+Heart)
- [x] Done -- [Ignite the Beacon](https://scryfall.com/search?q=Ignite+the+Beacon)
- [x] Done -- [Ilharg, the Raze-Boar](https://scryfall.com/search?q=Ilharg,+the+Raze-Boar)
- [x] Done -- [Interplanar Beacon](https://scryfall.com/search?q=Interplanar+Beacon)
- [x] Done -- [Invade the City](https://scryfall.com/search?q=Invade+the+City)
- [x] Done -- [Invading Manticore](https://scryfall.com/search?q=Invading+Manticore)
- [x] Done -- [Iron Bully](https://scryfall.com/search?q=Iron+Bully)
- [x] Done -- [Ironclad Krovod](https://scryfall.com/search?q=Ironclad+Krovod)
- [x] Done -- [Jace's Projection](https://scryfall.com/search?q=Jaces+Projection)
- [x] Done -- [Jace's Ruse](https://scryfall.com/search?q=Jaces+Ruse)
- [x] Done -- [Jace's Triumph](https://scryfall.com/search?q=Jaces+Triumph)
- [x] Done -- [Jace, Arcane Strategist](https://scryfall.com/search?q=Jace,+Arcane+Strategist)
- [x] Done -- [Jace, Wielder of Mysteries](https://scryfall.com/search?q=Jace,+Wielder+of+Mysteries)
- [x] Done -- [Jaya's Greeting](https://scryfall.com/search?q=Jayas+Greeting)
- [x] Done -- [Jaya, Venerated Firemage](https://scryfall.com/search?q=Jaya,+Venerated+Firemage)
- [x] Done -- [Jiang Yanggu, Wildcrafter](https://scryfall.com/search?q=Jiang+Yanggu,+Wildcrafter)
- [x] Done -- [Karn's Bastion](https://scryfall.com/search?q=Karns+Bastion)
- [x] Done -- [Karn, the Great Creator](https://scryfall.com/search?q=Karn,+the+Great+Creator)
- [x] Done -- [Kasmina's Transmutation](https://scryfall.com/search?q=Kasminas+Transmutation)
- [x] Done -- [Kasmina, Enigmatic Mentor](https://scryfall.com/search?q=Kasmina,+Enigmatic+Mentor)
- [x] Done -- [Kaya's Ghostform](https://scryfall.com/search?q=Kayas+Ghostform)
- [x] Done -- [Kaya, Bane of the Dead](https://scryfall.com/search?q=Kaya,+Bane+of+the+Dead)
- [x] Done -- [Kiora's Dambreaker](https://scryfall.com/search?q=Kioras+Dambreaker)
- [x] Done -- [Kiora, Behemoth Beckoner](https://scryfall.com/search?q=Kiora,+Behemoth+Beckoner)
- [x] Done -- [Kraul Stinger](https://scryfall.com/search?q=Kraul+Stinger)
- [x] Done -- [Krenko, Tin Street Kingpin](https://scryfall.com/search?q=Krenko,+Tin+Street+Kingpin)
- [x] Done -- [Kronch Wrangler](https://scryfall.com/search?q=Kronch+Wrangler)
- [x] Done -- [Law-Rune Enforcer](https://scryfall.com/search?q=Law-Rune+Enforcer)
- [x] Done -- [Lazotep Behemoth](https://scryfall.com/search?q=Lazotep+Behemoth)
- [x] Done -- [Lazotep Plating](https://scryfall.com/search?q=Lazotep+Plating)
- [x] Done -- [Lazotep Reaver](https://scryfall.com/search?q=Lazotep+Reaver)
- [x] Done -- [Leyline Prowler](https://scryfall.com/search?q=Leyline+Prowler)
- [x] Done -- [Liliana's Triumph](https://scryfall.com/search?q=Lilianas+Triumph)
- [x] Done -- [Liliana, Dreadhorde General](https://scryfall.com/search?q=Liliana,+Dreadhorde+General)
- [x] Done -- [Living Twister](https://scryfall.com/search?q=Living+Twister)
- [x] Done -- [Loxodon Sergeant](https://scryfall.com/search?q=Loxodon+Sergeant)
- [x] Done -- [Makeshift Battalion](https://scryfall.com/search?q=Makeshift+Battalion)
- [x] Done -- [Mana Geode](https://scryfall.com/search?q=Mana+Geode)
- [x] Done -- [Martyr for the Cause](https://scryfall.com/search?q=Martyr+for+the+Cause)
- [x] Done -- [Massacre Girl](https://scryfall.com/search?q=Massacre+Girl)
- [x] Done -- [Mayhem Devil](https://scryfall.com/search?q=Mayhem+Devil)
- [x] Done -- [Merfolk Skydiver](https://scryfall.com/search?q=Merfolk+Skydiver)
- [x] Done -- [Mizzium Tank](https://scryfall.com/search?q=Mizzium+Tank)
- [x] Done -- [Mobilized District](https://scryfall.com/search?q=Mobilized+District)
- [x] Done -- [Mowu, Loyal Companion](https://scryfall.com/search?q=Mowu,+Loyal+Companion)
- [x] Done -- [Naga Eternal](https://scryfall.com/search?q=Naga+Eternal)
- [x] Done -- [Nahiri's Stoneblades](https://scryfall.com/search?q=Nahiris+Stoneblades)
- [x] Done -- [Nahiri, Storm of Stone](https://scryfall.com/search?q=Nahiri,+Storm+of+Stone)
- [x] Done -- [Narset's Reversal](https://scryfall.com/search?q=Narsets+Reversal)
- [x] Done -- [Narset, Parter of Veils](https://scryfall.com/search?q=Narset,+Parter+of+Veils)
- [x] Done -- [Neheb, Dreadhorde Champion](https://scryfall.com/search?q=Neheb,+Dreadhorde+Champion)
- [x] Done -- [Neoform](https://scryfall.com/search?q=Neoform)
- [x] Done -- [New Horizons](https://scryfall.com/search?q=New+Horizons)
- [x] Done -- [Nicol Bolas, Dragon-God](https://scryfall.com/search?q=Nicol+Bolas,+Dragon-God)
- [x] Done -- [Nissa's Triumph](https://scryfall.com/search?q=Nissas+Triumph)
- [x] Done -- [Nissa, Who Shakes the World](https://scryfall.com/search?q=Nissa,+Who+Shakes+the+World)
- [x] Done -- [Niv-Mizzet Reborn](https://scryfall.com/search?q=Niv-Mizzet+Reborn)
- [x] Done -- [No Escape](https://scryfall.com/search?q=No+Escape)
- [x] Done -- [Oath of Kaya](https://scryfall.com/search?q=Oath+of+Kaya)
- [x] Done -- [Ob Nixilis's Cruelty](https://scryfall.com/search?q=Ob+Nixiliss+Cruelty)
- [x] Done -- [Ob Nixilis, the Hate-Twisted](https://scryfall.com/search?q=Ob+Nixilis,+the+Hate-Twisted)
- [x] Done -- [Orzhov Guildgate](https://scryfall.com/search?q=Orzhov+Guildgate)
- [x] Done -- [Paradise Druid](https://scryfall.com/search?q=Paradise+Druid)
- [x] Done -- [Parhelion II](https://scryfall.com/search?q=Parhelion+II)
- [x] Done -- [Planewide Celebration](https://scryfall.com/search?q=Planewide+Celebration)
- [x] Done -- [Pledge of Unity](https://scryfall.com/search?q=Pledge+of+Unity)
- [x] Done -- [Pollenbright Druid](https://scryfall.com/search?q=Pollenbright+Druid)
- [x] Done -- [Pouncing Lynx](https://scryfall.com/search?q=Pouncing+Lynx)
- [x] Done -- [Price of Betrayal](https://scryfall.com/search?q=Price+of+Betrayal)
- [x] Done -- [Primordial Wurm](https://scryfall.com/search?q=Primordial+Wurm)
- [x] Done -- [Prismite](https://scryfall.com/search?q=Prismite)
- [x] Done -- [Prison Realm](https://scryfall.com/search?q=Prison+Realm)
- [x] Done -- [Raging Kronch](https://scryfall.com/search?q=Raging+Kronch)
- [x] Done -- [Ral's Outburst](https://scryfall.com/search?q=Rals+Outburst)
- [x] Done -- [Ral, Storm Conduit](https://scryfall.com/search?q=Ral,+Storm+Conduit)
- [x] Done -- [Rally of Wings](https://scryfall.com/search?q=Rally+of+Wings)
- [x] Done -- [Ravnica at War](https://scryfall.com/search?q=Ravnica+at+War)
- [x] Done -- [Relentless Advance](https://scryfall.com/search?q=Relentless+Advance)
- [x] Done -- [Rescuer Sphinx](https://scryfall.com/search?q=Rescuer+Sphinx)
- [x] Done -- [Return to Nature](https://scryfall.com/search?q=Return+to+Nature)
- [x] Done -- [Rising Populace](https://scryfall.com/search?q=Rising+Populace)
- [x] Done -- [Roalesk, Apex Hybrid](https://scryfall.com/search?q=Roalesk,+Apex+Hybrid)
- [x] Done -- [Role Reversal](https://scryfall.com/search?q=Role+Reversal)
- [x] Done -- [Rubblebelt Rioters](https://scryfall.com/search?q=Rubblebelt+Rioters)
- [x] Done -- [Saheeli's Silverwing](https://scryfall.com/search?q=Saheelis+Silverwing)
- [x] Done -- [Saheeli, Sublime Artificer](https://scryfall.com/search?q=Saheeli,+Sublime+Artificer)
- [x] Done -- [Samut's Sprint](https://scryfall.com/search?q=Samuts+Sprint)
- [x] Done -- [Samut, Tyrant Smasher](https://scryfall.com/search?q=Samut,+Tyrant+Smasher)
- [x] Done -- [Sarkhan the Masterless](https://scryfall.com/search?q=Sarkhan+the+Masterless)
- [x] Done -- [Sarkhan's Catharsis](https://scryfall.com/search?q=Sarkhans+Catharsis)
- [x] Done -- [Shriekdiver](https://scryfall.com/search?q=Shriekdiver)
- [x] Done -- [Silent Submersible](https://scryfall.com/search?q=Silent+Submersible)
- [x] Done -- [Simic Guildgate](https://scryfall.com/search?q=Simic+Guildgate)
- [x] Done -- [Single Combat](https://scryfall.com/search?q=Single+Combat)
- [x] Done -- [Sky Theater Strix](https://scryfall.com/search?q=Sky+Theater+Strix)
- [x] Done -- [Snarespinner](https://scryfall.com/search?q=Snarespinner)
- [x] Done -- [Solar Blaze](https://scryfall.com/search?q=Solar+Blaze)
- [x] Done -- [Sorin's Thirst](https://scryfall.com/search?q=Sorins+Thirst)
- [x] Done -- [Sorin, Vengeful Bloodlord](https://scryfall.com/search?q=Sorin,+Vengeful+Bloodlord)
- [x] Done -- [Soul Diviner](https://scryfall.com/search?q=Soul+Diviner)
- [x] Done -- [Spark Harvest](https://scryfall.com/search?q=Spark+Harvest)
- [x] Done -- [Spark Reaper](https://scryfall.com/search?q=Spark+Reaper)
- [x] Done -- [Spellgorger Weird](https://scryfall.com/search?q=Spellgorger+Weird)
- [x] Done -- [Spellkeeper Weird](https://scryfall.com/search?q=Spellkeeper+Weird)
- [x] Done -- [Steady Aim](https://scryfall.com/search?q=Steady+Aim)
- [x] Done -- [Stealth Mission](https://scryfall.com/search?q=Stealth+Mission)
- [x] Done -- [Storm the Citadel](https://scryfall.com/search?q=Storm+the+Citadel)
- [x] Done -- [Storrev, Devkarin Lich](https://scryfall.com/search?q=Storrev,+Devkarin+Lich)
- [x] Done -- [Sunblade Angel](https://scryfall.com/search?q=Sunblade+Angel)
- [x] Done -- [Tamiyo's Epiphany](https://scryfall.com/search?q=Tamiyos+Epiphany)
- [x] Done -- [Tamiyo, Collector of Tales](https://scryfall.com/search?q=Tamiyo,+Collector+of+Tales)
- [x] Done -- [Teferi's Time Twist](https://scryfall.com/search?q=Teferis+Time+Twist)
- [x] Done -- [Teferi, Time Raveler](https://scryfall.com/search?q=Teferi,+Time+Raveler)
- [x] Done -- [Tenth District Legionnaire](https://scryfall.com/search?q=Tenth+District+Legionnaire)
- [x] Done -- [Teyo's Lightshield](https://scryfall.com/search?q=Teyos+Lightshield)
- [x] Done -- [Teyo, the Shieldmage](https://scryfall.com/search?q=Teyo,+the+Shieldmage)
- [x] Done -- [Tezzeret, Master of the Bridge](https://scryfall.com/search?q=Tezzeret,+Master+of+the+Bridge)
- [x] Done -- [The Elderspell](https://scryfall.com/search?q=The+Elderspell)
- [x] Done -- [The Wanderer](https://scryfall.com/search?q=The+Wanderer)
- [x] Done -- [Thunder Drake](https://scryfall.com/search?q=Thunder+Drake)
- [x] Done -- [Thundering Ceratok](https://scryfall.com/search?q=Thundering+Ceratok)
- [x] Done -- [Tibalt's Rager](https://scryfall.com/search?q=Tibalts+Rager)
- [x] Done -- [Tibalt, Rakish Instigator](https://scryfall.com/search?q=Tibalt,+Rakish+Instigator)
- [x] Done -- [Time Wipe](https://scryfall.com/search?q=Time+Wipe)
- [x] Done -- [Tithebearer Giant](https://scryfall.com/search?q=Tithebearer+Giant)
- [x] Done -- [Toll of the Invasion](https://scryfall.com/search?q=Toll+of+the+Invasion)
- [x] Done -- [Tolsimir, Friend to Wolves](https://scryfall.com/search?q=Tolsimir,+Friend+to+Wolves)
- [x] Done -- [Tomik, Distinguished Advokist](https://scryfall.com/search?q=Tomik,+Distinguished+Advokist)
- [x] Done -- [Topple the Statue](https://scryfall.com/search?q=Topple+the+Statue)
- [x] Done -- [Totally Lost](https://scryfall.com/search?q=Totally+Lost)
- [x] Done -- [Trusted Pegasus](https://scryfall.com/search?q=Trusted+Pegasus)
- [x] Done -- [Turret Ogre](https://scryfall.com/search?q=Turret+Ogre)
- [x] Done -- [Tyrant's Scorn](https://scryfall.com/search?q=Tyrants+Scorn)
- [x] Done -- [Ugin's Conjurant](https://scryfall.com/search?q=Ugins+Conjurant)
- [x] Done -- [Ugin, the Ineffable](https://scryfall.com/search?q=Ugin,+the+Ineffable)
- [x] Done -- [Unlikely Aid](https://scryfall.com/search?q=Unlikely+Aid)
- [x] Done -- [Vampire Opportunist](https://scryfall.com/search?q=Vampire+Opportunist)
- [x] Done -- [Vivien's Arkbow](https://scryfall.com/search?q=Viviens+Arkbow)
- [x] Done -- [Vivien's Grizzly](https://scryfall.com/search?q=Viviens+Grizzly)
- [x] Done -- [Vivien, Champion of the Wilds](https://scryfall.com/search?q=Vivien,+Champion+of+the+Wilds)
- [x] Done -- [Vizier of the Scorpion](https://scryfall.com/search?q=Vizier+of+the+Scorpion)
- [x] Done -- [Vraska's Finisher](https://scryfall.com/search?q=Vraskas+Finisher)
- [x] Done -- [Vraska, Swarm's Eminence](https://scryfall.com/search?q=Vraska,+Swarms+Eminence)
- [x] Done -- [Wall of Runes](https://scryfall.com/search?q=Wall+of+Runes)
- [x] Done -- [Wanderer's Strike](https://scryfall.com/search?q=Wanderers+Strike)
- [x] Done -- [War Screecher](https://scryfall.com/search?q=War+Screecher)
- [x] Done -- [Wardscale Crocodile](https://scryfall.com/search?q=Wardscale+Crocodile)
- [x] Done -- [Widespread Brutality](https://scryfall.com/search?q=Widespread+Brutality)
</details>

**Comment by theelk801** [comment]
# Implemented Cards

- [x] Done -- [Ajani's Pridemate](https://scryfall.com/search?q=Ajanis+Pridemate)

**Comment by theelk801** [comment]
-[ ] Update proliferate to increase all counters on a given rather than just one

**Comment by JayDi85** [comment]
* [ ] Interplanar Beacon works incorrectly. It allows you to add two mana in ANY COMBINATION of colours to be added to your mana pool. Instead of two mana of different colours (19 Mar 2018, Hoac, forum).
* [ ] Ignite the Beacon does not restrict the search to planeswalkers, you can search for any 2 cards you want at instant speed (19 Mar 2018, Hoac, forum).

**Comment by antoni-g** [comment]
Hi all,

I'm going to jump in and do:
[Centaur Nurturer](https://scryfall.com/search?q=Centaur+Nurturer)
[Contentious Plan](https://scryfall.com/card/war/46/contentious-plan)

**Comment by CCTV-1** [comment]
Awakening of Vitu-Ghazi convert land, then 10 +1/+1 counter in land,xmage display 5/5(build:19-04-13 03:28 )
![S5W7RQCXWZJ0HT ~@UA@MXU](https://user-images.githubusercontent.com/7350506/56258271-85d98f00-6101-11e9-94dc-9c2b85734e67.png)

**Comment by ninf-fct** [comment]
Feather seems to have a bug where it's ability is triggered even by spells controlled by the opponent if they target your creatures. This only seems to happen in a Feather mirror match.

**Comment by theelk801** [comment]
Thanks, I'll look into it

**Comment by CCTV-1** [comment]
in my turn `Gideon Blackblade` not is creature
can't cast `Gideon's Triumph`,this is exception message:
```
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.34V1.5 (build: 2019-04-18 12:55)
mage.cards.g.GideonsTriumphCondition.apply(GideonsTriumph.java:91)
mage.cards.g.GideonsTriumphCondition.apply(GideonsTriumph.java:85)
mage.filter.predicate.Predicates$AndPredicate.lambda$apply$0(Predicates.java:145)
java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
java.util.stream.AbstractPipeline.copyInto(Unknown Source)
java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
java.util.stream.AbstractPipeline.evaluate(Unknown Source)
java.util.stream.ReferencePipeline.allMatch(Unknown Source)
mage.filter.predicate.Predicates$AndPredicate.apply(Predicates.java:145)
mage.filter.FilterImpl.match(FilterImpl.java:38)
mage.game.permanent.Battlefield.lambda$countAll$0(Battlefield.java:63)
java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
java.util.Iterator.forEachRemaining(Unknown Source)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
java.util.stream.AbstractPipeline.copyInto(Unknown Source)
java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
java.util.stream.AbstractPipeline.evaluate(Unknown Source)
java.util.stream.LongPipeline.reduce(Unknown Source)
java.util.stream.LongPipeline.sum(Unknown Source)
java.util.stream.ReferencePipeline.count(Unknown Source)
mage.game.permanent.Battlefield.countAll(Battlefield.java:65)
mage.abilities.effects.common.SacrificeEffect.apply(SacrificeEffect.java:56)
mage.cards.g.GideonsTriumphEffect.apply(GideonsTriumph.java:81)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:176)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:166)
mage.game.stack.Spell.resolve(Spell.java:220)
mage.game.GameImpl.resolve(GameImpl.java:1319)
mage.game.GameImpl.playPriority(GameImpl.java:1269)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:850)
mage.game.GameImpl.play(GameImpl.java:759)
mage.game.GameImpl.start(GameImpl.java:723)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)
```

client version:`1.4.33.dev_2019-04-18_12-59`

**Comment by theelk801** [comment]
I'm pushing fixes for both of those, thanks

**Comment by antoni-g** [comment]
chiming in - grabbing Ugin's Conjurant and Finale of Devastation

**Comment by JayDi85** [comment]
Release notes:

https://magic.wizards.com/en/articles/archive/feature/war-spark-release-notes-2019-04-19

**Comment by messuped** [comment]
> Thanks, I'll look into it

I think I may have an idea on the Feather bug (since it just happened).

I was in an EDH game with 4 other people  and I had cast a cantrip with Feather out (so naturally, the trigger occurred). Then the blue player answered with Reality Shift on my other create (note, not Feather). At the end step, his cantrip was returned to his hand, and not mine. 

Maybe it is a fault on the way Feather chooses which cantrip to return to hand, picking the last card on the stack? Not sure, haven't studied Feather's code extensively.

**Comment by messuped** [comment]
> > Thanks, I'll look into it
> 
> I think I may have an idea on the Feather bug (since it just happened).
> 
> I was in an EDH game with 4 other people and I had cast a cantrip with Feather out (so naturally, the trigger occurred). Then the blue player answered with Reality Shift on my other creature (note, not Feather). At the end step, his cantrip was returned to his hand, and not mine.
> 
> Maybe it is a fault on the way Feather chooses which cantrip to return to hand, picking the last card on the stack? Not sure, haven't studied Feather's code extensively.

![image](https://user-images.githubusercontent.com/23510956/56476461-af8f0f00-648f-11e9-9e2b-fc5af04757ae.png)

This also happened on a turn Feather was in exile at the begining of the turn (she wasn't present for the casting of the five spells)

**Comment by JayDi85** [comment]
Bug reports from de-server about new cards added post above:
https://github.com/magefree/mage/issues/5662#issuecomment-480773122
