### ISSUE TITLE
v33 feedback and errors - old tasks

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5664]
Active bugs from v33 topic: #5529

Bugs:
 * [ ] Necropotence doesnt work on local EDH game - Necropotence doesnt work if u playing EDH commander on local server vs. Mad Computers. Im paying life for every card i wanna draw,but dont get the cards after the trigger resolves in my endstep. Only my hand gets empty. (w00x, 2019-01-25 00:29:53.32) 
* [ ] Desertion - if the spell is my commander dont aply put this card under your control (Thalo, 2019-01-27 02:08:26.172) 
* [ ] Treasure Nabber - treasure nabber still broken (igniteaxoim, 2019-02-01 22:28:57.98) 
* [ ] Mishra's Factory unable to be selected as a Blocker in current patch. It's animated and ready at select block step but it no longer allows you to select it, it'll just engage the factory activation window (reddit, ashent2)
* [ ] Praetor's Grasp and Mystic Remora bug? Praetor's Grasp is able to exile a card face down, but I am having trouble being able to play the card exiled with it. Mystic Remora doesn't draw a card upon failure to pay tax. (reddit, Exacerbated)
* [ ] Stony Silence - stony silence vs darksteel citadel, stony silence should not affect the land (X11, 2019-02-10 15:46:25.946) 
* [ ] Stony Silence - Stony Silence stops Darksteel Citadel from tapping for mana. It's a mana ability not an activated one (KamiTech, 2019-02-10 15:48:29.326) 
* [ ] Wild Evocation - Wild Evocation revealed Boom // Bust from a player hand in EDH, but the card wasn't cast (MrBourse, 2019-02-10 23:26:17.044) 
* [ ] Isochron Scepter - Isochron Scepter and Aetherflux Reservoir: translated from spain feedback:  the copies of the cetro isocrono have for a storm? I'm saying it because the spell counter adds the copies of the scepter as if it were a played spell. (whiteraven, 2019-02-11 03:11:50.119)
* [ ] Scapeshift - isn't working, I cast scapeshift with 7 lands in play, i searched for 5 mountains and 2 scapeshifts and it did zero damange. I believe it should trigger for 5 Mts enterning together. (fattrick13, 2019-02-12 01:00:10.602) 
* [ ] Urabrask the Hidden - Currently, creatures an opponent controls enter the battlefield tapped when they enter the battlefield at the same time as Urabrask the Hidden. This should not happen. (reddit, tim163)
* [ ] coco brought 10 cost ulamog into plaY - title (Raskunda, 2019-02-13 15:38:43.192)
* [ ] Gate Colossus - gate colossus exiled with thief of sanity gets owner's discount - player A's Gate Colossus exiled under player B's Thief of Sanity, player B can cast the gate colossus for reduced mana even if they own no gates (Ellsming, 2019-02-13 00:47:11.557) 
* [ ] Penny Dreadful out of date - hey, the penny dreadful filter is out of date. Thanks f or the good work! (00Raiz2, 2019-02-14 00:58:40.004) 
* [ ] Momentary Blink - Momentary Blink text says return under owner's control but it returned under caster's control. (LeoRedfire43, 2019-02-14 02:55:19.469) 
* [ ] Conqueror's Galleon - Conqueror's Galleon text says return under your control but returned under owner's control. (LeoRedfire43, 2019-02-14 02:55:19.469) 
* [ ] Meren of Clan Nel Toth - Meren doesn't track experience counters and will let me put card from the graveyard into my hand (Sandman, 2019-02-17 03:50:01.656) 
* [ ] "Ignore" feature on chat doesn't work - I added a few users to my ignore list in the chat yet I still see their messages. (JHard, 2019-02-17 06:22:04.352) 
* [ ] Magus of the Moon - tapped lands should enter untapped (humblegreek, 2019-02-17 21:47:35.302) 
* [ ] Standard Bearer - i was in a pauper game. On battlefield it have Standard bearer and when my opponents cast their spells on it because he have to target it, the Spell fizzle and goes to graveyard without dealing damage.  it happen 3 time. It was in the main phase always (Caracole, 2019-02-17 23:00:22.021) 
* [ ] Reckless Bushwhacker - ETB problems - I put a Reckless Buhwhacker on the battlefield, and when its ETB abbility was on the stack, the oppent burned him. But as the burn when after the abbilty on the stack, it killed the creature and the ETB abillity did not resolve. Thanks, (DomPedroII, 2019-02-17 23:00:29.268) 
 * [ ] Leaving Tables - When a player concedes it should mark them as passing priority (to not get the table hung up waiting for them).  It should also get rid of my PHASE buttons and chancge the CONCEDE button to LEAVE TABLE. (CrutchSapper, 2019-01-19 01:36:36.359) 
* [ ] Phantasmal Image - phantasmal image isn't effected by the legend rule even when coppied creature is legendary and under the same control (MuyBien, 2019-02-17 23:40:20.051) 
* [ ] Triton Tactics - i was playing a modern game where i was on tron and my opp was on amulet titan. one of the turns i attacked with a wurmcoil and a world breaker he casted triton tactics on a trinket mage and a plat created by one of his lands, he then proceed to block with the plant to my wurm, after the attacks the plant died. [Logs and more info](https://www.reddit.com/r/XMage/comments/arpm8e/triton_tactics_bug/) (reddit, DarkEneas);
* [ ] Urabrask the Hidden - Currently, creatures an opponent controls enter the battlefield tapped when they enter the battlefield at the same time as Urabrask the Hidden. This should not happen. ([reddit, tim163](https://www.reddit.com/r/XMage/comments/aqukad/bug_urabrask_the_hidden/));
* [ ] Deck Editor: if you draft, and when yorue at deckbuilder, if you pick up cards on your mouse to move them, but press the add lands button and add lands, the cards on your mouse dissapears from your list of cards. And you cant get em back. Lost 14 nonbasic lands that way a few days ago when i drafted, felt good (vincent);
* [  ] Death-Mask Duplicant - idk whats happening (just watching ) but one guy is having a total meltdown because it seems to be getting put into his hand whenever he casts it or something and he thinks its cheating lmao (discord, A Drunk Human);
 * [ ] AI: The computer like to tap/untap Basalt Monolith during the instant phase of combat and it doesn't stop. (BrassAngel42)
* [ ] Issue with image downloading - Image downloading function stops with around a thousand cards still missing, and won't download any more cards after that. (Athena, 2019-02-07 23:36:17.881) 
* [ ] Lags - waiting 5-7 minute each player's turn.... wow xmage what is the bad service. (fmbgames, 2019-02-12 01:38:50.217)
* [ ] Lags - App has been sloooow since update 2 weeks ago - Ever since an update made to this app about a couple weeks ago, i've experienced a LOT of extra slowness when playing in xmage.  I have an iMac.  I always keep up-to-date with the latest update. (paladisiac, 2019-02-12 21:23:13.634)

Feature requested:
* [ ] Land Image Download - How about an option to download only lands. Lots of players like to use lands from the UN sets but not the cards (Scapegoat_Tom, 2019-01-26 21:17:58.349) 
* [ ] Planechase Images - I would really like to be able to see the images of the Planes for  Planechase games. (CrutchSapper, 2019-01-28 17:31:43.672) 
* [ ] new way to set stop point - https://imgchr.com/i/kUrG4J left click set stop only once,right click always stop at that step,and use different color to show them. (spphins, 2019-02-10 05:34:56.518) 
* [ ] Priority Audible Alert - Can you make it an option that when I have priority in a game that I can hear a ticking sound to let me know that I have priority and that everyone is waiting on me. (CrutchSapper, 2019-02-10 23:57:56.096) 
* [ ] Graveyard display - I would like to have the graveyard displayd to me like other zones, IE; Command Zone, Exile Instead of how it is now, please and thank you. (CrutchSapper, 2019-02-11 04:00:39.018) 
* [ ] Missing card "Equinox" - There is a white enchament from the legends set named Equinox that is not available (Knighthawke, 2019-02-12 04:34:05.692) 
* [ ] Trigger orders choose - Muliple amulet of Vigor triggers on the stack - whenever I click an ability to resolve first on the stack, it puts the others on the stack without letting me choose their order. [More info and discussion](https://www.reddit.com/r/XMage/comments/ar97lh/muliple_amulet_of_vigor_triggers_on_the_stack/) (reddit, TheBloxlord);

**Comment by ingmargoudt** [comment]
https://blogs.magicjudges.org/rulestips/tag/darksteel-citadel/

Stony Silence does shutdown Darksteel Citadel.

**Comment by Rewyn** [comment]
> Scapeshift - isn't working, I cast scapeshift with 7 lands in play, i searched for 5 mountains and 2 scapeshifts and it did zero damange. I believe it should trigger for 5 Mts enterning together. (fattrick13, 2019-02-12 01:00:10.602)
Assuming this is meant with valakut on the field (or searched via scapeshift); not a bug. Valakut triggers only for each further mountain beyond 5. So each mountain entering the battlefield has to see 5 other mountains for valakut to trigger.
