### ISSUE TITLE
Feedback XMage Version 1.4.36V2

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5859]
Cards and abilities:
* [x] Minor Oathbreaker tweaks - According to Oathbreaker rules, Signature Spell can never go anywhere but the stack or the command zone. This is not the case in XMage client.
Also, the prompt asks about "returning your commander to command zone", which is mildly confusing. (Mazeura, 2019-06-08 14:23:21) 
* [x] Planewide Celebration not working - Card from War of the Spark "Planewide Celebration" doesn't work properly. It lets the player choose one thing and just once. (Mazeura, 2019-06-08 14:24:06) 
* [ ] Collision // Colossus from command zone - There's been a problem with playing a split card from command zone in oathbreaker - it doesn't let you pick the mode, instead asking you to pay for both halves at the same time. (Mazeura, 2019-06-08 15:05:34)
* [x] Seasoned pyromancer - seasoned pyromancer is bugged, it makes you discard your hand and redraw 2, then creates as many tokens as your hand was, instead of making you discard just 2. (Yoloswaggins, 2019-06-08 17:19:33) 
* [x] Seasoned Pyromancer - It makes you discard your whole hand and not just 2 cards (james5265, 2019-06-08 17:36:27) 
* [x] Seasoned Pyromancer - Game doesn't resolve etb trigger properly when player has exactly one card in hand (Bob49, 2019-06-08 20:21:58) 
* [x] Seasoned Pyromancer - It makes you discard your whole hand instead of just two (Biest, 2019-06-09 01:01:44) 
* [x] Seasoned Pyromancer - whenever you play seasoned pyro it forces you to discard your entire hand (DogPolice, 2019-06-09 07:39:10) 
* [x] Seasoned Pyromancer - Tried to play Seasoned Pyromancer with 1 card in hand, wouldn't let me select only 1 card to discard. Seems like a bug as that is legal. (alphabet_sam, 2019-06-10 03:41:45) 
* [x] Seasond Pyromancer - is not working - when you play the card you must discard your whole hand if you have more than 2 cards, but if you have 1 card you cant do anything, not even concede (kole99, 2019-06-10 20:21:39) 
* [x] Seasoned Pyromancer - is not working - Hi, the card seasoned pyromancer is not working at all. If i have no cards to discard from the etb trigger i cannot proceed. If i have more than 2 cards in hand i have to discard whole hand. Please fix. Thank you (smarties1, 2019-06-10 22:34:58) 
* [x] Seasoned Pyromancer - Seasoned Pyromancer forces you to discard your whole hand instead of just two cards. (ChickenGod, 2019-06-11 10:36:28) 
* [x] Seasoned Pyromancer - Playing against my friend her seasoned pyromancer made her discard 4 cards and then she only drew two cards. She was not able to discard fewer than 4 cards but the card says discard 2 on it. (Enoikay, 2019-06-11 19:41:20) 
* [x] Seasoned pyromancer - I cast seasoned pyromancer with 6 cards in hand. It forced me to select all 6 cards to discard, then made 6 elemental tokens and drew me 2 cards. (alana, 2019-06-11 20:33:04) 
* [x] Seasoned pyromancer - Seasoned pyromancer ETB ability made me discard 3 cards instead of 2 (Nery, 2019-06-11 20:57:54) 
* [x] Seasoned PYromancer Glitch - I cast seasoned pyromancer with only one card in hand and the game asked me to discard 2. So the game was not able to proceed, after several minutes I lost the game for atempting to drawing  from empty library(!?) which was not empty (Nery, 2019-06-11 21:46:26) 
* [x] Seasoned Pyromancer bug - When my seasoned pyromancer enters the battle field the triggered ability is supposed to allow me to choose which 2 cards to discard. Instead Xmage forces me to discard my entire hand. Please fix where I can only discard the 2. Thanks! (blueXmage, 2019-06-12 07:21:04) 
* [x] Seasoned Pyromancer works wrong - You have to discard your entire hand. (AculAlHazred, 2019-06-12 16:09:45) 
* [x] Seasoned Pyromancer must discard 3 cards, not 2 as the text written. - Seasoned Pyromancer must discard 3 cards, not 2 as the text written. (Nek, 2019-06-12 17:01:19) 
* [x] Seasoned Pyromancer - Forces me to discard 3 cards and also rewards me with 3 elementals (KLT, 2019-06-12 22:45:19) 
* [x] seasoned pyromancer bug - Seasoned Pyromancer makes you discard 3 instead of 2 cards (MadMoses, 2019-06-12 22:45:29) 
* [x] Seasoned Pyromancer is bugged - When you only have 1 card in hand, the abilitie doesn't resolve, it makes you choose 2, and you cant cancel, even you only have one. I also used it once with 3 cards in hand and had to discard all 3 (zulado, 2019-06-21 06:51:03)
* [x] seasoned pyromancer - seasoned pyromancer forces you to discard your whole hand and if you don't have at least 2 cards the client gets stuck (Raagh, 2019-06-18 23:36:45) 
* [x] Seasoned Pyromancer freezes match - Seasoned Pyromancer has no done button, so if you have less than 2 cards in hand, it freezes the game. If you have more than 2, you have to discard entire hand (ChiefDrana, 2019-06-18 06:02:29) 
* [x] Seasoned Pyromancer is BUGGED - Seasoned pyromancer doesnt let you continue through the discard if you have 1 card in hand and if you have more than two it forces you to discard your hand thank you for your time (Pyronic, 2019-06-17 09:17:54) 
* [x] seasoned pyromancer bug - if pyro enters the battlefield and you have only one card in hand, xmage 
wants you to select a second one. so you can do nothing as close the program. (Schlaubi, 2019-06-16 18:22:29) 
* [x] Seasonned Pyromancer fix - Hello, I see the card is fexed in github ... can you release PLEASE ! Thx (Gros19, 2019-06-14 15:44:57) 
* [x] seasoned pyromance bug - Seasoneed Pyromancer is supposed to discard two or less cards, but instead forces you to discard your hand then gives you more than 2 creatures if you have enough nonlands. (ChiefDrana, 2019-06-14 05:31:25) 
* [x] Seasonned Pyromancer - Pyro blast doesn't work from the command zone - Please fix. (appleatingoat1, 2019-06-21 02:56:06) 
* [ ] First Sliver - there is a bug with the cascade abilty it triggers more then once and goes all the way down to 0 cnc (Brozo, 2019-06-08 17:16:44) 
* [ ] Llanowar elves - Well it says tap to add a tree. it doesn't work. (belhaj7, 2019-06-08 20:14:41) 
* [ ] Tutoring problem - It appears that players can't tutor/search libraries for cards, at least in Commander games. (callmeonions, 2019-06-09 02:13:30) 
* [ ] Double-faced Cards - My double-faced cards don't have images, e.g. Delver of Secrets, Garruk Relentless, Hanweir Battlements. The problem is not confined to specific sets. (callmeonions, 2019-06-09 02:19:20) 
* [x] Ephemerate - Ephemerate returns creature tapped when it is rebound. The text doesnt say that (The_Examiner, 2019-06-10 02:04:24) 
* [x] Ephemerate - Ephemerate returned Twin Silk Spider tapped instead of untapped (twice) (MadMoses, 2019-06-11 22:54:29) 
* [x] Ephemerate returns creatures tapped - Ephemerate card exiles and returns creatures, but does so
tapped, so they can't blocked. This is incorrect. (Squeeq, 2019-06-13 09:00:46) 
* [x] Ephemerate bug - ephemerate ... the4 creature enters tapped :/ (satiro_bcn, 2019-06-12 21:17:18) 
* [x] ephemerate makes creature tapped - ephemerate makes creature tapped (quod, 2019-06-17 18:04:47) 
* [x] Ephemerate is bugged - Ephemerate is not working properly. When you target a tapped creature, it re-enters the battlefield tapped. (Neopard, 2019-06-17 21:25:21) 
* [ ] polluted delta - Don't give my swamp when i activate the hability (BichoX, 2019-06-10 07:23:17) 
* [x] Buyback - The BUYBACK of Recruite the worthy doesn't work. - The BUYBACK of Recruite the worthy doesn't work. It doesn't not return to hand, but goes to graveyard instead. (Nek, 2019-06-10 09:33:26) 
* [x] Buyback - imminent resolution - Buyback on cards like Costant Mists or Capsize doesn't work (Uomocondor, 2019-06-10 22:31:09) 
* [x] Buyback - FIX BUYBACK, THE CARD GOES TO GRAVE INSTEAD IN HAND (Uomocondor, 2019-06-11 12:36:12) 
* [x] Buyback - Recruit the Worthy buyback doesn't work - buyback doesn't work even if cost is paid (Electro, 2019-06-12 01:39:06) 
* [x] Buyback - not working - Hi!, buyback doesnt sem to work anymore. the card goes to the yard. Greetings (anelintruder, 2019-06-18 21:06:10) 
* [x] Buyback - Recruit the Worthy Buyback bugged - Recruit the Worthy doesn't buyback when paid for (NaturalOrderer, 2019-06-16 00:58:37) 
* [x] Buyback - buyback does not work (ggbruno, 2019-06-13 16:50:47) 
* [x] Buyback - When you cast a spell with Buyback...the spell go to gravyard. (Baurong1, 2019-06-13 05:34:20) 
* [ ] Splice Ability of Splicer's Skill doesn't work. - Splice Ability of Splicer's Skill doesn't work. (Nek, 2019-06-10 14:20:26) 
* [ ] unsettled mariner doesnt work with abilities? - Unsettled Mariner did not trigger its extra cost ability when liliana used her minus ability to make me sacrifice a creature. (Dextinite, 2019-06-11 02:35:19) 
* [ ] Oathbreaker - Affinity cost reduction Oathbreaker Signiture Spell Tax - When using Thoughtcast as my signiture spell in oathbreaker affinity should reduce the cost. The way costs are calculated in magic is Additional costs first, then discounts then trinisphere. Thus affinity cuts through additional costs. (GrimTutor, 2019-06-11 07:56:57) 
* [x] Oathbreaker - i've noticed a lot of bugs with the oathbreaker signature spells, whenever a card has several modes or options it bugs out, only allowing the first mode and once (Telandril, 2019-06-16 06:24:26) 
* [ ] Mirari - Mirari's triggered ability seems to be bugged (Brozo, 2019-06-11 08:46:53) 
* [ ] unwind - i could counter Vampiric Tutor with my unwind i had the lands untapped (Brozo, 2019-06-11 09:15:42) 
* [x] Unbound Flourishing is bugged - Unbound Flourishing copied my Cyclonic Rift, which it should not do. (Jumpstick, 2019-06-11 18:49:17) 
* [x] Unbound flourshing - copies ponder... (ss22, 2019-06-12 13:13:08) 
* [x] Unbound flourishing bug - Somehow the card [Unbound Flourishing] copied [Bond of Flourishing], it could also copy other sorceries, but my error appeared with this two (Amigurumi, 2019-06-15 07:13:04) 
* [ ] Ninjutsu wrong combat step - I can activate Ninjutsu before blockers are declared. (KLT, 2019-06-11 22:57:15) 
* [ ] dack fayden artifact creature bug - when gaining control of an artifact creature using Dack Fayden's -2 abbility, the creature will not be able to attack even though it was cast before. (1sanchez, 2019-06-11 23:14:58) 
* [ ] Unsettled Mariner not triggering abilities? - Unsettled mariner does not work with abilities? did not work on field of ruin activation or liliana of the veil - activation. (Dextinite, 2019-06-12 01:47:12) 
* [ ] Suspend - Suspend spells NEED to be checked. I used Rift Bolt, took time counter off, and was unable to cast it (jsant1, 2019-06-21 04:42:51) 
* [ ] Archmage's Charm doesn't counter spell. - Archmage's Charm doesn't counter creature spell. It enters the battlefield as the Charm doesn't work. (Nek, 2019-06-12 19:21:35) 
* [ ] Quakefoot Cyclops - Wrongly implemented, when cast, up to two target creatures can't block instead of only one (KLT, 2019-06-12 22:51:29) 
* [ ] Quakefoot Cyclops Bug - Quakefoot Cyclops makes only 1 creature unable to block instead of 2 (when cast) (MadMoses, 2019-06-12 22:51:57) 
* [ ] Silent Gravestone - Silent Gravestone seems to be previnting you from casting Faithless Looting from your graveyard but this shouldn't be the case. (binnet, 2019-06-13 05:21:37) 
* [ ] Goad - Goad doesn't work right in multiplayer. Its specifies that the goaded creature has to attack a player other than you, but currently you can get round it by attacking a planeswalker. This shouldn't be able to happen since it specifies player. (Magonkio, 2019-06-13 15:11:52) 
* [ ] Lava dart flashback - The flashback mechanic on lava dart doesn't work properly, it only allows to flashback once when instead it should be as many times as mountains you have available. 
Thanks for all the games dough, cheers. (Karnitas, 2019-06-14 08:19:41) 
* [ ] Thousand Year Storm is bugged - Whenever I have TYS on the battlefield, it doesn't allow me to copy my instants and sorceries. Tested over several games, including attempts to roll back. (MarksmanSnir, 2019-06-14 14:52:21) 
* [ ] Watcher for Tomorrow - The card thats hidden under Watcher is NOT put in your hand when he's exiled (e.g. Felidar Guardian/Restoration Angel flicker), though he says "When Watcher LEAVES the battlefield...". (Bierbacke, 2019-06-15 11:17:25) 
* [ ] Meddling mage / aether vial - When you put a meddling mage into play off of aether vial its lets you name a card but doesnt keep the name on the mage. (Liam, 2019-06-15 12:25:19) 
* [ ] Brass herald draws all cards - It doesnt seem to care about creature types at all, it drew me both a cabal coffers and a etchings of the chosen along 2cards of the chosen type (Deadlylama, 2019-06-15 23:08:54) 
* [ ] blood moon problem - https://gatherer.wizards.com/pages/card/Details.aspx?multiverseid=83008 i just tell a lot time but u don't want listen, blood moon prevent effect on lands befor it will be applicate (Il_Barba, 2019-06-16 02:39:08) 
* [ ] Training Grounds interaction - Traning grounds suppose to help creatures, but it actually affects lands too. FOr example, with training grounds on the table, I can activate cabal coffers for only 1 mana. (SkifterOk, 2019-06-16 21:33:17) 
* [ ] Card Return w/ Feather - Targeted an opponent's creature with "Murder" while Feather was on the field. Opponent cast indestructible spell on their creature and it returned "Murder" to my hand instead of fizzling. (scottymandingo, 2019-06-17 00:14:48) 
* [ ] Varchild and changelings (impostor of the six pride) - Somehow varchild steals changelings without leaving battlefield It happen in a FFA with the mentioned card but i suspect it could affect other changelings (Amigurumi, 2019-06-17 16:14:40) 
* [ ] varchild, just varchild - i thought at first it was a bug of the changelings, but it seem the problem its the commander varchild, once it leaves battlefield once, the sttealing effect becomes permanent, so no one can play changeling without losing them (Amigurumi, 2019-06-17 16:19:07) 
* [ ] changeling and essence sliver - i attack with a changeling titan and another player controller an Essence sliver and it's him that get the life (Genshii, 2019-06-18 04:28:05) 
* [ ] lure of prey - in multiplayer in my deck will make all spells uncastable (EmrakulPorn, 2019-06-19 08:28:11) 
* [ ] Yixlid Jailer bug - I think there's a bug with Yixlid Jailer - if I return a creature from my graveyard when Yixlid Jailer was on the battlefield that creature becomes uncastable and still doesn't have any abilities in my hand. (Varondus, 2019-06-19 16:51:38) 
* [ ] Aminatou isn't working - In particular Aminatou the Fate Shifter and Aminatou's Augury haven't been working. Aminatou's Augury isn't letting you vsdt the spells you exile with it. Aminatou herself isn't able to blink herself using her second loyalty ability (Skaespeare, 2019-06-21 03:01:32) 

Gameplay and UI:
* [ ] Add a tab for pauper - The pauper games keep appearing on every tab, why dont they have their own tab? (rtol, 2019-06-09 09:20:01) 
* [ ] Amount of games avilable - Game type tabs could have numbers next to them telling us, how many games can be joined. (rtol, 2019-06-09 09:21:27) 
* [ ] new vintage cube? - Is the current Vintage Cube on MTGO slated to be added? (WhiskeyBurned, 2019-06-09 12:27:38) 
* [x] Snowlands randomly added to draft - Adding lands to the draft deck can still randomly add snow basics from older sets. I got 2 Coldsnap snowlands when adding lands from random sets. (GrimStrider, 2019-06-10 11:39:28) 
* [ ] Cleanup Step Prevents Timeout - My opponent failed with their gimmick deck and has been sitting at the cleanup step with 52 cards in hand for 12 minutes. They should have timed out after 5. (GrimTutor, 2019-06-12 00:31:17) 
* [ ] Kick button - We need a "/kick" vote function. some players will wait 4 and a half minutes before doing anything just to mess up free for all games. (QuoVadis, 2019-06-12 11:14:35) 
* [ ] laggg - wow this is a joke... lag as f*** all day it's no fun to play (fmbgames, 2019-06-14 03:54:52) 
* [ ] rollback cancel skip - if someone does any rollback - cancel all skips! (HoesT, 2019-06-14 08:57:47) 
* [x] Incorrect Pints list - Fatbond is no longer a point in Canadian Highlander. Please decrease it to 0. (Nookie, 2019-06-15 20:11:47) 
* [ ] Drawing a lot of lands only have 19 in deck and drew 14, its not possible in 60 cards.. do something. (EternalMaster, 2019-06-15 20:12:38) 
* [ ] Mass Stack Ordering - When casting X cost spells where they need to order the same trigger 500+ times, why not condense a player's triggers of the same card to a single trigger with a counter on it? (ThePalePhoenix, 2019-06-18 08:06:04) 
* [ ] Can only activate the first ability of lands - I have the bug recently where i cant use abilitys of Lands but the first one. If it does more than one mana, i cant add the 2nd color into my pool, i cant make Manlands to creatures, i cant give my creatures +1+2 with pendelhaven and so on. (LinkXNess, 2019-06-18 22:50:31) 
* [ ] Chat idea - As I am reading chat, it will jump to the most recent post. This becomes annoying as I may be trying to talk to someone in particualr, or am reading an arguement. Is there a way to not have that 'jump' effect? (Popalofiti, 2019-06-19 14:38:22) 
* [ ] Add a friends list - xMage is really cool as free MTGO, and I love it. I'd love to see a buddy system (or Notify list like IRC) for friends. (cocohead781, 2019-06-20 07:30:58) 
* [ ] Reconnect to games when you close client and enter back in. - When you close the client and reconnect if the game you were in is still ongoing you should be reconnected to the game. Useful for when xmage bugs out, such as with image overlapping,to reset and continue longer games such as commander. (CursedCatch3r, 2019-06-20 07:43:04) 
* [ ] goldfish mode - when testing a new deck having a goldfish mode w/out waiting 4 an opponent would be great for practicing combo decks (shroudmaster, 2019-06-20 10:39:26) 
* [ ] Touch Screen Support - Please consider adding tablet support. I can not double tap cards in draft with touch. I also thing that "hold" will bring up a menu either. (XMage, 2019-06-21 04:02:53)
