### ISSUE TITLE
Feedback XMage Version 1.4.36V3

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5873]
Cards requests:
* [ ] Heat wave and lava burst - Please add those two cards.By the way great job for all this hard work (neowillow, 2019-06-23 23:08:17) 
* [ ] Grenzo's Rebuttal - Card is not in the game (Daucro, 2019-06-22 07:31:47)

Other:
* [ ] Connection - Tournaments bugged - Hi, Unfortunately, all tournaments and drafts I played in the last two days didn't work well, they all crashed at some point.Would be cool, if you could fix this, I love Xmage for this feature! (Beerslayer, 2019-06-23 11:31:50) 
* [ ] Auto-login - Reporting loggin problem - When you create a new user in the server, if you select automatic loggin, if theres's a problem creating the user, the program crush when you start the program and it try to autoconnect and the user notexist (BichoX, 2019-06-23 23:52:17) 
* [x] Game modes - daze is banned in pauper :/ - people continue playing daze... (satiro_bcn, 2019-06-24 18:37:26) 
* [x] Games - i add guys to my ignore list and can join in rooms i create :/ (satiro_bcn, 2019-06-24 18:59:27) **JayDi85: that's ok, new settings apply for new created game**
* [x] Deck editor - Import only imports 385 cards of 450 card cube - I tried to import Aaron's cube, but it consistently only imports 385 cards. The excluded cards appear to be random, e.g. Brainstorm. (Miryafa, 2019-06-25 04:55:34) 
* [ ] Closing of exile window - Please enable it that i can close the exile window if i want to. I can reopen it on like the graveyard if i want to. In a 4 Player game these windows start to be annoying. Otherwise thank you for making magic available for free and also for mac :-* (Chri, 2019-06-27 22:02:21)
* [ ] A friends system - I think that this program would improve if it had some sort of friends system. Telling you whether they are online or not. (Kwantumphysix, 2019-06-29 21:17:06) 
* [x] continus ddos - how is possible all time i try to win a game server crash immidiatly, all time, and when i lose game is perfect. isn't possible, opponent ddos me (Il_Barba, 2019-06-30 04:17:10) **JayDi85: nope, you can't be ddosed, BUT your opponent can close client and make disconnect/freeze for some cards**
* [ ] notification - What the f* is up with this. The game NEVER notifies me when my game starts. no sound. no noise. no pop up message no nothing. Only when I time out. so annoying. (OgounBadagris, 2019-06-30 19:06:03) 
* [x] probe is not banned?? - probe is not banned?? (quod, 2019-06-30 21:27:23) 

Ability bugs:
* [ ] things not properly leaving the battlefield - when creatures leave the battlefield and come back instantly the game treats it liked they didn't really leave. (OgounBadagris, 2019-06-26 17:18:09) 
* [ ] cat wasn't a sliver - I had that green sliver out that makes it so slivers get +1/+1 when damaging an opponent. I attacked with him and a cat. I played that red spell that gives everyone +2/+0 and all creature types. My cat was not bloked. But he didn't get a +1/+1 counter. (OgounBadagris, 2019-06-29 12:24:16) 

Card bugs:
* [ ] Hivestone on Vehicles - Hivestone has a static effect that make all creatures into slives. That is also the case when you crew vehicles. Can you please fix it so it works (RandomGuy, 2019-06-23 07:54:27) 
* [ ] Blood Moon - About enter the battelfield land and blood moon - When blood moon is on board normaly you can play your ravland untap whithout paying 2 life. Ithinks it will be cool to fix that. Thank you  PS: Xmage is so cool thank you (Bassaris, 2019-06-23 11:32:34) 
* [ ] Blood Moon Chromatic Lantern - My non basic lands are mountains, but I can't tap them for any color besides red, despite haveing a chromatic lantern.  The chromatic lantern came into play first (djmarder, 2019-06-25 16:59:08) 
* [ ] Essence sliver broken - When a sliver deals damage while essence sliver is on the battlefield, the controller of essence sliver gains the life as opposed to the controller of the sliver that dealt the damage. This is wrong. (DerpHaven, 2019-06-23 16:54:32) 
* [ ] Crypt Rats - i cant resp himself to hability of crypt rats... sometimes to kill a young wolf i need crypt rats of 2, and i resp myself crypt rats of 1 before rats dies... and can't XD (satiro_bcn, 2019-06-24 18:22:04) 
* [ ] Yixlid Jailer - The Yixlid Jailer static effect never goes away, even after Jailer dies. (Ikashy73, 2019-06-24 20:59:54) 
* [ ] Yixlid Jailer works incorrectly with reanimation spelss - I cast Unearth targeting Seasoned Pyromancer with a Yixlid Jailer in play, but didnt get the Pyromancer's ETB trigger. This is a bug as Jailer only affaects cards when they are on the battle field (RosettaStoned, 2019-06-25 16:29:52) 
* [ ] Expropriate - Expropriate spell hangs the game. Plz fix (raja, 2019-06-25 15:04:49) 
* [ ] Soulherder - Soulherder is supposed to be another target creature, right now it can exile itself. Also it gets a +1/+1 counter when it exiles itself. (Handofemrakul, 2019-06-26 00:57:23) 
* [ ] Soulherder - watcher for tomorrow/soulherder bug - The 2 Modern Horizon cards Soulherder or watcher for tomorrow are bugged... when you try to flicker watcher for tommorow end of turn with soulherder, you dont get the card exiled under it! (RespectTheCat, 2019-06-27 16:41:44) 
* [x] Boiling Earth - Can't play Boiling Earth without awaken... :( (Bonilla, 2019-06-26 05:35:08) 
* [ ] Star Wars removal - The SWS set removal spell that costs BB and kills anything that costs less than 4 has been bugged for months. can't target anything (OgounBadagris, 2019-06-27 13:21:32)
* [ ] Nature's will - Doesn't tap attacked opponents lands when damage is dealth (djmarder, 2019-06-28 17:02:17) 
* [x] Wretched gryff - i wants play wretched gryff with 5 lands and 2 wall of rots without emerge cost, paying 7... and i can't... mandatory emerge :/ (satiro_bcn, 2019-06-30 13:40:45)
