### ISSUE TITLE
Feedback XMage Version 1.4.37V0

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5876]
Abilities:
* [ ] cards that make creatures other types - When you crew a vehicle it is a creature and if you have the cards Conspiracy, Arcane Adaptation, Xenograft, or Hivestone. The vehicles are also suppose to become the chosen creature types. please fix it so it works that way (RandomGuy, 2019-07-02 06:56:53) 
* [ ] clues - THere is a possibility that clues break the game. It does not happen all the time but sometimes. (Lunar, 2019-07-01 16:08:34) 

Cards:
* [x] chandra, doesn't sacrifice tokens - the 3 mana one (DOTA_TATA, 2019-07-01 05:03:10) 
* [x] chandra acolyte - she doesnt sac her elementals at end of turn (yaba777, 2019-07-01 18:45:46) 
* [x] chandras embercat - chandras embercat isnt letting its mana be used for my opponent to play the new 4 drop chandra. not sure if this is just that chandra or if its all of them (yaba777, 2019-07-01 18:52:08) 
* [x] Chandra, Acolyte of Flame tokens won't disappear - Chandra, Acolyte of Flame from Core 2020 +0 ability to spawn 2 1/1 elementals does not sacrifice them at end of turn (Electro, 2019-07-02 09:11:34) 
* [ ] Mystic Forge und Lotus Bloom - Cant cast a Lotus Bloom on top with Mystic Forge (Kalli, 2019-07-01 11:17:01) 
* [ ] chandra - bug chandra and repeted reverberation - chandra, aweken inferno's emble does not work and repeted reverberation does not clone pw acqivation (Zepherus, 2019-07-02 10:23:41) 
* [ ] Aminatou's Augury. Cant cast exiled spells (raja, 2019-07-01 11:36:55) 
* [ ] Flood of tears - Flood of tears does not work at all (Zepherus, 2019-07-01 12:20:56) 
* [ ] Blood moon - Blood moon still is not corect, fast lands and shock lands still come in tapped. (binnet, 2019-07-01 14:32:46) 
* [ ] watcher of tomorrow broken - playing inalla commander, cast watcher of tomorrow, make make copy of watcher using inalla's ability, hideaway, when turn ends, token exiles, shouldmtrigger watchers delayed trigger fails. tried several times. same result. (EvicereLeiden, 2019-07-01 18:47:32)
* [ ] Gargos, Vicious Watcher - Gargos, Vicious Watcher trigger doesn't work when I cast Growth Cycle on creature I control (LastBreath, 2019-07-01 19:20:18) 
* [x] woodland champion + ferocious pup and no counter +1+1... lol (satiro_bcn, 2019-07-01 20:06:50) 
* [ ] leyline of combustion - leyline of combustion is only suppose to activate if an opponent targets you or a permanent but it hurts you when you target one of your creatures (yaba777, 2019-07-01 20:57:50) 
* [ ] leyline bug - played gift of paradise on a land while leyline of combustion was out. It damaged me for 2, despite not being a spell or ability an OPPONENT controls. (Zox, 2019-07-02 01:45:11) 
* [ ] Soulbound - Creatures with soulbound dont ask you to make a new bound  when a new creature is coming into play (when they are bound to another creature) I have checked Gatherer and it should work the way i am saying (rtol, 2019-07-01 21:46:11) 
* [ ] Jeering Homunculus - Jeering Homunculus has incomplete card text (DerLhurgoyf, 2019-07-01 22:01:40) 
* [ ] Gonti-ed morph creature asks owner - Opponent played Gonti and stole a face-down card from my deck, Which happened to be a morph creature. When he tried to cast it the game would ask me if I wanted to play it as face down morph instead of him. (DerLhurgoyf, 2019-07-01 23:24:09)

Other:
* [ ] 2019 vintage cube keeps freezing during draft in between packs - (300 characters max) (WhiskeyBurned, 2019-07-01 18:19:23) 
* [ ] notifications - The game only notifies me when I time out from a match, not when a game starts. This is really f'ing annoying. Is there any way to fix this? (OgounBadagris, 2019-07-01 19:41:23)

**Comment by siyiye** [comment]
“Convolute” no effect

**Comment by Alex-Vasile** [comment]
"Lotus Bloom and Mystic Forge - I can still not cast a Lotus Bloom on top with Mystic Forge (Kalli, 2019-07-09 09:52:02)"

Is this a bug? Lotus Bloom has no mana cost, and so you can only cast it using it's suspend ability. but suspend can only be used if the card's in your hand.

**Comment by awjackson** [comment]
No, it's not a bug.
