### ISSUE TITLE
Feedback XMage Version 1.4.38

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6003]
Cards:
* **v0**
* [ ] Blood Moon - Blood moon still not working corrctly, see updated rules on how it interacts with lands that come in tapped, like shocks etc. They should just come in untapped with no possibility of paying life etc. (binnet, 2019-09-13 03:53:50) 
* [ ] Genesis Wave - It skips the choice permanent part directly to the put into gravyard. Its like mill X (NeverThwTwelve, 2019-09-21 17:08:27) 
* [ ] Gift of doom - Gift of doom does not morph correctly (Zepherus, 2019-09-13 00:37:03) 
* [ ] Korvold breaks commander games i think - so i'm trying to play my commander deck xith korvold as the general but the game freezes for everyone after one library is shuffled 
* [ ] Oko - Okos first ability does omething else (rtol, 2019-09-14 13:57:49) 
* [ ] Oko, thief of Crowns is bugged - Okos first ability has the wrong cost. Its +2 and not -X (JanG44, 2019-09-23 17:00:24) 
* [ ] Protean Hydra and -1/-1 counters - When you put a -1/-1 counter on Protean Hydra it doesn't trigger its second ability (JohnLemon, 2019-09-17 09:25:04) 
* [ ] Sevinne - Casting a spell with sevinne inplay is impossible and resets the turn (Sciurus, 2019-09-21 14:51:04) 
* [ ] Sevinne - Problem with Sevinne and flashback spells - Ive been playtesting Sevinne recently in EDH games, and the game bugs out when i use certain flashback spells. (TurdFerguson, 2019-09-19 05:18:39) 
* [ ] Sevinne - needs to be fixed - When you play Sevinne, the Chronoclasm the game breaks when you cast from other zones than hand and targeting sometimes breaks the game as well so this card is completly unplayable. (Lunar, 2019-09-14 14:04:38) 
* [ ] Shriekhorn - The text on Shriekhorn is very weird. (rolfmtg, 2019-09-14 16:54:00) 
* [ ] Stoneforge mystic tutor - I was using stoneforge and i could find a batterskull on my deck, only Jitte's. (Juaum000, 2019-09-25 00:21:17) 
* [ ] Toxic Deluge BUG - Sometimes, toxic deluge wont ask me to pay X and just destroy everything on the battlefield without even making me loose life (nikopol, 2019-09-19 19:51:09) 
* [ ] Training grounds reduces the cost of activation of everything, lands artifacts etc... instead of just creatures Thanks ! (nikopol, 2019-09-19 18:42:32) 
* [ ] Unsettled mariner does not prevent field of ruin.... (X11, 2019-09-22 13:39:22) 
* [ ] Watcher for Tomorrow bug - Hi. I send this message to you because the stack abillity from the named card which allows to put the exiled card in hand doesn't work for me, so I wonder if you could say me if it's actually a bug. I wait for your answer. (Mellro, 2019-09-23 20:20:07) 
* [ ] Watcher for Tomorrow does not give you the cards if you use a flicker card that targets him since he doesn't "leave the battlefield" in the client. (JGamer, 2019-09-15 08:54:19) 
* [ ] Watcher of toomorrow - trigger bug - Watcher of toomorrow doesn't trigger with efemerate  you can t get the card face down in hand (khenshoth, 2019-09-15 00:31:17) 
* [x] Hunt the Weak wrong art - Hunt the Weak for IMA uses the artwork for Hunting Pack instead of Hunt the Weak. (JesterFlows, 2019-09-11 03:41:44)
* [x] Piper of the Swarm - Hello, Piper of the Swarm is not +1+1 to rats. its rats have manace. Both text and abillity are incorrect in the game. thx. (FirstBornEvil, 2019-09-14 16:35:13) 
* [x] Rayami - rayami doesnt work. creatures dont get exiled (crud, 2019-09-10 22:08:13) 
* [x] Rayami doesn't exile creatures - Rayami's exile ability doesnt work (mininine, 2019-09-10 06:44:03) 
* [x] Rayami not implemented correctly - Rayami doesn't exile cards with blood counters on them as intended (TheMessinger47, 2019-09-14 16:17:06) 
* [x] Rayami, First of the Fallen - Rayami's exile part doesnt work most of the time, the only time i worked was when he also died (mininine, 2019-09-10 07:04:59) 
* [x] Syr Konrad Making Games Not Start - When games start and Syr Konrad is in anyones deck the game will never start. Hangs for a second and then back to lobbies. (MoralityShift, 2019-09-11 10:03:24) 
the new cards in the deck are korvold arcane signet and syr konrad, anyway thank for the app keep the good work going ^^ (gd172, 2019-09-11 01:38:08) 

Others:
* **v0**
* [ ] New mode - Partial Paris mulligan - In my playgroup we use the partial paris mulligan aka Commander mulligan. Would be great if you implement it. (myrrdin, 2019-09-11 19:05:20) 
* [ ] Canadian Highlander - CanLander Points Bug - Gilt-Leaf Palace is showing as 2 points when attempting to start a Canadian Highlander game. (Nookie, 2019-09-12 10:45:06) 
* [x] Ignore list - Please, activate or repair ignore list - please fix the issue of the "ignore list" ... IT DOES NOT WORK. I have people on the ignore list and they can enter the games that I created ... and if they don't want to leave you can't throw them out or do anything ... it's quite frustrating (satiro_bcn, 2019-09-12 21:42:33) **JayDi85: new added users wil be applied on new games, not exists**
* [x] Images - downloading images - i cant finish downloading token images. https://i.imgur.com/r4LOpXI.gifv (FxyO, 2019-09-13 02:21:16) ** JayDi85: old tokens is not downloadable in current version, put [that zip file](http://xmage.today/X/TOK.zip) to xmage/mage-client/plugins/images/TOK.zip , restart xmage and re-download latest images from scryfall**
* [x] Premodern - Banlist Update - Hi guys, there has been a recent unbanning of frantic search in premodern. maybe you can adress this in a fututre update. appreciated! thank you and goodbye (hiqualityh2o, 2019-09-14 11:16:52) 
* [x] Premodern - Banned/Unbanned - On August 20th Yawgmoth's Bargain got banned and Frantic Search got unbanned in Premodern format (SKELETAH666, 2019-09-16 22:00:38) 
* [x] Upload an avatar? - The ability to upload our own avatars? Or just add more? Planeswalkers for instance. That would also require the ability to report an avatar in case it's inappropriate (ThanosThMadMan, 2019-09-20 10:35:55) **JayDi85: no upload will be available, but cards as avatars possible in the feature**
* [x] Audio - Fix Audio Bug pls - While having Xmage fullscreen, Discord overlay does not push audio to my wireless headset. minimizing the xmage client or windowing it allows the audio to be released without issue. Not sure if this is an Xmage bug or an discord bug. (Dyslexis961, 2019-09-21 05:55:23) **JayDi85: that's [discord feature/bug](https://support.discordapp.com/hc/en-us/community/posts/360047135171-Screen-Sharing-Fullscreen-Applications), not xmage bug**

**Comment by Opchip** [comment]
Merchant of the Vale // Haggle missing from the game.


![java_mNRxAqpQZP](https://user-images.githubusercontent.com/56376469/66535711-c519f300-eb1a-11e9-9bb4-9e6b1c58688c.png)

**Comment by Jayguy6** [comment]
Genesis Wave now causes game to crash if x=8 or more.
