### ISSUE TITLE
Feedback XMage Version 1.4.39

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6075]
Bug reports from September to November 2019.

Cards:
* [ ] Ayara bug - Ayara (from the new set) triggered when my bolas cidadel ETB (Spartan117, 2019-10-21 06:28:30) 
* [ ] Ayara's enchantment trigger - Ayara triggers her ability when enchantments enter the battlefield (tilleruez, 2019-10-06 19:40:45) 
* [ ] Ayara, First of Lochtwain - I have been experiencing issues with Ayara, First of Lochtwain triggering off of any black permanent (MacroMade, 2019-10-27 10:04:46) 
* [ ] Ayara, First of Lochtwain - In a game, I had Ayara, First of Lochtwain on the battlefield and I resolved a Leyline of the Void which then triggered my Ayara, First of Lochtwain, draining my opponent for 1. (MacroMade, 2019-10-27 08:47:16) 
* [ ] Ayara, first of locthwain - triggers on black enchantments (du7ch, 2019-10-22 04:56:41) 
* [ ] Blood Moon updates - Check the gatherer updates and the Ixalan Comprehensive rules upate to blood moon (Tasigoyf, 2019-09-28 06:08:14) 
* [ ] Blood Moon/Magus of the Moon bugged - Blood Moon effects are bugged. ETB tapped lands shouldn't enter tapped under a Blood Moon effect but they do on XMage. (JHard, 2019-11-03 23:53:43) 
* [ ] Brass herald puts all cards revealed into hand - seems like it doesnt put them on the bottom if they dont fit the creature type (Deadlylama, 2019-10-24 15:24:14) 
* [ ] Brazen Borrower missing - Brazen Borrower ELD (39) missing (aNdV, 2019-10-01 16:29:13) 
* [ ] Bridge from below - Problem - I`ve been having the same issue with Leyline of the Void, and bridge from below been on my graveyard, if a creature dies, bridge from below is exiled even if the creature is been exile instead. a good few times I had the same issue. (CrazyMonkey, 2019-10-22 00:20:25) 
* [ ] Burning Earth - The opponents Burning Earth unrightly triggered twice when I activated my Cavern of Souls for mana. It's only supposed to trigger one time. (sethery94, 2019-10-11 23:40:02) 
* [ ] Clever impersonator -  Copying flip side doesn't work - Clever impersonator fails to copy back side of Awoken Horror (LebronJames, 2019-11-21 20:56:24) 
* [ ] Curious Pair - Curious Pair is currently missing. in Throne of Eldraine (Atmosphere, 2019-10-11 07:19:02) 
* [ ] Deafening silence - The eldraine card does not work as the text reads. It permits opponents to cast more than one non-creature spell as if the enchantment was not on the battlefield. (Peripheral72, 2019-10-18 20:18:32) 
* [ ] Deathless Knight trigger bug - There is currently a bug where gaining life causes Deathless Knight to trigger in any zone, not just the graveyard. Seems like an easy fix. (GhostOfKings, 2019-10-09 04:41:11) 
* [ ] Deathless knight bug - deathless knight triggers on lifegain while it is in the sideboard (Tooxie, 2019-10-04 22:53:33) 
* [ ] Deathless knight triggers on battlefield(Biest, 2019-09-28 18:44:51) 
* [ ] Deathless knigt - effect is announced, even when card is in sideboard (X11, 2019-09-29 17:06:45) 
* [ ] Dregde - Bug - opponent reanimates my golgari grave troll with his animate dead. troll died immediately und goes back to my graveyard. at my turn, i couldnt dregde the troll. on the turn of my opppnent, he was able to dredge with my troll in my graveyard... thx. (onkelon2, 2019-11-10 17:16:23) 
* [ ] Elkin Lair BUG - Elkin Lair only allows the caster to cast his spells not all players (jameswindsfury, 2019-10-21 19:20:28) 
* [ ] Embercleave - Wrong Oracletext -  The Oracletext that appears on mouseover says "...first strike.." but Embercleave gives double strike, just like shown in the image. (myrrdin, 2019-11-24 12:26:47) 
* [ ] Embercleave Oracle text is wrong - Hey there. I noticed that Embercleave's oracle text says first strike instead of double strike. By the way keep up the good work, really apreciate being able to play in Xmage (Karnitas, 2019-11-18 00:48:50) 
* [ ] Empowerd autogenerator - its not working fine, i fet way too much counters. i should get 1 per taping this artifact, but im getting way more. pls check that, thanks (Blackkusa, 2019-10-18 17:43:03) 
* [ ] Empowered Autogenerator - This card is so broken I dont know how it passed testing? (GhostOfKings, 2019-10-10 14:25:19) 
* [ ] Empowered autogenerator - Hello XMage Team, The autogenerator in its current state gets way too many counters. I think now it is getting a counter for every phase it is  untapped plus one for tapping it.Thx (ThedeadSettler, 2019-11-02 18:14:28) 
* [ ] Empowered autogenerator bug - Empowered autogenerator would randomly start to generate charge counters for no reason (Lightslayer247, 2019-11-10 02:49:27) 
* [ ] Emry, Lurker of the Loch - Hey guys! So far it doesn`t work to cast an artifact out of the graveyard with the new Emry. Thanks for your work! Cheers! Oliver (Phunkgeraet, 2019-09-28 09:41:51) 
* [ ] Enduring Ideal is bugged - After casting enduring ideal and selecting an enchantment, the selected enchantment does not come into play.  This only happens when it is first cast, it works fine every upkeep after. (Scrafted, 2019-10-14 16:31:50) 
* [ ] Erayo, Soratami Ascendant + Rollback EDH - When destroying the Creature Erayo while the Flip is on stack and rolling back the Action in EDH, Erayo is in your Graveyard and in the Commandzone afterwards (xxldoener, 2019-11-17 11:37:13) 
* [ ] Exodskeletal armor - doesnt count all cards in all graveyards (avatarofwoah, 2019-10-19 17:42:12) 
* [ ] Expropriate - Not work when choose money. (Walterly, 2019-10-10 19:21:57) 
* [ ] Expropriate - the car expropriate is bugged when the opponent has to chose for time or money. (r33v3r, 2019-11-15 21:20:06) 
* [ ] Fabled Passage is bugged - Fabled Passage doesn't work on XMage the way is supposed to. It's supposed to put the land into play tapped, then untap it. But it just puts it into play already untapped. This difference is relevant for cards like Amulket of Vigor. (JHard, 2019-11-05 22:04:11) 
* [ ] Fires of invention - needs a fix, it's avoiding commander tax. (vampiredraco, 2019-11-04 06:52:35) 
* [ ] Firesong and sunspear - Triggers too often with Lifelink from R/W spells (Biest, 2019-11-03 02:17:19) 
* [ ] Giant killer ELD adventure not working - giant killer ELD adventure not working (ProBonoGigolo, 2019-10-16 20:12:48) 
* [ ] Goad - please fix goad - goad doesn't work correctly in 1v1. It should force a creature to attack you but it currently doesn't. Thank you for all that you do! (durianstorm, 2019-10-14 03:56:51) 
* [ ] Improbable Alliance - Improbable Alliance is buggy (angelbabe, 2019-10-28 06:29:44) 
* [ ] Improbable Alliance - doesnt work with tomebound lich, if i have 1 faerie onto the battlefield, second doesnt appears (n0m4d, 2019-10-04 07:42:21) 
* [ ] Improbable Alliance - it only triggers once (breadlord, 2019-10-27 18:48:15) 
* [ ] Improbable Alliance Bug - Improbable Alliance isn't making tokens with Fevered Visions, and sometimes other cards that draw during your opponents turn of on end step. (PariahHS, 2019-11-11 15:37:48) 
* [ ] Improbable Alliance does not trigger every time - Improbable Alliance did not trigger of cycling or idol of oblivion activations (Biest, 2019-10-19 21:27:09) 
* [ ] Incubation Druid bug - When you have Nykthdos on the battlefield, Incubation Druid can produce colorless mana. Colorless is not a color. (Pandapip1, 2019-11-28 22:52:00) 
* [ ] Irencrag Pyromancer - Untriggered triggers - Drawing my 2nd card per turn off of Tome Raider did not trigger either my Irencrag Pyromancer of Mad Ratter in ELD sealed (1Drakos1, 2019-10-11 05:02:14) 
* [ ] Irencrag Pyromancer bug - Irencrag Pyromancer seems to be doing nothing (breadlord, 2019-10-26 23:13:39) 
* [ ] Kenrith - the last  of Kenrith ability does'nt work thanks (sidman, 2019-10-11 22:22:59)
* [ ] Kenrith bug - Kenrith's last ability seems buged, it says "target creature gains  life" Thanks for all the amazing work!!! (nikopol, 2019-10-13 23:32:20) 
* [ ] Kenrith's black ability - Kenrith's black ability is not rightly implemented (JohnLemon, 2019-11-01 11:54:04) 
* [ ] Kenrith's black ability error - Kenrith's black ability is wrong, it says "target creature gains 5 life" and the real one is "Put target creature card from a graveyard onto the battlefield under its owner’s control." (DaniPorter, 2019-11-05 23:54:35) 
* [ ] Kenrith, the Returned King - His 5th ability, '4B: Target creature card gains 5 life.' is broken as fuck. (Chewbaklava, 2019-11-05 03:02:53) 
* [ ] Kenrith, the Returned King's 5th ability does not work - Kenrith, the Returned King's 5th ability does not work (Chewbaklava, 2019-10-15 00:36:28) 
* [ ] Kess and Fire/Ice - When you cast fire/ice from your graverayr with kess it doesn't exile it self (WeeZy, 2019-10-06 18:31:56) 
* [ ] K´rrik card is not available - (nerox283, 2019-10-12 10:04:01) 
* [ ] Leadership Vacuum resets the board - Leadership vacuum resets the turn uppon resolve (Sciurus, 2019-10-01 18:36:41) 
* [ ] Lochmere bug - hello lochemere dont exile 5 cards in opponent graveyeard, bug in ELD card (Matc2, 2019-10-18 23:36:38) 
* [ ] Lost Legion - Does not trigger the scry effect. (Daemonic, 2019-10-11 18:46:09) 
* [ ] Maginatic Core - Hexproof creature seems to break Maginatic Core. Hexproof creature is only creature on the battlefield. It is stuck asking me to select a creature and I can only repeatedly click Done. (XMage, 2019-10-19 04:19:56) 
* [ ] Mantle of Tides does not trigger from drawing second card with opt - Mantle of Tides attached to a creature did not trigger from second card drawn with opt on my turn (Engwar, 2019-10-16 10:29:53) 
* [ ] Marisi, Bereaker of chains - opponent can cast during combat (avatarofwoah, 2019-10-19 17:41:42) 
* [ ] Master of Cruelties - Master of Cruelties currently sets the life to 1 even if it is blocked (Bob49, 2019-11-11 22:03:36) 
* [ ] Mindblade Render draws more than one card per turn - You can trigger Mindblade render off each warrior you control. It should be capped at one card per combat step. (Chewbaklava, 2019-11-08 06:41:36) 
* [ ] Morbid triggered all game for Malicious Affliction (GracefulDave, 2019-10-21 02:04:22) 
* [ ] NICOL BOLA DRAGON GOD - on +1, opened a windown and i can't select a card and had to concede (bentira, 2019-11-05 13:42:37) 
* [ ] Nightmare glitch - When saccing a nightmare creature with its ability on the stack, the game glitches and resets the boardstate to how it was at the start of the turn (durianstorm, 2019-10-21 01:34:15) 
* [ ] Oakhame adversary - oakhame adversary cant be cast for the reduced casting cast cost (LibbOx, 2019-09-28 06:14:17) 
* [ ] Oko bug - When oko turns artifact into elk it shouldn't keep artifact type but it does. (androsss, 2019-11-19 09:53:20) 
* [ ] Oko targeting a morph - I targeted my opponent's morph with Oko's +1 and it didn't turn into a green creature, it was still colorless. Relevant for Noxious Grasp targeting it. (psychospam90, 2019-10-30 23:57:14) 
* [ ] Once Upon a Time is bugged - I was on the draw and mulliganed to 6. My opponent played a land and passed, I drew for turn and then tried to cast Once Upon a Time for free and it wouldn't let me. It only gave me the option to cast if for 1G. (JHard, 2019-11-02 21:56:48) 
* [ ] Panopticon Plane broken - When on the Panopticon plane in Planechase, players don't draw the extra card on their draw step. (JayRed, 2019-11-04 06:06:02) 
* [ ] Patorn of the Moon bugged - Patron is bugged when trying to cast for offering. The client wont take into consideration the discount in manacost when offering a moonfolk. Fix, please as I'm using it as my commander, thanks. (RosettaStoned, 2019-10-26 19:54:03) 
* [ ] Pramikon + goad - So if you pramikon then goad someone to the opposite way they are soft locked and cat take any action past declare attackers. (Sexy, 2019-10-17 12:56:06) 
* [ ] Psychosis Crawler - i fpund a bug - i play day undoing with psychosis crawler in play and don't trigger his hability when i draw my seven cards. Thanks (BichoX, 2019-10-02 03:46:17) 
* [ ] Questing Beast - bug interaction Questing beast and TNN - Already 3 times today I've had a bug with questing beast and true name nemesis. QB prevents dmg from being prevented, but my opp will decide to block with TNN. when they do, the game freezes. Please fix bug. (Silv4n4s2, 2019-10-27 23:47:57) 
* [ ] Ramos bug with Sisay Weatherlight Captain - When Ramos sees Sisay cast, Ramos adds 5 +1/+1 counters when it should only add 1 (Lightslayer247, 2019-10-16 18:08:48) 
* [ ] Rare in Legions - Legions packs do not have rares in Richman draft (XMage, 2019-11-25 05:46:32) 
* [ ] Rogue Skycaptain causes a server error on cast - as above, causes an error message and rolls back the cast (Deadlylama, 2019-10-24 15:11:40) 
* [ ] Scourge of the throne - I played scourge of the throne on edh, kept attacking the player with the most life but the ability on the scourge (additional battlephase) didnt trigger (rafikus, 2019-10-03 00:38:20) 
* [ ] Sevinne's Reclamation flashback not working - Hello dear XMage development team, when you flashback Sevinne's Reclamation, the second copy of the spell does not work properly, it does not return the targeted card to the battlefield. tested twice and both times failed. Thank you! (JanErik, 2019-10-01 15:12:27) 
* [ ] Sorceress Queen - card change soon but ability still activated (xilim3, 2019-10-31 19:56:52) 
* [ ] Stoneforge mystic didn't work quite right - With Leonin Arbiter in Play, put Stoneforge Mystic in play. Said I couldnt search library even though I have 2 lands available. (Gozerfish15, 2019-10-27 05:10:06) 
* [ ] The Wanderer is bugged - Noncombat damage from Bond of Passion passed through with The Wanderer on the battlefield. (Neopard, 2019-10-20 23:22:27) 
* [ ] Tome of Legends - Tome of Legends currently triggers whenever any commander enters play, not just yours (Bob49, 2019-11-04 18:28:45) 
* [ ] Tome of Legends Bug - Tome of Legends currently adds a counter whenever a commander is played or attacks, instead of just your commander (Ameliarate, 2019-11-16 01:55:56) 
* [ ] Tome of Legends Bugged - Tome of Legends triggers on every commander, not just "your" commander, as it reads on the card. (IrishMidgetMan, 2019-11-16 01:58:24) 
* [ ] Tome of legends isnt working right - a page counter is added whenever any commander etb or attacks, not just mine (Mox_Cardboard, 2019-11-16 01:55:15) 
* [ ] Tooth// Nail - I think the entwine on this card is currently bugged. lets me search library, but then after i select a creature card, nothing happens and it goes to the graveyard with neither effect (TrueXenocide, 2019-09-30 01:42:04) 
* [ ] Vesuva comes into play untapped whilst copying shockland - vesuva comes into play untapped whilst copying shockland (quod, 2019-10-19 18:06:28) 
* [ ] Vesuvan Shapeshifter - incorrect interaction - Vesuvan Shapeshifter is unable to copy creatures with hexproof.  The ability of Vesuvan Shapeshifter does not target and should be able to get around hexproof. (madman384, 2019-11-25 02:57:56) 
* [ ] Vivian, Arkbow unable to +1 without creature - Vivian should be able to +1 without targeting a creature (Electro, 2019-09-30 04:43:18) 
* [ ] War's Toll - Text of the second part is wrong. It shouldn't say and trigger on: attacks you (FuryOfFungus, 2019-10-26 18:35:47) 
* [ ] Watcher for Tomorrow - The Modern Horizons 1 card Watcher for tomorrow does not work as intended. It has hideaway, and does not put the facedown card into your hand when watcher for tomorrow leaves the battlefield. Please fix this. (Peripheral72, 2019-10-18 20:20:06) 
* [ ] Watcher for Tomorrow - Watcher for Tomorrow doesn't give you the cards from exile when you blink it with ephemerate. (Meke, 2019-10-04 00:34:07) 
* [ ] Watcher for Tomorrow Bug - Hi, Watcher of Tomorrow does not work correctly (at least the ephemerate interaction). I somehow have not gotten the exiled card back in my hand. Thank you and best Regards (Steggen, 2019-10-31 16:55:37) 
* [ ] Watcher for Tomorrow bug - When Watcher for Tomorrow leaves the battlefield the face down card does not go to hand. (BodofChrist, 2019-10-17 05:16:37) 
* [ ] Watcher for tomorrow BUGGED WHEN BLINKED - Watcher for tomorrow doesn't return the face down exiled card when blinked. The trigger goes on the stack, resolves, and does nothing. Please Fix (Chewbaklava, 2019-10-18 08:48:12) 
* [ ] Watcher of tomorrow - Bugged when blinking it (pepelotazo, 2019-11-15 02:46:01) 
* [ ] Watcher of tomorrow - Watcher of tomorrow not working when been blicked by any source, like ephemerate or soulherder, still working if dies blocking. Could you please fix that? Regards Pepe (pepelotazo, 2019-11-07 01:28:13) 
* [ ] Yixlid jailer's ability lasts forever - yixlid jailer's ability lasts forever (quod, 2019-11-15 10:39:16) 
* [ ] Kenrith ability bug - the new Kenrith has his final 5cmc ability coded incorrectly and it affects his ability to be a commander. (reddwind, 2019-11-03 01:46:37) 
* [ ] Varchild - varchild died, then next turn i played an irregular cohort and varchild's controller instantly gained control of it. the triggered token entered on varchild's side too. tried rollbacking, same thing happened (LibbOx, 2019-10-06 18:18:14) 
* [x] Irencrag Pyromancer - Draw second card - Faerie Vandal and Irencrag Pyromancer only seem to trigger once a game (Train, 2019-11-07 02:09:10) 
* [x] Irencrag Pyromancer - Irencrag Pyromancer not triggering correctly (Trautacular, 2019-09-29 19:55:37) 
* [x] Irencrag Pyromancer - Irencrag pyromancer stops triggering after its first or second trigger. (Levitathe, 2019-10-04 11:44:28) 
* [x] Irencrag Pyromancer and  Improbable Alliance - I was playing a new standard deck with Irencrag Pyromancer and  Improbable Alliance. The triggers of the cards do not appear to be working all the time (GiddyGoat, 2019-10-07 13:25:22) 
* [x] Irencrag pyromancer - not working properly (igniteaxoim, 2019-11-27 05:08:11) 
* [x] Rankle (ELD) bug - hello, revie Rankle, the abiity creature is choose all ability, not any abiliti. (Matc2, 2019-10-14 20:18:34) 
* [x] Rankle - Rankle does not let me stop choosing modes (rtol, 2019-09-29 20:57:33) 
* [x] Rankle bug - Rankle master of pranks makes you choose all three modes. There is no done option like on similar cards like collective brutality. (JasonK1, 2019-10-27 22:52:06) 
* [x] Rankle bug - When i deal damage with rankle i cannot choose "cancel" option (gumba, 2019-09-29 18:13:42) 
* [x] Rankle still does not work (rtol, 2019-10-08 22:03:36) 
* [x] Rankle what about fixing Rankle??? - Rankle still wants all three modes, when is the update coming, when are adventure cards going to be implemented? (rtol, 2019-10-23 19:01:49) 
* [x] Rankle, Master of Pranks - It only let's you choose all three modes. You can't chose one, two or none of the modes. (binnet, 2019-10-15 23:15:47) 
* [x] Rankle, Master of Pranks Bug - Rankle, Master of Pranks triggered ability does not let you choose correctly, it forces you to take all 3 options (Tooxie, 2019-09-30 16:46:42) 
* [x] Rankle - cant be canceled, u have to take all 3 (CyanTCG, 2019-10-08 16:18:25) 
* [x] Rankle bugged - selecting one or two of rankle's abilities and cancelling does not work, all three must be selected each time (ChndraAblzn420, 2019-11-03 00:55:35) 
* [x] Rankle mater of pranks - rankle is bugged u have to take all 3 options mandatory thats wrong (CyanTCG, 2019-10-11 14:20:46) 

Other:
* [ ] Game: Cicle of Onslawght Crowns - Crowns of onslawght are now pauper legal, and could be excelent tools for aura oriented pauper decks. Could you add them in the next patch? They are Crown of Awe, Suspicion, Ascension, Fury and Vigor. (Sebamm, 2019-10-08 18:38:32) 
* [ ] New cards: Add Grusilda <3 - Could you guys please add the card "Grusilda, Monster Masher" to xmage? She makes a great commander for casual games and i would love to be able to play her on xmage. PS: You guys rock :D Thank you for keeping xmage up and running (Kraya, 2019-10-12 22:12:56) 
* [ ] New cards: Adventure Cards - Can not play really Standard because the adventure mechanics don´t exists (nerox283, 2019-10-12 10:04:59) 
* [ ] New cards: Adventure Cards - Hey, there are no adventure cards added in the new sez (ELD). (TheSnake, 2019-10-08 17:43:18) 
* [ ] New cards: Adventure Cards - It's been weeks. There are many decks I can't play because we don't have adventures yet. Please please please get them out soon! :( (crazymagicman, 2019-10-29 01:41:11) 
* [ ] New cards: Adventure Cards - Where is the Rest of throne of eldraine? Its been weeks now (Atmosphere, 2019-10-23 05:58:20) 
* [ ] New cards: Adventure Cards - hello. Cant see some adventure cards like - murderous rider. hope u can find time to fix. anyway thanks for this amazing software and all your work. much appreciated. (Darkconfidant, 2019-11-01 16:50:28) 
* [ ] New cards: Adventure Cards Not all ELD cards are up - I was looking for some cards, particularly the Throne of Eldraine cards, and noted it missed Merfolk Secretkeeper from it. Still looking for other cards and if i'll see others missing i'll tell you! (LucidDream, 2019-10-27 13:21:48) 
* [ ] New cards: Adventure cards - Add Brazen Borrower - Hey Devs, Thanks for this amazing software! I have noticed that Brazen Borrower is not in the cardset. Can you please add it? Thanks again! (goidenphoenix, 2019-11-27 00:10:04) 
* [ ] New cards: Adventure cards - Adventure cards & Pioneer - I'm sure that this is deliberate until fixed. Some Adventure cards are non-existenta (Brazen Borrower) and the others are not working (Giant Killer). Also, Pioneer is not defined as a separate format, but that's no problem. Btw, you guys rock, tnx (kakarot168, 2019-11-12 20:33:01) 
* [ ] New cards: Adventure cards - Brazen Borrower - [Brazen Borrower] card is missing - doesn't even show on the deck editor list... (Occultist, 2019-11-05 21:44:55) 
* [ ] New cards: Adventure cards - Do you have an ETA on adventure cards? I'm trying to test murderous rider. (The_Scrub, 2019-10-05 06:20:57) 
* [ ] New cards: Adventure cards - Giant killer - Adventure is not working (Toshenko, 2019-11-16 16:46:32) 
* [ ] New cards: Adventure cards - Hi, i have a question about the adventure cards of Eldrain, why i cant play with that cards, i cant cast a giant killer for his adventure cost (whiteraven, 2019-10-21 04:00:03) 
* [ ] New cards: Adventure cards - Missing Cards from ELD - Cards not found: - Foulmire Knight - Order of Midnight (myrrdin, 2019-11-23 10:26:17) 
* [ ] New cards: Adventure cards - New expansion is available? throne of eldrain (adridonpepe, 2019-11-03 02:42:54) 
* [ ] New cards: Adventure cards - No view this card Murderous Rider - No view this card Murderous Rider of throne of eldraine thanks (adridonpepe, 2019-11-03 02:47:06) 
* [ ] New cards: Adventure cards - merchant of the vale - merchant of the vale is not popping up in search. other eldraine cards are on here just not that one. (JasonK1, 2019-10-06 04:10:45) 
* [ ] New cards: Adventure cards - missing card - Stabilizer from the Scourge set is missing from your database (madman384, 2019-11-25 03:49:43) 
* [ ] New cards: Adventure cards - missing some cards in throne of eldraine (Kresh35, 2019-11-03 20:11:34) 
* [ ] New cards: Adventure cards - not found bazen borrower - there is no brazen borrower card (comehigados, 2019-11-21 12:29:14) 
* [ ] New cards: Adventure cards - please make them availiable. (The_Scrub, 2019-10-02 00:26:46) 
* [ ] New cards: Adventure cards - swift end and murerous rider - these card i cant seem to fine or are not  the data base i have use both swift end and murdes rider and nothing is popping up pls help whould much be helpful (theDjin, 2019-11-13 17:49:34) 
* [ ] Second card bug - In the most recent set, Cards that say "when you draw your second card each turn" only trigger once and never again, instead of triggering once each turn assuming you have drawn atleast 2 cards. (Rrehtua, 2019-10-17 20:26:09) 
* [ ] Server: Game stuck sometimes - Sometimes it happens that I can't press anything (i had F9 active) and then somehow the game says I have priority, while simultaniously stating "waiting for opponent" to me, while my clock is running. there is no way to get out of this lock for me. (Chri, 2019-11-08 19:34:47) 
* [ ] Server: Quit % is broken - Quit percentage is including games that freeze. This isn't something under my contronl, it shouldn't count aginst me. (jameswindsfury, 2019-10-21 19:04:31) 
* [ ] Server: Rares missing in chaos draft - Ive noticed this a few times, legions is the pack its happening in this time. There is no rare in a richman pack. (XMage, 2019-10-21 12:11:29) 
* [ ] Server: fix match starting during tourneys, please - Very very frequently, during a tourney (xmage.de server), the player who was playing the last match of the previous round doesn't connect for the next match, so the match doesn't start properly and becomes impossible to play out. (fujitaji313, 2019-10-17 20:32:03) 
* [ ] Server: player left game with priority on stack, add option to clear stack (mcrakdos, 2019-10-21 22:25:30) 
* [ ] UI: Fix this pls - https://sun9-11.userapi.com/c858020/v858020849/d468a/2ZqOwuUtv54.jpg (UnRel_Sunora, 2019-11-04 00:41:38) 
* [ ] UI: Movable stack - The stack is very badly placed in a corner. It should be in the middle of the battlefield or at least movable there. (senberg, 2019-11-01 06:39:13) 
* [ ] UI: No cancel for alt cast cost - ALternate casting cost options (Force of Will, Force of Negation, Daze, etc) don't allow you to cancel casting (presumably to cast the spell without using the alternate cost.)  They should allow that instead. (Angelbaka, 2019-09-30 06:45:40) 
* [ ] UI: Pop up card boxes - Hello, i have windows 10 instaled and every time a pop up card box show up, i get a really anoying bug that dosent let me play (MigZ, 2019-10-13 02:08:19) 
* [ ] UI: Sample hand in deck editor - It would be great if there was a sample hand option in deck editor. (r33v3r, 2019-11-27 07:44:47) 
* [ ] UI: Searching your deck to etb does not work gives me two selection screens - Whenever I use a golos or solemn simulucarum like effect the game glitches on the selection screen and does not let me get the thing then asks me again if I want to search for the thing again from the selection box :S (Charla_collec, 2019-10-07 01:03:07) 
* [ ] UI: Spacebar X2 - Quit from tournament - I believe hitting spacebar twice just quit and confirmed exiting the tournament. I think I've seen this before too. (XMage, 2019-10-21 08:53:39) 
* [ ] UI: Tourneys info - I was wondering why there is no more info about match time and construction time in limited tournaments... (Alonzo, 2019-10-01 01:23:13) 
* [ ] UI: XMage freezed - I selected multiple Basic Snow lands and tried to duplicate. Then XMage freezed. Version: 1.4.39 OS: Debian Stretch XFCE (myrrdin, 2019-11-13 19:37:50) 
* [ ] UI: auto ban list cards - auto mark a card on the ban list for the edited decklist in the format of players choice (RStilskin, 2019-11-24 00:51:17) 
* [ ] UI: change deck after create game - allow to change deck after creating a new game lobby (mage3k, 2019-11-22 20:51:46) 
* [ ] UI: close window with exiled cards - please make closing the window with the exiled cards possible. i can have a look at them by clicking the exiled cards thing per player anyways (Chri, 2019-11-08 19:33:45) 
* [ ] UI: german cardnames - While one can load german card images, that is not really helpful without being able to search for german card names. (myrrdin, 2019-10-20 12:56:04) 
* [ ] UI: localization - Some of my friends don't understand english very well. I would be happy for them if you offer german localization. I would help translate via https://weblate.org/ (myrrdin, 2019-10-20 12:40:22) 
* [ ] UI: missing images Standard - hello, I miss images from throne of eldrain. pls help (RAM, 2019-10-13 19:24:42) 
* [ ] UI: server could download automatically all images missing every time one connects - for reasons I dont know, I'm unable to download images from sets like,  Throne of Eldraine and Guilds of Ravnica (Rickymag, 2019-10-10 16:38:53)
* [ ] UI: votekick players - my opponents are very very slow i would like to encourage them to play faster preferably by kicking them so we dont have to wait 15 minutes before we can continue. (Zix, 2019-10-12 22:25:08) 
* [x] Game: Update to Premodern Ban List - Hello, I could not load a Premodern deck because I got a popup stating Frantic Search is banned. Frantic Search was recently unbanned in Premodern though. Thanks, Joe (Jozek7, 2019-11-25 00:11:53) 
* [x] Game: astrolabe is banned in pauper - now astrolabe is banned in pauper, thanks (satiro_bcn, 2019-10-22 15:09:52) 
* [x] Game: why is shuffling so lousy? - l cannot help but finding the shuffling system anything but lousy.... can't you do something about that? (X11, 2019-10-09 13:54:33) 
* [x] Other: Development Help - Is XMage open source? Are additional development resources needed? -Ben (GiantBen, 2019-11-27 23:17:47) 
* [x] Other: thanks - seriously thank you for making this platform for us who believe if i own a card i should be able to play it when and where ever i damn well please. (240sxCaptain, 2019-11-01 12:08:20) 
* [x] Second card bug - Draw 2 doesn't work - Draw 2 doesn't work with bloodhaze wolverine, pyromancer, ... It seems that it only works the first time it's triggered. (anwesender, 2019-10-07 15:34:25) 
* [x] Second card bug - The cards that trigger when you draw your second card per turn only tigger once per game per card. This is clearly not how the cards are supposed to work (Tasigoyf, 2019-09-28 06:42:16) 
* [x] Second card bug - the "Whenever you draw your second card each turn" clause often used in ELD doesnt work if the regular draw step card is the second card (Tooxie, 2019-10-05 18:17:11) 
* [x] Server: Can't Connect Locally - Can connect to servers but not the local server for AI games.
* [x] Server: Finally Xmage no lag - Xmage its very fast today, thanks for create it. Xmage its better than Cockatrice or Untap.in i love Xmage but in the past de deucht server always lag Xmage. (whiteraven, 2019-10-04 22:26:51) 
* [x] UI: to fix the damn Xmage - Several warnings about the lost of focus, which caused a bug of interface, which makes it nearly impossible to see the table/to play a match (UnRel_Sunora, 2019-11-04 00:07:00) 
* [x] UIL ignore list no work - people in my ignore list CAN JOIN in my rooms :/ (satiro_bcn, 2019-11-29 09:47:32)

**Comment by ssouders412** [comment]
K'rrik was added in #6038 and fixed in #6060.

**Comment by Alex-Vasile** [comment]
Curious Pair has been added with https://github.com/magefree/mage/commit/e32430bebf6afd67e15a5cfa9f82ceb6aad90221 and https://github.com/magefree/mage/commit/04a4b91a59fc0fe2ba3fa449cd287de47693009f.

**Comment by Alex-Vasile** [comment]
I think the Burning Earth problem has been fixed at some point. I couldn't reproduce it
Same with Lost Legion.
