### ISSUE TITLE
Feedback XMage Version 1.4.40

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6076]
Cards:
* **v0**
* [ ] Chainer doesn't have haste when casted from commander zone - Chainer should have haste when casted from the commander zone but he come into plays without haste (FluffyGiraffe, 2019-12-06 03:16:21) 
* [ ] Destructive revelery - I had a bugf where a card became unplayable from my hand - I was playing a deck with destructive revelery and for some reason I could never cast the 2nd one in my hand. Game claerly knew I had 3 cards in hand but I just couldnt cast it no matter how much green and red mana I had. (KittyBot, 2019-12-04 23:16:58) 
* [ ] Expropriate - Expropriate doesn't work correctly, I like to play Jodah Archmage EDH, this card seems to break the game. P.S you guys rock! <3 (Darmorr, 2019-12-05 22:12:51) 
* [ ] K'rrik ability - Opp had K'rrik in play. Other opponent could pay 2 life to cast his Saskia. (gifgif, 2019-12-02 03:05:08) 
* [ ] Kalitas, traitor of ghet trigger - casted tragic arrgance with kalitas, traitor of ghet into play, forced oponent to sac 2 creatures. they were exiled but zombies weren't created. maybe, kalitas's trigger isnt working. thank you for your support (K4sp, 2019-11-30 02:17:01) 
* [ ] Obzedat's Trigger Not working - Hello, Obzedat's doesn't return to the battlefield on the next turn when the abbility is triggered. Please fix this issue. Thank you. (N1K3, 2019-12-04 21:03:35) 
* [ ] Obzedat, Ghost Council Doesn't Return to the Battlefield - Obzedat, Ghost Council Doesn't Return to the Battlefield after being exiled with it's abbility. Please fix it. Thank you in advance! (N1K3, 2019-12-05 20:28:21) 
* [ ] Once Upon a Time is still bugged - I was playing on the German server and was on the draw and had Once Upon a Time in my opening hand. I drew for turn and then tried to cast it but it didn't give me the option of casting it for free, only for 1G. (JHard, 2019-12-01 09:10:14) 
* [ ] Opportunistic Dragon - can't block/can't attack effect did not end when opportunistic dragon was exiled (dsn, 2019-12-04 01:50:51) 
* [ ] Rankle Machine Broke - Rankle makes you choose all 3 modes (Gilgafresh, 2019-11-30 01:41:11) 
* [ ] Rankle is Broken - Rankle makes you choose all three modes and has no option to select 1 or 2 (funkytown85, 2019-11-30 01:41:24) 
* [ ] Tome of legends bug - the card "tome of legends" triggers with every commander instead of just my own. (sliverqueen, 2019-12-04 22:20:36) 

Other:
* **v0**
* [ ] New cards: Adventure cards - Adventure creatures are missing - need to play Brazen Borrower // Petty Theft but can't find it. Whes is it available? (Quion, 2019-12-01 00:40:34) 
* [ ] New cards: Adventure cards - Brazen Borrower - First off, great program overall but what happened with Brazen Borrower or other Adventure cards? They're still missing. (pumicore, 2019-12-05 01:26:36)
* [ ] New cards: Adventure cards - Card data base - Murderous Rider doesn't appear in card data base (Atletista, 2019-12-02 13:36:10) 
* [ ] Other: I love you guys - Thats all, thank you for all you do! (Chewbaklava, 2019-12-03 02:08:08) 
* [x] Game: Pioneer - Return to RAVNICA legal - Telling me dedck is illegal with Return to Ravnica cards (Gozerfish15, 2019-12-02 00:59:26) 
* [x] Game: Pioneer legal cards - Supreme Verdict is legal in Pioneer but when i build deck or try to join game it says it's not. (Snowflake, 2019-12-01 16:17:05) 
* [x] Game: Pithing Needle not working in Pioneer - Pithing Needle is legal in Pioneer, but not in xmage (edi, 2019-11-30 18:55:16) 
* [x] Game: RTR legal in pioneer - it's missing RTR in the pioneer format (K4sp, 2019-11-30 01:56:52) 
* [x] Game: Return to Ravnica (RTR) not Legal set in Pioneer - Return to Ravnica (RTR)  is not legal set in PIONEER Format (DosManos, 2019-12-04 09:37:20) 
* [x] Game: Rtr pioneer - system says rtr isn't allowed in pioneer (crazymagicman, 2019-12-04 16:08:47) 
* [x] Other: Thank you very much for your dedication - . (K4sp, 2019-11-30 01:57:29)

**Comment by ssouders412** [comment]
The K'rrik and Rankle bugs are fixed.

#6060 
#6064

**Comment by awjackson** [comment]
The Hangarback Walker interaction with -1/-1 counters is not a bug, it's how it's supposed to work. See the Oracle notes for Hangarback Walker.
