### ISSUE TITLE
Feedback XMage Version 1.4.41

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6115]
Cards:
* **v0**
* [ ] Collective restraint and koskun falls dont work - these cards make it so the controler of it cant be attacked due to the bug of not being allowed to pay. (Staticmtg666, 2019-12-22 03:45:05) 
* [x] Bolas Citadel not working on last update - Seems last patch made a bug on the cast for life on bolas citadel. On the previous version was running fine (Amigurumi, 2019-12-22 02:32:07) 
* [x] Bolas's citadel not allowing cast from top of deck - 2019/12/21 (mulliganto7, 2019-12-22 02:32:40) 
* [x] Glacial revelation is bugged - Is not possible to pick the snow permanents (Seton87, 2019-12-22 02:06:23) 
* [x] Karn the great creator - bug in the search hability from karn. he cann´t search from the exile (i exile my map and cannt search it with karn) (darkaniel44, 2019-12-22 20:40:06) 
* [x] Ludevic, Necro-Alchemist - Ludevic, Necro-Alchemist dosen't draw the controller cards just opponents. (Techies, 2019-12-22 03:39:19) 

Other:
* **v0**
* [ ] Game: Random Boosters - Again I play against the same rares in Chaos random draft. You might be seeding both packs with the same timestamp (XMage, 2019-12-23 09:56:55) 
* [ ] Server: Fixing - Please fix the part ween someone leaves the game. it brakes the game. people do that on purpose. its boring. Thank you. (EternalMaster, 2019-12-22 18:56:19) 
* [ ] Server: Got disconnected from draft without any apparent reason - Hi Today I was playing Vintage draft. On my very first game, I was kicked out of turnament (just before it even started). Not sure if this is a new bug introduced in the patch but wanted you to know. (voriax, 2019-12-21 20:07:09) 
* [ ] Server: Lag - Xmage is lagging so much that its not possible to play the game without losing to time. It's been like this for at least a year, since the american servers got shut off. Please do somethign about this! (Sonam, 2019-12-23 00:04:14)

**Comment by awjackson** [comment]
> Soul's fire with zada - i cast soul's fire on zada hedron grinder and it didnt trigger zada giving me no copys

This is not a bug. Zada triggers on spells that target *only* Zada. Soul's Fire has two targets.
