### ISSUE TITLE
Feedback XMage Version 1.4.42 (February 2020)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6291]
For previous bugs in 1.4.42 (January 2020) see #6169

**CARDS**

**v3 on 15.02.2020**
* [ ] Abeyance - Abeyance prevents any player from casting instants or sorceries (AthenaThree, 2020-02-11 01:34:45) 
* [ ] Argothian pixies - this card has been bugged forever. it prevents all damage to pixies not ust damage from artifact sources (OgounBadagris, 2020-02-02 10:57:06) 
* [ ] Ashiok, Phantasmal Image, Baleful Strix - When using Ashiok, Nightmare Weaver to put Phantasmal image into play copying Baleful Strix the copy will erroneously think it is being targetet and sacrifice itself. (DerBlaueEngel2, 2020-02-03 14:35:04) 
* [ ] Brainstorm + terminus triggered ability doesnt happens (ThomYorkshire, 2020-02-05 03:15:17) 
* [ ] Cream of the Crop isnt working properly - Cream of the crop triggered ability isnt working properly, i lost 3 triggers while choosing the card i wnated to put on top. totally screwed my tempo (rafikus, 2020-02-13 22:43:11) 
* [ ] Devouring Hellion death bug - Devouring Hellion doesn't activate dying abilities. I used Devouring Hellion to kill Bucher of Malakir and Vindictive Vampire and no interactions took place. (Benbo, 2020-02-02 22:16:37) 
* [ ] Dreadful apathy - bug with dreadful apathy and flicker of fate - Flickering the aura with its ability on the stack causes the new creature to be exiled instead of the original. (Eldritchguy, 2020-02-02 11:08:46) 
* [x] Extirpate - Bug - Hey guys, everytime I cast Extirpate, I cant select named card from my opponents hand (it doesnt even show the green outline around the card). Please, fix it. Thank you! (TotalPawn, 2020-02-06 13:07:40) 
* [ ] Fire//Ice and Snapcaster - Snapcaster can target fire//ice in graveyard, but will not let you cast either of the spells. (Daemonic, 2020-02-05 19:32:53) 
* [ ] Granted // Fae of Wishes and Underworld Breach - You should be able to cast the Granted half of Granted // Fae of Wishes from the graveyard using Underworld Breach. That is not possible currently. (psychospam90, 2020-02-15 04:56:14) 
* [ ] Maze of ith is not restricted in old school EC rules - unrestrict maze of ith in old school EC rules (NEIL, 2020-02-09 16:02:04) 
* [ ] Mirari is broken - Mirari dosen't copy spells even when you pay. (Techies, 2020-02-06 17:19:06) 
* [x] Mogis 2 damage trigger in upkeep - the mogis, god trigger for 2 damage in the upkeep unless I sack a creature doesn't deal damage if i have no creature on board (Chri, 2020-02-10 17:46:56) 
* [x] Mogis, God of Slaughter - His ability doesnt work (Ephaara, 2020-02-14 00:01:59) 
* [x] Mogis, God of Slaughter - Something causes  upkeep trigger to not deal damage in commander. Played one game where it worked, next game it deals no damage even if oppoent selects to take it. (Snowflake, 2020-02-10 17:49:21) 
* [ ] Pheres-Band Brawler - I flickered of fate on the Brawler, but the fight trigger didn't occur and should have, please fix. (AnotherTest, 2020-02-06 06:04:00) 
* [ ] Prized Amalgam - Prized Amalgam sometimes triggers for no reason (rtol, 2020-02-04 19:27:43) 
* [x] Sevinn'e reclamation broken since release - the copy on flashback doesn't work (Chewbaklava, 2020-02-11 09:30:46) 
* [x] Sevinne's Reclamation isn't copied when cast with flashback - When I cast SevRec with flashback I get a prompt (while it is resolving) asking me whether I want to copy it. When I say yes, it asks me to choose a target. However, the copy is never put on the stack. (ObNoxilis, 2020-02-03 12:27:05) 
* [x] Sevinne's reclamation flashback bugged - sevinne's reclamation flashback will not correctly copy (Chewbaklava, 2020-02-11 05:07:02) 
* [ ] Snake Basket - Snake Basket card 6th edition (6ED) shows Soul Net card in picture. (Snowflake, 2020-02-10 18:23:19) 
* [x] Surgical Extraction Select Card in Hand didn't work - I casted Surgical Extraction targeting a Devoted Druid in my opponent's graveyard and the ability to select the one he had in hand didn't work.  Selecting from the graveyard and library still worked though. (AnonymousGrove, 2020-02-08 17:53:43) 
* [x] Surgical Extraction does not work - You can NOT select the cards in opponents hand when playing Surgical Extraction, only in Graveyard and Library. (svenproud, 2020-02-13 16:22:49) 
* [x] Surgical and Extirpate problem - Basically neither surgical nor extirpate allows me to select the card from the hand of my opponent, the game doesn't recognize it as such in the hand. (LucidDream, 2020-02-01 13:50:46) 
* [x] Surgical extraction and narcomoeba - opponent dredged and with narc trigger on the stack i cast surgical targeting narc. game would not let me select the narc in my opponents hand (MiKiwisLethal, 2020-02-05 05:37:16) 

**OTHER**
**v3 on 15.02.2020**
* [x] Other: hey guys - Just wanted to say thank you. I really like being able to play magic whenever i want. Amazing job. Thank you (Nic, 2020-02-02 00:43:57) 
* [ ] Card request: Add the Onslaught card "Kaboom!" - The Onslaught card Kaboom! is not available in xmage. It would neat to have access to the classic card. Thanks! (KinglessName, 2020-02-06 22:24:30) 
* [ ] UI: View your deck in Draft Tournament Window - I was wondering if it would be possible to have an option to view your deck in the draft/cube Tournament Window.  Sometimes games dont launch properly it would allow you to save your deck and launch individually. (Lonestar68, 2020-02-09 03:40:29) 
* [x] Server: Its painfully slow - Its so slow to play with more than 3 players, send help! (ilfrit, 2020-02-10 21:20:48) **JayDi85: check your connection/vpn or use another server**
* [ ] Server: Disconnects from servers remove you from viewing current tables - Multiple times I've been disconnected from the .de server and upon recconect find that I cannot join the game I was already in. It does not show up in the "switch panels" tab and the "watch" action does nothing (Torchess, 2020-02-11 18:49:01)

**Comment by CCTV-1** [comment]
V5

looks any will create Food token cards(did not really test everyone card)resolve:
```
java.lang.NullPointerException
        at mage.player.ai.ma.ArtificialScoringSystem.getCardDefinitionScore(ArtificialScoringSystem.java:46)
        at mage.player.ai.ma.ArtificialScoringSystem.getFixedPermanentScore(ArtificialScoringSystem.java:52)
        at mage.player.ai.GameStateEvaluator2.evaluatePermanent(GameStateEvaluator2.java:104)
        at mage.player.ai.ComputerPlayer6.printOutState(ComputerPlayer6.java:143)
        at mage.player.ai.ComputerPlayer6.printOutState(ComputerPlayer6.java:107)
        at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:58)
        at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:37)
        at mage.game.GameImpl.playPriority(GameImpl.java:1292)
        at mage.game.turn.Step.priority(Step.java:61)
        at mage.game.turn.Phase.playStep(Phase.java:184)
        at mage.game.turn.Phase.play(Phase.java:89)
        at mage.game.turn.Turn.play(Turn.java:126)
        at mage.game.GameImpl.playTurn(GameImpl.java:889)
        at mage.game.GameImpl.play(GameImpl.java:798)
        at mage.game.GameImpl.start(GameImpl.java:762)
        at mage.server.game.GameWorker.call(GameWorker.java:34)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

then:
```
mage.MageException: Iterated player priority after game exception too often, game ends!
        at mage.game.GameImpl.playPriority(GameImpl.java:1336)
        at mage.game.turn.Step.priority(Step.java:61)
        at mage.game.turn.Phase.playStep(Phase.java:184)
        at mage.game.turn.Phase.play(Phase.java:89)
        at mage.game.turn.Turn.play(Turn.java:126)
        at mage.game.GameImpl.playTurn(GameImpl.java:889)
        at mage.game.GameImpl.play(GameImpl.java:798)
        at mage.game.GameImpl.start(GameImpl.java:762)
        at mage.server.game.GameWorker.call(GameWorker.java:34)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

only test in local bot game.

**Comment by JayDi85** [comment]
@CCTV-1 that rollback error with mana cards fixed in #6300 (`ArtificialScoringSystem` error)

**Comment by CCTV-1** [comment]
V5

`Dreadful Apathy` and `Flicker of Fate` interact incorrectly

example log:
```
下午9:28: CCTV casts Dreadful Apathy [56e] targeting Riptide Turtle [121] 
下午9:28: CCTV puts Dreadful Apathy [56e] from stack onto the Battlefield
下午9:28: CCTV attacks with 0 creatures
下午9:28: Turn 15 computer (20 - 20)
下午9:28: computer draws a card
下午9:28: computer casts Vantress Gargoyle [e00]
下午9:28: computer puts Vantress Gargoyle [e00] from stack onto the Battlefield
下午9:28: computer attacks with 0 creatures
下午9:28: Turn 16 CCTV (20 - 20)
下午9:28: CCTV draws a card
下午9:28: CCTV puts Plains [b04] from hand onto the Battlefield
下午9:28: CCTV plays Plains [b04]
下午9:28: CCTV activates: Exile enchanted creature. from Dreadful Apathy [56e]
下午9:28: CCTV casts Flicker of Fate [df3] targeting Dreadful Apathy [56e] 
下午9:28: CCTV moves Dreadful Apathy [56e] from battlefield to the exile zone
下午9:28: CCTV puts Flicker of Fate [df3] from stack into their graveyard
下午9:28: CCTV moves Wall of Runes [c9e] from battlefield to the exile zone
下午9:28: Dreadful Apathy [56e] is put into graveyard from battlefield
```


the correct behavior is `moves Riptide Turtle [121] from battlefield to the exile zone `

[NOTES AND RULES INFORMATION FOR DREADFUL APATHY:](https://scryfall.com/card/thb/11/dreadful-apathy)
`If Dreadful Apathy leaves the battlefield while its last ability is on the stack, the permanent that’s exiled is the one Dreadful Apathy enchanted before leaving the battlefield, even if that permanent is no longer a creature.`
