### ISSUE TITLE
Extra or Missing Commas / Periods / Spaces

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6474]
- [x] Colfenor's Urn: extra comma
![image](https://user-images.githubusercontent.com/59861365/80269809-97d90080-8678-11ea-8601-7673d8d94fa3.png)

- [x] Haunted Cloak: extra comma
![image](https://user-images.githubusercontent.com/59861365/80269867-10d85800-8679-11ea-99f0-3031f832dfe9.png)

- [x] Opportunistic Dragon: extra period
![image](https://user-images.githubusercontent.com/59861365/80269837-d66ebb00-8678-11ea-9499-4507b690f106.png)

- [x] Tall as a Beanstalk: extra period
![image](https://user-images.githubusercontent.com/59861365/80269841-e5556d80-8678-11ea-9762-0ea45f0ca56b.png)

- [x] Tribal Golem: two extra periods
![image](https://user-images.githubusercontent.com/59861365/80269851-f7371080-8678-11ea-8d2f-6afee745843a.png)

- [x] Wirefly Hive: extra period
![image](https://user-images.githubusercontent.com/59861365/80269873-22216480-8679-11ea-8f52-d9c2f65b1fab.png)

- [x] Torgaar, Famine Incarnate: extra period
![image](https://user-images.githubusercontent.com/59861365/80269878-32394400-8679-11ea-9b49-b85981aab66b.png)

- [x] Glittering Lynx: extra period
![image](https://user-images.githubusercontent.com/59861365/80270952-34ec6700-8682-11ea-8f0f-acc6f56ba787.png)

- [x] Genju of the Fields: extra period
![image](https://user-images.githubusercontent.com/59861365/80270957-433a8300-8682-11ea-82de-b4b212981844.png)

- [x] Verdant Rebirth: extra period
![image](https://user-images.githubusercontent.com/59861365/80270966-52213580-8682-11ea-8a72-8ed9e23cbd2d.png)

- [x] Force Projection (a SWS card): extra period
![image](https://user-images.githubusercontent.com/59861365/80270981-636a4200-8682-11ea-9b8b-9d2d9e1319c7.png)

- [x] Luke Skywalker, the Last Jedi (a SWS card): extra period
![image](https://user-images.githubusercontent.com/59861365/80270988-77ae3f00-8682-11ea-84a8-d95b4fdb580c.png)

- [x] Glittering Lion: extra period
![image](https://user-images.githubusercontent.com/59861365/80270998-8c8ad280-8682-11ea-90b1-bed440de47b7.png)

- [x] Dreams of the Dead: extra period
![image](https://user-images.githubusercontent.com/59861365/80271003-990f2b00-8682-11ea-93b9-7533a466731f.png)

- [x] Teferi's Protection: extra period
![image](https://user-images.githubusercontent.com/59861365/80298320-a8f54080-8750-11ea-8b0a-03420f2093e1.png)

- [x] Unity of Purpose: extra period
![image](https://user-images.githubusercontent.com/59861365/80298331-c6c2a580-8750-11ea-94a0-a69cafc8255e.png)

- [x] Kiora, Master of the Depths: extra period
![image](https://user-images.githubusercontent.com/59861365/80271014-aaf0ce00-8682-11ea-95fa-9b14ca1a7192.png)

- [x] Najeela, the Blade Blossom: missing a space
![image](https://user-images.githubusercontent.com/59861365/80314132-44200180-87b5-11ea-8e62-445aa7983150.png)

- [x] Land's Edge: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270329-84c82f80-867c-11ea-9af3-d6e60a6fbd66.png)

- [x] Fell the Pheasant: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270348-b0e3b080-867c-11ea-9573-f88ef1ee42f1.png)

- [x] Soul Separator: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270357-c3f68080-867c-11ea-93c3-3957a4ddebcc.png)

- [x] Recross the Paths: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270418-69a9ef80-867d-11ea-8a9f-57ea5cd49d7e.png)

- [x] Bond of Discipline: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270434-9c53e800-867d-11ea-985c-cfb5db9b4184.png)

- [x] Portent: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270440-b8578980-867d-11ea-8b9f-3dd72ff2b1e4.png)

- [x] Forever Young: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270443-c5747880-867d-11ea-830a-6488b7d85cbe.png)

- [x] Foresight: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270456-e63cce00-867d-11ea-892a-925ed90509df.png)

- [x] Benefactor's Draught: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270463-fe145200-867d-11ea-8bf8-826d022c4210.png)

- [x] Winnow: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270472-11272200-867e-11ea-84a5-aa60c7cfc035.png)

- [x] Solfatara: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270478-23a15b80-867e-11ea-88b5-60cda60d0c35.png)

- [x] Spiritualize: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270485-361b9500-867e-11ea-9920-d4c4360112f4.png)

- [x] Clear the Mind: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270487-429fed80-867e-11ea-8f42-ee2a04c1c296.png)

- [x] Leadership Vacuum: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270497-521f3680-867e-11ea-8fb7-ae3959d78de1.png)

- [x] Turf Wound: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270506-5f3c2580-867e-11ea-9a22-22a4dcd5afcf.png)

- [x] Finale of Revelation: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270517-7d098a80-867e-11ea-9b90-e41468bd1dbb.png)

- [x] Mandate of Peace: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270519-898de300-867e-11ea-9c1d-0b0f565728f2.png)

- [x] Bond of Insight: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270537-96aad200-867e-11ea-8352-774e4ea81e48.png)

- [ ] Twilight Prophet: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270546-a5918480-867e-11ea-83d5-bd35a7ae4146.png)

- [x] Necromaster Dragon: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270548-b04c1980-867e-11ea-8b46-53f7d2f5a83e.png)

- [x] Suncleanser: missing *two* spaces
![image](https://user-images.githubusercontent.com/59861365/80270564-dbcf0400-867e-11ea-9297-a7ce130b8cac.png)

- [x] Goatnap: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270573-ea1d2000-867e-11ea-9155-8d64ed2c3c06.png)

- [x] Blind Fury: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270586-fef9b380-867e-11ea-854e-a58c404346b8.png)

- [x] Soldevi Golem: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270589-0ae57580-867f-11ea-8adb-ba242f61a0b1.png)

- [x] Queen of Ice: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270595-19339180-867f-11ea-82e6-d3df374cf587.png)

- [x] Nissa, Who Shakes the World: missing a space, extra period
![image](https://user-images.githubusercontent.com/59861365/80270606-336d6f80-867f-11ea-8611-3c5b23e4d61b.png)

- [x] Insult // Injury: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270613-43854f00-867f-11ea-98ee-f3a05aef65a9.png)

- [x] Prepare // Fight: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270618-5566f200-867f-11ea-8a23-1b001fb0a90d.png)

- [x] Roving Keep: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270621-6152b400-867f-11ea-8c6d-64ff9be4715f.png)

- [x] Workshop Elders: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270628-6dd70c80-867f-11ea-98c1-ab7148ea7a5f.png)

- [x] Chromium the Mutable: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270638-7b8c9200-867f-11ea-9a80-a6415f57c27a.png)

- [x] Single Combat: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270649-965f0680-867f-11ea-95ff-26fd8a68f012.png)

- [x] Animating Faerie: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270663-b55d9880-867f-11ea-9a5b-85929b332e3c.png)

- [x] Oko, the Trickster: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270668-c6a6a500-867f-11ea-9c4a-c482cc2b7c66.png)

- [x] Force Denail (a SWS card): missing a space
![image](https://user-images.githubusercontent.com/59861365/80270684-eb9b1800-867f-11ea-851d-71e899045a20.png)

- [x] Fateful End: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270693-fa81ca80-867f-11ea-86db-cf76914f4518.png)

- [x] Fatal Frenzy: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270698-053c5f80-8680-11ea-9fb5-0f176b546755.png)

- [x] Deathsprout: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270707-17b69900-8680-11ea-892c-afbabfa25b82.png)

- [x] Ancient Animus: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270725-37e65800-8680-11ea-8c21-06464cd8f056.png)

- [x] Chance for Glory: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270733-45034700-8680-11ea-82d4-85371f6e12c3.png)

- [x] Farrel's Mantle: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270745-5c423480-8680-11ea-97d4-ccaf26f465a1.png)

- [x] Wicked Wolf: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270753-7da32080-8680-11ea-97fd-45a5172426b7.png)

- [x] Juxtapose: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270759-8b58a600-8680-11ea-8e12-f1f66846a2be.png)

- [x] Sorin, Vengeful Bloodlord: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270776-9f9ca300-8680-11ea-8995-2ef97ce18ea3.png)

- [x] Vivien, Arkbow Ranger: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270791-b3480980-8680-11ea-8a62-36ec2a682746.png)

- [x] Collapsing Borders: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270803-c529ac80-8680-11ea-923a-e1bb2643c624.png)

- [x] Zirilan of the Claw: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270810-d5418c00-8680-11ea-8938-3f58af7b2637.png)

- [x] Ajani, Valiant Protector: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270822-ea1e1f80-8680-11ea-8de2-c146e2a9d056.png)

- [x] Vraska, Regal Gorgon: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270831-f7d3a500-8680-11ea-9480-8d3affc67b08.png)

- [x] Bringer of the Red Dawn: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270839-05892a80-8681-11ea-894a-e6eebc86ac56.png)

- [x] Colossal Heroics: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270847-19cd2780-8681-11ea-9934-85026aca59d1.png)

- [x] Molder: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270861-408b5e00-8681-11ea-9d8c-c6adf6123850.png)

- [x] Stolen by the Fae: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270869-58fb7880-8681-11ea-873b-c4d8a441617a.png)

- [x] Battlefield Promotion: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270883-657fd100-8681-11ea-891a-211934bc73d1.png)

- [x] Desperate Lunge: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270891-703a6600-8681-11ea-85b0-6d444b70f9c1.png)

- [x] Malicious Advice: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270894-7cbebe80-8681-11ea-88e5-b2fc0f3eaedb.png)

- [x] Wellspring: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270898-8811ea00-8681-11ea-8930-b402f4494e65.png)

- [x] Kari Zev's Expertise: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270900-93fdac00-8681-11ea-9d87-16a9824d6b94.png)

- [x] Triumphant Surge: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270905-a2e45e80-8681-11ea-9c78-0034cc58c0ac.png)

- [x] From Under the Floorboards: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270908-b1327a80-8681-11ea-8701-2b1b26a62bc7.png)

- [x] Ivory Gargoyle: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270911-bc85a600-8681-11ea-9845-5816bf6b2ab3.png)

- [x] Molten Firebird: missing a space
![image](https://user-images.githubusercontent.com/59861365/80270918-cb6c5880-8681-11ea-8a9e-cb58d9ea38e2.png)

**Comment by cimaxwell** [comment]
I am new to this repository, If someone could direct me to where the card descriptions/info is stored, I would be happy to fix as many of these as I can.

**Comment by JayDi85** [comment]
@cimaxwell most card texts are auto-generated by xmage, so you must look at each card file and research ability/effects code too. 

Some cards can be easy to fix (like duplicated text, typo, dot in effects, renamed filters, etc). BUT another cards are hard to fix and needs to modify effect/ability text generating. Even more -- wrong text can be mark of wrong/bugged card's code.

Fixing text is hard work.

As example from first bug:
![shot_200429_142922](https://user-images.githubusercontent.com/8344157/80586356-e2b29980-8a25-11ea-885e-b83a9632f8de.png)

There are useful unit tests in `VerifyCardDataTest` to run it from IntelliJ and check card texts:
1. `showCardInfo` -- allows to see real card text in output logs. Use it to check card text before and after any fix;
![shot_200429_143832](https://user-images.githubusercontent.com/8344157/80587154-1cd06b00-8a27-11ea-9e92-93a72c2a2506.png)

2. `verifyCards` -- checks many cards and make output logs about different in cards text from one set (use `FULL_ABILITIES_CHECK_SET_CODE` to setup checking set).
![shot_200429_144139](https://user-images.githubusercontent.com/8344157/80587410-8e101e00-8a27-11ea-81ef-540c8d05ff78.png)

**Comment by timhae** [comment]
Would it be useful to have an external tool check the generated text and compare it to scryfall data? I thought about doing something like that in python.

**Comment by etpalmer63** [comment]
I am working through this list and trying to understand what the common practice is for text generation. It looks like the getRule method in Effects.java handles punctuation and capitalization at the beginning and end of rules. In this sense, capitalization at the beginning and punctuation at the end of the rule should be removed from any text entered in each card's java file. I'm finding that removing ending punctuation is fixing many typos on this list.

So is the rule, "capitalization at the beginning and punctuation at the end is handled outside the card's java file"? If so, then the same thing should apply to common effects that auto generate their rules as well, correct? 

Thanks,

Erik

**Comment by JayDi85** [comment]
@etpalmer63 that's right -- xmage uses auto-generations and collecs final rules from multiple abilities and effects.

Basic rules:
* Try to use auto-generation as much as possible (good card is card without any `setText`, getRules and etc overrides).
* Custom effect text must be minimal (lower first char, no end char like dot);
* Custom ability text must be full (capitalization + punctuation);
* Some abilities or effects have special params in constructors to control card's text -- it can concat text with prev effect like `.concatBy` call, setup param to add `it` or `this creature` in the texts, insert filter name in effect text and vice versa.

Even more some devs can add punctuations and delimiters to the effect's text (or more worse -- in filters and dynamic values). 

So it's a complex task. That's why you must test card after changes (fastest way to test: run `showCardInfo()` test).

**Comment by Zerrisx** [comment]
- [ ] Paragon of the Amesha has an extra period and space:
![image](https://user-images.githubusercontent.com/59861365/83060741-8ee5a100-a021-11ea-855e-ca2d1aa3c619.png)

**Comment by etpalmer63** [comment]
Isn't soul separator also missing "Exile target creature from your graveyard" ?

**Comment by Zerrisx** [comment]
Moved the last three issues on here to #6654
