### ISSUE TITLE
Issues involving Rielle, the Everwise

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6532]
### Unfixed issues Involving Rielle:

- [ ]  If you play Kaervak's Spite with Rielle out, you always draw cards equal to the cards you discarded.  However, you can pay costs in any order, so you should have the *choice* of whether to trigger Rielle or not, depending on the order in which you sacrifice and discard.  They are certainly two separate costs and not a single one, despite what this chat log seems to imply:
![image](https://user-images.githubusercontent.com/59861365/82157228-c005ea80-9845-11ea-9537-d130c5f11d1e.png)

- [ ] If you have Rielle the Everwise out and discard to hand size, nobody gets priority to respond to Rielle's trigger, which is incorrect.  Players should receive priority like normal until the stack is clear and another cleanup step occurs.

- [ ] Balancing Act still triggers Rielle even if you sacrifice her to the creature effect, which is wrong, because each step is done in order so she shouldn't be on the battlefield at the time the discard occurs.
![image](https://user-images.githubusercontent.com/59861365/81442318-f9997000-9138-11ea-9ebe-c1f2b534e01d.png)

- [ ] Collective Brutality escalated twice still only draws one card off Rielle
![image](https://user-images.githubusercontent.com/59861365/81442513-58f78000-9139-11ea-9942-6600d2255046.png)

- [ ] Rare-B-Gone still triggers Rielle even though she gets sacrificed before the discard, which is wrong
![image](https://user-images.githubusercontent.com/59861365/81464011-e8c21c00-9183-11ea-8981-507ef3012d20.png)

- [ ] Rielle only ever draws one card from Vexing Sphinx's cumulative upkeep, when she should draw all of it
![image](https://user-images.githubusercontent.com/59861365/81466748-8a079d00-9199-11ea-9e63-78a28add2939.png)

### Already Fixed:

- [x] Cavalier of Flame only draws one card even if you discard multiple
![image](https://user-images.githubusercontent.com/59861365/81448633-52bad100-9144-11ea-9737-ae4d894285b8.png)

- [x] Even if you discard multiple cards to Persecute, Rielle only draws one
![image](https://user-images.githubusercontent.com/59861365/81461647-cffd3a80-9172-11ea-9e6d-5f46b63efef2.png)

- [x] Oath of Lim-Dul's discard is simultaneous, so Rielle should draw the full amount; she currently does not
![image](https://user-images.githubusercontent.com/59861365/81462360-911db380-9177-11ea-95a4-8a8dda3a89b0.png)

- [x] Abandon Hope says you choose cards from any player, but should be opponents only
![image](https://user-images.githubusercontent.com/59861365/81440247-5430cd00-9135-11ea-98d5-f75d49c4f6bb.png)
![image](https://user-images.githubusercontent.com/59861365/81440277-6448ac80-9135-11ea-8c1c-7ae955fa9dd2.png)

- [x] Abandon Hope's hover text is still wrong, though the functionality is now correct.
![image](https://user-images.githubusercontent.com/59861365/82158050-d9f5fc00-984a-11ea-8c1e-5c4809718d76.png)

- [x] Alexi, Zephyr Mage's text is wrong - missing an X and should be <to their owners' hands> instead of <to its owner's hand>
![image](https://user-images.githubusercontent.com/59861365/81442904-12565580-913a-11ea-9ad3-3f3f14c8c1de.png)

- [x] Ana Battlemage's blue kicker can only target opponents, when it should be target player
![image](https://user-images.githubusercontent.com/59861365/81439815-96a5da00-9134-11ea-8d6f-433efb30951c.png)

- [x] Arterial Flow gives a rollback error when cast
![image](https://user-images.githubusercontent.com/59861365/81443899-e20fb680-913b-11ea-9902-a61f4b9e73e2.png)

- [x] Casting Balance (or Restore Balance) on this board (with each player having one creature in play) results in both creatures being sacrificed instead of neither
![image](https://user-images.githubusercontent.com/59861365/81464058-3dfe2d80-9184-11ea-9563-109cf7eddcb3.png)

- [x] Bite of the Black Rose and Capital Punishment cause a rollback error when cast (against the AI if relevant) - probably an issue with voting cards in general.
![image](https://user-images.githubusercontent.com/59861365/81448955-de346200-9144-11ea-9ae5-90be8767ebe6.png)

- [x] Bog Down's text says "two" twice
![image](https://user-images.githubusercontent.com/59861365/81450046-38362700-9147-11ea-9935-4c17da7d6615.png)

- [x] Cabal Therapist has an extra period in the ability text
![image](https://user-images.githubusercontent.com/59861365/81439426-fcde2d00-9133-11ea-85cd-e5281c3a1419.png)

- [x] I was unable to cast Cabal Therapy from my hand (but could still cast it from the graveyard) - couldn't reproduce, so not sure what exactly caused it.

- [x] Caligo Skin-Witch throws a rollback error when cast with kicker
![image](https://user-images.githubusercontent.com/59861365/81451671-9a445b80-914a-11ea-9f17-0fb47d5ed4c9.png)

- [x] Champion of Wits' ability text is wrong
![image](https://user-images.githubusercontent.com/59861365/81448377-df18c400-9143-11ea-8f62-395f5c097968.png)

- [x] Crosis, the Purger is *very* wrong in how the ability resolves.  It discards all the cards in *your own* hand of the chosen color, but *says* that the opponent discarded them (and triggers the opponent's Rielle if applicable).
![image](https://user-images.githubusercontent.com/59861365/81443382-f30bf800-913a-11ea-9073-3ebdd434cc3c.png)
![image](https://user-images.githubusercontent.com/59861365/81443422-00c17d80-913b-11ea-82d5-21d567dbe6f3.png)

- [x] Distended Mindbender makes you choose your sacrifice twice - you choose, pay mana, then choose again
![image](https://user-images.githubusercontent.com/59861365/81444481-d07ade80-913c-11ea-9384-87d78c0cb804.png)
![image](https://user-images.githubusercontent.com/59861365/81444505-dec8fa80-913c-11ea-9c9b-6542ea7d0753.png)

- [x] Distended Mindbender isn't letting me pick any cards (for either cmc choice):
![image](https://user-images.githubusercontent.com/59861365/81444572-facc9c00-913c-11ea-9b7b-12f61b469365.png)

- [x] Greel, Mind Raker's text is wrong
![image](https://user-images.githubusercontent.com/59861365/81453472-38d2bb80-914f-11ea-88e6-5de7c943d0e7.png)

- [x] Gruesome Discovery with kicker isn't letting me pick cards
![image](https://user-images.githubusercontent.com/59861365/81453062-358b0000-914e-11ea-88c6-f6a4f6496acd.png)

- [x] Insidious Dreams says "as an additional cost" twice
![image](https://user-images.githubusercontent.com/59861365/81455484-f90ed280-9154-11ea-96ad-9872ffb7bdbb.png)

- [x] Kaervek's Spite doesn't have a target, so it doesn't deal damage to anything
![image](https://user-images.githubusercontent.com/59861365/81455181-15f6d600-9154-11ea-9733-b7ded313f188.png)

- [x] Knollspine Dragon puts the draw text in chat twice - the first time correctly, and a second time incorrectly.  The second instance should be removed.
![image](https://user-images.githubusercontent.com/59861365/81456543-4d678180-9158-11ea-8707-76695c90f415.png)

- [x] Midnight Oil - text is missing a bit
![image](https://user-images.githubusercontent.com/59861365/81460239-abe92b80-9169-11ea-93ad-007cc5166705.png)

- [x] Mind Warp can't select cards
![image](https://user-images.githubusercontent.com/59861365/81460495-501fa200-916b-11ea-92db-46aebc9ff2b9.png)

- [x] Mind Warp: card > cards
![image](https://user-images.githubusercontent.com/59861365/83027779-259c6880-9ff6-11ea-99d4-080ff7966633.png)

- [x] Noggin Whack is making the player discard all three cards instead of just the two chosen
![image](https://user-images.githubusercontent.com/59861365/81462017-4e5adc00-9175-11ea-984d-21d4e265a9d4.png)

- [x] Noxious Vapors discards all cards, even the ones you selected

- [x] Probe's 'if' should be an uppercase 'If'
![image](https://user-images.githubusercontent.com/59861365/81461826-f1aaf180-9173-11ea-9f4c-ce974f53781f.png)

- [x] Psychic Vortex's trigger has an extra period
![image](https://user-images.githubusercontent.com/59861365/81461951-e60bfa80-9174-11ea-8047-87bbe0551093.png)

- [x] Tasigur's Cruelty crashed with a null pointer exception
![image](https://user-images.githubusercontent.com/59861365/81466097-73ab1280-9194-11ea-91d7-49356c4d3080.png)

- [x] Thought Gorger makes you discard your hand if it's alive when the first trigger resolves, even if the action of putting counters on it is still impossible e.g. due to Solemnity being in play
![image](https://user-images.githubusercontent.com/59861365/81465852-d3082300-9192-11ea-9293-c3b4bb1c94c9.png)

- [x] Unnerve is throwing a null pointer error
![image](https://user-images.githubusercontent.com/59861365/81466393-0b116500-9197-11ea-87f1-d3ad4da95683.png)

**Comment by Zerrisx** [comment]
Split the last two unrelated issues out into their own issue threads, so this is now only unfixed issues with Rielle herself.

**Comment by Zerrisx** [comment]
Collapsing the remaining issues into #6761 for clarity, since they're all specific to Rielle.
