### ISSUE TITLE
Follow-up to issue "Keywords in quotes #6477"

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6533]
- [x] Hedron Blade - "Equipped creature" > "it" or set the text across two lines.
![image](https://user-images.githubusercontent.com/59861365/81479653-1e99eb80-91ea-11ea-92a7-ab46fe7fbb55.png)

- [x] Sky Tether - remove second instance of "Enchanted creature" or set the text across two lines.
![image](https://user-images.githubusercontent.com/59861365/81479718-9cf68d80-91ea-11ea-9006-7a91f3091dbc.png)

- [x] Lashknife - "Tap" > "tap"
![image](https://user-images.githubusercontent.com/59861365/81479875-c4018f00-91eb-11ea-9d9b-20389450989d.png)

- [x] Aspect of Manticore - "Enchanted" > "enchanted"
![image](https://user-images.githubusercontent.com/59861365/81479895-d7acf580-91eb-11ea-94f3-000e84ebd8b2.png)

- [x] Helm of Kaldra - missing a period
![image](https://user-images.githubusercontent.com/59861365/81479922-eb585c00-91eb-11ea-9fda-e59d052e2a9b.png)

- [x] Angelic Armaments - should be "becomes White" and "is an Angel"
![image](https://user-images.githubusercontent.com/59861365/81480084-eb0c9080-91ec-11ea-8cd4-ae8b42e5f435.png)

- [x] Ring of Valkas - missing a period

- [x] Ring of Kalonia - missing same period

- [x] Ring of Xathrid - missing same period
![image](https://user-images.githubusercontent.com/59861365/81480189-9a496780-91ed-11ea-9bf0-1d45cf30fa1e.png)

- [x] Executioner's Hood - "Intimidate" > "intimidate"

- [x] Grisly Transformation - "Intimidate" > "intimidate"

- [x] Gruesome Deformity - "Intimidate" > "intimidate"

- [x] Nim Deathmantle - "Intimidate" > "intimidate"
![image](https://user-images.githubusercontent.com/59861365/81480245-fc09d180-91ed-11ea-9746-bbce2b76229a.png)

- [ ] Cloak of Invisibility - "Phasing" > "phasing"

- [ ] Teferi's Curse - "Phasing" > "phasing"
![image](https://user-images.githubusercontent.com/59861365/81480259-15128280-91ee-11ea-901e-271a0613598a.png)

- [x] Corrupted Conscience - "Infect" > "infect"

- [x] Glistening Oil - "Infect" > "infect"

- [x] Grafted Exoskeleton - "Infect" > "infect"

- [x] Phyresis - "Infect" > "infect"
![image](https://user-images.githubusercontent.com/59861365/81480273-2eb3ca00-91ee-11ea-89cc-31dd5ccf35f8.png)

- [x] Snake Cult Initiation - "Poisonous" > "poisonous"
![image](https://user-images.githubusercontent.com/59861365/81480341-c74a4a00-91ee-11ea-9300-ad2a6156bfb1.png)

- [x] Hunter Sliver - "Provoke" > "provoke", and also remove the quotes
![image](https://user-images.githubusercontent.com/59861365/81480378-0b3d4f00-91ef-11ea-9fb5-ddff20be8f5e.png)

- [x] Oni Possession - "a a" > "a"
![image](https://user-images.githubusercontent.com/59861365/81480610-69b6fd00-91f0-11ea-88fa-20121113b9c3.png)
