### ISSUE TITLE
Split Card Bugs

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6549]
### Bugs found while testing fixes:

- [x] Split cards can't be cast with flashback (although this at least no longer crashes) - already noted in the following issues:  #4594 #6327 #6470

- [x] Armed // Dangerous cast with Council of the Absolute in play on "Armed" now has a _different_ incorrect cost.  It's discounting before combining the costs, thus charging R + 3G, when the entire spell contains the name Armed and thus should be discounted post-combined-cost, resulting in a total cost of 2RG instead.

- [x] Likely related to the above, Thalia, Guardian of Thraben increases the cost of fused spells by {2}  (once per half) instead of {1}.  Costs should be combined for Fuse before taxes/discounts are applied.  Probably the same issue in #6493.

-----

- [x] If you want to cast a fuse card with fuse, you have to select the fuse option twice.
![image](https://user-images.githubusercontent.com/59861365/82158414-5ab5f780-984d-11ea-8506-0391742bf907.png)
![image](https://user-images.githubusercontent.com/59861365/82158417-61dd0580-984d-11ea-890a-2979fb535181.png)

- [x] If you name Armed with Council of the Absolute, then casting a fused Armed//Dangerous costs only 3G, when it should cost 2RG.  You also don't get to choose a target for Armed, although if you only have one creature out, it will be chosen.
![image](https://user-images.githubusercontent.com/59861365/82158540-3c9cc700-984e-11ea-9a09-42e3a7020bb1.png)
![image](https://user-images.githubusercontent.com/59861365/82158543-47575c00-984e-11ea-8085-fe83abb83737.png)

- [x] All split cards have weird text... but only while in the hand; not while in deck editor.
![image](https://user-images.githubusercontent.com/59861365/81447824-f2775f80-9142-11ea-908f-8376d1eb7ad9.png)

- [x] Trying to cast Armed//Dangerous from the yard after giving it flashback with Snapcaster mage threw a rollback error:
![image](https://user-images.githubusercontent.com/59861365/82158393-35c18480-984d-11ea-82a7-c289de2272cf.png)

- [x] Casting Delay on a fused Wear // Tear resulted in time counters never coming off it.  It just sat there with three counters every turn.
![image](https://user-images.githubusercontent.com/59861365/82163660-3c162780-9872-11ea-8ee2-46de10c32c5a.png)

**Comment by Zerrisx** [comment]
Updated top post with new issues revealed by fixes.

**Comment by JayDi85** [comment]
> Split cards can't be fused when cast from the top of the library with Future Sight

That's correct. Fused spells works from hands only (e.g. you can't fuse from graveyard with flashback or from top of the library). See [here](https://cantrip.ru/en/mtg-cards/Turn-Burn.shtml) (search by Future Sight).

**Comment by Zerrisx** [comment]
> 
> 
> > Split cards can't be fused when cast from the top of the library with Future Sight
> 
> That's correct. Fused spells works from hands only (e.g. you can't fuse from graveyard with flashback or from top of the library). See [here](https://cantrip.ru/en/mtg-cards/Turn-Burn.shtml) (search by Future Sight).

Right you are.

**Comment by JayDi85** [comment]
All fixed

**Comment by jeffwadsworth** [comment]
Of course, there is always another bug in the house.  Retrace doesn't get added to the Split-Card in the graveyard via the Wrenn and Six emblem.
![EmblemRetraceSplitCardsBug](https://user-images.githubusercontent.com/1496996/103803907-e4057e80-5016-11eb-97f4-5a8ec9be8227.png)

**Comment by fhattori** [comment]
When retracing a split card, it gave me only the fuse option and did not let me choose targets. This was tested with wear//tear and retrace ability from Wrenn and Six emblem. Fuse should be only available when the spell is cast from player's hand.

**Comment by jeffwadsworth** [comment]
The emblem needs extra code to handle all card types.  Right now, it handles Adventure cards, but not MDFC and split-cards.  Checking it out tomorrow.
