### ISSUE TITLE
Fixed/Duplicate Issues for closure (through 2000)

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6551]
The following issues are CNR, fixed, or duplicates, and can be closed as such:

### Fixed/Not Reproducible:

- [x] #551 Damage handling of creatures getting first strike after first strike damage dealing step

- [x] #564 Show and Tell not putting cards on the battlefield simultaneously

- [x] #634 AI casts counters on its own spells

- [x] #643 Weird replacement effect (was not supposed to happen)

- [x] #659 Scale text size on abilities with preview image size

- [x] #666 Fate Reforged boosters may only have basic lands if those cards are foil.

- [x] #690 Lands and mana dorks tapping for automatically correct color

- [x] #700 Countering a non-copy spell that has copies on the stack counters one of the copies.

- [x] #905 Stony Silence - not working when playing AI

- [x] #1007 Aesthetic - Dynamically resizing tooltip text box

- [x] #1016 Venser, Shaper Savant error

- [x] #1054 XMage steals window focus whenever the screen updates

- [x] #1093 Joraga Invocation must be reworked

- [x] #1102 Oppressive rays seems to break the AI

- [x] #1122 Change to "tapped for mana" rule.

- [x] #1137 Chain of Vapor + Sensei's Divining Top, Sneak Attack

- [x] #1139 F-keys don't work after graveyard/exile/reveal windows are in focus

- [x] #1142 Add ID of card that causes trigger of Lazav, Dimir Mastermind's triggers on the stack

- [x] #1159 Issue with countering copies of a spell

- [x] #1205 Game draw when opponent concedes?

- [x] #1230 Hand card selection

- [x] #1247 CTRL+F5 causes game window to become tiny, clicking away causes it to disapear, no apparent way to get back into game

- [x] #1364 Deck save in deck editor is not working with double click

- [x] #1372 Delayed triggered abilities of copied cards don't get a source object

- [x] #1510 Suspend cards should not be castable from graveyard/top of library/exile for {0}

- [x] #1635 jace architect of thought: bug when deciding order of cards to go to the bottom

- [x] #1643 GUI - Enchantment offset on battlefield is too small

- [x] #1645 GUI - Pushing CTRL-F6 while modal window (e.g. trigger order) locks Xmage

- [x] #1658 Insufficient logging for Tempting Offer

- [x] #1727 [SOI] Sealed pool generation

- [x] #1740 Flickerwisp is bugged with multiple instances.

- [x] #1829 Phasing does not phase out the attached enchantments properly

- [x] #1857 Cancelling the casting of a spell when choosing to pay mana freezes the client and disconnects

- [x] #1876 Delve abilities should highlight cards selected

- [x] #1892 Using Surge to cast a card from graveyard with Harness the Storm does not work

- [x] #1915 Regular-frame BFZ/OGW basics missing

- [x] #1955 Add Momir Basic Free For All game type

- [x] #1968 Field of Souls game text is wrong

- [x] #2015 Cards that care about exile and are able to use cards exiled from previous invocations

- [x] #2024 Brass Herald Broken

- [x] #2076 Damage wrong when Watcher in the Web blocking multiple creatures

- [x] #2146 Using Future Sight to cast fused Wear/Tear from top of library crashes

### Duplicates:

- [x] #227 An issue about Council of the Absolute

- [x] #1133 Pauper deck legality check

- [x] #1233 Help: High resolution results in tiny program content

- [x] #1927 Errors going to time during tournament

- [x] #2038 Add Planechase Free For All game type

- [x] #2044 Unplayable on small screens

- [x] #2058 Rated games options
