### ISSUE TITLE
Old issues that are still broken

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6552]
### Tested and verified still bugged:

- [ ] #437 Harm's way and Shining Shoal - it's not possible to choose which damage and amount will be redirected if multiple targets get damage from one source

- [ ] #471 Aluren allows to cast the card with flash and pay the mana costs

- [x] #768 Mana abilities should be activated before costs are paid when casting a spell

- [ ] #981 Identifier and morphed or manifested or other face down cards.

- [x] #1072 Meddling Mage + Isochron Scepter

- [ ] #1167 AI gets stuck with two Kiora's Followers

- [x] #1219 Cavern of Souls resets incorrectly

- [ ] #1869 Triggered abilities of tokens have wrong symbol

- [ ] #2008 Savor the Moment - Skips Untap of Wrong Turn

- [ ] #2087 Gisa and Geralf interaction with Risen Execution not implemented correctly

- [ ] #2221 RegenerateAttachedEffect not working on abilities with SacrificeSourceCost

- [ ] #2362 Unwanted asking of user about replacment effect (Planeswalker Loyality.counter)

- [ ] #2382 Undopossible=false mana abilites can be undone by invoking 720.

- [ ] #2383 Costs involving {Q} are paid at the wrong time

- [ ] #2970 Mogg Flunkies + Goblin Assault interaction bugged

- [ ] #3087 3 way cube - Player who goes first doesn't get to draw a card

- [ ] #3160 Notification of a player joining your table no longer working

- [ ] #3296 Tables UI overlaps /strikes through the Deck Editor UI (possibly affects other area when multiple sections are open).

- [ ] #3309 Diluvan Primordial asks spell's owner to play entwine

- [ ] #3334 Shared Fate doesn't post in chat which player was targeted

- [ ] #3402 Nest of Scarabs various issues

- [ ] #3412 XP counters - potential bug

- [ ] #3476 Jeleva ETB resolves without her on battlefield does not exile cards

- [ ] #3515 Blind Obedience causes Xenagod to enter tapped

- [ ]  #3544 Olivia Voldaren bug in Momir Basic.

- [ ]  #3663 Angel of Jubilation

**Comment by Zerrisx** [comment]
Now that I've gone through and checked most of the backlog issues and closed unreproducibles, this is no longer a needed tracker.
