### ISSUE TITLE
M21 Text Issues

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6643]
The following cards' oracle text is not an exact match to the printed text.  In some cases (the shuffle ones in particular), that might still be fine to ignore; feel free to comment if so (and check off that card as "addressed").  Most of these, however, will need to be changed.

# Still Bugged:

- [ ] Enthralling Hold - targeting should be "Select a tapped creature"
![image](https://user-images.githubusercontent.com/59861365/86050053-d42e3180-ba18-11ea-8482-1f62c0ad63c6.png)

- [x] Heartfire Immolator - should deal damage "equal to its power", not whatever this is
![image](https://user-images.githubusercontent.com/59861365/84618533-1b081d00-ae98-11ea-9705-59a84a411630.png)

- [x] Revitalize - "Draw a card." should be on a separate line
![image](https://user-images.githubusercontent.com/59861365/84619007-7edf1580-ae99-11ea-958d-a3a7d70afd3c.png)

- [x] Roaming Ghostlight - has "non-spirit creature" doubled
![image](https://user-images.githubusercontent.com/59861365/91648852-4c719d00-ea32-11ea-8076-3e7ab016b684.png)

- [x] Stormwing Entity - "if instance" should be replaced by the actual trigger condition
![image](https://user-images.githubusercontent.com/59861365/84619684-6cfe7200-ae9b-11ea-97f3-55f8003c9f13.png)

- [x] Wildwood Scourge - remove "on it"
![image](https://user-images.githubusercontent.com/59861365/84620092-a4b9e980-ae9c-11ea-805e-e642086d94e1.png)

# Fixed:

- [x] Alpine Houndmaster - missing "Whenever Alpine Houndmaster attacks, "
![image](https://user-images.githubusercontent.com/59861365/84618125-d9c33d80-ae96-11ea-81b6-033f03da201f.png)

- [x] Barrin, Tolarian Archmage - missing a space
![image](https://user-images.githubusercontent.com/59861365/84724953-12265280-af4f-11ea-9ad9-e773d3c354c9.png)

- [x] Barrin, Tolarian Archmage - their owners' > it's owner's
![image](https://user-images.githubusercontent.com/59861365/84724989-2a966d00-af4f-11ea-9418-90fe7818e0c6.png)

- [x] Battle-Rattle Shaman - gets > get
![image](https://user-images.githubusercontent.com/59861365/84618175-0414fb00-ae97-11ea-8cda-6afabeb3de5d.png)

- [x] Caged Zombie - remove extra "if"
![image](https://user-images.githubusercontent.com/59861365/84840969-aa334300-b006-11ea-9b4e-48047ca80296.png)

- [x] Chandra, Heart of Fire - spells > cards
![image](https://user-images.githubusercontent.com/59861365/84717052-6bd05200-af3a-11ea-91ee-4a0f7a0ef27d.png)

- [x] Dire Fleet Warmonger - The +2/+2 and gains trample should be part of the same sentence/effect
![image](https://user-images.githubusercontent.com/59861365/84618226-2b6bc800-ae97-11ea-881e-883685a1f638.png)

- [x] Discontinuity - The two effects should be in the other order
![image](https://user-images.githubusercontent.com/59861365/84618292-5c4bfd00-ae97-11ea-932a-7f16a378d7dd.png)

- [x] Discontinuity - the reminder text is incomplete - it should also reference exiling the spell itself from the stack, and say that the player *whose turn it is* discards to hand size.
![image](https://user-images.githubusercontent.com/59861365/84618353-86052400-ae97-11ea-8860-ad451193533e.png)

- [x] Experimental Overload - missing a space
![image](https://user-images.githubusercontent.com/59861365/84723947-814e7780-af4c-11ea-8049-7d46302f59e4.png)

- [x] Fierce Empath - shuffling your library isn't part of a separate sentence on the printed card
![image](https://user-images.githubusercontent.com/59861365/84618380-a7661000-ae97-11ea-9818-f30cc1ef5a56.png)

- [x] Goblin Arsonist - "Goblin Arsonist deals" > "it deal"
![image](https://user-images.githubusercontent.com/59861365/84618415-c795cf00-ae97-11ea-9170-5d32813ae0e8.png)

- [x] Grim Tutor - shuffling your library isn't part of a separate sentence on the printed card
![image](https://user-images.githubusercontent.com/59861365/84618471-e8f6bb00-ae97-11ea-9a3a-953f67b62e37.png)

- [x] Jolrael, Mwonvuli Recluse - the entire second ability is wrong
![image](https://user-images.githubusercontent.com/59861365/84618593-4985f800-ae98-11ea-8cba-1f7137a158bd.png)

- [x] Kaervek, the Spiteful - remove "all"
![image](https://user-images.githubusercontent.com/59861365/84618645-68848a00-ae98-11ea-820d-473d6ff71d24.png)

- [x] Kaervek, the Spiteful - should be -1/-1 instead of +1/+1
![image](https://user-images.githubusercontent.com/59861365/90321838-2072f980-df13-11ea-9f27-beec5561f4ff.png)

- [x] Light of Promise - the granted ability should be in quotes
![image](https://user-images.githubusercontent.com/59861365/84618703-8c47d000-ae98-11ea-8409-385e2c573280.png)

- [x] Lorescale Coatl -  the effect is no longer optional - this *looks* like a functional change from WotC similar to what happened with Ajani's Pridemate.  As of right now, Gather Oracle text still agrees with XMage, but I expect that to change.
![image](https://user-images.githubusercontent.com/59861365/84618733-a41f5400-ae98-11ea-93c0-22e44f29e83f.png)

- [x] Malefic Scythe - "When equipped dies" > "Whenever equipped creature dies"
![image](https://user-images.githubusercontent.com/59861365/84618802-d9c43d00-ae98-11ea-81fe-aab9a4a25f7a.png)

- [x] Mangara, the Diplomat - "a planeswalker" > "planeswalkers"
![image](https://user-images.githubusercontent.com/59861365/84618846-fb252900-ae98-11ea-8682-81aefda3ce9a.png)

- [x] Pidemalkin - Missing an "Each" at the beginning, and "have" > "has"
![image](https://user-images.githubusercontent.com/59861365/84618902-24de5000-ae99-11ea-93c2-7faa87fb63b2.png)

- [x] Quirion Dryad - insert "a spell that's" at the arrow, and remove "spell" later on
![image](https://user-images.githubusercontent.com/59861365/84618943-4a6b5980-ae99-11ea-904c-09fb474ddcba.png)

- [x] Rise Again - remove the last bit
![image](https://user-images.githubusercontent.com/59861365/84841106-04cc9f00-b007-11ea-984a-af5e12455af1.png)

- [x] Roaming Ghostlight - "their owners'" > "its owner's"
![image](https://user-images.githubusercontent.com/59861365/84841148-2463c780-b007-11ea-997b-ba46bd221c04.png)

- [x] Runed Halo - the new M21 version changed "name" to "card name" at the end.  Gatherer oracle text doesn't yet reflect this, but I expect it to change when M21 comes out.
![image](https://user-images.githubusercontent.com/59861365/84620746-6291a780-ae9e-11ea-83cc-7dc67aaa694b.png)

- [x] Sanctum of All - "a a" > "a"
![image](https://user-images.githubusercontent.com/59861365/85796865-42fd4900-b700-11ea-9362-53ae3640c93b.png)

- [x] Sanctum of Calm Waters - the trigger has a duplicated phrase
![image](https://user-images.githubusercontent.com/59861365/84976758-569c2480-b0ee-11ea-84bb-27d6ee79c372.png)

- [x] Sanguine Indulgence - the abilities are out of order, and there's also an extra space at the end before the period
![image](https://user-images.githubusercontent.com/59861365/85173446-dfbf7280-b238-11ea-8ee0-3baea1d897b5.png)

- [x] Selfless Savior - must be a creature you control
![image](https://user-images.githubusercontent.com/59861365/84619567-142ed980-ae9b-11ea-931a-efcec187a686.png)

- [x] Solemn Simulacrum - shuffling your library isn't part of a separate sentence on the printed card
![image](https://user-images.githubusercontent.com/59861365/84619586-27da4000-ae9b-11ea-852a-3e23b3dd1d95.png)

- [x] Speaker of the Heavens - remove the duplicate "if"
![image](https://user-images.githubusercontent.com/59861365/84619636-48a29580-ae9b-11ea-81be-ce1c9e45b8f5.png)

- [x] Subira, Tulzidi Caravaneer - second activated ability is missing most of the text
![image](https://user-images.githubusercontent.com/59861365/85471623-511f5e00-b576-11ea-8d60-639482b8aa58.png)

- [x] Swift Response - "permanent" > "creature"
![image](https://user-images.githubusercontent.com/59861365/84841205-4a896780-b007-11ea-8be6-47c009d7d96b.png)

- [x] Teferi's Ageless Insight - "if you draw" > "if you would draw"
![image](https://user-images.githubusercontent.com/59861365/84619801-ce264580-ae9b-11ea-818b-1a0e3d24ac0c.png)

- [x] Track Down - the period after scry 3 should be a comma, and the reminder text should be at the end.
![image](https://user-images.githubusercontent.com/59861365/85184157-53bb4400-b254-11ea-808c-d841ee4c135b.png)

- [x] Traitorous Greed - missing a space
![image](https://user-images.githubusercontent.com/59861365/84619839-e8602380-ae9b-11ea-9a60-1f3ffd6c41ea.png)

- [x] Ugin, the Spirit Dragon - "draw 7 cards" > "draw seven cards"
![image](https://user-images.githubusercontent.com/59861365/84619893-0ded2d00-ae9c-11ea-8ad4-b330f7b8ba4a.png)

- [x] Volcanic Salvo - the abilities should be in the other order
![image](https://user-images.githubusercontent.com/59861365/84619990-56a4e600-ae9c-11ea-872f-a43c0b06136a.png)

- [x] Warden of the Woods - When > Whenever, and > an
![image](https://user-images.githubusercontent.com/59861365/84620034-7fc57680-ae9c-11ea-8852-5139baddfb44.png)

**Comment by acabaca24** [comment]
For the people updating the checkboxes in this issue, **Malefic Scythe** is already fixed in #6991

**Comment by Zerrisx** [comment]
> 
> 
> For the people updating the checkboxes in this issue, **Malefic Scythe** is already fixed in #6991

That would be me, and you're certainly right!  One minor issue, though - Roaming Ghostlight looks to have a new problem with duplicated text.  The rest are all good.

**Comment by acabaca24** [comment]
> > For the people updating the checkboxes in this issue, **Malefic Scythe** is already fixed in #6991
> 
> That would be me, and you're certainly right! One minor issue, though - Roaming Ghostlight looks to have a new problem with duplicated text. The rest are all good.

I'll be looking forward to fix that!

**Comment by acabaca24** [comment]
Well, I guess while testing it I tunnel visioned in the it/their part and forgot to read the rest. Because it was legit a copy paste error. 😓

**Comment by Alex-Vasile** [comment]
Already done and can be checked off 
- Heartfire Immolator
- Revitalize
- Roaming Ghostlight
- Stormwing Entity
- Wildwood Scourge
	- The "on it" should be there when compared to gatherer.wizards oracle text
	- The "creature" underlined has already been fixed
