### ISSUE TITLE
M21 Functional Bugs

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6646]
- [x] Alchemist's Gift - lets you choose Deathtouch or Lifelink, but neither option causes the spell to do anything.  It doesn't even give +1/+1.
![image](https://user-images.githubusercontent.com/59861365/84937679-c506c580-b0a1-11ea-937d-72b0b635b959.png)
![image](https://user-images.githubusercontent.com/59861365/84937712-d059f100-b0a1-11ea-9705-51a3a7c26d24.png)

- [x] Chandra's Incinerator - Not getting any discount after activating Chandra, Flame Catalyst's +1 ability, or casting Lightning Bolt targeting the opponent.
![image](https://user-images.githubusercontent.com/59861365/84698666-cb683680-af15-11ea-80f3-29d49daba591.png)
![image](https://user-images.githubusercontent.com/59861365/84698647-c30ffb80-af15-11ea-9314-3fc949013c5f.png)

- [x] Chandra's Incinerator - Also not dealing damage to a creature or planeswalker after the opponent takes non-combat damage.  (Tested with Lightning Bolt)

- [x] Dire Fleet Warmonger - the Trample gained from sacrificing a creature doesn't go away at end of turn.
![image](https://user-images.githubusercontent.com/59861365/84704183-0cb11400-af1f-11ea-843f-48758a15a109.png)

- [x] Enthralling Hold - is currently behaving as "enchant tapped creature", which is wrong in two ways.  First, if the target becomes untapped in response, the spell should still resolve, not fizzle.  Second, if the target becomes untapped after the spell resolves, it shouldn't go to the graveyard as a result.
![image](https://user-images.githubusercontent.com/59861365/85915174-e8044880-b80a-11ea-9ebe-7daa40768464.png)

- [x] Enthralling Hold - thinks it can be cast when the only creatures in play are untapped, and gives target highlighting to untapped creatures, even though you can't actually select them.
![image](https://user-images.githubusercontent.com/59861365/86049916-a0530c00-ba18-11ea-950e-a4054277c024.png)
![image](https://user-images.githubusercontent.com/59861365/86049969-b791f980-ba18-11ea-8bc1-5210aa8357b2.png)

- [x] Feline Sovereign - currently giving itself protection from dogs, in addition to other cats
![image](https://user-images.githubusercontent.com/59861365/84715861-5ad21180-af37-11ea-8d79-85d2a49a5abd.png)

- [x] Feline Sovereign - the on-hit trigger asks you twice; once to pick a target and a *second* time if you want to destroy it.  (It even asks twice if you didn't initially pick a target)
![image](https://user-images.githubusercontent.com/59861365/84716145-f82d4580-af37-11ea-9ddb-e316cb4d84e6.png)
![image](https://user-images.githubusercontent.com/59861365/84716096-e2b81b80-af37-11ea-932b-1385fe83c138.png)

- [x] Gadrak, the Crown-Scourge - can attack without any artifacts in play
![image](https://user-images.githubusercontent.com/59861365/84702530-66640f00-af1c-11ea-8879-311f0eb4c2be.png)

- [x] Garruk, Savage Herald - the -2 text is weird/wrong for the second target chosen
![image](https://user-images.githubusercontent.com/59861365/84687787-e5991900-af03-11ea-8489-85d26c3a2f94.png)

- [x] Ghostly Pilferer - draw triggers on tap instead of untap
![image](https://user-images.githubusercontent.com/59861365/84725741-f0c66600-af50-11ea-88e1-fb1379fed3ff.png)

- [x] Idol of Endurance - destroying it doesn't put the cards back into the graveyard
![image](https://user-images.githubusercontent.com/59861365/86079030-170dfa80-ba55-11ea-95dd-8d430b8e010f.png)

- [x] Idol of Endurance - if you have a Panharmonicon out, Idol only lets you choose creatures from the second exile trigger, even though both are linked to the ability.
![image](https://user-images.githubusercontent.com/59861365/86078042-ceedd880-ba52-11ea-86b0-8ff83a766943.png)

- [x] Liliana, Death Mage - the +1 asks you twice; once to pick a target and a *second* time if you want to return it.  (It even asks twice if you didn't initially pick a creature)
![image](https://user-images.githubusercontent.com/59861365/84709664-33c01380-af28-11ea-99e3-f31d2dce1061.png)
![image](https://user-images.githubusercontent.com/59861365/84709683-3cb0e500-af28-11ea-8050-5b6bcc9b5220.png)

- [x] Necromentia - only reveals zones that actually contain the card you name.  i.e. if the opponent has the card in their graveyard but not in their deck or their hand, you should still get to see their deck and their hand, but currently you don't.

- [x] Peer into the Abyss - is rounding down rather than up
![image](https://user-images.githubusercontent.com/59861365/84693409-0f0a7280-af0d-11ea-9023-4fd9f20afb67.png)
![image](https://user-images.githubusercontent.com/59861365/84693391-087bfb00-af0d-11ea-92ae-2e35a68af647.png)

- [x] Peer into the Abyss - always affects yourself, regardless of who you target
![image](https://user-images.githubusercontent.com/59861365/86020367-71737080-b9ed-11ea-8af3-461a156f81a6.png)

- [x] Primal Might - gets confused when you don't pick a second target (it is *up to* one).  In chat it claims the spell has fizzled, but it still gives the buff.  It shouldn't claim to have fizzled.
![image](https://user-images.githubusercontent.com/59861365/84704390-5bf74480-af1f-11ea-9576-38879698e3d1.png)
![image](https://user-images.githubusercontent.com/59861365/84704431-6d405100-af1f-11ea-9cc6-f4a01852ae5c.png)

- [x] Read the Tides - only returns one creature with the second option
![image](https://user-images.githubusercontent.com/59861365/84841431-e74c0500-b007-11ea-9b83-11bcb75a8703.png)

- [x] Sanctum of All - shouldn't trigger twice for itself; it only double the effects of *other* shrines.
![image](https://user-images.githubusercontent.com/59861365/85803853-bf4a5900-b70d-11ea-8874-359ef6d6a08f.png)

- [x] Sanctum of Shattered Heights - it doesn't let you pick a target, so it doesn't do anything besides discard the card, and nothing takes damage.
![image](https://user-images.githubusercontent.com/59861365/84976996-e2ae4c00-b0ee-11ea-809e-b0c58082df78.png)

- [x] See the Truth - currently draws three cards all the time, even when you cast it from your hand.
![image](https://user-images.githubusercontent.com/59861365/84712084-5e609b00-af2d-11ea-8399-0f890200feec.png)

- [x] Sublime Epiphany - bouncing and copying the same creature doesn't create a clone of it - but it should, per https://twitter.com/EliShffrn/status/1272252112420745216.

- [x] Terror of the Peaks - triggered ability when other creatures ETB doesn't do anything.
![image](https://user-images.githubusercontent.com/59861365/85472389-634dcc00-b577-11ea-9895-db53fae89fa8.png)
![image](https://user-images.githubusercontent.com/59861365/85472519-8d9f8980-b577-11ea-85c0-7c54743b8cf2.png)

- [x] Thieves' Guild Enforcer - currently giving *every creature you control* deathtouch.
![image](https://user-images.githubusercontent.com/59861365/84705525-22bfd400-af21-11ea-8173-9edd38b3b59a.png)

- [x] Thieves' Guild Enforcer - gets +2/+1 and Deathtouch regardless of how many cards are in each opponent's graveyard.
![image](https://user-images.githubusercontent.com/59861365/84705654-5b5fad80-af21-11ea-9c0a-f8b2e26b6e5b.png)

- [x] Tolarian Kraken - can only tap/untap creatures, but that isn't clear in the prompt you get
![image](https://user-images.githubusercontent.com/59861365/84699105-8ee90a80-af16-11ea-95ad-26392ab495a1.png)

- [x] Unleash Fury - triples power instead of doubling it
![image](https://user-images.githubusercontent.com/59861365/84723630-a68eb600-af4b-11ea-8848-9da6e7890531.png)

- [x] Vito, Thorn of the Dusk Rose - could use some additional clarity on which lifegain event each trigger is for.  If you give your entire team lifelink, you'll often get 5-10 triggers for different amounts, and there's no way to see which is for how much.  In a multiplayer game, you might want to strategically target them, and this makes it much harder.

- [x] Warded Battlements - giving +1/+1 instead of +1/+0
![image](https://user-images.githubusercontent.com/59861365/84841624-79540d80-b008-11ea-8ebb-6e80a16de9a2.png)

- [x] Wildwood Scourge - currently triggers from +1/+1 counters getting added to Hydras, which it shouldn't.  (This also makes two copies of it go infinite)
![image](https://user-images.githubusercontent.com/59861365/84710682-52270e80-af2a-11ea-81af-dcac76164dc4.png)

**Comment by Zerrisx** [comment]
Looks like everything's been addressed - great job y'all! Further issues can stand alone.
