### ISSUE TITLE
Blocks or becomes blocked (not by a creature)

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6660]
The following cards should trigger when they block or become blocked *in any way*, for example with the newly implemented Choking Vines.  However, currently they all appear to be coded to only trigger if they block or become blocked *by a creature*, which is wrong.

example:
![image](https://user-images.githubusercontent.com/59861365/84944074-dbfde580-b0aa-11ea-839d-96d133067cb1.png)

- [x] Alley Grifters

- [x] Bestial Fury

- [x] Brushwagg

- [x] Chub Toad

- [x] Corrupt Official

- [x] Dromosaur

- [x] Escaped Null

- [x] Flint Golem

- [x] Goblin Cadets

- [x] Goblin Elite Infantry

- [x] Karn, Silver Golem

- [x] Laccolith Rig

- [x] Raging Gorilla

- [x] Slate Street Ruffian

- [x] Slinking Giant

- [x] Thresher Beast

**Comment by arcox** [comment]
Thanks for writing up this list, I noticed the same while testing against Brushwagg
