### ISSUE TITLE
Jumpstart Functional Bugs

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6677]
- [x] Archaeomender - allows you to return Enchantments as well
![image](https://user-images.githubusercontent.com/59861365/85183747-751b3080-b252-11ea-8521-b27a18f4f9e3.png)

- [x] Aven Gagglemaster - also counting opponent's creatures with flying; should only count yours
![image](https://user-images.githubusercontent.com/59861365/85175548-52cae800-b23d-11ea-969f-6b899c760768.png)
![image](https://user-images.githubusercontent.com/59861365/85175565-59f1f600-b23d-11ea-9661-7389cd2876a2.png)

- [x] Inniaz, the Gale Force - the control switching ability isn't working quite right.  In a two-player game, it asks me to choose a permanent for my opponent to give to me... and a permanent for me *to also give to me*.  My opponent gets nothing.
![image](https://user-images.githubusercontent.com/59861365/85819583-b8394000-b739-11ea-98ba-f7f98f9b03cb.png)

- [x] Neyith of the Dire Hunt - doesn't just double power - it adds the creature's power to both power *and toughness*.
![image](https://user-images.githubusercontent.com/59861365/86196543-150d6f80-bb19-11ea-9dd8-76a95c521b56.png)
![image](https://user-images.githubusercontent.com/59861365/86197722-9cf47900-bb1b-11ea-9bc5-8abc470eea20.png)

- [x] Neyith of the Dire Hunt - doesn't trigger off blocks.  At all.
![image](https://user-images.githubusercontent.com/59861365/86196662-59990b00-bb19-11ea-9a08-bcf58a6e1b73.png)

- [x] In a multiplayer game, Neyith triggers once per player who blocks your creatures, instead of once per round of blocks.
![image](https://user-images.githubusercontent.com/59861365/86310262-3cc90a00-bbe3-11ea-85b9-0108dacdcc57.png)

- [x] Neyith of the Dire Hunt - doesn't handle blocks outside creatures in the declare blockers step - Balduvian Warlord, Choking Vines, etc
![image](https://user-images.githubusercontent.com/59861365/86380349-9b2cd180-bc51-11ea-8ff7-8c9669644639.png)
![image](https://user-images.githubusercontent.com/59861365/86380308-9405c380-bc51-11ea-8d95-822935d9e7d0.png)

- [x] Ormos, Archive Keeper - the first ability never triggers.  You don't lose the game for drawing from an empty library, but it also doesn't put any counters on Ormos.
![image](https://user-images.githubusercontent.com/59861365/85175844-03d18280-b23e-11ea-8d3a-865c37fb9cec.png)

- [x] Ormos, Archive Keeper - the three cards aren't being forced to all have different names
![image](https://user-images.githubusercontent.com/59861365/85175763-cc62d600-b23d-11ea-8f36-137c63d3369e.png)

- [x] Rookie Mistake - lets you target the same creature twice, which it shouldn't
![image](https://user-images.githubusercontent.com/59861365/85175301-bdc7ef00-b23c-11ea-8ef8-94be96d63195.png)

- [x] Tinybones, Trinket Thief - the activated ability doesn't seem to work; I activated it when my opponent had no cards in hand, but they didn't lose any life
![image](https://user-images.githubusercontent.com/59861365/85245897-a3456f80-b40e-11ea-882f-a0108f09ea76.png)

- [x] Thriving Lands - could *really* use some dynamic reminder text to remind you which other color they tap for when you click on them.  Especially if you have multiple Thriving Moors that tap for different other colors, this is not a helpful dialogue box.
![image](https://user-images.githubusercontent.com/59861365/85174730-8d338580-b23b-11ea-8925-a2d6dfc762d8.png)

- [x] Zurzoth, Chaos Rider - the "when devils attack" ability doesn't do anything.  It triggers, and resolves, but nobody draws or discards anything.
![image](https://user-images.githubusercontent.com/59861365/85915358-58f83000-b80c-11ea-9742-218b839a2f40.png)

**Comment by Zerrisx** [comment]
Looks like everything's been addressed - great job y'all!  Further issues can stand alone.
