### ISSUE TITLE
Community Requested Formats

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6766]
Creating this as a catch-all for various sanctioned or unsanctioned formats that have been requested.  These are listed in order by issue number, with no consideration for which would be easier to implement or more enjoyable to play.

- [ ] Two-Headed Giant #349
https://mtg.fandom.com/wiki/Two-Headed_Giant

- [ ] Winchester Draft #431
https://magic.wizards.com/en/articles/archive/latest-developments/winchester-draft-2011-05-20

- [ ] Vanguard #1413
https://mtg.gamepedia.com/Vanguard_(format)

- [ ] Mental Magic #2635
https://mtg.gamepedia.com/Mental_Magic

- [ ] Draft Leagues #3091
https://magic.wizards.com/en/articles/archive/magic-digital/magic-online-leagues-circle-complete-2016-08-24

- [ ] Team Limited / Team Constructed #3699
https://magic.wizards.com/en/articles/archive/top-decks/team-trios-constructed-pro-tour-standard-2018-07-31

- [ ] Rarity Restriction (i.e. Magic Duels) #4432
https://magicduels.fandom.com/wiki/Rarity

- [ ] 15-Card Highlander #5039
https://www.cardknocklife.com/introducing-fifteen-card-draft-cube/

- [ ] Singleton #5054
https://mtg.gamepedia.com/Singleton

- [ ] Battle Box #6213
https://mtgbattlebox.com/rules/

- [ ] German Highlander #6302
http://highlandermagic.info/banned-list/

- [ ] EDH Cube Draft #6386
(Can't find any official format rules for this one)

And associated request #4163 to support team games in general

**Comment by duelcastermage** [comment]
Could you please also add [Archon](https://archon.page/) to this list?

Thanks!

**Comment by ketsuban** [comment]
I move to disqualify Mental Magic - I'm not sure having to pick a spell from memory really works in a medium where you can just pull up a browser window and open Scryfall.

**Comment by Zerrisx** [comment]
Closed all sub-issues that didn't add meaningful information beyond describing the rules of a format that can be looked up in a more official location.

**Comment by JayDi85** [comment]
@Zerrisx don't close independent issues. It can be combined in one issue for a more complete overview, but all discussions and requests must be under different tasks.

Combine and close only duplicated issues with same reason/source. As example: 
* AI targets it's own permanents instead opponents -- it's same bug's source (wrong outcome in target settings);
* AI can't play cards or do it wrong (e.g. taped for nothing) -- it's can be different bugs with different reason, so it can't be combined in one. Only as tracking, but not duplicated/closed.
* AI can't play one card -- all card's related issues can be closed as duplicate.

**Comment by Zunon** [comment]
I move to request that [Conquest](https://conquesthub.wordpress.com/), a commander multiplayer competitive variant be added as well.
Notably The format has its own post-mulligan "scry rule" that makes players scry X where X is their seating order, starting player scrying 0, then the player after that scries 1, and so forth.
