### ISSUE TITLE
Stop Hitting Yourself: AI chooses itself as target for detrimental effects

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6838]
The AI sometimes targets itself or its own permanents with effects that are mostly or completely detrimental, or targets the opponent with effects that are mostly or completely beneficial.  This should be avoided.

Since these types of issues can be intermittent or difficult to reproduce - and are also low priority - I'm just combining them all into one tracking issue, rather than testing to see which still occur.  Some issues listed here may already be fixed.

- [ ] AI targets its own cards in graveyard with Surgical Extraction #1227

- [ ] AI destroys its own permanents with Aura Shards #5704

- [ ] AI grafts onto opponents' creatures with Aquastrand Spider #5705 

- [ ] AI destroys its own lands with Beast Within #5775

- [ ] AI chooses itself with Saskia, the Unyielding #5810

- [ ] AI destroys its own permanents with Angel of Despair #5849

- [ ] AI uses Maze of Ith on its own attackers #5850

- [ ] AI buffs opponents' creatures with Retreat to Hagra #5909

- [ ] AI attaches Shielded by Faith to opponents' creatures #6335

- [ ] AI damages its own creatures with Sword of Fire and Ice #6341

- [ ] AI enchants its own creatures with Inevitable End #6363

- [ ] AI gives creatures attacking it double strike with Duelist's Heritage #6376

**Comment by copperfield42** [comment]
I was thinking about making a new issue, but I guess I mention it here better: 

AI target it own _Quarry Colossus_ with its effect.

Now I see Aura Shards mention here, same apply to _Qasali Slingers_
