### ISSUE TITLE
Why would you do that: AI takes actions that have no (meaningful) effect

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6839]
The AI sometimes takes actions that don't affect the board state, but cost time or resources, even when better actions that would affect the board state are also available. This should be avoided.

Since these types of issues can be intermittent or difficult to reproduce - and are also low priority - I'm just combining them all into one tracking issue, rather than testing to see which still occur. Some issues listed here may already be fixed.

- [ ] AI with two Kiora's Followers will just use them to untap each other #1167

- [ ] AI will tap and untap Basalt Monolith repeatedly #2023

- [ ] AI crews vehicles in second main phase (and even when summoning sick) #4166

- [ ] AI casts pump spells on its creatures when nothing threatens them and they cannot attack #4458

- [ ] AI taps creature lands to pay for their own cost of activation #5615

- [ ] AI re-activates creature lands that are already animated (i.e. Mishra's Factory) #5615 #6172

- [ ] AI will bounce the land it just played when playing karoo/bounce lands #5773

- [ ] AI targets indestructible creatures with Dark Hatchling #5778

- [ ] AI casts Astral Cornucopia with X=0 #5894

- [ ] AI re-equips Shining Armor to already equipped creature #6107

- [ ] AI discards cards to pump Vampire Hounds when it can't attack #6118

- [ ] AI uses Thespian's Stage to copy itself #6145

- [ ] AI names colors that haven't been observed in the game with Prismatic Circle #6237

- [ ] AI will regenerate beasts with Krosan Warchief when those beasts are not in danger of dying #6280

- [ ] AI will use Marath, Will of the Wild's ability to take off and return the same counters #6281

- [ ] AI will activate First of the Suns and Jodah, Eternal Archmage to cast already castable spells that cost less than five mana #6358

- [ ] AI will cast Journey to Nowhere and Oblivion Ring without targets on the battlefield #6425

- [ ] AI will pay life to regenerate Marrow Bats when it is not in danger of dying #6587

**Comment by JayDi85** [comment]
@Zerrisx  don't close related issues. It's a different tasks with different bug reason and fixes.

**Comment by copperfield42** [comment]
I was thinking of making a new issue for some of those, but I guess I mention it here better: 

The AI bounce the bounce land when there are not a basic in play, more specifically, turn 1 play _Temple Garden_, turn 2 _Selesnya Sanctuary_ and bounce it, repeat this for like 3 turn in a row until star playing other land and later when it have a basic in play Santuary again and bounce a tap basic.

Every turn activate _Detection Tower_ or _Shadowspear_ for basically no reason, in the case Shadowspear it used several times wasting all its mana on it either on its turn or across several turns (tho one time is was kind of funny because it was beneficial to me)

I guess this apply to Equipment that don't grant stats bonus in general: the AI waste all its mana moving _Swiftfoot Boots_ around on its creatures, last I try it was several version ago so I change it to _Lightning Greaves_, still waste time moving it around but at least it does not waste mana on it with that one. Tho _Whispersilk Cloak_ seem to use it well, so I guess the equip cost is also a factor

It play _Prototype Portal_ without imprinting anything, and later activate it to do nothing. I observe this one once, but I change the card immediately none the least.

It always took all the cards with _Sylvan Library_ even if that kill it.

Sometime it fog itself with _Glacial Crevasses_ (I mentioned this one as part of a previous issue)

Does not untap anything under _Smoke_ effect, when I guess the most valuable creature is already untap.

It produce colors outside of its color identity with _Selvala, Heart of the Wilds_

Spam _Asceticism_ effects on its creatures, sometimes several times on the same creature.

---

Well those are some of the _why would you do that_ moments that come to mind at this time while playing with the AI

**Comment by allentiak** [comment]
@Zerrisx You might want to add #6697 to your list...

**Comment by Zerrisx** [comment]
> 
> 
> @Zerrisx You might want to add #6697 to your list...

That play is impressively dumb... but it does at least do *something*.  I'm trying to restrict this just to actions that are equivalent to tapping 3 mana because you can, then saying go.

**Comment by jeffwadsworth** [comment]
I always tried to avoid putting AI specific code on the cards, but in order to fix many of these issues, that may be the only way.  JayDi's trigger check for Duelist's Heritage is just one example.  A while back, I believe it was LevelX2 who added code to try and stop repetitive actions by the AI, but it had limited success.  I will experiment with some simple checks and see how it goes.

**Comment by JayDi85** [comment]
BTW current test framework supports full AI testing. Commands:
* `aiPlayPriority()`
* `aiPlayStep()`

That's commands can be run after battlefield prepare (search commands for examples).

So all that repeats and wrong actions can be tested by unit tests. Even more -- you can see AI logs with actions list and scores tree (why it used or not used some actions or why AI repeats it).

**Comment by jeffwadsworth** [comment]
I was testing the checkForRepeatedAction() code and it doesn't detect the Basalt Monolith cycle.  The test suite used for it is not correct.  Working on that aspect first.

**Comment by copperfield42** [comment]
I have some more _why would you do that_ moments

-cast X spell or used X activated abilities with X=0, some examples include: _Increasing Confusion_ (casted for 0) and _Folio of Fancies_ (activated for x=0)
-_Shred Memory_ (targeting cards for multiples greveyards)
-_Selhoff Occultist_ (mill itself)
-Attack with creatures that die to effects of cards on the field like: _Powerstone Minefield_, _Circle of Flame_, _Caltrops_ 
-Cast a boost spell or use a boost ability on a creature that isn't involve in combat or anything that care about power/thoughtness or do soo in the post combat main phase: like casting _Overwhelming Stampede_ or putting _Craterhoof Behemoth_ with a _Natural Order_ on main 2, or using a _Rhonas the Indomitable_ or Arahbo's abilities on creatures that can't attack that turn or the weren't declared as attackers.
-flip jace, PW side +1 on its own creatures
-use _Rogue's Passage_ on opponent creature, when itself is creatureless
-not untapping any tap land under _Winter Orb_ when it have untap land
-And oldie, but I guess is worth mentioning too, don't block a lethal attack and not block in general unless blocker can survive or trade on stats alone even if it have other abilities that make it a good blocker.

**Comment by ziqueiros** [comment]
I think we may need a new approach to all of this. Please let me know if there is any reddit, discord or something to talk about all this issues.

**Comment by allentiak** [comment]
I think the answer is simple: card-by-card-based pseudo-AI algorithms
simply do not scale for an ever-growing card universe. Period.
Depending in the context, the same effect ("discard three cards"), even if
applied to the same target, can be good or bad.

The only similar project I know of that really shines on the AI aspect is
Magarena.

>
