### ISSUE TITLE
Tokens must be reworked (missing tokens from old sets, broken images)

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6955]
Now that pull #6190 for card images has been merged, it should be safer / easier to clean up token images in similar ways.  In particular, the following issues:

- [x] #5622 Need verify checks for missing or wrong tokens (enable and run `test_checkMissingTokenData` for more bugs/errors)
- [x] #4533 Various Token Issues
- [x] #6701 missing token image in gameplay & random token img in c20 card viewer
- [x] #5767 Images: tokens source is broken (tokens.mtg.onl)
- [ ] #2158 Fallback to alternate art for cards that are missing art

Documenting that 1) a lot of tokens are linking incorrectly or are missing, and 2) if a token can't be found for a given art, we should fall back to any other art of it we do have, to minimize the number of times we show art-less tokens.

**Comment by Zerrisx** [comment]
@timhae You mentioned interest in this project, if you'd still like it.

**Comment by Alex-Vasile** [comment]
@PurpleCrowbar See which of these you are closing with your PRs

**Comment by JayDi85** [comment]
There is special test `test_checkMissingTokenData` with extra checks for tokens. It's disabled by default but can show different problems like wrong token class names, wrong token usage, miss constructors, miss token images in `card-pictures-tok.txt`, etc.

**Comment by Jieiku** [comment]
How can I test which Tokens I am missing?

In the image downloader I can see I am missing 32 card images and 238 token images....

I got most of the missing card images here using the clipboard option: https://github.com/magefree/mage/issues/9249#issuecomment-1457490644

**Comment by Jieiku** [comment]
Does anyone know someplace else that all tokens can be downloaded?

**Comment by JayDi85** [comment]
Not actual anymore
