### ISSUE TITLE
ZNR Text Issues

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#7044]
The following cards' oracle text is not an exact match to the printed text.
*Current up to the implementation of Akiri, Fearless Voyager.*

- [x] Blood Price: "hand. Put the rest" > "hand, and the rest".
![image](https://user-images.githubusercontent.com/59861365/93940809-c7a53680-fcf2-11ea-8bdc-0a132305b010.png)

- [x] Deliberate - remove the extra period and move the hint text to the end of the section
![image](https://user-images.githubusercontent.com/59861365/92634127-6cf2f000-f299-11ea-9b02-bc54e1fd2673.png)

- [x] Emeria Captain - "Emeria Captain" > "it"
![image](https://user-images.githubusercontent.com/59861365/92316704-688ab680-efbd-11ea-922c-ae9ad87b9b94.png)

- [x] Farsight Adept - has an extra random period (and corresponding capital letter)
![image](https://user-images.githubusercontent.com/59861365/92316749-fc5c8280-efbd-11ea-9fa9-7b9254c5dee2.png)

- [x] Inscription of Abundance - remove "another"
![image](https://user-images.githubusercontent.com/59861365/92633809-f35b0200-f298-11ea-971d-2245437fe904.png)

- [x] Inscription of Insight - remove the extra period and move the hint text to the end of the section
![image](https://user-images.githubusercontent.com/59861365/92633938-256c6400-f299-11ea-9f24-eee1b74e9bc5.png)

- [x] Inscription of Ruin - remove "under your control"
![image](https://user-images.githubusercontent.com/59861365/92634063-5187e500-f299-11ea-93a0-42b4c35f37ef.png)

- [x] Khalni Ambush// - remove "another"
![image](https://user-images.githubusercontent.com/59861365/93530596-73b9dc80-f903-11ea-8c2d-40b93ef4db64.png)

- [x] Legion Angel - "Choose card" > "Choose a card"
![image](https://user-images.githubusercontent.com/59861365/92336604-00dd7580-f068-11ea-9495-12571294e15f.png)

- [x] Malakir Blood-Priest - "your" > "the"
![image](https://user-images.githubusercontent.com/59861365/93937629-b6a5f680-fced-11ea-91ba-fdc48697cabf.png)

- [x] Nighthawk Scavenger - seems to think it starts as an 0/3, it should start as a 1/3.
![image](https://user-images.githubusercontent.com/59861365/92317016-75110e00-efc1-11ea-93f0-0b7bbcf3da24.png)

- [x] Pelakka Predation// - "player" > "opponent", and remove "from it" from the end of the second sentence
![image](https://user-images.githubusercontent.com/59861365/93533024-bf6e8500-f907-11ea-9f3f-3eff43c21add.png)

- [x] Soaring Thought-Thief - "you attack with one or more rogues" > "one or more rogues you control attack"
![image](https://user-images.githubusercontent.com/59861365/92981085-07039580-f45e-11ea-909d-cf11f61189bb.png)

- [x] Tajuru Paragon - missing a period at the end
![image](https://user-images.githubusercontent.com/59861365/93291862-dd25d800-f7a9-11ea-8095-dee9ef7c1cab.png)

- [x] Thieving Skydiver - missing the kicker helptext
![image](https://user-images.githubusercontent.com/59861365/93939066-d8a07880-fcef-11ea-96d0-355f32893890.png)

- [x] Windrider Wizard - "card, if you do discard a card." > "card. If you do, discard a card.".
![image](https://user-images.githubusercontent.com/59861365/92317146-2ebcae80-efc3-11ea-9589-a0a87b6dc9e4.png)

### Verified Fixed
<details>

- [x] Kicker - all kickers are wrong; they have an extra "-" that shouldn't be there, and the helptext is different.  I don't think kicker has changed in this set, so we should continue to use the old templating.
![image](https://user-images.githubusercontent.com/59861365/92316557-793a2d00-efbb-11ea-9b65-05918bf5c00d.png)
For comparison:
![image](https://user-images.githubusercontent.com/59861365/92316563-94a53800-efbb-11ea-987a-0b3c7b9b1f6d.png)

- [x] Kicker - the kicker text on the three inscriptions is wrong; they have an extra "-" that shouldn't be there, and the helptext is different.  I don't think kicker has changed in this set, so we should continue to use the old templating.
![image](https://user-images.githubusercontent.com/59861365/93940689-90368a00-fcf2-11ea-9911-d6f88cde82ec.png)

- [x] All the Inscriptions have an extra "--" that shouldn't be there
![image](https://user-images.githubusercontent.com/59861365/92633676-bbec5580-f298-11ea-8a80-85bdcf7b3785.png)

Party - four cards are missing the Party hint text.

- [x] Concerted Defense
- [x] Drana's Silencer
- [x] Practiced Tactics
- [x] Strength of Solidarity) 

![image](https://user-images.githubusercontent.com/59861365/92633173-fdc8cc00-f297-11ea-8a2e-4e08c0312766.png)
![image](https://user-images.githubusercontent.com/59861365/92633456-6f087f00-f298-11ea-9a1e-0873c8e445cb.png)
![image](https://user-images.githubusercontent.com/59861365/92633493-77f95080-f298-11ea-99aa-bff10600f1c1.png)
![image](https://user-images.githubusercontent.com/59861365/92633520-7fb8f500-f298-11ea-8a7a-5a985fc4b1fb.png)

- [x] Acquisitions Expert - this card is off in... many ways.  "Target player" should be "target opponent".  "equal to creature" should be "equal to the number of creatures".  The helptext shouldn't have a period after the parenthesis, and it should go at the end instead of in the middle.  "You choose a one card of them" should be "you choose one of those cards".
![image](https://user-images.githubusercontent.com/59861365/92316593-03829100-efbc-11ea-8379-6946a4d9a61f.png)

- [x] Ancient Greenwarden - "land cards" > "lands"
![image](https://user-images.githubusercontent.com/59861365/92635626-c65c1e80-f29b-11ea-9c70-3808506b621a.png)

- [x] Archpriest of Iona - "creature" > "creatures"
![image](https://user-images.githubusercontent.com/59861365/92316539-3d06cc80-efbb-11ea-94a7-0fe8dfdd75ca.png)

- [x] Attended Healer - "When" > "Whenever" and move the hint to the end of the section
![image](https://user-images.githubusercontent.com/59861365/92633097-e12c9400-f297-11ea-9c9e-ceb3de1e9179.png)

- [x] Cleric of Life's Bond - "When" > "Whenever"
![image](https://user-images.githubusercontent.com/59861365/92316647-dd112580-efbc-11ea-831f-40d38fc79b8c.png)

- [x] Coveted Prize - the two sections are out of order
![image](https://user-images.githubusercontent.com/59861365/92980934-7d53c800-f45d-11ea-8c30-3cba73b7ffd6.png)

- [x] Deadly Alliance - the two parts should be in the opposite order
![image](https://user-images.githubusercontent.com/59861365/92316667-2c575600-efbd-11ea-8ef0-36df28d834f4.png)

- [x] Expedition Champion - "warrior" > "Warrior"
![image](https://user-images.githubusercontent.com/59861365/92316712-7d674a00-efbd-11ea-8f40-e3297d08c0a5.png)

- [x] Forsaken Monument - "Colorles" > "Colorless"
![image](https://user-images.githubusercontent.com/59861365/93270874-97e8b280-f777-11ea-8080-1b4c38f95daf.png)

- [x] Glasspool Mimic// - missing a period at the end
![image](https://user-images.githubusercontent.com/59861365/93530373-1aea4400-f903-11ea-81f8-883bac789f93.png)

- [x] Grotag Bug-Catcher - "Grotag Bug-Catcher" > "it"
![image](https://user-images.githubusercontent.com/59861365/92316762-15653380-efbe-11ea-807e-d0be92543e17.png)

- [x] Hagra Mauling// - replace the "if instance" with the actual condition
![image](https://user-images.githubusercontent.com/59861365/93530435-33f2f500-f903-11ea-9617-4e6367c64f43.png)

- [x] Jace, Mirror Mage - missing a comma
![image](https://user-images.githubusercontent.com/59861365/92316787-670dbe00-efbe-11ea-87f4-7daa006ce383.png)

- [x] Kazandu Mammoth// - "+1/+1" > "+2/+2"
![image](https://user-images.githubusercontent.com/59861365/93530551-5b49c200-f903-11ea-94c4-9c69b867dd05.png)

- [x] Lotus Cobra - likely as an eratta for ease of play, *this trigger is no longer optional*.
![image](https://user-images.githubusercontent.com/59861365/92316847-3417fa00-efbf-11ea-940f-4b867760cb35.png)

- [x] Lullmage's Domination - has the completely wrong target in the second section
![image](https://user-images.githubusercontent.com/59861365/92634222-93189000-f299-11ea-95ad-72aeb2b7b54e.png)

- [x] Malakir Blood-Priest - has an entire half a sentence that's weird.  "1 life for each creature in your party." > "X life", and then move the help text to the bottom.
![image](https://user-images.githubusercontent.com/59861365/92316967-d5ec1680-efc0-11ea-9717-f44c461d8d39.png)

- [x] Molten Blast - the first ability is wrong
![image](https://user-images.githubusercontent.com/59861365/92634286-adeb0480-f299-11ea-8729-2de67fa3dbca.png)

- [x] Myriad Construct - "colourless" > "colorless"
![image](https://user-images.githubusercontent.com/59861365/92635694-dd9b0c00-f29b-11ea-9eea-5afa8fafbbc9.png)

- [x] Nissa of Shadowed Boughs - completely missing the +1 ability
![image](https://user-images.githubusercontent.com/59861365/93271008-e26a2f00-f777-11ea-8789-61a2612365e8.png)

- [x] Ravager's Mace - there shouldn't be a period after "party", and the helptext should go at the end.
![image](https://user-images.githubusercontent.com/59861365/92317076-084a4380-efc2-11ea-9208-680180fb9d72.png)

- [x] Relic Robber - "target" > "that"
![image](https://user-images.githubusercontent.com/59861365/92634375-d672fe80-f299-11ea-8e9a-34173bbf8933.png)

- [x] Scale the Heights - "that" > "up to one target"
![image](https://user-images.githubusercontent.com/59861365/92634490-002c2580-f29a-11ea-8b70-adaacb2a5bd1.png)

- [x] Scourge of the Skyclaves - remove "the number of" before 20
![image](https://user-images.githubusercontent.com/59861365/92980991-b2f8b100-f45d-11ea-9008-2b0739f86eba.png)

- [x] Sea Gate Stormcaller - the first piece of text is duplicated
![image](https://user-images.githubusercontent.com/59861365/92981046-df143200-f45d-11ea-9431-42a4db3ff461.png)

- [x] Spoils of Adventure - the two parts are out of order
![image](https://user-images.githubusercontent.com/59861365/92317116-ba820b00-efc2-11ea-8f15-021ac1263da7.png)

- [x] Sure-Footed Infiltrator - missing "this turn" at the end of the first ability.
![image](https://user-images.githubusercontent.com/59861365/92317351-37ae7f80-efc5-11ea-99f5-8f01dd71564d.png)

- [x] Tajuru Paragon - missing the if it was kicked clause on the ability
![image](https://user-images.githubusercontent.com/59861365/92635810-0b805080-f29c-11ea-8565-9626b5bcedf6.png)

- [x] Thieving Skydiver - missing the "X can't be 0" line.
![image](https://user-images.githubusercontent.com/59861365/93277861-9ffd1e00-f788-11ea-8feb-bfe9ade0c28e.png)

- [x] Throne of Makindi - "three" > "two"
![image](https://user-images.githubusercontent.com/59861365/92981124-2e5a6280-f45e-11ea-8c71-f7b0bfde91c6.png)

- [x] Thwart the Grave - the two parts are out of order
![image](https://user-images.githubusercontent.com/59861365/92317136-1b114800-efc3-11ea-9e83-5231c3802ff1.png)

- [x] Yasharn, Implacable Earth - Three issues: first, "Yasharn, Implacable Earth" > "Yasharn", second, "creatures" > "nonland permanents", third, the period before "Or" shouldn't be there.
![image](https://user-images.githubusercontent.com/59861365/92660618-5d3ad200-f2c0-11ea-8975-0b116b70c4f4.png)

- [x] Zareth San, the Trickster - missing an "an" in the first sentence.
![image](https://user-images.githubusercontent.com/59861365/92981163-51851200-f45e-11ea-8170-cd7d07462da2.png)

- [x] Zof Consumption// - missing the part about you gaining 4 life
![image](https://user-images.githubusercontent.com/59861365/93530723-a8c62f00-f903-11ea-9a8d-91a17c9970ba.png)
</details>

**Comment by theelk801** [comment]
Not sure if we're gonna be able to fix the #5019 problem, it's surprisingly annoying to deal with.

**Comment by Zerrisx** [comment]
Yeah, I assume it's not unique to this set, so it probably wants to be examined separately from this issue; I don't mind splitting it out.
