### ISSUE TITLE
ZNC - Zendikar Rising Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7059]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Implemented Cards
 

- [x] Done -- [Anowon, the Ruin Thief](https://scryfall.com/search?q=!"Anowon,+the+Ruin+Thief")
- [x] Done -- [Enigma Thief](https://scryfall.com/search?q=!"Enigma+Thief")
- [x] Done -- [Geode Rager](https://scryfall.com/search?q=!"Geode+Rager")
- [x] Done -- [Obuun, Mul Daya Ancestor](https://scryfall.com/search?q=!"Obuun,+Mul+Daya+Ancestor")
- [x] Done -- [Trove Warden](https://scryfall.com/search?q=!"Trove+Warden")
- [x] Done -- [Whispersteel Dagger](https://scryfall.com/search?q=!"Whispersteel+Dagger")

**Comment by theelk801** [comment]
- [ ] In progress -- [Anowon, the Ruin Thief](https://scryfall.com/search?q=!"Anowon,+the+Ruin+Thief")
- [ ] In progress -- [Geode Rager](https://scryfall.com/search?q=!"Geode+Rager")
- [ ] In progress -- [Obuun, Mul Daya Ancestor](https://scryfall.com/search?q=!"Obuun,+Mul+Daya+Ancestor")
- [ ] In progress -- [Trove Warden](https://scryfall.com/search?q=!"Trove+Warden")
- [ ] In progress -- [Whispersteel Dagger](https://scryfall.com/search?q=!"Whispersteel+Dagger")

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"Anowon,%20the%20Ruin%20Thief"or!"Geode%20Rager"or!"Obuun,%20Mul%20Daya%20Ancestor"or!"Trove%20Warden"or!"Whispersteel%20Dagger"&unique=cards)
