### ISSUE TITLE
ZNC Functional Bugs and Text Issues

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#7085]
### Verified Fixed:
<details>

- [x] Anowon, the Ruin Thief - the mill trigger resolves, but doesn't mill anything.
![image](https://user-images.githubusercontent.com/59861365/94348535-bf0a7400-0002-11eb-9639-ac18b87a7f8b.png)

- [x] Enigma Thief - missing the third ability, both functionally and in the text.
![image](https://user-images.githubusercontent.com/59861365/94348447-02b0ae00-0002-11eb-880d-e881f903b712.png)

- [x] Geode Rager - missing the second ability, both functionally and in the text.
![image](https://user-images.githubusercontent.com/59861365/94348461-165c1480-0002-11eb-951f-c2cccbe98bd0.png)

- [x] Trove Warden's ability triggers, but does nothing - here I have three permanents exiled, but none are returned to the battlefield.
![image](https://user-images.githubusercontent.com/59861365/94348715-1a893180-0004-11eb-8a18-4f39beaf0d44.png)

- [x] Whispersteel Dagger - the cast a creature from the graveyard ability triggers, but doesn't do anything.  You can see me here in second main phase, having triggered it, against an opponent with a graveyard of creatures and open mana, but I can't cast any of them.
![image](https://user-images.githubusercontent.com/59861365/94348631-7901e000-0003-11eb-9d76-99480a2d91e4.png)

- [x] Whispersteel Dagger - has a period that shouldn't be there - "and. You" > "and you"
![image](https://user-images.githubusercontent.com/59861365/94348480-37246a00-0002-11eb-98c7-881f74628030.png)

</details>

**Comment by Zerrisx** [comment]
All of the fixes look good; closing issue.
