### ISSUE TITLE
GUI: auto-replace card images in gameplay to specific sets (and more)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#7182]
Original problem: opponents can use old or rare card versions, so you don't have images for that card or you like another images.

It's a card images replacement on client side only while playing games (example: game shows card from old set, but uses image from the new). Deck editor must show original images.

Most requested feature: replace all lands by full size version from specific set.

Possible preferences options:
* [ ] replace all basic lands to specific set;
* [ ] replace missing images by basic set (if available);
* [ ] use only basic set images (replace all promo cards to normal -- if available);
* [ ] use images from latest basic set only (help to replace old cards but newest versions);

**Comment by Alex-Vasile** [comment]
Can I re-assign this to myself and look into it?

**Comment by JayDi85** [comment]
Yes, feel free to take it.
