### ISSUE TITLE
[CMR] Bugs in Commander Legends

### ISSUE THREAD

**Issue by NekoNL** [magefree/mage#7198]
* [x] Hellkite Courser's ETB does not work
* [x] Krark, the Thumbless: Casting a lightning bolt and failing flip 1 and then winning flip 2. While the copy was on the stack and the lightning bolt back in hand, i was not allowed to cast the lightning bolt until the copy resolved. Can be related to #7192
* [x] Belbe, Corrupted Observer does not give the mana on combat damage or any lifeloss.
* [x] Riverglide pathway. The land only gives red mana on any mode chosen. Do not know if this is the case for the other versions. Fixed in related issue #7188

**Comment by JayDi85** [comment]
Hellkite Courser fixed by c548b3fd1d287359034fb86a2aa91b43d29fa4d2

**Comment by JayDi85** [comment]
Belbe, Corrupted Observer fixed by c13716d1c588cfc629312a4f894c9b540a34c6d5

**Comment by JayDi85** [comment]
Krark, the Thumbless works fine and can be casted again after lose flip (use case: your hand contains card, your stack contains copied spell and you allowed to cast hand's card). Related test added by 936be75a66ad68704a7d740a1cd9b9e05873a262.
