### ISSUE TITLE
New format: Commander Draft

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#7206]
Format [documentation](https://mtg.gamepedia.com/Commander_Draft).

TODO:
* [ ] Draft with two cards pick instead one;
* [ ] Additional "commanders panel" in sideboard for deck editor or another mechanics to construct commander deck. Users must able construct commander deck and move unused cards to sideboard as card pool;
* [ ] Additional mechanics to setup and store card's settings in deck editor (see The Prismatic Piper with card color choose dialog);
* [ ] Deck legality checks on draft deck submits (player must lose on wrong deck and "out of time" submit);
* [ ] 903.13e After the draft is complete, the cards a player drafted become that player’s card pool. A player may add up to two cards named The Prismatic Piper to their card pool, but only if those cards are used as the player’s commander(s).;
* [ ] 903.13f Commander Draft deck construction follows the same rules as Commander deck construction (see rule 903.5) with two exceptions: (1) A player’s deck must contain at least 60 cards. There is no maximum deck size. (2) A player’s deck may include any number of cards from that player’s card pool with the same name.;
