### ISSUE TITLE
KHC - Kaldheim Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7421]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abomination of Llanowar](https://scryfall.com/search?q=!"Abomination+of+Llanowar")
- [x] Done -- [Ambition's Cost](https://scryfall.com/search?q=!"Ambitions+Cost")
- [x] Done -- [Angel of Finality](https://scryfall.com/search?q=!"Angel+of+Finality")
- [x] Done -- [Angel of Serenity](https://scryfall.com/search?q=!"Angel+of+Serenity")
- [x] Done -- [Arcane Artisan](https://scryfall.com/search?q=!"Arcane+Artisan")
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!"Arcane+Signet")
- [x] Done -- [Azorius Chancery](https://scryfall.com/search?q=!"Azorius+Chancery")
- [x] Done -- [Azorius Guildgate](https://scryfall.com/search?q=!"Azorius+Guildgate")
- [x] Done -- [Azorius Signet](https://scryfall.com/search?q=!"Azorius+Signet")
- [x] Done -- [Banishing Light](https://scryfall.com/search?q=!"Banishing+Light")
- [x] Done -- [Beast Whisperer](https://scryfall.com/search?q=!"Beast+Whisperer")
- [x] Done -- [Bounty of Skemfar](https://scryfall.com/search?q=!"Bounty+of+Skemfar")
- [x] Done -- [Brago, King Eternal](https://scryfall.com/search?q=!"Brago,+King+Eternal")
- [x] Done -- [Burnished Hart](https://scryfall.com/search?q=!"Burnished+Hart")
- [x] Done -- [Casualties of War](https://scryfall.com/search?q=!"Casualties+of+War")
- [x] Done -- [Cleansing Nova](https://scryfall.com/search?q=!"Cleansing+Nova")
- [x] Done -- [Cloudblazer](https://scryfall.com/search?q=!"Cloudblazer")
- [x] Done -- [Cloudgoat Ranger](https://scryfall.com/search?q=!"Cloudgoat+Ranger")
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!"Command+Tower")
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=!"Commanders+Sphere")
- [x] Done -- [Cosmic Intervention](https://scryfall.com/search?q=!"Cosmic+Intervention")
- [x] Done -- [Crown of Skemfar](https://scryfall.com/search?q=!"Crown+of+Skemfar")
- [x] Done -- [Cryptic Caves](https://scryfall.com/search?q=!"Cryptic+Caves")
- [x] Done -- [Cultivator of Blades](https://scryfall.com/search?q=!"Cultivator+of+Blades")
- [x] Done -- [Curse of the Swine](https://scryfall.com/search?q=!"Curse+of+the+Swine")
- [x] Done -- [Day of the Dragons](https://scryfall.com/search?q=!"Day+of+the+Dragons")
- [x] Done -- [Dwynen, Gilt-Leaf Daen](https://scryfall.com/search?q=!"Dwynen,+Gilt-Leaf+Daen")
- [x] Done -- [Eerie Interlude](https://scryfall.com/search?q=!"Eerie+Interlude")
- [x] Done -- [Elderfang Venom](https://scryfall.com/search?q=!"Elderfang+Venom")
- [x] Done -- [Elvish Archdruid](https://scryfall.com/search?q=!"Elvish+Archdruid")
- [x] Done -- [Elvish Mystic](https://scryfall.com/search?q=!"Elvish+Mystic")
- [x] Done -- [Elvish Promenade](https://scryfall.com/search?q=!"Elvish+Promenade")
- [x] Done -- [Elvish Rejuvenator](https://scryfall.com/search?q=!"Elvish+Rejuvenator")
- [x] Done -- [Empyrean Eagle](https://scryfall.com/search?q=!"Empyrean+Eagle")
- [x] Done -- [End-Raze Forerunners](https://scryfall.com/search?q=!"End-Raze+Forerunners")
- [x] Done -- [Ethereal Valkyrie](https://scryfall.com/search?q=!"Ethereal+Valkyrie")
- [x] Done -- [Evangel of Heliod](https://scryfall.com/search?q=!"Evangel+of+Heliod")
- [x] Done -- [Eyeblight Cullers](https://scryfall.com/search?q=!"Eyeblight+Cullers")
- [x] Done -- [Eyeblight Massacre](https://scryfall.com/search?q=!"Eyeblight+Massacre")
- [x] Done -- [Farhaven Elf](https://scryfall.com/search?q=!"Farhaven+Elf")
- [x] Done -- [Flickerwisp](https://scryfall.com/search?q=!"Flickerwisp")
- [x] Done -- [Foul Orchard](https://scryfall.com/search?q=!"Foul+Orchard")
- [x] Done -- [Geist-Honored Monk](https://scryfall.com/search?q=!"Geist-Honored+Monk")
- [x] Done -- [Ghostly Flicker](https://scryfall.com/search?q=!"Ghostly+Flicker")
- [x] Done -- [Ghostly Prison](https://scryfall.com/search?q=!"Ghostly+Prison")
- [x] Done -- [Goldnight Commander](https://scryfall.com/search?q=!"Goldnight+Commander")
- [x] Done -- [Golgari Findbroker](https://scryfall.com/search?q=!"Golgari+Findbroker")
- [x] Done -- [Golgari Guildgate](https://scryfall.com/search?q=!"Golgari+Guildgate")
- [x] Done -- [Golgari Rot Farm](https://scryfall.com/search?q=!"Golgari+Rot+Farm")
- [x] Done -- [Harvest Season](https://scryfall.com/search?q=!"Harvest+Season")
- [x] Done -- [Hero of Bretagard](https://scryfall.com/search?q=!"Hero+of+Bretagard")
- [x] Done -- [Imperious Perfect](https://scryfall.com/search?q=!"Imperious+Perfect")
- [x] Done -- [Inspired Sphinx](https://scryfall.com/search?q=!"Inspired+Sphinx")
- [x] Done -- [Jagged-Scar Archers](https://scryfall.com/search?q=!"Jagged-Scar+Archers")
- [x] Done -- [Jungle Hollow](https://scryfall.com/search?q=!"Jungle+Hollow")
- [x] Done -- [Kor Cartographer](https://scryfall.com/search?q=!"Kor+Cartographer")
- [x] Done -- [Lathril, Blade of the Elves](https://scryfall.com/search?q=!"Lathril,+Blade+of+the+Elves")
- [x] Done -- [Llanowar Tribe](https://scryfall.com/search?q=!"Llanowar+Tribe")
- [x] Done -- [Lys Alana Huntmaster](https://scryfall.com/search?q=!"Lys+Alana+Huntmaster")
- [x] Done -- [Lys Alana Scarblade](https://scryfall.com/search?q=!"Lys+Alana+Scarblade")
- [x] Done -- [Marble Diamond](https://scryfall.com/search?q=!"Marble+Diamond")
- [x] Done -- [Marshal's Anthem](https://scryfall.com/search?q=!"Marshals+Anthem")
- [x] Done -- [Marwyn, the Nurturer](https://scryfall.com/search?q=!"Marwyn,+the+Nurturer")
- [x] Done -- [Masked Admirers](https://scryfall.com/search?q=!"Masked+Admirers")
- [x] Done -- [Meandering River](https://scryfall.com/search?q=!"Meandering+River")
- [x] Done -- [Meteor Golem](https://scryfall.com/search?q=!"Meteor+Golem")
- [x] Done -- [Miara, Thorn of the Glade](https://scryfall.com/search?q=!"Miara,+Thorn+of+the+Glade")
- [x] Done -- [Migratory Route](https://scryfall.com/search?q=!"Migratory+Route")
- [x] Done -- [Mind Stone](https://scryfall.com/search?q=!"Mind+Stone")
- [x] Done -- [Mist Raven](https://scryfall.com/search?q=!"Mist+Raven")
- [x] Done -- [Mistmeadow Witch](https://scryfall.com/search?q=!"Mistmeadow+Witch")
- [x] Done -- [Moldervine Reclamation](https://scryfall.com/search?q=!"Moldervine+Reclamation")
- [x] Done -- [Momentary Blink](https://scryfall.com/search?q=!"Momentary+Blink")
- [x] Done -- [Mulldrifter](https://scryfall.com/search?q=!"Mulldrifter")
- [x] Done -- [Myriad Landscape](https://scryfall.com/search?q=!"Myriad+Landscape")
- [x] Done -- [Nullmage Shepherd](https://scryfall.com/search?q=!"Nullmage+Shepherd")
- [x] Done -- [Numa, Joraga Chieftain](https://scryfall.com/search?q=!"Numa,+Joraga+Chieftain")
- [x] Done -- [Opal Palace](https://scryfall.com/search?q=!"Opal+Palace")
- [x] Done -- [Pact of the Serpent](https://scryfall.com/search?q=!"Pact+of+the+Serpent")
- [x] Done -- [Path of Ancestry](https://scryfall.com/search?q=!"Path+of+Ancestry")
- [x] Done -- [Poison-Tip Archer](https://scryfall.com/search?q=!"Poison-Tip+Archer")
- [x] Done -- [Pride of the Perfect](https://scryfall.com/search?q=!"Pride+of+the+Perfect")
- [x] Done -- [Prowess of the Fair](https://scryfall.com/search?q=!"Prowess+of+the+Fair")
- [x] Done -- [Putrefy](https://scryfall.com/search?q=!"Putrefy")
- [x] Done -- [Ranar the Ever-Watchful](https://scryfall.com/search?q=!"Ranar+the+Ever-Watchful")
- [x] Done -- [Reclamation Sage](https://scryfall.com/search?q=!"Reclamation+Sage")
- [x] Done -- [Restoration Angel](https://scryfall.com/search?q=!"Restoration+Angel")
- [x] Done -- [Return to Dust](https://scryfall.com/search?q=!"Return+to+Dust")
- [x] Done -- [Rhys the Exiled](https://scryfall.com/search?q=!"Rhys+the+Exiled")
- [x] Done -- [Ruthless Winnower](https://scryfall.com/search?q=!"Ruthless+Winnower")
- [x] Done -- [Sage of the Beyond](https://scryfall.com/search?q=!"Sage+of+the+Beyond")
- [x] Done -- [Sea Gate Oracle](https://scryfall.com/search?q=!"Sea+Gate+Oracle")
- [x] Done -- [Sejiri Refuge](https://scryfall.com/search?q=!"Sejiri+Refuge")
- [x] Done -- [Serpent's Soul-Jar](https://scryfall.com/search?q=!"Serpents+Soul-Jar")
- [x] Done -- [Shaman of the Pack](https://scryfall.com/search?q=!"Shaman+of+the+Pack")
- [x] Done -- [Sky Diamond](https://scryfall.com/search?q=!"Sky+Diamond")
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!"Sol+Ring")
- [x] Done -- [Soulherder](https://scryfall.com/search?q=!"Soulherder")
- [x] Done -- [Spectral Deluge](https://scryfall.com/search?q=!"Spectral+Deluge")
- [x] Done -- [Springbloom Druid](https://scryfall.com/search?q=!"Springbloom+Druid")
- [x] Done -- [Stoic Farmer](https://scryfall.com/search?q=!"Stoic+Farmer")
- [x] Done -- [Storm Herd](https://scryfall.com/search?q=!"Storm+Herd")
- [x] Done -- [Sun Titan](https://scryfall.com/search?q=!"Sun+Titan")
- [x] Done -- [Swiftfoot Boots](https://scryfall.com/search?q=!"Swiftfoot+Boots")
- [x] Done -- [Sylvan Messenger](https://scryfall.com/search?q=!"Sylvan+Messenger")
- [x] Done -- [Synthetic Destiny](https://scryfall.com/search?q=!"Synthetic+Destiny")
- [x] Done -- [Tales of the Ancestors](https://scryfall.com/search?q=!"Tales+of+the+Ancestors")
- [x] Done -- [Thunderclap Wyvern](https://scryfall.com/search?q=!"Thunderclap+Wyvern")
- [x] Done -- [Timberwatch Elf](https://scryfall.com/search?q=!"Timberwatch+Elf")
- [x] Done -- [Tranquil Cove](https://scryfall.com/search?q=!"Tranquil+Cove")
- [x] Done -- [Twinblade Assassins](https://scryfall.com/search?q=!"Twinblade+Assassins")
- [x] Done -- [Voice of Many](https://scryfall.com/search?q=!"Voice+of+Many")
- [x] Done -- [Voice of the Woods](https://scryfall.com/search?q=!"Voice+of+the+Woods")
- [x] Done -- [Wall of Omens](https://scryfall.com/search?q=!"Wall+of+Omens")
- [x] Done -- [Whirler Rogue](https://scryfall.com/search?q=!"Whirler+Rogue")
- [x] Done -- [Windfall](https://scryfall.com/search?q=!"Windfall")
- [x] Done -- [Wirewood Channeler](https://scryfall.com/search?q=!"Wirewood+Channeler")
- [x] Done -- [Wolverine Riders](https://scryfall.com/search?q=!"Wolverine+Riders")
- [x] Done -- [Wood Elves](https://scryfall.com/search?q=!"Wood+Elves")
</details>

**Comment by theelk801** [comment]
- [ ] In progress -- [Lathril, Blade of the Elves](https://scryfall.com/search?q=!"Lathril,+Blade+of+the+Elves")
- [ ] In progress -- [Ranar the Ever-Watchful](https://scryfall.com/search?q=!"Ranar+the+Ever-Watchful")
- [ ] In progress -- [Wolverine Riders](https://scryfall.com/search?q=!"Wolverine+Riders")

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"Lathril,%20Blade%20of%20the%20Elves"or!"Ranar%20the%20Ever-Watchful"or!"Wolverine%20Riders"&unique=cards)

**Comment by theelk801** [comment]
Additional Tasks: none yet (foretell is part of KHM implementation)

**Comment by weirddan455** [comment]
Just curious, is this part of KHM (where full spoiler is out) or are there more cards coming for this later?

**Comment by theelk801** [comment]
this is all the new cards, the rest are reprints that I’m gonna add once they’re on scryfall

**Comment by jeffwadsworth** [comment]
I will start on these tomorrow.  Hopefully finish by the weekend.

**Comment by peter-thoenen** [comment]
The following cards are miscoded somehow as not being valid modern cards even though they are part of KHC and not banned (yet):

Cosmic Intervention
Ethereal Valkiyre
Ranar the Ever-Watchful
Spectral Deluge

![image](https://user-images.githubusercontent.com/15895994/107454292-d7ca8080-6af0-11eb-9baa-31a2b8b006ff.png)

**Comment by peter-thoenen** [comment]
The following cards are miscoded somehow as not being valid MODERN cards even though they are part of KHC and not banned (yet):

Cosmic Intervention
Ethereal Valkiyre
Ranar the Ever-Watchful
Spectral Deluge

![image](https://user-images.githubusercontent.com/15895994/107454385-ffb9e400-6af0-11eb-85d7-41d3da3e0f62.png)

**Comment by theelk801** [comment]
KHC is a commander set and is not legal in modern

**Comment by peter-thoenen** [comment]
My bad, completely missed those weren't part of Kaldheim.  Didn't realize "foretell" existed prior to that and did a search on it.

**Comment by theelk801** [comment]
It's not from before, this is the set that goes with the Kaldheim commander decks
