### ISSUE TITLE
STX - Strixhaven: School of Mages Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7602]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Academic Dispute](https://scryfall.com/search?q=!"Academic+Dispute")
- [x] Done -- [Academic Probation](https://scryfall.com/search?q=!"Academic+Probation")
- [x] Done -- [Access Tunnel](https://scryfall.com/search?q=!"Access+Tunnel")
- [x] Done -- [Accomplished Alchemist](https://scryfall.com/search?q=!"Accomplished+Alchemist")
- [x] Done -- [Aether Helix](https://scryfall.com/search?q=!"Aether+Helix")
- [x] Done -- [Ageless Guardian](https://scryfall.com/search?q=!"Ageless+Guardian")
- [x] Done -- [Arcane Subtraction](https://scryfall.com/search?q=!"Arcane+Subtraction")
- [x] Done -- [Archmage Emeritus](https://scryfall.com/search?q=!"Archmage+Emeritus")
- [x] Done -- [Archway Commons](https://scryfall.com/search?q=!"Archway+Commons")
- [x] Done -- [Ardent Dustspeaker](https://scryfall.com/search?q=!"Ardent+Dustspeaker")
- [x] Done -- [Arrogant Poet](https://scryfall.com/search?q=!"Arrogant+Poet")
- [x] Done -- [Augmenter Pugilist](https://scryfall.com/search?q=!"Augmenter+Pugilist")
- [x] Done -- [Baleful Mastery](https://scryfall.com/search?q=!"Baleful+Mastery")
- [x] Done -- [Basic Conjuration](https://scryfall.com/search?q=!"Basic+Conjuration")
- [x] Done -- [Bayou Groff](https://scryfall.com/search?q=!"Bayou+Groff")
- [x] Done -- [Beaming Defiance](https://scryfall.com/search?q=!"Beaming+Defiance")
- [x] Done -- [Beledros Witherbloom](https://scryfall.com/search?q=!"Beledros+Witherbloom")
- [x] Done -- [Biblioplex Assistant](https://scryfall.com/search?q=!"Biblioplex+Assistant")
- [x] Done -- [Big Play](https://scryfall.com/search?q=!"Big+Play")
- [x] Done -- [Biomathematician](https://scryfall.com/search?q=!"Biomathematician")
- [x] Done -- [Blade Historian](https://scryfall.com/search?q=!"Blade+Historian")
- [x] Done -- [Blex, Vexing Pest](https://scryfall.com/search?q=!"Blex,+Vexing+Pest")
- [x] Done -- [Blood Age General](https://scryfall.com/search?q=!"Blood+Age+General")
- [x] Done -- [Blood Researcher](https://scryfall.com/search?q=!"Blood+Researcher")
- [x] Done -- [Blot Out the Sky](https://scryfall.com/search?q=!"Blot+Out+the+Sky")
- [x] Done -- [Body of Research](https://scryfall.com/search?q=!"Body+of+Research")
- [x] Done -- [Bookwurm](https://scryfall.com/search?q=!"Bookwurm")
- [x] Done -- [Brackish Trudge](https://scryfall.com/search?q=!"Brackish+Trudge")
- [x] Done -- [Burrog Befuddler](https://scryfall.com/search?q=!"Burrog+Befuddler")
- [x] Done -- [Bury in Books](https://scryfall.com/search?q=!"Bury+in+Books")
- [x] Done -- [Callous Bloodmage](https://scryfall.com/search?q=!"Callous+Bloodmage")
- [x] Done -- [Campus Guide](https://scryfall.com/search?q=!"Campus+Guide")
- [x] Done -- [Charge Through](https://scryfall.com/search?q=!"Charge+Through")
- [x] Done -- [Clever Lumimancer](https://scryfall.com/search?q=!"Clever+Lumimancer")
- [x] Done -- [Closing Statement](https://scryfall.com/search?q=!"Closing+Statement")
- [x] Done -- [Codie, Vociferous Codex](https://scryfall.com/search?q=!"Codie,+Vociferous+Codex")
- [x] Done -- [Cogwork Archivist](https://scryfall.com/search?q=!"Cogwork+Archivist")
- [x] Done -- [Combat Professor](https://scryfall.com/search?q=!"Combat+Professor")
- [x] Done -- [Confront the Past](https://scryfall.com/search?q=!"Confront+the+Past")
- [x] Done -- [Conspiracy Theorist](https://scryfall.com/search?q=!"Conspiracy+Theorist")
- [x] Done -- [Containment Breach](https://scryfall.com/search?q=!"Containment+Breach")
- [x] Done -- [Crackle with Power](https://scryfall.com/search?q=!"Crackle+with+Power")
- [x] Done -- [Cram Session](https://scryfall.com/search?q=!"Cram+Session")
- [x] Done -- [Creative Outburst](https://scryfall.com/search?q=!"Creative+Outburst")
- [x] Done -- [Crushing Disappointment](https://scryfall.com/search?q=!"Crushing+Disappointment")
- [x] Done -- [Culling Ritual](https://scryfall.com/search?q=!"Culling+Ritual")
- [x] Done -- [Culmination of Studies](https://scryfall.com/search?q=!"Culmination+of+Studies")
- [x] Done -- [Curate](https://scryfall.com/search?q=!"Curate")
- [x] Done -- [Daemogoth Titan](https://scryfall.com/search?q=!"Daemogoth+Titan")
- [x] Done -- [Daemogoth Woe-Eater](https://scryfall.com/search?q=!"Daemogoth+Woe-Eater")
- [x] Done -- [Deadly Brew](https://scryfall.com/search?q=!"Deadly+Brew")
- [x] Done -- [Decisive Denial](https://scryfall.com/search?q=!"Decisive+Denial")
- [x] Done -- [Defend the Campus](https://scryfall.com/search?q=!"Defend+the+Campus")
- [x] Done -- [Detention Vortex](https://scryfall.com/search?q=!"Detention+Vortex")
- [x] Done -- [Devastating Mastery](https://scryfall.com/search?q=!"Devastating+Mastery")
- [x] Done -- [Devouring Tendrils](https://scryfall.com/search?q=!"Devouring+Tendrils")
- [x] Done -- [Dina, Soul Steeper](https://scryfall.com/search?q=!"Dina,+Soul+Steeper")
- [x] Done -- [Divide by Zero](https://scryfall.com/search?q=!"Divide+by+Zero")
- [x] Done -- [Double Major](https://scryfall.com/search?q=!"Double+Major")
- [x] Done -- [Draconic Intervention](https://scryfall.com/search?q=!"Draconic+Intervention")
- [x] Done -- [Dragon's Approach](https://scryfall.com/search?q=!"Dragons+Approach")
- [x] Done -- [Dragonsguard Elite](https://scryfall.com/search?q=!"Dragonsguard+Elite")
- [x] Done -- [Dramatic Finale](https://scryfall.com/search?q=!"Dramatic+Finale")
- [x] Done -- [Dream Strix](https://scryfall.com/search?q=!"Dream+Strix")
- [x] Done -- [Dueling Coach](https://scryfall.com/search?q=!"Dueling+Coach")
- [x] Done -- [Eager First-Year](https://scryfall.com/search?q=!"Eager+First-Year")
- [x] Done -- [Ecological Appreciation](https://scryfall.com/search?q=!"Ecological+Appreciation")
- [x] Done -- [Efreet Flamepainter](https://scryfall.com/search?q=!"Efreet+Flamepainter")
- [x] Done -- [Elemental Expressionist](https://scryfall.com/search?q=!"Elemental+Expressionist")
- [x] Done -- [Elemental Masterpiece](https://scryfall.com/search?q=!"Elemental+Masterpiece")
- [x] Done -- [Elemental Summoning](https://scryfall.com/search?q=!"Elemental+Summoning")
- [x] Done -- [Elite Spellbinder](https://scryfall.com/search?q=!"Elite+Spellbinder")
- [x] Done -- [Emergent Sequence](https://scryfall.com/search?q=!"Emergent+Sequence")
- [x] Done -- [Enthusiastic Study](https://scryfall.com/search?q=!"Enthusiastic+Study")
- [x] Done -- [Environmental Sciences](https://scryfall.com/search?q=!"Environmental+Sciences")
- [x] Done -- [Essence Infusion](https://scryfall.com/search?q=!"Essence+Infusion")
- [x] Done -- [Eureka Moment](https://scryfall.com/search?q=!"Eureka+Moment")
- [x] Done -- [Excavated Wall](https://scryfall.com/search?q=!"Excavated+Wall")
- [x] Done -- [Exhilarating Elocution](https://scryfall.com/search?q=!"Exhilarating+Elocution")
- [x] Done -- [Expanded Anatomy](https://scryfall.com/search?q=!"Expanded+Anatomy")
- [x] Done -- [Expel](https://scryfall.com/search?q=!"Expel")
- [x] Done -- [Explosive Welcome](https://scryfall.com/search?q=!"Explosive+Welcome")
- [x] Done -- [Exponential Growth](https://scryfall.com/search?q=!"Exponential+Growth")
- [x] Done -- [Expressive Iteration](https://scryfall.com/search?q=!"Expressive+Iteration")
- [x] Done -- [Extus, Oriq Overlord](https://scryfall.com/search?q=!"Extus,+Oriq+Overlord")
- [x] Done -- [Eyetwitch](https://scryfall.com/search?q=!"Eyetwitch")
- [x] Done -- [Fervent Mastery](https://scryfall.com/search?q=!"Fervent+Mastery")
- [x] Done -- [Field Trip](https://scryfall.com/search?q=!"Field+Trip")
- [x] Done -- [First Day of Class](https://scryfall.com/search?q=!"First+Day+of+Class")
- [x] Done -- [Flamescroll Celebrant](https://scryfall.com/search?q=!"Flamescroll+Celebrant")
- [x] Done -- [Flunk](https://scryfall.com/search?q=!"Flunk")
- [x] Done -- [Fortifying Draught](https://scryfall.com/search?q=!"Fortifying+Draught")
- [x] Done -- [Fractal Summoning](https://scryfall.com/search?q=!"Fractal+Summoning")
- [x] Done -- [Fracture](https://scryfall.com/search?q=!"Fracture")
- [x] Done -- [Frost Trickster](https://scryfall.com/search?q=!"Frost+Trickster")
- [x] Done -- [Frostboil Snarl](https://scryfall.com/search?q=!"Frostboil+Snarl")
- [x] Done -- [Fuming Effigy](https://scryfall.com/search?q=!"Fuming+Effigy")
- [x] Done -- [Furycalm Snarl](https://scryfall.com/search?q=!"Furycalm+Snarl")
- [x] Done -- [Galazeth Prismari](https://scryfall.com/search?q=!"Galazeth+Prismari")
- [x] Done -- [Gnarled Professor](https://scryfall.com/search?q=!"Gnarled+Professor")
- [x] Done -- [Go Blank](https://scryfall.com/search?q=!"Go+Blank")
- [x] Done -- [Golden Ratio](https://scryfall.com/search?q=!"Golden+Ratio")
- [x] Done -- [Grinning Ignus](https://scryfall.com/search?q=!"Grinning+Ignus")
- [x] Done -- [Guiding Voice](https://scryfall.com/search?q=!"Guiding+Voice")
- [x] Done -- [Hall Monitor](https://scryfall.com/search?q=!"Hall+Monitor")
- [x] Done -- [Hall of Oracles](https://scryfall.com/search?q=!"Hall+of+Oracles")
- [x] Done -- [Harness Infinity](https://scryfall.com/search?q=!"Harness+Infinity")
- [x] Done -- [Heated Debate](https://scryfall.com/search?q=!"Heated+Debate")
- [x] Done -- [Hofri Ghostforge](https://scryfall.com/search?q=!"Hofri+Ghostforge")
- [x] Done -- [Honor Troll](https://scryfall.com/search?q=!"Honor+Troll")
- [x] Done -- [Humiliate](https://scryfall.com/search?q=!"Humiliate")
- [x] Done -- [Hunt for Specimens](https://scryfall.com/search?q=!"Hunt+for+Specimens")
- [x] Done -- [Igneous Inspiration](https://scryfall.com/search?q=!"Igneous+Inspiration")
- [x] Done -- [Illuminate History](https://scryfall.com/search?q=!"Illuminate+History")
- [x] Done -- [Illustrious Historian](https://scryfall.com/search?q=!"Illustrious+Historian")
- [x] Done -- [Infuse with Vitality](https://scryfall.com/search?q=!"Infuse+with+Vitality")
- [x] Done -- [Ingenious Mastery](https://scryfall.com/search?q=!"Ingenious+Mastery")
- [x] Done -- [Inkling Summoning](https://scryfall.com/search?q=!"Inkling+Summoning")
- [x] Done -- [Introduction to Annihilation](https://scryfall.com/search?q=!"Introduction+to+Annihilation")
- [x] Done -- [Introduction to Prophecy](https://scryfall.com/search?q=!"Introduction+to+Prophecy")
- [x] Done -- [Jadzi, Oracle of Arcavios](https://scryfall.com/search?q=!"Jadzi,+Oracle+of+Arcavios")
- [x] Done -- [Karok Wrangler](https://scryfall.com/search?q=!"Karok+Wrangler")
- [x] Done -- [Kasmina, Enigma Sage](https://scryfall.com/search?q=!"Kasmina,+Enigma+Sage")
- [x] Done -- [Kelpie Guide](https://scryfall.com/search?q=!"Kelpie+Guide")
- [x] Done -- [Kianne, Dean of Substance](https://scryfall.com/search?q=!"Kianne,+Dean+of+Substance")
- [x] Done -- [Killian, Ink Duelist](https://scryfall.com/search?q=!"Killian,+Ink+Duelist")
- [x] Done -- [Lash of Malice](https://scryfall.com/search?q=!"Lash+of+Malice")
- [x] Done -- [Leech Fanatic](https://scryfall.com/search?q=!"Leech+Fanatic")
- [x] Done -- [Leonin Lightscribe](https://scryfall.com/search?q=!"Leonin+Lightscribe")
- [x] Done -- [Letter of Acceptance](https://scryfall.com/search?q=!"Letter+of+Acceptance")
- [x] Done -- [Leyline Invocation](https://scryfall.com/search?q=!"Leyline+Invocation")
- [x] Done -- [Lorehold Apprentice](https://scryfall.com/search?q=!"Lorehold+Apprentice")
- [x] Done -- [Lorehold Campus](https://scryfall.com/search?q=!"Lorehold+Campus")
- [x] Done -- [Lorehold Command](https://scryfall.com/search?q=!"Lorehold+Command")
- [x] Done -- [Lorehold Excavation](https://scryfall.com/search?q=!"Lorehold+Excavation")
- [x] Done -- [Lorehold Pledgemage](https://scryfall.com/search?q=!"Lorehold+Pledgemage")
- [x] Done -- [Maelstrom Muse](https://scryfall.com/search?q=!"Maelstrom+Muse")
- [x] Done -- [Mage Duel](https://scryfall.com/search?q=!"Mage+Duel")
- [x] Done -- [Mage Hunter](https://scryfall.com/search?q=!"Mage+Hunter")
- [x] Done -- [Mage Hunters' Onslaught](https://scryfall.com/search?q=!"Mage+Hunters+Onslaught")
- [x] Done -- [Magma Opus](https://scryfall.com/search?q=!"Magma+Opus")
- [x] Done -- [Make Your Mark](https://scryfall.com/search?q=!"Make+Your+Mark")
- [x] Done -- [Manifestation Sage](https://scryfall.com/search?q=!"Manifestation+Sage")
- [x] Done -- [Mascot Exhibition](https://scryfall.com/search?q=!"Mascot+Exhibition")
- [x] Done -- [Mascot Interception](https://scryfall.com/search?q=!"Mascot+Interception")
- [x] Done -- [Master Symmetrist](https://scryfall.com/search?q=!"Master+Symmetrist")
- [x] Done -- [Mavinda, Students' Advocate](https://scryfall.com/search?q=!"Mavinda,+Students+Advocate")
- [x] Done -- [Mentor's Guidance](https://scryfall.com/search?q=!"Mentors+Guidance")
- [x] Done -- [Mercurial Transformation](https://scryfall.com/search?q=!"Mercurial+Transformation")
- [x] Done -- [Mila, Crafty Companion](https://scryfall.com/search?q=!"Mila,+Crafty+Companion")
- [x] Done -- [Moldering Karok](https://scryfall.com/search?q=!"Moldering+Karok")
- [x] Done -- [Mortality Spear](https://scryfall.com/search?q=!"Mortality+Spear")
- [x] Done -- [Multiple Choice](https://scryfall.com/search?q=!"Multiple+Choice")
- [x] Done -- [Necroblossom Snarl](https://scryfall.com/search?q=!"Necroblossom+Snarl")
- [x] Done -- [Necrotic Fumes](https://scryfall.com/search?q=!"Necrotic+Fumes")
- [x] Done -- [Needlethorn Drake](https://scryfall.com/search?q=!"Needlethorn+Drake")
- [x] Done -- [Novice Dissector](https://scryfall.com/search?q=!"Novice+Dissector")
- [x] Done -- [Oggyar Battle-Seer](https://scryfall.com/search?q=!"Oggyar+Battle-Seer")
- [x] Done -- [Oriq Loremage](https://scryfall.com/search?q=!"Oriq+Loremage")
- [x] Done -- [Overgrown Arch](https://scryfall.com/search?q=!"Overgrown+Arch")
- [x] Done -- [Owlin Shieldmage](https://scryfall.com/search?q=!"Owlin+Shieldmage")
- [x] Done -- [Pest Summoning](https://scryfall.com/search?q=!"Pest+Summoning")
- [x] Done -- [Pestilent Cauldron](https://scryfall.com/search?q=!"Pestilent+Cauldron")
- [x] Done -- [Pigment Storm](https://scryfall.com/search?q=!"Pigment+Storm")
- [x] Done -- [Pilgrim of the Ages](https://scryfall.com/search?q=!"Pilgrim+of+the+Ages")
- [x] Done -- [Pillardrop Rescuer](https://scryfall.com/search?q=!"Pillardrop+Rescuer")
- [x] Done -- [Pillardrop Warden](https://scryfall.com/search?q=!"Pillardrop+Warden")
- [x] Done -- [Plargg, Dean of Chaos](https://scryfall.com/search?q=!"Plargg,+Dean+of+Chaos")
- [x] Done -- [Plumb the Forbidden](https://scryfall.com/search?q=!"Plumb+the+Forbidden")
- [x] Done -- [Poet's Quill](https://scryfall.com/search?q=!"Poets+Quill")
- [x] Done -- [Pop Quiz](https://scryfall.com/search?q=!"Pop+Quiz")
- [x] Done -- [Practical Research](https://scryfall.com/search?q=!"Practical+Research")
- [x] Done -- [Prismari Apprentice](https://scryfall.com/search?q=!"Prismari+Apprentice")
- [x] Done -- [Prismari Campus](https://scryfall.com/search?q=!"Prismari+Campus")
- [x] Done -- [Prismari Command](https://scryfall.com/search?q=!"Prismari+Command")
- [x] Done -- [Prismari Pledgemage](https://scryfall.com/search?q=!"Prismari+Pledgemage")
- [x] Done -- [Professor Onyx](https://scryfall.com/search?q=!"Professor+Onyx")
- [x] Done -- [Professor of Symbology](https://scryfall.com/search?q=!"Professor+of+Symbology")
- [x] Done -- [Professor of Zoomancy](https://scryfall.com/search?q=!"Professor+of+Zoomancy")
- [x] Done -- [Professor's Warning](https://scryfall.com/search?q=!"Professors+Warning")
- [x] Done -- [Promising Duskmage](https://scryfall.com/search?q=!"Promising+Duskmage")
- [x] Done -- [Quandrix Apprentice](https://scryfall.com/search?q=!"Quandrix+Apprentice")
- [x] Done -- [Quandrix Campus](https://scryfall.com/search?q=!"Quandrix+Campus")
- [x] Done -- [Quandrix Command](https://scryfall.com/search?q=!"Quandrix+Command")
- [x] Done -- [Quandrix Cultivator](https://scryfall.com/search?q=!"Quandrix+Cultivator")
- [x] Done -- [Quandrix Pledgemage](https://scryfall.com/search?q=!"Quandrix+Pledgemage")
- [x] Done -- [Quintorius, Field Historian](https://scryfall.com/search?q=!"Quintorius,+Field+Historian")
- [x] Done -- [Radiant Scrollwielder](https://scryfall.com/search?q=!"Radiant+Scrollwielder")
- [x] Done -- [Reckless Amplimancer](https://scryfall.com/search?q=!"Reckless+Amplimancer")
- [x] Done -- [Reconstruct History](https://scryfall.com/search?q=!"Reconstruct+History")
- [x] Done -- [Reduce to Memory](https://scryfall.com/search?q=!"Reduce+to+Memory")
- [x] Done -- [Reflective Golem](https://scryfall.com/search?q=!"Reflective+Golem")
- [x] Done -- [Reject](https://scryfall.com/search?q=!"Reject")
- [x] Done -- [Relic Sloth](https://scryfall.com/search?q=!"Relic+Sloth")
- [x] Done -- [Resculpt](https://scryfall.com/search?q=!"Resculpt")
- [x] Done -- [Retriever Phoenix](https://scryfall.com/search?q=!"Retriever+Phoenix")
- [x] Done -- [Returned Pastcaller](https://scryfall.com/search?q=!"Returned+Pastcaller")
- [x] Done -- [Rip Apart](https://scryfall.com/search?q=!"Rip+Apart")
- [x] Done -- [Rise of Extus](https://scryfall.com/search?q=!"Rise+of+Extus")
- [x] Done -- [Rootha, Mercurial Artist](https://scryfall.com/search?q=!"Rootha,+Mercurial+Artist")
- [x] Done -- [Rowan, Scholar of Sparks](https://scryfall.com/search?q=!"Rowan,+Scholar+of+Sparks")
- [x] Done -- [Rushed Rebirth](https://scryfall.com/search?q=!"Rushed+Rebirth")
- [x] Done -- [Scurrid Colony](https://scryfall.com/search?q=!"Scurrid+Colony")
- [x] Done -- [Secret Rendezvous](https://scryfall.com/search?q=!"Secret+Rendezvous")
- [x] Done -- [Sedgemoor Witch](https://scryfall.com/search?q=!"Sedgemoor+Witch")
- [x] Done -- [Selfless Glyphweaver](https://scryfall.com/search?q=!"Selfless+Glyphweaver")
- [x] Done -- [Semester's End](https://scryfall.com/search?q=!"Semesters+End")
- [x] Done -- [Serpentine Curve](https://scryfall.com/search?q=!"Serpentine+Curve")
- [x] Done -- [Shadewing Laureate](https://scryfall.com/search?q=!"Shadewing+Laureate")
- [x] Done -- [Shadrix Silverquill](https://scryfall.com/search?q=!"Shadrix+Silverquill")
- [x] Done -- [Shaile, Dean of Radiance](https://scryfall.com/search?q=!"Shaile,+Dean+of+Radiance")
- [x] Done -- [Shineshadow Snarl](https://scryfall.com/search?q=!"Shineshadow+Snarl")
- [x] Done -- [Show of Confidence](https://scryfall.com/search?q=!"Show+of+Confidence")
- [x] Done -- [Silverquill Apprentice](https://scryfall.com/search?q=!"Silverquill+Apprentice")
- [x] Done -- [Silverquill Campus](https://scryfall.com/search?q=!"Silverquill+Campus")
- [x] Done -- [Silverquill Command](https://scryfall.com/search?q=!"Silverquill+Command")
- [x] Done -- [Silverquill Pledgemage](https://scryfall.com/search?q=!"Silverquill+Pledgemage")
- [x] Done -- [Silverquill Silencer](https://scryfall.com/search?q=!"Silverquill+Silencer")
- [x] Done -- [Snow Day](https://scryfall.com/search?q=!"Snow+Day")
- [x] Done -- [Solve the Equation](https://scryfall.com/search?q=!"Solve+the+Equation")
- [x] Done -- [Soothsayer Adept](https://scryfall.com/search?q=!"Soothsayer+Adept")
- [x] Done -- [Sparring Regimen](https://scryfall.com/search?q=!"Sparring+Regimen")
- [x] Done -- [Spectacle Mage](https://scryfall.com/search?q=!"Spectacle+Mage")
- [x] Done -- [Specter of the Fens](https://scryfall.com/search?q=!"Specter+of+the+Fens")
- [x] Done -- [Spell Satchel](https://scryfall.com/search?q=!"Spell+Satchel")
- [x] Done -- [Spined Karok](https://scryfall.com/search?q=!"Spined+Karok")
- [x] Done -- [Spirit Summoning](https://scryfall.com/search?q=!"Spirit+Summoning")
- [x] Done -- [Spiteful Squad](https://scryfall.com/search?q=!"Spiteful+Squad")
- [x] Done -- [Springmane Cervin](https://scryfall.com/search?q=!"Springmane+Cervin")
- [x] Done -- [Square Up](https://scryfall.com/search?q=!"Square+Up")
- [x] Done -- [Star Pupil](https://scryfall.com/search?q=!"Star+Pupil")
- [x] Done -- [Start from Scratch](https://scryfall.com/search?q=!"Start+from+Scratch")
- [x] Done -- [Stonebinder's Familiar](https://scryfall.com/search?q=!"Stonebinders+Familiar")
- [x] Done -- [Stonebound Mentor](https://scryfall.com/search?q=!"Stonebound+Mentor")
- [x] Done -- [Stonerise Spirit](https://scryfall.com/search?q=!"Stonerise+Spirit")
- [x] Done -- [Storm-Kiln Artist](https://scryfall.com/search?q=!"Storm-Kiln+Artist")
- [x] Done -- [Strict Proctor](https://scryfall.com/search?q=!"Strict+Proctor")
- [x] Done -- [Strixhaven Stadium](https://scryfall.com/search?q=!"Strixhaven+Stadium")
- [x] Done -- [Study Break](https://scryfall.com/search?q=!"Study+Break")
- [x] Done -- [Sudden Breakthrough](https://scryfall.com/search?q=!"Sudden+Breakthrough")
- [x] Done -- [Symmetry Sage](https://scryfall.com/search?q=!"Symmetry+Sage")
- [x] Done -- [Tanazir Quandrix](https://scryfall.com/search?q=!"Tanazir+Quandrix")
- [x] Done -- [Tangletrap](https://scryfall.com/search?q=!"Tangletrap")
- [x] Done -- [Teach by Example](https://scryfall.com/search?q=!"Teach+by+Example")
- [x] Done -- [Teachings of the Archaics](https://scryfall.com/search?q=!"Teachings+of+the+Archaics")
- [x] Done -- [Team Pennant](https://scryfall.com/search?q=!"Team+Pennant")
- [x] Done -- [Tempted by the Oriq](https://scryfall.com/search?q=!"Tempted+by+the+Oriq")
- [x] Done -- [Tend the Pests](https://scryfall.com/search?q=!"Tend+the+Pests")
- [x] Done -- [Tenured Inkcaster](https://scryfall.com/search?q=!"Tenured+Inkcaster")
- [x] Done -- [Test of Talents](https://scryfall.com/search?q=!"Test+of+Talents")
- [x] Done -- [The Biblioplex](https://scryfall.com/search?q=!"The+Biblioplex")
- [x] Done -- [Thrilling Discovery](https://scryfall.com/search?q=!"Thrilling+Discovery")
- [x] Done -- [Thunderous Orator](https://scryfall.com/search?q=!"Thunderous+Orator")
- [x] Done -- [Tome Shredder](https://scryfall.com/search?q=!"Tome+Shredder")
- [x] Done -- [Torrent Sculptor](https://scryfall.com/search?q=!"Torrent+Sculptor")
- [x] Done -- [Twinscroll Shaman](https://scryfall.com/search?q=!"Twinscroll+Shaman")
- [x] Done -- [Umbral Juke](https://scryfall.com/search?q=!"Umbral+Juke")
- [x] Done -- [Unwilling Ingredient](https://scryfall.com/search?q=!"Unwilling+Ingredient")
- [x] Done -- [Uvilda, Dean of Perfection](https://scryfall.com/search?q=!"Uvilda,+Dean+of+Perfection")
- [x] Done -- [Valentin, Dean of the Vein](https://scryfall.com/search?q=!"Valentin,+Dean+of+the+Vein")
- [x] Done -- [Vanishing Verse](https://scryfall.com/search?q=!"Vanishing+Verse")
- [x] Done -- [Velomachus Lorehold](https://scryfall.com/search?q=!"Velomachus+Lorehold")
- [x] Done -- [Venerable Warsinger](https://scryfall.com/search?q=!"Venerable+Warsinger")
- [x] Done -- [Verdant Mastery](https://scryfall.com/search?q=!"Verdant+Mastery")
- [x] Done -- [Vineglimmer Snarl](https://scryfall.com/search?q=!"Vineglimmer+Snarl")
- [x] Done -- [Vortex Runner](https://scryfall.com/search?q=!"Vortex+Runner")
- [x] Done -- [Wandering Archaic](https://scryfall.com/search?q=!"Wandering+Archaic")
- [x] Done -- [Waterfall Aerialist](https://scryfall.com/search?q=!"Waterfall+Aerialist")
- [x] Done -- [Witherbloom Apprentice](https://scryfall.com/search?q=!"Witherbloom+Apprentice")
- [x] Done -- [Witherbloom Campus](https://scryfall.com/search?q=!"Witherbloom+Campus")
- [x] Done -- [Witherbloom Command](https://scryfall.com/search?q=!"Witherbloom+Command")
- [x] Done -- [Witherbloom Pledgemage](https://scryfall.com/search?q=!"Witherbloom+Pledgemage")
- [x] Done -- [Wormhole Serpent](https://scryfall.com/search?q=!"Wormhole+Serpent")
- [x] Done -- [Zephyr Boots](https://scryfall.com/search?q=!"Zephyr+Boots")
- [x] Done -- [Zimone, Quandrix Prodigy](https://scryfall.com/search?q=!"Zimone,+Quandrix+Prodigy")
</details>

**Comment by theelk801** [comment]
- [ ] In progress -- [Lorehold Command](https://scryfall.com/search?q=!"Lorehold+Command")
- [ ] In progress -- [Quandrix Command](https://scryfall.com/search?q=!"Quandrix+Command")
- [ ] In progress -- [Silverquill Command](https://scryfall.com/search?q=!"Silverquill+Command")
- [ ] In progress -- [Witherbloom Command](https://scryfall.com/search?q=!"Witherbloom+Command")

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"Lorehold%20Command"or!"Quandrix%20Command"or!"Silverquill%20Command"or!"Witherbloom%20Command"&unique=cards)

**Comment by theelk801** [comment]
Additional tasks:
- [ ] refactor all instances of "converted mana cost" to "mana value" (gonna wait to actually do this one for now)
- [ ] refactor instances of "shuffle your library" to "shuffle" (also waiting on this one)

**Comment by htrajan** [comment]
I'll take:

Augusta, Dean of Order
Confront the Past
Embrose, Dean of Shadow
First Day of Class

**Comment by htrajan** [comment]
Next up, I'll take:

Academic Probation
Accomplished Alchemist
Augmenter Pugilist
Baleful Mastery
Basic Conjuration
Closing Statement

**Comment by weirddan455** [comment]
I hate GitHub's editor.  I'm just going down in alphabetical order.  I checked off Beledros Witherbloom but it looks like it reverted your earlier edits to the checklist for some unknown reason.

**Comment by theelk801** [comment]
No worries, I'll fix it.

**Comment by htrajan** [comment]
I'll take:

Conspiracy Theorist
Devouring Tendrils
Ecological Appreciation
Efreet Flamepainter
Elite Spellbinder

next.

**Comment by theelk801** [comment]
That's a wrap, thanks to everyone who contributed! I'm gonna leave this open until I deal with all the text issues but otherwise we're done.

**Comment by dosfod** [comment]
Is this set released to the main server? I can't find any cards from it, only on beta...

Thanks for the efforts :)

**Comment by RafaelMion** [comment]
when this set  will released to the main server?

**Comment by JayDi85** [comment]
Today in 1-2 hours.
