### ISSUE TITLE
C21 - Commander 2021 Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7694]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Adrix and Nev, Twincasters](https://scryfall.com/search?q=!adrixandnevtwincasters)
- [x] Done -- [Aether Gale](https://scryfall.com/search?q=!aethergale)
- [x] Done -- [Aetherspouts](https://scryfall.com/search?q=!aetherspouts)
- [x] Done -- [Ageless Entity](https://scryfall.com/search?q=!agelessentity)
- [x] Done -- [Alhammarret's Archive](https://scryfall.com/search?q=!alhammarretsarchive)
- [x] Done -- [Alibou, Ancient Witness](https://scryfall.com/search?q=!alibouancientwitness)
- [x] Done -- [Ambition's Cost](https://scryfall.com/search?q=!ambitionscost)
- [x] Done -- [Ancient Craving](https://scryfall.com/search?q=!ancientcraving)
- [x] Done -- [Ancient Den](https://scryfall.com/search?q=!ancientden)
- [x] Done -- [Angel of Serenity](https://scryfall.com/search?q=!angelofserenity)
- [x] Done -- [Angel of the Ruins](https://scryfall.com/search?q=!angeloftheruins)
- [x] Done -- [Apex of Power](https://scryfall.com/search?q=!apexofpower)
- [x] Done -- [Arashi, the Sky Asunder](https://scryfall.com/search?q=!arashitheskyasunder)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Archaeomancer's Map](https://scryfall.com/search?q=!archaeomancersmap)
- [x] Done -- [Audacious Reshapers](https://scryfall.com/search?q=!audaciousreshapers)
- [x] Done -- [Author of Shadows](https://scryfall.com/search?q=!authorofshadows)
- [x] Done -- [Barren Moor](https://scryfall.com/search?q=!barrenmoor)
- [x] Done -- [Battlefield Forge](https://scryfall.com/search?q=!battlefieldforge)
- [x] Done -- [Battlemage's Bracers](https://scryfall.com/search?q=!battlemagesbracers)
- [x] Done -- [Beast Within](https://scryfall.com/search?q=!beastwithin)
- [x] Done -- [Biomass Mutation](https://scryfall.com/search?q=!biomassmutation)
- [x] Done -- [Blasphemous Act](https://scryfall.com/search?q=!blasphemousact)
- [x] Done -- [Blight Mound](https://scryfall.com/search?q=!blightmound)
- [x] Done -- [Blighted Cataract](https://scryfall.com/search?q=!blightedcataract)
- [x] Done -- [Blighted Woodland](https://scryfall.com/search?q=!blightedwoodland)
- [x] Done -- [Bloodthirsty Aerialist](https://scryfall.com/search?q=!bloodthirstyaerialist)
- [x] Done -- [Bloodthirsty Blade](https://scryfall.com/search?q=!bloodthirstyblade)
- [x] Done -- [Bloodtracker](https://scryfall.com/search?q=!bloodtracker)
- [x] Done -- [Blossoming Bogbeast](https://scryfall.com/search?q=!blossomingbogbeast)
- [x] Done -- [Bojuka Bog](https://scryfall.com/search?q=!bojukabog)
- [x] Done -- [Bold Plagiarist](https://scryfall.com/search?q=!boldplagiarist)
- [x] Done -- [Boreas Charger](https://scryfall.com/search?q=!boreascharger)
- [x] Done -- [Boros Charm](https://scryfall.com/search?q=!boroscharm)
- [x] Done -- [Boros Garrison](https://scryfall.com/search?q=!borosgarrison)
- [x] Done -- [Boros Locket](https://scryfall.com/search?q=!boroslocket)
- [x] Done -- [Bosh, Iron Golem](https://scryfall.com/search?q=!boshirongolem)
- [x] Done -- [Brainstorm](https://scryfall.com/search?q=!brainstorm)
- [x] Done -- [Brass's Bounty](https://scryfall.com/search?q=!brasssbounty)
- [x] Done -- [Breena, the Demagogue](https://scryfall.com/search?q=!breenathedemagogue)
- [x] Done -- [Bronze Guardian](https://scryfall.com/search?q=!bronzeguardian)
- [x] Done -- [Burnished Hart](https://scryfall.com/search?q=!burnishedhart)
- [x] Done -- [Call the Skybreaker](https://scryfall.com/search?q=!calltheskybreaker)
- [x] Done -- [Caves of Koilos](https://scryfall.com/search?q=!cavesofkoilos)
- [x] Done -- [Chain Reaction](https://scryfall.com/search?q=!chainreaction)
- [x] Done -- [Champion of Wits](https://scryfall.com/search?q=!championofwits)
- [x] Done -- [Charmbreaker Devils](https://scryfall.com/search?q=!charmbreakerdevils)
- [x] Done -- [Citadel Siege](https://scryfall.com/search?q=!citadelsiege)
- [x] Done -- [Cleansing Nova](https://scryfall.com/search?q=!cleansingnova)
- [x] Done -- [Coiling Oracle](https://scryfall.com/search?q=!coilingoracle)
- [x] Done -- [Combat Calligrapher](https://scryfall.com/search?q=!combatcalligrapher)
- [x] Done -- [Combustible Gearhulk](https://scryfall.com/search?q=!combustiblegearhulk)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Commander's Insight](https://scryfall.com/search?q=!commandersinsight)
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=!commanderssphere)
- [x] Done -- [Coveted Jewel](https://scryfall.com/search?q=!covetedjewel)
- [x] Done -- [Crackling Drake](https://scryfall.com/search?q=!cracklingdrake)
- [x] Done -- [Crafty Cutpurse](https://scryfall.com/search?q=!craftycutpurse)
- [x] Done -- [Creative Technique](https://scryfall.com/search?q=!creativetechnique)
- [x] Done -- [Cultivate](https://scryfall.com/search?q=!cultivate)
- [x] Done -- [Cunning Rhetoric](https://scryfall.com/search?q=!cunningrhetoric)
- [x] Done -- [Curiosity Crafter](https://scryfall.com/search?q=!curiositycrafter)
- [x] Done -- [Curse of Disturbance](https://scryfall.com/search?q=!curseofdisturbance)
- [x] Done -- [Curse of the Swine](https://scryfall.com/search?q=!curseoftheswine)
- [x] Done -- [Cursed Mirror](https://scryfall.com/search?q=!cursedmirror)
- [x] Done -- [Damnable Pact](https://scryfall.com/search?q=!damnablepact)
- [x] Done -- [Daretti, Scrap Savant](https://scryfall.com/search?q=!darettiscrapsavant)
- [x] Done -- [Darksteel Citadel](https://scryfall.com/search?q=!darksteelcitadel)
- [x] Done -- [Darksteel Mutation](https://scryfall.com/search?q=!darksteelmutation)
- [x] Done -- [Dazzling Sphinx](https://scryfall.com/search?q=!dazzlingsphinx)
- [x] Done -- [Deadly Tempest](https://scryfall.com/search?q=!deadlytempest)
- [x] Done -- [Deathbringer Liege](https://scryfall.com/search?q=!deathbringerliege)
- [x] Done -- [Deathbringer Regent](https://scryfall.com/search?q=!deathbringerregent)
- [x] Done -- [Debtors' Knell](https://scryfall.com/search?q=!debtorsknell)
- [x] Done -- [Deekah, Fractal Theorist](https://scryfall.com/search?q=!deekahfractaltheorist)
- [x] Done -- [Defiant Bloodlord](https://scryfall.com/search?q=!defiantbloodlord)
- [x] Done -- [Desert of the Fervent](https://scryfall.com/search?q=!desertofthefervent)
- [x] Done -- [Desert of the Mindful](https://scryfall.com/search?q=!desertofthemindful)
- [x] Done -- [Desolation Twin](https://scryfall.com/search?q=!desolationtwin)
- [x] Done -- [Dig Through Time](https://scryfall.com/search?q=!digthroughtime)
- [x] Done -- [Digsite Engineer](https://scryfall.com/search?q=!digsiteengineer)
- [x] Done -- [Diluvian Primordial](https://scryfall.com/search?q=!diluvianprimordial)
- [x] Done -- [Dispatch](https://scryfall.com/search?q=!dispatch)
- [x] Done -- [Dispeller's Capsule](https://scryfall.com/search?q=!dispellerscapsule)
- [x] Done -- [Druidic Satchel](https://scryfall.com/search?q=!druidicsatchel)
- [x] Done -- [Dualcaster Mage](https://scryfall.com/search?q=!dualcastermage)
- [x] Done -- [Duelist's Heritage](https://scryfall.com/search?q=!duelistsheritage)
- [x] Done -- [Duplicant](https://scryfall.com/search?q=!duplicant)
- [x] Done -- [Elementalist's Palette](https://scryfall.com/search?q=!elementalistspalette)
- [x] Done -- [Elite Scaleguard](https://scryfall.com/search?q=!elitescaleguard)
- [x] Done -- [Elixir of Immortality](https://scryfall.com/search?q=!elixirofimmortality)
- [x] Done -- [Epic Experiment](https://scryfall.com/search?q=!epicexperiment)
- [x] Done -- [Epicure of Blood](https://scryfall.com/search?q=!epicureofblood)
- [x] Done -- [Erratic Cyclops](https://scryfall.com/search?q=!erraticcyclops)
- [x] Done -- [Esix, Fractal Bloom](https://scryfall.com/search?q=!esixfractalbloom)
- [x] Done -- [Essence Pulse](https://scryfall.com/search?q=!essencepulse)
- [x] Done -- [Etali, Primal Storm](https://scryfall.com/search?q=!etaliprimalstorm)
- [x] Done -- [Excavation Technique](https://scryfall.com/search?q=!excavationtechnique)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Ezuri's Predation](https://scryfall.com/search?q=!ezurispredation)
- [x] Done -- [Ezzaroot Channeler](https://scryfall.com/search?q=!ezzarootchanneler)
- [x] Done -- [Fain, the Broker](https://scryfall.com/search?q=!fainthebroker)
- [x] Done -- [Faithless Looting](https://scryfall.com/search?q=!faithlesslooting)
- [x] Done -- [Feed the Swarm](https://scryfall.com/search?q=!feedtheswarm)
- [x] Done -- [Feldon of the Third Path](https://scryfall.com/search?q=!feldonofthethirdpath)
- [x] Done -- [Felisa, Fang of Silverquill](https://scryfall.com/search?q=!felisafangofsilverquill)
- [x] Done -- [Fiery Encore](https://scryfall.com/search?q=!fieryencore)
- [x] Done -- [Fiery Fall](https://scryfall.com/search?q=!fieryfall)
- [x] Done -- [Forgotten Ancient](https://scryfall.com/search?q=!forgottenancient)
- [x] Done -- [Forgotten Cave](https://scryfall.com/search?q=!forgottencave)
- [x] Done -- [Fractal Harness](https://scryfall.com/search?q=!fractalharness)
- [x] Done -- [Garruk, Primal Hunter](https://scryfall.com/search?q=!garrukprimalhunter)
- [x] Done -- [Gaze of Granite](https://scryfall.com/search?q=!gazeofgranite)
- [x] Done -- [Geometric Nexus](https://scryfall.com/search?q=!geometricnexus)
- [x] Done -- [Ghostly Prison](https://scryfall.com/search?q=!ghostlyprison)
- [x] Done -- [Gideon, Champion of Justice](https://scryfall.com/search?q=!gideonchampionofjustice)
- [x] Done -- [Gift of Paradise](https://scryfall.com/search?q=!giftofparadise)
- [x] Done -- [Gingerbread Cabin](https://scryfall.com/search?q=!gingerbreadcabin)
- [x] Done -- [Gluttonous Troll](https://scryfall.com/search?q=!gluttonoustroll)
- [x] Done -- [Golgari Rot Farm](https://scryfall.com/search?q=!golgarirotfarm)
- [x] Done -- [Great Furnace](https://scryfall.com/search?q=!greatfurnace)
- [x] Done -- [Greed](https://scryfall.com/search?q=!greed)
- [x] Done -- [Guardian Archon](https://scryfall.com/search?q=!guardianarchon)
- [x] Done -- [Guardian Augmenter](https://scryfall.com/search?q=!guardianaugmenter)
- [x] Done -- [Gyome, Master Chef](https://scryfall.com/search?q=!gyomemasterchef)
- [x] Done -- [Healing Technique](https://scryfall.com/search?q=!healingtechnique)
- [x] Done -- [Hedron Archive](https://scryfall.com/search?q=!hedronarchive)
- [x] Done -- [Hellkite Igniter](https://scryfall.com/search?q=!hellkiteigniter)
- [x] Done -- [Hellkite Tyrant](https://scryfall.com/search?q=!hellkitetyrant)
- [x] Done -- [High Market](https://scryfall.com/search?q=!highmarket)
- [x] Done -- [Hoard-Smelter Dragon](https://scryfall.com/search?q=!hoardsmelterdragon)
- [x] Done -- [Hornet Nest](https://scryfall.com/search?q=!hornetnest)
- [x] Done -- [Hornet Queen](https://scryfall.com/search?q=!hornetqueen)
- [x] Done -- [Humble Defector](https://scryfall.com/search?q=!humbledefector)
- [x] Done -- [Hunted Lammasu](https://scryfall.com/search?q=!huntedlammasu)
- [x] Done -- [Hydra Broodmaster](https://scryfall.com/search?q=!hydrabroodmaster)
- [x] Done -- [Ichor Wellspring](https://scryfall.com/search?q=!ichorwellspring)
- [x] Done -- [Idol of Oblivion](https://scryfall.com/search?q=!idolofoblivion)
- [x] Done -- [Incarnation Technique](https://scryfall.com/search?q=!incarnationtechnique)
- [x] Done -- [Incubation // Incongruity](https://scryfall.com/search?q=!incubation//incongruity)
- [x] Done -- [Incubation Druid](https://scryfall.com/search?q=!incubationdruid)
- [x] Done -- [Infernal Offering](https://scryfall.com/search?q=!infernaloffering)
- [x] Done -- [Inferno Project](https://scryfall.com/search?q=!infernoproject)
- [x] Done -- [Inkshield](https://scryfall.com/search?q=!inkshield)
- [x] Done -- [Inspiring Refrain](https://scryfall.com/search?q=!inspiringrefrain)
- [x] Done -- [Izzet Boilerworks](https://scryfall.com/search?q=!izzetboilerworks)
- [x] Done -- [Izzet Signet](https://scryfall.com/search?q=!izzetsignet)
- [x] Done -- [Jaya Ballard](https://scryfall.com/search?q=!jayaballard)
- [x] Done -- [Jor Kadeen, the Prevailer](https://scryfall.com/search?q=!jorkadeentheprevailer)
- [x] Done -- [Jungle Hollow](https://scryfall.com/search?q=!junglehollow)
- [x] Done -- [Kaseto, Orochi Archmage](https://scryfall.com/search?q=!kasetoorochiarchmage)
- [x] Done -- [Kazandu Tuskcaller](https://scryfall.com/search?q=!kazandutuskcaller)
- [x] Done -- [Keen Duelist](https://scryfall.com/search?q=!keenduelist)
- [x] Done -- [Key to the City](https://scryfall.com/search?q=!keytothecity)
- [x] Done -- [Knight of the White Orchid](https://scryfall.com/search?q=!knightofthewhiteorchid)
- [x] Done -- [Kodama's Reach](https://scryfall.com/search?q=!kodamasreach)
- [x] Done -- [Krosan Grip](https://scryfall.com/search?q=!krosangrip)
- [x] Done -- [Laelia, the Blade Reforged](https://scryfall.com/search?q=!laeliathebladereforged)
- [x] Done -- [Leyline Prowler](https://scryfall.com/search?q=!leylineprowler)
- [x] Done -- [Living Lore](https://scryfall.com/search?q=!livinglore)
- [x] Done -- [Llanowar Reborn](https://scryfall.com/search?q=!llanowarreborn)
- [x] Done -- [Llanowar Wastes](https://scryfall.com/search?q=!llanowarwastes)
- [x] Done -- [Lonely Sandbar](https://scryfall.com/search?q=!lonelysandbar)
- [x] Done -- [Losheel, Clockwork Scholar](https://scryfall.com/search?q=!losheelclockworkscholar)
- [x] Done -- [Loxodon Warhammer](https://scryfall.com/search?q=!loxodonwarhammer)
- [x] Done -- [Lumbering Falls](https://scryfall.com/search?q=!lumberingfalls)
- [x] Done -- [Mage-Ring Network](https://scryfall.com/search?q=!mageringnetwork)
- [x] Done -- [Magister of Worth](https://scryfall.com/search?q=!magisterofworth)
- [x] Done -- [Mana Geyser](https://scryfall.com/search?q=!manageyser)
- [x] Done -- [Managorger Hydra](https://scryfall.com/search?q=!managorgerhydra)
- [x] Done -- [Marshland Bloodcaster](https://scryfall.com/search?q=!marshlandbloodcaster)
- [x] Done -- [Martial Impetus](https://scryfall.com/search?q=!martialimpetus)
- [x] Done -- [Master Biomancer](https://scryfall.com/search?q=!masterbiomancer)
- [x] Done -- [Memorial to Genius](https://scryfall.com/search?q=!memorialtogenius)
- [x] Done -- [Metallurgic Summonings](https://scryfall.com/search?q=!metallurgicsummonings)
- [x] Done -- [Meteor Golem](https://scryfall.com/search?q=!meteorgolem)
- [x] Done -- [Mikokoro, Center of the Sea](https://scryfall.com/search?q=!mikokorocenterofthesea)
- [x] Done -- [Mind Stone](https://scryfall.com/search?q=!mindstone)
- [x] Done -- [Mind's Desire](https://scryfall.com/search?q=!mindsdesire)
- [x] Done -- [Moldervine Reclamation](https://scryfall.com/search?q=!moldervinereclamation)
- [x] Done -- [Monologue Tax](https://scryfall.com/search?q=!monologuetax)
- [x] Done -- [Mosswort Bridge](https://scryfall.com/search?q=!mosswortbridge)
- [x] Done -- [Muse Vortex](https://scryfall.com/search?q=!musevortex)
- [x] Done -- [Mycosynth Wellspring](https://scryfall.com/search?q=!mycosynthwellspring)
- [x] Done -- [Myr Battlesphere](https://scryfall.com/search?q=!myrbattlesphere)
- [x] Done -- [Myriad Landscape](https://scryfall.com/search?q=!myriadlandscape)
- [x] Done -- [Naru Meha, Master Wizard](https://scryfall.com/search?q=!narumehamasterwizard)
- [x] Done -- [Necropolis Regent](https://scryfall.com/search?q=!necropolisregent)
- [x] Done -- [Nils, Discipline Enforcer](https://scryfall.com/search?q=!nilsdisciplineenforcer)
- [x] Done -- [Nissa's Expedition](https://scryfall.com/search?q=!nissasexpedition)
- [x] Done -- [Nissa's Renewal](https://scryfall.com/search?q=!nissasrenewal)
- [x] Done -- [Novijen, Heart of Progress](https://scryfall.com/search?q=!novijenheartofprogress)
- [x] Done -- [Noxious Gearhulk](https://scryfall.com/search?q=!noxiousgearhulk)
- [x] Done -- [Ob Nixilis Reignited](https://scryfall.com/search?q=!obnixilisreignited)
- [x] Done -- [Oblation](https://scryfall.com/search?q=!oblation)
- [x] Done -- [Octavia, Living Thesis](https://scryfall.com/search?q=!octavialivingthesis)
- [x] Done -- [Opal Palace](https://scryfall.com/search?q=!opalpalace)
- [x] Done -- [Oran-Rief, the Vastwood](https://scryfall.com/search?q=!oranriefthevastwood)
- [x] Done -- [Oreskos Explorer](https://scryfall.com/search?q=!oreskosexplorer)
- [x] Done -- [Orzhov Advokist](https://scryfall.com/search?q=!orzhovadvokist)
- [x] Done -- [Orzhov Basilica](https://scryfall.com/search?q=!orzhovbasilica)
- [x] Done -- [Orzhov Signet](https://scryfall.com/search?q=!orzhovsignet)
- [x] Done -- [Osgir, the Reconstructor](https://scryfall.com/search?q=!osgirthereconstructor)
- [x] Done -- [Oversimplify](https://scryfall.com/search?q=!oversimplify)
- [x] Done -- [Paradise Plume](https://scryfall.com/search?q=!paradiseplume)
- [x] Done -- [Paradox Zone](https://scryfall.com/search?q=!paradoxzone)
- [x] Done -- [Parasitic Impetus](https://scryfall.com/search?q=!parasiticimpetus)
- [x] Done -- [Pendant of Prosperity](https://scryfall.com/search?q=!pendantofprosperity)
- [x] Done -- [Perplexing Test](https://scryfall.com/search?q=!perplexingtest)
- [x] Done -- [Pest Infestation](https://scryfall.com/search?q=!pestinfestation)
- [x] Done -- [Phyrexia's Core](https://scryfall.com/search?q=!phyrexiascore)
- [x] Done -- [Pia Nalaar](https://scryfall.com/search?q=!pianalaar)
- [x] Done -- [Pilgrim's Eye](https://scryfall.com/search?q=!pilgrimseye)
- [x] Done -- [Plaxcaster Frogling](https://scryfall.com/search?q=!plaxcasterfrogling)
- [x] Done -- [Ponder](https://scryfall.com/search?q=!ponder)
- [x] Done -- [Primal Empathy](https://scryfall.com/search?q=!primalempathy)
- [x] Done -- [Pristine Talisman](https://scryfall.com/search?q=!pristinetalisman)
- [x] Done -- [Promise of Loyalty](https://scryfall.com/search?q=!promiseofloyalty)
- [x] Done -- [Pulse of Murasa](https://scryfall.com/search?q=!pulseofmurasa)
- [x] Done -- [Pyromancer's Goggles](https://scryfall.com/search?q=!pyromancersgoggles)
- [x] Done -- [Quicksmith Genius](https://scryfall.com/search?q=!quicksmithgenius)
- [x] Done -- [Radiant Fountain](https://scryfall.com/search?q=!radiantfountain)
- [x] Done -- [Radiant Performer](https://scryfall.com/search?q=!radiantperformer)
- [x] Done -- [Rampaging Baloths](https://scryfall.com/search?q=!rampagingbaloths)
- [x] Done -- [Rampant Growth](https://scryfall.com/search?q=!rampantgrowth)
- [x] Done -- [Rapid Hybridization](https://scryfall.com/search?q=!rapidhybridization)
- [x] Done -- [Reckless Spite](https://scryfall.com/search?q=!recklessspite)
- [x] Done -- [Reef Worm](https://scryfall.com/search?q=!reefworm)
- [x] Done -- [Reinterpret](https://scryfall.com/search?q=!reinterpret)
- [x] Done -- [Reliquary Tower](https://scryfall.com/search?q=!reliquarytower)
- [x] Done -- [Replication Technique](https://scryfall.com/search?q=!replicationtechnique)
- [x] Done -- [Return of the Wildspeaker](https://scryfall.com/search?q=!returnofthewildspeaker)
- [x] Done -- [Return to Dust](https://scryfall.com/search?q=!returntodust)
- [x] Done -- [Revival Experiment](https://scryfall.com/search?q=!revivalexperiment)
- [x] Done -- [Rionya, Fire Dancer](https://scryfall.com/search?q=!rionyafiredancer)
- [x] Done -- [Rite of Replication](https://scryfall.com/search?q=!riteofreplication)
- [x] Done -- [Rogue's Passage](https://scryfall.com/search?q=!roguespassage)
- [x] Done -- [Rousing Refrain](https://scryfall.com/search?q=!rousingrefrain)
- [x] Done -- [Rout](https://scryfall.com/search?q=!rout)
- [x] Done -- [Ruin Grinder](https://scryfall.com/search?q=!ruingrinder)
- [x] Done -- [Ruxa, Patient Professor](https://scryfall.com/search?q=!ruxapatientprofessor)
- [x] Done -- [Sanctum Gargoyle](https://scryfall.com/search?q=!sanctumgargoyle)
- [x] Done -- [Sangromancer](https://scryfall.com/search?q=!sangromancer)
- [x] Done -- [Sanguine Bond](https://scryfall.com/search?q=!sanguinebond)
- [x] Done -- [Sapling of Colfenor](https://scryfall.com/search?q=!saplingofcolfenor)
- [x] Done -- [Sapseep Forest](https://scryfall.com/search?q=!sapseepforest)
- [x] Done -- [Scavenger Grounds](https://scryfall.com/search?q=!scavengergrounds)
- [x] Done -- [Scholarship Sponsor](https://scryfall.com/search?q=!scholarshipsponsor)
- [x] Done -- [Scrap Trawler](https://scryfall.com/search?q=!scraptrawler)
- [x] Done -- [Sculpting Steel](https://scryfall.com/search?q=!sculptingsteel)
- [x] Done -- [Secluded Steppe](https://scryfall.com/search?q=!secludedsteppe)
- [x] Done -- [Seething Song](https://scryfall.com/search?q=!seethingsong)
- [x] Done -- [Selfless Squire](https://scryfall.com/search?q=!selflesssquire)
- [x] Done -- [Sequence Engine](https://scryfall.com/search?q=!sequenceengine)
- [x] Done -- [Serum Visions](https://scryfall.com/search?q=!serumvisions)
- [x] Done -- [Shamanic Revelation](https://scryfall.com/search?q=!shamanicrevelation)
- [x] Done -- [Shivan Reef](https://scryfall.com/search?q=!shivanreef)
- [x] Done -- [Silversmote Ghoul](https://scryfall.com/search?q=!silversmoteghoul)
- [x] Done -- [Simic Growth Chamber](https://scryfall.com/search?q=!simicgrowthchamber)
- [x] Done -- [Simic Signet](https://scryfall.com/search?q=!simicsignet)
- [x] Done -- [Slayers' Stronghold](https://scryfall.com/search?q=!slayersstronghold)
- [x] Done -- [Sly Instigator](https://scryfall.com/search?q=!slyinstigator)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Solemn Simulacrum](https://scryfall.com/search?q=!solemnsimulacrum)
- [x] Done -- [Soul Snare](https://scryfall.com/search?q=!soulsnare)
- [x] Done -- [Spawning Kraken](https://scryfall.com/search?q=!spawningkraken)
- [x] Done -- [Spectral Searchlight](https://scryfall.com/search?q=!spectralsearchlight)
- [x] Done -- [Spitting Image](https://scryfall.com/search?q=!spittingimage)
- [x] Done -- [Sproutback Trudge](https://scryfall.com/search?q=!sproutbacktrudge)
- [x] Done -- [Stalking Leonin](https://scryfall.com/search?q=!stalkingleonin)
- [x] Done -- [Steel Hellkite](https://scryfall.com/search?q=!steelhellkite)
- [x] Done -- [Steel Overseer](https://scryfall.com/search?q=!steeloverseer)
- [x] Done -- [Stinging Study](https://scryfall.com/search?q=!stingingstudy)
- [x] Done -- [Study Hall](https://scryfall.com/search?q=!studyhall)
- [x] Done -- [Suffer the Past](https://scryfall.com/search?q=!sufferthepast)
- [x] Done -- [Sun Droplet](https://scryfall.com/search?q=!sundroplet)
- [x] Done -- [Sun Titan](https://scryfall.com/search?q=!suntitan)
- [x] Done -- [Sunbird's Invocation](https://scryfall.com/search?q=!sunbirdsinvocation)
- [x] Done -- [Sunhome, Fortress of the Legion](https://scryfall.com/search?q=!sunhomefortressofthelegion)
- [x] Done -- [Sunscorch Regent](https://scryfall.com/search?q=!sunscorchregent)
- [x] Done -- [Surge to Victory](https://scryfall.com/search?q=!surgetovictory)
- [x] Done -- [Swarm Intelligence](https://scryfall.com/search?q=!swarmintelligence)
- [x] Done -- [Tainted Field](https://scryfall.com/search?q=!taintedfield)
- [x] Done -- [Tainted Wood](https://scryfall.com/search?q=!taintedwood)
- [x] Done -- [Talisman of Creativity](https://scryfall.com/search?q=!talismanofcreativity)
- [x] Done -- [Talisman of Resilience](https://scryfall.com/search?q=!talismanofresilience)
- [x] Done -- [Talrand, Sky Summoner](https://scryfall.com/search?q=!talrandskysummoner)
- [x] Done -- [Taste of Death](https://scryfall.com/search?q=!tasteofdeath)
- [x] Done -- [Temple of Epiphany](https://scryfall.com/search?q=!templeofepiphany)
- [x] Done -- [Temple of Malady](https://scryfall.com/search?q=!templeofmalady)
- [x] Done -- [Temple of Mystery](https://scryfall.com/search?q=!templeofmystery)
- [x] Done -- [Temple of Silence](https://scryfall.com/search?q=!templeofsilence)
- [x] Done -- [Temple of Triumph](https://scryfall.com/search?q=!templeoftriumph)
- [x] Done -- [Temple of the False God](https://scryfall.com/search?q=!templeofthefalsegod)
- [x] Done -- [Tempting Contract](https://scryfall.com/search?q=!temptingcontract)
- [x] Done -- [Terastodon](https://scryfall.com/search?q=!terastodon)
- [x] Done -- [Teysa, Envoy of Ghosts](https://scryfall.com/search?q=!teysaenvoyofghosts)
- [x] Done -- [Theoretical Duplication](https://scryfall.com/search?q=!theoreticalduplication)
- [x] Done -- [Thopter Engineer](https://scryfall.com/search?q=!thopterengineer)
- [x] Done -- [Thousand-Year Elixir](https://scryfall.com/search?q=!thousandyearelixir)
- [x] Done -- [Tivash, Gloom Summoner](https://scryfall.com/search?q=!tivashgloomsummoner)
- [x] Done -- [Together Forever](https://scryfall.com/search?q=!togetherforever)
- [x] Done -- [Tragic Arrogance](https://scryfall.com/search?q=!tragicarrogance)
- [x] Done -- [Tranquil Thicket](https://scryfall.com/search?q=!tranquilthicket)
- [x] Done -- [Traumatic Visions](https://scryfall.com/search?q=!traumaticvisions)
- [x] Done -- [Treasure Cruise](https://scryfall.com/search?q=!treasurecruise)
- [x] Done -- [Triplicate Titan](https://scryfall.com/search?q=!triplicatetitan)
- [x] Done -- [Trudge Garden](https://scryfall.com/search?q=!trudgegarden)
- [x] Done -- [Trygon Predator](https://scryfall.com/search?q=!trygonpredator)
- [x] Done -- [Unstable Obelisk](https://scryfall.com/search?q=!unstableobelisk)
- [x] Done -- [Utter End](https://scryfall.com/search?q=!utterend)
- [x] Done -- [Vampire Nighthawk](https://scryfall.com/search?q=!vampirenighthawk)
- [x] Done -- [Veinwitch Coven](https://scryfall.com/search?q=!veinwitchcoven)
- [x] Done -- [Venser's Journal](https://scryfall.com/search?q=!vensersjournal)
- [x] Done -- [Verdant Sun's Avatar](https://scryfall.com/search?q=!verdantsunsavatar)
- [x] Done -- [Veyran, Voice of Duality](https://scryfall.com/search?q=!veyranvoiceofduality)
- [x] Done -- [Victory Chimes](https://scryfall.com/search?q=!victorychimes)
- [x] Done -- [Volcanic Vision](https://scryfall.com/search?q=!volcanicvision)
- [x] Done -- [Vow of Duty](https://scryfall.com/search?q=!vowofduty)
- [x] Done -- [Wake the Past](https://scryfall.com/search?q=!wakethepast)
- [x] Done -- [Well of Lost Dreams](https://scryfall.com/search?q=!welloflostdreams)
- [x] Done -- [Wildfire Devils](https://scryfall.com/search?q=!wildfiredevils)
- [x] Done -- [Willowdusk, Essence Seer](https://scryfall.com/search?q=!willowduskessenceseer)
- [x] Done -- [Windborn Muse](https://scryfall.com/search?q=!windbornmuse)
- [x] Done -- [Witch's Clinic](https://scryfall.com/search?q=!witchsclinic)
- [x] Done -- [Yavimaya Coast](https://scryfall.com/search?q=!yavimayacoast)
- [x] Done -- [Yedora, Grave Gardener](https://scryfall.com/search?q=!yedoragravegardener)
- [x] Done -- [Zaffai, Thunder Conductor](https://scryfall.com/search?q=!zaffaithunderconductor)
- [x] Done -- [Zetalpa, Primal Dawn](https://scryfall.com/search?q=!zetalpaprimaldawn)
</details>

**Comment by theelk801** [comment]
- [ ] In progress -- [Adrix and Nev, Twincasters](https://scryfall.com/search?q=!"Adrix+and+Nev,+Twincasters")
- [ ] In progress -- [Breena, the Demagogue](https://scryfall.com/search?q=!"Breena,+the+Demagogue")
- [ ] In progress -- [Osgir, the Reconstructor](https://scryfall.com/search?q=!"Osgir,+the+Reconstructor")
- [ ] In progress -- [Willowdusk, Essence Seer](https://scryfall.com/search?q=!"Willowdusk,+Essence+Seer")
- [ ] In progress -- [Zaffai, Thunder Conductor](https://scryfall.com/search?q=!"Zaffai,+Thunder+Conductor")

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"adrixandnevtwincasters"or!"breenathedemagogue"or!"osgirthereconstructor"or!"willowduskessenceseer"or!"zaffaithunderconductor"&unique=cards)

**Comment by arketec** [comment]
I have implemented Osgir, the Reconstructor, how do I request a PR? 

I tried to push a branch but received a 403 unauthorized response

**Comment by theelk801** [comment]
I'm waiting on Laelia right now as there's apparently an incoming errata to that card and a few other ones, otherwise the set is done.

**Comment by alexander-novo** [comment]
@theelk801 I think Laelia has already received errata on gatherer. If you look on scryfall they changed the second ability to read
> Whenever **a spell or ability you control** exiles

**Comment by theelk801** [comment]
Right, but there’s [more](https://twitter.com/dunkatog/status/1385368740905115649) coming on top of that

**Comment by jmharmon** [comment]
@theelk801 what are the other changes? Laelia seems to work with multiple cards that exile cards from the hand and library. Here's the ones I test it with.

Azor's Gateway
Bomat Courier
Cave-In
Demon Bolt
Pyxis of Pandemonium

**Comment by theelk801** [comment]
It needs to work when you exile something as a cost like Foretell or Force of Will/

**Comment by jmharmon** [comment]
I made the PR, everything looks like it works correctly.

**Comment by theelk801** [comment]
Thanks, C21 is now done.
