### ISSUE TITLE
MH2 - Modern Horizons 2 Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7807]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abiding Grace](https://scryfall.com/search?q=!abidinggrace)
- [x] Done -- [Abundant Harvest](https://scryfall.com/search?q=!abundantharvest)
- [x] Done -- [Academy Manufactor](https://scryfall.com/search?q=!academymanufactor)
- [x] Done -- [Aeromoeba](https://scryfall.com/search?q=!aeromoeba)
- [x] Done -- [Aeve, Progenitor Ooze](https://scryfall.com/search?q=!aeveprogenitorooze)
- [x] Done -- [Altar of the Goyf](https://scryfall.com/search?q=!altarofthegoyf)
- [x] Done -- [Angelic Curator](https://scryfall.com/search?q=!angeliccurator)
- [x] Done -- [Arcbound Javelineer](https://scryfall.com/search?q=!arcboundjavelineer)
- [x] Done -- [Arcbound Mouser](https://scryfall.com/search?q=!arcboundmouser)
- [x] Done -- [Arcbound Prototype](https://scryfall.com/search?q=!arcboundprototype)
- [x] Done -- [Arcbound Shikari](https://scryfall.com/search?q=!arcboundshikari)
- [x] Done -- [Arcbound Slasher](https://scryfall.com/search?q=!arcboundslasher)
- [x] Done -- [Arcbound Tracker](https://scryfall.com/search?q=!arcboundtracker)
- [x] Done -- [Arcbound Whelp](https://scryfall.com/search?q=!arcboundwhelp)
- [x] Done -- [Archfiend of Sorrows](https://scryfall.com/search?q=!archfiendofsorrows)
- [x] Done -- [Archon of Cruelty](https://scryfall.com/search?q=!archonofcruelty)
- [x] Done -- [Arcus Acolyte](https://scryfall.com/search?q=!arcusacolyte)
- [x] Done -- [Arid Mesa](https://scryfall.com/search?q=!aridmesa)
- [x] Done -- [Asmoranomardicadaistinaculdacar](https://scryfall.com/search?q=!asmoranomardicadaistinaculdacar)
- [x] Done -- [Bannerhide Krushok](https://scryfall.com/search?q=!bannerhidekrushok)
- [x] Done -- [Barbed Spike](https://scryfall.com/search?q=!barbedspike)
- [x] Done -- [Batterbone](https://scryfall.com/search?q=!batterbone)
- [x] Done -- [Battle Plan](https://scryfall.com/search?q=!battleplan)
- [x] Done -- [Blacksmith's Skill](https://scryfall.com/search?q=!blacksmithsskill)
- [x] Done -- [Blazing Rootwalla](https://scryfall.com/search?q=!blazingrootwalla)
- [x] Done -- [Blessed Respite](https://scryfall.com/search?q=!blessedrespite)
- [x] Done -- [Bloodbraid Marauder](https://scryfall.com/search?q=!bloodbraidmarauder)
- [x] Done -- [Blossoming Calm](https://scryfall.com/search?q=!blossomingcalm)
- [x] Done -- [Bone Shards](https://scryfall.com/search?q=!boneshards)
- [x] Done -- [Bone Shredder](https://scryfall.com/search?q=!boneshredder)
- [x] Done -- [Bottle Golems](https://scryfall.com/search?q=!bottlegolems)
- [x] Done -- [Braids, Cabal Minion](https://scryfall.com/search?q=!braidscabalminion)
- [x] Done -- [Brainstone](https://scryfall.com/search?q=!brainstone)
- [x] Done -- [Break Ties](https://scryfall.com/search?q=!breakties)
- [x] Done -- [Break the Ice](https://scryfall.com/search?q=!breaktheice)
- [x] Done -- [Breathless Knight](https://scryfall.com/search?q=!breathlessknight)
- [x] Done -- [Breya's Apprentice](https://scryfall.com/search?q=!breyasapprentice)
- [x] Done -- [Burdened Aerialist](https://scryfall.com/search?q=!burdenedaerialist)
- [x] Done -- [Cabal Coffers](https://scryfall.com/search?q=!cabalcoffers)
- [x] Done -- [Cabal Initiate](https://scryfall.com/search?q=!cabalinitiate)
- [x] Done -- [Calibrated Blast](https://scryfall.com/search?q=!calibratedblast)
- [x] Done -- [Caprichrome](https://scryfall.com/search?q=!caprichrome)
- [x] Done -- [Captain Ripley Vance](https://scryfall.com/search?q=!captainripleyvance)
- [x] Done -- [Captured by Lagacs](https://scryfall.com/search?q=!capturedbylagacs)
- [x] Done -- [Carth the Lion](https://scryfall.com/search?q=!carththelion)
- [x] Done -- [Chainer, Nightmare Adept](https://scryfall.com/search?q=!chainernightmareadept)
- [x] Done -- [Chance Encounter](https://scryfall.com/search?q=!chanceencounter)
- [x] Done -- [Chatterfang, Squirrel General](https://scryfall.com/search?q=!chatterfangsquirrelgeneral)
- [x] Done -- [Chatterstorm](https://scryfall.com/search?q=!chatterstorm)
- [x] Done -- [Chef's Kiss](https://scryfall.com/search?q=!chefskiss)
- [x] Done -- [Chitterspitter](https://scryfall.com/search?q=!chitterspitter)
- [x] Done -- [Chrome Courier](https://scryfall.com/search?q=!chromecourier)
- [x] Done -- [Clattering Augur](https://scryfall.com/search?q=!clatteringaugur)
- [x] Done -- [Combine Chrysalis](https://scryfall.com/search?q=!combinechrysalis)
- [x] Done -- [Constable of the Realm](https://scryfall.com/search?q=!constableoftherealm)
- [x] Done -- [Counterspell](https://scryfall.com/search?q=!counterspell)
- [x] Done -- [Crack Open](https://scryfall.com/search?q=!crackopen)
- [x] Done -- [Cursed Totem](https://scryfall.com/search?q=!cursedtotem)
- [x] Done -- [Dakkon, Shadow Slayer](https://scryfall.com/search?q=!dakkonshadowslayer)
- [x] Done -- [Damn](https://scryfall.com/search?q=!damn)
- [x] Done -- [Darkmoss Bridge](https://scryfall.com/search?q=!darkmossbridge)
- [x] Done -- [Dauthi Voidwalker](https://scryfall.com/search?q=!dauthivoidwalker)
- [x] Done -- [Deepwood Denizen](https://scryfall.com/search?q=!deepwooddenizen)
- [x] Done -- [Dermotaxi](https://scryfall.com/search?q=!dermotaxi)
- [x] Done -- [Diamond Lion](https://scryfall.com/search?q=!diamondlion)
- [x] Done -- [Dihada's Ploy](https://scryfall.com/search?q=!dihadasploy)
- [x] Done -- [Discerning Taste](https://scryfall.com/search?q=!discerningtaste)
- [x] Done -- [Disciple of the Sun](https://scryfall.com/search?q=!discipleofthesun)
- [x] Done -- [Dragon's Rage Channeler](https://scryfall.com/search?q=!dragonsragechanneler)
- [x] Done -- [Dress Down](https://scryfall.com/search?q=!dressdown)
- [x] Done -- [Drey Keeper](https://scryfall.com/search?q=!dreykeeper)
- [x] Done -- [Drossforge Bridge](https://scryfall.com/search?q=!drossforgebridge)
- [x] Done -- [Duskshell Crawler](https://scryfall.com/search?q=!duskshellcrawler)
- [x] Done -- [Echoing Return](https://scryfall.com/search?q=!echoingreturn)
- [x] Done -- [Enchantress's Presence](https://scryfall.com/search?q=!enchantressspresence)
- [x] Done -- [Endurance](https://scryfall.com/search?q=!endurance)
- [x] Done -- [Esper Sentinel](https://scryfall.com/search?q=!espersentinel)
- [x] Done -- [Etherium Spinner](https://scryfall.com/search?q=!etheriumspinner)
- [x] Done -- [Ethersworn Sphinx](https://scryfall.com/search?q=!etherswornsphinx)
- [x] Done -- [Extruder](https://scryfall.com/search?q=!extruder)
- [x] Done -- [Fae Offering](https://scryfall.com/search?q=!faeoffering)
- [x] Done -- [Fairgrounds Patrol](https://scryfall.com/search?q=!fairgroundspatrol)
- [x] Done -- [Faithless Salvaging](https://scryfall.com/search?q=!faithlesssalvaging)
- [x] Done -- [Fast // Furious](https://scryfall.com/search?q=!fast//furious)
- [x] Done -- [Feast of Sanity](https://scryfall.com/search?q=!feastofsanity)
- [x] Done -- [Filigree Attendant](https://scryfall.com/search?q=!filigreeattendant)
- [x] Done -- [Fire // Ice](https://scryfall.com/search?q=!fire//ice)
- [x] Done -- [Flame Blitz](https://scryfall.com/search?q=!flameblitz)
- [x] Done -- [Flame Rift](https://scryfall.com/search?q=!flamerift)
- [x] Done -- [Flametongue Yearling](https://scryfall.com/search?q=!flametongueyearling)
- [x] Done -- [Flay Essence](https://scryfall.com/search?q=!flayessence)
- [x] Done -- [Floodhound](https://scryfall.com/search?q=!floodhound)
- [x] Done -- [Flourishing Strike](https://scryfall.com/search?q=!flourishingstrike)
- [x] Done -- [Fodder Tosser](https://scryfall.com/search?q=!foddertosser)
- [x] Done -- [Foul Watcher](https://scryfall.com/search?q=!foulwatcher)
- [x] Done -- [Foundation Breaker](https://scryfall.com/search?q=!foundationbreaker)
- [x] Done -- [Foundry Helix](https://scryfall.com/search?q=!foundryhelix)
- [x] Done -- [Fractured Sanity](https://scryfall.com/search?q=!fracturedsanity)
- [x] Done -- [Funnel-Web Recluse](https://scryfall.com/search?q=!funnelwebrecluse)
- [x] Done -- [Fury](https://scryfall.com/search?q=!fury)
- [x] Done -- [Gaea's Will](https://scryfall.com/search?q=!gaeaswill)
- [x] Done -- [Galvanic Relay](https://scryfall.com/search?q=!galvanicrelay)
- [x] Done -- [Gargadon](https://scryfall.com/search?q=!gargadon)
- [x] Done -- [Garth One-Eye](https://scryfall.com/search?q=!garthoneeye)
- [x] Done -- [General Ferrous Rokiric](https://scryfall.com/search?q=!generalferrousrokiric)
- [x] Done -- [Geyadrone Dihada](https://scryfall.com/search?q=!geyadronedihada)
- [x] Done -- [Ghost-Lit Drifter](https://scryfall.com/search?q=!ghostlitdrifter)
- [x] Done -- [Gilt-Blade Prowler](https://scryfall.com/search?q=!giltbladeprowler)
- [x] Done -- [Glimmer Bairn](https://scryfall.com/search?q=!glimmerbairn)
- [x] Done -- [Glimpse of Tomorrow](https://scryfall.com/search?q=!glimpseoftomorrow)
- [x] Done -- [Glinting Creeper](https://scryfall.com/search?q=!glintingcreeper)
- [x] Done -- [Glorious Enforcer](https://scryfall.com/search?q=!gloriousenforcer)
- [x] Done -- [Goblin Anarchomancer](https://scryfall.com/search?q=!goblinanarchomancer)
- [x] Done -- [Goblin Bombardment](https://scryfall.com/search?q=!goblinbombardment)
- [x] Done -- [Goblin Traprunner](https://scryfall.com/search?q=!goblintraprunner)
- [x] Done -- [Goldmire Bridge](https://scryfall.com/search?q=!goldmirebridge)
- [x] Done -- [Gorilla Shaman](https://scryfall.com/search?q=!gorillashaman)
- [x] Done -- [Gouged Zealot](https://scryfall.com/search?q=!gougedzealot)
- [x] Done -- [Graceful Restoration](https://scryfall.com/search?q=!gracefulrestoration)
- [x] Done -- [Greed](https://scryfall.com/search?q=!greed)
- [x] Done -- [Grief](https://scryfall.com/search?q=!grief)
- [x] Done -- [Grist, the Hunger Tide](https://scryfall.com/search?q=!gristthehungertide)
- [x] Done -- [Guardian Kirin](https://scryfall.com/search?q=!guardiankirin)
- [x] Done -- [Hard Evidence](https://scryfall.com/search?q=!hardevidence)
- [x] Done -- [Harmonic Prodigy](https://scryfall.com/search?q=!harmonicprodigy)
- [x] Done -- [Healer's Flock](https://scryfall.com/search?q=!healersflock)
- [x] Done -- [Hell Mongrel](https://scryfall.com/search?q=!hellmongrel)
- [x] Done -- [Herd Baloth](https://scryfall.com/search?q=!herdbaloth)
- [x] Done -- [Hunting Pack](https://scryfall.com/search?q=!huntingpack)
- [x] Done -- [Ignoble Hierarch](https://scryfall.com/search?q=!ignoblehierarch)
- [x] Done -- [Imperial Recruiter](https://scryfall.com/search?q=!imperialrecruiter)
- [x] Done -- [Inevitable Betrayal](https://scryfall.com/search?q=!inevitablebetrayal)
- [x] Done -- [Jade Avenger](https://scryfall.com/search?q=!jadeavenger)
- [x] Done -- [Jewel-Eyed Cobra](https://scryfall.com/search?q=!jeweleyedcobra)
- [x] Done -- [Junk Winder](https://scryfall.com/search?q=!junkwinder)
- [x] Done -- [Kaldra Compleat](https://scryfall.com/search?q=!kaldracompleat)
- [x] Done -- [Kaleidoscorch](https://scryfall.com/search?q=!kaleidoscorch)
- [x] Done -- [Karmic Guide](https://scryfall.com/search?q=!karmicguide)
- [x] Done -- [Kitchen Imp](https://scryfall.com/search?q=!kitchenimp)
- [x] Done -- [Knighted Myr](https://scryfall.com/search?q=!knightedmyr)
- [x] Done -- [Landscaper Colos](https://scryfall.com/search?q=!landscapercolos)
- [x] Done -- [Late to Dinner](https://scryfall.com/search?q=!latetodinner)
- [x] Done -- [Lazotep Chancellor](https://scryfall.com/search?q=!lazotepchancellor)
- [x] Done -- [Legion Vanguard](https://scryfall.com/search?q=!legionvanguard)
- [x] Done -- [Lens Flare](https://scryfall.com/search?q=!lensflare)
- [x] Done -- [Lightning Spear](https://scryfall.com/search?q=!lightningspear)
- [x] Done -- [Liquimetal Torque](https://scryfall.com/search?q=!liquimetaltorque)
- [x] Done -- [Loathsome Curator](https://scryfall.com/search?q=!loathsomecurator)
- [x] Done -- [Lonis, Cryptozoologist](https://scryfall.com/search?q=!loniscryptozoologist)
- [x] Done -- [Lose Focus](https://scryfall.com/search?q=!losefocus)
- [x] Done -- [Lucid Dreams](https://scryfall.com/search?q=!luciddreams)
- [x] Done -- [Magus of the Bridge](https://scryfall.com/search?q=!magusofthebridge)
- [x] Done -- [Marble Gargoyle](https://scryfall.com/search?q=!marblegargoyle)
- [x] Done -- [Marsh Flats](https://scryfall.com/search?q=!marshflats)
- [x] Done -- [Master of Death](https://scryfall.com/search?q=!masterofdeath)
- [x] Done -- [Mental Journey](https://scryfall.com/search?q=!mentaljourney)
- [x] Done -- [Millikin](https://scryfall.com/search?q=!millikin)
- [x] Done -- [Mine Collapse](https://scryfall.com/search?q=!minecollapse)
- [x] Done -- [Mirari's Wake](https://scryfall.com/search?q=!mirariswake)
- [x] Done -- [Mishra's Factory](https://scryfall.com/search?q=!mishrasfactory)
- [x] Done -- [Mistvault Bridge](https://scryfall.com/search?q=!mistvaultbridge)
- [x] Done -- [Misty Rainforest](https://scryfall.com/search?q=!mistyrainforest)
- [x] Done -- [Moderation](https://scryfall.com/search?q=!moderation)
- [x] Done -- [Mogg Salvage](https://scryfall.com/search?q=!moggsalvage)
- [x] Done -- [Monoskelion](https://scryfall.com/search?q=!monoskelion)
- [x] Done -- [Mount Velus Manticore](https://scryfall.com/search?q=!mountvelusmanticore)
- [x] Done -- [Murktide Regent](https://scryfall.com/search?q=!murktideregent)
- [x] Done -- [Myr Scrapling](https://scryfall.com/search?q=!myrscrapling)
- [x] Done -- [Mystic Redaction](https://scryfall.com/search?q=!mysticredaction)
- [x] Done -- [Necrogoyf](https://scryfall.com/search?q=!necrogoyf)
- [x] Done -- [Necromancer's Familiar](https://scryfall.com/search?q=!necromancersfamiliar)
- [x] Done -- [Nested Shambler](https://scryfall.com/search?q=!nestedshambler)
- [x] Done -- [Nettlecyst](https://scryfall.com/search?q=!nettlecyst)
- [x] Done -- [Nevinyrral's Disk](https://scryfall.com/search?q=!nevinyrralsdisk)
- [x] Done -- [Nykthos Paragon](https://scryfall.com/search?q=!nykthosparagon)
- [x] Done -- [Obsidian Charmaw](https://scryfall.com/search?q=!obsidiancharmaw)
- [x] Done -- [Orchard Strider](https://scryfall.com/search?q=!orchardstrider)
- [x] Done -- [Ornithopter of Paradise](https://scryfall.com/search?q=!ornithopterofparadise)
- [x] Done -- [Out of Time](https://scryfall.com/search?q=!outoftime)
- [x] Done -- [Parcel Myr](https://scryfall.com/search?q=!parcelmyr)
- [x] Done -- [Patchwork Gnomes](https://scryfall.com/search?q=!patchworkgnomes)
- [x] Done -- [Patriarch's Bidding](https://scryfall.com/search?q=!patriarchsbidding)
- [x] Done -- [Persist](https://scryfall.com/search?q=!persist)
- [x] Done -- [Phantasmal Dreadmaw](https://scryfall.com/search?q=!phantasmaldreadmaw)
- [x] Done -- [Piercing Rays](https://scryfall.com/search?q=!piercingrays)
- [x] Done -- [Piru, the Volatile](https://scryfall.com/search?q=!piruthevolatile)
- [x] Done -- [Power Depot](https://scryfall.com/search?q=!powerdepot)
- [x] Done -- [Priest of Fell Rites](https://scryfall.com/search?q=!priestoffellrites)
- [x] Done -- [Prismatic Ending](https://scryfall.com/search?q=!prismaticending)
- [x] Done -- [Profane Tutor](https://scryfall.com/search?q=!profanetutor)
- [x] Done -- [Prophetic Titan](https://scryfall.com/search?q=!prophetictitan)
- [x] Done -- [Quirion Ranger](https://scryfall.com/search?q=!quirionranger)
- [x] Done -- [Radiant Epicure](https://scryfall.com/search?q=!radiantepicure)
- [x] Done -- [Ragavan, Nimble Pilferer](https://scryfall.com/search?q=!ragavannimblepilferer)
- [x] Done -- [Rakdos Headliner](https://scryfall.com/search?q=!rakdosheadliner)
- [x] Done -- [Ravenous Squirrel](https://scryfall.com/search?q=!ravenoussquirrel)
- [x] Done -- [Raving Visionary](https://scryfall.com/search?q=!ravingvisionary)
- [x] Done -- [Razortide Bridge](https://scryfall.com/search?q=!razortidebridge)
- [x] Done -- [Recalibrate](https://scryfall.com/search?q=!recalibrate)
- [x] Done -- [Resurgent Belief](https://scryfall.com/search?q=!resurgentbelief)
- [x] Done -- [Revolutionist](https://scryfall.com/search?q=!revolutionist)
- [x] Done -- [Rift Sower](https://scryfall.com/search?q=!riftsower)
- [x] Done -- [Riptide Laboratory](https://scryfall.com/search?q=!riptidelaboratory)
- [x] Done -- [Rise and Shine](https://scryfall.com/search?q=!riseandshine)
- [x] Done -- [Rishadan Dockhand](https://scryfall.com/search?q=!rishadandockhand)
- [x] Done -- [Road // Ruin](https://scryfall.com/search?q=!road//ruin)
- [x] Done -- [Rustvale Bridge](https://scryfall.com/search?q=!rustvalebridge)
- [x] Done -- [Said // Done](https://scryfall.com/search?q=!said//done)
- [x] Done -- [Sanctifier en-Vec](https://scryfall.com/search?q=!sanctifierenvec)
- [x] Done -- [Sanctuary Raptor](https://scryfall.com/search?q=!sanctuaryraptor)
- [x] Done -- [Sanctum Prelate](https://scryfall.com/search?q=!sanctumprelate)
- [x] Done -- [Sanctum Weaver](https://scryfall.com/search?q=!sanctumweaver)
- [x] Done -- [Scalding Tarn](https://scryfall.com/search?q=!scaldingtarn)
- [x] Done -- [Scion of Draco](https://scryfall.com/search?q=!scionofdraco)
- [x] Done -- [Scour the Desert](https://scryfall.com/search?q=!scourthedesert)
- [x] Done -- [Scurry Oak](https://scryfall.com/search?q=!scurryoak)
- [x] Done -- [Scuttletide](https://scryfall.com/search?q=!scuttletide)
- [x] Done -- [Sea Drake](https://scryfall.com/search?q=!seadrake)
- [x] Done -- [Seal of Cleansing](https://scryfall.com/search?q=!sealofcleansing)
- [x] Done -- [Seal of Removal](https://scryfall.com/search?q=!sealofremoval)
- [x] Done -- [Search the Premises](https://scryfall.com/search?q=!searchthepremises)
- [x] Done -- [Serra's Emissary](https://scryfall.com/search?q=!serrasemissary)
- [x] Done -- [Shardless Agent](https://scryfall.com/search?q=!shardlessagent)
- [x] Done -- [Shattered Ego](https://scryfall.com/search?q=!shatteredego)
- [x] Done -- [Silverbluff Bridge](https://scryfall.com/search?q=!silverbluffbridge)
- [x] Done -- [Sinister Starfish](https://scryfall.com/search?q=!sinisterstarfish)
- [x] Done -- [Skirge Familiar](https://scryfall.com/search?q=!skirgefamiliar)
- [x] Done -- [Skophos Reaver](https://scryfall.com/search?q=!skophosreaver)
- [x] Done -- [Skyblade's Boon](https://scryfall.com/search?q=!skybladesboon)
- [x] Done -- [Slag Strider](https://scryfall.com/search?q=!slagstrider)
- [x] Done -- [Slagwoods Bridge](https://scryfall.com/search?q=!slagwoodsbridge)
- [x] Done -- [Smell Fear](https://scryfall.com/search?q=!smellfear)
- [x] Done -- [So Shiny](https://scryfall.com/search?q=!soshiny)
- [x] Done -- [Sojourner's Companion](https://scryfall.com/search?q=!sojournerscompanion)
- [x] Done -- [Sol Talisman](https://scryfall.com/search?q=!soltalisman)
- [x] Done -- [Solitary Confinement](https://scryfall.com/search?q=!solitaryconfinement)
- [x] Done -- [Solitude](https://scryfall.com/search?q=!solitude)
- [x] Done -- [Soul Snare](https://scryfall.com/search?q=!soulsnare)
- [x] Done -- [Soul of Migration](https://scryfall.com/search?q=!soulofmigration)
- [x] Done -- [Specimen Collector](https://scryfall.com/search?q=!specimencollector)
- [x] Done -- [Spreading Insurrection](https://scryfall.com/search?q=!spreadinginsurrection)
- [x] Done -- [Squirrel Mob](https://scryfall.com/search?q=!squirrelmob)
- [x] Done -- [Squirrel Sanctuary](https://scryfall.com/search?q=!squirrelsanctuary)
- [x] Done -- [Squirrel Sovereign](https://scryfall.com/search?q=!squirrelsovereign)
- [x] Done -- [Steel Dromedary](https://scryfall.com/search?q=!steeldromedary)
- [x] Done -- [Steelfin Whale](https://scryfall.com/search?q=!steelfinwhale)
- [x] Done -- [Step Through](https://scryfall.com/search?q=!stepthrough)
- [x] Done -- [Sterling Grove](https://scryfall.com/search?q=!sterlinggrove)
- [x] Done -- [Storm God's Oracle](https://scryfall.com/search?q=!stormgodsoracle)
- [x] Done -- [Strike It Rich](https://scryfall.com/search?q=!strikeitrich)
- [x] Done -- [Subtlety](https://scryfall.com/search?q=!subtlety)
- [x] Done -- [Sudden Edict](https://scryfall.com/search?q=!suddenedict)
- [x] Done -- [Suspend](https://scryfall.com/search?q=!suspend)
- [x] Done -- [Svyelun of Sea and Sky](https://scryfall.com/search?q=!svyelunofseaandsky)
- [x] Done -- [Sweep the Skies](https://scryfall.com/search?q=!sweeptheskies)
- [x] Done -- [Sword of Hearth and Home](https://scryfall.com/search?q=!swordofhearthandhome)
- [x] Done -- [Sylvan Anthem](https://scryfall.com/search?q=!sylvananthem)
- [x] Done -- [Sythis, Harvest's Hand](https://scryfall.com/search?q=!sythisharvestshand)
- [x] Done -- [Tanglepool Bridge](https://scryfall.com/search?q=!tanglepoolbridge)
- [x] Done -- [Tavern Scoundrel](https://scryfall.com/search?q=!tavernscoundrel)
- [x] Done -- [Terminal Agony](https://scryfall.com/search?q=!terminalagony)
- [x] Done -- [Terramorph](https://scryfall.com/search?q=!terramorph)
- [x] Done -- [Territorial Kavu](https://scryfall.com/search?q=!territorialkavu)
- [x] Done -- [The Underworld Cookbook](https://scryfall.com/search?q=!theunderworldcookbook)
- [x] Done -- [Thornglint Bridge](https://scryfall.com/search?q=!thornglintbridge)
- [x] Done -- [Thought Monitor](https://scryfall.com/search?q=!thoughtmonitor)
- [x] Done -- [Thraben Watcher](https://scryfall.com/search?q=!thrabenwatcher)
- [x] Done -- [Thrasta, Tempest's Roar](https://scryfall.com/search?q=!thrastatempestsroar)
- [x] Done -- [Tide Shaper](https://scryfall.com/search?q=!tideshaper)
- [x] Done -- [Timeless Dragon](https://scryfall.com/search?q=!timelessdragon)
- [x] Done -- [Timeless Witness](https://scryfall.com/search?q=!timelesswitness)
- [x] Done -- [Tireless Provisioner](https://scryfall.com/search?q=!tirelessprovisioner)
- [x] Done -- [Titania, Protector of Argoth](https://scryfall.com/search?q=!titaniaprotectorofargoth)
- [x] Done -- [Tizerus Charger](https://scryfall.com/search?q=!tizeruscharger)
- [x] Done -- [Tormod's Cryptkeeper](https://scryfall.com/search?q=!tormodscryptkeeper)
- [x] Done -- [Tourach's Canticle](https://scryfall.com/search?q=!tourachscanticle)
- [x] Done -- [Tourach, Dread Cantor](https://scryfall.com/search?q=!tourachdreadcantor)
- [x] Done -- [Tragic Fall](https://scryfall.com/search?q=!tragicfall)
- [x] Done -- [Unbounded Potential](https://scryfall.com/search?q=!unboundedpotential)
- [x] Done -- [Underworld Hermit](https://scryfall.com/search?q=!underworldhermit)
- [x] Done -- [Unholy Heat](https://scryfall.com/search?q=!unholyheat)
- [x] Done -- [Unmarked Grave](https://scryfall.com/search?q=!unmarkedgrave)
- [x] Done -- [Upheaval](https://scryfall.com/search?q=!upheaval)
- [x] Done -- [Urban Daggertooth](https://scryfall.com/search?q=!urbandaggertooth)
- [x] Done -- [Urza's Saga](https://scryfall.com/search?q=!urzassaga)
- [x] Done -- [Vectis Gloves](https://scryfall.com/search?q=!vectisgloves)
- [x] Done -- [Vedalken Infiltrator](https://scryfall.com/search?q=!vedalkeninfiltrator)
- [x] Done -- [Verdant Catacombs](https://scryfall.com/search?q=!verdantcatacombs)
- [x] Done -- [Verdant Command](https://scryfall.com/search?q=!verdantcommand)
- [x] Done -- [Vermin Gorger](https://scryfall.com/search?q=!vermingorger)
- [x] Done -- [Viashino Lashclaw](https://scryfall.com/search?q=!viashinolashclaw)
- [x] Done -- [Vile Entomber](https://scryfall.com/search?q=!vileentomber)
- [x] Done -- [Vindicate](https://scryfall.com/search?q=!vindicate)
- [x] Done -- [Void Mirror](https://scryfall.com/search?q=!voidmirror)
- [x] Done -- [Wavesifter](https://scryfall.com/search?q=!wavesifter)
- [x] Done -- [Wonder](https://scryfall.com/search?q=!wonder)
- [x] Done -- [World-Weary](https://scryfall.com/search?q=!worldweary)
- [x] Done -- [Wren's Run Hydra](https://scryfall.com/search?q=!wrensrunhydra)
- [x] Done -- [Yavimaya Elder](https://scryfall.com/search?q=!yavimayaelder)
- [x] Done -- [Yavimaya, Cradle of Growth](https://scryfall.com/search?q=!yavimayacradleofgrowth)
- [x] Done -- [Young Necromancer](https://scryfall.com/search?q=!youngnecromancer)
- [x] Done -- [Yusri, Fortune's Flame](https://scryfall.com/search?q=!yusrifortunesflame)
- [x] Done -- [Zabaz, the Glimmerwasp](https://scryfall.com/search?q=!zabaztheglimmerwasp)
- [x] Done -- [Zuran Orb](https://scryfall.com/search?q=!zuranorb)
</details>

**Comment by theelk801** [comment]
All currently previewed cards are implemented

**Comment by Fubs** [comment]
submitted a pull request for thrasta.

**Comment by Fubs** [comment]
ill start working on grist and zabaz

**Comment by jmharmon** [comment]
PR made for Altar of the Goyf, Blazing Rootwalla, Clattering Augur, and Damn.

**Comment by theelk801** [comment]
@Fubs hey, are you still working on those cards?

**Comment by Fubs** [comment]
> @Fubs hey, are you still working on those cards?

Been busy recently so haven't made much progress on them. Someone else should probably do them so set can be released

**Comment by theelk801** [comment]
Alright then, I'm just gonna mark them as not in progress for now.

**Comment by theelk801** [comment]
Grist is gonna require a large refactor as it changes its card type outside the battlefield which hasn't been done before. I'll probably do that after the other cards are done unless someone else wants to.

**Comment by alecvn** [comment]
Hi everyone.  Firstly, thanks for your work on Xmage, I wish I could contribute, but I'd need to get up to speed with Java first.

A request regarding MH2, and I totally understand if it's not possible:

It seems there are only two cards outstanding, at least one of which requires some larger refactoring, which may already be under review.  Is it not possible to release MH2 without those two cards so people can draft/play sealed while MH2 is still "hot"?
