### ISSUE TITLE
AFR - Adventures in the Forgotten Realms Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7808]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [+2 Mace](https://scryfall.com/search?q=!+2mace)
- [x] Done -- [Aberrant Mind Sorcerer](https://scryfall.com/search?q=!aberrantmindsorcerer)
- [x] Done -- [Acererak the Archlich](https://scryfall.com/search?q=!acererakthearchlich)
- [x] Done -- [Adult Gold Dragon](https://scryfall.com/search?q=!adultgolddragon)
- [x] Done -- [Air-Cult Elemental](https://scryfall.com/search?q=!aircultelemental)
- [x] Done -- [Arborea Pegasus](https://scryfall.com/search?q=!arboreapegasus)
- [x] Done -- [Arcane Investigator](https://scryfall.com/search?q=!arcaneinvestigator)
- [x] Done -- [Armory Veteran](https://scryfall.com/search?q=!armoryveteran)
- [x] Done -- [Asmodeus the Archfiend](https://scryfall.com/search?q=!asmodeusthearchfiend)
- [x] Done -- [Bag of Holding](https://scryfall.com/search?q=!bagofholding)
- [x] Done -- [Baleful Beholder](https://scryfall.com/search?q=!balefulbeholder)
- [x] Done -- [Bar the Gate](https://scryfall.com/search?q=!barthegate)
- [x] Done -- [Barbarian Class](https://scryfall.com/search?q=!barbarianclass)
- [x] Done -- [Bard Class](https://scryfall.com/search?q=!bardclass)
- [x] Done -- [Barrowin of Clan Undurr](https://scryfall.com/search?q=!barrowinofclanundurr)
- [x] Done -- [Battle Cry Goblin](https://scryfall.com/search?q=!battlecrygoblin)
- [x] Done -- [Black Dragon](https://scryfall.com/search?q=!blackdragon)
- [x] Done -- [Blink Dog](https://scryfall.com/search?q=!blinkdog)
- [x] Done -- [Blue Dragon](https://scryfall.com/search?q=!bluedragon)
- [x] Done -- [Boots of Speed](https://scryfall.com/search?q=!bootsofspeed)
- [x] Done -- [Brazen Dwarf](https://scryfall.com/search?q=!brazendwarf)
- [x] Done -- [Bruenor Battlehammer](https://scryfall.com/search?q=!bruenorbattlehammer)
- [x] Done -- [Bulette](https://scryfall.com/search?q=!bulette)
- [x] Done -- [Bull's Strength](https://scryfall.com/search?q=!bullsstrength)
- [x] Done -- [Burning Hands](https://scryfall.com/search?q=!burninghands)
- [x] Done -- [Cave of the Frost Dragon](https://scryfall.com/search?q=!caveofthefrostdragon)
- [x] Done -- [Celestial Unicorn](https://scryfall.com/search?q=!celestialunicorn)
- [x] Done -- [Chaos Channeler](https://scryfall.com/search?q=!chaoschanneler)
- [x] Done -- [Charmed Sleep](https://scryfall.com/search?q=!charmedsleep)
- [x] Done -- [Check for Traps](https://scryfall.com/search?q=!checkfortraps)
- [x] Done -- [Choose Your Weapon](https://scryfall.com/search?q=!chooseyourweapon)
- [x] Done -- [Circle of Dreams Druid](https://scryfall.com/search?q=!circleofdreamsdruid)
- [x] Done -- [Circle of the Moon Druid](https://scryfall.com/search?q=!circleofthemoondruid)
- [x] Done -- [Clattering Skeletons](https://scryfall.com/search?q=!clatteringskeletons)
- [x] Done -- [Cleric Class](https://scryfall.com/search?q=!clericclass)
- [x] Done -- [Clever Conjurer](https://scryfall.com/search?q=!cleverconjurer)
- [x] Done -- [Cloister Gargoyle](https://scryfall.com/search?q=!cloistergargoyle)
- [x] Done -- [Compelled Duel](https://scryfall.com/search?q=!compelledduel)
- [x] Done -- [Contact Other Plane](https://scryfall.com/search?q=!contactotherplane)
- [x] Done -- [Critical Hit](https://scryfall.com/search?q=!criticalhit)
- [x] Done -- [Dancing Sword](https://scryfall.com/search?q=!dancingsword)
- [x] Done -- [Dawnbringer Cleric](https://scryfall.com/search?q=!dawnbringercleric)
- [x] Done -- [Deadly Dispute](https://scryfall.com/search?q=!deadlydispute)
- [x] Done -- [Death-Priest of Myrkul](https://scryfall.com/search?q=!deathpriestofmyrkul)
- [x] Done -- [Delina, Wild Mage](https://scryfall.com/search?q=!delinawildmage)
- [x] Done -- [Delver's Torch](https://scryfall.com/search?q=!delverstorch)
- [x] Done -- [Demilich](https://scryfall.com/search?q=!demilich)
- [x] Done -- [Demogorgon's Clutches](https://scryfall.com/search?q=!demogorgonsclutches)
- [x] Done -- [Den of the Bugbear](https://scryfall.com/search?q=!denofthebugbear)
- [x] Done -- [Devoted Paladin](https://scryfall.com/search?q=!devotedpaladin)
- [x] Done -- [Devour Intellect](https://scryfall.com/search?q=!devourintellect)
- [x] Done -- [Dire Wolf Prowler](https://scryfall.com/search?q=!direwolfprowler)
- [x] Done -- [Displacer Beast](https://scryfall.com/search?q=!displacerbeast)
- [x] Done -- [Divine Smite](https://scryfall.com/search?q=!divinesmite)
- [x] Done -- [Djinni Windseer](https://scryfall.com/search?q=!djinniwindseer)
- [x] Done -- [Dragon Turtle](https://scryfall.com/search?q=!dragonturtle)
- [x] Done -- [Dragon's Disciple](https://scryfall.com/search?q=!dragonsdisciple)
- [x] Done -- [Dragon's Fire](https://scryfall.com/search?q=!dragonsfire)
- [x] Done -- [Drider](https://scryfall.com/search?q=!drider)
- [x] Done -- [Drizzt Do'Urden](https://scryfall.com/search?q=!drizztdourden)
- [x] Done -- [Druid Class](https://scryfall.com/search?q=!druidclass)
- [x] Done -- [Dueling Rapier](https://scryfall.com/search?q=!duelingrapier)
- [x] Done -- [Dungeon Crawler](https://scryfall.com/search?q=!dungeoncrawler)
- [x] Done -- [Dungeon Descent](https://scryfall.com/search?q=!dungeondescent)
- [x] Done -- [Dungeon Map](https://scryfall.com/search?q=!dungeonmap)
- [x] Done -- [Dwarfhold Champion](https://scryfall.com/search?q=!dwarfholdchampion)
- [x] Done -- [Earth-Cult Elemental](https://scryfall.com/search?q=!earthcultelemental)
- [x] Done -- [Ebondeath, Dracolich](https://scryfall.com/search?q=!ebondeathdracolich)
- [x] Done -- [Eccentric Apprentice](https://scryfall.com/search?q=!eccentricapprentice)
- [x] Done -- [Ellywick Tumblestrum](https://scryfall.com/search?q=!ellywicktumblestrum)
- [x] Done -- [Elturgard Ranger](https://scryfall.com/search?q=!elturgardranger)
- [x] Done -- [Evolving Wilds](https://scryfall.com/search?q=!evolvingwilds)
- [x] Done -- [Eye of Vecna](https://scryfall.com/search?q=!eyeofvecna)
- [x] Done -- [Eyes of the Beholder](https://scryfall.com/search?q=!eyesofthebeholder)
- [x] Done -- [Farideh's Fireball](https://scryfall.com/search?q=!faridehsfireball)
- [x] Done -- [Farideh, Devil's Chosen](https://scryfall.com/search?q=!faridehdevilschosen)
- [x] Done -- [Fates' Reversal](https://scryfall.com/search?q=!fatesreversal)
- [x] Done -- [Feign Death](https://scryfall.com/search?q=!feigndeath)
- [x] Done -- [Feywild Trickster](https://scryfall.com/search?q=!feywildtrickster)
- [x] Done -- [Fifty Feet of Rope](https://scryfall.com/search?q=!fiftyfeetofrope)
- [x] Done -- [Fighter Class](https://scryfall.com/search?q=!fighterclass)
- [x] Done -- [Find the Path](https://scryfall.com/search?q=!findthepath)
- [x] Done -- [Flameskull](https://scryfall.com/search?q=!flameskull)
- [x] Done -- [Flumph](https://scryfall.com/search?q=!flumph)
- [x] Done -- [Fly](https://scryfall.com/search?q=!fly)
- [x] Done -- [Forsworn Paladin](https://scryfall.com/search?q=!forswornpaladin)
- [x] Done -- [Froghemoth](https://scryfall.com/search?q=!froghemoth)
- [x] Done -- [Gelatinous Cube](https://scryfall.com/search?q=!gelatinouscube)
- [x] Done -- [Gloom Stalker](https://scryfall.com/search?q=!gloomstalker)
- [x] Done -- [Gnoll Hunter](https://scryfall.com/search?q=!gnollhunter)
- [x] Done -- [Goblin Javelineer](https://scryfall.com/search?q=!goblinjavelineer)
- [x] Done -- [Goblin Morningstar](https://scryfall.com/search?q=!goblinmorningstar)
- [x] Done -- [Grand Master of Flowers](https://scryfall.com/search?q=!grandmasterofflowers)
- [x] Done -- [Grazilaxx, Illithid Scholar](https://scryfall.com/search?q=!grazilaxxillithidscholar)
- [x] Done -- [Greataxe](https://scryfall.com/search?q=!greataxe)
- [x] Done -- [Green Dragon](https://scryfall.com/search?q=!greendragon)
- [x] Done -- [Gretchen Titchwillow](https://scryfall.com/search?q=!gretchentitchwillow)
- [x] Done -- [Grim Bounty](https://scryfall.com/search?q=!grimbounty)
- [x] Done -- [Grim Wanderer](https://scryfall.com/search?q=!grimwanderer)
- [x] Done -- [Guardian of Faith](https://scryfall.com/search?q=!guardianoffaith)
- [x] Done -- [Guild Thief](https://scryfall.com/search?q=!guildthief)
- [x] Done -- [Half-Elf Monk](https://scryfall.com/search?q=!halfelfmonk)
- [x] Done -- [Hall of Storm Giants](https://scryfall.com/search?q=!hallofstormgiants)
- [x] Done -- [Hama Pashar, Ruin Seeker](https://scryfall.com/search?q=!hamapasharruinseeker)
- [x] Done -- [Hand of Vecna](https://scryfall.com/search?q=!handofvecna)
- [x] Done -- [Herald of Hadar](https://scryfall.com/search?q=!heraldofhadar)
- [x] Done -- [Hill Giant Herdgorger](https://scryfall.com/search?q=!hillgiantherdgorger)
- [x] Done -- [Hired Hexblade](https://scryfall.com/search?q=!hiredhexblade)
- [x] Done -- [Hive of the Eye Tyrant](https://scryfall.com/search?q=!hiveoftheeyetyrant)
- [x] Done -- [Hoard Robber](https://scryfall.com/search?q=!hoardrobber)
- [x] Done -- [Hoarding Ogre](https://scryfall.com/search?q=!hoardingogre)
- [x] Done -- [Hobgoblin Bandit Lord](https://scryfall.com/search?q=!hobgoblinbanditlord)
- [x] Done -- [Hobgoblin Captain](https://scryfall.com/search?q=!hobgoblincaptain)
- [x] Done -- [Hulking Bugbear](https://scryfall.com/search?q=!hulkingbugbear)
- [x] Done -- [Hunter's Mark](https://scryfall.com/search?q=!huntersmark)
- [x] Done -- [Icingdeath, Frost Tyrant](https://scryfall.com/search?q=!icingdeathfrosttyrant)
- [x] Done -- [Improvised Weaponry](https://scryfall.com/search?q=!improvisedweaponry)
- [x] Done -- [Inferno of the Star Mounts](https://scryfall.com/search?q=!infernoofthestarmounts)
- [x] Done -- [Ingenious Smith](https://scryfall.com/search?q=!ingenioussmith)
- [x] Done -- [Inspiring Bard](https://scryfall.com/search?q=!inspiringbard)
- [x] Done -- [Instrument of the Bards](https://scryfall.com/search?q=!instrumentofthebards)
- [x] Done -- [Intrepid Outlander](https://scryfall.com/search?q=!intrepidoutlander)
- [x] Done -- [Iron Golem](https://scryfall.com/search?q=!irongolem)
- [x] Done -- [Iymrith, Desert Doom](https://scryfall.com/search?q=!iymrithdesertdoom)
- [x] Done -- [Jaded Sell-Sword](https://scryfall.com/search?q=!jadedsellsword)
- [x] Done -- [Kalain, Reclusive Painter](https://scryfall.com/search?q=!kalainreclusivepainter)
- [x] Done -- [Keen-Eared Sentry](https://scryfall.com/search?q=!keenearedsentry)
- [x] Done -- [Kick in the Door](https://scryfall.com/search?q=!kickinthedoor)
- [x] Done -- [Krydle of Baldur's Gate](https://scryfall.com/search?q=!krydleofbaldursgate)
- [x] Done -- [Lair of the Hydra](https://scryfall.com/search?q=!lairofthehydra)
- [x] Done -- [Leather Armor](https://scryfall.com/search?q=!leatherarmor)
- [x] Done -- [Lightfoot Rogue](https://scryfall.com/search?q=!lightfootrogue)
- [x] Done -- [Loathsome Troll](https://scryfall.com/search?q=!loathsometroll)
- [x] Done -- [Lolth, Spider Queen](https://scryfall.com/search?q=!lolthspiderqueen)
- [x] Done -- [Long Rest](https://scryfall.com/search?q=!longrest)
- [x] Done -- [Loyal Warhound](https://scryfall.com/search?q=!loyalwarhound)
- [x] Done -- [Lurking Roper](https://scryfall.com/search?q=!lurkingroper)
- [x] Done -- [Magic Missile](https://scryfall.com/search?q=!magicmissile)
- [x] Done -- [Manticore](https://scryfall.com/search?q=!manticore)
- [x] Done -- [Meteor Swarm](https://scryfall.com/search?q=!meteorswarm)
- [x] Done -- [Mimic](https://scryfall.com/search?q=!mimic)
- [x] Done -- [Mind Flayer](https://scryfall.com/search?q=!mindflayer)
- [x] Done -- [Minimus Containment](https://scryfall.com/search?q=!minimuscontainment)
- [x] Done -- [Minion of the Mighty](https://scryfall.com/search?q=!minionofthemighty)
- [x] Done -- [Minsc, Beloved Ranger](https://scryfall.com/search?q=!minscbelovedranger)
- [x] Done -- [Monk Class](https://scryfall.com/search?q=!monkclass)
- [x] Done -- [Monk of the Open Hand](https://scryfall.com/search?q=!monkoftheopenhand)
- [x] Done -- [Moon-Blessed Cleric](https://scryfall.com/search?q=!moonblessedcleric)
- [x] Done -- [Mordenkainen's Polymorph](https://scryfall.com/search?q=!mordenkainenspolymorph)
- [x] Done -- [Mordenkainen](https://scryfall.com/search?q=!mordenkainen)
- [x] Done -- [Nadaar, Selfless Paladin](https://scryfall.com/search?q=!nadaarselflesspaladin)
- [x] Done -- [Neverwinter Dryad](https://scryfall.com/search?q=!neverwinterdryad)
- [x] Done -- [Ochre Jelly](https://scryfall.com/search?q=!ochrejelly)
- [x] Done -- [Old Gnawbone](https://scryfall.com/search?q=!oldgnawbone)
- [x] Done -- [Orb of Dragonkind](https://scryfall.com/search?q=!orbofdragonkind)
- [x] Done -- [Orcus, Prince of Undeath](https://scryfall.com/search?q=!orcusprinceofundeath)
- [x] Done -- [Oswald Fiddlebender](https://scryfall.com/search?q=!oswaldfiddlebender)
- [x] Done -- [Owlbear](https://scryfall.com/search?q=!owlbear)
- [x] Done -- [Paladin Class](https://scryfall.com/search?q=!paladinclass)
- [x] Done -- [Paladin's Shield](https://scryfall.com/search?q=!paladinsshield)
- [x] Done -- [Pixie Guide](https://scryfall.com/search?q=!pixieguide)
- [x] Done -- [Planar Ally](https://scryfall.com/search?q=!planarally)
- [x] Done -- [Plate Armor](https://scryfall.com/search?q=!platearmor)
- [x] Done -- [Plummet](https://scryfall.com/search?q=!plummet)
- [x] Done -- [Plundering Barbarian](https://scryfall.com/search?q=!plunderingbarbarian)
- [x] Done -- [Portable Hole](https://scryfall.com/search?q=!portablehole)
- [x] Done -- [Potion of Healing](https://scryfall.com/search?q=!potionofhealing)
- [x] Done -- [Power Word Kill](https://scryfall.com/search?q=!powerwordkill)
- [x] Done -- [Power of Persuasion](https://scryfall.com/search?q=!powerofpersuasion)
- [x] Done -- [Precipitous Drop](https://scryfall.com/search?q=!precipitousdrop)
- [x] Done -- [Price of Loyalty](https://scryfall.com/search?q=!priceofloyalty)
- [x] Done -- [Priest of Ancient Lore](https://scryfall.com/search?q=!priestofancientlore)
- [x] Done -- [Prosperous Innkeeper](https://scryfall.com/search?q=!prosperousinnkeeper)
- [x] Done -- [Purple Worm](https://scryfall.com/search?q=!purpleworm)
- [x] Done -- [Rally Maneuver](https://scryfall.com/search?q=!rallymaneuver)
- [x] Done -- [Ranger Class](https://scryfall.com/search?q=!rangerclass)
- [x] Done -- [Ranger's Hawk](https://scryfall.com/search?q=!rangershawk)
- [x] Done -- [Ranger's Longbow](https://scryfall.com/search?q=!rangerslongbow)
- [x] Done -- [Ray of Enfeeblement](https://scryfall.com/search?q=!rayofenfeeblement)
- [x] Done -- [Ray of Frost](https://scryfall.com/search?q=!rayoffrost)
- [x] Done -- [Reaper's Talisman](https://scryfall.com/search?q=!reaperstalisman)
- [x] Done -- [Red Dragon](https://scryfall.com/search?q=!reddragon)
- [x] Done -- [Rimeshield Frost Giant](https://scryfall.com/search?q=!rimeshieldfrostgiant)
- [x] Done -- [Rogue Class](https://scryfall.com/search?q=!rogueclass)
- [x] Done -- [Rust Monster](https://scryfall.com/search?q=!rustmonster)
- [x] Done -- [Scaled Herbalist](https://scryfall.com/search?q=!scaledherbalist)
- [x] Done -- [Scion of Stygia](https://scryfall.com/search?q=!scionofstygia)
- [x] Done -- [Secret Door](https://scryfall.com/search?q=!secretdoor)
- [x] Done -- [Sepulcher Ghoul](https://scryfall.com/search?q=!sepulcherghoul)
- [x] Done -- [Shambling Ghast](https://scryfall.com/search?q=!shamblingghast)
- [x] Done -- [Shessra, Death's Whisper](https://scryfall.com/search?q=!shessradeathswhisper)
- [x] Done -- [Shocking Grasp](https://scryfall.com/search?q=!shockinggrasp)
- [x] Done -- [Shortcut Seeker](https://scryfall.com/search?q=!shortcutseeker)
- [x] Done -- [Silver Raven](https://scryfall.com/search?q=!silverraven)
- [x] Done -- [Skeletal Swarming](https://scryfall.com/search?q=!skeletalswarming)
- [x] Done -- [Skullport Merchant](https://scryfall.com/search?q=!skullportmerchant)
- [x] Done -- [Sorcerer Class](https://scryfall.com/search?q=!sorcererclass)
- [x] Done -- [Soulknife Spy](https://scryfall.com/search?q=!soulknifespy)
- [x] Done -- [Spare Dagger](https://scryfall.com/search?q=!sparedagger)
- [x] Done -- [Sphere of Annihilation](https://scryfall.com/search?q=!sphereofannihilation)
- [x] Done -- [Spiked Pit Trap](https://scryfall.com/search?q=!spikedpittrap)
- [x] Done -- [Split the Party](https://scryfall.com/search?q=!splittheparty)
- [x] Done -- [Spoils of the Hunt](https://scryfall.com/search?q=!spoilsofthehunt)
- [x] Done -- [Steadfast Paladin](https://scryfall.com/search?q=!steadfastpaladin)
- [x] Done -- [Sudden Insight](https://scryfall.com/search?q=!suddeninsight)
- [x] Done -- [Swarming Goblins](https://scryfall.com/search?q=!swarminggoblins)
- [x] Done -- [Sylvan Shepherd](https://scryfall.com/search?q=!sylvanshepherd)
- [x] Done -- [Targ Nar, Demon-Fang Gnoll](https://scryfall.com/search?q=!targnardemonfanggnoll)
- [x] Done -- [Tasha's Hideous Laughter](https://scryfall.com/search?q=!tashashideouslaughter)
- [x] Done -- [Teleportation Circle](https://scryfall.com/search?q=!teleportationcircle)
- [x] Done -- [Temple of the Dragon Queen](https://scryfall.com/search?q=!templeofthedragonqueen)
- [x] Done -- [The Blackstaff of Waterdeep](https://scryfall.com/search?q=!theblackstaffofwaterdeep)
- [x] Done -- [The Book of Exalted Deeds](https://scryfall.com/search?q=!thebookofexalteddeeds)
- [x] Done -- [The Book of Vile Darkness](https://scryfall.com/search?q=!thebookofviledarkness)
- [x] Done -- [The Deck of Many Things](https://scryfall.com/search?q=!thedeckofmanythings)
- [x] Done -- [The Tarrasque](https://scryfall.com/search?q=!thetarrasque)
- [x] Done -- [Thieves' Tools](https://scryfall.com/search?q=!thievestools)
- [x] Done -- [Tiamat](https://scryfall.com/search?q=!tiamat)
- [x] Done -- [Tiger-Tribe Hunter](https://scryfall.com/search?q=!tigertribehunter)
- [x] Done -- [Treasure Chest](https://scryfall.com/search?q=!treasurechest)
- [x] Done -- [Treasure Vault](https://scryfall.com/search?q=!treasurevault)
- [x] Done -- [Trelasarra, Moon Dancer](https://scryfall.com/search?q=!trelasarramoondancer)
- [x] Done -- [Trickster's Talisman](https://scryfall.com/search?q=!tricksterstalisman)
- [x] Done -- [Triumphant Adventurer](https://scryfall.com/search?q=!triumphantadventurer)
- [x] Done -- [True Polymorph](https://scryfall.com/search?q=!truepolymorph)
- [x] Done -- [Underdark Basilisk](https://scryfall.com/search?q=!underdarkbasilisk)
- [x] Done -- [Unexpected Windfall](https://scryfall.com/search?q=!unexpectedwindfall)
- [x] Done -- [Valor Singer](https://scryfall.com/search?q=!valorsinger)
- [x] Done -- [Vampire Spawn](https://scryfall.com/search?q=!vampirespawn)
- [x] Done -- [Varis, Silverymoon Ranger](https://scryfall.com/search?q=!varissilverymoonranger)
- [x] Done -- [Veteran Dungeoneer](https://scryfall.com/search?q=!veterandungeoneer)
- [x] Done -- [Volo, Guide to Monsters](https://scryfall.com/search?q=!vologuidetomonsters)
- [x] Done -- [Vorpal Sword](https://scryfall.com/search?q=!vorpalsword)
- [x] Done -- [Wandering Troubadour](https://scryfall.com/search?q=!wanderingtroubadour)
- [x] Done -- [Warlock Class](https://scryfall.com/search?q=!warlockclass)
- [x] Done -- [Werewolf Pack Leader](https://scryfall.com/search?q=!werewolfpackleader)
- [x] Done -- [Westgate Regent](https://scryfall.com/search?q=!westgateregent)
- [x] Done -- [White Dragon](https://scryfall.com/search?q=!whitedragon)
- [x] Done -- [Wight](https://scryfall.com/search?q=!wight)
- [x] Done -- [Wild Shape](https://scryfall.com/search?q=!wildshape)
- [x] Done -- [Wish](https://scryfall.com/search?q=!wish)
- [x] Done -- [Wizard Class](https://scryfall.com/search?q=!wizardclass)
- [x] Done -- [Wizard's Spellbook](https://scryfall.com/search?q=!wizardsspellbook)
- [x] Done -- [Xanathar, Guild Kingpin](https://scryfall.com/search?q=!xanatharguildkingpin)
- [x] Done -- [Xorn](https://scryfall.com/search?q=!xorn)
- [x] Done -- [You Come to a River](https://scryfall.com/search?q=!youcometoariver)
- [x] Done -- [You Come to the Gnoll Camp](https://scryfall.com/search?q=!youcometothegnollcamp)
- [x] Done -- [You Find Some Prisoners](https://scryfall.com/search?q=!youfindsomeprisoners)
- [x] Done -- [You Find a Cursed Idol](https://scryfall.com/search?q=!youfindacursedidol)
- [x] Done -- [You Find the Villains' Lair](https://scryfall.com/search?q=!youfindthevillainslair)
- [x] Done -- [You Happen On a Glade](https://scryfall.com/search?q=!youhappenonaglade)
- [x] Done -- [You Hear Something on Watch](https://scryfall.com/search?q=!youhearsomethingonwatch)
- [x] Done -- [You Meet in a Tavern](https://scryfall.com/search?q=!youmeetinatavern)
- [x] Done -- [You See a Guard Approach](https://scryfall.com/search?q=!youseeaguardapproach)
- [x] Done -- [You See a Pair of Goblins](https://scryfall.com/search?q=!youseeapairofgoblins)
- [x] Done -- [You're Ambushed on the Road](https://scryfall.com/search?q=!youreambushedontheroad)
- [x] Done -- [Yuan-Ti Fang-Blade](https://scryfall.com/search?q=!yuantifangblade)
- [x] Done -- [Yuan-Ti Malison](https://scryfall.com/search?q=!yuantimalison)
- [x] Done -- [Zalto, Fire Giant Duke](https://scryfall.com/search?q=!zaltofiregiantduke)
- [x] Done -- [Zariel, Archduke of Avernus](https://scryfall.com/search?q=!zarielarchdukeofavernus)
- [x] Done -- [Zombie Ogre](https://scryfall.com/search?q=!zombieogre)
</details>

**Comment by theelk801** [comment]
All currently previewed cards are implemented

**Comment by theelk801** [comment]
Additional tasks:

- [ ] Implement [dungeon mechanic](https://magic.wizards.com/en/articles/archive/feature/adventures-forgotten-realms-mechanics-2021-06-24)

**Comment by JayDi85** [comment]
@theelk801 is it need GUI or graphic improves?

**Comment by theelk801** [comment]
Yeah, probably. I'm not exactly sure how yet but once I get it functioning we'll need to make the GUI aspect of it make sense.

**Comment by weirddan455** [comment]
@theelk801 What's the issue with the flavor words on triggered abilities?  I see you've implemented [[Dawnbringer Cleric]] already and its ETB trigger seems to work fine with the flavor word.  Can you give an example of a card that's having problems?

**Comment by theelk801** [comment]
they work fine when you add them to modes or activated abilities, the problem is cards where you have to add them to the beginning of a triggered ability like on [[Manticore]]

**Comment by Raphael-Schulz** [comment]
Hi everyone, first of all thank you for your great work on Xmage 🎉 
I have been happily using it for a long time now so I would like to start contributing to the project. 
For starting I thought I might help implementing some of the more simple cards from the new set.

If that is fine, I would start with [Meteor Swarm](https://scryfall.com/card/afr/155/meteor-swarm) 😄 
(It looks like I can not toggle the `In progress` checkbox)

**Comment by jeffwadsworth** [comment]
Xanathar, Guild Kingpin may run into the same issue we are having with Sen Triplets.  I will run some tests and check it out.

**Comment by jeffwadsworth** [comment]
@theelk801 Hey, I can take Xanathar, Guild Kingpin if you haven't done it yet.

**Comment by theelk801** [comment]
yeah, go for it

**Comment by Raphael-Schulz** [comment]
Hey @jeffwadsworth, I was also trying on implementing Xanathar, Guild Kingpin yesterday 😃 
Forgot to write a comment here. I will create a PR for it soon but maybe it is not the best solution anyways.

In any case I recognized that there are some weird interactions with other existing cards that let you play cards from the top of your own library like [Elsha of the Infinite](https://edhrec.com/commanders/elsha-of-the-infinite) (also affects cards beeing played from the top of opponents libraries).

I am very curious to see how you implemented it :)

**Comment by jeffwadsworth** [comment]
@Raphael-Schulz Fortunately, I didn’t start on it yet, so it is all yours.
