### ISSUE TITLE
AFC - Forgotten Realms Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7978]
This checklist is here to help manage the implementation of Forgotten Realms Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Share the Spoils](https://scryfall.com/search?q=!sharethespoils)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"sharethespoils"&unique=cards)
# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abundant Growth](https://scryfall.com/search?q=!abundantgrowth)
- [x] Done -- [Acidic Slime](https://scryfall.com/search?q=!acidicslime)
- [x] Done -- [Angel of Finality](https://scryfall.com/search?q=!angeloffinality)
- [x] Done -- [Angelic Gift](https://scryfall.com/search?q=!angelicgift)
- [x] Done -- [Anger](https://scryfall.com/search?q=!anger)
- [x] Done -- [Apex of Power](https://scryfall.com/search?q=!apexofpower)
- [x] Done -- [Arcane Endeavor](https://scryfall.com/search?q=!arcaneendeavor)
- [x] Done -- [Arcane Sanctum](https://scryfall.com/search?q=!arcanesanctum)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Argentum Armor](https://scryfall.com/search?q=!argentumarmor)
- [x] Done -- [Ashen Rider](https://scryfall.com/search?q=!ashenrider)
- [x] Done -- [Atarka, World Render](https://scryfall.com/search?q=!atarkaworldrender)
- [x] Done -- [Azorius Chancery](https://scryfall.com/search?q=!azoriuschancery)
- [x] Done -- [Bag of Devouring](https://scryfall.com/search?q=!bagofdevouring)
- [x] Done -- [Bag of Tricks](https://scryfall.com/search?q=!bagoftricks)
- [x] Done -- [Baleful Strix](https://scryfall.com/search?q=!balefulstrix)
- [x] Done -- [Bant Charm](https://scryfall.com/search?q=!bantcharm)
- [x] Done -- [Bant Panorama](https://scryfall.com/search?q=!bantpanorama)
- [x] Done -- [Basilisk Collar](https://scryfall.com/search?q=!basiliskcollar)
- [x] Done -- [Beast Within](https://scryfall.com/search?q=!beastwithin)
- [x] Done -- [Bedevil](https://scryfall.com/search?q=!bedevil)
- [x] Done -- [Behemoth Sledge](https://scryfall.com/search?q=!behemothsledge)
- [x] Done -- [Belt of Giant Strength](https://scryfall.com/search?q=!beltofgiantstrength)
- [x] Done -- [Berserker's Frenzy](https://scryfall.com/search?q=!berserkersfrenzy)
- [x] Done -- [Bituminous Blast](https://scryfall.com/search?q=!bituminousblast)
- [x] Done -- [Bogardan Hellkite](https://scryfall.com/search?q=!bogardanhellkite)
- [x] Done -- [Bojuka Bog](https://scryfall.com/search?q=!bojukabog)
- [x] Done -- [Brainstorm](https://scryfall.com/search?q=!brainstorm)
- [x] Done -- [Bucknard's Everfull Purse](https://scryfall.com/search?q=!bucknardseverfullpurse)
- [x] Done -- [Burnished Hart](https://scryfall.com/search?q=!burnishedhart)
- [x] Done -- [Canopy Vista](https://scryfall.com/search?q=!canopyvista)
- [x] Done -- [Cataclysmic Gearhulk](https://scryfall.com/search?q=!cataclysmicgearhulk)
- [x] Done -- [Catti-brie of Mithral Hall](https://scryfall.com/search?q=!cattibrieofmithralhall)
- [x] Done -- [Chain Reaction](https://scryfall.com/search?q=!chainreaction)
- [x] Done -- [Chameleon Colossus](https://scryfall.com/search?q=!chameleoncolossus)
- [x] Done -- [Champion of Wits](https://scryfall.com/search?q=!championofwits)
- [x] Done -- [Chaos Dragon](https://scryfall.com/search?q=!chaosdragon)
- [x] Done -- [Chaos Wand](https://scryfall.com/search?q=!chaoswand)
- [x] Done -- [Chaos Warp](https://scryfall.com/search?q=!chaoswarp)
- [x] Done -- [Chittering Witch](https://scryfall.com/search?q=!chitteringwitch)
- [x] Done -- [Choked Estuary](https://scryfall.com/search?q=!chokedestuary)
- [x] Done -- [Cinder Glade](https://scryfall.com/search?q=!cinderglade)
- [x] Done -- [Clay Golem](https://scryfall.com/search?q=!claygolem)
- [x] Done -- [Cloudblazer](https://scryfall.com/search?q=!cloudblazer)
- [x] Done -- [Cold-Eyed Selkie](https://scryfall.com/search?q=!coldeyedselkie)
- [x] Done -- [Colossal Majesty](https://scryfall.com/search?q=!colossalmajesty)
- [x] Done -- [Colossus Hammer](https://scryfall.com/search?q=!colossushammer)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=!commanderssphere)
- [x] Done -- [Commune with Lava](https://scryfall.com/search?q=!communewithlava)
- [x] Done -- [Component Pouch](https://scryfall.com/search?q=!componentpouch)
- [x] Done -- [Consuming Vapors](https://scryfall.com/search?q=!consumingvapors)
- [x] Done -- [Crucible of the Spirit Dragon](https://scryfall.com/search?q=!crucibleofthespiritdragon)
- [x] Done -- [Cultivate](https://scryfall.com/search?q=!cultivate)
- [x] Done -- [Curator of Mysteries](https://scryfall.com/search?q=!curatorofmysteries)
- [x] Done -- [Curse of Verbosity](https://scryfall.com/search?q=!curseofverbosity)
- [x] Done -- [Danse Macabre](https://scryfall.com/search?q=!dansemacabre)
- [x] Done -- [Dark-Dweller Oracle](https://scryfall.com/search?q=!darkdwelleroracle)
- [x] Done -- [Darkwater Catacombs](https://scryfall.com/search?q=!darkwatercatacombs)
- [x] Done -- [Dead Man's Chest](https://scryfall.com/search?q=!deadmanschest)
- [x] Done -- [Death Tyrant](https://scryfall.com/search?q=!deathtyrant)
- [x] Done -- [Decree of Savagery](https://scryfall.com/search?q=!decreeofsavagery)
- [x] Done -- [Demanding Dragon](https://scryfall.com/search?q=!demandingdragon)
- [x] Done -- [Desert](https://scryfall.com/search?q=!desert)
- [x] Done -- [Despark](https://scryfall.com/search?q=!despark)
- [x] Done -- [Dimir Aqueduct](https://scryfall.com/search?q=!dimiraqueduct)
- [x] Done -- [Dire Fleet Daredevil](https://scryfall.com/search?q=!direfleetdaredevil)
- [x] Done -- [Disrupt Decorum](https://scryfall.com/search?q=!disruptdecorum)
- [x] Done -- [Diviner's Portent](https://scryfall.com/search?q=!divinersportent)
- [x] Done -- [Doomed Necromancer](https://scryfall.com/search?q=!doomednecromancer)
- [x] Done -- [Dragon's Hoard](https://scryfall.com/search?q=!dragonshoard)
- [x] Done -- [Dragonborn Champion](https://scryfall.com/search?q=!dragonbornchampion)
- [x] Done -- [Dragonlord's Servant](https://scryfall.com/search?q=!dragonlordsservant)
- [x] Done -- [Dragonmaster Outcast](https://scryfall.com/search?q=!dragonmasteroutcast)
- [x] Done -- [Dragonspeaker Shaman](https://scryfall.com/search?q=!dragonspeakershaman)
- [x] Done -- [Dream Pillager](https://scryfall.com/search?q=!dreampillager)
- [x] Done -- [Druid of Purification](https://scryfall.com/search?q=!druidofpurification)
- [x] Done -- [Ebony Fly](https://scryfall.com/search?q=!ebonyfly)
- [x] Done -- [Eel Umbra](https://scryfall.com/search?q=!eelumbra)
- [x] Done -- [Esper Panorama](https://scryfall.com/search?q=!esperpanorama)
- [x] Done -- [Etali, Primal Storm](https://scryfall.com/search?q=!etaliprimalstorm)
- [x] Done -- [Eternal Dragon](https://scryfall.com/search?q=!eternaldragon)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Explore](https://scryfall.com/search?q=!explore)
- [x] Done -- [Explorer's Scope](https://scryfall.com/search?q=!explorersscope)
- [x] Done -- [Extract Brain](https://scryfall.com/search?q=!extractbrain)
- [x] Done -- [Fellwar Stone](https://scryfall.com/search?q=!fellwarstone)
- [x] Done -- [Fertile Ground](https://scryfall.com/search?q=!fertileground)
- [x] Done -- [Fevered Suspicion](https://scryfall.com/search?q=!feveredsuspicion)
- [x] Done -- [Fey Steed](https://scryfall.com/search?q=!feysteed)
- [x] Done -- [Fiend of the Shadows](https://scryfall.com/search?q=!fiendoftheshadows)
- [x] Done -- [Fiendlash](https://scryfall.com/search?q=!fiendlash)
- [x] Done -- [Fleecemane Lion](https://scryfall.com/search?q=!fleecemanelion)
- [x] Done -- [Flood Plain](https://scryfall.com/search?q=!floodplain)
- [x] Done -- [Forbidden Alchemy](https://scryfall.com/search?q=!forbiddenalchemy)
- [x] Done -- [Foreboding Ruins](https://scryfall.com/search?q=!forebodingruins)
- [x] Done -- [Fortified Village](https://scryfall.com/search?q=!fortifiedvillage)
- [x] Done -- [Galea, Kindler of Hope](https://scryfall.com/search?q=!galeakindlerofhope)
- [x] Done -- [Game Trail](https://scryfall.com/search?q=!gametrail)
- [x] Done -- [Garruk's Uprising](https://scryfall.com/search?q=!garruksuprising)
- [x] Done -- [Geier Reach Sanitarium](https://scryfall.com/search?q=!geierreachsanitarium)
- [x] Done -- [Gonti, Lord of Luxury](https://scryfall.com/search?q=!gontilordofluxury)
- [x] Done -- [Grasslands](https://scryfall.com/search?q=!grasslands)
- [x] Done -- [Gratuitous Violence](https://scryfall.com/search?q=!gratuitousviolence)
- [x] Done -- [Grave Endeavor](https://scryfall.com/search?q=!graveendeavor)
- [x] Done -- [Greater Good](https://scryfall.com/search?q=!greatergood)
- [x] Done -- [Grim Hireling](https://scryfall.com/search?q=!grimhireling)
- [x] Done -- [Gruul Signet](https://scryfall.com/search?q=!gruulsignet)
- [x] Done -- [Gruul Turf](https://scryfall.com/search?q=!gruulturf)
- [x] Done -- [Gryff's Boon](https://scryfall.com/search?q=!gryffsboon)
- [x] Done -- [Halimar Depths](https://scryfall.com/search?q=!halimardepths)
- [x] Done -- [Haven of the Spirit Dragon](https://scryfall.com/search?q=!havenofthespiritdragon)
- [x] Done -- [Heirloom Blade](https://scryfall.com/search?q=!heirloomblade)
- [x] Done -- [Hellish Rebuke](https://scryfall.com/search?q=!hellishrebuke)
- [x] Done -- [Heroic Intervention](https://scryfall.com/search?q=!heroicintervention)
- [x] Done -- [Hex](https://scryfall.com/search?q=!hex)
- [x] Done -- [High Market](https://scryfall.com/search?q=!highmarket)
- [x] Done -- [Hoard-Smelter Dragon](https://scryfall.com/search?q=!hoardsmelterdragon)
- [x] Done -- [Holy Avenger](https://scryfall.com/search?q=!holyavenger)
- [x] Done -- [Hostage Taker](https://scryfall.com/search?q=!hostagetaker)
- [x] Done -- [Hurl Through Hell](https://scryfall.com/search?q=!hurlthroughhell)
- [x] Done -- [Ignite the Future](https://scryfall.com/search?q=!ignitethefuture)
- [x] Done -- [Immovable Rod](https://scryfall.com/search?q=!immovablerod)
- [x] Done -- [Imprisoned in the Moon](https://scryfall.com/search?q=!imprisonedinthemoon)
- [x] Done -- [Indomitable Might](https://scryfall.com/search?q=!indomitablemight)
- [x] Done -- [Izzet Chemister](https://scryfall.com/search?q=!izzetchemister)
- [x] Done -- [Karazikar, the Eye Tyrant](https://scryfall.com/search?q=!karazikartheeyetyrant)
- [x] Done -- [Karmic Guide](https://scryfall.com/search?q=!karmicguide)
- [x] Done -- [Kenrith's Transformation](https://scryfall.com/search?q=!kenrithstransformation)
- [x] Done -- [Kindred Summons](https://scryfall.com/search?q=!kindredsummons)
- [x] Done -- [Klauth's Will](https://scryfall.com/search?q=!klauthswill)
- [x] Done -- [Klauth, Unrivaled Ancient](https://scryfall.com/search?q=!klauthunrivaledancient)
- [x] Done -- [Knight of Autumn](https://scryfall.com/search?q=!knightofautumn)
- [x] Done -- [Light Up the Stage](https://scryfall.com/search?q=!lightupthestage)
- [x] Done -- [Lightning Greaves](https://scryfall.com/search?q=!lightninggreaves)
- [x] Done -- [Lorcan, Warlock Collector](https://scryfall.com/search?q=!lorcanwarlockcollector)
- [x] Done -- [Loyal Apprentice](https://scryfall.com/search?q=!loyalapprentice)
- [x] Done -- [Lumbering Falls](https://scryfall.com/search?q=!lumberingfalls)
- [x] Done -- [Maddening Hex](https://scryfall.com/search?q=!maddeninghex)
- [x] Done -- [Magmaquake](https://scryfall.com/search?q=!magmaquake)
- [x] Done -- [Mantle of the Ancients](https://scryfall.com/search?q=!mantleoftheancients)
- [x] Done -- [Marionette Master](https://scryfall.com/search?q=!marionettemaster)
- [x] Done -- [Masterwork of Ingenuity](https://scryfall.com/search?q=!masterworkofingenuity)
- [x] Done -- [Merfolk Looter](https://scryfall.com/search?q=!merfolklooter)
- [x] Done -- [Meteor Golem](https://scryfall.com/search?q=!meteorgolem)
- [x] Done -- [Midnight Pathlighter](https://scryfall.com/search?q=!midnightpathlighter)
- [x] Done -- [Mind Stone](https://scryfall.com/search?q=!mindstone)
- [x] Done -- [Minn, Wily Illusionist](https://scryfall.com/search?q=!minnwilyillusionist)
- [x] Done -- [Mishra's Factory](https://scryfall.com/search?q=!mishrasfactory)
- [x] Done -- [Moonsilver Spear](https://scryfall.com/search?q=!moonsilverspear)
- [x] Done -- [Mortuary Mire](https://scryfall.com/search?q=!mortuarymire)
- [x] Done -- [Mossfire Valley](https://scryfall.com/search?q=!mossfirevalley)
- [x] Done -- [Mosswort Bridge](https://scryfall.com/search?q=!mosswortbridge)
- [x] Done -- [Mulldrifter](https://scryfall.com/search?q=!mulldrifter)
- [x] Done -- [Murder of Crows](https://scryfall.com/search?q=!murderofcrows)
- [x] Done -- [Nature's Lore](https://scryfall.com/search?q=!natureslore)
- [x] Done -- [Necromantic Selection](https://scryfall.com/search?q=!necromanticselection)
- [x] Done -- [Necrotic Sliver](https://scryfall.com/search?q=!necroticsliver)
- [x] Done -- [Netherese Puzzle-Ward](https://scryfall.com/search?q=!netheresepuzzleward)
- [x] Done -- [Neverwinter Hydra](https://scryfall.com/search?q=!neverwinterhydra)
- [x] Done -- [Nihiloor](https://scryfall.com/search?q=!nihiloor)
- [x] Done -- [Nimbus Maze](https://scryfall.com/search?q=!nimbusmaze)
- [x] Done -- [Obsessive Stitcher](https://scryfall.com/search?q=!obsessivestitcher)
- [x] Done -- [Ogre Slumlord](https://scryfall.com/search?q=!ogreslumlord)
- [x] Done -- [Opportunistic Dragon](https://scryfall.com/search?q=!opportunisticdragon)
- [x] Done -- [Orazca Relic](https://scryfall.com/search?q=!orazcarelic)
- [x] Done -- [Orzhov Basilica](https://scryfall.com/search?q=!orzhovbasilica)
- [x] Done -- [Outpost Siege](https://scryfall.com/search?q=!outpostsiege)
- [x] Done -- [Paradise Druid](https://scryfall.com/search?q=!paradisedruid)
- [x] Done -- [Path of Ancestry](https://scryfall.com/search?q=!pathofancestry)
- [x] Done -- [Phantasmal Image](https://scryfall.com/search?q=!phantasmalimage)
- [x] Done -- [Phantom Steed](https://scryfall.com/search?q=!phantomsteed)
- [x] Done -- [Phthisis](https://scryfall.com/search?q=!phthisis)
- [x] Done -- [Piper of the Swarm](https://scryfall.com/search?q=!piperoftheswarm)
- [x] Done -- [Plaguecrafter](https://scryfall.com/search?q=!plaguecrafter)
- [x] Done -- [Pontiff of Blight](https://scryfall.com/search?q=!pontiffofblight)
- [x] Done -- [Port Town](https://scryfall.com/search?q=!porttown)
- [x] Done -- [Prairie Stream](https://scryfall.com/search?q=!prairiestream)
- [x] Done -- [Prognostic Sphinx](https://scryfall.com/search?q=!prognosticsphinx)
- [x] Done -- [Propaganda](https://scryfall.com/search?q=!propaganda)
- [x] Done -- [Prosper, Tome-Bound](https://scryfall.com/search?q=!prospertomebound)
- [x] Done -- [Psychic Impetus](https://scryfall.com/search?q=!psychicimpetus)
- [x] Done -- [Puresteel Paladin](https://scryfall.com/search?q=!puresteelpaladin)
- [x] Done -- [Radiant Solar](https://scryfall.com/search?q=!radiantsolar)
- [x] Done -- [Rakdos Carnarium](https://scryfall.com/search?q=!rakdoscarnarium)
- [x] Done -- [Rakdos Charm](https://scryfall.com/search?q=!rakdoscharm)
- [x] Done -- [Rakdos Signet](https://scryfall.com/search?q=!rakdossignet)
- [x] Done -- [Rampant Growth](https://scryfall.com/search?q=!rampantgrowth)
- [x] Done -- [Rancor](https://scryfall.com/search?q=!rancor)
- [x] Done -- [Realm-Cloaked Giant](https://scryfall.com/search?q=!realmcloakedgiant)
- [x] Done -- [Reassembling Skeleton](https://scryfall.com/search?q=!reassemblingskeleton)
- [x] Done -- [Reckless Endeavor](https://scryfall.com/search?q=!recklessendeavor)
- [x] Done -- [Return of the Wildspeaker](https://scryfall.com/search?q=!returnofthewildspeaker)
- [x] Done -- [Return to Nature](https://scryfall.com/search?q=!returntonature)
- [x] Done -- [Revivify](https://scryfall.com/search?q=!revivify)
- [x] Done -- [Ride the Avalanche](https://scryfall.com/search?q=!ridetheavalanche)
- [x] Done -- [Rile](https://scryfall.com/search?q=!rile)
- [x] Done -- [Rishkar's Expertise](https://scryfall.com/search?q=!rishkarsexpertise)
- [x] Done -- [Riverwise Augur](https://scryfall.com/search?q=!riverwiseaugur)
- [x] Done -- [Robe of Stars](https://scryfall.com/search?q=!robeofstars)
- [x] Done -- [Rod of Absorption](https://scryfall.com/search?q=!rodofabsorption)
- [x] Done -- [Ronom Unicorn](https://scryfall.com/search?q=!ronomunicorn)
- [x] Done -- [Savage Ventmaw](https://scryfall.com/search?q=!savageventmaw)
- [x] Done -- [Scourge of Valkas](https://scryfall.com/search?q=!scourgeofvalkas)
- [x] Done -- [Seaside Citadel](https://scryfall.com/search?q=!seasidecitadel)
- [x] Done -- [Sefris of the Hidden Ways](https://scryfall.com/search?q=!sefrisofthehiddenways)
- [x] Done -- [Serum Visions](https://scryfall.com/search?q=!serumvisions)
- [x] Done -- [Shadowblood Ridge](https://scryfall.com/search?q=!shadowbloodridge)
- [x] Done -- [Shamanic Revelation](https://scryfall.com/search?q=!shamanicrevelation)
- [x] Done -- [Shielding Plax](https://scryfall.com/search?q=!shieldingplax)
- [x] Done -- [Shiny Impetus](https://scryfall.com/search?q=!shinyimpetus)
- [x] Done -- [Shivan Hellkite](https://scryfall.com/search?q=!shivanhellkite)
- [x] Done -- [Shriekmaw](https://scryfall.com/search?q=!shriekmaw)
- [x] Done -- [Simic Growth Chamber](https://scryfall.com/search?q=!simicgrowthchamber)
- [x] Done -- [Skycloud Expanse](https://scryfall.com/search?q=!skycloudexpanse)
- [x] Done -- [Skyline Despot](https://scryfall.com/search?q=!skylinedespot)
- [x] Done -- [Skyship Stalker](https://scryfall.com/search?q=!skyshipstalker)
- [x] Done -- [Smoldering Marsh](https://scryfall.com/search?q=!smolderingmarsh)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Solemn Simulacrum](https://scryfall.com/search?q=!solemnsimulacrum)
- [x] Done -- [Song of Inspiration](https://scryfall.com/search?q=!songofinspiration)
- [x] Done -- [Spinerock Knoll](https://scryfall.com/search?q=!spinerockknoll)
- [x] Done -- [Spit Flame](https://scryfall.com/search?q=!spitflame)
- [x] Done -- [Sram, Senior Edificer](https://scryfall.com/search?q=!sramsenioredificer)
- [x] Done -- [Storvald, Frost Giant Jarl](https://scryfall.com/search?q=!storvaldfrostgiantjarl)
- [x] Done -- [Sun Titan](https://scryfall.com/search?q=!suntitan)
- [x] Done -- [Sunblast Angel](https://scryfall.com/search?q=!sunblastangel)
- [x] Done -- [Sungrass Prairie](https://scryfall.com/search?q=!sungrassprairie)
- [x] Done -- [Sunken Hollow](https://scryfall.com/search?q=!sunkenhollow)
- [x] Done -- [Swiftfoot Boots](https://scryfall.com/search?q=!swiftfootboots)
- [x] Done -- [Sword of Hours](https://scryfall.com/search?q=!swordofhours)
- [x] Done -- [Sword of the Animist](https://scryfall.com/search?q=!swordoftheanimist)
- [x] Done -- [Swords to Plowshares](https://scryfall.com/search?q=!swordstoplowshares)
- [x] Done -- [Tainted Peak](https://scryfall.com/search?q=!taintedpeak)
- [x] Done -- [Talisman of Indulgence](https://scryfall.com/search?q=!talismanofindulgence)
- [x] Done -- [Taurean Mauler](https://scryfall.com/search?q=!taureanmauler)
- [x] Done -- [Tectonic Giant](https://scryfall.com/search?q=!tectonicgiant)
- [x] Done -- [Terminate](https://scryfall.com/search?q=!terminate)
- [x] Done -- [Terramorphic Expanse](https://scryfall.com/search?q=!terramorphicexpanse)
- [x] Done -- [Terror of Mount Velus](https://scryfall.com/search?q=!terrorofmountvelus)
- [x] Done -- [Theater of Horrors](https://scryfall.com/search?q=!theaterofhorrors)
- [x] Done -- [Thorough Investigation](https://scryfall.com/search?q=!thoroughinvestigation)
- [x] Done -- [Thriving Grove](https://scryfall.com/search?q=!thrivinggrove)
- [x] Done -- [Thriving Heath](https://scryfall.com/search?q=!thrivingheath)
- [x] Done -- [Thriving Isle](https://scryfall.com/search?q=!thrivingisle)
- [x] Done -- [Thriving Moor](https://scryfall.com/search?q=!thrivingmoor)
- [x] Done -- [Throes of Chaos](https://scryfall.com/search?q=!throesofchaos)
- [x] Done -- [Thunderbreak Regent](https://scryfall.com/search?q=!thunderbreakregent)
- [x] Done -- [Unburial Rites](https://scryfall.com/search?q=!unburialrites)
- [x] Done -- [Underdark Rift](https://scryfall.com/search?q=!underdarkrift)
- [x] Done -- [Unstable Obelisk](https://scryfall.com/search?q=!unstableobelisk)
- [x] Done -- [Utopia Sprawl](https://scryfall.com/search?q=!utopiasprawl)
- [x] Done -- [Utter End](https://scryfall.com/search?q=!utterend)
- [x] Done -- [Valiant Endeavor](https://scryfall.com/search?q=!valiantendeavor)
- [x] Done -- [Valorous Stance](https://scryfall.com/search?q=!valorousstance)
- [x] Done -- [Vandalblast](https://scryfall.com/search?q=!vandalblast)
- [x] Done -- [Vanish into Memory](https://scryfall.com/search?q=!vanishintomemory)
- [x] Done -- [Vengeful Ancestor](https://scryfall.com/search?q=!vengefulancestor)
- [x] Done -- [Verdant Embrace](https://scryfall.com/search?q=!verdantembrace)
- [x] Done -- [Victimize](https://scryfall.com/search?q=!victimize)
- [x] Done -- [Viridian Longbow](https://scryfall.com/search?q=!viridianlongbow)
- [x] Done -- [Vitu-Ghazi, the City-Tree](https://scryfall.com/search?q=!vitughazithecitytree)
- [x] Done -- [Vrondiss, Rage of Ancients](https://scryfall.com/search?q=!vrondissrageofancients)
- [x] Done -- [Wall of Omens](https://scryfall.com/search?q=!wallofomens)
- [x] Done -- [Wand of Orcus](https://scryfall.com/search?q=!wandoforcus)
- [x] Done -- [Warstorm Surge](https://scryfall.com/search?q=!warstormsurge)
- [x] Done -- [Wayfarer's Bauble](https://scryfall.com/search?q=!wayfarersbauble)
- [x] Done -- [Wild Endeavor](https://scryfall.com/search?q=!wildendeavor)
- [x] Done -- [Wild Growth](https://scryfall.com/search?q=!wildgrowth)
- [x] Done -- [Wild-Magic Sorcerer](https://scryfall.com/search?q=!wildmagicsorcerer)
- [x] Done -- [Winds of Rath](https://scryfall.com/search?q=!windsofrath)
- [x] Done -- [Winged Boots](https://scryfall.com/search?q=!wingedboots)
- [x] Done -- [Wulfgar of Icewind Dale](https://scryfall.com/search?q=!wulfgaroficewinddale)
- [x] Done -- [Zhalfirin Void](https://scryfall.com/search?q=!zhalfirinvoid)
</details>

**Comment by theelk801** [comment]
- [ ] In progress -- [Galea, Kindler of Hope](https://scryfall.com/search?q=!galeakindlerofhope)
- [ ] In progress -- [Prosper, Tome-Bound](https://scryfall.com/search?q=!prospertomebound)
- [ ] In progress -- [Sefris of the Hidden Ways](https://scryfall.com/search?q=!sefrisofthehiddenways)
- [ ] In progress -- [Vrondiss, Rage of Ancients](https://scryfall.com/search?q=!vrondissrageofancients)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"galeakindlerofhope"or!"prospertomebound"or!"sefrisofthehiddenways"or!"vrondissrageofancients"&unique=cards)

**Comment by theelk801** [comment]
Additional tasks:

None yet

**Comment by zeffirojoe** [comment]
Cant mark cards:
Fiendlash and Fey Steed Merged
