### ISSUE TITLE
MID - Innistrad: Midnight Hunt Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8103]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abandon the Post](https://scryfall.com/search?q=!abandonthepost)
- [x] Done -- [Adeline, Resplendent Cathar](https://scryfall.com/search?q=!adelineresplendentcathar)
- [x] Done -- [Ambitious Farmhand](https://scryfall.com/search?q=!ambitiousfarmhand)
- [x] Done -- [Angelfire Ignition](https://scryfall.com/search?q=!angelfireignition)
- [x] Done -- [Angelic Enforcer](https://scryfall.com/search?q=!angelicenforcer)
- [x] Done -- [Arcane Infusion](https://scryfall.com/search?q=!arcaneinfusion)
- [x] Done -- [Archive Haunt](https://scryfall.com/search?q=!archivehaunt)
- [x] Done -- [Ardent Elementalist](https://scryfall.com/search?q=!ardentelementalist)
- [x] Done -- [Arlinn, the Moon's Fury](https://scryfall.com/search?q=!arlinnthemoonsfury)
- [x] Done -- [Arlinn, the Pack's Hope](https://scryfall.com/search?q=!arlinnthepackshope)
- [x] Done -- [Arrogant Outlaw](https://scryfall.com/search?q=!arrogantoutlaw)
- [x] Done -- [Ashmouth Dragon](https://scryfall.com/search?q=!ashmouthdragon)
- [x] Done -- [Augur of Autumn](https://scryfall.com/search?q=!augurofautumn)
- [x] Done -- [Awoken Demon](https://scryfall.com/search?q=!awokendemon)
- [x] Done -- [Baithook Angler](https://scryfall.com/search?q=!baithookangler)
- [x] Done -- [Baneblade Scoundrel](https://scryfall.com/search?q=!banebladescoundrel)
- [x] Done -- [Baneclaw Marauder](https://scryfall.com/search?q=!baneclawmarauder)
- [x] Done -- [Bat Whisperer](https://scryfall.com/search?q=!batwhisperer)
- [x] Done -- [Beloved Beggar](https://scryfall.com/search?q=!belovedbeggar)
- [x] Done -- [Benevolent Geist](https://scryfall.com/search?q=!benevolentgeist)
- [x] Done -- [Bereaved Survivor](https://scryfall.com/search?q=!bereavedsurvivor)
- [x] Done -- [Bird Admirer](https://scryfall.com/search?q=!birdadmirer)
- [x] Done -- [Bladebrand](https://scryfall.com/search?q=!bladebrand)
- [x] Done -- [Bladestitched Skaab](https://scryfall.com/search?q=!bladestitchedskaab)
- [x] Done -- [Blessed Defiance](https://scryfall.com/search?q=!blesseddefiance)
- [x] Done -- [Blood Pact](https://scryfall.com/search?q=!bloodpact)
- [x] Done -- [Bloodline Culling](https://scryfall.com/search?q=!bloodlineculling)
- [x] Done -- [Bloodthirsty Adversary](https://scryfall.com/search?q=!bloodthirstyadversary)
- [x] Done -- [Bloodtithe Collector](https://scryfall.com/search?q=!bloodtithecollector)
- [x] Done -- [Borrowed Time](https://scryfall.com/search?q=!borrowedtime)
- [x] Done -- [Bounding Wolf](https://scryfall.com/search?q=!boundingwolf)
- [x] Done -- [Bramble Armor](https://scryfall.com/search?q=!bramblearmor)
- [x] Done -- [Briarbridge Tracker](https://scryfall.com/search?q=!briarbridgetracker)
- [x] Done -- [Brimstone Vandal](https://scryfall.com/search?q=!brimstonevandal)
- [x] Done -- [Brood Weaver](https://scryfall.com/search?q=!broodweaver)
- [x] Done -- [Brutal Cathar](https://scryfall.com/search?q=!brutalcathar)
- [x] Done -- [Burly Breaker](https://scryfall.com/search?q=!burlybreaker)
- [x] Done -- [Burn Down the House](https://scryfall.com/search?q=!burndownthehouse)
- [x] Done -- [Burn the Accursed](https://scryfall.com/search?q=!burntheaccursed)
- [x] Done -- [Can't Stay Away](https://scryfall.com/search?q=!cantstayaway)
- [x] Done -- [Candlegrove Witch](https://scryfall.com/search?q=!candlegrovewitch)
- [x] Done -- [Candlelit Cavalry](https://scryfall.com/search?q=!candlelitcavalry)
- [x] Done -- [Candletrap](https://scryfall.com/search?q=!candletrap)
- [x] Done -- [Cathar Commando](https://scryfall.com/search?q=!catharcommando)
- [x] Done -- [Cathar's Call](https://scryfall.com/search?q=!catharscall)
- [x] Done -- [Cathartic Pyre](https://scryfall.com/search?q=!catharticpyre)
- [x] Done -- [Celestus Sanctifier](https://scryfall.com/search?q=!celestussanctifier)
- [x] Done -- [Champion of the Perished](https://scryfall.com/search?q=!championoftheperished)
- [x] Done -- [Chapel Shieldgeist](https://scryfall.com/search?q=!chapelshieldgeist)
- [x] Done -- [Chaplain of Alms](https://scryfall.com/search?q=!chaplainofalms)
- [x] Done -- [Chilling Chronicle](https://scryfall.com/search?q=!chillingchronicle)
- [x] Done -- [Clarion Cathars](https://scryfall.com/search?q=!clarioncathars)
- [x] Done -- [Clear Shot](https://scryfall.com/search?q=!clearshot)
- [x] Done -- [Component Collector](https://scryfall.com/search?q=!componentcollector)
- [x] Done -- [Consider](https://scryfall.com/search?q=!consider)
- [x] Done -- [Consuming Blob](https://scryfall.com/search?q=!consumingblob)
- [x] Done -- [Contortionist Troupe](https://scryfall.com/search?q=!contortionisttroupe)
- [x] Done -- [Corpse Cobble](https://scryfall.com/search?q=!corpsecobble)
- [x] Done -- [Covert Cutpurse](https://scryfall.com/search?q=!covertcutpurse)
- [x] Done -- [Covetous Castaway](https://scryfall.com/search?q=!covetouscastaway)
- [x] Done -- [Covetous Geist](https://scryfall.com/search?q=!covetousgeist)
- [x] Done -- [Crawl from the Cellar](https://scryfall.com/search?q=!crawlfromthecellar)
- [x] Done -- [Creeping Inn](https://scryfall.com/search?q=!creepinginn)
- [x] Done -- [Croaking Counterpart](https://scryfall.com/search?q=!croakingcounterpart)
- [x] Done -- [Crossroads Candleguide](https://scryfall.com/search?q=!crossroadscandleguide)
- [x] Done -- [Curse of Leeches](https://scryfall.com/search?q=!curseofleeches)
- [x] Done -- [Curse of Shaken Faith](https://scryfall.com/search?q=!curseofshakenfaith)
- [x] Done -- [Curse of Silence](https://scryfall.com/search?q=!curseofsilence)
- [x] Done -- [Curse of Surveillance](https://scryfall.com/search?q=!curseofsurveillance)
- [x] Done -- [Dauntless Avenger](https://scryfall.com/search?q=!dauntlessavenger)
- [x] Done -- [Dawnhart Mentor](https://scryfall.com/search?q=!dawnhartmentor)
- [x] Done -- [Dawnhart Rejuvenator](https://scryfall.com/search?q=!dawnhartrejuvenator)
- [x] Done -- [Dawnhart Wardens](https://scryfall.com/search?q=!dawnhartwardens)
- [x] Done -- [Deathbonnet Hulk](https://scryfall.com/search?q=!deathbonnethulk)
- [x] Done -- [Deathbonnet Sprout](https://scryfall.com/search?q=!deathbonnetsprout)
- [x] Done -- [Defend the Celestus](https://scryfall.com/search?q=!defendthecelestus)
- [x] Done -- [Defenestrate](https://scryfall.com/search?q=!defenestrate)
- [x] Done -- [Delver of Secrets](https://scryfall.com/search?q=!delverofsecrets)
- [x] Done -- [Dennick, Pious Apparition](https://scryfall.com/search?q=!dennickpiousapparition)
- [x] Done -- [Dennick, Pious Apprentice](https://scryfall.com/search?q=!dennickpiousapprentice)
- [x] Done -- [Departed Soulkeeper](https://scryfall.com/search?q=!departedsoulkeeper)
- [x] Done -- [Deserted Beach](https://scryfall.com/search?q=!desertedbeach)
- [x] Done -- [Devious Cover-Up](https://scryfall.com/search?q=!deviouscoverup)
- [x] Done -- [Devoted Grafkeeper](https://scryfall.com/search?q=!devotedgrafkeeper)
- [x] Done -- [Dire-Strain Brawler](https://scryfall.com/search?q=!direstrainbrawler)
- [x] Done -- [Dire-Strain Demolisher](https://scryfall.com/search?q=!direstraindemolisher)
- [x] Done -- [Dire-Strain Rampage](https://scryfall.com/search?q=!direstrainrampage)
- [x] Done -- [Diregraf Horde](https://scryfall.com/search?q=!diregrafhorde)
- [x] Done -- [Diregraf Rebirth](https://scryfall.com/search?q=!diregrafrebirth)
- [x] Done -- [Dissipate](https://scryfall.com/search?q=!dissipate)
- [x] Done -- [Dreadhound](https://scryfall.com/search?q=!dreadhound)
- [x] Done -- [Drownyard Amalgam](https://scryfall.com/search?q=!drownyardamalgam)
- [x] Done -- [Dryad's Revival](https://scryfall.com/search?q=!dryadsrevival)
- [x] Done -- [Duel for Dominance](https://scryfall.com/search?q=!duelfordominance)
- [x] Done -- [Duelcraft Trainer](https://scryfall.com/search?q=!duelcrafttrainer)
- [x] Done -- [Duress](https://scryfall.com/search?q=!duress)
- [x] Done -- [Eaten Alive](https://scryfall.com/search?q=!eatenalive)
- [x] Done -- [Eccentric Farmer](https://scryfall.com/search?q=!eccentricfarmer)
- [x] Done -- [Ecstatic Awakener](https://scryfall.com/search?q=!ecstaticawakener)
- [x] Done -- [Electric Revelation](https://scryfall.com/search?q=!electricrevelation)
- [x] Done -- [Embodiment of Flame](https://scryfall.com/search?q=!embodimentofflame)
- [x] Done -- [Enduring Angel](https://scryfall.com/search?q=!enduringangel)
- [x] Done -- [Evolving Wilds](https://scryfall.com/search?q=!evolvingwilds)
- [x] Done -- [Fading Hope](https://scryfall.com/search?q=!fadinghope)
- [x] Done -- [Faithful Mending](https://scryfall.com/search?q=!faithfulmending)
- [x] Done -- [Falcon Abomination](https://scryfall.com/search?q=!falconabomination)
- [x] Done -- [Falkenrath Perforator](https://scryfall.com/search?q=!falkenrathperforator)
- [x] Done -- [Falkenrath Pit Fighter](https://scryfall.com/search?q=!falkenrathpitfighter)
- [x] Done -- [Famished Foragers](https://scryfall.com/search?q=!famishedforagers)
- [x] Done -- [Fangblade Brigand](https://scryfall.com/search?q=!fangbladebrigand)
- [x] Done -- [Fangblade Eviscerator](https://scryfall.com/search?q=!fangbladeeviscerator)
- [x] Done -- [Fateful Absence](https://scryfall.com/search?q=!fatefulabsence)
- [x] Done -- [Festival Crasher](https://scryfall.com/search?q=!festivalcrasher)
- [x] Done -- [Field of Ruin](https://scryfall.com/search?q=!fieldofruin)
- [x] Done -- [Firmament Sage](https://scryfall.com/search?q=!firmamentsage)
- [x] Done -- [Flame Channeler](https://scryfall.com/search?q=!flamechanneler)
- [x] Done -- [Flare of Faith](https://scryfall.com/search?q=!flareoffaith)
- [x] Done -- [Fleshtaker](https://scryfall.com/search?q=!fleshtaker)
- [x] Done -- [Flip the Switch](https://scryfall.com/search?q=!fliptheswitch)
- [x] Done -- [Florian, Voldaren Scion](https://scryfall.com/search?q=!florianvoldarenscion)
- [x] Done -- [Foul Play](https://scryfall.com/search?q=!foulplay)
- [x] Done -- [Frenzied Trapbreaker](https://scryfall.com/search?q=!frenziedtrapbreaker)
- [x] Done -- [Galedrifter](https://scryfall.com/search?q=!galedrifter)
- [x] Done -- [Galvanic Iteration](https://scryfall.com/search?q=!galvaniciteration)
- [x] Done -- [Gavony Dawnguard](https://scryfall.com/search?q=!gavonydawnguard)
- [x] Done -- [Gavony Silversmith](https://scryfall.com/search?q=!gavonysilversmith)
- [x] Done -- [Gavony Trapper](https://scryfall.com/search?q=!gavonytrapper)
- [x] Done -- [Geistflame Reservoir](https://scryfall.com/search?q=!geistflamereservoir)
- [x] Done -- [Geistwave](https://scryfall.com/search?q=!geistwave)
- [x] Done -- [Generous Soul](https://scryfall.com/search?q=!generoussoul)
- [x] Done -- [Ghostly Castigator](https://scryfall.com/search?q=!ghostlycastigator)
- [x] Done -- [Ghoulcaller's Harvest](https://scryfall.com/search?q=!ghoulcallersharvest)
- [x] Done -- [Ghoulish Procession](https://scryfall.com/search?q=!ghoulishprocession)
- [x] Done -- [Gisa, Glorious Resurrector](https://scryfall.com/search?q=!gisagloriousresurrector)
- [x] Done -- [Grafted Identity](https://scryfall.com/search?q=!graftedidentity)
- [x] Done -- [Graveyard Glutton](https://scryfall.com/search?q=!graveyardglutton)
- [x] Done -- [Graveyard Trespasser](https://scryfall.com/search?q=!graveyardtrespasser)
- [x] Done -- [Grizzly Ghoul](https://scryfall.com/search?q=!grizzlyghoul)
- [x] Done -- [Hallowed Respite](https://scryfall.com/search?q=!hallowedrespite)
- [x] Done -- [Harvesttide Assailant](https://scryfall.com/search?q=!harvesttideassailant)
- [x] Done -- [Harvesttide Infiltrator](https://scryfall.com/search?q=!harvesttideinfiltrator)
- [x] Done -- [Harvesttide Sentry](https://scryfall.com/search?q=!harvesttidesentry)
- [x] Done -- [Haunted Ridge](https://scryfall.com/search?q=!hauntedridge)
- [x] Done -- [Hedgewitch's Mask](https://scryfall.com/search?q=!hedgewitchsmask)
- [x] Done -- [Heirloom Mirror](https://scryfall.com/search?q=!heirloommirror)
- [x] Done -- [Hobbling Zombie](https://scryfall.com/search?q=!hobblingzombie)
- [x] Done -- [Homestead Courage](https://scryfall.com/search?q=!homesteadcourage)
- [x] Done -- [Hook-Haunt Drifter](https://scryfall.com/search?q=!hookhauntdrifter)
- [x] Done -- [Hostile Hostel](https://scryfall.com/search?q=!hostilehostel)
- [x] Done -- [Hound Tamer](https://scryfall.com/search?q=!houndtamer)
- [x] Done -- [Howl of the Hunt](https://scryfall.com/search?q=!howlofthehunt)
- [x] Done -- [Hungry for More](https://scryfall.com/search?q=!hungryformore)
- [x] Done -- [Immolation](https://scryfall.com/search?q=!immolation)
- [x] Done -- [Infernal Grasp](https://scryfall.com/search?q=!infernalgrasp)
- [x] Done -- [Inherited Fiend](https://scryfall.com/search?q=!inheritedfiend)
- [x] Done -- [Insectile Aberration](https://scryfall.com/search?q=!insectileaberration)
- [x] Done -- [Intrepid Adversary](https://scryfall.com/search?q=!intrepidadversary)
- [x] Done -- [Jack-o'-Lantern](https://scryfall.com/search?q=!jackolantern)
- [x] Done -- [Jadar, Ghoulcaller of Nephalia](https://scryfall.com/search?q=!jadarghoulcallerofnephalia)
- [x] Done -- [Jerren, Corrupted Bishop](https://scryfall.com/search?q=!jerrencorruptedbishop)
- [x] Done -- [Join the Dance](https://scryfall.com/search?q=!jointhedance)
- [x] Done -- [Katilda, Dawnhart Prime](https://scryfall.com/search?q=!katildadawnhartprime)
- [x] Done -- [Kessig Naturalist](https://scryfall.com/search?q=!kessignaturalist)
- [x] Done -- [Lambholt Harrier](https://scryfall.com/search?q=!lambholtharrier)
- [x] Done -- [Larder Zombie](https://scryfall.com/search?q=!larderzombie)
- [x] Done -- [Leeching Lurker](https://scryfall.com/search?q=!leechinglurker)
- [x] Done -- [Lier, Disciple of the Drowned](https://scryfall.com/search?q=!lierdiscipleofthedrowned)
- [x] Done -- [Liesa, Forgotten Archangel](https://scryfall.com/search?q=!liesaforgottenarchangel)
- [x] Done -- [Light Up the Night](https://scryfall.com/search?q=!lightupthenight)
- [x] Done -- [Locked in the Cemetery](https://scryfall.com/search?q=!lockedinthecemetery)
- [x] Done -- [Lord of the Forsaken](https://scryfall.com/search?q=!lordoftheforsaken)
- [x] Done -- [Lord of the Ulvenwald](https://scryfall.com/search?q=!lordoftheulvenwald)
- [x] Done -- [Loyal Gryff](https://scryfall.com/search?q=!loyalgryff)
- [x] Done -- [Ludevic, Necrogenius](https://scryfall.com/search?q=!ludevicnecrogenius)
- [x] Done -- [Luminous Phantom](https://scryfall.com/search?q=!luminousphantom)
- [x] Done -- [Lunar Frenzy](https://scryfall.com/search?q=!lunarfrenzy)
- [x] Done -- [Lunarch Veteran](https://scryfall.com/search?q=!lunarchveteran)
- [x] Done -- [Malevolent Hermit](https://scryfall.com/search?q=!malevolenthermit)
- [x] Done -- [Mask of Griselbrand](https://scryfall.com/search?q=!maskofgriselbrand)
- [x] Done -- [Memory Deluge](https://scryfall.com/search?q=!memorydeluge)
- [x] Done -- [Might of the Old Ways](https://scryfall.com/search?q=!mightoftheoldways)
- [x] Done -- [Moonrage Brute](https://scryfall.com/search?q=!moonragebrute)
- [x] Done -- [Moonrager's Slash](https://scryfall.com/search?q=!moonragersslash)
- [x] Done -- [Moonsilver Key](https://scryfall.com/search?q=!moonsilverkey)
- [x] Done -- [Moonveil Regent](https://scryfall.com/search?q=!moonveilregent)
- [x] Done -- [Morbid Opportunist](https://scryfall.com/search?q=!morbidopportunist)
- [x] Done -- [Morkrut Behemoth](https://scryfall.com/search?q=!morkrutbehemoth)
- [x] Done -- [Morning Apparition](https://scryfall.com/search?q=!morningapparition)
- [x] Done -- [Mounted Dreadknight](https://scryfall.com/search?q=!mounteddreadknight)
- [x] Done -- [Mourning Patrol](https://scryfall.com/search?q=!mourningpatrol)
- [x] Done -- [Mysterious Tome](https://scryfall.com/search?q=!mysterioustome)
- [x] Done -- [Mystic Monstrosity](https://scryfall.com/search?q=!mysticmonstrosity)
- [x] Done -- [Mystic Skull](https://scryfall.com/search?q=!mysticskull)
- [x] Done -- [Nebelgast Intruder](https://scryfall.com/search?q=!nebelgastintruder)
- [x] Done -- [Necrosynthesis](https://scryfall.com/search?q=!necrosynthesis)
- [x] Done -- [Neonate's Rush](https://scryfall.com/search?q=!neonatesrush)
- [x] Done -- [No Way Out](https://scryfall.com/search?q=!nowayout)
- [x] Done -- [Novice Occultist](https://scryfall.com/search?q=!noviceoccultist)
- [x] Done -- [Obsessive Astronomer](https://scryfall.com/search?q=!obsessiveastronomer)
- [x] Done -- [Odric's Outrider](https://scryfall.com/search?q=!odricsoutrider)
- [x] Done -- [Olag, Ludevic's Hubris](https://scryfall.com/search?q=!olagludevicshubris)
- [x] Done -- [Old Stickfingers](https://scryfall.com/search?q=!oldstickfingers)
- [x] Done -- [Olivia's Midnight Ambush](https://scryfall.com/search?q=!oliviasmidnightambush)
- [x] Done -- [Ominous Roost](https://scryfall.com/search?q=!ominousroost)
- [x] Done -- [Organ Hoarder](https://scryfall.com/search?q=!organhoarder)
- [x] Done -- [Ormendahl, the Corrupter](https://scryfall.com/search?q=!ormendahlthecorrupter)
- [x] Done -- [Otherworldly Gaze](https://scryfall.com/search?q=!otherworldlygaze)
- [x] Done -- [Outland Liberator](https://scryfall.com/search?q=!outlandliberator)
- [x] Done -- [Overgrown Farmland](https://scryfall.com/search?q=!overgrownfarmland)
- [x] Done -- [Overwhelmed Archivist](https://scryfall.com/search?q=!overwhelmedarchivist)
- [x] Done -- [Pack's Betrayal](https://scryfall.com/search?q=!packsbetrayal)
- [x] Done -- [Path to the Festival](https://scryfall.com/search?q=!pathtothefestival)
- [x] Done -- [Patrician Geist](https://scryfall.com/search?q=!patriciangeist)
- [x] Done -- [Pestilent Wolf](https://scryfall.com/search?q=!pestilentwolf)
- [x] Done -- [Phantom Carriage](https://scryfall.com/search?q=!phantomcarriage)
- [x] Done -- [Pithing Needle](https://scryfall.com/search?q=!pithingneedle)
- [x] Done -- [Play with Fire](https://scryfall.com/search?q=!playwithfire)
- [x] Done -- [Plummet](https://scryfall.com/search?q=!plummet)
- [x] Done -- [Poppet Factory](https://scryfall.com/search?q=!poppetfactory)
- [x] Done -- [Poppet Stitcher](https://scryfall.com/search?q=!poppetstitcher)
- [x] Done -- [Primal Adversary](https://scryfall.com/search?q=!primaladversary)
- [x] Done -- [Purifying Dragon](https://scryfall.com/search?q=!purifyingdragon)
- [x] Done -- [Raze the Effigy](https://scryfall.com/search?q=!razetheeffigy)
- [x] Done -- [Reckless Stormseeker](https://scryfall.com/search?q=!recklessstormseeker)
- [x] Done -- [Rem Karolus, Stalwart Slayer](https://scryfall.com/search?q=!remkarolusstalwartslayer)
- [x] Done -- [Return to Nature](https://scryfall.com/search?q=!returntonature)
- [x] Done -- [Revenge of the Drowned](https://scryfall.com/search?q=!revengeofthedrowned)
- [x] Done -- [Rise of the Ants](https://scryfall.com/search?q=!riseoftheants)
- [x] Done -- [Rite of Harmony](https://scryfall.com/search?q=!riteofharmony)
- [x] Done -- [Rite of Oblivion](https://scryfall.com/search?q=!riteofoblivion)
- [x] Done -- [Ritual Guardian](https://scryfall.com/search?q=!ritualguardian)
- [x] Done -- [Ritual of Hope](https://scryfall.com/search?q=!ritualofhope)
- [x] Done -- [Rockfall Vale](https://scryfall.com/search?q=!rockfallvale)
- [x] Done -- [Rootcoil Creeper](https://scryfall.com/search?q=!rootcoilcreeper)
- [x] Done -- [Rotten Reunion](https://scryfall.com/search?q=!rottenreunion)
- [x] Done -- [Sacred Fire](https://scryfall.com/search?q=!sacredfire)
- [x] Done -- [Saryth, the Viper's Fang](https://scryfall.com/search?q=!saryththevipersfang)
- [x] Done -- [Seafaring Werewolf](https://scryfall.com/search?q=!seafaringwerewolf)
- [x] Done -- [Search Party Captain](https://scryfall.com/search?q=!searchpartycaptain)
- [x] Done -- [Seasoned Cathar](https://scryfall.com/search?q=!seasonedcathar)
- [x] Done -- [Secrets of the Key](https://scryfall.com/search?q=!secretsofthekey)
- [x] Done -- [Seize the Storm](https://scryfall.com/search?q=!seizethestorm)
- [x] Done -- [Shadowbeast Sighting](https://scryfall.com/search?q=!shadowbeastsighting)
- [x] Done -- [Shady Traveler](https://scryfall.com/search?q=!shadytraveler)
- [x] Done -- [Shipwreck Marsh](https://scryfall.com/search?q=!shipwreckmarsh)
- [x] Done -- [Shipwreck Sifters](https://scryfall.com/search?q=!shipwrecksifters)
- [x] Done -- [Siege Zombie](https://scryfall.com/search?q=!siegezombie)
- [x] Done -- [Sigarda's Splendor](https://scryfall.com/search?q=!sigardassplendor)
- [x] Done -- [Sigarda, Champion of Light](https://scryfall.com/search?q=!sigardachampionoflight)
- [x] Done -- [Sigardian Savior](https://scryfall.com/search?q=!sigardiansavior)
- [x] Done -- [Silver Bolt](https://scryfall.com/search?q=!silverbolt)
- [x] Done -- [Siphon Insight](https://scryfall.com/search?q=!siphoninsight)
- [x] Done -- [Skaab Wrangler](https://scryfall.com/search?q=!skaabwrangler)
- [x] Done -- [Slaughter Specialist](https://scryfall.com/search?q=!slaughterspecialist)
- [x] Done -- [Slogurk, the Overslime](https://scryfall.com/search?q=!slogurktheoverslime)
- [x] Done -- [Sludge Monster](https://scryfall.com/search?q=!sludgemonster)
- [x] Done -- [Smoldering Egg](https://scryfall.com/search?q=!smolderingegg)
- [x] Done -- [Snarling Wolf](https://scryfall.com/search?q=!snarlingwolf)
- [x] Done -- [Soul-Guide Gryff](https://scryfall.com/search?q=!soulguidegryff)
- [x] Done -- [Spectral Adversary](https://scryfall.com/search?q=!spectraladversary)
- [x] Done -- [Spellrune Howler](https://scryfall.com/search?q=!spellrunehowler)
- [x] Done -- [Spellrune Painter](https://scryfall.com/search?q=!spellrunepainter)
- [x] Done -- [Stalking Predator](https://scryfall.com/search?q=!stalkingpredator)
- [x] Done -- [Startle](https://scryfall.com/search?q=!startle)
- [x] Done -- [Stolen Vitality](https://scryfall.com/search?q=!stolenvitality)
- [x] Done -- [Storm Skreelix](https://scryfall.com/search?q=!stormskreelix)
- [x] Done -- [Storm the Festival](https://scryfall.com/search?q=!stormthefestival)
- [x] Done -- [Storm-Charged Slasher](https://scryfall.com/search?q=!stormchargedslasher)
- [x] Done -- [Stormrider Spirit](https://scryfall.com/search?q=!stormriderspirit)
- [x] Done -- [Strangling Grasp](https://scryfall.com/search?q=!stranglinggrasp)
- [x] Done -- [Stromkirk Bloodthief](https://scryfall.com/search?q=!stromkirkbloodthief)
- [x] Done -- [Stuffed Bear](https://scryfall.com/search?q=!stuffedbear)
- [x] Done -- [Sungold Barrage](https://scryfall.com/search?q=!sungoldbarrage)
- [x] Done -- [Sungold Sentinel](https://scryfall.com/search?q=!sungoldsentinel)
- [x] Done -- [Sunrise Cavalier](https://scryfall.com/search?q=!sunrisecavalier)
- [x] Done -- [Sunset Revelry](https://scryfall.com/search?q=!sunsetrevelry)
- [x] Done -- [Sunstreak Phoenix](https://scryfall.com/search?q=!sunstreakphoenix)
- [x] Done -- [Suspicious Stowaway](https://scryfall.com/search?q=!suspiciousstowaway)
- [x] Done -- [Tainted Adversary](https://scryfall.com/search?q=!taintedadversary)
- [x] Done -- [Tapping at the Window](https://scryfall.com/search?q=!tappingatthewindow)
- [x] Done -- [Tavern Ruffian](https://scryfall.com/search?q=!tavernruffian)
- [x] Done -- [Tavern Smasher](https://scryfall.com/search?q=!tavernsmasher)
- [x] Done -- [Teferi, Who Slows the Sunset](https://scryfall.com/search?q=!teferiwhoslowsthesunset)
- [x] Done -- [The Celestus](https://scryfall.com/search?q=!thecelestus)
- [x] Done -- [The Meathook Massacre](https://scryfall.com/search?q=!themeathookmassacre)
- [x] Done -- [Thermo-Alchemist](https://scryfall.com/search?q=!thermoalchemist)
- [x] Done -- [Thraben Exorcism](https://scryfall.com/search?q=!thrabenexorcism)
- [x] Done -- [Timberland Guide](https://scryfall.com/search?q=!timberlandguide)
- [x] Done -- [Tireless Hauler](https://scryfall.com/search?q=!tirelesshauler)
- [x] Done -- [Tovolar's Huntmaster](https://scryfall.com/search?q=!tovolarshuntmaster)
- [x] Done -- [Tovolar's Packleader](https://scryfall.com/search?q=!tovolarspackleader)
- [x] Done -- [Tovolar, Dire Overlord](https://scryfall.com/search?q=!tovolardireoverlord)
- [x] Done -- [Tovolar, the Midnight Scourge](https://scryfall.com/search?q=!tovolarthemidnightscourge)
- [x] Done -- [Triskaidekaphile](https://scryfall.com/search?q=!triskaidekaphile)
- [x] Done -- [Turn the Earth](https://scryfall.com/search?q=!turntheearth)
- [x] Done -- [Unblinking Observer](https://scryfall.com/search?q=!unblinkingobserver)
- [x] Done -- [Unnatural Growth](https://scryfall.com/search?q=!unnaturalgrowth)
- [x] Done -- [Unnatural Moonrise](https://scryfall.com/search?q=!unnaturalmoonrise)
- [x] Done -- [Unruly Mob](https://scryfall.com/search?q=!unrulymob)
- [x] Done -- [Untamed Pup](https://scryfall.com/search?q=!untamedpup)
- [x] Done -- [Vadrik, Astral Archmage](https://scryfall.com/search?q=!vadrikastralarchmage)
- [x] Done -- [Vampire Interloper](https://scryfall.com/search?q=!vampireinterloper)
- [x] Done -- [Vampire Socialite](https://scryfall.com/search?q=!vampiresocialite)
- [x] Done -- [Vanquish the Horde](https://scryfall.com/search?q=!vanquishthehorde)
- [x] Done -- [Vengeful Strangler](https://scryfall.com/search?q=!vengefulstrangler)
- [x] Done -- [Village Reavers](https://scryfall.com/search?q=!villagereavers)
- [x] Done -- [Village Watch](https://scryfall.com/search?q=!villagewatch)
- [x] Done -- [Vivisection](https://scryfall.com/search?q=!vivisection)
- [x] Done -- [Voldaren Ambusher](https://scryfall.com/search?q=!voldarenambusher)
- [x] Done -- [Voldaren Stinger](https://scryfall.com/search?q=!voldarenstinger)
- [x] Done -- [Waildrifter](https://scryfall.com/search?q=!waildrifter)
- [x] Done -- [Wake to Slaughter](https://scryfall.com/search?q=!waketoslaughter)
- [x] Done -- [Willow Geist](https://scryfall.com/search?q=!willowgeist)
- [x] Done -- [Wing Shredder](https://scryfall.com/search?q=!wingshredder)
- [x] Done -- [Winterthorn Blessing](https://scryfall.com/search?q=!winterthornblessing)
- [x] Done -- [Wrenn and Seven](https://scryfall.com/search?q=!wrennandseven)
</details>

**Comment by theelk801** [comment]
All currently previewed cards have been implemented

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by weirddan455** [comment]
I'll take a shot at getting Disturb implemented.

**Comment by michaelrfarcasin** [comment]
I implemented Baneblade Scoundrel in this PR:
https://github.com/magefree/mage/pull/8360

**Comment by theelk801** [comment]
Baneblade Scoundrel is already implemented as part of #8200

**Comment by michaelrfarcasin** [comment]
I don't understand - the original post says it's not done.
What still needs to be done for MID?

**Comment by JayDi85** [comment]
@michaelrfarcasin look at next comment with "progress". All mid's cards are done and need some testing and improves.

**Comment by michaelrfarcasin** [comment]
I read through the comments for this and the two PRs, and it looks like they're just waiting to be merged.
