### ISSUE TITLE
J21 - Jumpstart: Historic Horizons Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8105]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] Not Done -- [Baffling Defenses](https://scryfall.com/search?q=!bafflingdefenses)
- [ ] Not Done -- [Benalish Partisan](https://scryfall.com/search?q=!benalishpartisan)
- [ ] Not Done -- [Boneyard Aberration](https://scryfall.com/search?q=!boneyardaberration)
- [ ] Not Done -- [Davriel's Withering](https://scryfall.com/search?q=!davrielswithering)
- [ ] Not Done -- [Davriel, Soul Broker](https://scryfall.com/search?q=!davrielsoulbroker)
- [ ] Not Done -- [Ethereal Grasp](https://scryfall.com/search?q=!etherealgrasp)
- [ ] Not Done -- [Freyalise, Skyshroud Partisan](https://scryfall.com/search?q=!freyaliseskyshroudpartisan)
- [ ] Not Done -- [Kiora, the Tide's Fury](https://scryfall.com/search?q=!kiorathetidesfury)
- [ ] Not Done -- [Leonin Sanctifier](https://scryfall.com/search?q=!leoninsanctifier)
- [ ] Not Done -- [Longtusk Staker](https://scryfall.com/search?q=!longtuskstaker)
- [ ] Not Done -- [Lumbering Lightshield](https://scryfall.com/search?q=!lumberinglightshield)
- [ ] Not Done -- [Managorger Phoenix](https://scryfall.com/search?q=!managorgerphoenix)
- [ ] Not Done -- [Mentor of Evos Isle](https://scryfall.com/search?q=!mentorofevosisle)
- [ ] Not Done -- [Plaguecrafter's Familiar](https://scryfall.com/search?q=!plaguecraftersfamiliar)
- [ ] Not Done -- [Pool of Vigorous Growth](https://scryfall.com/search?q=!poolofvigorousgrowth)
- [ ] Not Done -- [Reckless Ringleader](https://scryfall.com/search?q=!recklessringleader)
- [ ] Not Done -- [Sarkhan's Scorn](https://scryfall.com/search?q=!sarkhansscorn)
- [ ] Not Done -- [Sarkhan, Wanderer to Shiv](https://scryfall.com/search?q=!sarkhanwanderertoshiv)
- [ ] Not Done -- [Scion of Shiv](https://scryfall.com/search?q=!scionofshiv)
- [ ] Not Done -- [Shoreline Scout](https://scryfall.com/search?q=!shorelinescout)
- [ ] Not Done -- [Skyshroud Ambush](https://scryfall.com/search?q=!skyshroudambush)
- [ ] Not Done -- [Static Discharge](https://scryfall.com/search?q=!staticdischarge)
- [ ] Not Done -- [Subversive Acolyte](https://scryfall.com/search?q=!subversiveacolyte)
- [ ] Not Done -- [Teyo, Aegis Adept](https://scryfall.com/search?q=!teyoaegisadept)
- [ ] Not Done -- [Tome of the Infinite](https://scryfall.com/search?q=!tomeoftheinfinite)
- [ ] Not Done -- [Veteran Charger](https://scryfall.com/search?q=!veterancharger)
- [ ] Not Done -- [Wingsteed Trainer](https://scryfall.com/search?q=!wingsteedtrainer)
# Implemented Cards

- [x] Done -- [Bounty of the Deep](https://scryfall.com/search?q=!bountyofthedeep)
- [x] Done -- [Faceless Agent](https://scryfall.com/search?q=!facelessagent)
- [x] Done -- [Manor Guardian](https://scryfall.com/search?q=!manorguardian)
- [x] Done -- [Skyshroud Lookout](https://scryfall.com/search?q=!skyshroudlookout)

**Comment by theelk801** [comment]
- [ ] In progress -- [Baffling Defenses](https://scryfall.com/search?q=!bafflingdefenses)
- [ ] In progress -- [Benalish Partisan](https://scryfall.com/search?q=!benalishpartisan)
- [ ] In progress -- [Boneyard Aberration](https://scryfall.com/search?q=!boneyardaberration)
- [ ] In progress -- [Davriel's Withering](https://scryfall.com/search?q=!davrielswithering)
- [ ] In progress -- [Davriel, Soul Broker](https://scryfall.com/search?q=!davrielsoulbroker)
- [ ] In progress -- [Ethereal Grasp](https://scryfall.com/search?q=!etherealgrasp)
- [ ] In progress -- [Freyalise, Skyshroud Partisan](https://scryfall.com/search?q=!freyaliseskyshroudpartisan)
- [ ] In progress -- [Kiora, the Tide's Fury](https://scryfall.com/search?q=!kiorathetidesfury)
- [ ] In progress -- [Leonin Sanctifier](https://scryfall.com/search?q=!leoninsanctifier)
- [ ] In progress -- [Longtusk Staker](https://scryfall.com/search?q=!longtuskstaker)
- [ ] In progress -- [Lumbering Lightshield](https://scryfall.com/search?q=!lumberinglightshield)
- [ ] In progress -- [Managorger Phoenix](https://scryfall.com/search?q=!managorgerphoenix)
- [ ] In progress -- [Mentor of Evos Isle](https://scryfall.com/search?q=!mentorofevosisle)
- [ ] In progress -- [Plaguecrafter's Familiar](https://scryfall.com/search?q=!plaguecraftersfamiliar)
- [ ] In progress -- [Pool of Vigorous Growth](https://scryfall.com/search?q=!poolofvigorousgrowth)
- [ ] In progress -- [Reckless Ringleader](https://scryfall.com/search?q=!recklessringleader)
- [ ] In progress -- [Sarkhan's Scorn](https://scryfall.com/search?q=!sarkhansscorn)
- [ ] In progress -- [Sarkhan, Wanderer to Shiv](https://scryfall.com/search?q=!sarkhanwanderertoshiv)
- [ ] In progress -- [Scion of Shiv](https://scryfall.com/search?q=!scionofshiv)
- [ ] In progress -- [Shoreline Scout](https://scryfall.com/search?q=!shorelinescout)
- [ ] In progress -- [Skyshroud Ambush](https://scryfall.com/search?q=!skyshroudambush)
- [ ] In progress -- [Static Discharge](https://scryfall.com/search?q=!staticdischarge)
- [ ] In progress -- [Subversive Acolyte](https://scryfall.com/search?q=!subversiveacolyte)
- [ ] In progress -- [Teyo, Aegis Adept](https://scryfall.com/search?q=!teyoaegisadept)
- [ ] In progress -- [Tome of the Infinite](https://scryfall.com/search?q=!tomeoftheinfinite)
- [ ] In progress -- [Veteran Charger](https://scryfall.com/search?q=!veterancharger)
- [ ] In progress -- [Wingsteed Trainer](https://scryfall.com/search?q=!wingsteedtrainer)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"bafflingdefenses"or!"benalishpartisan"or!"boneyardaberration"or!"davrielswithering"or!"davrielsoulbroker"or!"etherealgrasp"or!"freyaliseskyshroudpartisan"or!"kiorathetidesfury"or!"leoninsanctifier"or!"longtuskstaker"or!"lumberinglightshield"or!"managorgerphoenix"or!"mentorofevosisle"or!"plaguecraftersfamiliar"or!"poolofvigorousgrowth"or!"recklessringleader"or!"sarkhansscorn"or!"sarkhanwanderertoshiv"or!"scionofshiv"or!"shorelinescout"or!"skyshroudambush"or!"staticdischarge"or!"subversiveacolyte"or!"teyoaegisadept"or!"tomeoftheinfinite"or!"veterancharger"or!"wingsteedtrainer"&unique=cards)

**Comment by theelk801** [comment]
Additional tasks:

- [ ] Implement "perpetual" mechanic
- [x] Implement "seek" mechanic
- [ ] Implemented "conjure" mechanic

**Comment by alexander-novo** [comment]
Out of curiosity, how will this affect eternal formats available on xMage? I'm just assuming they won't be available under normal commander but what about freeform/freeform unlimited?

**Comment by theelk801** [comment]
I don't see why they wouldn't be in freeform.

**Comment by karapuzz14** [comment]
Working on [Pool of Vigorous Growth](https://scryfall.com/card/j21/28/pool-of-vigorous-growth).

**Comment by muz** [comment]
# Unimplemented Cards

- [ ] In progress -- [Baffling Defenses](https://scryfall.com/search?q=!"BafflingDefenses"&nbsp;e:J21)
- [ ] In progress -- [Benalish Partisan](https://scryfall.com/search?q=!"BenalishPartisan"&nbsp;e:J21)
- [ ] In progress -- [Davriel, Soul Broker](https://scryfall.com/search?q=!"Davriel,SoulBroker"&nbsp;e:J21)
- [ ] In progress -- [Davriel's Withering](https://scryfall.com/search?q=!"Davriel'sWithering"&nbsp;e:J21)
- [ ] In progress -- [Ethereal Grasp](https://scryfall.com/search?q=!"EtherealGrasp"&nbsp;e:J21)
- [ ] In progress -- [Freyalise, Skyshroud Partisan](https://scryfall.com/search?q=!"Freyalise,SkyshroudPartisan"&nbsp;e:J21)
- [ ] In progress -- [Leonin Sanctifier](https://scryfall.com/search?q=!"LeoninSanctifier"&nbsp;e:J21)
- [ ] In progress -- [Longtusk Stalker](https://scryfall.com/search?q=!"LongtuskStalker"&nbsp;e:J21)
- [ ] In progress -- [Lumbering Lightshield](https://scryfall.com/search?q=!"LumberingLightshield"&nbsp;e:J21)
- [ ] In progress -- [Managorger Phoenix](https://scryfall.com/search?q=!"ManagorgerPhoenix"&nbsp;e:J21)
- [ ] In progress -- [Mentor of Evos Isle](https://scryfall.com/search?q=!"MentorofEvosIsle"&nbsp;e:J21)
- [ ] In progress -- [Plaguecrafter's Familiar](https://scryfall.com/search?q=!"Plaguecrafter'sFamiliar"&nbsp;e:J21)
- [ ] In progress -- [Pool of Vigorous Growth](https://scryfall.com/search?q=!"PoolofVigorousGrowth"&nbsp;e:J21)
- [ ] In progress -- [Reckless Ringleader](https://scryfall.com/search?q=!"RecklessRingleader"&nbsp;e:J21)
- [ ] In progress -- [Sarkhan, Wanderer to Shiv](https://scryfall.com/search?q=!"Sarkhan,WanderertoShiv"&nbsp;e:J21)
- [ ] In progress -- [Scion of Shiv](https://scryfall.com/search?q=!"ScionofShiv"&nbsp;e:J21)
- [x] In progress -- [Skyshroud Ambush](https://scryfall.com/search?q=!"SkyshroudAmbush"&nbsp;e:J21)
- [ ] In progress -- [Static Discharge](https://scryfall.com/search?q=!"StaticDischarge"&nbsp;e:J21)
- [ ] In progress -- [Teyo, Aegis Adept](https://scryfall.com/search?q=!"Teyo,AegisAdept"&nbsp;e:J21)
- [ ] In progress -- [Tome of the Infinite](https://scryfall.com/search?q=!"TomeoftheInfinite"&nbsp;e:J21)
- [ ] In progress -- [Veteran Charger](https://scryfall.com/search?q=!"VeteranCharger"&nbsp;e:J21)
