### ISSUE TITLE
MIC - Midnight Hunt Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8197]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] Not Done -- [Curse of Obsession](https://scryfall.com/search?q=!curseofobsession)
- [ ] Not Done -- [Leinore, Autumn Sovereign](https://scryfall.com/search?q=!leinoreautumnsovereign)
- [ ] Not Done -- [Visions of Dominance](https://scryfall.com/search?q=!visionsofdominance)
- [ ] Not Done -- [Visions of Dread](https://scryfall.com/search?q=!visionsofdread)
- [ ] Not Done -- [Visions of Duplicity](https://scryfall.com/search?q=!visionsofduplicity)
- [ ] Not Done -- [Visions of Glory](https://scryfall.com/search?q=!visionsofglory)
- [ ] Not Done -- [Visions of Ruin](https://scryfall.com/search?q=!visionsofruin)
- [ ] Not Done -- [Wilhelt, the Rotcleaver](https://scryfall.com/search?q=!wilhelttherotcleaver)
# Implemented Cards

- [x] Done -- [Avacyn's Memorial](https://scryfall.com/search?q=!avacynsmemorial)

**Comment by theelk801** [comment]
- [ ] In progress -- [Curse of Obsession](https://scryfall.com/search?q=!curseofobsession)
- [ ] In progress -- [Leinore, Autumn Sovereign](https://scryfall.com/search?q=!leinoreautumnsovereign)
- [ ] In progress -- [Visions of Dominance](https://scryfall.com/search?q=!visionsofdominance)
- [ ] In progress -- [Visions of Dread](https://scryfall.com/search?q=!visionsofdread)
- [ ] In progress -- [Visions of Duplicity](https://scryfall.com/search?q=!visionsofduplicity)
- [ ] In progress -- [Visions of Glory](https://scryfall.com/search?q=!visionsofglory)
- [ ] In progress -- [Visions of Ruin](https://scryfall.com/search?q=!visionsofruin)
- [ ] In progress -- [Wilhelt, the Rotcleaver](https://scryfall.com/search?q=!wilhelttherotcleaver)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"curseofobsession"or!"leinoreautumnsovereign"or!"visionsofdominance"or!"visionsofdread"or!"visionsofduplicity"or!"visionsofglory"or!"visionsofruin"or!"wilhelttherotcleaver"&unique=cards)

**Comment by theelk801** [comment]
Additional tasks:

None yet
