### ISSUE TITLE
VOW - Innistrad: Crimson Vow Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8409]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abrade](https://scryfall.com/search?q=!abrade)
- [x] Done -- [Adamant Will](https://scryfall.com/search?q=!adamantwill)
- [x] Done -- [Aim for the Head](https://scryfall.com/search?q=!aimforthehead)
- [x] Done -- [Alchemist's Gambit](https://scryfall.com/search?q=!alchemistsgambit)
- [x] Done -- [Alchemist's Retrieval](https://scryfall.com/search?q=!alchemistsretrieval)
- [x] Done -- [Alluring Suitor](https://scryfall.com/search?q=!alluringsuitor)
- [x] Done -- [Ancestor's Embrace](https://scryfall.com/search?q=!ancestorsembrace)
- [x] Done -- [Ancestral Anger](https://scryfall.com/search?q=!ancestralanger)
- [x] Done -- [Ancient Lumberknot](https://scryfall.com/search?q=!ancientlumberknot)
- [x] Done -- [Angelic Quartermaster](https://scryfall.com/search?q=!angelicquartermaster)
- [x] Done -- [Anje, Maid of Dishonor](https://scryfall.com/search?q=!anjemaidofdishonor)
- [x] Done -- [Apprentice Sharpshooter](https://scryfall.com/search?q=!apprenticesharpshooter)
- [x] Done -- [Archghoul of Thraben](https://scryfall.com/search?q=!archghoulofthraben)
- [x] Done -- [Arm the Cathars](https://scryfall.com/search?q=!armthecathars)
- [x] Done -- [Ascendant Packleader](https://scryfall.com/search?q=!ascendantpackleader)
- [x] Done -- [Avabruck Caretaker](https://scryfall.com/search?q=!avabruckcaretaker)
- [x] Done -- [Ballista Watcher](https://scryfall.com/search?q=!ballistawatcher)
- [x] Done -- [Ballista Wielder](https://scryfall.com/search?q=!ballistawielder)
- [x] Done -- [Belligerent Guest](https://scryfall.com/search?q=!belligerentguest)
- [x] Done -- [Binding Geist](https://scryfall.com/search?q=!bindinggeist)
- [x] Done -- [Biolume Egg](https://scryfall.com/search?q=!biolumeegg)
- [x] Done -- [Biolume Serpent](https://scryfall.com/search?q=!biolumeserpent)
- [x] Done -- [Bleed Dry](https://scryfall.com/search?q=!bleeddry)
- [x] Done -- [Blood Fountain](https://scryfall.com/search?q=!bloodfountain)
- [x] Done -- [Blood Hypnotist](https://scryfall.com/search?q=!bloodhypnotist)
- [x] Done -- [Blood Petal Celebrant](https://scryfall.com/search?q=!bloodpetalcelebrant)
- [x] Done -- [Blood Servitor](https://scryfall.com/search?q=!bloodservitor)
- [x] Done -- [Bloodbat Summoner](https://scryfall.com/search?q=!bloodbatsummoner)
- [x] Done -- [Bloodcrazed Socialite](https://scryfall.com/search?q=!bloodcrazedsocialite)
- [x] Done -- [Bloodsoaked Reveler](https://scryfall.com/search?q=!bloodsoakedreveler)
- [x] Done -- [Bloodsworn Knight](https://scryfall.com/search?q=!bloodswornknight)
- [x] Done -- [Bloodsworn Squire](https://scryfall.com/search?q=!bloodswornsquire)
- [x] Done -- [Bloodtithe Harvester](https://scryfall.com/search?q=!bloodtitheharvester)
- [x] Done -- [Bloodvial Purveyor](https://scryfall.com/search?q=!bloodvialpurveyor)
- [x] Done -- [Bloody Betrayal](https://scryfall.com/search?q=!bloodybetrayal)
- [x] Done -- [Blossom-Clad Werewolf](https://scryfall.com/search?q=!blossomcladwerewolf)
- [x] Done -- [Boarded Window](https://scryfall.com/search?q=!boardedwindow)
- [x] Done -- [Bramble Armor](https://scryfall.com/search?q=!bramblearmor)
- [x] Done -- [Bramble Wurm](https://scryfall.com/search?q=!bramblewurm)
- [x] Done -- [Bride's Gown](https://scryfall.com/search?q=!bridesgown)
- [x] Done -- [Brine Comber](https://scryfall.com/search?q=!brinecomber)
- [x] Done -- [Brinebound Gift](https://scryfall.com/search?q=!brineboundgift)
- [x] Done -- [By Invitation Only](https://scryfall.com/search?q=!byinvitationonly)
- [x] Done -- [Cackling Culprit](https://scryfall.com/search?q=!cacklingculprit)
- [x] Done -- [Cartographer's Survey](https://scryfall.com/search?q=!cartographerssurvey)
- [x] Done -- [Catapult Captain](https://scryfall.com/search?q=!catapultcaptain)
- [x] Done -- [Catapult Fodder](https://scryfall.com/search?q=!catapultfodder)
- [x] Done -- [Catlike Curiosity](https://scryfall.com/search?q=!catlikecuriosity)
- [x] Done -- [Cemetery Desecrator](https://scryfall.com/search?q=!cemeterydesecrator)
- [x] Done -- [Cemetery Gatekeeper](https://scryfall.com/search?q=!cemeterygatekeeper)
- [x] Done -- [Cemetery Illuminator](https://scryfall.com/search?q=!cemeteryilluminator)
- [x] Done -- [Cemetery Protector](https://scryfall.com/search?q=!cemeteryprotector)
- [x] Done -- [Cemetery Prowler](https://scryfall.com/search?q=!cemeteryprowler)
- [x] Done -- [Ceremonial Knife](https://scryfall.com/search?q=!ceremonialknife)
- [x] Done -- [Chandra, Dressed to Kill](https://scryfall.com/search?q=!chandradressedtokill)
- [x] Done -- [Change of Fortune](https://scryfall.com/search?q=!changeoffortune)
- [x] Done -- [Child of the Pack](https://scryfall.com/search?q=!childofthepack)
- [x] Done -- [Chill of the Grave](https://scryfall.com/search?q=!chillofthegrave)
- [x] Done -- [Cipherbound Spirit](https://scryfall.com/search?q=!cipherboundspirit)
- [x] Done -- [Circle of Confinement](https://scryfall.com/search?q=!circleofconfinement)
- [x] Done -- [Clever Distraction](https://scryfall.com/search?q=!cleverdistraction)
- [x] Done -- [Cloaked Cadet](https://scryfall.com/search?q=!cloakedcadet)
- [x] Done -- [Cobbled Lancer](https://scryfall.com/search?q=!cobbledlancer)
- [x] Done -- [Concealing Curtains](https://scryfall.com/search?q=!concealingcurtains)
- [x] Done -- [Consuming Tide](https://scryfall.com/search?q=!consumingtide)
- [x] Done -- [Courier Bat](https://scryfall.com/search?q=!courierbat)
- [x] Done -- [Cradle of Safety](https://scryfall.com/search?q=!cradleofsafety)
- [x] Done -- [Crawling Infestation](https://scryfall.com/search?q=!crawlinginfestation)
- [x] Done -- [Creepy Puppeteer](https://scryfall.com/search?q=!creepypuppeteer)
- [x] Done -- [Cruel Witness](https://scryfall.com/search?q=!cruelwitness)
- [x] Done -- [Crushing Canopy](https://scryfall.com/search?q=!crushingcanopy)
- [x] Done -- [Cultivator Colossus](https://scryfall.com/search?q=!cultivatorcolossus)
- [x] Done -- [Curse of Hospitality](https://scryfall.com/search?q=!curseofhospitality)
- [x] Done -- [Dawnhart Disciple](https://scryfall.com/search?q=!dawnhartdisciple)
- [x] Done -- [Dawnhart Geist](https://scryfall.com/search?q=!dawnhartgeist)
- [x] Done -- [Daybreak Combatants](https://scryfall.com/search?q=!daybreakcombatants)
- [x] Done -- [Deadly Dancer](https://scryfall.com/search?q=!deadlydancer)
- [x] Done -- [Deathcap Glade](https://scryfall.com/search?q=!deathcapglade)
- [x] Done -- [Demonic Bargain](https://scryfall.com/search?q=!demonicbargain)
- [x] Done -- [Depraved Harvester](https://scryfall.com/search?q=!depravedharvester)
- [x] Done -- [Desperate Farmer](https://scryfall.com/search?q=!desperatefarmer)
- [x] Done -- [Dig Up](https://scryfall.com/search?q=!digup)
- [x] Done -- [Dire-Strain Anarchist](https://scryfall.com/search?q=!direstrainanarchist)
- [x] Done -- [Diregraf Scavenger](https://scryfall.com/search?q=!diregrafscavenger)
- [x] Done -- [Distracting Geist](https://scryfall.com/search?q=!distractinggeist)
- [x] Done -- [Diver Skaab](https://scryfall.com/search?q=!diverskaab)
- [x] Done -- [Dollhouse of Horrors](https://scryfall.com/search?q=!dollhouseofhorrors)
- [x] Done -- [Dominating Vampire](https://scryfall.com/search?q=!dominatingvampire)
- [x] Done -- [Doomed Dissenter](https://scryfall.com/search?q=!doomeddissenter)
- [x] Done -- [Dormant Grove](https://scryfall.com/search?q=!dormantgrove)
- [x] Done -- [Dorothea's Retribution](https://scryfall.com/search?q=!dorotheasretribution)
- [x] Done -- [Dorothea, Vengeful Victim](https://scryfall.com/search?q=!dorotheavengefulvictim)
- [x] Done -- [Dread Fugue](https://scryfall.com/search?q=!dreadfugue)
- [x] Done -- [Dreadfeast Demon](https://scryfall.com/search?q=!dreadfeastdemon)
- [x] Done -- [Dreadlight Monstrosity](https://scryfall.com/search?q=!dreadlightmonstrosity)
- [x] Done -- [Dreamroot Cascade](https://scryfall.com/search?q=!dreamrootcascade)
- [x] Done -- [Dreamshackle Geist](https://scryfall.com/search?q=!dreamshacklegeist)
- [x] Done -- [Drogskol Armaments](https://scryfall.com/search?q=!drogskolarmaments)
- [x] Done -- [Drogskol Infantry](https://scryfall.com/search?q=!drogskolinfantry)
- [x] Done -- [Dying to Serve](https://scryfall.com/search?q=!dyingtoserve)
- [x] Done -- [Edgar Markov's Coffin](https://scryfall.com/search?q=!edgarmarkovscoffin)
- [x] Done -- [Edgar's Awakening](https://scryfall.com/search?q=!edgarsawakening)
- [x] Done -- [Edgar, Charmed Groom](https://scryfall.com/search?q=!edgarcharmedgroom)
- [x] Done -- [End the Festivities](https://scryfall.com/search?q=!endthefestivities)
- [x] Done -- [Eruth, Tormented Prophet](https://scryfall.com/search?q=!eruthtormentedprophet)
- [x] Done -- [Estwald Shieldbasher](https://scryfall.com/search?q=!estwaldshieldbasher)
- [x] Done -- [Evolving Wilds](https://scryfall.com/search?q=!evolvingwilds)
- [x] Done -- [Faithbound Judge](https://scryfall.com/search?q=!faithboundjudge)
- [x] Done -- [Falkenrath Celebrants](https://scryfall.com/search?q=!falkenrathcelebrants)
- [x] Done -- [Falkenrath Forebear](https://scryfall.com/search?q=!falkenrathforebear)
- [x] Done -- [Fear of Death](https://scryfall.com/search?q=!fearofdeath)
- [x] Done -- [Fearful Villager](https://scryfall.com/search?q=!fearfulvillager)
- [x] Done -- [Fearsome Werewolf](https://scryfall.com/search?q=!fearsomewerewolf)
- [x] Done -- [Fell Stinger](https://scryfall.com/search?q=!fellstinger)
- [x] Done -- [Fierce Retribution](https://scryfall.com/search?q=!fierceretribution)
- [x] Done -- [Flame-Blessed Bolt](https://scryfall.com/search?q=!flameblessedbolt)
- [x] Done -- [Fleeting Spirit](https://scryfall.com/search?q=!fleetingspirit)
- [x] Done -- [Flourishing Hunter](https://scryfall.com/search?q=!flourishinghunter)
- [x] Done -- [Foreboding Statue](https://scryfall.com/search?q=!forebodingstatue)
- [x] Done -- [Forsaken Thresher](https://scryfall.com/search?q=!forsakenthresher)
- [x] Done -- [Frenzied Devils](https://scryfall.com/search?q=!frenzieddevils)
- [x] Done -- [Geistlight Snare](https://scryfall.com/search?q=!geistlightsnare)
- [x] Done -- [Geralf, Visionary Stitcher](https://scryfall.com/search?q=!geralfvisionarystitcher)
- [x] Done -- [Ghastly Mimicry](https://scryfall.com/search?q=!ghastlymimicry)
- [x] Done -- [Gift of Fangs](https://scryfall.com/search?q=!giftoffangs)
- [x] Done -- [Glorious Sunrise](https://scryfall.com/search?q=!glorioussunrise)
- [x] Done -- [Gluttonous Guest](https://scryfall.com/search?q=!gluttonousguest)
- [x] Done -- [Gnarled Grovestrider](https://scryfall.com/search?q=!gnarledgrovestrider)
- [x] Done -- [Graf Reaver](https://scryfall.com/search?q=!grafreaver)
- [x] Done -- [Grisly Ritual](https://scryfall.com/search?q=!grislyritual)
- [x] Done -- [Grolnok, the Omnivore](https://scryfall.com/search?q=!grolnoktheomnivore)
- [x] Done -- [Groom's Finery](https://scryfall.com/search?q=!groomsfinery)
- [x] Done -- [Gryff Rider](https://scryfall.com/search?q=!gryffrider)
- [x] Done -- [Gryffwing Cavalry](https://scryfall.com/search?q=!gryffwingcavalry)
- [x] Done -- [Gutter Shortcut](https://scryfall.com/search?q=!guttershortcut)
- [x] Done -- [Gutter Skulker](https://scryfall.com/search?q=!gutterskulker)
- [x] Done -- [Halana and Alena, Partners](https://scryfall.com/search?q=!halanaandalenapartners)
- [x] Done -- [Hallowed Haunting](https://scryfall.com/search?q=!hallowedhaunting)
- [x] Done -- [Hamlet Vanguard](https://scryfall.com/search?q=!hamletvanguard)
- [x] Done -- [Hauken's Insight](https://scryfall.com/search?q=!haukensinsight)
- [x] Done -- [Headless Rider](https://scryfall.com/search?q=!headlessrider)
- [x] Done -- [Henrika Domnathi](https://scryfall.com/search?q=!henrikadomnathi)
- [x] Done -- [Henrika, Infernal Seer](https://scryfall.com/search?q=!henrikainfernalseer)
- [x] Done -- [Hero's Downfall](https://scryfall.com/search?q=!herosdownfall)
- [x] Done -- [Heron of Hope](https://scryfall.com/search?q=!heronofhope)
- [x] Done -- [Heron-Blessed Geist](https://scryfall.com/search?q=!heronblessedgeist)
- [x] Done -- [Hiveheart Shaman](https://scryfall.com/search?q=!hiveheartshaman)
- [x] Done -- [Hollowhenge Huntmaster](https://scryfall.com/search?q=!hollowhengehuntmaster)
- [x] Done -- [Honeymoon Hearse](https://scryfall.com/search?q=!honeymoonhearse)
- [x] Done -- [Honored Heirloom](https://scryfall.com/search?q=!honoredheirloom)
- [x] Done -- [Hookhand Mariner](https://scryfall.com/search?q=!hookhandmariner)
- [x] Done -- [Hopeful Initiate](https://scryfall.com/search?q=!hopefulinitiate)
- [x] Done -- [Howling Moon](https://scryfall.com/search?q=!howlingmoon)
- [x] Done -- [Howlpack Avenger](https://scryfall.com/search?q=!howlpackavenger)
- [x] Done -- [Howlpack Piper](https://scryfall.com/search?q=!howlpackpiper)
- [x] Done -- [Hullbreaker Horror](https://scryfall.com/search?q=!hullbreakerhorror)
- [x] Done -- [Hungry Ridgewolf](https://scryfall.com/search?q=!hungryridgewolf)
- [x] Done -- [Ill-Tempered Loner](https://scryfall.com/search?q=!illtemperedloner)
- [x] Done -- [Infestation Expert](https://scryfall.com/search?q=!infestationexpert)
- [x] Done -- [Infested Werewolf](https://scryfall.com/search?q=!infestedwerewolf)
- [x] Done -- [Innocent Traveler](https://scryfall.com/search?q=!innocenttraveler)
- [x] Done -- [Inspired Idea](https://scryfall.com/search?q=!inspiredidea)
- [x] Done -- [Into the Night](https://scryfall.com/search?q=!intothenight)
- [x] Done -- [Investigator's Journal](https://scryfall.com/search?q=!investigatorsjournal)
- [x] Done -- [Jacob Hauken, Inspector](https://scryfall.com/search?q=!jacobhaukeninspector)
- [x] Done -- [Katilda's Rising Dawn](https://scryfall.com/search?q=!katildasrisingdawn)
- [x] Done -- [Katilda, Dawnhart Martyr](https://scryfall.com/search?q=!katildadawnhartmartyr)
- [x] Done -- [Kaya, Geist Hunter](https://scryfall.com/search?q=!kayageisthunter)
- [x] Done -- [Kessig Flamebreather](https://scryfall.com/search?q=!kessigflamebreather)
- [x] Done -- [Kessig Wolfrider](https://scryfall.com/search?q=!kessigwolfrider)
- [x] Done -- [Kindly Ancestor](https://scryfall.com/search?q=!kindlyancestor)
- [x] Done -- [Krothuss, Lord of the Deep](https://scryfall.com/search?q=!krothusslordofthedeep)
- [x] Done -- [Lacerate Flesh](https://scryfall.com/search?q=!lacerateflesh)
- [x] Done -- [Laid to Rest](https://scryfall.com/search?q=!laidtorest)
- [x] Done -- [Lambholt Raconteur](https://scryfall.com/search?q=!lambholtraconteur)
- [x] Done -- [Lambholt Ravager](https://scryfall.com/search?q=!lambholtravager)
- [x] Done -- [Lantern Bearer](https://scryfall.com/search?q=!lanternbearer)
- [x] Done -- [Lantern Flare](https://scryfall.com/search?q=!lanternflare)
- [x] Done -- [Lantern of the Lost](https://scryfall.com/search?q=!lanternofthelost)
- [x] Done -- [Lanterns' Lift](https://scryfall.com/search?q=!lanternslift)
- [x] Done -- [Lightning Wolf](https://scryfall.com/search?q=!lightningwolf)
- [x] Done -- [Lunar Rejection](https://scryfall.com/search?q=!lunarrejection)
- [x] Done -- [Magma Pummeler](https://scryfall.com/search?q=!magmapummeler)
- [x] Done -- [Malicious Invader](https://scryfall.com/search?q=!maliciousinvader)
- [x] Done -- [Manaform Hellkite](https://scryfall.com/search?q=!manaformhellkite)
- [x] Done -- [Markov Purifier](https://scryfall.com/search?q=!markovpurifier)
- [x] Done -- [Markov Retribution](https://scryfall.com/search?q=!markovretribution)
- [x] Done -- [Markov Waltzer](https://scryfall.com/search?q=!markovwaltzer)
- [x] Done -- [Massive Might](https://scryfall.com/search?q=!massivemight)
- [x] Done -- [Militia Rallier](https://scryfall.com/search?q=!militiarallier)
- [x] Done -- [Mindleech Ghoul](https://scryfall.com/search?q=!mindleechghoul)
- [x] Done -- [Mirrorhall Mimic](https://scryfall.com/search?q=!mirrorhallmimic)
- [x] Done -- [Mischievous Catgeist](https://scryfall.com/search?q=!mischievouscatgeist)
- [x] Done -- [Moldgraf Millipede](https://scryfall.com/search?q=!moldgrafmillipede)
- [x] Done -- [Moonlit Ambusher](https://scryfall.com/search?q=!moonlitambusher)
- [x] Done -- [Mulch](https://scryfall.com/search?q=!mulch)
- [x] Done -- [Nature's Embrace](https://scryfall.com/search?q=!naturesembrace)
- [x] Done -- [Nebelgast Beguiler](https://scryfall.com/search?q=!nebelgastbeguiler)
- [x] Done -- [Necroduality](https://scryfall.com/search?q=!necroduality)
- [x] Done -- [Nurturing Presence](https://scryfall.com/search?q=!nurturingpresence)
- [x] Done -- [Oakshade Stalker](https://scryfall.com/search?q=!oakshadestalker)
- [x] Done -- [Odious Witch](https://scryfall.com/search?q=!odiouswitch)
- [x] Done -- [Odric, Blood-Cursed](https://scryfall.com/search?q=!odricbloodcursed)
- [x] Done -- [Old Rutstein](https://scryfall.com/search?q=!oldrutstein)
- [x] Done -- [Olivia's Attendants](https://scryfall.com/search?q=!oliviasattendants)
- [x] Done -- [Olivia, Crimson Bride](https://scryfall.com/search?q=!oliviacrimsonbride)
- [x] Done -- [Ollenbock Escort](https://scryfall.com/search?q=!ollenbockescort)
- [x] Done -- [Overcharged Amalgam](https://scryfall.com/search?q=!overchargedamalgam)
- [x] Done -- [Packsong Pup](https://scryfall.com/search?q=!packsongpup)
- [x] Done -- [Panicked Bystander](https://scryfall.com/search?q=!panickedbystander)
- [x] Done -- [Parasitic Grasp](https://scryfall.com/search?q=!parasiticgrasp)
- [x] Done -- [Parish-Blade Trainee](https://scryfall.com/search?q=!parishbladetrainee)
- [x] Done -- [Patchwork Crawler](https://scryfall.com/search?q=!patchworkcrawler)
- [x] Done -- [Path of Peril](https://scryfall.com/search?q=!pathofperil)
- [x] Done -- [Persistent Specimen](https://scryfall.com/search?q=!persistentspecimen)
- [x] Done -- [Piercing Light](https://scryfall.com/search?q=!piercinglight)
- [x] Done -- [Pointed Discussion](https://scryfall.com/search?q=!pointeddiscussion)
- [x] Done -- [Pyre Spawn](https://scryfall.com/search?q=!pyrespawn)
- [x] Done -- [Radiant Grace](https://scryfall.com/search?q=!radiantgrace)
- [x] Done -- [Radiant Restraints](https://scryfall.com/search?q=!radiantrestraints)
- [x] Done -- [Ragged Recluse](https://scryfall.com/search?q=!raggedrecluse)
- [x] Done -- [Reckless Impulse](https://scryfall.com/search?q=!recklessimpulse)
- [x] Done -- [Reclusive Taxidermist](https://scryfall.com/search?q=!reclusivetaxidermist)
- [x] Done -- [Rending Flame](https://scryfall.com/search?q=!rendingflame)
- [x] Done -- [Repository Skaab](https://scryfall.com/search?q=!repositoryskaab)
- [x] Done -- [Resistance Squad](https://scryfall.com/search?q=!resistancesquad)
- [x] Done -- [Restless Bloodseeker](https://scryfall.com/search?q=!restlessbloodseeker)
- [x] Done -- [Retrieve](https://scryfall.com/search?q=!retrieve)
- [x] Done -- [Revealing Eye](https://scryfall.com/search?q=!revealingeye)
- [x] Done -- [Riphook Raider](https://scryfall.com/search?q=!riphookraider)
- [x] Done -- [Rot-Tide Gargantua](https://scryfall.com/search?q=!rottidegargantua)
- [x] Done -- [Runebound Wolf](https://scryfall.com/search?q=!runeboundwolf)
- [x] Done -- [Runo Stromkirk](https://scryfall.com/search?q=!runostromkirk)
- [x] Done -- [Rural Recruit](https://scryfall.com/search?q=!ruralrecruit)
- [x] Done -- [Sanctify](https://scryfall.com/search?q=!sanctify)
- [x] Done -- [Sanguine Statuette](https://scryfall.com/search?q=!sanguinestatuette)
- [x] Done -- [Savage Packmate](https://scryfall.com/search?q=!savagepackmate)
- [x] Done -- [Savior of Ollenbock](https://scryfall.com/search?q=!saviorofollenbock)
- [x] Done -- [Sawblade Slinger](https://scryfall.com/search?q=!sawbladeslinger)
- [x] Done -- [Scattered Thoughts](https://scryfall.com/search?q=!scatteredthoughts)
- [x] Done -- [Screaming Swarm](https://scryfall.com/search?q=!screamingswarm)
- [x] Done -- [Selhoff Entomber](https://scryfall.com/search?q=!selhoffentomber)
- [x] Done -- [Serpentine Ambush](https://scryfall.com/search?q=!serpentineambush)
- [x] Done -- [Shattered Sanctum](https://scryfall.com/search?q=!shatteredsanctum)
- [x] Done -- [Sheltering Boughs](https://scryfall.com/search?q=!shelteringboughs)
- [x] Done -- [Sigarda's Imprisonment](https://scryfall.com/search?q=!sigardasimprisonment)
- [x] Done -- [Sigarda's Summons](https://scryfall.com/search?q=!sigardassummons)
- [x] Done -- [Sigardian Paladin](https://scryfall.com/search?q=!sigardianpaladin)
- [x] Done -- [Sinner's Judgment](https://scryfall.com/search?q=!sinnersjudgment)
- [x] Done -- [Skulking Killer](https://scryfall.com/search?q=!skulkingkiller)
- [x] Done -- [Skull Skaab](https://scryfall.com/search?q=!skullskaab)
- [x] Done -- [Skywarp Skaab](https://scryfall.com/search?q=!skywarpskaab)
- [x] Done -- [Snarling Wolf](https://scryfall.com/search?q=!snarlingwolf)
- [x] Done -- [Sorin the Mirthless](https://scryfall.com/search?q=!sorinthemirthless)
- [x] Done -- [Soulcipher Board](https://scryfall.com/search?q=!soulcipherboard)
- [x] Done -- [Spectral Binding](https://scryfall.com/search?q=!spectralbinding)
- [x] Done -- [Spiked Ripsaw](https://scryfall.com/search?q=!spikedripsaw)
- [x] Done -- [Splendid Reclamation](https://scryfall.com/search?q=!splendidreclamation)
- [x] Done -- [Spore Crawler](https://scryfall.com/search?q=!sporecrawler)
- [x] Done -- [Sporeback Wolf](https://scryfall.com/search?q=!sporebackwolf)
- [x] Done -- [Steelclad Spirit](https://scryfall.com/search?q=!steelcladspirit)
- [x] Done -- [Stensia Uprising](https://scryfall.com/search?q=!stensiauprising)
- [x] Done -- [Stitched Assistant](https://scryfall.com/search?q=!stitchedassistant)
- [x] Done -- [Stormcarved Coast](https://scryfall.com/search?q=!stormcarvedcoast)
- [x] Done -- [Stormchaser Drake](https://scryfall.com/search?q=!stormchaserdrake)
- [x] Done -- [Sundown Pass](https://scryfall.com/search?q=!sundownpass)
- [x] Done -- [Supernatural Rescue](https://scryfall.com/search?q=!supernaturalrescue)
- [x] Done -- [Sure Strike](https://scryfall.com/search?q=!surestrike)
- [x] Done -- [Syncopate](https://scryfall.com/search?q=!syncopate)
- [x] Done -- [Syphon Essence](https://scryfall.com/search?q=!syphonessence)
- [x] Done -- [Thalia, Guardian of Thraben](https://scryfall.com/search?q=!thaliaguardianofthraben)
- [x] Done -- [Thirst for Discovery](https://scryfall.com/search?q=!thirstfordiscovery)
- [x] Done -- [Torens, Fist of the Angels](https://scryfall.com/search?q=!torensfistoftheangels)
- [x] Done -- [Toxic Scorpion](https://scryfall.com/search?q=!toxicscorpion)
- [x] Done -- [Toxrill, the Corrosive](https://scryfall.com/search?q=!toxrillthecorrosive)
- [x] Done -- [Traveling Minister](https://scryfall.com/search?q=!travelingminister)
- [x] Done -- [Twinblade Geist](https://scryfall.com/search?q=!twinbladegeist)
- [x] Done -- [Twinblade Invocation](https://scryfall.com/search?q=!twinbladeinvocation)
- [x] Done -- [Ulvenwald Behemoth](https://scryfall.com/search?q=!ulvenwaldbehemoth)
- [x] Done -- [Ulvenwald Oddity](https://scryfall.com/search?q=!ulvenwaldoddity)
- [x] Done -- [Undead Butler](https://scryfall.com/search?q=!undeadbutler)
- [x] Done -- [Undying Malice](https://scryfall.com/search?q=!undyingmalice)
- [x] Done -- [Unhallowed Phalanx](https://scryfall.com/search?q=!unhallowedphalanx)
- [x] Done -- [Unholy Officiant](https://scryfall.com/search?q=!unholyofficiant)
- [x] Done -- [Valorous Stance](https://scryfall.com/search?q=!valorousstance)
- [x] Done -- [Vampire Slayer](https://scryfall.com/search?q=!vampireslayer)
- [x] Done -- [Vampire's Kiss](https://scryfall.com/search?q=!vampireskiss)
- [x] Done -- [Vampires' Vengeance](https://scryfall.com/search?q=!vampiresvengeance)
- [x] Done -- [Vilespawn Spider](https://scryfall.com/search?q=!vilespawnspider)
- [x] Done -- [Voice of the Blessed](https://scryfall.com/search?q=!voiceoftheblessed)
- [x] Done -- [Volatile Arsonist](https://scryfall.com/search?q=!volatilearsonist)
- [x] Done -- [Voldaren Bloodcaster](https://scryfall.com/search?q=!voldarenbloodcaster)
- [x] Done -- [Voldaren Epicure](https://scryfall.com/search?q=!voldarenepicure)
- [x] Done -- [Voldaren Estate](https://scryfall.com/search?q=!voldarenestate)
- [x] Done -- [Volt-Charged Berserker](https://scryfall.com/search?q=!voltchargedberserker)
- [x] Done -- [Voltaic Visionary](https://scryfall.com/search?q=!voltaicvisionary)
- [x] Done -- [Wandering Mind](https://scryfall.com/search?q=!wanderingmind)
- [x] Done -- [Wanderlight Spirit](https://scryfall.com/search?q=!wanderlightspirit)
- [x] Done -- [Wash Away](https://scryfall.com/search?q=!washaway)
- [x] Done -- [Weary Prisoner](https://scryfall.com/search?q=!wearyprisoner)
- [x] Done -- [Weaver of Blossoms](https://scryfall.com/search?q=!weaverofblossoms)
- [x] Done -- [Wedding Announcement](https://scryfall.com/search?q=!weddingannouncement)
- [x] Done -- [Wedding Crasher](https://scryfall.com/search?q=!weddingcrasher)
- [x] Done -- [Wedding Festivity](https://scryfall.com/search?q=!weddingfestivity)
- [x] Done -- [Wedding Invitation](https://scryfall.com/search?q=!weddinginvitation)
- [x] Done -- [Wedding Security](https://scryfall.com/search?q=!weddingsecurity)
- [x] Done -- [Welcoming Vampire](https://scryfall.com/search?q=!welcomingvampire)
- [x] Done -- [Whispering Wizard](https://scryfall.com/search?q=!whisperingwizard)
- [x] Done -- [Wildsong Howler](https://scryfall.com/search?q=!wildsonghowler)
- [x] Done -- [Winged Portent](https://scryfall.com/search?q=!wingedportent)
- [x] Done -- [Witch's Web](https://scryfall.com/search?q=!witchsweb)
- [x] Done -- [Witness the Future](https://scryfall.com/search?q=!witnessthefuture)
- [x] Done -- [Wolf Strike](https://scryfall.com/search?q=!wolfstrike)
- [x] Done -- [Wolfkin Outcast](https://scryfall.com/search?q=!wolfkinoutcast)
- [x] Done -- [Wrathful Jailbreaker](https://scryfall.com/search?q=!wrathfuljailbreaker)
- [x] Done -- [Wretched Throng](https://scryfall.com/search?q=!wretchedthrong)
</details>

**Comment by theelk801** [comment]
that's a wrap, special thanks to @weirddan455 for all the help
