### ISSUE TITLE
VOC - Crimson Vow Commander Set Card Implementation Tracking 

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8410]
This checklist is here to help manage the implementation of Crimson Vow Commander. If a card is marked as being in progress then someone is working on it

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [x] In progress -- [Spectral Arcanist](https://scryfall.com/search?q=!spectralarcanist)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"spectralarcanist"&unique=cards)
# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Ancient Craving](https://scryfall.com/search?q=!ancientcraving)
- [x] Done -- [Angel of Flight Alabaster](https://scryfall.com/search?q=!angelofflightalabaster)
- [x] Done -- [Anje's Ravager](https://scryfall.com/search?q=!anjesravager)
- [x] Done -- [Anowon, the Ruin Sage](https://scryfall.com/search?q=!anowontheruinsage)
- [x] Done -- [Arcane Denial](https://scryfall.com/search?q=!arcanedenial)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Arterial Alchemy](https://scryfall.com/search?q=!arterialalchemy)
- [x] Done -- [Avacyn's Judgment](https://scryfall.com/search?q=!avacynsjudgment)
- [x] Done -- [Azorius Chancery](https://scryfall.com/search?q=!azoriuschancery)
- [x] Done -- [Azorius Locket](https://scryfall.com/search?q=!azoriuslocket)
- [x] Done -- [Azorius Signet](https://scryfall.com/search?q=!azoriussignet)
- [x] Done -- [Benevolent Offering](https://scryfall.com/search?q=!benevolentoffering)
- [x] Done -- [Blasphemous Act](https://scryfall.com/search?q=!blasphemousact)
- [x] Done -- [Blood Artist](https://scryfall.com/search?q=!bloodartist)
- [x] Done -- [Bloodline Necromancer](https://scryfall.com/search?q=!bloodlinenecromancer)
- [x] Done -- [Bloodlord of Vaasgoth](https://scryfall.com/search?q=!bloodlordofvaasgoth)
- [x] Done -- [Bloodsworn Steward](https://scryfall.com/search?q=!bloodswornsteward)
- [x] Done -- [Bloodtracker](https://scryfall.com/search?q=!bloodtracker)
- [x] Done -- [Boreas Charger](https://scryfall.com/search?q=!boreascharger)
- [x] Done -- [Breath of the Sleepless](https://scryfall.com/search?q=!breathofthesleepless)
- [x] Done -- [Breathkeeper Seraph](https://scryfall.com/search?q=!breathkeeperseraph)
- [x] Done -- [Butcher of Malakir](https://scryfall.com/search?q=!butcherofmalakir)
- [x] Done -- [Bygone Bishop](https://scryfall.com/search?q=!bygonebishop)
- [x] Done -- [Champion of Dusk](https://scryfall.com/search?q=!championofdusk)
- [x] Done -- [Charcoal Diamond](https://scryfall.com/search?q=!charcoaldiamond)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=!commanderssphere)
- [x] Done -- [Cordial Vampire](https://scryfall.com/search?q=!cordialvampire)
- [x] Done -- [Crimson Honor Guard](https://scryfall.com/search?q=!crimsonhonorguard)
- [x] Done -- [Crossway Troublemakers](https://scryfall.com/search?q=!crosswaytroublemakers)
- [x] Done -- [Crush Contraband](https://scryfall.com/search?q=!crushcontraband)
- [x] Done -- [Custodi Soulbinders](https://scryfall.com/search?q=!custodisoulbinders)
- [x] Done -- [Custodi Squire](https://scryfall.com/search?q=!custodisquire)
- [x] Done -- [Damnable Pact](https://scryfall.com/search?q=!damnablepact)
- [x] Done -- [Dark Impostor](https://scryfall.com/search?q=!darkimpostor)
- [x] Done -- [Darksteel Mutation](https://scryfall.com/search?q=!darksteelmutation)
- [x] Done -- [Disorder in the Court](https://scryfall.com/search?q=!disorderinthecourt)
- [x] Done -- [Distant Melody](https://scryfall.com/search?q=!distantmelody)
- [x] Done -- [Donal, Herald of Wings](https://scryfall.com/search?q=!donalheraldofwings)
- [x] Done -- [Doom Weaver](https://scryfall.com/search?q=!doomweaver)
- [x] Done -- [Dovin, Grand Arbiter](https://scryfall.com/search?q=!dovingrandarbiter)
- [x] Done -- [Drogskol Captain](https://scryfall.com/search?q=!drogskolcaptain)
- [x] Done -- [Drogskol Reinforcements](https://scryfall.com/search?q=!drogskolreinforcements)
- [x] Done -- [Ethereal Investigator](https://scryfall.com/search?q=!etherealinvestigator)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Falkenrath Gorger](https://scryfall.com/search?q=!falkenrathgorger)
- [x] Done -- [Falkenrath Noble](https://scryfall.com/search?q=!falkenrathnoble)
- [x] Done -- [Feed the Swarm](https://scryfall.com/search?q=!feedtheswarm)
- [x] Done -- [Fell the Mighty](https://scryfall.com/search?q=!fellthemighty)
- [x] Done -- [Field of Souls](https://scryfall.com/search?q=!fieldofsouls)
- [x] Done -- [Fire Diamond](https://scryfall.com/search?q=!firediamond)
- [x] Done -- [Flood of Tears](https://scryfall.com/search?q=!floodoftears)
- [x] Done -- [Foreboding Ruins](https://scryfall.com/search?q=!forebodingruins)
- [x] Done -- [Geist of Saint Traft](https://scryfall.com/search?q=!geistofsainttraft)
- [x] Done -- [Ghostly Pilferer](https://scryfall.com/search?q=!ghostlypilferer)
- [x] Done -- [Ghostly Prison](https://scryfall.com/search?q=!ghostlyprison)
- [x] Done -- [Glass-Cast Heart](https://scryfall.com/search?q=!glasscastheart)
- [x] Done -- [Hallowed Spiritkeeper](https://scryfall.com/search?q=!hallowedspiritkeeper)
- [x] Done -- [Hanged Executioner](https://scryfall.com/search?q=!hangedexecutioner)
- [x] Done -- [Haunted Library](https://scryfall.com/search?q=!hauntedlibrary)
- [x] Done -- [Haunting Imitation](https://scryfall.com/search?q=!hauntingimitation)
- [x] Done -- [Hollowhenge Overlord](https://scryfall.com/search?q=!hollowhengeoverlord)
- [x] Done -- [Imperious Mindbreaker](https://scryfall.com/search?q=!imperiousmindbreaker)
- [x] Done -- [Imposing Grandeur](https://scryfall.com/search?q=!imposinggrandeur)
- [x] Done -- [Imprisoned in the Moon](https://scryfall.com/search?q=!imprisonedinthemoon)
- [x] Done -- [Indulgent Aristocrat](https://scryfall.com/search?q=!indulgentaristocrat)
- [x] Done -- [Kamber, the Plunderer](https://scryfall.com/search?q=!kambertheplunderer)
- [x] Done -- [Kami of the Crescent Moon](https://scryfall.com/search?q=!kamiofthecrescentmoon)
- [x] Done -- [Karmic Guide](https://scryfall.com/search?q=!karmicguide)
- [x] Done -- [Kirtar's Wrath](https://scryfall.com/search?q=!kirtarswrath)
- [x] Done -- [Knight of the White Orchid](https://scryfall.com/search?q=!knightofthewhiteorchid)
- [x] Done -- [Laurine, the Diversion](https://scryfall.com/search?q=!laurinethediversion)
- [x] Done -- [Malakir Bloodwitch](https://scryfall.com/search?q=!malakirbloodwitch)
- [x] Done -- [Marble Diamond](https://scryfall.com/search?q=!marblediamond)
- [x] Done -- [Markov Enforcer](https://scryfall.com/search?q=!markovenforcer)
- [x] Done -- [Mentor of the Meek](https://scryfall.com/search?q=!mentorofthemeek)
- [x] Done -- [Midnight Arsonist](https://scryfall.com/search?q=!midnightarsonist)
- [x] Done -- [Midnight Clock](https://scryfall.com/search?q=!midnightclock)
- [x] Done -- [Millicent, Restless Revenant](https://scryfall.com/search?q=!millicentrestlessrevenant)
- [x] Done -- [Mirage Phalanx](https://scryfall.com/search?q=!miragephalanx)
- [x] Done -- [Mirror Entity](https://scryfall.com/search?q=!mirrorentity)
- [x] Done -- [Mob Rule](https://scryfall.com/search?q=!mobrule)
- [x] Done -- [Molten Echoes](https://scryfall.com/search?q=!moltenechoes)
- [x] Done -- [Moorland Haunt](https://scryfall.com/search?q=!moorlandhaunt)
- [x] Done -- [Myriad Landscape](https://scryfall.com/search?q=!myriadlandscape)
- [x] Done -- [Nebelgast Herald](https://scryfall.com/search?q=!nebelgastherald)
- [x] Done -- [Necropolis Regent](https://scryfall.com/search?q=!necropolisregent)
- [x] Done -- [Night's Whisper](https://scryfall.com/search?q=!nightswhisper)
- [x] Done -- [Nirkana Revenant](https://scryfall.com/search?q=!nirkanarevenant)
- [x] Done -- [Occult Epiphany](https://scryfall.com/search?q=!occultepiphany)
- [x] Done -- [Olivia's Wrath](https://scryfall.com/search?q=!oliviaswrath)
- [x] Done -- [Oyobi, Who Split the Heavens](https://scryfall.com/search?q=!oyobiwhosplittheheavens)
- [x] Done -- [Path of Ancestry](https://scryfall.com/search?q=!pathofancestry)
- [x] Done -- [Patron of the Vein](https://scryfall.com/search?q=!patronofthevein)
- [x] Done -- [Port Town](https://scryfall.com/search?q=!porttown)
- [x] Done -- [Prairie Stream](https://scryfall.com/search?q=!prairiestream)
- [x] Done -- [Predators' Hour](https://scryfall.com/search?q=!predatorshour)
- [x] Done -- [Priest of the Blessed Graf](https://scryfall.com/search?q=!priestoftheblessedgraf)
- [x] Done -- [Promise of Bunrei](https://scryfall.com/search?q=!promiseofbunrei)
- [x] Done -- [Rakdos Carnarium](https://scryfall.com/search?q=!rakdoscarnarium)
- [x] Done -- [Rakdos Charm](https://scryfall.com/search?q=!rakdoscharm)
- [x] Done -- [Rakdos Signet](https://scryfall.com/search?q=!rakdossignet)
- [x] Done -- [Rakish Heir](https://scryfall.com/search?q=!rakishheir)
- [x] Done -- [Rattlechains](https://scryfall.com/search?q=!rattlechains)
- [x] Done -- [Reconnaissance Mission](https://scryfall.com/search?q=!reconnaissancemission)
- [x] Done -- [Remorseful Cleric](https://scryfall.com/search?q=!remorsefulcleric)
- [x] Done -- [Rhoda, Geist Avenger](https://scryfall.com/search?q=!rhodageistavenger)
- [x] Done -- [Sanctum Seeker](https://scryfall.com/search?q=!sanctumseeker)
- [x] Done -- [Scion of Opulence](https://scryfall.com/search?q=!scionofopulence)
- [x] Done -- [Shacklegeist](https://scryfall.com/search?q=!shacklegeist)
- [x] Done -- [Shadowblood Ridge](https://scryfall.com/search?q=!shadowbloodridge)
- [x] Done -- [Shadowgrange Archfiend](https://scryfall.com/search?q=!shadowgrangearchfiend)
- [x] Done -- [Sinister Waltz](https://scryfall.com/search?q=!sinisterwaltz)
- [x] Done -- [Sire of the Storm](https://scryfall.com/search?q=!sireofthestorm)
- [x] Done -- [Sky Diamond](https://scryfall.com/search?q=!skydiamond)
- [x] Done -- [Skycloud Expanse](https://scryfall.com/search?q=!skycloudexpanse)
- [x] Done -- [Smoldering Marsh](https://scryfall.com/search?q=!smolderingmarsh)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Spectral Sailor](https://scryfall.com/search?q=!spectralsailor)
- [x] Done -- [Spectral Shepherd](https://scryfall.com/search?q=!spectralshepherd)
- [x] Done -- [Stensia Masquerade](https://scryfall.com/search?q=!stensiamasquerade)
- [x] Done -- [Storm of Souls](https://scryfall.com/search?q=!stormofsouls)
- [x] Done -- [Strefan, Maurer Progenitor](https://scryfall.com/search?q=!strefanmaurerprogenitor)
- [x] Done -- [Stromkirk Captain](https://scryfall.com/search?q=!stromkirkcaptain)
- [x] Done -- [Stromkirk Condemned](https://scryfall.com/search?q=!stromkirkcondemned)
- [x] Done -- [Stromkirk Occultist](https://scryfall.com/search?q=!stromkirkoccultist)
- [x] Done -- [Sudden Salvation](https://scryfall.com/search?q=!suddensalvation)
- [x] Done -- [Supreme Phantom](https://scryfall.com/search?q=!supremephantom)
- [x] Done -- [Swiftfoot Boots](https://scryfall.com/search?q=!swiftfootboots)
- [x] Done -- [Swords to Plowshares](https://scryfall.com/search?q=!swordstoplowshares)
- [x] Done -- [Tainted Peak](https://scryfall.com/search?q=!taintedpeak)
- [x] Done -- [Temple of Enlightenment](https://scryfall.com/search?q=!templeofenlightenment)
- [x] Done -- [Temple of Malice](https://scryfall.com/search?q=!templeofmalice)
- [x] Done -- [Temple of the False God](https://scryfall.com/search?q=!templeofthefalsegod)
- [x] Done -- [Thundering Mightmare](https://scryfall.com/search?q=!thunderingmightmare)
- [x] Done -- [Timin, Youthful Geist](https://scryfall.com/search?q=!timinyouthfulgeist)
- [x] Done -- [Timothar, Baron of Bats](https://scryfall.com/search?q=!timotharbaronofbats)
- [x] Done -- [Twilight Drover](https://scryfall.com/search?q=!twilightdrover)
- [x] Done -- [Umbris, Fear Manifest](https://scryfall.com/search?q=!umbrisfearmanifest)
- [x] Done -- [Unclaimed Territory](https://scryfall.com/search?q=!unclaimedterritory)
- [x] Done -- [Underworld Connections](https://scryfall.com/search?q=!underworldconnections)
- [x] Done -- [Unstable Obelisk](https://scryfall.com/search?q=!unstableobelisk)
- [x] Done -- [Urge to Feed](https://scryfall.com/search?q=!urgetofeed)
- [x] Done -- [Vampire Nighthawk](https://scryfall.com/search?q=!vampirenighthawk)
- [x] Done -- [Vampiric Dragon](https://scryfall.com/search?q=!vampiricdragon)
- [x] Done -- [Vandalblast](https://scryfall.com/search?q=!vandalblast)
- [x] Done -- [Verity Circle](https://scryfall.com/search?q=!veritycircle)
- [x] Done -- [Wedding Ring](https://scryfall.com/search?q=!weddingring)
- [x] Done -- [Windborn Muse](https://scryfall.com/search?q=!windbornmuse)
</details>

**Comment by Alex-Vasile** [comment]
Are cards that are marked as "in progress" on here or on another tracking lists claimed and being worked on by others? Or do they need someone? I'm asking to not double up work.

**Comment by theelk801** [comment]
Yeah, nothing here is marked as in progress so no one has claimed any of it.

**Comment by Alex-Vasile** [comment]
> Yeah, nothing here is marked as in progress so no one has claimed any of it.

Ahh. I was confused by your comment on the issue which has several cards marked as "in progress". I thought that meant you were working on them.

**Comment by theelk801** [comment]
They're all checkboxes but you can't check them off unless you're a member, that's why it says to leave a comment instead.

**Comment by Alex-Vasile** [comment]
Donal, Herald of Wings, Spectral Arcanist, Mirage Phalanx are in progress.

Predator's Hour is done.

And Shadowgrange Archfiend is waiting on someone to review.

**Comment by Alex-Vasile** [comment]
I need #8136 in order to do Spectral Arcanist.

**Comment by CommanderMasterEDH** [comment]
Was Spectral Arcanist ever implemented yet?

It saids this thread is still open
