### ISSUE TITLE
UNF - Unfinity Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8491]
Mark cards you're working on in the second post of this issue.
If you can't check things off, leave a comment instead.
Once the card is committed, check off the card here to show that it's finished.
Don't worry about adding new spoilers to this list, it's generated by a script.
Also, don't worry about text issues as those are usually fixed when the set is done. 

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] Not Done -- [Assembled Ensemble](https://scryfall.com/search?q=!assembledensemble)
- [ ] Not Done -- [Killer Cosplay](https://scryfall.com/search?q=!killercosplay)
- [ ] Not Done -- [Saw in Half](https://scryfall.com/search?q=!sawinhalf)
# Implemented Cards

- [x] Done -- [Blood Crypt](https://scryfall.com/search?q=!bloodcrypt)
- [x] Done -- [Breeding Pool](https://scryfall.com/search?q=!breedingpool)
- [x] Done -- [Godless Shrine](https://scryfall.com/search?q=!godlessshrine)
- [x] Done -- [Hallowed Fountain](https://scryfall.com/search?q=!hallowedfountain)
- [x] Done -- [Overgrown Tomb](https://scryfall.com/search?q=!overgrowntomb)
- [x] Done -- [Sacred Foundry](https://scryfall.com/search?q=!sacredfoundry)
- [x] Done -- [Steam Vents](https://scryfall.com/search?q=!steamvents)
- [x] Done -- [Stomping Ground](https://scryfall.com/search?q=!stompingground)
- [x] Done -- [Temple Garden](https://scryfall.com/search?q=!templegarden)
- [x] Done -- [The Space Family Goblinson](https://scryfall.com/search?q=!thespacefamilygoblinson)
- [x] Done -- [Watery Grave](https://scryfall.com/search?q=!waterygrave)

**Comment by theelk801** [comment]
- [ ] In progress -- [Assembled Ensemble](https://scryfall.com/search?q=!assembledensemble)
- [ ] In progress -- [Killer Cosplay](https://scryfall.com/search?q=!killercosplay)
- [ ] In progress -- [Saw in Half](https://scryfall.com/search?q=!sawinhalf)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"assembledensemble"or!"killercosplay"or!"sawinhalf"&unique=cards)

**Comment by theelk801** [comment]
Additional Tasks:

- [ ] handle new "acorn stamp" rarity correctly, the set is legacy legal but a portion of the cards are essentially silver-bordered

**Comment by jmharmon** [comment]
I thought cards that care about art can't be implemented into Xmage. So Assembled Ensemble will work?

**Comment by theelk801** [comment]
No, I just put the whole list up and didn’t bother figuring out what was or wasn’t doable. When the full set comes out I might filter it more but for now there’s really no point.

**Comment by skyler1221** [comment]
Magar is listed in the ACORN STAMP category, which he isn't

**Comment by Susucre** [comment]
Opened a PR for Comet, Stellar Pup: #10925

**Comment by jimga150** [comment]
Working on [Celebr-8000](https://scryfall.com/search?q=!celebr8000)

**Comment by Sidorovich77** [comment]
Working on Atomwheel Acrobats & Six-Sided Die 
#12651
