### ISSUE TITLE
NEC - Neon Dynasty Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8607]
This checklist is here to help manage the implementation of Neon Dynasty Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Access Denied](https://scryfall.com/search?q=!accessdenied)
- [x] Done -- [Acidic Slime](https://scryfall.com/search?q=!acidicslime)
- [x] Done -- [Aerial Surveyor](https://scryfall.com/search?q=!aerialsurveyor)
- [x] Done -- [Aeronaut Admiral](https://scryfall.com/search?q=!aeronautadmiral)
- [x] Done -- [Agitator Ant](https://scryfall.com/search?q=!agitatorant)
- [x] Done -- [Akki Battle Squad](https://scryfall.com/search?q=!akkibattlesquad)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Arcanist's Owl](https://scryfall.com/search?q=!arcanistsowl)
- [x] Done -- [Armed and Armored](https://scryfall.com/search?q=!armedandarmored)
- [x] Done -- [Ascendant Acolyte](https://scryfall.com/search?q=!ascendantacolyte)
- [x] Done -- [Azorius Signet](https://scryfall.com/search?q=!azoriussignet)
- [x] Done -- [Bear Umbra](https://scryfall.com/search?q=!bearumbra)
- [x] Done -- [Beast Within](https://scryfall.com/search?q=!beastwithin)
- [x] Done -- [Blackblade Reforged](https://scryfall.com/search?q=!blackbladereforged)
- [x] Done -- [Bonehoard](https://scryfall.com/search?q=!bonehoard)
- [x] Done -- [Cataclysmic Gearhulk](https://scryfall.com/search?q=!cataclysmicgearhulk)
- [x] Done -- [Chain Reaction](https://scryfall.com/search?q=!chainreaction)
- [x] Done -- [Champion of Lambholt](https://scryfall.com/search?q=!championoflambholt)
- [x] Done -- [Chaos Warp](https://scryfall.com/search?q=!chaoswarp)
- [x] Done -- [Chishiro, the Shattered Blade](https://scryfall.com/search?q=!chishirotheshatteredblade)
- [x] Done -- [Cinder Glade](https://scryfall.com/search?q=!cinderglade)
- [x] Done -- [Collision of Realms](https://scryfall.com/search?q=!collisionofrealms)
- [x] Done -- [Colossal Plow](https://scryfall.com/search?q=!colossalplow)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Concord with the Kami](https://scryfall.com/search?q=!concordwiththekami)
- [x] Done -- [Crush Contraband](https://scryfall.com/search?q=!crushcontraband)
- [x] Done -- [Cultivator's Caravan](https://scryfall.com/search?q=!cultivatorscaravan)
- [x] Done -- [Cyberdrive Awakener](https://scryfall.com/search?q=!cyberdriveawakener)
- [x] Done -- [Dance of the Manse](https://scryfall.com/search?q=!danceofthemanse)
- [x] Done -- [Decimate](https://scryfall.com/search?q=!decimate)
- [x] Done -- [Dispatch](https://scryfall.com/search?q=!dispatch)
- [x] Done -- [Drumbellower](https://scryfall.com/search?q=!drumbellower)
- [x] Done -- [Elemental Mastery](https://scryfall.com/search?q=!elementalmastery)
- [x] Done -- [Emry, Lurker of the Loch](https://scryfall.com/search?q=!emrylurkeroftheloch)
- [x] Done -- [Etherium Sculptor](https://scryfall.com/search?q=!etheriumsculptor)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Fellwar Stone](https://scryfall.com/search?q=!fellwarstone)
- [x] Done -- [Fertilid](https://scryfall.com/search?q=!fertilid)
- [x] Done -- [Fireshrieker](https://scryfall.com/search?q=!fireshrieker)
- [x] Done -- [Forgotten Ancient](https://scryfall.com/search?q=!forgottenancient)
- [x] Done -- [Foundry Inspector](https://scryfall.com/search?q=!foundryinspector)
- [x] Done -- [Game Trail](https://scryfall.com/search?q=!gametrail)
- [x] Done -- [Generous Gift](https://scryfall.com/search?q=!generousgift)
- [x] Done -- [Genesis Hydra](https://scryfall.com/search?q=!genesishydra)
- [x] Done -- [Go-Shintai of Life's Origin](https://scryfall.com/search?q=!goshintaioflifesorigin)
- [x] Done -- [Goblin Razerunners](https://scryfall.com/search?q=!goblinrazerunners)
- [x] Done -- [Gold Myr](https://scryfall.com/search?q=!goldmyr)
- [x] Done -- [Grumgully, the Generous](https://scryfall.com/search?q=!grumgullythegenerous)
- [x] Done -- [Gruul Turf](https://scryfall.com/search?q=!gruulturf)
- [x] Done -- [Hanna, Ship's Navigator](https://scryfall.com/search?q=!hannashipsnavigator)
- [x] Done -- [Hunter's Insight](https://scryfall.com/search?q=!huntersinsight)
- [x] Done -- [Imposter Mech](https://scryfall.com/search?q=!impostermech)
- [x] Done -- [Indomitable Archangel](https://scryfall.com/search?q=!indomitablearchangel)
- [x] Done -- [Ironsoul Enforcer](https://scryfall.com/search?q=!ironsoulenforcer)
- [x] Done -- [Jace, Architect of Thought](https://scryfall.com/search?q=!jacearchitectofthought)
- [x] Done -- [Kaima, the Fractured Calm](https://scryfall.com/search?q=!kaimathefracturedcalm)
- [x] Done -- [Kami of Celebration](https://scryfall.com/search?q=!kamiofcelebration)
- [x] Done -- [Kappa Cannoneer](https://scryfall.com/search?q=!kappacannoneer)
- [x] Done -- [Katsumasa, the Animator](https://scryfall.com/search?q=!katsumasatheanimator)
- [x] Done -- [Kodama's Reach](https://scryfall.com/search?q=!kodamasreach)
- [x] Done -- [Komainu Battle Armor](https://scryfall.com/search?q=!komainubattlearmor)
- [x] Done -- [Kosei, Penitent Warlord](https://scryfall.com/search?q=!koseipenitentwarlord)
- [x] Done -- [Kotori, Pilot Prodigy](https://scryfall.com/search?q=!kotoripilotprodigy)
- [x] Done -- [Krenko, Tin Street Kingpin](https://scryfall.com/search?q=!krenkotinstreetkingpin)
- [x] Done -- [Loyal Guardian](https://scryfall.com/search?q=!loyalguardian)
- [x] Done -- [Mage Slayer](https://scryfall.com/search?q=!mageslayer)
- [x] Done -- [Master of Etherium](https://scryfall.com/search?q=!masterofetherium)
- [x] Done -- [Mirage Mirror](https://scryfall.com/search?q=!miragemirror)
- [x] Done -- [Mossfire Valley](https://scryfall.com/search?q=!mossfirevalley)
- [x] Done -- [Myojin of Blooming Dawn](https://scryfall.com/search?q=!myojinofbloomingdawn)
- [x] Done -- [Myojin of Cryptic Dreams](https://scryfall.com/search?q=!myojinofcrypticdreams)
- [x] Done -- [Myojin of Grim Betrayal](https://scryfall.com/search?q=!myojinofgrimbetrayal)
- [x] Done -- [Myojin of Roaring Blades](https://scryfall.com/search?q=!myojinofroaringblades)
- [x] Done -- [Myojin of Towering Might](https://scryfall.com/search?q=!myojinoftoweringmight)
- [x] Done -- [Myrsmith](https://scryfall.com/search?q=!myrsmith)
- [x] Done -- [Nissa, Voice of Zendikar](https://scryfall.com/search?q=!nissavoiceofzendikar)
- [x] Done -- [One with the Kami](https://scryfall.com/search?q=!onewiththekami)
- [x] Done -- [Opal Palace](https://scryfall.com/search?q=!opalpalace)
- [x] Done -- [Oran-Rief, the Vastwood](https://scryfall.com/search?q=!oranriefthevastwood)
- [x] Done -- [Ordeal of Nylea](https://scryfall.com/search?q=!ordealofnylea)
- [x] Done -- [Organic Extinction](https://scryfall.com/search?q=!organicextinction)
- [x] Done -- [Ox of Agonas](https://scryfall.com/search?q=!oxofagonas)
- [x] Done -- [Parhelion II](https://scryfall.com/search?q=!parhelionii)
- [x] Done -- [Peacewalker Colossus](https://scryfall.com/search?q=!peacewalkercolossus)
- [x] Done -- [Port Town](https://scryfall.com/search?q=!porttown)
- [x] Done -- [Prairie Stream](https://scryfall.com/search?q=!prairiestream)
- [x] Done -- [Primeval Protector](https://scryfall.com/search?q=!primevalprotector)
- [x] Done -- [Raff Capashen, Ship's Mage](https://scryfall.com/search?q=!raffcapashenshipsmage)
- [x] Done -- [Raging Ravine](https://scryfall.com/search?q=!ragingravine)
- [x] Done -- [Raiders' Karve](https://scryfall.com/search?q=!raiderskarve)
- [x] Done -- [Rampant Growth](https://scryfall.com/search?q=!rampantgrowth)
- [x] Done -- [Rampant Rejuvenator](https://scryfall.com/search?q=!rampantrejuvenator)
- [x] Done -- [Reality Shift](https://scryfall.com/search?q=!realityshift)
- [x] Done -- [Release to Memory](https://scryfall.com/search?q=!releasetomemory)
- [x] Done -- [Research Thief](https://scryfall.com/search?q=!researchthief)
- [x] Done -- [Rhythm of the Wild](https://scryfall.com/search?q=!rhythmofthewild)
- [x] Done -- [Riddlesmith](https://scryfall.com/search?q=!riddlesmith)
- [x] Done -- [Rishkar's Expertise](https://scryfall.com/search?q=!rishkarsexpertise)
- [x] Done -- [Rishkar, Peema Renegade](https://scryfall.com/search?q=!rishkarpeemarenegade)
- [x] Done -- [Ruthless Technomancer](https://scryfall.com/search?q=!ruthlesstechnomancer)
- [x] Done -- [Sai, Master Thopterist](https://scryfall.com/search?q=!saimasterthopterist)
- [x] Done -- [Sakura-Tribe Elder](https://scryfall.com/search?q=!sakuratribeelder)
- [x] Done -- [Shamanic Revelation](https://scryfall.com/search?q=!shamanicrevelation)
- [x] Done -- [Shifting Shadow](https://scryfall.com/search?q=!shiftingshadow)
- [x] Done -- [Shimmer Myr](https://scryfall.com/search?q=!shimmermyr)
- [x] Done -- [Shorikai, Genesis Engine](https://scryfall.com/search?q=!shorikaigenesisengine)
- [x] Done -- [Silkguard](https://scryfall.com/search?q=!silkguard)
- [x] Done -- [Silver Myr](https://scryfall.com/search?q=!silvermyr)
- [x] Done -- [Skycloud Expanse](https://scryfall.com/search?q=!skycloudexpanse)
- [x] Done -- [Skysovereign, Consul Flagship](https://scryfall.com/search?q=!skysovereignconsulflagship)
- [x] Done -- [Smoke Spirits' Aid](https://scryfall.com/search?q=!smokespiritsaid)
- [x] Done -- [Smuggler's Copter](https://scryfall.com/search?q=!smugglerscopter)
- [x] Done -- [Snake Umbra](https://scryfall.com/search?q=!snakeumbra)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Solemn Simulacrum](https://scryfall.com/search?q=!solemnsimulacrum)
- [x] Done -- [Soul's Majesty](https://scryfall.com/search?q=!soulsmajesty)
- [x] Done -- [Spearbreaker Behemoth](https://scryfall.com/search?q=!spearbreakerbehemoth)
- [x] Done -- [Spire of Industry](https://scryfall.com/search?q=!spireofindustry)
- [x] Done -- [Sram, Senior Edificer](https://scryfall.com/search?q=!sramsenioredificer)
- [x] Done -- [Starstorm](https://scryfall.com/search?q=!starstorm)
- [x] Done -- [Swift Reconfiguration](https://scryfall.com/search?q=!swiftreconfiguration)
- [x] Done -- [Swiftfoot Boots](https://scryfall.com/search?q=!swiftfootboots)
- [x] Done -- [Sword of Vengeance](https://scryfall.com/search?q=!swordofvengeance)
- [x] Done -- [Swords to Plowshares](https://scryfall.com/search?q=!swordstoplowshares)
- [x] Done -- [Tanuki Transplanter](https://scryfall.com/search?q=!tanukitransplanter)
- [x] Done -- [Taurean Mauler](https://scryfall.com/search?q=!taureanmauler)
- [x] Done -- [Temple of Abandon](https://scryfall.com/search?q=!templeofabandon)
- [x] Done -- [Temple of Enlightenment](https://scryfall.com/search?q=!templeofenlightenment)
- [x] Done -- [Teshar, Ancestor's Apostle](https://scryfall.com/search?q=!tesharancestorsapostle)
- [x] Done -- [Thopter Spy Network](https://scryfall.com/search?q=!thopterspynetwork)
- [x] Done -- [Thoughtcast](https://scryfall.com/search?q=!thoughtcast)
- [x] Done -- [Ulasht, the Hate Seed](https://scryfall.com/search?q=!ulashtthehateseed)
- [x] Done -- [Universal Surveillance](https://scryfall.com/search?q=!universalsurveillance)
- [x] Done -- [Unquenchable Fury](https://scryfall.com/search?q=!unquenchablefury)
- [x] Done -- [Vastwood Surge](https://scryfall.com/search?q=!vastwoodsurge)
- [x] Done -- [Vedalken Engineer](https://scryfall.com/search?q=!vedalkenengineer)
- [x] Done -- [Weatherlight](https://scryfall.com/search?q=!weatherlight)
- [x] Done -- [Whiptongue Hydra](https://scryfall.com/search?q=!whiptonguehydra)
- [x] Done -- [Whirler Rogue](https://scryfall.com/search?q=!whirlerrogue)
- [x] Done -- [Yoshimaru, Ever Faithful](https://scryfall.com/search?q=!yoshimarueverfaithful)
</details>

**Comment by theelk801** [comment]
Additional tasks: none yet

**Comment by Alex-Vasile** [comment]
I am going to try out the two Miojin cards, mark them as in-progress please.

**Comment by Alex-Vasile** [comment]
Can Akki Battle Squad be properly implemented given #8595?

Is that ability supposed to untap modified creatures during the declare attackers step?

**Comment by theelk801** [comment]
it should be fine, the untapping doesn’t happen while you’re declaring attackers
