### ISSUE TITLE
Y22 - Alchemy: Innistrad Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8732]
This checklist is here to help manage the implementation of Alchemy: Innistrad. If a card is marked as being in progress then someone is working on it. Some of the cards in this set may not be implementable, so this list may stay incomplete.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Absorb Energy](https://scryfall.com/search?q=!absorbenergy)
- [ ] In progress -- [Angel of Eternal Dawn](https://scryfall.com/search?q=!angelofeternaldawn)
- [ ] In progress -- [Angel of Unity](https://scryfall.com/search?q=!angelofunity)
- [ ] In progress -- [Antique Collector](https://scryfall.com/search?q=!antiquecollector)
- [ ] In progress -- [Arms Scavenger](https://scryfall.com/search?q=!armsscavenger)
- [ ] In progress -- [Assemble from Parts](https://scryfall.com/search?q=!assemblefromparts)
- [ ] In progress -- [Begin Anew](https://scryfall.com/search?q=!beginanew)
- [ ] In progress -- [Bloodrage Alpha](https://scryfall.com/search?q=!bloodragealpha)
- [ ] In progress -- [Break Expectations](https://scryfall.com/search?q=!breakexpectations)
- [ ] In progress -- [Brittle Blast](https://scryfall.com/search?q=!brittleblast)
- [ ] In progress -- [Captain Eberhart](https://scryfall.com/search?q=!captaineberhart)
- [ ] In progress -- [Clone Crafter](https://scryfall.com/search?q=!clonecrafter)
- [ ] In progress -- [Conductive Current](https://scryfall.com/search?q=!conductivecurrent)
- [ ] In progress -- [Discover the Formula](https://scryfall.com/search?q=!discovertheformula)
- [ ] In progress -- [Divine Purge](https://scryfall.com/search?q=!divinepurge)
- [ ] In progress -- [Electrostatic Blast](https://scryfall.com/search?q=!electrostaticblast)
- [ ] In progress -- [Ethereal Escort](https://scryfall.com/search?q=!etherealescort)
- [ ] In progress -- [Fearsome Whelp](https://scryfall.com/search?q=!fearsomewhelp)
- [ ] In progress -- [Forsaken Crossroads](https://scryfall.com/search?q=!forsakencrossroads)
- [ ] In progress -- [Frenzied Geistblaster](https://scryfall.com/search?q=!frenziedgeistblaster)
- [ ] In progress -- [Garruk, Wrath of the Wilds](https://scryfall.com/search?q=!garrukwrathofthewilds)
- [ ] In progress -- [Geist of Regret](https://scryfall.com/search?q=!geistofregret)
- [ ] In progress -- [Geistchanneler](https://scryfall.com/search?q=!geistchanneler)
- [ ] In progress -- [Geistpack Alpha](https://scryfall.com/search?q=!geistpackalpha)
- [ ] In progress -- [Gitrog, Horror of Zhava](https://scryfall.com/search?q=!gitroghorrorofzhava)
- [ ] In progress -- [Grizzled Huntmaster](https://scryfall.com/search?q=!grizzledhuntmaster)
- [ ] In progress -- [Gutmorn, Pactbound Servant](https://scryfall.com/search?q=!gutmornpactboundservant)
- [ ] In progress -- [Hinterland Chef](https://scryfall.com/search?q=!hinterlandchef)
- [ ] In progress -- [Hollowhenge Wrangler](https://scryfall.com/search?q=!hollowhengewrangler)
- [ ] In progress -- [Inquisitor Captain](https://scryfall.com/search?q=!inquisitorcaptain)
- [ ] In progress -- [Lupine Harbingers](https://scryfall.com/search?q=!lupineharbingers)
- [ ] In progress -- [Oglor, Devoted Assistant](https://scryfall.com/search?q=!oglordevotedassistant)
- [ ] In progress -- [Ominous Traveler](https://scryfall.com/search?q=!ominoustraveler)
- [ ] In progress -- [Patient Zero](https://scryfall.com/search?q=!patientzero)
- [ ] In progress -- [Predatory Sludge](https://scryfall.com/search?q=!predatorysludge)
- [ ] In progress -- [Puppet Raiser](https://scryfall.com/search?q=!puppetraiser)
- [ ] In progress -- [Rahilda, Wanted Cutthroat](https://scryfall.com/search?q=!rahildawantedcutthroat)
- [ ] In progress -- [Ravenous Pursuit](https://scryfall.com/search?q=!ravenouspursuit)
- [ ] In progress -- [Rimewall Protector](https://scryfall.com/search?q=!rimewallprotector)
- [ ] In progress -- [Sanguine Brushstroke](https://scryfall.com/search?q=!sanguinebrushstroke)
- [ ] In progress -- [Sap Vitality](https://scryfall.com/search?q=!sapvitality)
- [ ] In progress -- [Settle the Wilds](https://scryfall.com/search?q=!settlethewilds)
- [ ] In progress -- [Sigardian Evangel](https://scryfall.com/search?q=!sigardianevangel)
- [ ] In progress -- [Sinister Reflections](https://scryfall.com/search?q=!sinisterreflections)
- [ ] In progress -- [Slayer's Bounty](https://scryfall.com/search?q=!slayersbounty)
- [ ] In progress -- [Tenacious Pup](https://scryfall.com/search?q=!tenaciouspup)
- [ ] In progress -- [Tibalt, Wicked Tormentor](https://scryfall.com/search?q=!tibaltwickedtormentor)
- [ ] In progress -- [Toralf's Disciple](https://scryfall.com/search?q=!toralfsdisciple)
- [ ] In progress -- [Town-Razer Tyrant](https://scryfall.com/search?q=!townrazertyrant)
- [ ] In progress -- [Unexpected Conversion](https://scryfall.com/search?q=!unexpectedconversion)
- [ ] In progress -- [Veteran Ghoulcaller](https://scryfall.com/search?q=!veteranghoulcaller)
- [ ] In progress -- [Wickerwing Effigy](https://scryfall.com/search?q=!wickerwingeffigy)

[Scryfall gallery of everything currently unimplemented (page 1)](https://scryfall.com/search?q=!"absorbenergy"or!"angelofeternaldawn"or!"angelofunity"or!"antiquecollector"or!"armsscavenger"or!"assemblefromparts"or!"beginanew"or!"bloodragealpha"or!"breakexpectations"or!"brittleblast"or!"captaineberhart"or!"clonecrafter"or!"conductivecurrent"or!"discovertheformula"or!"divinepurge"or!"electrostaticblast"or!"etherealescort"or!"fearsomewhelp"or!"forsakencrossroads"or!"frenziedgeistblaster"or!"garrukwrathofthewilds"or!"geistofregret"or!"geistchanneler"or!"geistpackalpha"or!"gitroghorrorofzhava"or!"grizzledhuntmaster"&unique=cards)
[Scryfall gallery of everything currently unimplemented (page 2)](https://scryfall.com/search?q=!"gutmornpactboundservant"or!"hinterlandchef"or!"hollowhengewrangler"or!"inquisitorcaptain"or!"lupineharbingers"or!"oglordevotedassistant"or!"ominoustraveler"or!"patientzero"or!"predatorysludge"or!"puppetraiser"or!"rahildawantedcutthroat"or!"ravenouspursuit"or!"rimewallprotector"or!"sanguinebrushstroke"or!"sapvitality"or!"settlethewilds"or!"sigardianevangel"or!"sinisterreflections"or!"slayersbounty"or!"tenaciouspup"or!"tibaltwickedtormentor"or!"toralfsdisciple"or!"townrazertyrant"or!"unexpectedconversion"or!"veteranghoulcaller"or!"wickerwingeffigy"&unique=cards)
# Implemented Cards

- [x] Done -- [Citystalker Connoisseur](https://scryfall.com/search?q=!citystalkerconnoisseur)
- [x] Done -- [Cursebound Witch](https://scryfall.com/search?q=!curseboundwitch)
- [x] Done -- [Expedition Supplier](https://scryfall.com/search?q=!expeditionsupplier)
- [x] Done -- [Faithful Disciple](https://scryfall.com/search?q=!faithfuldisciple)
- [x] Done -- [Ishkanah, Broodmother](https://scryfall.com/search?q=!ishkanahbroodmother)
- [x] Done -- [Key to the Archive](https://scryfall.com/search?q=!keytothearchive)
- [x] Done -- [Kindred Denial](https://scryfall.com/search?q=!kindreddenial)
- [x] Done -- [Obsessive Collector](https://scryfall.com/search?q=!obsessivecollector)
- [x] Done -- [Soulstealer Axe](https://scryfall.com/search?q=!soulstealeraxe)
- [x] Done -- [Suntail Squadron](https://scryfall.com/search?q=!suntailsquadron)
- [x] Done -- [Tireless Angler](https://scryfall.com/search?q=!tirelessangler)
