### ISSUE TITLE
SNC - Streets of New Capenna Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8741]
This checklist is here to help manage the implementation of Streets of New Capenna. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [A Little Chat](https://scryfall.com/search?q=!alittlechat)
- [x] Done -- [All-Seeing Arbiter](https://scryfall.com/search?q=!allseeingarbiter)
- [x] Done -- [An Offer You Can't Refuse](https://scryfall.com/search?q=!anofferyoucantrefuse)
- [x] Done -- [Angel of Suffering](https://scryfall.com/search?q=!angelofsuffering)
- [x] Done -- [Angelic Observer](https://scryfall.com/search?q=!angelicobserver)
- [x] Done -- [Antagonize](https://scryfall.com/search?q=!antagonize)
- [x] Done -- [Arc Spitter](https://scryfall.com/search?q=!arcspitter)
- [x] Done -- [Arcane Bombardment](https://scryfall.com/search?q=!arcanebombardment)
- [x] Done -- [Attended Socialite](https://scryfall.com/search?q=!attendedsocialite)
- [x] Done -- [Aven Heartstabber](https://scryfall.com/search?q=!avenheartstabber)
- [x] Done -- [Backstreet Bruiser](https://scryfall.com/search?q=!backstreetbruiser)
- [x] Done -- [Backup Agent](https://scryfall.com/search?q=!backupagent)
- [x] Done -- [Ballroom Brawlers](https://scryfall.com/search?q=!ballroombrawlers)
- [x] Done -- [Big Score](https://scryfall.com/search?q=!bigscore)
- [x] Done -- [Black Market Tycoon](https://scryfall.com/search?q=!blackmarkettycoon)
- [x] Done -- [Body Dropper](https://scryfall.com/search?q=!bodydropper)
- [x] Done -- [Body Launderer](https://scryfall.com/search?q=!bodylaunderer)
- [x] Done -- [Boon of Safety](https://scryfall.com/search?q=!boonofsafety)
- [x] Done -- [Bootleggers' Stash](https://scryfall.com/search?q=!bootleggersstash)
- [x] Done -- [Botanical Plaza](https://scryfall.com/search?q=!botanicalplaza)
- [x] Done -- [Bouncer's Beatdown](https://scryfall.com/search?q=!bouncersbeatdown)
- [x] Done -- [Brass Knuckles](https://scryfall.com/search?q=!brassknuckles)
- [x] Done -- [Brazen Upstart](https://scryfall.com/search?q=!brazenupstart)
- [x] Done -- [Broken Wings](https://scryfall.com/search?q=!brokenwings)
- [x] Done -- [Brokers Ascendancy](https://scryfall.com/search?q=!brokersascendancy)
- [x] Done -- [Brokers Charm](https://scryfall.com/search?q=!brokerscharm)
- [x] Done -- [Brokers Hideout](https://scryfall.com/search?q=!brokershideout)
- [x] Done -- [Brokers Initiate](https://scryfall.com/search?q=!brokersinitiate)
- [x] Done -- [Brokers Veteran](https://scryfall.com/search?q=!brokersveteran)
- [x] Done -- [Buy Your Silence](https://scryfall.com/search?q=!buyyoursilence)
- [x] Done -- [Cabaretti Ascendancy](https://scryfall.com/search?q=!cabarettiascendancy)
- [x] Done -- [Cabaretti Charm](https://scryfall.com/search?q=!cabaretticharm)
- [x] Done -- [Cabaretti Courtyard](https://scryfall.com/search?q=!cabaretticourtyard)
- [x] Done -- [Cabaretti Initiate](https://scryfall.com/search?q=!cabarettiinitiate)
- [x] Done -- [Caldaia Strongarm](https://scryfall.com/search?q=!caldaiastrongarm)
- [x] Done -- [Call In a Professional](https://scryfall.com/search?q=!callinaprofessional)
- [x] Done -- [Capenna Express](https://scryfall.com/search?q=!capennaexpress)
- [x] Done -- [Case the Joint](https://scryfall.com/search?q=!casethejoint)
- [x] Done -- [Celebrity Fencer](https://scryfall.com/search?q=!celebrityfencer)
- [x] Done -- [Celestial Regulator](https://scryfall.com/search?q=!celestialregulator)
- [x] Done -- [Cement Shoes](https://scryfall.com/search?q=!cementshoes)
- [x] Done -- [Cemetery Tampering](https://scryfall.com/search?q=!cemeterytampering)
- [x] Done -- [Ceremonial Groundbreaker](https://scryfall.com/search?q=!ceremonialgroundbreaker)
- [x] Done -- [Chrome Cat](https://scryfall.com/search?q=!chromecat)
- [x] Done -- [Citizen's Crowbar](https://scryfall.com/search?q=!citizenscrowbar)
- [x] Done -- [Civic Gardener](https://scryfall.com/search?q=!civicgardener)
- [x] Done -- [Civil Servant](https://scryfall.com/search?q=!civilservant)
- [x] Done -- [Cleanup Crew](https://scryfall.com/search?q=!cleanupcrew)
- [x] Done -- [Cormela, Glamour Thief](https://scryfall.com/search?q=!cormelaglamourthief)
- [x] Done -- [Corpse Appraiser](https://scryfall.com/search?q=!corpseappraiser)
- [x] Done -- [Corpse Explosion](https://scryfall.com/search?q=!corpseexplosion)
- [x] Done -- [Corrupt Court Official](https://scryfall.com/search?q=!corruptcourtofficial)
- [x] Done -- [Courier's Briefcase](https://scryfall.com/search?q=!couriersbriefcase)
- [x] Done -- [Crew Captain](https://scryfall.com/search?q=!crewcaptain)
- [x] Done -- [Crooked Custodian](https://scryfall.com/search?q=!crookedcustodian)
- [x] Done -- [Cut Your Losses](https://scryfall.com/search?q=!cutyourlosses)
- [x] Done -- [Cut of the Profits](https://scryfall.com/search?q=!cutoftheprofits)
- [x] Done -- [Cutthroat Contender](https://scryfall.com/search?q=!cutthroatcontender)
- [x] Done -- [Dapper Shieldmate](https://scryfall.com/search?q=!dappershieldmate)
- [x] Done -- [Daring Escape](https://scryfall.com/search?q=!daringescape)
- [x] Done -- [Darling of the Masses](https://scryfall.com/search?q=!darlingofthemasses)
- [x] Done -- [Deal Gone Bad](https://scryfall.com/search?q=!dealgonebad)
- [x] Done -- [Demon's Due](https://scryfall.com/search?q=!demonsdue)
- [x] Done -- [Depopulate](https://scryfall.com/search?q=!depopulate)
- [x] Done -- [Devilish Valet](https://scryfall.com/search?q=!devilishvalet)
- [x] Done -- [Dig Up the Body](https://scryfall.com/search?q=!digupthebody)
- [x] Done -- [Disciplined Duelist](https://scryfall.com/search?q=!disciplinedduelist)
- [x] Done -- [Disdainful Stroke](https://scryfall.com/search?q=!disdainfulstroke)
- [x] Done -- [Dusk Mangler](https://scryfall.com/search?q=!duskmangler)
- [x] Done -- [Echo Inspector](https://scryfall.com/search?q=!echoinspector)
- [x] Done -- [Elegant Entourage](https://scryfall.com/search?q=!elegantentourage)
- [x] Done -- [Elspeth Resplendent](https://scryfall.com/search?q=!elspethresplendent)
- [x] Done -- [Endless Detour](https://scryfall.com/search?q=!endlessdetour)
- [x] Done -- [Errant, Street Artist](https://scryfall.com/search?q=!errantstreetartist)
- [x] Done -- [Evelyn, the Covetous](https://scryfall.com/search?q=!evelynthecovetous)
- [x] Done -- [Even the Score](https://scryfall.com/search?q=!eventhescore)
- [x] Done -- [Evolving Door](https://scryfall.com/search?q=!evolvingdoor)
- [x] Done -- [Exhibition Magician](https://scryfall.com/search?q=!exhibitionmagician)
- [x] Done -- [Exotic Pets](https://scryfall.com/search?q=!exoticpets)
- [x] Done -- [Expendable Lackey](https://scryfall.com/search?q=!expendablelackey)
- [x] Done -- [Extract the Truth](https://scryfall.com/search?q=!extractthetruth)
- [x] Done -- [Extraction Specialist](https://scryfall.com/search?q=!extractionspecialist)
- [x] Done -- [Faerie Vandal](https://scryfall.com/search?q=!faerievandal)
- [x] Done -- [Fake Your Own Death](https://scryfall.com/search?q=!fakeyourowndeath)
- [x] Done -- [Falco Spara, Pactweaver](https://scryfall.com/search?q=!falcosparapactweaver)
- [x] Done -- [Fatal Grudge](https://scryfall.com/search?q=!fatalgrudge)
- [x] Done -- [Fight Rigging](https://scryfall.com/search?q=!fightrigging)
- [x] Done -- [Fleetfoot Dancer](https://scryfall.com/search?q=!fleetfootdancer)
- [x] Done -- [For the Family](https://scryfall.com/search?q=!forthefamily)
- [x] Done -- [Forge Boss](https://scryfall.com/search?q=!forgeboss)
- [x] Done -- [Freelance Muscle](https://scryfall.com/search?q=!freelancemuscle)
- [x] Done -- [Gala Greeters](https://scryfall.com/search?q=!galagreeters)
- [x] Done -- [Gathering Throng](https://scryfall.com/search?q=!gatheringthrong)
- [x] Done -- [Getaway Car](https://scryfall.com/search?q=!getawaycar)
- [x] Done -- [Giada, Font of Hope](https://scryfall.com/search?q=!giadafontofhope)
- [x] Done -- [Gilded Pinions](https://scryfall.com/search?q=!gildedpinions)
- [x] Done -- [Girder Goons](https://scryfall.com/search?q=!girdergoons)
- [x] Done -- [Glamorous Outlaw](https://scryfall.com/search?q=!glamorousoutlaw)
- [x] Done -- [Glittering Stockpile](https://scryfall.com/search?q=!glitteringstockpile)
- [x] Done -- [Glittermonger](https://scryfall.com/search?q=!glittermonger)
- [x] Done -- [Goldhound](https://scryfall.com/search?q=!goldhound)
- [x] Done -- [Graveyard Shift](https://scryfall.com/search?q=!graveyardshift)
- [x] Done -- [Grisly Sigil](https://scryfall.com/search?q=!grislysigil)
- [x] Done -- [Halo Fountain](https://scryfall.com/search?q=!halofountain)
- [x] Done -- [Halo Scarab](https://scryfall.com/search?q=!haloscarab)
- [x] Done -- [High-Rise Sawjack](https://scryfall.com/search?q=!highrisesawjack)
- [x] Done -- [Hoard Hauler](https://scryfall.com/search?q=!hoardhauler)
- [x] Done -- [Hold for Ransom](https://scryfall.com/search?q=!holdforransom)
- [x] Done -- [Hostile Takeover](https://scryfall.com/search?q=!hostiletakeover)
- [x] Done -- [Hypnotic Grifter](https://scryfall.com/search?q=!hypnoticgrifter)
- [x] Done -- [Illicit Shipment](https://scryfall.com/search?q=!illicitshipment)
- [x] Done -- [Illuminator Virtuoso](https://scryfall.com/search?q=!illuminatorvirtuoso)
- [x] Done -- [Incandescent Aria](https://scryfall.com/search?q=!incandescentaria)
- [x] Done -- [Incriminate](https://scryfall.com/search?q=!incriminate)
- [x] Done -- [Inspiring Overseer](https://scryfall.com/search?q=!inspiringoverseer)
- [x] Done -- [Involuntary Employment](https://scryfall.com/search?q=!involuntaryemployment)
- [x] Done -- [Jackhammer](https://scryfall.com/search?q=!jackhammer)
- [x] Done -- [Jaxis, the Troublemaker](https://scryfall.com/search?q=!jaxisthetroublemaker)
- [x] Done -- [Jetmir's Fixer](https://scryfall.com/search?q=!jetmirsfixer)
- [x] Done -- [Jetmir's Garden](https://scryfall.com/search?q=!jetmirsgarden)
- [x] Done -- [Jetmir, Nexus of Revels](https://scryfall.com/search?q=!jetmirnexusofrevels)
- [x] Done -- [Jewel Thief](https://scryfall.com/search?q=!jewelthief)
- [x] Done -- [Jinnie Fay, Jetmir's Second](https://scryfall.com/search?q=!jinniefayjetmirssecond)
- [x] Done -- [Join the Maestros](https://scryfall.com/search?q=!jointhemaestros)
- [x] Done -- [Kill Shot](https://scryfall.com/search?q=!killshot)
- [x] Done -- [Knockout Blow](https://scryfall.com/search?q=!knockoutblow)
- [x] Done -- [Lagrella, the Magpie](https://scryfall.com/search?q=!lagrellathemagpie)
- [x] Done -- [Ledger Shredder](https://scryfall.com/search?q=!ledgershredder)
- [x] Done -- [Light 'Em Up](https://scryfall.com/search?q=!lightemup)
- [x] Done -- [Lord Xander, the Collector](https://scryfall.com/search?q=!lordxanderthecollector)
- [x] Done -- [Luxior, Giada's Gift](https://scryfall.com/search?q=!luxiorgiadasgift)
- [x] Done -- [Luxurious Libation](https://scryfall.com/search?q=!luxuriouslibation)
- [x] Done -- [Maestros Ascendancy](https://scryfall.com/search?q=!maestrosascendancy)
- [x] Done -- [Maestros Charm](https://scryfall.com/search?q=!maestroscharm)
- [x] Done -- [Maestros Diabolist](https://scryfall.com/search?q=!maestrosdiabolist)
- [x] Done -- [Maestros Initiate](https://scryfall.com/search?q=!maestrosinitiate)
- [x] Done -- [Maestros Theater](https://scryfall.com/search?q=!maestrostheater)
- [x] Done -- [Mage's Attendant](https://scryfall.com/search?q=!magesattendant)
- [x] Done -- [Majestic Metamorphosis](https://scryfall.com/search?q=!majesticmetamorphosis)
- [x] Done -- [Make Disappear](https://scryfall.com/search?q=!makedisappear)
- [x] Done -- [Masked Bandits](https://scryfall.com/search?q=!maskedbandits)
- [x] Done -- [Mayhem Patrol](https://scryfall.com/search?q=!mayhempatrol)
- [x] Done -- [Meeting of the Five](https://scryfall.com/search?q=!meetingofthefive)
- [x] Done -- [Metropolis Angel](https://scryfall.com/search?q=!metropolisangel)
- [x] Done -- [Midnight Assassin](https://scryfall.com/search?q=!midnightassassin)
- [x] Done -- [Most Wanted](https://scryfall.com/search?q=!mostwanted)
- [x] Done -- [Mr. Orfeo, the Boulder](https://scryfall.com/search?q=!mrorfeotheboulder)
- [x] Done -- [Murder](https://scryfall.com/search?q=!murder)
- [x] Done -- [Mysterious Limousine](https://scryfall.com/search?q=!mysteriouslimousine)
- [x] Done -- [Night Clubber](https://scryfall.com/search?q=!nightclubber)
- [x] Done -- [Nimble Larcenist](https://scryfall.com/search?q=!nimblelarcenist)
- [x] Done -- [Ob Nixilis, the Adversary](https://scryfall.com/search?q=!obnixilistheadversary)
- [x] Done -- [Obscura Ascendancy](https://scryfall.com/search?q=!obscuraascendancy)
- [x] Done -- [Obscura Charm](https://scryfall.com/search?q=!obscuracharm)
- [x] Done -- [Obscura Initiate](https://scryfall.com/search?q=!obscurainitiate)
- [x] Done -- [Obscura Interceptor](https://scryfall.com/search?q=!obscurainterceptor)
- [x] Done -- [Obscura Storefront](https://scryfall.com/search?q=!obscurastorefront)
- [x] Done -- [Ognis, the Dragon's Lash](https://scryfall.com/search?q=!ognisthedragonslash)
- [x] Done -- [Ominous Parcel](https://scryfall.com/search?q=!ominousparcel)
- [x] Done -- [Out of the Way](https://scryfall.com/search?q=!outoftheway)
- [x] Done -- [Paragon of Modernity](https://scryfall.com/search?q=!paragonofmodernity)
- [x] Done -- [Park Heights Pegasus](https://scryfall.com/search?q=!parkheightspegasus)
- [x] Done -- [Patch Up](https://scryfall.com/search?q=!patchup)
- [x] Done -- [Plasma Jockey](https://scryfall.com/search?q=!plasmajockey)
- [x] Done -- [Prizefight](https://scryfall.com/search?q=!prizefight)
- [x] Done -- [Professional Face-Breaker](https://scryfall.com/search?q=!professionalfacebreaker)
- [x] Done -- [Psionic Snoop](https://scryfall.com/search?q=!psionicsnoop)
- [x] Done -- [Psychic Pickpocket](https://scryfall.com/search?q=!psychicpickpocket)
- [x] Done -- [Public Enemy](https://scryfall.com/search?q=!publicenemy)
- [x] Done -- [Pugnacious Pugilist](https://scryfall.com/search?q=!pugnaciouspugilist)
- [x] Done -- [Pyre-Sledge Arsonist](https://scryfall.com/search?q=!pyresledgearsonist)
- [x] Done -- [Queza, Augur of Agonies](https://scryfall.com/search?q=!quezaaugurofagonies)
- [x] Done -- [Quick-Draw Dagger](https://scryfall.com/search?q=!quickdrawdagger)
- [x] Done -- [Rabble Rousing](https://scryfall.com/search?q=!rabblerousing)
- [x] Done -- [Racers' Ring](https://scryfall.com/search?q=!racersring)
- [x] Done -- [Raffine's Guidance](https://scryfall.com/search?q=!raffinesguidance)
- [x] Done -- [Raffine's Informant](https://scryfall.com/search?q=!raffinesinformant)
- [x] Done -- [Raffine's Silencer](https://scryfall.com/search?q=!raffinessilencer)
- [x] Done -- [Raffine's Tower](https://scryfall.com/search?q=!raffinestower)
- [x] Done -- [Raffine, Scheming Seer](https://scryfall.com/search?q=!raffineschemingseer)
- [x] Done -- [Rakish Revelers](https://scryfall.com/search?q=!rakishrevelers)
- [x] Done -- [Ready to Rumble](https://scryfall.com/search?q=!readytorumble)
- [x] Done -- [Refuse to Yield](https://scryfall.com/search?q=!refusetoyield)
- [x] Done -- [Reservoir Kraken](https://scryfall.com/search?q=!reservoirkraken)
- [x] Done -- [Revel Ruiner](https://scryfall.com/search?q=!revelruiner)
- [x] Done -- [Revelation of Power](https://scryfall.com/search?q=!revelationofpower)
- [x] Done -- [Rhox Pummeler](https://scryfall.com/search?q=!rhoxpummeler)
- [x] Done -- [Rigo, Streetwise Mentor](https://scryfall.com/search?q=!rigostreetwisementor)
- [x] Done -- [Riveteers Ascendancy](https://scryfall.com/search?q=!riveteersascendancy)
- [x] Done -- [Riveteers Charm](https://scryfall.com/search?q=!riveteerscharm)
- [x] Done -- [Riveteers Decoy](https://scryfall.com/search?q=!riveteersdecoy)
- [x] Done -- [Riveteers Initiate](https://scryfall.com/search?q=!riveteersinitiate)
- [x] Done -- [Riveteers Overlook](https://scryfall.com/search?q=!riveteersoverlook)
- [x] Done -- [Riveteers Requisitioner](https://scryfall.com/search?q=!riveteersrequisitioner)
- [x] Done -- [Rob the Archives](https://scryfall.com/search?q=!robthearchives)
- [x] Done -- [Rocco, Cabaretti Caterer](https://scryfall.com/search?q=!roccocabaretticaterer)
- [x] Done -- [Rogues' Gallery](https://scryfall.com/search?q=!roguesgallery)
- [x] Done -- [Rooftop Nuisance](https://scryfall.com/search?q=!rooftopnuisance)
- [x] Done -- [Rumor Gatherer](https://scryfall.com/search?q=!rumorgatherer)
- [x] Done -- [Run Out of Town](https://scryfall.com/search?q=!runoutoftown)
- [x] Done -- [Sanctuary Warden](https://scryfall.com/search?q=!sanctuarywarden)
- [x] Done -- [Sanguine Spy](https://scryfall.com/search?q=!sanguinespy)
- [x] Done -- [Scheming Fence](https://scryfall.com/search?q=!schemingfence)
- [x] Done -- [Scuttling Butler](https://scryfall.com/search?q=!scuttlingbutler)
- [x] Done -- [Security Bypass](https://scryfall.com/search?q=!securitybypass)
- [x] Done -- [Security Rhox](https://scryfall.com/search?q=!securityrhox)
- [x] Done -- [Sewer Crocodile](https://scryfall.com/search?q=!sewercrocodile)
- [x] Done -- [Shadow of Mortality](https://scryfall.com/search?q=!shadowofmortality)
- [x] Done -- [Shakedown Heavy](https://scryfall.com/search?q=!shakedownheavy)
- [x] Done -- [Shattered Seraph](https://scryfall.com/search?q=!shatteredseraph)
- [x] Done -- [Sizzling Soloist](https://scryfall.com/search?q=!sizzlingsoloist)
- [x] Done -- [Sky Crier](https://scryfall.com/search?q=!skycrier)
- [x] Done -- [Skybridge Towers](https://scryfall.com/search?q=!skybridgetowers)
- [x] Done -- [Sleep with the Fishes](https://scryfall.com/search?q=!sleepwiththefishes)
- [x] Done -- [Slip Out the Back](https://scryfall.com/search?q=!slipouttheback)
- [x] Done -- [Snooping Newsie](https://scryfall.com/search?q=!snoopingnewsie)
- [x] Done -- [Social Climber](https://scryfall.com/search?q=!socialclimber)
- [x] Done -- [Soul of Emancipation](https://scryfall.com/search?q=!soulofemancipation)
- [x] Done -- [Spara's Adjudicators](https://scryfall.com/search?q=!sparasadjudicators)
- [x] Done -- [Spara's Headquarters](https://scryfall.com/search?q=!sparasheadquarters)
- [x] Done -- [Speakeasy Server](https://scryfall.com/search?q=!speakeasyserver)
- [x] Done -- [Sticky Fingers](https://scryfall.com/search?q=!stickyfingers)
- [x] Done -- [Stimulus Package](https://scryfall.com/search?q=!stimuluspackage)
- [x] Done -- [Strangle](https://scryfall.com/search?q=!strangle)
- [x] Done -- [Structural Assault](https://scryfall.com/search?q=!structuralassault)
- [x] Done -- [Suspicious Bookcase](https://scryfall.com/search?q=!suspiciousbookcase)
- [x] Done -- [Swooping Protector](https://scryfall.com/search?q=!swoopingprotector)
- [x] Done -- [Syndicate Infiltrator](https://scryfall.com/search?q=!syndicateinfiltrator)
- [x] Done -- [Tainted Indulgence](https://scryfall.com/search?q=!taintedindulgence)
- [x] Done -- [Take to the Streets](https://scryfall.com/search?q=!taketothestreets)
- [x] Done -- [Tavern Swindler](https://scryfall.com/search?q=!tavernswindler)
- [x] Done -- [Tenacious Underdog](https://scryfall.com/search?q=!tenaciousunderdog)
- [x] Done -- [Titan of Industry](https://scryfall.com/search?q=!titanofindustry)
- [x] Done -- [Toluz, Clever Conductor](https://scryfall.com/search?q=!toluzcleverconductor)
- [x] Done -- [Topiary Stomper](https://scryfall.com/search?q=!topiarystomper)
- [x] Done -- [Torch Breath](https://scryfall.com/search?q=!torchbreath)
- [x] Done -- [Tramway Station](https://scryfall.com/search?q=!tramwaystation)
- [x] Done -- [Undercover Operative](https://scryfall.com/search?q=!undercoveroperative)
- [x] Done -- [Unleash the Inferno](https://scryfall.com/search?q=!unleashtheinferno)
- [x] Done -- [Unlicensed Hearse](https://scryfall.com/search?q=!unlicensedhearse)
- [x] Done -- [Unlucky Witness](https://scryfall.com/search?q=!unluckywitness)
- [x] Done -- [Urabrask, Heretic Praetor](https://scryfall.com/search?q=!urabraskhereticpraetor)
- [x] Done -- [Vampire Scrivener](https://scryfall.com/search?q=!vampirescrivener)
- [x] Done -- [Venom Connoisseur](https://scryfall.com/search?q=!venomconnoisseur)
- [x] Done -- [Vivien on the Hunt](https://scryfall.com/search?q=!vivienonthehunt)
- [x] Done -- [Voice of the Vermin](https://scryfall.com/search?q=!voiceofthevermin)
- [x] Done -- [Void Rend](https://scryfall.com/search?q=!voidrend)
- [x] Done -- [Warm Welcome](https://scryfall.com/search?q=!warmwelcome)
- [x] Done -- [Waterfront District](https://scryfall.com/search?q=!waterfrontdistrict)
- [x] Done -- [Whack](https://scryfall.com/search?q=!whack)
- [x] Done -- [Widespread Thieving](https://scryfall.com/search?q=!widespreadthieving)
- [x] Done -- [Wingshield Agent](https://scryfall.com/search?q=!wingshieldagent)
- [x] Done -- [Wiretapping](https://scryfall.com/search?q=!wiretapping)
- [x] Done -- [Witness Protection](https://scryfall.com/search?q=!witnessprotection)
- [x] Done -- [Witty Roastmaster](https://scryfall.com/search?q=!wittyroastmaster)
- [x] Done -- [Workshop Warchief](https://scryfall.com/search?q=!workshopwarchief)
- [x] Done -- [Wrecking Crew](https://scryfall.com/search?q=!wreckingcrew)
- [x] Done -- [Xander's Lounge](https://scryfall.com/search?q=!xanderslounge)
- [x] Done -- [Ziatora's Envoy](https://scryfall.com/search?q=!ziatorasenvoy)
- [x] Done -- [Ziatora's Proving Ground](https://scryfall.com/search?q=!ziatorasprovingground)
- [x] Done -- [Ziatora, the Incinerator](https://scryfall.com/search?q=!ziatoratheincinerator)
</details>

**Comment by weirddan455** [comment]
It looks like shield counters already exist on at least one old card [[Palliation Accord]]

Have they said if this is getting errata'd to do the new thing "If it would be dealt damage or destroyed, remove a shield counter from it instead"?

**Comment by theelk801** [comment]
yeah they’re changing the name of the counters on that card, I already took care of it

**Comment by weirddan455** [comment]
Ok cool.  I'll take a shot at getting the shield counter mechanic implemented.

**Comment by hidde-vb** [comment]
I'd like to implement Rafinne's Guidane

**Comment by weirddan455** [comment]
I just read reminder text on Call In a Professional (or "Colin" lol).  "Shield counters don’t prevent this damage as they’re removed"

Does this mean that "damage can't be prevented" effects should get around shield counter protection?  Right now that's not the way it's implemented but should be a fairly simple change if that's the way it's supposed to work.

**Comment by theelk801** [comment]
yeah, they’re supposed to prevent the damage and remove the counter, so if damage can’t be prevented then the counter is still removed

**Comment by weirddan455** [comment]
Well right now, the counter is always getting removed but the creature doesn't get damaged.  It's a replacement effect rather than prevention so it interacts with Colin the same way it does with Lightning Bolt.

Is that right or should the creature be taking the damage *and* removing the counter?

**Comment by theelk801** [comment]
yeah, it should take the damage and remove the counter

**Comment by weirddan455** [comment]
fixed in 21a1cfbea9bb2481c2d090d54107cfd5c0bc1387

**Comment by awjackson** [comment]
Warm Welcome is implemented in my lookattop branch.

**Comment by woshikie** [comment]
Giada, Font of Hope implemented in #8870

**Comment by theelk801** [comment]
That's a wrap, thanks for all the contributions.

**Comment by shadoxxhd** [comment]
Where are the Alchemy cards from New Capenna tracked? I just wanted to import a Brawl deck into xmage, but couldn't find Bind to Secrecy...

**Comment by Grath** [comment]
Alchemy cards are not tracked, similarly to un-cards and playtest cards, due to the substantial differences in how they function relative to real Magic cards. Feel free to take a crack at implementing them, however.
