### ISSUE TITLE
[CLB] - Commander Legends: Battle for Baldur's Gate Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8785]
This checklist is here to help manage the implementation of Commander Legends: Battle for Baldur's Gate. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Ancient Brass Dragon](https://scryfall.com/search?q=!ancientbrassdragon)
- [ ] In progress -- [Elder Brain](https://scryfall.com/search?q=!elderbrain)
- [ ] In progress -- [Wand of Wonder](https://scryfall.com/search?q=!wandofwonder)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"AncientBrassDragon"or!"ElderBrain"or!"WandOfWonder"&unique=cards)
# Implemented Cards

- [x] Done -- [Bountiful Promenade](https://scryfall.com/search?q=!bountifulpromenade)
- [x] Done -- [Fireball](https://scryfall.com/search?q=!fireball)
- [x] Done -- [Lightning Bolt](https://scryfall.com/search?q=!lightningbolt)
- [x] Done -- [Luxury Suite](https://scryfall.com/search?q=!luxurysuite)
- [x] Done -- [Minsc & Boo, Timeless Heroes](https://scryfall.com/search?q=!minsc&bootimelessheroes)
- [x] Done -- [Morphic Pool](https://scryfall.com/search?q=!morphicpool)
- [x] Done -- [Reflecting Pool](https://scryfall.com/search?q=!reflectingpool)
- [x] Done -- [Sea of Clouds](https://scryfall.com/search?q=!seaofclouds)
- [x] Done -- [Spire Garden](https://scryfall.com/search?q=!spiregarden)

**Comment by theelk801** [comment]
Additional tasks: none yet

**Comment by AmeyMirchandani** [comment]
Working on Carnelian Orb Of Dragonkind

**Comment by FreaIsDead** [comment]
I wanna implement "Banishment" :)

**Comment by NicolasCamachoP** [comment]
Working on Jade Orb of Dragonkind!

**Comment by mateoflorido** [comment]
Working on Master Chef :)

**Comment by RJayz** [comment]
I am working on Scion of Halaster

**Comment by RJayz** [comment]
I am working on Gale, Waterdeep Prodigy

**Comment by satchmosanzabar** [comment]
Greetings folks. I kindly ask that someone makes an effort to implement Baeloth Barrityl, Entertainer . I'm looking forward to playing him as a commander.

**Comment by Rowan-Gudmundsson** [comment]
PR up for Deep Gnome Terramancer, Aboleth Spawn, Lae'zel's Acrobatics, and Windshaper Planetar.

**Comment by PCMSec** [comment]
Finished and tested https://github.com/magefree/mage/pull/9865

**Comment by satchmosanzabar** [comment]
> Greetings folks. I kindly ask that someone makes an effort to implement Baeloth Barrityl, Entertainer . I'm looking forward to playing him as a commander.

Thanks for implementing him! Now, can you implement Noble Heritage? That's the background for the commander deck I want to try :)

**Comment by Grath** [comment]
Got Noble Heritage implemented, but a bunch of these pull requests need to be reviewed and merged still.

**Comment by VecchioLorenzo** [comment]
Several cards are marked as in progress in the list above. 
Any update on the progress on Jon Irenicus?

**Comment by zelane** [comment]
[PR](https://github.com/magefree/mage/pull/10277/files) for [Alaundo the Seer](https://scryfall.com/search?q=!alaundotheseer)

**Comment by HaegarTheHorrible** [comment]
Can any Dev please tell us for the "The Initiative" / "Venture" / "Undercity" mechanic:

Which filename must be put in which ZIP file or path, to represent the "The Initiative" & "Undercity" **card images** in the XMage client?

I've tried: 
...\xmage\mage-client\plugins\images\TOK.zip\CLB\The Initiative.full.jpg
...\xmage\mage-client\plugins\images\TOK.zip\CLB\Undercity.full.jpg

But the images won't show up in game.

**Comment by Susucre** [comment]
![monarchimages](https://github.com/magefree/mage/assets/34709007/a16c45e8-c870-49ce-8322-21be6e1a51fb)

This may help? I do not know how images are working.

**Comment by Susucre** [comment]
@HaegarTheHorrible 
![undercity_image](https://github.com/magefree/mage/assets/34709007/c1791938-6857-4542-a3f1-178b066aed3f)

Alright, there is no notion for set for where the client is looking for the image.
This is a `./TOK/undercity.full.jpg`. Will update this post with the others three Dungeons.

**Comment by HaegarTheHorrible** [comment]
Worked for me:
xmage\mage-client\plugins\images\TOK.zip\The Initiative.full.jpg
xmage\mage-client\plugins\images\TOK.zip\Undercity.full.jpg

Although I did put as both images the map of Undercity, because I like to see the available rooms, when I have to make the decision, which way to go:

<img width="768" alt="undercity" src="https://github.com/magefree/mage/assets/100722648/3f4e23c2-53e8-4758-928f-5d28cdc08920">

**Comment by Fyusel** [comment]
PR for [Kagha, Shadow Archdruid](https://github.com/magefree/mage/pull/10919)

Tested with self mill of other cards which are taken into account as well. Further more cards from previous turns are not taken into account.

**Comment by Grath** [comment]
> Any update on Jon Irenicus?

Jon Irenicus was implemented on December 31st, but the current build is from December 23rd. He'll be available next time there's an update.

**Comment by drownik** [comment]
Can any developer check Durnan of the Yawning Portal and Tlincalli Hunter, please?? I see they're still pending since 2022, and nobody has reported being working on them.

Thank you.

**Comment by mybaum** [comment]
any update on Alaundo the Seer?

**Comment by DDriggs00** [comment]
How long does something have to be in progress for with no updates before it is no longer considered in progress?

**Comment by Grath** [comment]
'in progress' isn't 'nobody else is allowed to touch this', it's 'I think I'm gonna do this, so if you work on it that might be wasted effort'.

**Comment by AntonioLeonan** [comment]
Any update on Alaundo the Seer?
