### ISSUE TITLE
NCC - New Capenna Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8823]
This checklist is here to help manage the implementation of New Capenna Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [x] In progress -- [Henzie "Toolbox" Torre](https://scryfall.com/search?q=!henzietoolboxtorre)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"HenzieToolboxTorre"&unique=cards)
# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Aerial Extortionist](https://scryfall.com/search?q=!aerialextortionist)
- [x] Done -- [Aether Snap](https://scryfall.com/search?q=!aethersnap)
- [x] Done -- [Agent's Toolkit](https://scryfall.com/search?q=!agentstoolkit)
- [x] Done -- [Agitator Ant](https://scryfall.com/search?q=!agitatorant)
- [x] Done -- [Ajani Unyielding](https://scryfall.com/search?q=!ajaniunyielding)
- [x] Done -- [Alela, Artful Provocateur](https://scryfall.com/search?q=!alelaartfulprovocateur)
- [x] Done -- [Angelic Sleuth](https://scryfall.com/search?q=!angelicsleuth)
- [x] Done -- [Anhelo, the Painter](https://scryfall.com/search?q=!anhelothepainter)
- [x] Done -- [Arasta of the Endless Web](https://scryfall.com/search?q=!arastaoftheendlessweb)
- [x] Done -- [Arcane Sanctum](https://scryfall.com/search?q=!arcanesanctum)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Archon of Coronation](https://scryfall.com/search?q=!archonofcoronation)
- [x] Done -- [Army of the Damned](https://scryfall.com/search?q=!armyofthedamned)
- [x] Done -- [Artifact Mutation](https://scryfall.com/search?q=!artifactmutation)
- [x] Done -- [Artisan of Kozilek](https://scryfall.com/search?q=!artisanofkozilek)
- [x] Done -- [Ash Barrens](https://scryfall.com/search?q=!ashbarrens)
- [x] Done -- [Assemble the Legion](https://scryfall.com/search?q=!assemblethelegion)
- [x] Done -- [Audacious Swap](https://scryfall.com/search?q=!audaciousswap)
- [x] Done -- [Aura Mutation](https://scryfall.com/search?q=!auramutation)
- [x] Done -- [Austere Command](https://scryfall.com/search?q=!austerecommand)
- [x] Done -- [Aven Courier](https://scryfall.com/search?q=!avencourier)
- [x] Done -- [Aven Mimeomancer](https://scryfall.com/search?q=!avenmimeomancer)
- [x] Done -- [Avenger of Zendikar](https://scryfall.com/search?q=!avengerofzendikar)
- [x] Done -- [Avenging Huntbonder](https://scryfall.com/search?q=!avenginghuntbonder)
- [x] Done -- [Awakening Zone](https://scryfall.com/search?q=!awakeningzone)
- [x] Done -- [Azorius Signet](https://scryfall.com/search?q=!azoriussignet)
- [x] Done -- [Bant Charm](https://scryfall.com/search?q=!bantcharm)
- [x] Done -- [Bant Panorama](https://scryfall.com/search?q=!bantpanorama)
- [x] Done -- [Beast Within](https://scryfall.com/search?q=!beastwithin)
- [x] Done -- [Beastmaster Ascension](https://scryfall.com/search?q=!beastmasterascension)
- [x] Done -- [Bedevil](https://scryfall.com/search?q=!bedevil)
- [x] Done -- [Bellowing Mauler](https://scryfall.com/search?q=!bellowingmauler)
- [x] Done -- [Bennie Bracks, Zoologist](https://scryfall.com/search?q=!benniebrackszoologist)
- [x] Done -- [Bess, Soul Nourisher](https://scryfall.com/search?q=!besssoulnourisher)
- [x] Done -- [Blasphemous Act](https://scryfall.com/search?q=!blasphemousact)
- [x] Done -- [Blighted Woodland](https://scryfall.com/search?q=!blightedwoodland)
- [x] Done -- [Bloodsoaked Champion](https://scryfall.com/search?q=!bloodsoakedchampion)
- [x] Done -- [Bloodthirsty Blade](https://scryfall.com/search?q=!bloodthirstyblade)
- [x] Done -- [Body Count](https://scryfall.com/search?q=!bodycount)
- [x] Done -- [Boros Charm](https://scryfall.com/search?q=!boroscharm)
- [x] Done -- [Boss's Chauffeur](https://scryfall.com/search?q=!bossschauffeur)
- [x] Done -- [Boxing Ring](https://scryfall.com/search?q=!boxingring)
- [x] Done -- [Bribe Taker](https://scryfall.com/search?q=!bribetaker)
- [x] Done -- [Brokers Confluence](https://scryfall.com/search?q=!brokersconfluence)
- [x] Done -- [Cabaretti Confluence](https://scryfall.com/search?q=!cabaretticonfluence)
- [x] Done -- [Caldaia Guardian](https://scryfall.com/search?q=!caldaiaguardian)
- [x] Done -- [Call the Coppercoats](https://scryfall.com/search?q=!callthecoppercoats)
- [x] Done -- [Call the Skybreaker](https://scryfall.com/search?q=!calltheskybreaker)
- [x] Done -- [Camaraderie](https://scryfall.com/search?q=!camaraderie)
- [x] Done -- [Canopy Vista](https://scryfall.com/search?q=!canopyvista)
- [x] Done -- [Cascade Bluffs](https://scryfall.com/search?q=!cascadebluffs)
- [x] Done -- [Castle Ardenvale](https://scryfall.com/search?q=!castleardenvale)
- [x] Done -- [Castle Embereth](https://scryfall.com/search?q=!castleembereth)
- [x] Done -- [Cephalid Facetaker](https://scryfall.com/search?q=!cephalidfacetaker)
- [x] Done -- [Chain Reaction](https://scryfall.com/search?q=!chainreaction)
- [x] Done -- [Champion of Lambholt](https://scryfall.com/search?q=!championoflambholt)
- [x] Done -- [Champion of Wits](https://scryfall.com/search?q=!championofwits)
- [x] Done -- [Change of Plans](https://scryfall.com/search?q=!changeofplans)
- [x] Done -- [Chaos Warp](https://scryfall.com/search?q=!chaoswarp)
- [x] Done -- [Chasm Skulker](https://scryfall.com/search?q=!chasmskulker)
- [x] Done -- [Choked Estuary](https://scryfall.com/search?q=!chokedestuary)
- [x] Done -- [Cinder Glade](https://scryfall.com/search?q=!cinderglade)
- [x] Done -- [Clone Legion](https://scryfall.com/search?q=!clonelegion)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=!commanderssphere)
- [x] Done -- [Commit // Memory](https://scryfall.com/search?q=!commitmemory)
- [x] Done -- [Contractual Safeguard](https://scryfall.com/search?q=!contractualsafeguard)
- [x] Done -- [Crash the Party](https://scryfall.com/search?q=!crashtheparty)
- [x] Done -- [Creeping Tar Pit](https://scryfall.com/search?q=!creepingtarpit)
- [x] Done -- [Crumbling Necropolis](https://scryfall.com/search?q=!crumblingnecropolis)
- [x] Done -- [Cryptic Pursuit](https://scryfall.com/search?q=!crypticpursuit)
- [x] Done -- [Crystalline Giant](https://scryfall.com/search?q=!crystallinegiant)
- [x] Done -- [Cultivate](https://scryfall.com/search?q=!cultivate)
- [x] Done -- [Currency Converter](https://scryfall.com/search?q=!currencyconverter)
- [x] Done -- [Custodi Lich](https://scryfall.com/search?q=!custodilich)
- [x] Done -- [Damnable Pact](https://scryfall.com/search?q=!damnablepact)
- [x] Done -- [Damning Verdict](https://scryfall.com/search?q=!damningverdict)
- [x] Done -- [Daring Saboteur](https://scryfall.com/search?q=!daringsaboteur)
- [x] Done -- [Darkwater Catacombs](https://scryfall.com/search?q=!darkwatercatacombs)
- [x] Done -- [Daxos of Meletis](https://scryfall.com/search?q=!daxosofmeletis)
- [x] Done -- [Deathbringer Regent](https://scryfall.com/search?q=!deathbringerregent)
- [x] Done -- [Deathreap Ritual](https://scryfall.com/search?q=!deathreapritual)
- [x] Done -- [Declaration in Stone](https://scryfall.com/search?q=!declarationinstone)
- [x] Done -- [Deep Analysis](https://scryfall.com/search?q=!deepanalysis)
- [x] Done -- [Denry Klin, Editor in Chief](https://scryfall.com/search?q=!denryklineditorinchief)
- [x] Done -- [Determined Iteration](https://scryfall.com/search?q=!determinediteration)
- [x] Done -- [Devoted Druid](https://scryfall.com/search?q=!devoteddruid)
- [x] Done -- [Dig Through Time](https://scryfall.com/search?q=!digthroughtime)
- [x] Done -- [Dimir Signet](https://scryfall.com/search?q=!dimirsignet)
- [x] Done -- [Disciple of Bolas](https://scryfall.com/search?q=!discipleofbolas)
- [x] Done -- [Dodgy Jalopy](https://scryfall.com/search?q=!dodgyjalopy)
- [x] Done -- [Dogged Detective](https://scryfall.com/search?q=!doggeddetective)
- [x] Done -- [Double Vision](https://scryfall.com/search?q=!doublevision)
- [x] Done -- [Dragonlord Ojutai](https://scryfall.com/search?q=!dragonlordojutai)
- [x] Done -- [Drana, Liberator of Malakir](https://scryfall.com/search?q=!dranaliberatorofmalakir)
- [x] Done -- [Drawn from Dreams](https://scryfall.com/search?q=!drawnfromdreams)
- [x] Done -- [Dread Summons](https://scryfall.com/search?q=!dreadsummons)
- [x] Done -- [Duelist's Heritage](https://scryfall.com/search?q=!duelistsheritage)
- [x] Done -- [Dusk // Dawn](https://scryfall.com/search?q=!duskdawn)
- [x] Done -- [Esper Panorama](https://scryfall.com/search?q=!esperpanorama)
- [x] Done -- [Etali, Primal Storm](https://scryfall.com/search?q=!etaliprimalstorm)
- [x] Done -- [Everflowing Chalice](https://scryfall.com/search?q=!everflowingchalice)
- [x] Done -- [Evolution Sage](https://scryfall.com/search?q=!evolutionsage)
- [x] Done -- [Evolutionary Leap](https://scryfall.com/search?q=!evolutionaryleap)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Explore](https://scryfall.com/search?q=!explore)
- [x] Done -- [Extravagant Replication](https://scryfall.com/search?q=!extravagantreplication)
- [x] Done -- [Fact or Fiction](https://scryfall.com/search?q=!factorfiction)
- [x] Done -- [Fallen Shinobi](https://scryfall.com/search?q=!fallenshinobi)
- [x] Done -- [False Floor](https://scryfall.com/search?q=!falsefloor)
- [x] Done -- [Family's Favor](https://scryfall.com/search?q=!familysfavor)
- [x] Done -- [Farseek](https://scryfall.com/search?q=!farseek)
- [x] Done -- [Fathom Mage](https://scryfall.com/search?q=!fathommage)
- [x] Done -- [Feed the Swarm](https://scryfall.com/search?q=!feedtheswarm)
- [x] Done -- [Felidar Retreat](https://scryfall.com/search?q=!felidarretreat)
- [x] Done -- [Fell the Mighty](https://scryfall.com/search?q=!fellthemighty)
- [x] Done -- [Fellwar Stone](https://scryfall.com/search?q=!fellwarstone)
- [x] Done -- [Fetid Heath](https://scryfall.com/search?q=!fetidheath)
- [x] Done -- [First Responder](https://scryfall.com/search?q=!firstresponder)
- [x] Done -- [Flawless Forgery](https://scryfall.com/search?q=!flawlessforgery)
- [x] Done -- [Flooded Grove](https://scryfall.com/search?q=!floodedgrove)
- [x] Done -- [Foreboding Ruins](https://scryfall.com/search?q=!forebodingruins)
- [x] Done -- [Forgotten Ancient](https://scryfall.com/search?q=!forgottenancient)
- [x] Done -- [Fortified Village](https://scryfall.com/search?q=!fortifiedvillage)
- [x] Done -- [Frantic Search](https://scryfall.com/search?q=!franticsearch)
- [x] Done -- [Gahiji, Honored One](https://scryfall.com/search?q=!gahijihonoredone)
- [x] Done -- [Game Trail](https://scryfall.com/search?q=!gametrail)
- [x] Done -- [Garruk's Uprising](https://scryfall.com/search?q=!garruksuprising)
- [x] Done -- [Gavel of the Righteous](https://scryfall.com/search?q=!gaveloftherighteous)
- [x] Done -- [Gavony Township](https://scryfall.com/search?q=!gavonytownship)
- [x] Done -- [Generous Gift](https://scryfall.com/search?q=!generousgift)
- [x] Done -- [Ghostly Pilferer](https://scryfall.com/search?q=!ghostlypilferer)
- [x] Done -- [Giant Adephage](https://scryfall.com/search?q=!giantadephage)
- [x] Done -- [Goblin Electromancer](https://scryfall.com/search?q=!goblinelectromancer)
- [x] Done -- [Grand Crescendo](https://scryfall.com/search?q=!grandcrescendo)
- [x] Done -- [Grateful Apparition](https://scryfall.com/search?q=!gratefulapparition)
- [x] Done -- [Graveblade Marauder](https://scryfall.com/search?q=!graveblademarauder)
- [x] Done -- [Greenwarden of Murasa](https://scryfall.com/search?q=!greenwardenofmurasa)
- [x] Done -- [Grime Gorger](https://scryfall.com/search?q=!grimegorger)
- [x] Done -- [Grixis Panorama](https://scryfall.com/search?q=!grixispanorama)
- [x] Done -- [Harmonize](https://scryfall.com/search?q=!harmonize)
- [x] Done -- [Hex](https://scryfall.com/search?q=!hex)
- [x] Done -- [Hoofprints of the Stag](https://scryfall.com/search?q=!hoofprintsofthestag)
- [x] Done -- [Identity Thief](https://scryfall.com/search?q=!identitythief)
- [x] Done -- [Idol of Oblivion](https://scryfall.com/search?q=!idolofoblivion)
- [x] Done -- [In Too Deep](https://scryfall.com/search?q=!intoodeep)
- [x] Done -- [Incubation Druid](https://scryfall.com/search?q=!incubationdruid)
- [x] Done -- [Indrik Stomphowler](https://scryfall.com/search?q=!indrikstomphowler)
- [x] Done -- [Indulge // Excess](https://scryfall.com/search?q=!indulgeexcess)
- [x] Done -- [Industrial Advancement](https://scryfall.com/search?q=!industrialadvancement)
- [x] Done -- [Inferno Titan](https://scryfall.com/search?q=!infernotitan)
- [x] Done -- [Inkfathom Witch](https://scryfall.com/search?q=!inkfathomwitch)
- [x] Done -- [Intangible Virtue](https://scryfall.com/search?q=!intangiblevirtue)
- [x] Done -- [Izzet Signet](https://scryfall.com/search?q=!izzetsignet)
- [x] Done -- [Jailbreak](https://scryfall.com/search?q=!jailbreak)
- [x] Done -- [Jenara, Asura of War](https://scryfall.com/search?q=!jenaraasuraofwar)
- [x] Done -- [Jolene, the Plunder Queen](https://scryfall.com/search?q=!jolenetheplunderqueen)
- [x] Done -- [Jund Panorama](https://scryfall.com/search?q=!jundpanorama)
- [x] Done -- [Jungle Shrine](https://scryfall.com/search?q=!jungleshrine)
- [x] Done -- [Kamiz, Obscura Oculus](https://scryfall.com/search?q=!kamizobscuraoculus)
- [x] Done -- [Karn's Bastion](https://scryfall.com/search?q=!karnsbastion)
- [x] Done -- [Kazuul, Tyrant of the Cliffs](https://scryfall.com/search?q=!kazuultyrantofthecliffs)
- [x] Done -- [Kess, Dissident Mage](https://scryfall.com/search?q=!kessdissidentmage)
- [x] Done -- [Kessig Wolf Run](https://scryfall.com/search?q=!kessigwolfrun)
- [x] Done -- [Killer Service](https://scryfall.com/search?q=!killerservice)
- [x] Done -- [Kitt Kanto, Mayhem Diva](https://scryfall.com/search?q=!kittkantomayhemdiva)
- [x] Done -- [Kodama's Reach](https://scryfall.com/search?q=!kodamasreach)
- [x] Done -- [Kresh the Bloodbraided](https://scryfall.com/search?q=!kreshthebloodbraided)
- [x] Done -- [Kros, Defense Contractor](https://scryfall.com/search?q=!krosdefensecontractor)
- [x] Done -- [Leafkin Druid](https://scryfall.com/search?q=!leafkindruid)
- [x] Done -- [Lethal Scheme](https://scryfall.com/search?q=!lethalscheme)
- [x] Done -- [Life Insurance](https://scryfall.com/search?q=!lifeinsurance)
- [x] Done -- [Life of the Party](https://scryfall.com/search?q=!lifeoftheparty)
- [x] Done -- [Life's Legacy](https://scryfall.com/search?q=!lifeslegacy)
- [x] Done -- [Lifecrafter's Bestiary](https://scryfall.com/search?q=!lifecraftersbestiary)
- [x] Done -- [Lightning Greaves](https://scryfall.com/search?q=!lightninggreaves)
- [x] Done -- [Littjara Mirrorlake](https://scryfall.com/search?q=!littjaramirrorlake)
- [x] Done -- [Llanowar Reborn](https://scryfall.com/search?q=!llanowarreborn)
- [x] Done -- [Looter il-Kor](https://scryfall.com/search?q=!looterilkor)
- [x] Done -- [Luminarch Aspirant](https://scryfall.com/search?q=!luminarchaspirant)
- [x] Done -- [Maestros Confluence](https://scryfall.com/search?q=!maestrosconfluence)
- [x] Done -- [Magus of the Wheel](https://scryfall.com/search?q=!magusofthewheel)
- [x] Done -- [Make an Example](https://scryfall.com/search?q=!makeanexample)
- [x] Done -- [March of the Multitudes](https://scryfall.com/search?q=!marchofthemultitudes)
- [x] Done -- [Mari, the Killing Quill](https://scryfall.com/search?q=!marithekillingquill)
- [x] Done -- [Martial Coup](https://scryfall.com/search?q=!martialcoup)
- [x] Done -- [Mask of Riddles](https://scryfall.com/search?q=!maskofriddles)
- [x] Done -- [Mask of the Schemer](https://scryfall.com/search?q=!maskoftheschemer)
- [x] Done -- [Master of Ceremonies](https://scryfall.com/search?q=!masterofceremonies)
- [x] Done -- [Mezzio Mugger](https://scryfall.com/search?q=!mezziomugger)
- [x] Done -- [Midnight Clock](https://scryfall.com/search?q=!midnightclock)
- [x] Done -- [Migration Path](https://scryfall.com/search?q=!migrationpath)
- [x] Done -- [Mimic Vat](https://scryfall.com/search?q=!mimicvat)
- [x] Done -- [Misfortune Teller](https://scryfall.com/search?q=!misfortuneteller)
- [x] Done -- [Mitotic Slime](https://scryfall.com/search?q=!mitoticslime)
- [x] Done -- [Mossfire Valley](https://scryfall.com/search?q=!mossfirevalley)
- [x] Done -- [Mosswort Bridge](https://scryfall.com/search?q=!mosswortbridge)
- [x] Done -- [Myriad Landscape](https://scryfall.com/search?q=!myriadlandscape)
- [x] Done -- [Mystic Confluence](https://scryfall.com/search?q=!mysticconfluence)
- [x] Done -- [Nadir Kraken](https://scryfall.com/search?q=!nadirkraken)
- [x] Done -- [Naya Panorama](https://scryfall.com/search?q=!nayapanorama)
- [x] Done -- [Nesting Grounds](https://scryfall.com/search?q=!nestinggrounds)
- [x] Done -- [Next of Kin](https://scryfall.com/search?q=!nextofkin)
- [x] Done -- [Nightmare Unmaking](https://scryfall.com/search?q=!nightmareunmaking)
- [x] Done -- [Noxious Gearhulk](https://scryfall.com/search?q=!noxiousgearhulk)
- [x] Done -- [Oblivion Stone](https://scryfall.com/search?q=!oblivionstone)
- [x] Done -- [Obscura Confluence](https://scryfall.com/search?q=!obscuraconfluence)
- [x] Done -- [Oracle's Vault](https://scryfall.com/search?q=!oraclesvault)
- [x] Done -- [Orzhov Advokist](https://scryfall.com/search?q=!orzhovadvokist)
- [x] Done -- [Orzhov Signet](https://scryfall.com/search?q=!orzhovsignet)
- [x] Done -- [Oskar, Rubbish Reclaimer](https://scryfall.com/search?q=!oskarrubbishreclaimer)
- [x] Done -- [Outpost Siege](https://scryfall.com/search?q=!outpostsiege)
- [x] Done -- [Overgrown Battlement](https://scryfall.com/search?q=!overgrownbattlement)
- [x] Done -- [Painful Truths](https://scryfall.com/search?q=!painfultruths)
- [x] Done -- [Park Heights Maverick](https://scryfall.com/search?q=!parkheightsmaverick)
- [x] Done -- [Parnesse, the Subtle Brush](https://scryfall.com/search?q=!parnessethesubtlebrush)
- [x] Done -- [Path of Ancestry](https://scryfall.com/search?q=!pathofancestry)
- [x] Done -- [Path to Exile](https://scryfall.com/search?q=!pathtoexile)
- [x] Done -- [Perrie, the Pulverizer](https://scryfall.com/search?q=!perriethepulverizer)
- [x] Done -- [Phabine, Boss's Confidant](https://scryfall.com/search?q=!phabinebosssconfidant)
- [x] Done -- [Planar Outburst](https://scryfall.com/search?q=!planaroutburst)
- [x] Done -- [Ponder](https://scryfall.com/search?q=!ponder)
- [x] Done -- [Port Town](https://scryfall.com/search?q=!porttown)
- [x] Done -- [Power Conduit](https://scryfall.com/search?q=!powerconduit)
- [x] Done -- [Prairie Stream](https://scryfall.com/search?q=!prairiestream)
- [x] Done -- [Preordain](https://scryfall.com/search?q=!preordain)
- [x] Done -- [Primal Empathy](https://scryfall.com/search?q=!primalempathy)
- [x] Done -- [Profane Command](https://scryfall.com/search?q=!profanecommand)
- [x] Done -- [Prosperous Partnership](https://scryfall.com/search?q=!prosperouspartnership)
- [x] Done -- [Protection Racket](https://scryfall.com/search?q=!protectionracket)
- [x] Done -- [Puppeteer Clique](https://scryfall.com/search?q=!puppeteerclique)
- [x] Done -- [Quietus Spike](https://scryfall.com/search?q=!quietusspike)
- [x] Done -- [Rain of Riches](https://scryfall.com/search?q=!rainofriches)
- [x] Done -- [Rakdos Signet](https://scryfall.com/search?q=!rakdossignet)
- [x] Done -- [Rampant Growth](https://scryfall.com/search?q=!rampantgrowth)
- [x] Done -- [Reign of the Pit](https://scryfall.com/search?q=!reignofthepit)
- [x] Done -- [Rekindling Phoenix](https://scryfall.com/search?q=!rekindlingphoenix)
- [x] Done -- [Resourceful Defense](https://scryfall.com/search?q=!resourcefuldefense)
- [x] Done -- [Rishkar's Expertise](https://scryfall.com/search?q=!rishkarsexpertise)
- [x] Done -- [Rishkar, Peema Renegade](https://scryfall.com/search?q=!rishkarpeemarenegade)
- [x] Done -- [Rite of the Raging Storm](https://scryfall.com/search?q=!riteoftheragingstorm)
- [x] Done -- [River's Rebuke](https://scryfall.com/search?q=!riversrebuke)
- [x] Done -- [Riveteers Confluence](https://scryfall.com/search?q=!riveteersconfluence)
- [x] Done -- [Roalesk, Apex Hybrid](https://scryfall.com/search?q=!roaleskapexhybrid)
- [x] Done -- [Rogue's Passage](https://scryfall.com/search?q=!roguespassage)
- [x] Done -- [Rose Room Treasurer](https://scryfall.com/search?q=!roseroomtreasurer)
- [x] Done -- [Rugged Prairie](https://scryfall.com/search?q=!ruggedprairie)
- [x] Done -- [Sakura-Tribe Elder](https://scryfall.com/search?q=!sakuratribeelder)
- [x] Done -- [Sandwurm Convergence](https://scryfall.com/search?q=!sandwurmconvergence)
- [x] Done -- [Savage Lands](https://scryfall.com/search?q=!savagelands)
- [x] Done -- [Scavenging Ooze](https://scryfall.com/search?q=!scavengingooze)
- [x] Done -- [Scepter of Celebration](https://scryfall.com/search?q=!scepterofcelebration)
- [x] Done -- [Scute Swarm](https://scryfall.com/search?q=!scuteswarm)
- [x] Done -- [Seaside Citadel](https://scryfall.com/search?q=!seasidecitadel)
- [x] Done -- [Seize the Spotlight](https://scryfall.com/search?q=!seizethespotlight)
- [x] Done -- [Selvala, Explorer Returned](https://scryfall.com/search?q=!selvalaexplorerreturned)
- [x] Done -- [Sever the Bloodline](https://scryfall.com/search?q=!severthebloodline)
- [x] Done -- [Shadowblood Ridge](https://scryfall.com/search?q=!shadowbloodridge)
- [x] Done -- [Shadowmage Infiltrator](https://scryfall.com/search?q=!shadowmageinfiltrator)
- [x] Done -- [Shamanic Revelation](https://scryfall.com/search?q=!shamanicrevelation)
- [x] Done -- [Shield Broker](https://scryfall.com/search?q=!shieldbroker)
- [x] Done -- [Silent-Blade Oni](https://scryfall.com/search?q=!silentbladeoni)
- [x] Done -- [Sinister Concierge](https://scryfall.com/search?q=!sinisterconcierge)
- [x] Done -- [Skyboon Evangelist](https://scryfall.com/search?q=!skyboonevangelist)
- [x] Done -- [Skyclave Shade](https://scryfall.com/search?q=!skyclaveshade)
- [x] Done -- [Skycloud Expanse](https://scryfall.com/search?q=!skycloudexpanse)
- [x] Done -- [Skyship Plunderer](https://scryfall.com/search?q=!skyshipplunderer)
- [x] Done -- [Skyway Robber](https://scryfall.com/search?q=!skywayrobber)
- [x] Done -- [Slippery Bogbonder](https://scryfall.com/search?q=!slipperybogbonder)
- [x] Done -- [Smoldering Marsh](https://scryfall.com/search?q=!smolderingmarsh)
- [x] Done -- [Smuggler's Buggy](https://scryfall.com/search?q=!smugglersbuggy)
- [x] Done -- [Smuggler's Share](https://scryfall.com/search?q=!smugglersshare)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Solemn Simulacrum](https://scryfall.com/search?q=!solemnsimulacrum)
- [x] Done -- [Spellbinding Soprano](https://scryfall.com/search?q=!spellbindingsoprano)
- [x] Done -- [Spinerock Knoll](https://scryfall.com/search?q=!spinerockknoll)
- [x] Done -- [Spiteful Repossession](https://scryfall.com/search?q=!spitefulrepossession)
- [x] Done -- [Squee, the Immortal](https://scryfall.com/search?q=!squeetheimmortal)
- [x] Done -- [Stalking Vengeance](https://scryfall.com/search?q=!stalkingvengeance)
- [x] Done -- [Steelbane Hydra](https://scryfall.com/search?q=!steelbanehydra)
- [x] Done -- [Stolen Identity](https://scryfall.com/search?q=!stolenidentity)
- [x] Done -- [Storm of Forms](https://scryfall.com/search?q=!stormofforms)
- [x] Done -- [Strionic Resonator](https://scryfall.com/search?q=!strionicresonator)
- [x] Done -- [Sun Titan](https://scryfall.com/search?q=!suntitan)
- [x] Done -- [Sungrass Prairie](https://scryfall.com/search?q=!sungrassprairie)
- [x] Done -- [Sunken Hollow](https://scryfall.com/search?q=!sunkenhollow)
- [x] Done -- [Swiftfoot Boots](https://scryfall.com/search?q=!swiftfootboots)
- [x] Done -- [Swindler's Scheme](https://scryfall.com/search?q=!swindlersscheme)
- [x] Done -- [Swords to Plowshares](https://scryfall.com/search?q=!swordstoplowshares)
- [x] Done -- [Sylvan Offering](https://scryfall.com/search?q=!sylvanoffering)
- [x] Done -- [Syrix, Carrier of the Flame](https://scryfall.com/search?q=!syrixcarrieroftheflame)
- [x] Done -- [Talrand's Invocation](https://scryfall.com/search?q=!talrandsinvocation)
- [x] Done -- [Temple of Epiphany](https://scryfall.com/search?q=!templeofepiphany)
- [x] Done -- [Temple of Malady](https://scryfall.com/search?q=!templeofmalady)
- [x] Done -- [Temple of Mystery](https://scryfall.com/search?q=!templeofmystery)
- [x] Done -- [Temple of Silence](https://scryfall.com/search?q=!templeofsilence)
- [x] Done -- [Temple of Triumph](https://scryfall.com/search?q=!templeoftriumph)
- [x] Done -- [Temple of the False God](https://scryfall.com/search?q=!templeofthefalsegod)
- [x] Done -- [Temur Sabertooth](https://scryfall.com/search?q=!temursabertooth)
- [x] Done -- [Tenuous Truce](https://scryfall.com/search?q=!tenuoustruce)
- [x] Done -- [Terminate](https://scryfall.com/search?q=!terminate)
- [x] Done -- [Tezzeret's Gambit](https://scryfall.com/search?q=!tezzeretsgambit)
- [x] Done -- [The Beamtown Bullies](https://scryfall.com/search?q=!thebeamtownbullies)
- [x] Done -- [Thief of Sanity](https://scryfall.com/search?q=!thiefofsanity)
- [x] Done -- [Thragtusk](https://scryfall.com/search?q=!thragtusk)
- [x] Done -- [Threefold Signal](https://scryfall.com/search?q=!threefoldsignal)
- [x] Done -- [Thriving Bluff](https://scryfall.com/search?q=!thrivingbluff)
- [x] Done -- [Thriving Grove](https://scryfall.com/search?q=!thrivinggrove)
- [x] Done -- [Thriving Heath](https://scryfall.com/search?q=!thrivingheath)
- [x] Done -- [Thriving Isle](https://scryfall.com/search?q=!thrivingisle)
- [x] Done -- [Thriving Moor](https://scryfall.com/search?q=!thrivingmoor)
- [x] Done -- [Thrummingbird](https://scryfall.com/search?q=!thrummingbird)
- [x] Done -- [Thunderfoot Baloth](https://scryfall.com/search?q=!thunderfootbaloth)
- [x] Done -- [Tivit, Seller of Secrets](https://scryfall.com/search?q=!tivitsellerofsecrets)
- [x] Done -- [Together Forever](https://scryfall.com/search?q=!togetherforever)
- [x] Done -- [Treasure Cruise](https://scryfall.com/search?q=!treasurecruise)
- [x] Done -- [Treeshaker Chimera](https://scryfall.com/search?q=!treeshakerchimera)
- [x] Done -- [Turf War](https://scryfall.com/search?q=!turfwar)
- [x] Done -- [Twilight Mire](https://scryfall.com/search?q=!twilightmire)
- [x] Done -- [Twinning Staff](https://scryfall.com/search?q=!twinningstaff)
- [x] Done -- [Urban Evolution](https://scryfall.com/search?q=!urbanevolution)
- [x] Done -- [Utter End](https://scryfall.com/search?q=!utterend)
- [x] Done -- [Vazi, Keen Negotiator](https://scryfall.com/search?q=!vazikeennegotiator)
- [x] Done -- [Victimize](https://scryfall.com/search?q=!victimize)
- [x] Done -- [Vivid Creek](https://scryfall.com/search?q=!vividcreek)
- [x] Done -- [Vivid Grove](https://scryfall.com/search?q=!vividgrove)
- [x] Done -- [Vivid Meadow](https://scryfall.com/search?q=!vividmeadow)
- [x] Done -- [Vivien's Stampede](https://scryfall.com/search?q=!viviensstampede)
- [x] Done -- [Vorel of the Hull Clade](https://scryfall.com/search?q=!vorelofthehullclade)
- [x] Done -- [Wall of Roots](https://scryfall.com/search?q=!wallofroots)
- [x] Done -- [Warstorm Surge](https://scryfall.com/search?q=!warstormsurge)
- [x] Done -- [Waste Management](https://scryfall.com/search?q=!wastemanagement)
- [x] Done -- [Wave of Rats](https://scryfall.com/search?q=!waveofrats)
- [x] Done -- [Wayfarer's Bauble](https://scryfall.com/search?q=!wayfarersbauble)
- [x] Done -- [Weathered Sentinels](https://scryfall.com/search?q=!weatheredsentinels)
- [x] Done -- [Whirler Rogue](https://scryfall.com/search?q=!whirlerrogue)
- [x] Done -- [Wickerbough Elder](https://scryfall.com/search?q=!wickerboughelder)
- [x] Done -- [Windbrisk Heights](https://scryfall.com/search?q=!windbriskheights)
- [x] Done -- [Windgrace's Judgment](https://scryfall.com/search?q=!windgracesjudgment)
- [x] Done -- [Wingspan Mentor](https://scryfall.com/search?q=!wingspanmentor)
- [x] Done -- [Woe Strider](https://scryfall.com/search?q=!woestrider)
- [x] Done -- [Wood Elves](https://scryfall.com/search?q=!woodelves)
- [x] Done -- [Woodfall Primus](https://scryfall.com/search?q=!woodfallprimus)
- [x] Done -- [World Shaper](https://scryfall.com/search?q=!worldshaper)
- [x] Done -- [Wrexial, the Risen Deep](https://scryfall.com/search?q=!wrexialtherisendeep)
- [x] Done -- [Writ of Return](https://scryfall.com/search?q=!writofreturn)
- [x] Done -- [Xander's Pact](https://scryfall.com/search?q=!xanderspact)
- [x] Done -- [Zndrsplt's Judgment](https://scryfall.com/search?q=!zndrspltsjudgment)
- [x] Done -- [Zurzoth, Chaos Rider](https://scryfall.com/search?q=!zurzothchaosrider)
</details>

**Comment by theelk801** [comment]
Additional tasks: none yet

**Comment by Susucre** [comment]
Working on

- Jolene, the Plunder Queen: [Pull Request](https://github.com/magefree/mage/pull/9093)
- Lethal Scheme

**Comment by Slanman3755** [comment]
https://github.com/magefree/mage/pull/9295

**Comment by arketec** [comment]
The Beamtown Bullies #9378

**Comment by Hat70ri** [comment]
Will Henzie be implemented?

**Comment by alexander-novo** [comment]
> Will Henzie be implemented?

It is in progress.
