### ISSUE TITLE
40K - Warhammer 40,000 Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8954]
This checklist is here to help manage the implementation of Warhammer 40,000. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Abaddon the Despoiler](https://scryfall.com/search?q=!abaddonthedespoiler)
- [ ] In progress -- [Blood for the Blood God!](https://scryfall.com/search?q=!bloodforthebloodgod!)
- [ ] In progress -- [Vanguard Suppressor](https://scryfall.com/search?q=!vanguardsuppressor)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"AbaddonTheDespoiler"or!"BloodForTheBloodGod!"or!"VanguardSuppressor"&unique=cards)
# Implemented Cards

- [x] Done -- [Fabricate](https://scryfall.com/search?q=!fabricate)

**Comment by theelk801** [comment]
Additional tasks:

- [ ] Implement Squad mechanic

**Comment by Susucre** [comment]
I am attempting to implement the squad mechanic.
There is a lot care to have around copiable value and link an etb trigger to the squad cost being paid (similar to kicker/multikicker).
Will drop a pull request soon, hopefully with everything working and unit tested.

**Comment by timhae** [comment]
Any updates on the cards that are listed as in progress? I started with Anrakyr but it needs something like `CardUtil.castSpellWithAttributesForFreeOrLife` and `mage.abilities.effects.common.cost.CastFromHandOrGraveyardForLifeEffect`, if nobody is working on that at the moment, I will continue to do so.

**Comment by stevedavidmusic** [comment]
Request to implement Triumph of Saint Katherine if there isn't any particular blocker on a technical level. The card currently sees play in Legacy miracles.

**Comment by Chewbaklava** [comment]
> Request to implement Triumph of Saint Katherine if there isn't any particular blocker on a technical level. The card currently sees play in Legacy miracles.

+1

**Comment by xenohedron** [comment]
#10125 pending review to implement Triumph of Saint Katherine

**Comment by Sidorovich77** [comment]
I've implemented The Red Terror.
#12647

**Comment by jimga150** [comment]
Working on [Seeker of Slaanesh](https://scryfall.com/search?q=!seekerofslaanesh) and [The Ruinous Powers](https://scryfall.com/search?q=!theruinouspowers)

**Comment by Susucre** [comment]
@theelk801 last two cards are implemented, if there is closing tasks to do for the set

**Comment by theelk801** [comment]
I think we're good, thanks to everyone for their contributions!

**Comment by xenohedron** [comment]
what about alternate arts?

**Comment by theelk801** [comment]
right, forgot those
