### ISSUE TITLE
Duplicate Token Tracking

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#8996]
This checklist's purpose is tracking instances of "duplicate tokens", in which two cards which create the same token actually create different token objects. This bloats the codebase and leads to problems with tokens' images.

### To-Do
- [x] Remove [AerieWorshippersBirdToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/AerieWorshippersBirdToken.java), [RiseOfEaglesBirdToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/RiseOfEaglesBirdToken.java), replace with single "EnchantmentBirdToken" file
- [x] Remove [CreakwoodLiegeToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/CreakwoodLiegeToken.java), [WormHarvestToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/WormHarvestToken.java), replace with single "BlackGreenWormToken" file
- [x] Remove [AkoumStonewakerElementalToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/AkoumStonewakerElementalToken.java), [ValdukElementalToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/ValdukElementalToken.java), replace with single "TrampleHasteRedElementalToken" file
- [x] Remove [SkywiseTeachingsToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/SkywiseTeachingsToken.java). As [DjinnMonkToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/DjinnMonkToken.java) already exists, all references to SkywiseTeachingsTokens should instead be replaced by "DjinnMonkToken", and no new file must be made
- [x] Remove [BroodKeeperDragonToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/BroodKeeperDragonToken.java), [DragonEggDragonToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/DragonEggDragonToken.java), replace with single "MiniShivanDragonToken" file (or any other name you think is more fitting)
- [x] Remove [ChasmSkulkerSquidToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/ChasmSkulkerSquidToken.java), [CoralBarrierSquidToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/CoralBarrierSquidToken.java), replace with single "SquidToken" file
- [x] Remove [LinvalaAngelToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/LinvalaAngelToken.java). As [Angel33Token](https://github.com/magefree/mage/blob/4a167b3a17274c15d8d584f4f7d90bf43aac4e00/Mage/src/main/java/mage/game/permanent/token/Angel33Token.java) already exists, all references to LinvalaAngelToken should instead be replaced by "Angel33Token", and no new file must be made
- [x] Remove [ElementalMasteryElementalToken](https://github.com/magefree/mage/blob/80f6ceccff24a0aebf17060c6974f6f18971b0fd/Mage/src/main/java/mage/game/permanent/token/ElementalMasteryElementalToken.java), [TemptWithVengeanceElementalToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/TemptWithVengeanceElementalToken.java), replace with single "RedHasteElementalToken" file
