### ISSUE TITLE
Ruhan of the Fomori bug tracking

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#9096]
The ability of [[Ruhan of the Fomori]] causes him to attack a player at random, chosen at the beginning of combat. In xmage, this works as expected unless a turn has multiple combat phases, potentially caused by a card like [[Raiyuu, Storm's Edge]]. In this case, Ruhan *will* be forced to attack on the second combat phase, but his attack decision is not random (i.e., the player is able to select an opponent for Ruhan to attack).

According to one of Ruhan's rulings, this ability should trigger at the beginning of every combat step, selecting a target randomly again (not necessarily the same player):

"*[If your turn has multiple combat phases, Ruhan’s ability triggers at the beginning of each of them. Ignore any choices made during previous combat phases.](https://gatherer.wizards.com/pages/card/details.aspx?name=Ruhan%20of%20the%20Fomori)*"

**Comment by PurpleCrowbar** [comment]
Additionally, if Ruhan *kills* a player on the first combat phase, then he seems to be forced to attack the now dead player on the second combat phase, instead of making a new choice based on the living players at the time of the ability triggering.

**Comment by PurpleCrowbar** [comment]
Found another bug, so am turning this into a Ruhan of the Fomori bug-tracking issue. See below:

- [ ] On an additional combat phase, Ruhan is forced to attack but his target is not assigned randomly, so the player is wrongly able to choose an opponent to be attacked.
- [ ] If Ruhan kills a player on the first combat phase, then has an additional combat phase during which he can attack (e.g., because of vigilance), he will be forced to attack the dead player that he killed on the previous combat phase that turn.
- [ ] Despite Ruhan's target being randomly selected during the Beginnning of Combat step, there is nothing to indicate which opponent was selected until the declare attackers step when Ruhan is committed to the attack. This means that opponents cannot, for example, tap him in response to being selected as the target.
