### ISSUE TITLE
Discord Feedback 1.4.51-XX

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9258]
# Not Solved
- [x] #9273
- [ ] "very minor bug, the first trigger on the Undercity doesn't reveal the card you find"
- [ ] "I had inevitable betrayal cast on me, grabbing scourge of kher ridges, in response to the abiltiy activation I conceded, and it wasn't exiled
- [ ] "Inspiring statuary doesn't work with commanders sometimes"
- [ ] Cubed added in https://github.com/magefree/mage/pull/8961 is not available on the beta server, but is available on local server
- [x] #9715
- [ ] "when you cast "first day of class" for the second time in one turn, choose LEARN, it will restart the turn to untap phase"
- [ ] Speed up AI when multiple instances of the same trigger go on the stack. If the AI chooses to do nothing for the first trigger, have it do nothing for the subsequent ones.
- [ ] "When my commander, Elenda, the Dusk Rose dies and goes to the command zone, her death trigger doesn't actually trigger unless I keep her in the gy. They changed the rules a while back so that she should still get the trigger."
- [ ] "chance of getting hideaway to work with strionic resonator?
you should be able to play both cards if you get that to fire..."
- [ ] "the new gate cards make you pick the mode instead of autotapping like any other multicolor land I would expect that, ex., a cliffgate where you choose blue would have identical behavior to izzet guildgate"
- [ ] "Plague of vermin you can keep spending life past 0"
- [ ] "Why isn't there an option to have favorite servers yet?"
- [ ] New Tournament Save/Load does not save/load all settings
- [ ] Add an afk kick timer for people who are connected to the server but doing nothing.
- [ ] "dying to commander damage while I had the initiative (from Sarevok's Tome) didn't transfer the initiative to the player that dealt combat damage"
- [x] #9419
- [ ] "Serra's emissary is bugged. Opponent named artifact but my artifact creatures could still attack and do damage to him"
- [ ] "Liliana, Waker of the dead's emblem isn't giving haste to the creatures it brings out from the graveyard sometimes, not sure how to replicate (On the Beta)"
- [ ] "Zaxara, the exemplar doesnt trigger on x spells"
- [ ] #4686: "New Table creation window allows you to pick incompatible deck and game types. One should be made primary and the other should be filtered based on the choice of the primary one."
![unknown](https://user-images.githubusercontent.com/48962821/181306283-8b9721c1-3e33-46f3-8b83-eab8fc937bdc.png)
- [ ] "Invasion Plans is forcing creatures that can't block to block, you can't proceed with combat.
![image](https://user-images.githubusercontent.com/48962821/178569510-05a0eff7-6d2e-49e4-aaa9-df1bb4cb03b4.jpeg)

# Solved
- [x] #9275
- [x] "If you play Explosive Welcome, you just win atleast in the non-beta version"
- [x] #9317
- [x] "Urborg Lhurgoyf only mills one card instead of three when it's kicker for just {B}"
- [x] "I had shroud on Zur the Enchanter and couldn't play enchantments on him while he had it from hand or his effect"
- [x] #9424 "dusk mangler seems broken. it won't let me cast it, and throws errors"
- [x] "Battle-Rage Blessing doesn't let the player target anything"
- [x] "Legion's Initiative - The ability activates but creatures are not returned to owner's control"
- [x] #9414
- [x] #9413
- [x] #9395
- [x] #9316
- [x] "protection racket draws the cards even though opponents choose to exile"
- [x] "ancient brass dragon looks only at the controller's graveyard when it should be all, and I can't even select creatures to bring back"
- [x] "Evelyn, the Covetous partially doesnt work, wont let you cast as id mana of any color
- [x] "Latest update on the beta server appears to have broken Kroxa, when it's ETB trigger that causes discard attempts to resolve an error is thrown and the turn is restarted." (latest beta = 2022-07-09 15:23 at time of writing)
- [x] "In multiplayer commander games, the Eminence trigger from Edgar Markov causes some players to get a UI error (Server's error: offset out of bounds), causing the game to be unplayable."
- [x] #9259
- [x] "ingenious artillerist seems to be triggering on any artifact entering, not just mine"
- [x] "bhaal, lord of murder is coded backwards we noticed this the other day he has indestructable if you have more then half your total, and is killable if you have less then half."
- [x] " there's a typo in the hover text for the "rated game" box on table creation (match**e** -> match)"
![unknown](https://user-images.githubusercontent.com/48962821/179815496-148aaaa7-981d-4a7c-abaf-2922ceb47fea.png)
- [x] "life of the party crashed the game, for some odd reason... one token crashed into another token, and the universe exploded..." 
- [x]  "Opalescence + Maskwood Nexus Doesn't seem to apply creature types to animated creatures thus Coat of Arms not working."
- [x] Incriminate is throwing an UnsupportedOperationException on line 97 of Incriminate.java as it resolves. "Came up trying to cast Incriminate on Light-Paws and another card."
![image](https://user-images.githubusercontent.com/48962821/178569426-b6c835a1-beed-4172-b2ae-a919e2bf25eb.png)

**Comment by JayDi85** [comment]
Is it all related to new auto choices logic?

**Comment by Grath** [comment]
Ancient Brass Dragon is duplicate of #9128 which was fixed.

**Comment by Alex-Vasile** [comment]
Can't reproduce Life of the Party bug in latest build

**Comment by Alex-Vasile** [comment]
Can't reproduce Evelyn, the Covetous on latest build

**Comment by awjackson** [comment]
The Legion's Initiative issue is a duplicate of https://github.com/magefree/mage/issues/8761, which is fixed (and I just checked that it hasn't re-regressed somehow). I assume the person who reported it is still on 1.4.50.

**Comment by awjackson** [comment]
I can't reproduce the Zur issue. I gave him shroud with Aspect of Mongoose and was still able to attach Auras to him that his triggered ability cheated onto the battlefield.
