### ISSUE TITLE
DMU - Dominaria United Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#9303]
This checklist is here to help manage the implementation of Dominaria United. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Academy Loremaster](https://scryfall.com/search?q=!academyloremaster)
- [x] Done -- [Academy Wall](https://scryfall.com/search?q=!academywall)
- [x] Done -- [Adarkar Wastes](https://scryfall.com/search?q=!adarkarwastes)
- [x] Done -- [Aether Channeler](https://scryfall.com/search?q=!aetherchanneler)
- [x] Done -- [Aggressive Sabotage](https://scryfall.com/search?q=!aggressivesabotage)
- [x] Done -- [Ajani, Sleeper Agent](https://scryfall.com/search?q=!ajanisleeperagent)
- [x] Done -- [Anointed Peacekeeper](https://scryfall.com/search?q=!anointedpeacekeeper)
- [x] Done -- [Archangel of Wrath](https://scryfall.com/search?q=!archangelofwrath)
- [x] Done -- [Argivian Cavalier](https://scryfall.com/search?q=!argiviancavalier)
- [x] Done -- [Argivian Phalanx](https://scryfall.com/search?q=!argivianphalanx)
- [x] Done -- [Aron, Benalia's Ruin](https://scryfall.com/search?q=!aronbenaliasruin)
- [x] Done -- [Artillery Blast](https://scryfall.com/search?q=!artilleryblast)
- [x] Done -- [Astor, Bearer of Blades](https://scryfall.com/search?q=!astorbearerofblades)
- [x] Done -- [Automatic Librarian](https://scryfall.com/search?q=!automaticlibrarian)
- [x] Done -- [Baird, Argivian Recruiter](https://scryfall.com/search?q=!bairdargivianrecruiter)
- [x] Done -- [Balduvian Atrocity](https://scryfall.com/search?q=!balduvianatrocity)
- [x] Done -- [Balduvian Berserker](https://scryfall.com/search?q=!balduvianberserker)
- [x] Done -- [Balmor, Battlemage Captain](https://scryfall.com/search?q=!balmorbattlemagecaptain)
- [x] Done -- [Barkweave Crusher](https://scryfall.com/search?q=!barkweavecrusher)
- [x] Done -- [Battle-Rage Blessing](https://scryfall.com/search?q=!battlerageblessing)
- [x] Done -- [Battlefly Swarm](https://scryfall.com/search?q=!battleflyswarm)
- [x] Done -- [Battlewing Mystic](https://scryfall.com/search?q=!battlewingmystic)
- [x] Done -- [Benalish Faithbonder](https://scryfall.com/search?q=!benalishfaithbonder)
- [x] Done -- [Benalish Sleeper](https://scryfall.com/search?q=!benalishsleeper)
- [x] Done -- [Bite Down](https://scryfall.com/search?q=!bitedown)
- [x] Done -- [Blight Pile](https://scryfall.com/search?q=!blightpile)
- [x] Done -- [Bog Badger](https://scryfall.com/search?q=!bogbadger)
- [x] Done -- [Bone Splinters](https://scryfall.com/search?q=!bonesplinters)
- [x] Done -- [Bortuk Bonerattle](https://scryfall.com/search?q=!bortukbonerattle)
- [x] Done -- [Braids's Frightful Return](https://scryfall.com/search?q=!braidssfrightfulreturn)
- [x] Done -- [Braids, Arisen Nightmare](https://scryfall.com/search?q=!braidsarisennightmare)
- [x] Done -- [Briar Hydra](https://scryfall.com/search?q=!briarhydra)
- [x] Done -- [Broken Wings](https://scryfall.com/search?q=!brokenwings)
- [x] Done -- [Captain's Call](https://scryfall.com/search?q=!captainscall)
- [x] Done -- [Caves of Koilos](https://scryfall.com/search?q=!cavesofkoilos)
- [x] Done -- [Chaotic Transformation](https://scryfall.com/search?q=!chaotictransformation)
- [x] Done -- [Charismatic Vanguard](https://scryfall.com/search?q=!charismaticvanguard)
- [x] Done -- [Choking Miasma](https://scryfall.com/search?q=!chokingmiasma)
- [x] Done -- [Citizen's Arrest](https://scryfall.com/search?q=!citizensarrest)
- [x] Done -- [Cleaving Skyrider](https://scryfall.com/search?q=!cleavingskyrider)
- [x] Done -- [Clockwork Drawbridge](https://scryfall.com/search?q=!clockworkdrawbridge)
- [x] Done -- [Coalition Skyknight](https://scryfall.com/search?q=!coalitionskyknight)
- [x] Done -- [Coalition Warbrute](https://scryfall.com/search?q=!coalitionwarbrute)
- [x] Done -- [Colossal Growth](https://scryfall.com/search?q=!colossalgrowth)
- [x] Done -- [Combat Research](https://scryfall.com/search?q=!combatresearch)
- [x] Done -- [Contaminated Aquifer](https://scryfall.com/search?q=!contaminatedaquifer)
- [x] Done -- [Coral Colony](https://scryfall.com/search?q=!coralcolony)
- [x] Done -- [Cosmic Epiphany](https://scryfall.com/search?q=!cosmicepiphany)
- [x] Done -- [Crystal Grotto](https://scryfall.com/search?q=!crystalgrotto)
- [x] Done -- [Cult Conscript](https://scryfall.com/search?q=!cultconscript)
- [x] Done -- [Cut Down](https://scryfall.com/search?q=!cutdown)
- [x] Done -- [Danitha, Benalia's Hope](https://scryfall.com/search?q=!danithabenaliashope)
- [x] Done -- [Deathbloom Gardener](https://scryfall.com/search?q=!deathbloomgardener)
- [x] Done -- [Defiler of Dreams](https://scryfall.com/search?q=!defilerofdreams)
- [x] Done -- [Defiler of Faith](https://scryfall.com/search?q=!defileroffaith)
- [x] Done -- [Defiler of Flesh](https://scryfall.com/search?q=!defilerofflesh)
- [x] Done -- [Defiler of Instinct](https://scryfall.com/search?q=!defilerofinstinct)
- [x] Done -- [Defiler of Vigor](https://scryfall.com/search?q=!defilerofvigor)
- [x] Done -- [Destroy Evil](https://scryfall.com/search?q=!destroyevil)
- [x] Done -- [Djinn of the Fountain](https://scryfall.com/search?q=!djinnofthefountain)
- [x] Done -- [Drag to the Bottom](https://scryfall.com/search?q=!dragtothebottom)
- [x] Done -- [Dragon Whelp](https://scryfall.com/search?q=!dragonwhelp)
- [x] Done -- [Eerie Soultender](https://scryfall.com/search?q=!eeriesoultender)
- [x] Done -- [Elas il-Kor, Sadistic Pilgrim](https://scryfall.com/search?q=!elasilkorsadisticpilgrim)
- [x] Done -- [Electrostatic Infantry](https://scryfall.com/search?q=!electrostaticinfantry)
- [x] Done -- [Elfhame Wurm](https://scryfall.com/search?q=!elfhamewurm)
- [x] Done -- [Elvish Hydromancer](https://scryfall.com/search?q=!elvishhydromancer)
- [x] Done -- [Ertai Resurrected](https://scryfall.com/search?q=!ertairesurrected)
- [x] Done -- [Ertai's Scorn](https://scryfall.com/search?q=!ertaisscorn)
- [x] Done -- [Essence Scatter](https://scryfall.com/search?q=!essencescatter)
- [x] Done -- [Evolved Sleeper](https://scryfall.com/search?q=!evolvedsleeper)
- [x] Done -- [Extinguish the Light](https://scryfall.com/search?q=!extinguishthelight)
- [x] Done -- [Fires of Victory](https://scryfall.com/search?q=!firesofvictory)
- [x] Done -- [Floriferous Vinewall](https://scryfall.com/search?q=!floriferousvinewall)
- [x] Done -- [Flowstone Infusion](https://scryfall.com/search?q=!flowstoneinfusion)
- [x] Done -- [Flowstone Kavu](https://scryfall.com/search?q=!flowstonekavu)
- [x] Done -- [Founding the Third Path](https://scryfall.com/search?q=!foundingthethirdpath)
- [x] Done -- [Frostfist Strider](https://scryfall.com/search?q=!frostfiststrider)
- [x] Done -- [Furious Bellow](https://scryfall.com/search?q=!furiousbellow)
- [x] Done -- [Gaea's Might](https://scryfall.com/search?q=!gaeasmight)
- [x] Done -- [Garna, Bloodfist of Keld](https://scryfall.com/search?q=!garnabloodfistofkeld)
- [x] Done -- [Geothermal Bog](https://scryfall.com/search?q=!geothermalbog)
- [x] Done -- [Ghitu Amplifier](https://scryfall.com/search?q=!ghituamplifier)
- [x] Done -- [Gibbering Barricade](https://scryfall.com/search?q=!gibberingbarricade)
- [x] Done -- [Goblin Picker](https://scryfall.com/search?q=!goblinpicker)
- [x] Done -- [Golden Argosy](https://scryfall.com/search?q=!goldenargosy)
- [x] Done -- [Griffin Protector](https://scryfall.com/search?q=!griffinprotector)
- [x] Done -- [Guardian of New Benalia](https://scryfall.com/search?q=!guardianofnewbenalia)
- [x] Done -- [Hammerhand](https://scryfall.com/search?q=!hammerhand)
- [x] Done -- [Haughty Djinn](https://scryfall.com/search?q=!haughtydjinn)
- [x] Done -- [Haunted Mire](https://scryfall.com/search?q=!hauntedmire)
- [x] Done -- [Haunting Figment](https://scryfall.com/search?q=!hauntingfigment)
- [x] Done -- [Herd Migration](https://scryfall.com/search?q=!herdmigration)
- [x] Done -- [Hero's Heirloom](https://scryfall.com/search?q=!herosheirloom)
- [x] Done -- [Heroic Charge](https://scryfall.com/search?q=!heroiccharge)
- [x] Done -- [Hexbane Tortoise](https://scryfall.com/search?q=!hexbanetortoise)
- [x] Done -- [Hurler Cyclops](https://scryfall.com/search?q=!hurlercyclops)
- [x] Done -- [Hurloon Battle Hymn](https://scryfall.com/search?q=!hurloonbattlehymn)
- [x] Done -- [Idyllic Beachfront](https://scryfall.com/search?q=!idyllicbeachfront)
- [x] Done -- [Impede Momentum](https://scryfall.com/search?q=!impedemomentum)
- [x] Done -- [Impulse](https://scryfall.com/search?q=!impulse)
- [x] Done -- [In Thrall to the Pit](https://scryfall.com/search?q=!inthralltothepit)
- [x] Done -- [Inscribed Tablet](https://scryfall.com/search?q=!inscribedtablet)
- [x] Done -- [Ivy, Gleeful Spellthief](https://scryfall.com/search?q=!ivygleefulspellthief)
- [x] Done -- [Jaya's Firenado](https://scryfall.com/search?q=!jayasfirenado)
- [x] Done -- [Jaya, Fiery Negotiator](https://scryfall.com/search?q=!jayafierynegotiator)
- [x] Done -- [Jhoira, Ageless Innovator](https://scryfall.com/search?q=!jhoiraagelessinnovator)
- [x] Done -- [Jodah's Codex](https://scryfall.com/search?q=!jodahscodex)
- [x] Done -- [Jodah, the Unifier](https://scryfall.com/search?q=!jodahtheunifier)
- [x] Done -- [Join Forces](https://scryfall.com/search?q=!joinforces)
- [x] Done -- [Joint Exploration](https://scryfall.com/search?q=!jointexploration)
- [x] Done -- [Juniper Order Rootweaver](https://scryfall.com/search?q=!juniperorderrootweaver)
- [x] Done -- [Karn's Sylex](https://scryfall.com/search?q=!karnssylex)
- [x] Done -- [Karn, Living Legacy](https://scryfall.com/search?q=!karnlivinglegacy)
- [x] Done -- [Karplusan Forest](https://scryfall.com/search?q=!karplusanforest)
- [x] Done -- [Keldon Flamesage](https://scryfall.com/search?q=!keldonflamesage)
- [x] Done -- [Keldon Strike Team](https://scryfall.com/search?q=!keldonstriketeam)
- [x] Done -- [King Darien XLVIII](https://scryfall.com/search?q=!kingdarienxlviii)
- [x] Done -- [Knight of Dawn's Light](https://scryfall.com/search?q=!knightofdawnslight)
- [x] Done -- [Knight of Dusk's Shadow](https://scryfall.com/search?q=!knightofdusksshadow)
- [x] Done -- [Lagomos, Hand of Hatred](https://scryfall.com/search?q=!lagomoshandofhatred)
- [x] Done -- [Leaf-Crowned Visionary](https://scryfall.com/search?q=!leafcrownedvisionary)
- [x] Done -- [Leyline Binding](https://scryfall.com/search?q=!leylinebinding)
- [x] Done -- [Lightning Strike](https://scryfall.com/search?q=!lightningstrike)
- [x] Done -- [Liliana of the Veil](https://scryfall.com/search?q=!lilianaoftheveil)
- [x] Done -- [Linebreaker Baloth](https://scryfall.com/search?q=!linebreakerbaloth)
- [x] Done -- [Llanowar Greenwidow](https://scryfall.com/search?q=!llanowargreenwidow)
- [x] Done -- [Llanowar Loamspeaker](https://scryfall.com/search?q=!llanowarloamspeaker)
- [x] Done -- [Llanowar Stalker](https://scryfall.com/search?q=!llanowarstalker)
- [x] Done -- [Love Song of Night and Day](https://scryfall.com/search?q=!lovesongofnightandday)
- [x] Done -- [Magnigoth Sentry](https://scryfall.com/search?q=!magnigothsentry)
- [x] Done -- [Meria's Outrider](https://scryfall.com/search?q=!meriasoutrider)
- [x] Done -- [Meria, Scholar of Antiquity](https://scryfall.com/search?q=!meriascholarofantiquity)
- [x] Done -- [Mesa Cavalier](https://scryfall.com/search?q=!mesacavalier)
- [x] Done -- [Meteorite](https://scryfall.com/search?q=!meteorite)
- [x] Done -- [Micromancer](https://scryfall.com/search?q=!micromancer)
- [x] Done -- [Molten Monstrosity](https://scryfall.com/search?q=!moltenmonstrosity)
- [x] Done -- [Molten Tributary](https://scryfall.com/search?q=!moltentributary)
- [x] Done -- [Monstrous War-Leech](https://scryfall.com/search?q=!monstrouswarleech)
- [x] Done -- [Mossbeard Ancient](https://scryfall.com/search?q=!mossbeardancient)
- [x] Done -- [Nael, Avizoa Aeronaut](https://scryfall.com/search?q=!naelavizoaaeronaut)
- [x] Done -- [Najal, the Storm Runner](https://scryfall.com/search?q=!najalthestormrunner)
- [x] Done -- [Negate](https://scryfall.com/search?q=!negate)
- [x] Done -- [Nemata, Primeval Warden](https://scryfall.com/search?q=!nemataprimevalwarden)
- [x] Done -- [Nishoba Brawler](https://scryfall.com/search?q=!nishobabrawler)
- [x] Done -- [Phoenix Chick](https://scryfall.com/search?q=!phoenixchick)
- [x] Done -- [Phyrexian Espionage](https://scryfall.com/search?q=!phyrexianespionage)
- [x] Done -- [Phyrexian Missionary](https://scryfall.com/search?q=!phyrexianmissionary)
- [x] Done -- [Phyrexian Rager](https://scryfall.com/search?q=!phyrexianrager)
- [x] Done -- [Phyrexian Vivisector](https://scryfall.com/search?q=!phyrexianvivisector)
- [x] Done -- [Phyrexian Warhorse](https://scryfall.com/search?q=!phyrexianwarhorse)
- [x] Done -- [Pilfer](https://scryfall.com/search?q=!pilfer)
- [x] Done -- [Pixie Illusionist](https://scryfall.com/search?q=!pixieillusionist)
- [x] Done -- [Plaza of Heroes](https://scryfall.com/search?q=!plazaofheroes)
- [x] Done -- [Prayer of Binding](https://scryfall.com/search?q=!prayerofbinding)
- [x] Done -- [Protect the Negotiators](https://scryfall.com/search?q=!protectthenegotiators)
- [x] Done -- [Queen Allenal of Ruadach](https://scryfall.com/search?q=!queenallenalofruadach)
- [x] Done -- [Quirion Beastcaller](https://scryfall.com/search?q=!quirionbeastcaller)
- [x] Done -- [Radha's Firebrand](https://scryfall.com/search?q=!radhasfirebrand)
- [x] Done -- [Radha, Coalition Warlord](https://scryfall.com/search?q=!radhacoalitionwarlord)
- [x] Done -- [Radiant Grove](https://scryfall.com/search?q=!radiantgrove)
- [x] Done -- [Raff, Weatherlight Stalwart](https://scryfall.com/search?q=!raffweatherlightstalwart)
- [x] Done -- [Ragefire Hellkite](https://scryfall.com/search?q=!ragefirehellkite)
- [x] Done -- [Ratadrabik of Urborg](https://scryfall.com/search?q=!ratadrabikofurborg)
- [x] Done -- [Relic of Legends](https://scryfall.com/search?q=!relicoflegends)
- [x] Done -- [Resolute Reinforcements](https://scryfall.com/search?q=!resolutereinforcements)
- [x] Done -- [Rith, Liberated Primeval](https://scryfall.com/search?q=!rithliberatedprimeval)
- [x] Done -- [Rivaz of the Claw](https://scryfall.com/search?q=!rivazoftheclaw)
- [x] Done -- [Rona's Vortex](https://scryfall.com/search?q=!ronasvortex)
- [x] Done -- [Rona, Sheoldred's Faithful](https://scryfall.com/search?q=!ronasheoldredsfaithful)
- [x] Done -- [Rulik Mons, Warren Chief](https://scryfall.com/search?q=!rulikmonswarrenchief)
- [x] Done -- [Rundvelt Hordemaster](https://scryfall.com/search?q=!rundvelthordemaster)
- [x] Done -- [Runic Shot](https://scryfall.com/search?q=!runicshot)
- [x] Done -- [Sacred Peaks](https://scryfall.com/search?q=!sacredpeaks)
- [x] Done -- [Salvaged Manaworker](https://scryfall.com/search?q=!salvagedmanaworker)
- [x] Done -- [Samite Herbalist](https://scryfall.com/search?q=!samiteherbalist)
- [x] Done -- [Scout the Wilderness](https://scryfall.com/search?q=!scoutthewilderness)
- [x] Done -- [Sengir Connoisseur](https://scryfall.com/search?q=!sengirconnoisseur)
- [x] Done -- [Serra Paragon](https://scryfall.com/search?q=!serraparagon)
- [x] Done -- [Serra Redeemer](https://scryfall.com/search?q=!serraredeemer)
- [x] Done -- [Shadow Prophecy](https://scryfall.com/search?q=!shadowprophecy)
- [x] Done -- [Shadow-Rite Priest](https://scryfall.com/search?q=!shadowritepriest)
- [x] Done -- [Shalai's Acolyte](https://scryfall.com/search?q=!shalaisacolyte)
- [x] Done -- [Shanna, Purifying Blade](https://scryfall.com/search?q=!shannapurifyingblade)
- [x] Done -- [Sheoldred's Restoration](https://scryfall.com/search?q=!sheoldredsrestoration)
- [x] Done -- [Sheoldred, the Apocalypse](https://scryfall.com/search?q=!sheoldredtheapocalypse)
- [x] Done -- [Shield-Wall Sentinel](https://scryfall.com/search?q=!shieldwallsentinel)
- [x] Done -- [Shivan Devastator](https://scryfall.com/search?q=!shivandevastator)
- [x] Done -- [Shivan Reef](https://scryfall.com/search?q=!shivanreef)
- [x] Done -- [Shore Up](https://scryfall.com/search?q=!shoreup)
- [x] Done -- [Silver Scrutiny](https://scryfall.com/search?q=!silverscrutiny)
- [x] Done -- [Silverback Elder](https://scryfall.com/search?q=!silverbackelder)
- [x] Done -- [Slimefoot's Survey](https://scryfall.com/search?q=!slimefootssurvey)
- [x] Done -- [Smash to Dust](https://scryfall.com/search?q=!smashtodust)
- [x] Done -- [Snarespinner](https://scryfall.com/search?q=!snarespinner)
- [x] Done -- [Soaring Drake](https://scryfall.com/search?q=!soaringdrake)
- [x] Done -- [Sol'Kanar the Tainted](https://scryfall.com/search?q=!solkanarthetainted)
- [x] Done -- [Soul of Windgrace](https://scryfall.com/search?q=!soulofwindgrace)
- [x] Done -- [Sphinx of Clear Skies](https://scryfall.com/search?q=!sphinxofclearskies)
- [x] Done -- [Splatter Goblin](https://scryfall.com/search?q=!splattergoblin)
- [x] Done -- [Sprouting Goblin](https://scryfall.com/search?q=!sproutinggoblin)
- [x] Done -- [Squee, Dubious Monarch](https://scryfall.com/search?q=!squeedubiousmonarch)
- [x] Done -- [Stall for Time](https://scryfall.com/search?q=!stallfortime)
- [x] Done -- [Stenn, Paranoid Partisan](https://scryfall.com/search?q=!stennparanoidpartisan)
- [x] Done -- [Strength of the Coalition](https://scryfall.com/search?q=!strengthofthecoalition)
- [x] Done -- [Stronghold Arena](https://scryfall.com/search?q=!strongholdarena)
- [x] Done -- [Sulfurous Springs](https://scryfall.com/search?q=!sulfuroussprings)
- [x] Done -- [Sunbathing Rootwalla](https://scryfall.com/search?q=!sunbathingrootwalla)
- [x] Done -- [Sunlit Marsh](https://scryfall.com/search?q=!sunlitmarsh)
- [x] Done -- [Tail Swipe](https://scryfall.com/search?q=!tailswipe)
- [x] Done -- [Take Up the Shield](https://scryfall.com/search?q=!takeuptheshield)
- [x] Done -- [Talas Lookout](https://scryfall.com/search?q=!talaslookout)
- [x] Done -- [Tangled Islet](https://scryfall.com/search?q=!tangledislet)
- [x] Done -- [Tattered Apparition](https://scryfall.com/search?q=!tatteredapparition)
- [x] Done -- [Tatyova, Steward of Tides](https://scryfall.com/search?q=!tatyovastewardoftides)
- [x] Done -- [Tear Asunder](https://scryfall.com/search?q=!tearasunder)
- [x] Done -- [Temporal Firestorm](https://scryfall.com/search?q=!temporalfirestorm)
- [x] Done -- [Temporary Lockdown](https://scryfall.com/search?q=!temporarylockdown)
- [x] Done -- [Territorial Maro](https://scryfall.com/search?q=!territorialmaro)
- [x] Done -- [The Cruelty of Gix](https://scryfall.com/search?q=!thecrueltyofgix)
- [x] Done -- [The Elder Dragon War](https://scryfall.com/search?q=!theelderdragonwar)
- [x] Done -- [The Phasing of Zhalfir](https://scryfall.com/search?q=!thephasingofzhalfir)
- [x] Done -- [The Raven Man](https://scryfall.com/search?q=!theravenman)
- [x] Done -- [The Weatherseed Treaty](https://scryfall.com/search?q=!theweatherseedtreaty)
- [x] Done -- [The World Spell](https://scryfall.com/search?q=!theworldspell)
- [x] Done -- [Thran Portal](https://scryfall.com/search?q=!thranportal)
- [x] Done -- [Threats Undetected](https://scryfall.com/search?q=!threatsundetected)
- [x] Done -- [Thrill of Possibility](https://scryfall.com/search?q=!thrillofpossibility)
- [x] Done -- [Tidepool Turtle](https://scryfall.com/search?q=!tidepoolturtle)
- [x] Done -- [Timeless Lotus](https://scryfall.com/search?q=!timelesslotus)
- [x] Done -- [Timely Interference](https://scryfall.com/search?q=!timelyinterference)
- [x] Done -- [Tolarian Geyser](https://scryfall.com/search?q=!tolariangeyser)
- [x] Done -- [Tolarian Terror](https://scryfall.com/search?q=!tolarianterror)
- [x] Done -- [Tori D'Avenant, Fury Rider](https://scryfall.com/search?q=!toridavenantfuryrider)
- [x] Done -- [Toxic Abomination](https://scryfall.com/search?q=!toxicabomination)
- [x] Done -- [Tribute to Urborg](https://scryfall.com/search?q=!tributetourborg)
- [x] Done -- [Twinferno](https://scryfall.com/search?q=!twinferno)
- [x] Done -- [Tyrannical Pitlord](https://scryfall.com/search?q=!tyrannicalpitlord)
- [x] Done -- [Urborg Lhurgoyf](https://scryfall.com/search?q=!urborglhurgoyf)
- [x] Done -- [Urborg Repossession](https://scryfall.com/search?q=!urborgrepossession)
- [x] Done -- [Urza Assembles the Titans](https://scryfall.com/search?q=!urzaassemblesthetitans)
- [x] Done -- [Uurg, Spawn of Turg](https://scryfall.com/search?q=!uurgspawnofturg)
- [x] Done -- [Valiant Veteran](https://scryfall.com/search?q=!valiantveteran)
- [x] Done -- [Vanquisher's Axe](https://scryfall.com/search?q=!vanquishersaxe)
- [x] Done -- [Vesuvan Duplimancy](https://scryfall.com/search?q=!vesuvanduplimancy)
- [x] Done -- [Viashino Branchrider](https://scryfall.com/search?q=!viashinobranchrider)
- [x] Done -- [Vineshaper Prodigy](https://scryfall.com/search?q=!vineshaperprodigy)
- [x] Done -- [Voda Sea Scavenger](https://scryfall.com/search?q=!vodaseascavenger)
- [x] Done -- [Vodalian Hexcatcher](https://scryfall.com/search?q=!vodalianhexcatcher)
- [x] Done -- [Vodalian Mindsinger](https://scryfall.com/search?q=!vodalianmindsinger)
- [x] Done -- [Vohar, Vodalian Desecrator](https://scryfall.com/search?q=!voharvodaliandesecrator)
- [x] Done -- [Volshe Tideturner](https://scryfall.com/search?q=!volshetideturner)
- [x] Done -- [Walking Bulwark](https://scryfall.com/search?q=!walkingbulwark)
- [x] Done -- [Warhost's Frenzy](https://scryfall.com/search?q=!warhostsfrenzy)
- [x] Done -- [Weatherlight Compleated](https://scryfall.com/search?q=!weatherlightcompleated)
- [x] Done -- [Wingmantle Chaplain](https://scryfall.com/search?q=!wingmantlechaplain)
- [x] Done -- [Wooded Ridgeline](https://scryfall.com/search?q=!woodedridgeline)
- [x] Done -- [Writhing Necromass](https://scryfall.com/search?q=!writhingnecromass)
- [x] Done -- [Yavimaya Coast](https://scryfall.com/search?q=!yavimayacoast)
- [x] Done -- [Yavimaya Iconoclast](https://scryfall.com/search?q=!yavimayaiconoclast)
- [x] Done -- [Yavimaya Sojourner](https://scryfall.com/search?q=!yavimayasojourner)
- [x] Done -- [Yavimaya Steelcrusher](https://scryfall.com/search?q=!yavimayasteelcrusher)
- [x] Done -- [Yotia Declares War](https://scryfall.com/search?q=!yotiadeclareswar)
- [x] Done -- [Zar Ojanen, Scion of Efrava](https://scryfall.com/search?q=!zarojanenscionofefrava)
- [x] Done -- [Zur, Eternal Schemer](https://scryfall.com/search?q=!zureternalschemer)
</details>

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by FreaIsDead** [comment]
I wanna implement "Yavimaya Iconoclast" :)

**Comment by weirddan455** [comment]
Regarding the tokens, Raven Man's token is implemented.  It just needs the image download code and I'm not sure how to do that.  Same for Lagomos, Hand of Hatred which also got a new token type.

**Comment by PurpleCrowbar** [comment]
> Regarding the tokens, Raven Man's token is implemented. It just needs the image download code and I'm not sure how to do that. Same for Lagomos, Hand of Hatred which also got a new token type.

That can be done when the tokens have been revealed or the set releases and the images come up on Scryfall. Usually downloads for new tokens’ images are dealt with when the set releases and the tokens can just use the placeholder image until then

**Comment by rockydirtbag** [comment]
I've implemented Ratadrabik of Urborg ([Pull Request](https://github.com/magefree/mage/pull/9447)). This is my first upload, so I hope I've done everything right :-)

**Comment by awjackson** [comment]
I'm working on Baird, though it won't work correctly until @Alex-Vasile's base-P/T PR is merged.

**Comment by weirddan455** [comment]
So that's every card being worked on except Serra Paragon.  Fun fact about that card:  It doesn't work with the current rules of Magic.  This guy made a pretty good video explaining the situation:  https://www.youtube.com/watch?v=S4VEx9TEUfw

They're surely going to have to either errata the card or change a rule and we may have to wait on that to happen so we know how to implement it.

**Comment by theelk801** [comment]
I think it can be implemented anyway given that it's on arena and magic online

**Comment by weirddan455** [comment]
> I think it can be implemented anyway given that it's on arena and magic online

Yea, it's a little tricky though right?  With the gain ability effect being stapled onto the same static ability.  I guess it can be implemented as a replacement effect?  Not really sure.

It's also bugged on Arena, not that that really matters for our purposes.  It applies the ability multiple times sometimes so when one thing dies, you get the gain life trigger more that once.

**Comment by Grath** [comment]
Seems to be straightforward that if people care that much about how it kinda technically shouldn't work, next time they're updating the comprehensive rules they'll add an exception for it.

**Comment by theelk801** [comment]
Alright, we can finally close this. Thanks to everyone who contributed!
