### ISSUE TITLE
DMC - Dominaria United Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#9311]
This checklist is here to help manage the implementation of Dominaria United Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abundant Growth](https://scryfall.com/search?q=!abundantgrowth)
- [x] Done -- [Abzan Charm](https://scryfall.com/search?q=!abzancharm)
- [x] Done -- [Activated Sleeper](https://scryfall.com/search?q=!activatedsleeper)
- [x] Done -- [Adriana, Captain of the Guard](https://scryfall.com/search?q=!adrianacaptainoftheguard)
- [x] Done -- [Alesha, Who Smiles at Death](https://scryfall.com/search?q=!aleshawhosmilesatdeath)
- [x] Done -- [Ambition's Cost](https://scryfall.com/search?q=!ambitionscost)
- [x] Done -- [Anafenza, Kin-Tree Spirit](https://scryfall.com/search?q=!anafenzakintreespirit)
- [x] Done -- [Arcane Sanctum](https://scryfall.com/search?q=!arcanesanctum)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Archelos, Lagoon Mystic](https://scryfall.com/search?q=!archeloslagoonmystic)
- [x] Done -- [Arvad the Cursed](https://scryfall.com/search?q=!arvadthecursed)
- [x] Done -- [Ashling the Pilgrim](https://scryfall.com/search?q=!ashlingthepilgrim)
- [x] Done -- [Atla Palani, Nest Tender](https://scryfall.com/search?q=!atlapalaninesttender)
- [x] Done -- [Ayesha Tanaka, Armorer](https://scryfall.com/search?q=!ayeshatanakaarmorer)
- [x] Done -- [Bad River](https://scryfall.com/search?q=!badriver)
- [x] Done -- [Baleful Strix](https://scryfall.com/search?q=!balefulstrix)
- [x] Done -- [Baru, Wurmspeaker](https://scryfall.com/search?q=!baruwurmspeaker)
- [x] Done -- [Battlefield Forge](https://scryfall.com/search?q=!battlefieldforge)
- [x] Done -- [Beast Within](https://scryfall.com/search?q=!beastwithin)
- [x] Done -- [Bedevil](https://scryfall.com/search?q=!bedevil)
- [x] Done -- [Bell Borca, Spectral Sergeant](https://scryfall.com/search?q=!bellborcaspectralsergeant)
- [x] Done -- [Blackblade Reforged](https://scryfall.com/search?q=!blackbladereforged)
- [x] Done -- [Bladewing, Deathless Tyrant](https://scryfall.com/search?q=!bladewingdeathlesstyrant)
- [x] Done -- [Bojuka Bog](https://scryfall.com/search?q=!bojukabog)
- [x] Done -- [Bontu's Monument](https://scryfall.com/search?q=!bontusmonument)
- [x] Done -- [Boros Garrison](https://scryfall.com/search?q=!borosgarrison)
- [x] Done -- [Cadric, Soul Kindler](https://scryfall.com/search?q=!cadricsoulkindler)
- [x] Done -- [Canopy Vista](https://scryfall.com/search?q=!canopyvista)
- [x] Done -- [Captain Lannery Storm](https://scryfall.com/search?q=!captainlannerystorm)
- [x] Done -- [Cascading Cataracts](https://scryfall.com/search?q=!cascadingcataracts)
- [x] Done -- [Chromanticore](https://scryfall.com/search?q=!chromanticore)
- [x] Done -- [Cinder Glade](https://scryfall.com/search?q=!cinderglade)
- [x] Done -- [Coalition Relic](https://scryfall.com/search?q=!coalitionrelic)
- [x] Done -- [Coiling Oracle](https://scryfall.com/search?q=!coilingoracle)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=!commanderssphere)
- [x] Done -- [Crumbling Necropolis](https://scryfall.com/search?q=!crumblingnecropolis)
- [x] Done -- [Crystal Quarry](https://scryfall.com/search?q=!crystalquarry)
- [x] Done -- [Cultivate](https://scryfall.com/search?q=!cultivate)
- [x] Done -- [Day of Destiny](https://scryfall.com/search?q=!dayofdestiny)
- [x] Done -- [Dihada, Binder of Wills](https://scryfall.com/search?q=!dihadabinderofwills)
- [x] Done -- [Dragonskull Summit](https://scryfall.com/search?q=!dragonskullsummit)
- [x] Done -- [Drana, Liberator of Malakir](https://scryfall.com/search?q=!dranaliberatorofmalakir)
- [x] Done -- [Duneblast](https://scryfall.com/search?q=!duneblast)
- [x] Done -- [Echoing Truth](https://scryfall.com/search?q=!echoingtruth)
- [x] Done -- [Emperor Mihail II](https://scryfall.com/search?q=!emperormihailii)
- [x] Done -- [Etali, Primal Storm](https://scryfall.com/search?q=!etaliprimalstorm)
- [x] Done -- [Evolving Wilds](https://scryfall.com/search?q=!evolvingwilds)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Explore](https://scryfall.com/search?q=!explore)
- [x] Done -- [Explosive Vegetation](https://scryfall.com/search?q=!explosivevegetation)
- [x] Done -- [Faeburrow Elder](https://scryfall.com/search?q=!faeburrowelder)
- [x] Done -- [Faithless Looting](https://scryfall.com/search?q=!faithlesslooting)
- [x] Done -- [Fallaji Wayfarer](https://scryfall.com/search?q=!fallajiwayfarer)
- [x] Done -- [Farseek](https://scryfall.com/search?q=!farseek)
- [x] Done -- [Fellwar Stone](https://scryfall.com/search?q=!fellwarstone)
- [x] Done -- [Flood Plain](https://scryfall.com/search?q=!floodplain)
- [x] Done -- [Foreboding Ruins](https://scryfall.com/search?q=!forebodingruins)
- [x] Done -- [Frontier Bivouac](https://scryfall.com/search?q=!frontierbivouac)
- [x] Done -- [Fusion Elemental](https://scryfall.com/search?q=!fusionelemental)
- [x] Done -- [Garna, the Bloodflame](https://scryfall.com/search?q=!garnathebloodflame)
- [x] Done -- [Geier Reach Sanitarium](https://scryfall.com/search?q=!geierreachsanitarium)
- [x] Done -- [General Marhault Elsdragon](https://scryfall.com/search?q=!generalmarhaultelsdragon)
- [x] Done -- [Generous Gift](https://scryfall.com/search?q=!generousgift)
- [x] Done -- [Gerrard's Hourglass Pendant](https://scryfall.com/search?q=!gerrardshourglasspendant)
- [x] Done -- [Glint-Eye Nephilim](https://scryfall.com/search?q=!glinteyenephilim)
- [x] Done -- [Grasslands](https://scryfall.com/search?q=!grasslands)
- [x] Done -- [Greensleeves, Maro-Sorcerer](https://scryfall.com/search?q=!greensleevesmarosorcerer)
- [x] Done -- [Growth Spiral](https://scryfall.com/search?q=!growthspiral)
- [x] Done -- [Hazezon, Shaper of Sand](https://scryfall.com/search?q=!hazezonshaperofsand)
- [x] Done -- [Hazoret's Monument](https://scryfall.com/search?q=!hazoretsmonument)
- [x] Done -- [Hedron Archive](https://scryfall.com/search?q=!hedronarchive)
- [x] Done -- [Hero of Precinct One](https://scryfall.com/search?q=!heroofprecinctone)
- [x] Done -- [Hero's Blade](https://scryfall.com/search?q=!herosblade)
- [x] Done -- [Hero's Downfall](https://scryfall.com/search?q=!herosdownfall)
- [x] Done -- [Heroes' Podium](https://scryfall.com/search?q=!heroespodium)
- [x] Done -- [Historian's Boon](https://scryfall.com/search?q=!historiansboon)
- [x] Done -- [Honor-Worn Shaku](https://scryfall.com/search?q=!honorwornshaku)
- [x] Done -- [Illuna, Apex of Wishes](https://scryfall.com/search?q=!illunaapexofwishes)
- [x] Done -- [Iridian Maelstrom](https://scryfall.com/search?q=!iridianmaelstrom)
- [x] Done -- [Jared Carthalion](https://scryfall.com/search?q=!jaredcarthalion)
- [x] Done -- [Jasmine Boreal of the Seven](https://scryfall.com/search?q=!jasmineborealoftheseven)
- [x] Done -- [Jazal Goldmane](https://scryfall.com/search?q=!jazalgoldmane)
- [x] Done -- [Jedit Ojanen, Mercenary](https://scryfall.com/search?q=!jeditojanenmercenary)
- [x] Done -- [Jenson Carthalion, Druid Exile](https://scryfall.com/search?q=!jensoncarthaliondruidexile)
- [x] Done -- [Josu Vess, Lich Knight](https://scryfall.com/search?q=!josuvesslichknight)
- [x] Done -- [Jungle Shrine](https://scryfall.com/search?q=!jungleshrine)
- [x] Done -- [Kari Zev, Skyship Raider](https://scryfall.com/search?q=!karizevskyshipraider)
- [x] Done -- [Kaya's Wrath](https://scryfall.com/search?q=!kayaswrath)
- [x] Done -- [Knight of New Alara](https://scryfall.com/search?q=!knightofnewalara)
- [x] Done -- [Kodama's Reach](https://scryfall.com/search?q=!kodamasreach)
- [x] Done -- [Kothophed, Soul Hoarder](https://scryfall.com/search?q=!kothophedsoulhoarder)
- [x] Done -- [Krenko, Tin Street Kingpin](https://scryfall.com/search?q=!krenkotinstreetkingpin)
- [x] Done -- [Krosan Verge](https://scryfall.com/search?q=!krosanverge)
- [x] Done -- [Lavalanche](https://scryfall.com/search?q=!lavalanche)
- [x] Done -- [Maelstrom Archangel](https://scryfall.com/search?q=!maelstromarchangel)
- [x] Done -- [Maelstrom Nexus](https://scryfall.com/search?q=!maelstromnexus)
- [x] Done -- [Mana Cannons](https://scryfall.com/search?q=!manacannons)
- [x] Done -- [Merciless Eviction](https://scryfall.com/search?q=!mercilesseviction)
- [x] Done -- [Migration Path](https://scryfall.com/search?q=!migrationpath)
- [x] Done -- [Mikokoro, Center of the Sea](https://scryfall.com/search?q=!mikokorocenterofthesea)
- [x] Done -- [Mobilized District](https://scryfall.com/search?q=!mobilizeddistrict)
- [x] Done -- [Moira, Urborg Haunt](https://scryfall.com/search?q=!moiraurborghaunt)
- [x] Done -- [Mortify](https://scryfall.com/search?q=!mortify)
- [x] Done -- [Mountain Valley](https://scryfall.com/search?q=!mountainvalley)
- [x] Done -- [Murmuring Bosk](https://scryfall.com/search?q=!murmuringbosk)
- [x] Done -- [Mystic Monastery](https://scryfall.com/search?q=!mysticmonastery)
- [x] Done -- [Naya Charm](https://scryfall.com/search?q=!nayacharm)
- [x] Done -- [Neheb, Dreadhorde Champion](https://scryfall.com/search?q=!nehebdreadhordechampion)
- [x] Done -- [Nethroi, Apex of Death](https://scryfall.com/search?q=!nethroiapexofdeath)
- [x] Done -- [Night's Whisper](https://scryfall.com/search?q=!nightswhisper)
- [x] Done -- [Nomad Outpost](https://scryfall.com/search?q=!nomadoutpost)
- [x] Done -- [O-Kagachi, Vengeful Kami](https://scryfall.com/search?q=!okagachivengefulkami)
- [x] Done -- [Obsidian Obelisk](https://scryfall.com/search?q=!obsidianobelisk)
- [x] Done -- [Odric, Lunarch Marshal](https://scryfall.com/search?q=!odriclunarchmarshal)
- [x] Done -- [Ohabi Caleria](https://scryfall.com/search?q=!ohabicaleria)
- [x] Done -- [Oketra's Monument](https://scryfall.com/search?q=!oketrasmonument)
- [x] Done -- [Opulent Palace](https://scryfall.com/search?q=!opulentpalace)
- [x] Done -- [Orca, Siege Demon](https://scryfall.com/search?q=!orcasiegedemon)
- [x] Done -- [Orzhov Basilica](https://scryfall.com/search?q=!orzhovbasilica)
- [x] Done -- [Painful Truths](https://scryfall.com/search?q=!painfultruths)
- [x] Done -- [Path to Exile](https://scryfall.com/search?q=!pathtoexile)
- [x] Done -- [Path to the World Tree](https://scryfall.com/search?q=!pathtotheworldtree)
- [x] Done -- [Prairie Stream](https://scryfall.com/search?q=!prairiestream)
- [x] Done -- [Primeval Spawn](https://scryfall.com/search?q=!primevalspawn)
- [x] Done -- [Primevals' Glorious Rebirth](https://scryfall.com/search?q=!primevalsgloriousrebirth)
- [x] Done -- [Prophetic Prism](https://scryfall.com/search?q=!propheticprism)
- [x] Done -- [Radiant Flames](https://scryfall.com/search?q=!radiantflames)
- [x] Done -- [Rakdos Carnarium](https://scryfall.com/search?q=!rakdoscarnarium)
- [x] Done -- [Ramirez DePietro, Pillager](https://scryfall.com/search?q=!ramirezdepietropillager)
- [x] Done -- [Ramses, Assassin Lord](https://scryfall.com/search?q=!ramsesassassinlord)
- [x] Done -- [Rasputin, the Oneiromancer](https://scryfall.com/search?q=!rasputintheoneiromancer)
- [x] Done -- [Read the Bones](https://scryfall.com/search?q=!readthebones)
- [x] Done -- [Reliquary Tower](https://scryfall.com/search?q=!reliquarytower)
- [x] Done -- [Rienne, Angel of Rebirth](https://scryfall.com/search?q=!rienneangelofrebirth)
- [x] Done -- [Robaran Mercenaries](https://scryfall.com/search?q=!robaranmercenaries)
- [x] Done -- [Rocky Tar Pit](https://scryfall.com/search?q=!rockytarpit)
- [x] Done -- [Rohgahh, Kher Keep Overlord](https://scryfall.com/search?q=!rohgahhkherkeepoverlord)
- [x] Done -- [Rosnakht, Heir of Rohgahh](https://scryfall.com/search?q=!rosnakhtheirofrohgahh)
- [x] Done -- [Sandsteppe Citadel](https://scryfall.com/search?q=!sandsteppecitadel)
- [x] Done -- [Savage Lands](https://scryfall.com/search?q=!savagelands)
- [x] Done -- [Search for Tomorrow](https://scryfall.com/search?q=!searchfortomorrow)
- [x] Done -- [Seaside Citadel](https://scryfall.com/search?q=!seasidecitadel)
- [x] Done -- [Selvala, Explorer Returned](https://scryfall.com/search?q=!selvalaexplorerreturned)
- [x] Done -- [Shanid, Sleepers' Scourge](https://scryfall.com/search?q=!shanidsleepersscourge)
- [x] Done -- [Shivan Gorge](https://scryfall.com/search?q=!shivangorge)
- [x] Done -- [Shizo, Death's Storehouse](https://scryfall.com/search?q=!shizodeathsstorehouse)
- [x] Done -- [Sivitri, Dragon Master](https://scryfall.com/search?q=!sivitridragonmaster)
- [x] Done -- [Smoldering Marsh](https://scryfall.com/search?q=!smolderingmarsh)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Solemn Simulacrum](https://scryfall.com/search?q=!solemnsimulacrum)
- [x] Done -- [Stangg, Echo Warrior](https://scryfall.com/search?q=!stanggechowarrior)
- [x] Done -- [Sultai Charm](https://scryfall.com/search?q=!sultaicharm)
- [x] Done -- [Sunken Hollow](https://scryfall.com/search?q=!sunkenhollow)
- [x] Done -- [Surrak Dragonclaw](https://scryfall.com/search?q=!surrakdragonclaw)
- [x] Done -- [Sword of the Chosen](https://scryfall.com/search?q=!swordofthechosen)
- [x] Done -- [Sylvan Reclamation](https://scryfall.com/search?q=!sylvanreclamation)
- [x] Done -- [Tajic, Blade of the Legion](https://scryfall.com/search?q=!tajicbladeofthelegion)
- [x] Done -- [Temple of Malice](https://scryfall.com/search?q=!templeofmalice)
- [x] Done -- [Temple of Silence](https://scryfall.com/search?q=!templeofsilence)
- [x] Done -- [Temple of Triumph](https://scryfall.com/search?q=!templeoftriumph)
- [x] Done -- [Tenza, Godo's Maul](https://scryfall.com/search?q=!tenzagodosmaul)
- [x] Done -- [Terminate](https://scryfall.com/search?q=!terminate)
- [x] Done -- [Terramorphic Expanse](https://scryfall.com/search?q=!terramorphicexpanse)
- [x] Done -- [Teshar, Ancestor's Apostle](https://scryfall.com/search?q=!tesharancestorsapostle)
- [x] Done -- [Tetsuo, Imperial Champion](https://scryfall.com/search?q=!tetsuoimperialchampion)
- [x] Done -- [The Circle of Loyalty](https://scryfall.com/search?q=!thecircleofloyalty)
- [x] Done -- [The Ever-Changing 'Dane](https://scryfall.com/search?q=!theeverchangingdane)
- [x] Done -- [The Lady of Otaria](https://scryfall.com/search?q=!theladyofotaria)
- [x] Done -- [The Mana Rig](https://scryfall.com/search?q=!themanarig)
- [x] Done -- [The Peregrine Dynamo](https://scryfall.com/search?q=!theperegrinedynamo)
- [x] Done -- [The Reaver Cleaver](https://scryfall.com/search?q=!thereavercleaver)
- [x] Done -- [Thrill of Possibility](https://scryfall.com/search?q=!thrillofpossibility)
- [x] Done -- [Tiller Engine](https://scryfall.com/search?q=!tillerengine)
- [x] Done -- [Time Wipe](https://scryfall.com/search?q=!timewipe)
- [x] Done -- [Tobias, Doomed Conqueror](https://scryfall.com/search?q=!tobiasdoomedconqueror)
- [x] Done -- [Tor Wauki the Younger](https://scryfall.com/search?q=!torwaukitheyounger)
- [x] Done -- [Torsten, Founder of Benalia](https://scryfall.com/search?q=!torstenfounderofbenalia)
- [x] Done -- [Transguild Courier](https://scryfall.com/search?q=!transguildcourier)
- [x] Done -- [Traxos, Scourge of Kroog](https://scryfall.com/search?q=!traxosscourgeofkroog)
- [x] Done -- [Two-Headed Hellkite](https://scryfall.com/search?q=!twoheadedhellkite)
- [x] Done -- [Tyrite Sanctum](https://scryfall.com/search?q=!tyritesanctum)
- [x] Done -- [Unbreakable Formation](https://scryfall.com/search?q=!unbreakableformation)
- [x] Done -- [Unite the Coalition](https://scryfall.com/search?q=!unitethecoalition)
- [x] Done -- [Urza's Ruinous Blast](https://scryfall.com/search?q=!urzasruinousblast)
- [x] Done -- [Verrak, Warped Sengir](https://scryfall.com/search?q=!verrakwarpedsengir)
- [x] Done -- [Wear // Tear](https://scryfall.com/search?q=!weartear)
- [x] Done -- [Xira, the Golden Sting](https://scryfall.com/search?q=!xirathegoldensting)
- [x] Done -- [Xyris, the Writhing Storm](https://scryfall.com/search?q=!xyristhewrithingstorm)
- [x] Done -- [Zaxara, the Exemplary](https://scryfall.com/search?q=!zaxaratheexemplary)
- [x] Done -- [Zeriam, Golden Wind](https://scryfall.com/search?q=!zeriamgoldenwind)
- [x] Done -- [Zetalpa, Primal Dawn](https://scryfall.com/search?q=!zetalpaprimaldawn)
</details>

**Comment by theelk801** [comment]
Additional tasks:

none yet

**Comment by FreaIsDead** [comment]
Hello :) @theelk801  I would like to work on " Zeriam, Golden Wind "

**Comment by FreaIsDead** [comment]
@theelk801 working on "Shanid, Sleepers' Scourge" :)

**Comment by awjackson** [comment]
@theelk801 Working on General Marhault Elsdragon

**Comment by PurpleCrowbar** [comment]
Disclaimer to anyone planning on implementing [[Xira, the Golden Sting]], I have already made her insect token so I could add all of the token images in one push. The token is called [XiraBlackInsectToken](https://github.com/magefree/mage/blob/2b74c85e08cd1614320d3babe74153608cd92241/Mage/src/main/java/mage/game/permanent/token/XiraBlackInsectToken.java)

**Comment by theelk801** [comment]
That's a wrap, thanks to everyone who contributed!
