### ISSUE TITLE
GN3 - Game Night: Free-for-All Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#9434]
This checklist is here to help manage the implementation of Game Night: Free-for-All. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abrade](https://scryfall.com/search?q=!abrade)
- [x] Done -- [Ancestral Blade](https://scryfall.com/search?q=!ancestralblade)
- [x] Done -- [Ancient Hellkite](https://scryfall.com/search?q=!ancienthellkite)
- [x] Done -- [Angler Drake](https://scryfall.com/search?q=!anglerdrake)
- [x] Done -- [Angler Turtle](https://scryfall.com/search?q=!anglerturtle)
- [x] Done -- [Argentum Armor](https://scryfall.com/search?q=!argentumarmor)
- [x] Done -- [Banisher Priest](https://scryfall.com/search?q=!banisherpriest)
- [x] Done -- [Beast Whisperer](https://scryfall.com/search?q=!beastwhisperer)
- [x] Done -- [Blaze](https://scryfall.com/search?q=!blaze)
- [x] Done -- [Bloodsoaked Altar](https://scryfall.com/search?q=!bloodsoakedaltar)
- [x] Done -- [Bloodthirsty Blade](https://scryfall.com/search?q=!bloodthirstyblade)
- [x] Done -- [Brineborn Cutthroat](https://scryfall.com/search?q=!brineborncutthroat)
- [x] Done -- [Broken Wings](https://scryfall.com/search?q=!brokenwings)
- [x] Done -- [Bushmeat Poacher](https://scryfall.com/search?q=!bushmeatpoacher)
- [x] Done -- [Captain of the Watch](https://scryfall.com/search?q=!captainofthewatch)
- [x] Done -- [Colossus Hammer](https://scryfall.com/search?q=!colossushammer)
- [x] Done -- [Counterspell](https://scryfall.com/search?q=!counterspell)
- [x] Done -- [Crucible of Fire](https://scryfall.com/search?q=!crucibleoffire)
- [x] Done -- [Danitha Capashen, Paragon](https://scryfall.com/search?q=!danithacapashenparagon)
- [x] Done -- [Demon of Loathing](https://scryfall.com/search?q=!demonofloathing)
- [x] Done -- [Demonic Embrace](https://scryfall.com/search?q=!demonicembrace)
- [x] Done -- [Diluvian Primordial](https://scryfall.com/search?q=!diluvianprimordial)
- [x] Done -- [Doom Blade](https://scryfall.com/search?q=!doomblade)
- [x] Done -- [Doomed Dissenter](https://scryfall.com/search?q=!doomeddissenter)
- [x] Done -- [Dragon Egg](https://scryfall.com/search?q=!dragonegg)
- [x] Done -- [Dragon Hatchling](https://scryfall.com/search?q=!dragonhatchling)
- [x] Done -- [Dragon Mage](https://scryfall.com/search?q=!dragonmage)
- [x] Done -- [Dragon Tempest](https://scryfall.com/search?q=!dragontempest)
- [x] Done -- [Dragonspeaker Shaman](https://scryfall.com/search?q=!dragonspeakershaman)
- [x] Done -- [Drakuseth, Maw of Flames](https://scryfall.com/search?q=!drakusethmawofflames)
- [x] Done -- [Dusk Legion Zealot](https://scryfall.com/search?q=!dusklegionzealot)
- [x] Done -- [Dwynen's Elite](https://scryfall.com/search?q=!dwynenselite)
- [x] Done -- [Elven Ambush](https://scryfall.com/search?q=!elvenambush)
- [x] Done -- [Elvish Archdruid](https://scryfall.com/search?q=!elvisharchdruid)
- [x] Done -- [Elvish Rejuvenator](https://scryfall.com/search?q=!elvishrejuvenator)
- [x] Done -- [Elvish Skysweeper](https://scryfall.com/search?q=!elvishskysweeper)
- [x] Done -- [Elvish Visionary](https://scryfall.com/search?q=!elvishvisionary)
- [x] Done -- [End-Raze Forerunners](https://scryfall.com/search?q=!endrazeforerunners)
- [x] Done -- [Fact or Fiction](https://scryfall.com/search?q=!factorfiction)
- [x] Done -- [Flameblast Dragon](https://scryfall.com/search?q=!flameblastdragon)
- [x] Done -- [Flametongue Kavu](https://scryfall.com/search?q=!flametonguekavu)
- [x] Done -- [Fleshbag Marauder](https://scryfall.com/search?q=!fleshbagmarauder)
- [x] Done -- [Fog Bank](https://scryfall.com/search?q=!fogbank)
- [x] Done -- [Forbidding Spirit](https://scryfall.com/search?q=!forbiddingspirit)
- [x] Done -- [Furnace Whelp](https://scryfall.com/search?q=!furnacewhelp)
- [x] Done -- [Gavony Unhallowed](https://scryfall.com/search?q=!gavonyunhallowed)
- [x] Done -- [Gifted Aetherborn](https://scryfall.com/search?q=!giftedaetherborn)
- [x] Done -- [Goblin Motivator](https://scryfall.com/search?q=!goblinmotivator)
- [x] Done -- [Gravewaker](https://scryfall.com/search?q=!gravewaker)
- [x] Done -- [Greatsword](https://scryfall.com/search?q=!greatsword)
- [x] Done -- [Heavenly Blademaster](https://scryfall.com/search?q=!heavenlyblademaster)
- [x] Done -- [Howling Golem](https://scryfall.com/search?q=!howlinggolem)
- [x] Done -- [Illusory Ambusher](https://scryfall.com/search?q=!illusoryambusher)
- [x] Done -- [Imaryll, Elfhame Elite](https://scryfall.com/search?q=!imaryllelfhameelite)
- [x] Done -- [Immaculate Magistrate](https://scryfall.com/search?q=!immaculatemagistrate)
- [x] Done -- [Impulse](https://scryfall.com/search?q=!impulse)
- [x] Done -- [Invigorate](https://scryfall.com/search?q=!invigorate)
- [x] Done -- [Jeering Homunculus](https://scryfall.com/search?q=!jeeringhomunculus)
- [x] Done -- [Joraga Visionary](https://scryfall.com/search?q=!joragavisionary)
- [x] Done -- [Kargan Dragonrider](https://scryfall.com/search?q=!kargandragonrider)
- [x] Done -- [Kitesail Apprentice](https://scryfall.com/search?q=!kitesailapprentice)
- [x] Done -- [Knollspine Dragon](https://scryfall.com/search?q=!knollspinedragon)
- [x] Done -- [Kor Duelist](https://scryfall.com/search?q=!korduelist)
- [x] Done -- [Kor Outfitter](https://scryfall.com/search?q=!koroutfitter)
- [x] Done -- [Lightning Bolt](https://scryfall.com/search?q=!lightningbolt)
- [x] Done -- [Liliana's Mastery](https://scryfall.com/search?q=!lilianasmastery)
- [x] Done -- [Llanowar Elves](https://scryfall.com/search?q=!llanowarelves)
- [x] Done -- [Llanowar Tribe](https://scryfall.com/search?q=!llanowartribe)
- [x] Done -- [Lord of the Accursed](https://scryfall.com/search?q=!lordoftheaccursed)
- [x] Done -- [Maalfeld Twins](https://scryfall.com/search?q=!maalfeldtwins)
- [x] Done -- [Maeve, Insidious Singer](https://scryfall.com/search?q=!maeveinsidioussinger)
- [x] Done -- [Mana Geyser](https://scryfall.com/search?q=!manageyser)
- [x] Done -- [Moan of the Unhallowed](https://scryfall.com/search?q=!moanoftheunhallowed)
- [x] Done -- [Moonsilver Spear](https://scryfall.com/search?q=!moonsilverspear)
- [x] Done -- [Murmuring Mystic](https://scryfall.com/search?q=!murmuringmystic)
- [x] Done -- [Nogi, Draco-Zealot](https://scryfall.com/search?q=!nogidracozealot)
- [x] Done -- [Overrun](https://scryfall.com/search?q=!overrun)
- [x] Done -- [Path to Exile](https://scryfall.com/search?q=!pathtoexile)
- [x] Done -- [Pilgrim of the Ages](https://scryfall.com/search?q=!pilgrimoftheages)
- [x] Done -- [Plea for Power](https://scryfall.com/search?q=!pleaforpower)
- [x] Done -- [Precognitive Perception](https://scryfall.com/search?q=!precognitiveperception)
- [x] Done -- [Priest of the Blood Rite](https://scryfall.com/search?q=!priestofthebloodrite)
- [x] Done -- [Pull from Tomorrow](https://scryfall.com/search?q=!pullfromtomorrow)
- [x] Done -- [Rabid Bite](https://scryfall.com/search?q=!rabidbite)
- [x] Done -- [Ram Through](https://scryfall.com/search?q=!ramthrough)
- [x] Done -- [Rapacious Dragon](https://scryfall.com/search?q=!rapaciousdragon)
- [x] Done -- [Ravenous Chupacabra](https://scryfall.com/search?q=!ravenouschupacabra)
- [x] Done -- [Reassembling Skeleton](https://scryfall.com/search?q=!reassemblingskeleton)
- [x] Done -- [Regrowth](https://scryfall.com/search?q=!regrowth)
- [x] Done -- [Repulse](https://scryfall.com/search?q=!repulse)
- [x] Done -- [Ring of Thune](https://scryfall.com/search?q=!ringofthune)
- [x] Done -- [Run Away Together](https://scryfall.com/search?q=!runawaytogether)
- [x] Done -- [Sea Gate Oracle](https://scryfall.com/search?q=!seagateoracle)
- [x] Done -- [Seize the Spoils](https://scryfall.com/search?q=!seizethespoils)
- [x] Done -- [Serra Angel](https://scryfall.com/search?q=!serraangel)
- [x] Done -- [Shivan Dragon](https://scryfall.com/search?q=!shivandragon)
- [x] Done -- [Sign in Blood](https://scryfall.com/search?q=!signinblood)
- [x] Done -- [Split Decision](https://scryfall.com/search?q=!splitdecision)
- [x] Done -- [Strength of Arms](https://scryfall.com/search?q=!strengthofarms)
- [x] Done -- [Supernatural Stamina](https://scryfall.com/search?q=!supernaturalstamina)
- [x] Done -- [Supreme Will](https://scryfall.com/search?q=!supremewill)
- [x] Done -- [Sword of Vengeance](https://scryfall.com/search?q=!swordofvengeance)
- [x] Done -- [Swords to Plowshares](https://scryfall.com/search?q=!swordstoplowshares)
- [x] Done -- [Sylvan Messenger](https://scryfall.com/search?q=!sylvanmessenger)
- [x] Done -- [Talrand's Invocation](https://scryfall.com/search?q=!talrandsinvocation)
- [x] Done -- [Taunting Elf](https://scryfall.com/search?q=!tauntingelf)
- [x] Done -- [Thorn Lieutenant](https://scryfall.com/search?q=!thornlieutenant)
- [x] Done -- [Thornweald Archer](https://scryfall.com/search?q=!thornwealdarcher)
- [x] Done -- [Trusty Machete](https://scryfall.com/search?q=!trustymachete)
- [x] Done -- [Valorous Stance](https://scryfall.com/search?q=!valorousstance)
- [x] Done -- [Vilis, Broker of Blood](https://scryfall.com/search?q=!vilisbrokerofblood)
- [x] Done -- [Village Rites](https://scryfall.com/search?q=!villagerites)
- [x] Done -- [Vogar, Necropolis Tyrant](https://scryfall.com/search?q=!vogarnecropolistyrant)
- [x] Done -- [Vow of Duty](https://scryfall.com/search?q=!vowofduty)
- [x] Done -- [Vow of Flight](https://scryfall.com/search?q=!vowofflight)
- [x] Done -- [Vow of Lightning](https://scryfall.com/search?q=!vowoflightning)
- [x] Done -- [Vow of Torment](https://scryfall.com/search?q=!vowoftorment)
- [x] Done -- [Vow of Wildness](https://scryfall.com/search?q=!vowofwildness)
- [x] Done -- [Wirewood Pride](https://scryfall.com/search?q=!wirewoodpride)
- [x] Done -- [Zamriel, Seraph of Steel](https://scryfall.com/search?q=!zamrielseraphofsteel)
</details>
