### ISSUE TITLE
Refactor: Several refactors that should be done found during implementing cards

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9553]
Leftover TODOs from #9328:
- [ ] Several very similar `MoveCounterFromTargetToTargetEffect` should be refactored to a common class
- [ ] Change cards to make use of new `SpellCastControllerTriggeredAbility`'s `fromZone` (e.g. Kami of Celebration, Sunbird's Invocation)
- [ ] Make use of new non-token creature static filter
- [ ] Change Ob Nixilis, the Adversary to use standard Casualty ability rather than custom implementation
- [ ] Refactor `TargetOfOpponentsSpellOrAbilityTriggeredAbility ` and `BecomesTargetControlledPermanentTriggeredAbility` into a single class for "Whenever {a} becomes the target of a {b}" that takes filters for both {a} and {b}.
- [ ] ~~Refactor `MageObject.getColor(game)` so that it handles the intricacies of MDFC and split cards internally rather than needing to be wrapped externally.~~ Clean up and double check by https://github.com/magefree/mage/pull/9328#issuecomment-1255699247
- [ ] Refactor Replicate cost show  the final cost of the spell at once when paying. Currently the replicate cost is only shown _after_ the regular cost has been paid.

**Comment by jeffwadsworth** [comment]
[[Kami of Celebration]] [[Sunbird's Invocation]] [[Ob Nixilis, the Adversary]]
