### ISSUE TITLE
BRC - The Brothers' War Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#9602]
This checklist is here to help manage the implementation of The Brothers' War Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Abrade](https://scryfall.com/search?q=!abrade)
- [x] Done -- [Alela, Artful Provocateur](https://scryfall.com/search?q=!alelaartfulprovocateur)
- [x] Done -- [Ancient Den](https://scryfall.com/search?q=!ancientden)
- [x] Done -- [Angel of the Ruins](https://scryfall.com/search?q=!angeloftheruins)
- [x] Done -- [Arcane Sanctum](https://scryfall.com/search?q=!arcanesanctum)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Armix, Filigree Thrasher](https://scryfall.com/search?q=!armixfiligreethrasher)
- [x] Done -- [Ash Barrens](https://scryfall.com/search?q=!ashbarrens)
- [x] Done -- [Ashnod the Uncaring](https://scryfall.com/search?q=!ashnodtheuncaring)
- [x] Done -- [Audacious Reshapers](https://scryfall.com/search?q=!audaciousreshapers)
- [x] Done -- [Austere Command](https://scryfall.com/search?q=!austerecommand)
- [x] Done -- [Azorius Chancery](https://scryfall.com/search?q=!azoriuschancery)
- [x] Done -- [Azorius Signet](https://scryfall.com/search?q=!azoriussignet)
- [x] Done -- [Baleful Strix](https://scryfall.com/search?q=!balefulstrix)
- [x] Done -- [Bedevil](https://scryfall.com/search?q=!bedevil)
- [x] Done -- [Bident of Thassa](https://scryfall.com/search?q=!bidentofthassa)
- [x] Done -- [Blasphemous Act](https://scryfall.com/search?q=!blasphemousact)
- [x] Done -- [Blast-Furnace Hellkite](https://scryfall.com/search?q=!blastfurnacehellkite)
- [x] Done -- [Bojuka Bog](https://scryfall.com/search?q=!bojukabog)
- [x] Done -- [Bronze Guardian](https://scryfall.com/search?q=!bronzeguardian)
- [x] Done -- [Brudiclad, Telchor Engineer](https://scryfall.com/search?q=!brudicladtelchorengineer)
- [x] Done -- [Buried Ruin](https://scryfall.com/search?q=!buriedruin)
- [x] Done -- [Chaos Warp](https://scryfall.com/search?q=!chaoswarp)
- [x] Done -- [Chief of the Foundry](https://scryfall.com/search?q=!chiefofthefoundry)
- [x] Done -- [Chrome Courier](https://scryfall.com/search?q=!chromecourier)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=!commanderssphere)
- [x] Done -- [Cranial Plating](https://scryfall.com/search?q=!cranialplating)
- [x] Done -- [Crumbling Necropolis](https://scryfall.com/search?q=!crumblingnecropolis)
- [x] Done -- [Cursed Mirror](https://scryfall.com/search?q=!cursedmirror)
- [x] Done -- [Darksteel Citadel](https://scryfall.com/search?q=!darksteelcitadel)
- [x] Done -- [Darksteel Juggernaut](https://scryfall.com/search?q=!darksteeljuggernaut)
- [x] Done -- [Darkwater Catacombs](https://scryfall.com/search?q=!darkwatercatacombs)
- [x] Done -- [Despark](https://scryfall.com/search?q=!despark)
- [x] Done -- [Digsite Engineer](https://scryfall.com/search?q=!digsiteengineer)
- [x] Done -- [Dimir Aqueduct](https://scryfall.com/search?q=!dimiraqueduct)
- [x] Done -- [Dimir Signet](https://scryfall.com/search?q=!dimirsignet)
- [x] Done -- [Disciple of Caelus Nin](https://scryfall.com/search?q=!discipleofcaelusnin)
- [x] Done -- [Dreamstone Hedron](https://scryfall.com/search?q=!dreamstonehedron)
- [x] Done -- [Drossforge Bridge](https://scryfall.com/search?q=!drossforgebridge)
- [x] Done -- [Emry, Lurker of the Loch](https://scryfall.com/search?q=!emrylurkeroftheloch)
- [x] Done -- [Etched Champion](https://scryfall.com/search?q=!etchedchampion)
- [x] Done -- [Etherium Sculptor](https://scryfall.com/search?q=!etheriumsculptor)
- [x] Done -- [Ethersworn Adjudicator](https://scryfall.com/search?q=!etherswornadjudicator)
- [x] Done -- [Evolving Wilds](https://scryfall.com/search?q=!evolvingwilds)
- [x] Done -- [Executioner's Capsule](https://scryfall.com/search?q=!executionerscapsule)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Expressive Iteration](https://scryfall.com/search?q=!expressiveiteration)
- [x] Done -- [Fact or Fiction](https://scryfall.com/search?q=!factorfiction)
- [x] Done -- [Fain, the Broker](https://scryfall.com/search?q=!fainthebroker)
- [x] Done -- [Faithless Looting](https://scryfall.com/search?q=!faithlesslooting)
- [x] Done -- [Farid, Enterprising Salvager](https://scryfall.com/search?q=!faridenterprisingsalvager)
- [x] Done -- [Feed the Swarm](https://scryfall.com/search?q=!feedtheswarm)
- [x] Done -- [Fellwar Stone](https://scryfall.com/search?q=!fellwarstone)
- [x] Done -- [Filigree Attendant](https://scryfall.com/search?q=!filigreeattendant)
- [x] Done -- [Geth, Lord of the Vault](https://scryfall.com/search?q=!gethlordofthevault)
- [x] Done -- [Glint Raker](https://scryfall.com/search?q=!glintraker)
- [x] Done -- [Goldmire Bridge](https://scryfall.com/search?q=!goldmirebridge)
- [x] Done -- [Great Furnace](https://scryfall.com/search?q=!greatfurnace)
- [x] Done -- [Hedron Archive](https://scryfall.com/search?q=!hedronarchive)
- [x] Done -- [Hellkite Igniter](https://scryfall.com/search?q=!hellkiteigniter)
- [x] Done -- [Herald of Anguish](https://scryfall.com/search?q=!heraldofanguish)
- [x] Done -- [Hexavus](https://scryfall.com/search?q=!hexavus)
- [x] Done -- [Ichor Wellspring](https://scryfall.com/search?q=!ichorwellspring)
- [x] Done -- [Idol of Oblivion](https://scryfall.com/search?q=!idolofoblivion)
- [x] Done -- [Indomitable Archangel](https://scryfall.com/search?q=!indomitablearchangel)
- [x] Done -- [Izzet Boilerworks](https://scryfall.com/search?q=!izzetboilerworks)
- [x] Done -- [Jhoira, Weatherlight Captain](https://scryfall.com/search?q=!jhoiraweatherlightcaptain)
- [x] Done -- [Kayla's Music Box](https://scryfall.com/search?q=!kaylasmusicbox)
- [x] Done -- [Liquimetal Torque](https://scryfall.com/search?q=!liquimetaltorque)
- [x] Done -- [Lithoform Engine](https://scryfall.com/search?q=!lithoformengine)
- [x] Done -- [Losheel, Clockwork Scholar](https://scryfall.com/search?q=!losheelclockworkscholar)
- [x] Done -- [Machine God's Effigy](https://scryfall.com/search?q=!machinegodseffigy)
- [x] Done -- [March of Progress](https://scryfall.com/search?q=!marchofprogress)
- [x] Done -- [Marionette Master](https://scryfall.com/search?q=!marionettemaster)
- [x] Done -- [Master Transmuter](https://scryfall.com/search?q=!mastertransmuter)
- [x] Done -- [Master of Etherium](https://scryfall.com/search?q=!masterofetherium)
- [x] Done -- [Metalwork Colossus](https://scryfall.com/search?q=!metalworkcolossus)
- [x] Done -- [Mind Stone](https://scryfall.com/search?q=!mindstone)
- [x] Done -- [Mirrorworks](https://scryfall.com/search?q=!mirrorworks)
- [x] Done -- [Mishra, Eminent One](https://scryfall.com/search?q=!mishraeminentone)
- [x] Done -- [Mistvault Bridge](https://scryfall.com/search?q=!mistvaultbridge)
- [x] Done -- [Mnemonic Sphere](https://scryfall.com/search?q=!mnemonicsphere)
- [x] Done -- [Muzzio, Visionary Architect](https://scryfall.com/search?q=!muzziovisionaryarchitect)
- [x] Done -- [Mycosynth Wellspring](https://scryfall.com/search?q=!mycosynthwellspring)
- [x] Done -- [Myr Battlesphere](https://scryfall.com/search?q=!myrbattlesphere)
- [x] Done -- [Myriad Landscape](https://scryfall.com/search?q=!myriadlandscape)
- [x] Done -- [Nihil Spellbomb](https://scryfall.com/search?q=!nihilspellbomb)
- [x] Done -- [Noxious Gearhulk](https://scryfall.com/search?q=!noxiousgearhulk)
- [x] Done -- [Oblivion Stone](https://scryfall.com/search?q=!oblivionstone)
- [x] Done -- [One with the Machine](https://scryfall.com/search?q=!onewiththemachine)
- [x] Done -- [Oni-Cult Anvil](https://scryfall.com/search?q=!onicultanvil)
- [x] Done -- [Orzhov Basilica](https://scryfall.com/search?q=!orzhovbasilica)
- [x] Done -- [Orzhov Signet](https://scryfall.com/search?q=!orzhovsignet)
- [x] Done -- [Padeem, Consul of Innovation](https://scryfall.com/search?q=!padeemconsulofinnovation)
- [x] Done -- [Path of Ancestry](https://scryfall.com/search?q=!pathofancestry)
- [x] Done -- [Phyrexian Rebirth](https://scryfall.com/search?q=!phyrexianrebirth)
- [x] Done -- [Prairie Stream](https://scryfall.com/search?q=!prairiestream)
- [x] Done -- [Preordain](https://scryfall.com/search?q=!preordain)
- [x] Done -- [Prophetic Prism](https://scryfall.com/search?q=!propheticprism)
- [x] Done -- [Rakdos Carnarium](https://scryfall.com/search?q=!rakdoscarnarium)
- [x] Done -- [Rakdos Signet](https://scryfall.com/search?q=!rakdossignet)
- [x] Done -- [Razortide Bridge](https://scryfall.com/search?q=!razortidebridge)
- [x] Done -- [Relic of Progenitus](https://scryfall.com/search?q=!relicofprogenitus)
- [x] Done -- [Reliquary Tower](https://scryfall.com/search?q=!reliquarytower)
- [x] Done -- [River of Tears](https://scryfall.com/search?q=!riveroftears)
- [x] Done -- [Rootpath Purifier](https://scryfall.com/search?q=!rootpathpurifier)
- [x] Done -- [Sai, Master Thopterist](https://scryfall.com/search?q=!saimasterthopterist)
- [x] Done -- [Sanwell, Avenger Ace](https://scryfall.com/search?q=!sanwellavengerace)
- [x] Done -- [Sardian Avenger](https://scryfall.com/search?q=!sardianavenger)
- [x] Done -- [Scavenged Brawler](https://scryfall.com/search?q=!scavengedbrawler)
- [x] Done -- [Scholar of New Horizons](https://scryfall.com/search?q=!scholarofnewhorizons)
- [x] Done -- [Seat of the Synod](https://scryfall.com/search?q=!seatofthesynod)
- [x] Done -- [Servo Schematic](https://scryfall.com/search?q=!servoschematic)
- [x] Done -- [Shadowblood Ridge](https://scryfall.com/search?q=!shadowbloodridge)
- [x] Done -- [Sharding Sphinx](https://scryfall.com/search?q=!shardingsphinx)
- [x] Done -- [Sharuum the Hegemon](https://scryfall.com/search?q=!sharuumthehegemon)
- [x] Done -- [Shimmer Dragon](https://scryfall.com/search?q=!shimmerdragon)
- [x] Done -- [Silas Renn, Seeker Adept](https://scryfall.com/search?q=!silasrennseekeradept)
- [x] Done -- [Silverbluff Bridge](https://scryfall.com/search?q=!silverbluffbridge)
- [x] Done -- [Skullclamp](https://scryfall.com/search?q=!skullclamp)
- [x] Done -- [Skycloud Expanse](https://scryfall.com/search?q=!skycloudexpanse)
- [x] Done -- [Slobad, Goblin Tinkerer](https://scryfall.com/search?q=!slobadgoblintinkerer)
- [x] Done -- [Smelting Vat](https://scryfall.com/search?q=!smeltingvat)
- [x] Done -- [Smoldering Marsh](https://scryfall.com/search?q=!smolderingmarsh)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Solemn Simulacrum](https://scryfall.com/search?q=!solemnsimulacrum)
- [x] Done -- [Sphinx's Revelation](https://scryfall.com/search?q=!sphinxsrevelation)
- [x] Done -- [Spine of Ish Sah](https://scryfall.com/search?q=!spineofishsah)
- [x] Done -- [Spire of Industry](https://scryfall.com/search?q=!spireofindustry)
- [x] Done -- [Staff of Titania](https://scryfall.com/search?q=!staffoftitania)
- [x] Done -- [Steel Hellkite](https://scryfall.com/search?q=!steelhellkite)
- [x] Done -- [Steel Overseer](https://scryfall.com/search?q=!steeloverseer)
- [x] Done -- [Strionic Resonator](https://scryfall.com/search?q=!strionicresonator)
- [x] Done -- [Sunken Hollow](https://scryfall.com/search?q=!sunkenhollow)
- [x] Done -- [Swiftfoot Boots](https://scryfall.com/search?q=!swiftfootboots)
- [x] Done -- [Swords to Plowshares](https://scryfall.com/search?q=!swordstoplowshares)
- [x] Done -- [Tawnos, Solemn Survivor](https://scryfall.com/search?q=!tawnossolemnsurvivor)
- [x] Done -- [Tempered Steel](https://scryfall.com/search?q=!temperedsteel)
- [x] Done -- [Temple of Deceit](https://scryfall.com/search?q=!templeofdeceit)
- [x] Done -- [Temple of Enlightenment](https://scryfall.com/search?q=!templeofenlightenment)
- [x] Done -- [Temple of Epiphany](https://scryfall.com/search?q=!templeofepiphany)
- [x] Done -- [Temple of Malice](https://scryfall.com/search?q=!templeofmalice)
- [x] Done -- [Temple of Silence](https://scryfall.com/search?q=!templeofsilence)
- [x] Done -- [Terisiare's Devastation](https://scryfall.com/search?q=!terisiaresdevastation)
- [x] Done -- [Terramorphic Expanse](https://scryfall.com/search?q=!terramorphicexpanse)
- [x] Done -- [Teshar, Ancestor's Apostle](https://scryfall.com/search?q=!tesharancestorsapostle)
- [x] Done -- [The Archimandrite](https://scryfall.com/search?q=!thearchimandrite)
- [x] Done -- [The Brothers' War](https://scryfall.com/search?q=!thebrotherswar)
- [x] Done -- [Thirst for Knowledge](https://scryfall.com/search?q=!thirstforknowledge)
- [x] Done -- [Thopter Shop](https://scryfall.com/search?q=!thoptershop)
- [x] Done -- [Thopter Spy Network](https://scryfall.com/search?q=!thopterspynetwork)
- [x] Done -- [Thought Monitor](https://scryfall.com/search?q=!thoughtmonitor)
- [x] Done -- [Thought Vessel](https://scryfall.com/search?q=!thoughtvessel)
- [x] Done -- [Thoughtcast](https://scryfall.com/search?q=!thoughtcast)
- [x] Done -- [Thran Dynamo](https://scryfall.com/search?q=!thrandynamo)
- [x] Done -- [Titania, Nature's Force](https://scryfall.com/search?q=!titanianaturesforce)
- [x] Done -- [Trading Post](https://scryfall.com/search?q=!tradingpost)
- [x] Done -- [Traxos, Scourge of Kroog](https://scryfall.com/search?q=!traxosscourgeofkroog)
- [x] Done -- [Unbreakable Formation](https://scryfall.com/search?q=!unbreakableformation)
- [x] Done -- [Urza's Ruinous Blast](https://scryfall.com/search?q=!urzasruinousblast)
- [x] Done -- [Urza's Workshop](https://scryfall.com/search?q=!urzasworkshop)
- [x] Done -- [Urza, Chief Artificer](https://scryfall.com/search?q=!urzachiefartificer)
- [x] Done -- [Vault of Whispers](https://scryfall.com/search?q=!vaultofwhispers)
- [x] Done -- [Vedalken Humiliator](https://scryfall.com/search?q=!vedalkenhumiliator)
- [x] Done -- [Vindicate](https://scryfall.com/search?q=!vindicate)
- [x] Done -- [Wayfarer's Bauble](https://scryfall.com/search?q=!wayfarersbauble)
- [x] Done -- [Whirler Rogue](https://scryfall.com/search?q=!whirlerrogue)
- [x] Done -- [Wire Surgeons](https://scryfall.com/search?q=!wiresurgeons)
- [x] Done -- [Wondrous Crucible](https://scryfall.com/search?q=!wondrouscrucible)
- [x] Done -- [Workshop Elders](https://scryfall.com/search?q=!workshopelders)
- [x] Done -- [Wreck Hunter](https://scryfall.com/search?q=!wreckhunter)
</details>

**Comment by theelk801** [comment]
Additional tasks:

None yet

**Comment by xenohedron** [comment]
@theelk801 this set's finished now
