### ISSUE TITLE
BOT - Transformers Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#9605]
This checklist is here to help manage the implementation of Transformers. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

# Unimplemented Cards

- [ ] In progress -- [Flamewar, Brash Veteran](https://scryfall.com/search?q=!flamewarbrashveteran)
- [ ] In progress -- [Goldbug, Humanity's Ally](https://scryfall.com/search?q=!goldbughumanitysally)
- [ ] In progress -- [Optimus Prime, Hero](https://scryfall.com/search?q=!optimusprimehero)
- [ ] In progress -- [Slicer, Hired Muscle](https://scryfall.com/search?q=!slicerhiredmuscle)
- [ ] In progress -- [Soundwave, Sonic Spy](https://scryfall.com/search?q=!soundwavesonicspy)
- [ ] In progress -- [Starscream, Power Hungry](https://scryfall.com/search?q=!starscreampowerhungry)

[Scryfall gallery of everything currently unimplemented](https://scryfall.com/search?q=!"FlamewarBrashVeteran"or!"GoldbugHumanitysAlly"or!"OptimusPrimeHero"or!"SlicerHiredMuscle"or!"SoundwaveSonicSpy"or!"StarscreamPowerHungry"&unique=cards)
# Implemented Cards

**Comment by theelk801** [comment]
Additional Tasks:

- [ ] Implement More Than Meets The Eye mechanic
- [ ] Implemented Living Metal mechanic

**Comment by jbureau88** [comment]
I have been working on [Optimus Prime, Hero](https://scryfall.com/search?q=!optimusprimehero) but having some issues with the Optimus Prime, Autobot Leader effect on attack. 
Also noticed while testing that the More than meets the eye doesn't work properly when cast from commander zone but does work when cast from hand.

**Comment by Bakerbakura** [comment]
Hey there! I'm just wondering why some cards which have tickboxes marked are not in the Implemented section. In particular, I'm wondering about Slicer, Hired Muscle.

**Comment by Susucre** [comment]
> Hey there! I'm just wondering why some cards which have tickboxes marked are not in the Implemented section. In particular, I'm wondering about Slicer, Hired Muscle.

Those are either ready for next beta release, or are work in progress by someone (sometimes were work in progress that is now inactive and stalled). I think Slicer got merged a few days ago so will be there next release.

**Comment by mllagostera** [comment]
This cards are already on the release:
- [Slicer, Hired Muscle](https://scryfall.com/search?q=!slicerhiredmuscle)
- [Cyclonus, the Saboteur](https://scryfall.com/search?q=!cyclonusthesaboteur)
- [Megatron, Tyrant](https://scryfall.com/search?q=!megatrontyrant)
- [Optimus Prime, Hero](https://scryfall.com/search?q=!optimusprimehero)
- [Starscream, Power Hungry](https://scryfall.com/search?q=!starscreampowerhungry)

Can anyone set is as done?
