### ISSUE TITLE
ONE - Phyrexia: All Will Be One Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#9806]
This checklist is here to help manage the implementation of Phyrexia: All Will Be One. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Adaptive Sporesinger](https://scryfall.com/search?q=!adaptivesporesinger)
- [x] Done -- [Against All Odds](https://scryfall.com/search?q=!againstallodds)
- [x] Done -- [All Will Be One](https://scryfall.com/search?q=!allwillbeone)
- [x] Done -- [Ambulatory Edifice](https://scryfall.com/search?q=!ambulatoryedifice)
- [x] Done -- [Annex Sentry](https://scryfall.com/search?q=!annexsentry)
- [x] Done -- [Annihilating Glare](https://scryfall.com/search?q=!annihilatingglare)
- [x] Done -- [Anoint with Affliction](https://scryfall.com/search?q=!anointwithaffliction)
- [x] Done -- [Apostle of Invasion](https://scryfall.com/search?q=!apostleofinvasion)
- [x] Done -- [Archfiend of the Dross](https://scryfall.com/search?q=!archfiendofthedross)
- [x] Done -- [Argentum Masticore](https://scryfall.com/search?q=!argentummasticore)
- [x] Done -- [Armored Scrapgorger](https://scryfall.com/search?q=!armoredscrapgorger)
- [x] Done -- [Aspirant's Ascent](https://scryfall.com/search?q=!aspirantsascent)
- [x] Done -- [Atmosphere Surgeon](https://scryfall.com/search?q=!atmospheresurgeon)
- [x] Done -- [Atraxa's Skitterfang](https://scryfall.com/search?q=!atraxasskitterfang)
- [x] Done -- [Atraxa, Grand Unifier](https://scryfall.com/search?q=!atraxagrandunifier)
- [x] Done -- [Awaken the Sleeper](https://scryfall.com/search?q=!awakenthesleeper)
- [x] Done -- [Axiom Engraver](https://scryfall.com/search?q=!axiomengraver)
- [x] Done -- [Barbed Batterfist](https://scryfall.com/search?q=!barbedbatterfist)
- [x] Done -- [Basilica Shepherd](https://scryfall.com/search?q=!basilicashepherd)
- [x] Done -- [Basilica Skullbomb](https://scryfall.com/search?q=!basilicaskullbomb)
- [x] Done -- [Bilious Skulldweller](https://scryfall.com/search?q=!biliousskulldweller)
- [x] Done -- [Black Sun's Twilight](https://scryfall.com/search?q=!blacksunstwilight)
- [x] Done -- [Blackcleave Cliffs](https://scryfall.com/search?q=!blackcleavecliffs)
- [x] Done -- [Blade of Shared Souls](https://scryfall.com/search?q=!bladeofsharedsouls)
- [x] Done -- [Bladed Ambassador](https://scryfall.com/search?q=!bladedambassador)
- [x] Done -- [Bladegraft Aspirant](https://scryfall.com/search?q=!bladegraftaspirant)
- [x] Done -- [Bladehold War-Whip](https://scryfall.com/search?q=!bladeholdwarwhip)
- [x] Done -- [Blazing Crescendo](https://scryfall.com/search?q=!blazingcrescendo)
- [x] Done -- [Blightbelly Rat](https://scryfall.com/search?q=!blightbellyrat)
- [x] Done -- [Bloated Contaminator](https://scryfall.com/search?q=!bloatedcontaminator)
- [x] Done -- [Blue Sun's Twilight](https://scryfall.com/search?q=!bluesunstwilight)
- [x] Done -- [Bonepicker Skirge](https://scryfall.com/search?q=!bonepickerskirge)
- [x] Done -- [Branchblight Stalker](https://scryfall.com/search?q=!branchblightstalker)
- [x] Done -- [Bring the Ending](https://scryfall.com/search?q=!bringtheending)
- [x] Done -- [Cacophony Scamp](https://scryfall.com/search?q=!cacophonyscamp)
- [x] Done -- [Cankerbloom](https://scryfall.com/search?q=!cankerbloom)
- [x] Done -- [Capricious Hellraiser](https://scryfall.com/search?q=!capricioushellraiser)
- [x] Done -- [Carnivorous Canopy](https://scryfall.com/search?q=!carnivorouscanopy)
- [x] Done -- [Cephalopod Sentry](https://scryfall.com/search?q=!cephalopodsentry)
- [x] Done -- [Charforger](https://scryfall.com/search?q=!charforger)
- [x] Done -- [Charge of the Mites](https://scryfall.com/search?q=!chargeofthemites)
- [x] Done -- [Chimney Rabble](https://scryfall.com/search?q=!chimneyrabble)
- [x] Done -- [Chittering Skitterling](https://scryfall.com/search?q=!chitteringskitterling)
- [x] Done -- [Chrome Prowler](https://scryfall.com/search?q=!chromeprowler)
- [x] Done -- [Churning Reservoir](https://scryfall.com/search?q=!churningreservoir)
- [x] Done -- [Cinderslash Ravager](https://scryfall.com/search?q=!cinderslashravager)
- [x] Done -- [Compleat Devotion](https://scryfall.com/search?q=!compleatdevotion)
- [x] Done -- [Conduit of Worlds](https://scryfall.com/search?q=!conduitofworlds)
- [x] Done -- [Contagious Vorrac](https://scryfall.com/search?q=!contagiousvorrac)
- [x] Done -- [Copper Longlegs](https://scryfall.com/search?q=!copperlonglegs)
- [x] Done -- [Copperline Gorge](https://scryfall.com/search?q=!copperlinegorge)
- [x] Done -- [Crawling Chorus](https://scryfall.com/search?q=!crawlingchorus)
- [x] Done -- [Cruel Grimnarch](https://scryfall.com/search?q=!cruelgrimnarch)
- [x] Done -- [Cutthroat Centurion](https://scryfall.com/search?q=!cutthroatcenturion)
- [x] Done -- [Darkslick Shores](https://scryfall.com/search?q=!darkslickshores)
- [x] Done -- [Distorted Curiosity](https://scryfall.com/search?q=!distortedcuriosity)
- [x] Done -- [Dragonwing Glider](https://scryfall.com/search?q=!dragonwingglider)
- [x] Done -- [Drivnod, Carnage Dominus](https://scryfall.com/search?q=!drivnodcarnagedominus)
- [x] Done -- [Dross Skullbomb](https://scryfall.com/search?q=!drossskullbomb)
- [x] Done -- [Drown in Ichor](https://scryfall.com/search?q=!drowninichor)
- [x] Done -- [Duelist of Deep Faith](https://scryfall.com/search?q=!duelistofdeepfaith)
- [x] Done -- [Dune Mover](https://scryfall.com/search?q=!dunemover)
- [x] Done -- [Duress](https://scryfall.com/search?q=!duress)
- [x] Done -- [Elesh Norn, Mother of Machines](https://scryfall.com/search?q=!eleshnornmotherofmachines)
- [x] Done -- [Encroaching Mycosynth](https://scryfall.com/search?q=!encroachingmycosynth)
- [x] Done -- [Escaped Experiment](https://scryfall.com/search?q=!escapedexperiment)
- [x] Done -- [Evolved Spinoderm](https://scryfall.com/search?q=!evolvedspinoderm)
- [x] Done -- [Evolving Adaptive](https://scryfall.com/search?q=!evolvingadaptive)
- [x] Done -- [Expand the Sphere](https://scryfall.com/search?q=!expandthesphere)
- [x] Done -- [Experimental Augury](https://scryfall.com/search?q=!experimentalaugury)
- [x] Done -- [Exuberant Fuseling](https://scryfall.com/search?q=!exuberantfuseling)
- [x] Done -- [Eye of Malcator](https://scryfall.com/search?q=!eyeofmalcator)
- [x] Done -- [Ezuri, Stalker of Spheres](https://scryfall.com/search?q=!ezuristalkerofspheres)
- [x] Done -- [Feed the Infection](https://scryfall.com/search?q=!feedtheinfection)
- [x] Done -- [Flensing Raptor](https://scryfall.com/search?q=!flensingraptor)
- [x] Done -- [Fleshless Gladiator](https://scryfall.com/search?q=!fleshlessgladiator)
- [x] Done -- [Font of Progress](https://scryfall.com/search?q=!fontofprogress)
- [x] Done -- [Forgehammer Centurion](https://scryfall.com/search?q=!forgehammercenturion)
- [x] Done -- [Free from Flesh](https://scryfall.com/search?q=!freefromflesh)
- [x] Done -- [Furnace Punisher](https://scryfall.com/search?q=!furnacepunisher)
- [x] Done -- [Furnace Skullbomb](https://scryfall.com/search?q=!furnaceskullbomb)
- [x] Done -- [Furnace Strider](https://scryfall.com/search?q=!furnacestrider)
- [x] Done -- [Geth, Thane of Contracts](https://scryfall.com/search?q=!geththaneofcontracts)
- [x] Done -- [Gitaxian Anatomist](https://scryfall.com/search?q=!gitaxiananatomist)
- [x] Done -- [Gitaxian Raptor](https://scryfall.com/search?q=!gitaxianraptor)
- [x] Done -- [Gleeful Demolition](https://scryfall.com/search?q=!gleefuldemolition)
- [x] Done -- [Glissa Sunslayer](https://scryfall.com/search?q=!glissasunslayer)
- [x] Done -- [Glistener Seer](https://scryfall.com/search?q=!glistenerseer)
- [x] Done -- [Goldwarden's Helm](https://scryfall.com/search?q=!goldwardenshelm)
- [x] Done -- [Goliath Hatchery](https://scryfall.com/search?q=!goliathhatchery)
- [x] Done -- [Graaz, Unstoppable Juggernaut](https://scryfall.com/search?q=!graazunstoppablejuggernaut)
- [x] Done -- [Green Sun's Twilight](https://scryfall.com/search?q=!greensunstwilight)
- [x] Done -- [Gulping Scraptrap](https://scryfall.com/search?q=!gulpingscraptrap)
- [x] Done -- [Hazardous Blast](https://scryfall.com/search?q=!hazardousblast)
- [x] Done -- [Hexgold Halberd](https://scryfall.com/search?q=!hexgoldhalberd)
- [x] Done -- [Hexgold Hoverwings](https://scryfall.com/search?q=!hexgoldhoverwings)
- [x] Done -- [Hexgold Slash](https://scryfall.com/search?q=!hexgoldslash)
- [x] Done -- [Ichor Synthesizer](https://scryfall.com/search?q=!ichorsynthesizer)
- [x] Done -- [Ichormoon Gauntlet](https://scryfall.com/search?q=!ichormoongauntlet)
- [x] Done -- [Ichorplate Golem](https://scryfall.com/search?q=!ichorplategolem)
- [x] Done -- [Ichorspit Basilisk](https://scryfall.com/search?q=!ichorspitbasilisk)
- [x] Done -- [Incisor Glider](https://scryfall.com/search?q=!incisorglider)
- [x] Done -- [Incubation Sac](https://scryfall.com/search?q=!incubationsac)
- [x] Done -- [Indoctrination Attendant](https://scryfall.com/search?q=!indoctrinationattendant)
- [x] Done -- [Infectious Bite](https://scryfall.com/search?q=!infectiousbite)
- [x] Done -- [Infectious Inquiry](https://scryfall.com/search?q=!infectiousinquiry)
- [x] Done -- [Infested Fleshcutter](https://scryfall.com/search?q=!infestedfleshcutter)
- [x] Done -- [Jace, the Perfected Mind](https://scryfall.com/search?q=!jacetheperfectedmind)
- [x] Done -- [Jawbone Duelist](https://scryfall.com/search?q=!jawboneduelist)
- [x] Done -- [Jor Kadeen, First Goldwarden](https://scryfall.com/search?q=!jorkadeenfirstgoldwarden)
- [x] Done -- [Kaito, Dancing Shadow](https://scryfall.com/search?q=!kaitodancingshadow)
- [x] Done -- [Karumonix, the Rat King](https://scryfall.com/search?q=!karumonixtheratking)
- [x] Done -- [Kaya, Intangible Slayer](https://scryfall.com/search?q=!kayaintangibleslayer)
- [x] Done -- [Kemba, Kha Enduring](https://scryfall.com/search?q=!kembakhaenduring)
- [x] Done -- [Kethek, Crucible Goliath](https://scryfall.com/search?q=!kethekcruciblegoliath)
- [x] Done -- [Kinzu of the Bleak Coven](https://scryfall.com/search?q=!kinzuofthebleakcoven)
- [x] Done -- [Koth, Fire of Resistance](https://scryfall.com/search?q=!kothfireofresistance)
- [x] Done -- [Kuldotha Cackler](https://scryfall.com/search?q=!kuldothacackler)
- [x] Done -- [Lattice-Blade Mantis](https://scryfall.com/search?q=!latticeblademantis)
- [x] Done -- [Leonin Lightbringer](https://scryfall.com/search?q=!leoninlightbringer)
- [x] Done -- [Lukka, Bound to Ruin](https://scryfall.com/search?q=!lukkaboundtoruin)
- [x] Done -- [Magmatic Sprinter](https://scryfall.com/search?q=!magmaticsprinter)
- [x] Done -- [Malcator's Watcher](https://scryfall.com/search?q=!malcatorswatcher)
- [x] Done -- [Malcator, Purity Overseer](https://scryfall.com/search?q=!malcatorpurityoverseer)
- [x] Done -- [Mandible Justiciar](https://scryfall.com/search?q=!mandiblejusticiar)
- [x] Done -- [Maze Skullbomb](https://scryfall.com/search?q=!mazeskullbomb)
- [x] Done -- [Maze's Mantle](https://scryfall.com/search?q=!mazesmantle)
- [x] Done -- [Meldweb Curator](https://scryfall.com/search?q=!meldwebcurator)
- [x] Done -- [Meldweb Strider](https://scryfall.com/search?q=!meldwebstrider)
- [x] Done -- [Melira, the Living Cure](https://scryfall.com/search?q=!melirathelivingcure)
- [x] Done -- [Mercurial Spelldancer](https://scryfall.com/search?q=!mercurialspelldancer)
- [x] Done -- [Mesmerizing Dose](https://scryfall.com/search?q=!mesmerizingdose)
- [x] Done -- [Migloz, Maze Crusher](https://scryfall.com/search?q=!miglozmazecrusher)
- [x] Done -- [Mindsplice Apparatus](https://scryfall.com/search?q=!mindspliceapparatus)
- [x] Done -- [Minor Misstep](https://scryfall.com/search?q=!minormisstep)
- [x] Done -- [Mirran Bardiche](https://scryfall.com/search?q=!mirranbardiche)
- [x] Done -- [Mirran Safehouse](https://scryfall.com/search?q=!mirransafehouse)
- [x] Done -- [Mirrex](https://scryfall.com/search?q=!mirrex)
- [x] Done -- [Mite Overseer](https://scryfall.com/search?q=!miteoverseer)
- [x] Done -- [Molten Rebuke](https://scryfall.com/search?q=!moltenrebuke)
- [x] Done -- [Mondrak, Glory Dominus](https://scryfall.com/search?q=!mondrakglorydominus)
- [x] Done -- [Monument to Perfection](https://scryfall.com/search?q=!monumenttoperfection)
- [x] Done -- [Myr Convert](https://scryfall.com/search?q=!myrconvert)
- [x] Done -- [Myr Custodian](https://scryfall.com/search?q=!myrcustodian)
- [x] Done -- [Myr Kinsmith](https://scryfall.com/search?q=!myrkinsmith)
- [x] Done -- [Nahiri's Sacrifice](https://scryfall.com/search?q=!nahirissacrifice)
- [x] Done -- [Nahiri, the Unforgiving](https://scryfall.com/search?q=!nahiritheunforgiving)
- [x] Done -- [Necrogen Communion](https://scryfall.com/search?q=!necrogencommunion)
- [x] Done -- [Necrogen Rotpriest](https://scryfall.com/search?q=!necrogenrotpriest)
- [x] Done -- [Necrosquito](https://scryfall.com/search?q=!necrosquito)
- [x] Done -- [Nimraiser Paladin](https://scryfall.com/search?q=!nimraiserpaladin)
- [x] Done -- [Nissa, Ascended Animist](https://scryfall.com/search?q=!nissaascendedanimist)
- [x] Done -- [Norn's Wellspring](https://scryfall.com/search?q=!nornswellspring)
- [x] Done -- [Noxious Assault](https://scryfall.com/search?q=!noxiousassault)
- [x] Done -- [Offer Immortality](https://scryfall.com/search?q=!offerimmortality)
- [x] Done -- [Oil-Gorger Troll](https://scryfall.com/search?q=!oilgorgertroll)
- [x] Done -- [Orthodoxy Enforcer](https://scryfall.com/search?q=!orthodoxyenforcer)
- [x] Done -- [Ossification](https://scryfall.com/search?q=!ossification)
- [x] Done -- [Ovika, Enigma Goliath](https://scryfall.com/search?q=!ovikaenigmagoliath)
- [x] Done -- [Oxidda Finisher](https://scryfall.com/search?q=!oxiddafinisher)
- [x] Done -- [Paladin of Predation](https://scryfall.com/search?q=!paladinofpredation)
- [x] Done -- [Pestilent Syphoner](https://scryfall.com/search?q=!pestilentsyphoner)
- [x] Done -- [Phyrexian Arena](https://scryfall.com/search?q=!phyrexianarena)
- [x] Done -- [Phyrexian Atlas](https://scryfall.com/search?q=!phyrexianatlas)
- [x] Done -- [Phyrexian Obliterator](https://scryfall.com/search?q=!phyrexianobliterator)
- [x] Done -- [Phyrexian Vindicator](https://scryfall.com/search?q=!phyrexianvindicator)
- [x] Done -- [Plague Nurse](https://scryfall.com/search?q=!plaguenurse)
- [x] Done -- [Planar Disruption](https://scryfall.com/search?q=!planardisruption)
- [x] Done -- [Plated Onslaught](https://scryfall.com/search?q=!platedonslaught)
- [x] Done -- [Porcelain Zealot](https://scryfall.com/search?q=!porcelainzealot)
- [x] Done -- [Predation Steward](https://scryfall.com/search?q=!predationsteward)
- [x] Done -- [Prologue to Phyresis](https://scryfall.com/search?q=!prologuetophyresis)
- [x] Done -- [Prophetic Prism](https://scryfall.com/search?q=!propheticprism)
- [x] Done -- [Prosthetic Injector](https://scryfall.com/search?q=!prostheticinjector)
- [x] Done -- [Quicksilver Fisher](https://scryfall.com/search?q=!quicksilverfisher)
- [x] Done -- [Ravenous Necrotitan](https://scryfall.com/search?q=!ravenousnecrotitan)
- [x] Done -- [Razorverge Thicket](https://scryfall.com/search?q=!razorvergethicket)
- [x] Done -- [Rebel Salvo](https://scryfall.com/search?q=!rebelsalvo)
- [x] Done -- [Red Sun's Twilight](https://scryfall.com/search?q=!redsunstwilight)
- [x] Done -- [Reject Imperfection](https://scryfall.com/search?q=!rejectimperfection)
- [x] Done -- [Resistance Reunited](https://scryfall.com/search?q=!resistancereunited)
- [x] Done -- [Resistance Skywarden](https://scryfall.com/search?q=!resistanceskywarden)
- [x] Done -- [Rhuk, Hexgold Nabber](https://scryfall.com/search?q=!rhukhexgoldnabber)
- [x] Done -- [Ria Ivor, Bane of Bladehold](https://scryfall.com/search?q=!riaivorbaneofbladehold)
- [x] Done -- [Ribskiff](https://scryfall.com/search?q=!ribskiff)
- [x] Done -- [Rustvine Cultivator](https://scryfall.com/search?q=!rustvinecultivator)
- [x] Done -- [Ruthless Predation](https://scryfall.com/search?q=!ruthlesspredation)
- [x] Done -- [Sawblade Scamp](https://scryfall.com/search?q=!sawbladescamp)
- [x] Done -- [Scheming Aspirant](https://scryfall.com/search?q=!schemingaspirant)
- [x] Done -- [Seachrome Coast](https://scryfall.com/search?q=!seachromecoast)
- [x] Done -- [Serum Snare](https://scryfall.com/search?q=!serumsnare)
- [x] Done -- [Serum Sovereign](https://scryfall.com/search?q=!serumsovereign)
- [x] Done -- [Serum-Core Chimera](https://scryfall.com/search?q=!serumcorechimera)
- [x] Done -- [Sheoldred's Edict](https://scryfall.com/search?q=!sheoldredsedict)
- [x] Done -- [Sheoldred's Headcleaver](https://scryfall.com/search?q=!sheoldredsheadcleaver)
- [x] Done -- [Shrapnel Slinger](https://scryfall.com/search?q=!shrapnelslinger)
- [x] Done -- [Sinew Dancer](https://scryfall.com/search?q=!sinewdancer)
- [x] Done -- [Skrelv's Hive](https://scryfall.com/search?q=!skrelvshive)
- [x] Done -- [Skrelv, Defector Mite](https://scryfall.com/search?q=!skrelvdefectormite)
- [x] Done -- [Skyscythe Engulfer](https://scryfall.com/search?q=!skyscytheengulfer)
- [x] Done -- [Slaughter Singer](https://scryfall.com/search?q=!slaughtersinger)
- [x] Done -- [Slobad, Iron Goblin](https://scryfall.com/search?q=!slobadirongoblin)
- [x] Done -- [Solphim, Mayhem Dominus](https://scryfall.com/search?q=!solphimmayhemdominus)
- [x] Done -- [Soulless Jailer](https://scryfall.com/search?q=!soullessjailer)
- [x] Done -- [Staff of Compleation](https://scryfall.com/search?q=!staffofcompleation)
- [x] Done -- [Stinging Hivemaster](https://scryfall.com/search?q=!stinginghivemaster)
- [x] Done -- [Surgical Skullbomb](https://scryfall.com/search?q=!surgicalskullbomb)
- [x] Done -- [Swooping Lookout](https://scryfall.com/search?q=!swoopinglookout)
- [x] Done -- [Sword of Forge and Frontier](https://scryfall.com/search?q=!swordofforgeandfrontier)
- [x] Done -- [Sylvok Battle-Chair](https://scryfall.com/search?q=!sylvokbattlechair)
- [x] Done -- [Tablet of Compleation](https://scryfall.com/search?q=!tabletofcompleation)
- [x] Done -- [Tainted Observer](https://scryfall.com/search?q=!taintedobserver)
- [x] Done -- [Tamiyo's Immobilizer](https://scryfall.com/search?q=!tamiyosimmobilizer)
- [x] Done -- [Tamiyo's Logbook](https://scryfall.com/search?q=!tamiyoslogbook)
- [x] Done -- [Tekuthal, Inquiry Dominus](https://scryfall.com/search?q=!tekuthalinquirydominus)
- [x] Done -- [Terramorphic Expanse](https://scryfall.com/search?q=!terramorphicexpanse)
- [x] Done -- [Testament Bearer](https://scryfall.com/search?q=!testamentbearer)
- [x] Done -- [The Autonomous Furnace](https://scryfall.com/search?q=!theautonomousfurnace)
- [x] Done -- [The Dross Pits](https://scryfall.com/search?q=!thedrosspits)
- [x] Done -- [The Eternal Wanderer](https://scryfall.com/search?q=!theeternalwanderer)
- [x] Done -- [The Fair Basilica](https://scryfall.com/search?q=!thefairbasilica)
- [x] Done -- [The Filigree Sylex](https://scryfall.com/search?q=!thefiligreesylex)
- [x] Done -- [The Hunter Maze](https://scryfall.com/search?q=!thehuntermaze)
- [x] Done -- [The Monumental Facade](https://scryfall.com/search?q=!themonumentalfacade)
- [x] Done -- [The Mycosynth Gardens](https://scryfall.com/search?q=!themycosynthgardens)
- [x] Done -- [The Seedcore](https://scryfall.com/search?q=!theseedcore)
- [x] Done -- [The Surgical Bay](https://scryfall.com/search?q=!thesurgicalbay)
- [x] Done -- [Thirsting Roots](https://scryfall.com/search?q=!thirstingroots)
- [x] Done -- [Thrill of Possibility](https://scryfall.com/search?q=!thrillofpossibility)
- [x] Done -- [Thrummingbird](https://scryfall.com/search?q=!thrummingbird)
- [x] Done -- [Thrun, Breaker of Silence](https://scryfall.com/search?q=!thrunbreakerofsilence)
- [x] Done -- [Titanic Growth](https://scryfall.com/search?q=!titanicgrowth)
- [x] Done -- [Transplant Theorist](https://scryfall.com/search?q=!transplanttheorist)
- [x] Done -- [Trawler Drake](https://scryfall.com/search?q=!trawlerdrake)
- [x] Done -- [Tyrranax Atrocity](https://scryfall.com/search?q=!tyrranaxatrocity)
- [x] Done -- [Tyrranax Rex](https://scryfall.com/search?q=!tyrranaxrex)
- [x] Done -- [Tyvar's Stand](https://scryfall.com/search?q=!tyvarsstand)
- [x] Done -- [Tyvar, Jubilant Brawler](https://scryfall.com/search?q=!tyvarjubilantbrawler)
- [x] Done -- [Unctus's Retrofitter](https://scryfall.com/search?q=!unctussretrofitter)
- [x] Done -- [Unctus, Grand Metatect](https://scryfall.com/search?q=!unctusgrandmetatect)
- [x] Done -- [Unnatural Restoration](https://scryfall.com/search?q=!unnaturalrestoration)
- [x] Done -- [Urabrask's Anointer](https://scryfall.com/search?q=!urabrasksanointer)
- [x] Done -- [Urabrask's Forge](https://scryfall.com/search?q=!urabrasksforge)
- [x] Done -- [Vanish into Eternity](https://scryfall.com/search?q=!vanishintoeternity)
- [x] Done -- [Vat Emergence](https://scryfall.com/search?q=!vatemergence)
- [x] Done -- [Vat of Rebirth](https://scryfall.com/search?q=!vatofrebirth)
- [x] Done -- [Veil of Assimilation](https://scryfall.com/search?q=!veilofassimilation)
- [x] Done -- [Venerated Rotpriest](https://scryfall.com/search?q=!veneratedrotpriest)
- [x] Done -- [Venomous Brutalizer](https://scryfall.com/search?q=!venomousbrutalizer)
- [x] Done -- [Venser, Corpse Puppet](https://scryfall.com/search?q=!vensercorpsepuppet)
- [x] Done -- [Vindictive Flamestoker](https://scryfall.com/search?q=!vindictiveflamestoker)
- [x] Done -- [Viral Spawning](https://scryfall.com/search?q=!viralspawning)
- [x] Done -- [Vivisection Evangelist](https://scryfall.com/search?q=!vivisectionevangelist)
- [x] Done -- [Vivisurgeon's Insight](https://scryfall.com/search?q=!vivisurgeonsinsight)
- [x] Done -- [Voidwing Hybrid](https://scryfall.com/search?q=!voidwinghybrid)
- [x] Done -- [Volt Charge](https://scryfall.com/search?q=!voltcharge)
- [x] Done -- [Vraan, Executioner Thane](https://scryfall.com/search?q=!vraanexecutionerthane)
- [x] Done -- [Vraska's Fall](https://scryfall.com/search?q=!vraskasfall)
- [x] Done -- [Vraska, Betrayal's Sting](https://scryfall.com/search?q=!vraskabetrayalssting)
- [x] Done -- [Vulshok Splitter](https://scryfall.com/search?q=!vulshoksplitter)
- [x] Done -- [Watchful Blisterzoa](https://scryfall.com/search?q=!watchfulblisterzoa)
- [x] Done -- [Whisper of the Dross](https://scryfall.com/search?q=!whisperofthedross)
- [x] Done -- [White Sun's Twilight](https://scryfall.com/search?q=!whitesunstwilight)
- [x] Done -- [Zealot's Conviction](https://scryfall.com/search?q=!zealotsconviction)
- [x] Done -- [Zenith Chronicler](https://scryfall.com/search?q=!zenithchronicler)
- [x] Done -- [Zopandrel, Hunger Dominus](https://scryfall.com/search?q=!zopandrelhungerdominus)
</details>

**Comment by theelk801** [comment]
Additional Tasks:
None yet

**Comment by AhmadYProjects** [comment]
Messed around a little bit and i have thrunn 99% done i think

**Comment by Grath** [comment]
I did the other three Dominus, but I have no idea where to even start on doubling Proliferate for Tekuthal.

**Comment by AhmadYProjects** [comment]
> 

for Tekuthal, how about a TriggeredAbility looking for the GameEvent.EventType.PROLIFERATED that would cause another proliferate to go on the stack?

**Comment by theelk801** [comment]
you have to do a replacement effect, take a look at how effects like scry are implemented

**Comment by AhmadYProjects** [comment]
> you have to do a replacement effect, take a look at how effects like scry are implemented

that was the other idea i was thinking but im still doing research through the codebase

**Comment by Grath** [comment]
> you have to do a replacement effect, take a look at how effects like scry are implemented

Yea, scry has an event with an amount that I could just modify (for Kenessos, the only replacement effect that increases your Scry amounts) - as far as I could see, there isn't a clear way to add an additional Proliferate without digging deep into the bowels of how XMage works.

**Comment by theelk801** [comment]
you can just wrap the proliferate code in a for loop and have the replacement effect change the amount of loops

**Comment by Merlingilb** [comment]
I did implement [Atmosphere Surgeon](https://scryfall.com/search?q=!atmospheresurgeon)
See #9985

**Comment by Merlingilb** [comment]
I did implement [Charforger](https://scryfall.com/search?q=!charforger)
See #9986

**Comment by Merlingilb** [comment]
I did implement [Compleat Devotion](https://scryfall.com/search?q=!compleatdevotion)
See #9987

**Comment by Merlingilb** [comment]
I did implement [Evolving Adaptive](https://scryfall.com/search?q=!evolvingadaptive)
See #9990

**Comment by Merlingilb** [comment]
I did implement [Expand the Sphere](https://scryfall.com/search?q=!expandthesphere)
See #9991

**Comment by Merlingilb** [comment]
I did implement [Exuberant Fuseling](https://scryfall.com/search?q=!exuberantfuseling)
See #9992

**Comment by Grath** [comment]
You don't have to actually say that in this thread each time. The point of this thread is to avoid people simultaneously working on the same card at once, which hasn't been happening lately.

**Comment by Mervius** [comment]
I know this says Churning Reservoir is Implemented, but I don't actually see it in the deckbuilder or card viewer.

**Comment by xenohedron** [comment]
Part of implementing a new set is preparing booster generation for limited. I think these tracking threads are likely the best place for the following tasks:

- [ ] Enable booster generation (once all but a few cards are implemented)
- [ ] Implement collation (once all cards are implemented and <https://www.lethe.xyz/mtg/collation/> has information)
