### ISSUE TITLE
ONC - Phyrexia: All Will Be One Commander Set Card Implementation Tracking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#9889]
This checklist is here to help manage the implementation of Phyrexia: All Will Be One Commander. If a card is marked as being in progress then someone is working on it.

If you're new to implementing cards then you likely don't have permission to check things off. This is totally fine! We still appreciate your contributions so just leave a comment to let us know that you're working on it.

Don't worry about moving things from in progress to completed either, there's a script that handles that, and don't worry about fixing text issues as those are usually handled when the set is done.

[All Sets](https://github.com/magefree/mage/wiki/Set-implementation-list)

All cards are implemented

# Implemented Cards
<details><summary>Click to expand</summary>

- [x] Done -- [Adriana, Captain of the Guard](https://scryfall.com/search?q=!adrianacaptainoftheguard)
- [x] Done -- [Arcane Signet](https://scryfall.com/search?q=!arcanesignet)
- [x] Done -- [Assemble the Legion](https://scryfall.com/search?q=!assemblethelegion)
- [x] Done -- [Battle Screech](https://scryfall.com/search?q=!battlescreech)
- [x] Done -- [Beast Within](https://scryfall.com/search?q=!beastwithin)
- [x] Done -- [Blight Mamba](https://scryfall.com/search?q=!blightmamba)
- [x] Done -- [Bojuka Bog](https://scryfall.com/search?q=!bojukabog)
- [x] Done -- [Boros Charm](https://scryfall.com/search?q=!boroscharm)
- [x] Done -- [Boros Garrison](https://scryfall.com/search?q=!borosgarrison)
- [x] Done -- [Boros Signet](https://scryfall.com/search?q=!borossignet)
- [x] Done -- [Buried Ruin](https://scryfall.com/search?q=!buriedruin)
- [x] Done -- [Call the Coppercoats](https://scryfall.com/search?q=!callthecoppercoats)
- [x] Done -- [Canopy Vista](https://scryfall.com/search?q=!canopyvista)
- [x] Done -- [Caress of Phyrexia](https://scryfall.com/search?q=!caressofphyrexia)
- [x] Done -- [Carrion Call](https://scryfall.com/search?q=!carrioncall)
- [x] Done -- [Castle Ardenvale](https://scryfall.com/search?q=!castleardenvale)
- [x] Done -- [Castle Embereth](https://scryfall.com/search?q=!castleembereth)
- [x] Done -- [Chain Reaction](https://scryfall.com/search?q=!chainreaction)
- [x] Done -- [Chiss-Goria, Forge Tyrant](https://scryfall.com/search?q=!chissgoriaforgetyrant)
- [x] Done -- [Chromatic Lantern](https://scryfall.com/search?q=!chromaticlantern)
- [x] Done -- [Clever Concealment](https://scryfall.com/search?q=!cleverconcealment)
- [x] Done -- [Collective Effort](https://scryfall.com/search?q=!collectiveeffort)
- [x] Done -- [Command Tower](https://scryfall.com/search?q=!commandtower)
- [x] Done -- [Commander's Sphere](https://scryfall.com/search?q=!commanderssphere)
- [x] Done -- [Contagion Clasp](https://scryfall.com/search?q=!contagionclasp)
- [x] Done -- [Contaminant Grafter](https://scryfall.com/search?q=!contaminantgrafter)
- [x] Done -- [Court of Grace](https://scryfall.com/search?q=!courtofgrace)
- [x] Done -- [Culling Ritual](https://scryfall.com/search?q=!cullingritual)
- [x] Done -- [Cultivate](https://scryfall.com/search?q=!cultivate)
- [x] Done -- [Cut a Deal](https://scryfall.com/search?q=!cutadeal)
- [x] Done -- [Dragonmaster Outcast](https://scryfall.com/search?q=!dragonmasteroutcast)
- [x] Done -- [Elspeth Tirel](https://scryfall.com/search?q=!elspethtirel)
- [x] Done -- [Emeria Angel](https://scryfall.com/search?q=!emeriaangel)
- [x] Done -- [Evolution Sage](https://scryfall.com/search?q=!evolutionsage)
- [x] Done -- [Exotic Orchard](https://scryfall.com/search?q=!exoticorchard)
- [x] Done -- [Felidar Retreat](https://scryfall.com/search?q=!felidarretreat)
- [x] Done -- [Fellwar Stone](https://scryfall.com/search?q=!fellwarstone)
- [x] Done -- [Finale of Glory](https://scryfall.com/search?q=!finaleofglory)
- [x] Done -- [Flawless Maneuver](https://scryfall.com/search?q=!flawlessmaneuver)
- [x] Done -- [Forgotten Cave](https://scryfall.com/search?q=!forgottencave)
- [x] Done -- [Fortified Village](https://scryfall.com/search?q=!fortifiedvillage)
- [x] Done -- [Fumigate](https://scryfall.com/search?q=!fumigate)
- [x] Done -- [Furycalm Snarl](https://scryfall.com/search?q=!furycalmsnarl)
- [x] Done -- [Generous Gift](https://scryfall.com/search?q=!generousgift)
- [x] Done -- [Geth's Summons](https://scryfall.com/search?q=!gethssummons)
- [x] Done -- [Ghostly Prison](https://scryfall.com/search?q=!ghostlyprison)
- [x] Done -- [Glimmer Lens](https://scryfall.com/search?q=!glimmerlens)
- [x] Done -- [Glissa's Retriever](https://scryfall.com/search?q=!glissasretriever)
- [x] Done -- [Glistening Sphere](https://scryfall.com/search?q=!glisteningsphere)
- [x] Done -- [Goldnight Commander](https://scryfall.com/search?q=!goldnightcommander)
- [x] Done -- [Goldwardens' Gambit](https://scryfall.com/search?q=!goldwardensgambit)
- [x] Done -- [Golgari Signet](https://scryfall.com/search?q=!golgarisignet)
- [x] Done -- [Grafted Exoskeleton](https://scryfall.com/search?q=!graftedexoskeleton)
- [x] Done -- [Grateful Apparition](https://scryfall.com/search?q=!gratefulapparition)
- [x] Done -- [Harmonious Archon](https://scryfall.com/search?q=!harmoniousarchon)
- [x] Done -- [Hate Mirage](https://scryfall.com/search?q=!hatemirage)
- [x] Done -- [Heroic Reinforcements](https://scryfall.com/search?q=!heroicreinforcements)
- [x] Done -- [Hexplate Wallbreaker](https://scryfall.com/search?q=!hexplatewallbreaker)
- [x] Done -- [Hordeling Outburst](https://scryfall.com/search?q=!hordelingoutburst)
- [x] Done -- [Hour of Reckoning](https://scryfall.com/search?q=!hourofreckoning)
- [x] Done -- [Ichor Rats](https://scryfall.com/search?q=!ichorrats)
- [x] Done -- [Ichorclaw Myr](https://scryfall.com/search?q=!ichorclawmyr)
- [x] Done -- [Idol of Oblivion](https://scryfall.com/search?q=!idolofoblivion)
- [x] Done -- [Increasing Devotion](https://scryfall.com/search?q=!increasingdevotion)
- [x] Done -- [Intangible Virtue](https://scryfall.com/search?q=!intangiblevirtue)
- [x] Done -- [Ixhel, Scion of Atraxa](https://scryfall.com/search?q=!ixhelscionofatraxa)
- [x] Done -- [Jor Kadeen, the Prevailer](https://scryfall.com/search?q=!jorkadeentheprevailer)
- [x] Done -- [Karn's Bastion](https://scryfall.com/search?q=!karnsbastion)
- [x] Done -- [Kemba's Banner](https://scryfall.com/search?q=!kembasbanner)
- [x] Done -- [Kher Keep](https://scryfall.com/search?q=!kherkeep)
- [x] Done -- [Krosan Verge](https://scryfall.com/search?q=!krosanverge)
- [x] Done -- [Legion Warboss](https://scryfall.com/search?q=!legionwarboss)
- [x] Done -- [Loxodon Warhammer](https://scryfall.com/search?q=!loxodonwarhammer)
- [x] Done -- [Loyal Apprentice](https://scryfall.com/search?q=!loyalapprentice)
- [x] Done -- [Lux Artillery](https://scryfall.com/search?q=!luxartillery)
- [x] Done -- [Mace of the Valiant](https://scryfall.com/search?q=!maceofthevaliant)
- [x] Done -- [Martial Coup](https://scryfall.com/search?q=!martialcoup)
- [x] Done -- [Mask of Memory](https://scryfall.com/search?q=!maskofmemory)
- [x] Done -- [Maul of the Skyclaves](https://scryfall.com/search?q=!mauloftheskyclaves)
- [x] Done -- [Mentor of the Meek](https://scryfall.com/search?q=!mentorofthemeek)
- [x] Done -- [Merciless Eviction](https://scryfall.com/search?q=!mercilesseviction)
- [x] Done -- [Midnight Haunting](https://scryfall.com/search?q=!midnighthaunting)
- [x] Done -- [Mind Stone](https://scryfall.com/search?q=!mindstone)
- [x] Done -- [Mirage Mockery](https://scryfall.com/search?q=!miragemockery)
- [x] Done -- [Moldervine Reclamation](https://scryfall.com/search?q=!moldervinereclamation)
- [x] Done -- [Monumental Corruption](https://scryfall.com/search?q=!monumentalcorruption)
- [x] Done -- [Mortify](https://scryfall.com/search?q=!mortify)
- [x] Done -- [Mycosynth Fiend](https://scryfall.com/search?q=!mycosynthfiend)
- [x] Done -- [Myr Battlesphere](https://scryfall.com/search?q=!myrbattlesphere)
- [x] Done -- [Myriad Landscape](https://scryfall.com/search?q=!myriadlandscape)
- [x] Done -- [Necroblossom Snarl](https://scryfall.com/search?q=!necroblossomsnarl)
- [x] Done -- [Neyali, Suns' Vanguard](https://scryfall.com/search?q=!neyalisunsvanguard)
- [x] Done -- [Night's Whisper](https://scryfall.com/search?q=!nightswhisper)
- [x] Done -- [Norn's Annex](https://scryfall.com/search?q=!nornsannex)
- [x] Done -- [Norn's Choirmaster](https://scryfall.com/search?q=!nornschoirmaster)
- [x] Done -- [Norn's Decree](https://scryfall.com/search?q=!nornsdecree)
- [x] Done -- [Noxious Revival](https://scryfall.com/search?q=!noxiousrevival)
- [x] Done -- [Otharri, Suns' Glory](https://scryfall.com/search?q=!otharrisunsglory)
- [x] Done -- [Painful Truths](https://scryfall.com/search?q=!painfultruths)
- [x] Done -- [Path of Ancestry](https://scryfall.com/search?q=!pathofancestry)
- [x] Done -- [Path to Exile](https://scryfall.com/search?q=!pathtoexile)
- [x] Done -- [Phantom General](https://scryfall.com/search?q=!phantomgeneral)
- [x] Done -- [Phyresis Outbreak](https://scryfall.com/search?q=!phyresisoutbreak)
- [x] Done -- [Phyrexian Rebirth](https://scryfall.com/search?q=!phyrexianrebirth)
- [x] Done -- [Phyrexian Swarmlord](https://scryfall.com/search?q=!phyrexianswarmlord)
- [x] Done -- [Plague Myr](https://scryfall.com/search?q=!plaguemyr)
- [x] Done -- [Plague Stinger](https://scryfall.com/search?q=!plaguestinger)
- [x] Done -- [Prava of the Steel Legion](https://scryfall.com/search?q=!pravaofthesteellegion)
- [x] Done -- [Putrefy](https://scryfall.com/search?q=!putrefy)
- [x] Done -- [Rip Apart](https://scryfall.com/search?q=!ripapart)
- [x] Done -- [Roar of Resistance](https://scryfall.com/search?q=!roarofresistance)
- [x] Done -- [Sandsteppe Citadel](https://scryfall.com/search?q=!sandsteppecitadel)
- [x] Done -- [Scavenging Ooze](https://scryfall.com/search?q=!scavengingooze)
- [x] Done -- [Secluded Steppe](https://scryfall.com/search?q=!secludedsteppe)
- [x] Done -- [Shineshadow Snarl](https://scryfall.com/search?q=!shineshadowsnarl)
- [x] Done -- [Siege-Gang Commander](https://scryfall.com/search?q=!siegegangcommander)
- [x] Done -- [Silverwing Squadron](https://scryfall.com/search?q=!silverwingsquadron)
- [x] Done -- [Skyhunter Strike Force](https://scryfall.com/search?q=!skyhunterstrikeforce)
- [x] Done -- [Slayers' Stronghold](https://scryfall.com/search?q=!slayersstronghold)
- [x] Done -- [Sol Ring](https://scryfall.com/search?q=!solring)
- [x] Done -- [Solemn Simulacrum](https://scryfall.com/search?q=!solemnsimulacrum)
- [x] Done -- [Soul-Guide Lantern](https://scryfall.com/search?q=!soulguidelantern)
- [x] Done -- [Staff of the Storyteller](https://scryfall.com/search?q=!staffofthestoryteller)
- [x] Done -- [Sungrass Prairie](https://scryfall.com/search?q=!sungrassprairie)
- [x] Done -- [Swords to Plowshares](https://scryfall.com/search?q=!swordstoplowshares)
- [x] Done -- [Synthesis Pod](https://scryfall.com/search?q=!synthesispod)
- [x] Done -- [Tainted Field](https://scryfall.com/search?q=!taintedfield)
- [x] Done -- [Tainted Wood](https://scryfall.com/search?q=!taintedwood)
- [x] Done -- [Talisman of Conviction](https://scryfall.com/search?q=!talismanofconviction)
- [x] Done -- [Tangleweave Armor](https://scryfall.com/search?q=!tangleweavearmor)
- [x] Done -- [Temple of Malady](https://scryfall.com/search?q=!templeofmalady)
- [x] Done -- [Temple of Plenty](https://scryfall.com/search?q=!templeofplenty)
- [x] Done -- [Temple of Silence](https://scryfall.com/search?q=!templeofsilence)
- [x] Done -- [Temple of Triumph](https://scryfall.com/search?q=!templeoftriumph)
- [x] Done -- [Temple of the False God](https://scryfall.com/search?q=!templeofthefalsegod)
- [x] Done -- [Trailblazer's Boots](https://scryfall.com/search?q=!trailblazersboots)
- [x] Done -- [Urtet, Remnant of Memnarch](https://scryfall.com/search?q=!urtetremnantofmemnarch)
- [x] Done -- [Viridian Corrupter](https://scryfall.com/search?q=!viridiancorrupter)
- [x] Done -- [Vishgraz, the Doomhive](https://scryfall.com/search?q=!vishgrazthedoomhive)
- [x] Done -- [Vulshok Factory](https://scryfall.com/search?q=!vulshokfactory)
- [x] Done -- [White Sun's Zenith](https://scryfall.com/search?q=!whitesunszenith)
- [x] Done -- [Windborn Muse](https://scryfall.com/search?q=!windbornmuse)
- [x] Done -- [Windbrisk Heights](https://scryfall.com/search?q=!windbriskheights)
- [x] Done -- [Wurmquake](https://scryfall.com/search?q=!wurmquake)
</details>

**Comment by theelk801** [comment]
Additional tasks:
none yet

**Comment by alexander-novo** [comment]
I'll work on Norn's Decree

**Comment by Chewbaklava** [comment]
I see Staff of the Storyteller is implemented but isn't yet live. How would I help speed up that process?

**Comment by Grath** [comment]
The only thing you could do is build your own server/client from a more recent commit, distribute the relevant client files to everyone you'd like to play with, and host your own server.

**Comment by xenohedron** [comment]
@theelk801 all cards implemented here

**Comment by theelk801** [comment]
that's a wrap, thanks to everyone who helped
